---- SRC LAYER ----
WITH
SRC_H              as ( SELECT BKCC, CONTROLLING_AREA_BK, CONTROLLING_AREA_HK, REC_SRC FROM {{ ref('hub_controlling_area') }} as SRC  ),
SRC_SAT_WINN       as ( SELECT CONTROLLING_AREA_HK , MANDT , KOKRS , GLREQUEST , BEZEI , WAERS , KTOPL , LMONA , KOKFI , LOGSYSTEM , ALEMT , MD_LOGSYSTEM , KHINR , KOMP1 , KOMP0 , KOMP2 , ERKRS , DPRCT , PHINR , PCLDG , PCBEL , XWBUK , BPHINR , XBPALE , KSTAR_FIN , KSTAR_FID , PCACUR , PCACURTP , PCATRCUR , CTYP , RCLAC , BLART , FIKRS , RCL_PRIMAC , PCA_ALEMT , PCA_VALU , CVPROF , CVACT , VNAME , PCA_ACC_DIFF , TP_VALOHB , DEFPRCTR , AUTH_USE_NO_STD , AUTH_USE_ADD1 , AUTH_USE_ADD2 , AUTH_KE_NO_STD , AUTH_KE_USE_ADD1 , AUTH_KE_USE_ADD2 , GLDELFLAG , GLCHANGETIME , GLSOURCESYSTEM , PSA_RECORD_SOURCE , PSA_DELETE_IND , LOAD_DTS FROM {{ ref('sat_controlling_area__winn_sap') }} as SRC 
                        QUALIFY 1= ROW_NUMBER() OVER(PARTITION BY CONTROLLING_AREA_HK ORDER BY LOAD_DTS DESC) )

/*
SRC_H              as ( SELECT * FROM RAW_VAULT.HUB_CONTROLLING_AREA_HEADER )
SRC_SAT_WINN       as ( SELECT * FROM RAW_VAULT.SAT_CONTROLLING_AREA_HEADER_WINN_SAP )
SRC_COEP       as ( SELECT * FROM RAW_VAULT.SAT_CONTROLLING_LEDGER_ENTRY_WINN_SAP )
*/
---- LOGIC LAYER ----

, LOGIC_H as (
    SELECT
        'PIT_CONTROLLING_AREA'                                       as                                        PIT_REC_SRC
      , CURRENT_DATE                                                 as                                       SNAPSHOTDATE
      , CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP )                  as                                       PIT_LOAD_DTS
      , CONTROLLING_AREA_HK
      , CONTROLLING_AREA_BK
      , BKCC
      , REC_SRC
    FROM SRC_H
)
, LOGIC_SAT_WINN as (
     SELECT
        CONTROLLING_AREA_HK   as SAT_WINN_CONTROLLING_AREA_HK
       , BEZEI                as NAME_OF_THE_CONTROLLING_AREA
       , WAERS                as CURRENCY_KEY
       , KTOPL                as CHART_OF_ACCOUNTS
       , LMONA                as FISCAL_YEAR_VARIANT
       , KOKFI                as ALLOCATION_INDICATOR
       , LOGSYSTEM            as LOGICAL_SYSTEM
       , ALEMT                as COST_CENTER_DISTRIBUTION_METHOD_USING_ALE
       , MD_LOGSYSTEM         as LOGICAL_SYSTEM_FOR_MASTER_DATA_MAINTENANCE
       , KHINR                as STANDARD_HIERARCHY_FOR_COST_CENTERS
       , KOMP1                as INDICATOR_REVENUE_MUST_BE_CONVERTED
       , KOMP0                as PRODUCTIVE_INDICATOR_FOR_CONTROLLING_AREA
       , KOMP2                as INDICATOR_RESERVE_NOT_USED_AT_PRESENT
       , ERKRS                as OPERATING_CONCERN
       , DPRCT                as DUMMY_PROFIT_CENTER
       , PHINR                as PROFIT_CENTER_AREA
       , PCLDG                as PROFIT_CENTER_LEDGER
       , PCBEL                as ELIMINATION_OF_INTERNAL_BUS_VOLUME_FOR_PROFIT_CENTER_ACCTG
       , XWBUK                as INDICATOR_DIFFERENT_COMPANY_CODE_CURRENCY_IS_ALLOWED
       , BPHINR               as STANDARD_HIERARCHY_AREA
       , XBPALE               as INDICATOR_ALE_FOR_ACTIVE_BUSINESS_PROCESS_PROCESS_COSTS
       , KSTAR_FIN            as COST_ELEMENT_FOR_VENDOR_DOWNPAYMENTS_WO_PURCHASE_ORD_REF
       , KSTAR_FID            as REVENUE_TYPE_FOR_DEBITOR_DOWNPAYMENTS_WITHOUT_SALES_ORD_REF
       , PCACUR               as LOCAL_CURRENCY_FOR_PROFIT_CENTER_ACCOUNTING
       , PCACURTP             as CURRENCY_TYPE_OF_THE_PROFIT_CENTER_REPORT_CURRENC      
       , PCATRCUR             as STORE_TRANSACTION_CURRENCY_IN_EC_PCA
       , CTYP                 as CURRENCY_TYPE_FOR_CONTROLLING_AREA
       , RCLAC                as RECONCILIATION_LEDGER_ACTIVE
       , BLART                as DOCUMENT_TYPE_FOR_RECONCIL_POSTINGS_FROM_RECONCIL_LEDGER
       , PCA_VALU             as VALUATION_VIEW      
       , TP_VALOHB            as VALUATION_VIEW_FOR_CALCULATION_BASE
       , PSA_DELETE_IND      
    FROM SRC_SAT_WINN
)
  ---- RENAME LAYER ----

, RENAME_H as (
    SELECT
        PIT_REC_SRC
      , SNAPSHOTDATE
      , PIT_LOAD_DTS
      , CONTROLLING_AREA_HK
      , CONTROLLING_AREA_BK
      , BKCC
      , REC_SRC
    FROM LOGIC_H
)

, RENAME_SAT_WINN as (
    SELECT
        SAT_WINN_CONTROLLING_AREA_HK
      , NAME_OF_THE_CONTROLLING_AREA
      , CURRENCY_KEY
      , CHART_OF_ACCOUNTS
      , FISCAL_YEAR_VARIANT
      , ALLOCATION_INDICATOR
      , LOGICAL_SYSTEM
      , COST_CENTER_DISTRIBUTION_METHOD_USING_ALE
      , LOGICAL_SYSTEM_FOR_MASTER_DATA_MAINTENANCE
      , STANDARD_HIERARCHY_FOR_COST_CENTERS
      , INDICATOR_REVENUE_MUST_BE_CONVERTED
      , PRODUCTIVE_INDICATOR_FOR_CONTROLLING_AREA
      , INDICATOR_RESERVE_NOT_USED_AT_PRESENT
      , OPERATING_CONCERN
      , DUMMY_PROFIT_CENTER
      , PROFIT_CENTER_AREA
      , PROFIT_CENTER_LEDGER
      , ELIMINATION_OF_INTERNAL_BUS_VOLUME_FOR_PROFIT_CENTER_ACCTG
      , INDICATOR_DIFFERENT_COMPANY_CODE_CURRENCY_IS_ALLOWED
      , STANDARD_HIERARCHY_AREA
      , INDICATOR_ALE_FOR_ACTIVE_BUSINESS_PROCESS_PROCESS_COSTS
      , COST_ELEMENT_FOR_VENDOR_DOWNPAYMENTS_WO_PURCHASE_ORD_REF
      , REVENUE_TYPE_FOR_DEBITOR_DOWNPAYMENTS_WITHOUT_SALES_ORD_REF
      , LOCAL_CURRENCY_FOR_PROFIT_CENTER_ACCOUNTING
      , CURRENCY_TYPE_OF_THE_PROFIT_CENTER_REPORT_CURRENC
      , STORE_TRANSACTION_CURRENCY_IN_EC_PCA
      , CURRENCY_TYPE_FOR_CONTROLLING_AREA
      , RECONCILIATION_LEDGER_ACTIVE
      , DOCUMENT_TYPE_FOR_RECONCIL_POSTINGS_FROM_RECONCIL_LEDGER
      , VALUATION_VIEW
      , VALUATION_VIEW_FOR_CALCULATION_BASE
      , PSA_DELETE_IND
    FROM LOGIC_SAT_WINN
)

---- FILTER LAYER ----

, FILTER_H as (
    SELECT *
    FROM RENAME_H
    WHERE REC_SRC <> 'USAZET.SNOWFLAKE.FBIN.DERIVED'   /* This filter is to exclude the ghost records */
)

, FILTER_SAT_WINN as (
    SELECT *
    FROM RENAME_SAT_WINN
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM FILTER_H
    LEFT JOIN FILTER_SAT_WINN
        ON FILTER_H.CONTROLLING_AREA_HK  = FILTER_SAT_WINN.SAT_WINN_CONTROLLING_AREA_HK 

)

---- FINAL LAYER ----
SELECT
          PIT_REC_SRC
        , SNAPSHOTDATE
        , PIT_LOAD_DTS
        , CONTROLLING_AREA_HK
        , NAME_OF_THE_CONTROLLING_AREA
        , CURRENCY_KEY
        , CHART_OF_ACCOUNTS
        , FISCAL_YEAR_VARIANT
        , ALLOCATION_INDICATOR
        , LOGICAL_SYSTEM
        , COST_CENTER_DISTRIBUTION_METHOD_USING_ALE
        , LOGICAL_SYSTEM_FOR_MASTER_DATA_MAINTENANCE
        , STANDARD_HIERARCHY_FOR_COST_CENTERS
        , INDICATOR_REVENUE_MUST_BE_CONVERTED
        , PRODUCTIVE_INDICATOR_FOR_CONTROLLING_AREA
        , INDICATOR_RESERVE_NOT_USED_AT_PRESENT
        , OPERATING_CONCERN
        , DUMMY_PROFIT_CENTER
        , PROFIT_CENTER_AREA
        , PROFIT_CENTER_LEDGER
        , ELIMINATION_OF_INTERNAL_BUS_VOLUME_FOR_PROFIT_CENTER_ACCTG
        , INDICATOR_DIFFERENT_COMPANY_CODE_CURRENCY_IS_ALLOWED
        , STANDARD_HIERARCHY_AREA
        , INDICATOR_ALE_FOR_ACTIVE_BUSINESS_PROCESS_PROCESS_COSTS
        , COST_ELEMENT_FOR_VENDOR_DOWNPAYMENTS_WO_PURCHASE_ORD_REF
        , REVENUE_TYPE_FOR_DEBITOR_DOWNPAYMENTS_WITHOUT_SALES_ORD_REF
        , LOCAL_CURRENCY_FOR_PROFIT_CENTER_ACCOUNTING
        , CURRENCY_TYPE_OF_THE_PROFIT_CENTER_REPORT_CURRENC
        , STORE_TRANSACTION_CURRENCY_IN_EC_PCA
        , CURRENCY_TYPE_FOR_CONTROLLING_AREA
        , RECONCILIATION_LEDGER_ACTIVE
        , DOCUMENT_TYPE_FOR_RECONCIL_POSTINGS_FROM_RECONCIL_LEDGER
        , VALUATION_VIEW
        , VALUATION_VIEW_FOR_CALCULATION_BASE
        , BKCC
        , REC_SRC
        , CASE BKCC WHEN 'Hiding_Tiger' THEN PSA_DELETE_IND
          END as IS_DELETED
FROM JOIN_RESULT
QUALIFY 1 = ROW_NUMBER() OVER(PARTITION BY CONTROLLING_AREA_HK ORDER BY PIT_LOAD_DTS DESC)
