---- SRC LAYER ----
WITH
SRC_s              as ( SELECT * FROM {{ ref('v_psa_stg_demand_planning_history__winn_sap') }} as SRC 
                        {% if is_incremental() %}
                        WHERE SRC.LOAD_DTS > (SELECT DATEADD('HOUR', '-1', MAX(LOAD_DTS)) FROM {{this}}){% endif %} )

/*
SRC_s              as ( SELECT * FROM STAGING.v_psa_stg_demand_planning_history__winn_sap )
*/
---- LOGIC LAYER ----

, LOGIC_s as (
    SELECT
        REQUID
      , CALMONTH
      , CALQUARTER
      , CALWEEK
      , FISCPER
      , FISCVARNT
      , FISCYEAR
      , CALYEAR
      , SALES_UNIT
      , UNIT
      , BASE_UOM
      , DATE0
      , DISTR_CHAN
      , DIVISION
      , MATERIAL
      , PLANT
      , SALESORG
      , BIC_ZZAPOACCT
      , BIC_ZZAPOGRP
      , APO_PLVERS
      , BIC_ZZPLANPER
      , BIC_ZFQUARTER
      , BIC_ZFYEAR
      , BIC_ZMONTH
      , BIC_ZQUARTER
      , MAT_PLANT
      , BIC_ZACCTMATL
      , BIC_ZZMATENTR
      , CURRENCY
      , GLREQUEST
      , GLSOURCESYSTEM
      , ORDER_QTY
      , BIC_Z9ADFCST
      , BIC_ZCANNIBAL
      , BIC_ZCORRHIST
      , BIC_ZCUSTFORE
      , BIC_ZFCSTERR
      , BIC_ZFINLFCST
      , BIC_ZLYSALES1
      , BIC_ZLYSALES2
      , BIC_ZMANUCORR
      , BIC_ZMAPE
      , BIC_ZMKTCORR
      , BIC_ZPRODLIFE
      , BIC_ZPROMOPCT
      , BIC_ZPROMOQTY
      , BIC_ZSLSCORR
      , BIC_ZSNPCONS
      , BIC_ZSTATFORE
      , BIC_ZLEADIND
      , BIC_ZPOSQTY
      , BIC_ZMCORHIST
      , BIC_ZACPROR
      , BIC_ZADDPF
      , BIC_ZALTFCST
      , BIC_ZCUSTINV
      , BIC_ZDUMMY1
      , BIC_ZDUMMY2
      , BIC_ZFCSTCI
      , BIC_ZINTFCST1
      , BIC_ZINTFCST2
      , BIC_ZNWPP
      , BIC_ZPRMOFCST
      , BIC_ZUPSS
      , BIC_ZUPTDAY
      , BIC_ZYANPLAN
      , BIC_ZCANNIBLE
      , BIC_ZANALIFT
      , BIC_ZBASELN
      , BIC_ZDPDOLLAR
      , BIC_ZINTFCST
      , BIC_ZINVLD
      , BIC_ZMKTGRTH
      , BIC_ZNODOLLAR
      , BIC_ZPOSCORR
      , BIC_ZPULLAHD
      , BIC_ZSTAT1
      , BIC_ZSTAT2
      , BIC_ZSTAT4
      , BIC_ZTOPFCST
      , BIC_ZSTATFCST
      , BIC_ZTOPGRTH
      , BIC_ZTRANSDMD
      , BIC_ZEXTRA1
      , BIC_ZEXTRA2
      , BIC_ZEXTRA3
      , BIC_ZEXTRA4
      , BIC_ZMOENPROP
      , BIC_ZNEWPFCST
      , BIC_ZOUTTED
      , BIC_ZSTAT3
      , GLDELFLAG
      , GLCHANGETIME
      , PSA_LOAD_DTS
      , PSA_DELETE_IND
      , PSA_RECORD_SOURCE
      , LOAD_DTS
      , REC_SRC
      , DEMAND_PLAN_LHK
      , HASHDIFF
    FROM SRC_s
)
---- RENAME LAYER ----

, RENAME_s as (
    SELECT
        REQUID
      , CALMONTH
      , CALQUARTER
      , CALWEEK
      , FISCPER
      , FISCVARNT
      , FISCYEAR
      , CALYEAR
      , SALES_UNIT
      , UNIT
      , BASE_UOM
      , DATE0
      , DISTR_CHAN
      , DIVISION
      , MATERIAL
      , PLANT
      , SALESORG
      , BIC_ZZAPOACCT
      , BIC_ZZAPOGRP
      , APO_PLVERS
      , BIC_ZZPLANPER
      , BIC_ZFQUARTER
      , BIC_ZFYEAR
      , BIC_ZMONTH
      , BIC_ZQUARTER
      , MAT_PLANT
      , BIC_ZACCTMATL
      , BIC_ZZMATENTR
      , CURRENCY
      , GLREQUEST
      , GLSOURCESYSTEM
      , ORDER_QTY
      , BIC_Z9ADFCST
      , BIC_ZCANNIBAL
      , BIC_ZCORRHIST
      , BIC_ZCUSTFORE
      , BIC_ZFCSTERR
      , BIC_ZFINLFCST
      , BIC_ZLYSALES1
      , BIC_ZLYSALES2
      , BIC_ZMANUCORR
      , BIC_ZMAPE
      , BIC_ZMKTCORR
      , BIC_ZPRODLIFE
      , BIC_ZPROMOPCT
      , BIC_ZPROMOQTY
      , BIC_ZSLSCORR
      , BIC_ZSNPCONS
      , BIC_ZSTATFORE
      , BIC_ZLEADIND
      , BIC_ZPOSQTY
      , BIC_ZMCORHIST
      , BIC_ZACPROR
      , BIC_ZADDPF
      , BIC_ZALTFCST
      , BIC_ZCUSTINV
      , BIC_ZDUMMY1
      , BIC_ZDUMMY2
      , BIC_ZFCSTCI
      , BIC_ZINTFCST1
      , BIC_ZINTFCST2
      , BIC_ZNWPP
      , BIC_ZPRMOFCST
      , BIC_ZUPSS
      , BIC_ZUPTDAY
      , BIC_ZYANPLAN
      , BIC_ZCANNIBLE
      , BIC_ZANALIFT
      , BIC_ZBASELN
      , BIC_ZDPDOLLAR
      , BIC_ZINTFCST
      , BIC_ZINVLD
      , BIC_ZMKTGRTH
      , BIC_ZNODOLLAR
      , BIC_ZPOSCORR
      , BIC_ZPULLAHD
      , BIC_ZSTAT1
      , BIC_ZSTAT2
      , BIC_ZSTAT4
      , BIC_ZTOPFCST
      , BIC_ZSTATFCST
      , BIC_ZTOPGRTH
      , BIC_ZTRANSDMD
      , BIC_ZEXTRA1
      , BIC_ZEXTRA2
      , BIC_ZEXTRA3
      , BIC_ZEXTRA4
      , BIC_ZMOENPROP
      , BIC_ZNEWPFCST
      , BIC_ZOUTTED
      , BIC_ZSTAT3
      , GLDELFLAG
      , GLCHANGETIME
      , PSA_LOAD_DTS
      , PSA_DELETE_IND
      , PSA_RECORD_SOURCE
      , LOAD_DTS
      , REC_SRC
      , DEMAND_PLAN_LHK
      , HASHDIFF
    FROM LOGIC_s
)
---- FILTER LAYER ----

, FILTER_s as (
    SELECT *
    FROM RENAME_s
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM FILTER_s
)

---- FINAL LAYER ----
SELECT
          REQUID
        , CALMONTH
        , CALQUARTER
        , CALWEEK
        , FISCPER
        , FISCVARNT
        , FISCYEAR
        , CALYEAR
        , SALES_UNIT
        , UNIT
        , BASE_UOM
        , DATE0
        , DISTR_CHAN
        , DIVISION
        , MATERIAL
        , PLANT
        , SALESORG
        , BIC_ZZAPOACCT
        , BIC_ZZAPOGRP
        , APO_PLVERS
        , BIC_ZZPLANPER
        , BIC_ZFQUARTER
        , BIC_ZFYEAR
        , BIC_ZMONTH
        , BIC_ZQUARTER
        , MAT_PLANT
        , BIC_ZACCTMATL
        , BIC_ZZMATENTR
        , CURRENCY
        , GLREQUEST
        , GLSOURCESYSTEM
        , ORDER_QTY
        , BIC_Z9ADFCST
        , BIC_ZCANNIBAL
        , BIC_ZCORRHIST
        , BIC_ZCUSTFORE
        , BIC_ZFCSTERR
        , BIC_ZFINLFCST
        , BIC_ZLYSALES1
        , BIC_ZLYSALES2
        , BIC_ZMANUCORR
        , BIC_ZMAPE
        , BIC_ZMKTCORR
        , BIC_ZPRODLIFE
        , BIC_ZPROMOPCT
        , BIC_ZPROMOQTY
        , BIC_ZSLSCORR
        , BIC_ZSNPCONS
        , BIC_ZSTATFORE
        , BIC_ZLEADIND
        , BIC_ZPOSQTY
        , BIC_ZMCORHIST
        , BIC_ZACPROR
        , BIC_ZADDPF
        , BIC_ZALTFCST
        , BIC_ZCUSTINV
        , BIC_ZDUMMY1
        , BIC_ZDUMMY2
        , BIC_ZFCSTCI
        , BIC_ZINTFCST1
        , BIC_ZINTFCST2
        , BIC_ZNWPP
        , BIC_ZPRMOFCST
        , BIC_ZUPSS
        , BIC_ZUPTDAY
        , BIC_ZYANPLAN
        , BIC_ZCANNIBLE
        , BIC_ZANALIFT
        , BIC_ZBASELN
        , BIC_ZDPDOLLAR
        , BIC_ZINTFCST
        , BIC_ZINVLD
        , BIC_ZMKTGRTH
        , BIC_ZNODOLLAR
        , BIC_ZPOSCORR
        , BIC_ZPULLAHD
        , BIC_ZSTAT1
        , BIC_ZSTAT2
        , BIC_ZSTAT4
        , BIC_ZTOPFCST
        , BIC_ZSTATFCST
        , BIC_ZTOPGRTH
        , BIC_ZTRANSDMD
        , BIC_ZEXTRA1
        , BIC_ZEXTRA2
        , BIC_ZEXTRA3
        , BIC_ZEXTRA4
        , BIC_ZMOENPROP
        , BIC_ZNEWPFCST
        , BIC_ZOUTTED
        , BIC_ZSTAT3
        , GLDELFLAG
        , GLCHANGETIME
        , PSA_LOAD_DTS
        , PSA_DELETE_IND
        , PSA_RECORD_SOURCE
        , LOAD_DTS
        , REC_SRC
        , DEMAND_PLAN_LHK
        , HASHDIFF
FROM JOIN_RESULT
{% if is_incremental() %}
WHERE NOT EXISTS (
SELECT 1
FROM {{ this }} existing
WHERE existing.DEMAND_PLAN_LHK = JOIN_RESULT.DEMAND_PLAN_LHK
  AND existing.MATERIAL = JOIN_RESULT.MATERIAL
  AND existing.CALWEEK = JOIN_RESULT.CALWEEK
  AND existing.DATE0 = JOIN_RESULT.DATE0
  AND existing.HASHDIFF = JOIN_RESULT.HASHDIFF
)
{% endif %}
{% if not is_incremental() %}

/* The following qualifier is implemented to prevent multiple loads of touched records during the initial build, such as multiple rows per HK and hashdiff. */
qualify 1 = row_number() over (partition by DEMAND_PLAN_LHK, MATERIAL, CALWEEK, DATE0, HASHDIFF order by PSA_LOAD_DTS)

union all
SELECT
NULL AS REQUID,
NULL AS CALMONTH,
NULL AS CALQUARTER,
GR.VALUE AS CALWEEK,
NULL AS FISCPER,
NULL AS FISCVARNT,
NULL AS FISCYEAR,
NULL AS CALYEAR,
NULL AS SALES_UNIT,
NULL AS UNIT,
NULL AS BASE_UOM,
GR.VALUE AS DATE0,
NULL AS DISTR_CHAN,
NULL AS DIVISION,
GR.VALUE AS MATERIAL,
NULL AS PLANT,
NULL AS SALESORG,
NULL AS BIC_ZZAPOACCT,
NULL AS BIC_ZZAPOGRP,
NULL AS APO_PLVERS,
NULL AS BIC_ZZPLANPER,
NULL AS BIC_ZFQUARTER,
NULL AS BIC_ZFYEAR,
NULL AS BIC_ZMONTH,
NULL AS BIC_ZQUARTER,
NULL AS MAT_PLANT,
NULL AS BIC_ZACCTMATL,
NULL AS BIC_ZZMATENTR,
NULL AS CURRENCY,
NULL AS GLREQUEST,
NULL AS GLSOURCESYSTEM,
NULL AS ORDER_QTY,
NULL AS BIC_Z9ADFCST,
NULL AS BIC_ZCANNIBAL,
NULL AS BIC_ZCORRHIST,
NULL AS BIC_ZCUSTFORE,
NULL AS BIC_ZFCSTERR,
NULL AS BIC_ZFINLFCST,
NULL AS BIC_ZLYSALES1,
NULL AS BIC_ZLYSALES2,
NULL AS BIC_ZMANUCORR,
NULL AS BIC_ZMAPE,
NULL AS BIC_ZMKTCORR,
NULL AS BIC_ZPRODLIFE,
NULL AS BIC_ZPROMOPCT,
NULL AS BIC_ZPROMOQTY,
NULL AS BIC_ZSLSCORR,
NULL AS BIC_ZSNPCONS,
NULL AS BIC_ZSTATFORE,
NULL AS BIC_ZLEADIND,
NULL AS BIC_ZPOSQTY,
NULL AS BIC_ZMCORHIST,
NULL AS BIC_ZACPROR,
NULL AS BIC_ZADDPF,
NULL AS BIC_ZALTFCST,
NULL AS BIC_ZCUSTINV,
NULL AS BIC_ZDUMMY1,
NULL AS BIC_ZDUMMY2,
NULL AS BIC_ZFCSTCI,
NULL AS BIC_ZINTFCST1,
NULL AS BIC_ZINTFCST2,
NULL AS BIC_ZNWPP,
NULL AS BIC_ZPRMOFCST,
NULL AS BIC_ZUPSS,
NULL AS BIC_ZUPTDAY,
NULL AS BIC_ZYANPLAN,
NULL AS BIC_ZCANNIBLE,
NULL AS BIC_ZANALIFT,
NULL AS BIC_ZBASELN,
NULL AS BIC_ZDPDOLLAR,
NULL AS BIC_ZINTFCST,
NULL AS BIC_ZINVLD,
NULL AS BIC_ZMKTGRTH,
NULL AS BIC_ZNODOLLAR,
NULL AS BIC_ZPOSCORR,
NULL AS BIC_ZPULLAHD,
NULL AS BIC_ZSTAT1,
NULL AS BIC_ZSTAT2,
NULL AS BIC_ZSTAT4,
NULL AS BIC_ZTOPFCST,
NULL AS BIC_ZSTATFCST,
NULL AS BIC_ZTOPGRTH,
NULL AS BIC_ZTRANSDMD,
NULL AS BIC_ZEXTRA1,
NULL AS BIC_ZEXTRA2,
NULL AS BIC_ZEXTRA3,
NULL AS BIC_ZEXTRA4,
NULL AS BIC_ZMOENPROP,
NULL AS BIC_ZNEWPFCST,
NULL AS BIC_ZOUTTED,
NULL AS BIC_ZSTAT3,
NULL AS GLDELFLAG,
NULL AS GLCHANGETIME,
NULL AS PSA_LOAD_DTS,
NULL AS PSA_DELETE_IND,
NULL AS PSA_RECORD_SOURCE,
CONVERT_TIMEZONE('UTC','1900-01-01'::TIMESTAMP) AS LOAD_DTS,
'USAZET.SNOWFLAKE.FBIN.DERIVED' AS REC_SRC,
MD5_BINARY(GR.VALUE) AS DEMAND_PLAN_LHK,
''::BINARY AS HASHDIFF
FROM
TABLE(strtok_split_to_table('0|-1|-2', '|')) AS GR
{% endif %}
