---- SRC LAYER ----
WITH
SRC_a              as ( SELECT * FROM {{ ref('v_psa_stg_po_receipt__ml_ebs') }} as SRC 
                        {% if is_incremental() %}
                              where src.load_dts > (select dateadd('HOUR',-1,max(load_dts)) from {{ this }})
                            {% endif %}   )

/*
SRC_a              as ( SELECT * FROM STAGING.v_psa_stg_po_receipt__ml_ebs )
*/
---- LOGIC LAYER ----

, LOGIC_a as (
    SELECT
        LNK_PO_RECEIPT_HK
      , PO_HEADER_ID
      , LINE_NUM
      , TRANSACTION_ID
      , ORGANIZATION_ID
      , TRANSACTION_SOURCE_ID
      , COMMON_ROUTING_SEQ_ID
      , TRANSACTION_SET_ID
      , COST_GROUP_ID
      , VARIANCE_AMOUNT
      , ERROR_EXPLANATION
      , ATTRIBUTE10
      , CYCLE_COUNT_ID
      , ERROR_CODE
      , SECONDARY_UOM_CODE
      , SHIPMENT_COSTED
      , INTERCOMPANY_COST
      , TRANSACTION_BATCH_SEQ
      , PROJECT_ID
      , TO_PROJECT_ID
      , EXPENSE_ACCOUNT_ID
      , TRANSFER_OWNING_TP_TYPE
      , INVENTORY_ITEM_ID
      , LPN_ID
      , MOVE_ORDER_LINE_ID
      , ATTRIBUTE1
      , SOURCE_CODE
      , VALUE_CHANGE
      , PUT_AWAY_RULE_ID
      , TRANSACTION_UOM
      , TRANSFER_PRICE
      , LAST_UPDATE_LOGIN
      , PICKING_LINE_ID
      , USSGL_TRANSACTION_CODE
      , TRANSFER_SUBINVENTORY
      , EXPENDITURE_TYPE
      , SO_ISSUE_ACCOUNT_TYPE
      , OVERHEAD_ACCOUNT
      , PRIOR_COST
      , TRANSFER_LOCATOR_ID
      , TRANSACTION_EXTRACTED
      , ATTRIBUTE2
      , OVERCOMPLETION_TRANSACTION_QTY
      , PA_EXPENDITURE_ORG_ID
      , MATERIAL_OVERHEAD_ACCOUNT
      , TRANSPORTATION_DIST_ACCOUNT
      , TRANSFER_PLANNING_TP_TYPE
      , TRANSACTION_BATCH_ID
      , TRANSFER_ORGANIZATION_TYPE
      , PARENT_TRANSACTION_ID
      , _FIVETRAN_SYNCED
      , XFR_PLANNING_ORGANIZATION_ID
      , OPM_COSTED_FLAG
      , _FIVETRAN_ID
      , TRANSFER_COST_DIST_ACCOUNT
      , OWNING_TP_TYPE
      , PICK_STRATEGY_ID
      , RECEIVING_DOCUMENT
      , PERCENTAGE_CHANGE
      , NUMBER_OF_CONTAINERS
      , LOCATOR_ID
      , TRANSACTION_ACTION_ID
      , ORGANIZATION_TYPE
      , EMPLOYEE_CODE
      , REASON_ID
      , OWNING_ORGANIZATION_ID
      , CREATED_BY
      , ACTUAL_COST
      , PLANNING_ORGANIZATION_ID
      , REPETITIVE_LINE_ID
      , TRANSPORTATION_COST
      , ATTRIBUTE3
      , MATERIAL_ACCOUNT
      , TRANSFER_TRANSACTION_ID
      , PM_COST_COLLECTED
      , RESERVATION_ID
      , LOGICAL_TRANSACTION
      , SHIP_TO_LOCATION_ID
      , ATTRIBUTE15
      , COMMON_BOM_SEQ_ID
      , PRIOR_COSTED_QUANTITY
      , TRANSFER_ORGANIZATION_ID
      , INTRANSIT_ACCOUNT
      , COMPLETION_TRANSACTION_ID
      , LOGICAL_TRX_TYPE_CODE
      , INTERCOMPANY_CURRENCY_CODE
      , PLANNING_TP_TYPE
      , COGS_RECOGNITION_PERCENT
      , MASTER_SCHEDULE_UPDATE_CODE
      , QA_COLLECTION_ID
      , PERIODIC_PRIMARY_QUANTITY
      , ATTRIBUTE6
      , TRX_SOURCE_LINE_ID
      , REQUEST_ID
      , SOURCE_LINE_ID
      , CURRENCY_CONVERSION_TYPE
      , ATTRIBUTE4
      , LAST_UPDATE_DATE
      , OPERATION_SEQ_NUM
      , ATTRIBUTE7
      , PICK_RULE_ID
      , INVOICED_FLAG
      , CONTENT_LPN_ID
      , TRANSACTION_QUANTITY
      , TRANSFER_LPN_ID
      , TRANSACTION_SOURCE_TYPE_ID
      , ORIGINAL_TRANSACTION_TEMP_ID
      , OVERCOMPLETION_TRANSACTION_ID
      , ATTRIBUTE12
      , SHORTAGE_PROCESS_CODE
      , XFR_OWNING_ORGANIZATION_ID
      , ATTRIBUTE11
      , CURRENCY_CODE
      , DEPARTMENT_ID
      , COST_UPDATE_ID
      , PICK_SLIP_NUMBER
      , RCV_TRANSACTION_ID
      , ENCUMBRANCE_ACCOUNT
      , COST_TYPE_ID
      , MVT_STAT_STATUS
      , OVERCOMPLETION_PRIMARY_QTY
      , CREATION_DATE
      , LAST_UPDATED_BY
      , OUTSIDE_PROCESSING_ACCOUNT
      , DISTRIBUTION_ACCOUNT_ID
      , TRANSACTION_REFERENCE
      , NEW_COST
      , FLOW_SCHEDULE
      , TRX_SOURCE_DELIVERY_ID
      , MOVE_TRANSACTION_ID
      , ACCT_PERIOD_ID
      , TRANSACTION_MODE
      , SHIPMENT_NUMBER
      , TRANSACTION_DATE
      , VENDOR_LOT_NUMBER
      , FREIGHT_CODE
      , TRANSFER_COST
      , ATTRIBUTE9
      , PRIMARY_QUANTITY
      , FINAL_COMPLETION_FLAG
      , TO_TASK_ID
      , TRANSACTION_COST
      , FOB_POINT
      , REVISION
      , SUBINVENTORY_CODE
      , ATTRIBUTE13
      , LOGICAL_TRANSACTIONS_CREATED
      , _FIVETRAN_DELETED
      , CURRENCY_CONVERSION_RATE
      , QUANTITY_ADJUSTED
      , PUT_AWAY_STRATEGY_ID
      , ENCUMBRANCE_AMOUNT
      , SOURCE_PROJECT_ID
      , TRANSACTION_GROUP_SEQ
      , TASK_GROUP_ID
      , MATERIAL_EXPENSE_ACCOUNT
      , TRANSACTION_SOURCE_NAME
      , XML_DOCUMENT_ID
      , TRANSFER_PERCENTAGE
      , TRANSACTION_GROUP_ID
      , ATTRIBUTE14
      , ATTRIBUTE8
      , PROGRAM_UPDATE_DATE
      , MOVEMENT_ID
      , PICK_SLIP_DATE
      , PHYSICAL_ADJUSTMENT_ID
      , TASK_ID
      , WAYBILL_AIRBILL
      , RMA_LINE_ID
      , SOURCE_TASK_ID
      , PROGRAM_ID
      , TRANSFER_COST_GROUP_ID
      , TRANSACTION_TYPE_ID
      , ATTRIBUTE5
      , COST_CATEGORY_ID
      , ATTRIBUTE_CATEGORY
      , TRANSFER_PRIOR_COSTED_QUANTITY
      , INTERCOMPANY_PRICING_OPTION
      , CURRENCY_CONVERSION_DATE
      , PROGRAM_APPLICATION_ID
      , ORG_COST_GROUP_ID
      , SECONDARY_TRANSACTION_QUANTITY
      , RESOURCE_ACCOUNT
      , TRX_FLOW_HEADER_ID
      , COSTED_FLAG
      , PM_COST_COLLECTOR_GROUP_ID
      , PSA_LOAD_DTS
      , PSA_DELETE_IND
      , LOAD_DTS
      , BKCC
      , REC_SRC
      , HASHDIFF
    FROM SRC_a
)
---- RENAME LAYER ----

, RENAME_a as (
    SELECT
        LNK_PO_RECEIPT_HK
      , PO_HEADER_ID
      , LINE_NUM
      , TRANSACTION_ID
      , ORGANIZATION_ID
      , TRANSACTION_SOURCE_ID
      , COMMON_ROUTING_SEQ_ID
      , TRANSACTION_SET_ID
      , COST_GROUP_ID
      , VARIANCE_AMOUNT
      , ERROR_EXPLANATION
      , ATTRIBUTE10
      , CYCLE_COUNT_ID
      , ERROR_CODE
      , SECONDARY_UOM_CODE
      , SHIPMENT_COSTED
      , INTERCOMPANY_COST
      , TRANSACTION_BATCH_SEQ
      , PROJECT_ID
      , TO_PROJECT_ID
      , EXPENSE_ACCOUNT_ID
      , TRANSFER_OWNING_TP_TYPE
      , INVENTORY_ITEM_ID
      , LPN_ID
      , MOVE_ORDER_LINE_ID
      , ATTRIBUTE1
      , SOURCE_CODE
      , VALUE_CHANGE
      , PUT_AWAY_RULE_ID
      , TRANSACTION_UOM
      , TRANSFER_PRICE
      , LAST_UPDATE_LOGIN
      , PICKING_LINE_ID
      , USSGL_TRANSACTION_CODE
      , TRANSFER_SUBINVENTORY
      , EXPENDITURE_TYPE
      , SO_ISSUE_ACCOUNT_TYPE
      , OVERHEAD_ACCOUNT
      , PRIOR_COST
      , TRANSFER_LOCATOR_ID
      , TRANSACTION_EXTRACTED
      , ATTRIBUTE2
      , OVERCOMPLETION_TRANSACTION_QTY
      , PA_EXPENDITURE_ORG_ID
      , MATERIAL_OVERHEAD_ACCOUNT
      , TRANSPORTATION_DIST_ACCOUNT
      , TRANSFER_PLANNING_TP_TYPE
      , TRANSACTION_BATCH_ID
      , TRANSFER_ORGANIZATION_TYPE
      , PARENT_TRANSACTION_ID
      , _FIVETRAN_SYNCED
      , XFR_PLANNING_ORGANIZATION_ID
      , OPM_COSTED_FLAG
      , _FIVETRAN_ID
      , TRANSFER_COST_DIST_ACCOUNT
      , OWNING_TP_TYPE
      , PICK_STRATEGY_ID
      , RECEIVING_DOCUMENT
      , PERCENTAGE_CHANGE
      , NUMBER_OF_CONTAINERS
      , LOCATOR_ID
      , TRANSACTION_ACTION_ID
      , ORGANIZATION_TYPE
      , EMPLOYEE_CODE
      , REASON_ID
      , OWNING_ORGANIZATION_ID
      , CREATED_BY
      , ACTUAL_COST
      , PLANNING_ORGANIZATION_ID
      , REPETITIVE_LINE_ID
      , TRANSPORTATION_COST
      , ATTRIBUTE3
      , MATERIAL_ACCOUNT
      , TRANSFER_TRANSACTION_ID
      , PM_COST_COLLECTED
      , RESERVATION_ID
      , LOGICAL_TRANSACTION
      , SHIP_TO_LOCATION_ID
      , ATTRIBUTE15
      , COMMON_BOM_SEQ_ID
      , PRIOR_COSTED_QUANTITY
      , TRANSFER_ORGANIZATION_ID
      , INTRANSIT_ACCOUNT
      , COMPLETION_TRANSACTION_ID
      , LOGICAL_TRX_TYPE_CODE
      , INTERCOMPANY_CURRENCY_CODE
      , PLANNING_TP_TYPE
      , COGS_RECOGNITION_PERCENT
      , MASTER_SCHEDULE_UPDATE_CODE
      , QA_COLLECTION_ID
      , PERIODIC_PRIMARY_QUANTITY
      , ATTRIBUTE6
      , TRX_SOURCE_LINE_ID
      , REQUEST_ID
      , SOURCE_LINE_ID
      , CURRENCY_CONVERSION_TYPE
      , ATTRIBUTE4
      , LAST_UPDATE_DATE
      , OPERATION_SEQ_NUM
      , ATTRIBUTE7
      , PICK_RULE_ID
      , INVOICED_FLAG
      , CONTENT_LPN_ID
      , TRANSACTION_QUANTITY
      , TRANSFER_LPN_ID
      , TRANSACTION_SOURCE_TYPE_ID
      , ORIGINAL_TRANSACTION_TEMP_ID
      , OVERCOMPLETION_TRANSACTION_ID
      , ATTRIBUTE12
      , SHORTAGE_PROCESS_CODE
      , XFR_OWNING_ORGANIZATION_ID
      , ATTRIBUTE11
      , CURRENCY_CODE
      , DEPARTMENT_ID
      , COST_UPDATE_ID
      , PICK_SLIP_NUMBER
      , RCV_TRANSACTION_ID
      , ENCUMBRANCE_ACCOUNT
      , COST_TYPE_ID
      , MVT_STAT_STATUS
      , OVERCOMPLETION_PRIMARY_QTY
      , CREATION_DATE
      , LAST_UPDATED_BY
      , OUTSIDE_PROCESSING_ACCOUNT
      , DISTRIBUTION_ACCOUNT_ID
      , TRANSACTION_REFERENCE
      , NEW_COST
      , FLOW_SCHEDULE
      , TRX_SOURCE_DELIVERY_ID
      , MOVE_TRANSACTION_ID
      , ACCT_PERIOD_ID
      , TRANSACTION_MODE
      , SHIPMENT_NUMBER
      , TRANSACTION_DATE
      , VENDOR_LOT_NUMBER
      , FREIGHT_CODE
      , TRANSFER_COST
      , ATTRIBUTE9
      , PRIMARY_QUANTITY
      , FINAL_COMPLETION_FLAG
      , TO_TASK_ID
      , TRANSACTION_COST
      , FOB_POINT
      , REVISION
      , SUBINVENTORY_CODE
      , ATTRIBUTE13
      , LOGICAL_TRANSACTIONS_CREATED
      , _FIVETRAN_DELETED
      , CURRENCY_CONVERSION_RATE
      , QUANTITY_ADJUSTED
      , PUT_AWAY_STRATEGY_ID
      , ENCUMBRANCE_AMOUNT
      , SOURCE_PROJECT_ID
      , TRANSACTION_GROUP_SEQ
      , TASK_GROUP_ID
      , MATERIAL_EXPENSE_ACCOUNT
      , TRANSACTION_SOURCE_NAME
      , XML_DOCUMENT_ID
      , TRANSFER_PERCENTAGE
      , TRANSACTION_GROUP_ID
      , ATTRIBUTE14
      , ATTRIBUTE8
      , PROGRAM_UPDATE_DATE
      , MOVEMENT_ID
      , PICK_SLIP_DATE
      , PHYSICAL_ADJUSTMENT_ID
      , TASK_ID
      , WAYBILL_AIRBILL
      , RMA_LINE_ID
      , SOURCE_TASK_ID
      , PROGRAM_ID
      , TRANSFER_COST_GROUP_ID
      , TRANSACTION_TYPE_ID
      , ATTRIBUTE5
      , COST_CATEGORY_ID
      , ATTRIBUTE_CATEGORY
      , TRANSFER_PRIOR_COSTED_QUANTITY
      , INTERCOMPANY_PRICING_OPTION
      , CURRENCY_CONVERSION_DATE
      , PROGRAM_APPLICATION_ID
      , ORG_COST_GROUP_ID
      , SECONDARY_TRANSACTION_QUANTITY
      , RESOURCE_ACCOUNT
      , TRX_FLOW_HEADER_ID
      , COSTED_FLAG
      , PM_COST_COLLECTOR_GROUP_ID
      , PSA_LOAD_DTS
      , PSA_DELETE_IND
      , LOAD_DTS
      , BKCC
      , REC_SRC
      , HASHDIFF
    FROM LOGIC_a
)
---- FILTER LAYER ----

, FILTER_a as (
    SELECT *
    FROM RENAME_a
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM FILTER_a
)

---- FINAL LAYER ----
SELECT
          LNK_PO_RECEIPT_HK
        , PO_HEADER_ID
        , LINE_NUM
        , TRANSACTION_ID
        , ORGANIZATION_ID
        , TRANSACTION_SOURCE_ID
        , COMMON_ROUTING_SEQ_ID
        , TRANSACTION_SET_ID
        , COST_GROUP_ID
        , VARIANCE_AMOUNT
        , ERROR_EXPLANATION
        , ATTRIBUTE10
        , CYCLE_COUNT_ID
        , ERROR_CODE
        , SECONDARY_UOM_CODE
        , SHIPMENT_COSTED
        , INTERCOMPANY_COST
        , TRANSACTION_BATCH_SEQ
        , PROJECT_ID
        , TO_PROJECT_ID
        , EXPENSE_ACCOUNT_ID
        , TRANSFER_OWNING_TP_TYPE
        , INVENTORY_ITEM_ID
        , LPN_ID
        , MOVE_ORDER_LINE_ID
        , ATTRIBUTE1
        , SOURCE_CODE
        , VALUE_CHANGE
        , PUT_AWAY_RULE_ID
        , TRANSACTION_UOM
        , TRANSFER_PRICE
        , LAST_UPDATE_LOGIN
        , PICKING_LINE_ID
        , USSGL_TRANSACTION_CODE
        , TRANSFER_SUBINVENTORY
        , EXPENDITURE_TYPE
        , SO_ISSUE_ACCOUNT_TYPE
        , OVERHEAD_ACCOUNT
        , PRIOR_COST
        , TRANSFER_LOCATOR_ID
        , TRANSACTION_EXTRACTED
        , ATTRIBUTE2
        , OVERCOMPLETION_TRANSACTION_QTY
        , PA_EXPENDITURE_ORG_ID
        , MATERIAL_OVERHEAD_ACCOUNT
        , TRANSPORTATION_DIST_ACCOUNT
        , TRANSFER_PLANNING_TP_TYPE
        , TRANSACTION_BATCH_ID
        , TRANSFER_ORGANIZATION_TYPE
        , PARENT_TRANSACTION_ID
        , _FIVETRAN_SYNCED
        , XFR_PLANNING_ORGANIZATION_ID
        , OPM_COSTED_FLAG
        , _FIVETRAN_ID
        , TRANSFER_COST_DIST_ACCOUNT
        , OWNING_TP_TYPE
        , PICK_STRATEGY_ID
        , RECEIVING_DOCUMENT
        , PERCENTAGE_CHANGE
        , NUMBER_OF_CONTAINERS
        , LOCATOR_ID
        , TRANSACTION_ACTION_ID
        , ORGANIZATION_TYPE
        , EMPLOYEE_CODE
        , REASON_ID
        , OWNING_ORGANIZATION_ID
        , CREATED_BY
        , ACTUAL_COST
        , PLANNING_ORGANIZATION_ID
        , REPETITIVE_LINE_ID
        , TRANSPORTATION_COST
        , ATTRIBUTE3
        , MATERIAL_ACCOUNT
        , TRANSFER_TRANSACTION_ID
        , PM_COST_COLLECTED
        , RESERVATION_ID
        , LOGICAL_TRANSACTION
        , SHIP_TO_LOCATION_ID
        , ATTRIBUTE15
        , COMMON_BOM_SEQ_ID
        , PRIOR_COSTED_QUANTITY
        , TRANSFER_ORGANIZATION_ID
        , INTRANSIT_ACCOUNT
        , COMPLETION_TRANSACTION_ID
        , LOGICAL_TRX_TYPE_CODE
        , INTERCOMPANY_CURRENCY_CODE
        , PLANNING_TP_TYPE
        , COGS_RECOGNITION_PERCENT
        , MASTER_SCHEDULE_UPDATE_CODE
        , QA_COLLECTION_ID
        , PERIODIC_PRIMARY_QUANTITY
        , ATTRIBUTE6
        , TRX_SOURCE_LINE_ID
        , REQUEST_ID
        , SOURCE_LINE_ID
        , CURRENCY_CONVERSION_TYPE
        , ATTRIBUTE4
        , LAST_UPDATE_DATE
        , OPERATION_SEQ_NUM
        , ATTRIBUTE7
        , PICK_RULE_ID
        , INVOICED_FLAG
        , CONTENT_LPN_ID
        , TRANSACTION_QUANTITY
        , TRANSFER_LPN_ID
        , TRANSACTION_SOURCE_TYPE_ID
        , ORIGINAL_TRANSACTION_TEMP_ID
        , OVERCOMPLETION_TRANSACTION_ID
        , ATTRIBUTE12
        , SHORTAGE_PROCESS_CODE
        , XFR_OWNING_ORGANIZATION_ID
        , ATTRIBUTE11
        , CURRENCY_CODE
        , DEPARTMENT_ID
        , COST_UPDATE_ID
        , PICK_SLIP_NUMBER
        , RCV_TRANSACTION_ID
        , ENCUMBRANCE_ACCOUNT
        , COST_TYPE_ID
        , MVT_STAT_STATUS
        , OVERCOMPLETION_PRIMARY_QTY
        , CREATION_DATE
        , LAST_UPDATED_BY
        , OUTSIDE_PROCESSING_ACCOUNT
        , DISTRIBUTION_ACCOUNT_ID
        , TRANSACTION_REFERENCE
        , NEW_COST
        , FLOW_SCHEDULE
        , TRX_SOURCE_DELIVERY_ID
        , MOVE_TRANSACTION_ID
        , ACCT_PERIOD_ID
        , TRANSACTION_MODE
        , SHIPMENT_NUMBER
        , TRANSACTION_DATE
        , VENDOR_LOT_NUMBER
        , FREIGHT_CODE
        , TRANSFER_COST
        , ATTRIBUTE9
        , PRIMARY_QUANTITY
        , FINAL_COMPLETION_FLAG
        , TO_TASK_ID
        , TRANSACTION_COST
        , FOB_POINT
        , REVISION
        , SUBINVENTORY_CODE
        , ATTRIBUTE13
        , LOGICAL_TRANSACTIONS_CREATED
        , _FIVETRAN_DELETED
        , CURRENCY_CONVERSION_RATE
        , QUANTITY_ADJUSTED
        , PUT_AWAY_STRATEGY_ID
        , ENCUMBRANCE_AMOUNT
        , SOURCE_PROJECT_ID
        , TRANSACTION_GROUP_SEQ
        , TASK_GROUP_ID
        , MATERIAL_EXPENSE_ACCOUNT
        , TRANSACTION_SOURCE_NAME
        , XML_DOCUMENT_ID
        , TRANSFER_PERCENTAGE
        , TRANSACTION_GROUP_ID
        , ATTRIBUTE14
        , ATTRIBUTE8
        , PROGRAM_UPDATE_DATE
        , MOVEMENT_ID
        , PICK_SLIP_DATE
        , PHYSICAL_ADJUSTMENT_ID
        , TASK_ID
        , WAYBILL_AIRBILL
        , RMA_LINE_ID
        , SOURCE_TASK_ID
        , PROGRAM_ID
        , TRANSFER_COST_GROUP_ID
        , TRANSACTION_TYPE_ID
        , ATTRIBUTE5
        , COST_CATEGORY_ID
        , ATTRIBUTE_CATEGORY
        , TRANSFER_PRIOR_COSTED_QUANTITY
        , INTERCOMPANY_PRICING_OPTION
        , CURRENCY_CONVERSION_DATE
        , PROGRAM_APPLICATION_ID
        , ORG_COST_GROUP_ID
        , SECONDARY_TRANSACTION_QUANTITY
        , RESOURCE_ACCOUNT
        , TRX_FLOW_HEADER_ID
        , COSTED_FLAG
        , PM_COST_COLLECTOR_GROUP_ID
        , PSA_LOAD_DTS
        , PSA_DELETE_IND
        , LOAD_DTS
        , BKCC
        , REC_SRC
        , HASHDIFF
FROM JOIN_RESULT
{% if is_incremental() %}
WHERE NOT EXISTS (
    SELECT 1 
    FROM {{ this }} existing
    WHERE existing.LNK_PO_RECEIPT_HK = JOIN_RESULT.LNK_PO_RECEIPT_HK
    AND existing.HASHDIFF = JOIN_RESULT.HASHDIFF
)
{% endif %}
{% if not is_incremental() %}

/* The following qualifier is implemented to prevent multiple loads of touched records during the initial build, such as multiple rows per HK and hashdiff. */
qualify 1 = row_number() over (partition by LNK_PO_RECEIPT_HK, HASHDIFF order by PSA_LOAD_DTS)

union all
SELECT 
MD5_BINARY(GR.VALUE) AS LNK_PO_RECEIPT_HK,
GR.VALUE::number AS PO_HEADER_ID,
GR.VALUE::number AS LINE_NUM,
GR.VALUE::number AS TRANSACTION_ID,
GR.VALUE::number AS ORGANIZATION_ID,
NULL AS TRANSACTION_SOURCE_ID,
NULL AS COMMON_ROUTING_SEQ_ID,
NULL AS TRANSACTION_SET_ID,
NULL AS COST_GROUP_ID,
NULL AS VARIANCE_AMOUNT,
NULL AS ERROR_EXPLANATION,
NULL AS ATTRIBUTE10,
NULL AS CYCLE_COUNT_ID,
NULL AS ERROR_CODE,
NULL AS SECONDARY_UOM_CODE,
NULL AS SHIPMENT_COSTED,
NULL AS INTERCOMPANY_COST,
NULL AS TRANSACTION_BATCH_SEQ,
NULL AS PROJECT_ID,
NULL AS TO_PROJECT_ID,
NULL AS EXPENSE_ACCOUNT_ID,
NULL AS TRANSFER_OWNING_TP_TYPE,
NULL AS INVENTORY_ITEM_ID,
NULL AS LPN_ID,
NULL AS MOVE_ORDER_LINE_ID,
NULL AS ATTRIBUTE1,
NULL AS SOURCE_CODE,
NULL AS VALUE_CHANGE,
NULL AS PUT_AWAY_RULE_ID,
NULL AS TRANSACTION_UOM,
NULL AS TRANSFER_PRICE,
NULL AS LAST_UPDATE_LOGIN,
NULL AS PICKING_LINE_ID,
NULL AS USSGL_TRANSACTION_CODE,
NULL AS TRANSFER_SUBINVENTORY,
NULL AS EXPENDITURE_TYPE,
NULL AS SO_ISSUE_ACCOUNT_TYPE,
NULL AS OVERHEAD_ACCOUNT,
NULL AS PRIOR_COST,
NULL AS TRANSFER_LOCATOR_ID,
NULL AS TRANSACTION_EXTRACTED,
NULL AS ATTRIBUTE2,
NULL AS OVERCOMPLETION_TRANSACTION_QTY,
NULL AS PA_EXPENDITURE_ORG_ID,
NULL AS MATERIAL_OVERHEAD_ACCOUNT,
NULL AS TRANSPORTATION_DIST_ACCOUNT,
NULL AS TRANSFER_PLANNING_TP_TYPE,
NULL AS TRANSACTION_BATCH_ID,
NULL AS TRANSFER_ORGANIZATION_TYPE,
NULL AS PARENT_TRANSACTION_ID,
NULL AS _FIVETRAN_SYNCED,
NULL AS XFR_PLANNING_ORGANIZATION_ID,
NULL AS OPM_COSTED_FLAG,
NULL AS _FIVETRAN_ID,
NULL AS TRANSFER_COST_DIST_ACCOUNT,
NULL AS OWNING_TP_TYPE,
NULL AS PICK_STRATEGY_ID,
NULL AS RECEIVING_DOCUMENT,
NULL AS PERCENTAGE_CHANGE,
NULL AS NUMBER_OF_CONTAINERS,
NULL AS LOCATOR_ID,
NULL AS TRANSACTION_ACTION_ID,
NULL AS ORGANIZATION_TYPE,
NULL AS EMPLOYEE_CODE,
NULL AS REASON_ID,
NULL AS OWNING_ORGANIZATION_ID,
NULL AS CREATED_BY,
NULL AS ACTUAL_COST,
NULL AS PLANNING_ORGANIZATION_ID,
NULL AS REPETITIVE_LINE_ID,
NULL AS TRANSPORTATION_COST,
NULL AS ATTRIBUTE3,
NULL AS MATERIAL_ACCOUNT,
NULL AS TRANSFER_TRANSACTION_ID,
NULL AS PM_COST_COLLECTED,
NULL AS RESERVATION_ID,
NULL AS LOGICAL_TRANSACTION,
NULL AS SHIP_TO_LOCATION_ID,
NULL AS ATTRIBUTE15,
NULL AS COMMON_BOM_SEQ_ID,
NULL AS PRIOR_COSTED_QUANTITY,
NULL AS TRANSFER_ORGANIZATION_ID,
NULL AS INTRANSIT_ACCOUNT,
NULL AS COMPLETION_TRANSACTION_ID,
NULL AS LOGICAL_TRX_TYPE_CODE,
NULL AS INTERCOMPANY_CURRENCY_CODE,
NULL AS PLANNING_TP_TYPE,
NULL AS COGS_RECOGNITION_PERCENT,
NULL AS MASTER_SCHEDULE_UPDATE_CODE,
NULL AS QA_COLLECTION_ID,
NULL AS PERIODIC_PRIMARY_QUANTITY,
NULL AS ATTRIBUTE6,
NULL AS TRX_SOURCE_LINE_ID,
NULL AS REQUEST_ID,
NULL AS SOURCE_LINE_ID,
NULL AS CURRENCY_CONVERSION_TYPE,
NULL AS ATTRIBUTE4,
NULL AS LAST_UPDATE_DATE,
NULL AS OPERATION_SEQ_NUM,
NULL AS ATTRIBUTE7,
NULL AS PICK_RULE_ID,
NULL AS INVOICED_FLAG,
NULL AS CONTENT_LPN_ID,
NULL AS TRANSACTION_QUANTITY,
NULL AS TRANSFER_LPN_ID,
NULL AS TRANSACTION_SOURCE_TYPE_ID,
NULL AS ORIGINAL_TRANSACTION_TEMP_ID,
NULL AS OVERCOMPLETION_TRANSACTION_ID,
NULL AS ATTRIBUTE12,
NULL AS SHORTAGE_PROCESS_CODE,
NULL AS XFR_OWNING_ORGANIZATION_ID,
NULL AS ATTRIBUTE11,
NULL AS CURRENCY_CODE,
NULL AS DEPARTMENT_ID,
NULL AS COST_UPDATE_ID,
NULL AS PICK_SLIP_NUMBER,
NULL AS RCV_TRANSACTION_ID,
NULL AS ENCUMBRANCE_ACCOUNT,
NULL AS COST_TYPE_ID,
NULL AS MVT_STAT_STATUS,
NULL AS OVERCOMPLETION_PRIMARY_QTY,
NULL AS CREATION_DATE,
NULL AS LAST_UPDATED_BY,
NULL AS OUTSIDE_PROCESSING_ACCOUNT,
NULL AS DISTRIBUTION_ACCOUNT_ID,
NULL AS TRANSACTION_REFERENCE,
NULL AS NEW_COST,
NULL AS FLOW_SCHEDULE,
NULL AS TRX_SOURCE_DELIVERY_ID,
NULL AS MOVE_TRANSACTION_ID,
NULL AS ACCT_PERIOD_ID,
NULL AS TRANSACTION_MODE,
NULL AS SHIPMENT_NUMBER,
NULL AS TRANSACTION_DATE,
NULL AS VENDOR_LOT_NUMBER,
NULL AS FREIGHT_CODE,
NULL AS TRANSFER_COST,
NULL AS ATTRIBUTE9,
NULL AS PRIMARY_QUANTITY,
NULL AS FINAL_COMPLETION_FLAG,
NULL AS TO_TASK_ID,
NULL AS TRANSACTION_COST,
NULL AS FOB_POINT,
NULL AS REVISION,
NULL AS SUBINVENTORY_CODE,
NULL AS ATTRIBUTE13,
NULL AS LOGICAL_TRANSACTIONS_CREATED,
NULL AS _FIVETRAN_DELETED,
NULL AS CURRENCY_CONVERSION_RATE,
NULL AS QUANTITY_ADJUSTED,
NULL AS PUT_AWAY_STRATEGY_ID,
NULL AS ENCUMBRANCE_AMOUNT,
NULL AS SOURCE_PROJECT_ID,
NULL AS TRANSACTION_GROUP_SEQ,
NULL AS TASK_GROUP_ID,
NULL AS MATERIAL_EXPENSE_ACCOUNT,
NULL AS TRANSACTION_SOURCE_NAME,
NULL AS XML_DOCUMENT_ID,
NULL AS TRANSFER_PERCENTAGE,
NULL AS TRANSACTION_GROUP_ID,
NULL AS ATTRIBUTE14,
NULL AS ATTRIBUTE8,
NULL AS PROGRAM_UPDATE_DATE,
NULL AS MOVEMENT_ID,
NULL AS PICK_SLIP_DATE,
NULL AS PHYSICAL_ADJUSTMENT_ID,
NULL AS TASK_ID,
NULL AS WAYBILL_AIRBILL,
NULL AS RMA_LINE_ID,
NULL AS SOURCE_TASK_ID,
NULL AS PROGRAM_ID,
NULL AS TRANSFER_COST_GROUP_ID,
NULL AS TRANSACTION_TYPE_ID,
NULL AS ATTRIBUTE5,
NULL AS COST_CATEGORY_ID,
NULL AS ATTRIBUTE_CATEGORY,
NULL AS TRANSFER_PRIOR_COSTED_QUANTITY,
NULL AS INTERCOMPANY_PRICING_OPTION,
NULL AS CURRENCY_CONVERSION_DATE,
NULL AS PROGRAM_APPLICATION_ID,
NULL AS ORG_COST_GROUP_ID,
NULL AS SECONDARY_TRANSACTION_QUANTITY,
NULL AS RESOURCE_ACCOUNT,
NULL AS TRX_FLOW_HEADER_ID,
NULL AS COSTED_FLAG,
NULL AS PM_COST_COLLECTOR_GROUP_ID,
'1900-01-01'::TIMESTAMP AS PSA_LOAD_DTS,
'N' AS PSA_DELETE_IND,
CONVERT_TIMEZONE('UTC','1900-01-01'::TIMESTAMP) AS LOAD_DTS,
DECODE(GR.VALUE, 0, 'GHOST RECORD-SYSTEM', -1, 'GHOST RECORD-nullkey-required', -2, 'GHOST RECORD-nullkey-optional') AS BKCC,
'USAZET.SNOWFLAKE.FBIN.DERIVED' AS REC_SRC,
''::BINARY AS HASHDIFF
FROM
TABLE(strtok_split_to_table('0|-1|-2', '|')) AS GR
{% endif %}
