---- SRC LAYER ----
WITH
SRC_a              as ( SELECT * FROM {{ ref('v_psa_stg_po_receipt__fib_ocf') }} as SRC 
                        {% if is_incremental() %}
                              where src.load_dts > (select dateadd('HOUR',-1,max(load_dts)) from {{ this }})
                            {% endif %}   )

/*
SRC_a              as ( SELECT * FROM STAGING.v_psa_stg_po_receipt__fib_ocf )
*/
---- LOGIC LAYER ----

, LOGIC_a as (
    SELECT
        LNK_PO_RECEIPT_HK
      , TRANSACTION_ID
      , COST_CATEGORY_ID
      , ATTRIBUTE_14
      , ATTRIBUTE_NUMBER_8
      , SHIPMENT_NUMBER
      , ATTRIBUTE_16
      , SHIPMENT_COSTED
      , ORGANIZATION_ID
      , ATTRIBUTE_NUMBER_9
      , PJC_USER_DEF_ATTRIBUTE_2
      , SOURCE_LOT_FLAG
      , ORIG_TRANSACTION_QUANTITY
      , INV_RESERVED_ATTRIBUTE_2
      , TRX_SOURCE_LINE_ID
      , ERROR_CODE
      , ORGANIZATION_TYPE
      , ORIGINAL_TRANSACTION_TEMP_ID
      , TRANSFER_PRIOR_COSTED_QUANTITY
      , PJC_RESERVED_ATTRIBUTE_2
      , EMPLOYEE_CODE
      , CONSUMPTION_LINE_ID
      , ATTRIBUTE_DATE_5
      , OPERATION_TRANSACTION_ID
      , TO_PROJECT_ID
      , PJC_USER_DEF_ATTRIBUTE_8
      , TRANSFER_TASK_ID
      , PRIOR_COST
      , NUMBER_OF_CONTAINERS
      , PJC_BILLABLE_FLAG
      , TRX_FLOW_HEADER_ID
      , PRODUCT_FISC_CLASSIFICATION
      , REPAIR_TXN_CODE_ID
      , REVISION
      , LOCATION_TYPE
      , QUANTITY_ADJUSTED
      , SECONDARY_TRANSACTION_QUANTITY
      , ORIG_SUBINVENTORY_CODE
      , CREATED_BY
      , PJC_RESERVED_ATTRIBUTE_6
      , PERIODIC_PRIMARY_QUANTITY
      , SUBINVENTORY_CODE
      , PJC_RESERVED_ATTRIBUTE_10
      , ATTRIBUTE_DATE_1
      , PHYSICAL_ADJUSTMENT_ID
      , BUILD_BREAK_TO_UOM
      , TRANSFER_COST_GROUP_ID
      , TRANSFER_OWNING_TP_TYPE
      , ASSESSABLE_VALUE
      , TRANSFER_LOCATOR_ID
      , ATTRIBUTE_17
      , LAST_UPDATE_LOGIN
      , USER_DEFINED_FISC_CLASS
      , INTERCOMPANY_CURRENCY_CODE
      , PUT_AWAY_STRATEGY_ID
      , PJC_RESERVED_ATTRIBUTE_5
      , LOT_TXN_GROUP_NAME
      , TAX_INVOICE_NUMBER
      , PJC_FUNDING_ALLOCATION_ID
      , CONTENT_LPN_ID
      , CURRENCY_CODE
      , PJC_EXPENDITURE_TYPE_ID
      , PLANNING_TP_TYPE
      , ATTRIBUTE_NUMBER_2
      , JOB_DEFINITION_NAME
      , FINAL_DISCHARGE_LOCATION_ID
      , PICK_SLIP_DATE
      , FOB_POINT
      , ENCUMBRANCE_ACCOUNT
      , TRX_SOURCE_DELIVERY_ID
      , LAST_UPDATED_BY
      , PRODUCT_TYPE
      , TRANSFER_COST_DIST_ACCOUNT
      , TASK_GROUP_ID
      , WIP_SUPPLY_TYPE
      , INV_RESERVED_ATTRIBUTE_1
      , ATTRIBUTE_NUMBER_10
      , RESERVATION_ID
      , INVOICED_FLAG
      , TRANSACTION_COST
      , LOGICAL_TRANSACTIONS_CREATED
      , EXTERNAL_SYS_TXN_REFERENCE
      , DISTRIBUTION_ACCOUNT_ID
      , TRANSACTION_SOURCE_ID
      , ATTRIBUTE_13
      , INV_USER_DEF_ATTRIBUTE_10
      , RESOURCE_ACCOUNT
      , COSTED_FLAG
      , PM_COST_COLLECTOR_GROUP_ID
      , ENCUMBRANCE_AMOUNT
      , CONS_ERROR_TYPE_CODE
      , ATTRIBUTE_9
      , TRANSFER_TRANSACTION_ID
      , TRANSACTION_ACTION_ID
      , TRANSACTION_UOM
      , PJC_RESERVED_ATTRIBUTE_1
      , AGING_EXPIRATION_DATE
      , CURRENCY_CONVERSION_DATE
      , PJC_USER_DEF_ATTRIBUTE_7
      , USSGL_TRANSACTION_CODE
      , DOCUMENT_SUB_TYPE
      , PJC_EXPENDITURE_ITEM_DATE
      , ATTRIBUTE_NUMBER_1
      , INTRANSIT_ACCOUNT
      , ATTRIBUTE_TIMESTAMP_4
      , PJC_RESERVED_ATTRIBUTE_3
      , JOB_DEFINITION_PACKAGE
      , LOCATOR_ID
      , MOVE_TRANSACTION_ID
      , INV_USER_DEF_ATTRIBUTE_8
      , USE_CURRENT_COST_FLAG
      , ATTRIBUTE_12
      , LICENSE_PLATE_NUMBER
      , ORIGINAL_SHIPMENT_TXN_ID
      , PJC_CONTRACT_LINE_ID
      , ATTRIBUTE_DATE_4
      , COST_UPDATE_ID
      , SO_ISSUE_ACCOUNT_TYPE
      , MVT_STAT_STATUS
      , ATTRIBUTE_TIMESTAMP_2
      , OVERCOMPLETION_TRANSACTION_QTY
      , TRANSFER_ORGANIZATION_ID
      , PICK_SLIP_NUMBER
      , CURRENCY_CONVERSION_RATE
      , OBJECT_VERSION_NUMBER
      , TRANSACTION_MODE
      , ATTRIBUTE_19
      , TRANSFER_ORGANIZATION_TYPE
      , VARIANCE_AMOUNT
      , EXPENSE_ACCOUNT_ID
      , WAYBILL_AIRBILL
      , TRANSACTION_BATCH_SEQ
      , PRODUCT_CATEGORY
      , INV_USER_DEF_ATTRIBUTE_7
      , COMMON_ROUTING_SEQ_ID
      , ACTUAL_COST
      , OVERHEAD_ACCOUNT
      , CATEGORY_ID
      , LPN_ID
      , PJC_RESERVED_ATTRIBUTE_8
      , COMMON_BOM_SEQ_ID
      , ERROR_CONS_HEADER_ID
      , REPETITIVE_LINE_ID
      , PICK_SLIP_LINE_NUMBER
      , PJC_CONTEXT_CATEGORY
      , FLOW_SCHEDULE
      , TRANSACTION_SOURCE_NAME
      , TRANSACTION_QUANTITY
      , OWNING_TP_TYPE
      , ATTRIBUTE_TIMESTAMP_1
      , INV_USER_DEF_ATTRIBUTE_2
      , LOGICAL_TRANSACTION
      , ATTRIBUTE_7
      , ASSEMBLY_ASSET_ID
      , PJC_USER_DEF_ATTRIBUTE_5
      , TAX_CLASSIFICATION_CODE
      , PJC_USER_DEF_ATTRIBUTE_10
      , TRANSACTION_INTERFACE_LINE_NUM
      , PJC_TASK_ID
      , INTERCOMPANY_PRICING_OPTION
      , ASSEMBLY_SERIAL_NUMBER
      , XFR_OWNING_ORGANIZATION_ID
      , PJC_RESERVED_ATTRIBUTE_7
      , OVERCOMPLETION_PRIMARY_QTY
      , CONSUMPTION_UNIT_PRICE
      , TRANSACTION_BATCH_ID
      , REASON_ID
      , ATTRIBUTE_10
      , RECEIVING_DOCUMENT
      , INTERCOMPANY_COST
      , TRANSPORTATION_DIST_ACCOUNT
      , PJC_USER_DEF_ATTRIBUTE_9
      , INV_USER_DEF_ATTRIBUTE_6
      , SHIPMENT_LINE_NUMBER
      , TRANSACTION_GROUP_ID
      , PJC_USER_DEF_ATTRIBUTE_1
      , TRANSACTION_SOURCE_TYPE_ID
      , COUNTRY_OF_ORIGIN_CODE
      , SHIP_TO_LOCATION_ID
      , CONSUMPTION_TAX_EXC_UNIT_PRICE
      , PARENT_ID
      , MATERIAL_ACCOUNT
      , RCV_TRANSACTION_ID
      , OPERATION_SEQ_NUM
      , ORIG_LOT_NUMBER
      , ATTRIBUTE_NUMBER_6
      , ATTRIBUTE_DATE_2
      , CYCLE_COUNT_ID
      , ORG_COST_GROUP_ID
      , INV_USER_DEF_ATTRIBUTE_4
      , FINAL_COMPLETION_FLAG
      , MOVE_ORDER_LINE_ID
      , OPERATION_SEQ_NUMBER_ID
      , TRANSPORTATION_COST
      , E_RECORD_ID
      , IS_EVENT_PUBLISHED
      , PRIOR_COSTED_QUANTITY
      , SHORTAGE_PROCESS_CODE
      , TRANSFER_SUBINVENTORY
      , ATTRIBUTE_6
      , TO_TASK_ID
      , ATTRIBUTE_NUMBER_3
      , REQUEST_ID
      , ATTRIBUTE_CATEGORY
      , ATTRIBUTE_TIMESTAMP_3
      , SHIP_FROM_LOCATION_ID
      , REQUESTER_ID
      , ATTRIBUTE_2
      , SOURCE_CODE
      , MASTER_SCHEDULE_UPDATE_CODE
      , EXEMPT_CERTIFICATE_NUMBER
      , ATTRIBUTE_1
      , PERCENTAGE_CHANGE
      , PICK_STRATEGY_ID
      , ATTRIBUTE_5
      , PJC_PROJECT_ID
      , CREATION_DATE
      , DEPARTMENT_CODE
      , INV_USER_DEF_ATTRIBUTE_3
      , PJC_USER_DEF_ATTRIBUTE_3
      , CURRENCY_CONVERSION_TYPE
      , ALM_INTERFACE_ERROR_CODE
      , CSE_INTERFACE_STATUS_CODE
      , PJC_CAPITALIZABLE_FLAG
      , TRANSFER_COST
      , TO_GRADE_CODE
      , MOVEMENT_ID
      , QA_COLLECTION_ID
      , PLANNING_ORGANIZATION_ID
      , ERROR_EXPLANATION
      , COMPLETION_TRANSACTION_ID
      , ATTRIBUTE_4
      , SOURCE_LINE_ID
      , PJC_RESERVED_ATTRIBUTE_4
      , TRANSFER_PRICE
      , MANUAL_RECEIPT_EXPENSE
      , PJC_ORGANIZATION_ID
      , TRANSFER_PLANNING_TP_TYPE
      , CONSIGNMENT_SOURCE_TXN_ID
      , AGING_ONSET_DATE
      , PJC_USER_DEF_ATTRIBUTE_4
      , INV_USER_DEF_ATTRIBUTE_1
      , ATTRIBUTE_18
      , WO_EXT_SYS_GROUP_ID
      , ATTRIBUTE_20
      , ATTRIBUTE_11
      , ALM_INTERFACE_STATUS
      , OUTSIDE_PROCESSING_ACCOUNT
      , DEFAULT_TAXATION_COUNTRY
      , TASK_ID
      , INTENDED_USE_CLASSIF_ID
      , ATTRIBUTE_8
      , FIRST_PTY_REG_ID
      , EXEMPT_REASON_CODE
      , TRANSACTION_SET_ID
      , INVENTORY_ITEM_ID
      , AVAIL_XFER_TO_CONSIGNED_QTY
      , SECONDARY_UOM_CODE
      , VENDOR_LOT_NUMBER
      , FROM_PROJECT_ID
      , ATTRIBUTE_DATE_3
      , PICKING_LINE_ID
      , TRANSFER_PERCENTAGE
      , XFR_PLANNING_ORGANIZATION_ID
      , CONS_ERROR_ACTION_CODE
      , NEW_COST
      , TRANSACTION_TYPE_ID
      , COST_GROUP_ID
      , TRX_BUSINESS_CATEGORY
      , DEPARTMENT_ID
      , OWNING_ORGANIZATION_ID
      , ATTRIBUTE_3
      , LOAD_REQUEST_ID
      , RMA_LINE_ID
      , TRANSFER_LPN_ID
      , INV_USER_DEF_ATTRIBUTE_5
      , TRANSACTION_DATE
      , TAX_INVOICE_DATE
      , PJC_WORK_TYPE_ID
      , ATTRIBUTE_NUMBER_5
      , OPM_COSTED_FLAG
      , PM_COST_COLLECTED
      , VALUE_CHANGE
      , TRANSACTION_REFERENCE
      , PJC_RESERVED_ATTRIBUTE_9
      , PJC_CONTRACT_ID
      , INV_USER_DEF_ATTRIBUTE_9
      , INV_STRIPING_CATEGORY
      , FROM_GRADE_CODE
      , FROM_TASK_ID
      , ATTRIBUTE_15
      , LOGICAL_TRX_TYPE_CODE
      , OWNERSHIP_CHANGE_TXN_ID
      , PARENT_TRANSACTION_ID
      , ATTRIBUTE_NUMBER_7
      , LAST_UPDATE_DATE
      , ORIG_LOCATOR_ID
      , PROJECT_ID
      , PJC_USER_DEF_ATTRIBUTE_6
      , ACCT_PERIOD_ID
      , PUT_AWAY_RULE_ID
      , PRIMARY_QUANTITY
      , COST_TYPE_ID
      , DEPRECIABLE_FLAG
      , COGS_RECOGNITION_PERCENT
      , OVERCOMPLETION_TRANSACTION_ID
      , TRANSACTION_INTERFACE_ID
      , FREIGHT_CODE
      , MATERIAL_OVERHEAD_ACCOUNT
      , PICK_RULE_ID
      , ATTRIBUTE_NUMBER_4
      , EXTERNAL_SYSTEM_PACKING_UNIT
      , TRANSFER_PROJECT_ID
      , ATTRIBUTE_TIMESTAMP_5
      , THIRD_PTY_REG_ID
      , DEBRIEF_LINE_ID
      , ZONE_ID
      , SERVICE_WIP_FLAG
      , DELIVERY_CART_ID
      , MATERIAL_SEQ_NUMBER
      , _FIVETRAN_SYNCED
      , _FIVETRAN_DELETED
      , PSA_LOAD_DTS
      , PSA_DELETE_IND
      , LOAD_DTS
      , BKCC
      , REC_SRC
      , HASHDIFF
    FROM SRC_a
)
---- RENAME LAYER ----

, RENAME_a as (
    SELECT
        LNK_PO_RECEIPT_HK
      , TRANSACTION_ID
      , COST_CATEGORY_ID
      , ATTRIBUTE_14
      , ATTRIBUTE_NUMBER_8
      , SHIPMENT_NUMBER
      , ATTRIBUTE_16
      , SHIPMENT_COSTED
      , ORGANIZATION_ID
      , ATTRIBUTE_NUMBER_9
      , PJC_USER_DEF_ATTRIBUTE_2
      , SOURCE_LOT_FLAG
      , ORIG_TRANSACTION_QUANTITY
      , INV_RESERVED_ATTRIBUTE_2
      , TRX_SOURCE_LINE_ID
      , ERROR_CODE
      , ORGANIZATION_TYPE
      , ORIGINAL_TRANSACTION_TEMP_ID
      , TRANSFER_PRIOR_COSTED_QUANTITY
      , PJC_RESERVED_ATTRIBUTE_2
      , EMPLOYEE_CODE
      , CONSUMPTION_LINE_ID
      , ATTRIBUTE_DATE_5
      , OPERATION_TRANSACTION_ID
      , TO_PROJECT_ID
      , PJC_USER_DEF_ATTRIBUTE_8
      , TRANSFER_TASK_ID
      , PRIOR_COST
      , NUMBER_OF_CONTAINERS
      , PJC_BILLABLE_FLAG
      , TRX_FLOW_HEADER_ID
      , PRODUCT_FISC_CLASSIFICATION
      , REPAIR_TXN_CODE_ID
      , REVISION
      , LOCATION_TYPE
      , QUANTITY_ADJUSTED
      , SECONDARY_TRANSACTION_QUANTITY
      , ORIG_SUBINVENTORY_CODE
      , CREATED_BY
      , PJC_RESERVED_ATTRIBUTE_6
      , PERIODIC_PRIMARY_QUANTITY
      , SUBINVENTORY_CODE
      , PJC_RESERVED_ATTRIBUTE_10
      , ATTRIBUTE_DATE_1
      , PHYSICAL_ADJUSTMENT_ID
      , BUILD_BREAK_TO_UOM
      , TRANSFER_COST_GROUP_ID
      , TRANSFER_OWNING_TP_TYPE
      , ASSESSABLE_VALUE
      , TRANSFER_LOCATOR_ID
      , ATTRIBUTE_17
      , LAST_UPDATE_LOGIN
      , USER_DEFINED_FISC_CLASS
      , INTERCOMPANY_CURRENCY_CODE
      , PUT_AWAY_STRATEGY_ID
      , PJC_RESERVED_ATTRIBUTE_5
      , LOT_TXN_GROUP_NAME
      , TAX_INVOICE_NUMBER
      , PJC_FUNDING_ALLOCATION_ID
      , CONTENT_LPN_ID
      , CURRENCY_CODE
      , PJC_EXPENDITURE_TYPE_ID
      , PLANNING_TP_TYPE
      , ATTRIBUTE_NUMBER_2
      , JOB_DEFINITION_NAME
      , FINAL_DISCHARGE_LOCATION_ID
      , PICK_SLIP_DATE
      , FOB_POINT
      , ENCUMBRANCE_ACCOUNT
      , TRX_SOURCE_DELIVERY_ID
      , LAST_UPDATED_BY
      , PRODUCT_TYPE
      , TRANSFER_COST_DIST_ACCOUNT
      , TASK_GROUP_ID
      , WIP_SUPPLY_TYPE
      , INV_RESERVED_ATTRIBUTE_1
      , ATTRIBUTE_NUMBER_10
      , RESERVATION_ID
      , INVOICED_FLAG
      , TRANSACTION_COST
      , LOGICAL_TRANSACTIONS_CREATED
      , EXTERNAL_SYS_TXN_REFERENCE
      , DISTRIBUTION_ACCOUNT_ID
      , TRANSACTION_SOURCE_ID
      , ATTRIBUTE_13
      , INV_USER_DEF_ATTRIBUTE_10
      , RESOURCE_ACCOUNT
      , COSTED_FLAG
      , PM_COST_COLLECTOR_GROUP_ID
      , ENCUMBRANCE_AMOUNT
      , CONS_ERROR_TYPE_CODE
      , ATTRIBUTE_9
      , TRANSFER_TRANSACTION_ID
      , TRANSACTION_ACTION_ID
      , TRANSACTION_UOM
      , PJC_RESERVED_ATTRIBUTE_1
      , AGING_EXPIRATION_DATE
      , CURRENCY_CONVERSION_DATE
      , PJC_USER_DEF_ATTRIBUTE_7
      , USSGL_TRANSACTION_CODE
      , DOCUMENT_SUB_TYPE
      , PJC_EXPENDITURE_ITEM_DATE
      , ATTRIBUTE_NUMBER_1
      , INTRANSIT_ACCOUNT
      , ATTRIBUTE_TIMESTAMP_4
      , PJC_RESERVED_ATTRIBUTE_3
      , JOB_DEFINITION_PACKAGE
      , LOCATOR_ID
      , MOVE_TRANSACTION_ID
      , INV_USER_DEF_ATTRIBUTE_8
      , USE_CURRENT_COST_FLAG
      , ATTRIBUTE_12
      , LICENSE_PLATE_NUMBER
      , ORIGINAL_SHIPMENT_TXN_ID
      , PJC_CONTRACT_LINE_ID
      , ATTRIBUTE_DATE_4
      , COST_UPDATE_ID
      , SO_ISSUE_ACCOUNT_TYPE
      , MVT_STAT_STATUS
      , ATTRIBUTE_TIMESTAMP_2
      , OVERCOMPLETION_TRANSACTION_QTY
      , TRANSFER_ORGANIZATION_ID
      , PICK_SLIP_NUMBER
      , CURRENCY_CONVERSION_RATE
      , OBJECT_VERSION_NUMBER
      , TRANSACTION_MODE
      , ATTRIBUTE_19
      , TRANSFER_ORGANIZATION_TYPE
      , VARIANCE_AMOUNT
      , EXPENSE_ACCOUNT_ID
      , WAYBILL_AIRBILL
      , TRANSACTION_BATCH_SEQ
      , PRODUCT_CATEGORY
      , INV_USER_DEF_ATTRIBUTE_7
      , COMMON_ROUTING_SEQ_ID
      , ACTUAL_COST
      , OVERHEAD_ACCOUNT
      , CATEGORY_ID
      , LPN_ID
      , PJC_RESERVED_ATTRIBUTE_8
      , COMMON_BOM_SEQ_ID
      , ERROR_CONS_HEADER_ID
      , REPETITIVE_LINE_ID
      , PICK_SLIP_LINE_NUMBER
      , PJC_CONTEXT_CATEGORY
      , FLOW_SCHEDULE
      , TRANSACTION_SOURCE_NAME
      , TRANSACTION_QUANTITY
      , OWNING_TP_TYPE
      , ATTRIBUTE_TIMESTAMP_1
      , INV_USER_DEF_ATTRIBUTE_2
      , LOGICAL_TRANSACTION
      , ATTRIBUTE_7
      , ASSEMBLY_ASSET_ID
      , PJC_USER_DEF_ATTRIBUTE_5
      , TAX_CLASSIFICATION_CODE
      , PJC_USER_DEF_ATTRIBUTE_10
      , TRANSACTION_INTERFACE_LINE_NUM
      , PJC_TASK_ID
      , INTERCOMPANY_PRICING_OPTION
      , ASSEMBLY_SERIAL_NUMBER
      , XFR_OWNING_ORGANIZATION_ID
      , PJC_RESERVED_ATTRIBUTE_7
      , OVERCOMPLETION_PRIMARY_QTY
      , CONSUMPTION_UNIT_PRICE
      , TRANSACTION_BATCH_ID
      , REASON_ID
      , ATTRIBUTE_10
      , RECEIVING_DOCUMENT
      , INTERCOMPANY_COST
      , TRANSPORTATION_DIST_ACCOUNT
      , PJC_USER_DEF_ATTRIBUTE_9
      , INV_USER_DEF_ATTRIBUTE_6
      , SHIPMENT_LINE_NUMBER
      , TRANSACTION_GROUP_ID
      , PJC_USER_DEF_ATTRIBUTE_1
      , TRANSACTION_SOURCE_TYPE_ID
      , COUNTRY_OF_ORIGIN_CODE
      , SHIP_TO_LOCATION_ID
      , CONSUMPTION_TAX_EXC_UNIT_PRICE
      , PARENT_ID
      , MATERIAL_ACCOUNT
      , RCV_TRANSACTION_ID
      , OPERATION_SEQ_NUM
      , ORIG_LOT_NUMBER
      , ATTRIBUTE_NUMBER_6
      , ATTRIBUTE_DATE_2
      , CYCLE_COUNT_ID
      , ORG_COST_GROUP_ID
      , INV_USER_DEF_ATTRIBUTE_4
      , FINAL_COMPLETION_FLAG
      , MOVE_ORDER_LINE_ID
      , OPERATION_SEQ_NUMBER_ID
      , TRANSPORTATION_COST
      , E_RECORD_ID
      , IS_EVENT_PUBLISHED
      , PRIOR_COSTED_QUANTITY
      , SHORTAGE_PROCESS_CODE
      , TRANSFER_SUBINVENTORY
      , ATTRIBUTE_6
      , TO_TASK_ID
      , ATTRIBUTE_NUMBER_3
      , REQUEST_ID
      , ATTRIBUTE_CATEGORY
      , ATTRIBUTE_TIMESTAMP_3
      , SHIP_FROM_LOCATION_ID
      , REQUESTER_ID
      , ATTRIBUTE_2
      , SOURCE_CODE
      , MASTER_SCHEDULE_UPDATE_CODE
      , EXEMPT_CERTIFICATE_NUMBER
      , ATTRIBUTE_1
      , PERCENTAGE_CHANGE
      , PICK_STRATEGY_ID
      , ATTRIBUTE_5
      , PJC_PROJECT_ID
      , CREATION_DATE
      , DEPARTMENT_CODE
      , INV_USER_DEF_ATTRIBUTE_3
      , PJC_USER_DEF_ATTRIBUTE_3
      , CURRENCY_CONVERSION_TYPE
      , ALM_INTERFACE_ERROR_CODE
      , CSE_INTERFACE_STATUS_CODE
      , PJC_CAPITALIZABLE_FLAG
      , TRANSFER_COST
      , TO_GRADE_CODE
      , MOVEMENT_ID
      , QA_COLLECTION_ID
      , PLANNING_ORGANIZATION_ID
      , ERROR_EXPLANATION
      , COMPLETION_TRANSACTION_ID
      , ATTRIBUTE_4
      , SOURCE_LINE_ID
      , PJC_RESERVED_ATTRIBUTE_4
      , TRANSFER_PRICE
      , MANUAL_RECEIPT_EXPENSE
      , PJC_ORGANIZATION_ID
      , TRANSFER_PLANNING_TP_TYPE
      , CONSIGNMENT_SOURCE_TXN_ID
      , AGING_ONSET_DATE
      , PJC_USER_DEF_ATTRIBUTE_4
      , INV_USER_DEF_ATTRIBUTE_1
      , ATTRIBUTE_18
      , WO_EXT_SYS_GROUP_ID
      , ATTRIBUTE_20
      , ATTRIBUTE_11
      , ALM_INTERFACE_STATUS
      , OUTSIDE_PROCESSING_ACCOUNT
      , DEFAULT_TAXATION_COUNTRY
      , TASK_ID
      , INTENDED_USE_CLASSIF_ID
      , ATTRIBUTE_8
      , FIRST_PTY_REG_ID
      , EXEMPT_REASON_CODE
      , TRANSACTION_SET_ID
      , INVENTORY_ITEM_ID
      , AVAIL_XFER_TO_CONSIGNED_QTY
      , SECONDARY_UOM_CODE
      , VENDOR_LOT_NUMBER
      , FROM_PROJECT_ID
      , ATTRIBUTE_DATE_3
      , PICKING_LINE_ID
      , TRANSFER_PERCENTAGE
      , XFR_PLANNING_ORGANIZATION_ID
      , CONS_ERROR_ACTION_CODE
      , NEW_COST
      , TRANSACTION_TYPE_ID
      , COST_GROUP_ID
      , TRX_BUSINESS_CATEGORY
      , DEPARTMENT_ID
      , OWNING_ORGANIZATION_ID
      , ATTRIBUTE_3
      , LOAD_REQUEST_ID
      , RMA_LINE_ID
      , TRANSFER_LPN_ID
      , INV_USER_DEF_ATTRIBUTE_5
      , TRANSACTION_DATE
      , TAX_INVOICE_DATE
      , PJC_WORK_TYPE_ID
      , ATTRIBUTE_NUMBER_5
      , OPM_COSTED_FLAG
      , PM_COST_COLLECTED
      , VALUE_CHANGE
      , TRANSACTION_REFERENCE
      , PJC_RESERVED_ATTRIBUTE_9
      , PJC_CONTRACT_ID
      , INV_USER_DEF_ATTRIBUTE_9
      , INV_STRIPING_CATEGORY
      , FROM_GRADE_CODE
      , FROM_TASK_ID
      , ATTRIBUTE_15
      , LOGICAL_TRX_TYPE_CODE
      , OWNERSHIP_CHANGE_TXN_ID
      , PARENT_TRANSACTION_ID
      , ATTRIBUTE_NUMBER_7
      , LAST_UPDATE_DATE
      , ORIG_LOCATOR_ID
      , PROJECT_ID
      , PJC_USER_DEF_ATTRIBUTE_6
      , ACCT_PERIOD_ID
      , PUT_AWAY_RULE_ID
      , PRIMARY_QUANTITY
      , COST_TYPE_ID
      , DEPRECIABLE_FLAG
      , COGS_RECOGNITION_PERCENT
      , OVERCOMPLETION_TRANSACTION_ID
      , TRANSACTION_INTERFACE_ID
      , FREIGHT_CODE
      , MATERIAL_OVERHEAD_ACCOUNT
      , PICK_RULE_ID
      , ATTRIBUTE_NUMBER_4
      , EXTERNAL_SYSTEM_PACKING_UNIT
      , TRANSFER_PROJECT_ID
      , ATTRIBUTE_TIMESTAMP_5
      , THIRD_PTY_REG_ID
      , DEBRIEF_LINE_ID
      , ZONE_ID
      , SERVICE_WIP_FLAG
      , DELIVERY_CART_ID
      , MATERIAL_SEQ_NUMBER
      , _FIVETRAN_SYNCED
      , _FIVETRAN_DELETED
      , PSA_LOAD_DTS
      , PSA_DELETE_IND
      , LOAD_DTS
      , BKCC
      , REC_SRC
      , HASHDIFF
    FROM LOGIC_a
)
---- FILTER LAYER ----

, FILTER_a as (
    SELECT *
    FROM RENAME_a
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM FILTER_a
)

---- FINAL LAYER ----
SELECT
          LNK_PO_RECEIPT_HK
        , TRANSACTION_ID
        , COST_CATEGORY_ID
        , ATTRIBUTE_14
        , ATTRIBUTE_NUMBER_8
        , SHIPMENT_NUMBER
        , ATTRIBUTE_16
        , SHIPMENT_COSTED
        , ORGANIZATION_ID
        , ATTRIBUTE_NUMBER_9
        , PJC_USER_DEF_ATTRIBUTE_2
        , SOURCE_LOT_FLAG
        , ORIG_TRANSACTION_QUANTITY
        , INV_RESERVED_ATTRIBUTE_2
        , TRX_SOURCE_LINE_ID
        , ERROR_CODE
        , ORGANIZATION_TYPE
        , ORIGINAL_TRANSACTION_TEMP_ID
        , TRANSFER_PRIOR_COSTED_QUANTITY
        , PJC_RESERVED_ATTRIBUTE_2
        , EMPLOYEE_CODE
        , CONSUMPTION_LINE_ID
        , ATTRIBUTE_DATE_5
        , OPERATION_TRANSACTION_ID
        , TO_PROJECT_ID
        , PJC_USER_DEF_ATTRIBUTE_8
        , TRANSFER_TASK_ID
        , PRIOR_COST
        , NUMBER_OF_CONTAINERS
        , PJC_BILLABLE_FLAG
        , TRX_FLOW_HEADER_ID
        , PRODUCT_FISC_CLASSIFICATION
        , REPAIR_TXN_CODE_ID
        , REVISION
        , LOCATION_TYPE
        , QUANTITY_ADJUSTED
        , SECONDARY_TRANSACTION_QUANTITY
        , ORIG_SUBINVENTORY_CODE
        , CREATED_BY
        , PJC_RESERVED_ATTRIBUTE_6
        , PERIODIC_PRIMARY_QUANTITY
        , SUBINVENTORY_CODE
        , PJC_RESERVED_ATTRIBUTE_10
        , ATTRIBUTE_DATE_1
        , PHYSICAL_ADJUSTMENT_ID
        , BUILD_BREAK_TO_UOM
        , TRANSFER_COST_GROUP_ID
        , TRANSFER_OWNING_TP_TYPE
        , ASSESSABLE_VALUE
        , TRANSFER_LOCATOR_ID
        , ATTRIBUTE_17
        , LAST_UPDATE_LOGIN
        , USER_DEFINED_FISC_CLASS
        , INTERCOMPANY_CURRENCY_CODE
        , PUT_AWAY_STRATEGY_ID
        , PJC_RESERVED_ATTRIBUTE_5
        , LOT_TXN_GROUP_NAME
        , TAX_INVOICE_NUMBER
        , PJC_FUNDING_ALLOCATION_ID
        , CONTENT_LPN_ID
        , CURRENCY_CODE
        , PJC_EXPENDITURE_TYPE_ID
        , PLANNING_TP_TYPE
        , ATTRIBUTE_NUMBER_2
        , JOB_DEFINITION_NAME
        , FINAL_DISCHARGE_LOCATION_ID
        , PICK_SLIP_DATE
        , FOB_POINT
        , ENCUMBRANCE_ACCOUNT
        , TRX_SOURCE_DELIVERY_ID
        , LAST_UPDATED_BY
        , PRODUCT_TYPE
        , TRANSFER_COST_DIST_ACCOUNT
        , TASK_GROUP_ID
        , WIP_SUPPLY_TYPE
        , INV_RESERVED_ATTRIBUTE_1
        , ATTRIBUTE_NUMBER_10
        , RESERVATION_ID
        , INVOICED_FLAG
        , TRANSACTION_COST
        , LOGICAL_TRANSACTIONS_CREATED
        , EXTERNAL_SYS_TXN_REFERENCE
        , DISTRIBUTION_ACCOUNT_ID
        , TRANSACTION_SOURCE_ID
        , ATTRIBUTE_13
        , INV_USER_DEF_ATTRIBUTE_10
        , RESOURCE_ACCOUNT
        , COSTED_FLAG
        , PM_COST_COLLECTOR_GROUP_ID
        , ENCUMBRANCE_AMOUNT
        , CONS_ERROR_TYPE_CODE
        , ATTRIBUTE_9
        , TRANSFER_TRANSACTION_ID
        , TRANSACTION_ACTION_ID
        , TRANSACTION_UOM
        , PJC_RESERVED_ATTRIBUTE_1
        , AGING_EXPIRATION_DATE
        , CURRENCY_CONVERSION_DATE
        , PJC_USER_DEF_ATTRIBUTE_7
        , USSGL_TRANSACTION_CODE
        , DOCUMENT_SUB_TYPE
        , PJC_EXPENDITURE_ITEM_DATE
        , ATTRIBUTE_NUMBER_1
        , INTRANSIT_ACCOUNT
        , ATTRIBUTE_TIMESTAMP_4
        , PJC_RESERVED_ATTRIBUTE_3
        , JOB_DEFINITION_PACKAGE
        , LOCATOR_ID
        , MOVE_TRANSACTION_ID
        , INV_USER_DEF_ATTRIBUTE_8
        , USE_CURRENT_COST_FLAG
        , ATTRIBUTE_12
        , LICENSE_PLATE_NUMBER
        , ORIGINAL_SHIPMENT_TXN_ID
        , PJC_CONTRACT_LINE_ID
        , ATTRIBUTE_DATE_4
        , COST_UPDATE_ID
        , SO_ISSUE_ACCOUNT_TYPE
        , MVT_STAT_STATUS
        , ATTRIBUTE_TIMESTAMP_2
        , OVERCOMPLETION_TRANSACTION_QTY
        , TRANSFER_ORGANIZATION_ID
        , PICK_SLIP_NUMBER
        , CURRENCY_CONVERSION_RATE
        , OBJECT_VERSION_NUMBER
        , TRANSACTION_MODE
        , ATTRIBUTE_19
        , TRANSFER_ORGANIZATION_TYPE
        , VARIANCE_AMOUNT
        , EXPENSE_ACCOUNT_ID
        , WAYBILL_AIRBILL
        , TRANSACTION_BATCH_SEQ
        , PRODUCT_CATEGORY
        , INV_USER_DEF_ATTRIBUTE_7
        , COMMON_ROUTING_SEQ_ID
        , ACTUAL_COST
        , OVERHEAD_ACCOUNT
        , CATEGORY_ID
        , LPN_ID
        , PJC_RESERVED_ATTRIBUTE_8
        , COMMON_BOM_SEQ_ID
        , ERROR_CONS_HEADER_ID
        , REPETITIVE_LINE_ID
        , PICK_SLIP_LINE_NUMBER
        , PJC_CONTEXT_CATEGORY
        , FLOW_SCHEDULE
        , TRANSACTION_SOURCE_NAME
        , TRANSACTION_QUANTITY
        , OWNING_TP_TYPE
        , ATTRIBUTE_TIMESTAMP_1
        , INV_USER_DEF_ATTRIBUTE_2
        , LOGICAL_TRANSACTION
        , ATTRIBUTE_7
        , ASSEMBLY_ASSET_ID
        , PJC_USER_DEF_ATTRIBUTE_5
        , TAX_CLASSIFICATION_CODE
        , PJC_USER_DEF_ATTRIBUTE_10
        , TRANSACTION_INTERFACE_LINE_NUM
        , PJC_TASK_ID
        , INTERCOMPANY_PRICING_OPTION
        , ASSEMBLY_SERIAL_NUMBER
        , XFR_OWNING_ORGANIZATION_ID
        , PJC_RESERVED_ATTRIBUTE_7
        , OVERCOMPLETION_PRIMARY_QTY
        , CONSUMPTION_UNIT_PRICE
        , TRANSACTION_BATCH_ID
        , REASON_ID
        , ATTRIBUTE_10
        , RECEIVING_DOCUMENT
        , INTERCOMPANY_COST
        , TRANSPORTATION_DIST_ACCOUNT
        , PJC_USER_DEF_ATTRIBUTE_9
        , INV_USER_DEF_ATTRIBUTE_6
        , SHIPMENT_LINE_NUMBER
        , TRANSACTION_GROUP_ID
        , PJC_USER_DEF_ATTRIBUTE_1
        , TRANSACTION_SOURCE_TYPE_ID
        , COUNTRY_OF_ORIGIN_CODE
        , SHIP_TO_LOCATION_ID
        , CONSUMPTION_TAX_EXC_UNIT_PRICE
        , PARENT_ID
        , MATERIAL_ACCOUNT
        , RCV_TRANSACTION_ID
        , OPERATION_SEQ_NUM
        , ORIG_LOT_NUMBER
        , ATTRIBUTE_NUMBER_6
        , ATTRIBUTE_DATE_2
        , CYCLE_COUNT_ID
        , ORG_COST_GROUP_ID
        , INV_USER_DEF_ATTRIBUTE_4
        , FINAL_COMPLETION_FLAG
        , MOVE_ORDER_LINE_ID
        , OPERATION_SEQ_NUMBER_ID
        , TRANSPORTATION_COST
        , E_RECORD_ID
        , IS_EVENT_PUBLISHED
        , PRIOR_COSTED_QUANTITY
        , SHORTAGE_PROCESS_CODE
        , TRANSFER_SUBINVENTORY
        , ATTRIBUTE_6
        , TO_TASK_ID
        , ATTRIBUTE_NUMBER_3
        , REQUEST_ID
        , ATTRIBUTE_CATEGORY
        , ATTRIBUTE_TIMESTAMP_3
        , SHIP_FROM_LOCATION_ID
        , REQUESTER_ID
        , ATTRIBUTE_2
        , SOURCE_CODE
        , MASTER_SCHEDULE_UPDATE_CODE
        , EXEMPT_CERTIFICATE_NUMBER
        , ATTRIBUTE_1
        , PERCENTAGE_CHANGE
        , PICK_STRATEGY_ID
        , ATTRIBUTE_5
        , PJC_PROJECT_ID
        , CREATION_DATE
        , DEPARTMENT_CODE
        , INV_USER_DEF_ATTRIBUTE_3
        , PJC_USER_DEF_ATTRIBUTE_3
        , CURRENCY_CONVERSION_TYPE
        , ALM_INTERFACE_ERROR_CODE
        , CSE_INTERFACE_STATUS_CODE
        , PJC_CAPITALIZABLE_FLAG
        , TRANSFER_COST
        , TO_GRADE_CODE
        , MOVEMENT_ID
        , QA_COLLECTION_ID
        , PLANNING_ORGANIZATION_ID
        , ERROR_EXPLANATION
        , COMPLETION_TRANSACTION_ID
        , ATTRIBUTE_4
        , SOURCE_LINE_ID
        , PJC_RESERVED_ATTRIBUTE_4
        , TRANSFER_PRICE
        , MANUAL_RECEIPT_EXPENSE
        , PJC_ORGANIZATION_ID
        , TRANSFER_PLANNING_TP_TYPE
        , CONSIGNMENT_SOURCE_TXN_ID
        , AGING_ONSET_DATE
        , PJC_USER_DEF_ATTRIBUTE_4
        , INV_USER_DEF_ATTRIBUTE_1
        , ATTRIBUTE_18
        , WO_EXT_SYS_GROUP_ID
        , ATTRIBUTE_20
        , ATTRIBUTE_11
        , ALM_INTERFACE_STATUS
        , OUTSIDE_PROCESSING_ACCOUNT
        , DEFAULT_TAXATION_COUNTRY
        , TASK_ID
        , INTENDED_USE_CLASSIF_ID
        , ATTRIBUTE_8
        , FIRST_PTY_REG_ID
        , EXEMPT_REASON_CODE
        , TRANSACTION_SET_ID
        , INVENTORY_ITEM_ID
        , AVAIL_XFER_TO_CONSIGNED_QTY
        , SECONDARY_UOM_CODE
        , VENDOR_LOT_NUMBER
        , FROM_PROJECT_ID
        , ATTRIBUTE_DATE_3
        , PICKING_LINE_ID
        , TRANSFER_PERCENTAGE
        , XFR_PLANNING_ORGANIZATION_ID
        , CONS_ERROR_ACTION_CODE
        , NEW_COST
        , TRANSACTION_TYPE_ID
        , COST_GROUP_ID
        , TRX_BUSINESS_CATEGORY
        , DEPARTMENT_ID
        , OWNING_ORGANIZATION_ID
        , ATTRIBUTE_3
        , LOAD_REQUEST_ID
        , RMA_LINE_ID
        , TRANSFER_LPN_ID
        , INV_USER_DEF_ATTRIBUTE_5
        , TRANSACTION_DATE
        , TAX_INVOICE_DATE
        , PJC_WORK_TYPE_ID
        , ATTRIBUTE_NUMBER_5
        , OPM_COSTED_FLAG
        , PM_COST_COLLECTED
        , VALUE_CHANGE
        , TRANSACTION_REFERENCE
        , PJC_RESERVED_ATTRIBUTE_9
        , PJC_CONTRACT_ID
        , INV_USER_DEF_ATTRIBUTE_9
        , INV_STRIPING_CATEGORY
        , FROM_GRADE_CODE
        , FROM_TASK_ID
        , ATTRIBUTE_15
        , LOGICAL_TRX_TYPE_CODE
        , OWNERSHIP_CHANGE_TXN_ID
        , PARENT_TRANSACTION_ID
        , ATTRIBUTE_NUMBER_7
        , LAST_UPDATE_DATE
        , ORIG_LOCATOR_ID
        , PROJECT_ID
        , PJC_USER_DEF_ATTRIBUTE_6
        , ACCT_PERIOD_ID
        , PUT_AWAY_RULE_ID
        , PRIMARY_QUANTITY
        , COST_TYPE_ID
        , DEPRECIABLE_FLAG
        , COGS_RECOGNITION_PERCENT
        , OVERCOMPLETION_TRANSACTION_ID
        , TRANSACTION_INTERFACE_ID
        , FREIGHT_CODE
        , MATERIAL_OVERHEAD_ACCOUNT
        , PICK_RULE_ID
        , ATTRIBUTE_NUMBER_4
        , EXTERNAL_SYSTEM_PACKING_UNIT
        , TRANSFER_PROJECT_ID
        , ATTRIBUTE_TIMESTAMP_5
        , THIRD_PTY_REG_ID
        , DEBRIEF_LINE_ID
        , ZONE_ID
        , SERVICE_WIP_FLAG
        , DELIVERY_CART_ID
        , MATERIAL_SEQ_NUMBER
        , _FIVETRAN_SYNCED
        , _FIVETRAN_DELETED
        , PSA_LOAD_DTS
        , PSA_DELETE_IND
        , LOAD_DTS
        , BKCC
        , REC_SRC
        , HASHDIFF
FROM JOIN_RESULT
{% if is_incremental() %}
WHERE NOT EXISTS (
    SELECT 1 
    FROM {{ this }} existing
    WHERE existing.LNK_PO_RECEIPT_HK = JOIN_RESULT.LNK_PO_RECEIPT_HK
    AND existing.HASHDIFF = JOIN_RESULT.HASHDIFF
)
{% endif %}
{% if not is_incremental() %}

/* The following qualifier is implemented to prevent multiple loads of touched records during the initial build, such as multiple rows per HK and hashdiff. */
qualify 1 = row_number() over (partition by LNK_PO_RECEIPT_HK, HASHDIFF order by PSA_LOAD_DTS)

union all
SELECT 
MD5_BINARY(GR.VALUE) AS LNK_PO_RECEIPT_HK,
GR.VALUE::number AS TRANSACTION_ID,
NULL AS COST_CATEGORY_ID,
NULL AS ATTRIBUTE_14,
NULL AS ATTRIBUTE_NUMBER_8,
NULL AS SHIPMENT_NUMBER,
NULL AS ATTRIBUTE_16,
NULL AS SHIPMENT_COSTED,
NULL AS ORGANIZATION_ID,
NULL AS ATTRIBUTE_NUMBER_9,
NULL AS PJC_USER_DEF_ATTRIBUTE_2,
NULL AS SOURCE_LOT_FLAG,
NULL AS ORIG_TRANSACTION_QUANTITY,
NULL AS INV_RESERVED_ATTRIBUTE_2,
NULL AS TRX_SOURCE_LINE_ID,
NULL AS ERROR_CODE,
NULL AS ORGANIZATION_TYPE,
NULL AS ORIGINAL_TRANSACTION_TEMP_ID,
NULL AS TRANSFER_PRIOR_COSTED_QUANTITY,
NULL AS PJC_RESERVED_ATTRIBUTE_2,
NULL AS EMPLOYEE_CODE,
NULL AS CONSUMPTION_LINE_ID,
NULL AS ATTRIBUTE_DATE_5,
NULL AS OPERATION_TRANSACTION_ID,
NULL AS TO_PROJECT_ID,
NULL AS PJC_USER_DEF_ATTRIBUTE_8,
NULL AS TRANSFER_TASK_ID,
NULL AS PRIOR_COST,
NULL AS NUMBER_OF_CONTAINERS,
NULL AS PJC_BILLABLE_FLAG,
NULL AS TRX_FLOW_HEADER_ID,
NULL AS PRODUCT_FISC_CLASSIFICATION,
NULL AS REPAIR_TXN_CODE_ID,
NULL AS REVISION,
NULL AS LOCATION_TYPE,
NULL AS QUANTITY_ADJUSTED,
NULL AS SECONDARY_TRANSACTION_QUANTITY,
NULL AS ORIG_SUBINVENTORY_CODE,
NULL AS CREATED_BY,
NULL AS PJC_RESERVED_ATTRIBUTE_6,
NULL AS PERIODIC_PRIMARY_QUANTITY,
NULL AS SUBINVENTORY_CODE,
NULL AS PJC_RESERVED_ATTRIBUTE_10,
NULL AS ATTRIBUTE_DATE_1,
NULL AS PHYSICAL_ADJUSTMENT_ID,
NULL AS BUILD_BREAK_TO_UOM,
NULL AS TRANSFER_COST_GROUP_ID,
NULL AS TRANSFER_OWNING_TP_TYPE,
NULL AS ASSESSABLE_VALUE,
NULL AS TRANSFER_LOCATOR_ID,
NULL AS ATTRIBUTE_17,
NULL AS LAST_UPDATE_LOGIN,
NULL AS USER_DEFINED_FISC_CLASS,
NULL AS INTERCOMPANY_CURRENCY_CODE,
NULL AS PUT_AWAY_STRATEGY_ID,
NULL AS PJC_RESERVED_ATTRIBUTE_5,
NULL AS LOT_TXN_GROUP_NAME,
NULL AS TAX_INVOICE_NUMBER,
NULL AS PJC_FUNDING_ALLOCATION_ID,
NULL AS CONTENT_LPN_ID,
NULL AS CURRENCY_CODE,
NULL AS PJC_EXPENDITURE_TYPE_ID,
NULL AS PLANNING_TP_TYPE,
NULL AS ATTRIBUTE_NUMBER_2,
NULL AS JOB_DEFINITION_NAME,
NULL AS FINAL_DISCHARGE_LOCATION_ID,
NULL AS PICK_SLIP_DATE,
NULL AS FOB_POINT,
NULL AS ENCUMBRANCE_ACCOUNT,
NULL AS TRX_SOURCE_DELIVERY_ID,
NULL AS LAST_UPDATED_BY,
NULL AS PRODUCT_TYPE,
NULL AS TRANSFER_COST_DIST_ACCOUNT,
NULL AS TASK_GROUP_ID,
NULL AS WIP_SUPPLY_TYPE,
NULL AS INV_RESERVED_ATTRIBUTE_1,
NULL AS ATTRIBUTE_NUMBER_10,
NULL AS RESERVATION_ID,
NULL AS INVOICED_FLAG,
NULL AS TRANSACTION_COST,
NULL AS LOGICAL_TRANSACTIONS_CREATED,
NULL AS EXTERNAL_SYS_TXN_REFERENCE,
NULL AS DISTRIBUTION_ACCOUNT_ID,
NULL AS TRANSACTION_SOURCE_ID,
NULL AS ATTRIBUTE_13,
NULL AS INV_USER_DEF_ATTRIBUTE_10,
NULL AS RESOURCE_ACCOUNT,
NULL AS COSTED_FLAG,
NULL AS PM_COST_COLLECTOR_GROUP_ID,
NULL AS ENCUMBRANCE_AMOUNT,
NULL AS CONS_ERROR_TYPE_CODE,
NULL AS ATTRIBUTE_9,
NULL AS TRANSFER_TRANSACTION_ID,
NULL AS TRANSACTION_ACTION_ID,
NULL AS TRANSACTION_UOM,
NULL AS PJC_RESERVED_ATTRIBUTE_1,
NULL AS AGING_EXPIRATION_DATE,
NULL AS CURRENCY_CONVERSION_DATE,
NULL AS PJC_USER_DEF_ATTRIBUTE_7,
NULL AS USSGL_TRANSACTION_CODE,
NULL AS DOCUMENT_SUB_TYPE,
NULL AS PJC_EXPENDITURE_ITEM_DATE,
NULL AS ATTRIBUTE_NUMBER_1,
NULL AS INTRANSIT_ACCOUNT,
NULL AS ATTRIBUTE_TIMESTAMP_4,
NULL AS PJC_RESERVED_ATTRIBUTE_3,
NULL AS JOB_DEFINITION_PACKAGE,
NULL AS LOCATOR_ID,
NULL AS MOVE_TRANSACTION_ID,
NULL AS INV_USER_DEF_ATTRIBUTE_8,
NULL AS USE_CURRENT_COST_FLAG,
NULL AS ATTRIBUTE_12,
NULL AS LICENSE_PLATE_NUMBER,
NULL AS ORIGINAL_SHIPMENT_TXN_ID,
NULL AS PJC_CONTRACT_LINE_ID,
NULL AS ATTRIBUTE_DATE_4,
NULL AS COST_UPDATE_ID,
NULL AS SO_ISSUE_ACCOUNT_TYPE,
NULL AS MVT_STAT_STATUS,
NULL AS ATTRIBUTE_TIMESTAMP_2,
NULL AS OVERCOMPLETION_TRANSACTION_QTY,
NULL AS TRANSFER_ORGANIZATION_ID,
NULL AS PICK_SLIP_NUMBER,
NULL AS CURRENCY_CONVERSION_RATE,
NULL AS OBJECT_VERSION_NUMBER,
NULL AS TRANSACTION_MODE,
NULL AS ATTRIBUTE_19,
NULL AS TRANSFER_ORGANIZATION_TYPE,
NULL AS VARIANCE_AMOUNT,
NULL AS EXPENSE_ACCOUNT_ID,
NULL AS WAYBILL_AIRBILL,
NULL AS TRANSACTION_BATCH_SEQ,
NULL AS PRODUCT_CATEGORY,
NULL AS INV_USER_DEF_ATTRIBUTE_7,
NULL AS COMMON_ROUTING_SEQ_ID,
NULL AS ACTUAL_COST,
NULL AS OVERHEAD_ACCOUNT,
NULL AS CATEGORY_ID,
NULL AS LPN_ID,
NULL AS PJC_RESERVED_ATTRIBUTE_8,
NULL AS COMMON_BOM_SEQ_ID,
NULL AS ERROR_CONS_HEADER_ID,
NULL AS REPETITIVE_LINE_ID,
NULL AS PICK_SLIP_LINE_NUMBER,
NULL AS PJC_CONTEXT_CATEGORY,
NULL AS FLOW_SCHEDULE,
NULL AS TRANSACTION_SOURCE_NAME,
NULL AS TRANSACTION_QUANTITY,
NULL AS OWNING_TP_TYPE,
NULL AS ATTRIBUTE_TIMESTAMP_1,
NULL AS INV_USER_DEF_ATTRIBUTE_2,
NULL AS LOGICAL_TRANSACTION,
NULL AS ATTRIBUTE_7,
NULL AS ASSEMBLY_ASSET_ID,
NULL AS PJC_USER_DEF_ATTRIBUTE_5,
NULL AS TAX_CLASSIFICATION_CODE,
NULL AS PJC_USER_DEF_ATTRIBUTE_10,
NULL AS TRANSACTION_INTERFACE_LINE_NUM,
NULL AS PJC_TASK_ID,
NULL AS INTERCOMPANY_PRICING_OPTION,
NULL AS ASSEMBLY_SERIAL_NUMBER,
NULL AS XFR_OWNING_ORGANIZATION_ID,
NULL AS PJC_RESERVED_ATTRIBUTE_7,
NULL AS OVERCOMPLETION_PRIMARY_QTY,
NULL AS CONSUMPTION_UNIT_PRICE,
NULL AS TRANSACTION_BATCH_ID,
NULL AS REASON_ID,
NULL AS ATTRIBUTE_10,
NULL AS RECEIVING_DOCUMENT,
NULL AS INTERCOMPANY_COST,
NULL AS TRANSPORTATION_DIST_ACCOUNT,
NULL AS PJC_USER_DEF_ATTRIBUTE_9,
NULL AS INV_USER_DEF_ATTRIBUTE_6,
NULL AS SHIPMENT_LINE_NUMBER,
NULL AS TRANSACTION_GROUP_ID,
NULL AS PJC_USER_DEF_ATTRIBUTE_1,
NULL AS TRANSACTION_SOURCE_TYPE_ID,
NULL AS COUNTRY_OF_ORIGIN_CODE,
NULL AS SHIP_TO_LOCATION_ID,
NULL AS CONSUMPTION_TAX_EXC_UNIT_PRICE,
NULL AS PARENT_ID,
NULL AS MATERIAL_ACCOUNT,
NULL AS RCV_TRANSACTION_ID,
NULL AS OPERATION_SEQ_NUM,
NULL AS ORIG_LOT_NUMBER,
NULL AS ATTRIBUTE_NUMBER_6,
NULL AS ATTRIBUTE_DATE_2,
NULL AS CYCLE_COUNT_ID,
NULL AS ORG_COST_GROUP_ID,
NULL AS INV_USER_DEF_ATTRIBUTE_4,
NULL AS FINAL_COMPLETION_FLAG,
NULL AS MOVE_ORDER_LINE_ID,
NULL AS OPERATION_SEQ_NUMBER_ID,
NULL AS TRANSPORTATION_COST,
NULL AS E_RECORD_ID,
NULL AS IS_EVENT_PUBLISHED,
NULL AS PRIOR_COSTED_QUANTITY,
NULL AS SHORTAGE_PROCESS_CODE,
NULL AS TRANSFER_SUBINVENTORY,
NULL AS ATTRIBUTE_6,
NULL AS TO_TASK_ID,
NULL AS ATTRIBUTE_NUMBER_3,
NULL AS REQUEST_ID,
NULL AS ATTRIBUTE_CATEGORY,
NULL AS ATTRIBUTE_TIMESTAMP_3,
NULL AS SHIP_FROM_LOCATION_ID,
NULL AS REQUESTER_ID,
NULL AS ATTRIBUTE_2,
NULL AS SOURCE_CODE,
NULL AS MASTER_SCHEDULE_UPDATE_CODE,
NULL AS EXEMPT_CERTIFICATE_NUMBER,
NULL AS ATTRIBUTE_1,
NULL AS PERCENTAGE_CHANGE,
NULL AS PICK_STRATEGY_ID,
NULL AS ATTRIBUTE_5,
NULL AS PJC_PROJECT_ID,
NULL AS CREATION_DATE,
NULL AS DEPARTMENT_CODE,
NULL AS INV_USER_DEF_ATTRIBUTE_3,
NULL AS PJC_USER_DEF_ATTRIBUTE_3,
NULL AS CURRENCY_CONVERSION_TYPE,
NULL AS ALM_INTERFACE_ERROR_CODE,
NULL AS CSE_INTERFACE_STATUS_CODE,
NULL AS PJC_CAPITALIZABLE_FLAG,
NULL AS TRANSFER_COST,
NULL AS TO_GRADE_CODE,
NULL AS MOVEMENT_ID,
NULL AS QA_COLLECTION_ID,
NULL AS PLANNING_ORGANIZATION_ID,
NULL AS ERROR_EXPLANATION,
NULL AS COMPLETION_TRANSACTION_ID,
NULL AS ATTRIBUTE_4,
NULL AS SOURCE_LINE_ID,
NULL AS PJC_RESERVED_ATTRIBUTE_4,
NULL AS TRANSFER_PRICE,
NULL AS MANUAL_RECEIPT_EXPENSE,
NULL AS PJC_ORGANIZATION_ID,
NULL AS TRANSFER_PLANNING_TP_TYPE,
NULL AS CONSIGNMENT_SOURCE_TXN_ID,
NULL AS AGING_ONSET_DATE,
NULL AS PJC_USER_DEF_ATTRIBUTE_4,
NULL AS INV_USER_DEF_ATTRIBUTE_1,
NULL AS ATTRIBUTE_18,
NULL AS WO_EXT_SYS_GROUP_ID,
NULL AS ATTRIBUTE_20,
NULL AS ATTRIBUTE_11,
NULL AS ALM_INTERFACE_STATUS,
NULL AS OUTSIDE_PROCESSING_ACCOUNT,
NULL AS DEFAULT_TAXATION_COUNTRY,
NULL AS TASK_ID,
NULL AS INTENDED_USE_CLASSIF_ID,
NULL AS ATTRIBUTE_8,
NULL AS FIRST_PTY_REG_ID,
NULL AS EXEMPT_REASON_CODE,
NULL AS TRANSACTION_SET_ID,
NULL AS INVENTORY_ITEM_ID,
NULL AS AVAIL_XFER_TO_CONSIGNED_QTY,
NULL AS SECONDARY_UOM_CODE,
NULL AS VENDOR_LOT_NUMBER,
NULL AS FROM_PROJECT_ID,
NULL AS ATTRIBUTE_DATE_3,
NULL AS PICKING_LINE_ID,
NULL AS TRANSFER_PERCENTAGE,
NULL AS XFR_PLANNING_ORGANIZATION_ID,
NULL AS CONS_ERROR_ACTION_CODE,
NULL AS NEW_COST,
NULL AS TRANSACTION_TYPE_ID,
NULL AS COST_GROUP_ID,
NULL AS TRX_BUSINESS_CATEGORY,
NULL AS DEPARTMENT_ID,
NULL AS OWNING_ORGANIZATION_ID,
NULL AS ATTRIBUTE_3,
NULL AS LOAD_REQUEST_ID,
NULL AS RMA_LINE_ID,
NULL AS TRANSFER_LPN_ID,
NULL AS INV_USER_DEF_ATTRIBUTE_5,
NULL AS TRANSACTION_DATE,
NULL AS TAX_INVOICE_DATE,
NULL AS PJC_WORK_TYPE_ID,
NULL AS ATTRIBUTE_NUMBER_5,
NULL AS OPM_COSTED_FLAG,
NULL AS PM_COST_COLLECTED,
NULL AS VALUE_CHANGE,
NULL AS TRANSACTION_REFERENCE,
NULL AS PJC_RESERVED_ATTRIBUTE_9,
NULL AS PJC_CONTRACT_ID,
NULL AS INV_USER_DEF_ATTRIBUTE_9,
NULL AS INV_STRIPING_CATEGORY,
NULL AS FROM_GRADE_CODE,
NULL AS FROM_TASK_ID,
NULL AS ATTRIBUTE_15,
NULL AS LOGICAL_TRX_TYPE_CODE,
NULL AS OWNERSHIP_CHANGE_TXN_ID,
NULL AS PARENT_TRANSACTION_ID,
NULL AS ATTRIBUTE_NUMBER_7,
NULL AS LAST_UPDATE_DATE,
NULL AS ORIG_LOCATOR_ID,
NULL AS PROJECT_ID,
NULL AS PJC_USER_DEF_ATTRIBUTE_6,
NULL AS ACCT_PERIOD_ID,
NULL AS PUT_AWAY_RULE_ID,
NULL AS PRIMARY_QUANTITY,
NULL AS COST_TYPE_ID,
NULL AS DEPRECIABLE_FLAG,
NULL AS COGS_RECOGNITION_PERCENT,
NULL AS OVERCOMPLETION_TRANSACTION_ID,
NULL AS TRANSACTION_INTERFACE_ID,
NULL AS FREIGHT_CODE,
NULL AS MATERIAL_OVERHEAD_ACCOUNT,
NULL AS PICK_RULE_ID,
NULL AS ATTRIBUTE_NUMBER_4,
NULL AS EXTERNAL_SYSTEM_PACKING_UNIT,
NULL AS TRANSFER_PROJECT_ID,
NULL AS ATTRIBUTE_TIMESTAMP_5,
NULL AS THIRD_PTY_REG_ID,
NULL AS DEBRIEF_LINE_ID,
NULL AS ZONE_ID,
NULL AS SERVICE_WIP_FLAG,
NULL AS DELIVERY_CART_ID,
NULL AS MATERIAL_SEQ_NUMBER,
NULL AS _FIVETRAN_SYNCED,
NULL AS _FIVETRAN_DELETED,
'1900-01-01'::TIMESTAMP AS PSA_LOAD_DTS,
'N' AS PSA_DELETE_IND,
CONVERT_TIMEZONE('UTC','1900-01-01'::TIMESTAMP) AS LOAD_DTS,
'USAZET.SNOWFLAKE.FBIN.DERIVED' AS BKCC,
DECODE(GR.VALUE, 0, 'GHOST RECORD-SYSTEM', -1, 'GHOST RECORD-nullkey-required', -2, 'GHOST RECORD-nullkey-optional') AS REC_SRC,
''::BINARY AS HASHDIFF
FROM
TABLE(strtok_split_to_table('0|-1|-2', '|')) AS GR
{% endif %}
