---- SRC LAYER ----
WITH
SRC_a              as ( SELECT * FROM {{ ref('v_psa_stg_po_receipt__lrsn_psft') }} as SRC 
                        {% if is_incremental() %}
                              where src.load_dts > (select dateadd('HOUR',-1,max(load_dts)) from {{ this }})
                            {% endif %}   )

/*
SRC_a              as ( SELECT * FROM STAGING.v_psa_stg_po_receipt__lrsn_psft )
*/
---- LOGIC LAYER ----

, LOGIC_a as (
    SELECT
        LNK_PO_RECEIPT_HK
      , RECEIVER_ID
      , RECV_LN_NBR
      , BUSINESS_UNIT
      , INV_ITEM_ID
      , PO_ID
      , LINE_NBR
      , _FIVETRAN_ID
      , RECV_SHIP_SEQ_NBR
      , AMT_ONLY_FLG
      , ASN_SEQ_NBR
      , BILL_OF_LADING
      , BUSINESS_UNIT_IN
      , BUSINESS_UNIT_PO
      , BUSINESS_UNIT_FROM
      , BILL_OF_ENTRY
      , BOE_LINE_NBR
      , BOE_TYPE
      , CATEGORY_ID
      , CLOSE_SHORT_FLG
      , CONFIG_CODE
      , CONVERSION_RATE
      , CONVERT_TO_STK
      , CONVERT_TO_PO
      , CONVERT_STK_TO_STD
      , COUNTRY_IST_ORIGIN
      , CURRENCY_CD
      , CURRENCY_CD_BASE
      , DESCR254_MIXED
      , DEVICE_TRACKING
      , DISTRIB_MTHD_FLG
      , DUE_DT
      , DUE_TIME
      , EIP_CTL_ID
      , ERS_INV_SEQ
      , ERS_STATUS
      , INSPECT_CD
      , INSPECT_DTTM
      , INSPECT_STATUS
      , INVOICE_ID
      , IST_DISTRIB_STATUS
      , ITM_ID_VNDR
      , ITM_SETID
      , LOT_CONTROL
      , LOT_STATUS
      , MATCH_LINE_FLG
      , MATCH_STATUS_LC
      , MERCH_AMT_BSE
      , MERCH_AMT_PO_BSE
      , MERCHANDISE_AMT
      , MERCHANDISE_AMT_PO
      , MFG_ID
      , MFG_ITM_ID
      , MOVE_STAT_AM
      , MOVE_STAT_INV
      , MOVE_STAT_MFG
      , OP_SEQUENCE
      , OPRID
      , PACKSLIP_NO
      , PO_TYPE
      , PRICE_PO
      , PRICE_PO_BSE
      , PRICE_RECV
      , PROCESS_COMPLETE
      , PROCESS_INSTANCE
      , PRODUCTION_ID
      , QTY_LN_ASSET_SUOM
      , QTY_LN_INV_SUOM
      , QTY_SH_ACCPT
      , QTY_SH_ACCPT_SUOM
      , QTY_SH_ACCPT_VUOM
      , QTY_SH_INSPD
      , QTY_SH_INSPD_SUOM
      , QTY_SH_INSPD_VUOM
      , QTY_SH_NETRCV_VUOM
      , QTY_SH_RECVD
      , QTY_SH_RECVD_SUOM
      , QTY_SH_RECVD_VUOM
      , QTY_SH_REJCT
      , QTY_SH_REJCT_SUOM
      , QTY_SH_REJCT_VUOM
      , QTY_SH_RTN
      , QTY_SH_RTN_SUOM
      , QTY_SH_RTN_VUOM
      , REJECT_ACTION
      , REJECT_REASON
      , REVISION
      , RMA_ID
      , RMA_LINE_NBR
      , RECEIPT_ALLOC_TYPE
      , RECEIPT_DTTM
      , RECEIPT_UM
      , RECEIVE_UOM
      , RECV_LN_MATCH_OPT
      , RECV_SHIP_STATUS
      , RECV_STOCK_UOM
      , REPLACEMENT_FLG
      , SCHED_NBR
      , SERIAL_CONTROL
      , SERIAL_STATUS
      , SHIP_DATE_STATUS
      , SHIP_QTY_STATUS
      , SHIPTO_ID
      , UNIT_MEASURE_STD
      , ORIG_INV_ITEM_ID
      , DESCR254_MIXED2
      , PO_GROUP_ID
      , PRIMARY_UNIT
      , UNIT_ALLOC_QTY
      , UNIT_ALLOC_AMT
      , USER_LINE_CHAR1
      , CUSTOM_C100_B1
      , CUSTOM_C100_B2
      , CUSTOM_C100_B3
      , CUSTOM_C100_B4
      , CUSTOM_DATE_B
      , CUSTOM_C1_B
      , USER_SCHED_CHAR1
      , CUSTOM_C100_C1
      , CUSTOM_C100_C2
      , CUSTOM_C100_C3
      , CUSTOM_DATE_C1
      , CUSTOM_DATE_C2
      , CUSTOM_C1_C
      , UPN_TYPE_CD
      , UPN_ID
      , _FIVETRAN_DELETED
      , _FIVETRAN_SYNCED
      , PSA_RECORD_SOURCE
      , PSA_LOAD_DTS
      , PSA_DELETE_IND
      , LOAD_DTS
      , BKCC
      , REC_SRC
      , HASHDIFF
    FROM SRC_a
)
---- RENAME LAYER ----

, RENAME_a as (
    SELECT
        LNK_PO_RECEIPT_HK
      , RECEIVER_ID
      , RECV_LN_NBR
      , BUSINESS_UNIT
      , INV_ITEM_ID
      , PO_ID
      , LINE_NBR
      , _FIVETRAN_ID
      , RECV_SHIP_SEQ_NBR
      , AMT_ONLY_FLG
      , ASN_SEQ_NBR
      , BILL_OF_LADING
      , BUSINESS_UNIT_IN
      , BUSINESS_UNIT_PO
      , BUSINESS_UNIT_FROM
      , BILL_OF_ENTRY
      , BOE_LINE_NBR
      , BOE_TYPE
      , CATEGORY_ID
      , CLOSE_SHORT_FLG
      , CONFIG_CODE
      , CONVERSION_RATE
      , CONVERT_TO_STK
      , CONVERT_TO_PO
      , CONVERT_STK_TO_STD
      , COUNTRY_IST_ORIGIN
      , CURRENCY_CD
      , CURRENCY_CD_BASE
      , DESCR254_MIXED
      , DEVICE_TRACKING
      , DISTRIB_MTHD_FLG
      , DUE_DT
      , DUE_TIME
      , EIP_CTL_ID
      , ERS_INV_SEQ
      , ERS_STATUS
      , INSPECT_CD
      , INSPECT_DTTM
      , INSPECT_STATUS
      , INVOICE_ID
      , IST_DISTRIB_STATUS
      , ITM_ID_VNDR
      , ITM_SETID
      , LOT_CONTROL
      , LOT_STATUS
      , MATCH_LINE_FLG
      , MATCH_STATUS_LC
      , MERCH_AMT_BSE
      , MERCH_AMT_PO_BSE
      , MERCHANDISE_AMT
      , MERCHANDISE_AMT_PO
      , MFG_ID
      , MFG_ITM_ID
      , MOVE_STAT_AM
      , MOVE_STAT_INV
      , MOVE_STAT_MFG
      , OP_SEQUENCE
      , OPRID
      , PACKSLIP_NO
      , PO_TYPE
      , PRICE_PO
      , PRICE_PO_BSE
      , PRICE_RECV
      , PROCESS_COMPLETE
      , PROCESS_INSTANCE
      , PRODUCTION_ID
      , QTY_LN_ASSET_SUOM
      , QTY_LN_INV_SUOM
      , QTY_SH_ACCPT
      , QTY_SH_ACCPT_SUOM
      , QTY_SH_ACCPT_VUOM
      , QTY_SH_INSPD
      , QTY_SH_INSPD_SUOM
      , QTY_SH_INSPD_VUOM
      , QTY_SH_NETRCV_VUOM
      , QTY_SH_RECVD
      , QTY_SH_RECVD_SUOM
      , QTY_SH_RECVD_VUOM
      , QTY_SH_REJCT
      , QTY_SH_REJCT_SUOM
      , QTY_SH_REJCT_VUOM
      , QTY_SH_RTN
      , QTY_SH_RTN_SUOM
      , QTY_SH_RTN_VUOM
      , REJECT_ACTION
      , REJECT_REASON
      , REVISION
      , RMA_ID
      , RMA_LINE_NBR
      , RECEIPT_ALLOC_TYPE
      , RECEIPT_DTTM
      , RECEIPT_UM
      , RECEIVE_UOM
      , RECV_LN_MATCH_OPT
      , RECV_SHIP_STATUS
      , RECV_STOCK_UOM
      , REPLACEMENT_FLG
      , SCHED_NBR
      , SERIAL_CONTROL
      , SERIAL_STATUS
      , SHIP_DATE_STATUS
      , SHIP_QTY_STATUS
      , SHIPTO_ID
      , UNIT_MEASURE_STD
      , ORIG_INV_ITEM_ID
      , DESCR254_MIXED2
      , PO_GROUP_ID
      , PRIMARY_UNIT
      , UNIT_ALLOC_QTY
      , UNIT_ALLOC_AMT
      , USER_LINE_CHAR1
      , CUSTOM_C100_B1
      , CUSTOM_C100_B2
      , CUSTOM_C100_B3
      , CUSTOM_C100_B4
      , CUSTOM_DATE_B
      , CUSTOM_C1_B
      , USER_SCHED_CHAR1
      , CUSTOM_C100_C1
      , CUSTOM_C100_C2
      , CUSTOM_C100_C3
      , CUSTOM_DATE_C1
      , CUSTOM_DATE_C2
      , CUSTOM_C1_C
      , UPN_TYPE_CD
      , UPN_ID
      , _FIVETRAN_DELETED
      , _FIVETRAN_SYNCED
      , PSA_RECORD_SOURCE
      , PSA_LOAD_DTS
      , PSA_DELETE_IND
      , LOAD_DTS
      , BKCC
      , REC_SRC
      , HASHDIFF
    FROM LOGIC_a
)
---- FILTER LAYER ----

, FILTER_a as (
    SELECT *
    FROM RENAME_a
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM FILTER_a
)

---- FINAL LAYER ----
SELECT
          LNK_PO_RECEIPT_HK
        , RECEIVER_ID
        , RECV_LN_NBR
        , BUSINESS_UNIT
        , INV_ITEM_ID
        , PO_ID
        , LINE_NBR
        , _FIVETRAN_ID
        , RECV_SHIP_SEQ_NBR
        , AMT_ONLY_FLG
        , ASN_SEQ_NBR
        , BILL_OF_LADING
        , BUSINESS_UNIT_IN
        , BUSINESS_UNIT_PO
        , BUSINESS_UNIT_FROM
        , BILL_OF_ENTRY
        , BOE_LINE_NBR
        , BOE_TYPE
        , CATEGORY_ID
        , CLOSE_SHORT_FLG
        , CONFIG_CODE
        , CONVERSION_RATE
        , CONVERT_TO_STK
        , CONVERT_TO_PO
        , CONVERT_STK_TO_STD
        , COUNTRY_IST_ORIGIN
        , CURRENCY_CD
        , CURRENCY_CD_BASE
        , DESCR254_MIXED
        , DEVICE_TRACKING
        , DISTRIB_MTHD_FLG
        , DUE_DT
        , DUE_TIME
        , EIP_CTL_ID
        , ERS_INV_SEQ
        , ERS_STATUS
        , INSPECT_CD
        , INSPECT_DTTM
        , INSPECT_STATUS
        , INVOICE_ID
        , IST_DISTRIB_STATUS
        , ITM_ID_VNDR
        , ITM_SETID
        , LOT_CONTROL
        , LOT_STATUS
        , MATCH_LINE_FLG
        , MATCH_STATUS_LC
        , MERCH_AMT_BSE
        , MERCH_AMT_PO_BSE
        , MERCHANDISE_AMT
        , MERCHANDISE_AMT_PO
        , MFG_ID
        , MFG_ITM_ID
        , MOVE_STAT_AM
        , MOVE_STAT_INV
        , MOVE_STAT_MFG
        , OP_SEQUENCE
        , OPRID
        , PACKSLIP_NO
        , PO_TYPE
        , PRICE_PO
        , PRICE_PO_BSE
        , PRICE_RECV
        , PROCESS_COMPLETE
        , PROCESS_INSTANCE
        , PRODUCTION_ID
        , QTY_LN_ASSET_SUOM
        , QTY_LN_INV_SUOM
        , QTY_SH_ACCPT
        , QTY_SH_ACCPT_SUOM
        , QTY_SH_ACCPT_VUOM
        , QTY_SH_INSPD
        , QTY_SH_INSPD_SUOM
        , QTY_SH_INSPD_VUOM
        , QTY_SH_NETRCV_VUOM
        , QTY_SH_RECVD
        , QTY_SH_RECVD_SUOM
        , QTY_SH_RECVD_VUOM
        , QTY_SH_REJCT
        , QTY_SH_REJCT_SUOM
        , QTY_SH_REJCT_VUOM
        , QTY_SH_RTN
        , QTY_SH_RTN_SUOM
        , QTY_SH_RTN_VUOM
        , REJECT_ACTION
        , REJECT_REASON
        , REVISION
        , RMA_ID
        , RMA_LINE_NBR
        , RECEIPT_ALLOC_TYPE
        , RECEIPT_DTTM
        , RECEIPT_UM
        , RECEIVE_UOM
        , RECV_LN_MATCH_OPT
        , RECV_SHIP_STATUS
        , RECV_STOCK_UOM
        , REPLACEMENT_FLG
        , SCHED_NBR
        , SERIAL_CONTROL
        , SERIAL_STATUS
        , SHIP_DATE_STATUS
        , SHIP_QTY_STATUS
        , SHIPTO_ID
        , UNIT_MEASURE_STD
        , ORIG_INV_ITEM_ID
        , DESCR254_MIXED2
        , PO_GROUP_ID
        , PRIMARY_UNIT
        , UNIT_ALLOC_QTY
        , UNIT_ALLOC_AMT
        , USER_LINE_CHAR1
        , CUSTOM_C100_B1
        , CUSTOM_C100_B2
        , CUSTOM_C100_B3
        , CUSTOM_C100_B4
        , CUSTOM_DATE_B
        , CUSTOM_C1_B
        , USER_SCHED_CHAR1
        , CUSTOM_C100_C1
        , CUSTOM_C100_C2
        , CUSTOM_C100_C3
        , CUSTOM_DATE_C1
        , CUSTOM_DATE_C2
        , CUSTOM_C1_C
        , UPN_TYPE_CD
        , UPN_ID
        , _FIVETRAN_DELETED
        , _FIVETRAN_SYNCED
        , PSA_RECORD_SOURCE
        , PSA_LOAD_DTS
        , PSA_DELETE_IND
        , LOAD_DTS
        , BKCC
        , REC_SRC
        , HASHDIFF
FROM JOIN_RESULT
{% if is_incremental() %}
WHERE NOT EXISTS (
    SELECT 1 
    FROM {{ this }} existing
    WHERE existing.LNK_PO_RECEIPT_HK = JOIN_RESULT.LNK_PO_RECEIPT_HK
    AND existing.HASHDIFF = JOIN_RESULT.HASHDIFF
)
{% endif %}
{% if not is_incremental() %}

/* The following qualifier is implemented to prevent multiple loads of touched records during the initial build, such as multiple rows per HK and hashdiff. */
qualify 1 = row_number() over (partition by LNK_PO_RECEIPT_HK, HASHDIFF order by PSA_LOAD_DTS)

union all
SELECT 
MD5_BINARY(GR.VALUE) AS LNK_PO_RECEIPT_HK,
GR.VALUE::text AS RECEIVER_ID,
GR.VALUE::number AS RECV_LN_NBR,
GR.VALUE::text AS BUSINESS_UNIT,
GR.VALUE::text AS INV_ITEM_ID,
GR.VALUE::text AS PO_ID,
GR.VALUE::number AS LINE_NBR,
NULL AS _FIVETRAN_ID,
NULL AS RECV_SHIP_SEQ_NBR,
NULL AS AMT_ONLY_FLG,
NULL AS ASN_SEQ_NBR,
NULL AS BILL_OF_LADING,
NULL AS BUSINESS_UNIT_IN,
NULL AS BUSINESS_UNIT_PO,
NULL AS BUSINESS_UNIT_FROM,
NULL AS BILL_OF_ENTRY,
NULL AS BOE_LINE_NBR,
NULL AS BOE_TYPE,
NULL AS CATEGORY_ID,
NULL AS CLOSE_SHORT_FLG,
NULL AS CONFIG_CODE,
NULL AS CONVERSION_RATE,
NULL AS CONVERT_TO_STK,
NULL AS CONVERT_TO_PO,
NULL AS CONVERT_STK_TO_STD,
NULL AS COUNTRY_IST_ORIGIN,
NULL AS CURRENCY_CD,
NULL AS CURRENCY_CD_BASE,
NULL AS DESCR254_MIXED,
NULL AS DEVICE_TRACKING,
NULL AS DISTRIB_MTHD_FLG,
NULL AS DUE_DT,
NULL AS DUE_TIME,
NULL AS EIP_CTL_ID,
NULL AS ERS_INV_SEQ,
NULL AS ERS_STATUS,
NULL AS INSPECT_CD,
NULL AS INSPECT_DTTM,
NULL AS INSPECT_STATUS,
NULL AS INVOICE_ID,
NULL AS IST_DISTRIB_STATUS,
NULL AS ITM_ID_VNDR,
NULL AS ITM_SETID,
NULL AS LOT_CONTROL,
NULL AS LOT_STATUS,
NULL AS MATCH_LINE_FLG,
NULL AS MATCH_STATUS_LC,
NULL AS MERCH_AMT_BSE,
NULL AS MERCH_AMT_PO_BSE,
NULL AS MERCHANDISE_AMT,
NULL AS MERCHANDISE_AMT_PO,
NULL AS MFG_ID,
NULL AS MFG_ITM_ID,
NULL AS MOVE_STAT_AM,
NULL AS MOVE_STAT_INV,
NULL AS MOVE_STAT_MFG,
NULL AS OP_SEQUENCE,
NULL AS OPRID,
NULL AS PACKSLIP_NO,
NULL AS PO_TYPE,
NULL AS PRICE_PO,
NULL AS PRICE_PO_BSE,
NULL AS PRICE_RECV,
NULL AS PROCESS_COMPLETE,
NULL AS PROCESS_INSTANCE,
NULL AS PRODUCTION_ID,
NULL AS QTY_LN_ASSET_SUOM,
NULL AS QTY_LN_INV_SUOM,
NULL AS QTY_SH_ACCPT,
NULL AS QTY_SH_ACCPT_SUOM,
NULL AS QTY_SH_ACCPT_VUOM,
NULL AS QTY_SH_INSPD,
NULL AS QTY_SH_INSPD_SUOM,
NULL AS QTY_SH_INSPD_VUOM,
NULL AS QTY_SH_NETRCV_VUOM,
NULL AS QTY_SH_RECVD,
NULL AS QTY_SH_RECVD_SUOM,
NULL AS QTY_SH_RECVD_VUOM,
NULL AS QTY_SH_REJCT,
NULL AS QTY_SH_REJCT_SUOM,
NULL AS QTY_SH_REJCT_VUOM,
NULL AS QTY_SH_RTN,
NULL AS QTY_SH_RTN_SUOM,
NULL AS QTY_SH_RTN_VUOM,
NULL AS REJECT_ACTION,
NULL AS REJECT_REASON,
NULL AS REVISION,
NULL AS RMA_ID,
NULL AS RMA_LINE_NBR,
NULL AS RECEIPT_ALLOC_TYPE,
NULL AS RECEIPT_DTTM,
NULL AS RECEIPT_UM,
NULL AS RECEIVE_UOM,
NULL AS RECV_LN_MATCH_OPT,
NULL AS RECV_SHIP_STATUS,
NULL AS RECV_STOCK_UOM,
NULL AS REPLACEMENT_FLG,
NULL AS SCHED_NBR,
NULL AS SERIAL_CONTROL,
NULL AS SERIAL_STATUS,
NULL AS SHIP_DATE_STATUS,
NULL AS SHIP_QTY_STATUS,
NULL AS SHIPTO_ID,
NULL AS UNIT_MEASURE_STD,
NULL AS ORIG_INV_ITEM_ID,
NULL AS DESCR254_MIXED2,
NULL AS PO_GROUP_ID,
NULL AS PRIMARY_UNIT,
NULL AS UNIT_ALLOC_QTY,
NULL AS UNIT_ALLOC_AMT,
NULL AS USER_LINE_CHAR1,
NULL AS CUSTOM_C100_B1,
NULL AS CUSTOM_C100_B2,
NULL AS CUSTOM_C100_B3,
NULL AS CUSTOM_C100_B4,
NULL AS CUSTOM_DATE_B,
NULL AS CUSTOM_C1_B,
NULL AS USER_SCHED_CHAR1,
NULL AS CUSTOM_C100_C1,
NULL AS CUSTOM_C100_C2,
NULL AS CUSTOM_C100_C3,
NULL AS CUSTOM_DATE_C1,
NULL AS CUSTOM_DATE_C2,
NULL AS CUSTOM_C1_C,
NULL AS UPN_TYPE_CD,
NULL AS UPN_ID,
NULL AS _FIVETRAN_DELETED,
NULL AS _FIVETRAN_SYNCED,
NULL AS PSA_RECORD_SOURCE,
'1900-01-01'::TIMESTAMP AS PSA_LOAD_DTS,
'N' AS PSA_DELETE_IND,
CONVERT_TIMEZONE('UTC','1900-01-01'::TIMESTAMP) AS LOAD_DTS,
DECODE(GR.VALUE, 0, 'GHOST RECORD-SYSTEM', -1, 'GHOST RECORD-nullkey-required', -2, 'GHOST RECORD-nullkey-optional') AS BKCC,
'USAZET.SNOWFLAKE.FBIN.DERIVED' AS REC_SRC,
''::BINARY AS HASHDIFF
FROM
TABLE(strtok_split_to_table('0|-1|-2', '|')) AS GR
{% endif %}
