---- SRC LAYER ----
WITH
SRC_SPLITTE        as ( SELECT * FROM {{ ref('v_psa_stg_plant_item__tt_e21') }} as SRC 
                         {% if is_incremental() %}
                         WHERE SRC.LOAD_DTS > (SELECT DATEADD('HOUR', '-1', MAX(LOAD_DTS)) FROM {{this}})
                         {% endif %}  )

/*
SRC_SPLITTE        as ( SELECT * FROM STAGING.v_psa_stg_plant_item__tt_e21 )
*/
---- LOGIC LAYER ----

, LOGIC_SPLITTE as (
    SELECT
        PLANT_ITEM_HK
      , COST_CTR
      , PART_CODE
      , PART_TYPE
      , LAST_COST
      , PART_STATUS
      , KIT_FLAG
      , TAXABLE
      , ADD_USER
      , ALT_PART4
      , ALT_PART3
      , MIN_INV
      , MIN_BATCH_SZ
      , ALT_PART2
      , ALT_PART1
      , MFG_LEAD_TIME
      , YTD_SALES_DOL
      , ADD_DATE
      , OE_MSG_ID
      , PLATFORM_TYPE
      , LONG_DESC9
      , LONG_DESC8
      , REINFORMIX_DAYS
      , LONG_DESC5
      , STD_BURDEN
      , LONG_DESC4
      , PRIC_TYPE
      , LONG_DESC7
      , LONG_DESC6
      , YTD_PUR_DOL
      , LCHFLD2
      , RPTUOM
      , LCHFLD1
      , PART_WT
      , LCHFLD4
      , LCHFLD3
      , FREIGHT_CLASS
      , STATUS_DATE
      , CSRUN
      , LCHFLD5
      , YTD_SALES_UNIT
      , PART_COST_BURDEN
      , SIM_COST
      , PART_DTYPE
      , STD_FIXED_BURDEN
      , PACK_HEIGHT
      , STD_MATL
      , DIR_SHIP_FLAG
      , MODEL_PKG_NUMB
      , WAVE_PICK
      , MRP_INCLUDE
      , GROS_WT
      , SIM_COST_LABOR
      , COST_NO4
      , COST_NO3
      , INACT_RSN_CODE
      , COST_NO6
      , COST_NO5
      , PART_LENGTH
      , SPEC_SHEET
      , SIM_VARIABLE_BURDEN
      , LOT_GROUP
      , USAGE
      , MFG_PRIOR
      , VERSION_NUMBER
      , LYR_SALES_UNIT
      , FIXED_BURDEN
      , YTD_PUR_UNIT
      , SIM_COST_MATL
      , BAG_PLT
      , COMMODITY_CODE
      , SW_LICENSE_CODE
      , PART_WIDTH
      , PART_DDATE
      , BUYER_CODE
      , LONG_DESC1
      , SIM_FIXED_BURDEN
      , ACCUM_MATL
      , LONG_DESC3
      , LONG_DESC2
      , LYR_PUR_DOL
      , PART_COST
      , REP_PART
      , UPDATE_USER
      , SER_ON_SHIP
      , SIM_COST_BURDEN
      , STD_LABOR
      , RESP_BSN_UNIT
      , PALLET_WGT
      , PART_PRICE
      , SETUPDATE
      , PART_SUBGRP2
      , PART_SUBGRP3
      , PALLET_TYPE
      , COST_NO2
      , COST_NO1
      , ACCUM_STD_BURDEN
      , ACCUM_STD_LABOR
      , STD_COST
      , MAX_INV
      , WARRANTY_CODE
      , LYR_PUR_UNIT
      , LEAD_DAYS
      , MAX_WO_SZ
      , LOT_REQ
      , UPDATE_DATE
      , PUOM
      , DTFLD1
      , NUMFLD1
      , NUMFLD2
      , SPEC_DOCID
      , NUMFLD3
      , DTFLD4
      , NUMFLD4
      , PACK_WEIGHT
      , CATCH_WT
      , NUMFLD5
      , DTFLD5
      , DTFLD2
      , DTFLD3
      , WARRANTY_DAYS
      , DOWNGRADE_GRP
      , LANGUAGE_CODE
      , ASSEMBLED
      , AUTO_HOLD
      , SCHED_GRP
      , RETEST_DAYS
      , TAX_CATEGORY
      , SERVICE
      , SHIPUOM
      , ECOM_INCL
      , ACCUM_SIM_LABOR
      , ROYALTY_CODE
      , CORE_INDICATOR
      , MSG_ID
      , SELLABLE
      , PART_DESC
      , INSTALL_INST
      , PART_COST_LABOR
      , LYR_SALES_DOL
      , SPECIAL_QUOTE
      , ACCUM_LABOR
      , ACCUM_SIM_MATL
      , INST_DOCID
      , SETUPUSER
      , MTO_FLAG
      , BATCH_SIZE
      , MAKE_BUY
      , SAFETY_STOCK
      , SCHFLD1
      , PART_SUBGRP
      , SCHFLD3
      , SCHFLD2
      , ACCUM_SIM_BURDEN
      , WIN
      , SCHFLD5
      , PACK_WIDTH
      , SCHFLD4
      , SERIALIZED
      , PACK_LENGTH
      , CONFIG_GRP
      , DOC_IMAGE_NUMB
      , PREF_FLG
      , MAX_WO_PDAY
      , MFG_UOM
      , PALLET_STACK
      , CYCLE_TIME
      , MEDIA_CODE
      , CYCLE_GRP
      , SETUP_CHRG_FLAG
      , PART_HEIGHT
      , PROD_MSG_ID
      , LONG_DESC10
      , TECH_LEVEL
      , VARIABLE_BURDEN
      , ORDUOM
      , SALE_TYPE
      , ACCUM_BURDEN
      , UOM
      , INVCTL_GRP
      , PART_GRP
      , BAG_WGT
      , ACCUM_STD_MATL
      , DOC_IMAGE_FOLDER
      , SHELF_LIFE
      , DOC_IMAGE_PAGE
      , STD_VARIABLE_BURDEN
      , YTD_PUR_STD
      , STORAGE_TYPE
      , COST_MATL
      , COST_METH
      , _FIVETRAN_DELETED
      , _FIVETRAN_SYNCED
      , PSA_LOAD_DTS
      , PSA_RECORD_SOURCE
      , PSA_DELETE_IND
      , LOAD_DTS
      , REC_SRC
      , HASHDIFF
    FROM SRC_SPLITTE
)
---- RENAME LAYER ----

, RENAME_SPLITTE as (
    SELECT
        PLANT_ITEM_HK
      , COST_CTR
      , PART_CODE
      , PART_TYPE
      , LAST_COST
      , PART_STATUS
      , KIT_FLAG
      , TAXABLE
      , ADD_USER
      , ALT_PART4
      , ALT_PART3
      , MIN_INV
      , MIN_BATCH_SZ
      , ALT_PART2
      , ALT_PART1
      , MFG_LEAD_TIME
      , YTD_SALES_DOL
      , ADD_DATE
      , OE_MSG_ID
      , PLATFORM_TYPE
      , LONG_DESC9
      , LONG_DESC8
      , REINFORMIX_DAYS
      , LONG_DESC5
      , STD_BURDEN
      , LONG_DESC4
      , PRIC_TYPE
      , LONG_DESC7
      , LONG_DESC6
      , YTD_PUR_DOL
      , LCHFLD2
      , RPTUOM
      , LCHFLD1
      , PART_WT
      , LCHFLD4
      , LCHFLD3
      , FREIGHT_CLASS
      , STATUS_DATE
      , CSRUN
      , LCHFLD5
      , YTD_SALES_UNIT
      , PART_COST_BURDEN
      , SIM_COST
      , PART_DTYPE
      , STD_FIXED_BURDEN
      , PACK_HEIGHT
      , STD_MATL
      , DIR_SHIP_FLAG
      , MODEL_PKG_NUMB
      , WAVE_PICK
      , MRP_INCLUDE
      , GROS_WT
      , SIM_COST_LABOR
      , COST_NO4
      , COST_NO3
      , INACT_RSN_CODE
      , COST_NO6
      , COST_NO5
      , PART_LENGTH
      , SPEC_SHEET
      , SIM_VARIABLE_BURDEN
      , LOT_GROUP
      , USAGE
      , MFG_PRIOR
      , VERSION_NUMBER
      , LYR_SALES_UNIT
      , FIXED_BURDEN
      , YTD_PUR_UNIT
      , SIM_COST_MATL
      , BAG_PLT
      , COMMODITY_CODE
      , SW_LICENSE_CODE
      , PART_WIDTH
      , PART_DDATE
      , BUYER_CODE
      , LONG_DESC1
      , SIM_FIXED_BURDEN
      , ACCUM_MATL
      , LONG_DESC3
      , LONG_DESC2
      , LYR_PUR_DOL
      , PART_COST
      , REP_PART
      , UPDATE_USER
      , SER_ON_SHIP
      , SIM_COST_BURDEN
      , STD_LABOR
      , RESP_BSN_UNIT
      , PALLET_WGT
      , PART_PRICE
      , SETUPDATE
      , PART_SUBGRP2
      , PART_SUBGRP3
      , PALLET_TYPE
      , COST_NO2
      , COST_NO1
      , ACCUM_STD_BURDEN
      , ACCUM_STD_LABOR
      , STD_COST
      , MAX_INV
      , WARRANTY_CODE
      , LYR_PUR_UNIT
      , LEAD_DAYS
      , MAX_WO_SZ
      , LOT_REQ
      , UPDATE_DATE
      , PUOM
      , DTFLD1
      , NUMFLD1
      , NUMFLD2
      , SPEC_DOCID
      , NUMFLD3
      , DTFLD4
      , NUMFLD4
      , PACK_WEIGHT
      , CATCH_WT
      , NUMFLD5
      , DTFLD5
      , DTFLD2
      , DTFLD3
      , WARRANTY_DAYS
      , DOWNGRADE_GRP
      , LANGUAGE_CODE
      , ASSEMBLED
      , AUTO_HOLD
      , SCHED_GRP
      , RETEST_DAYS
      , TAX_CATEGORY
      , SERVICE
      , SHIPUOM
      , ECOM_INCL
      , ACCUM_SIM_LABOR
      , ROYALTY_CODE
      , CORE_INDICATOR
      , MSG_ID
      , SELLABLE
      , PART_DESC
      , INSTALL_INST
      , PART_COST_LABOR
      , LYR_SALES_DOL
      , SPECIAL_QUOTE
      , ACCUM_LABOR
      , ACCUM_SIM_MATL
      , INST_DOCID
      , SETUPUSER
      , MTO_FLAG
      , BATCH_SIZE
      , MAKE_BUY
      , SAFETY_STOCK
      , SCHFLD1
      , PART_SUBGRP
      , SCHFLD3
      , SCHFLD2
      , ACCUM_SIM_BURDEN
      , WIN
      , SCHFLD5
      , PACK_WIDTH
      , SCHFLD4
      , SERIALIZED
      , PACK_LENGTH
      , CONFIG_GRP
      , DOC_IMAGE_NUMB
      , PREF_FLG
      , MAX_WO_PDAY
      , MFG_UOM
      , PALLET_STACK
      , CYCLE_TIME
      , MEDIA_CODE
      , CYCLE_GRP
      , SETUP_CHRG_FLAG
      , PART_HEIGHT
      , PROD_MSG_ID
      , LONG_DESC10
      , TECH_LEVEL
      , VARIABLE_BURDEN
      , ORDUOM
      , SALE_TYPE
      , ACCUM_BURDEN
      , UOM
      , INVCTL_GRP
      , PART_GRP
      , BAG_WGT
      , ACCUM_STD_MATL
      , DOC_IMAGE_FOLDER
      , SHELF_LIFE
      , DOC_IMAGE_PAGE
      , STD_VARIABLE_BURDEN
      , YTD_PUR_STD
      , STORAGE_TYPE
      , COST_MATL
      , COST_METH
      , _FIVETRAN_DELETED
      , _FIVETRAN_SYNCED
      , PSA_LOAD_DTS
      , PSA_RECORD_SOURCE
      , PSA_DELETE_IND
      , LOAD_DTS
      , REC_SRC
      , HASHDIFF
    FROM LOGIC_SPLITTE
)
---- FILTER LAYER ----

, FILTER_SPLITTE as (
    SELECT *
    FROM RENAME_SPLITTE
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM FILTER_SPLITTE
)

---- FINAL LAYER ----
SELECT
          PLANT_ITEM_HK
        , COST_CTR
        , PART_CODE
        , PART_TYPE
        , LAST_COST
        , PART_STATUS
        , KIT_FLAG
        , TAXABLE
        , ADD_USER
        , ALT_PART4
        , ALT_PART3
        , MIN_INV
        , MIN_BATCH_SZ
        , ALT_PART2
        , ALT_PART1
        , MFG_LEAD_TIME
        , YTD_SALES_DOL
        , ADD_DATE
        , OE_MSG_ID
        , PLATFORM_TYPE
        , LONG_DESC9
        , LONG_DESC8
        , REINFORMIX_DAYS
        , LONG_DESC5
        , STD_BURDEN
        , LONG_DESC4
        , PRIC_TYPE
        , LONG_DESC7
        , LONG_DESC6
        , YTD_PUR_DOL
        , LCHFLD2
        , RPTUOM
        , LCHFLD1
        , PART_WT
        , LCHFLD4
        , LCHFLD3
        , FREIGHT_CLASS
        , STATUS_DATE
        , CSRUN
        , LCHFLD5
        , YTD_SALES_UNIT
        , PART_COST_BURDEN
        , SIM_COST
        , PART_DTYPE
        , STD_FIXED_BURDEN
        , PACK_HEIGHT
        , STD_MATL
        , DIR_SHIP_FLAG
        , MODEL_PKG_NUMB
        , WAVE_PICK
        , MRP_INCLUDE
        , GROS_WT
        , SIM_COST_LABOR
        , COST_NO4
        , COST_NO3
        , INACT_RSN_CODE
        , COST_NO6
        , COST_NO5
        , PART_LENGTH
        , SPEC_SHEET
        , SIM_VARIABLE_BURDEN
        , LOT_GROUP
        , USAGE
        , MFG_PRIOR
        , VERSION_NUMBER
        , LYR_SALES_UNIT
        , FIXED_BURDEN
        , YTD_PUR_UNIT
        , SIM_COST_MATL
        , BAG_PLT
        , COMMODITY_CODE
        , SW_LICENSE_CODE
        , PART_WIDTH
        , PART_DDATE
        , BUYER_CODE
        , LONG_DESC1
        , SIM_FIXED_BURDEN
        , ACCUM_MATL
        , LONG_DESC3
        , LONG_DESC2
        , LYR_PUR_DOL
        , PART_COST
        , REP_PART
        , UPDATE_USER
        , SER_ON_SHIP
        , SIM_COST_BURDEN
        , STD_LABOR
        , RESP_BSN_UNIT
        , PALLET_WGT
        , PART_PRICE
        , SETUPDATE
        , PART_SUBGRP2
        , PART_SUBGRP3
        , PALLET_TYPE
        , COST_NO2
        , COST_NO1
        , ACCUM_STD_BURDEN
        , ACCUM_STD_LABOR
        , STD_COST
        , MAX_INV
        , WARRANTY_CODE
        , LYR_PUR_UNIT
        , LEAD_DAYS
        , MAX_WO_SZ
        , LOT_REQ
        , UPDATE_DATE
        , PUOM
        , DTFLD1
        , NUMFLD1
        , NUMFLD2
        , SPEC_DOCID
        , NUMFLD3
        , DTFLD4
        , NUMFLD4
        , PACK_WEIGHT
        , CATCH_WT
        , NUMFLD5
        , DTFLD5
        , DTFLD2
        , DTFLD3
        , WARRANTY_DAYS
        , DOWNGRADE_GRP
        , LANGUAGE_CODE
        , ASSEMBLED
        , AUTO_HOLD
        , SCHED_GRP
        , RETEST_DAYS
        , TAX_CATEGORY
        , SERVICE
        , SHIPUOM
        , ECOM_INCL
        , ACCUM_SIM_LABOR
        , ROYALTY_CODE
        , CORE_INDICATOR
        , MSG_ID
        , SELLABLE
        , PART_DESC
        , INSTALL_INST
        , PART_COST_LABOR
        , LYR_SALES_DOL
        , SPECIAL_QUOTE
        , ACCUM_LABOR
        , ACCUM_SIM_MATL
        , INST_DOCID
        , SETUPUSER
        , MTO_FLAG
        , BATCH_SIZE
        , MAKE_BUY
        , SAFETY_STOCK
        , SCHFLD1
        , PART_SUBGRP
        , SCHFLD3
        , SCHFLD2
        , ACCUM_SIM_BURDEN
        , WIN
        , SCHFLD5
        , PACK_WIDTH
        , SCHFLD4
        , SERIALIZED
        , PACK_LENGTH
        , CONFIG_GRP
        , DOC_IMAGE_NUMB
        , PREF_FLG
        , MAX_WO_PDAY
        , MFG_UOM
        , PALLET_STACK
        , CYCLE_TIME
        , MEDIA_CODE
        , CYCLE_GRP
        , SETUP_CHRG_FLAG
        , PART_HEIGHT
        , PROD_MSG_ID
        , LONG_DESC10
        , TECH_LEVEL
        , VARIABLE_BURDEN
        , ORDUOM
        , SALE_TYPE
        , ACCUM_BURDEN
        , UOM
        , INVCTL_GRP
        , PART_GRP
        , BAG_WGT
        , ACCUM_STD_MATL
        , DOC_IMAGE_FOLDER
        , SHELF_LIFE
        , DOC_IMAGE_PAGE
        , STD_VARIABLE_BURDEN
        , YTD_PUR_STD
        , STORAGE_TYPE
        , COST_MATL
        , COST_METH
        , _FIVETRAN_DELETED
        , _FIVETRAN_SYNCED
        , PSA_LOAD_DTS
        , PSA_RECORD_SOURCE
        , PSA_DELETE_IND
        , LOAD_DTS
        , REC_SRC
        , HASHDIFF
FROM JOIN_RESULT
{% if is_incremental() %}
WHERE NOT EXISTS (
    SELECT 1 
    FROM {{ this }} existing
    WHERE existing.PLANT_ITEM_HK= JOIN_RESULT.PLANT_ITEM_HK
    AND existing.HASHDIFF = JOIN_RESULT.HASHDIFF
)
{% endif %}
{% if not is_incremental() %}

/* The following qualifier is implemented to prevent multiple loads of touched records during the initial build, such as multiple rows per HK and hashdiff. */
qualify 1 = row_number() over (partition by PLANT_ITEM_HK, HASHDIFF order by PSA_LOAD_DTS)

union all
SELECT 
MD5_BINARY(GR.VALUE) AS PLANT_ITEM_HK,
GR.VALUE::text AS COST_CTR,
GR.VALUE::text AS PART_CODE,
NULL AS PART_TYPE,
NULL AS LAST_COST,
NULL AS PART_STATUS,
NULL AS KIT_FLAG,
NULL AS TAXABLE,
NULL AS ADD_USER,
NULL AS ALT_PART4,
NULL AS ALT_PART3,
NULL AS MIN_INV,
NULL AS MIN_BATCH_SZ,
NULL AS ALT_PART2,
NULL AS ALT_PART1,
NULL AS MFG_LEAD_TIME,
NULL AS YTD_SALES_DOL,
NULL AS ADD_DATE,
NULL AS OE_MSG_ID,
NULL AS PLATFORM_TYPE,
NULL AS LONG_DESC9,
NULL AS LONG_DESC8,
NULL AS REINFORMIX_DAYS,
NULL AS LONG_DESC5,
NULL AS STD_BURDEN,
NULL AS LONG_DESC4,
NULL AS PRIC_TYPE,
NULL AS LONG_DESC7,
NULL AS LONG_DESC6,
NULL AS YTD_PUR_DOL,
NULL AS LCHFLD2,
NULL AS RPTUOM,
NULL AS LCHFLD1,
NULL AS PART_WT,
NULL AS LCHFLD4,
NULL AS LCHFLD3,
NULL AS FREIGHT_CLASS,
NULL AS STATUS_DATE,
NULL AS CSRUN,
NULL AS LCHFLD5,
NULL AS YTD_SALES_UNIT,
NULL AS PART_COST_BURDEN,
NULL AS SIM_COST,
NULL AS PART_DTYPE,
NULL AS STD_FIXED_BURDEN,
NULL AS PACK_HEIGHT,
NULL AS STD_MATL,
NULL AS DIR_SHIP_FLAG,
NULL AS MODEL_PKG_NUMB,
NULL AS WAVE_PICK,
NULL AS MRP_INCLUDE,
NULL AS GROS_WT,
NULL AS SIM_COST_LABOR,
NULL AS COST_NO4,
NULL AS COST_NO3,
NULL AS INACT_RSN_CODE,
NULL AS COST_NO6,
NULL AS COST_NO5,
NULL AS PART_LENGTH,
NULL AS SPEC_SHEET,
NULL AS SIM_VARIABLE_BURDEN,
NULL AS LOT_GROUP,
NULL AS USAGE,
NULL AS MFG_PRIOR,
NULL AS VERSION_NUMBER,
NULL AS LYR_SALES_UNIT,
NULL AS FIXED_BURDEN,
NULL AS YTD_PUR_UNIT,
NULL AS SIM_COST_MATL,
NULL AS BAG_PLT,
NULL AS COMMODITY_CODE,
NULL AS SW_LICENSE_CODE,
NULL AS PART_WIDTH,
NULL AS PART_DDATE,
NULL AS BUYER_CODE,
NULL AS LONG_DESC1,
NULL AS SIM_FIXED_BURDEN,
NULL AS ACCUM_MATL,
NULL AS LONG_DESC3,
NULL AS LONG_DESC2,
NULL AS LYR_PUR_DOL,
NULL AS PART_COST,
NULL AS REP_PART,
NULL AS UPDATE_USER,
NULL AS SER_ON_SHIP,
NULL AS SIM_COST_BURDEN,
NULL AS STD_LABOR,
NULL AS RESP_BSN_UNIT,
NULL AS PALLET_WGT,
NULL AS PART_PRICE,
NULL AS SETUPDATE,
NULL AS PART_SUBGRP2,
NULL AS PART_SUBGRP3,
NULL AS PALLET_TYPE,
NULL AS COST_NO2,
NULL AS COST_NO1,
NULL AS ACCUM_STD_BURDEN,
NULL AS ACCUM_STD_LABOR,
NULL AS STD_COST,
NULL AS MAX_INV,
NULL AS WARRANTY_CODE,
NULL AS LYR_PUR_UNIT,
NULL AS LEAD_DAYS,
NULL AS MAX_WO_SZ,
NULL AS LOT_REQ,
NULL AS UPDATE_DATE,
NULL AS PUOM,
NULL AS DTFLD1,
NULL AS NUMFLD1,
NULL AS NUMFLD2,
NULL AS SPEC_DOCID,
NULL AS NUMFLD3,
NULL AS DTFLD4,
NULL AS NUMFLD4,
NULL AS PACK_WEIGHT,
NULL AS CATCH_WT,
NULL AS NUMFLD5,
NULL AS DTFLD5,
NULL AS DTFLD2,
NULL AS DTFLD3,
NULL AS WARRANTY_DAYS,
NULL AS DOWNGRADE_GRP,
NULL AS LANGUAGE_CODE,
NULL AS ASSEMBLED,
NULL AS AUTO_HOLD,
NULL AS SCHED_GRP,
NULL AS RETEST_DAYS,
NULL AS TAX_CATEGORY,
NULL AS SERVICE,
NULL AS SHIPUOM,
NULL AS ECOM_INCL,
NULL AS ACCUM_SIM_LABOR,
NULL AS ROYALTY_CODE,
NULL AS CORE_INDICATOR,
NULL AS MSG_ID,
NULL AS SELLABLE,
NULL AS PART_DESC,
NULL AS INSTALL_INST,
NULL AS PART_COST_LABOR,
NULL AS LYR_SALES_DOL,
NULL AS SPECIAL_QUOTE,
NULL AS ACCUM_LABOR,
NULL AS ACCUM_SIM_MATL,
NULL AS INST_DOCID,
NULL AS SETUPUSER,
NULL AS MTO_FLAG,
NULL AS BATCH_SIZE,
NULL AS MAKE_BUY,
NULL AS SAFETY_STOCK,
NULL AS SCHFLD1,
NULL AS PART_SUBGRP,
NULL AS SCHFLD3,
NULL AS SCHFLD2,
NULL AS ACCUM_SIM_BURDEN,
NULL AS WIN,
NULL AS SCHFLD5,
NULL AS PACK_WIDTH,
NULL AS SCHFLD4,
NULL AS SERIALIZED,
NULL AS PACK_LENGTH,
NULL AS CONFIG_GRP,
NULL AS DOC_IMAGE_NUMB,
NULL AS PREF_FLG,
NULL AS MAX_WO_PDAY,
NULL AS MFG_UOM,
NULL AS PALLET_STACK,
NULL AS CYCLE_TIME,
NULL AS MEDIA_CODE,
NULL AS CYCLE_GRP,
NULL AS SETUP_CHRG_FLAG,
NULL AS PART_HEIGHT,
NULL AS PROD_MSG_ID,
NULL AS LONG_DESC10,
NULL AS TECH_LEVEL,
NULL AS VARIABLE_BURDEN,
NULL AS ORDUOM,
NULL AS SALE_TYPE,
NULL AS ACCUM_BURDEN,
NULL AS UOM,
NULL AS INVCTL_GRP,
NULL AS PART_GRP,
NULL AS BAG_WGT,
NULL AS ACCUM_STD_MATL,
NULL AS DOC_IMAGE_FOLDER,
NULL AS SHELF_LIFE,
NULL AS DOC_IMAGE_PAGE,
NULL AS STD_VARIABLE_BURDEN,
NULL AS YTD_PUR_STD,
NULL AS STORAGE_TYPE,
NULL AS COST_MATL,
NULL AS COST_METH,
NULL AS _FIVETRAN_DELETED,
NULL AS _FIVETRAN_SYNCED,
'1900-01-01'::TIMESTAMP AS PSA_LOAD_DTS,
NULL AS PSA_RECORD_SOURCE,
'N' AS PSA_DELETE_IND,
CONVERT_TIMEZONE('UTC','1900-01-01'::TIMESTAMP) AS LOAD_DTS,
'USAZET.SNOWFLAKE.FBIN.DERIVED' AS REC_SRC,
''::BINARY AS HASHDIFF
FROM
TABLE(strtok_split_to_table('0|-1|-2', '|')) AS GR
{% endif %}
