---- SRC LAYER ----
WITH
SRC_SRC            as ( SELECT * FROM {{ ref('v_psa_stg_item_attribute__lrsn_psft') }} as SRC 
{% if is_incremental() %}
      where src.load_dts > (select dateadd('HOUR',-1,max(load_dts)) from {{ this }})
    {% endif %} )

/*
SRC_SRC            as ( SELECT * FROM int_staging_views.v_psa_stg_item_attribute__lrsn_psft )
*/
---- LOGIC LAYER ----

, LOGIC_SRC as (
    SELECT
        PLANT_ITEM_HK
      , INV_ITEM_ID
      , BUSINESS_UNIT
      , RESCH_OUT_FACTOR
      , RESCH_IN_FACTOR
      , DEMAND_FENCE_OF
      , PLAN_FENCE_OFF
      , PLAN_HORIZON
      , TRANSFER_MIN_ORDER
      , TRANSFER_MAX_ORDER
      , TRANS_ORD_MULTIPLE
      , TRANSFER_ORD_MOD
      , PUR_MIN_ORDER
      , PUR_MAX_ORDER
      , PUR_ORDER_MULTIPLE
      , PUR_ORDER_MOD
      , MFG_MOD_UNIT
      , MFG_MIN_ORDER
      , MFG_MAX_ORDER
      , MFG_ORDER_MULTIPLE
      , MFG_ORDER_MOD
      , MFG_LEAD_TIME_FLAG
      , SAFETY_LEVEL
      , EXCESS_LEVEL
      , AUTO_APPROVE_MSG
      , PLANNER_CD
      , PURCHASE_YIELD
      , TRANSFER_YIELD
      , SALES_CONSUMP
      , PROD_CONSUMP
      , TRANS_CONSUMP
      , MSR_CONSUMP
      , EXTRA_CONSUMP
      , PL_AGG_DMD_FLAG
      , RELEASED_ORDER
      , FIRMED_ORDER
      , PL_PRIO_FAMILY
      , USE_SHIPTO_LOC
      , PL_FIXED_PERIOD
      , PL_ITEM_EXPL
      , PL_PROJ_USE_DT
      , PLANNED_BY
      , CAP_FENCE_OFF
      , FCST_FULFILL_SIZE
      , FCST_ADJ_ACTION
      , EARLY_FENCE
      , GBL_EARLY_FENCE
      , PL_SEARCH_DEPTH
      , SPOT_BUY_FLG
      , DP_UOMGROUP
      , USE_PUR_ORD_MOD
      , USE_REGION_VNDR
      , PL_RESCHEDULE_TOL
      , PSA_DELETE_IND
      , PSA_LOAD_DTS
      , PSA_RECORD_SOURCE
      , _FIVETRAN_SYNCED
      , _FIVETRAN_ID
      , _FIVETRAN_DELETED
      , LOAD_DTS
      , REC_SRC
      , BKCC
      , HASHDIFF
    FROM SRC_SRC
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM LOGIC_SRC
)

---- FINAL LAYER ----
SELECT
          PLANT_ITEM_HK
        , INV_ITEM_ID
        , BUSINESS_UNIT
        , RESCH_OUT_FACTOR
        , RESCH_IN_FACTOR
        , DEMAND_FENCE_OF
        , PLAN_FENCE_OFF
        , PLAN_HORIZON
        , TRANSFER_MIN_ORDER
        , TRANSFER_MAX_ORDER
        , TRANS_ORD_MULTIPLE
        , TRANSFER_ORD_MOD
        , PUR_MIN_ORDER
        , PUR_MAX_ORDER
        , PUR_ORDER_MULTIPLE
        , PUR_ORDER_MOD
        , MFG_MOD_UNIT
        , MFG_MIN_ORDER
        , MFG_MAX_ORDER
        , MFG_ORDER_MULTIPLE
        , MFG_ORDER_MOD
        , MFG_LEAD_TIME_FLAG
        , SAFETY_LEVEL
        , EXCESS_LEVEL
        , AUTO_APPROVE_MSG
        , PLANNER_CD
        , PURCHASE_YIELD
        , TRANSFER_YIELD
        , SALES_CONSUMP
        , PROD_CONSUMP
        , TRANS_CONSUMP
        , MSR_CONSUMP
        , EXTRA_CONSUMP
        , PL_AGG_DMD_FLAG
        , RELEASED_ORDER
        , FIRMED_ORDER
        , PL_PRIO_FAMILY
        , USE_SHIPTO_LOC
        , PL_FIXED_PERIOD
        , PL_ITEM_EXPL
        , PL_PROJ_USE_DT
        , PLANNED_BY
        , CAP_FENCE_OFF
        , FCST_FULFILL_SIZE
        , FCST_ADJ_ACTION
        , EARLY_FENCE
        , GBL_EARLY_FENCE
        , PL_SEARCH_DEPTH
        , SPOT_BUY_FLG
        , DP_UOMGROUP
        , USE_PUR_ORD_MOD
        , USE_REGION_VNDR
        , PL_RESCHEDULE_TOL
        , PSA_DELETE_IND
        , PSA_LOAD_DTS
        , PSA_RECORD_SOURCE
        , _FIVETRAN_SYNCED
        , _FIVETRAN_ID
        , _FIVETRAN_DELETED
        , LOAD_DTS
        , REC_SRC
        , BKCC
        , HASHDIFF
FROM JOIN_RESULT
{% if is_incremental() %}
WHERE NOT EXISTS (
    SELECT 1
    FROM {{ this }} existing
    WHERE existing.PLANT_ITEM_HK = JOIN_RESULT.PLANT_ITEM_HK
      AND existing.HASHDIFF = JOIN_RESULT.HASHDIFF
)
{% endif %}
{% if not is_incremental() %}

/* The following qualifier is implemented to prevent multiple loads of touched records during the initial build, such as multiple rows per HK and hashdiff. */
qualify 1 = row_number() over (partition by PLANT_ITEM_HK, HASHDIFF order by PSA_LOAD_DTS)

union all
SELECT 
MD5_BINARY(GR.VALUE) AS PLANT_ITEM_HK,
NULL AS INV_ITEM_ID,
NULL AS BUSINESS_UNIT,
NULL AS RESCH_OUT_FACTOR,
NULL AS RESCH_IN_FACTOR,
NULL AS DEMAND_FENCE_OF,
NULL AS PLAN_FENCE_OFF,
NULL AS PLAN_HORIZON,
NULL AS TRANSFER_MIN_ORDER,
NULL AS TRANSFER_MAX_ORDER,
NULL AS TRANS_ORD_MULTIPLE,
NULL AS TRANSFER_ORD_MOD,
NULL AS PUR_MIN_ORDER,
NULL AS PUR_MAX_ORDER,
NULL AS PUR_ORDER_MULTIPLE,
NULL AS PUR_ORDER_MOD,
NULL AS MFG_MOD_UNIT,
NULL AS MFG_MIN_ORDER,
NULL AS MFG_MAX_ORDER,
NULL AS MFG_ORDER_MULTIPLE,
NULL AS MFG_ORDER_MOD,
NULL AS MFG_LEAD_TIME_FLAG,
NULL AS SAFETY_LEVEL,
NULL AS EXCESS_LEVEL,
NULL AS AUTO_APPROVE_MSG,
NULL AS PLANNER_CD,
NULL AS PURCHASE_YIELD,
NULL AS TRANSFER_YIELD,
NULL AS SALES_CONSUMP,
NULL AS PROD_CONSUMP,
NULL AS TRANS_CONSUMP,
NULL AS MSR_CONSUMP,
NULL AS EXTRA_CONSUMP,
NULL AS PL_AGG_DMD_FLAG,
NULL AS RELEASED_ORDER,
NULL AS FIRMED_ORDER,
NULL AS PL_PRIO_FAMILY,
NULL AS USE_SHIPTO_LOC,
NULL AS PL_FIXED_PERIOD,
NULL AS PL_ITEM_EXPL,
NULL AS PL_PROJ_USE_DT,
NULL AS PLANNED_BY,
NULL AS CAP_FENCE_OFF,
NULL AS FCST_FULFILL_SIZE,
NULL AS FCST_ADJ_ACTION,
NULL AS EARLY_FENCE,
NULL AS GBL_EARLY_FENCE,
NULL AS PL_SEARCH_DEPTH,
NULL AS SPOT_BUY_FLG,
NULL AS DP_UOMGROUP,
NULL AS USE_PUR_ORD_MOD,
NULL AS USE_REGION_VNDR,
NULL AS PL_RESCHEDULE_TOL,
'N' AS PSA_DELETE_IND,
'1900-01-01'::TIMESTAMP AS PSA_LOAD_DTS,
NULL AS PSA_RECORD_SOURCE,
NULL AS _FIVETRAN_SYNCED,
NULL AS _FIVETRAN_ID,
NULL AS _FIVETRAN_DELETED,
'1900-01-01T00:00:00'::TIMESTAMP_NTZ AS LOAD_DTS,
'USAZET.SNOWFLAKE.FBIN.DERIVED' AS REC_SRC,
DECODE(GR.VALUE, 0, 'GHOST RECORD-SYSTEM', -1, 'GHOST RECORD-nullkey-required', -2, 'GHOST RECORD-nullkey-optional') AS BKCC,
MD5_BINARY('') AS HASHDIFF
FROM
TABLE(strtok_split_to_table('0|-1|-2', '|')) AS GR
{% endif %}
