---- SRC LAYER ----
WITH
SRC_SHOPORDHD      as ( SELECT * FROM {{ ref('v_psa_stg_dtc_order_header__winn_shopify') }} as SRC 
                        {% if is_incremental() %}
                         WHERE SRC.LOAD_DTS > (SELECT DATEADD('HOUR', '-1', MAX(LOAD_DTS)) FROM {{this}})
                         {% endif %} )

/*
SRC_SHOPORDHD      as ( SELECT * FROM STAGING.v_psa_stg_dtc_order_header__winn_shopify )
*/
---- LOGIC LAYER ----

, LOGIC_SHOPORDHD as (
    SELECT
        LNK_ORDER_CUSTOMER_CONSUMER_HK
      , ID
      , NOTE
      , EMAIL
      , TAXES_INCLUDED
      , CURRENCY
      , SUBTOTAL_PRICE
      , SUBTOTAL_PRICE_SET
      , TOTAL_TAX
      , TOTAL_TAX_SET
      , TOTAL_PRICE
      , TOTAL_PRICE_SET
      , CREATED_AT
      , UPDATED_AT
      , NAME
      , SHIPPING_ADDRESS_NAME
      , SHIPPING_ADDRESS_FIRST_NAME
      , SHIPPING_ADDRESS_LAST_NAME
      , SHIPPING_ADDRESS_COMPANY
      , SHIPPING_ADDRESS_PHONE
      , SHIPPING_ADDRESS_ADDRESS_1
      , SHIPPING_ADDRESS_ADDRESS_2
      , SHIPPING_ADDRESS_CITY
      , SHIPPING_ADDRESS_COUNTRY
      , SHIPPING_ADDRESS_COUNTRY_CODE
      , SHIPPING_ADDRESS_PROVINCE
      , SHIPPING_ADDRESS_PROVINCE_CODE
      , SHIPPING_ADDRESS_ZIP
      , SHIPPING_ADDRESS_LATITUDE
      , SHIPPING_ADDRESS_LONGITUDE
      , BILLING_ADDRESS_NAME
      , BILLING_ADDRESS_FIRST_NAME
      , BILLING_ADDRESS_LAST_NAME
      , BILLING_ADDRESS_COMPANY
      , BILLING_ADDRESS_PHONE
      , BILLING_ADDRESS_ADDRESS_1
      , BILLING_ADDRESS_ADDRESS_2
      , BILLING_ADDRESS_CITY
      , BILLING_ADDRESS_COUNTRY
      , BILLING_ADDRESS_COUNTRY_CODE
      , BILLING_ADDRESS_PROVINCE
      , BILLING_ADDRESS_PROVINCE_CODE
      , BILLING_ADDRESS_ZIP
      , BILLING_ADDRESS_LATITUDE
      , BILLING_ADDRESS_LONGITUDE
      , CUSTOMER_ID
      , LOCATION_ID
      , USER_ID
      , APP_ID
      , NUMBER
      , ORDER_NUMBER
      , FINANCIAL_STATUS
      , FULFILLMENT_STATUS
      , PROCESSED_AT
      , REFERRING_SITE
      , CANCEL_REASON
      , CANCELLED_AT
      , CLOSED_AT
      , TOTAL_DISCOUNTS
      , TOTAL_TIP_RECEIVED
      , CURRENT_TOTAL_PRICE
      , CURRENT_TOTAL_DISCOUNTS
      , CURRENT_SUBTOTAL_PRICE
      , CURRENT_TOTAL_TAX
      , CURRENT_TOTAL_DISCOUNTS_SET
      , CURRENT_TOTAL_DUTIES_SET
      , CURRENT_TOTAL_PRICE_SET
      , CURRENT_SUBTOTAL_PRICE_SET
      , CURRENT_TOTAL_TAX_SET
      , TOTAL_DISCOUNTS_SET
      , TOTAL_SHIPPING_PRICE_SET
      , TOTAL_LINE_ITEMS_PRICE
      , TOTAL_LINE_ITEMS_PRICE_SET
      , ORIGINAL_TOTAL_DUTIES_SET
      , TOTAL_WEIGHT
      , SOURCE_NAME
      , BROWSER_IP
      , BUYER_ACCEPTS_MARKETING
      , CONFIRMED
      , TOKEN
      , CART_TOKEN
      , CHECKOUT_TOKEN
      , CHECKOUT_ID
      , CUSTOMER_LOCALE
      , DEVICE_ID
      , LANDING_SITE_REF
      , PRESENTMENT_CURRENCY
      , REFERENCE
      , SOURCE_IDENTIFIER
      , SOURCE_URL
      , _FIVETRAN_DELETED
      , ORDER_STATUS_URL
      , TEST
      , PAYMENT_GATEWAY_NAMES
      , NOTE_ATTRIBUTES
      , CLIENT_DETAILS_USER_AGENT
      , LANDING_SITE_BASE_URL
      , _FIVETRAN_SYNCED
      , COMPANY_ID
      , COMPANY_LOCATION_ID
      , PSA_LOAD_DTS
      , PSA_RECORD_SOURCE
      , PSA_DELETE_IND
      , LOAD_DTS
      , REC_SRC
      , HASHDIFF
    FROM SRC_SHOPORDHD
)
---- RENAME LAYER ----

, RENAME_SHOPORDHD as (
    SELECT
        LNK_ORDER_CUSTOMER_CONSUMER_HK
      , ID
      , NOTE
      , EMAIL
      , TAXES_INCLUDED
      , CURRENCY
      , SUBTOTAL_PRICE
      , SUBTOTAL_PRICE_SET
      , TOTAL_TAX
      , TOTAL_TAX_SET
      , TOTAL_PRICE
      , TOTAL_PRICE_SET
      , CREATED_AT
      , UPDATED_AT
      , NAME
      , SHIPPING_ADDRESS_NAME
      , SHIPPING_ADDRESS_FIRST_NAME
      , SHIPPING_ADDRESS_LAST_NAME
      , SHIPPING_ADDRESS_COMPANY
      , SHIPPING_ADDRESS_PHONE
      , SHIPPING_ADDRESS_ADDRESS_1
      , SHIPPING_ADDRESS_ADDRESS_2
      , SHIPPING_ADDRESS_CITY
      , SHIPPING_ADDRESS_COUNTRY
      , SHIPPING_ADDRESS_COUNTRY_CODE
      , SHIPPING_ADDRESS_PROVINCE
      , SHIPPING_ADDRESS_PROVINCE_CODE
      , SHIPPING_ADDRESS_ZIP
      , SHIPPING_ADDRESS_LATITUDE
      , SHIPPING_ADDRESS_LONGITUDE
      , BILLING_ADDRESS_NAME
      , BILLING_ADDRESS_FIRST_NAME
      , BILLING_ADDRESS_LAST_NAME
      , BILLING_ADDRESS_COMPANY
      , BILLING_ADDRESS_PHONE
      , BILLING_ADDRESS_ADDRESS_1
      , BILLING_ADDRESS_ADDRESS_2
      , BILLING_ADDRESS_CITY
      , BILLING_ADDRESS_COUNTRY
      , BILLING_ADDRESS_COUNTRY_CODE
      , BILLING_ADDRESS_PROVINCE
      , BILLING_ADDRESS_PROVINCE_CODE
      , BILLING_ADDRESS_ZIP
      , BILLING_ADDRESS_LATITUDE
      , BILLING_ADDRESS_LONGITUDE
      , CUSTOMER_ID
      , LOCATION_ID
      , USER_ID
      , APP_ID
      , NUMBER
      , ORDER_NUMBER
      , FINANCIAL_STATUS
      , FULFILLMENT_STATUS
      , PROCESSED_AT
      , REFERRING_SITE
      , CANCEL_REASON
      , CANCELLED_AT
      , CLOSED_AT
      , TOTAL_DISCOUNTS
      , TOTAL_TIP_RECEIVED
      , CURRENT_TOTAL_PRICE
      , CURRENT_TOTAL_DISCOUNTS
      , CURRENT_SUBTOTAL_PRICE
      , CURRENT_TOTAL_TAX
      , CURRENT_TOTAL_DISCOUNTS_SET
      , CURRENT_TOTAL_DUTIES_SET
      , CURRENT_TOTAL_PRICE_SET
      , CURRENT_SUBTOTAL_PRICE_SET
      , CURRENT_TOTAL_TAX_SET
      , TOTAL_DISCOUNTS_SET
      , TOTAL_SHIPPING_PRICE_SET
      , TOTAL_LINE_ITEMS_PRICE
      , TOTAL_LINE_ITEMS_PRICE_SET
      , ORIGINAL_TOTAL_DUTIES_SET
      , TOTAL_WEIGHT
      , SOURCE_NAME
      , BROWSER_IP
      , BUYER_ACCEPTS_MARKETING
      , CONFIRMED
      , TOKEN
      , CART_TOKEN
      , CHECKOUT_TOKEN
      , CHECKOUT_ID
      , CUSTOMER_LOCALE
      , DEVICE_ID
      , LANDING_SITE_REF
      , PRESENTMENT_CURRENCY
      , REFERENCE
      , SOURCE_IDENTIFIER
      , SOURCE_URL
      , _FIVETRAN_DELETED
      , ORDER_STATUS_URL
      , TEST
      , PAYMENT_GATEWAY_NAMES
      , NOTE_ATTRIBUTES
      , CLIENT_DETAILS_USER_AGENT
      , LANDING_SITE_BASE_URL
      , _FIVETRAN_SYNCED
      , COMPANY_ID
      , COMPANY_LOCATION_ID
      , PSA_LOAD_DTS
      , PSA_RECORD_SOURCE
      , PSA_DELETE_IND
      , LOAD_DTS
      , REC_SRC
      , HASHDIFF
    FROM LOGIC_SHOPORDHD
)
---- FILTER LAYER ----

, FILTER_SHOPORDHD as (
    SELECT *
    FROM RENAME_SHOPORDHD
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM FILTER_SHOPORDHD
)

---- FINAL LAYER ----
SELECT
          LNK_ORDER_CUSTOMER_CONSUMER_HK
        , ID
        , NOTE
        , EMAIL
        , TAXES_INCLUDED
        , CURRENCY
        , SUBTOTAL_PRICE
        , SUBTOTAL_PRICE_SET
        , TOTAL_TAX
        , TOTAL_TAX_SET
        , TOTAL_PRICE
        , TOTAL_PRICE_SET
        , CREATED_AT
        , UPDATED_AT
        , NAME
        , SHIPPING_ADDRESS_NAME
        , SHIPPING_ADDRESS_FIRST_NAME
        , SHIPPING_ADDRESS_LAST_NAME
        , SHIPPING_ADDRESS_COMPANY
        , SHIPPING_ADDRESS_PHONE
        , SHIPPING_ADDRESS_ADDRESS_1
        , SHIPPING_ADDRESS_ADDRESS_2
        , SHIPPING_ADDRESS_CITY
        , SHIPPING_ADDRESS_COUNTRY
        , SHIPPING_ADDRESS_COUNTRY_CODE
        , SHIPPING_ADDRESS_PROVINCE
        , SHIPPING_ADDRESS_PROVINCE_CODE
        , SHIPPING_ADDRESS_ZIP
        , SHIPPING_ADDRESS_LATITUDE
        , SHIPPING_ADDRESS_LONGITUDE
        , BILLING_ADDRESS_NAME
        , BILLING_ADDRESS_FIRST_NAME
        , BILLING_ADDRESS_LAST_NAME
        , BILLING_ADDRESS_COMPANY
        , BILLING_ADDRESS_PHONE
        , BILLING_ADDRESS_ADDRESS_1
        , BILLING_ADDRESS_ADDRESS_2
        , BILLING_ADDRESS_CITY
        , BILLING_ADDRESS_COUNTRY
        , BILLING_ADDRESS_COUNTRY_CODE
        , BILLING_ADDRESS_PROVINCE
        , BILLING_ADDRESS_PROVINCE_CODE
        , BILLING_ADDRESS_ZIP
        , BILLING_ADDRESS_LATITUDE
        , BILLING_ADDRESS_LONGITUDE
        , CUSTOMER_ID
        , LOCATION_ID
        , USER_ID
        , APP_ID
        , NUMBER
        , ORDER_NUMBER
        , FINANCIAL_STATUS
        , FULFILLMENT_STATUS
        , PROCESSED_AT
        , REFERRING_SITE
        , CANCEL_REASON
        , CANCELLED_AT
        , CLOSED_AT
        , TOTAL_DISCOUNTS
        , TOTAL_TIP_RECEIVED
        , CURRENT_TOTAL_PRICE
        , CURRENT_TOTAL_DISCOUNTS
        , CURRENT_SUBTOTAL_PRICE
        , CURRENT_TOTAL_TAX
        , CURRENT_TOTAL_DISCOUNTS_SET
        , CURRENT_TOTAL_DUTIES_SET
        , CURRENT_TOTAL_PRICE_SET
        , CURRENT_SUBTOTAL_PRICE_SET
        , CURRENT_TOTAL_TAX_SET
        , TOTAL_DISCOUNTS_SET
        , TOTAL_SHIPPING_PRICE_SET
        , TOTAL_LINE_ITEMS_PRICE
        , TOTAL_LINE_ITEMS_PRICE_SET
        , ORIGINAL_TOTAL_DUTIES_SET
        , TOTAL_WEIGHT
        , SOURCE_NAME
        , BROWSER_IP
        , BUYER_ACCEPTS_MARKETING
        , CONFIRMED
        , TOKEN
        , CART_TOKEN
        , CHECKOUT_TOKEN
        , CHECKOUT_ID
        , CUSTOMER_LOCALE
        , DEVICE_ID
        , LANDING_SITE_REF
        , PRESENTMENT_CURRENCY
        , REFERENCE
        , SOURCE_IDENTIFIER
        , SOURCE_URL
        , _FIVETRAN_DELETED
        , ORDER_STATUS_URL
        , TEST
        , PAYMENT_GATEWAY_NAMES
        , NOTE_ATTRIBUTES
        , CLIENT_DETAILS_USER_AGENT
        , LANDING_SITE_BASE_URL
        , _FIVETRAN_SYNCED
        , COMPANY_ID
        , COMPANY_LOCATION_ID
        , PSA_LOAD_DTS
        , PSA_RECORD_SOURCE
        , PSA_DELETE_IND
        , LOAD_DTS
        , REC_SRC
        , HASHDIFF
FROM JOIN_RESULT
{% if is_incremental() %}
WHERE NOT EXISTS (
    SELECT 1 
    FROM {{ this }} existing
    WHERE existing.LNK_ORDER_CUSTOMER_CONSUMER_HK = JOIN_RESULT.LNK_ORDER_CUSTOMER_CONSUMER_HK
	AND existing.HASHDIFF = JOIN_RESULT.HASHDIFF	
)
{% endif %}
{% if not is_incremental() %}

/* The following qualifier is implemented to prevent multiple loads of touched records during the initial build, such as multiple rows per HK and hashdiff. */
qualify 1 = row_number() over (partition by LNK_ORDER_CUSTOMER_CONSUMER_HK, HASHDIFF order by PSA_LOAD_DTS)

union all
SELECT 
MD5_BINARY(GR.VALUE) AS LNK_ORDER_CUSTOMER_CONSUMER_HK,
GR.VALUE::number AS ID,
NULL AS NOTE,
GR.VALUE::text AS EMAIL,
NULL AS TAXES_INCLUDED,
NULL AS CURRENCY,
NULL AS SUBTOTAL_PRICE,
NULL AS SUBTOTAL_PRICE_SET,
NULL AS TOTAL_TAX,
NULL AS TOTAL_TAX_SET,
NULL AS TOTAL_PRICE,
NULL AS TOTAL_PRICE_SET,
NULL AS CREATED_AT,
NULL AS UPDATED_AT,
GR.VALUE::text AS NAME,
NULL AS SHIPPING_ADDRESS_NAME,
NULL AS SHIPPING_ADDRESS_FIRST_NAME,
NULL AS SHIPPING_ADDRESS_LAST_NAME,
NULL AS SHIPPING_ADDRESS_COMPANY,
NULL AS SHIPPING_ADDRESS_PHONE,
NULL AS SHIPPING_ADDRESS_ADDRESS_1,
NULL AS SHIPPING_ADDRESS_ADDRESS_2,
NULL AS SHIPPING_ADDRESS_CITY,
NULL AS SHIPPING_ADDRESS_COUNTRY,
NULL AS SHIPPING_ADDRESS_COUNTRY_CODE,
NULL AS SHIPPING_ADDRESS_PROVINCE,
NULL AS SHIPPING_ADDRESS_PROVINCE_CODE,
NULL AS SHIPPING_ADDRESS_ZIP,
NULL AS SHIPPING_ADDRESS_LATITUDE,
NULL AS SHIPPING_ADDRESS_LONGITUDE,
NULL AS BILLING_ADDRESS_NAME,
NULL AS BILLING_ADDRESS_FIRST_NAME,
NULL AS BILLING_ADDRESS_LAST_NAME,
NULL AS BILLING_ADDRESS_COMPANY,
NULL AS BILLING_ADDRESS_PHONE,
NULL AS BILLING_ADDRESS_ADDRESS_1,
NULL AS BILLING_ADDRESS_ADDRESS_2,
NULL AS BILLING_ADDRESS_CITY,
NULL AS BILLING_ADDRESS_COUNTRY,
NULL AS BILLING_ADDRESS_COUNTRY_CODE,
NULL AS BILLING_ADDRESS_PROVINCE,
NULL AS BILLING_ADDRESS_PROVINCE_CODE,
NULL AS BILLING_ADDRESS_ZIP,
NULL AS BILLING_ADDRESS_LATITUDE,
NULL AS BILLING_ADDRESS_LONGITUDE,
GR.VALUE::number AS CUSTOMER_ID,
NULL AS LOCATION_ID,
NULL AS USER_ID,
NULL AS APP_ID,
NULL AS NUMBER,
NULL AS ORDER_NUMBER,
NULL AS FINANCIAL_STATUS,
NULL AS FULFILLMENT_STATUS,
NULL AS PROCESSED_AT,
NULL AS REFERRING_SITE,
NULL AS CANCEL_REASON,
NULL AS CANCELLED_AT,
NULL AS CLOSED_AT,
NULL AS TOTAL_DISCOUNTS,
NULL AS TOTAL_TIP_RECEIVED,
NULL AS CURRENT_TOTAL_PRICE,
NULL AS CURRENT_TOTAL_DISCOUNTS,
NULL AS CURRENT_SUBTOTAL_PRICE,
NULL AS CURRENT_TOTAL_TAX,
NULL AS CURRENT_TOTAL_DISCOUNTS_SET,
NULL AS CURRENT_TOTAL_DUTIES_SET,
NULL AS CURRENT_TOTAL_PRICE_SET,
NULL AS CURRENT_SUBTOTAL_PRICE_SET,
NULL AS CURRENT_TOTAL_TAX_SET,
NULL AS TOTAL_DISCOUNTS_SET,
NULL AS TOTAL_SHIPPING_PRICE_SET,
NULL AS TOTAL_LINE_ITEMS_PRICE,
NULL AS TOTAL_LINE_ITEMS_PRICE_SET,
NULL AS ORIGINAL_TOTAL_DUTIES_SET,
NULL AS TOTAL_WEIGHT,
NULL AS SOURCE_NAME,
NULL AS BROWSER_IP,
NULL AS BUYER_ACCEPTS_MARKETING,
NULL AS CONFIRMED,
NULL AS TOKEN,
NULL AS CART_TOKEN,
NULL AS CHECKOUT_TOKEN,
NULL AS CHECKOUT_ID,
NULL AS CUSTOMER_LOCALE,
NULL AS DEVICE_ID,
NULL AS LANDING_SITE_REF,
NULL AS PRESENTMENT_CURRENCY,
NULL AS REFERENCE,
NULL AS SOURCE_IDENTIFIER,
NULL AS SOURCE_URL,
NULL AS _FIVETRAN_DELETED,
NULL AS ORDER_STATUS_URL,
NULL AS TEST,
NULL AS PAYMENT_GATEWAY_NAMES,
NULL AS NOTE_ATTRIBUTES,
NULL AS CLIENT_DETAILS_USER_AGENT,
NULL AS LANDING_SITE_BASE_URL,
NULL AS _FIVETRAN_SYNCED,
NULL AS COMPANY_ID,
NULL AS COMPANY_LOCATION_ID,
'1900-01-01'::TIMESTAMP AS PSA_LOAD_DTS,
NULL AS PSA_RECORD_SOURCE,
'N' AS PSA_DELETE_IND,
CONVERT_TIMEZONE('UTC','1900-01-01'::TIMESTAMP) AS LOAD_DTS,
'USAZET.SNOWFLAKE.FBIN.DERIVED' AS REC_SRC,
''::BINARY AS HASHDIFF
FROM
TABLE(strtok_split_to_table('0|-1|-2', '|')) AS GR
{% endif %}
