---- SRC LAYER ----
WITH
SRC_SPITTGP        as ( SELECT * FROM {{ ref('v_psa_stg_plant_item__tt_gp') }} as SRC 
                         {% if is_incremental() %}
                         WHERE SRC.LOAD_DTS > (SELECT DATEADD('HOUR', '-1', MAX(LOAD_DTS)) FROM {{this}})
                         {% endif %}  )

/*
SRC_SPITTGP        as ( SELECT * FROM STAGING.v_psa_stg_plant_item__tt_gp )
*/
---- LOGIC LAYER ----

, LOGIC_SPITTGP as (
    SELECT
        PLANT_ITEM_HK
      , ITEMNMBR
      , LOCNCODE
      , BINNMBR
      , RCRDTYPE
      , PRIMVNDR
      , ITMFRFLG
      , BGNGQTY
      , LSORDQTY
      , LRCPTQTY
      , LSTORDDT
      , LSORDVND
      , LSRCPTDT
      , QTYRQSTN
      , QTYONORD
      , QTYBKORD
      , QTY_DROP_SHIPPED
      , QTYINUSE
      , QTYINSVC
      , QTYRTRND
      , QTYDMGED
      , QTYONHND
      , ATYALLOC
      , QTYCOMTD
      , QTYSOLD
      , NXTCNTDT
      , NXTCNTTM
      , LSTCNTDT
      , LSTCNTTM
      , STCKCNTINTRVL
      , LANDED_COST_GROUP_ID
      , BUYERID
      , PLANNERID
      , ORDERPOLICY
      , FXDORDRQTY
      , ORDRPNTQTY
      , NMBROFDYS
      , MNMMORDRQTY
      , MXMMORDRQTY
      , ORDERMULTIPLE
      , REPLENISHMENTMETHOD
      , SHRINKAGEFACTOR
      , PRCHSNGLDTM
      , MNFCTRNGFXDLDTM
      , MNFCTRNGVRBLLDTM
      , STAGINGLDTME
      , PLNNNGTMFNCDYS
      , DMNDTMFNCPRDS
      , INCLDDINPLNNNG
      , CALCULATEATP
      , AUTOCHKATP
      , PLNFNLPAB
      , FRCSTCNSMPTNPRD
      , ORDRUPTOLVL
      , SFTYSTCKQTY
      , REORDERVARIANCE
      , PORECEIPTBIN
      , PORETRNBIN
      , SOFULFILLMENTBIN
      , SORETURNBIN
      , BOMRCPTBIN
      , MATERIALISSUEBIN
      , MORECEIPTBIN
      , REPAIRISSUESBIN
      , REPLENISHMENTLEVEL
      , POPORDERMETHOD
      , MASTERLOCATIONCODE
      , POPVENDORSELECTION
      , POPPRICINGSELECTION
      , PURCHASEPRICE
      , INCLUDEALLOCATIONS
      , INCLUDEBACKORDERS
      , INCLUDEREQUISITIONS
      , PICKTICKETITEMOPT
      , DEX_ROW_ID
      , PSA_LOAD_DTS
      , PSA_RECORD_SOURCE
      , PSA_DELETE_IND
      , LOAD_DTS
      , REC_SRC
      , HASHDIFF
    FROM SRC_SPITTGP
)
---- RENAME LAYER ----

, RENAME_SPITTGP as (
    SELECT
        PLANT_ITEM_HK
      , ITEMNMBR
      , LOCNCODE
      , BINNMBR
      , RCRDTYPE
      , PRIMVNDR
      , ITMFRFLG
      , BGNGQTY
      , LSORDQTY
      , LRCPTQTY
      , LSTORDDT
      , LSORDVND
      , LSRCPTDT
      , QTYRQSTN
      , QTYONORD
      , QTYBKORD
      , QTY_DROP_SHIPPED
      , QTYINUSE
      , QTYINSVC
      , QTYRTRND
      , QTYDMGED
      , QTYONHND
      , ATYALLOC
      , QTYCOMTD
      , QTYSOLD
      , NXTCNTDT
      , NXTCNTTM
      , LSTCNTDT
      , LSTCNTTM
      , STCKCNTINTRVL
      , LANDED_COST_GROUP_ID
      , BUYERID
      , PLANNERID
      , ORDERPOLICY
      , FXDORDRQTY
      , ORDRPNTQTY
      , NMBROFDYS
      , MNMMORDRQTY
      , MXMMORDRQTY
      , ORDERMULTIPLE
      , REPLENISHMENTMETHOD
      , SHRINKAGEFACTOR
      , PRCHSNGLDTM
      , MNFCTRNGFXDLDTM
      , MNFCTRNGVRBLLDTM
      , STAGINGLDTME
      , PLNNNGTMFNCDYS
      , DMNDTMFNCPRDS
      , INCLDDINPLNNNG
      , CALCULATEATP
      , AUTOCHKATP
      , PLNFNLPAB
      , FRCSTCNSMPTNPRD
      , ORDRUPTOLVL
      , SFTYSTCKQTY
      , REORDERVARIANCE
      , PORECEIPTBIN
      , PORETRNBIN
      , SOFULFILLMENTBIN
      , SORETURNBIN
      , BOMRCPTBIN
      , MATERIALISSUEBIN
      , MORECEIPTBIN
      , REPAIRISSUESBIN
      , REPLENISHMENTLEVEL
      , POPORDERMETHOD
      , MASTERLOCATIONCODE
      , POPVENDORSELECTION
      , POPPRICINGSELECTION
      , PURCHASEPRICE
      , INCLUDEALLOCATIONS
      , INCLUDEBACKORDERS
      , INCLUDEREQUISITIONS
      , PICKTICKETITEMOPT
      , DEX_ROW_ID
      , PSA_LOAD_DTS
      , PSA_RECORD_SOURCE
      , PSA_DELETE_IND
      , LOAD_DTS
      , REC_SRC
      , HASHDIFF
    FROM LOGIC_SPITTGP
)
---- FILTER LAYER ----

, FILTER_SPITTGP as (
    SELECT *
    FROM RENAME_SPITTGP
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM FILTER_SPITTGP
)

---- FINAL LAYER ----
SELECT
          PLANT_ITEM_HK
        , ITEMNMBR
        , LOCNCODE
        , BINNMBR
        , RCRDTYPE
        , PRIMVNDR
        , ITMFRFLG
        , BGNGQTY
        , LSORDQTY
        , LRCPTQTY
        , LSTORDDT
        , LSORDVND
        , LSRCPTDT
        , QTYRQSTN
        , QTYONORD
        , QTYBKORD
        , QTY_DROP_SHIPPED
        , QTYINUSE
        , QTYINSVC
        , QTYRTRND
        , QTYDMGED
        , QTYONHND
        , ATYALLOC
        , QTYCOMTD
        , QTYSOLD
        , NXTCNTDT
        , NXTCNTTM
        , LSTCNTDT
        , LSTCNTTM
        , STCKCNTINTRVL
        , LANDED_COST_GROUP_ID
        , BUYERID
        , PLANNERID
        , ORDERPOLICY
        , FXDORDRQTY
        , ORDRPNTQTY
        , NMBROFDYS
        , MNMMORDRQTY
        , MXMMORDRQTY
        , ORDERMULTIPLE
        , REPLENISHMENTMETHOD
        , SHRINKAGEFACTOR
        , PRCHSNGLDTM
        , MNFCTRNGFXDLDTM
        , MNFCTRNGVRBLLDTM
        , STAGINGLDTME
        , PLNNNGTMFNCDYS
        , DMNDTMFNCPRDS
        , INCLDDINPLNNNG
        , CALCULATEATP
        , AUTOCHKATP
        , PLNFNLPAB
        , FRCSTCNSMPTNPRD
        , ORDRUPTOLVL
        , SFTYSTCKQTY
        , REORDERVARIANCE
        , PORECEIPTBIN
        , PORETRNBIN
        , SOFULFILLMENTBIN
        , SORETURNBIN
        , BOMRCPTBIN
        , MATERIALISSUEBIN
        , MORECEIPTBIN
        , REPAIRISSUESBIN
        , REPLENISHMENTLEVEL
        , POPORDERMETHOD
        , MASTERLOCATIONCODE
        , POPVENDORSELECTION
        , POPPRICINGSELECTION
        , PURCHASEPRICE
        , INCLUDEALLOCATIONS
        , INCLUDEBACKORDERS
        , INCLUDEREQUISITIONS
        , PICKTICKETITEMOPT
        , DEX_ROW_ID
        , PSA_LOAD_DTS
        , PSA_RECORD_SOURCE
        , PSA_DELETE_IND
        , LOAD_DTS
        , REC_SRC
        , HASHDIFF
FROM JOIN_RESULT
{% if is_incremental() %}
WHERE NOT EXISTS (
    SELECT 1 
    FROM {{ this }} existing
    WHERE existing.PLANT_ITEM_HK= JOIN_RESULT.PLANT_ITEM_HK
    AND existing.HASHDIFF = JOIN_RESULT.HASHDIFF
)
{% endif %}
{% if not is_incremental() %}

/* The following qualifier is implemented to prevent multiple loads of touched records during the initial build, such as multiple rows per HK and hashdiff. */
qualify 1 = row_number() over (partition by PLANT_ITEM_HK, LANDED_COST_GROUP_ID, DEX_ROW_ID, HASHDIFF order by PSA_LOAD_DTS)

union all
SELECT 
MD5_BINARY(GR.VALUE) AS PLANT_ITEM_HK,
GR.VALUE::text AS ITEMNMBR,
GR.VALUE::text AS LOCNCODE,
NULL AS BINNMBR,
NULL AS RCRDTYPE,
NULL AS PRIMVNDR,
NULL AS ITMFRFLG,
NULL AS BGNGQTY,
NULL AS LSORDQTY,
NULL AS LRCPTQTY,
NULL AS LSTORDDT,
NULL AS LSORDVND,
NULL AS LSRCPTDT,
NULL AS QTYRQSTN,
NULL AS QTYONORD,
NULL AS QTYBKORD,
NULL AS QTY_DROP_SHIPPED,
NULL AS QTYINUSE,
NULL AS QTYINSVC,
NULL AS QTYRTRND,
NULL AS QTYDMGED,
NULL AS QTYONHND,
NULL AS ATYALLOC,
NULL AS QTYCOMTD,
NULL AS QTYSOLD,
NULL AS NXTCNTDT,
NULL AS NXTCNTTM,
NULL AS LSTCNTDT,
NULL AS LSTCNTTM,
NULL AS STCKCNTINTRVL,
NULL AS LANDED_COST_GROUP_ID,
NULL AS BUYERID,
NULL AS PLANNERID,
NULL AS ORDERPOLICY,
NULL AS FXDORDRQTY,
NULL AS ORDRPNTQTY,
NULL AS NMBROFDYS,
NULL AS MNMMORDRQTY,
NULL AS MXMMORDRQTY,
NULL AS ORDERMULTIPLE,
NULL AS REPLENISHMENTMETHOD,
NULL AS SHRINKAGEFACTOR,
NULL AS PRCHSNGLDTM,
NULL AS MNFCTRNGFXDLDTM,
NULL AS MNFCTRNGVRBLLDTM,
NULL AS STAGINGLDTME,
NULL AS PLNNNGTMFNCDYS,
NULL AS DMNDTMFNCPRDS,
NULL AS INCLDDINPLNNNG,
NULL AS CALCULATEATP,
NULL AS AUTOCHKATP,
NULL AS PLNFNLPAB,
NULL AS FRCSTCNSMPTNPRD,
NULL AS ORDRUPTOLVL,
NULL AS SFTYSTCKQTY,
NULL AS REORDERVARIANCE,
NULL AS PORECEIPTBIN,
NULL AS PORETRNBIN,
NULL AS SOFULFILLMENTBIN,
NULL AS SORETURNBIN,
NULL AS BOMRCPTBIN,
NULL AS MATERIALISSUEBIN,
NULL AS MORECEIPTBIN,
NULL AS REPAIRISSUESBIN,
NULL AS REPLENISHMENTLEVEL,
NULL AS POPORDERMETHOD,
NULL AS MASTERLOCATIONCODE,
NULL AS POPVENDORSELECTION,
NULL AS POPPRICINGSELECTION,
NULL AS PURCHASEPRICE,
NULL AS INCLUDEALLOCATIONS,
NULL AS INCLUDEBACKORDERS,
NULL AS INCLUDEREQUISITIONS,
NULL AS PICKTICKETITEMOPT,
NULL AS DEX_ROW_ID,
'1900-01-01'::TIMESTAMP AS PSA_LOAD_DTS,
NULL AS PSA_RECORD_SOURCE,
'N' AS PSA_DELETE_IND,
CONVERT_TIMEZONE('UTC','1900-01-01'::TIMESTAMP) AS LOAD_DTS,
'USAZET.SNOWFLAKE.FBIN.DERIVED' AS REC_SRC,
''::BINARY AS HASHDIFF
FROM
TABLE(strtok_split_to_table('0|-1|-2', '|')) AS GR
{% endif %}
