---- SRC LAYER ----
WITH
SRC_sml            as ( SELECT * FROM {{ ref('v_psa_stg_payment_terms_lines__ml_ebs') }} as SRC 
                         {% if is_incremental() %}
                              where src.load_dts > (select dateadd('HOUR',-1,max(load_dts)) from {{ this }})
                            {% endif %}   )

/*
SRC_sml            as ( SELECT * FROM staging.v_psa_stg_payment_terms_lines__ml_ebs )
*/
---- LOGIC LAYER ----

, LOGIC_sml as (
    SELECT
        PAYMENT_TERM_HK
      , TERM_ID
      , SEQUENCE_NUM
      , ATTRIBUTE10
      , DISCOUNT_AMOUNT_3
      , DISCOUNT_AMOUNT_2
      , DISCOUNT_CRITERIA_3
      , DISCOUNT_CRITERIA_2
      , DISCOUNT_PERCENT_3
      , ATTRIBUTE14
      , DISCOUNT_PERCENT_2
      , ATTRIBUTE13
      , ATTRIBUTE12
      , ATTRIBUTE11
      , DISCOUNT_MONTHS_FORWARD_2
      , DISCOUNT_MONTHS_FORWARD_3
      , DUE_AMOUNT
      , FIXED_DATE
      , LAST_UPDATE_DATE
      , DUE_PERCENT
      , DISCOUNT_PERCENT
      , DISCOUNT_DAYS
      , DISCOUNT_DAY_OF_MONTH_2
      , DISCOUNT_DAY_OF_MONTH_3
      , DISCOUNT_CRITERIA
      , CREATED_BY
      , DISCOUNT_MONTHS_FORWARD
      , DISCOUNT_DAYS_3
      , ATTRIBUTE3
      , LAST_UPDATED_BY
      , DISCOUNT_DAYS_2
      , ATTRIBUTE2
      , ATTRIBUTE1
      , CREATION_DATE
      , ATTRIBUTE9
      , LAST_UPDATE_LOGIN
      , ATTRIBUTE8
      , ATTRIBUTE7
      , ATTRIBUTE6
      , DUE_MONTHS_FORWARD
      , ATTRIBUTE5
      , ATTRIBUTE4
      , DISCOUNT_DAY_OF_MONTH
      , ATTRIBUTE_CATEGORY
      , DUE_DAYS
      , DUE_DAY_OF_MONTH
      , DISCOUNT_AMOUNT
      , CALENDAR
      , ATTRIBUTE15
      , _FIVETRAN_ID
      , _FIVETRAN_DELETED
      , _FIVETRAN_SYNCED
      , PSA_LOAD_DTS
      , PSA_RECORD_SOURCE
      , PSA_DELETE_IND
      , LOAD_DTS
      , REC_SRC
      , BKCC
      , HASHDIFF
    FROM SRC_sml
)
---- RENAME LAYER ----

, RENAME_sml as (
    SELECT
        PAYMENT_TERM_HK
      , TERM_ID
      , SEQUENCE_NUM
      , ATTRIBUTE10
      , DISCOUNT_AMOUNT_3
      , DISCOUNT_AMOUNT_2
      , DISCOUNT_CRITERIA_3
      , DISCOUNT_CRITERIA_2
      , DISCOUNT_PERCENT_3
      , ATTRIBUTE14
      , DISCOUNT_PERCENT_2
      , ATTRIBUTE13
      , ATTRIBUTE12
      , ATTRIBUTE11
      , DISCOUNT_MONTHS_FORWARD_2
      , DISCOUNT_MONTHS_FORWARD_3
      , DUE_AMOUNT
      , FIXED_DATE
      , LAST_UPDATE_DATE
      , DUE_PERCENT
      , DISCOUNT_PERCENT
      , DISCOUNT_DAYS
      , DISCOUNT_DAY_OF_MONTH_2
      , DISCOUNT_DAY_OF_MONTH_3
      , DISCOUNT_CRITERIA
      , CREATED_BY
      , DISCOUNT_MONTHS_FORWARD
      , DISCOUNT_DAYS_3
      , ATTRIBUTE3
      , LAST_UPDATED_BY
      , DISCOUNT_DAYS_2
      , ATTRIBUTE2
      , ATTRIBUTE1
      , CREATION_DATE
      , ATTRIBUTE9
      , LAST_UPDATE_LOGIN
      , ATTRIBUTE8
      , ATTRIBUTE7
      , ATTRIBUTE6
      , DUE_MONTHS_FORWARD
      , ATTRIBUTE5
      , ATTRIBUTE4
      , DISCOUNT_DAY_OF_MONTH
      , ATTRIBUTE_CATEGORY
      , DUE_DAYS
      , DUE_DAY_OF_MONTH
      , DISCOUNT_AMOUNT
      , CALENDAR
      , ATTRIBUTE15
      , _FIVETRAN_ID
      , _FIVETRAN_DELETED
      , _FIVETRAN_SYNCED
      , PSA_LOAD_DTS
      , PSA_RECORD_SOURCE
      , PSA_DELETE_IND
      , LOAD_DTS
      , REC_SRC
      , BKCC
      , HASHDIFF
    FROM LOGIC_sml
)
---- FILTER LAYER ----

, FILTER_sml as (
    SELECT *
    FROM RENAME_sml
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM FILTER_sml
)

---- FINAL LAYER ----
SELECT
          PAYMENT_TERM_HK
        , TERM_ID
        , SEQUENCE_NUM
        , ATTRIBUTE10
        , DISCOUNT_AMOUNT_3
        , DISCOUNT_AMOUNT_2
        , DISCOUNT_CRITERIA_3
        , DISCOUNT_CRITERIA_2
        , DISCOUNT_PERCENT_3
        , ATTRIBUTE14
        , DISCOUNT_PERCENT_2
        , ATTRIBUTE13
        , ATTRIBUTE12
        , ATTRIBUTE11
        , DISCOUNT_MONTHS_FORWARD_2
        , DISCOUNT_MONTHS_FORWARD_3
        , DUE_AMOUNT
        , FIXED_DATE
        , LAST_UPDATE_DATE
        , DUE_PERCENT
        , DISCOUNT_PERCENT
        , DISCOUNT_DAYS
        , DISCOUNT_DAY_OF_MONTH_2
        , DISCOUNT_DAY_OF_MONTH_3
        , DISCOUNT_CRITERIA
        , CREATED_BY
        , DISCOUNT_MONTHS_FORWARD
        , DISCOUNT_DAYS_3
        , ATTRIBUTE3
        , LAST_UPDATED_BY
        , DISCOUNT_DAYS_2
        , ATTRIBUTE2
        , ATTRIBUTE1
        , CREATION_DATE
        , ATTRIBUTE9
        , LAST_UPDATE_LOGIN
        , ATTRIBUTE8
        , ATTRIBUTE7
        , ATTRIBUTE6
        , DUE_MONTHS_FORWARD
        , ATTRIBUTE5
        , ATTRIBUTE4
        , DISCOUNT_DAY_OF_MONTH
        , ATTRIBUTE_CATEGORY
        , DUE_DAYS
        , DUE_DAY_OF_MONTH
        , DISCOUNT_AMOUNT
        , CALENDAR
        , ATTRIBUTE15
        , _FIVETRAN_ID
        , _FIVETRAN_DELETED
        , _FIVETRAN_SYNCED
        , PSA_LOAD_DTS
        , PSA_RECORD_SOURCE
        , PSA_DELETE_IND
        , LOAD_DTS
        , REC_SRC
        , BKCC
        , HASHDIFF
FROM JOIN_RESULT
{% if is_incremental() %}
WHERE NOT EXISTS (
    SELECT 1 
    FROM {{ this }} existing
    WHERE existing.PAYMENT_TERM_HK = JOIN_RESULT.PAYMENT_TERM_HK
    AND existing.SEQUENCE_NUM = JOIN_RESULT.SEQUENCE_NUM
    AND existing.HASHDIFF = JOIN_RESULT.HASHDIFF
)
{% endif %}
{% if not is_incremental() %}

/* The following qualifier is implemented to prevent multiple loads of touched records during the initial build, such as multiple rows per HK and hashdiff. */
qualify 1 = row_number() over (partition by PAYMENT_TERM_HK, SEQUENCE_NUM, HASHDIFF order by PSA_LOAD_DTS)

union all
SELECT 
MD5_BINARY(GR.VALUE) AS PAYMENT_TERM_HK,
GR.VALUE::number AS TERM_ID,
GR.VALUE::number AS SEQUENCE_NUM,
NULL AS ATTRIBUTE10,
NULL AS DISCOUNT_AMOUNT_3,
NULL AS DISCOUNT_AMOUNT_2,
NULL AS DISCOUNT_CRITERIA_3,
NULL AS DISCOUNT_CRITERIA_2,
NULL AS DISCOUNT_PERCENT_3,
NULL AS ATTRIBUTE14,
NULL AS DISCOUNT_PERCENT_2,
NULL AS ATTRIBUTE13,
NULL AS ATTRIBUTE12,
NULL AS ATTRIBUTE11,
NULL AS DISCOUNT_MONTHS_FORWARD_2,
NULL AS DISCOUNT_MONTHS_FORWARD_3,
NULL AS DUE_AMOUNT,
NULL AS FIXED_DATE,
NULL AS LAST_UPDATE_DATE,
NULL AS DUE_PERCENT,
NULL AS DISCOUNT_PERCENT,
NULL AS DISCOUNT_DAYS,
NULL AS DISCOUNT_DAY_OF_MONTH_2,
NULL AS DISCOUNT_DAY_OF_MONTH_3,
NULL AS DISCOUNT_CRITERIA,
NULL AS CREATED_BY,
NULL AS DISCOUNT_MONTHS_FORWARD,
NULL AS DISCOUNT_DAYS_3,
NULL AS ATTRIBUTE3,
NULL AS LAST_UPDATED_BY,
NULL AS DISCOUNT_DAYS_2,
NULL AS ATTRIBUTE2,
NULL AS ATTRIBUTE1,
NULL AS CREATION_DATE,
NULL AS ATTRIBUTE9,
NULL AS LAST_UPDATE_LOGIN,
NULL AS ATTRIBUTE8,
NULL AS ATTRIBUTE7,
NULL AS ATTRIBUTE6,
NULL AS DUE_MONTHS_FORWARD,
NULL AS ATTRIBUTE5,
NULL AS ATTRIBUTE4,
NULL AS DISCOUNT_DAY_OF_MONTH,
NULL AS ATTRIBUTE_CATEGORY,
NULL AS DUE_DAYS,
NULL AS DUE_DAY_OF_MONTH,
NULL AS DISCOUNT_AMOUNT,
NULL AS CALENDAR,
NULL AS ATTRIBUTE15,
NULL AS _FIVETRAN_ID,
NULL AS _FIVETRAN_DELETED,
NULL AS _FIVETRAN_SYNCED,
'1900-01-01'::TIMESTAMP AS PSA_LOAD_DTS,
NULL AS PSA_RECORD_SOURCE,
'N' AS PSA_DELETE_IND,
CONVERT_TIMEZONE('UTC','1900-01-01'::TIMESTAMP) AS LOAD_DTS,
'USAZET.SNOWFLAKE.FBIN.DERIVED' AS REC_SRC,
DECODE(GR.VALUE, 0, 'GHOST RECORD-SYSTEM', -1, 'GHOST RECORD-nullkey-required', -2, 'GHOST RECORD-nullkey-optional') AS BKCC,
''::BINARY AS HASHDIFF
FROM
TABLE(strtok_split_to_table('0|-1|-2', '|')) AS GR
{% endif %}
