---- SRC LAYER ----
WITH
SRC_SRC            as ( SELECT * FROM {{ ref('v_psa_stg_po_item_schedule_lines__ml_ebs') }} as SRC 
{% if is_incremental() %}
      where src.load_dts > (select dateadd('HOUR',-1,max(load_dts)) from {{ this }})
    {% endif %} )

/*
SRC_SRC            as ( SELECT * FROM int_staging_views.v_psa_stg_po_item_schedule_lines__ml_ebs )
*/
---- LOGIC LAYER ----

, LOGIC_SRC as (
    SELECT
        PO_ITEM_HK
      , PO_HEADER_ID
      , LINE_NUM
      , LINE_LOCATION_ID
      , ORG_ID
      , FREIGHT_TERMS_LOOKUP_CODE
      , APPROVED_FLAG
      , ESTIMATED_TAX_AMOUNT
      , PROGRAM_ID
      , GLOBAL_ATTRIBUTE5
      , UDA_TEMPLATE_ID
      , BID_PAYMENT_ID
      , GLOBAL_ATTRIBUTE4
      , QUANTITY_ACCEPTED
      , GLOBAL_ATTRIBUTE7
      , GLOBAL_ATTRIBUTE6
      , GLOBAL_ATTRIBUTE1
      , QUANTITY_RECOUPED
      , PRICE_OVERRIDE
      , AMOUNT
      , GLOBAL_ATTRIBUTE3
      , GLOBAL_ATTRIBUTE2
      , FROM_LINE_LOCATION_ID
      , TAX_USER_OVERRIDE_FLAG
      , AMOUNT_ACCEPTED
      , GLOBAL_ATTRIBUTE9
      , GLOBAL_ATTRIBUTE8
      , ATTRIBUTE3
      , ATTRIBUTE2
      , DAYS_LATE_RECEIPT_ALLOWED
      , ATTRIBUTE1
      , ATTRIBUTE9
      , SALES_ORDER_UPDATE_DATE
      , ATTRIBUTE8
      , ATTRIBUTE7
      , USSGL_TRANSACTION_CODE
      , ATTRIBUTE6
      , QTY_RCV_EXCEPTION_CODE
      , ATTRIBUTE5
      , UNENCUMBERED_QUANTITY
      , ATTRIBUTE4
      , AMOUNT_BILLED
      , LEAD_TIME
      , SECONDARY_UNIT_OF_MEASURE
      , RECEIVE_CLOSE_TOLERANCE
      , ATTRIBUTE10
      , ATTRIBUTE14
      , ATTRIBUTE13
      , ATTRIBUTE12
      , ATTRIBUTE11
      , COUNTRY_OF_ORIGIN_CODE
      , SUPPLIER_ORDER_LINE_NUMBER
      , DROP_SHIP_FLAG
      , CANCEL_REASON
      , FROM_LINE_ID
      , TAX_CODE_ID
      , WORK_APPROVER_ID
      , DESCRIPTION
      , CLOSED_BY
      , TAX_NAME
      , QUANTITY_CANCELLED
      , FROM_HEADER_ID
      , CLOSED_FLAG
      , FIRM_DATE
      , GLOBAL_ATTRIBUTE20
      , START_DATE
      , SOURCE_SHIPMENT_ID
      , GLOBAL_ATTRIBUTE17
      , RETAINAGE_RELEASED_AMOUNT
      , GLOBAL_ATTRIBUTE18
      , CANCEL_FLAG
      , GLOBAL_ATTRIBUTE15
      , GLOBAL_ATTRIBUTE16
      , GLOBAL_ATTRIBUTE13
      , PO_HEADER_BK
      , GLOBAL_ATTRIBUTE14
      , GLOBAL_ATTRIBUTE11
      , GLOBAL_ATTRIBUTE12
      , CHANGE_PROMISED_DATE_REASON
      , ATTRIBUTE15
      , RECEIVING_ROUTING_ID
      , TAXABLE_FLAG
      , PRICE_DISCOUNT
      , SHIPMENT_TYPE
      , GLOBAL_ATTRIBUTE19
      , ORIGINAL_SHIPMENT_ID
      , CLOSED_REASON
      , QUANTITY
      , TRANSACTION_FLOW_HEADER_ID
      , END_DATE
      , GLOBAL_ATTRIBUTE10
      , ACCRUE_ON_RECEIPT_FLAG
      , LCM_FLAG
      , QUANTITY_RECEIVED
      , INSPECTION_REQUIRED_FLAG
      , SHIP_TO_LOCATION_ID
      , AMOUNT_RECEIVED
      , CREATED_BY
      , QUANTITY_SHIPPED
      , LAST_UPDATED_BY
      , CANCELLED_BY
      , SECONDARY_QUANTITY
      , SECONDARY_QUANTITY_REJECTED
      , RECEIPT_REQUIRED_FLAG
      , SHIPMENT_NUM
      , PO_RELEASE_ID
      , ENFORCE_SHIP_TO_LOCATION_CODE
      , PAYMENT_TYPE
      , TERMS_ID
      , CALCULATE_TAX_FLAG
      , CONSIGNED_FLAG
      , ENCUMBERED_FLAG
      , ATTRIBUTE_CATEGORY
      , PROGRAM_APPLICATION_ID
      , GOVERNMENT_CONTEXT
      , UNIT_MEAS_LOOKUP_CODE
      , PREFERRED_GRADE
      , OUTSOURCED_ASSEMBLY
      , MATCHING_BASIS
      , ALLOW_SUBSTITUTE_RECEIPTS_FLAG
      , SECONDARY_QUANTITY_ACCEPTED
      , QUANTITY_REJECTED
      , AMOUNT_SHIPPED
      , VALUE_BASIS
      , REQUEST_ID
      , VMI_FLAG
      , FIRM_STATUS_LOOKUP_CODE
      , MANUAL_PRICE_CHANGE_FLAG
      , NOTE_TO_RECEIVER
      , SECONDARY_QUANTITY_SHIPPED
      , ENCUMBER_NOW
      , RECEIPT_DAYS_EXCEPTION_CODE
      , INVOICE_CLOSE_TOLERANCE
      , CLOSED_CODE
      , SECONDARY_QUANTITY_RECEIVED
      , LEAD_TIME_UNIT
      , QUANTITY_FINANCED
      , AMOUNT_FINANCED
      , AMOUNT_REJECTED
      , DRAFT_ID
      , QTY_RCV_TOLERANCE
      , UNIT_OF_MEASURE_CLASS
      , TAX_ATTRIBUTE_UPDATE_CODE
      , AMOUNT_RECOUPED
      , ENCUMBERED_DATE
      , SECONDARY_QUANTITY_CANCELLED
      , MATCH_OPTION
      , LAST_UPDATE_LOGIN
      , AMOUNT_CANCELLED
      , GLOBAL_ATTRIBUTE_CATEGORY
      , SHIP_VIA_LOOKUP_CODE
      , FINAL_MATCH_FLAG
      , FOB_LOOKUP_CODE
      , SHIP_TO_ORGANIZATION_ID
      , RETAINAGE_WITHHELD_AMOUNT
      , DAYS_EARLY_RECEIPT_ALLOWED
      , PO_LINE_ID
      , CLOSED_DATE
      , SHIPMENT_CLOSED_DATE
      , CREATION_DATE
      , APPROVED_DATE
      , PROGRAM_UPDATE_DATE
      , CLOSED_FOR_RECEIVING_DATE
      , NEED_BY_DATE
      , LAST_ACCEPT_DATE
      , CANCEL_DATE
      , CLOSED_FOR_INVOICE_DATE
      , RETROACTIVE_DATE
      , QUANTITY_BILLED
      , PROMISED_DATE
      , LAST_UPDATE_DATE
      , PSA_DELETE_IND
      , PSA_LOAD_DTS
      , PSA_RECORD_SOURCE
      , _FIVETRAN_SYNCED
      , _FIVETRAN_ID
      , _FIVETRAN_DELETED
      , LOAD_DTS
      , REC_SRC
      , BKCC
      , HASHDIFF
    FROM SRC_SRC
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM LOGIC_SRC
)

---- FINAL LAYER ----
SELECT
          PO_ITEM_HK
        , PO_HEADER_ID
        , LINE_NUM
        , LINE_LOCATION_ID
        , ORG_ID
        , FREIGHT_TERMS_LOOKUP_CODE
        , APPROVED_FLAG
        , ESTIMATED_TAX_AMOUNT
        , PROGRAM_ID
        , GLOBAL_ATTRIBUTE5
        , UDA_TEMPLATE_ID
        , BID_PAYMENT_ID
        , GLOBAL_ATTRIBUTE4
        , QUANTITY_ACCEPTED
        , GLOBAL_ATTRIBUTE7
        , GLOBAL_ATTRIBUTE6
        , GLOBAL_ATTRIBUTE1
        , QUANTITY_RECOUPED
        , PRICE_OVERRIDE
        , AMOUNT
        , GLOBAL_ATTRIBUTE3
        , GLOBAL_ATTRIBUTE2
        , FROM_LINE_LOCATION_ID
        , TAX_USER_OVERRIDE_FLAG
        , AMOUNT_ACCEPTED
        , GLOBAL_ATTRIBUTE9
        , GLOBAL_ATTRIBUTE8
        , ATTRIBUTE3
        , ATTRIBUTE2
        , DAYS_LATE_RECEIPT_ALLOWED
        , ATTRIBUTE1
        , ATTRIBUTE9
        , SALES_ORDER_UPDATE_DATE
        , ATTRIBUTE8
        , ATTRIBUTE7
        , USSGL_TRANSACTION_CODE
        , ATTRIBUTE6
        , QTY_RCV_EXCEPTION_CODE
        , ATTRIBUTE5
        , UNENCUMBERED_QUANTITY
        , ATTRIBUTE4
        , AMOUNT_BILLED
        , LEAD_TIME
        , SECONDARY_UNIT_OF_MEASURE
        , RECEIVE_CLOSE_TOLERANCE
        , ATTRIBUTE10
        , ATTRIBUTE14
        , ATTRIBUTE13
        , ATTRIBUTE12
        , ATTRIBUTE11
        , COUNTRY_OF_ORIGIN_CODE
        , SUPPLIER_ORDER_LINE_NUMBER
        , DROP_SHIP_FLAG
        , CANCEL_REASON
        , FROM_LINE_ID
        , TAX_CODE_ID
        , WORK_APPROVER_ID
        , DESCRIPTION
        , CLOSED_BY
        , TAX_NAME
        , QUANTITY_CANCELLED
        , FROM_HEADER_ID
        , CLOSED_FLAG
        , FIRM_DATE
        , GLOBAL_ATTRIBUTE20
        , START_DATE
        , SOURCE_SHIPMENT_ID
        , GLOBAL_ATTRIBUTE17
        , RETAINAGE_RELEASED_AMOUNT
        , GLOBAL_ATTRIBUTE18
        , CANCEL_FLAG
        , GLOBAL_ATTRIBUTE15
        , GLOBAL_ATTRIBUTE16
        , GLOBAL_ATTRIBUTE13
        , PO_HEADER_BK
        , GLOBAL_ATTRIBUTE14
        , GLOBAL_ATTRIBUTE11
        , GLOBAL_ATTRIBUTE12
        , CHANGE_PROMISED_DATE_REASON
        , ATTRIBUTE15
        , RECEIVING_ROUTING_ID
        , TAXABLE_FLAG
        , PRICE_DISCOUNT
        , SHIPMENT_TYPE
        , GLOBAL_ATTRIBUTE19
        , ORIGINAL_SHIPMENT_ID
        , CLOSED_REASON
        , QUANTITY
        , TRANSACTION_FLOW_HEADER_ID
        , END_DATE
        , GLOBAL_ATTRIBUTE10
        , ACCRUE_ON_RECEIPT_FLAG
        , LCM_FLAG
        , QUANTITY_RECEIVED
        , INSPECTION_REQUIRED_FLAG
        , SHIP_TO_LOCATION_ID
        , AMOUNT_RECEIVED
        , CREATED_BY
        , QUANTITY_SHIPPED
        , LAST_UPDATED_BY
        , CANCELLED_BY
        , SECONDARY_QUANTITY
        , SECONDARY_QUANTITY_REJECTED
        , RECEIPT_REQUIRED_FLAG
        , SHIPMENT_NUM
        , PO_RELEASE_ID
        , ENFORCE_SHIP_TO_LOCATION_CODE
        , PAYMENT_TYPE
        , TERMS_ID
        , CALCULATE_TAX_FLAG
        , CONSIGNED_FLAG
        , ENCUMBERED_FLAG
        , ATTRIBUTE_CATEGORY
        , PROGRAM_APPLICATION_ID
        , GOVERNMENT_CONTEXT
        , UNIT_MEAS_LOOKUP_CODE
        , PREFERRED_GRADE
        , OUTSOURCED_ASSEMBLY
        , MATCHING_BASIS
        , ALLOW_SUBSTITUTE_RECEIPTS_FLAG
        , SECONDARY_QUANTITY_ACCEPTED
        , QUANTITY_REJECTED
        , AMOUNT_SHIPPED
        , VALUE_BASIS
        , REQUEST_ID
        , VMI_FLAG
        , FIRM_STATUS_LOOKUP_CODE
        , MANUAL_PRICE_CHANGE_FLAG
        , NOTE_TO_RECEIVER
        , SECONDARY_QUANTITY_SHIPPED
        , ENCUMBER_NOW
        , RECEIPT_DAYS_EXCEPTION_CODE
        , INVOICE_CLOSE_TOLERANCE
        , CLOSED_CODE
        , SECONDARY_QUANTITY_RECEIVED
        , LEAD_TIME_UNIT
        , QUANTITY_FINANCED
        , AMOUNT_FINANCED
        , AMOUNT_REJECTED
        , DRAFT_ID
        , QTY_RCV_TOLERANCE
        , UNIT_OF_MEASURE_CLASS
        , TAX_ATTRIBUTE_UPDATE_CODE
        , AMOUNT_RECOUPED
        , ENCUMBERED_DATE
        , SECONDARY_QUANTITY_CANCELLED
        , MATCH_OPTION
        , LAST_UPDATE_LOGIN
        , AMOUNT_CANCELLED
        , GLOBAL_ATTRIBUTE_CATEGORY
        , SHIP_VIA_LOOKUP_CODE
        , FINAL_MATCH_FLAG
        , FOB_LOOKUP_CODE
        , SHIP_TO_ORGANIZATION_ID
        , RETAINAGE_WITHHELD_AMOUNT
        , DAYS_EARLY_RECEIPT_ALLOWED
        , PO_LINE_ID
        , CLOSED_DATE
        , SHIPMENT_CLOSED_DATE
        , CREATION_DATE
        , APPROVED_DATE
        , PROGRAM_UPDATE_DATE
        , CLOSED_FOR_RECEIVING_DATE
        , NEED_BY_DATE
        , LAST_ACCEPT_DATE
        , CANCEL_DATE
        , CLOSED_FOR_INVOICE_DATE
        , RETROACTIVE_DATE
        , QUANTITY_BILLED
        , PROMISED_DATE
        , LAST_UPDATE_DATE
        , PSA_DELETE_IND
        , PSA_LOAD_DTS
        , PSA_RECORD_SOURCE
        , _FIVETRAN_SYNCED
        , _FIVETRAN_ID
        , _FIVETRAN_DELETED
        , LOAD_DTS
        , REC_SRC
        , BKCC
        , HASHDIFF
FROM JOIN_RESULT
{% if is_incremental() %}
WHERE NOT EXISTS (
    SELECT 1
    FROM {{ this }} existing
    WHERE existing.PO_ITEM_HK = JOIN_RESULT.PO_ITEM_HK
      AND existing.LINE_LOCATION_ID = JOIN_RESULT.LINE_LOCATION_ID
      AND existing.HASHDIFF = JOIN_RESULT.HASHDIFF
)
{% endif %}
{% if not is_incremental() %}

/* The following qualifier is implemented to prevent multiple loads of touched records during the initial build, such as multiple rows per HK and hashdiff. */
qualify 1 = row_number() over (partition by PO_ITEM_HK, LINE_LOCATION_ID, HASHDIFF order by PSA_LOAD_DTS)

union all
SELECT 
MD5_BINARY(GR.VALUE) AS PO_ITEM_HK,
GR.VALUE::number AS PO_HEADER_ID,
GR.VALUE::number AS LINE_NUM,
GR.VALUE::number AS LINE_LOCATION_ID,
NULL AS ORG_ID,
NULL AS FREIGHT_TERMS_LOOKUP_CODE,
NULL AS APPROVED_FLAG,
NULL AS ESTIMATED_TAX_AMOUNT,
NULL AS PROGRAM_ID,
NULL AS GLOBAL_ATTRIBUTE5,
NULL AS UDA_TEMPLATE_ID,
NULL AS BID_PAYMENT_ID,
NULL AS GLOBAL_ATTRIBUTE4,
NULL AS QUANTITY_ACCEPTED,
NULL AS GLOBAL_ATTRIBUTE7,
NULL AS GLOBAL_ATTRIBUTE6,
NULL AS GLOBAL_ATTRIBUTE1,
NULL AS QUANTITY_RECOUPED,
NULL AS PRICE_OVERRIDE,
NULL AS AMOUNT,
NULL AS GLOBAL_ATTRIBUTE3,
NULL AS GLOBAL_ATTRIBUTE2,
NULL AS FROM_LINE_LOCATION_ID,
NULL AS TAX_USER_OVERRIDE_FLAG,
NULL AS AMOUNT_ACCEPTED,
NULL AS GLOBAL_ATTRIBUTE9,
NULL AS GLOBAL_ATTRIBUTE8,
NULL AS ATTRIBUTE3,
NULL AS ATTRIBUTE2,
NULL AS DAYS_LATE_RECEIPT_ALLOWED,
NULL AS ATTRIBUTE1,
NULL AS ATTRIBUTE9,
NULL AS SALES_ORDER_UPDATE_DATE,
NULL AS ATTRIBUTE8,
NULL AS ATTRIBUTE7,
NULL AS USSGL_TRANSACTION_CODE,
NULL AS ATTRIBUTE6,
NULL AS QTY_RCV_EXCEPTION_CODE,
NULL AS ATTRIBUTE5,
NULL AS UNENCUMBERED_QUANTITY,
NULL AS ATTRIBUTE4,
NULL AS AMOUNT_BILLED,
NULL AS LEAD_TIME,
NULL AS SECONDARY_UNIT_OF_MEASURE,
NULL AS RECEIVE_CLOSE_TOLERANCE,
NULL AS ATTRIBUTE10,
NULL AS ATTRIBUTE14,
NULL AS ATTRIBUTE13,
NULL AS ATTRIBUTE12,
NULL AS ATTRIBUTE11,
NULL AS COUNTRY_OF_ORIGIN_CODE,
NULL AS SUPPLIER_ORDER_LINE_NUMBER,
NULL AS DROP_SHIP_FLAG,
NULL AS CANCEL_REASON,
NULL AS FROM_LINE_ID,
NULL AS TAX_CODE_ID,
NULL AS WORK_APPROVER_ID,
NULL AS DESCRIPTION,
NULL AS CLOSED_BY,
NULL AS TAX_NAME,
NULL AS QUANTITY_CANCELLED,
NULL AS FROM_HEADER_ID,
NULL AS CLOSED_FLAG,
NULL AS FIRM_DATE,
NULL AS GLOBAL_ATTRIBUTE20,
NULL AS START_DATE,
NULL AS SOURCE_SHIPMENT_ID,
NULL AS GLOBAL_ATTRIBUTE17,
NULL AS RETAINAGE_RELEASED_AMOUNT,
NULL AS GLOBAL_ATTRIBUTE18,
NULL AS CANCEL_FLAG,
NULL AS GLOBAL_ATTRIBUTE15,
NULL AS GLOBAL_ATTRIBUTE16,
NULL AS GLOBAL_ATTRIBUTE13,
NULL AS PO_HEADER_BK,
NULL AS GLOBAL_ATTRIBUTE14,
NULL AS GLOBAL_ATTRIBUTE11,
NULL AS GLOBAL_ATTRIBUTE12,
NULL AS CHANGE_PROMISED_DATE_REASON,
NULL AS ATTRIBUTE15,
NULL AS RECEIVING_ROUTING_ID,
NULL AS TAXABLE_FLAG,
NULL AS PRICE_DISCOUNT,
NULL AS SHIPMENT_TYPE,
NULL AS GLOBAL_ATTRIBUTE19,
NULL AS ORIGINAL_SHIPMENT_ID,
NULL AS CLOSED_REASON,
NULL AS QUANTITY,
NULL AS TRANSACTION_FLOW_HEADER_ID,
NULL AS END_DATE,
NULL AS GLOBAL_ATTRIBUTE10,
NULL AS ACCRUE_ON_RECEIPT_FLAG,
NULL AS LCM_FLAG,
NULL AS QUANTITY_RECEIVED,
NULL AS INSPECTION_REQUIRED_FLAG,
NULL AS SHIP_TO_LOCATION_ID,
NULL AS AMOUNT_RECEIVED,
NULL AS CREATED_BY,
NULL AS QUANTITY_SHIPPED,
NULL AS LAST_UPDATED_BY,
NULL AS CANCELLED_BY,
NULL AS SECONDARY_QUANTITY,
NULL AS SECONDARY_QUANTITY_REJECTED,
NULL AS RECEIPT_REQUIRED_FLAG,
NULL AS SHIPMENT_NUM,
NULL AS PO_RELEASE_ID,
NULL AS ENFORCE_SHIP_TO_LOCATION_CODE,
NULL AS PAYMENT_TYPE,
NULL AS TERMS_ID,
NULL AS CALCULATE_TAX_FLAG,
NULL AS CONSIGNED_FLAG,
NULL AS ENCUMBERED_FLAG,
NULL AS ATTRIBUTE_CATEGORY,
NULL AS PROGRAM_APPLICATION_ID,
NULL AS GOVERNMENT_CONTEXT,
NULL AS UNIT_MEAS_LOOKUP_CODE,
NULL AS PREFERRED_GRADE,
NULL AS OUTSOURCED_ASSEMBLY,
NULL AS MATCHING_BASIS,
NULL AS ALLOW_SUBSTITUTE_RECEIPTS_FLAG,
NULL AS SECONDARY_QUANTITY_ACCEPTED,
NULL AS QUANTITY_REJECTED,
NULL AS AMOUNT_SHIPPED,
NULL AS VALUE_BASIS,
NULL AS REQUEST_ID,
NULL AS VMI_FLAG,
NULL AS FIRM_STATUS_LOOKUP_CODE,
NULL AS MANUAL_PRICE_CHANGE_FLAG,
NULL AS NOTE_TO_RECEIVER,
NULL AS SECONDARY_QUANTITY_SHIPPED,
NULL AS ENCUMBER_NOW,
NULL AS RECEIPT_DAYS_EXCEPTION_CODE,
NULL AS INVOICE_CLOSE_TOLERANCE,
NULL AS CLOSED_CODE,
NULL AS SECONDARY_QUANTITY_RECEIVED,
NULL AS LEAD_TIME_UNIT,
NULL AS QUANTITY_FINANCED,
NULL AS AMOUNT_FINANCED,
NULL AS AMOUNT_REJECTED,
NULL AS DRAFT_ID,
NULL AS QTY_RCV_TOLERANCE,
NULL AS UNIT_OF_MEASURE_CLASS,
NULL AS TAX_ATTRIBUTE_UPDATE_CODE,
NULL AS AMOUNT_RECOUPED,
NULL AS ENCUMBERED_DATE,
NULL AS SECONDARY_QUANTITY_CANCELLED,
NULL AS MATCH_OPTION,
NULL AS LAST_UPDATE_LOGIN,
NULL AS AMOUNT_CANCELLED,
NULL AS GLOBAL_ATTRIBUTE_CATEGORY,
NULL AS SHIP_VIA_LOOKUP_CODE,
NULL AS FINAL_MATCH_FLAG,
NULL AS FOB_LOOKUP_CODE,
NULL AS SHIP_TO_ORGANIZATION_ID,
NULL AS RETAINAGE_WITHHELD_AMOUNT,
NULL AS DAYS_EARLY_RECEIPT_ALLOWED,
NULL AS PO_LINE_ID,
NULL AS CLOSED_DATE,
NULL AS SHIPMENT_CLOSED_DATE,
NULL AS CREATION_DATE,
NULL AS APPROVED_DATE,
NULL AS PROGRAM_UPDATE_DATE,
NULL AS CLOSED_FOR_RECEIVING_DATE,
NULL AS NEED_BY_DATE,
NULL AS LAST_ACCEPT_DATE,
NULL AS CANCEL_DATE,
NULL AS CLOSED_FOR_INVOICE_DATE,
NULL AS RETROACTIVE_DATE,
NULL AS QUANTITY_BILLED,
NULL AS PROMISED_DATE,
NULL AS LAST_UPDATE_DATE,
'N' AS PSA_DELETE_IND,
'1900-01-01'::TIMESTAMP AS PSA_LOAD_DTS,
NULL AS PSA_RECORD_SOURCE,
NULL AS _FIVETRAN_SYNCED,
NULL AS _FIVETRAN_ID,
NULL AS _FIVETRAN_DELETED,
'1900-01-01T00:00:00'::TIMESTAMP_NTZ AS LOAD_DTS,
'USAZET.SNOWFLAKE.FBIN.DERIVED' AS REC_SRC,
DECODE(GR.VALUE, 0, 'GHOST RECORD-SYSTEM', -1, 'GHOST RECORD-nullkey-required', -2, 'GHOST RECORD-nullkey-optional') AS BKCC,
MD5_BINARY('') AS HASHDIFF
FROM
TABLE(strtok_split_to_table('0|-1|-2', '|')) AS GR
{% endif %}
