---- SRC LAYER ----
WITH
SRC_SRC            as ( SELECT * FROM {{ ref('v_psa_stg_supplier_site__lrsn_psft') }} as SRC 
{% if is_incremental() %}
      where src.load_dts > (select dateadd('HOUR',-1,max(load_dts)) from {{ this }})
    {% endif %} )

/*
SRC_SRC            as ( SELECT * FROM int_staging_views.v_psa_stg_supplier_site__lrsn_psft )
*/
---- LOGIC LAYER ----

, LOGIC_SRC as (
    SELECT
        SUPPLIER_SITE_HK
      , VNDR_LOC
      , SETID
      , EFFDT
      , VENDOR_ID
      , EFF_STATUS
      , CURRENCY_CD
      , CUR_RT_TYPE
      , FREIGHT_TERMS
      , SHIP_TYPE_ID
      , DISP_METHOD
      , PYMNT_TERMS_CD
      , MATCH_OPT_FLG
      , MATCH_CNTRL_ID
      , MATCH_OPT
      , ERS_ACTION
      , ERS_FLAG
      , VCHR_APPRVL_FLG
      , BUSPROCNAME
      , APPR_RULE_SET
      , BUYER_ID
      , REMIT_SETID
      , REMIT_VENDOR
      , REMIT_LOC
      , REMIT_ADDR_SEQ_NUM
      , ADDR_SEQ_NUM_ORDR
      , PRICE_SETID
      , PRICE_VENDOR
      , PRICE_LOC
      , RETURN_VENDOR
      , RET_ADDR_SEQ_NUM
      , DST_CNTRL_ID
      , PREFERRED_LANGUAGE
      , RFQ_DISP_MTHD
      , CNTRCT_DISP_MTHD
      , PRIMARY_VENDOR
      , PRIM_ADDR_SEQ_NUM
      , SHIPTO_ID
      , SUT_BASE_ID
      , SALETX_TOL_AMT
      , SALETX_TOL_CUR_CD
      , SALETX_TOL_PCT
      , SALETX_TOL_RT_TYPE
      , SALETX_CD_ERS
      , SALES_USE_TX_FLG
      , AUTO_ASN_FLG
      , SALETX_TOL_FLG
      , SHIP_LOC_FLG
      , WTHD_CD
      , WTHD_SW
      , DOC_TYPE
      , DOC_TYPE_FLG
      , RTV_DISPATCH_METH
      , RTV_NOTIFY_METH
      , RTV_DEBIT_OPT
      , VNDR_SBI_FLG
      , SBI_APPROVAL_FLG
      , ACCOUNT
      , ALTACCT
      , DEPTID
      , OPERATING_UNIT
      , PRODUCT
      , FUND_CODE
      , CLASS_FLD
      , PROGRAM_CODE
      , BUDGET_REF
      , AFFILIATE
      , AFFILIATE_INTRA1
      , AFFILIATE_INTRA2
      , CHARTFIELD1
      , CHARTFIELD2
      , CHARTFIELD3
      , PROJECT_ID
      , CONSIGNED_FLAG
      , VCHR_CONSIGN_OPT
      , BANK_ACCT_SEQ_NBR
      , ACCT_TEMPL_FLG
      , PAY_TRM_BSE_DT_DFT
      , RECV_ONLY_MTCH_FLG
      , VCHR_MTCH_ADJ_DFLT
      , ERS_INV_DT_OPT
      , ERS_INV_DT_DFLT
      , ERS_TAX_TYPE_DFLT
      , ERS_TAX_CD_OPT
      , LAST_SBI_NUM
      , SBI_DOC_DFLT
      , SBI_PRINT_OPT
      , VCHR_TAX_ADJ_DFT
      , RTV_VCHR_ADJ_DFLT
      , VAT_SUSPENSION_FLG
      , VAT_ROUND_RULE
      , REPL_DISP_METHOD
      , VNDR_UPN_FLG
      , DISP_CO_FLAG
      , DATE_CALC_BASIS
      , PAY_SCHEDULE_TYPE
      , FEDERAL_INDICATOR
      , TRADING_PARTNER
      , ALC
      , WORKFLOW_OPT
      , PHYSICAL_NATURE
      , VAT_SVC_PERFRM_FLG
      , ULTIMATE_USE_CD
      , ADDR_SEQ_NUM_SHFR
      , POA_REQUIRED
      , ACK_ALERT_DISP
      , ACK_ALERT_SHIP
      , POA_CO_REQUIRED
      , POA_TOL_FLAG
      , POA_SCHED_EARLY
      , POA_SCHED_LATE
      , POA_QTY_OVER
      , POA_QTY_UNDER
      , POA_PRICE_OVER
      , POA_PRICE_UNDER
      , CC_ACCEPT_CC
      , CC_DISP_OPTION
      , CC_ALLOW_OVERRIDE
      , CC_SECURITY_ID
      , CC_USE_FLAG
      , MATCH_DELAY_FLG
      , MATCH_DELAY_DAYS
      , DISBURSING_OFFICE
      , GEN_1099_RPT
      , SPLIT_PO_BY_SHIPTO
      , SPEEDCHART_KEY
      , ACCOUNT_CODE
      , UPN_TYPE_CD
      , DAYS_HRS_AFTER
      , DAYS_HRS_BEFORE
      , COMMENTS_2000
      , PSA_DELETE_IND
      , PSA_LOAD_DTS
      , PSA_RECORD_SOURCE
      , _FIVETRAN_SYNCED
      , _FIVETRAN_ID
      , _FIVETRAN_DELETED
      , LOAD_DTS
      , REC_SRC
      , BKCC
      , HASHDIFF
    FROM SRC_SRC
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM LOGIC_SRC
)

---- FINAL LAYER ----
SELECT
          SUPPLIER_SITE_HK
        , VNDR_LOC
        , SETID
        , EFFDT
        , VENDOR_ID
        , EFF_STATUS
        , CURRENCY_CD
        , CUR_RT_TYPE
        , FREIGHT_TERMS
        , SHIP_TYPE_ID
        , DISP_METHOD
        , PYMNT_TERMS_CD
        , MATCH_OPT_FLG
        , MATCH_CNTRL_ID
        , MATCH_OPT
        , ERS_ACTION
        , ERS_FLAG
        , VCHR_APPRVL_FLG
        , BUSPROCNAME
        , APPR_RULE_SET
        , BUYER_ID
        , REMIT_SETID
        , REMIT_VENDOR
        , REMIT_LOC
        , REMIT_ADDR_SEQ_NUM
        , ADDR_SEQ_NUM_ORDR
        , PRICE_SETID
        , PRICE_VENDOR
        , PRICE_LOC
        , RETURN_VENDOR
        , RET_ADDR_SEQ_NUM
        , DST_CNTRL_ID
        , PREFERRED_LANGUAGE
        , RFQ_DISP_MTHD
        , CNTRCT_DISP_MTHD
        , PRIMARY_VENDOR
        , PRIM_ADDR_SEQ_NUM
        , SHIPTO_ID
        , SUT_BASE_ID
        , SALETX_TOL_AMT
        , SALETX_TOL_CUR_CD
        , SALETX_TOL_PCT
        , SALETX_TOL_RT_TYPE
        , SALETX_CD_ERS
        , SALES_USE_TX_FLG
        , AUTO_ASN_FLG
        , SALETX_TOL_FLG
        , SHIP_LOC_FLG
        , WTHD_CD
        , WTHD_SW
        , DOC_TYPE
        , DOC_TYPE_FLG
        , RTV_DISPATCH_METH
        , RTV_NOTIFY_METH
        , RTV_DEBIT_OPT
        , VNDR_SBI_FLG
        , SBI_APPROVAL_FLG
        , ACCOUNT
        , ALTACCT
        , DEPTID
        , OPERATING_UNIT
        , PRODUCT
        , FUND_CODE
        , CLASS_FLD
        , PROGRAM_CODE
        , BUDGET_REF
        , AFFILIATE
        , AFFILIATE_INTRA1
        , AFFILIATE_INTRA2
        , CHARTFIELD1
        , CHARTFIELD2
        , CHARTFIELD3
        , PROJECT_ID
        , CONSIGNED_FLAG
        , VCHR_CONSIGN_OPT
        , BANK_ACCT_SEQ_NBR
        , ACCT_TEMPL_FLG
        , PAY_TRM_BSE_DT_DFT
        , RECV_ONLY_MTCH_FLG
        , VCHR_MTCH_ADJ_DFLT
        , ERS_INV_DT_OPT
        , ERS_INV_DT_DFLT
        , ERS_TAX_TYPE_DFLT
        , ERS_TAX_CD_OPT
        , LAST_SBI_NUM
        , SBI_DOC_DFLT
        , SBI_PRINT_OPT
        , VCHR_TAX_ADJ_DFT
        , RTV_VCHR_ADJ_DFLT
        , VAT_SUSPENSION_FLG
        , VAT_ROUND_RULE
        , REPL_DISP_METHOD
        , VNDR_UPN_FLG
        , DISP_CO_FLAG
        , DATE_CALC_BASIS
        , PAY_SCHEDULE_TYPE
        , FEDERAL_INDICATOR
        , TRADING_PARTNER
        , ALC
        , WORKFLOW_OPT
        , PHYSICAL_NATURE
        , VAT_SVC_PERFRM_FLG
        , ULTIMATE_USE_CD
        , ADDR_SEQ_NUM_SHFR
        , POA_REQUIRED
        , ACK_ALERT_DISP
        , ACK_ALERT_SHIP
        , POA_CO_REQUIRED
        , POA_TOL_FLAG
        , POA_SCHED_EARLY
        , POA_SCHED_LATE
        , POA_QTY_OVER
        , POA_QTY_UNDER
        , POA_PRICE_OVER
        , POA_PRICE_UNDER
        , CC_ACCEPT_CC
        , CC_DISP_OPTION
        , CC_ALLOW_OVERRIDE
        , CC_SECURITY_ID
        , CC_USE_FLAG
        , MATCH_DELAY_FLG
        , MATCH_DELAY_DAYS
        , DISBURSING_OFFICE
        , GEN_1099_RPT
        , SPLIT_PO_BY_SHIPTO
        , SPEEDCHART_KEY
        , ACCOUNT_CODE
        , UPN_TYPE_CD
        , DAYS_HRS_AFTER
        , DAYS_HRS_BEFORE
        , COMMENTS_2000
        , PSA_DELETE_IND
        , PSA_LOAD_DTS
        , PSA_RECORD_SOURCE
        , _FIVETRAN_SYNCED
        , _FIVETRAN_ID
        , _FIVETRAN_DELETED
        , LOAD_DTS
        , REC_SRC
        , BKCC
        , HASHDIFF
FROM JOIN_RESULT
{% if is_incremental() %}
WHERE NOT EXISTS (
    SELECT 1
    FROM {{ this }} existing
    WHERE existing.SUPPLIER_SITE_HK = JOIN_RESULT.SUPPLIER_SITE_HK
      AND existing.SETID = JOIN_RESULT.SETID
      AND existing.EFFDT = JOIN_RESULT.EFFDT
      AND existing.HASHDIFF = JOIN_RESULT.HASHDIFF
)
{% endif %}
{% if not is_incremental() %}

/* The following qualifier is implemented to prevent multiple loads of touched records during the initial build, such as multiple rows per HK and hashdiff. */
qualify 1 = row_number() over (partition by SUPPLIER_SITE_HK, SETID, EFFDT, HASHDIFF order by PSA_LOAD_DTS)

union all
SELECT 
MD5_BINARY(GR.VALUE) AS SUPPLIER_SITE_HK,
NULL AS VNDR_LOC,
GR.VALUE::text AS SETID,
'1900-01-01'::DATE AS EFFDT,
NULL AS VENDOR_ID,
NULL AS EFF_STATUS,
NULL AS CURRENCY_CD,
NULL AS CUR_RT_TYPE,
NULL AS FREIGHT_TERMS,
NULL AS SHIP_TYPE_ID,
NULL AS DISP_METHOD,
NULL AS PYMNT_TERMS_CD,
NULL AS MATCH_OPT_FLG,
NULL AS MATCH_CNTRL_ID,
NULL AS MATCH_OPT,
NULL AS ERS_ACTION,
NULL AS ERS_FLAG,
NULL AS VCHR_APPRVL_FLG,
NULL AS BUSPROCNAME,
NULL AS APPR_RULE_SET,
NULL AS BUYER_ID,
NULL AS REMIT_SETID,
NULL AS REMIT_VENDOR,
NULL AS REMIT_LOC,
NULL AS REMIT_ADDR_SEQ_NUM,
NULL AS ADDR_SEQ_NUM_ORDR,
NULL AS PRICE_SETID,
NULL AS PRICE_VENDOR,
NULL AS PRICE_LOC,
NULL AS RETURN_VENDOR,
NULL AS RET_ADDR_SEQ_NUM,
NULL AS DST_CNTRL_ID,
NULL AS PREFERRED_LANGUAGE,
NULL AS RFQ_DISP_MTHD,
NULL AS CNTRCT_DISP_MTHD,
NULL AS PRIMARY_VENDOR,
NULL AS PRIM_ADDR_SEQ_NUM,
NULL AS SHIPTO_ID,
NULL AS SUT_BASE_ID,
NULL AS SALETX_TOL_AMT,
NULL AS SALETX_TOL_CUR_CD,
NULL AS SALETX_TOL_PCT,
NULL AS SALETX_TOL_RT_TYPE,
NULL AS SALETX_CD_ERS,
NULL AS SALES_USE_TX_FLG,
NULL AS AUTO_ASN_FLG,
NULL AS SALETX_TOL_FLG,
NULL AS SHIP_LOC_FLG,
NULL AS WTHD_CD,
NULL AS WTHD_SW,
NULL AS DOC_TYPE,
NULL AS DOC_TYPE_FLG,
NULL AS RTV_DISPATCH_METH,
NULL AS RTV_NOTIFY_METH,
NULL AS RTV_DEBIT_OPT,
NULL AS VNDR_SBI_FLG,
NULL AS SBI_APPROVAL_FLG,
NULL AS ACCOUNT,
NULL AS ALTACCT,
NULL AS DEPTID,
NULL AS OPERATING_UNIT,
NULL AS PRODUCT,
NULL AS FUND_CODE,
NULL AS CLASS_FLD,
NULL AS PROGRAM_CODE,
NULL AS BUDGET_REF,
NULL AS AFFILIATE,
NULL AS AFFILIATE_INTRA1,
NULL AS AFFILIATE_INTRA2,
NULL AS CHARTFIELD1,
NULL AS CHARTFIELD2,
NULL AS CHARTFIELD3,
NULL AS PROJECT_ID,
NULL AS CONSIGNED_FLAG,
NULL AS VCHR_CONSIGN_OPT,
NULL AS BANK_ACCT_SEQ_NBR,
NULL AS ACCT_TEMPL_FLG,
NULL AS PAY_TRM_BSE_DT_DFT,
NULL AS RECV_ONLY_MTCH_FLG,
NULL AS VCHR_MTCH_ADJ_DFLT,
NULL AS ERS_INV_DT_OPT,
NULL AS ERS_INV_DT_DFLT,
NULL AS ERS_TAX_TYPE_DFLT,
NULL AS ERS_TAX_CD_OPT,
NULL AS LAST_SBI_NUM,
NULL AS SBI_DOC_DFLT,
NULL AS SBI_PRINT_OPT,
NULL AS VCHR_TAX_ADJ_DFT,
NULL AS RTV_VCHR_ADJ_DFLT,
NULL AS VAT_SUSPENSION_FLG,
NULL AS VAT_ROUND_RULE,
NULL AS REPL_DISP_METHOD,
NULL AS VNDR_UPN_FLG,
NULL AS DISP_CO_FLAG,
NULL AS DATE_CALC_BASIS,
NULL AS PAY_SCHEDULE_TYPE,
NULL AS FEDERAL_INDICATOR,
NULL AS TRADING_PARTNER,
NULL AS ALC,
NULL AS WORKFLOW_OPT,
NULL AS PHYSICAL_NATURE,
NULL AS VAT_SVC_PERFRM_FLG,
NULL AS ULTIMATE_USE_CD,
NULL AS ADDR_SEQ_NUM_SHFR,
NULL AS POA_REQUIRED,
NULL AS ACK_ALERT_DISP,
NULL AS ACK_ALERT_SHIP,
NULL AS POA_CO_REQUIRED,
NULL AS POA_TOL_FLAG,
NULL AS POA_SCHED_EARLY,
NULL AS POA_SCHED_LATE,
NULL AS POA_QTY_OVER,
NULL AS POA_QTY_UNDER,
NULL AS POA_PRICE_OVER,
NULL AS POA_PRICE_UNDER,
NULL AS CC_ACCEPT_CC,
NULL AS CC_DISP_OPTION,
NULL AS CC_ALLOW_OVERRIDE,
NULL AS CC_SECURITY_ID,
NULL AS CC_USE_FLAG,
NULL AS MATCH_DELAY_FLG,
NULL AS MATCH_DELAY_DAYS,
NULL AS DISBURSING_OFFICE,
NULL AS GEN_1099_RPT,
NULL AS SPLIT_PO_BY_SHIPTO,
NULL AS SPEEDCHART_KEY,
NULL AS ACCOUNT_CODE,
NULL AS UPN_TYPE_CD,
NULL AS DAYS_HRS_AFTER,
NULL AS DAYS_HRS_BEFORE,
NULL AS COMMENTS_2000,
'N' AS PSA_DELETE_IND,
'1900-01-01'::TIMESTAMP AS PSA_LOAD_DTS,
NULL AS PSA_RECORD_SOURCE,
NULL AS _FIVETRAN_SYNCED,
NULL AS _FIVETRAN_ID,
NULL AS _FIVETRAN_DELETED,
'1900-01-01T00:00:00'::TIMESTAMP_NTZ AS LOAD_DTS,
'USAZET.SNOWFLAKE.FBIN.DERIVED' AS REC_SRC,
DECODE(GR.VALUE, 0, 'GHOST RECORD-SYSTEM', -1, 'GHOST RECORD-nullkey-required', -2, 'GHOST RECORD-nullkey-optional') AS BKCC,
MD5_BINARY('') AS HASHDIFF
FROM
TABLE(strtok_split_to_table('0|-1|-2', '|')) AS GR
{% endif %}
