---- SRC LAYER ----
WITH
SRC_SRC            as ( SELECT * FROM {{ ref('v_psa_stg_po_item_schedule_lines__emtk_ebs') }} as SRC 
{% if is_incremental() %}
      where src.load_dts > (select dateadd('HOUR',-1,max(load_dts)) from {{ this }})
    {% endif %} )

/*
SRC_SRC            as ( SELECT * FROM int_staging_views.v_psa_stg_po_item_schedule_lines__emtk_ebs )
*/
---- LOGIC LAYER ----

, LOGIC_SRC as (
    SELECT
        PO_ITEM_HK
      , PO_HEADER_ID
      , LINE_NUM
      , LINE_LOCATION_ID
      , LAST_UPDATE_DATE
      , LAST_UPDATED_BY
      , PO_LINE_ID
      , LAST_UPDATE_LOGIN
      , CREATION_DATE
      , CREATED_BY
      , QUANTITY
      , QUANTITY_RECEIVED
      , QUANTITY_ACCEPTED
      , QUANTITY_REJECTED
      , QUANTITY_BILLED
      , QUANTITY_CANCELLED
      , UNIT_MEAS_LOOKUP_CODE
      , PO_RELEASE_ID
      , SHIP_TO_LOCATION_ID
      , SHIP_VIA_LOOKUP_CODE
      , NEED_BY_DATE
      , PROMISED_DATE
      , LAST_ACCEPT_DATE
      , PRICE_OVERRIDE
      , ENCUMBERED_FLAG
      , ENCUMBERED_DATE
      , UNENCUMBERED_QUANTITY
      , FOB_LOOKUP_CODE
      , FREIGHT_TERMS_LOOKUP_CODE
      , TAXABLE_FLAG
      , TAX_NAME
      , ESTIMATED_TAX_AMOUNT
      , FROM_HEADER_ID
      , FROM_LINE_ID
      , FROM_LINE_LOCATION_ID
      , START_DATE
      , END_DATE
      , LEAD_TIME
      , LEAD_TIME_UNIT
      , PRICE_DISCOUNT
      , TERMS_ID
      , APPROVED_FLAG
      , APPROVED_DATE
      , CLOSED_FLAG
      , CANCEL_FLAG
      , CANCELLED_BY
      , CANCEL_DATE
      , FIRM_STATUS_LOOKUP_CODE
      , FIRM_DATE
      , ATTRIBUTE_CATEGORY
      , ATTRIBUTE1
      , ATTRIBUTE2
      , ATTRIBUTE3
      , ATTRIBUTE4
      , ATTRIBUTE5
      , ATTRIBUTE6
      , ATTRIBUTE7
      , ATTRIBUTE8
      , ATTRIBUTE9
      , ATTRIBUTE10
      , UNIT_OF_MEASURE_CLASS
      , ENCUMBER_NOW
      , ATTRIBUTE11
      , ATTRIBUTE12
      , ATTRIBUTE13
      , ATTRIBUTE14
      , ATTRIBUTE15
      , INSPECTION_REQUIRED_FLAG
      , RECEIPT_REQUIRED_FLAG
      , QTY_RCV_TOLERANCE
      , QTY_RCV_EXCEPTION_CODE
      , ENFORCE_SHIP_TO_LOCATION_CODE
      , ALLOW_SUBSTITUTE_RECEIPTS_FLAG
      , DAYS_EARLY_RECEIPT_ALLOWED
      , DAYS_LATE_RECEIPT_ALLOWED
      , RECEIPT_DAYS_EXCEPTION_CODE
      , INVOICE_CLOSE_TOLERANCE
      , RECEIVE_CLOSE_TOLERANCE
      , SHIP_TO_ORGANIZATION_ID
      , SHIPMENT_NUM
      , SOURCE_SHIPMENT_ID
      , SHIPMENT_TYPE
      , CLOSED_CODE
      , REQUEST_ID
      , PROGRAM_APPLICATION_ID
      , PROGRAM_ID
      , PROGRAM_UPDATE_DATE
      , USSGL_TRANSACTION_CODE
      , GOVERNMENT_CONTEXT
      , RECEIVING_ROUTING_ID
      , ACCRUE_ON_RECEIPT_FLAG
      , CLOSED_DATE
      , CLOSED_BY
      , ORG_ID
      , QUANTITY_SHIPPED
      , GLOBAL_ATTRIBUTE_CATEGORY
      , GLOBAL_ATTRIBUTE1
      , GLOBAL_ATTRIBUTE2
      , GLOBAL_ATTRIBUTE3
      , GLOBAL_ATTRIBUTE4
      , GLOBAL_ATTRIBUTE5
      , GLOBAL_ATTRIBUTE6
      , GLOBAL_ATTRIBUTE7
      , GLOBAL_ATTRIBUTE8
      , GLOBAL_ATTRIBUTE9
      , GLOBAL_ATTRIBUTE10
      , GLOBAL_ATTRIBUTE11
      , GLOBAL_ATTRIBUTE12
      , GLOBAL_ATTRIBUTE13
      , GLOBAL_ATTRIBUTE14
      , GLOBAL_ATTRIBUTE15
      , GLOBAL_ATTRIBUTE16
      , GLOBAL_ATTRIBUTE17
      , GLOBAL_ATTRIBUTE18
      , GLOBAL_ATTRIBUTE19
      , GLOBAL_ATTRIBUTE20
      , COUNTRY_OF_ORIGIN_CODE
      , TAX_USER_OVERRIDE_FLAG
      , MATCH_OPTION
      , TAX_CODE_ID
      , CALCULATE_TAX_FLAG
      , CHANGE_PROMISED_DATE_REASON
      , NOTE_TO_RECEIVER
      , SECONDARY_QUANTITY
      , SECONDARY_UNIT_OF_MEASURE
      , PREFERRED_GRADE
      , SECONDARY_QUANTITY_RECEIVED
      , SECONDARY_QUANTITY_ACCEPTED
      , SECONDARY_QUANTITY_REJECTED
      , SECONDARY_QUANTITY_CANCELLED
      , VMI_FLAG
      , CONSIGNED_FLAG
      , RETROACTIVE_DATE
      , SUPPLIER_ORDER_LINE_NUMBER
      , AMOUNT
      , AMOUNT_RECEIVED
      , AMOUNT_BILLED
      , AMOUNT_CANCELLED
      , AMOUNT_REJECTED
      , AMOUNT_ACCEPTED
      , DROP_SHIP_FLAG
      , SALES_ORDER_UPDATE_DATE
      , TRANSACTION_FLOW_HEADER_ID
      , FINAL_MATCH_FLAG
      , MANUAL_PRICE_CHANGE_FLAG
      , SHIPMENT_CLOSED_DATE
      , CLOSED_FOR_RECEIVING_DATE
      , CLOSED_FOR_INVOICE_DATE
      , SECONDARY_QUANTITY_SHIPPED
      , VALUE_BASIS
      , MATCHING_BASIS
      , PAYMENT_TYPE
      , DESCRIPTION
      , WORK_APPROVER_ID
      , BID_PAYMENT_ID
      , QUANTITY_FINANCED
      , AMOUNT_FINANCED
      , QUANTITY_RECOUPED
      , AMOUNT_RECOUPED
      , RETAINAGE_WITHHELD_AMOUNT
      , RETAINAGE_RELEASED_AMOUNT
      , AMOUNT_SHIPPED
      , TAX_ATTRIBUTE_UPDATE_CODE
      , ORIGINAL_SHIPMENT_ID
      , LCM_FLAG
      , UDA_TEMPLATE_ID
      , DRAFT_ID
      , CLM_PERIOD_PERF_END_DATE
      , CLM_PERIOD_PERF_START_DATE
      , REVISION_NUM
      , CLM_DELIVERY_PERIOD
      , CLM_DELIVERY_PERIOD_UOM
      , CLM_POP_DURATION
      , CLM_POP_DURATION_UOM
      , CLM_PROMISE_PERIOD
      , CLM_PROMISE_PERIOD_UOM
      , CANCEL_REASON_1
      , OUTSOURCED_ASSEMBLY_1
      , CLOSED_REASON_1
      , IGT_SCHEDULE_STATUS
      , ADVANCE_PAYMENT_INDICATOR
      , PSA_DELETE_IND
      , PSA_LOAD_DTS
      , PSA_RECORD_SOURCE
      , _FIVETRAN_SYNCED
      , _FIVETRAN_ID
      , _FIVETRAN_DELETED
      , LOAD_DTS
      , REC_SRC
      , BKCC
      , HASHDIFF
    FROM SRC_SRC
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM LOGIC_SRC
)

---- FINAL LAYER ----
SELECT
          PO_ITEM_HK
        , PO_HEADER_ID
        , LINE_NUM
        , LINE_LOCATION_ID
        , LAST_UPDATE_DATE
        , LAST_UPDATED_BY
        , PO_LINE_ID
        , LAST_UPDATE_LOGIN
        , CREATION_DATE
        , CREATED_BY
        , QUANTITY
        , QUANTITY_RECEIVED
        , QUANTITY_ACCEPTED
        , QUANTITY_REJECTED
        , QUANTITY_BILLED
        , QUANTITY_CANCELLED
        , UNIT_MEAS_LOOKUP_CODE
        , PO_RELEASE_ID
        , SHIP_TO_LOCATION_ID
        , SHIP_VIA_LOOKUP_CODE
        , NEED_BY_DATE
        , PROMISED_DATE
        , LAST_ACCEPT_DATE
        , PRICE_OVERRIDE
        , ENCUMBERED_FLAG
        , ENCUMBERED_DATE
        , UNENCUMBERED_QUANTITY
        , FOB_LOOKUP_CODE
        , FREIGHT_TERMS_LOOKUP_CODE
        , TAXABLE_FLAG
        , TAX_NAME
        , ESTIMATED_TAX_AMOUNT
        , FROM_HEADER_ID
        , FROM_LINE_ID
        , FROM_LINE_LOCATION_ID
        , START_DATE
        , END_DATE
        , LEAD_TIME
        , LEAD_TIME_UNIT
        , PRICE_DISCOUNT
        , TERMS_ID
        , APPROVED_FLAG
        , APPROVED_DATE
        , CLOSED_FLAG
        , CANCEL_FLAG
        , CANCELLED_BY
        , CANCEL_DATE
        , FIRM_STATUS_LOOKUP_CODE
        , FIRM_DATE
        , ATTRIBUTE_CATEGORY
        , ATTRIBUTE1
        , ATTRIBUTE2
        , ATTRIBUTE3
        , ATTRIBUTE4
        , ATTRIBUTE5
        , ATTRIBUTE6
        , ATTRIBUTE7
        , ATTRIBUTE8
        , ATTRIBUTE9
        , ATTRIBUTE10
        , UNIT_OF_MEASURE_CLASS
        , ENCUMBER_NOW
        , ATTRIBUTE11
        , ATTRIBUTE12
        , ATTRIBUTE13
        , ATTRIBUTE14
        , ATTRIBUTE15
        , INSPECTION_REQUIRED_FLAG
        , RECEIPT_REQUIRED_FLAG
        , QTY_RCV_TOLERANCE
        , QTY_RCV_EXCEPTION_CODE
        , ENFORCE_SHIP_TO_LOCATION_CODE
        , ALLOW_SUBSTITUTE_RECEIPTS_FLAG
        , DAYS_EARLY_RECEIPT_ALLOWED
        , DAYS_LATE_RECEIPT_ALLOWED
        , RECEIPT_DAYS_EXCEPTION_CODE
        , INVOICE_CLOSE_TOLERANCE
        , RECEIVE_CLOSE_TOLERANCE
        , SHIP_TO_ORGANIZATION_ID
        , SHIPMENT_NUM
        , SOURCE_SHIPMENT_ID
        , SHIPMENT_TYPE
        , CLOSED_CODE
        , REQUEST_ID
        , PROGRAM_APPLICATION_ID
        , PROGRAM_ID
        , PROGRAM_UPDATE_DATE
        , USSGL_TRANSACTION_CODE
        , GOVERNMENT_CONTEXT
        , RECEIVING_ROUTING_ID
        , ACCRUE_ON_RECEIPT_FLAG
        , CLOSED_DATE
        , CLOSED_BY
        , ORG_ID
        , QUANTITY_SHIPPED
        , GLOBAL_ATTRIBUTE_CATEGORY
        , GLOBAL_ATTRIBUTE1
        , GLOBAL_ATTRIBUTE2
        , GLOBAL_ATTRIBUTE3
        , GLOBAL_ATTRIBUTE4
        , GLOBAL_ATTRIBUTE5
        , GLOBAL_ATTRIBUTE6
        , GLOBAL_ATTRIBUTE7
        , GLOBAL_ATTRIBUTE8
        , GLOBAL_ATTRIBUTE9
        , GLOBAL_ATTRIBUTE10
        , GLOBAL_ATTRIBUTE11
        , GLOBAL_ATTRIBUTE12
        , GLOBAL_ATTRIBUTE13
        , GLOBAL_ATTRIBUTE14
        , GLOBAL_ATTRIBUTE15
        , GLOBAL_ATTRIBUTE16
        , GLOBAL_ATTRIBUTE17
        , GLOBAL_ATTRIBUTE18
        , GLOBAL_ATTRIBUTE19
        , GLOBAL_ATTRIBUTE20
        , COUNTRY_OF_ORIGIN_CODE
        , TAX_USER_OVERRIDE_FLAG
        , MATCH_OPTION
        , TAX_CODE_ID
        , CALCULATE_TAX_FLAG
        , CHANGE_PROMISED_DATE_REASON
        , NOTE_TO_RECEIVER
        , SECONDARY_QUANTITY
        , SECONDARY_UNIT_OF_MEASURE
        , PREFERRED_GRADE
        , SECONDARY_QUANTITY_RECEIVED
        , SECONDARY_QUANTITY_ACCEPTED
        , SECONDARY_QUANTITY_REJECTED
        , SECONDARY_QUANTITY_CANCELLED
        , VMI_FLAG
        , CONSIGNED_FLAG
        , RETROACTIVE_DATE
        , SUPPLIER_ORDER_LINE_NUMBER
        , AMOUNT
        , AMOUNT_RECEIVED
        , AMOUNT_BILLED
        , AMOUNT_CANCELLED
        , AMOUNT_REJECTED
        , AMOUNT_ACCEPTED
        , DROP_SHIP_FLAG
        , SALES_ORDER_UPDATE_DATE
        , TRANSACTION_FLOW_HEADER_ID
        , FINAL_MATCH_FLAG
        , MANUAL_PRICE_CHANGE_FLAG
        , SHIPMENT_CLOSED_DATE
        , CLOSED_FOR_RECEIVING_DATE
        , CLOSED_FOR_INVOICE_DATE
        , SECONDARY_QUANTITY_SHIPPED
        , VALUE_BASIS
        , MATCHING_BASIS
        , PAYMENT_TYPE
        , DESCRIPTION
        , WORK_APPROVER_ID
        , BID_PAYMENT_ID
        , QUANTITY_FINANCED
        , AMOUNT_FINANCED
        , QUANTITY_RECOUPED
        , AMOUNT_RECOUPED
        , RETAINAGE_WITHHELD_AMOUNT
        , RETAINAGE_RELEASED_AMOUNT
        , AMOUNT_SHIPPED
        , TAX_ATTRIBUTE_UPDATE_CODE
        , ORIGINAL_SHIPMENT_ID
        , LCM_FLAG
        , UDA_TEMPLATE_ID
        , DRAFT_ID
        , CLM_PERIOD_PERF_END_DATE
        , CLM_PERIOD_PERF_START_DATE
        , REVISION_NUM
        , CLM_DELIVERY_PERIOD
        , CLM_DELIVERY_PERIOD_UOM
        , CLM_POP_DURATION
        , CLM_POP_DURATION_UOM
        , CLM_PROMISE_PERIOD
        , CLM_PROMISE_PERIOD_UOM
        , CANCEL_REASON_1
        , OUTSOURCED_ASSEMBLY_1
        , CLOSED_REASON_1
        , IGT_SCHEDULE_STATUS
        , ADVANCE_PAYMENT_INDICATOR
        , PSA_DELETE_IND
        , PSA_LOAD_DTS
        , PSA_RECORD_SOURCE
        , _FIVETRAN_SYNCED
        , _FIVETRAN_ID
        , _FIVETRAN_DELETED
        , LOAD_DTS
        , REC_SRC
        , BKCC
        , HASHDIFF
FROM JOIN_RESULT
{% if is_incremental() %}
WHERE NOT EXISTS (
    SELECT 1
    FROM {{ this }} existing
    WHERE existing.PO_ITEM_HK = JOIN_RESULT.PO_ITEM_HK
      AND existing.LINE_LOCATION_ID = JOIN_RESULT.LINE_LOCATION_ID
      AND existing.HASHDIFF = JOIN_RESULT.HASHDIFF
)
{% endif %}
{% if not is_incremental() %}

/* The following qualifier is implemented to prevent multiple loads of touched records during the initial build, such as multiple rows per HK and hashdiff. */
qualify 1 = row_number() over (partition by PO_ITEM_HK, LINE_LOCATION_ID, HASHDIFF order by PSA_LOAD_DTS)

union all
SELECT 
MD5_BINARY(GR.VALUE) AS PO_ITEM_HK,
GR.VALUE::number AS PO_HEADER_ID,
GR.VALUE::number AS LINE_NUM,
GR.VALUE::number AS LINE_LOCATION_ID,
NULL AS LAST_UPDATE_DATE,
NULL AS LAST_UPDATED_BY,
NULL AS PO_LINE_ID,
NULL AS LAST_UPDATE_LOGIN,
NULL AS CREATION_DATE,
NULL AS CREATED_BY,
NULL AS QUANTITY,
NULL AS QUANTITY_RECEIVED,
NULL AS QUANTITY_ACCEPTED,
NULL AS QUANTITY_REJECTED,
NULL AS QUANTITY_BILLED,
NULL AS QUANTITY_CANCELLED,
NULL AS UNIT_MEAS_LOOKUP_CODE,
NULL AS PO_RELEASE_ID,
NULL AS SHIP_TO_LOCATION_ID,
NULL AS SHIP_VIA_LOOKUP_CODE,
NULL AS NEED_BY_DATE,
NULL AS PROMISED_DATE,
NULL AS LAST_ACCEPT_DATE,
NULL AS PRICE_OVERRIDE,
NULL AS ENCUMBERED_FLAG,
NULL AS ENCUMBERED_DATE,
NULL AS UNENCUMBERED_QUANTITY,
NULL AS FOB_LOOKUP_CODE,
NULL AS FREIGHT_TERMS_LOOKUP_CODE,
NULL AS TAXABLE_FLAG,
NULL AS TAX_NAME,
NULL AS ESTIMATED_TAX_AMOUNT,
NULL AS FROM_HEADER_ID,
NULL AS FROM_LINE_ID,
NULL AS FROM_LINE_LOCATION_ID,
NULL AS START_DATE,
NULL AS END_DATE,
NULL AS LEAD_TIME,
NULL AS LEAD_TIME_UNIT,
NULL AS PRICE_DISCOUNT,
NULL AS TERMS_ID,
NULL AS APPROVED_FLAG,
NULL AS APPROVED_DATE,
NULL AS CLOSED_FLAG,
NULL AS CANCEL_FLAG,
NULL AS CANCELLED_BY,
NULL AS CANCEL_DATE,
NULL AS FIRM_STATUS_LOOKUP_CODE,
NULL AS FIRM_DATE,
NULL AS ATTRIBUTE_CATEGORY,
NULL AS ATTRIBUTE1,
NULL AS ATTRIBUTE2,
NULL AS ATTRIBUTE3,
NULL AS ATTRIBUTE4,
NULL AS ATTRIBUTE5,
NULL AS ATTRIBUTE6,
NULL AS ATTRIBUTE7,
NULL AS ATTRIBUTE8,
NULL AS ATTRIBUTE9,
NULL AS ATTRIBUTE10,
NULL AS UNIT_OF_MEASURE_CLASS,
NULL AS ENCUMBER_NOW,
NULL AS ATTRIBUTE11,
NULL AS ATTRIBUTE12,
NULL AS ATTRIBUTE13,
NULL AS ATTRIBUTE14,
NULL AS ATTRIBUTE15,
NULL AS INSPECTION_REQUIRED_FLAG,
NULL AS RECEIPT_REQUIRED_FLAG,
NULL AS QTY_RCV_TOLERANCE,
NULL AS QTY_RCV_EXCEPTION_CODE,
NULL AS ENFORCE_SHIP_TO_LOCATION_CODE,
NULL AS ALLOW_SUBSTITUTE_RECEIPTS_FLAG,
NULL AS DAYS_EARLY_RECEIPT_ALLOWED,
NULL AS DAYS_LATE_RECEIPT_ALLOWED,
NULL AS RECEIPT_DAYS_EXCEPTION_CODE,
NULL AS INVOICE_CLOSE_TOLERANCE,
NULL AS RECEIVE_CLOSE_TOLERANCE,
NULL AS SHIP_TO_ORGANIZATION_ID,
NULL AS SHIPMENT_NUM,
NULL AS SOURCE_SHIPMENT_ID,
NULL AS SHIPMENT_TYPE,
NULL AS CLOSED_CODE,
NULL AS REQUEST_ID,
NULL AS PROGRAM_APPLICATION_ID,
NULL AS PROGRAM_ID,
NULL AS PROGRAM_UPDATE_DATE,
NULL AS USSGL_TRANSACTION_CODE,
NULL AS GOVERNMENT_CONTEXT,
NULL AS RECEIVING_ROUTING_ID,
NULL AS ACCRUE_ON_RECEIPT_FLAG,
NULL AS CLOSED_DATE,
NULL AS CLOSED_BY,
NULL AS ORG_ID,
NULL AS QUANTITY_SHIPPED,
NULL AS GLOBAL_ATTRIBUTE_CATEGORY,
NULL AS GLOBAL_ATTRIBUTE1,
NULL AS GLOBAL_ATTRIBUTE2,
NULL AS GLOBAL_ATTRIBUTE3,
NULL AS GLOBAL_ATTRIBUTE4,
NULL AS GLOBAL_ATTRIBUTE5,
NULL AS GLOBAL_ATTRIBUTE6,
NULL AS GLOBAL_ATTRIBUTE7,
NULL AS GLOBAL_ATTRIBUTE8,
NULL AS GLOBAL_ATTRIBUTE9,
NULL AS GLOBAL_ATTRIBUTE10,
NULL AS GLOBAL_ATTRIBUTE11,
NULL AS GLOBAL_ATTRIBUTE12,
NULL AS GLOBAL_ATTRIBUTE13,
NULL AS GLOBAL_ATTRIBUTE14,
NULL AS GLOBAL_ATTRIBUTE15,
NULL AS GLOBAL_ATTRIBUTE16,
NULL AS GLOBAL_ATTRIBUTE17,
NULL AS GLOBAL_ATTRIBUTE18,
NULL AS GLOBAL_ATTRIBUTE19,
NULL AS GLOBAL_ATTRIBUTE20,
NULL AS COUNTRY_OF_ORIGIN_CODE,
NULL AS TAX_USER_OVERRIDE_FLAG,
NULL AS MATCH_OPTION,
NULL AS TAX_CODE_ID,
NULL AS CALCULATE_TAX_FLAG,
NULL AS CHANGE_PROMISED_DATE_REASON,
NULL AS NOTE_TO_RECEIVER,
NULL AS SECONDARY_QUANTITY,
NULL AS SECONDARY_UNIT_OF_MEASURE,
NULL AS PREFERRED_GRADE,
NULL AS SECONDARY_QUANTITY_RECEIVED,
NULL AS SECONDARY_QUANTITY_ACCEPTED,
NULL AS SECONDARY_QUANTITY_REJECTED,
NULL AS SECONDARY_QUANTITY_CANCELLED,
NULL AS VMI_FLAG,
NULL AS CONSIGNED_FLAG,
NULL AS RETROACTIVE_DATE,
NULL AS SUPPLIER_ORDER_LINE_NUMBER,
NULL AS AMOUNT,
NULL AS AMOUNT_RECEIVED,
NULL AS AMOUNT_BILLED,
NULL AS AMOUNT_CANCELLED,
NULL AS AMOUNT_REJECTED,
NULL AS AMOUNT_ACCEPTED,
NULL AS DROP_SHIP_FLAG,
NULL AS SALES_ORDER_UPDATE_DATE,
NULL AS TRANSACTION_FLOW_HEADER_ID,
NULL AS FINAL_MATCH_FLAG,
NULL AS MANUAL_PRICE_CHANGE_FLAG,
NULL AS SHIPMENT_CLOSED_DATE,
NULL AS CLOSED_FOR_RECEIVING_DATE,
NULL AS CLOSED_FOR_INVOICE_DATE,
NULL AS SECONDARY_QUANTITY_SHIPPED,
NULL AS VALUE_BASIS,
NULL AS MATCHING_BASIS,
NULL AS PAYMENT_TYPE,
NULL AS DESCRIPTION,
NULL AS WORK_APPROVER_ID,
NULL AS BID_PAYMENT_ID,
NULL AS QUANTITY_FINANCED,
NULL AS AMOUNT_FINANCED,
NULL AS QUANTITY_RECOUPED,
NULL AS AMOUNT_RECOUPED,
NULL AS RETAINAGE_WITHHELD_AMOUNT,
NULL AS RETAINAGE_RELEASED_AMOUNT,
NULL AS AMOUNT_SHIPPED,
NULL AS TAX_ATTRIBUTE_UPDATE_CODE,
NULL AS ORIGINAL_SHIPMENT_ID,
NULL AS LCM_FLAG,
NULL AS UDA_TEMPLATE_ID,
NULL AS DRAFT_ID,
NULL AS CLM_PERIOD_PERF_END_DATE,
NULL AS CLM_PERIOD_PERF_START_DATE,
NULL AS REVISION_NUM,
NULL AS CLM_DELIVERY_PERIOD,
NULL AS CLM_DELIVERY_PERIOD_UOM,
NULL AS CLM_POP_DURATION,
NULL AS CLM_POP_DURATION_UOM,
NULL AS CLM_PROMISE_PERIOD,
NULL AS CLM_PROMISE_PERIOD_UOM,
NULL AS CANCEL_REASON_1,
NULL AS OUTSOURCED_ASSEMBLY_1,
NULL AS CLOSED_REASON_1,
NULL AS IGT_SCHEDULE_STATUS,
NULL AS ADVANCE_PAYMENT_INDICATOR,
'N' AS PSA_DELETE_IND,
'1900-01-01'::TIMESTAMP AS PSA_LOAD_DTS,
NULL AS PSA_RECORD_SOURCE,
NULL AS _FIVETRAN_SYNCED,
NULL AS _FIVETRAN_ID,
NULL AS _FIVETRAN_DELETED,
'1900-01-01T00:00:00'::TIMESTAMP_NTZ AS LOAD_DTS,
'USAZET.SNOWFLAKE.FBIN.DERIVED' AS REC_SRC,
DECODE(GR.VALUE, 0, 'GHOST RECORD-SYSTEM', -1, 'GHOST RECORD-nullkey-required', -2, 'GHOST RECORD-nullkey-optional') AS BKCC,
MD5_BINARY('') AS HASHDIFF
FROM
TABLE(strtok_split_to_table('0|-1|-2', '|')) AS GR
{% endif %}
