---- SRC LAYER ----
WITH
SRC_s              as ( SELECT * FROM {{ ref('v_psa_stg_acknowledgement_status_details__amazon') }} as SRC 
                        {% if is_incremental() %}
                        WHERE SRC.LOAD_DTS > (SELECT DATEADD('HOUR', '-1', MAX(LOAD_DTS)) FROM {{this}}){% endif %} )

/*
SRC_s              as ( SELECT * FROM STAGING.v_psa_stg_acknowledgement_status_details__amazon )
*/
---- LOGIC LAYER ----

, LOGIC_s as (
    SELECT
        _FIVETRAN_SYNCED
      , VENDOR_ORDER_ITEM_HK
      , INDEX
      , ACKNOWLEDGEMENT_DATE
      , ACCEPTED_QUANTITY_AMOUNT
      , ACCEPTED_QUANTITY_UNIT_OF_MEASURE
      , ACCEPTED_QUANTITY_UNIT_SIZE
      , REJECTED_QUANTITY_AMOUNT
      , REJECTED_QUANTITY_UNIT_OF_MEASURE
      , REJECTED_QUANTITY_UNIT_SIZE
      , ITEM_SEQUENCE_NUMBER
      , PSA_LOAD_DTS
      , PSA_RECORD_SOURCE
      , PSA_DELETE_IND
      , LOAD_DTS
      , HASHDIFF
      , REC_SRC
    FROM SRC_s
)
---- RENAME LAYER ----

, RENAME_s as (
    SELECT
        _FIVETRAN_SYNCED
      , VENDOR_ORDER_ITEM_HK
      , INDEX
      , ACKNOWLEDGEMENT_DATE
      , ACCEPTED_QUANTITY_AMOUNT
      , ACCEPTED_QUANTITY_UNIT_OF_MEASURE
      , ACCEPTED_QUANTITY_UNIT_SIZE
      , REJECTED_QUANTITY_AMOUNT
      , REJECTED_QUANTITY_UNIT_OF_MEASURE
      , REJECTED_QUANTITY_UNIT_SIZE
      , ITEM_SEQUENCE_NUMBER
      , PSA_LOAD_DTS
      , PSA_RECORD_SOURCE
      , PSA_DELETE_IND
      , LOAD_DTS
      , HASHDIFF
      , REC_SRC
    FROM LOGIC_s
)
---- FILTER LAYER ----

, FILTER_s as (
    SELECT *
    FROM RENAME_s
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM FILTER_s
)

---- FINAL LAYER ----
SELECT
          _FIVETRAN_SYNCED
        , VENDOR_ORDER_ITEM_HK
        , INDEX
        , ACKNOWLEDGEMENT_DATE
        , ACCEPTED_QUANTITY_AMOUNT
        , ACCEPTED_QUANTITY_UNIT_OF_MEASURE
        , ACCEPTED_QUANTITY_UNIT_SIZE
        , REJECTED_QUANTITY_AMOUNT
        , REJECTED_QUANTITY_UNIT_OF_MEASURE
        , REJECTED_QUANTITY_UNIT_SIZE
        , ITEM_SEQUENCE_NUMBER
        , PSA_LOAD_DTS
        , PSA_RECORD_SOURCE
        , PSA_DELETE_IND
        , LOAD_DTS
        , HASHDIFF
        , REC_SRC
FROM JOIN_RESULT
{% if is_incremental() %}
WHERE NOT EXISTS (
    SELECT 1 
    FROM {{ this }} existing
    WHERE existing.VENDOR_ORDER_ITEM_HK = JOIN_RESULT.VENDOR_ORDER_ITEM_HK  AND existing.INDEX = JOIN_RESULT.INDEX AND existing.HASHDIFF = JOIN_RESULT.HASHDIFF
)
{% endif %}
{% if not is_incremental() %}

/* The following qualifier is implemented to prevent multiple loads of touched records during the initial build, such as multiple rows per HK and hashdiff. */
qualify 1 = row_number() over (partition by VENDOR_ORDER_ITEM_HK, INDEX, HASHDIFF order by PSA_LOAD_DTS)

union all
SELECT 
NULL AS _FIVETRAN_SYNCED,
MD5_BINARY(GR.VALUE) AS VENDOR_ORDER_ITEM_HK,
GR.VALUE::number AS INDEX,
NULL AS ACKNOWLEDGEMENT_DATE,
NULL AS ACCEPTED_QUANTITY_AMOUNT,
NULL AS ACCEPTED_QUANTITY_UNIT_OF_MEASURE,
NULL AS ACCEPTED_QUANTITY_UNIT_SIZE,
NULL AS REJECTED_QUANTITY_AMOUNT,
NULL AS REJECTED_QUANTITY_UNIT_OF_MEASURE,
NULL AS REJECTED_QUANTITY_UNIT_SIZE,
NULL AS ITEM_SEQUENCE_NUMBER,
'1900-01-01'::TIMESTAMP AS PSA_LOAD_DTS,
'psa_record_source' AS PSA_RECORD_SOURCE,
'N' AS PSA_DELETE_IND,
CONVERT_TIMEZONE('UTC','1900-01-01'::TIMESTAMP) AS LOAD_DTS,
''::BINARY AS HASHDIFF,
'USAZET.SNOWFLAKE.FBIN.DERIVED' AS REC_SRC
FROM
TABLE(strtok_split_to_table('0|-1|-2', '|')) AS GR
{% endif %}