---- SRC LAYER ----
WITH
SRC_psa_csua       as ( SELECT * FROM {{ ref('v_psa_stg_customer_site_use__ml_ebs') }} as SRC 
                        {% if is_incremental() %}
                        WHERE SRC.LOAD_DTS > (SELECT DATEADD('HOUR', '-1', MAX(LOAD_DTS)) FROM {{this}}){% endif %} )

/*
SRC_psa_csua       as ( SELECT * FROM STAGING.V_PSA_STG_CUSTOMER_SITE_USE__ML_EBS )
*/
---- LOGIC LAYER ----

, LOGIC_psa_csua as (
    SELECT
        CUSTOMER_SITE_HK
      , ACCOUNT_NUMBER
      , CUST_ACCT_SITE_ID
      , SITE_USE_CODE
      , STATUS
      , LOCATION
      , SITE_USE_ID
      , ORG_ID
      , SHIP_PARTIAL
      , PROGRAM_ID
      , GLOBAL_ATTRIBUTE5
      , GLOBAL_ATTRIBUTE4
      , UNDER_RETURN_TOLERANCE
      , GLOBAL_ATTRIBUTE7
      , GLOBAL_ATTRIBUTE6
      , GLOBAL_ATTRIBUTE1
      , GLOBAL_ATTRIBUTE3
      , GLOBAL_ATTRIBUTE2
      , FREIGHT_TERM
      , FINCHRG_RECEIVABLES_TRX_ID
      , GLOBAL_ATTRIBUTE9
      , GLOBAL_ATTRIBUTE8
      , TERRITORY_ID
      , SORT_PRIORITY
      , CREATED_BY_MODULE
      , ATTRIBUTE3
      , ORIG_SYSTEM_REFERENCE
      , ATTRIBUTE2
      , ATTRIBUTE1
      , GL_ID_REC
      , ATTRIBUTE9
      , ATTRIBUTE8
      , GL_ID_UNBILLED
      , ATTRIBUTE7
      , ATTRIBUTE6
      , ATTRIBUTE5
      , ATTRIBUTE4
      , OVER_SHIPMENT_TOLERANCE
      , GL_ID_REV
      , LAST_UNACCRUE_CHARGE_DATE
      , GL_ID_UNPAID_REC
      , ATTRIBUTE10
      , ATTRIBUTE14
      , ATTRIBUTE13
      , TAX_CLASSIFICATION
      , ATTRIBUTE12
      , ATTRIBUTE11
      , GL_ID_UNEARNED
      , GL_ID_FACTOR
      , DATES_POSITIVE_TOLERANCE
      , OVER_RETURN_TOLERANCE
      , ATTRIBUTE21
      , ORDER_TYPE_ID
      , ATTRIBUTE20
      , TAX_HEADER_LEVEL_FLAG
      , ATTRIBUTE25
      , BILL_TO_SITE_USE_ID
      , ATTRIBUTE24
      , ATTRIBUTE23
      , ATTRIBUTE22
      , GLOBAL_ATTRIBUTE20
      , SIC_CODE
      , GLOBAL_ATTRIBUTE17
      , GLOBAL_ATTRIBUTE18
      , GLOBAL_ATTRIBUTE15
      , GLOBAL_ATTRIBUTE16
      , GLOBAL_ATTRIBUTE13
      , GLOBAL_ATTRIBUTE14
      , GLOBAL_ATTRIBUTE11
      , GLOBAL_ATTRIBUTE12
      , ATTRIBUTE18
      , ATTRIBUTE17
      , ATTRIBUTE16
      , ATTRIBUTE15
      , FOB_POINT
      , GLOBAL_ATTRIBUTE19
      , ATTRIBUTE19
      , GLOBAL_ATTRIBUTE10
      , GL_ID_CLEARING
      , SHIP_VIA
      , ARRIVALSETS_INCLUDE_LINES_FLAG
      , OBJECT_VERSION_NUMBER
      , TAX_REFERENCE
      , SHIP_SETS_INCLUDE_LINES_FLAG
      , CREATED_BY
      , LAST_UPDATED_BY
      , LAST_ACCRUE_CHARGE_DATE
      , PAYMENT_TERM_ID
      , UNDER_SHIPMENT_TOLERANCE
      , SCHED_DATE_PUSH_FLAG
      , GL_ID_REMITTANCE
      , PRICE_LIST_ID
      , SECOND_LAST_UNACCRUE_CHRG_DATE
      , WAREHOUSE_ID
      , ATTRIBUTE_CATEGORY
      , PROGRAM_APPLICATION_ID
      , SECOND_LAST_ACCRUE_CHARGE_DATE
      , TAX_ROUNDING_RULE
      , GL_ID_TAX
      , APPLICATION_ID
      , REQUEST_ID
      , DATE_TYPE_PREFERENCE
      , PRIMARY_FLAG
      , ITEM_CROSS_REF_PREF
      , INVOICE_QUANTITY_RULE
      , GL_ID_FREIGHT
      , DATES_NEGATIVE_TOLERANCE
      , LAST_UPDATE_LOGIN
      , GSA_INDICATOR
      , GLOBAL_ATTRIBUTE_CATEGORY
      , WH_UPDATE_DATE
      , PRICING_EVENT
      , DEMAND_CLASS_CODE
      , PRIMARY_SALESREP_ID
      , CONTACT_ID
      , TAX_CODE
      , _FIVETRAN_DELETED
      , _FIVETRAN_SYNCED
      , PROGRAM_UPDATE_DATE
      , CREATION_DATE
      , LAST_UPDATE_DATE
      , PSA_LOAD_DTS
      , PSA_RECORD_SOURCE
      , PSA_DELETE_IND
      , LOAD_DTS
      , REC_SRC
      , HASHDIFF
      , BKCC
    FROM SRC_psa_csua
)
---- RENAME LAYER ----

, RENAME_psa_csua as (
    SELECT
        CUSTOMER_SITE_HK
      , ACCOUNT_NUMBER
      , CUST_ACCT_SITE_ID
      , SITE_USE_CODE
      , STATUS
      , LOCATION
      , SITE_USE_ID
      , ORG_ID
      , SHIP_PARTIAL
      , PROGRAM_ID
      , GLOBAL_ATTRIBUTE5
      , GLOBAL_ATTRIBUTE4
      , UNDER_RETURN_TOLERANCE
      , GLOBAL_ATTRIBUTE7
      , GLOBAL_ATTRIBUTE6
      , GLOBAL_ATTRIBUTE1
      , GLOBAL_ATTRIBUTE3
      , GLOBAL_ATTRIBUTE2
      , FREIGHT_TERM
      , FINCHRG_RECEIVABLES_TRX_ID
      , GLOBAL_ATTRIBUTE9
      , GLOBAL_ATTRIBUTE8
      , TERRITORY_ID
      , SORT_PRIORITY
      , CREATED_BY_MODULE
      , ATTRIBUTE3
      , ORIG_SYSTEM_REFERENCE
      , ATTRIBUTE2
      , ATTRIBUTE1
      , GL_ID_REC
      , ATTRIBUTE9
      , ATTRIBUTE8
      , GL_ID_UNBILLED
      , ATTRIBUTE7
      , ATTRIBUTE6
      , ATTRIBUTE5
      , ATTRIBUTE4
      , OVER_SHIPMENT_TOLERANCE
      , GL_ID_REV
      , LAST_UNACCRUE_CHARGE_DATE
      , GL_ID_UNPAID_REC
      , ATTRIBUTE10
      , ATTRIBUTE14
      , ATTRIBUTE13
      , TAX_CLASSIFICATION
      , ATTRIBUTE12
      , ATTRIBUTE11
      , GL_ID_UNEARNED
      , GL_ID_FACTOR
      , DATES_POSITIVE_TOLERANCE
      , OVER_RETURN_TOLERANCE
      , ATTRIBUTE21
      , ORDER_TYPE_ID
      , ATTRIBUTE20
      , TAX_HEADER_LEVEL_FLAG
      , ATTRIBUTE25
      , BILL_TO_SITE_USE_ID
      , ATTRIBUTE24
      , ATTRIBUTE23
      , ATTRIBUTE22
      , GLOBAL_ATTRIBUTE20
      , SIC_CODE
      , GLOBAL_ATTRIBUTE17
      , GLOBAL_ATTRIBUTE18
      , GLOBAL_ATTRIBUTE15
      , GLOBAL_ATTRIBUTE16
      , GLOBAL_ATTRIBUTE13
      , GLOBAL_ATTRIBUTE14
      , GLOBAL_ATTRIBUTE11
      , GLOBAL_ATTRIBUTE12
      , ATTRIBUTE18
      , ATTRIBUTE17
      , ATTRIBUTE16
      , ATTRIBUTE15
      , FOB_POINT
      , GLOBAL_ATTRIBUTE19
      , ATTRIBUTE19
      , GLOBAL_ATTRIBUTE10
      , GL_ID_CLEARING
      , SHIP_VIA
      , ARRIVALSETS_INCLUDE_LINES_FLAG
      , OBJECT_VERSION_NUMBER
      , TAX_REFERENCE
      , SHIP_SETS_INCLUDE_LINES_FLAG
      , CREATED_BY
      , LAST_UPDATED_BY
      , LAST_ACCRUE_CHARGE_DATE
      , PAYMENT_TERM_ID
      , UNDER_SHIPMENT_TOLERANCE
      , SCHED_DATE_PUSH_FLAG
      , GL_ID_REMITTANCE
      , PRICE_LIST_ID
      , SECOND_LAST_UNACCRUE_CHRG_DATE
      , WAREHOUSE_ID
      , ATTRIBUTE_CATEGORY
      , PROGRAM_APPLICATION_ID
      , SECOND_LAST_ACCRUE_CHARGE_DATE
      , TAX_ROUNDING_RULE
      , GL_ID_TAX
      , APPLICATION_ID
      , REQUEST_ID
      , DATE_TYPE_PREFERENCE
      , PRIMARY_FLAG
      , ITEM_CROSS_REF_PREF
      , INVOICE_QUANTITY_RULE
      , GL_ID_FREIGHT
      , DATES_NEGATIVE_TOLERANCE
      , LAST_UPDATE_LOGIN
      , GSA_INDICATOR
      , GLOBAL_ATTRIBUTE_CATEGORY
      , WH_UPDATE_DATE
      , PRICING_EVENT
      , DEMAND_CLASS_CODE
      , PRIMARY_SALESREP_ID
      , CONTACT_ID
      , TAX_CODE
      , _FIVETRAN_DELETED
      , _FIVETRAN_SYNCED
      , PROGRAM_UPDATE_DATE
      , CREATION_DATE
      , LAST_UPDATE_DATE
      , PSA_LOAD_DTS
      , PSA_RECORD_SOURCE
      , PSA_DELETE_IND
      , LOAD_DTS
      , REC_SRC
      , HASHDIFF
      , BKCC
    FROM LOGIC_psa_csua
)
---- FILTER LAYER ----

, FILTER_psa_csua as (
    SELECT *
    FROM RENAME_psa_csua
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM FILTER_psa_csua
)

---- FINAL LAYER ----
SELECT
          CUSTOMER_SITE_HK
        , ACCOUNT_NUMBER
        , CUST_ACCT_SITE_ID
        , SITE_USE_CODE
        , STATUS
        , LOCATION
        , SITE_USE_ID
        , ORG_ID
        , SHIP_PARTIAL
        , PROGRAM_ID
        , GLOBAL_ATTRIBUTE5
        , GLOBAL_ATTRIBUTE4
        , UNDER_RETURN_TOLERANCE
        , GLOBAL_ATTRIBUTE7
        , GLOBAL_ATTRIBUTE6
        , GLOBAL_ATTRIBUTE1
        , GLOBAL_ATTRIBUTE3
        , GLOBAL_ATTRIBUTE2
        , FREIGHT_TERM
        , FINCHRG_RECEIVABLES_TRX_ID
        , GLOBAL_ATTRIBUTE9
        , GLOBAL_ATTRIBUTE8
        , TERRITORY_ID
        , SORT_PRIORITY
        , CREATED_BY_MODULE
        , ATTRIBUTE3
        , ORIG_SYSTEM_REFERENCE
        , ATTRIBUTE2
        , ATTRIBUTE1
        , GL_ID_REC
        , ATTRIBUTE9
        , ATTRIBUTE8
        , GL_ID_UNBILLED
        , ATTRIBUTE7
        , ATTRIBUTE6
        , ATTRIBUTE5
        , ATTRIBUTE4
        , OVER_SHIPMENT_TOLERANCE
        , GL_ID_REV
        , LAST_UNACCRUE_CHARGE_DATE
        , GL_ID_UNPAID_REC
        , ATTRIBUTE10
        , ATTRIBUTE14
        , ATTRIBUTE13
        , TAX_CLASSIFICATION
        , ATTRIBUTE12
        , ATTRIBUTE11
        , GL_ID_UNEARNED
        , GL_ID_FACTOR
        , DATES_POSITIVE_TOLERANCE
        , OVER_RETURN_TOLERANCE
        , ATTRIBUTE21
        , ORDER_TYPE_ID
        , ATTRIBUTE20
        , TAX_HEADER_LEVEL_FLAG
        , ATTRIBUTE25
        , BILL_TO_SITE_USE_ID
        , ATTRIBUTE24
        , ATTRIBUTE23
        , ATTRIBUTE22
        , GLOBAL_ATTRIBUTE20
        , SIC_CODE
        , GLOBAL_ATTRIBUTE17
        , GLOBAL_ATTRIBUTE18
        , GLOBAL_ATTRIBUTE15
        , GLOBAL_ATTRIBUTE16
        , GLOBAL_ATTRIBUTE13
        , GLOBAL_ATTRIBUTE14
        , GLOBAL_ATTRIBUTE11
        , GLOBAL_ATTRIBUTE12
        , ATTRIBUTE18
        , ATTRIBUTE17
        , ATTRIBUTE16
        , ATTRIBUTE15
        , FOB_POINT
        , GLOBAL_ATTRIBUTE19
        , ATTRIBUTE19
        , GLOBAL_ATTRIBUTE10
        , GL_ID_CLEARING
        , SHIP_VIA
        , ARRIVALSETS_INCLUDE_LINES_FLAG
        , OBJECT_VERSION_NUMBER
        , TAX_REFERENCE
        , SHIP_SETS_INCLUDE_LINES_FLAG
        , CREATED_BY
        , LAST_UPDATED_BY
        , LAST_ACCRUE_CHARGE_DATE
        , PAYMENT_TERM_ID
        , UNDER_SHIPMENT_TOLERANCE
        , SCHED_DATE_PUSH_FLAG
        , GL_ID_REMITTANCE
        , PRICE_LIST_ID
        , SECOND_LAST_UNACCRUE_CHRG_DATE
        , WAREHOUSE_ID
        , ATTRIBUTE_CATEGORY
        , PROGRAM_APPLICATION_ID
        , SECOND_LAST_ACCRUE_CHARGE_DATE
        , TAX_ROUNDING_RULE
        , GL_ID_TAX
        , APPLICATION_ID
        , REQUEST_ID
        , DATE_TYPE_PREFERENCE
        , PRIMARY_FLAG
        , ITEM_CROSS_REF_PREF
        , INVOICE_QUANTITY_RULE
        , GL_ID_FREIGHT
        , DATES_NEGATIVE_TOLERANCE
        , LAST_UPDATE_LOGIN
        , GSA_INDICATOR
        , GLOBAL_ATTRIBUTE_CATEGORY
        , WH_UPDATE_DATE
        , PRICING_EVENT
        , DEMAND_CLASS_CODE
        , PRIMARY_SALESREP_ID
        , CONTACT_ID
        , TAX_CODE
        , _FIVETRAN_DELETED
        , _FIVETRAN_SYNCED
        , PROGRAM_UPDATE_DATE
        , CREATION_DATE
        , LAST_UPDATE_DATE
        , PSA_LOAD_DTS
        , PSA_RECORD_SOURCE
        , PSA_DELETE_IND
        , LOAD_DTS
        , REC_SRC
        , HASHDIFF
        , BKCC
FROM JOIN_RESULT
{% if is_incremental() %}
WHERE NOT EXISTS (
    SELECT 1 
    FROM {{ this }} existing
    WHERE existing.CUSTOMER_SITE_HK = JOIN_RESULT.CUSTOMER_SITE_HK
    AND existing.SITE_USE_CODE = JOIN_RESULT.SITE_USE_CODE 
    AND existing.STATUS = JOIN_RESULT.STATUS 
    AND existing.LOCATION = JOIN_RESULT.LOCATION 
    AND existing.HASHDIFF = JOIN_RESULT.HASHDIFF
)
{% endif %}
{% if not is_incremental() %}

/* The following qualifier is implemented to prevent multiple loads of touched records during the initial build, such as multiple rows per HK and hashdiff. */
qualify 1 = row_number() over (partition by CUSTOMER_SITE_HK, SITE_USE_CODE, STATUS, LOCATION, HASHDIFF order by PSA_LOAD_DTS)

union all
SELECT 
MD5_BINARY(GR.VALUE) AS CUSTOMER_SITE_HK,
GR.VALUE::text AS ACCOUNT_NUMBER,
GR.VALUE::number AS CUST_ACCT_SITE_ID,
NULL AS SITE_USE_CODE,
NULL AS STATUS,
NULL AS LOCATION,
GR.VALUE::number AS SITE_USE_ID,
NULL AS ORG_ID,
NULL AS SHIP_PARTIAL,
NULL AS PROGRAM_ID,
NULL AS GLOBAL_ATTRIBUTE5,
NULL AS GLOBAL_ATTRIBUTE4,
NULL AS UNDER_RETURN_TOLERANCE,
NULL AS GLOBAL_ATTRIBUTE7,
NULL AS GLOBAL_ATTRIBUTE6,
NULL AS GLOBAL_ATTRIBUTE1,
NULL AS GLOBAL_ATTRIBUTE3,
NULL AS GLOBAL_ATTRIBUTE2,
NULL AS FREIGHT_TERM,
NULL AS FINCHRG_RECEIVABLES_TRX_ID,
NULL AS GLOBAL_ATTRIBUTE9,
NULL AS GLOBAL_ATTRIBUTE8,
NULL AS TERRITORY_ID,
NULL AS SORT_PRIORITY,
NULL AS CREATED_BY_MODULE,
NULL AS ATTRIBUTE3,
NULL AS ORIG_SYSTEM_REFERENCE,
NULL AS ATTRIBUTE2,
NULL AS ATTRIBUTE1,
NULL AS GL_ID_REC,
NULL AS ATTRIBUTE9,
NULL AS ATTRIBUTE8,
NULL AS GL_ID_UNBILLED,
NULL AS ATTRIBUTE7,
NULL AS ATTRIBUTE6,
NULL AS ATTRIBUTE5,
NULL AS ATTRIBUTE4,
NULL AS OVER_SHIPMENT_TOLERANCE,
NULL AS GL_ID_REV,
NULL AS LAST_UNACCRUE_CHARGE_DATE,
NULL AS GL_ID_UNPAID_REC,
NULL AS ATTRIBUTE10,
NULL AS ATTRIBUTE14,
NULL AS ATTRIBUTE13,
NULL AS TAX_CLASSIFICATION,
NULL AS ATTRIBUTE12,
NULL AS ATTRIBUTE11,
NULL AS GL_ID_UNEARNED,
NULL AS GL_ID_FACTOR,
NULL AS DATES_POSITIVE_TOLERANCE,
NULL AS OVER_RETURN_TOLERANCE,
NULL AS ATTRIBUTE21,
NULL AS ORDER_TYPE_ID,
NULL AS ATTRIBUTE20,
NULL AS TAX_HEADER_LEVEL_FLAG,
NULL AS ATTRIBUTE25,
NULL AS BILL_TO_SITE_USE_ID,
NULL AS ATTRIBUTE24,
NULL AS ATTRIBUTE23,
NULL AS ATTRIBUTE22,
NULL AS GLOBAL_ATTRIBUTE20,
NULL AS SIC_CODE,
NULL AS GLOBAL_ATTRIBUTE17,
NULL AS GLOBAL_ATTRIBUTE18,
NULL AS GLOBAL_ATTRIBUTE15,
NULL AS GLOBAL_ATTRIBUTE16,
NULL AS GLOBAL_ATTRIBUTE13,
NULL AS GLOBAL_ATTRIBUTE14,
NULL AS GLOBAL_ATTRIBUTE11,
NULL AS GLOBAL_ATTRIBUTE12,
NULL AS ATTRIBUTE18,
NULL AS ATTRIBUTE17,
NULL AS ATTRIBUTE16,
NULL AS ATTRIBUTE15,
NULL AS FOB_POINT,
NULL AS GLOBAL_ATTRIBUTE19,
NULL AS ATTRIBUTE19,
NULL AS GLOBAL_ATTRIBUTE10,
NULL AS GL_ID_CLEARING,
NULL AS SHIP_VIA,
NULL AS ARRIVALSETS_INCLUDE_LINES_FLAG,
NULL AS OBJECT_VERSION_NUMBER,
NULL AS TAX_REFERENCE,
NULL AS SHIP_SETS_INCLUDE_LINES_FLAG,
NULL AS CREATED_BY,
NULL AS LAST_UPDATED_BY,
NULL AS LAST_ACCRUE_CHARGE_DATE,
NULL AS PAYMENT_TERM_ID,
NULL AS UNDER_SHIPMENT_TOLERANCE,
NULL AS SCHED_DATE_PUSH_FLAG,
NULL AS GL_ID_REMITTANCE,
NULL AS PRICE_LIST_ID,
NULL AS SECOND_LAST_UNACCRUE_CHRG_DATE,
NULL AS WAREHOUSE_ID,
NULL AS ATTRIBUTE_CATEGORY,
NULL AS PROGRAM_APPLICATION_ID,
NULL AS SECOND_LAST_ACCRUE_CHARGE_DATE,
NULL AS TAX_ROUNDING_RULE,
NULL AS GL_ID_TAX,
NULL AS APPLICATION_ID,
NULL AS REQUEST_ID,
NULL AS DATE_TYPE_PREFERENCE,
NULL AS PRIMARY_FLAG,
NULL AS ITEM_CROSS_REF_PREF,
NULL AS INVOICE_QUANTITY_RULE,
NULL AS GL_ID_FREIGHT,
NULL AS DATES_NEGATIVE_TOLERANCE,
NULL AS LAST_UPDATE_LOGIN,
NULL AS GSA_INDICATOR,
NULL AS GLOBAL_ATTRIBUTE_CATEGORY,
NULL AS WH_UPDATE_DATE,
NULL AS PRICING_EVENT,
NULL AS DEMAND_CLASS_CODE,
NULL AS PRIMARY_SALESREP_ID,
NULL AS CONTACT_ID,
NULL AS TAX_CODE,
NULL AS _FIVETRAN_DELETED,
NULL AS _FIVETRAN_SYNCED,
NULL AS PROGRAM_UPDATE_DATE,
NULL AS CREATION_DATE,
NULL AS LAST_UPDATE_DATE,
'1900-01-01'::TIMESTAMP AS PSA_LOAD_DTS,
'psa_record_source' AS PSA_RECORD_SOURCE,
'N' AS PSA_DELETE_IND,
CONVERT_TIMEZONE('UTC','1900-01-01'::TIMESTAMP) AS LOAD_DTS,
'USAZET.SNOWFLAKE.FBIN.DERIVED' AS REC_SRC,
''::BINARY AS HASHDIFF,
DECODE(GR.VALUE, 0, 'GHOST RECORD-SYSTEM', -1, 'GHOST RECORD-nullkey-required', -2, 'GHOST RECORD-nullkey-optional') AS BKCC
FROM
TABLE(strtok_split_to_table('0|-1|-2', '|')) AS GR
{% endif %}
