---- SRC LAYER ----
WITH
SRC_SPAYML         as ( SELECT * FROM {{ ref('v_psa_stg_payment_schedule__ml_ebs') }} as SRC 
                         {% if is_incremental() %}
                         WHERE SRC.LOAD_DTS > (SELECT DATEADD('HOUR', '-1', MAX(LOAD_DTS)) FROM {{this}})
                         {% endif %}  )

/*
SRC_SPAYML         as ( SELECT * FROM STAGING.v_psa_stg_payment_schedule__ml_ebs )
*/
---- LOGIC LAYER ----

, LOGIC_SPAYML as (
    SELECT
        PAYMENT_SCHEDULE_HK
      , PAYMENT_SCHEDULE_ID
      , SECOND_LAST_CHARGE_DATE
      , ORG_ID
      , AMOUNT_DUE_ORIGINAL
      , AMOUNT_ADJUSTED
      , CASH_RECEIPT_ID
      , RECEIPT_CONFIRMED_FLAG
      , ASSOCIATED_CASH_RECEIPT_ID
      , AMOUNT_CREDITED
      , GLOBAL_ATTRIBUTE5
      , ACTUAL_DATE_CLOSED
      , GLOBAL_ATTRIBUTE4
      , GLOBAL_ATTRIBUTE7
      , GLOBAL_ATTRIBUTE6
      , AMOUNT_APPLIED
      , GLOBAL_ATTRIBUTE1
      , TRX_DATE
      , GLOBAL_ATTRIBUTE3
      , GLOBAL_ATTRIBUTE2
      , CASH_APPLIED_ID_LAST
      , CUSTOMER_SITE_USE_ID
      , GLOBAL_ATTRIBUTE9
      , GLOBAL_ATTRIBUTE8
      , ATTRIBUTE3
      , ATTRIBUTE2
      , ATTRIBUTE1
      , BR_AMOUNT_ASSIGNED
      , COLLECTOR_LAST
      , RESERVED_TYPE
      , MRC_ACCTD_AMOUNT_DUE_REMAINING
      , ATTRIBUTE9
      , ADJUSTMENT_AMOUNT_LAST
      , ATTRIBUTE8
      , ATTRIBUTE7
      , ATTRIBUTE6
      , GL_DATE
      , ATTRIBUTE5
      , MRC_EXCHANGE_RATE_TYPE
      , ATTRIBUTE4
      , CASH_GL_DATE_LAST
      , PROMISE_AMOUNT_LAST
      , GL_DATE_CLOSED
      , TERM_ID
      , ATTRIBUTE10
      , ATTRIBUTE14
      , ATTRIBUTE13
      , ATTRIBUTE12
      , ATTRIBUTE11
      , RECEIVABLES_CHARGES_CHARGED
      , TRX_NUMBER
      , CASH_RECEIPT_ID_LAST
      , FREIGHT_ORIGINAL
      , LAST_UNACCRUE_CHRG_DATE
      , PROMISE_DATE_LAST
      , PAYMENT_APPROVAL
      , MRC_EXCHANGE_DATE
      , DISCOUNT_ORIGINAL
      , MRC_EXCHANGE_RATE
      , TERMS_SEQUENCE_NUMBER
      , DISCOUNT_DATE
      , DUE_DATE
      , AMOUNT_ADJUSTED_PENDING
      , RECEIVABLES_CHARGES_REMAINING
      , CASH_APPLIED_STATUS_LAST
      , NUMBER_OF_DUE_DATES
      , DISPUTE_DATE
      , GLOBAL_ATTRIBUTE20
      , CASH_RECEIPT_DATE_LAST
      , SELECTED_FOR_RECEIPT_BATCH_ID
      , DISCOUNT_TAKEN_EARNED
      , DISCOUNT_REMAINING
      , GLOBAL_ATTRIBUTE17
      , GLOBAL_ATTRIBUTE18
      , GLOBAL_ATTRIBUTE15
      , FOLLOW_UP_DATE_LAST
      , GLOBAL_ATTRIBUTE16
      , GLOBAL_ATTRIBUTE13
      , GLOBAL_ATTRIBUTE14
      , GLOBAL_ATTRIBUTE11
      , MRC_CUSTOMER_TRX_ID
      , GLOBAL_ATTRIBUTE12
      , ATTRIBUTE15
      , INVOICE_CURRENCY_CODE
      , ADJUSTMENT_GL_DATE_LAST
      , GLOBAL_ATTRIBUTE19
      , REVERSED_CASH_RECEIPT_ID
      , EXCLUDE_FROM_CONS_BILL_FLAG
      , IN_COLLECTION
      , GLOBAL_ATTRIBUTE10
      , CASH_APPLIED_AMOUNT_LAST
      , EXCLUDE_FROM_DUNNING_FLAG
      , CLASS
      , SECOND_LAST_UNACCRUE_CHRG_DT
      , RESERVED_VALUE
      , STATUS
      , DISCOUNT_TAKEN_UNEARNED
      , EXCHANGE_DATE
      , ACCTD_AMOUNT_DUE_REMAINING
      , ADJUSTMENT_DATE_LAST
      , AMOUNT_LINE_ITEMS_ORIGINAL
      , CASH_RECEIPT_AMOUNT_LAST
      , CASH_APPLIED_DATE_LAST
      , AMOUNT_DUE_REMAINING
      , EXCHANGE_RATE
      , CUSTOMER_ID
      , FREIGHT_REMAINING
      , ATTRIBUTE_CATEGORY
      , FOLLOW_UP_CODE_LAST
      , AMOUNT_LINE_ITEMS_REMAINING
      , CONS_INV_ID
      , CONS_INV_ID_REV
      , CASH_RECEIPT_STATUS_LAST
      , TAX_REMAINING
      , CALL_DATE_LAST
      , DUNNING_LEVEL_OVERRIDE_DATE
      , CUST_TRX_TYPE_ID
      , TAX_ORIGINAL
      , EXCHANGE_RATE_TYPE
      , ACTIVE_CLAIM_FLAG
      , CUSTOMER_TRX_ID
      , AMOUNT_IN_DISPUTE
      , GLOBAL_ATTRIBUTE_CATEGORY
      , STAGED_DUNNING_LEVEL
      , ADJUSTMENT_ID_LAST
      , LAST_CHARGE_DATE
      , CREATED_BY
      , CREATION_DATE
      , LAST_UPDATED_BY
      , LAST_UPDATE_DATE
      , LAST_UPDATE_LOGIN
      , REQUEST_ID
      , PROGRAM_APPLICATION_ID
      , PROGRAM_ID
      , PROGRAM_UPDATE_DATE
      , _FIVETRAN_DELETED
      , _FIVETRAN_ID
      , _FIVETRAN_SYNCED
      , PSA_DELETE_IND
      , PSA_LOAD_DTS
      , PSA_RECORD_SOURCE
      , LOAD_DTS
      , REC_SRC
      , HASHDIFF
    FROM SRC_SPAYML
)
---- RENAME LAYER ----

, RENAME_SPAYML as (
    SELECT
        PAYMENT_SCHEDULE_HK
      , PAYMENT_SCHEDULE_ID
      , SECOND_LAST_CHARGE_DATE
      , ORG_ID
      , AMOUNT_DUE_ORIGINAL
      , AMOUNT_ADJUSTED
      , CASH_RECEIPT_ID
      , RECEIPT_CONFIRMED_FLAG
      , ASSOCIATED_CASH_RECEIPT_ID
      , AMOUNT_CREDITED
      , GLOBAL_ATTRIBUTE5
      , ACTUAL_DATE_CLOSED
      , GLOBAL_ATTRIBUTE4
      , GLOBAL_ATTRIBUTE7
      , GLOBAL_ATTRIBUTE6
      , AMOUNT_APPLIED
      , GLOBAL_ATTRIBUTE1
      , TRX_DATE
      , GLOBAL_ATTRIBUTE3
      , GLOBAL_ATTRIBUTE2
      , CASH_APPLIED_ID_LAST
      , CUSTOMER_SITE_USE_ID
      , GLOBAL_ATTRIBUTE9
      , GLOBAL_ATTRIBUTE8
      , ATTRIBUTE3
      , ATTRIBUTE2
      , ATTRIBUTE1
      , BR_AMOUNT_ASSIGNED
      , COLLECTOR_LAST
      , RESERVED_TYPE
      , MRC_ACCTD_AMOUNT_DUE_REMAINING
      , ATTRIBUTE9
      , ADJUSTMENT_AMOUNT_LAST
      , ATTRIBUTE8
      , ATTRIBUTE7
      , ATTRIBUTE6
      , GL_DATE
      , ATTRIBUTE5
      , MRC_EXCHANGE_RATE_TYPE
      , ATTRIBUTE4
      , CASH_GL_DATE_LAST
      , PROMISE_AMOUNT_LAST
      , GL_DATE_CLOSED
      , TERM_ID
      , ATTRIBUTE10
      , ATTRIBUTE14
      , ATTRIBUTE13
      , ATTRIBUTE12
      , ATTRIBUTE11
      , RECEIVABLES_CHARGES_CHARGED
      , TRX_NUMBER
      , CASH_RECEIPT_ID_LAST
      , FREIGHT_ORIGINAL
      , LAST_UNACCRUE_CHRG_DATE
      , PROMISE_DATE_LAST
      , PAYMENT_APPROVAL
      , MRC_EXCHANGE_DATE
      , DISCOUNT_ORIGINAL
      , MRC_EXCHANGE_RATE
      , TERMS_SEQUENCE_NUMBER
      , DISCOUNT_DATE
      , DUE_DATE
      , AMOUNT_ADJUSTED_PENDING
      , RECEIVABLES_CHARGES_REMAINING
      , CASH_APPLIED_STATUS_LAST
      , NUMBER_OF_DUE_DATES
      , DISPUTE_DATE
      , GLOBAL_ATTRIBUTE20
      , CASH_RECEIPT_DATE_LAST
      , SELECTED_FOR_RECEIPT_BATCH_ID
      , DISCOUNT_TAKEN_EARNED
      , DISCOUNT_REMAINING
      , GLOBAL_ATTRIBUTE17
      , GLOBAL_ATTRIBUTE18
      , GLOBAL_ATTRIBUTE15
      , FOLLOW_UP_DATE_LAST
      , GLOBAL_ATTRIBUTE16
      , GLOBAL_ATTRIBUTE13
      , GLOBAL_ATTRIBUTE14
      , GLOBAL_ATTRIBUTE11
      , MRC_CUSTOMER_TRX_ID
      , GLOBAL_ATTRIBUTE12
      , ATTRIBUTE15
      , INVOICE_CURRENCY_CODE
      , ADJUSTMENT_GL_DATE_LAST
      , GLOBAL_ATTRIBUTE19
      , REVERSED_CASH_RECEIPT_ID
      , EXCLUDE_FROM_CONS_BILL_FLAG
      , IN_COLLECTION
      , GLOBAL_ATTRIBUTE10
      , CASH_APPLIED_AMOUNT_LAST
      , EXCLUDE_FROM_DUNNING_FLAG
      , CLASS
      , SECOND_LAST_UNACCRUE_CHRG_DT
      , RESERVED_VALUE
      , STATUS
      , DISCOUNT_TAKEN_UNEARNED
      , EXCHANGE_DATE
      , ACCTD_AMOUNT_DUE_REMAINING
      , ADJUSTMENT_DATE_LAST
      , AMOUNT_LINE_ITEMS_ORIGINAL
      , CASH_RECEIPT_AMOUNT_LAST
      , CASH_APPLIED_DATE_LAST
      , AMOUNT_DUE_REMAINING
      , EXCHANGE_RATE
      , CUSTOMER_ID
      , FREIGHT_REMAINING
      , ATTRIBUTE_CATEGORY
      , FOLLOW_UP_CODE_LAST
      , AMOUNT_LINE_ITEMS_REMAINING
      , CONS_INV_ID
      , CONS_INV_ID_REV
      , CASH_RECEIPT_STATUS_LAST
      , TAX_REMAINING
      , CALL_DATE_LAST
      , DUNNING_LEVEL_OVERRIDE_DATE
      , CUST_TRX_TYPE_ID
      , TAX_ORIGINAL
      , EXCHANGE_RATE_TYPE
      , ACTIVE_CLAIM_FLAG
      , CUSTOMER_TRX_ID
      , AMOUNT_IN_DISPUTE
      , GLOBAL_ATTRIBUTE_CATEGORY
      , STAGED_DUNNING_LEVEL
      , ADJUSTMENT_ID_LAST
      , LAST_CHARGE_DATE
      , CREATED_BY
      , CREATION_DATE
      , LAST_UPDATED_BY
      , LAST_UPDATE_DATE
      , LAST_UPDATE_LOGIN
      , REQUEST_ID
      , PROGRAM_APPLICATION_ID
      , PROGRAM_ID
      , PROGRAM_UPDATE_DATE
      , _FIVETRAN_DELETED
      , _FIVETRAN_ID
      , _FIVETRAN_SYNCED
      , PSA_DELETE_IND
      , PSA_LOAD_DTS
      , PSA_RECORD_SOURCE
      , LOAD_DTS
      , REC_SRC
      , HASHDIFF
    FROM LOGIC_SPAYML
)
---- FILTER LAYER ----

, FILTER_SPAYML as (
    SELECT *
    FROM RENAME_SPAYML
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM FILTER_SPAYML
)

---- FINAL LAYER ----
SELECT
          PAYMENT_SCHEDULE_HK
        , PAYMENT_SCHEDULE_ID
        , SECOND_LAST_CHARGE_DATE
        , ORG_ID
        , AMOUNT_DUE_ORIGINAL
        , AMOUNT_ADJUSTED
        , CASH_RECEIPT_ID
        , RECEIPT_CONFIRMED_FLAG
        , ASSOCIATED_CASH_RECEIPT_ID
        , AMOUNT_CREDITED
        , GLOBAL_ATTRIBUTE5
        , ACTUAL_DATE_CLOSED
        , GLOBAL_ATTRIBUTE4
        , GLOBAL_ATTRIBUTE7
        , GLOBAL_ATTRIBUTE6
        , AMOUNT_APPLIED
        , GLOBAL_ATTRIBUTE1
        , TRX_DATE
        , GLOBAL_ATTRIBUTE3
        , GLOBAL_ATTRIBUTE2
        , CASH_APPLIED_ID_LAST
        , CUSTOMER_SITE_USE_ID
        , GLOBAL_ATTRIBUTE9
        , GLOBAL_ATTRIBUTE8
        , ATTRIBUTE3
        , ATTRIBUTE2
        , ATTRIBUTE1
        , BR_AMOUNT_ASSIGNED
        , COLLECTOR_LAST
        , RESERVED_TYPE
        , MRC_ACCTD_AMOUNT_DUE_REMAINING
        , ATTRIBUTE9
        , ADJUSTMENT_AMOUNT_LAST
        , ATTRIBUTE8
        , ATTRIBUTE7
        , ATTRIBUTE6
        , GL_DATE
        , ATTRIBUTE5
        , MRC_EXCHANGE_RATE_TYPE
        , ATTRIBUTE4
        , CASH_GL_DATE_LAST
        , PROMISE_AMOUNT_LAST
        , GL_DATE_CLOSED
        , TERM_ID
        , ATTRIBUTE10
        , ATTRIBUTE14
        , ATTRIBUTE13
        , ATTRIBUTE12
        , ATTRIBUTE11
        , RECEIVABLES_CHARGES_CHARGED
        , TRX_NUMBER
        , CASH_RECEIPT_ID_LAST
        , FREIGHT_ORIGINAL
        , LAST_UNACCRUE_CHRG_DATE
        , PROMISE_DATE_LAST
        , PAYMENT_APPROVAL
        , MRC_EXCHANGE_DATE
        , DISCOUNT_ORIGINAL
        , MRC_EXCHANGE_RATE
        , TERMS_SEQUENCE_NUMBER
        , DISCOUNT_DATE
        , DUE_DATE
        , AMOUNT_ADJUSTED_PENDING
        , RECEIVABLES_CHARGES_REMAINING
        , CASH_APPLIED_STATUS_LAST
        , NUMBER_OF_DUE_DATES
        , DISPUTE_DATE
        , GLOBAL_ATTRIBUTE20
        , CASH_RECEIPT_DATE_LAST
        , SELECTED_FOR_RECEIPT_BATCH_ID
        , DISCOUNT_TAKEN_EARNED
        , DISCOUNT_REMAINING
        , GLOBAL_ATTRIBUTE17
        , GLOBAL_ATTRIBUTE18
        , GLOBAL_ATTRIBUTE15
        , FOLLOW_UP_DATE_LAST
        , GLOBAL_ATTRIBUTE16
        , GLOBAL_ATTRIBUTE13
        , GLOBAL_ATTRIBUTE14
        , GLOBAL_ATTRIBUTE11
        , MRC_CUSTOMER_TRX_ID
        , GLOBAL_ATTRIBUTE12
        , ATTRIBUTE15
        , INVOICE_CURRENCY_CODE
        , ADJUSTMENT_GL_DATE_LAST
        , GLOBAL_ATTRIBUTE19
        , REVERSED_CASH_RECEIPT_ID
        , EXCLUDE_FROM_CONS_BILL_FLAG
        , IN_COLLECTION
        , GLOBAL_ATTRIBUTE10
        , CASH_APPLIED_AMOUNT_LAST
        , EXCLUDE_FROM_DUNNING_FLAG
        , CLASS
        , SECOND_LAST_UNACCRUE_CHRG_DT
        , RESERVED_VALUE
        , STATUS
        , DISCOUNT_TAKEN_UNEARNED
        , EXCHANGE_DATE
        , ACCTD_AMOUNT_DUE_REMAINING
        , ADJUSTMENT_DATE_LAST
        , AMOUNT_LINE_ITEMS_ORIGINAL
        , CASH_RECEIPT_AMOUNT_LAST
        , CASH_APPLIED_DATE_LAST
        , AMOUNT_DUE_REMAINING
        , EXCHANGE_RATE
        , CUSTOMER_ID
        , FREIGHT_REMAINING
        , ATTRIBUTE_CATEGORY
        , FOLLOW_UP_CODE_LAST
        , AMOUNT_LINE_ITEMS_REMAINING
        , CONS_INV_ID
        , CONS_INV_ID_REV
        , CASH_RECEIPT_STATUS_LAST
        , TAX_REMAINING
        , CALL_DATE_LAST
        , DUNNING_LEVEL_OVERRIDE_DATE
        , CUST_TRX_TYPE_ID
        , TAX_ORIGINAL
        , EXCHANGE_RATE_TYPE
        , ACTIVE_CLAIM_FLAG
        , CUSTOMER_TRX_ID
        , AMOUNT_IN_DISPUTE
        , GLOBAL_ATTRIBUTE_CATEGORY
        , STAGED_DUNNING_LEVEL
        , ADJUSTMENT_ID_LAST
        , LAST_CHARGE_DATE
        , CREATED_BY
        , CREATION_DATE
        , LAST_UPDATED_BY
        , LAST_UPDATE_DATE
        , LAST_UPDATE_LOGIN
        , REQUEST_ID
        , PROGRAM_APPLICATION_ID
        , PROGRAM_ID
        , PROGRAM_UPDATE_DATE
        , _FIVETRAN_DELETED
        , _FIVETRAN_ID
        , _FIVETRAN_SYNCED
        , PSA_DELETE_IND
        , PSA_LOAD_DTS
        , PSA_RECORD_SOURCE
        , LOAD_DTS
        , REC_SRC
        , HASHDIFF
FROM JOIN_RESULT
{% if is_incremental() %}
WHERE NOT EXISTS (
    SELECT 1 
    FROM {{ this }} existing
    WHERE existing.PAYMENT_SCHEDULE_HK = JOIN_RESULT.PAYMENT_SCHEDULE_HK 
    AND existing.HASHDIFF = JOIN_RESULT.HASHDIFF
)
{% endif %} 
{% if not is_incremental() %}
/*the following qualify is to restrict multiple loads of touched records during the initial build. Ex: multiple row per hk, hashdiff */
qualify 1= row_number()over(partition by PAYMENT_SCHEDULE_HK , HASHDIFF order by PSA_LOAD_DTS)
union all
    SELECT         MD5_BINARY(GR.VALUE) AS PAYMENT_SCHEDULE_HK
    ,     GR.VALUE::NUMBER  as PAYMENT_SCHEDULE_ID
    , null as SECOND_LAST_CHARGE_DATE
    , null as ORG_ID
    , null as AMOUNT_DUE_ORIGINAL
    , null as AMOUNT_ADJUSTED
    , null as CASH_RECEIPT_ID
    , null as RECEIPT_CONFIRMED_FLAG
    , null as ASSOCIATED_CASH_RECEIPT_ID
    , null as AMOUNT_CREDITED
    , null as GLOBAL_ATTRIBUTE5
    , null as ACTUAL_DATE_CLOSED
    , null as GLOBAL_ATTRIBUTE4
    , null as GLOBAL_ATTRIBUTE7
    , null as GLOBAL_ATTRIBUTE6
    , null as AMOUNT_APPLIED
    , null as GLOBAL_ATTRIBUTE1
    , null as TRX_DATE
    , null as GLOBAL_ATTRIBUTE3
    , null as GLOBAL_ATTRIBUTE2
    , null as CASH_APPLIED_ID_LAST
    , null as CUSTOMER_SITE_USE_ID
    , null as GLOBAL_ATTRIBUTE9
    , null as GLOBAL_ATTRIBUTE8
    , null as ATTRIBUTE3
    , null as ATTRIBUTE2
    , null as ATTRIBUTE1
    , null as BR_AMOUNT_ASSIGNED
    , null as COLLECTOR_LAST
    , null as RESERVED_TYPE
    , null as MRC_ACCTD_AMOUNT_DUE_REMAINING
    , null as ATTRIBUTE9
    , null as ADJUSTMENT_AMOUNT_LAST
    , null as ATTRIBUTE8
    , null as ATTRIBUTE7
    , null as ATTRIBUTE6
    , null as GL_DATE
    , null as ATTRIBUTE5
    , null as MRC_EXCHANGE_RATE_TYPE
    , null as ATTRIBUTE4
    , null as CASH_GL_DATE_LAST
    , null as PROMISE_AMOUNT_LAST
    , null as GL_DATE_CLOSED
    , null as TERM_ID
    , null as ATTRIBUTE10
    , null as ATTRIBUTE14
    , null as ATTRIBUTE13
    , null as ATTRIBUTE12
    , null as ATTRIBUTE11
    , null as RECEIVABLES_CHARGES_CHARGED
    , null as TRX_NUMBER
    , null as CASH_RECEIPT_ID_LAST
    , null as FREIGHT_ORIGINAL
    , null as LAST_UNACCRUE_CHRG_DATE
    , null as PROMISE_DATE_LAST
    , null as PAYMENT_APPROVAL
    , null as MRC_EXCHANGE_DATE
    , null as DISCOUNT_ORIGINAL
    , null as MRC_EXCHANGE_RATE
    , null as TERMS_SEQUENCE_NUMBER
    , null as DISCOUNT_DATE
    , null as DUE_DATE
    , null as AMOUNT_ADJUSTED_PENDING
    , null as RECEIVABLES_CHARGES_REMAINING
    , null as CASH_APPLIED_STATUS_LAST
    , null as NUMBER_OF_DUE_DATES
    , null as DISPUTE_DATE
    , null as GLOBAL_ATTRIBUTE20
    , null as CASH_RECEIPT_DATE_LAST
    , null as SELECTED_FOR_RECEIPT_BATCH_ID
    , null as DISCOUNT_TAKEN_EARNED
    , null as DISCOUNT_REMAINING
    , null as GLOBAL_ATTRIBUTE17
    , null as GLOBAL_ATTRIBUTE18
    , null as GLOBAL_ATTRIBUTE15
    , null as FOLLOW_UP_DATE_LAST
    , null as GLOBAL_ATTRIBUTE16
    , null as GLOBAL_ATTRIBUTE13
    , null as GLOBAL_ATTRIBUTE14
    , null as GLOBAL_ATTRIBUTE11
    , null as MRC_CUSTOMER_TRX_ID
    , null as GLOBAL_ATTRIBUTE12
    , null as ATTRIBUTE15
    , null as INVOICE_CURRENCY_CODE
    , null as ADJUSTMENT_GL_DATE_LAST
    , null as GLOBAL_ATTRIBUTE19
    , null as REVERSED_CASH_RECEIPT_ID
    , null as EXCLUDE_FROM_CONS_BILL_FLAG
    , null as IN_COLLECTION
    , null as GLOBAL_ATTRIBUTE10
    , null as CASH_APPLIED_AMOUNT_LAST
    , null as EXCLUDE_FROM_DUNNING_FLAG
    , null as CLASS
    , null as SECOND_LAST_UNACCRUE_CHRG_DT
    , null as RESERVED_VALUE
    , null as STATUS
    , null as DISCOUNT_TAKEN_UNEARNED
    , null as EXCHANGE_DATE
    , null as ACCTD_AMOUNT_DUE_REMAINING
    , null as ADJUSTMENT_DATE_LAST
    , null as AMOUNT_LINE_ITEMS_ORIGINAL
    , null as CASH_RECEIPT_AMOUNT_LAST
    , null as CASH_APPLIED_DATE_LAST
    , null as AMOUNT_DUE_REMAINING
    , null as EXCHANGE_RATE
    , null as CUSTOMER_ID
    , null as FREIGHT_REMAINING
    , null as ATTRIBUTE_CATEGORY
    , null as FOLLOW_UP_CODE_LAST
    , null as AMOUNT_LINE_ITEMS_REMAINING
    , null as CONS_INV_ID
    , null as CONS_INV_ID_REV
    , null as CASH_RECEIPT_STATUS_LAST
    , null as TAX_REMAINING
    , null as CALL_DATE_LAST
    , null as DUNNING_LEVEL_OVERRIDE_DATE
    , null as CUST_TRX_TYPE_ID
    , null as TAX_ORIGINAL
    , null as EXCHANGE_RATE_TYPE
    , null as ACTIVE_CLAIM_FLAG
    , null as CUSTOMER_TRX_ID
    , null as AMOUNT_IN_DISPUTE
    , null as GLOBAL_ATTRIBUTE_CATEGORY
    , null as STAGED_DUNNING_LEVEL
    , null as ADJUSTMENT_ID_LAST
    , null as LAST_CHARGE_DATE
, null as CREATED_BY
, null as CREATION_DATE
, null as LAST_UPDATED_BY
, null as LAST_UPDATE_DATE
, null as LAST_UPDATE_LOGIN
, null as REQUEST_ID
, null as PROGRAM_APPLICATION_ID
, null as PROGRAM_ID
, null as PROGRAM_UPDATE_DATE
, null as _FIVETRAN_DELETED
, null as _FIVETRAN_ID
, null as _FIVETRAN_SYNCED
, null as PSA_DELETE_IND
, null as PSA_LOAD_DTS
, null as PSA_RECORD_SOURCE
    , CONVERT_TIMEZONE('UTC','1900-01-01'::TIMESTAMP)::TIMESTAMP  as  LOAD_DTS
,'USAZET.SNOWFLAKE.FBIN.DERIVED' AS REC_SRC
, ''::BINARY as HASH_DIFF
  FROM
        TABLE(strtok_split_to_table('0|-1|-2', '|')) AS GR
{% endif %}