---- SRC LAYER ----
WITH
SRC_HYD            as ( SELECT * FROM {{ ref('v_psa_stg_smart_device_hyd_shadow') }} as SRC 
                         {% if is_incremental() %}
                         WHERE SRC.LOAD_DTS > (SELECT DATEADD('HOUR', '-1', MAX(LOAD_DTS)) FROM {{this}})
                         {% endif %}  )

/*
SRC_HYD            as ( SELECT * FROM staging.v_psa_stg_smart_device_hyd_shadow )
*/
---- LOGIC LAYER ----

, LOGIC_HYD as (
    SELECT
        SMART_DEVICE_HK
      , LOAD_DTS
      , SERIAL_NUMBER
      , TIMESTAMP
      , FIRMWARE_VERSION
      , UPGRADE_URI
      , CONNECTED
      , LAST_CONNECT
      , WIFI_RSSI
      , WIFI_NETWORK
      , WIFI_NO_POLL
      , COMMAND
      , COMMAND_SRC
      , LOGCOMMAND_COMMAND
      , LOGCOMMAND_EVENTID
      , LOGCOMMAND_DURATION
      , LOGCOMMAND_ARGS
      , LOGALERTACK_EVENTID
      , LOGALERTACK_TYPE
      , LOG_DEBUG
      , LOG_DEBUG_STATE
      , SYSTEM_STATE
      , DEV_DEVICE
      , DISP_LANGUAGE
      , POWER_SOURCE
      , BATTERY_PERCENTAGE
      , BATTERY_LIFE_REMAINING
      , BEEPER_PIEZO_ENABLE
      , TEMP_SCALE
      , TIMEZONE_OFFSET
      , SCHEDULER_COMMAND
      , SCHEDULER_SRC
      , SCHEDULER_TIMEOUT
      , SCHEDULER_ZONE_ID
      , SCHEDULER_SCHEDULE_ID
      , SCHEDULER_SENSOR_ID
      , WATER_ENABLE
      , SCHEDULE_RUNNING_ID
      , SCHEDULE_NEXT_ID
      , SCHEDULE_NEXT_STARTTIME
      , SCHEDULE_NEXT_WILL_RUN_SOON
      , MASTER_VALVE_CONNECTED
      , MASTER_VALVE_STATUS
      , RAIN_SENSOR_CONNECTED
      , RAIN_SENSOR_TYPE
      , SEASONAL_ADJUST
      , SOIL_SENSORS
      , SOIL_SENSORS_LOST
      , FLOW_SENSOR_CONNECTED
      , FLOW_SENSOR_KFACTOR
      , FLOW_SENSOR_OFFSET
      , WEATHER_SKIP_REASON
      , WEATHER_SKIP_STARTTIME
      , WEATHER_SKIP_ENDTIME
      , HYDRA_OVERVIEW_STATUS
      , HYDRA_OVERVIEW_ZONE_ID
      , HYDRA_OVERVIEW_DURATION
      , HYDRA_OVERVIEW_DURATION_REMAINING
      , HYDRA_OVERVIEW_FLOW
      , HYDRA_OVERVIEW_RAIN
      , HYDRA_OVERVIEW_RESTRICTED
      , HYDRA_OVERVIEW_RUN_PLAN_SEQ_NUM
      , HYDRA_OVERVIEW_PAUSED
      , SCHEDULES_MAX
      , SCHEDULES_LOADED
      , RESTRICT_LOADED
      , NUM_ZONES
      , ZONES
      , ALERTS
      , CURRENT_VERSION
      , DEVICE_TYPE
      , VERSION
      , _RESCUED_DATA
      , PSA_LOAD_DTS
      , PSA_RECORD_SOURCE
      , PSA_DELETE_IND
      , REC_SRC
      , BKCC
      , HASHDIFF
    FROM SRC_HYD
)
---- RENAME LAYER ----

, RENAME_HYD as (
    SELECT
        SMART_DEVICE_HK
      , LOAD_DTS
      , SERIAL_NUMBER
      , TIMESTAMP
      , FIRMWARE_VERSION
      , UPGRADE_URI
      , CONNECTED
      , LAST_CONNECT
      , WIFI_RSSI
      , WIFI_NETWORK
      , WIFI_NO_POLL
      , COMMAND
      , COMMAND_SRC
      , LOGCOMMAND_COMMAND
      , LOGCOMMAND_EVENTID
      , LOGCOMMAND_DURATION
      , LOGCOMMAND_ARGS
      , LOGALERTACK_EVENTID
      , LOGALERTACK_TYPE
      , LOG_DEBUG
      , LOG_DEBUG_STATE
      , SYSTEM_STATE
      , DEV_DEVICE
      , DISP_LANGUAGE
      , POWER_SOURCE
      , BATTERY_PERCENTAGE
      , BATTERY_LIFE_REMAINING
      , BEEPER_PIEZO_ENABLE
      , TEMP_SCALE
      , TIMEZONE_OFFSET
      , SCHEDULER_COMMAND
      , SCHEDULER_SRC
      , SCHEDULER_TIMEOUT
      , SCHEDULER_ZONE_ID
      , SCHEDULER_SCHEDULE_ID
      , SCHEDULER_SENSOR_ID
      , WATER_ENABLE
      , SCHEDULE_RUNNING_ID
      , SCHEDULE_NEXT_ID
      , SCHEDULE_NEXT_STARTTIME
      , SCHEDULE_NEXT_WILL_RUN_SOON
      , MASTER_VALVE_CONNECTED
      , MASTER_VALVE_STATUS
      , RAIN_SENSOR_CONNECTED
      , RAIN_SENSOR_TYPE
      , SEASONAL_ADJUST
      , SOIL_SENSORS
      , SOIL_SENSORS_LOST
      , FLOW_SENSOR_CONNECTED
      , FLOW_SENSOR_KFACTOR
      , FLOW_SENSOR_OFFSET
      , WEATHER_SKIP_REASON
      , WEATHER_SKIP_STARTTIME
      , WEATHER_SKIP_ENDTIME
      , HYDRA_OVERVIEW_STATUS
      , HYDRA_OVERVIEW_ZONE_ID
      , HYDRA_OVERVIEW_DURATION
      , HYDRA_OVERVIEW_DURATION_REMAINING
      , HYDRA_OVERVIEW_FLOW
      , HYDRA_OVERVIEW_RAIN
      , HYDRA_OVERVIEW_RESTRICTED
      , HYDRA_OVERVIEW_RUN_PLAN_SEQ_NUM
      , HYDRA_OVERVIEW_PAUSED
      , SCHEDULES_MAX
      , SCHEDULES_LOADED
      , RESTRICT_LOADED
      , NUM_ZONES
      , ZONES
      , ALERTS
      , CURRENT_VERSION
      , DEVICE_TYPE
      , VERSION
      , _RESCUED_DATA
      , PSA_LOAD_DTS
      , PSA_RECORD_SOURCE
      , PSA_DELETE_IND
      , REC_SRC
      , BKCC
      , HASHDIFF
    FROM LOGIC_HYD
)
---- FILTER LAYER ----

, FILTER_HYD as (
    SELECT *
    FROM RENAME_HYD
)
---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT * FROM FILTER_HYD
)

---- FINAL LAYER ----
SELECT
          SMART_DEVICE_HK
        , LOAD_DTS
        , SERIAL_NUMBER
        , TIMESTAMP
        , FIRMWARE_VERSION
        , UPGRADE_URI
        , CONNECTED
        , LAST_CONNECT
        , WIFI_RSSI
        , WIFI_NETWORK
        , WIFI_NO_POLL
        , COMMAND
        , COMMAND_SRC
        , LOGCOMMAND_COMMAND
        , LOGCOMMAND_EVENTID
        , LOGCOMMAND_DURATION
        , LOGCOMMAND_ARGS
        , LOGALERTACK_EVENTID
        , LOGALERTACK_TYPE
        , LOG_DEBUG
        , LOG_DEBUG_STATE
        , SYSTEM_STATE
        , DEV_DEVICE
        , DISP_LANGUAGE
        , POWER_SOURCE
        , BATTERY_PERCENTAGE
        , BATTERY_LIFE_REMAINING
        , BEEPER_PIEZO_ENABLE
        , TEMP_SCALE
        , TIMEZONE_OFFSET
        , SCHEDULER_COMMAND
        , SCHEDULER_SRC
        , SCHEDULER_TIMEOUT
        , SCHEDULER_ZONE_ID
        , SCHEDULER_SCHEDULE_ID
        , SCHEDULER_SENSOR_ID
        , WATER_ENABLE
        , SCHEDULE_RUNNING_ID
        , SCHEDULE_NEXT_ID
        , SCHEDULE_NEXT_STARTTIME
        , SCHEDULE_NEXT_WILL_RUN_SOON
        , MASTER_VALVE_CONNECTED
        , MASTER_VALVE_STATUS
        , RAIN_SENSOR_CONNECTED
        , RAIN_SENSOR_TYPE
        , SEASONAL_ADJUST
        , SOIL_SENSORS
        , SOIL_SENSORS_LOST
        , FLOW_SENSOR_CONNECTED
        , FLOW_SENSOR_KFACTOR
        , FLOW_SENSOR_OFFSET
        , WEATHER_SKIP_REASON
        , WEATHER_SKIP_STARTTIME
        , WEATHER_SKIP_ENDTIME
        , HYDRA_OVERVIEW_STATUS
        , HYDRA_OVERVIEW_ZONE_ID
        , HYDRA_OVERVIEW_DURATION
        , HYDRA_OVERVIEW_DURATION_REMAINING
        , HYDRA_OVERVIEW_FLOW
        , HYDRA_OVERVIEW_RAIN
        , HYDRA_OVERVIEW_RESTRICTED
        , HYDRA_OVERVIEW_RUN_PLAN_SEQ_NUM
        , HYDRA_OVERVIEW_PAUSED
        , SCHEDULES_MAX
        , SCHEDULES_LOADED
        , RESTRICT_LOADED
        , NUM_ZONES
        , ZONES
        , ALERTS
        , CURRENT_VERSION
        , DEVICE_TYPE
        , VERSION
        , _RESCUED_DATA
        , PSA_LOAD_DTS
        , PSA_RECORD_SOURCE
        , PSA_DELETE_IND
        , REC_SRC
        , BKCC
        , HASHDIFF
FROM JOIN_RESULT
{% if is_incremental() %}
WHERE NOT EXISTS (
    SELECT 1 
    FROM {{ this }} existing
    WHERE existing.SMART_DEVICE_HK = JOIN_RESULT.SMART_DEVICE_HK
    AND existing.HASHDIFF = JOIN_RESULT.HASHDIFF
)
{% endif %} 
qualify 1= row_number()over(partition by SMART_DEVICE_HK, HASHDIFF order by LOAD_DTS)
{% if not is_incremental() %}
union all
SELECT
MD5_BINARY(GR.VALUE) AS SMART_DEVICE_HK
,CONVERT_TIMEZONE('UTC','1900-01-01'::TIMESTAMP)  AS LOAD_DTS
, null as SERIAL_NUMBER
, null as TIMESTAMP
, null as FIRMWARE_VERSION
, null as UPGRADE_URI
, null as CONNECTED
, null as LAST_CONNECT
, null as WIFI_RSSI
, null as WIFI_NETWORK
, null as WIFI_NO_POLL
, null as COMMAND
, null as COMMAND_SRC
, null as LOGCOMMAND_COMMAND
, null as LOGCOMMAND_EVENTID
, null as LOGCOMMAND_DURATION
, null as LOGCOMMAND_ARGS
, null as LOGALERTACK_EVENTID
, null as LOGALERTACK_TYPE
, null as LOG_DEBUG
, null as LOG_DEBUG_STATE
, null as SYSTEM_STATE
, null as DEV_DEVICE
, null as DISP_LANGUAGE
, null as POWER_SOURCE
, null as BATTERY_PERCENTAGE
, null as BATTERY_LIFE_REMAINING
, null as BEEPER_PIEZO_ENABLE
, null as TEMP_SCALE
, null as TIMEZONE_OFFSET
, null as SCHEDULER_COMMAND
, null as SCHEDULER_SRC
, null as SCHEDULER_TIMEOUT
, null as SCHEDULER_ZONE_ID
, null as SCHEDULER_SCHEDULE_ID
, null as SCHEDULER_SENSOR_ID
, null as WATER_ENABLE
, null as SCHEDULE_RUNNING_ID
, null as SCHEDULE_NEXT_ID
, null as SCHEDULE_NEXT_STARTTIME
, null as SCHEDULE_NEXT_WILL_RUN_SOON
, null as MASTER_VALVE_CONNECTED
, null as MASTER_VALVE_STATUS
, null as RAIN_SENSOR_CONNECTED
, null as RAIN_SENSOR_TYPE
, null as SEASONAL_ADJUST
, null as SOIL_SENSORS
, null as SOIL_SENSORS_LOST
, null as FLOW_SENSOR_CONNECTED
, null as FLOW_SENSOR_KFACTOR
, null as FLOW_SENSOR_OFFSET
, null as WEATHER_SKIP_REASON
, null as WEATHER_SKIP_STARTTIME
, null as WEATHER_SKIP_ENDTIME
, null as HYDRA_OVERVIEW_STATUS
, null as HYDRA_OVERVIEW_ZONE_ID
, null as HYDRA_OVERVIEW_DURATION
, null as HYDRA_OVERVIEW_DURATION_REMAINING
, null as HYDRA_OVERVIEW_FLOW
, null as HYDRA_OVERVIEW_RAIN
, null as HYDRA_OVERVIEW_RESTRICTED
, null as HYDRA_OVERVIEW_RUN_PLAN_SEQ_NUM
, null as HYDRA_OVERVIEW_PAUSED
, null as SCHEDULES_MAX
, null as SCHEDULES_LOADED
, null as RESTRICT_LOADED
, null as NUM_ZONES
, null as ZONES
, null as ALERTS
, null as CURRENT_VERSION
, null as DEVICE_TYPE
, null as VERSION
, null as _RESCUED_DATA
,null as PSA_LOAD_DTS
,null as PSA_RECORD_SOURCE
,null as PSA_DELETE_IND		
, DECODE(GR.VALUE, 0, 'GHOST RECORD-SYSTEM', -1, 'GHOST RECORD-nullkey-required', -2, 'GHOST RECORD-nullkey-optional')  AS BKCC
, 'USAZET.SNOWFLAKE.FBIN.DERIVED' AS REC_SRC
, ''::BINARY as HASHDIFF
FROM
TABLE(strtok_split_to_table('0|-1|-2', '|')) AS GR

{% endif %}