---- SRC LAYER ----
WITH
SRC_SINVLNFB       as ( SELECT * FROM {{ ref('v_psa_stg_invoice_line__fib_ocf') }} as SRC 
                         {% if is_incremental() %}
                         WHERE SRC.LOAD_DTS > (SELECT DATEADD('HOUR', '-1', MAX(LOAD_DTS)) FROM {{this}})
                         {% endif %}  )

/*
SRC_SINVLNFB       as ( SELECT * FROM STAGING.v_psa_stg_invoice_line__fib_ocf )
*/
---- LOGIC LAYER ----

, LOGIC_SINVLNFB as (
    SELECT
        INVOICE_LINE_HK
      , CUSTOMER_TRX_LINE_ID
      , CUSTOMER_TRX_ID
      , ATTRIBUTE_7
      , INTERFACE_LINE_ATTRIBUTE_4
      , ACCTD_AMOUNT_DUE_ORIGINAL
      , BILL_PLAN_LINE_ID
      , ATTRIBUTE_11
      , INTERFACE_LINE_ATTRIBUTE_6
      , SALES_ORDER_SOURCE
      , ACCOUNTING_RULE_ID
      , BILLING_PERIOD_START_DATE
      , GLOBAL_ATTRIBUTE_NUMBER_3
      , BR_ADJUSTMENT_ID
      , MISCELLANEOUS_CHARGE
      , TRANSLATED_DESCRIPTION
      , UNIT_STANDARD_PRICE
      , DOC_LINE_ID_CHAR_1
      , QUANTITY_INVOICED
      , TAX_INVOICE_DATE
      , GLOBAL_ATTRIBUTE_11
      , COMMERCIAL_DISCOUNT
      , OBJECT_VERSION_NUMBER
      , GLOBAL_ATTRIBUTE_20
      , ATTRIBUTE_NUMBER_3
      , PRODUCT_TYPE
      , ATTRIBUTE_NUMBER_2
      , GLOBAL_ATTRIBUTE_DATE_3
      , EXTENDED_AMOUNT
      , ATTRIBUTE_DATE_5
      , PREVIOUS_CUSTOMER_TRX_ID
      , GROSS_UNIT_SELLING_PRICE
      , FRT_ADJ_ACCTD_REMAINING
      , INTERFACE_LINE_ATTRIBUTE_14
      , ATTRIBUTE_13
      , TAX_RECOVERABLE
      , LINK_TO_PARENTLINE_ATTRIBUTE_14
      , SOURCE_DATA_KEY_5
      , LINE_INTENDED_USE
      , LINK_TO_PARENTLINE_ATTRIBUTE_4
      , CREATION_DATE
      , REVENUE_AMOUNT
      , GLOBAL_ATTRIBUTE_10
      , REASON_CODE
      , INTERFACE_LINE_ATTRIBUTE_7
      , SHIP_TO_PARTY_CONTACT_ID
      , GLOBAL_ATTRIBUTE_NUMBER_1
      , MOVEMENT_ID
      , MRC_EXTENDED_ACCTD_AMOUNT
      , TAX_PRECEDENCE
      , CONTRACT_START_DATE
      , LINE_TYPE
      , FRT_ED_AMOUNT
      , LAST_UPDATE_DATE
      , AMOUNT_INCLUDES_TAX_FLAG
      , SOURCE_DOCUMENT_LINE_ID
      , TAX_RATE
      , PROGRAM_APPLICATION_ID
      , SOURCE_DATA_KEY_2
      , LINK_TO_PARENTLINE_ATTRIBUTE_12
      , ORG_ID
      , ATTRIBUTE_1
      , DOC_LINE_ID_INT_5
      , INTERFACE_LINE_ATTRIBUTE_12
      , QUANTITY_CREDITED
      , WAREHOUSE_ID
      , INTERFACE_LINE_ATTRIBUTE_13
      , AUTH_COMPLETE_FLAG
      , DOC_LINE_ID_INT_2
      , INVENTORY_ITEM_ID
      , LINE_RECOVERABLE
      , FRT_UNED_AMOUNT
      , INTERFACE_LINE_ATTRIBUTE_5
      , INTEREST_LINE_ID
      , PROGRAM_UPDATE_DATE
      , GLOBAL_ATTRIBUTE_9
      , TAX_EXEMPTION_ID
      , SHIP_TO_SITE_USE_ID
      , INTERFACE_LINE_ATTRIBUTE_1
      , LINK_TO_PARENTLINE_ATTRIBUTE_5
      , DEFERRAL_EXCLUSION_FLAG
      , ATTRIBUTE_6
      , BR_REF_PAYMENT_SCHEDULE_ID
      , SHIP_TO_CUSTOMER_ID
      , ATTRIBUTE_NUMBER_5
      , TAX_EXEMPT_FLAG
      , AUTOTAX
      , CONTRACT_LINE_ID
      , SOURCE_DATA_KEY_4
      , DOC_LINE_ID_CHAR_3
      , FRT_UNED_ACCTD_AMOUNT
      , INTERFACE_LINE_ATTRIBUTE_10
      , GLOBAL_ATTRIBUTE_14
      , BILLING_PERIOD_END_DATE
      , ASSESSABLE_VALUE
      , DOC_LINE_ID_CHAR_2
      , PRODUCT_CATEGORY
      , GLOBAL_ATTRIBUTE_5
      , CONTRACT_END_DATE
      , DOC_LINE_ID_INT_4
      , PAYMENT_SET_ID
      , TAX_VENDOR_RETURN_CODE
      , LAST_PERIOD_TO_CREDIT
      , UOM_CODE
      , DOC_LINE_ID_INT_1
      , LINK_TO_PARENTLINE_ATTRIBUTE_7
      , LINK_TO_PARENTLINE_ATTRIBUTE_15
      , GLOBAL_ATTRIBUTE_18
      , CHRG_ACCTD_AMOUNT_REMAINING
      , FRT_ADJ_REMAINING
      , USER_DEFINED_FISC_CLASS
      , LINK_TO_PARENTLINE_ATTRIBUTE_3
      , GLOBAL_ATTRIBUTE_16
      , FAIR_MARKET_VALUE_AMOUNT
      , ATTRIBUTE_NUMBER_1
      , BR_REF_CUSTOMER_TRX_ID
      , UNIT_SELLING_PRICE
      , GLOBAL_ATTRIBUTE_DATE_5
      , EXTENDED_ACCTD_AMOUNT
      , ATTRIBUTE_9
      , ITEM_CONTEXT
      , INTERFACE_LINE_ATTRIBUTE_8
      , ATTRIBUTE_4
      , ATTRIBUTE_DATE_1
      , ATTRIBUTE_DATE_3
      , SALES_ORDER
      , TAX_CLASSIFICATION_CODE
      , SET_OF_BOOKS_ID
      , AUTHORIZATION_NUMBER
      , SALES_ORDER_LINE
      , INTERFACE_LINE_ATTRIBUTE_3
      , TAX_ACTION
      , GLOBAL_ATTRIBUTE_12
      , INTERFACE_LINE_CONTEXT
      , ACCTD_AMOUNT_DUE_REMAINING
      , DOC_LINE_ID_INT_3
      , GLOBAL_ATTRIBUTE_6
      , HISTORICAL_FLAG
      , INTERFACE_LINE_ATTRIBUTE_15
      , TAXABLE_AMOUNT
      , AUTORULE_DURATION_PROCESSED
      , TAX_LINE_ID
      , ATTRIBUTE_12
      , SHIP_TO_PARTY_ID
      , AMOUNT_DUE_REMAINING
      , DEFAULT_USSGL_TRX_CODE_CONTEXT
      , PREPAY_CUSTOMER_TRX_LINE_ID
      , DOC_LINE_ID_CHAR_4
      , PROGRAM_ID
      , LINE_NUMBER
      , ATTRIBUTE_DATE_4
      , LINK_TO_PARENTLINE_ATTRIBUTE_6
      , FINAL_DISCHARGE_LOCATION_ID
      , GLOBAL_ATTRIBUTE_13
      , INVOICED_LINE_ACCTG_LEVEL
      , OVERRIDE_AUTO_ACCOUNTING_FLAG
      , TAX_EXEMPT_NUMBER
      , ATTRIBUTE_2
      , INITIAL_CUSTOMER_TRX_LINE_ID
      , MEMO_LINE_SEQ_ID
      , LINK_TO_CUST_TRX_LINE_ID
      , SHIP_TO_PARTY_SITE_USE_ID
      , RECURRING_BILL_FLAG
      , PRODUCT_FISC_CLASSIFICATION
      , FRT_ED_ACCTD_AMOUNT
      , SOURCE_DOCUMENT_LINE_NUMBER
      , WH_UPDATE_DATE
      , TAXABLE_FLAG
      , GLOBAL_ATTRIBUTE_NUMBER_4
      , DEFAULT_USSGL_TRANSACTION_CODE
      , REQUEST_ID
      , GLOBAL_ATTRIBUTE_4
      , GLOBAL_ATTRIBUTE_DATE_4
      , ATTRIBUTE_NUMBER_4
      , SHIP_TO_CONTACT_ID
      , LINK_TO_PARENTLINE_ATTRIBUTE_1
      , INTERFACE_LINE_ATTRIBUTE_9
      , ATTRIBUTE_10
      , ATTRIBUTE_5
      , SHIP_TO_PARTY_ADDRESS_ID
      , LINK_TO_PARENTLINE_ATTRIBUTE_13
      , GLOBAL_ATTRIBUTE_3
      , SALES_ORDER_REVISION
      , VAT_TAX_ID
      , DOC_LINE_ID_CHAR_5
      , LINK_TO_PARENTLINE_ATTRIBUTE_2
      , GLOBAL_ATTRIBUTE_2
      , QUANTITY_ORDERED
      , SALES_ORDER_DATE
      , SOURCE_DATA_KEY_3
      , RULE_END_DATE
      , GLOBAL_ATTRIBUTE_CATEGORY
      , ATTRIBUTE_14
      , CREATED_BY
      , SHIP_TO_ADDRESS_ID
      , ACCOUNTING_RULE_DURATION
      , REMAINING_PREPAY_AMOUNT
      , GLOBAL_ATTRIBUTE_DATE_1
      , DESCRIPTION
      , AMOUNT_DUE_ORIGINAL
      , PREVIOUS_CUSTOMER_TRX_LINE_ID
      , GLOBAL_ATTRIBUTE_17
      , RECURRING_BILL_PLAN_LINE_ID
      , LINK_TO_PARENTLINE_ATTRIBUTE_9
      , CHRG_AMOUNT_REMAINING
      , SOURCE_DATA_KEY_1
      , LINK_TO_PARENTLINE_ATTRIBUTE_8
      , REQUIRES_MANUAL_SCHEDULING
      , GLOBAL_ATTRIBUTE_19
      , GROSS_EXTENDED_AMOUNT
      , ATTRIBUTE_15
      , GLOBAL_ATTRIBUTE_DATE_2
      , INTERFACE_LINE_ATTRIBUTE_11
      , INSURANCE_CHARGE
      , GLOBAL_ATTRIBUTE_NUMBER_5
      , LAST_UPDATE_LOGIN
      , ATTRIBUTE_8
      , LOCATION_SEGMENT_ID
      , TAX_EXEMPT_REASON_CODE
      , ATTRIBUTE_3
      , LINK_TO_PARENTLINE_ATTRIBUTE_10
      , GLOBAL_ATTRIBUTE_1
      , RULE_START_DATE
      , LINK_TO_PARENTLINE_CONTEXT
      , FREIGHT_CHARGE
      , INTERFACE_LINE_ATTRIBUTE_2
      , RECURRING_BILL_PLAN_ID
      , TRX_BUSINESS_CATEGORY
      , GLOBAL_ATTRIBUTE_NUMBER_2
      , PACKING_CHARGE
      , TAX_INVOICE_NUMBER
      , LINK_TO_PARENTLINE_ATTRIBUTE_11
      , AUTORULE_COMPLETE_FLAG
      , SALES_TAX_ID
      , ATTRIBUTE_DATE_2
      , GLOBAL_ATTRIBUTE_8
      , PREPAY_CUSTOMER_TRX_ID
      , ITEM_EXCEPTION_RATE_ID
      , LAST_UPDATED_BY
      , GLOBAL_ATTRIBUTE_15
      , ATTRIBUTE_CATEGORY
      , GLOBAL_ATTRIBUTE_7
      , PAYMENT_TRXN_EXTENSION_ID
      , _FIVETRAN_DELETED
      , _FIVETRAN_SYNCED
      , PSA_DELETE_IND
      , PSA_LOAD_DTS
      , PSA_RECORD_SOURCE
      , LOAD_DTS
      , REC_SRC
      , HASHDIFF
    FROM SRC_SINVLNFB
)
---- RENAME LAYER ----

, RENAME_SINVLNFB as (
    SELECT
        INVOICE_LINE_HK
      , CUSTOMER_TRX_LINE_ID
      , CUSTOMER_TRX_ID
      , ATTRIBUTE_7
      , INTERFACE_LINE_ATTRIBUTE_4
      , ACCTD_AMOUNT_DUE_ORIGINAL
      , BILL_PLAN_LINE_ID
      , ATTRIBUTE_11
      , INTERFACE_LINE_ATTRIBUTE_6
      , SALES_ORDER_SOURCE
      , ACCOUNTING_RULE_ID
      , BILLING_PERIOD_START_DATE
      , GLOBAL_ATTRIBUTE_NUMBER_3
      , BR_ADJUSTMENT_ID
      , MISCELLANEOUS_CHARGE
      , TRANSLATED_DESCRIPTION
      , UNIT_STANDARD_PRICE
      , DOC_LINE_ID_CHAR_1
      , QUANTITY_INVOICED
      , TAX_INVOICE_DATE
      , GLOBAL_ATTRIBUTE_11
      , COMMERCIAL_DISCOUNT
      , OBJECT_VERSION_NUMBER
      , GLOBAL_ATTRIBUTE_20
      , ATTRIBUTE_NUMBER_3
      , PRODUCT_TYPE
      , ATTRIBUTE_NUMBER_2
      , GLOBAL_ATTRIBUTE_DATE_3
      , EXTENDED_AMOUNT
      , ATTRIBUTE_DATE_5
      , PREVIOUS_CUSTOMER_TRX_ID
      , GROSS_UNIT_SELLING_PRICE
      , FRT_ADJ_ACCTD_REMAINING
      , INTERFACE_LINE_ATTRIBUTE_14
      , ATTRIBUTE_13
      , TAX_RECOVERABLE
      , LINK_TO_PARENTLINE_ATTRIBUTE_14
      , SOURCE_DATA_KEY_5
      , LINE_INTENDED_USE
      , LINK_TO_PARENTLINE_ATTRIBUTE_4
      , CREATION_DATE
      , REVENUE_AMOUNT
      , GLOBAL_ATTRIBUTE_10
      , REASON_CODE
      , INTERFACE_LINE_ATTRIBUTE_7
      , SHIP_TO_PARTY_CONTACT_ID
      , GLOBAL_ATTRIBUTE_NUMBER_1
      , MOVEMENT_ID
      , MRC_EXTENDED_ACCTD_AMOUNT
      , TAX_PRECEDENCE
      , CONTRACT_START_DATE
      , LINE_TYPE
      , FRT_ED_AMOUNT
      , LAST_UPDATE_DATE
      , AMOUNT_INCLUDES_TAX_FLAG
      , SOURCE_DOCUMENT_LINE_ID
      , TAX_RATE
      , PROGRAM_APPLICATION_ID
      , SOURCE_DATA_KEY_2
      , LINK_TO_PARENTLINE_ATTRIBUTE_12
      , ORG_ID
      , ATTRIBUTE_1
      , DOC_LINE_ID_INT_5
      , INTERFACE_LINE_ATTRIBUTE_12
      , QUANTITY_CREDITED
      , WAREHOUSE_ID
      , INTERFACE_LINE_ATTRIBUTE_13
      , AUTH_COMPLETE_FLAG
      , DOC_LINE_ID_INT_2
      , INVENTORY_ITEM_ID
      , LINE_RECOVERABLE
      , FRT_UNED_AMOUNT
      , INTERFACE_LINE_ATTRIBUTE_5
      , INTEREST_LINE_ID
      , PROGRAM_UPDATE_DATE
      , GLOBAL_ATTRIBUTE_9
      , TAX_EXEMPTION_ID
      , SHIP_TO_SITE_USE_ID
      , INTERFACE_LINE_ATTRIBUTE_1
      , LINK_TO_PARENTLINE_ATTRIBUTE_5
      , DEFERRAL_EXCLUSION_FLAG
      , ATTRIBUTE_6
      , BR_REF_PAYMENT_SCHEDULE_ID
      , SHIP_TO_CUSTOMER_ID
      , ATTRIBUTE_NUMBER_5
      , TAX_EXEMPT_FLAG
      , AUTOTAX
      , CONTRACT_LINE_ID
      , SOURCE_DATA_KEY_4
      , DOC_LINE_ID_CHAR_3
      , FRT_UNED_ACCTD_AMOUNT
      , INTERFACE_LINE_ATTRIBUTE_10
      , GLOBAL_ATTRIBUTE_14
      , BILLING_PERIOD_END_DATE
      , ASSESSABLE_VALUE
      , DOC_LINE_ID_CHAR_2
      , PRODUCT_CATEGORY
      , GLOBAL_ATTRIBUTE_5
      , CONTRACT_END_DATE
      , DOC_LINE_ID_INT_4
      , PAYMENT_SET_ID
      , TAX_VENDOR_RETURN_CODE
      , LAST_PERIOD_TO_CREDIT
      , UOM_CODE
      , DOC_LINE_ID_INT_1
      , LINK_TO_PARENTLINE_ATTRIBUTE_7
      , LINK_TO_PARENTLINE_ATTRIBUTE_15
      , GLOBAL_ATTRIBUTE_18
      , CHRG_ACCTD_AMOUNT_REMAINING
      , FRT_ADJ_REMAINING
      , USER_DEFINED_FISC_CLASS
      , LINK_TO_PARENTLINE_ATTRIBUTE_3
      , GLOBAL_ATTRIBUTE_16
      , FAIR_MARKET_VALUE_AMOUNT
      , ATTRIBUTE_NUMBER_1
      , BR_REF_CUSTOMER_TRX_ID
      , UNIT_SELLING_PRICE
      , GLOBAL_ATTRIBUTE_DATE_5
      , EXTENDED_ACCTD_AMOUNT
      , ATTRIBUTE_9
      , ITEM_CONTEXT
      , INTERFACE_LINE_ATTRIBUTE_8
      , ATTRIBUTE_4
      , ATTRIBUTE_DATE_1
      , ATTRIBUTE_DATE_3
      , SALES_ORDER
      , TAX_CLASSIFICATION_CODE
      , SET_OF_BOOKS_ID
      , AUTHORIZATION_NUMBER
      , SALES_ORDER_LINE
      , INTERFACE_LINE_ATTRIBUTE_3
      , TAX_ACTION
      , GLOBAL_ATTRIBUTE_12
      , INTERFACE_LINE_CONTEXT
      , ACCTD_AMOUNT_DUE_REMAINING
      , DOC_LINE_ID_INT_3
      , GLOBAL_ATTRIBUTE_6
      , HISTORICAL_FLAG
      , INTERFACE_LINE_ATTRIBUTE_15
      , TAXABLE_AMOUNT
      , AUTORULE_DURATION_PROCESSED
      , TAX_LINE_ID
      , ATTRIBUTE_12
      , SHIP_TO_PARTY_ID
      , AMOUNT_DUE_REMAINING
      , DEFAULT_USSGL_TRX_CODE_CONTEXT
      , PREPAY_CUSTOMER_TRX_LINE_ID
      , DOC_LINE_ID_CHAR_4
      , PROGRAM_ID
      , LINE_NUMBER
      , ATTRIBUTE_DATE_4
      , LINK_TO_PARENTLINE_ATTRIBUTE_6
      , FINAL_DISCHARGE_LOCATION_ID
      , GLOBAL_ATTRIBUTE_13
      , INVOICED_LINE_ACCTG_LEVEL
      , OVERRIDE_AUTO_ACCOUNTING_FLAG
      , TAX_EXEMPT_NUMBER
      , ATTRIBUTE_2
      , INITIAL_CUSTOMER_TRX_LINE_ID
      , MEMO_LINE_SEQ_ID
      , LINK_TO_CUST_TRX_LINE_ID
      , SHIP_TO_PARTY_SITE_USE_ID
      , RECURRING_BILL_FLAG
      , PRODUCT_FISC_CLASSIFICATION
      , FRT_ED_ACCTD_AMOUNT
      , SOURCE_DOCUMENT_LINE_NUMBER
      , WH_UPDATE_DATE
      , TAXABLE_FLAG
      , GLOBAL_ATTRIBUTE_NUMBER_4
      , DEFAULT_USSGL_TRANSACTION_CODE
      , REQUEST_ID
      , GLOBAL_ATTRIBUTE_4
      , GLOBAL_ATTRIBUTE_DATE_4
      , ATTRIBUTE_NUMBER_4
      , SHIP_TO_CONTACT_ID
      , LINK_TO_PARENTLINE_ATTRIBUTE_1
      , INTERFACE_LINE_ATTRIBUTE_9
      , ATTRIBUTE_10
      , ATTRIBUTE_5
      , SHIP_TO_PARTY_ADDRESS_ID
      , LINK_TO_PARENTLINE_ATTRIBUTE_13
      , GLOBAL_ATTRIBUTE_3
      , SALES_ORDER_REVISION
      , VAT_TAX_ID
      , DOC_LINE_ID_CHAR_5
      , LINK_TO_PARENTLINE_ATTRIBUTE_2
      , GLOBAL_ATTRIBUTE_2
      , QUANTITY_ORDERED
      , SALES_ORDER_DATE
      , SOURCE_DATA_KEY_3
      , RULE_END_DATE
      , GLOBAL_ATTRIBUTE_CATEGORY
      , ATTRIBUTE_14
      , CREATED_BY
      , SHIP_TO_ADDRESS_ID
      , ACCOUNTING_RULE_DURATION
      , REMAINING_PREPAY_AMOUNT
      , GLOBAL_ATTRIBUTE_DATE_1
      , DESCRIPTION
      , AMOUNT_DUE_ORIGINAL
      , PREVIOUS_CUSTOMER_TRX_LINE_ID
      , GLOBAL_ATTRIBUTE_17
      , RECURRING_BILL_PLAN_LINE_ID
      , LINK_TO_PARENTLINE_ATTRIBUTE_9
      , CHRG_AMOUNT_REMAINING
      , SOURCE_DATA_KEY_1
      , LINK_TO_PARENTLINE_ATTRIBUTE_8
      , REQUIRES_MANUAL_SCHEDULING
      , GLOBAL_ATTRIBUTE_19
      , GROSS_EXTENDED_AMOUNT
      , ATTRIBUTE_15
      , GLOBAL_ATTRIBUTE_DATE_2
      , INTERFACE_LINE_ATTRIBUTE_11
      , INSURANCE_CHARGE
      , GLOBAL_ATTRIBUTE_NUMBER_5
      , LAST_UPDATE_LOGIN
      , ATTRIBUTE_8
      , LOCATION_SEGMENT_ID
      , TAX_EXEMPT_REASON_CODE
      , ATTRIBUTE_3
      , LINK_TO_PARENTLINE_ATTRIBUTE_10
      , GLOBAL_ATTRIBUTE_1
      , RULE_START_DATE
      , LINK_TO_PARENTLINE_CONTEXT
      , FREIGHT_CHARGE
      , INTERFACE_LINE_ATTRIBUTE_2
      , RECURRING_BILL_PLAN_ID
      , TRX_BUSINESS_CATEGORY
      , GLOBAL_ATTRIBUTE_NUMBER_2
      , PACKING_CHARGE
      , TAX_INVOICE_NUMBER
      , LINK_TO_PARENTLINE_ATTRIBUTE_11
      , AUTORULE_COMPLETE_FLAG
      , SALES_TAX_ID
      , ATTRIBUTE_DATE_2
      , GLOBAL_ATTRIBUTE_8
      , PREPAY_CUSTOMER_TRX_ID
      , ITEM_EXCEPTION_RATE_ID
      , LAST_UPDATED_BY
      , GLOBAL_ATTRIBUTE_15
      , ATTRIBUTE_CATEGORY
      , GLOBAL_ATTRIBUTE_7
      , PAYMENT_TRXN_EXTENSION_ID
      , _FIVETRAN_DELETED
      , _FIVETRAN_SYNCED
      , PSA_DELETE_IND
      , PSA_LOAD_DTS
      , PSA_RECORD_SOURCE
      , LOAD_DTS
      , REC_SRC
      , HASHDIFF
    FROM LOGIC_SINVLNFB
)
---- FILTER LAYER ----

, FILTER_SINVLNFB as (
    SELECT *
    FROM RENAME_SINVLNFB
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM FILTER_SINVLNFB
)

---- FINAL LAYER ----
SELECT
          INVOICE_LINE_HK
        , CUSTOMER_TRX_LINE_ID
        , CUSTOMER_TRX_ID
        , ATTRIBUTE_7
        , INTERFACE_LINE_ATTRIBUTE_4
        , ACCTD_AMOUNT_DUE_ORIGINAL
        , BILL_PLAN_LINE_ID
        , ATTRIBUTE_11
        , INTERFACE_LINE_ATTRIBUTE_6
        , SALES_ORDER_SOURCE
        , ACCOUNTING_RULE_ID
        , BILLING_PERIOD_START_DATE
        , GLOBAL_ATTRIBUTE_NUMBER_3
        , BR_ADJUSTMENT_ID
        , MISCELLANEOUS_CHARGE
        , TRANSLATED_DESCRIPTION
        , UNIT_STANDARD_PRICE
        , DOC_LINE_ID_CHAR_1
        , QUANTITY_INVOICED
        , TAX_INVOICE_DATE
        , GLOBAL_ATTRIBUTE_11
        , COMMERCIAL_DISCOUNT
        , OBJECT_VERSION_NUMBER
        , GLOBAL_ATTRIBUTE_20
        , ATTRIBUTE_NUMBER_3
        , PRODUCT_TYPE
        , ATTRIBUTE_NUMBER_2
        , GLOBAL_ATTRIBUTE_DATE_3
        , EXTENDED_AMOUNT
        , ATTRIBUTE_DATE_5
        , PREVIOUS_CUSTOMER_TRX_ID
        , GROSS_UNIT_SELLING_PRICE
        , FRT_ADJ_ACCTD_REMAINING
        , INTERFACE_LINE_ATTRIBUTE_14
        , ATTRIBUTE_13
        , TAX_RECOVERABLE
        , LINK_TO_PARENTLINE_ATTRIBUTE_14
        , SOURCE_DATA_KEY_5
        , LINE_INTENDED_USE
        , LINK_TO_PARENTLINE_ATTRIBUTE_4
        , CREATION_DATE
        , REVENUE_AMOUNT
        , GLOBAL_ATTRIBUTE_10
        , REASON_CODE
        , INTERFACE_LINE_ATTRIBUTE_7
        , SHIP_TO_PARTY_CONTACT_ID
        , GLOBAL_ATTRIBUTE_NUMBER_1
        , MOVEMENT_ID
        , MRC_EXTENDED_ACCTD_AMOUNT
        , TAX_PRECEDENCE
        , CONTRACT_START_DATE
        , LINE_TYPE
        , FRT_ED_AMOUNT
        , LAST_UPDATE_DATE
        , AMOUNT_INCLUDES_TAX_FLAG
        , SOURCE_DOCUMENT_LINE_ID
        , TAX_RATE
        , PROGRAM_APPLICATION_ID
        , SOURCE_DATA_KEY_2
        , LINK_TO_PARENTLINE_ATTRIBUTE_12
        , ORG_ID
        , ATTRIBUTE_1
        , DOC_LINE_ID_INT_5
        , INTERFACE_LINE_ATTRIBUTE_12
        , QUANTITY_CREDITED
        , WAREHOUSE_ID
        , INTERFACE_LINE_ATTRIBUTE_13
        , AUTH_COMPLETE_FLAG
        , DOC_LINE_ID_INT_2
        , INVENTORY_ITEM_ID
        , LINE_RECOVERABLE
        , FRT_UNED_AMOUNT
        , INTERFACE_LINE_ATTRIBUTE_5
        , INTEREST_LINE_ID
        , PROGRAM_UPDATE_DATE
        , GLOBAL_ATTRIBUTE_9
        , TAX_EXEMPTION_ID
        , SHIP_TO_SITE_USE_ID
        , INTERFACE_LINE_ATTRIBUTE_1
        , LINK_TO_PARENTLINE_ATTRIBUTE_5
        , DEFERRAL_EXCLUSION_FLAG
        , ATTRIBUTE_6
        , BR_REF_PAYMENT_SCHEDULE_ID
        , SHIP_TO_CUSTOMER_ID
        , ATTRIBUTE_NUMBER_5
        , TAX_EXEMPT_FLAG
        , AUTOTAX
        , CONTRACT_LINE_ID
        , SOURCE_DATA_KEY_4
        , DOC_LINE_ID_CHAR_3
        , FRT_UNED_ACCTD_AMOUNT
        , INTERFACE_LINE_ATTRIBUTE_10
        , GLOBAL_ATTRIBUTE_14
        , BILLING_PERIOD_END_DATE
        , ASSESSABLE_VALUE
        , DOC_LINE_ID_CHAR_2
        , PRODUCT_CATEGORY
        , GLOBAL_ATTRIBUTE_5
        , CONTRACT_END_DATE
        , DOC_LINE_ID_INT_4
        , PAYMENT_SET_ID
        , TAX_VENDOR_RETURN_CODE
        , LAST_PERIOD_TO_CREDIT
        , UOM_CODE
        , DOC_LINE_ID_INT_1
        , LINK_TO_PARENTLINE_ATTRIBUTE_7
        , LINK_TO_PARENTLINE_ATTRIBUTE_15
        , GLOBAL_ATTRIBUTE_18
        , CHRG_ACCTD_AMOUNT_REMAINING
        , FRT_ADJ_REMAINING
        , USER_DEFINED_FISC_CLASS
        , LINK_TO_PARENTLINE_ATTRIBUTE_3
        , GLOBAL_ATTRIBUTE_16
        , FAIR_MARKET_VALUE_AMOUNT
        , ATTRIBUTE_NUMBER_1
        , BR_REF_CUSTOMER_TRX_ID
        , UNIT_SELLING_PRICE
        , GLOBAL_ATTRIBUTE_DATE_5
        , EXTENDED_ACCTD_AMOUNT
        , ATTRIBUTE_9
        , ITEM_CONTEXT
        , INTERFACE_LINE_ATTRIBUTE_8
        , ATTRIBUTE_4
        , ATTRIBUTE_DATE_1
        , ATTRIBUTE_DATE_3
        , SALES_ORDER
        , TAX_CLASSIFICATION_CODE
        , SET_OF_BOOKS_ID
        , AUTHORIZATION_NUMBER
        , SALES_ORDER_LINE
        , INTERFACE_LINE_ATTRIBUTE_3
        , TAX_ACTION
        , GLOBAL_ATTRIBUTE_12
        , INTERFACE_LINE_CONTEXT
        , ACCTD_AMOUNT_DUE_REMAINING
        , DOC_LINE_ID_INT_3
        , GLOBAL_ATTRIBUTE_6
        , HISTORICAL_FLAG
        , INTERFACE_LINE_ATTRIBUTE_15
        , TAXABLE_AMOUNT
        , AUTORULE_DURATION_PROCESSED
        , TAX_LINE_ID
        , ATTRIBUTE_12
        , SHIP_TO_PARTY_ID
        , AMOUNT_DUE_REMAINING
        , DEFAULT_USSGL_TRX_CODE_CONTEXT
        , PREPAY_CUSTOMER_TRX_LINE_ID
        , DOC_LINE_ID_CHAR_4
        , PROGRAM_ID
        , LINE_NUMBER
        , ATTRIBUTE_DATE_4
        , LINK_TO_PARENTLINE_ATTRIBUTE_6
        , FINAL_DISCHARGE_LOCATION_ID
        , GLOBAL_ATTRIBUTE_13
        , INVOICED_LINE_ACCTG_LEVEL
        , OVERRIDE_AUTO_ACCOUNTING_FLAG
        , TAX_EXEMPT_NUMBER
        , ATTRIBUTE_2
        , INITIAL_CUSTOMER_TRX_LINE_ID
        , MEMO_LINE_SEQ_ID
        , LINK_TO_CUST_TRX_LINE_ID
        , SHIP_TO_PARTY_SITE_USE_ID
        , RECURRING_BILL_FLAG
        , PRODUCT_FISC_CLASSIFICATION
        , FRT_ED_ACCTD_AMOUNT
        , SOURCE_DOCUMENT_LINE_NUMBER
        , WH_UPDATE_DATE
        , TAXABLE_FLAG
        , GLOBAL_ATTRIBUTE_NUMBER_4
        , DEFAULT_USSGL_TRANSACTION_CODE
        , REQUEST_ID
        , GLOBAL_ATTRIBUTE_4
        , GLOBAL_ATTRIBUTE_DATE_4
        , ATTRIBUTE_NUMBER_4
        , SHIP_TO_CONTACT_ID
        , LINK_TO_PARENTLINE_ATTRIBUTE_1
        , INTERFACE_LINE_ATTRIBUTE_9
        , ATTRIBUTE_10
        , ATTRIBUTE_5
        , SHIP_TO_PARTY_ADDRESS_ID
        , LINK_TO_PARENTLINE_ATTRIBUTE_13
        , GLOBAL_ATTRIBUTE_3
        , SALES_ORDER_REVISION
        , VAT_TAX_ID
        , DOC_LINE_ID_CHAR_5
        , LINK_TO_PARENTLINE_ATTRIBUTE_2
        , GLOBAL_ATTRIBUTE_2
        , QUANTITY_ORDERED
        , SALES_ORDER_DATE
        , SOURCE_DATA_KEY_3
        , RULE_END_DATE
        , GLOBAL_ATTRIBUTE_CATEGORY
        , ATTRIBUTE_14
        , CREATED_BY
        , SHIP_TO_ADDRESS_ID
        , ACCOUNTING_RULE_DURATION
        , REMAINING_PREPAY_AMOUNT
        , GLOBAL_ATTRIBUTE_DATE_1
        , DESCRIPTION
        , AMOUNT_DUE_ORIGINAL
        , PREVIOUS_CUSTOMER_TRX_LINE_ID
        , GLOBAL_ATTRIBUTE_17
        , RECURRING_BILL_PLAN_LINE_ID
        , LINK_TO_PARENTLINE_ATTRIBUTE_9
        , CHRG_AMOUNT_REMAINING
        , SOURCE_DATA_KEY_1
        , LINK_TO_PARENTLINE_ATTRIBUTE_8
        , REQUIRES_MANUAL_SCHEDULING
        , GLOBAL_ATTRIBUTE_19
        , GROSS_EXTENDED_AMOUNT
        , ATTRIBUTE_15
        , GLOBAL_ATTRIBUTE_DATE_2
        , INTERFACE_LINE_ATTRIBUTE_11
        , INSURANCE_CHARGE
        , GLOBAL_ATTRIBUTE_NUMBER_5
        , LAST_UPDATE_LOGIN
        , ATTRIBUTE_8
        , LOCATION_SEGMENT_ID
        , TAX_EXEMPT_REASON_CODE
        , ATTRIBUTE_3
        , LINK_TO_PARENTLINE_ATTRIBUTE_10
        , GLOBAL_ATTRIBUTE_1
        , RULE_START_DATE
        , LINK_TO_PARENTLINE_CONTEXT
        , FREIGHT_CHARGE
        , INTERFACE_LINE_ATTRIBUTE_2
        , RECURRING_BILL_PLAN_ID
        , TRX_BUSINESS_CATEGORY
        , GLOBAL_ATTRIBUTE_NUMBER_2
        , PACKING_CHARGE
        , TAX_INVOICE_NUMBER
        , LINK_TO_PARENTLINE_ATTRIBUTE_11
        , AUTORULE_COMPLETE_FLAG
        , SALES_TAX_ID
        , ATTRIBUTE_DATE_2
        , GLOBAL_ATTRIBUTE_8
        , PREPAY_CUSTOMER_TRX_ID
        , ITEM_EXCEPTION_RATE_ID
        , LAST_UPDATED_BY
        , GLOBAL_ATTRIBUTE_15
        , ATTRIBUTE_CATEGORY
        , GLOBAL_ATTRIBUTE_7
        , PAYMENT_TRXN_EXTENSION_ID
        , _FIVETRAN_DELETED
        , _FIVETRAN_SYNCED
        , PSA_DELETE_IND
        , PSA_LOAD_DTS
        , PSA_RECORD_SOURCE
        , LOAD_DTS
        , REC_SRC
        , HASHDIFF
FROM JOIN_RESULT
{% if is_incremental() %}
WHERE NOT EXISTS (
    SELECT 1 
    FROM {{ this }} existing
    WHERE existing.INVOICE_LINE_HK = JOIN_RESULT.INVOICE_LINE_HK
    AND existing.HASHDIFF = JOIN_RESULT.HASHDIFF
)
{% endif %}
{% if not is_incremental() %}

/* The following qualifier is implemented to prevent multiple loads of touched records during the initial build, such as multiple rows per HK and hashdiff. */
qualify 1 = row_number() over (partition by INVOICE_LINE_HK, HASHDIFF order by PSA_LOAD_DTS)

union all
SELECT 
MD5_BINARY(GR.VALUE) AS INVOICE_LINE_HK,
GR.VALUE::number AS CUSTOMER_TRX_LINE_ID,
GR.VALUE::number AS CUSTOMER_TRX_ID,
NULL AS ATTRIBUTE_7,
NULL AS INTERFACE_LINE_ATTRIBUTE_4,
NULL AS ACCTD_AMOUNT_DUE_ORIGINAL,
NULL AS BILL_PLAN_LINE_ID,
NULL AS ATTRIBUTE_11,
NULL AS INTERFACE_LINE_ATTRIBUTE_6,
NULL AS SALES_ORDER_SOURCE,
NULL AS ACCOUNTING_RULE_ID,
NULL AS BILLING_PERIOD_START_DATE,
NULL AS GLOBAL_ATTRIBUTE_NUMBER_3,
NULL AS BR_ADJUSTMENT_ID,
NULL AS MISCELLANEOUS_CHARGE,
NULL AS TRANSLATED_DESCRIPTION,
NULL AS UNIT_STANDARD_PRICE,
NULL AS DOC_LINE_ID_CHAR_1,
NULL AS QUANTITY_INVOICED,
NULL AS TAX_INVOICE_DATE,
NULL AS GLOBAL_ATTRIBUTE_11,
NULL AS COMMERCIAL_DISCOUNT,
NULL AS OBJECT_VERSION_NUMBER,
NULL AS GLOBAL_ATTRIBUTE_20,
NULL AS ATTRIBUTE_NUMBER_3,
NULL AS PRODUCT_TYPE,
NULL AS ATTRIBUTE_NUMBER_2,
NULL AS GLOBAL_ATTRIBUTE_DATE_3,
NULL AS EXTENDED_AMOUNT,
NULL AS ATTRIBUTE_DATE_5,
NULL AS PREVIOUS_CUSTOMER_TRX_ID,
NULL AS GROSS_UNIT_SELLING_PRICE,
NULL AS FRT_ADJ_ACCTD_REMAINING,
NULL AS INTERFACE_LINE_ATTRIBUTE_14,
NULL AS ATTRIBUTE_13,
NULL AS TAX_RECOVERABLE,
NULL AS LINK_TO_PARENTLINE_ATTRIBUTE_14,
NULL AS SOURCE_DATA_KEY_5,
NULL AS LINE_INTENDED_USE,
NULL AS LINK_TO_PARENTLINE_ATTRIBUTE_4,
NULL AS CREATION_DATE,
NULL AS REVENUE_AMOUNT,
NULL AS GLOBAL_ATTRIBUTE_10,
NULL AS REASON_CODE,
NULL AS INTERFACE_LINE_ATTRIBUTE_7,
NULL AS SHIP_TO_PARTY_CONTACT_ID,
NULL AS GLOBAL_ATTRIBUTE_NUMBER_1,
NULL AS MOVEMENT_ID,
NULL AS MRC_EXTENDED_ACCTD_AMOUNT,
NULL AS TAX_PRECEDENCE,
NULL AS CONTRACT_START_DATE,
NULL AS LINE_TYPE,
NULL AS FRT_ED_AMOUNT,
NULL AS LAST_UPDATE_DATE,
NULL AS AMOUNT_INCLUDES_TAX_FLAG,
NULL AS SOURCE_DOCUMENT_LINE_ID,
NULL AS TAX_RATE,
NULL AS PROGRAM_APPLICATION_ID,
NULL AS SOURCE_DATA_KEY_2,
NULL AS LINK_TO_PARENTLINE_ATTRIBUTE_12,
NULL AS ORG_ID,
NULL AS ATTRIBUTE_1,
NULL AS DOC_LINE_ID_INT_5,
NULL AS INTERFACE_LINE_ATTRIBUTE_12,
NULL AS QUANTITY_CREDITED,
NULL AS WAREHOUSE_ID,
NULL AS INTERFACE_LINE_ATTRIBUTE_13,
NULL AS AUTH_COMPLETE_FLAG,
NULL AS DOC_LINE_ID_INT_2,
NULL AS INVENTORY_ITEM_ID,
NULL AS LINE_RECOVERABLE,
NULL AS FRT_UNED_AMOUNT,
NULL AS INTERFACE_LINE_ATTRIBUTE_5,
NULL AS INTEREST_LINE_ID,
NULL AS PROGRAM_UPDATE_DATE,
NULL AS GLOBAL_ATTRIBUTE_9,
NULL AS TAX_EXEMPTION_ID,
NULL AS SHIP_TO_SITE_USE_ID,
NULL AS INTERFACE_LINE_ATTRIBUTE_1,
NULL AS LINK_TO_PARENTLINE_ATTRIBUTE_5,
NULL AS DEFERRAL_EXCLUSION_FLAG,
NULL AS ATTRIBUTE_6,
NULL AS BR_REF_PAYMENT_SCHEDULE_ID,
NULL AS SHIP_TO_CUSTOMER_ID,
NULL AS ATTRIBUTE_NUMBER_5,
NULL AS TAX_EXEMPT_FLAG,
NULL AS AUTOTAX,
NULL AS CONTRACT_LINE_ID,
NULL AS SOURCE_DATA_KEY_4,
NULL AS DOC_LINE_ID_CHAR_3,
NULL AS FRT_UNED_ACCTD_AMOUNT,
NULL AS INTERFACE_LINE_ATTRIBUTE_10,
NULL AS GLOBAL_ATTRIBUTE_14,
NULL AS BILLING_PERIOD_END_DATE,
NULL AS ASSESSABLE_VALUE,
NULL AS DOC_LINE_ID_CHAR_2,
NULL AS PRODUCT_CATEGORY,
NULL AS GLOBAL_ATTRIBUTE_5,
NULL AS CONTRACT_END_DATE,
NULL AS DOC_LINE_ID_INT_4,
NULL AS PAYMENT_SET_ID,
NULL AS TAX_VENDOR_RETURN_CODE,
NULL AS LAST_PERIOD_TO_CREDIT,
NULL AS UOM_CODE,
NULL AS DOC_LINE_ID_INT_1,
NULL AS LINK_TO_PARENTLINE_ATTRIBUTE_7,
NULL AS LINK_TO_PARENTLINE_ATTRIBUTE_15,
NULL AS GLOBAL_ATTRIBUTE_18,
NULL AS CHRG_ACCTD_AMOUNT_REMAINING,
NULL AS FRT_ADJ_REMAINING,
NULL AS USER_DEFINED_FISC_CLASS,
NULL AS LINK_TO_PARENTLINE_ATTRIBUTE_3,
NULL AS GLOBAL_ATTRIBUTE_16,
NULL AS FAIR_MARKET_VALUE_AMOUNT,
NULL AS ATTRIBUTE_NUMBER_1,
NULL AS BR_REF_CUSTOMER_TRX_ID,
NULL AS UNIT_SELLING_PRICE,
NULL AS GLOBAL_ATTRIBUTE_DATE_5,
NULL AS EXTENDED_ACCTD_AMOUNT,
NULL AS ATTRIBUTE_9,
NULL AS ITEM_CONTEXT,
NULL AS INTERFACE_LINE_ATTRIBUTE_8,
NULL AS ATTRIBUTE_4,
NULL AS ATTRIBUTE_DATE_1,
NULL AS ATTRIBUTE_DATE_3,
NULL AS SALES_ORDER,
NULL AS TAX_CLASSIFICATION_CODE,
NULL AS SET_OF_BOOKS_ID,
NULL AS AUTHORIZATION_NUMBER,
NULL AS SALES_ORDER_LINE,
NULL AS INTERFACE_LINE_ATTRIBUTE_3,
NULL AS TAX_ACTION,
NULL AS GLOBAL_ATTRIBUTE_12,
NULL AS INTERFACE_LINE_CONTEXT,
NULL AS ACCTD_AMOUNT_DUE_REMAINING,
NULL AS DOC_LINE_ID_INT_3,
NULL AS GLOBAL_ATTRIBUTE_6,
NULL AS HISTORICAL_FLAG,
NULL AS INTERFACE_LINE_ATTRIBUTE_15,
NULL AS TAXABLE_AMOUNT,
NULL AS AUTORULE_DURATION_PROCESSED,
NULL AS TAX_LINE_ID,
NULL AS ATTRIBUTE_12,
NULL AS SHIP_TO_PARTY_ID,
NULL AS AMOUNT_DUE_REMAINING,
NULL AS DEFAULT_USSGL_TRX_CODE_CONTEXT,
NULL AS PREPAY_CUSTOMER_TRX_LINE_ID,
NULL AS DOC_LINE_ID_CHAR_4,
NULL AS PROGRAM_ID,
NULL AS LINE_NUMBER,
NULL AS ATTRIBUTE_DATE_4,
NULL AS LINK_TO_PARENTLINE_ATTRIBUTE_6,
NULL AS FINAL_DISCHARGE_LOCATION_ID,
NULL AS GLOBAL_ATTRIBUTE_13,
NULL AS INVOICED_LINE_ACCTG_LEVEL,
NULL AS OVERRIDE_AUTO_ACCOUNTING_FLAG,
NULL AS TAX_EXEMPT_NUMBER,
NULL AS ATTRIBUTE_2,
NULL AS INITIAL_CUSTOMER_TRX_LINE_ID,
NULL AS MEMO_LINE_SEQ_ID,
NULL AS LINK_TO_CUST_TRX_LINE_ID,
NULL AS SHIP_TO_PARTY_SITE_USE_ID,
NULL AS RECURRING_BILL_FLAG,
NULL AS PRODUCT_FISC_CLASSIFICATION,
NULL AS FRT_ED_ACCTD_AMOUNT,
NULL AS SOURCE_DOCUMENT_LINE_NUMBER,
NULL AS WH_UPDATE_DATE,
NULL AS TAXABLE_FLAG,
NULL AS GLOBAL_ATTRIBUTE_NUMBER_4,
NULL AS DEFAULT_USSGL_TRANSACTION_CODE,
NULL AS REQUEST_ID,
NULL AS GLOBAL_ATTRIBUTE_4,
NULL AS GLOBAL_ATTRIBUTE_DATE_4,
NULL AS ATTRIBUTE_NUMBER_4,
NULL AS SHIP_TO_CONTACT_ID,
NULL AS LINK_TO_PARENTLINE_ATTRIBUTE_1,
NULL AS INTERFACE_LINE_ATTRIBUTE_9,
NULL AS ATTRIBUTE_10,
NULL AS ATTRIBUTE_5,
NULL AS SHIP_TO_PARTY_ADDRESS_ID,
NULL AS LINK_TO_PARENTLINE_ATTRIBUTE_13,
NULL AS GLOBAL_ATTRIBUTE_3,
NULL AS SALES_ORDER_REVISION,
NULL AS VAT_TAX_ID,
NULL AS DOC_LINE_ID_CHAR_5,
NULL AS LINK_TO_PARENTLINE_ATTRIBUTE_2,
NULL AS GLOBAL_ATTRIBUTE_2,
NULL AS QUANTITY_ORDERED,
NULL AS SALES_ORDER_DATE,
NULL AS SOURCE_DATA_KEY_3,
NULL AS RULE_END_DATE,
NULL AS GLOBAL_ATTRIBUTE_CATEGORY,
NULL AS ATTRIBUTE_14,
NULL AS CREATED_BY,
NULL AS SHIP_TO_ADDRESS_ID,
NULL AS ACCOUNTING_RULE_DURATION,
NULL AS REMAINING_PREPAY_AMOUNT,
NULL AS GLOBAL_ATTRIBUTE_DATE_1,
NULL AS DESCRIPTION,
NULL AS AMOUNT_DUE_ORIGINAL,
NULL AS PREVIOUS_CUSTOMER_TRX_LINE_ID,
NULL AS GLOBAL_ATTRIBUTE_17,
NULL AS RECURRING_BILL_PLAN_LINE_ID,
NULL AS LINK_TO_PARENTLINE_ATTRIBUTE_9,
NULL AS CHRG_AMOUNT_REMAINING,
NULL AS SOURCE_DATA_KEY_1,
NULL AS LINK_TO_PARENTLINE_ATTRIBUTE_8,
NULL AS REQUIRES_MANUAL_SCHEDULING,
NULL AS GLOBAL_ATTRIBUTE_19,
NULL AS GROSS_EXTENDED_AMOUNT,
NULL AS ATTRIBUTE_15,
NULL AS GLOBAL_ATTRIBUTE_DATE_2,
NULL AS INTERFACE_LINE_ATTRIBUTE_11,
NULL AS INSURANCE_CHARGE,
NULL AS GLOBAL_ATTRIBUTE_NUMBER_5,
NULL AS LAST_UPDATE_LOGIN,
NULL AS ATTRIBUTE_8,
NULL AS LOCATION_SEGMENT_ID,
NULL AS TAX_EXEMPT_REASON_CODE,
NULL AS ATTRIBUTE_3,
NULL AS LINK_TO_PARENTLINE_ATTRIBUTE_10,
NULL AS GLOBAL_ATTRIBUTE_1,
NULL AS RULE_START_DATE,
NULL AS LINK_TO_PARENTLINE_CONTEXT,
NULL AS FREIGHT_CHARGE,
NULL AS INTERFACE_LINE_ATTRIBUTE_2,
NULL AS RECURRING_BILL_PLAN_ID,
NULL AS TRX_BUSINESS_CATEGORY,
NULL AS GLOBAL_ATTRIBUTE_NUMBER_2,
NULL AS PACKING_CHARGE,
NULL AS TAX_INVOICE_NUMBER,
NULL AS LINK_TO_PARENTLINE_ATTRIBUTE_11,
NULL AS AUTORULE_COMPLETE_FLAG,
NULL AS SALES_TAX_ID,
NULL AS ATTRIBUTE_DATE_2,
NULL AS GLOBAL_ATTRIBUTE_8,
NULL AS PREPAY_CUSTOMER_TRX_ID,
NULL AS ITEM_EXCEPTION_RATE_ID,
NULL AS LAST_UPDATED_BY,
NULL AS GLOBAL_ATTRIBUTE_15,
NULL AS ATTRIBUTE_CATEGORY,
NULL AS GLOBAL_ATTRIBUTE_7,
NULL AS PAYMENT_TRXN_EXTENSION_ID,
NULL AS _FIVETRAN_DELETED,
NULL AS _FIVETRAN_SYNCED,
'N' AS PSA_DELETE_IND,
'1900-01-01'::TIMESTAMP AS PSA_LOAD_DTS,
NULL AS PSA_RECORD_SOURCE,
CONVERT_TIMEZONE('UTC','1900-01-01'::TIMESTAMP) AS LOAD_DTS,
'USAZET.SNOWFLAKE.FBIN.DERIVED' AS REC_SRC,
''::BINARY AS HASHDIFF
FROM
TABLE(strtok_split_to_table('0|-1|-2', '|')) AS GR
{% endif %}
