---- SRC LAYER ----
WITH
SRC_ttemtk         as ( 
    SELECT 
        PO_HEADER_HK,
        PO_HEADER_ID,
        AGENT_ID,
        TYPE_LOOKUP_CODE,
        LAST_UPDATE_DATE,
        LAST_UPDATED_BY,
        SEGMENT1,
        SUMMARY_FLAG,
        ENABLED_FLAG,
        SEGMENT2,
        SEGMENT3,
        SEGMENT4,
        SEGMENT5,
        START_DATE_ACTIVE,
        END_DATE_ACTIVE,
        LAST_UPDATE_LOGIN,
        CREATION_DATE,
        CREATED_BY,
        VENDOR_ID,
        VENDOR_SITE_ID,
        VENDOR_CONTACT_ID,
        SHIP_TO_LOCATION_ID,
        BILL_TO_LOCATION_ID,
        TERMS_ID,
        SHIP_VIA_LOOKUP_CODE,
        FOB_LOOKUP_CODE,
        FREIGHT_TERMS_LOOKUP_CODE,
        STATUS_LOOKUP_CODE,
        CURRENCY_CODE,
        RATE_TYPE,
        RATE_DATE,
        RATE,
        FROM_HEADER_ID,
        FROM_TYPE_LOOKUP_CODE,
        START_DATE,
        END_DATE,
        BLANKET_TOTAL_AMOUNT,
        AUTHORIZATION_STATUS,
        REVISION_NUM,
        REVISED_DATE,
        APPROVED_FLAG,
        APPROVED_DATE,
        AMOUNT_LIMIT,
        MIN_RELEASE_AMOUNT,
        NOTE_TO_AUTHORIZER,
        NOTE_TO_VENDOR,
        NOTE_TO_RECEIVER,
        PRINT_COUNT,
        PRINTED_DATE,
        VENDOR_ORDER_NUM,
        CONFIRMING_ORDER_FLAG,
        COMMENTS,
        REPLY_DATE,
        REPLY_METHOD_LOOKUP_CODE,
        RFQ_CLOSE_DATE,
        QUOTE_TYPE_LOOKUP_CODE,
        QUOTATION_CLASS_CODE,
        QUOTE_WARNING_DELAY_UNIT,
        QUOTE_WARNING_DELAY,
        QUOTE_VENDOR_QUOTE_NUMBER,
        ACCEPTANCE_REQUIRED_FLAG,
        ACCEPTANCE_DUE_DATE,
        CLOSED_DATE,
        USER_HOLD_FLAG,
        APPROVAL_REQUIRED_FLAG,
        CANCEL_FLAG,
        FIRM_STATUS_LOOKUP_CODE,
        FIRM_DATE,
        FROZEN_FLAG,
        SUPPLY_AGREEMENT_FLAG,
        EDI_PROCESSED_FLAG,
        EDI_PROCESSED_STATUS,
        ATTRIBUTE_CATEGORY,
        ATTRIBUTE1,
        ATTRIBUTE2,
        ATTRIBUTE3,
        ATTRIBUTE4,
        ATTRIBUTE5,
        ATTRIBUTE6,
        ATTRIBUTE7,
        ATTRIBUTE8,
        ATTRIBUTE9,
        ATTRIBUTE10,
        ATTRIBUTE11,
        ATTRIBUTE12,
        ATTRIBUTE13,
        ATTRIBUTE14,
        ATTRIBUTE15,
        CLOSED_CODE,
        USSGL_TRANSACTION_CODE,
        GOVERNMENT_CONTEXT,
        REQUEST_ID,
        PROGRAM_APPLICATION_ID,
        PROGRAM_ID,
        PROGRAM_UPDATE_DATE,
        ORG_ID,
        GLOBAL_ATTRIBUTE_CATEGORY,
        GLOBAL_ATTRIBUTE1,
        GLOBAL_ATTRIBUTE2,
        GLOBAL_ATTRIBUTE3,
        GLOBAL_ATTRIBUTE4,
        GLOBAL_ATTRIBUTE5,
        GLOBAL_ATTRIBUTE6,
        GLOBAL_ATTRIBUTE7,
        GLOBAL_ATTRIBUTE8,
        GLOBAL_ATTRIBUTE9,
        GLOBAL_ATTRIBUTE10,
        GLOBAL_ATTRIBUTE11,
        GLOBAL_ATTRIBUTE12,
        GLOBAL_ATTRIBUTE13,
        GLOBAL_ATTRIBUTE14,
        GLOBAL_ATTRIBUTE15,
        GLOBAL_ATTRIBUTE16,
        GLOBAL_ATTRIBUTE17,
        GLOBAL_ATTRIBUTE18,
        GLOBAL_ATTRIBUTE19,
        GLOBAL_ATTRIBUTE20,
        INTERFACE_SOURCE_CODE,
        REFERENCE_NUM,
        WF_ITEM_TYPE,
        WF_ITEM_KEY,
        MRC_RATE_TYPE,
        MRC_RATE_DATE,
        MRC_RATE,
        PCARD_ID,
        PRICE_UPDATE_TOLERANCE,
        PAY_ON_CODE,
        XML_FLAG,
        XML_SEND_DATE,
        XML_CHANGE_SEND_DATE,
        GLOBAL_AGREEMENT_FLAG,
        CONSIGNED_CONSUMPTION_FLAG,
        CBC_ACCOUNTING_DATE,
        CONSUME_REQ_DEMAND_FLAG,
        CHANGE_REQUESTED_BY,
        SHIPPING_CONTROL,
        CONTERMS_EXIST_FLAG,
        CONTERMS_ARTICLES_UPD_DATE,
        CONTERMS_DELIV_UPD_DATE,
        ENCUMBRANCE_REQUIRED_FLAG,
        PENDING_SIGNATURE_FLAG,
        CHANGE_SUMMARY,
        DOCUMENT_CREATION_METHOD,
        SUBMIT_DATE,
        ENABLE_ALL_SITES,
        CREATED_LANGUAGE,
        CPA_REFERENCE,
        LAST_UPDATED_PROGRAM,
        OTM_STATUS_CODE,
        OTM_RECOVERY_FLAG,
        COMM_REV_NUM,
        SUPPLIER_NOTIF_METHOD,
        FAX,
        EMAIL_ADDRESS,
        RETRO_PRICE_COMM_UPDATES_FLAG,
        RETRO_PRICE_APPLY_UPDATES_FLAG,
        UPDATE_SOURCING_RULES_FLAG,
        AUTO_SOURCING_FLAG,
        LOCK_OWNER_ROLE,
        LOCK_OWNER_USER_ID,
        SUPPLIER_AUTH_ENABLED_FLAG,
        CAT_ADMIN_AUTH_ENABLED_FLAG,
        STYLE_ID,
        TAX_ATTRIBUTE_UPDATE_CODE,
        PAY_WHEN_PAID,
        UDA_TEMPLATE_ID,
        UDA_TEMPLATE_DATE,
        USER_DOCUMENT_STATUS,
        AME_APPROVAL_ID,
        DRAFT_ID,
        CLM_EFFECTIVE_DATE,
        CLM_VENDOR_OFFER_NUMBER,
        CLM_AWARD_ADMINISTRATOR,
        CLM_NO_SIGNED_COPIES_TO_RETURN,
        CLM_MIN_GUARANTEE_AWARD_AMT,
        CLM_MIN_GUAR_AWARD_AMT_PERCENT,
        CLM_MIN_ORDER_AMOUNT,
        CLM_MAX_ORDER_AMOUNT,
        CLM_AMT_SYNCED_TO_AGREEMENT,
        CLM_AMOUNT_RELEASED,
        CLM_EXTERNAL_IDV,
        CLM_SUPPLIER_NAME,
        CLM_SUPPLIER_SITE_NAME,
        CLM_DOCUMENT_NUMBER,
        CLM_SOURCE_DOCUMENT_ID,
        CLM_ISSUING_OFFICE,
        CLM_COTR_OFFICE,
        CLM_COTR_CONTACT,
        CLM_PRIORITY_CODE,
        CLM_MOD_ISSUING_OFFICE,
        CLM_STANDARD_FORM,
        CLM_DOCUMENT_FORMAT,
        AME_TRANSACTION_TYPE,
        CLM_AWARD_TYPE,
        CLM_CONTRACT_OFFICER,
        CLM_CLOSEOUT_STATUS,
        UMBRELLA_PROGRAM_ID,
        FON_REF_ID,
        CLM_DEFAULT_DIST_FLAG,
        CLM_EDAGEN_DATE,
        CLM_CONTRACT_FINANCE_CODE,
        CLM_PAYMENT_INSTR_CODE,
        CLM_SPECIAL_CONTRACT_TYPE,
        IGT_DOCUMENT_NUMBER,
        IGT_GTNC_NUMBER,
        IGT_STATUS,
        AGREEMENT_TYPE,
        ASSISTED_ACQUISITION_IND,
        ADVANCE_PAYMENT_IND,
        ENFORCE_TOTAL_AMT_IND,
        TERMINATION_DAYS,
        TOTAL_REMAINING_AMT,
        IGT_BUSINESS_TXN_ID,
        TERM_DESCRIPTION,
        _FIVETRAN_ID,
        _FIVETRAN_DELETED,
        _FIVETRAN_SYNCED,
        PSA_LOAD_DTS,
        PSA_RECORD_SOURCE,
        PSA_DELETE_IND,
        LOAD_DTS,
        REC_SRC,
        BKCC,
        HASHDIFF
    FROM {{ ref('v_psa_stg_po_header__emtk_ebs') }} as SRC
    {% if is_incremental() %}
    WHERE src.load_dts > (SELECT dateadd('HOUR', -1, max(load_dts)) FROM {{ this }})
    {% endif %}
)

/*
SRC_ttemtk         as ( SELECT * FROM STAGING.v_psa_stg_po_header__emtk_ebs )
*/
---- LOGIC LAYER ----

, LOGIC_ttemtk as (
    SELECT
        PO_HEADER_HK
      , PO_HEADER_ID
      , AGENT_ID
      , TYPE_LOOKUP_CODE
      , LAST_UPDATE_DATE
      , LAST_UPDATED_BY
      , SEGMENT1
      , SUMMARY_FLAG
      , ENABLED_FLAG
      , SEGMENT2
      , SEGMENT3
      , SEGMENT4
      , SEGMENT5
      , START_DATE_ACTIVE
      , END_DATE_ACTIVE
      , LAST_UPDATE_LOGIN
      , CREATION_DATE
      , CREATED_BY
      , VENDOR_ID
      , VENDOR_SITE_ID
      , VENDOR_CONTACT_ID
      , SHIP_TO_LOCATION_ID
      , BILL_TO_LOCATION_ID
      , TERMS_ID
      , SHIP_VIA_LOOKUP_CODE
      , FOB_LOOKUP_CODE
      , FREIGHT_TERMS_LOOKUP_CODE
      , STATUS_LOOKUP_CODE
      , CURRENCY_CODE
      , RATE_TYPE
      , RATE_DATE
      , RATE
      , FROM_HEADER_ID
      , FROM_TYPE_LOOKUP_CODE
      , START_DATE
      , END_DATE
      , BLANKET_TOTAL_AMOUNT
      , AUTHORIZATION_STATUS
      , REVISION_NUM
      , REVISED_DATE
      , APPROVED_FLAG
      , APPROVED_DATE
      , AMOUNT_LIMIT
      , MIN_RELEASE_AMOUNT
      , NOTE_TO_AUTHORIZER
      , NOTE_TO_VENDOR
      , NOTE_TO_RECEIVER
      , PRINT_COUNT
      , PRINTED_DATE
      , VENDOR_ORDER_NUM
      , CONFIRMING_ORDER_FLAG
      , COMMENTS
      , REPLY_DATE
      , REPLY_METHOD_LOOKUP_CODE
      , RFQ_CLOSE_DATE
      , QUOTE_TYPE_LOOKUP_CODE
      , QUOTATION_CLASS_CODE
      , QUOTE_WARNING_DELAY_UNIT
      , QUOTE_WARNING_DELAY
      , QUOTE_VENDOR_QUOTE_NUMBER
      , ACCEPTANCE_REQUIRED_FLAG
      , ACCEPTANCE_DUE_DATE
      , CLOSED_DATE
      , USER_HOLD_FLAG
      , APPROVAL_REQUIRED_FLAG
      , CANCEL_FLAG
      , FIRM_STATUS_LOOKUP_CODE
      , FIRM_DATE
      , FROZEN_FLAG
      , SUPPLY_AGREEMENT_FLAG
      , EDI_PROCESSED_FLAG
      , EDI_PROCESSED_STATUS
      , ATTRIBUTE_CATEGORY
      , ATTRIBUTE1
      , ATTRIBUTE2
      , ATTRIBUTE3
      , ATTRIBUTE4
      , ATTRIBUTE5
      , ATTRIBUTE6
      , ATTRIBUTE7
      , ATTRIBUTE8
      , ATTRIBUTE9
      , ATTRIBUTE10
      , ATTRIBUTE11
      , ATTRIBUTE12
      , ATTRIBUTE13
      , ATTRIBUTE14
      , ATTRIBUTE15
      , CLOSED_CODE
      , USSGL_TRANSACTION_CODE
      , GOVERNMENT_CONTEXT
      , REQUEST_ID
      , PROGRAM_APPLICATION_ID
      , PROGRAM_ID
      , PROGRAM_UPDATE_DATE
      , ORG_ID
      , GLOBAL_ATTRIBUTE_CATEGORY
      , GLOBAL_ATTRIBUTE1
      , GLOBAL_ATTRIBUTE2
      , GLOBAL_ATTRIBUTE3
      , GLOBAL_ATTRIBUTE4
      , GLOBAL_ATTRIBUTE5
      , GLOBAL_ATTRIBUTE6
      , GLOBAL_ATTRIBUTE7
      , GLOBAL_ATTRIBUTE8
      , GLOBAL_ATTRIBUTE9
      , GLOBAL_ATTRIBUTE10
      , GLOBAL_ATTRIBUTE11
      , GLOBAL_ATTRIBUTE12
      , GLOBAL_ATTRIBUTE13
      , GLOBAL_ATTRIBUTE14
      , GLOBAL_ATTRIBUTE15
      , GLOBAL_ATTRIBUTE16
      , GLOBAL_ATTRIBUTE17
      , GLOBAL_ATTRIBUTE18
      , GLOBAL_ATTRIBUTE19
      , GLOBAL_ATTRIBUTE20
      , INTERFACE_SOURCE_CODE
      , REFERENCE_NUM
      , WF_ITEM_TYPE
      , WF_ITEM_KEY
      , MRC_RATE_TYPE
      , MRC_RATE_DATE
      , MRC_RATE
      , PCARD_ID
      , PRICE_UPDATE_TOLERANCE
      , PAY_ON_CODE
      , XML_FLAG
      , XML_SEND_DATE
      , XML_CHANGE_SEND_DATE
      , GLOBAL_AGREEMENT_FLAG
      , CONSIGNED_CONSUMPTION_FLAG
      , CBC_ACCOUNTING_DATE
      , CONSUME_REQ_DEMAND_FLAG
      , CHANGE_REQUESTED_BY
      , SHIPPING_CONTROL
      , CONTERMS_EXIST_FLAG
      , CONTERMS_ARTICLES_UPD_DATE
      , CONTERMS_DELIV_UPD_DATE
      , ENCUMBRANCE_REQUIRED_FLAG
      , PENDING_SIGNATURE_FLAG
      , CHANGE_SUMMARY
      , DOCUMENT_CREATION_METHOD
      , SUBMIT_DATE
      , ENABLE_ALL_SITES
      , CREATED_LANGUAGE
      , CPA_REFERENCE
      , LAST_UPDATED_PROGRAM
      , OTM_STATUS_CODE
      , OTM_RECOVERY_FLAG
      , COMM_REV_NUM
      , SUPPLIER_NOTIF_METHOD
      , FAX
      , EMAIL_ADDRESS
      , RETRO_PRICE_COMM_UPDATES_FLAG
      , RETRO_PRICE_APPLY_UPDATES_FLAG
      , UPDATE_SOURCING_RULES_FLAG
      , AUTO_SOURCING_FLAG
      , LOCK_OWNER_ROLE
      , LOCK_OWNER_USER_ID
      , SUPPLIER_AUTH_ENABLED_FLAG
      , CAT_ADMIN_AUTH_ENABLED_FLAG
      , STYLE_ID
      , TAX_ATTRIBUTE_UPDATE_CODE
      , PAY_WHEN_PAID
      , UDA_TEMPLATE_ID
      , UDA_TEMPLATE_DATE
      , USER_DOCUMENT_STATUS
      , AME_APPROVAL_ID
      , DRAFT_ID
      , CLM_EFFECTIVE_DATE
      , CLM_VENDOR_OFFER_NUMBER
      , CLM_AWARD_ADMINISTRATOR
      , CLM_NO_SIGNED_COPIES_TO_RETURN
      , CLM_MIN_GUARANTEE_AWARD_AMT
      , CLM_MIN_GUAR_AWARD_AMT_PERCENT
      , CLM_MIN_ORDER_AMOUNT
      , CLM_MAX_ORDER_AMOUNT
      , CLM_AMT_SYNCED_TO_AGREEMENT
      , CLM_AMOUNT_RELEASED
      , CLM_EXTERNAL_IDV
      , CLM_SUPPLIER_NAME
      , CLM_SUPPLIER_SITE_NAME
      , CLM_DOCUMENT_NUMBER
      , CLM_SOURCE_DOCUMENT_ID
      , CLM_ISSUING_OFFICE
      , CLM_COTR_OFFICE
      , CLM_COTR_CONTACT
      , CLM_PRIORITY_CODE
      , CLM_MOD_ISSUING_OFFICE
      , CLM_STANDARD_FORM
      , CLM_DOCUMENT_FORMAT
      , AME_TRANSACTION_TYPE
      , CLM_AWARD_TYPE
      , CLM_CONTRACT_OFFICER
      , CLM_CLOSEOUT_STATUS
      , UMBRELLA_PROGRAM_ID
      , FON_REF_ID
      , CLM_DEFAULT_DIST_FLAG
      , CLM_EDAGEN_DATE
      , CLM_CONTRACT_FINANCE_CODE
      , CLM_PAYMENT_INSTR_CODE
      , CLM_SPECIAL_CONTRACT_TYPE
      , IGT_DOCUMENT_NUMBER
      , IGT_GTNC_NUMBER
      , IGT_STATUS
      , AGREEMENT_TYPE
      , ASSISTED_ACQUISITION_IND
      , ADVANCE_PAYMENT_IND
      , ENFORCE_TOTAL_AMT_IND
      , TERMINATION_DAYS
      , TOTAL_REMAINING_AMT
      , IGT_BUSINESS_TXN_ID
      , TERM_DESCRIPTION
      , _FIVETRAN_ID
      , _FIVETRAN_DELETED
      , _FIVETRAN_SYNCED
      , PSA_LOAD_DTS
      , PSA_RECORD_SOURCE
      , PSA_DELETE_IND
      , LOAD_DTS
      , REC_SRC
      , BKCC
      , HASHDIFF
    FROM SRC_ttemtk
)
---- RENAME LAYER ----

, RENAME_ttemtk as (
    SELECT
        PO_HEADER_HK
      , PO_HEADER_ID
      , AGENT_ID
      , TYPE_LOOKUP_CODE
      , LAST_UPDATE_DATE
      , LAST_UPDATED_BY
      , SEGMENT1
      , SUMMARY_FLAG
      , ENABLED_FLAG
      , SEGMENT2
      , SEGMENT3
      , SEGMENT4
      , SEGMENT5
      , START_DATE_ACTIVE
      , END_DATE_ACTIVE
      , LAST_UPDATE_LOGIN
      , CREATION_DATE
      , CREATED_BY
      , VENDOR_ID
      , VENDOR_SITE_ID
      , VENDOR_CONTACT_ID
      , SHIP_TO_LOCATION_ID
      , BILL_TO_LOCATION_ID
      , TERMS_ID
      , SHIP_VIA_LOOKUP_CODE
      , FOB_LOOKUP_CODE
      , FREIGHT_TERMS_LOOKUP_CODE
      , STATUS_LOOKUP_CODE
      , CURRENCY_CODE
      , RATE_TYPE
      , RATE_DATE
      , RATE
      , FROM_HEADER_ID
      , FROM_TYPE_LOOKUP_CODE
      , START_DATE
      , END_DATE
      , BLANKET_TOTAL_AMOUNT
      , AUTHORIZATION_STATUS
      , REVISION_NUM
      , REVISED_DATE
      , APPROVED_FLAG
      , APPROVED_DATE
      , AMOUNT_LIMIT
      , MIN_RELEASE_AMOUNT
      , NOTE_TO_AUTHORIZER
      , NOTE_TO_VENDOR
      , NOTE_TO_RECEIVER
      , PRINT_COUNT
      , PRINTED_DATE
      , VENDOR_ORDER_NUM
      , CONFIRMING_ORDER_FLAG
      , COMMENTS
      , REPLY_DATE
      , REPLY_METHOD_LOOKUP_CODE
      , RFQ_CLOSE_DATE
      , QUOTE_TYPE_LOOKUP_CODE
      , QUOTATION_CLASS_CODE
      , QUOTE_WARNING_DELAY_UNIT
      , QUOTE_WARNING_DELAY
      , QUOTE_VENDOR_QUOTE_NUMBER
      , ACCEPTANCE_REQUIRED_FLAG
      , ACCEPTANCE_DUE_DATE
      , CLOSED_DATE
      , USER_HOLD_FLAG
      , APPROVAL_REQUIRED_FLAG
      , CANCEL_FLAG
      , FIRM_STATUS_LOOKUP_CODE
      , FIRM_DATE
      , FROZEN_FLAG
      , SUPPLY_AGREEMENT_FLAG
      , EDI_PROCESSED_FLAG
      , EDI_PROCESSED_STATUS
      , ATTRIBUTE_CATEGORY
      , ATTRIBUTE1
      , ATTRIBUTE2
      , ATTRIBUTE3
      , ATTRIBUTE4
      , ATTRIBUTE5
      , ATTRIBUTE6
      , ATTRIBUTE7
      , ATTRIBUTE8
      , ATTRIBUTE9
      , ATTRIBUTE10
      , ATTRIBUTE11
      , ATTRIBUTE12
      , ATTRIBUTE13
      , ATTRIBUTE14
      , ATTRIBUTE15
      , CLOSED_CODE
      , USSGL_TRANSACTION_CODE
      , GOVERNMENT_CONTEXT
      , REQUEST_ID
      , PROGRAM_APPLICATION_ID
      , PROGRAM_ID
      , PROGRAM_UPDATE_DATE
      , ORG_ID
      , GLOBAL_ATTRIBUTE_CATEGORY
      , GLOBAL_ATTRIBUTE1
      , GLOBAL_ATTRIBUTE2
      , GLOBAL_ATTRIBUTE3
      , GLOBAL_ATTRIBUTE4
      , GLOBAL_ATTRIBUTE5
      , GLOBAL_ATTRIBUTE6
      , GLOBAL_ATTRIBUTE7
      , GLOBAL_ATTRIBUTE8
      , GLOBAL_ATTRIBUTE9
      , GLOBAL_ATTRIBUTE10
      , GLOBAL_ATTRIBUTE11
      , GLOBAL_ATTRIBUTE12
      , GLOBAL_ATTRIBUTE13
      , GLOBAL_ATTRIBUTE14
      , GLOBAL_ATTRIBUTE15
      , GLOBAL_ATTRIBUTE16
      , GLOBAL_ATTRIBUTE17
      , GLOBAL_ATTRIBUTE18
      , GLOBAL_ATTRIBUTE19
      , GLOBAL_ATTRIBUTE20
      , INTERFACE_SOURCE_CODE
      , REFERENCE_NUM
      , WF_ITEM_TYPE
      , WF_ITEM_KEY
      , MRC_RATE_TYPE
      , MRC_RATE_DATE
      , MRC_RATE
      , PCARD_ID
      , PRICE_UPDATE_TOLERANCE
      , PAY_ON_CODE
      , XML_FLAG
      , XML_SEND_DATE
      , XML_CHANGE_SEND_DATE
      , GLOBAL_AGREEMENT_FLAG
      , CONSIGNED_CONSUMPTION_FLAG
      , CBC_ACCOUNTING_DATE
      , CONSUME_REQ_DEMAND_FLAG
      , CHANGE_REQUESTED_BY
      , SHIPPING_CONTROL
      , CONTERMS_EXIST_FLAG
      , CONTERMS_ARTICLES_UPD_DATE
      , CONTERMS_DELIV_UPD_DATE
      , ENCUMBRANCE_REQUIRED_FLAG
      , PENDING_SIGNATURE_FLAG
      , CHANGE_SUMMARY
      , DOCUMENT_CREATION_METHOD
      , SUBMIT_DATE
      , ENABLE_ALL_SITES
      , CREATED_LANGUAGE
      , CPA_REFERENCE
      , LAST_UPDATED_PROGRAM
      , OTM_STATUS_CODE
      , OTM_RECOVERY_FLAG
      , COMM_REV_NUM
      , SUPPLIER_NOTIF_METHOD
      , FAX
      , EMAIL_ADDRESS
      , RETRO_PRICE_COMM_UPDATES_FLAG
      , RETRO_PRICE_APPLY_UPDATES_FLAG
      , UPDATE_SOURCING_RULES_FLAG
      , AUTO_SOURCING_FLAG
      , LOCK_OWNER_ROLE
      , LOCK_OWNER_USER_ID
      , SUPPLIER_AUTH_ENABLED_FLAG
      , CAT_ADMIN_AUTH_ENABLED_FLAG
      , STYLE_ID
      , TAX_ATTRIBUTE_UPDATE_CODE
      , PAY_WHEN_PAID
      , UDA_TEMPLATE_ID
      , UDA_TEMPLATE_DATE
      , USER_DOCUMENT_STATUS
      , AME_APPROVAL_ID
      , DRAFT_ID
      , CLM_EFFECTIVE_DATE
      , CLM_VENDOR_OFFER_NUMBER
      , CLM_AWARD_ADMINISTRATOR
      , CLM_NO_SIGNED_COPIES_TO_RETURN
      , CLM_MIN_GUARANTEE_AWARD_AMT
      , CLM_MIN_GUAR_AWARD_AMT_PERCENT
      , CLM_MIN_ORDER_AMOUNT
      , CLM_MAX_ORDER_AMOUNT
      , CLM_AMT_SYNCED_TO_AGREEMENT
      , CLM_AMOUNT_RELEASED
      , CLM_EXTERNAL_IDV
      , CLM_SUPPLIER_NAME
      , CLM_SUPPLIER_SITE_NAME
      , CLM_DOCUMENT_NUMBER
      , CLM_SOURCE_DOCUMENT_ID
      , CLM_ISSUING_OFFICE
      , CLM_COTR_OFFICE
      , CLM_COTR_CONTACT
      , CLM_PRIORITY_CODE
      , CLM_MOD_ISSUING_OFFICE
      , CLM_STANDARD_FORM
      , CLM_DOCUMENT_FORMAT
      , AME_TRANSACTION_TYPE
      , CLM_AWARD_TYPE
      , CLM_CONTRACT_OFFICER
      , CLM_CLOSEOUT_STATUS
      , UMBRELLA_PROGRAM_ID
      , FON_REF_ID
      , CLM_DEFAULT_DIST_FLAG
      , CLM_EDAGEN_DATE
      , CLM_CONTRACT_FINANCE_CODE
      , CLM_PAYMENT_INSTR_CODE
      , CLM_SPECIAL_CONTRACT_TYPE
      , IGT_DOCUMENT_NUMBER
      , IGT_GTNC_NUMBER
      , IGT_STATUS
      , AGREEMENT_TYPE
      , ASSISTED_ACQUISITION_IND
      , ADVANCE_PAYMENT_IND
      , ENFORCE_TOTAL_AMT_IND
      , TERMINATION_DAYS
      , TOTAL_REMAINING_AMT
      , IGT_BUSINESS_TXN_ID
      , TERM_DESCRIPTION
      , _FIVETRAN_ID
      , _FIVETRAN_DELETED
      , _FIVETRAN_SYNCED
      , PSA_LOAD_DTS
      , PSA_RECORD_SOURCE
      , PSA_DELETE_IND
      , LOAD_DTS
      , REC_SRC
      , BKCC
      , HASHDIFF
    FROM LOGIC_ttemtk
)
---- FILTER LAYER ----

, FILTER_ttemtk as (
    SELECT *
    FROM RENAME_ttemtk
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM FILTER_ttemtk
)

---- FINAL LAYER ----
SELECT
          PO_HEADER_HK
        , PO_HEADER_ID
        , AGENT_ID
        , TYPE_LOOKUP_CODE
        , LAST_UPDATE_DATE
        , LAST_UPDATED_BY
        , SEGMENT1
        , SUMMARY_FLAG
        , ENABLED_FLAG
        , SEGMENT2
        , SEGMENT3
        , SEGMENT4
        , SEGMENT5
        , START_DATE_ACTIVE
        , END_DATE_ACTIVE
        , LAST_UPDATE_LOGIN
        , CREATION_DATE
        , CREATED_BY
        , VENDOR_ID
        , VENDOR_SITE_ID
        , VENDOR_CONTACT_ID
        , SHIP_TO_LOCATION_ID
        , BILL_TO_LOCATION_ID
        , TERMS_ID
        , SHIP_VIA_LOOKUP_CODE
        , FOB_LOOKUP_CODE
        , FREIGHT_TERMS_LOOKUP_CODE
        , STATUS_LOOKUP_CODE
        , CURRENCY_CODE
        , RATE_TYPE
        , RATE_DATE
        , RATE
        , FROM_HEADER_ID
        , FROM_TYPE_LOOKUP_CODE
        , START_DATE
        , END_DATE
        , BLANKET_TOTAL_AMOUNT
        , AUTHORIZATION_STATUS
        , REVISION_NUM
        , REVISED_DATE
        , APPROVED_FLAG
        , APPROVED_DATE
        , AMOUNT_LIMIT
        , MIN_RELEASE_AMOUNT
        , NOTE_TO_AUTHORIZER
        , NOTE_TO_VENDOR
        , NOTE_TO_RECEIVER
        , PRINT_COUNT
        , PRINTED_DATE
        , VENDOR_ORDER_NUM
        , CONFIRMING_ORDER_FLAG
        , COMMENTS
        , REPLY_DATE
        , REPLY_METHOD_LOOKUP_CODE
        , RFQ_CLOSE_DATE
        , QUOTE_TYPE_LOOKUP_CODE
        , QUOTATION_CLASS_CODE
        , QUOTE_WARNING_DELAY_UNIT
        , QUOTE_WARNING_DELAY
        , QUOTE_VENDOR_QUOTE_NUMBER
        , ACCEPTANCE_REQUIRED_FLAG
        , ACCEPTANCE_DUE_DATE
        , CLOSED_DATE
        , USER_HOLD_FLAG
        , APPROVAL_REQUIRED_FLAG
        , CANCEL_FLAG
        , FIRM_STATUS_LOOKUP_CODE
        , FIRM_DATE
        , FROZEN_FLAG
        , SUPPLY_AGREEMENT_FLAG
        , EDI_PROCESSED_FLAG
        , EDI_PROCESSED_STATUS
        , ATTRIBUTE_CATEGORY
        , ATTRIBUTE1
        , ATTRIBUTE2
        , ATTRIBUTE3
        , ATTRIBUTE4
        , ATTRIBUTE5
        , ATTRIBUTE6
        , ATTRIBUTE7
        , ATTRIBUTE8
        , ATTRIBUTE9
        , ATTRIBUTE10
        , ATTRIBUTE11
        , ATTRIBUTE12
        , ATTRIBUTE13
        , ATTRIBUTE14
        , ATTRIBUTE15
        , CLOSED_CODE
        , USSGL_TRANSACTION_CODE
        , GOVERNMENT_CONTEXT
        , REQUEST_ID
        , PROGRAM_APPLICATION_ID
        , PROGRAM_ID
        , PROGRAM_UPDATE_DATE
        , ORG_ID
        , GLOBAL_ATTRIBUTE_CATEGORY
        , GLOBAL_ATTRIBUTE1
        , GLOBAL_ATTRIBUTE2
        , GLOBAL_ATTRIBUTE3
        , GLOBAL_ATTRIBUTE4
        , GLOBAL_ATTRIBUTE5
        , GLOBAL_ATTRIBUTE6
        , GLOBAL_ATTRIBUTE7
        , GLOBAL_ATTRIBUTE8
        , GLOBAL_ATTRIBUTE9
        , GLOBAL_ATTRIBUTE10
        , GLOBAL_ATTRIBUTE11
        , GLOBAL_ATTRIBUTE12
        , GLOBAL_ATTRIBUTE13
        , GLOBAL_ATTRIBUTE14
        , GLOBAL_ATTRIBUTE15
        , GLOBAL_ATTRIBUTE16
        , GLOBAL_ATTRIBUTE17
        , GLOBAL_ATTRIBUTE18
        , GLOBAL_ATTRIBUTE19
        , GLOBAL_ATTRIBUTE20
        , INTERFACE_SOURCE_CODE
        , REFERENCE_NUM
        , WF_ITEM_TYPE
        , WF_ITEM_KEY
        , MRC_RATE_TYPE
        , MRC_RATE_DATE
        , MRC_RATE
        , PCARD_ID
        , PRICE_UPDATE_TOLERANCE
        , PAY_ON_CODE
        , XML_FLAG
        , XML_SEND_DATE
        , XML_CHANGE_SEND_DATE
        , GLOBAL_AGREEMENT_FLAG
        , CONSIGNED_CONSUMPTION_FLAG
        , CBC_ACCOUNTING_DATE
        , CONSUME_REQ_DEMAND_FLAG
        , CHANGE_REQUESTED_BY
        , SHIPPING_CONTROL
        , CONTERMS_EXIST_FLAG
        , CONTERMS_ARTICLES_UPD_DATE
        , CONTERMS_DELIV_UPD_DATE
        , ENCUMBRANCE_REQUIRED_FLAG
        , PENDING_SIGNATURE_FLAG
        , CHANGE_SUMMARY
        , DOCUMENT_CREATION_METHOD
        , SUBMIT_DATE
        , ENABLE_ALL_SITES
        , CREATED_LANGUAGE
        , CPA_REFERENCE
        , LAST_UPDATED_PROGRAM
        , OTM_STATUS_CODE
        , OTM_RECOVERY_FLAG
        , COMM_REV_NUM
        , SUPPLIER_NOTIF_METHOD
        , FAX
        , EMAIL_ADDRESS
        , RETRO_PRICE_COMM_UPDATES_FLAG
        , RETRO_PRICE_APPLY_UPDATES_FLAG
        , UPDATE_SOURCING_RULES_FLAG
        , AUTO_SOURCING_FLAG
        , LOCK_OWNER_ROLE
        , LOCK_OWNER_USER_ID
        , SUPPLIER_AUTH_ENABLED_FLAG
        , CAT_ADMIN_AUTH_ENABLED_FLAG
        , STYLE_ID
        , TAX_ATTRIBUTE_UPDATE_CODE
        , PAY_WHEN_PAID
        , UDA_TEMPLATE_ID
        , UDA_TEMPLATE_DATE
        , USER_DOCUMENT_STATUS
        , AME_APPROVAL_ID
        , DRAFT_ID
        , CLM_EFFECTIVE_DATE
        , CLM_VENDOR_OFFER_NUMBER
        , CLM_AWARD_ADMINISTRATOR
        , CLM_NO_SIGNED_COPIES_TO_RETURN
        , CLM_MIN_GUARANTEE_AWARD_AMT
        , CLM_MIN_GUAR_AWARD_AMT_PERCENT
        , CLM_MIN_ORDER_AMOUNT
        , CLM_MAX_ORDER_AMOUNT
        , CLM_AMT_SYNCED_TO_AGREEMENT
        , CLM_AMOUNT_RELEASED
        , CLM_EXTERNAL_IDV
        , CLM_SUPPLIER_NAME
        , CLM_SUPPLIER_SITE_NAME
        , CLM_DOCUMENT_NUMBER
        , CLM_SOURCE_DOCUMENT_ID
        , CLM_ISSUING_OFFICE
        , CLM_COTR_OFFICE
        , CLM_COTR_CONTACT
        , CLM_PRIORITY_CODE
        , CLM_MOD_ISSUING_OFFICE
        , CLM_STANDARD_FORM
        , CLM_DOCUMENT_FORMAT
        , AME_TRANSACTION_TYPE
        , CLM_AWARD_TYPE
        , CLM_CONTRACT_OFFICER
        , CLM_CLOSEOUT_STATUS
        , UMBRELLA_PROGRAM_ID
        , FON_REF_ID
        , CLM_DEFAULT_DIST_FLAG
        , CLM_EDAGEN_DATE
        , CLM_CONTRACT_FINANCE_CODE
        , CLM_PAYMENT_INSTR_CODE
        , CLM_SPECIAL_CONTRACT_TYPE
        , IGT_DOCUMENT_NUMBER
        , IGT_GTNC_NUMBER
        , IGT_STATUS
        , AGREEMENT_TYPE
        , ASSISTED_ACQUISITION_IND
        , ADVANCE_PAYMENT_IND
        , ENFORCE_TOTAL_AMT_IND
        , TERMINATION_DAYS
        , TOTAL_REMAINING_AMT
        , IGT_BUSINESS_TXN_ID
        , TERM_DESCRIPTION
        , _FIVETRAN_ID
        , _FIVETRAN_DELETED
        , _FIVETRAN_SYNCED
        , PSA_LOAD_DTS
        , PSA_RECORD_SOURCE
        , PSA_DELETE_IND
        , LOAD_DTS
        , REC_SRC
        , BKCC
        , HASHDIFF
FROM JOIN_RESULT
{% if is_incremental() %}
WHERE NOT EXISTS (
    SELECT 1 
    FROM {{ this }} existing
    WHERE existing.PO_HEADER_HK = JOIN_RESULT.PO_HEADER_HK 
    AND existing.HASHDIFF = JOIN_RESULT.HASHDIFF
)
{% endif %}

{% if not is_incremental() %}

/* The following qualifier is implemented to prevent multiple loads of touched records during the initial build, such as multiple rows per HK and hashdiff. */
qualify 1 = row_number() over (partition by PO_HEADER_HK, HASHDIFF order by PSA_LOAD_DTS)

union all
SELECT 
MD5_BINARY(GR.VALUE) AS PO_HEADER_HK,
GR.VALUE::text AS PO_HEADER_ID,
NULL AS AGENT_ID,
NULL AS TYPE_LOOKUP_CODE,
NULL AS LAST_UPDATE_DATE,
NULL AS LAST_UPDATED_BY,
NULL AS SEGMENT1,
NULL AS SUMMARY_FLAG,
NULL AS ENABLED_FLAG,
NULL AS SEGMENT2,
NULL AS SEGMENT3,
NULL AS SEGMENT4,
NULL AS SEGMENT5,
NULL AS START_DATE_ACTIVE,
NULL AS END_DATE_ACTIVE,
NULL AS LAST_UPDATE_LOGIN,
NULL AS CREATION_DATE,
NULL AS CREATED_BY,
NULL AS VENDOR_ID,
NULL AS VENDOR_SITE_ID,
NULL AS VENDOR_CONTACT_ID,
NULL AS SHIP_TO_LOCATION_ID,
NULL AS BILL_TO_LOCATION_ID,
NULL AS TERMS_ID,
NULL AS SHIP_VIA_LOOKUP_CODE,
NULL AS FOB_LOOKUP_CODE,
NULL AS FREIGHT_TERMS_LOOKUP_CODE,
NULL AS STATUS_LOOKUP_CODE,
NULL AS CURRENCY_CODE,
NULL AS RATE_TYPE,
NULL AS RATE_DATE,
NULL AS RATE,
NULL AS FROM_HEADER_ID,
NULL AS FROM_TYPE_LOOKUP_CODE,
NULL AS START_DATE,
NULL AS END_DATE,
NULL AS BLANKET_TOTAL_AMOUNT,
NULL AS AUTHORIZATION_STATUS,
NULL AS REVISION_NUM,
NULL AS REVISED_DATE,
NULL AS APPROVED_FLAG,
NULL AS APPROVED_DATE,
NULL AS AMOUNT_LIMIT,
NULL AS MIN_RELEASE_AMOUNT,
NULL AS NOTE_TO_AUTHORIZER,
NULL AS NOTE_TO_VENDOR,
NULL AS NOTE_TO_RECEIVER,
NULL AS PRINT_COUNT,
NULL AS PRINTED_DATE,
NULL AS VENDOR_ORDER_NUM,
NULL AS CONFIRMING_ORDER_FLAG,
NULL AS COMMENTS,
NULL AS REPLY_DATE,
NULL AS REPLY_METHOD_LOOKUP_CODE,
NULL AS RFQ_CLOSE_DATE,
NULL AS QUOTE_TYPE_LOOKUP_CODE,
NULL AS QUOTATION_CLASS_CODE,
NULL AS QUOTE_WARNING_DELAY_UNIT,
NULL AS QUOTE_WARNING_DELAY,
NULL AS QUOTE_VENDOR_QUOTE_NUMBER,
NULL AS ACCEPTANCE_REQUIRED_FLAG,
NULL AS ACCEPTANCE_DUE_DATE,
NULL AS CLOSED_DATE,
NULL AS USER_HOLD_FLAG,
NULL AS APPROVAL_REQUIRED_FLAG,
NULL AS CANCEL_FLAG,
NULL AS FIRM_STATUS_LOOKUP_CODE,
NULL AS FIRM_DATE,
NULL AS FROZEN_FLAG,
NULL AS SUPPLY_AGREEMENT_FLAG,
NULL AS EDI_PROCESSED_FLAG,
NULL AS EDI_PROCESSED_STATUS,
NULL AS ATTRIBUTE_CATEGORY,
NULL AS ATTRIBUTE1,
NULL AS ATTRIBUTE2,
NULL AS ATTRIBUTE3,
NULL AS ATTRIBUTE4,
NULL AS ATTRIBUTE5,
NULL AS ATTRIBUTE6,
NULL AS ATTRIBUTE7,
NULL AS ATTRIBUTE8,
NULL AS ATTRIBUTE9,
NULL AS ATTRIBUTE10,
NULL AS ATTRIBUTE11,
NULL AS ATTRIBUTE12,
NULL AS ATTRIBUTE13,
NULL AS ATTRIBUTE14,
NULL AS ATTRIBUTE15,
NULL AS CLOSED_CODE,
NULL AS USSGL_TRANSACTION_CODE,
NULL AS GOVERNMENT_CONTEXT,
NULL AS REQUEST_ID,
NULL AS PROGRAM_APPLICATION_ID,
NULL AS PROGRAM_ID,
NULL AS PROGRAM_UPDATE_DATE,
NULL AS ORG_ID,
NULL AS GLOBAL_ATTRIBUTE_CATEGORY,
NULL AS GLOBAL_ATTRIBUTE1,
NULL AS GLOBAL_ATTRIBUTE2,
NULL AS GLOBAL_ATTRIBUTE3,
NULL AS GLOBAL_ATTRIBUTE4,
NULL AS GLOBAL_ATTRIBUTE5,
NULL AS GLOBAL_ATTRIBUTE6,
NULL AS GLOBAL_ATTRIBUTE7,
NULL AS GLOBAL_ATTRIBUTE8,
NULL AS GLOBAL_ATTRIBUTE9,
NULL AS GLOBAL_ATTRIBUTE10,
NULL AS GLOBAL_ATTRIBUTE11,
NULL AS GLOBAL_ATTRIBUTE12,
NULL AS GLOBAL_ATTRIBUTE13,
NULL AS GLOBAL_ATTRIBUTE14,
NULL AS GLOBAL_ATTRIBUTE15,
NULL AS GLOBAL_ATTRIBUTE16,
NULL AS GLOBAL_ATTRIBUTE17,
NULL AS GLOBAL_ATTRIBUTE18,
NULL AS GLOBAL_ATTRIBUTE19,
NULL AS GLOBAL_ATTRIBUTE20,
NULL AS INTERFACE_SOURCE_CODE,
NULL AS REFERENCE_NUM,
NULL AS WF_ITEM_TYPE,
NULL AS WF_ITEM_KEY,
NULL AS MRC_RATE_TYPE,
NULL AS MRC_RATE_DATE,
NULL AS MRC_RATE,
NULL AS PCARD_ID,
NULL AS PRICE_UPDATE_TOLERANCE,
NULL AS PAY_ON_CODE,
NULL AS XML_FLAG,
NULL AS XML_SEND_DATE,
NULL AS XML_CHANGE_SEND_DATE,
NULL AS GLOBAL_AGREEMENT_FLAG,
NULL AS CONSIGNED_CONSUMPTION_FLAG,
NULL AS CBC_ACCOUNTING_DATE,
NULL AS CONSUME_REQ_DEMAND_FLAG,
NULL AS CHANGE_REQUESTED_BY,
NULL AS SHIPPING_CONTROL,
NULL AS CONTERMS_EXIST_FLAG,
NULL AS CONTERMS_ARTICLES_UPD_DATE,
NULL AS CONTERMS_DELIV_UPD_DATE,
NULL AS ENCUMBRANCE_REQUIRED_FLAG,
NULL AS PENDING_SIGNATURE_FLAG,
NULL AS CHANGE_SUMMARY,
NULL AS DOCUMENT_CREATION_METHOD,
NULL AS SUBMIT_DATE,
NULL AS ENABLE_ALL_SITES,
NULL AS CREATED_LANGUAGE,
NULL AS CPA_REFERENCE,
NULL AS LAST_UPDATED_PROGRAM,
NULL AS OTM_STATUS_CODE,
NULL AS OTM_RECOVERY_FLAG,
NULL AS COMM_REV_NUM,
NULL AS SUPPLIER_NOTIF_METHOD,
NULL AS FAX,
NULL AS EMAIL_ADDRESS,
NULL AS RETRO_PRICE_COMM_UPDATES_FLAG,
NULL AS RETRO_PRICE_APPLY_UPDATES_FLAG,
NULL AS UPDATE_SOURCING_RULES_FLAG,
NULL AS AUTO_SOURCING_FLAG,
NULL AS LOCK_OWNER_ROLE,
NULL AS LOCK_OWNER_USER_ID,
NULL AS SUPPLIER_AUTH_ENABLED_FLAG,
NULL AS CAT_ADMIN_AUTH_ENABLED_FLAG,
NULL AS STYLE_ID,
NULL AS TAX_ATTRIBUTE_UPDATE_CODE,
NULL AS PAY_WHEN_PAID,
NULL AS UDA_TEMPLATE_ID,
NULL AS UDA_TEMPLATE_DATE,
NULL AS USER_DOCUMENT_STATUS,
NULL AS AME_APPROVAL_ID,
NULL AS DRAFT_ID,
NULL AS CLM_EFFECTIVE_DATE,
NULL AS CLM_VENDOR_OFFER_NUMBER,
NULL AS CLM_AWARD_ADMINISTRATOR,
NULL AS CLM_NO_SIGNED_COPIES_TO_RETURN,
NULL AS CLM_MIN_GUARANTEE_AWARD_AMT,
NULL AS CLM_MIN_GUAR_AWARD_AMT_PERCENT,
NULL AS CLM_MIN_ORDER_AMOUNT,
NULL AS CLM_MAX_ORDER_AMOUNT,
NULL AS CLM_AMT_SYNCED_TO_AGREEMENT,
NULL AS CLM_AMOUNT_RELEASED,
NULL AS CLM_EXTERNAL_IDV,
NULL AS CLM_SUPPLIER_NAME,
NULL AS CLM_SUPPLIER_SITE_NAME,
NULL AS CLM_DOCUMENT_NUMBER,
NULL AS CLM_SOURCE_DOCUMENT_ID,
NULL AS CLM_ISSUING_OFFICE,
NULL AS CLM_COTR_OFFICE,
NULL AS CLM_COTR_CONTACT,
NULL AS CLM_PRIORITY_CODE,
NULL AS CLM_MOD_ISSUING_OFFICE,
NULL AS CLM_STANDARD_FORM,
NULL AS CLM_DOCUMENT_FORMAT,
NULL AS AME_TRANSACTION_TYPE,
NULL AS CLM_AWARD_TYPE,
NULL AS CLM_CONTRACT_OFFICER,
NULL AS CLM_CLOSEOUT_STATUS,
NULL AS UMBRELLA_PROGRAM_ID,
NULL AS FON_REF_ID,
NULL AS CLM_DEFAULT_DIST_FLAG,
NULL AS CLM_EDAGEN_DATE,
NULL AS CLM_CONTRACT_FINANCE_CODE,
NULL AS CLM_PAYMENT_INSTR_CODE,
NULL AS CLM_SPECIAL_CONTRACT_TYPE,
NULL AS IGT_DOCUMENT_NUMBER,
NULL AS IGT_GTNC_NUMBER,
NULL AS IGT_STATUS,
NULL AS AGREEMENT_TYPE,
NULL AS ASSISTED_ACQUISITION_IND,
NULL AS ADVANCE_PAYMENT_IND,
NULL AS ENFORCE_TOTAL_AMT_IND,
NULL AS TERMINATION_DAYS,
NULL AS TOTAL_REMAINING_AMT,
NULL AS IGT_BUSINESS_TXN_ID,
NULL AS TERM_DESCRIPTION,
NULL AS _FIVETRAN_ID,
NULL AS _FIVETRAN_DELETED,
NULL AS _FIVETRAN_SYNCED,
'1900-01-01'::TIMESTAMP AS PSA_LOAD_DTS,
NULL AS PSA_RECORD_SOURCE,
'N' AS PSA_DELETE_IND,
CONVERT_TIMEZONE('UTC','1900-01-01'::TIMESTAMP) AS LOAD_DTS,
'USAZET.SNOWFLAKE.FBIN.DERIVED' AS REC_SRC,
DECODE(GR.VALUE, 0, 'GHOST RECORD-SYSTEM', -1, 'GHOST RECORD-nullkey-required', -2, 'GHOST RECORD-nullkey-optional') AS BKCC,
''::BINARY AS HASHDIFF
FROM
TABLE(strtok_split_to_table('0|-1|-2', '|')) AS GR
{% endif %}
