---- SRC LAYER ----
WITH
SRC_SMFCFG         as ( SELECT * FROM {{ ref('v_psa_stg_sales__moen_cfg_ferguson_new') }} as SRC 
                         {% if is_incremental() %}
                         WHERE SRC.LOAD_DTS > (SELECT DATEADD('HOUR', '-1', MAX(LOAD_DTS)) FROM {{this}})
                         {% endif %}  )

/*
SRC_SMFCFG         as ( SELECT * FROM STAGING.v_psa_stg_sales__moen_cfg_ferguson_new )
*/
---- LOGIC LAYER ----

, LOGIC_SMFCFG as (
    SELECT
        STORE_HK
      , _LINE
      , _FILE
      , _MODIFIED
      , _FIVETRAN_SYNCED
      , YEAR_MONTH
      , DATE
      , TRANSACTION_TYPE
      , SELL_LOCATION_ID
      , LEGACY_SELL_LOCATION_ID
      , SELL_LOCATION_NAME
      , SHIP_LOCATION_ID
      , LEGACY_SHIP_LOCATION_ID
      , SHIP_LOCATION_NAME
      , SHIP_LOCATION_CITY
      , SHIP_LOCATION_STATE
      , SHIP_LOCATION_ZIP
      , ORDER_CHANNEL
      , FULFILLMENT_CHANNEL
      , SOURCE_SYSTEM
      , CUSTOMER_TYPE
      , CUSTOMER_GROUP
      , FEI_PRODUCT_NO
      , FEI_PRODUCT_CODE
      , FEI_PRODUCT_DESCRIPTION
      , VENDOR_CODE
      , SHIPPED_QTY
      , PRODUCT_DEST_CITY
      , PRODUCT_DEST_STATE
      , PRODUCT_DEST_ZIP
      , PRODUCT_DEST_ZIP_CODE
      , UOM
      , BUILD_COM_ORDER
      , INVOICE
      , PSA_LOAD_DTS
      , PSA_RECORD_SOURCE
      , PSA_DELETE_IND
      , LOAD_DTS
      , REC_SRC
      , HASHDIFF
    FROM SRC_SMFCFG
)
---- RENAME LAYER ----

, RENAME_SMFCFG as (
    SELECT
        STORE_HK
      , _LINE
      , _FILE
      , _MODIFIED
      , _FIVETRAN_SYNCED
      , YEAR_MONTH
      , DATE
      , TRANSACTION_TYPE
      , SELL_LOCATION_ID
      , LEGACY_SELL_LOCATION_ID
      , SELL_LOCATION_NAME
      , SHIP_LOCATION_ID
      , LEGACY_SHIP_LOCATION_ID
      , SHIP_LOCATION_NAME
      , SHIP_LOCATION_CITY
      , SHIP_LOCATION_STATE
      , SHIP_LOCATION_ZIP
      , ORDER_CHANNEL
      , FULFILLMENT_CHANNEL
      , SOURCE_SYSTEM
      , CUSTOMER_TYPE
      , CUSTOMER_GROUP
      , FEI_PRODUCT_NO
      , FEI_PRODUCT_CODE
      , FEI_PRODUCT_DESCRIPTION
      , VENDOR_CODE
      , SHIPPED_QTY
      , PRODUCT_DEST_CITY
      , PRODUCT_DEST_STATE
      , PRODUCT_DEST_ZIP
      , PRODUCT_DEST_ZIP_CODE
      , UOM
      , BUILD_COM_ORDER
      , INVOICE
      , PSA_LOAD_DTS
      , PSA_RECORD_SOURCE
      , PSA_DELETE_IND
      , LOAD_DTS
      , REC_SRC
      , HASHDIFF
    FROM LOGIC_SMFCFG
)
---- FILTER LAYER ----

, FILTER_SMFCFG as (
    SELECT *
    FROM RENAME_SMFCFG
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM FILTER_SMFCFG
)

---- FINAL LAYER ----
SELECT
          STORE_HK
        , _LINE
        , _FILE
        , _MODIFIED
        , _FIVETRAN_SYNCED
        , YEAR_MONTH
        , DATE
        , TRANSACTION_TYPE
        , SELL_LOCATION_ID
        , LEGACY_SELL_LOCATION_ID
        , SELL_LOCATION_NAME
        , SHIP_LOCATION_ID
        , LEGACY_SHIP_LOCATION_ID
        , SHIP_LOCATION_NAME
        , SHIP_LOCATION_CITY
        , SHIP_LOCATION_STATE
        , SHIP_LOCATION_ZIP
        , ORDER_CHANNEL
        , FULFILLMENT_CHANNEL
        , SOURCE_SYSTEM
        , CUSTOMER_TYPE
        , CUSTOMER_GROUP
        , FEI_PRODUCT_NO
        , FEI_PRODUCT_CODE
        , FEI_PRODUCT_DESCRIPTION
        , VENDOR_CODE
        , SHIPPED_QTY
        , PRODUCT_DEST_CITY
        , PRODUCT_DEST_STATE
        , PRODUCT_DEST_ZIP
        , PRODUCT_DEST_ZIP_CODE
        , UOM
        , BUILD_COM_ORDER
        , INVOICE
        , PSA_LOAD_DTS
        , PSA_RECORD_SOURCE
        , PSA_DELETE_IND
        , LOAD_DTS
        , REC_SRC
        , HASHDIFF
FROM JOIN_RESULT
{% if is_incremental() %}
WHERE NOT EXISTS (
    SELECT 1 
    FROM {{ this }} existing
    WHERE existing.STORE_HK = JOIN_RESULT.STORE_HK
	AND existing._LINE = JOIN_RESULT._LINE
	AND existing._FILE = JOIN_RESULT._FILE
	AND existing.HASHDIFF = JOIN_RESULT.HASHDIFF	
)
{% endif %}
{% if not is_incremental() %}

/* The following qualifier is implemented to prevent multiple loads of touched records during the initial build, such as multiple rows per HK and hashdiff. */
qualify 1 = row_number() over (partition by STORE_HK, _LINE, _FILE, HASHDIFF order by PSA_LOAD_DTS)

union all
SELECT 
MD5_BINARY(GR.VALUE) AS STORE_HK,
GR.VALUE::text AS _LINE,
GR.VALUE::text AS _FILE,
NULL AS _MODIFIED,
NULL AS _FIVETRAN_SYNCED,
NULL AS YEAR_MONTH,
NULL AS DATE,
NULL AS TRANSACTION_TYPE,
NULL AS SELL_LOCATION_ID,
NULL AS LEGACY_SELL_LOCATION_ID,
NULL AS SELL_LOCATION_NAME,
NULL AS SHIP_LOCATION_ID,
NULL AS LEGACY_SHIP_LOCATION_ID,
NULL AS SHIP_LOCATION_NAME,
NULL AS SHIP_LOCATION_CITY,
NULL AS SHIP_LOCATION_STATE,
NULL AS SHIP_LOCATION_ZIP,
NULL AS ORDER_CHANNEL,
NULL AS FULFILLMENT_CHANNEL,
NULL AS SOURCE_SYSTEM,
NULL AS CUSTOMER_TYPE,
NULL AS CUSTOMER_GROUP,
NULL AS FEI_PRODUCT_NO,
NULL AS FEI_PRODUCT_CODE,
NULL AS FEI_PRODUCT_DESCRIPTION,
NULL AS VENDOR_CODE,
NULL AS SHIPPED_QTY,
NULL AS PRODUCT_DEST_CITY,
NULL AS PRODUCT_DEST_STATE,
NULL AS PRODUCT_DEST_ZIP,
NULL AS PRODUCT_DEST_ZIP_CODE,
NULL AS UOM,
NULL AS BUILD_COM_ORDER,
NULL AS INVOICE,
'1900-01-01'::TIMESTAMP AS PSA_LOAD_DTS,
NULL AS PSA_RECORD_SOURCE,
'N' AS PSA_DELETE_IND,
CONVERT_TIMEZONE('UTC','1900-01-01'::TIMESTAMP) AS LOAD_DTS,
'USAZET.SNOWFLAKE.FBIN.DERIVED' AS REC_SRC,
''::BINARY AS HASHDIFF
FROM
TABLE(strtok_split_to_table('0|-1|-2', '|')) AS GR
{% endif %}
