---- SRC LAYER ----
WITH
SRC_a              as ( SELECT * FROM {{ ref('v_psa_stg_po_item_open_orders__ml_ascp') }} as SRC 
                         {% if is_incremental() %}
                              where src.load_dts > (select dateadd('HOUR',-1,max(load_dts)) from {{ this }})
                            {% endif %}   )

/*
SRC_a              as ( SELECT * FROM staging.v_psa_stg_po_item_open_orders__ml_ascp )
*/
---- LOGIC LAYER ----

, LOGIC_a as (
    SELECT
        PO_ITEM_HK
      , PO_LINE_ID
      , TRANSACTION_ID
      , CREATION_DATE
      , PLAN_ID
      , ORGANIZATION_ID
      , SR_INSTANCE_ID
      , INVENTORY_ITEM_ID
      , SCHEDULE_DESIGNATOR_ID
      , REVISION
      , UNIT_NUMBER
      , NEW_SCHEDULE_DATE
      , OLD_SCHEDULE_DATE
      , NEW_WIP_START_DATE
      , OLD_WIP_START_DATE
      , FIRST_UNIT_COMPLETION_DATE
      , LAST_UNIT_COMPLETION_DATE
      , FIRST_UNIT_START_DATE
      , LAST_UNIT_START_DATE
      , DISPOSITION_ID
      , DISPOSITION_STATUS_TYPE
      , ORDER_TYPE
      , SUPPLIER_ID
      , SUPPLIER_SITE_ID
      , NEW_ORDER_QUANTITY
      , OLD_ORDER_QUANTITY
      , NEW_ORDER_PLACEMENT_DATE
      , OLD_ORDER_PLACEMENT_DATE
      , RESCHEDULE_DAYS
      , RESCHEDULE_FLAG
      , SCHEDULE_COMPRESS_DAYS
      , NEW_PROCESSING_DAYS
      , PURCH_LINE_NUM
      , QUANTITY_IN_PROCESS
      , IMPLEMENTED_QUANTITY
      , FIRM_PLANNED_TYPE
      , FIRM_QUANTITY
      , FIRM_DATE
      , IMPLEMENT_DEMAND_CLASS
      , IMPLEMENT_DATE
      , IMPLEMENT_QUANTITY
      , IMPLEMENT_FIRM
      , IMPLEMENT_WIP_CLASS_CODE
      , IMPLEMENT_JOB_NAME
      , IMPLEMENT_DOCK_DATE
      , IMPLEMENT_STATUS_CODE
      , IMPLEMENT_EMPLOYEE_ID
      , IMPLEMENT_UOM_CODE
      , IMPLEMENT_LOCATION_ID
      , IMPLEMENT_SOURCE_ORG_ID
      , IMPLEMENT_SR_INSTANCE_ID
      , IMPLEMENT_SUPPLIER_ID
      , IMPLEMENT_SUPPLIER_SITE_ID
      , IMPLEMENT_AS
      , RELEASE_STATUS
      , LOAD_TYPE
      , PROCESS_SEQ_ID
      , SCO_SUPPLY_FLAG
      , ALTERNATE_BOM_DESIGNATOR
      , ALTERNATE_ROUTING_DESIGNATOR
      , OPERATION_SEQ_NUM
      , BY_PRODUCT_USING_ASSY_ID
      , SOURCE_ORGANIZATION_ID
      , SOURCE_SR_INSTANCE_ID
      , SOURCE_SUPPLIER_SITE_ID
      , SOURCE_SUPPLIER_ID
      , SHIP_METHOD
      , WEIGHT_CAPACITY_USED
      , VOLUME_CAPACITY_USED
      , NEW_SHIP_DATE
      , NEW_DOCK_DATE
      , OLD_DOCK_DATE
      , LINE_ID
      , PROJECT_ID
      , TASK_ID
      , PLANNING_GROUP
      , IMPLEMENT_PROJECT_ID
      , IMPLEMENT_TASK_ID
      , IMPLEMENT_SCHEDULE_GROUP_ID
      , IMPLEMENT_BUILD_SEQUENCE
      , IMPLEMENT_ALTERNATE_BOM
      , IMPLEMENT_ALTERNATE_ROUTING
      , IMPLEMENT_UNIT_NUMBER
      , IMPLEMENT_LINE_ID
      , RELEASE_ERRORS
      , NUMBER1
      , SOURCE_ITEM_ID
      , ORDER_NUMBER
      , SCHEDULE_GROUP_ID
      , BUILD_SEQUENCE
      , WIP_ENTITY_NAME
      , IMPLEMENT_PROCESSING_DAYS
      , DELIVERY_PRICE
      , LATE_SUPPLY_DATE
      , LATE_SUPPLY_QTY
      , LOT_NUMBER
      , SUBINVENTORY_CODE
      , QTY_SCRAPPED
      , EXPECTED_SCRAP_QTY
      , QTY_COMPLETED
      , DAILY_RATE
      , SCHEDULE_GROUP_NAME
      , UPDATED
      , SUBST_ITEM_FLAG
      , STATUS
      , APPLIED
      , EXPIRATION_QUANTITY
      , EXPIRATION_DATE
      , NON_NETTABLE_QTY
      , IMPLEMENT_WIP_START_DATE
      , REFRESH_NUMBER
      , LAST_UPDATE_DATE
      , LAST_UPDATED_BY
      , CREATED_BY
      , LAST_UPDATE_LOGIN
      , REQUEST_ID
      , PROGRAM_APPLICATION_ID
      , PROGRAM_ID
      , PROGRAM_UPDATE_DATE
      , IMPLEMENT_DAILY_RATE
      , NEED_BY_DATE
      , SOURCE_SUPPLY_ID
      , SR_MTL_SUPPLY_ID
      , WIP_STATUS_CODE
      , DEMAND_CLASS
      , FROM_ORGANIZATION_ID
      , WIP_SUPPLY_TYPE
      , LOAD_FACTOR_RATE
      , ROUTING_SEQUENCE_ID
      , BILL_SEQUENCE_ID
      , COPRODUCTS_SUPPLY
      , CFM_ROUTING_FLAG
      , CUSTOMER_ID
      , SHIP_TO_SITE_ID
      , OLD_NEED_BY_DATE
      , OLD_DAILY_RATE
      , OLD_FIRST_UNIT_START_DATE
      , OLD_LAST_UNIT_COMPLETION_DATE
      , OLD_NEW_SCHEDULE_DATE
      , OLD_QTY_COMPLETED
      , OLD_NEW_ORDER_QUANTITY
      , OLD_FIRM_QUANTITY
      , OLD_FIRM_DATE
      , PLANNING_PARTNER_SITE_ID
      , PLANNING_TP_TYPE
      , OWNING_PARTNER_SITE_ID
      , OWNING_TP_TYPE
      , VMI_FLAG
      , EARLIEST_START_DATE
      , EARLIEST_COMPLETION_DATE
      , MIN_START_DATE
      , SCHEDULED_DEMAND_ID
      , EXPLOSION_DATE
      , SCO_SUPPLY_DATE
      , RECORD_SOURCE
      , SUPPLY_IS_SHARED
      , ULPSD
      , ULPCD
      , UEPSD
      , UEPCD
      , EACD
      , ORIGINAL_NEED_BY_DATE
      , ORIGINAL_QUANTITY
      , ACCEPTANCE_REQUIRED_FLAG
      , PROMISED_DATE
      , WIP_START_QUANTITY
      , END_ORDER_NUMBER
      , END_ORDER_LINE_NUMBER
      , ORDER_LINE_NUMBER
      , QUANTITY_PER_ASSEMBLY
      , QUANTITY_ISSUED
      , UNBUCKETED_DEMAND_DATE
      , SHIPMENT_ID
      , JOB_OP_SEQ_NUM
      , JUMP_OP_SEQ_NUM
      , SHIP_CALENDAR
      , RECEIVING_CALENDAR
      , INTRANSIT_CALENDAR
      , INTRANSIT_LEAD_TIME
      , OLD_SHIP_DATE
      , IMPLEMENT_SHIP_DATE
      , ORIG_SHIP_METHOD
      , ORIG_INTRANSIT_LEAD_TIME
      , PARENT_ID
      , DAYS_LATE
      , SCHEDULE_PRIORITY
      , PO_LINE_LOCATION_ID
      , PO_DISTRIBUTION_ID
      , WSM_FAULTY_NETWORK
      , IMPLEMENT_DEST_ORG_ID
      , IMPLEMENT_DEST_INST_ID
      , REQUESTED_START_DATE
      , REQUESTED_COMPLETION_DATE
      , ASSET_SERIAL_NUMBER
      , ASSET_ITEM_ID
      , TOP_TRANSACTION_ID
      , UNBUCKETED_NEW_SCHED_DATE
      , IMPLEMENT_SHIP_METHOD
      , ACTUAL_START_DATE
      , FIRM_SHIP_DATE
      , SCHEDULE_ORIGINATION_TYPE
      , UNBUCKETED_START_DATE
      , SR_CUSTOMER_ACCT_ID
      , ITEM_TYPE_ID
      , CUSTOMER_PRODUCT_ID
      , RO_STATUS_CODE
      , SR_REPAIR_GROUP_ID
      , SR_REPAIR_TYPE_ID
      , ITEM_TYPE_VALUE
      , ZONE_ID
      , RO_CREATION_DATE
      , REPAIR_LEAD_TIME
      , FIRM_START_DATE
      , REQ_LINE_ID
      , INTRANSIT_OWNING_ORG_ID
      , RELEASABLE
      , BATCH_ID
      , OTM_ARRIVAL_DATE
      , PS_SUPPLY_FLAG
      , CTB_FLAG
      , CTB_COMP_AVAIL_PERCENT
      , RTB_ORDER_QTY_PERCENT
      , CTB_EXPECTED_DATE
      , POTENTIAL_RTB_PERCENT
      , CTB_PRIORITY
      , DESCRIPTION
      , MAINTENANCE_OBJECT_SOURCE
      , PRODUCTION_SCHEDULE_ID
      , VISIT_ID
      , PRODUCES_TO_STOCK
      , PRODUCT_CLASSIFICATION
      , MAINTENANCE_REQT
      , ACTIVITY_TYPE
      , ACTIVITY_NAME
      , CLASS_CODE
      , SHUTDOWN_TYPE
      , TO_BE_EXPLODED
      , OBJECT_TYPE
      , MAINTENANCE_TYPE_CODE
      , ACTIVITY_ITEM_ID
      , ORIG_FIRM_DATE
      , ORIG_FIRM_QUANTITY
      , USE_WO_SUBSTITUTE
      , ASSET_NUMBER
      , MAINTENANCE_OBJECT_ID
      , MAINTENANCE_OBJECT_TYPE
      , OPERATING_FLEET
      , MAINTENANCE_REQUIREMENT
      , COLL_ORDER_TYPE
      , CTB_EXPECTED_DATE_BUY_COMPS
      , SUBSTITUTE_COMPONENTS_USED
      , RESERVED_QTY
      , PO_OR_REQ_HEADER_ID
      , ACTUAL_LEAD_TIME
      , MIN_LEAD_TIME
      , PIP_ITEM_ID
      , SUPP_CAPACITY_OVERLOAD
      , VOLUME_CAPACITY_OVERLOAD
      , WEIGHT_CAPACITY_OVERLOAD
      , PM_SNAPSHOT_DATE
      , PSA_LOAD_DTS
      , PSA_RECORD_SOURCE
      , PSA_DELETE_IND
      , LOAD_DTS
      , REC_SRC
      , BKCC
      , HASHDIFF
    FROM SRC_a
)
---- RENAME LAYER ----

, RENAME_a as (
    SELECT
        PO_ITEM_HK
      , PO_LINE_ID
      , TRANSACTION_ID
      , CREATION_DATE
      , PLAN_ID
      , ORGANIZATION_ID
      , SR_INSTANCE_ID
      , INVENTORY_ITEM_ID
      , SCHEDULE_DESIGNATOR_ID
      , REVISION
      , UNIT_NUMBER
      , NEW_SCHEDULE_DATE
      , OLD_SCHEDULE_DATE
      , NEW_WIP_START_DATE
      , OLD_WIP_START_DATE
      , FIRST_UNIT_COMPLETION_DATE
      , LAST_UNIT_COMPLETION_DATE
      , FIRST_UNIT_START_DATE
      , LAST_UNIT_START_DATE
      , DISPOSITION_ID
      , DISPOSITION_STATUS_TYPE
      , ORDER_TYPE
      , SUPPLIER_ID
      , SUPPLIER_SITE_ID
      , NEW_ORDER_QUANTITY
      , OLD_ORDER_QUANTITY
      , NEW_ORDER_PLACEMENT_DATE
      , OLD_ORDER_PLACEMENT_DATE
      , RESCHEDULE_DAYS
      , RESCHEDULE_FLAG
      , SCHEDULE_COMPRESS_DAYS
      , NEW_PROCESSING_DAYS
      , PURCH_LINE_NUM
      , QUANTITY_IN_PROCESS
      , IMPLEMENTED_QUANTITY
      , FIRM_PLANNED_TYPE
      , FIRM_QUANTITY
      , FIRM_DATE
      , IMPLEMENT_DEMAND_CLASS
      , IMPLEMENT_DATE
      , IMPLEMENT_QUANTITY
      , IMPLEMENT_FIRM
      , IMPLEMENT_WIP_CLASS_CODE
      , IMPLEMENT_JOB_NAME
      , IMPLEMENT_DOCK_DATE
      , IMPLEMENT_STATUS_CODE
      , IMPLEMENT_EMPLOYEE_ID
      , IMPLEMENT_UOM_CODE
      , IMPLEMENT_LOCATION_ID
      , IMPLEMENT_SOURCE_ORG_ID
      , IMPLEMENT_SR_INSTANCE_ID
      , IMPLEMENT_SUPPLIER_ID
      , IMPLEMENT_SUPPLIER_SITE_ID
      , IMPLEMENT_AS
      , RELEASE_STATUS
      , LOAD_TYPE
      , PROCESS_SEQ_ID
      , SCO_SUPPLY_FLAG
      , ALTERNATE_BOM_DESIGNATOR
      , ALTERNATE_ROUTING_DESIGNATOR
      , OPERATION_SEQ_NUM
      , BY_PRODUCT_USING_ASSY_ID
      , SOURCE_ORGANIZATION_ID
      , SOURCE_SR_INSTANCE_ID
      , SOURCE_SUPPLIER_SITE_ID
      , SOURCE_SUPPLIER_ID
      , SHIP_METHOD
      , WEIGHT_CAPACITY_USED
      , VOLUME_CAPACITY_USED
      , NEW_SHIP_DATE
      , NEW_DOCK_DATE
      , OLD_DOCK_DATE
      , LINE_ID
      , PROJECT_ID
      , TASK_ID
      , PLANNING_GROUP
      , IMPLEMENT_PROJECT_ID
      , IMPLEMENT_TASK_ID
      , IMPLEMENT_SCHEDULE_GROUP_ID
      , IMPLEMENT_BUILD_SEQUENCE
      , IMPLEMENT_ALTERNATE_BOM
      , IMPLEMENT_ALTERNATE_ROUTING
      , IMPLEMENT_UNIT_NUMBER
      , IMPLEMENT_LINE_ID
      , RELEASE_ERRORS
      , NUMBER1
      , SOURCE_ITEM_ID
      , ORDER_NUMBER
      , SCHEDULE_GROUP_ID
      , BUILD_SEQUENCE
      , WIP_ENTITY_NAME
      , IMPLEMENT_PROCESSING_DAYS
      , DELIVERY_PRICE
      , LATE_SUPPLY_DATE
      , LATE_SUPPLY_QTY
      , LOT_NUMBER
      , SUBINVENTORY_CODE
      , QTY_SCRAPPED
      , EXPECTED_SCRAP_QTY
      , QTY_COMPLETED
      , DAILY_RATE
      , SCHEDULE_GROUP_NAME
      , UPDATED
      , SUBST_ITEM_FLAG
      , STATUS
      , APPLIED
      , EXPIRATION_QUANTITY
      , EXPIRATION_DATE
      , NON_NETTABLE_QTY
      , IMPLEMENT_WIP_START_DATE
      , REFRESH_NUMBER
      , LAST_UPDATE_DATE
      , LAST_UPDATED_BY
      , CREATED_BY
      , LAST_UPDATE_LOGIN
      , REQUEST_ID
      , PROGRAM_APPLICATION_ID
      , PROGRAM_ID
      , PROGRAM_UPDATE_DATE
      , IMPLEMENT_DAILY_RATE
      , NEED_BY_DATE
      , SOURCE_SUPPLY_ID
      , SR_MTL_SUPPLY_ID
      , WIP_STATUS_CODE
      , DEMAND_CLASS
      , FROM_ORGANIZATION_ID
      , WIP_SUPPLY_TYPE
      , LOAD_FACTOR_RATE
      , ROUTING_SEQUENCE_ID
      , BILL_SEQUENCE_ID
      , COPRODUCTS_SUPPLY
      , CFM_ROUTING_FLAG
      , CUSTOMER_ID
      , SHIP_TO_SITE_ID
      , OLD_NEED_BY_DATE
      , OLD_DAILY_RATE
      , OLD_FIRST_UNIT_START_DATE
      , OLD_LAST_UNIT_COMPLETION_DATE
      , OLD_NEW_SCHEDULE_DATE
      , OLD_QTY_COMPLETED
      , OLD_NEW_ORDER_QUANTITY
      , OLD_FIRM_QUANTITY
      , OLD_FIRM_DATE
      , PLANNING_PARTNER_SITE_ID
      , PLANNING_TP_TYPE
      , OWNING_PARTNER_SITE_ID
      , OWNING_TP_TYPE
      , VMI_FLAG
      , EARLIEST_START_DATE
      , EARLIEST_COMPLETION_DATE
      , MIN_START_DATE
      , SCHEDULED_DEMAND_ID
      , EXPLOSION_DATE
      , SCO_SUPPLY_DATE
      , RECORD_SOURCE
      , SUPPLY_IS_SHARED
      , ULPSD
      , ULPCD
      , UEPSD
      , UEPCD
      , EACD
      , ORIGINAL_NEED_BY_DATE
      , ORIGINAL_QUANTITY
      , ACCEPTANCE_REQUIRED_FLAG
      , PROMISED_DATE
      , WIP_START_QUANTITY
      , END_ORDER_NUMBER
      , END_ORDER_LINE_NUMBER
      , ORDER_LINE_NUMBER
      , QUANTITY_PER_ASSEMBLY
      , QUANTITY_ISSUED
      , UNBUCKETED_DEMAND_DATE
      , SHIPMENT_ID
      , JOB_OP_SEQ_NUM
      , JUMP_OP_SEQ_NUM
      , SHIP_CALENDAR
      , RECEIVING_CALENDAR
      , INTRANSIT_CALENDAR
      , INTRANSIT_LEAD_TIME
      , OLD_SHIP_DATE
      , IMPLEMENT_SHIP_DATE
      , ORIG_SHIP_METHOD
      , ORIG_INTRANSIT_LEAD_TIME
      , PARENT_ID
      , DAYS_LATE
      , SCHEDULE_PRIORITY
      , PO_LINE_LOCATION_ID
      , PO_DISTRIBUTION_ID
      , WSM_FAULTY_NETWORK
      , IMPLEMENT_DEST_ORG_ID
      , IMPLEMENT_DEST_INST_ID
      , REQUESTED_START_DATE
      , REQUESTED_COMPLETION_DATE
      , ASSET_SERIAL_NUMBER
      , ASSET_ITEM_ID
      , TOP_TRANSACTION_ID
      , UNBUCKETED_NEW_SCHED_DATE
      , IMPLEMENT_SHIP_METHOD
      , ACTUAL_START_DATE
      , FIRM_SHIP_DATE
      , SCHEDULE_ORIGINATION_TYPE
      , UNBUCKETED_START_DATE
      , SR_CUSTOMER_ACCT_ID
      , ITEM_TYPE_ID
      , CUSTOMER_PRODUCT_ID
      , RO_STATUS_CODE
      , SR_REPAIR_GROUP_ID
      , SR_REPAIR_TYPE_ID
      , ITEM_TYPE_VALUE
      , ZONE_ID
      , RO_CREATION_DATE
      , REPAIR_LEAD_TIME
      , FIRM_START_DATE
      , REQ_LINE_ID
      , INTRANSIT_OWNING_ORG_ID
      , RELEASABLE
      , BATCH_ID
      , OTM_ARRIVAL_DATE
      , PS_SUPPLY_FLAG
      , CTB_FLAG
      , CTB_COMP_AVAIL_PERCENT
      , RTB_ORDER_QTY_PERCENT
      , CTB_EXPECTED_DATE
      , POTENTIAL_RTB_PERCENT
      , CTB_PRIORITY
      , DESCRIPTION
      , MAINTENANCE_OBJECT_SOURCE
      , PRODUCTION_SCHEDULE_ID
      , VISIT_ID
      , PRODUCES_TO_STOCK
      , PRODUCT_CLASSIFICATION
      , MAINTENANCE_REQT
      , ACTIVITY_TYPE
      , ACTIVITY_NAME
      , CLASS_CODE
      , SHUTDOWN_TYPE
      , TO_BE_EXPLODED
      , OBJECT_TYPE
      , MAINTENANCE_TYPE_CODE
      , ACTIVITY_ITEM_ID
      , ORIG_FIRM_DATE
      , ORIG_FIRM_QUANTITY
      , USE_WO_SUBSTITUTE
      , ASSET_NUMBER
      , MAINTENANCE_OBJECT_ID
      , MAINTENANCE_OBJECT_TYPE
      , OPERATING_FLEET
      , MAINTENANCE_REQUIREMENT
      , COLL_ORDER_TYPE
      , CTB_EXPECTED_DATE_BUY_COMPS
      , SUBSTITUTE_COMPONENTS_USED
      , RESERVED_QTY
      , PO_OR_REQ_HEADER_ID
      , ACTUAL_LEAD_TIME
      , MIN_LEAD_TIME
      , PIP_ITEM_ID
      , SUPP_CAPACITY_OVERLOAD
      , VOLUME_CAPACITY_OVERLOAD
      , WEIGHT_CAPACITY_OVERLOAD
      , PM_SNAPSHOT_DATE
      , PSA_LOAD_DTS
      , PSA_RECORD_SOURCE
      , PSA_DELETE_IND
      , LOAD_DTS
      , REC_SRC
      , BKCC
      , HASHDIFF
    FROM LOGIC_a
)
---- FILTER LAYER ----

, FILTER_a as (
    SELECT *
    FROM RENAME_a
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM FILTER_a
)

---- FINAL LAYER ----
SELECT
          PO_ITEM_HK
        , PO_LINE_ID
        , TRANSACTION_ID
        , CREATION_DATE
        , PLAN_ID
        , ORGANIZATION_ID
        , SR_INSTANCE_ID
        , INVENTORY_ITEM_ID
        , SCHEDULE_DESIGNATOR_ID
        , REVISION
        , UNIT_NUMBER
        , NEW_SCHEDULE_DATE
        , OLD_SCHEDULE_DATE
        , NEW_WIP_START_DATE
        , OLD_WIP_START_DATE
        , FIRST_UNIT_COMPLETION_DATE
        , LAST_UNIT_COMPLETION_DATE
        , FIRST_UNIT_START_DATE
        , LAST_UNIT_START_DATE
        , DISPOSITION_ID
        , DISPOSITION_STATUS_TYPE
        , ORDER_TYPE
        , SUPPLIER_ID
        , SUPPLIER_SITE_ID
        , NEW_ORDER_QUANTITY
        , OLD_ORDER_QUANTITY
        , NEW_ORDER_PLACEMENT_DATE
        , OLD_ORDER_PLACEMENT_DATE
        , RESCHEDULE_DAYS
        , RESCHEDULE_FLAG
        , SCHEDULE_COMPRESS_DAYS
        , NEW_PROCESSING_DAYS
        , PURCH_LINE_NUM
        , QUANTITY_IN_PROCESS
        , IMPLEMENTED_QUANTITY
        , FIRM_PLANNED_TYPE
        , FIRM_QUANTITY
        , FIRM_DATE
        , IMPLEMENT_DEMAND_CLASS
        , IMPLEMENT_DATE
        , IMPLEMENT_QUANTITY
        , IMPLEMENT_FIRM
        , IMPLEMENT_WIP_CLASS_CODE
        , IMPLEMENT_JOB_NAME
        , IMPLEMENT_DOCK_DATE
        , IMPLEMENT_STATUS_CODE
        , IMPLEMENT_EMPLOYEE_ID
        , IMPLEMENT_UOM_CODE
        , IMPLEMENT_LOCATION_ID
        , IMPLEMENT_SOURCE_ORG_ID
        , IMPLEMENT_SR_INSTANCE_ID
        , IMPLEMENT_SUPPLIER_ID
        , IMPLEMENT_SUPPLIER_SITE_ID
        , IMPLEMENT_AS
        , RELEASE_STATUS
        , LOAD_TYPE
        , PROCESS_SEQ_ID
        , SCO_SUPPLY_FLAG
        , ALTERNATE_BOM_DESIGNATOR
        , ALTERNATE_ROUTING_DESIGNATOR
        , OPERATION_SEQ_NUM
        , BY_PRODUCT_USING_ASSY_ID
        , SOURCE_ORGANIZATION_ID
        , SOURCE_SR_INSTANCE_ID
        , SOURCE_SUPPLIER_SITE_ID
        , SOURCE_SUPPLIER_ID
        , SHIP_METHOD
        , WEIGHT_CAPACITY_USED
        , VOLUME_CAPACITY_USED
        , NEW_SHIP_DATE
        , NEW_DOCK_DATE
        , OLD_DOCK_DATE
        , LINE_ID
        , PROJECT_ID
        , TASK_ID
        , PLANNING_GROUP
        , IMPLEMENT_PROJECT_ID
        , IMPLEMENT_TASK_ID
        , IMPLEMENT_SCHEDULE_GROUP_ID
        , IMPLEMENT_BUILD_SEQUENCE
        , IMPLEMENT_ALTERNATE_BOM
        , IMPLEMENT_ALTERNATE_ROUTING
        , IMPLEMENT_UNIT_NUMBER
        , IMPLEMENT_LINE_ID
        , RELEASE_ERRORS
        , NUMBER1
        , SOURCE_ITEM_ID
        , ORDER_NUMBER
        , SCHEDULE_GROUP_ID
        , BUILD_SEQUENCE
        , WIP_ENTITY_NAME
        , IMPLEMENT_PROCESSING_DAYS
        , DELIVERY_PRICE
        , LATE_SUPPLY_DATE
        , LATE_SUPPLY_QTY
        , LOT_NUMBER
        , SUBINVENTORY_CODE
        , QTY_SCRAPPED
        , EXPECTED_SCRAP_QTY
        , QTY_COMPLETED
        , DAILY_RATE
        , SCHEDULE_GROUP_NAME
        , UPDATED
        , SUBST_ITEM_FLAG
        , STATUS
        , APPLIED
        , EXPIRATION_QUANTITY
        , EXPIRATION_DATE
        , NON_NETTABLE_QTY
        , IMPLEMENT_WIP_START_DATE
        , REFRESH_NUMBER
        , LAST_UPDATE_DATE
        , LAST_UPDATED_BY
        , CREATED_BY
        , LAST_UPDATE_LOGIN
        , REQUEST_ID
        , PROGRAM_APPLICATION_ID
        , PROGRAM_ID
        , PROGRAM_UPDATE_DATE
        , IMPLEMENT_DAILY_RATE
        , NEED_BY_DATE
        , SOURCE_SUPPLY_ID
        , SR_MTL_SUPPLY_ID
        , WIP_STATUS_CODE
        , DEMAND_CLASS
        , FROM_ORGANIZATION_ID
        , WIP_SUPPLY_TYPE
        , LOAD_FACTOR_RATE
        , ROUTING_SEQUENCE_ID
        , BILL_SEQUENCE_ID
        , COPRODUCTS_SUPPLY
        , CFM_ROUTING_FLAG
        , CUSTOMER_ID
        , SHIP_TO_SITE_ID
        , OLD_NEED_BY_DATE
        , OLD_DAILY_RATE
        , OLD_FIRST_UNIT_START_DATE
        , OLD_LAST_UNIT_COMPLETION_DATE
        , OLD_NEW_SCHEDULE_DATE
        , OLD_QTY_COMPLETED
        , OLD_NEW_ORDER_QUANTITY
        , OLD_FIRM_QUANTITY
        , OLD_FIRM_DATE
        , PLANNING_PARTNER_SITE_ID
        , PLANNING_TP_TYPE
        , OWNING_PARTNER_SITE_ID
        , OWNING_TP_TYPE
        , VMI_FLAG
        , EARLIEST_START_DATE
        , EARLIEST_COMPLETION_DATE
        , MIN_START_DATE
        , SCHEDULED_DEMAND_ID
        , EXPLOSION_DATE
        , SCO_SUPPLY_DATE
        , RECORD_SOURCE
        , SUPPLY_IS_SHARED
        , ULPSD
        , ULPCD
        , UEPSD
        , UEPCD
        , EACD
        , ORIGINAL_NEED_BY_DATE
        , ORIGINAL_QUANTITY
        , ACCEPTANCE_REQUIRED_FLAG
        , PROMISED_DATE
        , WIP_START_QUANTITY
        , END_ORDER_NUMBER
        , END_ORDER_LINE_NUMBER
        , ORDER_LINE_NUMBER
        , QUANTITY_PER_ASSEMBLY
        , QUANTITY_ISSUED
        , UNBUCKETED_DEMAND_DATE
        , SHIPMENT_ID
        , JOB_OP_SEQ_NUM
        , JUMP_OP_SEQ_NUM
        , SHIP_CALENDAR
        , RECEIVING_CALENDAR
        , INTRANSIT_CALENDAR
        , INTRANSIT_LEAD_TIME
        , OLD_SHIP_DATE
        , IMPLEMENT_SHIP_DATE
        , ORIG_SHIP_METHOD
        , ORIG_INTRANSIT_LEAD_TIME
        , PARENT_ID
        , DAYS_LATE
        , SCHEDULE_PRIORITY
        , PO_LINE_LOCATION_ID
        , PO_DISTRIBUTION_ID
        , WSM_FAULTY_NETWORK
        , IMPLEMENT_DEST_ORG_ID
        , IMPLEMENT_DEST_INST_ID
        , REQUESTED_START_DATE
        , REQUESTED_COMPLETION_DATE
        , ASSET_SERIAL_NUMBER
        , ASSET_ITEM_ID
        , TOP_TRANSACTION_ID
        , UNBUCKETED_NEW_SCHED_DATE
        , IMPLEMENT_SHIP_METHOD
        , ACTUAL_START_DATE
        , FIRM_SHIP_DATE
        , SCHEDULE_ORIGINATION_TYPE
        , UNBUCKETED_START_DATE
        , SR_CUSTOMER_ACCT_ID
        , ITEM_TYPE_ID
        , CUSTOMER_PRODUCT_ID
        , RO_STATUS_CODE
        , SR_REPAIR_GROUP_ID
        , SR_REPAIR_TYPE_ID
        , ITEM_TYPE_VALUE
        , ZONE_ID
        , RO_CREATION_DATE
        , REPAIR_LEAD_TIME
        , FIRM_START_DATE
        , REQ_LINE_ID
        , INTRANSIT_OWNING_ORG_ID
        , RELEASABLE
        , BATCH_ID
        , OTM_ARRIVAL_DATE
        , PS_SUPPLY_FLAG
        , CTB_FLAG
        , CTB_COMP_AVAIL_PERCENT
        , RTB_ORDER_QTY_PERCENT
        , CTB_EXPECTED_DATE
        , POTENTIAL_RTB_PERCENT
        , CTB_PRIORITY
        , DESCRIPTION
        , MAINTENANCE_OBJECT_SOURCE
        , PRODUCTION_SCHEDULE_ID
        , VISIT_ID
        , PRODUCES_TO_STOCK
        , PRODUCT_CLASSIFICATION
        , MAINTENANCE_REQT
        , ACTIVITY_TYPE
        , ACTIVITY_NAME
        , CLASS_CODE
        , SHUTDOWN_TYPE
        , TO_BE_EXPLODED
        , OBJECT_TYPE
        , MAINTENANCE_TYPE_CODE
        , ACTIVITY_ITEM_ID
        , ORIG_FIRM_DATE
        , ORIG_FIRM_QUANTITY
        , USE_WO_SUBSTITUTE
        , ASSET_NUMBER
        , MAINTENANCE_OBJECT_ID
        , MAINTENANCE_OBJECT_TYPE
        , OPERATING_FLEET
        , MAINTENANCE_REQUIREMENT
        , COLL_ORDER_TYPE
        , CTB_EXPECTED_DATE_BUY_COMPS
        , SUBSTITUTE_COMPONENTS_USED
        , RESERVED_QTY
        , PO_OR_REQ_HEADER_ID
        , ACTUAL_LEAD_TIME
        , MIN_LEAD_TIME
        , PIP_ITEM_ID
        , SUPP_CAPACITY_OVERLOAD
        , VOLUME_CAPACITY_OVERLOAD
        , WEIGHT_CAPACITY_OVERLOAD
        , PM_SNAPSHOT_DATE
        , PSA_LOAD_DTS
        , PSA_RECORD_SOURCE
        , PSA_DELETE_IND
        , LOAD_DTS
        , REC_SRC
        , BKCC
        , HASHDIFF
FROM JOIN_RESULT
{% if is_incremental() %}
WHERE NOT EXISTS (
    SELECT 1 
    FROM {{ this }} existing
    WHERE existing.PO_ITEM_HK = JOIN_RESULT.PO_ITEM_HK 
    AND existing.TRANSACTION_ID = JOIN_RESULT.TRANSACTION_ID
    AND existing.CREATION_DATE = JOIN_RESULT.CREATION_DATE
    AND existing.HASHDIFF = JOIN_RESULT.HASHDIFF
)
{% endif %}
{% if not is_incremental() %}

/* The following qualifier is implemented to prevent multiple loads of touched records during the initial build, such as multiple rows per HK and hashdiff. */
qualify 1 = row_number() over (partition by PO_ITEM_HK, TRANSACTION_ID, CREATION_DATE, HASHDIFF order by PSA_LOAD_DTS)

union all
SELECT 
MD5_BINARY(GR.VALUE) AS PO_ITEM_HK,
GR.VALUE::number AS PO_LINE_ID,
GR.VALUE::number AS TRANSACTION_ID,
'1900-01-01'::date AS CREATION_DATE,
GR.VALUE::number AS PLAN_ID,
NULL AS ORGANIZATION_ID,
NULL AS SR_INSTANCE_ID,
NULL AS INVENTORY_ITEM_ID,
NULL AS SCHEDULE_DESIGNATOR_ID,
NULL AS REVISION,
NULL AS UNIT_NUMBER,
NULL AS NEW_SCHEDULE_DATE,
NULL AS OLD_SCHEDULE_DATE,
NULL AS NEW_WIP_START_DATE,
NULL AS OLD_WIP_START_DATE,
NULL AS FIRST_UNIT_COMPLETION_DATE,
NULL AS LAST_UNIT_COMPLETION_DATE,
NULL AS FIRST_UNIT_START_DATE,
NULL AS LAST_UNIT_START_DATE,
NULL AS DISPOSITION_ID,
NULL AS DISPOSITION_STATUS_TYPE,
NULL AS ORDER_TYPE,
NULL AS SUPPLIER_ID,
NULL AS SUPPLIER_SITE_ID,
NULL AS NEW_ORDER_QUANTITY,
NULL AS OLD_ORDER_QUANTITY,
NULL AS NEW_ORDER_PLACEMENT_DATE,
NULL AS OLD_ORDER_PLACEMENT_DATE,
NULL AS RESCHEDULE_DAYS,
NULL AS RESCHEDULE_FLAG,
NULL AS SCHEDULE_COMPRESS_DAYS,
NULL AS NEW_PROCESSING_DAYS,
NULL AS PURCH_LINE_NUM,
NULL AS QUANTITY_IN_PROCESS,
NULL AS IMPLEMENTED_QUANTITY,
NULL AS FIRM_PLANNED_TYPE,
NULL AS FIRM_QUANTITY,
NULL AS FIRM_DATE,
NULL AS IMPLEMENT_DEMAND_CLASS,
NULL AS IMPLEMENT_DATE,
NULL AS IMPLEMENT_QUANTITY,
NULL AS IMPLEMENT_FIRM,
NULL AS IMPLEMENT_WIP_CLASS_CODE,
NULL AS IMPLEMENT_JOB_NAME,
NULL AS IMPLEMENT_DOCK_DATE,
NULL AS IMPLEMENT_STATUS_CODE,
NULL AS IMPLEMENT_EMPLOYEE_ID,
NULL AS IMPLEMENT_UOM_CODE,
NULL AS IMPLEMENT_LOCATION_ID,
NULL AS IMPLEMENT_SOURCE_ORG_ID,
NULL AS IMPLEMENT_SR_INSTANCE_ID,
NULL AS IMPLEMENT_SUPPLIER_ID,
NULL AS IMPLEMENT_SUPPLIER_SITE_ID,
NULL AS IMPLEMENT_AS,
NULL AS RELEASE_STATUS,
NULL AS LOAD_TYPE,
NULL AS PROCESS_SEQ_ID,
NULL AS SCO_SUPPLY_FLAG,
NULL AS ALTERNATE_BOM_DESIGNATOR,
NULL AS ALTERNATE_ROUTING_DESIGNATOR,
NULL AS OPERATION_SEQ_NUM,
NULL AS BY_PRODUCT_USING_ASSY_ID,
NULL AS SOURCE_ORGANIZATION_ID,
NULL AS SOURCE_SR_INSTANCE_ID,
NULL AS SOURCE_SUPPLIER_SITE_ID,
NULL AS SOURCE_SUPPLIER_ID,
NULL AS SHIP_METHOD,
NULL AS WEIGHT_CAPACITY_USED,
NULL AS VOLUME_CAPACITY_USED,
NULL AS NEW_SHIP_DATE,
NULL AS NEW_DOCK_DATE,
NULL AS OLD_DOCK_DATE,
NULL AS LINE_ID,
NULL AS PROJECT_ID,
NULL AS TASK_ID,
NULL AS PLANNING_GROUP,
NULL AS IMPLEMENT_PROJECT_ID,
NULL AS IMPLEMENT_TASK_ID,
NULL AS IMPLEMENT_SCHEDULE_GROUP_ID,
NULL AS IMPLEMENT_BUILD_SEQUENCE,
NULL AS IMPLEMENT_ALTERNATE_BOM,
NULL AS IMPLEMENT_ALTERNATE_ROUTING,
NULL AS IMPLEMENT_UNIT_NUMBER,
NULL AS IMPLEMENT_LINE_ID,
NULL AS RELEASE_ERRORS,
NULL AS NUMBER1,
NULL AS SOURCE_ITEM_ID,
NULL AS ORDER_NUMBER,
NULL AS SCHEDULE_GROUP_ID,
NULL AS BUILD_SEQUENCE,
NULL AS WIP_ENTITY_NAME,
NULL AS IMPLEMENT_PROCESSING_DAYS,
NULL AS DELIVERY_PRICE,
NULL AS LATE_SUPPLY_DATE,
NULL AS LATE_SUPPLY_QTY,
NULL AS LOT_NUMBER,
NULL AS SUBINVENTORY_CODE,
NULL AS QTY_SCRAPPED,
NULL AS EXPECTED_SCRAP_QTY,
NULL AS QTY_COMPLETED,
NULL AS DAILY_RATE,
NULL AS SCHEDULE_GROUP_NAME,
NULL AS UPDATED,
NULL AS SUBST_ITEM_FLAG,
NULL AS STATUS,
NULL AS APPLIED,
NULL AS EXPIRATION_QUANTITY,
NULL AS EXPIRATION_DATE,
NULL AS NON_NETTABLE_QTY,
NULL AS IMPLEMENT_WIP_START_DATE,
NULL AS REFRESH_NUMBER,
NULL AS LAST_UPDATE_DATE,
NULL AS LAST_UPDATED_BY,
NULL AS CREATED_BY,
NULL AS LAST_UPDATE_LOGIN,
NULL AS REQUEST_ID,
NULL AS PROGRAM_APPLICATION_ID,
NULL AS PROGRAM_ID,
NULL AS PROGRAM_UPDATE_DATE,
NULL AS IMPLEMENT_DAILY_RATE,
NULL AS NEED_BY_DATE,
NULL AS SOURCE_SUPPLY_ID,
NULL AS SR_MTL_SUPPLY_ID,
NULL AS WIP_STATUS_CODE,
NULL AS DEMAND_CLASS,
NULL AS FROM_ORGANIZATION_ID,
NULL AS WIP_SUPPLY_TYPE,
NULL AS LOAD_FACTOR_RATE,
NULL AS ROUTING_SEQUENCE_ID,
NULL AS BILL_SEQUENCE_ID,
NULL AS COPRODUCTS_SUPPLY,
NULL AS CFM_ROUTING_FLAG,
NULL AS CUSTOMER_ID,
NULL AS SHIP_TO_SITE_ID,
NULL AS OLD_NEED_BY_DATE,
NULL AS OLD_DAILY_RATE,
NULL AS OLD_FIRST_UNIT_START_DATE,
NULL AS OLD_LAST_UNIT_COMPLETION_DATE,
NULL AS OLD_NEW_SCHEDULE_DATE,
NULL AS OLD_QTY_COMPLETED,
NULL AS OLD_NEW_ORDER_QUANTITY,
NULL AS OLD_FIRM_QUANTITY,
NULL AS OLD_FIRM_DATE,
NULL AS PLANNING_PARTNER_SITE_ID,
NULL AS PLANNING_TP_TYPE,
NULL AS OWNING_PARTNER_SITE_ID,
NULL AS OWNING_TP_TYPE,
NULL AS VMI_FLAG,
NULL AS EARLIEST_START_DATE,
NULL AS EARLIEST_COMPLETION_DATE,
NULL AS MIN_START_DATE,
NULL AS SCHEDULED_DEMAND_ID,
NULL AS EXPLOSION_DATE,
NULL AS SCO_SUPPLY_DATE,
NULL AS RECORD_SOURCE,
NULL AS SUPPLY_IS_SHARED,
NULL AS ULPSD,
NULL AS ULPCD,
NULL AS UEPSD,
NULL AS UEPCD,
NULL AS EACD,
NULL AS ORIGINAL_NEED_BY_DATE,
NULL AS ORIGINAL_QUANTITY,
NULL AS ACCEPTANCE_REQUIRED_FLAG,
NULL AS PROMISED_DATE,
NULL AS WIP_START_QUANTITY,
NULL AS END_ORDER_NUMBER,
NULL AS END_ORDER_LINE_NUMBER,
NULL AS ORDER_LINE_NUMBER,
NULL AS QUANTITY_PER_ASSEMBLY,
NULL AS QUANTITY_ISSUED,
NULL AS UNBUCKETED_DEMAND_DATE,
NULL AS SHIPMENT_ID,
NULL AS JOB_OP_SEQ_NUM,
NULL AS JUMP_OP_SEQ_NUM,
NULL AS SHIP_CALENDAR,
NULL AS RECEIVING_CALENDAR,
NULL AS INTRANSIT_CALENDAR,
NULL AS INTRANSIT_LEAD_TIME,
NULL AS OLD_SHIP_DATE,
NULL AS IMPLEMENT_SHIP_DATE,
NULL AS ORIG_SHIP_METHOD,
NULL AS ORIG_INTRANSIT_LEAD_TIME,
NULL AS PARENT_ID,
NULL AS DAYS_LATE,
NULL AS SCHEDULE_PRIORITY,
NULL AS PO_LINE_LOCATION_ID,
NULL AS PO_DISTRIBUTION_ID,
NULL AS WSM_FAULTY_NETWORK,
NULL AS IMPLEMENT_DEST_ORG_ID,
NULL AS IMPLEMENT_DEST_INST_ID,
NULL AS REQUESTED_START_DATE,
NULL AS REQUESTED_COMPLETION_DATE,
NULL AS ASSET_SERIAL_NUMBER,
NULL AS ASSET_ITEM_ID,
NULL AS TOP_TRANSACTION_ID,
NULL AS UNBUCKETED_NEW_SCHED_DATE,
NULL AS IMPLEMENT_SHIP_METHOD,
NULL AS ACTUAL_START_DATE,
NULL AS FIRM_SHIP_DATE,
NULL AS SCHEDULE_ORIGINATION_TYPE,
NULL AS UNBUCKETED_START_DATE,
NULL AS SR_CUSTOMER_ACCT_ID,
NULL AS ITEM_TYPE_ID,
NULL AS CUSTOMER_PRODUCT_ID,
NULL AS RO_STATUS_CODE,
NULL AS SR_REPAIR_GROUP_ID,
NULL AS SR_REPAIR_TYPE_ID,
NULL AS ITEM_TYPE_VALUE,
NULL AS ZONE_ID,
NULL AS RO_CREATION_DATE,
NULL AS REPAIR_LEAD_TIME,
NULL AS FIRM_START_DATE,
NULL AS REQ_LINE_ID,
NULL AS INTRANSIT_OWNING_ORG_ID,
NULL AS RELEASABLE,
NULL AS BATCH_ID,
NULL AS OTM_ARRIVAL_DATE,
NULL AS PS_SUPPLY_FLAG,
NULL AS CTB_FLAG,
NULL AS CTB_COMP_AVAIL_PERCENT,
NULL AS RTB_ORDER_QTY_PERCENT,
NULL AS CTB_EXPECTED_DATE,
NULL AS POTENTIAL_RTB_PERCENT,
NULL AS CTB_PRIORITY,
NULL AS DESCRIPTION,
NULL AS MAINTENANCE_OBJECT_SOURCE,
NULL AS PRODUCTION_SCHEDULE_ID,
NULL AS VISIT_ID,
NULL AS PRODUCES_TO_STOCK,
NULL AS PRODUCT_CLASSIFICATION,
NULL AS MAINTENANCE_REQT,
NULL AS ACTIVITY_TYPE,
NULL AS ACTIVITY_NAME,
NULL AS CLASS_CODE,
NULL AS SHUTDOWN_TYPE,
NULL AS TO_BE_EXPLODED,
NULL AS OBJECT_TYPE,
NULL AS MAINTENANCE_TYPE_CODE,
NULL AS ACTIVITY_ITEM_ID,
NULL AS ORIG_FIRM_DATE,
NULL AS ORIG_FIRM_QUANTITY,
NULL AS USE_WO_SUBSTITUTE,
NULL AS ASSET_NUMBER,
NULL AS MAINTENANCE_OBJECT_ID,
NULL AS MAINTENANCE_OBJECT_TYPE,
NULL AS OPERATING_FLEET,
NULL AS MAINTENANCE_REQUIREMENT,
NULL AS COLL_ORDER_TYPE,
NULL AS CTB_EXPECTED_DATE_BUY_COMPS,
NULL AS SUBSTITUTE_COMPONENTS_USED,
NULL AS RESERVED_QTY,
NULL AS PO_OR_REQ_HEADER_ID,
NULL AS ACTUAL_LEAD_TIME,
NULL AS MIN_LEAD_TIME,
NULL AS PIP_ITEM_ID,
NULL AS SUPP_CAPACITY_OVERLOAD,
NULL AS VOLUME_CAPACITY_OVERLOAD,
NULL AS WEIGHT_CAPACITY_OVERLOAD,
NULL AS PM_SNAPSHOT_DATE,
'1900-01-01'::TIMESTAMP AS PSA_LOAD_DTS,
NULL AS PSA_RECORD_SOURCE,
'N' AS PSA_DELETE_IND,
CONVERT_TIMEZONE('UTC','1900-01-01'::TIMESTAMP) AS LOAD_DTS,
'USAZET.SNOWFLAKE.FBIN.DERIVED' AS REC_SRC,
DECODE(GR.VALUE, 0, 'GHOST RECORD-SYSTEM', -1, 'GHOST RECORD-nullkey-required', -2, 'GHOST RECORD-nullkey-optional') AS BKCC,
''::BINARY AS HASHDIFF
FROM
TABLE(strtok_split_to_table('0|-1|-2', '|')) AS GR
{% endif %}
