---- SRC LAYER ----
WITH
SRC_SMFNREF        as ( SELECT * FROM {{ ref('v_psa_stg_pos_gross_sales_history_ref__moen_ferguson_new') }} as SRC 
                         {% if is_incremental() %}
                         WHERE SRC.LOAD_DTS > (SELECT DATEADD('HOUR', '-1', MAX(LOAD_DTS)) FROM {{this}})
                         {% endif %}  )

/*
SRC_SMFNREF        as ( SELECT * FROM STAGING.v_psa_stg_pos_gross_sales_history_ref__moen_ferguson_new )
*/
---- LOGIC LAYER ----

, LOGIC_SMFNREF as (
    SELECT
        STORE_HK
      , SALESORG
      , DISTRIBUTION_CHANNEL
      , CUSTOMER_DIVISION
      , _FILE
      , YEAR_MONTH
      , DATE
      , TRANSACTION_TYPE
      , SELL_LOCATION_ID
      , LEGACY_SELL_LOCATION_ID
      , SELL_LOCATION_NAME
      , SHIP_LOCATION_ZIP
      , LEGACY_SHIP_LOCATION_ID
      , SHIP_LOCATION_NAME
      , SHIP_LOCATION_CITY
      , SHIP_LOCATION_STATE
      , ORDER_CHANNEL
      , BUILD_COM_ORDER
      , CUSTOMER_GROUP
      , FEI_PRODUCT_NO
      , FEI_PRODUCT_CODE
      , FEI_PRODUCT_DESCRIPTION
      , VENDOR_CODE
      , SHIPPED_QTY
      , PRODUCT_DEST_CITY
      , PRODUCT_DEST_STATE
      , PRODUCT_DEST_ZIP
      , PRODUCT_DEST_ZIP_CODE
      , UOM
      , _FIVETRAN_SYNCED
      , SHIP_CUSTOMER
      , SHIP_CUSTOMER_ID
      , DEST_CUSTOMER
      , DEST_CUSTOMER_ID
      , SAP_MATERIAL_NUMBER
      , FILE_SOURCE
      , GROSS_DOLLARS
      , PM_SNAPSHOT_DATE
      , PSA_LOAD_DTS
      , PSA_RECORD_SOURCE
      , PSA_DELETE_IND
      , LOAD_DTS
      , REC_SRC
      , HASHDIFF
    FROM SRC_SMFNREF
)
---- RENAME LAYER ----

, RENAME_SMFNREF as (
    SELECT
        STORE_HK
      , SALESORG
      , DISTRIBUTION_CHANNEL
      , CUSTOMER_DIVISION
      , _FILE
      , YEAR_MONTH
      , DATE
      , TRANSACTION_TYPE
      , SELL_LOCATION_ID
      , LEGACY_SELL_LOCATION_ID
      , SELL_LOCATION_NAME
      , SHIP_LOCATION_ZIP
      , LEGACY_SHIP_LOCATION_ID
      , SHIP_LOCATION_NAME
      , SHIP_LOCATION_CITY
      , SHIP_LOCATION_STATE
      , ORDER_CHANNEL
      , BUILD_COM_ORDER
      , CUSTOMER_GROUP
      , FEI_PRODUCT_NO
      , FEI_PRODUCT_CODE
      , FEI_PRODUCT_DESCRIPTION
      , VENDOR_CODE
      , SHIPPED_QTY
      , PRODUCT_DEST_CITY
      , PRODUCT_DEST_STATE
      , PRODUCT_DEST_ZIP
      , PRODUCT_DEST_ZIP_CODE
      , UOM
      , _FIVETRAN_SYNCED
      , SHIP_CUSTOMER
      , SHIP_CUSTOMER_ID
      , DEST_CUSTOMER
      , DEST_CUSTOMER_ID
      , SAP_MATERIAL_NUMBER
      , FILE_SOURCE
      , GROSS_DOLLARS
      , PM_SNAPSHOT_DATE
      , PSA_LOAD_DTS
      , PSA_RECORD_SOURCE
      , PSA_DELETE_IND
      , LOAD_DTS
      , REC_SRC
      , HASHDIFF
    FROM LOGIC_SMFNREF
)
---- FILTER LAYER ----

, FILTER_SMFNREF as (
    SELECT *
    FROM RENAME_SMFNREF
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM FILTER_SMFNREF
)

---- FINAL LAYER ----
SELECT
          STORE_HK
        , SALESORG
        , DISTRIBUTION_CHANNEL
        , CUSTOMER_DIVISION
        , _FILE
        , YEAR_MONTH
        , DATE
        , TRANSACTION_TYPE
        , SELL_LOCATION_ID
        , LEGACY_SELL_LOCATION_ID
        , SELL_LOCATION_NAME
        , SHIP_LOCATION_ZIP
        , LEGACY_SHIP_LOCATION_ID
        , SHIP_LOCATION_NAME
        , SHIP_LOCATION_CITY
        , SHIP_LOCATION_STATE
        , ORDER_CHANNEL
        , BUILD_COM_ORDER
        , CUSTOMER_GROUP
        , FEI_PRODUCT_NO
        , FEI_PRODUCT_CODE
        , FEI_PRODUCT_DESCRIPTION
        , VENDOR_CODE
        , SHIPPED_QTY
        , PRODUCT_DEST_CITY
        , PRODUCT_DEST_STATE
        , PRODUCT_DEST_ZIP
        , PRODUCT_DEST_ZIP_CODE
        , UOM
        , _FIVETRAN_SYNCED
        , SHIP_CUSTOMER
        , SHIP_CUSTOMER_ID
        , DEST_CUSTOMER
        , DEST_CUSTOMER_ID
        , SAP_MATERIAL_NUMBER
        , FILE_SOURCE
        , GROSS_DOLLARS
        , PM_SNAPSHOT_DATE
        , PSA_LOAD_DTS
        , PSA_RECORD_SOURCE
        , PSA_DELETE_IND
        , LOAD_DTS
        , REC_SRC
        , HASHDIFF
FROM JOIN_RESULT
{% if is_incremental() %}
WHERE NOT EXISTS (
    SELECT 1 
    FROM {{ this }} existing
    WHERE existing.STORE_HK = JOIN_RESULT.STORE_HK
	AND existing._FILE = JOIN_RESULT._FILE
	AND existing.DATE = JOIN_RESULT.DATE
	AND existing.FEI_PRODUCT_CODE = JOIN_RESULT.FEI_PRODUCT_CODE
	AND existing.TRANSACTION_TYPE = JOIN_RESULT.TRANSACTION_TYPE
	AND existing.ORDER_CHANNEL = JOIN_RESULT.ORDER_CHANNEL
	AND existing.HASHDIFF = JOIN_RESULT.HASHDIFF	
)
{% endif %}
{% if not is_incremental() %}

union all
SELECT 
MD5_BINARY(GR.VALUE) AS STORE_HK,
NULL AS SALESORG,
NULL AS DISTRIBUTION_CHANNEL,
NULL AS CUSTOMER_DIVISION,
GR.VALUE::text AS _FILE,
NULL AS YEAR_MONTH,
'1900-01-01' AS DATE,
GR.VALUE::text AS TRANSACTION_TYPE,
NULL AS SELL_LOCATION_ID,
NULL AS LEGACY_SELL_LOCATION_ID,
NULL AS SELL_LOCATION_NAME,
NULL AS SHIP_LOCATION_ZIP,
NULL AS LEGACY_SHIP_LOCATION_ID,
NULL AS SHIP_LOCATION_NAME,
NULL AS SHIP_LOCATION_CITY,
NULL AS SHIP_LOCATION_STATE,
GR.VALUE::text AS ORDER_CHANNEL,
NULL AS BUILD_COM_ORDER,
NULL AS CUSTOMER_GROUP,
NULL AS FEI_PRODUCT_NO,
GR.VALUE::text AS FEI_PRODUCT_CODE,
NULL AS FEI_PRODUCT_DESCRIPTION,
NULL AS VENDOR_CODE,
NULL AS SHIPPED_QTY,
NULL AS PRODUCT_DEST_CITY,
NULL AS PRODUCT_DEST_STATE,
NULL AS PRODUCT_DEST_ZIP,
NULL AS PRODUCT_DEST_ZIP_CODE,
NULL AS UOM,
NULL AS _FIVETRAN_SYNCED,
NULL AS SHIP_CUSTOMER,
NULL AS SHIP_CUSTOMER_ID,
NULL AS DEST_CUSTOMER,
NULL AS DEST_CUSTOMER_ID,
NULL AS SAP_MATERIAL_NUMBER,
NULL AS FILE_SOURCE,
NULL AS GROSS_DOLLARS,
NULL AS PM_SNAPSHOT_DATE,
'1900-01-01'::TIMESTAMP AS PSA_LOAD_DTS,
NULL AS PSA_RECORD_SOURCE,
'N' AS PSA_DELETE_IND,
CONVERT_TIMEZONE('UTC','1900-01-01'::TIMESTAMP) AS LOAD_DTS,
'USAZET.SNOWFLAKE.FBIN.DERIVED' AS REC_SRC,
''::BINARY AS HASHDIFF
FROM
TABLE(strtok_split_to_table('0|-1|-2', '|')) AS GR
{% endif %}
