---- SRC LAYER ----
WITH
SRC_a              as ( SELECT * FROM {{ ref('v_psa_stg_po_item__ml_ebs') }} as SRC 
                         {% if is_incremental() %}
                              where src.load_dts > (select dateadd('HOUR',-1,max(load_dts)) from {{ this }})
                            {% endif %}   )

/*
SRC_a              as ( SELECT * FROM staging.v_psa_stg_po_item__ml_ebs )
*/
---- LOGIC LAYER ----

, LOGIC_a as (
    SELECT
        PO_ITEM_HK
      , PO_HEADER_ID
      , LINE_NUM
      , CATEGORY_ID
      , ORG_ID
      , PRICE_BREAK_LOOKUP_CODE
      , OKE_CONTRACT_VERSION_ID
      , UNIT_PRICE
      , SVC_COMPLETION_NOTIF_SENT
      , PROGRAM_ID
      , UDA_TEMPLATE_ID
      , GLOBAL_ATTRIBUTE5
      , GLOBAL_ATTRIBUTE4
      , GLOBAL_ATTRIBUTE7
      , GLOBAL_ATTRIBUTE6
      , GLOBAL_ATTRIBUTE1
      , AMOUNT
      , GLOBAL_ATTRIBUTE3
      , GLOBAL_ATTRIBUTE2
      , FROM_LINE_LOCATION_ID
      , BASE_UNIT_PRICE
      , GROUP_LINE_ID
      , GLOBAL_ATTRIBUTE9
      , GLOBAL_ATTRIBUTE8
      , MAX_ORDER_QUANTITY
      , UNORDERED_FLAG
      , NOT_TO_EXCEED_PRICE
      , ALLOW_PRICE_OVERRIDE_FLAG
      , ATTRIBUTE3
      , ATTRIBUTE2
      , ATTRIBUTE1
      , CONTRACT_NUM
      , VENDOR_PRODUCT_NUM
      , ITEM_ID
      , ATTRIBUTE9
      , SECONDARY_QTY
      , ATTRIBUTE8
      , ATTRIBUTE7
      , USSGL_TRANSACTION_CODE
      , ATTRIBUTE6
      , ATTRIBUTE5
      , AUCTION_DISPLAY_NUMBER
      , ATTRIBUTE4
      , CLM_EXERCISED_DATE
      , SECONDARY_UNIT_OF_MEASURE
      , EXPIRATION_DATE
      , BASE_QTY
      , NOTE_TO_VENDOR
      , TASK_ID
      , PROGRESS_PAYMENT_RATE
      , ATTRIBUTE10
      , CLM_OPTION_FROM_DATE
      , JOB_ID
      , OKE_CONTRACT_HEADER_ID
      , AUCTION_LINE_NUMBER
      , CAPITAL_EXPENSE_FLAG
      , ATTRIBUTE14
      , ATTRIBUTE13
      , ATTRIBUTE12
      , ATTRIBUTE11
      , CANCEL_REASON
      , CONTRACTOR_FIRST_NAME
      , FROM_LINE_ID
      , TAX_CODE_ID
      , CLM_FUNDED_FLAG
      , MIN_ORDER_QUANTITY
      , CLM_OPTION_TO_DATE
      , CLOSED_BY
      , COMMITTED_AMOUNT
      , PROJECT_ID
      , SUPPLIER_REF_NUMBER
      , TAX_NAME
      , FROM_HEADER_ID
      , CATALOG_NAME
      , CLOSED_FLAG
      , ITEM_REVISION
      , FIRM_DATE
      , GLOBAL_ATTRIBUTE20
      , ORDER_TYPE_LOOKUP_CODE
      , START_DATE
      , REFERENCE_NUM
      , MIN_RELEASE_AMOUNT
      , SUPPLIER_PART_AUXID
      , LAST_UPDATED_PROGRAM
      , GLOBAL_ATTRIBUTE17
      , GLOBAL_ATTRIBUTE18
      , GLOBAL_ATTRIBUTE15
      , QUANTITY_COMMITTED
      , CANCEL_FLAG
      , GLOBAL_ATTRIBUTE16
      , MAX_RETAINAGE_AMOUNT
      , GLOBAL_ATTRIBUTE13
      , GLOBAL_ATTRIBUTE14
      , BID_NUMBER
      , GLOBAL_ATTRIBUTE11
      , GLOBAL_ATTRIBUTE12
      , CLM_OPTION_INDICATOR
      , ATTRIBUTE15
      , TAXABLE_FLAG
      , GLOBAL_ATTRIBUTE19
      , CLOSED_REASON
      , QUANTITY
      , USER_HOLD_FLAG
      , SECONDARY_UOM
      , GLOBAL_ATTRIBUTE10
      , ITEM_DESCRIPTION
      , CONTRACTOR_LAST_NAME
      , SVC_AMOUNT_NOTIF_SENT
      , RECOUPMENT_RATE
      , CLM_BASE_LINE_NUM
      , CLM_IDC_TYPE
      , BASE_UOM
      , COST_CONSTRAINT
      , MARKET_PRICE
      , CREATED_BY
      , LAST_UPDATED_BY
      , TRANSACTION_REASON_CODE
      , CANCELLED_BY
      , LINE_REFERENCE_NUM
      , SECONDARY_QUANTITY
      , LINE_NUM_DISPLAY
      , CONTRACT_ID
      , HAZARD_CLASS_ID
      , CLM_OPTION_NUM
      , CONTRACT_TYPE
      , CLM_INFO_FLAG
      , AUCTION_HEADER_ID
      , ATTRIBUTE_CATEGORY
      , PROGRAM_APPLICATION_ID
      , GOVERNMENT_CONTEXT
      , LINE_TYPE_ID
      , UNIT_MEAS_LOOKUP_CODE
      , PREFERRED_GRADE
      , MATCHING_BASIS
      , REQUEST_ID
      , FIRM_STATUS_LOOKUP_CODE
      , MANUAL_PRICE_CHANGE_FLAG
      , BID_LINE_NUMBER
      , USER_DOCUMENT_STATUS
      , CLOSED_CODE
      , TYPE_1099
      , LIST_PRICE_PER_UNIT
      , NEGOTIATED_BY_PREPARER_FLAG
      , QC_GRADE
      , DRAFT_ID
      , QTY_RCV_TOLERANCE
      , TAX_ATTRIBUTE_UPDATE_CODE
      , PRICE_TYPE_LOOKUP_CODE
      , OVER_TOLERANCE_ERROR_FLAG
      , PURCHASE_BASIS
      , LAST_UPDATE_LOGIN
      , RETAINAGE_RATE
      , GLOBAL_ATTRIBUTE_CATEGORY
      , UN_NUMBER_ID
      , CLM_EXERCISED_FLAG
      , IP_CATEGORY_ID
      , PO_LINE_ID
      , PROGRAM_UPDATE_DATE
      , CLOSED_DATE
      , CANCEL_DATE
      , RETROACTIVE_DATE
      , CREATION_DATE
      , LAST_UPDATE_DATE
      , _FIVETRAN_DELETED
      , _FIVETRAN_ID
      , _FIVETRAN_SYNCED
      , PSA_LOAD_DTS
      , PSA_DELETE_IND
      , LOAD_DTS
      , REC_SRC
      , BKCC
      , HASHDIFF
    FROM SRC_a
)
---- RENAME LAYER ----

, RENAME_a as (
    SELECT
        PO_ITEM_HK
      , PO_HEADER_ID
      , LINE_NUM
      , CATEGORY_ID
      , ORG_ID
      , PRICE_BREAK_LOOKUP_CODE
      , OKE_CONTRACT_VERSION_ID
      , UNIT_PRICE
      , SVC_COMPLETION_NOTIF_SENT
      , PROGRAM_ID
      , UDA_TEMPLATE_ID
      , GLOBAL_ATTRIBUTE5
      , GLOBAL_ATTRIBUTE4
      , GLOBAL_ATTRIBUTE7
      , GLOBAL_ATTRIBUTE6
      , GLOBAL_ATTRIBUTE1
      , AMOUNT
      , GLOBAL_ATTRIBUTE3
      , GLOBAL_ATTRIBUTE2
      , FROM_LINE_LOCATION_ID
      , BASE_UNIT_PRICE
      , GROUP_LINE_ID
      , GLOBAL_ATTRIBUTE9
      , GLOBAL_ATTRIBUTE8
      , MAX_ORDER_QUANTITY
      , UNORDERED_FLAG
      , NOT_TO_EXCEED_PRICE
      , ALLOW_PRICE_OVERRIDE_FLAG
      , ATTRIBUTE3
      , ATTRIBUTE2
      , ATTRIBUTE1
      , CONTRACT_NUM
      , VENDOR_PRODUCT_NUM
      , ITEM_ID
      , ATTRIBUTE9
      , SECONDARY_QTY
      , ATTRIBUTE8
      , ATTRIBUTE7
      , USSGL_TRANSACTION_CODE
      , ATTRIBUTE6
      , ATTRIBUTE5
      , AUCTION_DISPLAY_NUMBER
      , ATTRIBUTE4
      , CLM_EXERCISED_DATE
      , SECONDARY_UNIT_OF_MEASURE
      , EXPIRATION_DATE
      , BASE_QTY
      , NOTE_TO_VENDOR
      , TASK_ID
      , PROGRESS_PAYMENT_RATE
      , ATTRIBUTE10
      , CLM_OPTION_FROM_DATE
      , JOB_ID
      , OKE_CONTRACT_HEADER_ID
      , AUCTION_LINE_NUMBER
      , CAPITAL_EXPENSE_FLAG
      , ATTRIBUTE14
      , ATTRIBUTE13
      , ATTRIBUTE12
      , ATTRIBUTE11
      , CANCEL_REASON
      , CONTRACTOR_FIRST_NAME
      , FROM_LINE_ID
      , TAX_CODE_ID
      , CLM_FUNDED_FLAG
      , MIN_ORDER_QUANTITY
      , CLM_OPTION_TO_DATE
      , CLOSED_BY
      , COMMITTED_AMOUNT
      , PROJECT_ID
      , SUPPLIER_REF_NUMBER
      , TAX_NAME
      , FROM_HEADER_ID
      , CATALOG_NAME
      , CLOSED_FLAG
      , ITEM_REVISION
      , FIRM_DATE
      , GLOBAL_ATTRIBUTE20
      , ORDER_TYPE_LOOKUP_CODE
      , START_DATE
      , REFERENCE_NUM
      , MIN_RELEASE_AMOUNT
      , SUPPLIER_PART_AUXID
      , LAST_UPDATED_PROGRAM
      , GLOBAL_ATTRIBUTE17
      , GLOBAL_ATTRIBUTE18
      , GLOBAL_ATTRIBUTE15
      , QUANTITY_COMMITTED
      , CANCEL_FLAG
      , GLOBAL_ATTRIBUTE16
      , MAX_RETAINAGE_AMOUNT
      , GLOBAL_ATTRIBUTE13
      , GLOBAL_ATTRIBUTE14
      , BID_NUMBER
      , GLOBAL_ATTRIBUTE11
      , GLOBAL_ATTRIBUTE12
      , CLM_OPTION_INDICATOR
      , ATTRIBUTE15
      , TAXABLE_FLAG
      , GLOBAL_ATTRIBUTE19
      , CLOSED_REASON
      , QUANTITY
      , USER_HOLD_FLAG
      , SECONDARY_UOM
      , GLOBAL_ATTRIBUTE10
      , ITEM_DESCRIPTION
      , CONTRACTOR_LAST_NAME
      , SVC_AMOUNT_NOTIF_SENT
      , RECOUPMENT_RATE
      , CLM_BASE_LINE_NUM
      , CLM_IDC_TYPE
      , BASE_UOM
      , COST_CONSTRAINT
      , MARKET_PRICE
      , CREATED_BY
      , LAST_UPDATED_BY
      , TRANSACTION_REASON_CODE
      , CANCELLED_BY
      , LINE_REFERENCE_NUM
      , SECONDARY_QUANTITY
      , LINE_NUM_DISPLAY
      , CONTRACT_ID
      , HAZARD_CLASS_ID
      , CLM_OPTION_NUM
      , CONTRACT_TYPE
      , CLM_INFO_FLAG
      , AUCTION_HEADER_ID
      , ATTRIBUTE_CATEGORY
      , PROGRAM_APPLICATION_ID
      , GOVERNMENT_CONTEXT
      , LINE_TYPE_ID
      , UNIT_MEAS_LOOKUP_CODE
      , PREFERRED_GRADE
      , MATCHING_BASIS
      , REQUEST_ID
      , FIRM_STATUS_LOOKUP_CODE
      , MANUAL_PRICE_CHANGE_FLAG
      , BID_LINE_NUMBER
      , USER_DOCUMENT_STATUS
      , CLOSED_CODE
      , TYPE_1099
      , LIST_PRICE_PER_UNIT
      , NEGOTIATED_BY_PREPARER_FLAG
      , QC_GRADE
      , DRAFT_ID
      , QTY_RCV_TOLERANCE
      , TAX_ATTRIBUTE_UPDATE_CODE
      , PRICE_TYPE_LOOKUP_CODE
      , OVER_TOLERANCE_ERROR_FLAG
      , PURCHASE_BASIS
      , LAST_UPDATE_LOGIN
      , RETAINAGE_RATE
      , GLOBAL_ATTRIBUTE_CATEGORY
      , UN_NUMBER_ID
      , CLM_EXERCISED_FLAG
      , IP_CATEGORY_ID
      , PO_LINE_ID
      , PROGRAM_UPDATE_DATE
      , CLOSED_DATE
      , CANCEL_DATE
      , RETROACTIVE_DATE
      , CREATION_DATE
      , LAST_UPDATE_DATE
      , _FIVETRAN_DELETED
      , _FIVETRAN_ID
      , _FIVETRAN_SYNCED
      , PSA_LOAD_DTS
      , PSA_DELETE_IND
      , LOAD_DTS
      , REC_SRC
      , BKCC
      , HASHDIFF
    FROM LOGIC_a
)
---- FILTER LAYER ----

, FILTER_a as (
    SELECT *
    FROM RENAME_a
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM FILTER_a
)

---- FINAL LAYER ----
SELECT
          PO_ITEM_HK
        , PO_HEADER_ID
        , LINE_NUM
        , CATEGORY_ID
        , ORG_ID
        , PRICE_BREAK_LOOKUP_CODE
        , OKE_CONTRACT_VERSION_ID
        , UNIT_PRICE
        , SVC_COMPLETION_NOTIF_SENT
        , PROGRAM_ID
        , UDA_TEMPLATE_ID
        , GLOBAL_ATTRIBUTE5
        , GLOBAL_ATTRIBUTE4
        , GLOBAL_ATTRIBUTE7
        , GLOBAL_ATTRIBUTE6
        , GLOBAL_ATTRIBUTE1
        , AMOUNT
        , GLOBAL_ATTRIBUTE3
        , GLOBAL_ATTRIBUTE2
        , FROM_LINE_LOCATION_ID
        , BASE_UNIT_PRICE
        , GROUP_LINE_ID
        , GLOBAL_ATTRIBUTE9
        , GLOBAL_ATTRIBUTE8
        , MAX_ORDER_QUANTITY
        , UNORDERED_FLAG
        , NOT_TO_EXCEED_PRICE
        , ALLOW_PRICE_OVERRIDE_FLAG
        , ATTRIBUTE3
        , ATTRIBUTE2
        , ATTRIBUTE1
        , CONTRACT_NUM
        , VENDOR_PRODUCT_NUM
        , ITEM_ID
        , ATTRIBUTE9
        , SECONDARY_QTY
        , ATTRIBUTE8
        , ATTRIBUTE7
        , USSGL_TRANSACTION_CODE
        , ATTRIBUTE6
        , ATTRIBUTE5
        , AUCTION_DISPLAY_NUMBER
        , ATTRIBUTE4
        , CLM_EXERCISED_DATE
        , SECONDARY_UNIT_OF_MEASURE
        , EXPIRATION_DATE
        , BASE_QTY
        , NOTE_TO_VENDOR
        , TASK_ID
        , PROGRESS_PAYMENT_RATE
        , ATTRIBUTE10
        , CLM_OPTION_FROM_DATE
        , JOB_ID
        , OKE_CONTRACT_HEADER_ID
        , AUCTION_LINE_NUMBER
        , CAPITAL_EXPENSE_FLAG
        , ATTRIBUTE14
        , ATTRIBUTE13
        , ATTRIBUTE12
        , ATTRIBUTE11
        , CANCEL_REASON
        , CONTRACTOR_FIRST_NAME
        , FROM_LINE_ID
        , TAX_CODE_ID
        , CLM_FUNDED_FLAG
        , MIN_ORDER_QUANTITY
        , CLM_OPTION_TO_DATE
        , CLOSED_BY
        , COMMITTED_AMOUNT
        , PROJECT_ID
        , SUPPLIER_REF_NUMBER
        , TAX_NAME
        , FROM_HEADER_ID
        , CATALOG_NAME
        , CLOSED_FLAG
        , ITEM_REVISION
        , FIRM_DATE
        , GLOBAL_ATTRIBUTE20
        , ORDER_TYPE_LOOKUP_CODE
        , START_DATE
        , REFERENCE_NUM
        , MIN_RELEASE_AMOUNT
        , SUPPLIER_PART_AUXID
        , LAST_UPDATED_PROGRAM
        , GLOBAL_ATTRIBUTE17
        , GLOBAL_ATTRIBUTE18
        , GLOBAL_ATTRIBUTE15
        , QUANTITY_COMMITTED
        , CANCEL_FLAG
        , GLOBAL_ATTRIBUTE16
        , MAX_RETAINAGE_AMOUNT
        , GLOBAL_ATTRIBUTE13
        , GLOBAL_ATTRIBUTE14
        , BID_NUMBER
        , GLOBAL_ATTRIBUTE11
        , GLOBAL_ATTRIBUTE12
        , CLM_OPTION_INDICATOR
        , ATTRIBUTE15
        , TAXABLE_FLAG
        , GLOBAL_ATTRIBUTE19
        , CLOSED_REASON
        , QUANTITY
        , USER_HOLD_FLAG
        , SECONDARY_UOM
        , GLOBAL_ATTRIBUTE10
        , ITEM_DESCRIPTION
        , CONTRACTOR_LAST_NAME
        , SVC_AMOUNT_NOTIF_SENT
        , RECOUPMENT_RATE
        , CLM_BASE_LINE_NUM
        , CLM_IDC_TYPE
        , BASE_UOM
        , COST_CONSTRAINT
        , MARKET_PRICE
        , CREATED_BY
        , LAST_UPDATED_BY
        , TRANSACTION_REASON_CODE
        , CANCELLED_BY
        , LINE_REFERENCE_NUM
        , SECONDARY_QUANTITY
        , LINE_NUM_DISPLAY
        , CONTRACT_ID
        , HAZARD_CLASS_ID
        , CLM_OPTION_NUM
        , CONTRACT_TYPE
        , CLM_INFO_FLAG
        , AUCTION_HEADER_ID
        , ATTRIBUTE_CATEGORY
        , PROGRAM_APPLICATION_ID
        , GOVERNMENT_CONTEXT
        , LINE_TYPE_ID
        , UNIT_MEAS_LOOKUP_CODE
        , PREFERRED_GRADE
        , MATCHING_BASIS
        , REQUEST_ID
        , FIRM_STATUS_LOOKUP_CODE
        , MANUAL_PRICE_CHANGE_FLAG
        , BID_LINE_NUMBER
        , USER_DOCUMENT_STATUS
        , CLOSED_CODE
        , TYPE_1099
        , LIST_PRICE_PER_UNIT
        , NEGOTIATED_BY_PREPARER_FLAG
        , QC_GRADE
        , DRAFT_ID
        , QTY_RCV_TOLERANCE
        , TAX_ATTRIBUTE_UPDATE_CODE
        , PRICE_TYPE_LOOKUP_CODE
        , OVER_TOLERANCE_ERROR_FLAG
        , PURCHASE_BASIS
        , LAST_UPDATE_LOGIN
        , RETAINAGE_RATE
        , GLOBAL_ATTRIBUTE_CATEGORY
        , UN_NUMBER_ID
        , CLM_EXERCISED_FLAG
        , IP_CATEGORY_ID
        , PO_LINE_ID
        , PROGRAM_UPDATE_DATE
        , CLOSED_DATE
        , CANCEL_DATE
        , RETROACTIVE_DATE
        , CREATION_DATE
        , LAST_UPDATE_DATE
        , _FIVETRAN_DELETED
        , _FIVETRAN_ID
        , _FIVETRAN_SYNCED
        , PSA_LOAD_DTS
        , PSA_DELETE_IND
        , LOAD_DTS
        , REC_SRC
        , BKCC
        , HASHDIFF
FROM JOIN_RESULT
{% if is_incremental() %}
WHERE NOT EXISTS (
    SELECT 1 
    FROM {{ this }} existing
    WHERE existing.PO_ITEM_HK = JOIN_RESULT.PO_ITEM_HK
    AND existing.HASHDIFF = JOIN_RESULT.HASHDIFF
)
{% endif %}
{% if not is_incremental() %}

/* The following qualifier is implemented to prevent multiple loads of touched records during the initial build, such as multiple rows per HK and hashdiff. */
qualify 1 = row_number() over (partition by PO_ITEM_HK, HASHDIFF order by PSA_LOAD_DTS)

union all
SELECT 
MD5_BINARY(GR.VALUE) AS PO_ITEM_HK,
GR.VALUE::number AS PO_HEADER_ID,
GR.VALUE::number AS LINE_NUM,
GR.VALUE::number AS CATEGORY_ID,
GR.VALUE::number AS ORG_ID,
NULL AS PRICE_BREAK_LOOKUP_CODE,
NULL AS OKE_CONTRACT_VERSION_ID,
NULL AS UNIT_PRICE,
NULL AS SVC_COMPLETION_NOTIF_SENT,
NULL AS PROGRAM_ID,
NULL AS UDA_TEMPLATE_ID,
NULL AS GLOBAL_ATTRIBUTE5,
NULL AS GLOBAL_ATTRIBUTE4,
NULL AS GLOBAL_ATTRIBUTE7,
NULL AS GLOBAL_ATTRIBUTE6,
NULL AS GLOBAL_ATTRIBUTE1,
NULL AS AMOUNT,
NULL AS GLOBAL_ATTRIBUTE3,
NULL AS GLOBAL_ATTRIBUTE2,
NULL AS FROM_LINE_LOCATION_ID,
NULL AS BASE_UNIT_PRICE,
NULL AS GROUP_LINE_ID,
NULL AS GLOBAL_ATTRIBUTE9,
NULL AS GLOBAL_ATTRIBUTE8,
NULL AS MAX_ORDER_QUANTITY,
NULL AS UNORDERED_FLAG,
NULL AS NOT_TO_EXCEED_PRICE,
NULL AS ALLOW_PRICE_OVERRIDE_FLAG,
NULL AS ATTRIBUTE3,
NULL AS ATTRIBUTE2,
NULL AS ATTRIBUTE1,
NULL AS CONTRACT_NUM,
NULL AS VENDOR_PRODUCT_NUM,
NULL AS ITEM_ID,
NULL AS ATTRIBUTE9,
NULL AS SECONDARY_QTY,
NULL AS ATTRIBUTE8,
NULL AS ATTRIBUTE7,
NULL AS USSGL_TRANSACTION_CODE,
NULL AS ATTRIBUTE6,
NULL AS ATTRIBUTE5,
NULL AS AUCTION_DISPLAY_NUMBER,
NULL AS ATTRIBUTE4,
NULL AS CLM_EXERCISED_DATE,
NULL AS SECONDARY_UNIT_OF_MEASURE,
NULL AS EXPIRATION_DATE,
NULL AS BASE_QTY,
NULL AS NOTE_TO_VENDOR,
NULL AS TASK_ID,
NULL AS PROGRESS_PAYMENT_RATE,
NULL AS ATTRIBUTE10,
NULL AS CLM_OPTION_FROM_DATE,
NULL AS JOB_ID,
NULL AS OKE_CONTRACT_HEADER_ID,
NULL AS AUCTION_LINE_NUMBER,
NULL AS CAPITAL_EXPENSE_FLAG,
NULL AS ATTRIBUTE14,
NULL AS ATTRIBUTE13,
NULL AS ATTRIBUTE12,
NULL AS ATTRIBUTE11,
NULL AS CANCEL_REASON,
NULL AS CONTRACTOR_FIRST_NAME,
NULL AS FROM_LINE_ID,
NULL AS TAX_CODE_ID,
NULL AS CLM_FUNDED_FLAG,
NULL AS MIN_ORDER_QUANTITY,
NULL AS CLM_OPTION_TO_DATE,
NULL AS CLOSED_BY,
NULL AS COMMITTED_AMOUNT,
NULL AS PROJECT_ID,
NULL AS SUPPLIER_REF_NUMBER,
NULL AS TAX_NAME,
NULL AS FROM_HEADER_ID,
NULL AS CATALOG_NAME,
NULL AS CLOSED_FLAG,
NULL AS ITEM_REVISION,
NULL AS FIRM_DATE,
NULL AS GLOBAL_ATTRIBUTE20,
NULL AS ORDER_TYPE_LOOKUP_CODE,
NULL AS START_DATE,
NULL AS REFERENCE_NUM,
NULL AS MIN_RELEASE_AMOUNT,
NULL AS SUPPLIER_PART_AUXID,
NULL AS LAST_UPDATED_PROGRAM,
NULL AS GLOBAL_ATTRIBUTE17,
NULL AS GLOBAL_ATTRIBUTE18,
NULL AS GLOBAL_ATTRIBUTE15,
NULL AS QUANTITY_COMMITTED,
NULL AS CANCEL_FLAG,
NULL AS GLOBAL_ATTRIBUTE16,
NULL AS MAX_RETAINAGE_AMOUNT,
NULL AS GLOBAL_ATTRIBUTE13,
NULL AS GLOBAL_ATTRIBUTE14,
NULL AS BID_NUMBER,
NULL AS GLOBAL_ATTRIBUTE11,
NULL AS GLOBAL_ATTRIBUTE12,
NULL AS CLM_OPTION_INDICATOR,
NULL AS ATTRIBUTE15,
NULL AS TAXABLE_FLAG,
NULL AS GLOBAL_ATTRIBUTE19,
NULL AS CLOSED_REASON,
NULL AS QUANTITY,
NULL AS USER_HOLD_FLAG,
NULL AS SECONDARY_UOM,
NULL AS GLOBAL_ATTRIBUTE10,
NULL AS ITEM_DESCRIPTION,
NULL AS CONTRACTOR_LAST_NAME,
NULL AS SVC_AMOUNT_NOTIF_SENT,
NULL AS RECOUPMENT_RATE,
NULL AS CLM_BASE_LINE_NUM,
NULL AS CLM_IDC_TYPE,
NULL AS BASE_UOM,
NULL AS COST_CONSTRAINT,
NULL AS MARKET_PRICE,
NULL AS CREATED_BY,
NULL AS LAST_UPDATED_BY,
NULL AS TRANSACTION_REASON_CODE,
NULL AS CANCELLED_BY,
NULL AS LINE_REFERENCE_NUM,
NULL AS SECONDARY_QUANTITY,
NULL AS LINE_NUM_DISPLAY,
NULL AS CONTRACT_ID,
NULL AS HAZARD_CLASS_ID,
NULL AS CLM_OPTION_NUM,
NULL AS CONTRACT_TYPE,
NULL AS CLM_INFO_FLAG,
NULL AS AUCTION_HEADER_ID,
NULL AS ATTRIBUTE_CATEGORY,
NULL AS PROGRAM_APPLICATION_ID,
NULL AS GOVERNMENT_CONTEXT,
NULL AS LINE_TYPE_ID,
NULL AS UNIT_MEAS_LOOKUP_CODE,
NULL AS PREFERRED_GRADE,
NULL AS MATCHING_BASIS,
NULL AS REQUEST_ID,
NULL AS FIRM_STATUS_LOOKUP_CODE,
NULL AS MANUAL_PRICE_CHANGE_FLAG,
NULL AS BID_LINE_NUMBER,
NULL AS USER_DOCUMENT_STATUS,
NULL AS CLOSED_CODE,
NULL AS TYPE_1099,
NULL AS LIST_PRICE_PER_UNIT,
NULL AS NEGOTIATED_BY_PREPARER_FLAG,
NULL AS QC_GRADE,
NULL AS DRAFT_ID,
NULL AS QTY_RCV_TOLERANCE,
NULL AS TAX_ATTRIBUTE_UPDATE_CODE,
NULL AS PRICE_TYPE_LOOKUP_CODE,
NULL AS OVER_TOLERANCE_ERROR_FLAG,
NULL AS PURCHASE_BASIS,
NULL AS LAST_UPDATE_LOGIN,
NULL AS RETAINAGE_RATE,
NULL AS GLOBAL_ATTRIBUTE_CATEGORY,
NULL AS UN_NUMBER_ID,
NULL AS CLM_EXERCISED_FLAG,
NULL AS IP_CATEGORY_ID,
NULL AS PO_LINE_ID,
NULL AS PROGRAM_UPDATE_DATE,
NULL AS CLOSED_DATE,
NULL AS CANCEL_DATE,
NULL AS RETROACTIVE_DATE,
NULL AS CREATION_DATE,
NULL AS LAST_UPDATE_DATE,
NULL AS _FIVETRAN_DELETED,
NULL AS _FIVETRAN_ID,
NULL AS _FIVETRAN_SYNCED,
'1900-01-01'::TIMESTAMP AS PSA_LOAD_DTS,
'N' AS PSA_DELETE_IND,
CONVERT_TIMEZONE('UTC','1900-01-01'::TIMESTAMP) AS LOAD_DTS,
'USAZET.SNOWFLAKE.FBIN.DERIVED' AS REC_SRC,
DECODE(GR.VALUE, 0, 'GHOST RECORD-SYSTEM', -1, 'GHOST RECORD-nullkey-required', -2, 'GHOST RECORD-nullkey-optional') AS BKCC,
''::BINARY AS HASHDIFF
FROM
TABLE(strtok_split_to_table('0|-1|-2', '|')) AS GR
{% endif %}
