---- SRC LAYER ----
WITH
SRC_SITMFB         as ( SELECT * FROM {{ ref('v_psa_stg_plant_item__fib_ocf') }} as SRC 
                         {% if is_incremental() %}
                         WHERE SRC.LOAD_DTS > (SELECT DATEADD('HOUR', '-1', MAX(LOAD_DTS)) FROM {{this}})
                         {% endif %}  )

/*
SRC_SITMFB         as ( SELECT * FROM STAGING.v_psa_stg_item_base__fib_ocf )
*/
---- LOGIC LAYER ----

, LOGIC_SITMFB as (
    SELECT
        ITEM_HK
      , ITEM_NUMBER
      , INVENTORY_ITEM_ID
      , ORGANIZATION_ID
      , GLOBAL_ATTRIBUTE_20
      , CONSIGNED_FLAG
      , GLOBAL_ATTRIBUTE_DATE_5
      , IMPLEMENTATION_DATE
      , VARIABLE_LEAD_TIME
      , PLANNING_TIME_FENCE_CODE
      , SHRINKAGE_RATE
      , MATERIAL_BILLABLE_FLAG
      , PROCESS_YIELD_SUBINVENTORY
      , FIXED_DAYS_SUPPLY
      , ATO_FORECAST_CONTROL
      , EXPIRATION_ACTION_CODE
      , UNIT_OF_ISSUE
      , GLOBAL_ATTRIBUTE_19
      , CREATE_SUPPLY_FLAG
      , ATTRIBUTE_12
      , PICK_COMPONENTS_FLAG
      , ATTRIBUTE_8
      , EXCLUDE_FROM_BUDGET_FLAG
      , ATTRIBUTE_20
      , ATTRIBUTE_15
      , OPTION_SPECIFIC_SOURCED
      , EQUIPMENT_TYPE
      , DAYS_TGT_INV_WINDOW
      , ASSET_CREATION_CODE
      , ALT_ITEM_CODE
      , ATTRIBUTE_24
      , SALES_PRODUCT_SUB_TYPE
      , IB_ITEM_INSTANCE_CLASS
      , ACCEPTABLE_EARLY_DAYS
      , ATTRIBUTE_TIMESTAMP_3
      , REPLACEMENT_TYPE
      , SERV_BILLING_ENABLED_FLAG
      , ATTRIBUTE_30
      , ENABLE_IOT_FLAG
      , LIST_PRICE_PER_UNIT
      , ENGINEERED_ITEM_FLAG
      , CHECK_SHORTAGES_FLAG
      , CYCLE_COUNT_ENABLED_FLAG
      , TRADE_ITEM_DESCRIPTOR
      , MINIMUM_LICENSE_QUANTITY
      , PURCHASING_ITEM_FLAG
      , ATTRIBUTE_NUMBER_7
      , LEAD_TIME_LOT_SIZE
      , OVERCOMPLETION_TOLERANCE_VALUE
      , CHILD_LOT_PREFIX
      , COSTING_ENABLED_FLAG
      , INVENTORY_PLANNING_CODE
      , DAYS_TGT_INV_SUPPLY
      , EAM_ACTIVITY_TYPE_CODE
      , OVER_RETURN_TOLERANCE
      , UNIT_LENGTH
      , EXPENDITURE_TYPE_ID
      , PARENT_CHILD_GENERATION_FLAG
      , WIP_SUPPLY_LOCATOR_ID
      , PAYMENT_TERMS_ID
      , ATTRIBUTE_NUMBER_1
      , SOURCE_SUBINVENTORY
      , BACK_ORDERABLE_FLAG
      , REPLENISH_TO_ORDER_FLAG
      , DEFAULT_TEMPLATE_FLAG
      , ATP_COMPONENTS_FLAG
      , START_AUTO_LOT_NUMBER
      , SERVICEABLE_PRODUCT_FLAG
      , SUBSTITUTION_WINDOW_CODE
      , ACCEPTABLE_RATE_INCREASE
      , RETURN_INSPECTION_REQUIREMENT
      , FIXED_LOT_MULTIPLIER
      , EXPENSE_ACCOUNT
      , GLOBAL_ATTRIBUTE_14
      , MINIMUM_FILL_PERCENT
      , GLOBAL_ATTRIBUTE_3
      , SALES_ACCOUNT
      , OUTSOURCED_ASSEMBLY
      , ATTRIBUTE_25
      , MASTER_ORG_ID
      , GLOBAL_ATTRIBUTE_DATE_3
      , CREATED_FROM_ITEM_ID
      , THREAD_ID
      , INVOICE_ENABLED_FLAG
      , UNDER_COMPL_TOLERANCE_VALUE
      , CREATED_FROM_REVISION_ID
      , QTY_RCV_TOLERANCE
      , AUTO_REDUCE_MPS
      , PURCHASING_TAX_CODE
      , LOT_STATUS_ENABLED
      , AUTO_LOT_ALPHA_PREFIX
      , DEFAULT_GRADE
      , GLOBAL_ATTRIBUTE_10
      , DIMENSION_UOM_CODE
      , EVENT_FLAG
      , PLANNER_CODE
      , GLOBAL_ATTRIBUTE_DATE_2
      , VMI_FIXED_ORDER_QUANTITY
      , CURRENT_PHASE_ID
      , INVOICEABLE_ITEM_FLAG
      , ATTRIBUTE_26
      , PROCESS_QUALITY_ENABLED_FLAG
      , CONFIG_ORGS
      , OVERCOMPLETION_TOLERANCE_TYPE
      , DEFAULT_SERIAL_STATUS_ID
      , COMN_SUPPLY_PRJ_DEMAND_FLAG
      , CREATION_DATE
      , VMI_MINIMUM_UNITS
      , CURRENT_PHASE_CODE
      , DUAL_UOM_DEVIATION_LOW
      , COLLATERAL_FLAG
      , PICKING_RULE_ID
      , ATTRIBUTE_NUMBER_5
      , COMMS_ACTIVATION_REQD_FLAG
      , SHIP_MODEL_COMPLETE_FLAG
      , START_AUTO_SERIAL_NUMBER
      , UNIT_HEIGHT
      , SHELF_LIFE_CODE
      , TRACKING_QUANTITY_IND
      , MRP_CALCULATE_ATP_FLAG
      , OUTSIDE_PROCESS_SERVICE_FLAG
      , REQUEST_ID
      , SHIPPABLE_ITEM_FLAG
      , SERVICE_STARTING_DELAY
      , MRP_PLANNING_CODE
      , ELIGIBILITY_COMPATIBILITY_RULE
      , ASSET_CATEGORY_ID
      , PRIMARY_UOM_CODE
      , TAX_CODE
      , INDIVISIBLE_FLAG
      , JOB_DEFINITION_NAME
      , SERV_REQ_ENABLED_CODE
      , WH_UPDATE_DATE
      , ACD_TYPE
      , UNIT_VOLUME
      , GDSN_OUTBOUND_ENABLED_FLAG
      , ORDER_COST
      , WEIGHT_UOM_CODE
      , ALLOWED_UNITS_LOOKUP_CODE
      , DEMAND_PERIOD
      , VERSION_ID
      , SERIAL_NUMBER_CONTROL_CODE
      , ATTRIBUTE_23
      , PRODUCT_FAMILY_ITEM_ID
      , SERVICE_START_DELAY
      , CREATED_BY
      , OPERATION_SLACK_PENALTY
      , PLANNING_MAKE_BUY_CODE
      , PREPOSITION_POINT
      , CHARGE_PERIODICITY_CODE
      , UNIT_WEIGHT
      , DAYS_OF_COVER
      , INVOICE_CLOSE_TOLERANCE
      , REQUIRES_ITM_ASSOCIATION_FLAG
      , ROUNDING_FACTOR
      , FORCE_PURCHASE_LEAD_TIME_FLAG
      , ATTRIBUTE_5
      , CUM_MANUFACTURING_LEAD_TIME
      , SUBCONTRACTING_COMPONENT
      , ATTRIBUTE_7
      , MAXIMUM_LOAD_WEIGHT
      , POSTPROCESSING_LEAD_TIME
      , CSS_ENABLED_FLAG
      , NEGATIVE_MEASUREMENT_ERROR
      , LOT_MERGE_ENABLED
      , SUBSTITUTION_WINDOW_DAYS
      , BASE_ITEM_ID
      , ATTRIBUTE_27
      , GLOBAL_ATTRIBUTE_13
      , SECONDARY_UOM_CODE
      , ATTRIBUTE_DATE_4
      , CUMULATIVE_TOTAL_LEAD_TIME
      , ROUNDING_CONTROL_TYPE
      , GRADE_CONTROL_FLAG
      , REPAIR_YIELD
      , MASTER_ITEM_VERSION_ID
      , HARD_PEGGING_LEVEL
      , RESTRICT_LOCATORS_CODE
      , CONFIG_MATCH
      , ATTRIBUTE_CATEGORY
      , LOCATION_CONTROL_CODE
      , LOT_TRANSLATE_ENABLED
      , COMMS_NL_TRACKABLE_FLAG
      , ATTRIBUTE_NUMBER_9
      , DEMAND_TIME_FENCE_CODE
      , CONTINOUS_TRANSFER
      , PRICE_TOLERANCE_PERCENT
      , COVERAGE_SCHEDULE_ID
      , DOWNLOADABLE_FLAG
      , SALES_PRODUCT_TYPE
      , RESTRICT_SUBINVENTORIES_CODE
      , CREATE_SUPPLY_AFTER_DATE
      , REPETITIVE_PLANNING_FLAG
      , ATTRIBUTE_DATE_2
      , INVENTORY_ITEM_STATUS_CODE
      , WIP_SUPPLY_TYPE
      , ATTRIBUTE_TIMESTAMP_4
      , FIXED_ORDER_QUANTITY
      , GLOBAL_ATTRIBUTE_NUMBER_4
      , ATTRIBUTE_NUMBER_2
      , ATTRIBUTE_NUMBER_6
      , ASN_AUTOEXPIRE_FLAG
      , STYLE_ITEM_FLAG
      , POSITIVE_MEASUREMENT_ERROR
      , REQUIRES_FULFILLMENT_LOC_FLAG
      , CONTRACT_MANUFACTURING
      , ATTRIBUTE_16
      , RESERVABLE_TYPE
      , PACKAGING_STRING_ID
      , BULK_PICKED_FLAG
      , ATTRIBUTE_22
      , UNIT_WIDTH
      , MARKET_PRICE
      , ALLOW_SUBSTITUTE_RECEIPTS_FLAG
      , ELECTRONIC_FLAG
      , BUYER_ID
      , DAYS_LATE_RECEIPT_ALLOWED
      , EAM_ACT_NOTIFICATION_FLAG
      , ATTRIBUTE_TIMESTAMP_2
      , QTY_RCV_EXCEPTION_CODE
      , BACK_TO_BACK_ENABLED
      , ASSET_TRACKED_FLAG
      , DUAL_UOM_DEVIATION_HIGH
      , ALLOW_EXPRESS_DELIVERY_FLAG
      , SERVICE_START_TYPE_CODE
      , ALLOW_SUSPEND_FLAG
      , MATURITY_DAYS
      , ENABLE_GENEALOGY_TRACKING_FLAG
      , INVENTORY_ASSET_FLAG
      , EAM_ACTIVITY_CAUSE_CODE
      , ENGINEERING_ITEM_ID
      , DUAL_UOM_CONTROL
      , SAFETY_STOCK_PLANNING_METHOD
      , INTERNAL_ORDER_FLAG
      , SHELF_LIFE_DAYS
      , UNDER_COMPL_TOLERANCE_TYPE
      , GLOBAL_ATTRIBUTE_15
      , CHILD_LOT_FLAG
      , GLOBAL_ATTRIBUTE_DATE_4
      , GLOBAL_ATTRIBUTE_NUMBER_5
      , GLOBAL_ATTRIBUTE_9
      , FORECAST_HORIZON
      , RELEASE_TIME_FENCE_CODE
      , CHANGE_BIT_MAP
      , PROCESS_EXECUTION_ENABLED_FLAG
      , GLOBAL_ATTRIBUTE_6
      , ATTRIBUTE_28
      , ATTRIBUTE_TIMESTAMP_5
      , EAM_ITEM_TYPE
      , START_UPON_MILESTONE_CODE
      , RECEIPT_REQUIRED_FLAG
      , GLOBAL_ATTRIBUTE_17
      , LAST_SUBMITTED_NIR_ID
      , END_DATE_ACTIVE
      , ATTRIBUTE_3
      , ATP_RULE_ID
      , ALLOW_TERMINATE_FLAG
      , GLOBAL_ATTRIBUTE_11
      , ATTRIBUTE_18
      , END_ASSEMBLY_PEGGING_FLAG
      , EAM_ACT_SHUTDOWN_STATUS
      , SERVICE_DURATION_TYPE_CODE
      , ATTRIBUTE_2
      , CONFIG_MODEL_TYPE
      , ATTRIBUTE_NUMBER_8
      , EAM_ACTIVITY_SOURCE_CODE
      , PROGRAM_NAME
      , MRP_SAFETY_STOCK_CODE
      , STD_LOT_SIZE
      , CONVERGENCE
      , REPAIR_LEADTIME
      , RECIPE_ENABLED_FLAG
      , ONT_PRICING_QTY_SOURCE
      , VERSION_END_DATE
      , GLOBAL_ATTRIBUTE_NUMBER_1
      , CONTRACT_ITEM_TYPE_CODE
      , ATTRIBUTE_11
      , ACCEPTABLE_RATE_DECREASE
      , FINANCING_ALLOWED_FLAG
      , AUTO_CREATED_CONFIG_FLAG
      , EXPIRATION_ACTION_INTERVAL
      , MIN_MINMAX_QUANTITY
      , FULL_LEAD_TIME
      , GLOBAL_ATTRIBUTE_18
      , REVISION_QTY_CONTROL_CODE
      , CREATE_FIXED_ASSET
      , DEFAULT_LOT_STATUS_ID
      , QSC_SALES_PRODUCT_TYPE
      , UNDER_SHIPMENT_TOLERANCE
      , MUST_USE_APPROVED_VENDOR_FLAG
      , DRP_PLANNED_FLAG
      , FIXED_LEAD_TIME
      , VOLUME_UOM_CODE
      , DEFECT_TRACKING_ON_FLAG
      , SUMMARY_FLAG
      , ATTRIBUTE_1
      , ATTRIBUTE_NUMBER_4
      , UN_NUMBER_ID
      , DEMAND_TIME_FENCE_DAYS
      , RECEIVE_CLOSE_TOLERANCE
      , PLANNING_TIME_FENCE_DAYS
      , SO_AUTHORIZATION_FLAG
      , HAZARDOUS_MATERIAL_FLAG
      , APPROVAL_STATUS
      , RECOVERED_PART_DISP_CODE
      , CHILD_LOT_STARTING_NUMBER
      , CHANGE_LINE_ID
      , GLOBAL_ATTRIBUTE_8
      , PROCESS_SUPPLY_SUBINVENTORY
      , WEB_STATUS
      , SERVICE_DURATION
      , EFFECTIVITY_CONTROL
      , INVOICE_MATCH_OPTION
      , VMI_MINIMUM_DAYS
      , BOM_ITEM_TYPE
      , GLOBAL_ATTRIBUTE_4
      , DIVERGENCE
      , JOB_DEFINITION_PACKAGE
      , ATTRIBUTE_19
      , ALLOW_ITEM_DESC_UPDATE_FLAG
      , SOURCE_ORGANIZATION_ID
      , ATTRIBUTE_13
      , GLOBAL_ATTRIBUTE_NUMBER_2
      , ITEM_CATALOG_GROUP_ID
      , ITEM_OBJECT_TYPE
      , PLANNING_EXCEPTION_SET
      , ALLOW_UNORDERED_RECEIPTS_FLAG
      , DAYS_MAX_INV_WINDOW
      , ATTRIBUTE_29
      , PREPROCESSING_LEAD_TIME
      , ATTRIBUTE_NUMBER_3
      , INVENTORY_ITEM_FLAG
      , WIP_SUPPLY_SUBINVENTORY
      , LOT_CONTROL_CODE
      , RELEASE_TIME_FENCE_DAYS
      , STYLE_ITEM_ID
      , ATTRIBUTE_DATE_1
      , PLANNED_INV_POINT_FLAG
      , MINIMUM_ORDER_QUANTITY
      , RECEIVING_ROUTING_ID
      , CRITICAL_COMPONENT_FLAG
      , VMI_FORECAST_TYPE
      , PROGRAM_APP_NAME
      , CAS_NUMBER
      , START_DATE_ACTIVE
      , OUTSIDE_OPERATION_UOM_TYPE
      , LOT_SPLIT_ENABLED
      , CARRYING_COST
      , OVER_SHIPMENT_TOLERANCE
      , ATTRIBUTE_9
      , ALLOW_MAINTENANCE_ASSET_FLAG
      , PROCESS_COSTING_ENABLED_FLAG
      , SAFETY_STOCK_BUCKET_DAYS
      , ATTRIBUTE_TIMESTAMP_1
      , TAXABLE_FLAG
      , PURCHASING_ENABLED_FLAG
      , LAST_UPDATED_BY
      , ITEM_TYPE
      , DEFAULT_SO_SOURCE_TYPE
      , STOCK_ENABLED_FLAG
      , MAX_MINMAX_QUANTITY
      , DAYS_EARLY_RECEIPT_ALLOWED
      , RECEIPT_DAYS_EXCEPTION_CODE
      , TEMPLATE_ITEM_FLAG
      , DQ_SEMANTIC_KEY
      , DQ_REQUIRED_FLAG
      , VEHICLE_ITEM_FLAG
      , OBJECT_VERSION_NUMBER
      , MAXIMUM_ORDER_QUANTITY
      , BUILD_IN_WIP_FLAG
      , UNDER_RETURN_TOLERANCE
      , SERIAL_STATUS_ENABLED
      , LOT_DIVISIBLE_FLAG
      , GLOBAL_ATTRIBUTE_5
      , MATCH_APPROVAL_LEVEL
      , SO_TRANSACTIONS_FLAG
      , VERSION_START_DATE
      , INVOICING_RULE_ID
      , ATTRIBUTE_14
      , INVENTORY_ORGANIZATION_ID
      , CHILD_LOT_VALIDATION_FLAG
      , NEGOTIATION_REQUIRED_FLAG
      , SOURCE_TYPE
      , ATTRIBUTE_21
      , ACCOUNTING_RULE_ID
      , SERVICE_DURATION_PERIOD_CODE
      , RETURNABLE_FLAG
      , LAST_UPDATE_LOGIN
      , ORDERABLE_ON_WEB_FLAG
      , PRIMARY_IMAGE_URL
      , ATTRIBUTE_NUMBER_10
      , REPAIR_PROGRAM
      , DEFAULT_INCLUDE_IN_ROLLUP_FLAG
      , AUTO_SERIAL_ALPHA_PREFIX
      , DEFAULT_SHIPPING_ORG
      , CUSTOMER_ORDER_ENABLED_FLAG
      , RETEST_INTERVAL
      , INVENTORY_CARRY_PENALTY
      , ATTRIBUTE_4
      , ATTRIBUTE_DATE_5
      , GLOBAL_ATTRIBUTE_CATEGORY
      , LOT_SUBSTITUTION_ENABLED
      , ATTRIBUTE_DATE_3
      , PROCESS_SUPPLY_LOCATOR_ID
      , DAYS_MAX_INV_SUPPLY
      , ENFORCE_SHIP_TO_LOCATION_CODE
      , ASSET_CLASS
      , INTERNAL_ORDER_ENABLED_FLAG
      , COPY_LOT_ATTRIBUTE_FLAG
      , CONTAINER_TYPE_CODE
      , SECONDARY_DEFAULT_IND
      , ATTRIBUTE_17
      , GLOBAL_ATTRIBUTE_1
      , ENABLED_FLAG
      , GLOBAL_ATTRIBUTE_12
      , GLOBAL_ATTRIBUTE_16
      , GLOBAL_ATTRIBUTE_7
      , INTERNAL_VOLUME
      , INSPECTION_REQUIRED_FLAG
      , VMI_MAXIMUM_DAYS
      , VMI_MAXIMUM_UNITS
      , GLOBAL_ATTRIBUTE_DATE_1
      , PROCESS_YIELD_LOCATOR_ID
      , CUSTOMER_ORDER_FLAG
      , OUTSIDE_OPERATION_FLAG
      , OVERRUN_PERCENTAGE
      , CONTAINER_ITEM_FLAG
      , ATTRIBUTE_6
      , LAST_UPDATE_DATE
      , GLOBAL_ATTRIBUTE_2
      , HOLD_DAYS
      , EGO_MASTER_ITEMS_DFF_CTX
      , MTL_TRANSACTIONS_ENABLED_FLAG
      , REPAIR_TRANSACTION_CODE
      , COMPLETENESS_SCORE
      , MRP_SAFETY_STOCK_PERCENT
      , ATTRIBUTE_10
      , HAZARD_CLASS_ID
      , ATP_FLAG
      , GLOBAL_ATTRIBUTE_NUMBER_3
      , PARTS_SOURCING
      , ORDER_MODIFIER_START_QTY_FLAG
      , _FIVETRAN_DELETED
      , _FIVETRAN_SYNCED
      , PSA_DELETE_IND
      , PSA_LOAD_DTS
      , PSA_RECORD_SOURCE
      , LOAD_DTS
      , REC_SRC
      , HASHDIFF
    FROM SRC_SITMFB
)
---- RENAME LAYER ----

, RENAME_SITMFB as (
    SELECT
        ITEM_HK
      , ITEM_NUMBER
      , INVENTORY_ITEM_ID
      , ORGANIZATION_ID
      , GLOBAL_ATTRIBUTE_20
      , CONSIGNED_FLAG
      , GLOBAL_ATTRIBUTE_DATE_5
      , IMPLEMENTATION_DATE
      , VARIABLE_LEAD_TIME
      , PLANNING_TIME_FENCE_CODE
      , SHRINKAGE_RATE
      , MATERIAL_BILLABLE_FLAG
      , PROCESS_YIELD_SUBINVENTORY
      , FIXED_DAYS_SUPPLY
      , ATO_FORECAST_CONTROL
      , EXPIRATION_ACTION_CODE
      , UNIT_OF_ISSUE
      , GLOBAL_ATTRIBUTE_19
      , CREATE_SUPPLY_FLAG
      , ATTRIBUTE_12
      , PICK_COMPONENTS_FLAG
      , ATTRIBUTE_8
      , EXCLUDE_FROM_BUDGET_FLAG
      , ATTRIBUTE_20
      , ATTRIBUTE_15
      , OPTION_SPECIFIC_SOURCED
      , EQUIPMENT_TYPE
      , DAYS_TGT_INV_WINDOW
      , ASSET_CREATION_CODE
      , ALT_ITEM_CODE
      , ATTRIBUTE_24
      , SALES_PRODUCT_SUB_TYPE
      , IB_ITEM_INSTANCE_CLASS
      , ACCEPTABLE_EARLY_DAYS
      , ATTRIBUTE_TIMESTAMP_3
      , REPLACEMENT_TYPE
      , SERV_BILLING_ENABLED_FLAG
      , ATTRIBUTE_30
      , ENABLE_IOT_FLAG
      , LIST_PRICE_PER_UNIT
      , ENGINEERED_ITEM_FLAG
      , CHECK_SHORTAGES_FLAG
      , CYCLE_COUNT_ENABLED_FLAG
      , TRADE_ITEM_DESCRIPTOR
      , MINIMUM_LICENSE_QUANTITY
      , PURCHASING_ITEM_FLAG
      , ATTRIBUTE_NUMBER_7
      , LEAD_TIME_LOT_SIZE
      , OVERCOMPLETION_TOLERANCE_VALUE
      , CHILD_LOT_PREFIX
      , COSTING_ENABLED_FLAG
      , INVENTORY_PLANNING_CODE
      , DAYS_TGT_INV_SUPPLY
      , EAM_ACTIVITY_TYPE_CODE
      , OVER_RETURN_TOLERANCE
      , UNIT_LENGTH
      , EXPENDITURE_TYPE_ID
      , PARENT_CHILD_GENERATION_FLAG
      , WIP_SUPPLY_LOCATOR_ID
      , PAYMENT_TERMS_ID
      , ATTRIBUTE_NUMBER_1
      , SOURCE_SUBINVENTORY
      , BACK_ORDERABLE_FLAG
      , REPLENISH_TO_ORDER_FLAG
      , DEFAULT_TEMPLATE_FLAG
      , ATP_COMPONENTS_FLAG
      , START_AUTO_LOT_NUMBER
      , SERVICEABLE_PRODUCT_FLAG
      , SUBSTITUTION_WINDOW_CODE
      , ACCEPTABLE_RATE_INCREASE
      , RETURN_INSPECTION_REQUIREMENT
      , FIXED_LOT_MULTIPLIER
      , EXPENSE_ACCOUNT
      , GLOBAL_ATTRIBUTE_14
      , MINIMUM_FILL_PERCENT
      , GLOBAL_ATTRIBUTE_3
      , SALES_ACCOUNT
      , OUTSOURCED_ASSEMBLY
      , ATTRIBUTE_25
      , MASTER_ORG_ID
      , GLOBAL_ATTRIBUTE_DATE_3
      , CREATED_FROM_ITEM_ID
      , THREAD_ID
      , INVOICE_ENABLED_FLAG
      , UNDER_COMPL_TOLERANCE_VALUE
      , CREATED_FROM_REVISION_ID
      , QTY_RCV_TOLERANCE
      , AUTO_REDUCE_MPS
      , PURCHASING_TAX_CODE
      , LOT_STATUS_ENABLED
      , AUTO_LOT_ALPHA_PREFIX
      , DEFAULT_GRADE
      , GLOBAL_ATTRIBUTE_10
      , DIMENSION_UOM_CODE
      , EVENT_FLAG
      , PLANNER_CODE
      , GLOBAL_ATTRIBUTE_DATE_2
      , VMI_FIXED_ORDER_QUANTITY
      , CURRENT_PHASE_ID
      , INVOICEABLE_ITEM_FLAG
      , ATTRIBUTE_26
      , PROCESS_QUALITY_ENABLED_FLAG
      , CONFIG_ORGS
      , OVERCOMPLETION_TOLERANCE_TYPE
      , DEFAULT_SERIAL_STATUS_ID
      , COMN_SUPPLY_PRJ_DEMAND_FLAG
      , CREATION_DATE
      , VMI_MINIMUM_UNITS
      , CURRENT_PHASE_CODE
      , DUAL_UOM_DEVIATION_LOW
      , COLLATERAL_FLAG
      , PICKING_RULE_ID
      , ATTRIBUTE_NUMBER_5
      , COMMS_ACTIVATION_REQD_FLAG
      , SHIP_MODEL_COMPLETE_FLAG
      , START_AUTO_SERIAL_NUMBER
      , UNIT_HEIGHT
      , SHELF_LIFE_CODE
      , TRACKING_QUANTITY_IND
      , MRP_CALCULATE_ATP_FLAG
      , OUTSIDE_PROCESS_SERVICE_FLAG
      , REQUEST_ID
      , SHIPPABLE_ITEM_FLAG
      , SERVICE_STARTING_DELAY
      , MRP_PLANNING_CODE
      , ELIGIBILITY_COMPATIBILITY_RULE
      , ASSET_CATEGORY_ID
      , PRIMARY_UOM_CODE
      , TAX_CODE
      , INDIVISIBLE_FLAG
      , JOB_DEFINITION_NAME
      , SERV_REQ_ENABLED_CODE
      , WH_UPDATE_DATE
      , ACD_TYPE
      , UNIT_VOLUME
      , GDSN_OUTBOUND_ENABLED_FLAG
      , ORDER_COST
      , WEIGHT_UOM_CODE
      , ALLOWED_UNITS_LOOKUP_CODE
      , DEMAND_PERIOD
      , VERSION_ID
      , SERIAL_NUMBER_CONTROL_CODE
      , ATTRIBUTE_23
      , PRODUCT_FAMILY_ITEM_ID
      , SERVICE_START_DELAY
      , CREATED_BY
      , OPERATION_SLACK_PENALTY
      , PLANNING_MAKE_BUY_CODE
      , PREPOSITION_POINT
      , CHARGE_PERIODICITY_CODE
      , UNIT_WEIGHT
      , DAYS_OF_COVER
      , INVOICE_CLOSE_TOLERANCE
      , REQUIRES_ITM_ASSOCIATION_FLAG
      , ROUNDING_FACTOR
      , FORCE_PURCHASE_LEAD_TIME_FLAG
      , ATTRIBUTE_5
      , CUM_MANUFACTURING_LEAD_TIME
      , SUBCONTRACTING_COMPONENT
      , ATTRIBUTE_7
      , MAXIMUM_LOAD_WEIGHT
      , POSTPROCESSING_LEAD_TIME
      , CSS_ENABLED_FLAG
      , NEGATIVE_MEASUREMENT_ERROR
      , LOT_MERGE_ENABLED
      , SUBSTITUTION_WINDOW_DAYS
      , BASE_ITEM_ID
      , ATTRIBUTE_27
      , GLOBAL_ATTRIBUTE_13
      , SECONDARY_UOM_CODE
      , ATTRIBUTE_DATE_4
      , CUMULATIVE_TOTAL_LEAD_TIME
      , ROUNDING_CONTROL_TYPE
      , GRADE_CONTROL_FLAG
      , REPAIR_YIELD
      , MASTER_ITEM_VERSION_ID
      , HARD_PEGGING_LEVEL
      , RESTRICT_LOCATORS_CODE
      , CONFIG_MATCH
      , ATTRIBUTE_CATEGORY
      , LOCATION_CONTROL_CODE
      , LOT_TRANSLATE_ENABLED
      , COMMS_NL_TRACKABLE_FLAG
      , ATTRIBUTE_NUMBER_9
      , DEMAND_TIME_FENCE_CODE
      , CONTINOUS_TRANSFER
      , PRICE_TOLERANCE_PERCENT
      , COVERAGE_SCHEDULE_ID
      , DOWNLOADABLE_FLAG
      , SALES_PRODUCT_TYPE
      , RESTRICT_SUBINVENTORIES_CODE
      , CREATE_SUPPLY_AFTER_DATE
      , REPETITIVE_PLANNING_FLAG
      , ATTRIBUTE_DATE_2
      , INVENTORY_ITEM_STATUS_CODE
      , WIP_SUPPLY_TYPE
      , ATTRIBUTE_TIMESTAMP_4
      , FIXED_ORDER_QUANTITY
      , GLOBAL_ATTRIBUTE_NUMBER_4
      , ATTRIBUTE_NUMBER_2
      , ATTRIBUTE_NUMBER_6
      , ASN_AUTOEXPIRE_FLAG
      , STYLE_ITEM_FLAG
      , POSITIVE_MEASUREMENT_ERROR
      , REQUIRES_FULFILLMENT_LOC_FLAG
      , CONTRACT_MANUFACTURING
      , ATTRIBUTE_16
      , RESERVABLE_TYPE
      , PACKAGING_STRING_ID
      , BULK_PICKED_FLAG
      , ATTRIBUTE_22
      , UNIT_WIDTH
      , MARKET_PRICE
      , ALLOW_SUBSTITUTE_RECEIPTS_FLAG
      , ELECTRONIC_FLAG
      , BUYER_ID
      , DAYS_LATE_RECEIPT_ALLOWED
      , EAM_ACT_NOTIFICATION_FLAG
      , ATTRIBUTE_TIMESTAMP_2
      , QTY_RCV_EXCEPTION_CODE
      , BACK_TO_BACK_ENABLED
      , ASSET_TRACKED_FLAG
      , DUAL_UOM_DEVIATION_HIGH
      , ALLOW_EXPRESS_DELIVERY_FLAG
      , SERVICE_START_TYPE_CODE
      , ALLOW_SUSPEND_FLAG
      , MATURITY_DAYS
      , ENABLE_GENEALOGY_TRACKING_FLAG
      , INVENTORY_ASSET_FLAG
      , EAM_ACTIVITY_CAUSE_CODE
      , ENGINEERING_ITEM_ID
      , DUAL_UOM_CONTROL
      , SAFETY_STOCK_PLANNING_METHOD
      , INTERNAL_ORDER_FLAG
      , SHELF_LIFE_DAYS
      , UNDER_COMPL_TOLERANCE_TYPE
      , GLOBAL_ATTRIBUTE_15
      , CHILD_LOT_FLAG
      , GLOBAL_ATTRIBUTE_DATE_4
      , GLOBAL_ATTRIBUTE_NUMBER_5
      , GLOBAL_ATTRIBUTE_9
      , FORECAST_HORIZON
      , RELEASE_TIME_FENCE_CODE
      , CHANGE_BIT_MAP
      , PROCESS_EXECUTION_ENABLED_FLAG
      , GLOBAL_ATTRIBUTE_6
      , ATTRIBUTE_28
      , ATTRIBUTE_TIMESTAMP_5
      , EAM_ITEM_TYPE
      , START_UPON_MILESTONE_CODE
      , RECEIPT_REQUIRED_FLAG
      , GLOBAL_ATTRIBUTE_17
      , LAST_SUBMITTED_NIR_ID
      , END_DATE_ACTIVE
      , ATTRIBUTE_3
      , ATP_RULE_ID
      , ALLOW_TERMINATE_FLAG
      , GLOBAL_ATTRIBUTE_11
      , ATTRIBUTE_18
      , END_ASSEMBLY_PEGGING_FLAG
      , EAM_ACT_SHUTDOWN_STATUS
      , SERVICE_DURATION_TYPE_CODE
      , ATTRIBUTE_2
      , CONFIG_MODEL_TYPE
      , ATTRIBUTE_NUMBER_8
      , EAM_ACTIVITY_SOURCE_CODE
      , PROGRAM_NAME
      , MRP_SAFETY_STOCK_CODE
      , STD_LOT_SIZE
      , CONVERGENCE
      , REPAIR_LEADTIME
      , RECIPE_ENABLED_FLAG
      , ONT_PRICING_QTY_SOURCE
      , VERSION_END_DATE
      , GLOBAL_ATTRIBUTE_NUMBER_1
      , CONTRACT_ITEM_TYPE_CODE
      , ATTRIBUTE_11
      , ACCEPTABLE_RATE_DECREASE
      , FINANCING_ALLOWED_FLAG
      , AUTO_CREATED_CONFIG_FLAG
      , EXPIRATION_ACTION_INTERVAL
      , MIN_MINMAX_QUANTITY
      , FULL_LEAD_TIME
      , GLOBAL_ATTRIBUTE_18
      , REVISION_QTY_CONTROL_CODE
      , CREATE_FIXED_ASSET
      , DEFAULT_LOT_STATUS_ID
      , QSC_SALES_PRODUCT_TYPE
      , UNDER_SHIPMENT_TOLERANCE
      , MUST_USE_APPROVED_VENDOR_FLAG
      , DRP_PLANNED_FLAG
      , FIXED_LEAD_TIME
      , VOLUME_UOM_CODE
      , DEFECT_TRACKING_ON_FLAG
      , SUMMARY_FLAG
      , ATTRIBUTE_1
      , ATTRIBUTE_NUMBER_4
      , UN_NUMBER_ID
      , DEMAND_TIME_FENCE_DAYS
      , RECEIVE_CLOSE_TOLERANCE
      , PLANNING_TIME_FENCE_DAYS
      , SO_AUTHORIZATION_FLAG
      , HAZARDOUS_MATERIAL_FLAG
      , APPROVAL_STATUS
      , RECOVERED_PART_DISP_CODE
      , CHILD_LOT_STARTING_NUMBER
      , CHANGE_LINE_ID
      , GLOBAL_ATTRIBUTE_8
      , PROCESS_SUPPLY_SUBINVENTORY
      , WEB_STATUS
      , SERVICE_DURATION
      , EFFECTIVITY_CONTROL
      , INVOICE_MATCH_OPTION
      , VMI_MINIMUM_DAYS
      , BOM_ITEM_TYPE
      , GLOBAL_ATTRIBUTE_4
      , DIVERGENCE
      , JOB_DEFINITION_PACKAGE
      , ATTRIBUTE_19
      , ALLOW_ITEM_DESC_UPDATE_FLAG
      , SOURCE_ORGANIZATION_ID
      , ATTRIBUTE_13
      , GLOBAL_ATTRIBUTE_NUMBER_2
      , ITEM_CATALOG_GROUP_ID
      , ITEM_OBJECT_TYPE
      , PLANNING_EXCEPTION_SET
      , ALLOW_UNORDERED_RECEIPTS_FLAG
      , DAYS_MAX_INV_WINDOW
      , ATTRIBUTE_29
      , PREPROCESSING_LEAD_TIME
      , ATTRIBUTE_NUMBER_3
      , INVENTORY_ITEM_FLAG
      , WIP_SUPPLY_SUBINVENTORY
      , LOT_CONTROL_CODE
      , RELEASE_TIME_FENCE_DAYS
      , STYLE_ITEM_ID
      , ATTRIBUTE_DATE_1
      , PLANNED_INV_POINT_FLAG
      , MINIMUM_ORDER_QUANTITY
      , RECEIVING_ROUTING_ID
      , CRITICAL_COMPONENT_FLAG
      , VMI_FORECAST_TYPE
      , PROGRAM_APP_NAME
      , CAS_NUMBER
      , START_DATE_ACTIVE
      , OUTSIDE_OPERATION_UOM_TYPE
      , LOT_SPLIT_ENABLED
      , CARRYING_COST
      , OVER_SHIPMENT_TOLERANCE
      , ATTRIBUTE_9
      , ALLOW_MAINTENANCE_ASSET_FLAG
      , PROCESS_COSTING_ENABLED_FLAG
      , SAFETY_STOCK_BUCKET_DAYS
      , ATTRIBUTE_TIMESTAMP_1
      , TAXABLE_FLAG
      , PURCHASING_ENABLED_FLAG
      , LAST_UPDATED_BY
      , ITEM_TYPE
      , DEFAULT_SO_SOURCE_TYPE
      , STOCK_ENABLED_FLAG
      , MAX_MINMAX_QUANTITY
      , DAYS_EARLY_RECEIPT_ALLOWED
      , RECEIPT_DAYS_EXCEPTION_CODE
      , TEMPLATE_ITEM_FLAG
      , DQ_SEMANTIC_KEY
      , DQ_REQUIRED_FLAG
      , VEHICLE_ITEM_FLAG
      , OBJECT_VERSION_NUMBER
      , MAXIMUM_ORDER_QUANTITY
      , BUILD_IN_WIP_FLAG
      , UNDER_RETURN_TOLERANCE
      , SERIAL_STATUS_ENABLED
      , LOT_DIVISIBLE_FLAG
      , GLOBAL_ATTRIBUTE_5
      , MATCH_APPROVAL_LEVEL
      , SO_TRANSACTIONS_FLAG
      , VERSION_START_DATE
      , INVOICING_RULE_ID
      , ATTRIBUTE_14
      , INVENTORY_ORGANIZATION_ID
      , CHILD_LOT_VALIDATION_FLAG
      , NEGOTIATION_REQUIRED_FLAG
      , SOURCE_TYPE
      , ATTRIBUTE_21
      , ACCOUNTING_RULE_ID
      , SERVICE_DURATION_PERIOD_CODE
      , RETURNABLE_FLAG
      , LAST_UPDATE_LOGIN
      , ORDERABLE_ON_WEB_FLAG
      , PRIMARY_IMAGE_URL
      , ATTRIBUTE_NUMBER_10
      , REPAIR_PROGRAM
      , DEFAULT_INCLUDE_IN_ROLLUP_FLAG
      , AUTO_SERIAL_ALPHA_PREFIX
      , DEFAULT_SHIPPING_ORG
      , CUSTOMER_ORDER_ENABLED_FLAG
      , RETEST_INTERVAL
      , INVENTORY_CARRY_PENALTY
      , ATTRIBUTE_4
      , ATTRIBUTE_DATE_5
      , GLOBAL_ATTRIBUTE_CATEGORY
      , LOT_SUBSTITUTION_ENABLED
      , ATTRIBUTE_DATE_3
      , PROCESS_SUPPLY_LOCATOR_ID
      , DAYS_MAX_INV_SUPPLY
      , ENFORCE_SHIP_TO_LOCATION_CODE
      , ASSET_CLASS
      , INTERNAL_ORDER_ENABLED_FLAG
      , COPY_LOT_ATTRIBUTE_FLAG
      , CONTAINER_TYPE_CODE
      , SECONDARY_DEFAULT_IND
      , ATTRIBUTE_17
      , GLOBAL_ATTRIBUTE_1
      , ENABLED_FLAG
      , GLOBAL_ATTRIBUTE_12
      , GLOBAL_ATTRIBUTE_16
      , GLOBAL_ATTRIBUTE_7
      , INTERNAL_VOLUME
      , INSPECTION_REQUIRED_FLAG
      , VMI_MAXIMUM_DAYS
      , VMI_MAXIMUM_UNITS
      , GLOBAL_ATTRIBUTE_DATE_1
      , PROCESS_YIELD_LOCATOR_ID
      , CUSTOMER_ORDER_FLAG
      , OUTSIDE_OPERATION_FLAG
      , OVERRUN_PERCENTAGE
      , CONTAINER_ITEM_FLAG
      , ATTRIBUTE_6
      , LAST_UPDATE_DATE
      , GLOBAL_ATTRIBUTE_2
      , HOLD_DAYS
      , EGO_MASTER_ITEMS_DFF_CTX
      , MTL_TRANSACTIONS_ENABLED_FLAG
      , REPAIR_TRANSACTION_CODE
      , COMPLETENESS_SCORE
      , MRP_SAFETY_STOCK_PERCENT
      , ATTRIBUTE_10
      , HAZARD_CLASS_ID
      , ATP_FLAG
      , GLOBAL_ATTRIBUTE_NUMBER_3
      , PARTS_SOURCING
      , ORDER_MODIFIER_START_QTY_FLAG
      , _FIVETRAN_DELETED
      , _FIVETRAN_SYNCED
      , PSA_DELETE_IND
      , PSA_LOAD_DTS
      , PSA_RECORD_SOURCE
      , LOAD_DTS
      , REC_SRC
      , HASHDIFF
    FROM LOGIC_SITMFB
)
---- FILTER LAYER ----

, FILTER_SITMFB as (
    SELECT *
    FROM RENAME_SITMFB
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM FILTER_SITMFB
)

---- FINAL LAYER ----
SELECT
          ITEM_HK
        , ITEM_NUMBER
        , INVENTORY_ITEM_ID
        , ORGANIZATION_ID
        , GLOBAL_ATTRIBUTE_20
        , CONSIGNED_FLAG
        , GLOBAL_ATTRIBUTE_DATE_5
        , IMPLEMENTATION_DATE
        , VARIABLE_LEAD_TIME
        , PLANNING_TIME_FENCE_CODE
        , SHRINKAGE_RATE
        , MATERIAL_BILLABLE_FLAG
        , PROCESS_YIELD_SUBINVENTORY
        , FIXED_DAYS_SUPPLY
        , ATO_FORECAST_CONTROL
        , EXPIRATION_ACTION_CODE
        , UNIT_OF_ISSUE
        , GLOBAL_ATTRIBUTE_19
        , CREATE_SUPPLY_FLAG
        , ATTRIBUTE_12
        , PICK_COMPONENTS_FLAG
        , ATTRIBUTE_8
        , EXCLUDE_FROM_BUDGET_FLAG
        , ATTRIBUTE_20
        , ATTRIBUTE_15
        , OPTION_SPECIFIC_SOURCED
        , EQUIPMENT_TYPE
        , DAYS_TGT_INV_WINDOW
        , ASSET_CREATION_CODE
        , ALT_ITEM_CODE
        , ATTRIBUTE_24
        , SALES_PRODUCT_SUB_TYPE
        , IB_ITEM_INSTANCE_CLASS
        , ACCEPTABLE_EARLY_DAYS
        , ATTRIBUTE_TIMESTAMP_3
        , REPLACEMENT_TYPE
        , SERV_BILLING_ENABLED_FLAG
        , ATTRIBUTE_30
        , ENABLE_IOT_FLAG
        , LIST_PRICE_PER_UNIT
        , ENGINEERED_ITEM_FLAG
        , CHECK_SHORTAGES_FLAG
        , CYCLE_COUNT_ENABLED_FLAG
        , TRADE_ITEM_DESCRIPTOR
        , MINIMUM_LICENSE_QUANTITY
        , PURCHASING_ITEM_FLAG
        , ATTRIBUTE_NUMBER_7
        , LEAD_TIME_LOT_SIZE
        , OVERCOMPLETION_TOLERANCE_VALUE
        , CHILD_LOT_PREFIX
        , COSTING_ENABLED_FLAG
        , INVENTORY_PLANNING_CODE
        , DAYS_TGT_INV_SUPPLY
        , EAM_ACTIVITY_TYPE_CODE
        , OVER_RETURN_TOLERANCE
        , UNIT_LENGTH
        , EXPENDITURE_TYPE_ID
        , PARENT_CHILD_GENERATION_FLAG
        , WIP_SUPPLY_LOCATOR_ID
        , PAYMENT_TERMS_ID
        , ATTRIBUTE_NUMBER_1
        , SOURCE_SUBINVENTORY
        , BACK_ORDERABLE_FLAG
        , REPLENISH_TO_ORDER_FLAG
        , DEFAULT_TEMPLATE_FLAG
        , ATP_COMPONENTS_FLAG
        , START_AUTO_LOT_NUMBER
        , SERVICEABLE_PRODUCT_FLAG
        , SUBSTITUTION_WINDOW_CODE
        , ACCEPTABLE_RATE_INCREASE
        , RETURN_INSPECTION_REQUIREMENT
        , FIXED_LOT_MULTIPLIER
        , EXPENSE_ACCOUNT
        , GLOBAL_ATTRIBUTE_14
        , MINIMUM_FILL_PERCENT
        , GLOBAL_ATTRIBUTE_3
        , SALES_ACCOUNT
        , OUTSOURCED_ASSEMBLY
        , ATTRIBUTE_25
        , MASTER_ORG_ID
        , GLOBAL_ATTRIBUTE_DATE_3
        , CREATED_FROM_ITEM_ID
        , THREAD_ID
        , INVOICE_ENABLED_FLAG
        , UNDER_COMPL_TOLERANCE_VALUE
        , CREATED_FROM_REVISION_ID
        , QTY_RCV_TOLERANCE
        , AUTO_REDUCE_MPS
        , PURCHASING_TAX_CODE
        , LOT_STATUS_ENABLED
        , AUTO_LOT_ALPHA_PREFIX
        , DEFAULT_GRADE
        , GLOBAL_ATTRIBUTE_10
        , DIMENSION_UOM_CODE
        , EVENT_FLAG
        , PLANNER_CODE
        , GLOBAL_ATTRIBUTE_DATE_2
        , VMI_FIXED_ORDER_QUANTITY
        , CURRENT_PHASE_ID
        , INVOICEABLE_ITEM_FLAG
        , ATTRIBUTE_26
        , PROCESS_QUALITY_ENABLED_FLAG
        , CONFIG_ORGS
        , OVERCOMPLETION_TOLERANCE_TYPE
        , DEFAULT_SERIAL_STATUS_ID
        , COMN_SUPPLY_PRJ_DEMAND_FLAG
        , CREATION_DATE
        , VMI_MINIMUM_UNITS
        , CURRENT_PHASE_CODE
        , DUAL_UOM_DEVIATION_LOW
        , COLLATERAL_FLAG
        , PICKING_RULE_ID
        , ATTRIBUTE_NUMBER_5
        , COMMS_ACTIVATION_REQD_FLAG
        , SHIP_MODEL_COMPLETE_FLAG
        , START_AUTO_SERIAL_NUMBER
        , UNIT_HEIGHT
        , SHELF_LIFE_CODE
        , TRACKING_QUANTITY_IND
        , MRP_CALCULATE_ATP_FLAG
        , OUTSIDE_PROCESS_SERVICE_FLAG
        , REQUEST_ID
        , SHIPPABLE_ITEM_FLAG
        , SERVICE_STARTING_DELAY
        , MRP_PLANNING_CODE
        , ELIGIBILITY_COMPATIBILITY_RULE
        , ASSET_CATEGORY_ID
        , PRIMARY_UOM_CODE
        , TAX_CODE
        , INDIVISIBLE_FLAG
        , JOB_DEFINITION_NAME
        , SERV_REQ_ENABLED_CODE
        , WH_UPDATE_DATE
        , ACD_TYPE
        , UNIT_VOLUME
        , GDSN_OUTBOUND_ENABLED_FLAG
        , ORDER_COST
        , WEIGHT_UOM_CODE
        , ALLOWED_UNITS_LOOKUP_CODE
        , DEMAND_PERIOD
        , VERSION_ID
        , SERIAL_NUMBER_CONTROL_CODE
        , ATTRIBUTE_23
        , PRODUCT_FAMILY_ITEM_ID
        , SERVICE_START_DELAY
        , CREATED_BY
        , OPERATION_SLACK_PENALTY
        , PLANNING_MAKE_BUY_CODE
        , PREPOSITION_POINT
        , CHARGE_PERIODICITY_CODE
        , UNIT_WEIGHT
        , DAYS_OF_COVER
        , INVOICE_CLOSE_TOLERANCE
        , REQUIRES_ITM_ASSOCIATION_FLAG
        , ROUNDING_FACTOR
        , FORCE_PURCHASE_LEAD_TIME_FLAG
        , ATTRIBUTE_5
        , CUM_MANUFACTURING_LEAD_TIME
        , SUBCONTRACTING_COMPONENT
        , ATTRIBUTE_7
        , MAXIMUM_LOAD_WEIGHT
        , POSTPROCESSING_LEAD_TIME
        , CSS_ENABLED_FLAG
        , NEGATIVE_MEASUREMENT_ERROR
        , LOT_MERGE_ENABLED
        , SUBSTITUTION_WINDOW_DAYS
        , BASE_ITEM_ID
        , ATTRIBUTE_27
        , GLOBAL_ATTRIBUTE_13
        , SECONDARY_UOM_CODE
        , ATTRIBUTE_DATE_4
        , CUMULATIVE_TOTAL_LEAD_TIME
        , ROUNDING_CONTROL_TYPE
        , GRADE_CONTROL_FLAG
        , REPAIR_YIELD
        , MASTER_ITEM_VERSION_ID
        , HARD_PEGGING_LEVEL
        , RESTRICT_LOCATORS_CODE
        , CONFIG_MATCH
        , ATTRIBUTE_CATEGORY
        , LOCATION_CONTROL_CODE
        , LOT_TRANSLATE_ENABLED
        , COMMS_NL_TRACKABLE_FLAG
        , ATTRIBUTE_NUMBER_9
        , DEMAND_TIME_FENCE_CODE
        , CONTINOUS_TRANSFER
        , PRICE_TOLERANCE_PERCENT
        , COVERAGE_SCHEDULE_ID
        , DOWNLOADABLE_FLAG
        , SALES_PRODUCT_TYPE
        , RESTRICT_SUBINVENTORIES_CODE
        , CREATE_SUPPLY_AFTER_DATE
        , REPETITIVE_PLANNING_FLAG
        , ATTRIBUTE_DATE_2
        , INVENTORY_ITEM_STATUS_CODE
        , WIP_SUPPLY_TYPE
        , ATTRIBUTE_TIMESTAMP_4
        , FIXED_ORDER_QUANTITY
        , GLOBAL_ATTRIBUTE_NUMBER_4
        , ATTRIBUTE_NUMBER_2
        , ATTRIBUTE_NUMBER_6
        , ASN_AUTOEXPIRE_FLAG
        , STYLE_ITEM_FLAG
        , POSITIVE_MEASUREMENT_ERROR
        , REQUIRES_FULFILLMENT_LOC_FLAG
        , CONTRACT_MANUFACTURING
        , ATTRIBUTE_16
        , RESERVABLE_TYPE
        , PACKAGING_STRING_ID
        , BULK_PICKED_FLAG
        , ATTRIBUTE_22
        , UNIT_WIDTH
        , MARKET_PRICE
        , ALLOW_SUBSTITUTE_RECEIPTS_FLAG
        , ELECTRONIC_FLAG
        , BUYER_ID
        , DAYS_LATE_RECEIPT_ALLOWED
        , EAM_ACT_NOTIFICATION_FLAG
        , ATTRIBUTE_TIMESTAMP_2
        , QTY_RCV_EXCEPTION_CODE
        , BACK_TO_BACK_ENABLED
        , ASSET_TRACKED_FLAG
        , DUAL_UOM_DEVIATION_HIGH
        , ALLOW_EXPRESS_DELIVERY_FLAG
        , SERVICE_START_TYPE_CODE
        , ALLOW_SUSPEND_FLAG
        , MATURITY_DAYS
        , ENABLE_GENEALOGY_TRACKING_FLAG
        , INVENTORY_ASSET_FLAG
        , EAM_ACTIVITY_CAUSE_CODE
        , ENGINEERING_ITEM_ID
        , DUAL_UOM_CONTROL
        , SAFETY_STOCK_PLANNING_METHOD
        , INTERNAL_ORDER_FLAG
        , SHELF_LIFE_DAYS
        , UNDER_COMPL_TOLERANCE_TYPE
        , GLOBAL_ATTRIBUTE_15
        , CHILD_LOT_FLAG
        , GLOBAL_ATTRIBUTE_DATE_4
        , GLOBAL_ATTRIBUTE_NUMBER_5
        , GLOBAL_ATTRIBUTE_9
        , FORECAST_HORIZON
        , RELEASE_TIME_FENCE_CODE
        , CHANGE_BIT_MAP
        , PROCESS_EXECUTION_ENABLED_FLAG
        , GLOBAL_ATTRIBUTE_6
        , ATTRIBUTE_28
        , ATTRIBUTE_TIMESTAMP_5
        , EAM_ITEM_TYPE
        , START_UPON_MILESTONE_CODE
        , RECEIPT_REQUIRED_FLAG
        , GLOBAL_ATTRIBUTE_17
        , LAST_SUBMITTED_NIR_ID
        , END_DATE_ACTIVE
        , ATTRIBUTE_3
        , ATP_RULE_ID
        , ALLOW_TERMINATE_FLAG
        , GLOBAL_ATTRIBUTE_11
        , ATTRIBUTE_18
        , END_ASSEMBLY_PEGGING_FLAG
        , EAM_ACT_SHUTDOWN_STATUS
        , SERVICE_DURATION_TYPE_CODE
        , ATTRIBUTE_2
        , CONFIG_MODEL_TYPE
        , ATTRIBUTE_NUMBER_8
        , EAM_ACTIVITY_SOURCE_CODE
        , PROGRAM_NAME
        , MRP_SAFETY_STOCK_CODE
        , STD_LOT_SIZE
        , CONVERGENCE
        , REPAIR_LEADTIME
        , RECIPE_ENABLED_FLAG
        , ONT_PRICING_QTY_SOURCE
        , VERSION_END_DATE
        , GLOBAL_ATTRIBUTE_NUMBER_1
        , CONTRACT_ITEM_TYPE_CODE
        , ATTRIBUTE_11
        , ACCEPTABLE_RATE_DECREASE
        , FINANCING_ALLOWED_FLAG
        , AUTO_CREATED_CONFIG_FLAG
        , EXPIRATION_ACTION_INTERVAL
        , MIN_MINMAX_QUANTITY
        , FULL_LEAD_TIME
        , GLOBAL_ATTRIBUTE_18
        , REVISION_QTY_CONTROL_CODE
        , CREATE_FIXED_ASSET
        , DEFAULT_LOT_STATUS_ID
        , QSC_SALES_PRODUCT_TYPE
        , UNDER_SHIPMENT_TOLERANCE
        , MUST_USE_APPROVED_VENDOR_FLAG
        , DRP_PLANNED_FLAG
        , FIXED_LEAD_TIME
        , VOLUME_UOM_CODE
        , DEFECT_TRACKING_ON_FLAG
        , SUMMARY_FLAG
        , ATTRIBUTE_1
        , ATTRIBUTE_NUMBER_4
        , UN_NUMBER_ID
        , DEMAND_TIME_FENCE_DAYS
        , RECEIVE_CLOSE_TOLERANCE
        , PLANNING_TIME_FENCE_DAYS
        , SO_AUTHORIZATION_FLAG
        , HAZARDOUS_MATERIAL_FLAG
        , APPROVAL_STATUS
        , RECOVERED_PART_DISP_CODE
        , CHILD_LOT_STARTING_NUMBER
        , CHANGE_LINE_ID
        , GLOBAL_ATTRIBUTE_8
        , PROCESS_SUPPLY_SUBINVENTORY
        , WEB_STATUS
        , SERVICE_DURATION
        , EFFECTIVITY_CONTROL
        , INVOICE_MATCH_OPTION
        , VMI_MINIMUM_DAYS
        , BOM_ITEM_TYPE
        , GLOBAL_ATTRIBUTE_4
        , DIVERGENCE
        , JOB_DEFINITION_PACKAGE
        , ATTRIBUTE_19
        , ALLOW_ITEM_DESC_UPDATE_FLAG
        , SOURCE_ORGANIZATION_ID
        , ATTRIBUTE_13
        , GLOBAL_ATTRIBUTE_NUMBER_2
        , ITEM_CATALOG_GROUP_ID
        , ITEM_OBJECT_TYPE
        , PLANNING_EXCEPTION_SET
        , ALLOW_UNORDERED_RECEIPTS_FLAG
        , DAYS_MAX_INV_WINDOW
        , ATTRIBUTE_29
        , PREPROCESSING_LEAD_TIME
        , ATTRIBUTE_NUMBER_3
        , INVENTORY_ITEM_FLAG
        , WIP_SUPPLY_SUBINVENTORY
        , LOT_CONTROL_CODE
        , RELEASE_TIME_FENCE_DAYS
        , STYLE_ITEM_ID
        , ATTRIBUTE_DATE_1
        , PLANNED_INV_POINT_FLAG
        , MINIMUM_ORDER_QUANTITY
        , RECEIVING_ROUTING_ID
        , CRITICAL_COMPONENT_FLAG
        , VMI_FORECAST_TYPE
        , PROGRAM_APP_NAME
        , CAS_NUMBER
        , START_DATE_ACTIVE
        , OUTSIDE_OPERATION_UOM_TYPE
        , LOT_SPLIT_ENABLED
        , CARRYING_COST
        , OVER_SHIPMENT_TOLERANCE
        , ATTRIBUTE_9
        , ALLOW_MAINTENANCE_ASSET_FLAG
        , PROCESS_COSTING_ENABLED_FLAG
        , SAFETY_STOCK_BUCKET_DAYS
        , ATTRIBUTE_TIMESTAMP_1
        , TAXABLE_FLAG
        , PURCHASING_ENABLED_FLAG
        , LAST_UPDATED_BY
        , ITEM_TYPE
        , DEFAULT_SO_SOURCE_TYPE
        , STOCK_ENABLED_FLAG
        , MAX_MINMAX_QUANTITY
        , DAYS_EARLY_RECEIPT_ALLOWED
        , RECEIPT_DAYS_EXCEPTION_CODE
        , TEMPLATE_ITEM_FLAG
        , DQ_SEMANTIC_KEY
        , DQ_REQUIRED_FLAG
        , VEHICLE_ITEM_FLAG
        , OBJECT_VERSION_NUMBER
        , MAXIMUM_ORDER_QUANTITY
        , BUILD_IN_WIP_FLAG
        , UNDER_RETURN_TOLERANCE
        , SERIAL_STATUS_ENABLED
        , LOT_DIVISIBLE_FLAG
        , GLOBAL_ATTRIBUTE_5
        , MATCH_APPROVAL_LEVEL
        , SO_TRANSACTIONS_FLAG
        , VERSION_START_DATE
        , INVOICING_RULE_ID
        , ATTRIBUTE_14
        , INVENTORY_ORGANIZATION_ID
        , CHILD_LOT_VALIDATION_FLAG
        , NEGOTIATION_REQUIRED_FLAG
        , SOURCE_TYPE
        , ATTRIBUTE_21
        , ACCOUNTING_RULE_ID
        , SERVICE_DURATION_PERIOD_CODE
        , RETURNABLE_FLAG
        , LAST_UPDATE_LOGIN
        , ORDERABLE_ON_WEB_FLAG
        , PRIMARY_IMAGE_URL
        , ATTRIBUTE_NUMBER_10
        , REPAIR_PROGRAM
        , DEFAULT_INCLUDE_IN_ROLLUP_FLAG
        , AUTO_SERIAL_ALPHA_PREFIX
        , DEFAULT_SHIPPING_ORG
        , CUSTOMER_ORDER_ENABLED_FLAG
        , RETEST_INTERVAL
        , INVENTORY_CARRY_PENALTY
        , ATTRIBUTE_4
        , ATTRIBUTE_DATE_5
        , GLOBAL_ATTRIBUTE_CATEGORY
        , LOT_SUBSTITUTION_ENABLED
        , ATTRIBUTE_DATE_3
        , PROCESS_SUPPLY_LOCATOR_ID
        , DAYS_MAX_INV_SUPPLY
        , ENFORCE_SHIP_TO_LOCATION_CODE
        , ASSET_CLASS
        , INTERNAL_ORDER_ENABLED_FLAG
        , COPY_LOT_ATTRIBUTE_FLAG
        , CONTAINER_TYPE_CODE
        , SECONDARY_DEFAULT_IND
        , ATTRIBUTE_17
        , GLOBAL_ATTRIBUTE_1
        , ENABLED_FLAG
        , GLOBAL_ATTRIBUTE_12
        , GLOBAL_ATTRIBUTE_16
        , GLOBAL_ATTRIBUTE_7
        , INTERNAL_VOLUME
        , INSPECTION_REQUIRED_FLAG
        , VMI_MAXIMUM_DAYS
        , VMI_MAXIMUM_UNITS
        , GLOBAL_ATTRIBUTE_DATE_1
        , PROCESS_YIELD_LOCATOR_ID
        , CUSTOMER_ORDER_FLAG
        , OUTSIDE_OPERATION_FLAG
        , OVERRUN_PERCENTAGE
        , CONTAINER_ITEM_FLAG
        , ATTRIBUTE_6
        , LAST_UPDATE_DATE
        , GLOBAL_ATTRIBUTE_2
        , HOLD_DAYS
        , EGO_MASTER_ITEMS_DFF_CTX
        , MTL_TRANSACTIONS_ENABLED_FLAG
        , REPAIR_TRANSACTION_CODE
        , COMPLETENESS_SCORE
        , MRP_SAFETY_STOCK_PERCENT
        , ATTRIBUTE_10
        , HAZARD_CLASS_ID
        , ATP_FLAG
        , GLOBAL_ATTRIBUTE_NUMBER_3
        , PARTS_SOURCING
        , ORDER_MODIFIER_START_QTY_FLAG
        , _FIVETRAN_DELETED
        , _FIVETRAN_SYNCED
        , PSA_DELETE_IND
        , PSA_LOAD_DTS
        , PSA_RECORD_SOURCE
        , LOAD_DTS
        , REC_SRC
        , HASHDIFF
FROM JOIN_RESULT
{% if is_incremental() %}
WHERE NOT EXISTS (
    SELECT 1 
    FROM {{ this }} existing
    WHERE existing.ITEM_HK= JOIN_RESULT.ITEM_HK
     AND existing.INVENTORY_ITEM_ID = JOIN_RESULT.INVENTORY_ITEM_ID 
     AND existing.ORGANIZATION_ID = JOIN_RESULT.ORGANIZATION_ID 
    AND existing.HASHDIFF = JOIN_RESULT.HASHDIFF
)
{% endif %} 
{% if not is_incremental() %}
/*the following qualify is to restrict multiple loads of touched records during the initial build. Ex: multiple row per hk, hashdiff */
qualify 1= row_number()over(partition by ITEM_HK, INVENTORY_ITEM_ID ,ORGANIZATION_ID ,HASHDIFF order by PSA_LOAD_DTS)
union all
    SELECT        MD5_BINARY(GR.VALUE) AS ITEM_HK
       , GR.VALUE as ITEM_NUMBER
    , GR.VALUE::NUMBER as INVENTORY_ITEM_ID
    , GR.VALUE::NUMBER as ORGANIZATION_ID
    , null as GLOBAL_ATTRIBUTE_20
    , null as CONSIGNED_FLAG
    , null as GLOBAL_ATTRIBUTE_DATE_5
    , null as IMPLEMENTATION_DATE
    , null as VARIABLE_LEAD_TIME
    , null as PLANNING_TIME_FENCE_CODE
    , null as SHRINKAGE_RATE
    , null as MATERIAL_BILLABLE_FLAG
    , null as PROCESS_YIELD_SUBINVENTORY
    , null as FIXED_DAYS_SUPPLY
    , null as ATO_FORECAST_CONTROL
    , null as EXPIRATION_ACTION_CODE
    , null as UNIT_OF_ISSUE
    , null as GLOBAL_ATTRIBUTE_19
    , null as CREATE_SUPPLY_FLAG
    , null as ATTRIBUTE_12
    , null as PICK_COMPONENTS_FLAG
    , null as ATTRIBUTE_8
    , null as EXCLUDE_FROM_BUDGET_FLAG
    , null as ATTRIBUTE_20
    , null as ATTRIBUTE_15
    , null as OPTION_SPECIFIC_SOURCED
    , null as EQUIPMENT_TYPE
    , null as DAYS_TGT_INV_WINDOW
    , null as ASSET_CREATION_CODE
    , null as ALT_ITEM_CODE
    , null as ATTRIBUTE_24
    , null as SALES_PRODUCT_SUB_TYPE
    , null as IB_ITEM_INSTANCE_CLASS
    , null as ACCEPTABLE_EARLY_DAYS
    , null as ATTRIBUTE_TIMESTAMP_3
    , null as REPLACEMENT_TYPE
    , null as SERV_BILLING_ENABLED_FLAG
    , null as ATTRIBUTE_30
    , null as ENABLE_IOT_FLAG
    , null as LIST_PRICE_PER_UNIT
    , null as ENGINEERED_ITEM_FLAG
    , null as CHECK_SHORTAGES_FLAG
    , null as CYCLE_COUNT_ENABLED_FLAG
    , null as TRADE_ITEM_DESCRIPTOR
    , null as MINIMUM_LICENSE_QUANTITY
    , null as PURCHASING_ITEM_FLAG
    , null as ATTRIBUTE_NUMBER_7
    , null as LEAD_TIME_LOT_SIZE
    , null as OVERCOMPLETION_TOLERANCE_VALUE
    , null as CHILD_LOT_PREFIX
    , null as COSTING_ENABLED_FLAG
    , null as INVENTORY_PLANNING_CODE
    , null as DAYS_TGT_INV_SUPPLY
    , null as EAM_ACTIVITY_TYPE_CODE
    , null as OVER_RETURN_TOLERANCE
    , null as UNIT_LENGTH
    , null as EXPENDITURE_TYPE_ID
    , null as PARENT_CHILD_GENERATION_FLAG
    , null as WIP_SUPPLY_LOCATOR_ID
    , null as PAYMENT_TERMS_ID
    , null as ATTRIBUTE_NUMBER_1
    , null as SOURCE_SUBINVENTORY
    , null as BACK_ORDERABLE_FLAG
    , null as REPLENISH_TO_ORDER_FLAG
    , null as DEFAULT_TEMPLATE_FLAG
    , null as ATP_COMPONENTS_FLAG
    , null as START_AUTO_LOT_NUMBER
    , null as SERVICEABLE_PRODUCT_FLAG
    , null as SUBSTITUTION_WINDOW_CODE
    , null as ACCEPTABLE_RATE_INCREASE
    , null as RETURN_INSPECTION_REQUIREMENT
    , null as FIXED_LOT_MULTIPLIER
    , null as EXPENSE_ACCOUNT
    , null as GLOBAL_ATTRIBUTE_14
    , null as MINIMUM_FILL_PERCENT
    , null as GLOBAL_ATTRIBUTE_3
    , null as SALES_ACCOUNT
    , null as OUTSOURCED_ASSEMBLY
    , null as ATTRIBUTE_25
    , null as MASTER_ORG_ID
    , null as GLOBAL_ATTRIBUTE_DATE_3
    , null as CREATED_FROM_ITEM_ID
    , null as THREAD_ID
    , null as INVOICE_ENABLED_FLAG
    , null as UNDER_COMPL_TOLERANCE_VALUE
    , null as CREATED_FROM_REVISION_ID
    , null as QTY_RCV_TOLERANCE
    , null as AUTO_REDUCE_MPS
    , null as PURCHASING_TAX_CODE
    , null as LOT_STATUS_ENABLED
    , null as AUTO_LOT_ALPHA_PREFIX
    , null as DEFAULT_GRADE
    , null as GLOBAL_ATTRIBUTE_10
    , null as DIMENSION_UOM_CODE
    , null as EVENT_FLAG
    , null as PLANNER_CODE
    , null as GLOBAL_ATTRIBUTE_DATE_2
    , null as VMI_FIXED_ORDER_QUANTITY
    , null as CURRENT_PHASE_ID
    , null as INVOICEABLE_ITEM_FLAG
    , null as ATTRIBUTE_26
    , null as PROCESS_QUALITY_ENABLED_FLAG
    , null as CONFIG_ORGS
    , null as OVERCOMPLETION_TOLERANCE_TYPE
    , null as DEFAULT_SERIAL_STATUS_ID
    , null as COMN_SUPPLY_PRJ_DEMAND_FLAG
    , null as CREATION_DATE
    , null as VMI_MINIMUM_UNITS
    , null as CURRENT_PHASE_CODE
    , null as DUAL_UOM_DEVIATION_LOW
    , null as COLLATERAL_FLAG
    , null as PICKING_RULE_ID
    , null as ATTRIBUTE_NUMBER_5
    , null as COMMS_ACTIVATION_REQD_FLAG
    , null as SHIP_MODEL_COMPLETE_FLAG
    , null as START_AUTO_SERIAL_NUMBER
    , null as UNIT_HEIGHT
    , null as SHELF_LIFE_CODE
    , null as TRACKING_QUANTITY_IND
    , null as MRP_CALCULATE_ATP_FLAG
    , null as OUTSIDE_PROCESS_SERVICE_FLAG
    , null as REQUEST_ID
    , null as SHIPPABLE_ITEM_FLAG
    , null as SERVICE_STARTING_DELAY
    , null as MRP_PLANNING_CODE
    , null as ELIGIBILITY_COMPATIBILITY_RULE
    , null as ASSET_CATEGORY_ID
    , null as PRIMARY_UOM_CODE
    , null as TAX_CODE
    , null as INDIVISIBLE_FLAG
    , null as JOB_DEFINITION_NAME
    , null as SERV_REQ_ENABLED_CODE
    , null as WH_UPDATE_DATE
    , null as ACD_TYPE
    , null as UNIT_VOLUME
    , null as GDSN_OUTBOUND_ENABLED_FLAG
    , null as ORDER_COST
    , null as WEIGHT_UOM_CODE
    , null as ALLOWED_UNITS_LOOKUP_CODE
    , null as DEMAND_PERIOD
    , null as VERSION_ID
    , null as SERIAL_NUMBER_CONTROL_CODE
    , null as ATTRIBUTE_23
    , null as PRODUCT_FAMILY_ITEM_ID
    , null as SERVICE_START_DELAY
    , null as CREATED_BY
    , null as OPERATION_SLACK_PENALTY
    , null as PLANNING_MAKE_BUY_CODE
    , null as PREPOSITION_POINT
    , null as CHARGE_PERIODICITY_CODE
    , null as UNIT_WEIGHT
    , null as DAYS_OF_COVER
    , null as INVOICE_CLOSE_TOLERANCE
    , null as REQUIRES_ITM_ASSOCIATION_FLAG
    , null as ROUNDING_FACTOR
    , null as FORCE_PURCHASE_LEAD_TIME_FLAG
    , null as ATTRIBUTE_5
    , null as CUM_MANUFACTURING_LEAD_TIME
    , null as SUBCONTRACTING_COMPONENT
    , null as ATTRIBUTE_7
    , null as MAXIMUM_LOAD_WEIGHT
    , null as POSTPROCESSING_LEAD_TIME
    , null as CSS_ENABLED_FLAG
    , null as NEGATIVE_MEASUREMENT_ERROR
    , null as LOT_MERGE_ENABLED
    , null as SUBSTITUTION_WINDOW_DAYS
    , null as BASE_ITEM_ID
    , null as ATTRIBUTE_27
    , null as GLOBAL_ATTRIBUTE_13
    , null as SECONDARY_UOM_CODE
    , null as ATTRIBUTE_DATE_4
    , null as CUMULATIVE_TOTAL_LEAD_TIME
    , null as ROUNDING_CONTROL_TYPE
    , null as GRADE_CONTROL_FLAG
    , null as REPAIR_YIELD
    , null as MASTER_ITEM_VERSION_ID
    , null as HARD_PEGGING_LEVEL
    , null as RESTRICT_LOCATORS_CODE
    , null as CONFIG_MATCH
    , null as ATTRIBUTE_CATEGORY
    , null as LOCATION_CONTROL_CODE
    , null as LOT_TRANSLATE_ENABLED
    , null as COMMS_NL_TRACKABLE_FLAG
    , null as ATTRIBUTE_NUMBER_9
    , null as DEMAND_TIME_FENCE_CODE
    , null as CONTINOUS_TRANSFER
    , null as PRICE_TOLERANCE_PERCENT
    , null as COVERAGE_SCHEDULE_ID
    , null as DOWNLOADABLE_FLAG
    , null as SALES_PRODUCT_TYPE
    , null as RESTRICT_SUBINVENTORIES_CODE
    , null as CREATE_SUPPLY_AFTER_DATE
    , null as REPETITIVE_PLANNING_FLAG
    , null as ATTRIBUTE_DATE_2
    , null as INVENTORY_ITEM_STATUS_CODE
    , null as WIP_SUPPLY_TYPE
    , null as ATTRIBUTE_TIMESTAMP_4
    , null as FIXED_ORDER_QUANTITY
    , null as GLOBAL_ATTRIBUTE_NUMBER_4
    , null as ATTRIBUTE_NUMBER_2
    , null as ATTRIBUTE_NUMBER_6
    , null as ASN_AUTOEXPIRE_FLAG
    , null as STYLE_ITEM_FLAG
    , null as POSITIVE_MEASUREMENT_ERROR
    , null as REQUIRES_FULFILLMENT_LOC_FLAG
    , null as CONTRACT_MANUFACTURING
    , null as ATTRIBUTE_16
    , null as RESERVABLE_TYPE
    , null as PACKAGING_STRING_ID
    , null as BULK_PICKED_FLAG
    , null as ATTRIBUTE_22
    , null as UNIT_WIDTH
    , null as MARKET_PRICE
    , null as ALLOW_SUBSTITUTE_RECEIPTS_FLAG
    , null as ELECTRONIC_FLAG
    , null as BUYER_ID
    , null as DAYS_LATE_RECEIPT_ALLOWED
    , null as EAM_ACT_NOTIFICATION_FLAG
    , null as ATTRIBUTE_TIMESTAMP_2
    , null as QTY_RCV_EXCEPTION_CODE
    , null as BACK_TO_BACK_ENABLED
    , null as ASSET_TRACKED_FLAG
    , null as DUAL_UOM_DEVIATION_HIGH
    , null as ALLOW_EXPRESS_DELIVERY_FLAG
    , null as SERVICE_START_TYPE_CODE
    , null as ALLOW_SUSPEND_FLAG
    , null as MATURITY_DAYS
    , null as ENABLE_GENEALOGY_TRACKING_FLAG
    , null as INVENTORY_ASSET_FLAG
    , null as EAM_ACTIVITY_CAUSE_CODE
    , null as ENGINEERING_ITEM_ID
    , null as DUAL_UOM_CONTROL
    , null as SAFETY_STOCK_PLANNING_METHOD
    , null as INTERNAL_ORDER_FLAG
    , null as SHELF_LIFE_DAYS
    , null as UNDER_COMPL_TOLERANCE_TYPE
    , null as GLOBAL_ATTRIBUTE_15
    , null as CHILD_LOT_FLAG
    , null as GLOBAL_ATTRIBUTE_DATE_4
    , null as GLOBAL_ATTRIBUTE_NUMBER_5
    , null as GLOBAL_ATTRIBUTE_9
    , null as FORECAST_HORIZON
    , null as RELEASE_TIME_FENCE_CODE
    , null as CHANGE_BIT_MAP
    , null as PROCESS_EXECUTION_ENABLED_FLAG
    , null as GLOBAL_ATTRIBUTE_6
    , null as ATTRIBUTE_28
    , null as ATTRIBUTE_TIMESTAMP_5
    , null as EAM_ITEM_TYPE
    , null as START_UPON_MILESTONE_CODE
    , null as RECEIPT_REQUIRED_FLAG
    , null as GLOBAL_ATTRIBUTE_17
    , null as LAST_SUBMITTED_NIR_ID
    , null as END_DATE_ACTIVE
    , null as ATTRIBUTE_3
    , null as ATP_RULE_ID
    , null as ALLOW_TERMINATE_FLAG
    , null as GLOBAL_ATTRIBUTE_11
    , null as ATTRIBUTE_18
    , null as END_ASSEMBLY_PEGGING_FLAG
    , null as EAM_ACT_SHUTDOWN_STATUS
    , null as SERVICE_DURATION_TYPE_CODE
    , null as ATTRIBUTE_2
    , null as CONFIG_MODEL_TYPE
    , null as ATTRIBUTE_NUMBER_8
    , null as EAM_ACTIVITY_SOURCE_CODE
    , null as PROGRAM_NAME
    , null as MRP_SAFETY_STOCK_CODE
    , null as STD_LOT_SIZE
    , null as CONVERGENCE
    , null as REPAIR_LEADTIME
    , null as RECIPE_ENABLED_FLAG
    , null as ONT_PRICING_QTY_SOURCE
    , null as VERSION_END_DATE
    , null as GLOBAL_ATTRIBUTE_NUMBER_1
    , null as CONTRACT_ITEM_TYPE_CODE
    , null as ATTRIBUTE_11
    , null as ACCEPTABLE_RATE_DECREASE
    , null as FINANCING_ALLOWED_FLAG
    , null as AUTO_CREATED_CONFIG_FLAG
    , null as EXPIRATION_ACTION_INTERVAL
    , null as MIN_MINMAX_QUANTITY
    , null as FULL_LEAD_TIME
    , null as GLOBAL_ATTRIBUTE_18
    , null as REVISION_QTY_CONTROL_CODE
    , null as CREATE_FIXED_ASSET
    , null as DEFAULT_LOT_STATUS_ID
    , null as QSC_SALES_PRODUCT_TYPE
    , null as UNDER_SHIPMENT_TOLERANCE
    , null as MUST_USE_APPROVED_VENDOR_FLAG
    , null as DRP_PLANNED_FLAG
    , null as FIXED_LEAD_TIME
    , null as VOLUME_UOM_CODE
    , null as DEFECT_TRACKING_ON_FLAG
    , null as SUMMARY_FLAG
    , null as ATTRIBUTE_1
    , null as ATTRIBUTE_NUMBER_4
    , null as UN_NUMBER_ID
    , null as DEMAND_TIME_FENCE_DAYS
    , null as RECEIVE_CLOSE_TOLERANCE
    , null as PLANNING_TIME_FENCE_DAYS
    , null as SO_AUTHORIZATION_FLAG
    , null as HAZARDOUS_MATERIAL_FLAG
    , null as APPROVAL_STATUS
    , null as RECOVERED_PART_DISP_CODE
    , null as CHILD_LOT_STARTING_NUMBER
    , null as CHANGE_LINE_ID
    , null as GLOBAL_ATTRIBUTE_8
    , null as PROCESS_SUPPLY_SUBINVENTORY
    , null as WEB_STATUS
    , null as SERVICE_DURATION
    , null as EFFECTIVITY_CONTROL
    , null as INVOICE_MATCH_OPTION
    , null as VMI_MINIMUM_DAYS
    , null as BOM_ITEM_TYPE
    , null as GLOBAL_ATTRIBUTE_4
    , null as DIVERGENCE
    , null as JOB_DEFINITION_PACKAGE
    , null as ATTRIBUTE_19
    , null as ALLOW_ITEM_DESC_UPDATE_FLAG
    , null as SOURCE_ORGANIZATION_ID
    , null as ATTRIBUTE_13
    , null as GLOBAL_ATTRIBUTE_NUMBER_2
    , null as ITEM_CATALOG_GROUP_ID
    , null as ITEM_OBJECT_TYPE
    , null as PLANNING_EXCEPTION_SET
    , null as ALLOW_UNORDERED_RECEIPTS_FLAG
    , null as DAYS_MAX_INV_WINDOW
    , null as ATTRIBUTE_29
    , null as PREPROCESSING_LEAD_TIME
    , null as ATTRIBUTE_NUMBER_3
    , null as INVENTORY_ITEM_FLAG
    , null as WIP_SUPPLY_SUBINVENTORY
    , null as LOT_CONTROL_CODE
    , null as RELEASE_TIME_FENCE_DAYS
    , null as STYLE_ITEM_ID
    , null as ATTRIBUTE_DATE_1
    , null as PLANNED_INV_POINT_FLAG
    , null as MINIMUM_ORDER_QUANTITY
    , null as RECEIVING_ROUTING_ID
    , null as CRITICAL_COMPONENT_FLAG
    , null as VMI_FORECAST_TYPE
    , null as PROGRAM_APP_NAME
    , null as CAS_NUMBER
    , null as START_DATE_ACTIVE
    , null as OUTSIDE_OPERATION_UOM_TYPE
    , null as LOT_SPLIT_ENABLED
    , null as CARRYING_COST
    , null as OVER_SHIPMENT_TOLERANCE
    , null as ATTRIBUTE_9
    , null as ALLOW_MAINTENANCE_ASSET_FLAG
    , null as PROCESS_COSTING_ENABLED_FLAG
    , null as SAFETY_STOCK_BUCKET_DAYS
    , null as ATTRIBUTE_TIMESTAMP_1
    , null as TAXABLE_FLAG
    , null as PURCHASING_ENABLED_FLAG
    , null as LAST_UPDATED_BY
    , null as ITEM_TYPE
    , null as DEFAULT_SO_SOURCE_TYPE
    , null as STOCK_ENABLED_FLAG
    , null as MAX_MINMAX_QUANTITY
    , null as DAYS_EARLY_RECEIPT_ALLOWED
    , null as RECEIPT_DAYS_EXCEPTION_CODE
    , null as TEMPLATE_ITEM_FLAG
    , null as DQ_SEMANTIC_KEY
    , null as DQ_REQUIRED_FLAG
    , null as VEHICLE_ITEM_FLAG
    , null as OBJECT_VERSION_NUMBER
    , null as MAXIMUM_ORDER_QUANTITY
    , null as BUILD_IN_WIP_FLAG
    , null as UNDER_RETURN_TOLERANCE
    , null as SERIAL_STATUS_ENABLED
    , null as LOT_DIVISIBLE_FLAG
    , null as GLOBAL_ATTRIBUTE_5
    , null as MATCH_APPROVAL_LEVEL
    , null as SO_TRANSACTIONS_FLAG
    , null as VERSION_START_DATE
    , null as INVOICING_RULE_ID
    , null as ATTRIBUTE_14
    , null as INVENTORY_ORGANIZATION_ID
    , null as CHILD_LOT_VALIDATION_FLAG
    , null as NEGOTIATION_REQUIRED_FLAG
    , null as SOURCE_TYPE
    , null as ATTRIBUTE_21
    , null as ACCOUNTING_RULE_ID
    , null as SERVICE_DURATION_PERIOD_CODE
    , null as RETURNABLE_FLAG
    , null as LAST_UPDATE_LOGIN
    , null as ORDERABLE_ON_WEB_FLAG
    , null as PRIMARY_IMAGE_URL
    , null as ATTRIBUTE_NUMBER_10
    , null as REPAIR_PROGRAM
    , null as DEFAULT_INCLUDE_IN_ROLLUP_FLAG
    , null as AUTO_SERIAL_ALPHA_PREFIX
    , null as DEFAULT_SHIPPING_ORG
    , null as CUSTOMER_ORDER_ENABLED_FLAG
    , null as RETEST_INTERVAL
    , null as INVENTORY_CARRY_PENALTY
    , null as ATTRIBUTE_4
    , null as ATTRIBUTE_DATE_5
    , null as GLOBAL_ATTRIBUTE_CATEGORY
    , null as LOT_SUBSTITUTION_ENABLED
    , null as ATTRIBUTE_DATE_3
    , null as PROCESS_SUPPLY_LOCATOR_ID
    , null as DAYS_MAX_INV_SUPPLY
    , null as ENFORCE_SHIP_TO_LOCATION_CODE
    , null as ASSET_CLASS
    , null as INTERNAL_ORDER_ENABLED_FLAG
    , null as COPY_LOT_ATTRIBUTE_FLAG
    , null as CONTAINER_TYPE_CODE
    , null as SECONDARY_DEFAULT_IND
    , null as ATTRIBUTE_17
    , null as GLOBAL_ATTRIBUTE_1
    , null as ENABLED_FLAG
    , null as GLOBAL_ATTRIBUTE_12
    , null as GLOBAL_ATTRIBUTE_16
    , null as GLOBAL_ATTRIBUTE_7
    , null as INTERNAL_VOLUME
    , null as INSPECTION_REQUIRED_FLAG
    , null as VMI_MAXIMUM_DAYS
    , null as VMI_MAXIMUM_UNITS
    , null as GLOBAL_ATTRIBUTE_DATE_1
    , null as PROCESS_YIELD_LOCATOR_ID
    , null as CUSTOMER_ORDER_FLAG
    , null as OUTSIDE_OPERATION_FLAG
    , null as OVERRUN_PERCENTAGE
    , null as CONTAINER_ITEM_FLAG
    , null as ATTRIBUTE_6
    , null as LAST_UPDATE_DATE
    , null as GLOBAL_ATTRIBUTE_2
    , null as HOLD_DAYS
    , null as EGO_MASTER_ITEMS_DFF_CTX
    , null as MTL_TRANSACTIONS_ENABLED_FLAG
    , null as REPAIR_TRANSACTION_CODE
    , null as COMPLETENESS_SCORE
    , null as MRP_SAFETY_STOCK_PERCENT
    , null as ATTRIBUTE_10
    , null as HAZARD_CLASS_ID
    , null as ATP_FLAG
    , null as GLOBAL_ATTRIBUTE_NUMBER_3
    , null as PARTS_SOURCING
    , null as ORDER_MODIFIER_START_QTY_FLAG
    , null as _FIVETRAN_DELETED
    , null as _FIVETRAN_SYNCED
, null as PSA_DELETE_IND
, null as PSA_LOAD_DTS
, null as PSA_RECORD_SOURCE
, CONVERT_TIMEZONE('UTC','1900-01-01'::TIMESTAMP)::TIMESTAMP as LOAD_DTS
,'USAZET.SNOWFLAKE.FBIN.DERIVED' AS REC_SRC
, ''::BINARY as HASHDIFF
  FROM
        TABLE(strtok_split_to_table('0|-1|-2', '|')) AS GR
{% endif %}