---- SRC LAYER ----
WITH
SRC_a              as ( SELECT * FROM {{ ref('v_psa_stg_item_base_plan__ml_ascp') }} as SRC 
                         {% if is_incremental() %}
                              where src.load_dts > (select dateadd('HOUR',-1,max(load_dts)) from {{ this }})
                            {% endif %}   )

/*
SRC_a              as ( SELECT * FROM staging.v_psa_stg_item_base_plan__ml_ascp )
*/
---- LOGIC LAYER ----

, LOGIC_a as (
    SELECT
        ITEM_HK
      , ITEM_NAME
      , PLAN_ID
      , ORGANIZATION_ID
      , INVENTORY_ITEM_ID
      , SR_INSTANCE_ID
      , SR_INVENTORY_ITEM_ID
      , LOTS_EXPIRATION
      , LOT_CONTROL_CODE
      , SHRINKAGE_RATE
      , FIXED_DAYS_SUPPLY
      , FIXED_ORDER_QUANTITY
      , FIXED_LOT_MULTIPLIER
      , MINIMUM_ORDER_QUANTITY
      , MAXIMUM_ORDER_QUANTITY
      , ROUNDING_CONTROL_TYPE
      , PLANNING_TIME_FENCE_DAYS
      , PLANNING_TIME_FENCE_DATE
      , DEMAND_TIME_FENCE_DAYS
      , DEMAND_TIME_FENCE_DATE
      , DESCRIPTION
      , RELEASE_TIME_FENCE_CODE
      , RELEASE_TIME_FENCE_DAYS
      , IN_SOURCE_PLAN
      , REVISION
      , SR_CATEGORY_ID
      , ABC_CLASS
      , CATEGORY_NAME
      , MRP_PLANNING_CODE
      , FIXED_LEAD_TIME
      , VARIABLE_LEAD_TIME
      , PREPROCESSING_LEAD_TIME
      , POSTPROCESSING_LEAD_TIME
      , FULL_LEAD_TIME
      , CUMULATIVE_TOTAL_LEAD_TIME
      , CUM_MANUFACTURING_LEAD_TIME
      , UOM_CODE
      , UNIT_WEIGHT
      , UNIT_VOLUME
      , WEIGHT_UOM
      , VOLUME_UOM
      , PRODUCT_FAMILY_ID
      , ATP_RULE_ID
      , ATP_COMPONENTS_FLAG
      , BUILD_IN_WIP_FLAG
      , PURCHASING_ENABLED_FLAG
      , PLANNING_MAKE_BUY_CODE
      , REPETITIVE_TYPE
      , REPETITIVE_VARIANCE
      , STANDARD_COST
      , CARRYING_COST
      , ORDER_COST
      , MATERIAL_COST
      , DMD_LATENESS_COST
      , RESOURCE_COST
      , SS_PENALTY_COST
      , SUPPLIER_CAP_OVERUTIL_COST
      , LIST_PRICE
      , AVERAGE_DISCOUNT
      , ENGINEERING_ITEM_FLAG
      , WIP_SUPPLY_TYPE
      , SAFETY_STOCK_CODE
      , SAFETY_STOCK_PERCENT
      , SAFETY_STOCK_BUCKET_DAYS
      , INVENTORY_USE_UP_DATE
      , BUYER_NAME
      , PLANNER_CODE
      , PLANNING_EXCEPTION_SET
      , EXCESS_QUANTITY
      , EXCEPTION_SHORTAGE_DAYS
      , EXCEPTION_EXCESS_DAYS
      , EXCEPTION_OVERPROMISED_DAYS
      , EXCEPTION_CODE
      , BOM_ITEM_TYPE
      , ATO_FORECAST_CONTROL
      , EFFECTIVITY_CONTROL
      , ORGANIZATION_CODE
      , ACCEPTABLE_RATE_INCREASE
      , ACCEPTABLE_RATE_DECREASE
      , EXCEPTION_REP_VARIANCE_DAYS
      , OVERRUN_PERCENTAGE
      , INVENTORY_PLANNING_CODE
      , ACCEPTABLE_EARLY_DELIVERY
      , CALCULATE_ATP
      , END_ASSEMBLY_PEGGING_FLAG
      , END_ASSEMBLY_PEGGING
      , FULL_PEGGING
      , INVENTORY_ITEM_FLAG
      , SOURCE_ORG_ID
      , BASE_ITEM_ID
      , ABC_CLASS_NAME
      , FIXED_SAFETY_STOCK_QTY
      , PRIMARY_SUPPLIER_ID
      , ATP_FLAG
      , LOW_LEVEL_CODE
      , PLANNER_STATUS_CODE
      , NETTABLE_INVENTORY_QUANTITY
      , NONNETTABLE_INVENTORY_QUANTITY
      , REFRESH_NUMBER
      , LAST_UPDATE_DATE
      , LAST_UPDATED_BY
      , CREATION_DATE
      , CREATED_BY
      , LAST_UPDATE_LOGIN
      , REQUEST_ID
      , PROGRAM_APPLICATION_ID
      , PROGRAM_ID
      , PROGRAM_UPDATE_DATE
      , ATTRIBUTE_CATEGORY
      , ATTRIBUTE1
      , ATTRIBUTE2
      , ATTRIBUTE3
      , ATTRIBUTE4
      , ATTRIBUTE5
      , ATTRIBUTE6
      , ATTRIBUTE7
      , ATTRIBUTE8
      , ATTRIBUTE9
      , ATTRIBUTE10
      , ATTRIBUTE11
      , ATTRIBUTE12
      , ATTRIBUTE13
      , ATTRIBUTE14
      , ATTRIBUTE15
      , REVISION_QTY_CONTROL_CODE
      , EXPENSE_ACCOUNT
      , INVENTORY_ASSET_FLAG
      , BUYER_ID
      , REPETITIVE_PLANNING_FLAG
      , PICK_COMPONENTS_FLAG
      , SERVICE_LEVEL
      , REPLENISH_TO_ORDER_FLAG
      , PIP_FLAG
      , YIELD_CONV_FACTOR
      , MIN_MINMAX_QUANTITY
      , MAX_MINMAX_QUANTITY
      , NEW_ATP_FLAG
      , SOURCE_TYPE
      , SUBSTITUTION_WINDOW
      , CREATE_SUPPLY_FLAG
      , REORDER_POINT
      , AVERAGE_ANNUAL_DEMAND
      , ECONOMIC_ORDER_QUANTITY
      , SERIAL_NUMBER_CONTROL_CODE
      , CONVERGENCE
      , DIVERGENCE
      , CONTINOUS_TRANSFER
      , CRITICAL_COMPONENT_FLAG
      , REDUCE_MPS
      , CONSIGNED_FLAG
      , VMI_MINIMUM_UNITS
      , VMI_MINIMUM_DAYS
      , VMI_MAXIMUM_UNITS
      , VMI_MAXIMUM_DAYS
      , AVERAGE_DAILY_DEMAND
      , VMI_FIXED_ORDER_QUANTITY
      , SO_AUTHORIZATION_FLAG
      , VMI_FORECAST_TYPE
      , FORECAST_HORIZON
      , ASN_AUTOEXPIRE_FLAG
      , VMI_REFRESH_FLAG
      , BUDGET_CONSTRAINED
      , MAX_QUANTITY
      , MAX_QUANTITY_DOS
      , DAYS_TGT_INV_WINDOW
      , DAYS_MAX_INV_WINDOW
      , DAYS_TGT_INV_SUPPLY
      , DAYS_MAX_INV_SUPPLY
      , DRP_PLANNED
      , AGGREGATE_TIME_FENCE_DATE
      , INFERRED_CRITICAL_FLAG
      , SS_WINDOW_SIZE
      , LOWEST_LEVEL_SRC
      , EAM_ITEM_TYPE
      , LOTS_EXIST
      , LEADTIME_VARIABILITY
      , MIN_SHELF_LIFE_DAYS
      , GROUP_ID
      , REPAIR_YIELD
      , REPAIR_PROGRAM
      , REPAIR_LEAD_TIME
      , PRE_POSITION_INVENTORY
      , PREPOSITION_POINT
      , REPAIR_LEADTIME
      , DEMAND_FULFILLMENT_LT
      , ITEM_CREATION_DATE
      , SHORTAGE_TYPE
      , EXCESS_TYPE
      , PLANNING_TIME_FENCE_CODE
      , PEGGING_DEMAND_WINDOW_DAYS
      , PEGGING_SUPPLY_WINDOW_DAYS
      , FORECAST_RULE_FOR_DEMANDS
      , FORECAST_RULE_FOR_RETURNS
      , DEMAND_DISTRIBUTION
      , INTERARRIVAL_TIME
      , END_OF_LIFE_DATE
      , STD_DMD_OVER_HORIZON
      , LIFE_TIME_BUY_DATE
      , REPAIR_COST
      , CRITICALITY_CATEGORY
      , AVG_DEMAND_BEYOND_PH
      , AVG_RETURNS_BEYOND_PH
      , RETURN_FORECAST_TIME_FENCE
      , DEFECTIVE_ITEM_COST
      , STD_DEVIATION_FOR_DEMAND
      , MEAN_INTER_ARRIVAL
      , STD_DEVIATION_INTER_ARRIVAL
      , INTERARRIVAL_DIST_METHOD
      , BASIS_AVG_DAILY_DEMAND
      , COEFFICIENT_OF_VARIATION
      , STANDARD_DEVIATION
      , LAST_REPLAN_DATE
      , NETCHANGE_REPLAN_FLAG
      , REPLAN_PERIOD
      , SAFETY_LEAD_TIME
      , UNSATISFIED_DEMAND_FACTOR
      , MAX_USAGE_FACTOR
      , MIN_SUP_DEM_PERCENT
      , DMD_SATISFIED_PERCENT
      , NEW_PLAN_ID
      , NEW_PLAN_LIST
      , SIMULATION_SET_ID
      , NO_PL_ORD_BEFORE_WIP_WIN
      , PLANNING_UNITS_OF_WORK
      , EXCESS_HORIZON
      , OBSOLESCENCE_DATE
      , COMPUTE_EOQ
      , COMPUTE_SS
      , ROP_SAFETY_STOCK
      , CONSIDER_IN_CTB_FLAG
      , CALCULATE_CTB_FLAG
      , CTB_KPI_HORIZON
      , APPLIED
      , INTERMITTENT_DEMAND
      , COMP_SUBSTITUTION_FLAG
      , CONSUME_BEF_PRIMARY_FLAG
      , REPAIR_MODULE
      , SCRAP_RATE
      , REBUILD_ACTIVITY
      , ORDER_PERIOD
      , INV_DAYS_INCREMENT
      , AVERAGE_CYCLE_STOCK
      , IS_MODIFIED
      , ADS_CALC_DAYS
      , SAFETY_STOCK_MRSL
      , MRSL_INGREDIENT
      , MRSL_INGREDIENT_ID
      , ANNUAL_SALES_QTY
      , ANNUAL_SALES_COUNT
      , ANNUAL_SALES_VALUE
      , ANNUAL_SHIP_QTY
      , ANNUAL_SHIP_COUNT
      , ANNUAL_SHIP_VALUE
      , DEMAND_VARIANCE
      , INVENTORY_POLICY
      , POLICY_UOM
      , MIN_UNITS
      , MAX_UNITS
      , MIN_DAYS
      , MAX_DAYS
      , ANNUAL_ORDER_CNT
      , ORDER_CYCLE_CAL
      , FCST_ERROR
      , PM_SNAPSHOT_DATE
      , PSA_LOAD_DTS
      , PSA_RECORD_SOURCE
      , PSA_DELETE_IND
      , LOAD_DTS
      , REC_SRC
      , BKCC
      , HASHDIFF
    FROM SRC_a
)
---- RENAME LAYER ----

, RENAME_a as (
    SELECT
        ITEM_HK
      , ITEM_NAME
      , PLAN_ID
      , ORGANIZATION_ID
      , INVENTORY_ITEM_ID
      , SR_INSTANCE_ID
      , SR_INVENTORY_ITEM_ID
      , LOTS_EXPIRATION
      , LOT_CONTROL_CODE
      , SHRINKAGE_RATE
      , FIXED_DAYS_SUPPLY
      , FIXED_ORDER_QUANTITY
      , FIXED_LOT_MULTIPLIER
      , MINIMUM_ORDER_QUANTITY
      , MAXIMUM_ORDER_QUANTITY
      , ROUNDING_CONTROL_TYPE
      , PLANNING_TIME_FENCE_DAYS
      , PLANNING_TIME_FENCE_DATE
      , DEMAND_TIME_FENCE_DAYS
      , DEMAND_TIME_FENCE_DATE
      , DESCRIPTION
      , RELEASE_TIME_FENCE_CODE
      , RELEASE_TIME_FENCE_DAYS
      , IN_SOURCE_PLAN
      , REVISION
      , SR_CATEGORY_ID
      , ABC_CLASS
      , CATEGORY_NAME
      , MRP_PLANNING_CODE
      , FIXED_LEAD_TIME
      , VARIABLE_LEAD_TIME
      , PREPROCESSING_LEAD_TIME
      , POSTPROCESSING_LEAD_TIME
      , FULL_LEAD_TIME
      , CUMULATIVE_TOTAL_LEAD_TIME
      , CUM_MANUFACTURING_LEAD_TIME
      , UOM_CODE
      , UNIT_WEIGHT
      , UNIT_VOLUME
      , WEIGHT_UOM
      , VOLUME_UOM
      , PRODUCT_FAMILY_ID
      , ATP_RULE_ID
      , ATP_COMPONENTS_FLAG
      , BUILD_IN_WIP_FLAG
      , PURCHASING_ENABLED_FLAG
      , PLANNING_MAKE_BUY_CODE
      , REPETITIVE_TYPE
      , REPETITIVE_VARIANCE
      , STANDARD_COST
      , CARRYING_COST
      , ORDER_COST
      , MATERIAL_COST
      , DMD_LATENESS_COST
      , RESOURCE_COST
      , SS_PENALTY_COST
      , SUPPLIER_CAP_OVERUTIL_COST
      , LIST_PRICE
      , AVERAGE_DISCOUNT
      , ENGINEERING_ITEM_FLAG
      , WIP_SUPPLY_TYPE
      , SAFETY_STOCK_CODE
      , SAFETY_STOCK_PERCENT
      , SAFETY_STOCK_BUCKET_DAYS
      , INVENTORY_USE_UP_DATE
      , BUYER_NAME
      , PLANNER_CODE
      , PLANNING_EXCEPTION_SET
      , EXCESS_QUANTITY
      , EXCEPTION_SHORTAGE_DAYS
      , EXCEPTION_EXCESS_DAYS
      , EXCEPTION_OVERPROMISED_DAYS
      , EXCEPTION_CODE
      , BOM_ITEM_TYPE
      , ATO_FORECAST_CONTROL
      , EFFECTIVITY_CONTROL
      , ORGANIZATION_CODE
      , ACCEPTABLE_RATE_INCREASE
      , ACCEPTABLE_RATE_DECREASE
      , EXCEPTION_REP_VARIANCE_DAYS
      , OVERRUN_PERCENTAGE
      , INVENTORY_PLANNING_CODE
      , ACCEPTABLE_EARLY_DELIVERY
      , CALCULATE_ATP
      , END_ASSEMBLY_PEGGING_FLAG
      , END_ASSEMBLY_PEGGING
      , FULL_PEGGING
      , INVENTORY_ITEM_FLAG
      , SOURCE_ORG_ID
      , BASE_ITEM_ID
      , ABC_CLASS_NAME
      , FIXED_SAFETY_STOCK_QTY
      , PRIMARY_SUPPLIER_ID
      , ATP_FLAG
      , LOW_LEVEL_CODE
      , PLANNER_STATUS_CODE
      , NETTABLE_INVENTORY_QUANTITY
      , NONNETTABLE_INVENTORY_QUANTITY
      , REFRESH_NUMBER
      , LAST_UPDATE_DATE
      , LAST_UPDATED_BY
      , CREATION_DATE
      , CREATED_BY
      , LAST_UPDATE_LOGIN
      , REQUEST_ID
      , PROGRAM_APPLICATION_ID
      , PROGRAM_ID
      , PROGRAM_UPDATE_DATE
      , ATTRIBUTE_CATEGORY
      , ATTRIBUTE1
      , ATTRIBUTE2
      , ATTRIBUTE3
      , ATTRIBUTE4
      , ATTRIBUTE5
      , ATTRIBUTE6
      , ATTRIBUTE7
      , ATTRIBUTE8
      , ATTRIBUTE9
      , ATTRIBUTE10
      , ATTRIBUTE11
      , ATTRIBUTE12
      , ATTRIBUTE13
      , ATTRIBUTE14
      , ATTRIBUTE15
      , REVISION_QTY_CONTROL_CODE
      , EXPENSE_ACCOUNT
      , INVENTORY_ASSET_FLAG
      , BUYER_ID
      , REPETITIVE_PLANNING_FLAG
      , PICK_COMPONENTS_FLAG
      , SERVICE_LEVEL
      , REPLENISH_TO_ORDER_FLAG
      , PIP_FLAG
      , YIELD_CONV_FACTOR
      , MIN_MINMAX_QUANTITY
      , MAX_MINMAX_QUANTITY
      , NEW_ATP_FLAG
      , SOURCE_TYPE
      , SUBSTITUTION_WINDOW
      , CREATE_SUPPLY_FLAG
      , REORDER_POINT
      , AVERAGE_ANNUAL_DEMAND
      , ECONOMIC_ORDER_QUANTITY
      , SERIAL_NUMBER_CONTROL_CODE
      , CONVERGENCE
      , DIVERGENCE
      , CONTINOUS_TRANSFER
      , CRITICAL_COMPONENT_FLAG
      , REDUCE_MPS
      , CONSIGNED_FLAG
      , VMI_MINIMUM_UNITS
      , VMI_MINIMUM_DAYS
      , VMI_MAXIMUM_UNITS
      , VMI_MAXIMUM_DAYS
      , AVERAGE_DAILY_DEMAND
      , VMI_FIXED_ORDER_QUANTITY
      , SO_AUTHORIZATION_FLAG
      , VMI_FORECAST_TYPE
      , FORECAST_HORIZON
      , ASN_AUTOEXPIRE_FLAG
      , VMI_REFRESH_FLAG
      , BUDGET_CONSTRAINED
      , MAX_QUANTITY
      , MAX_QUANTITY_DOS
      , DAYS_TGT_INV_WINDOW
      , DAYS_MAX_INV_WINDOW
      , DAYS_TGT_INV_SUPPLY
      , DAYS_MAX_INV_SUPPLY
      , DRP_PLANNED
      , AGGREGATE_TIME_FENCE_DATE
      , INFERRED_CRITICAL_FLAG
      , SS_WINDOW_SIZE
      , LOWEST_LEVEL_SRC
      , EAM_ITEM_TYPE
      , LOTS_EXIST
      , LEADTIME_VARIABILITY
      , MIN_SHELF_LIFE_DAYS
      , GROUP_ID
      , REPAIR_YIELD
      , REPAIR_PROGRAM
      , REPAIR_LEAD_TIME
      , PRE_POSITION_INVENTORY
      , PREPOSITION_POINT
      , REPAIR_LEADTIME
      , DEMAND_FULFILLMENT_LT
      , ITEM_CREATION_DATE
      , SHORTAGE_TYPE
      , EXCESS_TYPE
      , PLANNING_TIME_FENCE_CODE
      , PEGGING_DEMAND_WINDOW_DAYS
      , PEGGING_SUPPLY_WINDOW_DAYS
      , FORECAST_RULE_FOR_DEMANDS
      , FORECAST_RULE_FOR_RETURNS
      , DEMAND_DISTRIBUTION
      , INTERARRIVAL_TIME
      , END_OF_LIFE_DATE
      , STD_DMD_OVER_HORIZON
      , LIFE_TIME_BUY_DATE
      , REPAIR_COST
      , CRITICALITY_CATEGORY
      , AVG_DEMAND_BEYOND_PH
      , AVG_RETURNS_BEYOND_PH
      , RETURN_FORECAST_TIME_FENCE
      , DEFECTIVE_ITEM_COST
      , STD_DEVIATION_FOR_DEMAND
      , MEAN_INTER_ARRIVAL
      , STD_DEVIATION_INTER_ARRIVAL
      , INTERARRIVAL_DIST_METHOD
      , BASIS_AVG_DAILY_DEMAND
      , COEFFICIENT_OF_VARIATION
      , STANDARD_DEVIATION
      , LAST_REPLAN_DATE
      , NETCHANGE_REPLAN_FLAG
      , REPLAN_PERIOD
      , SAFETY_LEAD_TIME
      , UNSATISFIED_DEMAND_FACTOR
      , MAX_USAGE_FACTOR
      , MIN_SUP_DEM_PERCENT
      , DMD_SATISFIED_PERCENT
      , NEW_PLAN_ID
      , NEW_PLAN_LIST
      , SIMULATION_SET_ID
      , NO_PL_ORD_BEFORE_WIP_WIN
      , PLANNING_UNITS_OF_WORK
      , EXCESS_HORIZON
      , OBSOLESCENCE_DATE
      , COMPUTE_EOQ
      , COMPUTE_SS
      , ROP_SAFETY_STOCK
      , CONSIDER_IN_CTB_FLAG
      , CALCULATE_CTB_FLAG
      , CTB_KPI_HORIZON
      , APPLIED
      , INTERMITTENT_DEMAND
      , COMP_SUBSTITUTION_FLAG
      , CONSUME_BEF_PRIMARY_FLAG
      , REPAIR_MODULE
      , SCRAP_RATE
      , REBUILD_ACTIVITY
      , ORDER_PERIOD
      , INV_DAYS_INCREMENT
      , AVERAGE_CYCLE_STOCK
      , IS_MODIFIED
      , ADS_CALC_DAYS
      , SAFETY_STOCK_MRSL
      , MRSL_INGREDIENT
      , MRSL_INGREDIENT_ID
      , ANNUAL_SALES_QTY
      , ANNUAL_SALES_COUNT
      , ANNUAL_SALES_VALUE
      , ANNUAL_SHIP_QTY
      , ANNUAL_SHIP_COUNT
      , ANNUAL_SHIP_VALUE
      , DEMAND_VARIANCE
      , INVENTORY_POLICY
      , POLICY_UOM
      , MIN_UNITS
      , MAX_UNITS
      , MIN_DAYS
      , MAX_DAYS
      , ANNUAL_ORDER_CNT
      , ORDER_CYCLE_CAL
      , FCST_ERROR
      , PM_SNAPSHOT_DATE
      , PSA_LOAD_DTS
      , PSA_RECORD_SOURCE
      , PSA_DELETE_IND
      , LOAD_DTS
      , REC_SRC
      , BKCC
      , HASHDIFF
    FROM LOGIC_a
)
---- FILTER LAYER ----

, FILTER_a as (
    SELECT *
    FROM RENAME_a
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM FILTER_a
)

---- FINAL LAYER ----
SELECT
          ITEM_HK
        , ITEM_NAME
        , PLAN_ID
        , ORGANIZATION_ID
        , INVENTORY_ITEM_ID
        , SR_INSTANCE_ID
        , SR_INVENTORY_ITEM_ID
        , LOTS_EXPIRATION
        , LOT_CONTROL_CODE
        , SHRINKAGE_RATE
        , FIXED_DAYS_SUPPLY
        , FIXED_ORDER_QUANTITY
        , FIXED_LOT_MULTIPLIER
        , MINIMUM_ORDER_QUANTITY
        , MAXIMUM_ORDER_QUANTITY
        , ROUNDING_CONTROL_TYPE
        , PLANNING_TIME_FENCE_DAYS
        , PLANNING_TIME_FENCE_DATE
        , DEMAND_TIME_FENCE_DAYS
        , DEMAND_TIME_FENCE_DATE
        , DESCRIPTION
        , RELEASE_TIME_FENCE_CODE
        , RELEASE_TIME_FENCE_DAYS
        , IN_SOURCE_PLAN
        , REVISION
        , SR_CATEGORY_ID
        , ABC_CLASS
        , CATEGORY_NAME
        , MRP_PLANNING_CODE
        , FIXED_LEAD_TIME
        , VARIABLE_LEAD_TIME
        , PREPROCESSING_LEAD_TIME
        , POSTPROCESSING_LEAD_TIME
        , FULL_LEAD_TIME
        , CUMULATIVE_TOTAL_LEAD_TIME
        , CUM_MANUFACTURING_LEAD_TIME
        , UOM_CODE
        , UNIT_WEIGHT
        , UNIT_VOLUME
        , WEIGHT_UOM
        , VOLUME_UOM
        , PRODUCT_FAMILY_ID
        , ATP_RULE_ID
        , ATP_COMPONENTS_FLAG
        , BUILD_IN_WIP_FLAG
        , PURCHASING_ENABLED_FLAG
        , PLANNING_MAKE_BUY_CODE
        , REPETITIVE_TYPE
        , REPETITIVE_VARIANCE
        , STANDARD_COST
        , CARRYING_COST
        , ORDER_COST
        , MATERIAL_COST
        , DMD_LATENESS_COST
        , RESOURCE_COST
        , SS_PENALTY_COST
        , SUPPLIER_CAP_OVERUTIL_COST
        , LIST_PRICE
        , AVERAGE_DISCOUNT
        , ENGINEERING_ITEM_FLAG
        , WIP_SUPPLY_TYPE
        , SAFETY_STOCK_CODE
        , SAFETY_STOCK_PERCENT
        , SAFETY_STOCK_BUCKET_DAYS
        , INVENTORY_USE_UP_DATE
        , BUYER_NAME
        , PLANNER_CODE
        , PLANNING_EXCEPTION_SET
        , EXCESS_QUANTITY
        , EXCEPTION_SHORTAGE_DAYS
        , EXCEPTION_EXCESS_DAYS
        , EXCEPTION_OVERPROMISED_DAYS
        , EXCEPTION_CODE
        , BOM_ITEM_TYPE
        , ATO_FORECAST_CONTROL
        , EFFECTIVITY_CONTROL
        , ORGANIZATION_CODE
        , ACCEPTABLE_RATE_INCREASE
        , ACCEPTABLE_RATE_DECREASE
        , EXCEPTION_REP_VARIANCE_DAYS
        , OVERRUN_PERCENTAGE
        , INVENTORY_PLANNING_CODE
        , ACCEPTABLE_EARLY_DELIVERY
        , CALCULATE_ATP
        , END_ASSEMBLY_PEGGING_FLAG
        , END_ASSEMBLY_PEGGING
        , FULL_PEGGING
        , INVENTORY_ITEM_FLAG
        , SOURCE_ORG_ID
        , BASE_ITEM_ID
        , ABC_CLASS_NAME
        , FIXED_SAFETY_STOCK_QTY
        , PRIMARY_SUPPLIER_ID
        , ATP_FLAG
        , LOW_LEVEL_CODE
        , PLANNER_STATUS_CODE
        , NETTABLE_INVENTORY_QUANTITY
        , NONNETTABLE_INVENTORY_QUANTITY
        , REFRESH_NUMBER
        , LAST_UPDATE_DATE
        , LAST_UPDATED_BY
        , CREATION_DATE
        , CREATED_BY
        , LAST_UPDATE_LOGIN
        , REQUEST_ID
        , PROGRAM_APPLICATION_ID
        , PROGRAM_ID
        , PROGRAM_UPDATE_DATE
        , ATTRIBUTE_CATEGORY
        , ATTRIBUTE1
        , ATTRIBUTE2
        , ATTRIBUTE3
        , ATTRIBUTE4
        , ATTRIBUTE5
        , ATTRIBUTE6
        , ATTRIBUTE7
        , ATTRIBUTE8
        , ATTRIBUTE9
        , ATTRIBUTE10
        , ATTRIBUTE11
        , ATTRIBUTE12
        , ATTRIBUTE13
        , ATTRIBUTE14
        , ATTRIBUTE15
        , REVISION_QTY_CONTROL_CODE
        , EXPENSE_ACCOUNT
        , INVENTORY_ASSET_FLAG
        , BUYER_ID
        , REPETITIVE_PLANNING_FLAG
        , PICK_COMPONENTS_FLAG
        , SERVICE_LEVEL
        , REPLENISH_TO_ORDER_FLAG
        , PIP_FLAG
        , YIELD_CONV_FACTOR
        , MIN_MINMAX_QUANTITY
        , MAX_MINMAX_QUANTITY
        , NEW_ATP_FLAG
        , SOURCE_TYPE
        , SUBSTITUTION_WINDOW
        , CREATE_SUPPLY_FLAG
        , REORDER_POINT
        , AVERAGE_ANNUAL_DEMAND
        , ECONOMIC_ORDER_QUANTITY
        , SERIAL_NUMBER_CONTROL_CODE
        , CONVERGENCE
        , DIVERGENCE
        , CONTINOUS_TRANSFER
        , CRITICAL_COMPONENT_FLAG
        , REDUCE_MPS
        , CONSIGNED_FLAG
        , VMI_MINIMUM_UNITS
        , VMI_MINIMUM_DAYS
        , VMI_MAXIMUM_UNITS
        , VMI_MAXIMUM_DAYS
        , AVERAGE_DAILY_DEMAND
        , VMI_FIXED_ORDER_QUANTITY
        , SO_AUTHORIZATION_FLAG
        , VMI_FORECAST_TYPE
        , FORECAST_HORIZON
        , ASN_AUTOEXPIRE_FLAG
        , VMI_REFRESH_FLAG
        , BUDGET_CONSTRAINED
        , MAX_QUANTITY
        , MAX_QUANTITY_DOS
        , DAYS_TGT_INV_WINDOW
        , DAYS_MAX_INV_WINDOW
        , DAYS_TGT_INV_SUPPLY
        , DAYS_MAX_INV_SUPPLY
        , DRP_PLANNED
        , AGGREGATE_TIME_FENCE_DATE
        , INFERRED_CRITICAL_FLAG
        , SS_WINDOW_SIZE
        , LOWEST_LEVEL_SRC
        , EAM_ITEM_TYPE
        , LOTS_EXIST
        , LEADTIME_VARIABILITY
        , MIN_SHELF_LIFE_DAYS
        , GROUP_ID
        , REPAIR_YIELD
        , REPAIR_PROGRAM
        , REPAIR_LEAD_TIME
        , PRE_POSITION_INVENTORY
        , PREPOSITION_POINT
        , REPAIR_LEADTIME
        , DEMAND_FULFILLMENT_LT
        , ITEM_CREATION_DATE
        , SHORTAGE_TYPE
        , EXCESS_TYPE
        , PLANNING_TIME_FENCE_CODE
        , PEGGING_DEMAND_WINDOW_DAYS
        , PEGGING_SUPPLY_WINDOW_DAYS
        , FORECAST_RULE_FOR_DEMANDS
        , FORECAST_RULE_FOR_RETURNS
        , DEMAND_DISTRIBUTION
        , INTERARRIVAL_TIME
        , END_OF_LIFE_DATE
        , STD_DMD_OVER_HORIZON
        , LIFE_TIME_BUY_DATE
        , REPAIR_COST
        , CRITICALITY_CATEGORY
        , AVG_DEMAND_BEYOND_PH
        , AVG_RETURNS_BEYOND_PH
        , RETURN_FORECAST_TIME_FENCE
        , DEFECTIVE_ITEM_COST
        , STD_DEVIATION_FOR_DEMAND
        , MEAN_INTER_ARRIVAL
        , STD_DEVIATION_INTER_ARRIVAL
        , INTERARRIVAL_DIST_METHOD
        , BASIS_AVG_DAILY_DEMAND
        , COEFFICIENT_OF_VARIATION
        , STANDARD_DEVIATION
        , LAST_REPLAN_DATE
        , NETCHANGE_REPLAN_FLAG
        , REPLAN_PERIOD
        , SAFETY_LEAD_TIME
        , UNSATISFIED_DEMAND_FACTOR
        , MAX_USAGE_FACTOR
        , MIN_SUP_DEM_PERCENT
        , DMD_SATISFIED_PERCENT
        , NEW_PLAN_ID
        , NEW_PLAN_LIST
        , SIMULATION_SET_ID
        , NO_PL_ORD_BEFORE_WIP_WIN
        , PLANNING_UNITS_OF_WORK
        , EXCESS_HORIZON
        , OBSOLESCENCE_DATE
        , COMPUTE_EOQ
        , COMPUTE_SS
        , ROP_SAFETY_STOCK
        , CONSIDER_IN_CTB_FLAG
        , CALCULATE_CTB_FLAG
        , CTB_KPI_HORIZON
        , APPLIED
        , INTERMITTENT_DEMAND
        , COMP_SUBSTITUTION_FLAG
        , CONSUME_BEF_PRIMARY_FLAG
        , REPAIR_MODULE
        , SCRAP_RATE
        , REBUILD_ACTIVITY
        , ORDER_PERIOD
        , INV_DAYS_INCREMENT
        , AVERAGE_CYCLE_STOCK
        , IS_MODIFIED
        , ADS_CALC_DAYS
        , SAFETY_STOCK_MRSL
        , MRSL_INGREDIENT
        , MRSL_INGREDIENT_ID
        , ANNUAL_SALES_QTY
        , ANNUAL_SALES_COUNT
        , ANNUAL_SALES_VALUE
        , ANNUAL_SHIP_QTY
        , ANNUAL_SHIP_COUNT
        , ANNUAL_SHIP_VALUE
        , DEMAND_VARIANCE
        , INVENTORY_POLICY
        , POLICY_UOM
        , MIN_UNITS
        , MAX_UNITS
        , MIN_DAYS
        , MAX_DAYS
        , ANNUAL_ORDER_CNT
        , ORDER_CYCLE_CAL
        , FCST_ERROR
        , PM_SNAPSHOT_DATE
        , PSA_LOAD_DTS
        , PSA_RECORD_SOURCE
        , PSA_DELETE_IND
        , LOAD_DTS
        , REC_SRC
        , BKCC
        , HASHDIFF
FROM JOIN_RESULT
{% if is_incremental() %}
WHERE NOT EXISTS (
    SELECT 1 
    FROM {{ this }} existing
     WHERE existing.ITEM_HK= JOIN_RESULT.ITEM_HK
     AND existing.INVENTORY_ITEM_ID = JOIN_RESULT.INVENTORY_ITEM_ID 
     AND existing.ORGANIZATION_ID = JOIN_RESULT.ORGANIZATION_ID 
    AND existing.HASHDIFF = JOIN_RESULT.HASHDIFF
)
{% endif %}
{% if not is_incremental() %}

/* The following qualifier is implemented to prevent multiple loads of touched records during the initial build, such as multiple rows per HK and hashdiff. */
qualify 1 = row_number() over (partition by ITEM_HK, INVENTORY_ITEM_ID, ORGANIZATION_ID, HASHDIFF order by PSA_LOAD_DTS)

union all
SELECT 
MD5_BINARY(GR.VALUE) AS ITEM_HK,
GR.VALUE::text AS ITEM_NAME,
GR.VALUE::number AS PLAN_ID,
GR.VALUE::number AS ORGANIZATION_ID,
GR.VALUE::number AS INVENTORY_ITEM_ID,
NULL AS SR_INSTANCE_ID,
NULL AS SR_INVENTORY_ITEM_ID,
NULL AS LOTS_EXPIRATION,
NULL AS LOT_CONTROL_CODE,
NULL AS SHRINKAGE_RATE,
NULL AS FIXED_DAYS_SUPPLY,
NULL AS FIXED_ORDER_QUANTITY,
NULL AS FIXED_LOT_MULTIPLIER,
NULL AS MINIMUM_ORDER_QUANTITY,
NULL AS MAXIMUM_ORDER_QUANTITY,
NULL AS ROUNDING_CONTROL_TYPE,
NULL AS PLANNING_TIME_FENCE_DAYS,
NULL AS PLANNING_TIME_FENCE_DATE,
NULL AS DEMAND_TIME_FENCE_DAYS,
NULL AS DEMAND_TIME_FENCE_DATE,
NULL AS DESCRIPTION,
NULL AS RELEASE_TIME_FENCE_CODE,
NULL AS RELEASE_TIME_FENCE_DAYS,
NULL AS IN_SOURCE_PLAN,
NULL AS REVISION,
NULL AS SR_CATEGORY_ID,
NULL AS ABC_CLASS,
NULL AS CATEGORY_NAME,
NULL AS MRP_PLANNING_CODE,
NULL AS FIXED_LEAD_TIME,
NULL AS VARIABLE_LEAD_TIME,
NULL AS PREPROCESSING_LEAD_TIME,
NULL AS POSTPROCESSING_LEAD_TIME,
NULL AS FULL_LEAD_TIME,
NULL AS CUMULATIVE_TOTAL_LEAD_TIME,
NULL AS CUM_MANUFACTURING_LEAD_TIME,
NULL AS UOM_CODE,
NULL AS UNIT_WEIGHT,
NULL AS UNIT_VOLUME,
NULL AS WEIGHT_UOM,
NULL AS VOLUME_UOM,
NULL AS PRODUCT_FAMILY_ID,
NULL AS ATP_RULE_ID,
NULL AS ATP_COMPONENTS_FLAG,
NULL AS BUILD_IN_WIP_FLAG,
NULL AS PURCHASING_ENABLED_FLAG,
NULL AS PLANNING_MAKE_BUY_CODE,
NULL AS REPETITIVE_TYPE,
NULL AS REPETITIVE_VARIANCE,
NULL AS STANDARD_COST,
NULL AS CARRYING_COST,
NULL AS ORDER_COST,
NULL AS MATERIAL_COST,
NULL AS DMD_LATENESS_COST,
NULL AS RESOURCE_COST,
NULL AS SS_PENALTY_COST,
NULL AS SUPPLIER_CAP_OVERUTIL_COST,
NULL AS LIST_PRICE,
NULL AS AVERAGE_DISCOUNT,
NULL AS ENGINEERING_ITEM_FLAG,
NULL AS WIP_SUPPLY_TYPE,
NULL AS SAFETY_STOCK_CODE,
NULL AS SAFETY_STOCK_PERCENT,
NULL AS SAFETY_STOCK_BUCKET_DAYS,
NULL AS INVENTORY_USE_UP_DATE,
NULL AS BUYER_NAME,
NULL AS PLANNER_CODE,
NULL AS PLANNING_EXCEPTION_SET,
NULL AS EXCESS_QUANTITY,
NULL AS EXCEPTION_SHORTAGE_DAYS,
NULL AS EXCEPTION_EXCESS_DAYS,
NULL AS EXCEPTION_OVERPROMISED_DAYS,
NULL AS EXCEPTION_CODE,
NULL AS BOM_ITEM_TYPE,
NULL AS ATO_FORECAST_CONTROL,
NULL AS EFFECTIVITY_CONTROL,
NULL AS ORGANIZATION_CODE,
NULL AS ACCEPTABLE_RATE_INCREASE,
NULL AS ACCEPTABLE_RATE_DECREASE,
NULL AS EXCEPTION_REP_VARIANCE_DAYS,
NULL AS OVERRUN_PERCENTAGE,
NULL AS INVENTORY_PLANNING_CODE,
NULL AS ACCEPTABLE_EARLY_DELIVERY,
NULL AS CALCULATE_ATP,
NULL AS END_ASSEMBLY_PEGGING_FLAG,
NULL AS END_ASSEMBLY_PEGGING,
NULL AS FULL_PEGGING,
NULL AS INVENTORY_ITEM_FLAG,
NULL AS SOURCE_ORG_ID,
NULL AS BASE_ITEM_ID,
NULL AS ABC_CLASS_NAME,
NULL AS FIXED_SAFETY_STOCK_QTY,
NULL AS PRIMARY_SUPPLIER_ID,
NULL AS ATP_FLAG,
NULL AS LOW_LEVEL_CODE,
NULL AS PLANNER_STATUS_CODE,
NULL AS NETTABLE_INVENTORY_QUANTITY,
NULL AS NONNETTABLE_INVENTORY_QUANTITY,
NULL AS REFRESH_NUMBER,
NULL AS LAST_UPDATE_DATE,
NULL AS LAST_UPDATED_BY,
NULL AS CREATION_DATE,
NULL AS CREATED_BY,
NULL AS LAST_UPDATE_LOGIN,
NULL AS REQUEST_ID,
NULL AS PROGRAM_APPLICATION_ID,
NULL AS PROGRAM_ID,
NULL AS PROGRAM_UPDATE_DATE,
NULL AS ATTRIBUTE_CATEGORY,
NULL AS ATTRIBUTE1,
NULL AS ATTRIBUTE2,
NULL AS ATTRIBUTE3,
NULL AS ATTRIBUTE4,
NULL AS ATTRIBUTE5,
NULL AS ATTRIBUTE6,
NULL AS ATTRIBUTE7,
NULL AS ATTRIBUTE8,
NULL AS ATTRIBUTE9,
NULL AS ATTRIBUTE10,
NULL AS ATTRIBUTE11,
NULL AS ATTRIBUTE12,
NULL AS ATTRIBUTE13,
NULL AS ATTRIBUTE14,
NULL AS ATTRIBUTE15,
NULL AS REVISION_QTY_CONTROL_CODE,
NULL AS EXPENSE_ACCOUNT,
NULL AS INVENTORY_ASSET_FLAG,
NULL AS BUYER_ID,
NULL AS REPETITIVE_PLANNING_FLAG,
NULL AS PICK_COMPONENTS_FLAG,
NULL AS SERVICE_LEVEL,
NULL AS REPLENISH_TO_ORDER_FLAG,
NULL AS PIP_FLAG,
NULL AS YIELD_CONV_FACTOR,
NULL AS MIN_MINMAX_QUANTITY,
NULL AS MAX_MINMAX_QUANTITY,
NULL AS NEW_ATP_FLAG,
NULL AS SOURCE_TYPE,
NULL AS SUBSTITUTION_WINDOW,
NULL AS CREATE_SUPPLY_FLAG,
NULL AS REORDER_POINT,
NULL AS AVERAGE_ANNUAL_DEMAND,
NULL AS ECONOMIC_ORDER_QUANTITY,
NULL AS SERIAL_NUMBER_CONTROL_CODE,
NULL AS CONVERGENCE,
NULL AS DIVERGENCE,
NULL AS CONTINOUS_TRANSFER,
NULL AS CRITICAL_COMPONENT_FLAG,
NULL AS REDUCE_MPS,
NULL AS CONSIGNED_FLAG,
NULL AS VMI_MINIMUM_UNITS,
NULL AS VMI_MINIMUM_DAYS,
NULL AS VMI_MAXIMUM_UNITS,
NULL AS VMI_MAXIMUM_DAYS,
NULL AS AVERAGE_DAILY_DEMAND,
NULL AS VMI_FIXED_ORDER_QUANTITY,
NULL AS SO_AUTHORIZATION_FLAG,
NULL AS VMI_FORECAST_TYPE,
NULL AS FORECAST_HORIZON,
NULL AS ASN_AUTOEXPIRE_FLAG,
NULL AS VMI_REFRESH_FLAG,
NULL AS BUDGET_CONSTRAINED,
NULL AS MAX_QUANTITY,
NULL AS MAX_QUANTITY_DOS,
NULL AS DAYS_TGT_INV_WINDOW,
NULL AS DAYS_MAX_INV_WINDOW,
NULL AS DAYS_TGT_INV_SUPPLY,
NULL AS DAYS_MAX_INV_SUPPLY,
NULL AS DRP_PLANNED,
NULL AS AGGREGATE_TIME_FENCE_DATE,
NULL AS INFERRED_CRITICAL_FLAG,
NULL AS SS_WINDOW_SIZE,
NULL AS LOWEST_LEVEL_SRC,
NULL AS EAM_ITEM_TYPE,
NULL AS LOTS_EXIST,
NULL AS LEADTIME_VARIABILITY,
NULL AS MIN_SHELF_LIFE_DAYS,
NULL AS GROUP_ID,
NULL AS REPAIR_YIELD,
NULL AS REPAIR_PROGRAM,
NULL AS REPAIR_LEAD_TIME,
NULL AS PRE_POSITION_INVENTORY,
NULL AS PREPOSITION_POINT,
NULL AS REPAIR_LEADTIME,
NULL AS DEMAND_FULFILLMENT_LT,
NULL AS ITEM_CREATION_DATE,
NULL AS SHORTAGE_TYPE,
NULL AS EXCESS_TYPE,
NULL AS PLANNING_TIME_FENCE_CODE,
NULL AS PEGGING_DEMAND_WINDOW_DAYS,
NULL AS PEGGING_SUPPLY_WINDOW_DAYS,
NULL AS FORECAST_RULE_FOR_DEMANDS,
NULL AS FORECAST_RULE_FOR_RETURNS,
NULL AS DEMAND_DISTRIBUTION,
NULL AS INTERARRIVAL_TIME,
NULL AS END_OF_LIFE_DATE,
NULL AS STD_DMD_OVER_HORIZON,
NULL AS LIFE_TIME_BUY_DATE,
NULL AS REPAIR_COST,
NULL AS CRITICALITY_CATEGORY,
NULL AS AVG_DEMAND_BEYOND_PH,
NULL AS AVG_RETURNS_BEYOND_PH,
NULL AS RETURN_FORECAST_TIME_FENCE,
NULL AS DEFECTIVE_ITEM_COST,
NULL AS STD_DEVIATION_FOR_DEMAND,
NULL AS MEAN_INTER_ARRIVAL,
NULL AS STD_DEVIATION_INTER_ARRIVAL,
NULL AS INTERARRIVAL_DIST_METHOD,
NULL AS BASIS_AVG_DAILY_DEMAND,
NULL AS COEFFICIENT_OF_VARIATION,
NULL AS STANDARD_DEVIATION,
NULL AS LAST_REPLAN_DATE,
NULL AS NETCHANGE_REPLAN_FLAG,
NULL AS REPLAN_PERIOD,
NULL AS SAFETY_LEAD_TIME,
NULL AS UNSATISFIED_DEMAND_FACTOR,
NULL AS MAX_USAGE_FACTOR,
NULL AS MIN_SUP_DEM_PERCENT,
NULL AS DMD_SATISFIED_PERCENT,
NULL AS NEW_PLAN_ID,
NULL AS NEW_PLAN_LIST,
NULL AS SIMULATION_SET_ID,
NULL AS NO_PL_ORD_BEFORE_WIP_WIN,
NULL AS PLANNING_UNITS_OF_WORK,
NULL AS EXCESS_HORIZON,
NULL AS OBSOLESCENCE_DATE,
NULL AS COMPUTE_EOQ,
NULL AS COMPUTE_SS,
NULL AS ROP_SAFETY_STOCK,
NULL AS CONSIDER_IN_CTB_FLAG,
NULL AS CALCULATE_CTB_FLAG,
NULL AS CTB_KPI_HORIZON,
NULL AS APPLIED,
NULL AS INTERMITTENT_DEMAND,
NULL AS COMP_SUBSTITUTION_FLAG,
NULL AS CONSUME_BEF_PRIMARY_FLAG,
NULL AS REPAIR_MODULE,
NULL AS SCRAP_RATE,
NULL AS REBUILD_ACTIVITY,
NULL AS ORDER_PERIOD,
NULL AS INV_DAYS_INCREMENT,
NULL AS AVERAGE_CYCLE_STOCK,
NULL AS IS_MODIFIED,
NULL AS ADS_CALC_DAYS,
NULL AS SAFETY_STOCK_MRSL,
NULL AS MRSL_INGREDIENT,
NULL AS MRSL_INGREDIENT_ID,
NULL AS ANNUAL_SALES_QTY,
NULL AS ANNUAL_SALES_COUNT,
NULL AS ANNUAL_SALES_VALUE,
NULL AS ANNUAL_SHIP_QTY,
NULL AS ANNUAL_SHIP_COUNT,
NULL AS ANNUAL_SHIP_VALUE,
NULL AS DEMAND_VARIANCE,
NULL AS INVENTORY_POLICY,
NULL AS POLICY_UOM,
NULL AS MIN_UNITS,
NULL AS MAX_UNITS,
NULL AS MIN_DAYS,
NULL AS MAX_DAYS,
NULL AS ANNUAL_ORDER_CNT,
NULL AS ORDER_CYCLE_CAL,
NULL AS FCST_ERROR,
NULL AS PM_SNAPSHOT_DATE,
'1900-01-01'::TIMESTAMP AS PSA_LOAD_DTS,
NULL AS PSA_RECORD_SOURCE,
'N' AS PSA_DELETE_IND,
CONVERT_TIMEZONE('UTC','1900-01-01'::TIMESTAMP) AS LOAD_DTS,
'USAZET.SNOWFLAKE.FBIN.DERIVED' AS REC_SRC,
DECODE(GR.VALUE, 0, 'GHOST RECORD-SYSTEM', -1, 'GHOST RECORD-nullkey-required', -2, 'GHOST RECORD-nullkey-optional') AS BKCC,
''::BINARY AS HASHDIFF
FROM
TABLE(strtok_split_to_table('0|-1|-2', '|')) AS GR
{% endif %}
