---- SRC LAYER ----
WITH
SRC_SRC            as ( SELECT * FROM {{ ref('v_psa_stg_supplier_invoice_line__emtk_ebs') }} as SRC 
{% if is_incremental() %}
      where src.load_dts > (select dateadd('HOUR',-1,max(load_dts)) from {{ this }})
    {% endif %} )

/*
SRC_SRC            as ( SELECT * FROM int_staging_views.v_psa_stg_supplier_invoice_line__emtk_ebs )
*/
---- LOGIC LAYER ----

, LOGIC_SRC as (
    SELECT
        SUPPLIER_INVOICE_LINE_HK
      , INVOICE_ID
      , LINE_NUMBER
      , LINE_TYPE_LOOKUP_CODE
      , REQUESTER_ID
      , DESCRIPTION
      , LINE_SOURCE
      , ORG_ID
      , LINE_GROUP_NUMBER
      , INVENTORY_ITEM_ID
      , ITEM_DESCRIPTION
      , SERIAL_NUMBER
      , MANUFACTURER
      , MODEL_NUMBER
      , WARRANTY_NUMBER
      , GENERATE_DISTS
      , MATCH_TYPE
      , DISTRIBUTION_SET_ID
      , ACCOUNT_SEGMENT
      , BALANCING_SEGMENT
      , COST_CENTER_SEGMENT
      , OVERLAY_DIST_CODE_CONCAT
      , DEFAULT_DIST_CCID
      , PRORATE_ACROSS_ALL_ITEMS
      , ACCOUNTING_DATE
      , PERIOD_NAME
      , DEFERRED_ACCTG_FLAG
      , DEF_ACCTG_START_DATE
      , DEF_ACCTG_END_DATE
      , DEF_ACCTG_NUMBER_OF_PERIODS
      , DEF_ACCTG_PERIOD_TYPE
      , SET_OF_BOOKS_ID
      , AMOUNT
      , BASE_AMOUNT
      , ROUNDING_AMT
      , QUANTITY_INVOICED
      , UNIT_MEAS_LOOKUP_CODE
      , UNIT_PRICE
      , WFAPPROVAL_STATUS
      , USSGL_TRANSACTION_CODE
      , DISCARDED_FLAG
      , ORIGINAL_AMOUNT
      , ORIGINAL_BASE_AMOUNT
      , ORIGINAL_ROUNDING_AMT
      , CANCELLED_FLAG
      , INCOME_TAX_REGION
      , TYPE_1099
      , STAT_AMOUNT
      , PREPAY_INVOICE_ID
      , PREPAY_LINE_NUMBER
      , INVOICE_INCLUDES_PREPAY_FLAG
      , CORRECTED_INV_ID
      , CORRECTED_LINE_NUMBER
      , PO_HEADER_ID
      , PO_LINE_ID
      , PO_RELEASE_ID
      , PO_LINE_LOCATION_ID
      , PO_DISTRIBUTION_ID
      , RCV_TRANSACTION_ID
      , FINAL_MATCH_FLAG
      , ASSETS_TRACKING_FLAG
      , ASSET_BOOK_TYPE_CODE
      , ASSET_CATEGORY_ID
      , PROJECT_ID
      , TASK_ID
      , EXPENDITURE_TYPE
      , EXPENDITURE_ITEM_DATE
      , EXPENDITURE_ORGANIZATION_ID
      , PA_QUANTITY
      , PA_CC_AR_INVOICE_ID
      , PA_CC_AR_INVOICE_LINE_NUM
      , PA_CC_PROCESSED_CODE
      , AWARD_ID
      , AWT_GROUP_ID
      , REFERENCE_1
      , REFERENCE_2
      , RECEIPT_VERIFIED_FLAG
      , RECEIPT_REQUIRED_FLAG
      , RECEIPT_MISSING_FLAG
      , JUSTIFICATION
      , EXPENSE_GROUP
      , START_EXPENSE_DATE
      , END_EXPENSE_DATE
      , RECEIPT_CURRENCY_CODE
      , RECEIPT_CONVERSION_RATE
      , RECEIPT_CURRENCY_AMOUNT
      , DAILY_AMOUNT
      , WEB_PARAMETER_ID
      , ADJUSTMENT_REASON
      , MERCHANT_DOCUMENT_NUMBER
      , MERCHANT_REFERENCE
      , MERCHANT_TAX_REG_NUMBER
      , MERCHANT_TAXPAYER_ID
      , COUNTRY_OF_SUPPLY
      , CREDIT_CARD_TRX_ID
      , COMPANY_PREPAID_INVOICE_ID
      , CC_REVERSAL_FLAG
      , CREATION_DATE
      , CREATED_BY
      , LAST_UPDATED_BY
      , LAST_UPDATE_DATE
      , LAST_UPDATE_LOGIN
      , PROGRAM_APPLICATION_ID
      , PROGRAM_ID
      , PROGRAM_UPDATE_DATE
      , REQUEST_ID
      , ATTRIBUTE_CATEGORY
      , ATTRIBUTE1
      , ATTRIBUTE2
      , ATTRIBUTE3
      , ATTRIBUTE4
      , ATTRIBUTE5
      , ATTRIBUTE6
      , ATTRIBUTE7
      , ATTRIBUTE8
      , ATTRIBUTE9
      , ATTRIBUTE10
      , ATTRIBUTE11
      , ATTRIBUTE12
      , ATTRIBUTE13
      , ATTRIBUTE14
      , ATTRIBUTE15
      , GLOBAL_ATTRIBUTE_CATEGORY
      , GLOBAL_ATTRIBUTE1
      , GLOBAL_ATTRIBUTE2
      , GLOBAL_ATTRIBUTE3
      , GLOBAL_ATTRIBUTE4
      , GLOBAL_ATTRIBUTE5
      , GLOBAL_ATTRIBUTE6
      , GLOBAL_ATTRIBUTE7
      , GLOBAL_ATTRIBUTE8
      , GLOBAL_ATTRIBUTE9
      , GLOBAL_ATTRIBUTE10
      , GLOBAL_ATTRIBUTE11
      , GLOBAL_ATTRIBUTE12
      , GLOBAL_ATTRIBUTE13
      , GLOBAL_ATTRIBUTE14
      , GLOBAL_ATTRIBUTE15
      , GLOBAL_ATTRIBUTE16
      , GLOBAL_ATTRIBUTE17
      , GLOBAL_ATTRIBUTE18
      , GLOBAL_ATTRIBUTE19
      , GLOBAL_ATTRIBUTE20
      , LINE_SELECTED_FOR_APPL_FLAG
      , PREPAY_APPL_REQUEST_ID
      , APPLICATION_ID
      , PRODUCT_TABLE
      , REFERENCE_KEY1
      , REFERENCE_KEY2
      , REFERENCE_KEY3
      , REFERENCE_KEY4
      , REFERENCE_KEY5
      , PURCHASING_CATEGORY_ID
      , COST_FACTOR_ID
      , CONTROL_AMOUNT
      , ASSESSABLE_VALUE
      , TOTAL_REC_TAX_AMOUNT
      , TOTAL_NREC_TAX_AMOUNT
      , TOTAL_REC_TAX_AMT_FUNCL_CURR
      , TOTAL_NREC_TAX_AMT_FUNCL_CURR
      , INCLUDED_TAX_AMOUNT
      , PRIMARY_INTENDED_USE
      , TAX_ALREADY_CALCULATED_FLAG
      , SHIP_TO_LOCATION_ID
      , PRODUCT_TYPE
      , PRODUCT_CATEGORY
      , PRODUCT_FISC_CLASSIFICATION
      , USER_DEFINED_FISC_CLASS
      , TRX_BUSINESS_CATEGORY
      , SUMMARY_TAX_LINE_ID
      , TAX_REGIME_CODE
      , TAX
      , TAX_JURISDICTION_CODE
      , TAX_STATUS_CODE
      , TAX_RATE_ID
      , TAX_RATE_CODE
      , TAX_RATE
      , TAX_CODE_ID
      , HISTORICAL_FLAG
      , TAX_CLASSIFICATION_CODE
      , SOURCE_APPLICATION_ID
      , SOURCE_EVENT_CLASS_CODE
      , SOURCE_ENTITY_CODE
      , SOURCE_TRX_ID
      , SOURCE_LINE_ID
      , SOURCE_TRX_LEVEL_TYPE
      , RETAINED_AMOUNT
      , RETAINED_AMOUNT_REMAINING
      , RETAINED_INVOICE_ID
      , RETAINED_LINE_NUMBER
      , LINE_SELECTED_FOR_RELEASE_FLAG
      , LINE_OWNER_ROLE
      , DISPUTABLE_FLAG
      , RCV_SHIPMENT_LINE_ID
      , AIL_INVOICE_ID
      , AIL_DISTRIBUTION_LINE_NUMBER
      , AIL_INVOICE_ID2
      , AIL_DISTRIBUTION_LINE_NUMBER2
      , AIL_INVOICE_ID3
      , AIL_DISTRIBUTION_LINE_NUMBER3
      , AIL_INVOICE_ID4
      , PAY_AWT_GROUP_ID
      , MERCHANT_NAME_1
      , PSA_DELETE_IND
      , PSA_LOAD_DTS
      , PSA_RECORD_SOURCE
      , _FIVETRAN_SYNCED
      , _FIVETRAN_ID
      , _FIVETRAN_DELETED
      , LOAD_DTS
      , REC_SRC
      , BKCC
      , HASHDIFF
    FROM SRC_SRC
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM LOGIC_SRC
)

---- FINAL LAYER ----
SELECT
          SUPPLIER_INVOICE_LINE_HK
        , INVOICE_ID
        , LINE_NUMBER
        , LINE_TYPE_LOOKUP_CODE
        , REQUESTER_ID
        , DESCRIPTION
        , LINE_SOURCE
        , ORG_ID
        , LINE_GROUP_NUMBER
        , INVENTORY_ITEM_ID
        , ITEM_DESCRIPTION
        , SERIAL_NUMBER
        , MANUFACTURER
        , MODEL_NUMBER
        , WARRANTY_NUMBER
        , GENERATE_DISTS
        , MATCH_TYPE
        , DISTRIBUTION_SET_ID
        , ACCOUNT_SEGMENT
        , BALANCING_SEGMENT
        , COST_CENTER_SEGMENT
        , OVERLAY_DIST_CODE_CONCAT
        , DEFAULT_DIST_CCID
        , PRORATE_ACROSS_ALL_ITEMS
        , ACCOUNTING_DATE
        , PERIOD_NAME
        , DEFERRED_ACCTG_FLAG
        , DEF_ACCTG_START_DATE
        , DEF_ACCTG_END_DATE
        , DEF_ACCTG_NUMBER_OF_PERIODS
        , DEF_ACCTG_PERIOD_TYPE
        , SET_OF_BOOKS_ID
        , AMOUNT
        , BASE_AMOUNT
        , ROUNDING_AMT
        , QUANTITY_INVOICED
        , UNIT_MEAS_LOOKUP_CODE
        , UNIT_PRICE
        , WFAPPROVAL_STATUS
        , USSGL_TRANSACTION_CODE
        , DISCARDED_FLAG
        , ORIGINAL_AMOUNT
        , ORIGINAL_BASE_AMOUNT
        , ORIGINAL_ROUNDING_AMT
        , CANCELLED_FLAG
        , INCOME_TAX_REGION
        , TYPE_1099
        , STAT_AMOUNT
        , PREPAY_INVOICE_ID
        , PREPAY_LINE_NUMBER
        , INVOICE_INCLUDES_PREPAY_FLAG
        , CORRECTED_INV_ID
        , CORRECTED_LINE_NUMBER
        , PO_HEADER_ID
        , PO_LINE_ID
        , PO_RELEASE_ID
        , PO_LINE_LOCATION_ID
        , PO_DISTRIBUTION_ID
        , RCV_TRANSACTION_ID
        , FINAL_MATCH_FLAG
        , ASSETS_TRACKING_FLAG
        , ASSET_BOOK_TYPE_CODE
        , ASSET_CATEGORY_ID
        , PROJECT_ID
        , TASK_ID
        , EXPENDITURE_TYPE
        , EXPENDITURE_ITEM_DATE
        , EXPENDITURE_ORGANIZATION_ID
        , PA_QUANTITY
        , PA_CC_AR_INVOICE_ID
        , PA_CC_AR_INVOICE_LINE_NUM
        , PA_CC_PROCESSED_CODE
        , AWARD_ID
        , AWT_GROUP_ID
        , REFERENCE_1
        , REFERENCE_2
        , RECEIPT_VERIFIED_FLAG
        , RECEIPT_REQUIRED_FLAG
        , RECEIPT_MISSING_FLAG
        , JUSTIFICATION
        , EXPENSE_GROUP
        , START_EXPENSE_DATE
        , END_EXPENSE_DATE
        , RECEIPT_CURRENCY_CODE
        , RECEIPT_CONVERSION_RATE
        , RECEIPT_CURRENCY_AMOUNT
        , DAILY_AMOUNT
        , WEB_PARAMETER_ID
        , ADJUSTMENT_REASON
        , MERCHANT_DOCUMENT_NUMBER
        , MERCHANT_REFERENCE
        , MERCHANT_TAX_REG_NUMBER
        , MERCHANT_TAXPAYER_ID
        , COUNTRY_OF_SUPPLY
        , CREDIT_CARD_TRX_ID
        , COMPANY_PREPAID_INVOICE_ID
        , CC_REVERSAL_FLAG
        , CREATION_DATE
        , CREATED_BY
        , LAST_UPDATED_BY
        , LAST_UPDATE_DATE
        , LAST_UPDATE_LOGIN
        , PROGRAM_APPLICATION_ID
        , PROGRAM_ID
        , PROGRAM_UPDATE_DATE
        , REQUEST_ID
        , ATTRIBUTE_CATEGORY
        , ATTRIBUTE1
        , ATTRIBUTE2
        , ATTRIBUTE3
        , ATTRIBUTE4
        , ATTRIBUTE5
        , ATTRIBUTE6
        , ATTRIBUTE7
        , ATTRIBUTE8
        , ATTRIBUTE9
        , ATTRIBUTE10
        , ATTRIBUTE11
        , ATTRIBUTE12
        , ATTRIBUTE13
        , ATTRIBUTE14
        , ATTRIBUTE15
        , GLOBAL_ATTRIBUTE_CATEGORY
        , GLOBAL_ATTRIBUTE1
        , GLOBAL_ATTRIBUTE2
        , GLOBAL_ATTRIBUTE3
        , GLOBAL_ATTRIBUTE4
        , GLOBAL_ATTRIBUTE5
        , GLOBAL_ATTRIBUTE6
        , GLOBAL_ATTRIBUTE7
        , GLOBAL_ATTRIBUTE8
        , GLOBAL_ATTRIBUTE9
        , GLOBAL_ATTRIBUTE10
        , GLOBAL_ATTRIBUTE11
        , GLOBAL_ATTRIBUTE12
        , GLOBAL_ATTRIBUTE13
        , GLOBAL_ATTRIBUTE14
        , GLOBAL_ATTRIBUTE15
        , GLOBAL_ATTRIBUTE16
        , GLOBAL_ATTRIBUTE17
        , GLOBAL_ATTRIBUTE18
        , GLOBAL_ATTRIBUTE19
        , GLOBAL_ATTRIBUTE20
        , LINE_SELECTED_FOR_APPL_FLAG
        , PREPAY_APPL_REQUEST_ID
        , APPLICATION_ID
        , PRODUCT_TABLE
        , REFERENCE_KEY1
        , REFERENCE_KEY2
        , REFERENCE_KEY3
        , REFERENCE_KEY4
        , REFERENCE_KEY5
        , PURCHASING_CATEGORY_ID
        , COST_FACTOR_ID
        , CONTROL_AMOUNT
        , ASSESSABLE_VALUE
        , TOTAL_REC_TAX_AMOUNT
        , TOTAL_NREC_TAX_AMOUNT
        , TOTAL_REC_TAX_AMT_FUNCL_CURR
        , TOTAL_NREC_TAX_AMT_FUNCL_CURR
        , INCLUDED_TAX_AMOUNT
        , PRIMARY_INTENDED_USE
        , TAX_ALREADY_CALCULATED_FLAG
        , SHIP_TO_LOCATION_ID
        , PRODUCT_TYPE
        , PRODUCT_CATEGORY
        , PRODUCT_FISC_CLASSIFICATION
        , USER_DEFINED_FISC_CLASS
        , TRX_BUSINESS_CATEGORY
        , SUMMARY_TAX_LINE_ID
        , TAX_REGIME_CODE
        , TAX
        , TAX_JURISDICTION_CODE
        , TAX_STATUS_CODE
        , TAX_RATE_ID
        , TAX_RATE_CODE
        , TAX_RATE
        , TAX_CODE_ID
        , HISTORICAL_FLAG
        , TAX_CLASSIFICATION_CODE
        , SOURCE_APPLICATION_ID
        , SOURCE_EVENT_CLASS_CODE
        , SOURCE_ENTITY_CODE
        , SOURCE_TRX_ID
        , SOURCE_LINE_ID
        , SOURCE_TRX_LEVEL_TYPE
        , RETAINED_AMOUNT
        , RETAINED_AMOUNT_REMAINING
        , RETAINED_INVOICE_ID
        , RETAINED_LINE_NUMBER
        , LINE_SELECTED_FOR_RELEASE_FLAG
        , LINE_OWNER_ROLE
        , DISPUTABLE_FLAG
        , RCV_SHIPMENT_LINE_ID
        , AIL_INVOICE_ID
        , AIL_DISTRIBUTION_LINE_NUMBER
        , AIL_INVOICE_ID2
        , AIL_DISTRIBUTION_LINE_NUMBER2
        , AIL_INVOICE_ID3
        , AIL_DISTRIBUTION_LINE_NUMBER3
        , AIL_INVOICE_ID4
        , PAY_AWT_GROUP_ID
        , MERCHANT_NAME_1
        , PSA_DELETE_IND
        , PSA_LOAD_DTS
        , PSA_RECORD_SOURCE
        , _FIVETRAN_SYNCED
        , _FIVETRAN_ID
        , _FIVETRAN_DELETED
        , LOAD_DTS
        , REC_SRC
        , BKCC
        , HASHDIFF
FROM JOIN_RESULT
{% if is_incremental() %}
WHERE NOT EXISTS (
    SELECT 1
    FROM {{ this }} existing
    WHERE existing.SUPPLIER_INVOICE_LINE_HK = JOIN_RESULT.SUPPLIER_INVOICE_LINE_HK
      AND existing.HASHDIFF = JOIN_RESULT.HASHDIFF
)
{% endif %}
{% if not is_incremental() %}

/* The following qualifier is implemented to prevent multiple loads of touched records during the initial build, such as multiple rows per HK and hashdiff. */
qualify 1 = row_number() over (partition by SUPPLIER_INVOICE_LINE_HK, HASHDIFF order by PSA_LOAD_DTS)

union all
SELECT 
MD5_BINARY(GR.VALUE) AS SUPPLIER_INVOICE_LINE_HK,
NULL AS INVOICE_ID,
NULL AS LINE_NUMBER,
NULL AS LINE_TYPE_LOOKUP_CODE,
NULL AS REQUESTER_ID,
NULL AS DESCRIPTION,
NULL AS LINE_SOURCE,
NULL AS ORG_ID,
NULL AS LINE_GROUP_NUMBER,
NULL AS INVENTORY_ITEM_ID,
NULL AS ITEM_DESCRIPTION,
NULL AS SERIAL_NUMBER,
NULL AS MANUFACTURER,
NULL AS MODEL_NUMBER,
NULL AS WARRANTY_NUMBER,
NULL AS GENERATE_DISTS,
NULL AS MATCH_TYPE,
NULL AS DISTRIBUTION_SET_ID,
NULL AS ACCOUNT_SEGMENT,
NULL AS BALANCING_SEGMENT,
NULL AS COST_CENTER_SEGMENT,
NULL AS OVERLAY_DIST_CODE_CONCAT,
NULL AS DEFAULT_DIST_CCID,
NULL AS PRORATE_ACROSS_ALL_ITEMS,
NULL AS ACCOUNTING_DATE,
NULL AS PERIOD_NAME,
NULL AS DEFERRED_ACCTG_FLAG,
NULL AS DEF_ACCTG_START_DATE,
NULL AS DEF_ACCTG_END_DATE,
NULL AS DEF_ACCTG_NUMBER_OF_PERIODS,
NULL AS DEF_ACCTG_PERIOD_TYPE,
NULL AS SET_OF_BOOKS_ID,
NULL AS AMOUNT,
NULL AS BASE_AMOUNT,
NULL AS ROUNDING_AMT,
NULL AS QUANTITY_INVOICED,
NULL AS UNIT_MEAS_LOOKUP_CODE,
NULL AS UNIT_PRICE,
NULL AS WFAPPROVAL_STATUS,
NULL AS USSGL_TRANSACTION_CODE,
NULL AS DISCARDED_FLAG,
NULL AS ORIGINAL_AMOUNT,
NULL AS ORIGINAL_BASE_AMOUNT,
NULL AS ORIGINAL_ROUNDING_AMT,
NULL AS CANCELLED_FLAG,
NULL AS INCOME_TAX_REGION,
NULL AS TYPE_1099,
NULL AS STAT_AMOUNT,
NULL AS PREPAY_INVOICE_ID,
NULL AS PREPAY_LINE_NUMBER,
NULL AS INVOICE_INCLUDES_PREPAY_FLAG,
NULL AS CORRECTED_INV_ID,
NULL AS CORRECTED_LINE_NUMBER,
NULL AS PO_HEADER_ID,
NULL AS PO_LINE_ID,
NULL AS PO_RELEASE_ID,
NULL AS PO_LINE_LOCATION_ID,
NULL AS PO_DISTRIBUTION_ID,
NULL AS RCV_TRANSACTION_ID,
NULL AS FINAL_MATCH_FLAG,
NULL AS ASSETS_TRACKING_FLAG,
NULL AS ASSET_BOOK_TYPE_CODE,
NULL AS ASSET_CATEGORY_ID,
NULL AS PROJECT_ID,
NULL AS TASK_ID,
NULL AS EXPENDITURE_TYPE,
NULL AS EXPENDITURE_ITEM_DATE,
NULL AS EXPENDITURE_ORGANIZATION_ID,
NULL AS PA_QUANTITY,
NULL AS PA_CC_AR_INVOICE_ID,
NULL AS PA_CC_AR_INVOICE_LINE_NUM,
NULL AS PA_CC_PROCESSED_CODE,
NULL AS AWARD_ID,
NULL AS AWT_GROUP_ID,
NULL AS REFERENCE_1,
NULL AS REFERENCE_2,
NULL AS RECEIPT_VERIFIED_FLAG,
NULL AS RECEIPT_REQUIRED_FLAG,
NULL AS RECEIPT_MISSING_FLAG,
NULL AS JUSTIFICATION,
NULL AS EXPENSE_GROUP,
NULL AS START_EXPENSE_DATE,
NULL AS END_EXPENSE_DATE,
NULL AS RECEIPT_CURRENCY_CODE,
NULL AS RECEIPT_CONVERSION_RATE,
NULL AS RECEIPT_CURRENCY_AMOUNT,
NULL AS DAILY_AMOUNT,
NULL AS WEB_PARAMETER_ID,
NULL AS ADJUSTMENT_REASON,
NULL AS MERCHANT_DOCUMENT_NUMBER,
NULL AS MERCHANT_REFERENCE,
NULL AS MERCHANT_TAX_REG_NUMBER,
NULL AS MERCHANT_TAXPAYER_ID,
NULL AS COUNTRY_OF_SUPPLY,
NULL AS CREDIT_CARD_TRX_ID,
NULL AS COMPANY_PREPAID_INVOICE_ID,
NULL AS CC_REVERSAL_FLAG,
NULL AS CREATION_DATE,
NULL AS CREATED_BY,
NULL AS LAST_UPDATED_BY,
NULL AS LAST_UPDATE_DATE,
NULL AS LAST_UPDATE_LOGIN,
NULL AS PROGRAM_APPLICATION_ID,
NULL AS PROGRAM_ID,
NULL AS PROGRAM_UPDATE_DATE,
NULL AS REQUEST_ID,
NULL AS ATTRIBUTE_CATEGORY,
NULL AS ATTRIBUTE1,
NULL AS ATTRIBUTE2,
NULL AS ATTRIBUTE3,
NULL AS ATTRIBUTE4,
NULL AS ATTRIBUTE5,
NULL AS ATTRIBUTE6,
NULL AS ATTRIBUTE7,
NULL AS ATTRIBUTE8,
NULL AS ATTRIBUTE9,
NULL AS ATTRIBUTE10,
NULL AS ATTRIBUTE11,
NULL AS ATTRIBUTE12,
NULL AS ATTRIBUTE13,
NULL AS ATTRIBUTE14,
NULL AS ATTRIBUTE15,
NULL AS GLOBAL_ATTRIBUTE_CATEGORY,
NULL AS GLOBAL_ATTRIBUTE1,
NULL AS GLOBAL_ATTRIBUTE2,
NULL AS GLOBAL_ATTRIBUTE3,
NULL AS GLOBAL_ATTRIBUTE4,
NULL AS GLOBAL_ATTRIBUTE5,
NULL AS GLOBAL_ATTRIBUTE6,
NULL AS GLOBAL_ATTRIBUTE7,
NULL AS GLOBAL_ATTRIBUTE8,
NULL AS GLOBAL_ATTRIBUTE9,
NULL AS GLOBAL_ATTRIBUTE10,
NULL AS GLOBAL_ATTRIBUTE11,
NULL AS GLOBAL_ATTRIBUTE12,
NULL AS GLOBAL_ATTRIBUTE13,
NULL AS GLOBAL_ATTRIBUTE14,
NULL AS GLOBAL_ATTRIBUTE15,
NULL AS GLOBAL_ATTRIBUTE16,
NULL AS GLOBAL_ATTRIBUTE17,
NULL AS GLOBAL_ATTRIBUTE18,
NULL AS GLOBAL_ATTRIBUTE19,
NULL AS GLOBAL_ATTRIBUTE20,
NULL AS LINE_SELECTED_FOR_APPL_FLAG,
NULL AS PREPAY_APPL_REQUEST_ID,
NULL AS APPLICATION_ID,
NULL AS PRODUCT_TABLE,
NULL AS REFERENCE_KEY1,
NULL AS REFERENCE_KEY2,
NULL AS REFERENCE_KEY3,
NULL AS REFERENCE_KEY4,
NULL AS REFERENCE_KEY5,
NULL AS PURCHASING_CATEGORY_ID,
NULL AS COST_FACTOR_ID,
NULL AS CONTROL_AMOUNT,
NULL AS ASSESSABLE_VALUE,
NULL AS TOTAL_REC_TAX_AMOUNT,
NULL AS TOTAL_NREC_TAX_AMOUNT,
NULL AS TOTAL_REC_TAX_AMT_FUNCL_CURR,
NULL AS TOTAL_NREC_TAX_AMT_FUNCL_CURR,
NULL AS INCLUDED_TAX_AMOUNT,
NULL AS PRIMARY_INTENDED_USE,
NULL AS TAX_ALREADY_CALCULATED_FLAG,
NULL AS SHIP_TO_LOCATION_ID,
NULL AS PRODUCT_TYPE,
NULL AS PRODUCT_CATEGORY,
NULL AS PRODUCT_FISC_CLASSIFICATION,
NULL AS USER_DEFINED_FISC_CLASS,
NULL AS TRX_BUSINESS_CATEGORY,
NULL AS SUMMARY_TAX_LINE_ID,
NULL AS TAX_REGIME_CODE,
NULL AS TAX,
NULL AS TAX_JURISDICTION_CODE,
NULL AS TAX_STATUS_CODE,
NULL AS TAX_RATE_ID,
NULL AS TAX_RATE_CODE,
NULL AS TAX_RATE,
NULL AS TAX_CODE_ID,
NULL AS HISTORICAL_FLAG,
NULL AS TAX_CLASSIFICATION_CODE,
NULL AS SOURCE_APPLICATION_ID,
NULL AS SOURCE_EVENT_CLASS_CODE,
NULL AS SOURCE_ENTITY_CODE,
NULL AS SOURCE_TRX_ID,
NULL AS SOURCE_LINE_ID,
NULL AS SOURCE_TRX_LEVEL_TYPE,
NULL AS RETAINED_AMOUNT,
NULL AS RETAINED_AMOUNT_REMAINING,
NULL AS RETAINED_INVOICE_ID,
NULL AS RETAINED_LINE_NUMBER,
NULL AS LINE_SELECTED_FOR_RELEASE_FLAG,
NULL AS LINE_OWNER_ROLE,
NULL AS DISPUTABLE_FLAG,
NULL AS RCV_SHIPMENT_LINE_ID,
NULL AS AIL_INVOICE_ID,
NULL AS AIL_DISTRIBUTION_LINE_NUMBER,
NULL AS AIL_INVOICE_ID2,
NULL AS AIL_DISTRIBUTION_LINE_NUMBER2,
NULL AS AIL_INVOICE_ID3,
NULL AS AIL_DISTRIBUTION_LINE_NUMBER3,
NULL AS AIL_INVOICE_ID4,
NULL AS PAY_AWT_GROUP_ID,
NULL AS MERCHANT_NAME_1,
'N' AS PSA_DELETE_IND,
'1900-01-01'::TIMESTAMP AS PSA_LOAD_DTS,
NULL AS PSA_RECORD_SOURCE,
NULL AS _FIVETRAN_SYNCED,
NULL AS _FIVETRAN_ID,
NULL AS _FIVETRAN_DELETED,
'1900-01-01T00:00:00'::TIMESTAMP_NTZ AS LOAD_DTS,
'USAZET.SNOWFLAKE.FBIN.DERIVED' AS REC_SRC,
DECODE(GR.VALUE, 0, 'GHOST RECORD-SYSTEM', -1, 'GHOST RECORD-nullkey-required', -2, 'GHOST RECORD-nullkey-optional') AS BKCC,
MD5_BINARY('') AS HASHDIFF
FROM
TABLE(strtok_split_to_table('0|-1|-2', '|')) AS GR
{% endif %}
