{%- set source_model = "stg_purchase_order__emtk_ebs_po" -%}
{%- set src_pk = "purchase_order_hk" -%}
{%- set src_hashdiff = "purchase_order_hdiff" -%}
{%- set src_payload = [ 
  'org_id',
  'poh_segment1',
  'brand',  
  'sup_segment1',
  'vendor_site_id',
  'po_header_id',
  'agent_id',
  'full_name',
  'type_lookup_code',
  'last_update_date',
  'last_updated_by',
  'last_update_login',
  'creation_date',
  'created_by',
  'vendor_id',
  'vendor_contact_id',
  'ship_to_location_id',
  'bill_to_location_id',
  'terms_id',
  'fob_lookup_code',
  'freight_terms_lookup_code',
  'rate_date',
  'from_header_id',
  'start_date',
  'authorization_status',
  'revision_num',
  'revised_date',
  'approved_flag',
  'approved_date',
  'note_to_vendor',
  'note_to_receiver',
  'print_count',
  'printed_date',
  'confirming_order_flag',
  'comments',
  'acceptance_required_flag',
  'closed_date',
  'user_hold_flag',
  'cancel_flag',
  'frozen_flag',
  'attribute15',
  'closed_code',
  'request_id',
  'program_application_id',
  'program_id',
  'program_update_date',
  'wf_item_key',
  'change_summary',
  'document_creation_method',
  'submit_date',
  'supplier_notif_method',
  'email_address',
  'clm_effective_date',
  'clm_document_number'] -%}
{%- set src_ldts = "load_dts" -%}
{%- set src_source = "rec_src" -%}

{{ automate_dv.sat(src_pk=src_pk, src_hashdiff=src_hashdiff,
                   src_payload=src_payload, src_eff=none,
                   src_ldts=src_ldts, src_source=src_source,
                   source_model=source_model) }}
