---- SRC LAYER ----
WITH
SRC_EU             as ( SELECT * FROM {{ ref('v_psa_stg_user_engagement_android_track_flo') }} as SRC 
                         {% if is_incremental() %}
                         WHERE SRC.LOAD_DTS > (SELECT DATEADD('HOUR', '-1', MAX(LOAD_DTS)) FROM {{this}})
                         {% endif %}  )

/*
SRC_EU             as ( SELECT * FROM staging.v_psa_stg_user_engagement_android_track_flo )
*/
---- LOGIC LAYER ----

, LOGIC_EU as (
    SELECT
        CONSUMER_HK
      , LOAD_DTS
      , CONTEXT_NETWORK_WIFI
      , CONTEXT_OS_VERSION
      , CONTEXT_TRAITS_USER_ID
      , CONTEXT_DEVICE_TOKEN
      , CONTEXT_LOCALE
      , CONTEXT_APP_BUILD
      , CONTEXT_APP_VERSION
      , CONTEXT_SCREEN_WIDTH
      , ID
      , ORIGINAL_TIMESTAMP
      , CONTEXT_NETWORK_BLUETOOTH
      , CONTEXT_NETWORK_CARRIER
      , CONTEXT_OS_NAME
      , CONTEXT_USER_AGENT
      , RECEIVED_AT
      , ANONYMOUS_ID
      , CONTEXT_APP_NAME
      , CONTEXT_DEVICE_ID
      , CONTEXT_LIBRARY_VERSION
      , CONTEXT_NETWORK_CELLULAR
      , CONTEXT_TIMEZONE
      , CONTEXT_TRAITS_ANONYMOUS_ID
      , TIMESTAMP
      , CONTEXT_DEVICE_ADVERTISING_ID
      , CONTEXT_DEVICE_MANUFACTURER
      , CONTEXT_DEVICE_MODEL
      , CONTEXT_DEVICE_TYPE
      , CONTEXT_SCREEN_HEIGHT
      , EVENT
      , USER_ID
      , CONTEXT_DEVICE_AD_TRACKING_ENABLED
      , CONTEXT_DEVICE_NAME
      , CONTEXT_IP
      , CONTEXT_SCREEN_DENSITY
      , CONTEXT_TRAITS_LAST_NAME
      , CONTEXT_LIBRARY_NAME
      , CONTEXT_TRAITS_FIRST_NAME
      , EVENT_TEXT
      , SENT_AT
      , UUID_TS
      , CONTEXT_APP_NAMESPACE
      , PSA_LOAD_DTS
      , PSA_RECORD_SOURCE
      , PSA_DELETE_IND
      , REC_SRC
      , HASHDIFF
    FROM SRC_EU
)
---- RENAME LAYER ----

, RENAME_EU as (
    SELECT
        CONSUMER_HK
      , LOAD_DTS
      , CONTEXT_NETWORK_WIFI
      , CONTEXT_OS_VERSION
      , CONTEXT_TRAITS_USER_ID
      , CONTEXT_DEVICE_TOKEN
      , CONTEXT_LOCALE
      , CONTEXT_APP_BUILD
      , CONTEXT_APP_VERSION
      , CONTEXT_SCREEN_WIDTH
      , ID
      , ORIGINAL_TIMESTAMP
      , CONTEXT_NETWORK_BLUETOOTH
      , CONTEXT_NETWORK_CARRIER
      , CONTEXT_OS_NAME
      , CONTEXT_USER_AGENT
      , RECEIVED_AT
      , ANONYMOUS_ID
      , CONTEXT_APP_NAME
      , CONTEXT_DEVICE_ID
      , CONTEXT_LIBRARY_VERSION
      , CONTEXT_NETWORK_CELLULAR
      , CONTEXT_TIMEZONE
      , CONTEXT_TRAITS_ANONYMOUS_ID
      , TIMESTAMP
      , CONTEXT_DEVICE_ADVERTISING_ID
      , CONTEXT_DEVICE_MANUFACTURER
      , CONTEXT_DEVICE_MODEL
      , CONTEXT_DEVICE_TYPE
      , CONTEXT_SCREEN_HEIGHT
      , EVENT
      , USER_ID
      , CONTEXT_DEVICE_AD_TRACKING_ENABLED
      , CONTEXT_DEVICE_NAME
      , CONTEXT_IP
      , CONTEXT_SCREEN_DENSITY
      , CONTEXT_TRAITS_LAST_NAME
      , CONTEXT_LIBRARY_NAME
      , CONTEXT_TRAITS_FIRST_NAME
      , EVENT_TEXT
      , SENT_AT
      , UUID_TS
      , CONTEXT_APP_NAMESPACE
      , PSA_LOAD_DTS
      , PSA_RECORD_SOURCE
      , PSA_DELETE_IND
      , REC_SRC
      , HASHDIFF
    FROM LOGIC_EU
)
---- FILTER LAYER ----

, FILTER_EU as (
    SELECT *
    FROM RENAME_EU
)
---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT * FROM FILTER_EU
)

---- FINAL LAYER ----
SELECT
          CONSUMER_HK
        , LOAD_DTS
        , CONTEXT_NETWORK_WIFI
        , CONTEXT_OS_VERSION
        , CONTEXT_TRAITS_USER_ID
        , CONTEXT_DEVICE_TOKEN
        , CONTEXT_LOCALE
        , CONTEXT_APP_BUILD
        , CONTEXT_APP_VERSION
        , CONTEXT_SCREEN_WIDTH
        , ID
        , ORIGINAL_TIMESTAMP
        , CONTEXT_NETWORK_BLUETOOTH
        , CONTEXT_NETWORK_CARRIER
        , CONTEXT_OS_NAME
        , CONTEXT_USER_AGENT
        , RECEIVED_AT
        , ANONYMOUS_ID
        , CONTEXT_APP_NAME
        , CONTEXT_DEVICE_ID
        , CONTEXT_LIBRARY_VERSION
        , CONTEXT_NETWORK_CELLULAR
        , CONTEXT_TIMEZONE
        , CONTEXT_TRAITS_ANONYMOUS_ID
        , TIMESTAMP
        , CONTEXT_DEVICE_ADVERTISING_ID
        , CONTEXT_DEVICE_MANUFACTURER
        , CONTEXT_DEVICE_MODEL
        , CONTEXT_DEVICE_TYPE
        , CONTEXT_SCREEN_HEIGHT
        , EVENT
        , USER_ID
        , CONTEXT_DEVICE_AD_TRACKING_ENABLED
        , CONTEXT_DEVICE_NAME
        , CONTEXT_IP
        , CONTEXT_SCREEN_DENSITY
        , CONTEXT_TRAITS_LAST_NAME
        , CONTEXT_LIBRARY_NAME
        , CONTEXT_TRAITS_FIRST_NAME
        , EVENT_TEXT
        , SENT_AT
        , UUID_TS
        , CONTEXT_APP_NAMESPACE
        , PSA_LOAD_DTS
        , PSA_RECORD_SOURCE
        , PSA_DELETE_IND
        , REC_SRC
        , HASHDIFF
FROM JOIN_RESULT
{% if is_incremental() %}
WHERE NOT EXISTS (
    SELECT 1 
    FROM {{ this }} existing
    WHERE existing.CONSUMER_HK = JOIN_RESULT.CONSUMER_HK
    AND existing.HASHDIFF = JOIN_RESULT.HASHDIFF
)
{% endif %}
{% if not is_incremental() %}

/* The following qualifier is implemented to prevent multiple loads of touched records during the initial build, such as multiple rows per HK and hashdiff. */
qualify 1 = row_number() over (partition by CONSUMER_HK, HASHDIFF order by PSA_LOAD_DTS)

union all
SELECT 
MD5_BINARY(GR.VALUE) AS CONSUMER_HK,
CONVERT_TIMEZONE('UTC','1900-01-01'::TIMESTAMP) AS LOAD_DTS,
NULL AS CONTEXT_NETWORK_WIFI,
NULL AS CONTEXT_OS_VERSION,
NULL AS CONTEXT_TRAITS_USER_ID,
NULL AS CONTEXT_DEVICE_TOKEN,
NULL AS CONTEXT_LOCALE,
NULL AS CONTEXT_APP_BUILD,
NULL AS CONTEXT_APP_VERSION,
NULL AS CONTEXT_SCREEN_WIDTH,
NULL AS ID,
NULL AS ORIGINAL_TIMESTAMP,
NULL AS CONTEXT_NETWORK_BLUETOOTH,
NULL AS CONTEXT_NETWORK_CARRIER,
NULL AS CONTEXT_OS_NAME,
NULL AS CONTEXT_USER_AGENT,
NULL AS RECEIVED_AT,
GR.VALUE::text AS ANONYMOUS_ID,
NULL AS CONTEXT_APP_NAME,
NULL AS CONTEXT_DEVICE_ID,
NULL AS CONTEXT_LIBRARY_VERSION,
NULL AS CONTEXT_NETWORK_CELLULAR,
NULL AS CONTEXT_TIMEZONE,
GR.VALUE::text AS CONTEXT_TRAITS_ANONYMOUS_ID,
'1900-01-01'::timestamp_ntz(9) AS TIMESTAMP,
NULL AS CONTEXT_DEVICE_ADVERTISING_ID,
NULL AS CONTEXT_DEVICE_MANUFACTURER,
NULL AS CONTEXT_DEVICE_MODEL,
NULL AS CONTEXT_DEVICE_TYPE,
NULL AS CONTEXT_SCREEN_HEIGHT,
GR.VALUE::text AS EVENT,
NULL AS USER_ID,
NULL AS CONTEXT_DEVICE_AD_TRACKING_ENABLED,
NULL AS CONTEXT_DEVICE_NAME,
NULL AS CONTEXT_IP,
NULL AS CONTEXT_SCREEN_DENSITY,
NULL AS CONTEXT_TRAITS_LAST_NAME,
NULL AS CONTEXT_LIBRARY_NAME,
NULL AS CONTEXT_TRAITS_FIRST_NAME,
NULL AS EVENT_TEXT,
NULL AS SENT_AT,
NULL AS UUID_TS,
NULL AS CONTEXT_APP_NAMESPACE,
'1900-01-01'::TIMESTAMP AS PSA_LOAD_DTS,
NULL AS PSA_RECORD_SOURCE,
'N' AS PSA_DELETE_IND,
'USAZET.SNOWFLAKE.FBIN.DERIVED' AS REC_SRC,
''::BINARY AS HASHDIFF
FROM
TABLE(strtok_split_to_table('0|-1|-2', '|')) AS GR
{% endif %}
