---- SRC LAYER ----
WITH
SRC_SFIB           as ( SELECT * FROM {{ ref('v_psa_stg_supplier_site__fib_ocf') }} as SRC 
                         {% if is_incremental() %}
                         WHERE SRC.LOAD_DTS > (SELECT DATEADD('HOUR', '-1', MAX(LOAD_DTS)) FROM {{this}})
                         {% endif %}  )

/*
SRC_SFIB           as ( SELECT * FROM STAGING.v_psa_stg_supplier_site__fib_ocf )
*/
---- LOGIC LAYER ----

, LOGIC_SFIB as (
    SELECT
        SUPPLIER_SITE_HK
      , VENDOR_SITE_ID
      , VENDOR_ID
      , FAX
      , PHONE
      , AREA_CODE
      , ATTRIBUTE_8
      , RETAINAGE_RATE
      , GLOBAL_ATTRIBUTE_11
      , PAY_ON_USE_FLAG
      , GLOBAL_ATTRIBUTE_17
      , ATTRIBUTE_14
      , VENDOR_SITE_CODE
      , B_2_B_SITE_CODE
      , OFFSET_TAX_FLAG
      , PCARD_SITE_FLAG
      , GLOBAL_ATTRIBUTE_8
      , GLOBAL_ATTRIBUTE_NUMBER_6
      , FOB_LOOKUP_CODE
      , ALLOW_SUBSTITUTE_RECEIPTS_FLAG
      , GLOBAL_ATTRIBUTE_15
      , GLOBAL_ATTRIBUTE_19
      , ATTRIBUTE_DATE_3
      , GLOBAL_ATTRIBUTE_20
      , EXCLUDE_TAX_FROM_DISCOUNT
      , ATTRIBUTE_17
      , PURCHASING_SITE_FLAG
      , CARRIER_ID
      , AP_TAX_ROUNDING_RULE
      , EFFECTIVE_SEQUENCE
      , GLOBAL_ATTRIBUTE_NUMBER_2
      , RECEIVING_ROUTING_ID
      , ATTRIBUTE_11
      , ECE_TP_LOCATION_CODE
      , PAY_GROUP_LOOKUP_CODE
      , LAST_UPDATE_LOGIN
      , OFFSET_VAT_CODE
      , HOLD_ALL_PAYMENTS_FLAG
      , PARTY_SITE_ID
      , INVOICE_CHANNEL
      , GLOBAL_ATTRIBUTE_2
      , TOLERANCE_ID
      , ATTRIBUTE_NUMBER_10
      , ATTRIBUTE_DATE_6
      , GLOBAL_ATTRIBUTE_NUMBER_5
      , ATTRIBUTE_NUMBER_4
      , GLOBAL_ATTRIBUTE_NUMBER_7
      , GLOBAL_ATTRIBUTE_6
      , GLOBAL_ATTRIBUTE_4
      , PROGRAM_APPLICATION_ID
      , ATTRIBUTE_6
      , EXCLUDE_FREIGHT_FROM_DISCOUNT
      , DAYS_LATE_RECEIPT_ALLOWED
      , ATTRIBUTE_NUMBER_8
      , ATTRIBUTE_4
      , ATTRIBUTE_TIMESTAMP_10
      , TAX_REPORTING_SITE_FLAG
      , GLOBAL_ATTRIBUTE_1
      , PAY_SITE_FLAG
      , TERMS_DATE_BASIS
      , ATTRIBUTE_1
      , HOLD_FLAG
      , ATTRIBUTE_TIMESTAMP_9
      , ATTRIBUTE_NUMBER_3
      , CUSTOMER_NUM
      , PAY_ON_CODE
      , ALLOW_UNORDERED_RECEIPTS_FLAG
      , B_2_B_COMM_METHOD_CODE
      , INSPECTION_REQUIRED_FLAG
      , VENDOR_SITE_SPK_ID
      , ATTRIBUTE_TIMESTAMP_7
      , GAPLESS_INV_NUM_FLAG
      , RECEIPT_REQUIRED_FLAG
      , TERMS_ID
      , ATTRIBUTE_DATE_7
      , OVERRIDE_B_2_B_COMM_CODE
      , PRIMARY_PAY_SITE_FLAG
      , GLOBAL_ATTRIBUTE_TIMESTAMP_1
      , GLOBAL_ATTRIBUTE_NUMBER_4
      , GLOBAL_ATTRIBUTE_12
      , HOLD_UNMATCHED_INVOICES_FLAG
      , GLOBAL_ATTRIBUTE_10
      , ATTRIBUTE_DATE_5
      , HOLD_DATE
      , HOLD_FUTURE_PAYMENTS_FLAG
      , JOB_DEFINITION_NAME
      , PAY_ON_RECEIPT_SUMMARY_CODE
      , AGING_ONSET_POINT
      , QTY_RCV_EXCEPTION_CODE
      , GLOBAL_ATTRIBUTE_TIMESTAMP_4
      , AUTO_TAX_CALC_FLAG
      , ATTRIBUTE_15
      , ATTRIBUTE_7
      , OBJECT_VERSION_NUMBER
      , ATTRIBUTE_2
      , JOB_DEFINITION_PACKAGE
      , INVOICE_CURRENCY_CODE
      , GLOBAL_ATTRIBUTE_13
      , RECEIPT_DAYS_EXCEPTION_CODE
      , SERVICES_TOLERANCE_ID
      , TELEX
      , SERVICE_LEVEL
      , CONSUMPTION_ADVICE_FREQUENCY
      , GLOBAL_ATTRIBUTE_DATE_2
      , GLOBAL_ATTRIBUTE_NUMBER_1
      , ATTRIBUTE_NUMBER_2
      , ATTRIBUTE_NUMBER_7
      , GLOBAL_ATTRIBUTE_NUMBER_3
      , GLOBAL_ATTRIBUTE_TIMESTAMP_3
      , INVOICE_AMOUNT_LIMIT
      , BANK_CHARGE_BEARER
      , GLOBAL_ATTRIBUTE_TIMESTAMP_8
      , GLOBAL_ATTRIBUTE_TIMESTAMP_10
      , INACTIVE_DATE
      , PAY_DATE_BASIS_LOOKUP_CODE
      , GLOBAL_ATTRIBUTE_DATE_7
      , ATTRIBUTE_DATE_10
      , BANK_CHARGE_DEDUCTION_TYPE
      , GLOBAL_ATTRIBUTE_7
      , ATTRIBUTE_DATE_4
      , GLOBAL_ATTRIBUTE_DATE_10
      , HOLD_REASON
      , CREATION_DATE
      , GLOBAL_ATTRIBUTE_DATE_3
      , GLOBAL_ATTRIBUTE_NUMBER_10
      , ATTRIBUTE_18
      , SHIPPING_CONTROL
      , LAST_UPDATE_DATE
      , ATTRIBUTE_NUMBER_5
      , AMOUNT_INCLUDES_TAX_FLAG
      , ALWAYS_TAKE_DISC_FLAG
      , VAT_REGISTRATION_NUM
      , ATTRIBUTE_NUMBER_6
      , DEFAULT_PAY_SITE_ID
      , AUTO_CALCULATE_INTEREST_FLAG
      , MODE_OF_TRANSPORT
      , ATTRIBUTE_TIMESTAMP_6
      , SELLING_COMPANY_IDENTIFIER
      , MATCH_OPTION
      , HOLD_BY
      , DAYS_EARLY_RECEIPT_ALLOWED
      , ATTRIBUTE_TIMESTAMP_2
      , GLOBAL_ATTRIBUTE_DATE_5
      , BUYER_MANAGED_TRANSPORT_FLAG
      , GLOBAL_ATTRIBUTE_TIMESTAMP_2
      , SUPPLIER_NOTIF_METHOD
      , GLOBAL_ATTRIBUTE_DATE_6
      , ATTRIBUTE_TIMESTAMP_1
      , COUNTRY_OF_ORIGIN_CODE
      , CONSUMPTION_ADVICE_SUMMARY
      , ATTRIBUTE_NUMBER_9
      , GLOBAL_ATTRIBUTE_DATE_8
      , PHONE_COUNTRY_CODE
      , VAT_CODE
      , QTY_RCV_TOLERANCE
      , GLOBAL_ATTRIBUTE_NUMBER_8
      , AUTO_TAX_CALC_OVERRIDE
      , SHIP_VIA_LOOKUP_CODE
      , VENDOR_SITE_CODE_ALT
      , GLOBAL_ATTRIBUTE_9
      , ATTRIBUTE_TIMESTAMP_5
      , GLOBAL_ATTRIBUTE_5
      , GLOBAL_ATTRIBUTE_NUMBER_9
      , CREATED_BY
      , GLOBAL_ATTRIBUTE_DATE_9
      , ATTRIBUTE_13
      , GLOBAL_ATTRIBUTE_18
      , GLOBAL_ATTRIBUTE_TIMESTAMP_7
      , GLOBAL_ATTRIBUTE_14
      , PO_ACK_REQD_CODE
      , PURCHASING_HOLD_REASON
      , ATTRIBUTE_16
      , ATTRIBUTE_20
      , ATTRIBUTE_CATEGORY
      , ATTRIBUTE_9
      , ATTRIBUTE_19
      , EFFECTIVE_END_DATE
      , EMAIL_ADDRESS
      , FAX_COUNTRY_CODE
      , ATTRIBUTE_DATE_1
      , PAYMENT_PRIORITY
      , EFFECTIVE_START_DATE
      , FREIGHT_TERMS_LOOKUP_CODE
      , CREATE_DEBIT_MEMO_FLAG
      , TAX_COUNTRY_CODE
      , ATTENTION_AR_FLAG
      , PAYMENT_HOLD_DATE
      , TP_HEADER_ID
      , LOCATION_ID
      , REQUEST_ID
      , ATTRIBUTE_DATE_2
      , GLOBAL_ATTRIBUTE_DATE_4
      , ATTRIBUTE_3
      , ATTRIBUTE_NUMBER_1
      , ATTRIBUTE_5
      , GLOBAL_ATTRIBUTE_CATEGORY
      , GLOBAL_ATTRIBUTE_3
      , ATTRIBUTE_10
      , GLOBAL_ATTRIBUTE_TIMESTAMP_5
      , ATTRIBUTE_TIMESTAMP_4
      , PROGRAM_ID
      , PAYMENT_CURRENCY_CODE
      , ATTRIBUTE_12
      , GLOBAL_ATTRIBUTE_DATE_1
      , PRC_BU_ID
      , ENFORCE_SHIP_TO_LOCATION_CODE
      , ATTRIBUTE_DATE_8
      , GLOBAL_ATTRIBUTE_TIMESTAMP_6
      , GLOBAL_ATTRIBUTE_16
      , PROGRAM_UPDATE_DATE
      , EFFECTIVE_LATEST_CHANGE
      , PHONE_EXTENSION
      , LAST_UPDATED_BY
      , FAX_AREA_CODE
      , AGING_PERIOD_DAYS
      , ATTRIBUTE_TIMESTAMP_8
      , ATTRIBUTE_DATE_9
      , PO_ACK_REQD_DAYS
      , GLOBAL_ATTRIBUTE_TIMESTAMP_9
      , SHIPPING_NETWORK_LOCATION
      , ATTRIBUTE_TIMESTAMP_3
      , RFQ_ONLY_SITE_FLAG
      , _FIVETRAN_DELETED
      , _FIVETRAN_SYNCED
      , PSA_RECORD_SOURCE
      , PSA_LOAD_DTS
      , PSA_DELETE_IND
      , LOAD_DTS
      , BKCC
      , REC_SRC
      , HASHDIFF
    FROM SRC_SFIB
)
---- RENAME LAYER ----

, RENAME_SFIB as (
    SELECT
        SUPPLIER_SITE_HK
      , VENDOR_SITE_ID
      , VENDOR_ID
      , FAX
      , PHONE
      , AREA_CODE
      , ATTRIBUTE_8
      , RETAINAGE_RATE
      , GLOBAL_ATTRIBUTE_11
      , PAY_ON_USE_FLAG
      , GLOBAL_ATTRIBUTE_17
      , ATTRIBUTE_14
      , VENDOR_SITE_CODE
      , B_2_B_SITE_CODE
      , OFFSET_TAX_FLAG
      , PCARD_SITE_FLAG
      , GLOBAL_ATTRIBUTE_8
      , GLOBAL_ATTRIBUTE_NUMBER_6
      , FOB_LOOKUP_CODE
      , ALLOW_SUBSTITUTE_RECEIPTS_FLAG
      , GLOBAL_ATTRIBUTE_15
      , GLOBAL_ATTRIBUTE_19
      , ATTRIBUTE_DATE_3
      , GLOBAL_ATTRIBUTE_20
      , EXCLUDE_TAX_FROM_DISCOUNT
      , ATTRIBUTE_17
      , PURCHASING_SITE_FLAG
      , CARRIER_ID
      , AP_TAX_ROUNDING_RULE
      , EFFECTIVE_SEQUENCE
      , GLOBAL_ATTRIBUTE_NUMBER_2
      , RECEIVING_ROUTING_ID
      , ATTRIBUTE_11
      , ECE_TP_LOCATION_CODE
      , PAY_GROUP_LOOKUP_CODE
      , LAST_UPDATE_LOGIN
      , OFFSET_VAT_CODE
      , HOLD_ALL_PAYMENTS_FLAG
      , PARTY_SITE_ID
      , INVOICE_CHANNEL
      , GLOBAL_ATTRIBUTE_2
      , TOLERANCE_ID
      , ATTRIBUTE_NUMBER_10
      , ATTRIBUTE_DATE_6
      , GLOBAL_ATTRIBUTE_NUMBER_5
      , ATTRIBUTE_NUMBER_4
      , GLOBAL_ATTRIBUTE_NUMBER_7
      , GLOBAL_ATTRIBUTE_6
      , GLOBAL_ATTRIBUTE_4
      , PROGRAM_APPLICATION_ID
      , ATTRIBUTE_6
      , EXCLUDE_FREIGHT_FROM_DISCOUNT
      , DAYS_LATE_RECEIPT_ALLOWED
      , ATTRIBUTE_NUMBER_8
      , ATTRIBUTE_4
      , ATTRIBUTE_TIMESTAMP_10
      , TAX_REPORTING_SITE_FLAG
      , GLOBAL_ATTRIBUTE_1
      , PAY_SITE_FLAG
      , TERMS_DATE_BASIS
      , ATTRIBUTE_1
      , HOLD_FLAG
      , ATTRIBUTE_TIMESTAMP_9
      , ATTRIBUTE_NUMBER_3
      , CUSTOMER_NUM
      , PAY_ON_CODE
      , ALLOW_UNORDERED_RECEIPTS_FLAG
      , B_2_B_COMM_METHOD_CODE
      , INSPECTION_REQUIRED_FLAG
      , VENDOR_SITE_SPK_ID
      , ATTRIBUTE_TIMESTAMP_7
      , GAPLESS_INV_NUM_FLAG
      , RECEIPT_REQUIRED_FLAG
      , TERMS_ID
      , ATTRIBUTE_DATE_7
      , OVERRIDE_B_2_B_COMM_CODE
      , PRIMARY_PAY_SITE_FLAG
      , GLOBAL_ATTRIBUTE_TIMESTAMP_1
      , GLOBAL_ATTRIBUTE_NUMBER_4
      , GLOBAL_ATTRIBUTE_12
      , HOLD_UNMATCHED_INVOICES_FLAG
      , GLOBAL_ATTRIBUTE_10
      , ATTRIBUTE_DATE_5
      , HOLD_DATE
      , HOLD_FUTURE_PAYMENTS_FLAG
      , JOB_DEFINITION_NAME
      , PAY_ON_RECEIPT_SUMMARY_CODE
      , AGING_ONSET_POINT
      , QTY_RCV_EXCEPTION_CODE
      , GLOBAL_ATTRIBUTE_TIMESTAMP_4
      , AUTO_TAX_CALC_FLAG
      , ATTRIBUTE_15
      , ATTRIBUTE_7
      , OBJECT_VERSION_NUMBER
      , ATTRIBUTE_2
      , JOB_DEFINITION_PACKAGE
      , INVOICE_CURRENCY_CODE
      , GLOBAL_ATTRIBUTE_13
      , RECEIPT_DAYS_EXCEPTION_CODE
      , SERVICES_TOLERANCE_ID
      , TELEX
      , SERVICE_LEVEL
      , CONSUMPTION_ADVICE_FREQUENCY
      , GLOBAL_ATTRIBUTE_DATE_2
      , GLOBAL_ATTRIBUTE_NUMBER_1
      , ATTRIBUTE_NUMBER_2
      , ATTRIBUTE_NUMBER_7
      , GLOBAL_ATTRIBUTE_NUMBER_3
      , GLOBAL_ATTRIBUTE_TIMESTAMP_3
      , INVOICE_AMOUNT_LIMIT
      , BANK_CHARGE_BEARER
      , GLOBAL_ATTRIBUTE_TIMESTAMP_8
      , GLOBAL_ATTRIBUTE_TIMESTAMP_10
      , INACTIVE_DATE
      , PAY_DATE_BASIS_LOOKUP_CODE
      , GLOBAL_ATTRIBUTE_DATE_7
      , ATTRIBUTE_DATE_10
      , BANK_CHARGE_DEDUCTION_TYPE
      , GLOBAL_ATTRIBUTE_7
      , ATTRIBUTE_DATE_4
      , GLOBAL_ATTRIBUTE_DATE_10
      , HOLD_REASON
      , CREATION_DATE
      , GLOBAL_ATTRIBUTE_DATE_3
      , GLOBAL_ATTRIBUTE_NUMBER_10
      , ATTRIBUTE_18
      , SHIPPING_CONTROL
      , LAST_UPDATE_DATE
      , ATTRIBUTE_NUMBER_5
      , AMOUNT_INCLUDES_TAX_FLAG
      , ALWAYS_TAKE_DISC_FLAG
      , VAT_REGISTRATION_NUM
      , ATTRIBUTE_NUMBER_6
      , DEFAULT_PAY_SITE_ID
      , AUTO_CALCULATE_INTEREST_FLAG
      , MODE_OF_TRANSPORT
      , ATTRIBUTE_TIMESTAMP_6
      , SELLING_COMPANY_IDENTIFIER
      , MATCH_OPTION
      , HOLD_BY
      , DAYS_EARLY_RECEIPT_ALLOWED
      , ATTRIBUTE_TIMESTAMP_2
      , GLOBAL_ATTRIBUTE_DATE_5
      , BUYER_MANAGED_TRANSPORT_FLAG
      , GLOBAL_ATTRIBUTE_TIMESTAMP_2
      , SUPPLIER_NOTIF_METHOD
      , GLOBAL_ATTRIBUTE_DATE_6
      , ATTRIBUTE_TIMESTAMP_1
      , COUNTRY_OF_ORIGIN_CODE
      , CONSUMPTION_ADVICE_SUMMARY
      , ATTRIBUTE_NUMBER_9
      , GLOBAL_ATTRIBUTE_DATE_8
      , PHONE_COUNTRY_CODE
      , VAT_CODE
      , QTY_RCV_TOLERANCE
      , GLOBAL_ATTRIBUTE_NUMBER_8
      , AUTO_TAX_CALC_OVERRIDE
      , SHIP_VIA_LOOKUP_CODE
      , VENDOR_SITE_CODE_ALT
      , GLOBAL_ATTRIBUTE_9
      , ATTRIBUTE_TIMESTAMP_5
      , GLOBAL_ATTRIBUTE_5
      , GLOBAL_ATTRIBUTE_NUMBER_9
      , CREATED_BY
      , GLOBAL_ATTRIBUTE_DATE_9
      , ATTRIBUTE_13
      , GLOBAL_ATTRIBUTE_18
      , GLOBAL_ATTRIBUTE_TIMESTAMP_7
      , GLOBAL_ATTRIBUTE_14
      , PO_ACK_REQD_CODE
      , PURCHASING_HOLD_REASON
      , ATTRIBUTE_16
      , ATTRIBUTE_20
      , ATTRIBUTE_CATEGORY
      , ATTRIBUTE_9
      , ATTRIBUTE_19
      , EFFECTIVE_END_DATE
      , EMAIL_ADDRESS
      , FAX_COUNTRY_CODE
      , ATTRIBUTE_DATE_1
      , PAYMENT_PRIORITY
      , EFFECTIVE_START_DATE
      , FREIGHT_TERMS_LOOKUP_CODE
      , CREATE_DEBIT_MEMO_FLAG
      , TAX_COUNTRY_CODE
      , ATTENTION_AR_FLAG
      , PAYMENT_HOLD_DATE
      , TP_HEADER_ID
      , LOCATION_ID
      , REQUEST_ID
      , ATTRIBUTE_DATE_2
      , GLOBAL_ATTRIBUTE_DATE_4
      , ATTRIBUTE_3
      , ATTRIBUTE_NUMBER_1
      , ATTRIBUTE_5
      , GLOBAL_ATTRIBUTE_CATEGORY
      , GLOBAL_ATTRIBUTE_3
      , ATTRIBUTE_10
      , GLOBAL_ATTRIBUTE_TIMESTAMP_5
      , ATTRIBUTE_TIMESTAMP_4
      , PROGRAM_ID
      , PAYMENT_CURRENCY_CODE
      , ATTRIBUTE_12
      , GLOBAL_ATTRIBUTE_DATE_1
      , PRC_BU_ID
      , ENFORCE_SHIP_TO_LOCATION_CODE
      , ATTRIBUTE_DATE_8
      , GLOBAL_ATTRIBUTE_TIMESTAMP_6
      , GLOBAL_ATTRIBUTE_16
      , PROGRAM_UPDATE_DATE
      , EFFECTIVE_LATEST_CHANGE
      , PHONE_EXTENSION
      , LAST_UPDATED_BY
      , FAX_AREA_CODE
      , AGING_PERIOD_DAYS
      , ATTRIBUTE_TIMESTAMP_8
      , ATTRIBUTE_DATE_9
      , PO_ACK_REQD_DAYS
      , GLOBAL_ATTRIBUTE_TIMESTAMP_9
      , SHIPPING_NETWORK_LOCATION
      , ATTRIBUTE_TIMESTAMP_3
      , RFQ_ONLY_SITE_FLAG
      , _FIVETRAN_DELETED
      , _FIVETRAN_SYNCED
      , PSA_RECORD_SOURCE
      , PSA_LOAD_DTS
      , PSA_DELETE_IND
      , LOAD_DTS
      , BKCC
      , REC_SRC
      , HASHDIFF
    FROM LOGIC_SFIB
)
---- FILTER LAYER ----

, FILTER_SFIB as (
    SELECT *
    FROM RENAME_SFIB
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM FILTER_SFIB
)

---- FINAL LAYER ----
SELECT
          SUPPLIER_SITE_HK
        , VENDOR_SITE_ID
        , VENDOR_ID
        , FAX
        , PHONE
        , AREA_CODE
        , ATTRIBUTE_8
        , RETAINAGE_RATE
        , GLOBAL_ATTRIBUTE_11
        , PAY_ON_USE_FLAG
        , GLOBAL_ATTRIBUTE_17
        , ATTRIBUTE_14
        , VENDOR_SITE_CODE
        , B_2_B_SITE_CODE
        , OFFSET_TAX_FLAG
        , PCARD_SITE_FLAG
        , GLOBAL_ATTRIBUTE_8
        , GLOBAL_ATTRIBUTE_NUMBER_6
        , FOB_LOOKUP_CODE
        , ALLOW_SUBSTITUTE_RECEIPTS_FLAG
        , GLOBAL_ATTRIBUTE_15
        , GLOBAL_ATTRIBUTE_19
        , ATTRIBUTE_DATE_3
        , GLOBAL_ATTRIBUTE_20
        , EXCLUDE_TAX_FROM_DISCOUNT
        , ATTRIBUTE_17
        , PURCHASING_SITE_FLAG
        , CARRIER_ID
        , AP_TAX_ROUNDING_RULE
        , EFFECTIVE_SEQUENCE
        , GLOBAL_ATTRIBUTE_NUMBER_2
        , RECEIVING_ROUTING_ID
        , ATTRIBUTE_11
        , ECE_TP_LOCATION_CODE
        , PAY_GROUP_LOOKUP_CODE
        , LAST_UPDATE_LOGIN
        , OFFSET_VAT_CODE
        , HOLD_ALL_PAYMENTS_FLAG
        , PARTY_SITE_ID
        , INVOICE_CHANNEL
        , GLOBAL_ATTRIBUTE_2
        , TOLERANCE_ID
        , ATTRIBUTE_NUMBER_10
        , ATTRIBUTE_DATE_6
        , GLOBAL_ATTRIBUTE_NUMBER_5
        , ATTRIBUTE_NUMBER_4
        , GLOBAL_ATTRIBUTE_NUMBER_7
        , GLOBAL_ATTRIBUTE_6
        , GLOBAL_ATTRIBUTE_4
        , PROGRAM_APPLICATION_ID
        , ATTRIBUTE_6
        , EXCLUDE_FREIGHT_FROM_DISCOUNT
        , DAYS_LATE_RECEIPT_ALLOWED
        , ATTRIBUTE_NUMBER_8
        , ATTRIBUTE_4
        , ATTRIBUTE_TIMESTAMP_10
        , TAX_REPORTING_SITE_FLAG
        , GLOBAL_ATTRIBUTE_1
        , PAY_SITE_FLAG
        , TERMS_DATE_BASIS
        , ATTRIBUTE_1
        , HOLD_FLAG
        , ATTRIBUTE_TIMESTAMP_9
        , ATTRIBUTE_NUMBER_3
        , CUSTOMER_NUM
        , PAY_ON_CODE
        , ALLOW_UNORDERED_RECEIPTS_FLAG
        , B_2_B_COMM_METHOD_CODE
        , INSPECTION_REQUIRED_FLAG
        , VENDOR_SITE_SPK_ID
        , ATTRIBUTE_TIMESTAMP_7
        , GAPLESS_INV_NUM_FLAG
        , RECEIPT_REQUIRED_FLAG
        , TERMS_ID
        , ATTRIBUTE_DATE_7
        , OVERRIDE_B_2_B_COMM_CODE
        , PRIMARY_PAY_SITE_FLAG
        , GLOBAL_ATTRIBUTE_TIMESTAMP_1
        , GLOBAL_ATTRIBUTE_NUMBER_4
        , GLOBAL_ATTRIBUTE_12
        , HOLD_UNMATCHED_INVOICES_FLAG
        , GLOBAL_ATTRIBUTE_10
        , ATTRIBUTE_DATE_5
        , HOLD_DATE
        , HOLD_FUTURE_PAYMENTS_FLAG
        , JOB_DEFINITION_NAME
        , PAY_ON_RECEIPT_SUMMARY_CODE
        , AGING_ONSET_POINT
        , QTY_RCV_EXCEPTION_CODE
        , GLOBAL_ATTRIBUTE_TIMESTAMP_4
        , AUTO_TAX_CALC_FLAG
        , ATTRIBUTE_15
        , ATTRIBUTE_7
        , OBJECT_VERSION_NUMBER
        , ATTRIBUTE_2
        , JOB_DEFINITION_PACKAGE
        , INVOICE_CURRENCY_CODE
        , GLOBAL_ATTRIBUTE_13
        , RECEIPT_DAYS_EXCEPTION_CODE
        , SERVICES_TOLERANCE_ID
        , TELEX
        , SERVICE_LEVEL
        , CONSUMPTION_ADVICE_FREQUENCY
        , GLOBAL_ATTRIBUTE_DATE_2
        , GLOBAL_ATTRIBUTE_NUMBER_1
        , ATTRIBUTE_NUMBER_2
        , ATTRIBUTE_NUMBER_7
        , GLOBAL_ATTRIBUTE_NUMBER_3
        , GLOBAL_ATTRIBUTE_TIMESTAMP_3
        , INVOICE_AMOUNT_LIMIT
        , BANK_CHARGE_BEARER
        , GLOBAL_ATTRIBUTE_TIMESTAMP_8
        , GLOBAL_ATTRIBUTE_TIMESTAMP_10
        , INACTIVE_DATE
        , PAY_DATE_BASIS_LOOKUP_CODE
        , GLOBAL_ATTRIBUTE_DATE_7
        , ATTRIBUTE_DATE_10
        , BANK_CHARGE_DEDUCTION_TYPE
        , GLOBAL_ATTRIBUTE_7
        , ATTRIBUTE_DATE_4
        , GLOBAL_ATTRIBUTE_DATE_10
        , HOLD_REASON
        , CREATION_DATE
        , GLOBAL_ATTRIBUTE_DATE_3
        , GLOBAL_ATTRIBUTE_NUMBER_10
        , ATTRIBUTE_18
        , SHIPPING_CONTROL
        , LAST_UPDATE_DATE
        , ATTRIBUTE_NUMBER_5
        , AMOUNT_INCLUDES_TAX_FLAG
        , ALWAYS_TAKE_DISC_FLAG
        , VAT_REGISTRATION_NUM
        , ATTRIBUTE_NUMBER_6
        , DEFAULT_PAY_SITE_ID
        , AUTO_CALCULATE_INTEREST_FLAG
        , MODE_OF_TRANSPORT
        , ATTRIBUTE_TIMESTAMP_6
        , SELLING_COMPANY_IDENTIFIER
        , MATCH_OPTION
        , HOLD_BY
        , DAYS_EARLY_RECEIPT_ALLOWED
        , ATTRIBUTE_TIMESTAMP_2
        , GLOBAL_ATTRIBUTE_DATE_5
        , BUYER_MANAGED_TRANSPORT_FLAG
        , GLOBAL_ATTRIBUTE_TIMESTAMP_2
        , SUPPLIER_NOTIF_METHOD
        , GLOBAL_ATTRIBUTE_DATE_6
        , ATTRIBUTE_TIMESTAMP_1
        , COUNTRY_OF_ORIGIN_CODE
        , CONSUMPTION_ADVICE_SUMMARY
        , ATTRIBUTE_NUMBER_9
        , GLOBAL_ATTRIBUTE_DATE_8
        , PHONE_COUNTRY_CODE
        , VAT_CODE
        , QTY_RCV_TOLERANCE
        , GLOBAL_ATTRIBUTE_NUMBER_8
        , AUTO_TAX_CALC_OVERRIDE
        , SHIP_VIA_LOOKUP_CODE
        , VENDOR_SITE_CODE_ALT
        , GLOBAL_ATTRIBUTE_9
        , ATTRIBUTE_TIMESTAMP_5
        , GLOBAL_ATTRIBUTE_5
        , GLOBAL_ATTRIBUTE_NUMBER_9
        , CREATED_BY
        , GLOBAL_ATTRIBUTE_DATE_9
        , ATTRIBUTE_13
        , GLOBAL_ATTRIBUTE_18
        , GLOBAL_ATTRIBUTE_TIMESTAMP_7
        , GLOBAL_ATTRIBUTE_14
        , PO_ACK_REQD_CODE
        , PURCHASING_HOLD_REASON
        , ATTRIBUTE_16
        , ATTRIBUTE_20
        , ATTRIBUTE_CATEGORY
        , ATTRIBUTE_9
        , ATTRIBUTE_19
        , EFFECTIVE_END_DATE
        , EMAIL_ADDRESS
        , FAX_COUNTRY_CODE
        , ATTRIBUTE_DATE_1
        , PAYMENT_PRIORITY
        , EFFECTIVE_START_DATE
        , FREIGHT_TERMS_LOOKUP_CODE
        , CREATE_DEBIT_MEMO_FLAG
        , TAX_COUNTRY_CODE
        , ATTENTION_AR_FLAG
        , PAYMENT_HOLD_DATE
        , TP_HEADER_ID
        , LOCATION_ID
        , REQUEST_ID
        , ATTRIBUTE_DATE_2
        , GLOBAL_ATTRIBUTE_DATE_4
        , ATTRIBUTE_3
        , ATTRIBUTE_NUMBER_1
        , ATTRIBUTE_5
        , GLOBAL_ATTRIBUTE_CATEGORY
        , GLOBAL_ATTRIBUTE_3
        , ATTRIBUTE_10
        , GLOBAL_ATTRIBUTE_TIMESTAMP_5
        , ATTRIBUTE_TIMESTAMP_4
        , PROGRAM_ID
        , PAYMENT_CURRENCY_CODE
        , ATTRIBUTE_12
        , GLOBAL_ATTRIBUTE_DATE_1
        , PRC_BU_ID
        , ENFORCE_SHIP_TO_LOCATION_CODE
        , ATTRIBUTE_DATE_8
        , GLOBAL_ATTRIBUTE_TIMESTAMP_6
        , GLOBAL_ATTRIBUTE_16
        , PROGRAM_UPDATE_DATE
        , EFFECTIVE_LATEST_CHANGE
        , PHONE_EXTENSION
        , LAST_UPDATED_BY
        , FAX_AREA_CODE
        , AGING_PERIOD_DAYS
        , ATTRIBUTE_TIMESTAMP_8
        , ATTRIBUTE_DATE_9
        , PO_ACK_REQD_DAYS
        , GLOBAL_ATTRIBUTE_TIMESTAMP_9
        , SHIPPING_NETWORK_LOCATION
        , ATTRIBUTE_TIMESTAMP_3
        , RFQ_ONLY_SITE_FLAG
        , _FIVETRAN_DELETED
        , _FIVETRAN_SYNCED
        , PSA_RECORD_SOURCE
        , PSA_LOAD_DTS
        , PSA_DELETE_IND
        , LOAD_DTS
        , BKCC
        , REC_SRC
        , HASHDIFF
FROM JOIN_RESULT
{% if is_incremental() %}
WHERE NOT EXISTS (
    SELECT 1 
    FROM {{ this }} existing
    WHERE existing.SUPPLIER_SITE_HK = JOIN_RESULT.SUPPLIER_SITE_HK 
    AND existing.HASHDIFF = JOIN_RESULT.HASHDIFF
)
{% endif %}
{% if not is_incremental() %}

/* The following qualifier is implemented to prevent multiple loads of touched records during the initial build, such as multiple rows per HK and hashdiff. */
qualify 1 = row_number() over (partition by SUPPLIER_SITE_HK, HASHDIFF order by PSA_LOAD_DTS)

union all
SELECT 
MD5_BINARY(GR.VALUE) AS SUPPLIER_SITE_HK,
GR.VALUE::number AS VENDOR_SITE_ID,
GR.VALUE::number AS VENDOR_ID,
NULL AS FAX,
NULL AS PHONE,
NULL AS AREA_CODE,
NULL AS ATTRIBUTE_8,
NULL AS RETAINAGE_RATE,
NULL AS GLOBAL_ATTRIBUTE_11,
NULL AS PAY_ON_USE_FLAG,
NULL AS GLOBAL_ATTRIBUTE_17,
NULL AS ATTRIBUTE_14,
NULL AS VENDOR_SITE_CODE,
NULL AS B_2_B_SITE_CODE,
NULL AS OFFSET_TAX_FLAG,
NULL AS PCARD_SITE_FLAG,
NULL AS GLOBAL_ATTRIBUTE_8,
NULL AS GLOBAL_ATTRIBUTE_NUMBER_6,
NULL AS FOB_LOOKUP_CODE,
NULL AS ALLOW_SUBSTITUTE_RECEIPTS_FLAG,
NULL AS GLOBAL_ATTRIBUTE_15,
NULL AS GLOBAL_ATTRIBUTE_19,
NULL AS ATTRIBUTE_DATE_3,
NULL AS GLOBAL_ATTRIBUTE_20,
NULL AS EXCLUDE_TAX_FROM_DISCOUNT,
NULL AS ATTRIBUTE_17,
NULL AS PURCHASING_SITE_FLAG,
NULL AS CARRIER_ID,
NULL AS AP_TAX_ROUNDING_RULE,
NULL AS EFFECTIVE_SEQUENCE,
NULL AS GLOBAL_ATTRIBUTE_NUMBER_2,
NULL AS RECEIVING_ROUTING_ID,
NULL AS ATTRIBUTE_11,
NULL AS ECE_TP_LOCATION_CODE,
NULL AS PAY_GROUP_LOOKUP_CODE,
NULL AS LAST_UPDATE_LOGIN,
NULL AS OFFSET_VAT_CODE,
NULL AS HOLD_ALL_PAYMENTS_FLAG,
NULL AS PARTY_SITE_ID,
NULL AS INVOICE_CHANNEL,
NULL AS GLOBAL_ATTRIBUTE_2,
NULL AS TOLERANCE_ID,
NULL AS ATTRIBUTE_NUMBER_10,
NULL AS ATTRIBUTE_DATE_6,
NULL AS GLOBAL_ATTRIBUTE_NUMBER_5,
NULL AS ATTRIBUTE_NUMBER_4,
NULL AS GLOBAL_ATTRIBUTE_NUMBER_7,
NULL AS GLOBAL_ATTRIBUTE_6,
NULL AS GLOBAL_ATTRIBUTE_4,
NULL AS PROGRAM_APPLICATION_ID,
NULL AS ATTRIBUTE_6,
NULL AS EXCLUDE_FREIGHT_FROM_DISCOUNT,
NULL AS DAYS_LATE_RECEIPT_ALLOWED,
NULL AS ATTRIBUTE_NUMBER_8,
NULL AS ATTRIBUTE_4,
NULL AS ATTRIBUTE_TIMESTAMP_10,
NULL AS TAX_REPORTING_SITE_FLAG,
NULL AS GLOBAL_ATTRIBUTE_1,
NULL AS PAY_SITE_FLAG,
NULL AS TERMS_DATE_BASIS,
NULL AS ATTRIBUTE_1,
NULL AS HOLD_FLAG,
NULL AS ATTRIBUTE_TIMESTAMP_9,
NULL AS ATTRIBUTE_NUMBER_3,
NULL AS CUSTOMER_NUM,
NULL AS PAY_ON_CODE,
NULL AS ALLOW_UNORDERED_RECEIPTS_FLAG,
NULL AS B_2_B_COMM_METHOD_CODE,
NULL AS INSPECTION_REQUIRED_FLAG,
NULL AS VENDOR_SITE_SPK_ID,
NULL AS ATTRIBUTE_TIMESTAMP_7,
NULL AS GAPLESS_INV_NUM_FLAG,
NULL AS RECEIPT_REQUIRED_FLAG,
NULL AS TERMS_ID,
NULL AS ATTRIBUTE_DATE_7,
NULL AS OVERRIDE_B_2_B_COMM_CODE,
NULL AS PRIMARY_PAY_SITE_FLAG,
NULL AS GLOBAL_ATTRIBUTE_TIMESTAMP_1,
NULL AS GLOBAL_ATTRIBUTE_NUMBER_4,
NULL AS GLOBAL_ATTRIBUTE_12,
NULL AS HOLD_UNMATCHED_INVOICES_FLAG,
NULL AS GLOBAL_ATTRIBUTE_10,
NULL AS ATTRIBUTE_DATE_5,
NULL AS HOLD_DATE,
NULL AS HOLD_FUTURE_PAYMENTS_FLAG,
NULL AS JOB_DEFINITION_NAME,
NULL AS PAY_ON_RECEIPT_SUMMARY_CODE,
NULL AS AGING_ONSET_POINT,
NULL AS QTY_RCV_EXCEPTION_CODE,
NULL AS GLOBAL_ATTRIBUTE_TIMESTAMP_4,
NULL AS AUTO_TAX_CALC_FLAG,
NULL AS ATTRIBUTE_15,
NULL AS ATTRIBUTE_7,
NULL AS OBJECT_VERSION_NUMBER,
NULL AS ATTRIBUTE_2,
NULL AS JOB_DEFINITION_PACKAGE,
NULL AS INVOICE_CURRENCY_CODE,
NULL AS GLOBAL_ATTRIBUTE_13,
NULL AS RECEIPT_DAYS_EXCEPTION_CODE,
NULL AS SERVICES_TOLERANCE_ID,
NULL AS TELEX,
NULL AS SERVICE_LEVEL,
NULL AS CONSUMPTION_ADVICE_FREQUENCY,
NULL AS GLOBAL_ATTRIBUTE_DATE_2,
NULL AS GLOBAL_ATTRIBUTE_NUMBER_1,
NULL AS ATTRIBUTE_NUMBER_2,
NULL AS ATTRIBUTE_NUMBER_7,
NULL AS GLOBAL_ATTRIBUTE_NUMBER_3,
NULL AS GLOBAL_ATTRIBUTE_TIMESTAMP_3,
NULL AS INVOICE_AMOUNT_LIMIT,
NULL AS BANK_CHARGE_BEARER,
NULL AS GLOBAL_ATTRIBUTE_TIMESTAMP_8,
NULL AS GLOBAL_ATTRIBUTE_TIMESTAMP_10,
NULL AS INACTIVE_DATE,
NULL AS PAY_DATE_BASIS_LOOKUP_CODE,
NULL AS GLOBAL_ATTRIBUTE_DATE_7,
NULL AS ATTRIBUTE_DATE_10,
NULL AS BANK_CHARGE_DEDUCTION_TYPE,
NULL AS GLOBAL_ATTRIBUTE_7,
NULL AS ATTRIBUTE_DATE_4,
NULL AS GLOBAL_ATTRIBUTE_DATE_10,
NULL AS HOLD_REASON,
NULL AS CREATION_DATE,
NULL AS GLOBAL_ATTRIBUTE_DATE_3,
NULL AS GLOBAL_ATTRIBUTE_NUMBER_10,
NULL AS ATTRIBUTE_18,
NULL AS SHIPPING_CONTROL,
NULL AS LAST_UPDATE_DATE,
NULL AS ATTRIBUTE_NUMBER_5,
NULL AS AMOUNT_INCLUDES_TAX_FLAG,
NULL AS ALWAYS_TAKE_DISC_FLAG,
NULL AS VAT_REGISTRATION_NUM,
NULL AS ATTRIBUTE_NUMBER_6,
NULL AS DEFAULT_PAY_SITE_ID,
NULL AS AUTO_CALCULATE_INTEREST_FLAG,
NULL AS MODE_OF_TRANSPORT,
NULL AS ATTRIBUTE_TIMESTAMP_6,
NULL AS SELLING_COMPANY_IDENTIFIER,
NULL AS MATCH_OPTION,
NULL AS HOLD_BY,
NULL AS DAYS_EARLY_RECEIPT_ALLOWED,
NULL AS ATTRIBUTE_TIMESTAMP_2,
NULL AS GLOBAL_ATTRIBUTE_DATE_5,
NULL AS BUYER_MANAGED_TRANSPORT_FLAG,
NULL AS GLOBAL_ATTRIBUTE_TIMESTAMP_2,
NULL AS SUPPLIER_NOTIF_METHOD,
NULL AS GLOBAL_ATTRIBUTE_DATE_6,
NULL AS ATTRIBUTE_TIMESTAMP_1,
NULL AS COUNTRY_OF_ORIGIN_CODE,
NULL AS CONSUMPTION_ADVICE_SUMMARY,
NULL AS ATTRIBUTE_NUMBER_9,
NULL AS GLOBAL_ATTRIBUTE_DATE_8,
NULL AS PHONE_COUNTRY_CODE,
NULL AS VAT_CODE,
NULL AS QTY_RCV_TOLERANCE,
NULL AS GLOBAL_ATTRIBUTE_NUMBER_8,
NULL AS AUTO_TAX_CALC_OVERRIDE,
NULL AS SHIP_VIA_LOOKUP_CODE,
NULL AS VENDOR_SITE_CODE_ALT,
NULL AS GLOBAL_ATTRIBUTE_9,
NULL AS ATTRIBUTE_TIMESTAMP_5,
NULL AS GLOBAL_ATTRIBUTE_5,
NULL AS GLOBAL_ATTRIBUTE_NUMBER_9,
NULL AS CREATED_BY,
NULL AS GLOBAL_ATTRIBUTE_DATE_9,
NULL AS ATTRIBUTE_13,
NULL AS GLOBAL_ATTRIBUTE_18,
NULL AS GLOBAL_ATTRIBUTE_TIMESTAMP_7,
NULL AS GLOBAL_ATTRIBUTE_14,
NULL AS PO_ACK_REQD_CODE,
NULL AS PURCHASING_HOLD_REASON,
NULL AS ATTRIBUTE_16,
NULL AS ATTRIBUTE_20,
NULL AS ATTRIBUTE_CATEGORY,
NULL AS ATTRIBUTE_9,
NULL AS ATTRIBUTE_19,
NULL AS EFFECTIVE_END_DATE,
NULL AS EMAIL_ADDRESS,
NULL AS FAX_COUNTRY_CODE,
NULL AS ATTRIBUTE_DATE_1,
NULL AS PAYMENT_PRIORITY,
NULL AS EFFECTIVE_START_DATE,
NULL AS FREIGHT_TERMS_LOOKUP_CODE,
NULL AS CREATE_DEBIT_MEMO_FLAG,
NULL AS TAX_COUNTRY_CODE,
NULL AS ATTENTION_AR_FLAG,
NULL AS PAYMENT_HOLD_DATE,
NULL AS TP_HEADER_ID,
NULL AS LOCATION_ID,
NULL AS REQUEST_ID,
NULL AS ATTRIBUTE_DATE_2,
NULL AS GLOBAL_ATTRIBUTE_DATE_4,
NULL AS ATTRIBUTE_3,
NULL AS ATTRIBUTE_NUMBER_1,
NULL AS ATTRIBUTE_5,
NULL AS GLOBAL_ATTRIBUTE_CATEGORY,
NULL AS GLOBAL_ATTRIBUTE_3,
NULL AS ATTRIBUTE_10,
NULL AS GLOBAL_ATTRIBUTE_TIMESTAMP_5,
NULL AS ATTRIBUTE_TIMESTAMP_4,
NULL AS PROGRAM_ID,
NULL AS PAYMENT_CURRENCY_CODE,
NULL AS ATTRIBUTE_12,
NULL AS GLOBAL_ATTRIBUTE_DATE_1,
NULL AS PRC_BU_ID,
NULL AS ENFORCE_SHIP_TO_LOCATION_CODE,
NULL AS ATTRIBUTE_DATE_8,
NULL AS GLOBAL_ATTRIBUTE_TIMESTAMP_6,
NULL AS GLOBAL_ATTRIBUTE_16,
NULL AS PROGRAM_UPDATE_DATE,
NULL AS EFFECTIVE_LATEST_CHANGE,
NULL AS PHONE_EXTENSION,
NULL AS LAST_UPDATED_BY,
NULL AS FAX_AREA_CODE,
NULL AS AGING_PERIOD_DAYS,
NULL AS ATTRIBUTE_TIMESTAMP_8,
NULL AS ATTRIBUTE_DATE_9,
NULL AS PO_ACK_REQD_DAYS,
NULL AS GLOBAL_ATTRIBUTE_TIMESTAMP_9,
NULL AS SHIPPING_NETWORK_LOCATION,
NULL AS ATTRIBUTE_TIMESTAMP_3,
NULL AS RFQ_ONLY_SITE_FLAG,
NULL AS _FIVETRAN_DELETED,
NULL AS _FIVETRAN_SYNCED,
NULL AS PSA_RECORD_SOURCE,
'1900-01-01'::TIMESTAMP AS PSA_LOAD_DTS,
'N' AS PSA_DELETE_IND,
CONVERT_TIMEZONE('UTC','1900-01-01'::TIMESTAMP) AS LOAD_DTS,
DECODE(GR.VALUE, 0, 'GHOST RECORD-SYSTEM', -1, 'GHOST RECORD-nullkey-required', -2, 'GHOST RECORD-nullkey-optional') AS BKCC,
'USAZET.SNOWFLAKE.FBIN.DERIVED' AS REC_SRC,
''::BINARY AS HASHDIFF
FROM
TABLE(strtok_split_to_table('0|-1|-2', '|')) AS GR
{% endif %}
