---- SRC LAYER ----
WITH
SRC_itmb           as ( SELECT * FROM {{ ref('v_psa_stg_plant_item__ml_ebs') }} as SRC 
                         {% if is_incremental() %}
                              where src.load_dts > (select dateadd('HOUR',-1,max(load_dts)) from {{ this }})
                            {% endif %}   )

/*
SRC_itmb           as ( SELECT * FROM staging.V_PSA_STG_PLANT_ITEM__ML_EBS )
*/
---- LOGIC LAYER ----

, LOGIC_itmb as (
    SELECT
        ITEM_HK
      , SEGMENT1
      , INVENTORY_ITEM_ID
      , ORGANIZATION_ID
      , WIP_SUPPLY_LOCATOR_ID
      , ATTRIBUTE30
      , REPAIR_PROGRAM
      , PARENT_CHILD_GENERATION_FLAG
      , DEFAULT_MATERIAL_STATUS_ID
      , INTERNAL_ORDER_FLAG
      , DAYS_TGT_INV_WINDOW
      , PLANNING_TIME_FENCE_CODE
      , ATTRIBUTE29
      , WEB_STATUS
      , ATTRIBUTE28
      , UNIT_WEIGHT
      , ATTRIBUTE27
      , ATTRIBUTE26
      , WIP_SUPPLY_TYPE
      , MTL_TRANSACTIONS_ENABLED_FLAG
      , ATTRIBUTE3
      , DAYS_LATE_RECEIPT_ALLOWED
      , ATTRIBUTE2
      , ATTRIBUTE1
      , ATTRIBUTE9
      , ATTRIBUTE8
      , ATTRIBUTE7
      , UNIT_WIDTH
      , QTY_RCV_EXCEPTION_CODE
      , ATTRIBUTE6
      , ATTRIBUTE5
      , ATTRIBUTE4
      , OVER_SHIPMENT_TOLERANCE
      , SHRINKAGE_RATE
      , LOT_SPLIT_ENABLED
      , ATTRIBUTE10
      , MUST_USE_APPROVED_VENDOR_FLAG
      , ATTRIBUTE14
      , WIP_SUPPLY_SUBINVENTORY
      , ATTRIBUTE13
      , PICK_COMPONENTS_FLAG
      , ATTRIBUTE12
      , ATTRIBUTE11
      , APPROVAL_STATUS
      , DUAL_UOM_CONTROL
      , ONT_PRICING_QTY_SOURCE
      , EXPENSE_ACCOUNT
      , ATTRIBUTE21
      , ATTRIBUTE20
      , RESPONSE_TIME_PERIOD_CODE
      , ATTRIBUTE25
      , ATTRIBUTE24
      , PRICE_TOLERANCE_PERCENT
      , ATTRIBUTE23
      , ATTRIBUTE22
      , DEFAULT_SERIAL_STATUS_ID
      , SERVICEABLE_PRODUCT_FLAG
      , CURRENT_PHASE_ID
      , RESPONSE_TIME_VALUE
      , PREPOSITION_POINT
      , MAX_MINMAX_QUANTITY
      , ATTRIBUTE18
      , EAM_ACT_NOTIFICATION_FLAG
      , ATTRIBUTE17
      , ATTRIBUTE16
      , ATTRIBUTE15
      , DUAL_UOM_DEVIATION_LOW
      , ATTRIBUTE19
      , PLANNER_CODE
      , INTERNAL_ORDER_ENABLED_FLAG
      , POSITIVE_MEASUREMENT_ERROR
      , GLOBAL_ATTRIBUTE10
      , INVENTORY_PLANNING_CODE
      , INVENTORY_ITEM_FLAG
      , COST_OF_SALES_ACCOUNT
      , OBJECT_VERSION_NUMBER
      , INSPECTION_REQUIRED_FLAG
      , CHILD_LOT_STARTING_NUMBER
      , DAYS_MAX_INV_WINDOW
      , MARKET_PRICE
      , UNIT_OF_ISSUE
      , ACCEPTABLE_EARLY_DAYS
      , FIXED_LEAD_TIME
      , HOLD_DAYS
      , ENFORCE_SHIP_TO_LOCATION_CODE
      , SHELF_LIFE_CODE
      , PROCESS_COSTING_ENABLED_FLAG
      , CRITICAL_COMPONENT_FLAG
      , VENDOR_WARRANTY_FLAG
      , FORECAST_HORIZON
      , ATO_FORECAST_CONTROL
      , USAGE_ITEM_FLAG
      , SAFETY_STOCK_BUCKET_DAYS
      , REPAIR_YIELD
      , UNIT_LENGTH
      , DEFAULT_INCLUDE_IN_ROLLUP_FLAG
      , DEFECT_TRACKING_ON_FLAG
      , INVOICE_CLOSE_TOLERANCE
      , CHECK_SHORTAGES_FLAG
      , ITEM_TYPE
      , SUMMARY_FLAG
      , VMI_MINIMUM_DAYS
      , BOM_ITEM_TYPE
      , REPLENISH_TO_ORDER_FLAG
      , EAM_ITEM_TYPE
      , PLANNING_MAKE_BUY_CODE
      , GLOBAL_ATTRIBUTE_CATEGORY
      , UN_NUMBER_ID
      , CARRYING_COST
      , PRIMARY_SPECIALIST_ID
      , WEIGHT_UOM_CODE
      , MINIMUM_LICENSE_QUANTITY
      , GRADE_CONTROL_FLAG
      , VMI_FORECAST_TYPE
      , PAYMENT_TERMS_ID
      , OUTSIDE_OPERATION_UOM_TYPE
      , GLOBAL_ATTRIBUTE5
      , GLOBAL_ATTRIBUTE4
      , UNDER_RETURN_TOLERANCE
      , GLOBAL_ATTRIBUTE7
      , GLOBAL_ATTRIBUTE6
      , GLOBAL_ATTRIBUTE1
      , GLOBAL_ATTRIBUTE3
      , GLOBAL_ATTRIBUTE2
      , EAM_ACTIVITY_TYPE_CODE
      , STYLE_ITEM_ID
      , GLOBAL_ATTRIBUTE9
      , GLOBAL_ATTRIBUTE8
      , INVOICEABLE_ITEM_FLAG
      , ELECTRONIC_FLAG
      , POSTPROCESSING_LEAD_TIME
      , LIFECYCLE_ID
      , VMI_MAXIMUM_UNITS
      , SERVICEABLE_ITEM_CLASS_ID
      , CONTRACT_ITEM_TYPE_CODE
      , MODEL_CONFIG_CLAUSE_NAME
      , SERIAL_STATUS_ENABLED
      , EAM_ACT_SHUTDOWN_STATUS
      , AUTO_SERIAL_ALPHA_PREFIX
      , PLANNING_EXCEPTION_SET
      , PREPROCESSING_LEAD_TIME
      , RECEIVE_CLOSE_TOLERANCE
      , RETURN_INSPECTION_REQUIREMENT
      , COPY_LOT_ATTRIBUTE_FLAG
      , SO_AUTHORIZATION_FLAG
      , RETEST_INTERVAL
      , STOCK_ENABLED_FLAG
      , RECOVERED_PART_DISP_CODE
      , OVER_RETURN_TOLERANCE
      , CONFIG_MODEL_TYPE
      , ALLOW_ITEM_DESC_UPDATE_FLAG
      , INTERNAL_VOLUME
      , COVERAGE_SCHEDULE_ID
      , RFQ_REQUIRED_FLAG
      , MIN_MINMAX_QUANTITY
      , DEMAND_TIME_FENCE_CODE
      , ORDERABLE_ON_WEB_FLAG
      , CATALOG_STATUS_FLAG
      , SEGMENT11
      , SEGMENT10
      , FIXED_DAYS_SUPPLY
      , SEGMENT13
      , CYCLE_COUNT_ENABLED_FLAG
      , SEGMENT12
      , SEGMENT15
      , SEGMENT14
      , SEGMENT17
      , GLOBAL_ATTRIBUTE20
      , SEGMENT16
      , SEGMENT19
      , FIXED_LOT_MULTIPLIER
      , SEGMENT18
      , DAYS_TGT_INV_SUPPLY
      , SO_TRANSACTIONS_FLAG
      , CHILD_LOT_FLAG
      , GLOBAL_ATTRIBUTE17
      , GLOBAL_ATTRIBUTE18
      , GLOBAL_ATTRIBUTE15
      , GLOBAL_ATTRIBUTE16
      , GLOBAL_ATTRIBUTE13
      , GLOBAL_ATTRIBUTE14
      , VOL_DISCOUNT_EXEMPT_FLAG
      , PLANNED_INV_POINT_FLAG
      , GLOBAL_ATTRIBUTE11
      , GLOBAL_ATTRIBUTE12
      , PREVENTIVE_MAINTENANCE_FLAG
      , LOT_CONTROL_CODE
      , MAX_WARRANTY_AMOUNT
      , SUBSTITUTION_WINDOW_CODE
      , GLOBAL_ATTRIBUTE19
      , SEGMENT20
      , GDSN_OUTBOUND_ENABLED_FLAG
      , ORDER_COST
      , CHILD_LOT_VALIDATION_FLAG
      , UNDER_SHIPMENT_TOLERANCE
      , INVOICING_RULE_ID
      , COMMS_ACTIVATION_REQD_FLAG
      , HAZARD_CLASS_ID
      , EXPENSE_BILLABLE_FLAG
      , LOT_STATUS_ENABLED
      , EFFECTIVITY_CONTROL
      , ATTRIBUTE_CATEGORY
      , SUBSCRIPTION_DEPEND_FLAG
      , PROGRAM_APPLICATION_ID
      , VMI_MINIMUM_UNITS
      , TIME_BILLABLE_FLAG
      , PRORATE_SERVICE_FLAG
      , REPETITIVE_PLANNING_FLAG
      , ALLOW_SUBSTITUTE_RECEIPTS_FLAG
      , OVERCOMPLETION_TOLERANCE_TYPE
      , BOM_ENABLED_FLAG
      , SHIPPABLE_ITEM_FLAG
      , PURCHASING_ITEM_FLAG
      , SOURCE_TYPE
      , SERV_REQ_ENABLED_CODE
      , IB_ITEM_INSTANCE_CLASS
      , LOT_TRANSLATE_ENABLED
      , MAXIMUM_LOAD_WEIGHT
      , SERVICE_DURATION
      , MRP_SAFETY_STOCK_PERCENT
      , ALLOW_UNORDERED_RECEIPTS_FLAG
      , ALLOWED_UNITS_LOOKUP_CODE
      , LAST_UPDATE_LOGIN
      , PROCESS_SUPPLY_LOCATOR_ID
      , PROCESS_YIELD_SUBINVENTORY
      , ACCOUNTING_RULE_ID
      , VMI_MAXIMUM_DAYS
      , INVENTORY_ITEM_STATUS_CODE
      , TAX_CODE
      , AUTO_CREATED_CONFIG_FLAG
      , SUBCONTRACTING_COMPONENT
      , VMI_FIXED_ORDER_QUANTITY
      , PROGRAM_ID
      , CONTAINER_ITEM_FLAG
      , SEGMENT8
      , SEGMENT7
      , SEGMENT9
      , SERIAL_TAGGING_FLAG
      , SEGMENT4
      , SEGMENT3
      , EXPIRATION_ACTION_CODE
      , SEGMENT6
      , SEGMENT5
      , TRADE_ITEM_DESCRIPTOR
      , MINIMUM_FILL_PERCENT
      , END_DATE_ACTIVE
      , SALES_ACCOUNT
      , BACK_ORDERABLE_FLAG
      , STD_LOT_SIZE
      , FINANCING_ALLOWED_FLAG
      , LEAD_TIME_LOT_SIZE
      , PRIMARY_UOM_CODE
      , SHELF_LIFE_DAYS
      , CONTAINER_TYPE_CODE
      , DEFAULT_GRADE
      , CUSTOMER_ORDER_ENABLED_FLAG
      , ITEM_CATALOG_GROUP_ID
      , ATP_RULE_ID
      , SERVICE_STARTING_DELAY
      , RELEASE_TIME_FENCE_DAYS
      , OVERCOMPLETION_TOLERANCE_VALUE
      , UNIT_VOLUME
      , DESCRIPTION
      , CONVERGENCE
      , CUM_MANUFACTURING_LEAD_TIME
      , SHIP_MODEL_COMPLETE_FLAG
      , LOT_SUBSTITUTION_ENABLED
      , OUTSIDE_OPERATION_FLAG
      , AUTO_LOT_ALPHA_PREFIX
      , ATP_FLAG
      , EGO_MASTER_ITEMS_DFF_CTX
      , EAM_ACTIVITY_SOURCE_CODE
      , TAXABLE_FLAG
      , ALLOW_EXPRESS_DELIVERY_FLAG
      , PURCHASING_TAX_CODE
      , ENG_ITEM_FLAG
      , ENGINEERING_ITEM_ID
      , END_ASSEMBLY_PEGGING_FLAG
      , RETURNABLE_FLAG
      , PROCESS_YIELD_LOCATOR_ID
      , EAM_ACTIVITY_CAUSE_CODE
      , MATURITY_DAYS
      , ATP_COMPONENTS_FLAG
      , LAST_UPDATED_BY
      , COUPON_EXEMPT_FLAG
      , PLANNING_TIME_FENCE_DAYS
      , RECEIPT_REQUIRED_FLAG
      , VOLUME_UOM_CODE
      , LOCATION_CONTROL_CODE
      , WARRANTY_VENDOR_ID
      , INVENTORY_ASSET_FLAG
      , ENCUMBRANCE_ACCOUNT
      , SERVICEABLE_COMPONENT_FLAG
      , CUMULATIVE_TOTAL_LEAD_TIME
      , MRP_CALCULATE_ATP_FLAG
      , OUTSOURCED_ASSEMBLY
      , DEFAULT_LOT_STATUS_ID
      , VARIABLE_LEAD_TIME
      , AUTO_REDUCE_MPS
      , RECIPE_ENABLED_FLAG
      , ACCEPTABLE_RATE_DECREASE
      , BUILD_IN_WIP_FLAG
      , RECEIPT_DAYS_EXCEPTION_CODE
      , VEHICLE_ITEM_FLAG
      , CONFIG_MATCH
      , DOWNLOADABLE_FLAG
      , DEFAULT_SO_SOURCE_TYPE
      , FIXED_ORDER_QUANTITY
      , SUBSTITUTION_WINDOW_DAYS
      , EQUIPMENT_TYPE
      , CAS_NUMBER
      , SERV_IMPORTANCE_LEVEL
      , LOT_MERGE_ENABLED
      , SEGMENT2
      , CUSTOMER_ORDER_FLAG
      , ENABLED_FLAG
      , PURCHASING_ENABLED_FLAG
      , WH_UPDATE_DATE
      , OVERRUN_PERCENTAGE
      , ASSET_CREATION_CODE
      , DAYS_EARLY_RECEIPT_ALLOWED
      , NEGATIVE_MEASUREMENT_ERROR
      , BASE_WARRANTY_SERVICE_ID
      , START_AUTO_SERIAL_NUMBER
      , ROUNDING_CONTROL_TYPE
      , LOT_DIVISIBLE_FLAG
      , EXCLUDE_FROM_BUDGET_FLAG
      , MRP_PLANNING_CODE
      , BUYER_ID
      , RESERVABLE_TYPE
      , SOURCE_ORGANIZATION_ID
      , NEW_REVISION_CODE
      , DRP_PLANNED_FLAG
      , ASSET_CATEGORY_ID
      , MRP_SAFETY_STOCK_CODE
      , CONTINOUS_TRANSFER
      , HAZARDOUS_MATERIAL_FLAG
      , COSTING_ENABLED_FLAG
      , DIMENSION_UOM_CODE
      , SERVICE_DURATION_PERIOD_CODE
      , EVENT_FLAG
      , BULK_PICKED_FLAG
      , DEFAULT_SHIPPING_ORG
      , MATERIAL_BILLABLE_FLAG
      , PROCESS_QUALITY_ENABLED_FLAG
      , OPTION_SPECIFIC_SOURCED
      , SECONDARY_SPECIALIST_ID
      , PICKING_RULE_ID
      , EXPIRATION_ACTION_INTERVAL
      , ASN_AUTOEXPIRE_FLAG
      , START_AUTO_LOT_NUMBER
      , MINIMUM_ORDER_QUANTITY
      , COMMS_NL_TRACKABLE_FLAG
      , INVENTORY_CARRY_PENALTY
      , ENGINEERING_ECN_CODE
      , REPAIR_LEADTIME
      , SECONDARY_UOM_CODE
      , RECEIVING_ROUTING_ID
      , PRIMARY_UNIT_OF_MEASURE
      , CREATE_SUPPLY_FLAG
      , MAXIMUM_ORDER_QUANTITY
      , PROCESS_SUPPLY_SUBINVENTORY
      , PRODUCT_FAMILY_ITEM_ID
      , SOURCE_SUBINVENTORY
      , SERIAL_NUMBER_CONTROL_CODE
      , CREATED_BY
      , STYLE_ITEM_FLAG
      , CHARGE_PERIODICITY_CODE
      , INVOICE_ENABLED_FLAG
      , CONSIGNED_FLAG
      , DAYS_MAX_INV_SUPPLY
      , UNIT_HEIGHT
      , PROCESS_EXECUTION_ENABLED_FLAG
      , ROUNDING_FACTOR
      , OPERATION_SLACK_PENALTY
      , DEMAND_TIME_FENCE_DAYS
      , BASE_ITEM_ID
      , COLLATERAL_FLAG
      , REQUEST_ID
      , FULL_LEAD_TIME
      , SERVICE_ITEM_FLAG
      , INDIVISIBLE_FLAG
      , SERV_BILLING_ENABLED_FLAG
      , DIVERGENCE
      , SECONDARY_DEFAULT_IND
      , REVISION_QTY_CONTROL_CODE
      , QTY_RCV_TOLERANCE
      , DUAL_UOM_DEVIATION_HIGH
      , RELEASE_TIME_FENCE_CODE
      , ACCEPTABLE_RATE_INCREASE
      , RESTRICT_SUBINVENTORIES_CODE
      , CONFIG_ORGS
      , LAST_SUBMITTED_NIR_ID
      , RESTRICT_LOCATORS_CODE
      , CHILD_LOT_PREFIX
      , TRACKING_QUANTITY_IND
      , PROGRAM_UPDATE_DATE
      , START_DATE_ACTIVE
      , LIST_PRICE_PER_UNIT
      , CREATION_DATE
      , ENGINEERING_DATE
      , LAST_UPDATE_DATE
      , _FIVETRAN_DELETED
      , _FIVETRAN_ID
      , _FIVETRAN_SYNCED
      , PSA_DELETE_IND
      , PSA_LOAD_DTS
      , PSA_RECORD_SOURCE
      , LOAD_DTS
      , REC_SRC
      , HASHDIFF
    FROM SRC_itmb
)
---- RENAME LAYER ----

, RENAME_itmb as (
    SELECT
        ITEM_HK
      , SEGMENT1
      , INVENTORY_ITEM_ID
      , ORGANIZATION_ID
      , WIP_SUPPLY_LOCATOR_ID
      , ATTRIBUTE30
      , REPAIR_PROGRAM
      , PARENT_CHILD_GENERATION_FLAG
      , DEFAULT_MATERIAL_STATUS_ID
      , INTERNAL_ORDER_FLAG
      , DAYS_TGT_INV_WINDOW
      , PLANNING_TIME_FENCE_CODE
      , ATTRIBUTE29
      , WEB_STATUS
      , ATTRIBUTE28
      , UNIT_WEIGHT
      , ATTRIBUTE27
      , ATTRIBUTE26
      , WIP_SUPPLY_TYPE
      , MTL_TRANSACTIONS_ENABLED_FLAG
      , ATTRIBUTE3
      , DAYS_LATE_RECEIPT_ALLOWED
      , ATTRIBUTE2
      , ATTRIBUTE1
      , ATTRIBUTE9
      , ATTRIBUTE8
      , ATTRIBUTE7
      , UNIT_WIDTH
      , QTY_RCV_EXCEPTION_CODE
      , ATTRIBUTE6
      , ATTRIBUTE5
      , ATTRIBUTE4
      , OVER_SHIPMENT_TOLERANCE
      , SHRINKAGE_RATE
      , LOT_SPLIT_ENABLED
      , ATTRIBUTE10
      , MUST_USE_APPROVED_VENDOR_FLAG
      , ATTRIBUTE14
      , WIP_SUPPLY_SUBINVENTORY
      , ATTRIBUTE13
      , PICK_COMPONENTS_FLAG
      , ATTRIBUTE12
      , ATTRIBUTE11
      , APPROVAL_STATUS
      , DUAL_UOM_CONTROL
      , ONT_PRICING_QTY_SOURCE
      , EXPENSE_ACCOUNT
      , ATTRIBUTE21
      , ATTRIBUTE20
      , RESPONSE_TIME_PERIOD_CODE
      , ATTRIBUTE25
      , ATTRIBUTE24
      , PRICE_TOLERANCE_PERCENT
      , ATTRIBUTE23
      , ATTRIBUTE22
      , DEFAULT_SERIAL_STATUS_ID
      , SERVICEABLE_PRODUCT_FLAG
      , CURRENT_PHASE_ID
      , RESPONSE_TIME_VALUE
      , PREPOSITION_POINT
      , MAX_MINMAX_QUANTITY
      , ATTRIBUTE18
      , EAM_ACT_NOTIFICATION_FLAG
      , ATTRIBUTE17
      , ATTRIBUTE16
      , ATTRIBUTE15
      , DUAL_UOM_DEVIATION_LOW
      , ATTRIBUTE19
      , PLANNER_CODE
      , INTERNAL_ORDER_ENABLED_FLAG
      , POSITIVE_MEASUREMENT_ERROR
      , GLOBAL_ATTRIBUTE10
      , INVENTORY_PLANNING_CODE
      , INVENTORY_ITEM_FLAG
      , COST_OF_SALES_ACCOUNT
      , OBJECT_VERSION_NUMBER
      , INSPECTION_REQUIRED_FLAG
      , CHILD_LOT_STARTING_NUMBER
      , DAYS_MAX_INV_WINDOW
      , MARKET_PRICE
      , UNIT_OF_ISSUE
      , ACCEPTABLE_EARLY_DAYS
      , FIXED_LEAD_TIME
      , HOLD_DAYS
      , ENFORCE_SHIP_TO_LOCATION_CODE
      , SHELF_LIFE_CODE
      , PROCESS_COSTING_ENABLED_FLAG
      , CRITICAL_COMPONENT_FLAG
      , VENDOR_WARRANTY_FLAG
      , FORECAST_HORIZON
      , ATO_FORECAST_CONTROL
      , USAGE_ITEM_FLAG
      , SAFETY_STOCK_BUCKET_DAYS
      , REPAIR_YIELD
      , UNIT_LENGTH
      , DEFAULT_INCLUDE_IN_ROLLUP_FLAG
      , DEFECT_TRACKING_ON_FLAG
      , INVOICE_CLOSE_TOLERANCE
      , CHECK_SHORTAGES_FLAG
      , ITEM_TYPE
      , SUMMARY_FLAG
      , VMI_MINIMUM_DAYS
      , BOM_ITEM_TYPE
      , REPLENISH_TO_ORDER_FLAG
      , EAM_ITEM_TYPE
      , PLANNING_MAKE_BUY_CODE
      , GLOBAL_ATTRIBUTE_CATEGORY
      , UN_NUMBER_ID
      , CARRYING_COST
      , PRIMARY_SPECIALIST_ID
      , WEIGHT_UOM_CODE
      , MINIMUM_LICENSE_QUANTITY
      , GRADE_CONTROL_FLAG
      , VMI_FORECAST_TYPE
      , PAYMENT_TERMS_ID
      , OUTSIDE_OPERATION_UOM_TYPE
      , GLOBAL_ATTRIBUTE5
      , GLOBAL_ATTRIBUTE4
      , UNDER_RETURN_TOLERANCE
      , GLOBAL_ATTRIBUTE7
      , GLOBAL_ATTRIBUTE6
      , GLOBAL_ATTRIBUTE1
      , GLOBAL_ATTRIBUTE3
      , GLOBAL_ATTRIBUTE2
      , EAM_ACTIVITY_TYPE_CODE
      , STYLE_ITEM_ID
      , GLOBAL_ATTRIBUTE9
      , GLOBAL_ATTRIBUTE8
      , INVOICEABLE_ITEM_FLAG
      , ELECTRONIC_FLAG
      , POSTPROCESSING_LEAD_TIME
      , LIFECYCLE_ID
      , VMI_MAXIMUM_UNITS
      , SERVICEABLE_ITEM_CLASS_ID
      , CONTRACT_ITEM_TYPE_CODE
      , MODEL_CONFIG_CLAUSE_NAME
      , SERIAL_STATUS_ENABLED
      , EAM_ACT_SHUTDOWN_STATUS
      , AUTO_SERIAL_ALPHA_PREFIX
      , PLANNING_EXCEPTION_SET
      , PREPROCESSING_LEAD_TIME
      , RECEIVE_CLOSE_TOLERANCE
      , RETURN_INSPECTION_REQUIREMENT
      , COPY_LOT_ATTRIBUTE_FLAG
      , SO_AUTHORIZATION_FLAG
      , RETEST_INTERVAL
      , STOCK_ENABLED_FLAG
      , RECOVERED_PART_DISP_CODE
      , OVER_RETURN_TOLERANCE
      , CONFIG_MODEL_TYPE
      , ALLOW_ITEM_DESC_UPDATE_FLAG
      , INTERNAL_VOLUME
      , COVERAGE_SCHEDULE_ID
      , RFQ_REQUIRED_FLAG
      , MIN_MINMAX_QUANTITY
      , DEMAND_TIME_FENCE_CODE
      , ORDERABLE_ON_WEB_FLAG
      , CATALOG_STATUS_FLAG
      , SEGMENT11
      , SEGMENT10
      , FIXED_DAYS_SUPPLY
      , SEGMENT13
      , CYCLE_COUNT_ENABLED_FLAG
      , SEGMENT12
      , SEGMENT15
      , SEGMENT14
      , SEGMENT17
      , GLOBAL_ATTRIBUTE20
      , SEGMENT16
      , SEGMENT19
      , FIXED_LOT_MULTIPLIER
      , SEGMENT18
      , DAYS_TGT_INV_SUPPLY
      , SO_TRANSACTIONS_FLAG
      , CHILD_LOT_FLAG
      , GLOBAL_ATTRIBUTE17
      , GLOBAL_ATTRIBUTE18
      , GLOBAL_ATTRIBUTE15
      , GLOBAL_ATTRIBUTE16
      , GLOBAL_ATTRIBUTE13
      , GLOBAL_ATTRIBUTE14
      , VOL_DISCOUNT_EXEMPT_FLAG
      , PLANNED_INV_POINT_FLAG
      , GLOBAL_ATTRIBUTE11
      , GLOBAL_ATTRIBUTE12
      , PREVENTIVE_MAINTENANCE_FLAG
      , LOT_CONTROL_CODE
      , MAX_WARRANTY_AMOUNT
      , SUBSTITUTION_WINDOW_CODE
      , GLOBAL_ATTRIBUTE19
      , SEGMENT20
      , GDSN_OUTBOUND_ENABLED_FLAG
      , ORDER_COST
      , CHILD_LOT_VALIDATION_FLAG
      , UNDER_SHIPMENT_TOLERANCE
      , INVOICING_RULE_ID
      , COMMS_ACTIVATION_REQD_FLAG
      , HAZARD_CLASS_ID
      , EXPENSE_BILLABLE_FLAG
      , LOT_STATUS_ENABLED
      , EFFECTIVITY_CONTROL
      , ATTRIBUTE_CATEGORY
      , SUBSCRIPTION_DEPEND_FLAG
      , PROGRAM_APPLICATION_ID
      , VMI_MINIMUM_UNITS
      , TIME_BILLABLE_FLAG
      , PRORATE_SERVICE_FLAG
      , REPETITIVE_PLANNING_FLAG
      , ALLOW_SUBSTITUTE_RECEIPTS_FLAG
      , OVERCOMPLETION_TOLERANCE_TYPE
      , BOM_ENABLED_FLAG
      , SHIPPABLE_ITEM_FLAG
      , PURCHASING_ITEM_FLAG
      , SOURCE_TYPE
      , SERV_REQ_ENABLED_CODE
      , IB_ITEM_INSTANCE_CLASS
      , LOT_TRANSLATE_ENABLED
      , MAXIMUM_LOAD_WEIGHT
      , SERVICE_DURATION
      , MRP_SAFETY_STOCK_PERCENT
      , ALLOW_UNORDERED_RECEIPTS_FLAG
      , ALLOWED_UNITS_LOOKUP_CODE
      , LAST_UPDATE_LOGIN
      , PROCESS_SUPPLY_LOCATOR_ID
      , PROCESS_YIELD_SUBINVENTORY
      , ACCOUNTING_RULE_ID
      , VMI_MAXIMUM_DAYS
      , INVENTORY_ITEM_STATUS_CODE
      , TAX_CODE
      , AUTO_CREATED_CONFIG_FLAG
      , SUBCONTRACTING_COMPONENT
      , VMI_FIXED_ORDER_QUANTITY
      , PROGRAM_ID
      , CONTAINER_ITEM_FLAG
      , SEGMENT8
      , SEGMENT7
      , SEGMENT9
      , SERIAL_TAGGING_FLAG
      , SEGMENT4
      , SEGMENT3
      , EXPIRATION_ACTION_CODE
      , SEGMENT6
      , SEGMENT5
      , TRADE_ITEM_DESCRIPTOR
      , MINIMUM_FILL_PERCENT
      , END_DATE_ACTIVE
      , SALES_ACCOUNT
      , BACK_ORDERABLE_FLAG
      , STD_LOT_SIZE
      , FINANCING_ALLOWED_FLAG
      , LEAD_TIME_LOT_SIZE
      , PRIMARY_UOM_CODE
      , SHELF_LIFE_DAYS
      , CONTAINER_TYPE_CODE
      , DEFAULT_GRADE
      , CUSTOMER_ORDER_ENABLED_FLAG
      , ITEM_CATALOG_GROUP_ID
      , ATP_RULE_ID
      , SERVICE_STARTING_DELAY
      , RELEASE_TIME_FENCE_DAYS
      , OVERCOMPLETION_TOLERANCE_VALUE
      , UNIT_VOLUME
      , DESCRIPTION
      , CONVERGENCE
      , CUM_MANUFACTURING_LEAD_TIME
      , SHIP_MODEL_COMPLETE_FLAG
      , LOT_SUBSTITUTION_ENABLED
      , OUTSIDE_OPERATION_FLAG
      , AUTO_LOT_ALPHA_PREFIX
      , ATP_FLAG
      , EGO_MASTER_ITEMS_DFF_CTX
      , EAM_ACTIVITY_SOURCE_CODE
      , TAXABLE_FLAG
      , ALLOW_EXPRESS_DELIVERY_FLAG
      , PURCHASING_TAX_CODE
      , ENG_ITEM_FLAG
      , ENGINEERING_ITEM_ID
      , END_ASSEMBLY_PEGGING_FLAG
      , RETURNABLE_FLAG
      , PROCESS_YIELD_LOCATOR_ID
      , EAM_ACTIVITY_CAUSE_CODE
      , MATURITY_DAYS
      , ATP_COMPONENTS_FLAG
      , LAST_UPDATED_BY
      , COUPON_EXEMPT_FLAG
      , PLANNING_TIME_FENCE_DAYS
      , RECEIPT_REQUIRED_FLAG
      , VOLUME_UOM_CODE
      , LOCATION_CONTROL_CODE
      , WARRANTY_VENDOR_ID
      , INVENTORY_ASSET_FLAG
      , ENCUMBRANCE_ACCOUNT
      , SERVICEABLE_COMPONENT_FLAG
      , CUMULATIVE_TOTAL_LEAD_TIME
      , MRP_CALCULATE_ATP_FLAG
      , OUTSOURCED_ASSEMBLY
      , DEFAULT_LOT_STATUS_ID
      , VARIABLE_LEAD_TIME
      , AUTO_REDUCE_MPS
      , RECIPE_ENABLED_FLAG
      , ACCEPTABLE_RATE_DECREASE
      , BUILD_IN_WIP_FLAG
      , RECEIPT_DAYS_EXCEPTION_CODE
      , VEHICLE_ITEM_FLAG
      , CONFIG_MATCH
      , DOWNLOADABLE_FLAG
      , DEFAULT_SO_SOURCE_TYPE
      , FIXED_ORDER_QUANTITY
      , SUBSTITUTION_WINDOW_DAYS
      , EQUIPMENT_TYPE
      , CAS_NUMBER
      , SERV_IMPORTANCE_LEVEL
      , LOT_MERGE_ENABLED
      , SEGMENT2
      , CUSTOMER_ORDER_FLAG
      , ENABLED_FLAG
      , PURCHASING_ENABLED_FLAG
      , WH_UPDATE_DATE
      , OVERRUN_PERCENTAGE
      , ASSET_CREATION_CODE
      , DAYS_EARLY_RECEIPT_ALLOWED
      , NEGATIVE_MEASUREMENT_ERROR
      , BASE_WARRANTY_SERVICE_ID
      , START_AUTO_SERIAL_NUMBER
      , ROUNDING_CONTROL_TYPE
      , LOT_DIVISIBLE_FLAG
      , EXCLUDE_FROM_BUDGET_FLAG
      , MRP_PLANNING_CODE
      , BUYER_ID
      , RESERVABLE_TYPE
      , SOURCE_ORGANIZATION_ID
      , NEW_REVISION_CODE
      , DRP_PLANNED_FLAG
      , ASSET_CATEGORY_ID
      , MRP_SAFETY_STOCK_CODE
      , CONTINOUS_TRANSFER
      , HAZARDOUS_MATERIAL_FLAG
      , COSTING_ENABLED_FLAG
      , DIMENSION_UOM_CODE
      , SERVICE_DURATION_PERIOD_CODE
      , EVENT_FLAG
      , BULK_PICKED_FLAG
      , DEFAULT_SHIPPING_ORG
      , MATERIAL_BILLABLE_FLAG
      , PROCESS_QUALITY_ENABLED_FLAG
      , OPTION_SPECIFIC_SOURCED
      , SECONDARY_SPECIALIST_ID
      , PICKING_RULE_ID
      , EXPIRATION_ACTION_INTERVAL
      , ASN_AUTOEXPIRE_FLAG
      , START_AUTO_LOT_NUMBER
      , MINIMUM_ORDER_QUANTITY
      , COMMS_NL_TRACKABLE_FLAG
      , INVENTORY_CARRY_PENALTY
      , ENGINEERING_ECN_CODE
      , REPAIR_LEADTIME
      , SECONDARY_UOM_CODE
      , RECEIVING_ROUTING_ID
      , PRIMARY_UNIT_OF_MEASURE
      , CREATE_SUPPLY_FLAG
      , MAXIMUM_ORDER_QUANTITY
      , PROCESS_SUPPLY_SUBINVENTORY
      , PRODUCT_FAMILY_ITEM_ID
      , SOURCE_SUBINVENTORY
      , SERIAL_NUMBER_CONTROL_CODE
      , CREATED_BY
      , STYLE_ITEM_FLAG
      , CHARGE_PERIODICITY_CODE
      , INVOICE_ENABLED_FLAG
      , CONSIGNED_FLAG
      , DAYS_MAX_INV_SUPPLY
      , UNIT_HEIGHT
      , PROCESS_EXECUTION_ENABLED_FLAG
      , ROUNDING_FACTOR
      , OPERATION_SLACK_PENALTY
      , DEMAND_TIME_FENCE_DAYS
      , BASE_ITEM_ID
      , COLLATERAL_FLAG
      , REQUEST_ID
      , FULL_LEAD_TIME
      , SERVICE_ITEM_FLAG
      , INDIVISIBLE_FLAG
      , SERV_BILLING_ENABLED_FLAG
      , DIVERGENCE
      , SECONDARY_DEFAULT_IND
      , REVISION_QTY_CONTROL_CODE
      , QTY_RCV_TOLERANCE
      , DUAL_UOM_DEVIATION_HIGH
      , RELEASE_TIME_FENCE_CODE
      , ACCEPTABLE_RATE_INCREASE
      , RESTRICT_SUBINVENTORIES_CODE
      , CONFIG_ORGS
      , LAST_SUBMITTED_NIR_ID
      , RESTRICT_LOCATORS_CODE
      , CHILD_LOT_PREFIX
      , TRACKING_QUANTITY_IND
      , PROGRAM_UPDATE_DATE
      , START_DATE_ACTIVE
      , LIST_PRICE_PER_UNIT
      , CREATION_DATE
      , ENGINEERING_DATE
      , LAST_UPDATE_DATE
      , _FIVETRAN_DELETED
      , _FIVETRAN_ID
      , _FIVETRAN_SYNCED
      , PSA_DELETE_IND
      , PSA_LOAD_DTS
      , PSA_RECORD_SOURCE
      , LOAD_DTS
      , REC_SRC
      , HASHDIFF
    FROM LOGIC_itmb
)
---- FILTER LAYER ----

, FILTER_itmb as (
    SELECT *
    FROM RENAME_itmb
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM FILTER_itmb
)

---- FINAL LAYER ----
SELECT
          ITEM_HK
        , SEGMENT1
        , INVENTORY_ITEM_ID
        , ORGANIZATION_ID
        , WIP_SUPPLY_LOCATOR_ID
        , ATTRIBUTE30
        , REPAIR_PROGRAM
        , PARENT_CHILD_GENERATION_FLAG
        , DEFAULT_MATERIAL_STATUS_ID
        , INTERNAL_ORDER_FLAG
        , DAYS_TGT_INV_WINDOW
        , PLANNING_TIME_FENCE_CODE
        , ATTRIBUTE29
        , WEB_STATUS
        , ATTRIBUTE28
        , UNIT_WEIGHT
        , ATTRIBUTE27
        , ATTRIBUTE26
        , WIP_SUPPLY_TYPE
        , MTL_TRANSACTIONS_ENABLED_FLAG
        , ATTRIBUTE3
        , DAYS_LATE_RECEIPT_ALLOWED
        , ATTRIBUTE2
        , ATTRIBUTE1
        , ATTRIBUTE9
        , ATTRIBUTE8
        , ATTRIBUTE7
        , UNIT_WIDTH
        , QTY_RCV_EXCEPTION_CODE
        , ATTRIBUTE6
        , ATTRIBUTE5
        , ATTRIBUTE4
        , OVER_SHIPMENT_TOLERANCE
        , SHRINKAGE_RATE
        , LOT_SPLIT_ENABLED
        , ATTRIBUTE10
        , MUST_USE_APPROVED_VENDOR_FLAG
        , ATTRIBUTE14
        , WIP_SUPPLY_SUBINVENTORY
        , ATTRIBUTE13
        , PICK_COMPONENTS_FLAG
        , ATTRIBUTE12
        , ATTRIBUTE11
        , APPROVAL_STATUS
        , DUAL_UOM_CONTROL
        , ONT_PRICING_QTY_SOURCE
        , EXPENSE_ACCOUNT
        , ATTRIBUTE21
        , ATTRIBUTE20
        , RESPONSE_TIME_PERIOD_CODE
        , ATTRIBUTE25
        , ATTRIBUTE24
        , PRICE_TOLERANCE_PERCENT
        , ATTRIBUTE23
        , ATTRIBUTE22
        , DEFAULT_SERIAL_STATUS_ID
        , SERVICEABLE_PRODUCT_FLAG
        , CURRENT_PHASE_ID
        , RESPONSE_TIME_VALUE
        , PREPOSITION_POINT
        , MAX_MINMAX_QUANTITY
        , ATTRIBUTE18
        , EAM_ACT_NOTIFICATION_FLAG
        , ATTRIBUTE17
        , ATTRIBUTE16
        , ATTRIBUTE15
        , DUAL_UOM_DEVIATION_LOW
        , ATTRIBUTE19
        , PLANNER_CODE
        , INTERNAL_ORDER_ENABLED_FLAG
        , POSITIVE_MEASUREMENT_ERROR
        , GLOBAL_ATTRIBUTE10
        , INVENTORY_PLANNING_CODE
        , INVENTORY_ITEM_FLAG
        , COST_OF_SALES_ACCOUNT
        , OBJECT_VERSION_NUMBER
        , INSPECTION_REQUIRED_FLAG
        , CHILD_LOT_STARTING_NUMBER
        , DAYS_MAX_INV_WINDOW
        , MARKET_PRICE
        , UNIT_OF_ISSUE
        , ACCEPTABLE_EARLY_DAYS
        , FIXED_LEAD_TIME
        , HOLD_DAYS
        , ENFORCE_SHIP_TO_LOCATION_CODE
        , SHELF_LIFE_CODE
        , PROCESS_COSTING_ENABLED_FLAG
        , CRITICAL_COMPONENT_FLAG
        , VENDOR_WARRANTY_FLAG
        , FORECAST_HORIZON
        , ATO_FORECAST_CONTROL
        , USAGE_ITEM_FLAG
        , SAFETY_STOCK_BUCKET_DAYS
        , REPAIR_YIELD
        , UNIT_LENGTH
        , DEFAULT_INCLUDE_IN_ROLLUP_FLAG
        , DEFECT_TRACKING_ON_FLAG
        , INVOICE_CLOSE_TOLERANCE
        , CHECK_SHORTAGES_FLAG
        , ITEM_TYPE
        , SUMMARY_FLAG
        , VMI_MINIMUM_DAYS
        , BOM_ITEM_TYPE
        , REPLENISH_TO_ORDER_FLAG
        , EAM_ITEM_TYPE
        , PLANNING_MAKE_BUY_CODE
        , GLOBAL_ATTRIBUTE_CATEGORY
        , UN_NUMBER_ID
        , CARRYING_COST
        , PRIMARY_SPECIALIST_ID
        , WEIGHT_UOM_CODE
        , MINIMUM_LICENSE_QUANTITY
        , GRADE_CONTROL_FLAG
        , VMI_FORECAST_TYPE
        , PAYMENT_TERMS_ID
        , OUTSIDE_OPERATION_UOM_TYPE
        , GLOBAL_ATTRIBUTE5
        , GLOBAL_ATTRIBUTE4
        , UNDER_RETURN_TOLERANCE
        , GLOBAL_ATTRIBUTE7
        , GLOBAL_ATTRIBUTE6
        , GLOBAL_ATTRIBUTE1
        , GLOBAL_ATTRIBUTE3
        , GLOBAL_ATTRIBUTE2
        , EAM_ACTIVITY_TYPE_CODE
        , STYLE_ITEM_ID
        , GLOBAL_ATTRIBUTE9
        , GLOBAL_ATTRIBUTE8
        , INVOICEABLE_ITEM_FLAG
        , ELECTRONIC_FLAG
        , POSTPROCESSING_LEAD_TIME
        , LIFECYCLE_ID
        , VMI_MAXIMUM_UNITS
        , SERVICEABLE_ITEM_CLASS_ID
        , CONTRACT_ITEM_TYPE_CODE
        , MODEL_CONFIG_CLAUSE_NAME
        , SERIAL_STATUS_ENABLED
        , EAM_ACT_SHUTDOWN_STATUS
        , AUTO_SERIAL_ALPHA_PREFIX
        , PLANNING_EXCEPTION_SET
        , PREPROCESSING_LEAD_TIME
        , RECEIVE_CLOSE_TOLERANCE
        , RETURN_INSPECTION_REQUIREMENT
        , COPY_LOT_ATTRIBUTE_FLAG
        , SO_AUTHORIZATION_FLAG
        , RETEST_INTERVAL
        , STOCK_ENABLED_FLAG
        , RECOVERED_PART_DISP_CODE
        , OVER_RETURN_TOLERANCE
        , CONFIG_MODEL_TYPE
        , ALLOW_ITEM_DESC_UPDATE_FLAG
        , INTERNAL_VOLUME
        , COVERAGE_SCHEDULE_ID
        , RFQ_REQUIRED_FLAG
        , MIN_MINMAX_QUANTITY
        , DEMAND_TIME_FENCE_CODE
        , ORDERABLE_ON_WEB_FLAG
        , CATALOG_STATUS_FLAG
        , SEGMENT11
        , SEGMENT10
        , FIXED_DAYS_SUPPLY
        , SEGMENT13
        , CYCLE_COUNT_ENABLED_FLAG
        , SEGMENT12
        , SEGMENT15
        , SEGMENT14
        , SEGMENT17
        , GLOBAL_ATTRIBUTE20
        , SEGMENT16
        , SEGMENT19
        , FIXED_LOT_MULTIPLIER
        , SEGMENT18
        , DAYS_TGT_INV_SUPPLY
        , SO_TRANSACTIONS_FLAG
        , CHILD_LOT_FLAG
        , GLOBAL_ATTRIBUTE17
        , GLOBAL_ATTRIBUTE18
        , GLOBAL_ATTRIBUTE15
        , GLOBAL_ATTRIBUTE16
        , GLOBAL_ATTRIBUTE13
        , GLOBAL_ATTRIBUTE14
        , VOL_DISCOUNT_EXEMPT_FLAG
        , PLANNED_INV_POINT_FLAG
        , GLOBAL_ATTRIBUTE11
        , GLOBAL_ATTRIBUTE12
        , PREVENTIVE_MAINTENANCE_FLAG
        , LOT_CONTROL_CODE
        , MAX_WARRANTY_AMOUNT
        , SUBSTITUTION_WINDOW_CODE
        , GLOBAL_ATTRIBUTE19
        , SEGMENT20
        , GDSN_OUTBOUND_ENABLED_FLAG
        , ORDER_COST
        , CHILD_LOT_VALIDATION_FLAG
        , UNDER_SHIPMENT_TOLERANCE
        , INVOICING_RULE_ID
        , COMMS_ACTIVATION_REQD_FLAG
        , HAZARD_CLASS_ID
        , EXPENSE_BILLABLE_FLAG
        , LOT_STATUS_ENABLED
        , EFFECTIVITY_CONTROL
        , ATTRIBUTE_CATEGORY
        , SUBSCRIPTION_DEPEND_FLAG
        , PROGRAM_APPLICATION_ID
        , VMI_MINIMUM_UNITS
        , TIME_BILLABLE_FLAG
        , PRORATE_SERVICE_FLAG
        , REPETITIVE_PLANNING_FLAG
        , ALLOW_SUBSTITUTE_RECEIPTS_FLAG
        , OVERCOMPLETION_TOLERANCE_TYPE
        , BOM_ENABLED_FLAG
        , SHIPPABLE_ITEM_FLAG
        , PURCHASING_ITEM_FLAG
        , SOURCE_TYPE
        , SERV_REQ_ENABLED_CODE
        , IB_ITEM_INSTANCE_CLASS
        , LOT_TRANSLATE_ENABLED
        , MAXIMUM_LOAD_WEIGHT
        , SERVICE_DURATION
        , MRP_SAFETY_STOCK_PERCENT
        , ALLOW_UNORDERED_RECEIPTS_FLAG
        , ALLOWED_UNITS_LOOKUP_CODE
        , LAST_UPDATE_LOGIN
        , PROCESS_SUPPLY_LOCATOR_ID
        , PROCESS_YIELD_SUBINVENTORY
        , ACCOUNTING_RULE_ID
        , VMI_MAXIMUM_DAYS
        , INVENTORY_ITEM_STATUS_CODE
        , TAX_CODE
        , AUTO_CREATED_CONFIG_FLAG
        , SUBCONTRACTING_COMPONENT
        , VMI_FIXED_ORDER_QUANTITY
        , PROGRAM_ID
        , CONTAINER_ITEM_FLAG
        , SEGMENT8
        , SEGMENT7
        , SEGMENT9
        , SERIAL_TAGGING_FLAG
        , SEGMENT4
        , SEGMENT3
        , EXPIRATION_ACTION_CODE
        , SEGMENT6
        , SEGMENT5
        , TRADE_ITEM_DESCRIPTOR
        , MINIMUM_FILL_PERCENT
        , END_DATE_ACTIVE
        , SALES_ACCOUNT
        , BACK_ORDERABLE_FLAG
        , STD_LOT_SIZE
        , FINANCING_ALLOWED_FLAG
        , LEAD_TIME_LOT_SIZE
        , PRIMARY_UOM_CODE
        , SHELF_LIFE_DAYS
        , CONTAINER_TYPE_CODE
        , DEFAULT_GRADE
        , CUSTOMER_ORDER_ENABLED_FLAG
        , ITEM_CATALOG_GROUP_ID
        , ATP_RULE_ID
        , SERVICE_STARTING_DELAY
        , RELEASE_TIME_FENCE_DAYS
        , OVERCOMPLETION_TOLERANCE_VALUE
        , UNIT_VOLUME
        , DESCRIPTION
        , CONVERGENCE
        , CUM_MANUFACTURING_LEAD_TIME
        , SHIP_MODEL_COMPLETE_FLAG
        , LOT_SUBSTITUTION_ENABLED
        , OUTSIDE_OPERATION_FLAG
        , AUTO_LOT_ALPHA_PREFIX
        , ATP_FLAG
        , EGO_MASTER_ITEMS_DFF_CTX
        , EAM_ACTIVITY_SOURCE_CODE
        , TAXABLE_FLAG
        , ALLOW_EXPRESS_DELIVERY_FLAG
        , PURCHASING_TAX_CODE
        , ENG_ITEM_FLAG
        , ENGINEERING_ITEM_ID
        , END_ASSEMBLY_PEGGING_FLAG
        , RETURNABLE_FLAG
        , PROCESS_YIELD_LOCATOR_ID
        , EAM_ACTIVITY_CAUSE_CODE
        , MATURITY_DAYS
        , ATP_COMPONENTS_FLAG
        , LAST_UPDATED_BY
        , COUPON_EXEMPT_FLAG
        , PLANNING_TIME_FENCE_DAYS
        , RECEIPT_REQUIRED_FLAG
        , VOLUME_UOM_CODE
        , LOCATION_CONTROL_CODE
        , WARRANTY_VENDOR_ID
        , INVENTORY_ASSET_FLAG
        , ENCUMBRANCE_ACCOUNT
        , SERVICEABLE_COMPONENT_FLAG
        , CUMULATIVE_TOTAL_LEAD_TIME
        , MRP_CALCULATE_ATP_FLAG
        , OUTSOURCED_ASSEMBLY
        , DEFAULT_LOT_STATUS_ID
        , VARIABLE_LEAD_TIME
        , AUTO_REDUCE_MPS
        , RECIPE_ENABLED_FLAG
        , ACCEPTABLE_RATE_DECREASE
        , BUILD_IN_WIP_FLAG
        , RECEIPT_DAYS_EXCEPTION_CODE
        , VEHICLE_ITEM_FLAG
        , CONFIG_MATCH
        , DOWNLOADABLE_FLAG
        , DEFAULT_SO_SOURCE_TYPE
        , FIXED_ORDER_QUANTITY
        , SUBSTITUTION_WINDOW_DAYS
        , EQUIPMENT_TYPE
        , CAS_NUMBER
        , SERV_IMPORTANCE_LEVEL
        , LOT_MERGE_ENABLED
        , SEGMENT2
        , CUSTOMER_ORDER_FLAG
        , ENABLED_FLAG
        , PURCHASING_ENABLED_FLAG
        , WH_UPDATE_DATE
        , OVERRUN_PERCENTAGE
        , ASSET_CREATION_CODE
        , DAYS_EARLY_RECEIPT_ALLOWED
        , NEGATIVE_MEASUREMENT_ERROR
        , BASE_WARRANTY_SERVICE_ID
        , START_AUTO_SERIAL_NUMBER
        , ROUNDING_CONTROL_TYPE
        , LOT_DIVISIBLE_FLAG
        , EXCLUDE_FROM_BUDGET_FLAG
        , MRP_PLANNING_CODE
        , BUYER_ID
        , RESERVABLE_TYPE
        , SOURCE_ORGANIZATION_ID
        , NEW_REVISION_CODE
        , DRP_PLANNED_FLAG
        , ASSET_CATEGORY_ID
        , MRP_SAFETY_STOCK_CODE
        , CONTINOUS_TRANSFER
        , HAZARDOUS_MATERIAL_FLAG
        , COSTING_ENABLED_FLAG
        , DIMENSION_UOM_CODE
        , SERVICE_DURATION_PERIOD_CODE
        , EVENT_FLAG
        , BULK_PICKED_FLAG
        , DEFAULT_SHIPPING_ORG
        , MATERIAL_BILLABLE_FLAG
        , PROCESS_QUALITY_ENABLED_FLAG
        , OPTION_SPECIFIC_SOURCED
        , SECONDARY_SPECIALIST_ID
        , PICKING_RULE_ID
        , EXPIRATION_ACTION_INTERVAL
        , ASN_AUTOEXPIRE_FLAG
        , START_AUTO_LOT_NUMBER
        , MINIMUM_ORDER_QUANTITY
        , COMMS_NL_TRACKABLE_FLAG
        , INVENTORY_CARRY_PENALTY
        , ENGINEERING_ECN_CODE
        , REPAIR_LEADTIME
        , SECONDARY_UOM_CODE
        , RECEIVING_ROUTING_ID
        , PRIMARY_UNIT_OF_MEASURE
        , CREATE_SUPPLY_FLAG
        , MAXIMUM_ORDER_QUANTITY
        , PROCESS_SUPPLY_SUBINVENTORY
        , PRODUCT_FAMILY_ITEM_ID
        , SOURCE_SUBINVENTORY
        , SERIAL_NUMBER_CONTROL_CODE
        , CREATED_BY
        , STYLE_ITEM_FLAG
        , CHARGE_PERIODICITY_CODE
        , INVOICE_ENABLED_FLAG
        , CONSIGNED_FLAG
        , DAYS_MAX_INV_SUPPLY
        , UNIT_HEIGHT
        , PROCESS_EXECUTION_ENABLED_FLAG
        , ROUNDING_FACTOR
        , OPERATION_SLACK_PENALTY
        , DEMAND_TIME_FENCE_DAYS
        , BASE_ITEM_ID
        , COLLATERAL_FLAG
        , REQUEST_ID
        , FULL_LEAD_TIME
        , SERVICE_ITEM_FLAG
        , INDIVISIBLE_FLAG
        , SERV_BILLING_ENABLED_FLAG
        , DIVERGENCE
        , SECONDARY_DEFAULT_IND
        , REVISION_QTY_CONTROL_CODE
        , QTY_RCV_TOLERANCE
        , DUAL_UOM_DEVIATION_HIGH
        , RELEASE_TIME_FENCE_CODE
        , ACCEPTABLE_RATE_INCREASE
        , RESTRICT_SUBINVENTORIES_CODE
        , CONFIG_ORGS
        , LAST_SUBMITTED_NIR_ID
        , RESTRICT_LOCATORS_CODE
        , CHILD_LOT_PREFIX
        , TRACKING_QUANTITY_IND
        , PROGRAM_UPDATE_DATE
        , START_DATE_ACTIVE
        , LIST_PRICE_PER_UNIT
        , CREATION_DATE
        , ENGINEERING_DATE
        , LAST_UPDATE_DATE
        , _FIVETRAN_DELETED
        , _FIVETRAN_ID
        , _FIVETRAN_SYNCED
        , PSA_DELETE_IND
        , PSA_LOAD_DTS
        , PSA_RECORD_SOURCE
        , LOAD_DTS
        , REC_SRC
        , HASHDIFF
FROM JOIN_RESULT
{% if is_incremental() %}
WHERE NOT EXISTS (
    SELECT 1 
    FROM {{ this }} existing
    WHERE existing.ITEM_HK= JOIN_RESULT.ITEM_HK
     AND existing.INVENTORY_ITEM_ID = JOIN_RESULT.INVENTORY_ITEM_ID 
     AND existing.ORGANIZATION_ID = JOIN_RESULT.ORGANIZATION_ID 
    AND existing.HASHDIFF = JOIN_RESULT.HASHDIFF
)
{% endif %}
{% if not is_incremental() %}

/* The following qualifier is implemented to prevent multiple loads of touched records during the initial build, such as multiple rows per HK and hashdiff. */
qualify 1 = row_number() over (partition by ITEM_HK, INVENTORY_ITEM_ID, ORGANIZATION_ID, HASHDIFF order by PSA_LOAD_DTS)

union all
SELECT 
MD5_BINARY(GR.VALUE) AS ITEM_HK,
GR.VALUE::text AS SEGMENT1,
GR.VALUE::number AS INVENTORY_ITEM_ID,
GR.VALUE::number AS ORGANIZATION_ID,
NULL AS WIP_SUPPLY_LOCATOR_ID,
NULL AS ATTRIBUTE30,
NULL AS REPAIR_PROGRAM,
NULL AS PARENT_CHILD_GENERATION_FLAG,
NULL AS DEFAULT_MATERIAL_STATUS_ID,
NULL AS INTERNAL_ORDER_FLAG,
NULL AS DAYS_TGT_INV_WINDOW,
NULL AS PLANNING_TIME_FENCE_CODE,
NULL AS ATTRIBUTE29,
NULL AS WEB_STATUS,
NULL AS ATTRIBUTE28,
NULL AS UNIT_WEIGHT,
NULL AS ATTRIBUTE27,
NULL AS ATTRIBUTE26,
NULL AS WIP_SUPPLY_TYPE,
NULL AS MTL_TRANSACTIONS_ENABLED_FLAG,
NULL AS ATTRIBUTE3,
NULL AS DAYS_LATE_RECEIPT_ALLOWED,
NULL AS ATTRIBUTE2,
NULL AS ATTRIBUTE1,
NULL AS ATTRIBUTE9,
NULL AS ATTRIBUTE8,
NULL AS ATTRIBUTE7,
NULL AS UNIT_WIDTH,
NULL AS QTY_RCV_EXCEPTION_CODE,
NULL AS ATTRIBUTE6,
NULL AS ATTRIBUTE5,
NULL AS ATTRIBUTE4,
NULL AS OVER_SHIPMENT_TOLERANCE,
NULL AS SHRINKAGE_RATE,
NULL AS LOT_SPLIT_ENABLED,
NULL AS ATTRIBUTE10,
NULL AS MUST_USE_APPROVED_VENDOR_FLAG,
NULL AS ATTRIBUTE14,
NULL AS WIP_SUPPLY_SUBINVENTORY,
NULL AS ATTRIBUTE13,
NULL AS PICK_COMPONENTS_FLAG,
NULL AS ATTRIBUTE12,
NULL AS ATTRIBUTE11,
NULL AS APPROVAL_STATUS,
NULL AS DUAL_UOM_CONTROL,
NULL AS ONT_PRICING_QTY_SOURCE,
NULL AS EXPENSE_ACCOUNT,
NULL AS ATTRIBUTE21,
NULL AS ATTRIBUTE20,
NULL AS RESPONSE_TIME_PERIOD_CODE,
NULL AS ATTRIBUTE25,
NULL AS ATTRIBUTE24,
NULL AS PRICE_TOLERANCE_PERCENT,
NULL AS ATTRIBUTE23,
NULL AS ATTRIBUTE22,
NULL AS DEFAULT_SERIAL_STATUS_ID,
NULL AS SERVICEABLE_PRODUCT_FLAG,
NULL AS CURRENT_PHASE_ID,
NULL AS RESPONSE_TIME_VALUE,
NULL AS PREPOSITION_POINT,
NULL AS MAX_MINMAX_QUANTITY,
NULL AS ATTRIBUTE18,
NULL AS EAM_ACT_NOTIFICATION_FLAG,
NULL AS ATTRIBUTE17,
NULL AS ATTRIBUTE16,
NULL AS ATTRIBUTE15,
NULL AS DUAL_UOM_DEVIATION_LOW,
NULL AS ATTRIBUTE19,
NULL AS PLANNER_CODE,
NULL AS INTERNAL_ORDER_ENABLED_FLAG,
NULL AS POSITIVE_MEASUREMENT_ERROR,
NULL AS GLOBAL_ATTRIBUTE10,
NULL AS INVENTORY_PLANNING_CODE,
NULL AS INVENTORY_ITEM_FLAG,
NULL AS COST_OF_SALES_ACCOUNT,
NULL AS OBJECT_VERSION_NUMBER,
NULL AS INSPECTION_REQUIRED_FLAG,
NULL AS CHILD_LOT_STARTING_NUMBER,
NULL AS DAYS_MAX_INV_WINDOW,
NULL AS MARKET_PRICE,
NULL AS UNIT_OF_ISSUE,
NULL AS ACCEPTABLE_EARLY_DAYS,
NULL AS FIXED_LEAD_TIME,
NULL AS HOLD_DAYS,
NULL AS ENFORCE_SHIP_TO_LOCATION_CODE,
NULL AS SHELF_LIFE_CODE,
NULL AS PROCESS_COSTING_ENABLED_FLAG,
NULL AS CRITICAL_COMPONENT_FLAG,
NULL AS VENDOR_WARRANTY_FLAG,
NULL AS FORECAST_HORIZON,
NULL AS ATO_FORECAST_CONTROL,
NULL AS USAGE_ITEM_FLAG,
NULL AS SAFETY_STOCK_BUCKET_DAYS,
NULL AS REPAIR_YIELD,
NULL AS UNIT_LENGTH,
NULL AS DEFAULT_INCLUDE_IN_ROLLUP_FLAG,
NULL AS DEFECT_TRACKING_ON_FLAG,
NULL AS INVOICE_CLOSE_TOLERANCE,
NULL AS CHECK_SHORTAGES_FLAG,
NULL AS ITEM_TYPE,
NULL AS SUMMARY_FLAG,
NULL AS VMI_MINIMUM_DAYS,
NULL AS BOM_ITEM_TYPE,
NULL AS REPLENISH_TO_ORDER_FLAG,
NULL AS EAM_ITEM_TYPE,
NULL AS PLANNING_MAKE_BUY_CODE,
NULL AS GLOBAL_ATTRIBUTE_CATEGORY,
NULL AS UN_NUMBER_ID,
NULL AS CARRYING_COST,
NULL AS PRIMARY_SPECIALIST_ID,
NULL AS WEIGHT_UOM_CODE,
NULL AS MINIMUM_LICENSE_QUANTITY,
NULL AS GRADE_CONTROL_FLAG,
NULL AS VMI_FORECAST_TYPE,
NULL AS PAYMENT_TERMS_ID,
NULL AS OUTSIDE_OPERATION_UOM_TYPE,
NULL AS GLOBAL_ATTRIBUTE5,
NULL AS GLOBAL_ATTRIBUTE4,
NULL AS UNDER_RETURN_TOLERANCE,
NULL AS GLOBAL_ATTRIBUTE7,
NULL AS GLOBAL_ATTRIBUTE6,
NULL AS GLOBAL_ATTRIBUTE1,
NULL AS GLOBAL_ATTRIBUTE3,
NULL AS GLOBAL_ATTRIBUTE2,
NULL AS EAM_ACTIVITY_TYPE_CODE,
NULL AS STYLE_ITEM_ID,
NULL AS GLOBAL_ATTRIBUTE9,
NULL AS GLOBAL_ATTRIBUTE8,
NULL AS INVOICEABLE_ITEM_FLAG,
NULL AS ELECTRONIC_FLAG,
NULL AS POSTPROCESSING_LEAD_TIME,
NULL AS LIFECYCLE_ID,
NULL AS VMI_MAXIMUM_UNITS,
NULL AS SERVICEABLE_ITEM_CLASS_ID,
NULL AS CONTRACT_ITEM_TYPE_CODE,
NULL AS MODEL_CONFIG_CLAUSE_NAME,
NULL AS SERIAL_STATUS_ENABLED,
NULL AS EAM_ACT_SHUTDOWN_STATUS,
NULL AS AUTO_SERIAL_ALPHA_PREFIX,
NULL AS PLANNING_EXCEPTION_SET,
NULL AS PREPROCESSING_LEAD_TIME,
NULL AS RECEIVE_CLOSE_TOLERANCE,
NULL AS RETURN_INSPECTION_REQUIREMENT,
NULL AS COPY_LOT_ATTRIBUTE_FLAG,
NULL AS SO_AUTHORIZATION_FLAG,
NULL AS RETEST_INTERVAL,
NULL AS STOCK_ENABLED_FLAG,
NULL AS RECOVERED_PART_DISP_CODE,
NULL AS OVER_RETURN_TOLERANCE,
NULL AS CONFIG_MODEL_TYPE,
NULL AS ALLOW_ITEM_DESC_UPDATE_FLAG,
NULL AS INTERNAL_VOLUME,
NULL AS COVERAGE_SCHEDULE_ID,
NULL AS RFQ_REQUIRED_FLAG,
NULL AS MIN_MINMAX_QUANTITY,
NULL AS DEMAND_TIME_FENCE_CODE,
NULL AS ORDERABLE_ON_WEB_FLAG,
NULL AS CATALOG_STATUS_FLAG,
NULL AS SEGMENT11,
NULL AS SEGMENT10,
NULL AS FIXED_DAYS_SUPPLY,
NULL AS SEGMENT13,
NULL AS CYCLE_COUNT_ENABLED_FLAG,
NULL AS SEGMENT12,
NULL AS SEGMENT15,
NULL AS SEGMENT14,
NULL AS SEGMENT17,
NULL AS GLOBAL_ATTRIBUTE20,
NULL AS SEGMENT16,
NULL AS SEGMENT19,
NULL AS FIXED_LOT_MULTIPLIER,
NULL AS SEGMENT18,
NULL AS DAYS_TGT_INV_SUPPLY,
NULL AS SO_TRANSACTIONS_FLAG,
NULL AS CHILD_LOT_FLAG,
NULL AS GLOBAL_ATTRIBUTE17,
NULL AS GLOBAL_ATTRIBUTE18,
NULL AS GLOBAL_ATTRIBUTE15,
NULL AS GLOBAL_ATTRIBUTE16,
NULL AS GLOBAL_ATTRIBUTE13,
NULL AS GLOBAL_ATTRIBUTE14,
NULL AS VOL_DISCOUNT_EXEMPT_FLAG,
NULL AS PLANNED_INV_POINT_FLAG,
NULL AS GLOBAL_ATTRIBUTE11,
NULL AS GLOBAL_ATTRIBUTE12,
NULL AS PREVENTIVE_MAINTENANCE_FLAG,
NULL AS LOT_CONTROL_CODE,
NULL AS MAX_WARRANTY_AMOUNT,
NULL AS SUBSTITUTION_WINDOW_CODE,
NULL AS GLOBAL_ATTRIBUTE19,
NULL AS SEGMENT20,
NULL AS GDSN_OUTBOUND_ENABLED_FLAG,
NULL AS ORDER_COST,
NULL AS CHILD_LOT_VALIDATION_FLAG,
NULL AS UNDER_SHIPMENT_TOLERANCE,
NULL AS INVOICING_RULE_ID,
NULL AS COMMS_ACTIVATION_REQD_FLAG,
NULL AS HAZARD_CLASS_ID,
NULL AS EXPENSE_BILLABLE_FLAG,
NULL AS LOT_STATUS_ENABLED,
NULL AS EFFECTIVITY_CONTROL,
NULL AS ATTRIBUTE_CATEGORY,
NULL AS SUBSCRIPTION_DEPEND_FLAG,
NULL AS PROGRAM_APPLICATION_ID,
NULL AS VMI_MINIMUM_UNITS,
NULL AS TIME_BILLABLE_FLAG,
NULL AS PRORATE_SERVICE_FLAG,
NULL AS REPETITIVE_PLANNING_FLAG,
NULL AS ALLOW_SUBSTITUTE_RECEIPTS_FLAG,
NULL AS OVERCOMPLETION_TOLERANCE_TYPE,
NULL AS BOM_ENABLED_FLAG,
NULL AS SHIPPABLE_ITEM_FLAG,
NULL AS PURCHASING_ITEM_FLAG,
NULL AS SOURCE_TYPE,
NULL AS SERV_REQ_ENABLED_CODE,
NULL AS IB_ITEM_INSTANCE_CLASS,
NULL AS LOT_TRANSLATE_ENABLED,
NULL AS MAXIMUM_LOAD_WEIGHT,
NULL AS SERVICE_DURATION,
NULL AS MRP_SAFETY_STOCK_PERCENT,
NULL AS ALLOW_UNORDERED_RECEIPTS_FLAG,
NULL AS ALLOWED_UNITS_LOOKUP_CODE,
NULL AS LAST_UPDATE_LOGIN,
NULL AS PROCESS_SUPPLY_LOCATOR_ID,
NULL AS PROCESS_YIELD_SUBINVENTORY,
NULL AS ACCOUNTING_RULE_ID,
NULL AS VMI_MAXIMUM_DAYS,
NULL AS INVENTORY_ITEM_STATUS_CODE,
NULL AS TAX_CODE,
NULL AS AUTO_CREATED_CONFIG_FLAG,
NULL AS SUBCONTRACTING_COMPONENT,
NULL AS VMI_FIXED_ORDER_QUANTITY,
NULL AS PROGRAM_ID,
NULL AS CONTAINER_ITEM_FLAG,
NULL AS SEGMENT8,
NULL AS SEGMENT7,
NULL AS SEGMENT9,
NULL AS SERIAL_TAGGING_FLAG,
NULL AS SEGMENT4,
NULL AS SEGMENT3,
NULL AS EXPIRATION_ACTION_CODE,
NULL AS SEGMENT6,
NULL AS SEGMENT5,
NULL AS TRADE_ITEM_DESCRIPTOR,
NULL AS MINIMUM_FILL_PERCENT,
NULL AS END_DATE_ACTIVE,
NULL AS SALES_ACCOUNT,
NULL AS BACK_ORDERABLE_FLAG,
NULL AS STD_LOT_SIZE,
NULL AS FINANCING_ALLOWED_FLAG,
NULL AS LEAD_TIME_LOT_SIZE,
NULL AS PRIMARY_UOM_CODE,
NULL AS SHELF_LIFE_DAYS,
NULL AS CONTAINER_TYPE_CODE,
NULL AS DEFAULT_GRADE,
NULL AS CUSTOMER_ORDER_ENABLED_FLAG,
NULL AS ITEM_CATALOG_GROUP_ID,
NULL AS ATP_RULE_ID,
NULL AS SERVICE_STARTING_DELAY,
NULL AS RELEASE_TIME_FENCE_DAYS,
NULL AS OVERCOMPLETION_TOLERANCE_VALUE,
NULL AS UNIT_VOLUME,
NULL AS DESCRIPTION,
NULL AS CONVERGENCE,
NULL AS CUM_MANUFACTURING_LEAD_TIME,
NULL AS SHIP_MODEL_COMPLETE_FLAG,
NULL AS LOT_SUBSTITUTION_ENABLED,
NULL AS OUTSIDE_OPERATION_FLAG,
NULL AS AUTO_LOT_ALPHA_PREFIX,
NULL AS ATP_FLAG,
NULL AS EGO_MASTER_ITEMS_DFF_CTX,
NULL AS EAM_ACTIVITY_SOURCE_CODE,
NULL AS TAXABLE_FLAG,
NULL AS ALLOW_EXPRESS_DELIVERY_FLAG,
NULL AS PURCHASING_TAX_CODE,
NULL AS ENG_ITEM_FLAG,
NULL AS ENGINEERING_ITEM_ID,
NULL AS END_ASSEMBLY_PEGGING_FLAG,
NULL AS RETURNABLE_FLAG,
NULL AS PROCESS_YIELD_LOCATOR_ID,
NULL AS EAM_ACTIVITY_CAUSE_CODE,
NULL AS MATURITY_DAYS,
NULL AS ATP_COMPONENTS_FLAG,
NULL AS LAST_UPDATED_BY,
NULL AS COUPON_EXEMPT_FLAG,
NULL AS PLANNING_TIME_FENCE_DAYS,
NULL AS RECEIPT_REQUIRED_FLAG,
NULL AS VOLUME_UOM_CODE,
NULL AS LOCATION_CONTROL_CODE,
NULL AS WARRANTY_VENDOR_ID,
NULL AS INVENTORY_ASSET_FLAG,
NULL AS ENCUMBRANCE_ACCOUNT,
NULL AS SERVICEABLE_COMPONENT_FLAG,
NULL AS CUMULATIVE_TOTAL_LEAD_TIME,
NULL AS MRP_CALCULATE_ATP_FLAG,
NULL AS OUTSOURCED_ASSEMBLY,
NULL AS DEFAULT_LOT_STATUS_ID,
NULL AS VARIABLE_LEAD_TIME,
NULL AS AUTO_REDUCE_MPS,
NULL AS RECIPE_ENABLED_FLAG,
NULL AS ACCEPTABLE_RATE_DECREASE,
NULL AS BUILD_IN_WIP_FLAG,
NULL AS RECEIPT_DAYS_EXCEPTION_CODE,
NULL AS VEHICLE_ITEM_FLAG,
NULL AS CONFIG_MATCH,
NULL AS DOWNLOADABLE_FLAG,
NULL AS DEFAULT_SO_SOURCE_TYPE,
NULL AS FIXED_ORDER_QUANTITY,
NULL AS SUBSTITUTION_WINDOW_DAYS,
NULL AS EQUIPMENT_TYPE,
NULL AS CAS_NUMBER,
NULL AS SERV_IMPORTANCE_LEVEL,
NULL AS LOT_MERGE_ENABLED,
NULL AS SEGMENT2,
NULL AS CUSTOMER_ORDER_FLAG,
NULL AS ENABLED_FLAG,
NULL AS PURCHASING_ENABLED_FLAG,
NULL AS WH_UPDATE_DATE,
NULL AS OVERRUN_PERCENTAGE,
NULL AS ASSET_CREATION_CODE,
NULL AS DAYS_EARLY_RECEIPT_ALLOWED,
NULL AS NEGATIVE_MEASUREMENT_ERROR,
NULL AS BASE_WARRANTY_SERVICE_ID,
NULL AS START_AUTO_SERIAL_NUMBER,
NULL AS ROUNDING_CONTROL_TYPE,
NULL AS LOT_DIVISIBLE_FLAG,
NULL AS EXCLUDE_FROM_BUDGET_FLAG,
NULL AS MRP_PLANNING_CODE,
NULL AS BUYER_ID,
NULL AS RESERVABLE_TYPE,
NULL AS SOURCE_ORGANIZATION_ID,
NULL AS NEW_REVISION_CODE,
NULL AS DRP_PLANNED_FLAG,
NULL AS ASSET_CATEGORY_ID,
NULL AS MRP_SAFETY_STOCK_CODE,
NULL AS CONTINOUS_TRANSFER,
NULL AS HAZARDOUS_MATERIAL_FLAG,
NULL AS COSTING_ENABLED_FLAG,
NULL AS DIMENSION_UOM_CODE,
NULL AS SERVICE_DURATION_PERIOD_CODE,
NULL AS EVENT_FLAG,
NULL AS BULK_PICKED_FLAG,
NULL AS DEFAULT_SHIPPING_ORG,
NULL AS MATERIAL_BILLABLE_FLAG,
NULL AS PROCESS_QUALITY_ENABLED_FLAG,
NULL AS OPTION_SPECIFIC_SOURCED,
NULL AS SECONDARY_SPECIALIST_ID,
NULL AS PICKING_RULE_ID,
NULL AS EXPIRATION_ACTION_INTERVAL,
NULL AS ASN_AUTOEXPIRE_FLAG,
NULL AS START_AUTO_LOT_NUMBER,
NULL AS MINIMUM_ORDER_QUANTITY,
NULL AS COMMS_NL_TRACKABLE_FLAG,
NULL AS INVENTORY_CARRY_PENALTY,
NULL AS ENGINEERING_ECN_CODE,
NULL AS REPAIR_LEADTIME,
NULL AS SECONDARY_UOM_CODE,
NULL AS RECEIVING_ROUTING_ID,
NULL AS PRIMARY_UNIT_OF_MEASURE,
NULL AS CREATE_SUPPLY_FLAG,
NULL AS MAXIMUM_ORDER_QUANTITY,
NULL AS PROCESS_SUPPLY_SUBINVENTORY,
NULL AS PRODUCT_FAMILY_ITEM_ID,
NULL AS SOURCE_SUBINVENTORY,
NULL AS SERIAL_NUMBER_CONTROL_CODE,
NULL AS CREATED_BY,
NULL AS STYLE_ITEM_FLAG,
NULL AS CHARGE_PERIODICITY_CODE,
NULL AS INVOICE_ENABLED_FLAG,
NULL AS CONSIGNED_FLAG,
NULL AS DAYS_MAX_INV_SUPPLY,
NULL AS UNIT_HEIGHT,
NULL AS PROCESS_EXECUTION_ENABLED_FLAG,
NULL AS ROUNDING_FACTOR,
NULL AS OPERATION_SLACK_PENALTY,
NULL AS DEMAND_TIME_FENCE_DAYS,
NULL AS BASE_ITEM_ID,
NULL AS COLLATERAL_FLAG,
NULL AS REQUEST_ID,
NULL AS FULL_LEAD_TIME,
NULL AS SERVICE_ITEM_FLAG,
NULL AS INDIVISIBLE_FLAG,
NULL AS SERV_BILLING_ENABLED_FLAG,
NULL AS DIVERGENCE,
NULL AS SECONDARY_DEFAULT_IND,
NULL AS REVISION_QTY_CONTROL_CODE,
NULL AS QTY_RCV_TOLERANCE,
NULL AS DUAL_UOM_DEVIATION_HIGH,
NULL AS RELEASE_TIME_FENCE_CODE,
NULL AS ACCEPTABLE_RATE_INCREASE,
NULL AS RESTRICT_SUBINVENTORIES_CODE,
NULL AS CONFIG_ORGS,
NULL AS LAST_SUBMITTED_NIR_ID,
NULL AS RESTRICT_LOCATORS_CODE,
NULL AS CHILD_LOT_PREFIX,
NULL AS TRACKING_QUANTITY_IND,
NULL AS PROGRAM_UPDATE_DATE,
NULL AS START_DATE_ACTIVE,
NULL AS LIST_PRICE_PER_UNIT,
NULL AS CREATION_DATE,
NULL AS ENGINEERING_DATE,
NULL AS LAST_UPDATE_DATE,
NULL AS _FIVETRAN_DELETED,
NULL AS _FIVETRAN_ID,
NULL AS _FIVETRAN_SYNCED,
'N' AS PSA_DELETE_IND,
'1900-01-01'::TIMESTAMP AS PSA_LOAD_DTS,
NULL AS PSA_RECORD_SOURCE,
CONVERT_TIMEZONE('UTC','1900-01-01'::TIMESTAMP) AS LOAD_DTS,
'USAZET.SNOWFLAKE.FBIN.DERIVED' AS REC_SRC,
''::BINARY AS HASHDIFF
FROM
TABLE(strtok_split_to_table('0|-1|-2', '|')) AS GR
{% endif %}
