---- SRC LAYER ----
WITH
SRC_SEMTK          as ( SELECT * FROM {{ ref('v_psa_stg_supplier_site__emtk_ebs') }} as SRC 
                         {% if is_incremental() %}
                         WHERE SRC.LOAD_DTS > (SELECT DATEADD('HOUR', '-1', MAX(LOAD_DTS)) FROM {{this}})
                         {% endif %}  )

/*
SRC_SEMTK          as ( SELECT * FROM STAGING.v_psa_stg_supplier_site__emtk_ebs )
*/
---- LOGIC LAYER ----

, LOGIC_SEMTK as (
    SELECT
        SUPPLIER_SITE_HK
      , VENDOR_SITE_ID
      , VENDOR_ID
      , LAST_UPDATE_DATE
      , LAST_UPDATED_BY
      , VENDOR_SITE_CODE
      , VENDOR_SITE_CODE_ALT
      , LAST_UPDATE_LOGIN
      , CREATION_DATE
      , CREATED_BY
      , PURCHASING_SITE_FLAG
      , RFQ_ONLY_SITE_FLAG
      , PAY_SITE_FLAG
      , ATTENTION_AR_FLAG
      , ADDRESS_LINE1
      , ADDRESS_LINES_ALT
      , ADDRESS_LINE2
      , ADDRESS_LINE3
      , CITY
      , STATE
      , ZIP
      , PROVINCE
      , COUNTRY
      , AREA_CODE
      , PHONE
      , CUSTOMER_NUM
      , SHIP_TO_LOCATION_ID
      , BILL_TO_LOCATION_ID
      , SHIP_VIA_LOOKUP_CODE
      , FREIGHT_TERMS_LOOKUP_CODE
      , FOB_LOOKUP_CODE
      , FAX
      , FAX_AREA_CODE
      , TELEX
      , PAYMENT_METHOD_LOOKUP_CODE
      , BANK_ACCOUNT_NAME
      , BANK_ACCOUNT_NUM
      , BANK_NUM
      , BANK_ACCOUNT_TYPE
      , TERMS_DATE_BASIS
      , CURRENT_CATALOG_NUM
      , VAT_CODE
      , DISTRIBUTION_SET_ID
      , ACCTS_PAY_CODE_COMBINATION_ID
      , PREPAY_CODE_COMBINATION_ID
      , PAY_GROUP_LOOKUP_CODE
      , PAYMENT_PRIORITY
      , TERMS_ID
      , INVOICE_AMOUNT_LIMIT
      , PAY_DATE_BASIS_LOOKUP_CODE
      , ALWAYS_TAKE_DISC_FLAG
      , INVOICE_CURRENCY_CODE
      , PAYMENT_CURRENCY_CODE
      , HOLD_ALL_PAYMENTS_FLAG
      , HOLD_FUTURE_PAYMENTS_FLAG
      , HOLD_REASON
      , HOLD_UNMATCHED_INVOICES_FLAG
      , AP_TAX_ROUNDING_RULE
      , AUTO_TAX_CALC_FLAG
      , AUTO_TAX_CALC_OVERRIDE
      , AMOUNT_INCLUDES_TAX_FLAG
      , EXCLUSIVE_PAYMENT_FLAG
      , TAX_REPORTING_SITE_FLAG
      , ATTRIBUTE_CATEGORY
      , ATTRIBUTE1
      , ATTRIBUTE2
      , ATTRIBUTE3
      , ATTRIBUTE4
      , ATTRIBUTE5
      , ATTRIBUTE6
      , ATTRIBUTE7
      , ATTRIBUTE8
      , ATTRIBUTE9
      , ATTRIBUTE10
      , ATTRIBUTE11
      , ATTRIBUTE12
      , ATTRIBUTE13
      , ATTRIBUTE14
      , ATTRIBUTE15
      , REQUEST_ID
      , PROGRAM_APPLICATION_ID
      , PROGRAM_ID
      , PROGRAM_UPDATE_DATE
      , VALIDATION_NUMBER
      , EXCLUDE_FREIGHT_FROM_DISCOUNT
      , OFFSET_VAT_CODE
      , ORG_ID
      , CHECK_DIGITS
      , BANK_NUMBER
      , ADDRESS_LINE4
      , COUNTY
      , ADDRESS_STYLE
      , LANGUAGE
      , ALLOW_AWT_FLAG
      , AWT_GROUP_ID
      , GLOBAL_ATTRIBUTE1
      , GLOBAL_ATTRIBUTE2
      , GLOBAL_ATTRIBUTE3
      , GLOBAL_ATTRIBUTE4
      , GLOBAL_ATTRIBUTE5
      , GLOBAL_ATTRIBUTE6
      , GLOBAL_ATTRIBUTE7
      , GLOBAL_ATTRIBUTE8
      , GLOBAL_ATTRIBUTE9
      , GLOBAL_ATTRIBUTE10
      , GLOBAL_ATTRIBUTE11
      , GLOBAL_ATTRIBUTE12
      , GLOBAL_ATTRIBUTE13
      , GLOBAL_ATTRIBUTE14
      , GLOBAL_ATTRIBUTE15
      , GLOBAL_ATTRIBUTE16
      , GLOBAL_ATTRIBUTE17
      , GLOBAL_ATTRIBUTE18
      , GLOBAL_ATTRIBUTE19
      , GLOBAL_ATTRIBUTE20
      , GLOBAL_ATTRIBUTE_CATEGORY
      , EDI_TRANSACTION_HANDLING
      , EDI_ID_NUMBER
      , EDI_PAYMENT_METHOD
      , EDI_PAYMENT_FORMAT
      , EDI_REMITTANCE_METHOD
      , BANK_CHARGE_BEARER
      , EDI_REMITTANCE_INSTRUCTION
      , BANK_BRANCH_TYPE
      , PAY_ON_CODE
      , DEFAULT_PAY_SITE_ID
      , PAY_ON_RECEIPT_SUMMARY_CODE
      , TP_HEADER_ID
      , ECE_TP_LOCATION_CODE
      , PCARD_SITE_FLAG
      , MATCH_OPTION
      , COUNTRY_OF_ORIGIN_CODE
      , FUTURE_DATED_PAYMENT_CCID
      , CREATE_DEBIT_MEMO_FLAG
      , OFFSET_TAX_FLAG
      , SUPPLIER_NOTIF_METHOD
      , EMAIL_ADDRESS
      , REMITTANCE_EMAIL
      , PRIMARY_PAY_SITE_FLAG
      , SHIPPING_CONTROL
      , SELLING_COMPANY_IDENTIFIER
      , GAPLESS_INV_NUM_FLAG
      , DUNS_NUMBER
      , TOLERANCE_ID
      , LOCATION_ID
      , PARTY_SITE_ID
      , SERVICES_TOLERANCE_ID
      , RETAINAGE_RATE
      , TCA_SYNC_STATE
      , TCA_SYNC_PROVINCE
      , TCA_SYNC_COUNTY
      , TCA_SYNC_CITY
      , TCA_SYNC_ZIP
      , TCA_SYNC_COUNTRY
      , PAY_AWT_GROUP_ID
      , CAGE_CODE
      , LEGAL_BUSINESS_NAME
      , DOING_BUS_AS_NAME
      , DIVISION_NAME
      , SMALL_BUSINESS_CODE
      , CCR_COMMENTS
      , DEBARMENT_START_DATE
      , DEBARMENT_END_DATE
      , ACK_LEAD_TIME
      , VAT_REGISTRATION_NUM_1
      , INACTIVE_DATE
      , _FIVETRAN_ID
      , _FIVETRAN_DELETED
      , _FIVETRAN_SYNCED
      , PSA_RECORD_SOURCE
      , PSA_LOAD_DTS
      , PSA_DELETE_IND
      , LOAD_DTS
      , BKCC
      , REC_SRC
      , HASHDIFF
    FROM SRC_SEMTK
)
---- RENAME LAYER ----

, RENAME_SEMTK as (
    SELECT
        SUPPLIER_SITE_HK
      , VENDOR_SITE_ID
      , VENDOR_ID
      , LAST_UPDATE_DATE
      , LAST_UPDATED_BY
      , VENDOR_SITE_CODE
      , VENDOR_SITE_CODE_ALT
      , LAST_UPDATE_LOGIN
      , CREATION_DATE
      , CREATED_BY
      , PURCHASING_SITE_FLAG
      , RFQ_ONLY_SITE_FLAG
      , PAY_SITE_FLAG
      , ATTENTION_AR_FLAG
      , ADDRESS_LINE1
      , ADDRESS_LINES_ALT
      , ADDRESS_LINE2
      , ADDRESS_LINE3
      , CITY
      , STATE
      , ZIP
      , PROVINCE
      , COUNTRY
      , AREA_CODE
      , PHONE
      , CUSTOMER_NUM
      , SHIP_TO_LOCATION_ID
      , BILL_TO_LOCATION_ID
      , SHIP_VIA_LOOKUP_CODE
      , FREIGHT_TERMS_LOOKUP_CODE
      , FOB_LOOKUP_CODE
      , FAX
      , FAX_AREA_CODE
      , TELEX
      , PAYMENT_METHOD_LOOKUP_CODE
      , BANK_ACCOUNT_NAME
      , BANK_ACCOUNT_NUM
      , BANK_NUM
      , BANK_ACCOUNT_TYPE
      , TERMS_DATE_BASIS
      , CURRENT_CATALOG_NUM
      , VAT_CODE
      , DISTRIBUTION_SET_ID
      , ACCTS_PAY_CODE_COMBINATION_ID
      , PREPAY_CODE_COMBINATION_ID
      , PAY_GROUP_LOOKUP_CODE
      , PAYMENT_PRIORITY
      , TERMS_ID
      , INVOICE_AMOUNT_LIMIT
      , PAY_DATE_BASIS_LOOKUP_CODE
      , ALWAYS_TAKE_DISC_FLAG
      , INVOICE_CURRENCY_CODE
      , PAYMENT_CURRENCY_CODE
      , HOLD_ALL_PAYMENTS_FLAG
      , HOLD_FUTURE_PAYMENTS_FLAG
      , HOLD_REASON
      , HOLD_UNMATCHED_INVOICES_FLAG
      , AP_TAX_ROUNDING_RULE
      , AUTO_TAX_CALC_FLAG
      , AUTO_TAX_CALC_OVERRIDE
      , AMOUNT_INCLUDES_TAX_FLAG
      , EXCLUSIVE_PAYMENT_FLAG
      , TAX_REPORTING_SITE_FLAG
      , ATTRIBUTE_CATEGORY
      , ATTRIBUTE1
      , ATTRIBUTE2
      , ATTRIBUTE3
      , ATTRIBUTE4
      , ATTRIBUTE5
      , ATTRIBUTE6
      , ATTRIBUTE7
      , ATTRIBUTE8
      , ATTRIBUTE9
      , ATTRIBUTE10
      , ATTRIBUTE11
      , ATTRIBUTE12
      , ATTRIBUTE13
      , ATTRIBUTE14
      , ATTRIBUTE15
      , REQUEST_ID
      , PROGRAM_APPLICATION_ID
      , PROGRAM_ID
      , PROGRAM_UPDATE_DATE
      , VALIDATION_NUMBER
      , EXCLUDE_FREIGHT_FROM_DISCOUNT
      , OFFSET_VAT_CODE
      , ORG_ID
      , CHECK_DIGITS
      , BANK_NUMBER
      , ADDRESS_LINE4
      , COUNTY
      , ADDRESS_STYLE
      , LANGUAGE
      , ALLOW_AWT_FLAG
      , AWT_GROUP_ID
      , GLOBAL_ATTRIBUTE1
      , GLOBAL_ATTRIBUTE2
      , GLOBAL_ATTRIBUTE3
      , GLOBAL_ATTRIBUTE4
      , GLOBAL_ATTRIBUTE5
      , GLOBAL_ATTRIBUTE6
      , GLOBAL_ATTRIBUTE7
      , GLOBAL_ATTRIBUTE8
      , GLOBAL_ATTRIBUTE9
      , GLOBAL_ATTRIBUTE10
      , GLOBAL_ATTRIBUTE11
      , GLOBAL_ATTRIBUTE12
      , GLOBAL_ATTRIBUTE13
      , GLOBAL_ATTRIBUTE14
      , GLOBAL_ATTRIBUTE15
      , GLOBAL_ATTRIBUTE16
      , GLOBAL_ATTRIBUTE17
      , GLOBAL_ATTRIBUTE18
      , GLOBAL_ATTRIBUTE19
      , GLOBAL_ATTRIBUTE20
      , GLOBAL_ATTRIBUTE_CATEGORY
      , EDI_TRANSACTION_HANDLING
      , EDI_ID_NUMBER
      , EDI_PAYMENT_METHOD
      , EDI_PAYMENT_FORMAT
      , EDI_REMITTANCE_METHOD
      , BANK_CHARGE_BEARER
      , EDI_REMITTANCE_INSTRUCTION
      , BANK_BRANCH_TYPE
      , PAY_ON_CODE
      , DEFAULT_PAY_SITE_ID
      , PAY_ON_RECEIPT_SUMMARY_CODE
      , TP_HEADER_ID
      , ECE_TP_LOCATION_CODE
      , PCARD_SITE_FLAG
      , MATCH_OPTION
      , COUNTRY_OF_ORIGIN_CODE
      , FUTURE_DATED_PAYMENT_CCID
      , CREATE_DEBIT_MEMO_FLAG
      , OFFSET_TAX_FLAG
      , SUPPLIER_NOTIF_METHOD
      , EMAIL_ADDRESS
      , REMITTANCE_EMAIL
      , PRIMARY_PAY_SITE_FLAG
      , SHIPPING_CONTROL
      , SELLING_COMPANY_IDENTIFIER
      , GAPLESS_INV_NUM_FLAG
      , DUNS_NUMBER
      , TOLERANCE_ID
      , LOCATION_ID
      , PARTY_SITE_ID
      , SERVICES_TOLERANCE_ID
      , RETAINAGE_RATE
      , TCA_SYNC_STATE
      , TCA_SYNC_PROVINCE
      , TCA_SYNC_COUNTY
      , TCA_SYNC_CITY
      , TCA_SYNC_ZIP
      , TCA_SYNC_COUNTRY
      , PAY_AWT_GROUP_ID
      , CAGE_CODE
      , LEGAL_BUSINESS_NAME
      , DOING_BUS_AS_NAME
      , DIVISION_NAME
      , SMALL_BUSINESS_CODE
      , CCR_COMMENTS
      , DEBARMENT_START_DATE
      , DEBARMENT_END_DATE
      , ACK_LEAD_TIME
      , VAT_REGISTRATION_NUM_1
      , INACTIVE_DATE
      , _FIVETRAN_ID
      , _FIVETRAN_DELETED
      , _FIVETRAN_SYNCED
      , PSA_RECORD_SOURCE
      , PSA_LOAD_DTS
      , PSA_DELETE_IND
      , LOAD_DTS
      , BKCC
      , REC_SRC
      , HASHDIFF
    FROM LOGIC_SEMTK
)
---- FILTER LAYER ----

, FILTER_SEMTK as (
    SELECT *
    FROM RENAME_SEMTK
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM FILTER_SEMTK
)

---- FINAL LAYER ----
SELECT
          SUPPLIER_SITE_HK
        , VENDOR_SITE_ID
        , VENDOR_ID
        , LAST_UPDATE_DATE
        , LAST_UPDATED_BY
        , VENDOR_SITE_CODE
        , VENDOR_SITE_CODE_ALT
        , LAST_UPDATE_LOGIN
        , CREATION_DATE
        , CREATED_BY
        , PURCHASING_SITE_FLAG
        , RFQ_ONLY_SITE_FLAG
        , PAY_SITE_FLAG
        , ATTENTION_AR_FLAG
        , ADDRESS_LINE1
        , ADDRESS_LINES_ALT
        , ADDRESS_LINE2
        , ADDRESS_LINE3
        , CITY
        , STATE
        , ZIP
        , PROVINCE
        , COUNTRY
        , AREA_CODE
        , PHONE
        , CUSTOMER_NUM
        , SHIP_TO_LOCATION_ID
        , BILL_TO_LOCATION_ID
        , SHIP_VIA_LOOKUP_CODE
        , FREIGHT_TERMS_LOOKUP_CODE
        , FOB_LOOKUP_CODE
        , FAX
        , FAX_AREA_CODE
        , TELEX
        , PAYMENT_METHOD_LOOKUP_CODE
        , BANK_ACCOUNT_NAME
        , BANK_ACCOUNT_NUM
        , BANK_NUM
        , BANK_ACCOUNT_TYPE
        , TERMS_DATE_BASIS
        , CURRENT_CATALOG_NUM
        , VAT_CODE
        , DISTRIBUTION_SET_ID
        , ACCTS_PAY_CODE_COMBINATION_ID
        , PREPAY_CODE_COMBINATION_ID
        , PAY_GROUP_LOOKUP_CODE
        , PAYMENT_PRIORITY
        , TERMS_ID
        , INVOICE_AMOUNT_LIMIT
        , PAY_DATE_BASIS_LOOKUP_CODE
        , ALWAYS_TAKE_DISC_FLAG
        , INVOICE_CURRENCY_CODE
        , PAYMENT_CURRENCY_CODE
        , HOLD_ALL_PAYMENTS_FLAG
        , HOLD_FUTURE_PAYMENTS_FLAG
        , HOLD_REASON
        , HOLD_UNMATCHED_INVOICES_FLAG
        , AP_TAX_ROUNDING_RULE
        , AUTO_TAX_CALC_FLAG
        , AUTO_TAX_CALC_OVERRIDE
        , AMOUNT_INCLUDES_TAX_FLAG
        , EXCLUSIVE_PAYMENT_FLAG
        , TAX_REPORTING_SITE_FLAG
        , ATTRIBUTE_CATEGORY
        , ATTRIBUTE1
        , ATTRIBUTE2
        , ATTRIBUTE3
        , ATTRIBUTE4
        , ATTRIBUTE5
        , ATTRIBUTE6
        , ATTRIBUTE7
        , ATTRIBUTE8
        , ATTRIBUTE9
        , ATTRIBUTE10
        , ATTRIBUTE11
        , ATTRIBUTE12
        , ATTRIBUTE13
        , ATTRIBUTE14
        , ATTRIBUTE15
        , REQUEST_ID
        , PROGRAM_APPLICATION_ID
        , PROGRAM_ID
        , PROGRAM_UPDATE_DATE
        , VALIDATION_NUMBER
        , EXCLUDE_FREIGHT_FROM_DISCOUNT
        , OFFSET_VAT_CODE
        , ORG_ID
        , CHECK_DIGITS
        , BANK_NUMBER
        , ADDRESS_LINE4
        , COUNTY
        , ADDRESS_STYLE
        , LANGUAGE
        , ALLOW_AWT_FLAG
        , AWT_GROUP_ID
        , GLOBAL_ATTRIBUTE1
        , GLOBAL_ATTRIBUTE2
        , GLOBAL_ATTRIBUTE3
        , GLOBAL_ATTRIBUTE4
        , GLOBAL_ATTRIBUTE5
        , GLOBAL_ATTRIBUTE6
        , GLOBAL_ATTRIBUTE7
        , GLOBAL_ATTRIBUTE8
        , GLOBAL_ATTRIBUTE9
        , GLOBAL_ATTRIBUTE10
        , GLOBAL_ATTRIBUTE11
        , GLOBAL_ATTRIBUTE12
        , GLOBAL_ATTRIBUTE13
        , GLOBAL_ATTRIBUTE14
        , GLOBAL_ATTRIBUTE15
        , GLOBAL_ATTRIBUTE16
        , GLOBAL_ATTRIBUTE17
        , GLOBAL_ATTRIBUTE18
        , GLOBAL_ATTRIBUTE19
        , GLOBAL_ATTRIBUTE20
        , GLOBAL_ATTRIBUTE_CATEGORY
        , EDI_TRANSACTION_HANDLING
        , EDI_ID_NUMBER
        , EDI_PAYMENT_METHOD
        , EDI_PAYMENT_FORMAT
        , EDI_REMITTANCE_METHOD
        , BANK_CHARGE_BEARER
        , EDI_REMITTANCE_INSTRUCTION
        , BANK_BRANCH_TYPE
        , PAY_ON_CODE
        , DEFAULT_PAY_SITE_ID
        , PAY_ON_RECEIPT_SUMMARY_CODE
        , TP_HEADER_ID
        , ECE_TP_LOCATION_CODE
        , PCARD_SITE_FLAG
        , MATCH_OPTION
        , COUNTRY_OF_ORIGIN_CODE
        , FUTURE_DATED_PAYMENT_CCID
        , CREATE_DEBIT_MEMO_FLAG
        , OFFSET_TAX_FLAG
        , SUPPLIER_NOTIF_METHOD
        , EMAIL_ADDRESS
        , REMITTANCE_EMAIL
        , PRIMARY_PAY_SITE_FLAG
        , SHIPPING_CONTROL
        , SELLING_COMPANY_IDENTIFIER
        , GAPLESS_INV_NUM_FLAG
        , DUNS_NUMBER
        , TOLERANCE_ID
        , LOCATION_ID
        , PARTY_SITE_ID
        , SERVICES_TOLERANCE_ID
        , RETAINAGE_RATE
        , TCA_SYNC_STATE
        , TCA_SYNC_PROVINCE
        , TCA_SYNC_COUNTY
        , TCA_SYNC_CITY
        , TCA_SYNC_ZIP
        , TCA_SYNC_COUNTRY
        , PAY_AWT_GROUP_ID
        , CAGE_CODE
        , LEGAL_BUSINESS_NAME
        , DOING_BUS_AS_NAME
        , DIVISION_NAME
        , SMALL_BUSINESS_CODE
        , CCR_COMMENTS
        , DEBARMENT_START_DATE
        , DEBARMENT_END_DATE
        , ACK_LEAD_TIME
        , VAT_REGISTRATION_NUM_1
        , INACTIVE_DATE
        , _FIVETRAN_ID
        , _FIVETRAN_DELETED
        , _FIVETRAN_SYNCED
        , PSA_RECORD_SOURCE
        , PSA_LOAD_DTS
        , PSA_DELETE_IND
        , LOAD_DTS
        , BKCC
        , REC_SRC
        , HASHDIFF
FROM JOIN_RESULT
{% if is_incremental() %}
WHERE NOT EXISTS (
    SELECT 1 
    FROM {{ this }} existing
    WHERE existing.SUPPLIER_SITE_HK = JOIN_RESULT.SUPPLIER_SITE_HK 
    AND existing.HASHDIFF = JOIN_RESULT.HASHDIFF
)
{% endif %}
{% if not is_incremental() %}

/* The following qualifier is implemented to prevent multiple loads of touched records during the initial build, such as multiple rows per HK and hashdiff. */
qualify 1 = row_number() over (partition by SUPPLIER_SITE_HK, HASHDIFF order by PSA_LOAD_DTS)

union all
SELECT 
MD5_BINARY(GR.VALUE) AS SUPPLIER_SITE_HK,
GR.VALUE::number AS VENDOR_SITE_ID,
GR.VALUE::number AS VENDOR_ID,
NULL AS LAST_UPDATE_DATE,
NULL AS LAST_UPDATED_BY,
NULL AS VENDOR_SITE_CODE,
NULL AS VENDOR_SITE_CODE_ALT,
NULL AS LAST_UPDATE_LOGIN,
NULL AS CREATION_DATE,
NULL AS CREATED_BY,
NULL AS PURCHASING_SITE_FLAG,
NULL AS RFQ_ONLY_SITE_FLAG,
NULL AS PAY_SITE_FLAG,
NULL AS ATTENTION_AR_FLAG,
NULL AS ADDRESS_LINE1,
NULL AS ADDRESS_LINES_ALT,
NULL AS ADDRESS_LINE2,
NULL AS ADDRESS_LINE3,
NULL AS CITY,
NULL AS STATE,
NULL AS ZIP,
NULL AS PROVINCE,
NULL AS COUNTRY,
NULL AS AREA_CODE,
NULL AS PHONE,
NULL AS CUSTOMER_NUM,
NULL AS SHIP_TO_LOCATION_ID,
NULL AS BILL_TO_LOCATION_ID,
NULL AS SHIP_VIA_LOOKUP_CODE,
NULL AS FREIGHT_TERMS_LOOKUP_CODE,
NULL AS FOB_LOOKUP_CODE,
NULL AS FAX,
NULL AS FAX_AREA_CODE,
NULL AS TELEX,
NULL AS PAYMENT_METHOD_LOOKUP_CODE,
NULL AS BANK_ACCOUNT_NAME,
NULL AS BANK_ACCOUNT_NUM,
NULL AS BANK_NUM,
NULL AS BANK_ACCOUNT_TYPE,
NULL AS TERMS_DATE_BASIS,
NULL AS CURRENT_CATALOG_NUM,
NULL AS VAT_CODE,
NULL AS DISTRIBUTION_SET_ID,
NULL AS ACCTS_PAY_CODE_COMBINATION_ID,
NULL AS PREPAY_CODE_COMBINATION_ID,
NULL AS PAY_GROUP_LOOKUP_CODE,
NULL AS PAYMENT_PRIORITY,
NULL AS TERMS_ID,
NULL AS INVOICE_AMOUNT_LIMIT,
NULL AS PAY_DATE_BASIS_LOOKUP_CODE,
NULL AS ALWAYS_TAKE_DISC_FLAG,
NULL AS INVOICE_CURRENCY_CODE,
NULL AS PAYMENT_CURRENCY_CODE,
NULL AS HOLD_ALL_PAYMENTS_FLAG,
NULL AS HOLD_FUTURE_PAYMENTS_FLAG,
NULL AS HOLD_REASON,
NULL AS HOLD_UNMATCHED_INVOICES_FLAG,
NULL AS AP_TAX_ROUNDING_RULE,
NULL AS AUTO_TAX_CALC_FLAG,
NULL AS AUTO_TAX_CALC_OVERRIDE,
NULL AS AMOUNT_INCLUDES_TAX_FLAG,
NULL AS EXCLUSIVE_PAYMENT_FLAG,
NULL AS TAX_REPORTING_SITE_FLAG,
NULL AS ATTRIBUTE_CATEGORY,
NULL AS ATTRIBUTE1,
NULL AS ATTRIBUTE2,
NULL AS ATTRIBUTE3,
NULL AS ATTRIBUTE4,
NULL AS ATTRIBUTE5,
NULL AS ATTRIBUTE6,
NULL AS ATTRIBUTE7,
NULL AS ATTRIBUTE8,
NULL AS ATTRIBUTE9,
NULL AS ATTRIBUTE10,
NULL AS ATTRIBUTE11,
NULL AS ATTRIBUTE12,
NULL AS ATTRIBUTE13,
NULL AS ATTRIBUTE14,
NULL AS ATTRIBUTE15,
NULL AS REQUEST_ID,
NULL AS PROGRAM_APPLICATION_ID,
NULL AS PROGRAM_ID,
NULL AS PROGRAM_UPDATE_DATE,
NULL AS VALIDATION_NUMBER,
NULL AS EXCLUDE_FREIGHT_FROM_DISCOUNT,
NULL AS OFFSET_VAT_CODE,
NULL AS ORG_ID,
NULL AS CHECK_DIGITS,
NULL AS BANK_NUMBER,
NULL AS ADDRESS_LINE4,
NULL AS COUNTY,
NULL AS ADDRESS_STYLE,
NULL AS LANGUAGE,
NULL AS ALLOW_AWT_FLAG,
NULL AS AWT_GROUP_ID,
NULL AS GLOBAL_ATTRIBUTE1,
NULL AS GLOBAL_ATTRIBUTE2,
NULL AS GLOBAL_ATTRIBUTE3,
NULL AS GLOBAL_ATTRIBUTE4,
NULL AS GLOBAL_ATTRIBUTE5,
NULL AS GLOBAL_ATTRIBUTE6,
NULL AS GLOBAL_ATTRIBUTE7,
NULL AS GLOBAL_ATTRIBUTE8,
NULL AS GLOBAL_ATTRIBUTE9,
NULL AS GLOBAL_ATTRIBUTE10,
NULL AS GLOBAL_ATTRIBUTE11,
NULL AS GLOBAL_ATTRIBUTE12,
NULL AS GLOBAL_ATTRIBUTE13,
NULL AS GLOBAL_ATTRIBUTE14,
NULL AS GLOBAL_ATTRIBUTE15,
NULL AS GLOBAL_ATTRIBUTE16,
NULL AS GLOBAL_ATTRIBUTE17,
NULL AS GLOBAL_ATTRIBUTE18,
NULL AS GLOBAL_ATTRIBUTE19,
NULL AS GLOBAL_ATTRIBUTE20,
NULL AS GLOBAL_ATTRIBUTE_CATEGORY,
NULL AS EDI_TRANSACTION_HANDLING,
NULL AS EDI_ID_NUMBER,
NULL AS EDI_PAYMENT_METHOD,
NULL AS EDI_PAYMENT_FORMAT,
NULL AS EDI_REMITTANCE_METHOD,
NULL AS BANK_CHARGE_BEARER,
NULL AS EDI_REMITTANCE_INSTRUCTION,
NULL AS BANK_BRANCH_TYPE,
NULL AS PAY_ON_CODE,
NULL AS DEFAULT_PAY_SITE_ID,
NULL AS PAY_ON_RECEIPT_SUMMARY_CODE,
NULL AS TP_HEADER_ID,
NULL AS ECE_TP_LOCATION_CODE,
NULL AS PCARD_SITE_FLAG,
NULL AS MATCH_OPTION,
NULL AS COUNTRY_OF_ORIGIN_CODE,
NULL AS FUTURE_DATED_PAYMENT_CCID,
NULL AS CREATE_DEBIT_MEMO_FLAG,
NULL AS OFFSET_TAX_FLAG,
NULL AS SUPPLIER_NOTIF_METHOD,
NULL AS EMAIL_ADDRESS,
NULL AS REMITTANCE_EMAIL,
NULL AS PRIMARY_PAY_SITE_FLAG,
NULL AS SHIPPING_CONTROL,
NULL AS SELLING_COMPANY_IDENTIFIER,
NULL AS GAPLESS_INV_NUM_FLAG,
NULL AS DUNS_NUMBER,
NULL AS TOLERANCE_ID,
NULL AS LOCATION_ID,
NULL AS PARTY_SITE_ID,
NULL AS SERVICES_TOLERANCE_ID,
NULL AS RETAINAGE_RATE,
NULL AS TCA_SYNC_STATE,
NULL AS TCA_SYNC_PROVINCE,
NULL AS TCA_SYNC_COUNTY,
NULL AS TCA_SYNC_CITY,
NULL AS TCA_SYNC_ZIP,
NULL AS TCA_SYNC_COUNTRY,
NULL AS PAY_AWT_GROUP_ID,
NULL AS CAGE_CODE,
NULL AS LEGAL_BUSINESS_NAME,
NULL AS DOING_BUS_AS_NAME,
NULL AS DIVISION_NAME,
NULL AS SMALL_BUSINESS_CODE,
NULL AS CCR_COMMENTS,
NULL AS DEBARMENT_START_DATE,
NULL AS DEBARMENT_END_DATE,
NULL AS ACK_LEAD_TIME,
NULL AS VAT_REGISTRATION_NUM_1,
NULL AS INACTIVE_DATE,
NULL AS _FIVETRAN_ID,
NULL AS _FIVETRAN_DELETED,
NULL AS _FIVETRAN_SYNCED,
NULL AS PSA_RECORD_SOURCE,
'1900-01-01'::TIMESTAMP AS PSA_LOAD_DTS,
'N' AS PSA_DELETE_IND,
CONVERT_TIMEZONE('UTC','1900-01-01'::TIMESTAMP) AS LOAD_DTS,
DECODE(GR.VALUE, 0, 'GHOST RECORD-SYSTEM', -1, 'GHOST RECORD-nullkey-required', -2, 'GHOST RECORD-nullkey-optional') AS BKCC,
'USAZET.SNOWFLAKE.FBIN.DERIVED' AS REC_SRC,
''::BINARY AS HASHDIFF
FROM
TABLE(strtok_split_to_table('0|-1|-2', '|')) AS GR
{% endif %}
