---- SRC LAYER ----
WITH
SRC_SIM            as ( SELECT * FROM {{ ref('v_psa_stg_sales_inventory__masterlock_lowes') }} as SRC 
                         {% if is_incremental() %}
                         WHERE SRC.LOAD_DTS > (SELECT DATEADD('HOUR', '-1', MAX(LOAD_DTS)) FROM {{this}})
                         {% endif %}  )

/*
SRC_SIM            as ( SELECT * FROM STAGING.v_psa_stg_sales_inventory__masterlock_lowes )
*/
---- LOGIC LAYER ----

, LOGIC_SIM as (
    SELECT
        STORE_HK
      , LOCATION_ID
      , ITEM_ID
      , END_DATE
      , LOAD_DTS
      , ITEM_NAME
      , LOCATION_NAME
      , TY_AVAILABLE_INVENTORY_UNITS
      , LY_AVAILABLE_INVENTORY_UNITS
      , TY_VS_LY_AVAILABLE_INVENTORY_UNITS
      , TY_AVAILABLE_INVENTORY_SALES
      , LY_AVAILABLE_INVENTORY_SALES
      , TY_VS_LY_AVAILABLE_INVENTORY_SALES
      , AVAILABLE_DC_INVENTORY_UNITS
      , AVAILABLE_RETAIL_INVENTORY_UNITS
      , TY_INVENTORY_ON_DIRECT_ORDER_UNITS
      , LY_INVENTORY_ON_DIRECT_ORDER_UNITS
      , TY_VS_LY_INVENTORY_ON_DIRECT_ORDER_UNITS
      , TY_INVENTORY_ON_DIRECT_ORDER_SALES
      , LY_INVENTORY_ON_DIRECT_ORDER_SALES
      , TY_VS_LY_INVENTORY_ON_DIRECT_ORDER_SALES
      , TY_INVENTORY_UNITS_IN_REQ
      , LY_INVENTORY_UNITS_IN_REQ
      , TY_VS_LY_INVENTORY_UNITS_IN_REQ
      , TY_INVENTORY_UNITS_ON_BILL
      , LY_INVENTORY_UNITS_ON_BILL
      , TY_VS_LY_INVENTORY_UNITS_ON_BILL
      , TY_SALES_UNITS
      , LY_SALES_UNITS
      , TY_VS_LY_SALES_UNITS
      , TY_SALES
      , LY_SALES
      , TY_VS_LY_SALES
      , GROSS_SALES
      , TY_FULFILLED_INTERNET_UNITS
      , LY_FULFILLED_INTERNET_UNITS
      , TY_VS_LY_FULFILLED_INTERNET_UNITS
      , TY_FULFILLED_INTERNET_SALES
      , LY_FULFILLED_INTERNET_SALES
      , TY_VS_LY_FULFILLED_INTERNET_SALES
      , TY_AVG_INVENTORY_ON_HAND_UNITS
      , LY_AVG_INVENTORY_ON_HAND_UNITS
      , TY_VS_LY_AVG_INVENTORY_ON_HAND_UNITS
      , TY_AVG_INVENTORY_ON_HAND_SALES
      , LY_AVG_INVENTORY_ON_HAND_SALES
      , TY_VS_LY_AVG_INVENTORY_ON_HAND_SALES
      , TY_AVERAGE_INVENTORY_ON_DIRECT_ORDER_UNITS
      , LY_AVERAGE_INVENTORY_ON_DIRECT_ORDER_UNITS
      , TY_VS_LY_AVERAGE_INVENTORY_ON_DIRECT_ORDER_UNITS
      , TY_AVERAGE_INVENTORY_ON_DIRECT_ORDER_SALES
      , LY_AVERAGE_INVENTORY_ON_DIRECT_ORDER_SALES
      , TY_VS_LY_AVERAGE_INVENTORY_ON_DIRECT_ORDER_SALES
      , TY_AVERAGE_INVENTORY_ON_REQUISITION_UNITS
      , LY_AVERAGE_INVENTORY_ON_REQUISITION_UNITS
      , TY_VS_LY_AVERAGE_INVENTORY_ON_REQUISITION_UNITS
      , TY_AVERAGE_INVENTORY_ON_REQUISITION_SALES
      , LY_AVERAGE_INVENTORY_ON_REQUISITION_SALES
      , TY_VS_LY_AVERAGE_INVENTORY_ON_REQUISITION_SALES
      , IN_STOCK_PERCENTAGE
      , AVERAGE_YEAR_TO_DATE_SALES
      , TY_YEAR_TO_DATE_SALES_UNITS
      , LY_YEAR_TO_DATE_SALES_UNITS
      , TY_VS_LY_YEAR_TO_DATE_SALES_UNITS
      , WEEKS_OF_SUPPLY_ON_HAND
      , WEEKS_OF_SUPPLY_ON_ORDER
      , TY_JDA_LOST_SALES
      , TY_JDA_SERVICE_LEVEL
      , LY_TURN_RATE
      , TY_TURN_RATE
      , START_DATE
      , PSA_LOAD_DTS
      , PSA_RECORD_SOURCE
      , REC_SRC
      , BKCC
      , HASHDIFF
    FROM SRC_SIM
)
---- RENAME LAYER ----

, RENAME_SIM as (
    SELECT
        STORE_HK
      , LOCATION_ID
      , ITEM_ID
      , END_DATE
      , LOAD_DTS
      , ITEM_NAME
      , LOCATION_NAME
      , TY_AVAILABLE_INVENTORY_UNITS
      , LY_AVAILABLE_INVENTORY_UNITS
      , TY_VS_LY_AVAILABLE_INVENTORY_UNITS
      , TY_AVAILABLE_INVENTORY_SALES
      , LY_AVAILABLE_INVENTORY_SALES
      , TY_VS_LY_AVAILABLE_INVENTORY_SALES
      , AVAILABLE_DC_INVENTORY_UNITS
      , AVAILABLE_RETAIL_INVENTORY_UNITS
      , TY_INVENTORY_ON_DIRECT_ORDER_UNITS
      , LY_INVENTORY_ON_DIRECT_ORDER_UNITS
      , TY_VS_LY_INVENTORY_ON_DIRECT_ORDER_UNITS
      , TY_INVENTORY_ON_DIRECT_ORDER_SALES
      , LY_INVENTORY_ON_DIRECT_ORDER_SALES
      , TY_VS_LY_INVENTORY_ON_DIRECT_ORDER_SALES
      , TY_INVENTORY_UNITS_IN_REQ
      , LY_INVENTORY_UNITS_IN_REQ
      , TY_VS_LY_INVENTORY_UNITS_IN_REQ
      , TY_INVENTORY_UNITS_ON_BILL
      , LY_INVENTORY_UNITS_ON_BILL
      , TY_VS_LY_INVENTORY_UNITS_ON_BILL
      , TY_SALES_UNITS
      , LY_SALES_UNITS
      , TY_VS_LY_SALES_UNITS
      , TY_SALES
      , LY_SALES
      , TY_VS_LY_SALES
      , GROSS_SALES
      , TY_FULFILLED_INTERNET_UNITS
      , LY_FULFILLED_INTERNET_UNITS
      , TY_VS_LY_FULFILLED_INTERNET_UNITS
      , TY_FULFILLED_INTERNET_SALES
      , LY_FULFILLED_INTERNET_SALES
      , TY_VS_LY_FULFILLED_INTERNET_SALES
      , TY_AVG_INVENTORY_ON_HAND_UNITS
      , LY_AVG_INVENTORY_ON_HAND_UNITS
      , TY_VS_LY_AVG_INVENTORY_ON_HAND_UNITS
      , TY_AVG_INVENTORY_ON_HAND_SALES
      , LY_AVG_INVENTORY_ON_HAND_SALES
      , TY_VS_LY_AVG_INVENTORY_ON_HAND_SALES
      , TY_AVERAGE_INVENTORY_ON_DIRECT_ORDER_UNITS
      , LY_AVERAGE_INVENTORY_ON_DIRECT_ORDER_UNITS
      , TY_VS_LY_AVERAGE_INVENTORY_ON_DIRECT_ORDER_UNITS
      , TY_AVERAGE_INVENTORY_ON_DIRECT_ORDER_SALES
      , LY_AVERAGE_INVENTORY_ON_DIRECT_ORDER_SALES
      , TY_VS_LY_AVERAGE_INVENTORY_ON_DIRECT_ORDER_SALES
      , TY_AVERAGE_INVENTORY_ON_REQUISITION_UNITS
      , LY_AVERAGE_INVENTORY_ON_REQUISITION_UNITS
      , TY_VS_LY_AVERAGE_INVENTORY_ON_REQUISITION_UNITS
      , TY_AVERAGE_INVENTORY_ON_REQUISITION_SALES
      , LY_AVERAGE_INVENTORY_ON_REQUISITION_SALES
      , TY_VS_LY_AVERAGE_INVENTORY_ON_REQUISITION_SALES
      , IN_STOCK_PERCENTAGE
      , AVERAGE_YEAR_TO_DATE_SALES
      , TY_YEAR_TO_DATE_SALES_UNITS
      , LY_YEAR_TO_DATE_SALES_UNITS
      , TY_VS_LY_YEAR_TO_DATE_SALES_UNITS
      , WEEKS_OF_SUPPLY_ON_HAND
      , WEEKS_OF_SUPPLY_ON_ORDER
      , TY_JDA_LOST_SALES
      , TY_JDA_SERVICE_LEVEL
      , LY_TURN_RATE
      , TY_TURN_RATE
      , START_DATE
      , PSA_LOAD_DTS
      , PSA_RECORD_SOURCE
      , REC_SRC
      , BKCC
      , HASHDIFF
    FROM LOGIC_SIM
)
---- FILTER LAYER ----

, FILTER_SIM as (
    SELECT *
    FROM RENAME_SIM
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM FILTER_SIM
)

---- FINAL LAYER ----
SELECT
          STORE_HK
        , LOCATION_ID
        , ITEM_ID
        , END_DATE
        , LOAD_DTS
        , ITEM_NAME
        , LOCATION_NAME
        , TY_AVAILABLE_INVENTORY_UNITS
        , LY_AVAILABLE_INVENTORY_UNITS
        , TY_VS_LY_AVAILABLE_INVENTORY_UNITS
        , TY_AVAILABLE_INVENTORY_SALES
        , LY_AVAILABLE_INVENTORY_SALES
        , TY_VS_LY_AVAILABLE_INVENTORY_SALES
        , AVAILABLE_DC_INVENTORY_UNITS
        , AVAILABLE_RETAIL_INVENTORY_UNITS
        , TY_INVENTORY_ON_DIRECT_ORDER_UNITS
        , LY_INVENTORY_ON_DIRECT_ORDER_UNITS
        , TY_VS_LY_INVENTORY_ON_DIRECT_ORDER_UNITS
        , TY_INVENTORY_ON_DIRECT_ORDER_SALES
        , LY_INVENTORY_ON_DIRECT_ORDER_SALES
        , TY_VS_LY_INVENTORY_ON_DIRECT_ORDER_SALES
        , TY_INVENTORY_UNITS_IN_REQ
        , LY_INVENTORY_UNITS_IN_REQ
        , TY_VS_LY_INVENTORY_UNITS_IN_REQ
        , TY_INVENTORY_UNITS_ON_BILL
        , LY_INVENTORY_UNITS_ON_BILL
        , TY_VS_LY_INVENTORY_UNITS_ON_BILL
        , TY_SALES_UNITS
        , LY_SALES_UNITS
        , TY_VS_LY_SALES_UNITS
        , TY_SALES
        , LY_SALES
        , TY_VS_LY_SALES
        , GROSS_SALES
        , TY_FULFILLED_INTERNET_UNITS
        , LY_FULFILLED_INTERNET_UNITS
        , TY_VS_LY_FULFILLED_INTERNET_UNITS
        , TY_FULFILLED_INTERNET_SALES
        , LY_FULFILLED_INTERNET_SALES
        , TY_VS_LY_FULFILLED_INTERNET_SALES
        , TY_AVG_INVENTORY_ON_HAND_UNITS
        , LY_AVG_INVENTORY_ON_HAND_UNITS
        , TY_VS_LY_AVG_INVENTORY_ON_HAND_UNITS
        , TY_AVG_INVENTORY_ON_HAND_SALES
        , LY_AVG_INVENTORY_ON_HAND_SALES
        , TY_VS_LY_AVG_INVENTORY_ON_HAND_SALES
        , TY_AVERAGE_INVENTORY_ON_DIRECT_ORDER_UNITS
        , LY_AVERAGE_INVENTORY_ON_DIRECT_ORDER_UNITS
        , TY_VS_LY_AVERAGE_INVENTORY_ON_DIRECT_ORDER_UNITS
        , TY_AVERAGE_INVENTORY_ON_DIRECT_ORDER_SALES
        , LY_AVERAGE_INVENTORY_ON_DIRECT_ORDER_SALES
        , TY_VS_LY_AVERAGE_INVENTORY_ON_DIRECT_ORDER_SALES
        , TY_AVERAGE_INVENTORY_ON_REQUISITION_UNITS
        , LY_AVERAGE_INVENTORY_ON_REQUISITION_UNITS
        , TY_VS_LY_AVERAGE_INVENTORY_ON_REQUISITION_UNITS
        , TY_AVERAGE_INVENTORY_ON_REQUISITION_SALES
        , LY_AVERAGE_INVENTORY_ON_REQUISITION_SALES
        , TY_VS_LY_AVERAGE_INVENTORY_ON_REQUISITION_SALES
        , IN_STOCK_PERCENTAGE
        , AVERAGE_YEAR_TO_DATE_SALES
        , TY_YEAR_TO_DATE_SALES_UNITS
        , LY_YEAR_TO_DATE_SALES_UNITS
        , TY_VS_LY_YEAR_TO_DATE_SALES_UNITS
        , WEEKS_OF_SUPPLY_ON_HAND
        , WEEKS_OF_SUPPLY_ON_ORDER
        , TY_JDA_LOST_SALES
        , TY_JDA_SERVICE_LEVEL
        , LY_TURN_RATE
        , TY_TURN_RATE
        , START_DATE
        , PSA_LOAD_DTS
        , PSA_RECORD_SOURCE
        , REC_SRC
        , BKCC
        , HASHDIFF
FROM JOIN_RESULT
{% if is_incremental() %}
WHERE NOT EXISTS (
    SELECT 1 
    FROM {{ this }} existing
    WHERE existing.STORE_HK = JOIN_RESULT.STORE_HK 
	AND existing.ITEM_ID = JOIN_RESULT.ITEM_ID 
	AND existing.END_DATE = JOIN_RESULT.END_DATE 
    AND existing.HASHDIFF = JOIN_RESULT.HASHDIFF	
)
{% endif %}
 
{% if not is_incremental() %}
qualify 1=row_number() over(partition by store_hk,item_id,end_date,hashdiff order by psa_load_dts)
union all
SELECT MD5_BINARY(GR.VALUE::varchar) AS STORE_HK
	, GR.VALUE::varchar as LOCATION_ID
	, GR.VALUE::varchar as ITEM_ID
	, '1900-01-01' as END_DATE
	, CONVERT_TIMEZONE('UTC','1900-01-01'::TIMESTAMP) as LOAD_DTS
	, null as ITEM_NAME
	, null as LOCATION_NAME
	, null as TY_AVAILABLE_INVENTORY_UNITS
	, null as LY_AVAILABLE_INVENTORY_UNITS
	, null as TY_VS_LY_AVAILABLE_INVENTORY_UNITS
	, null as TY_AVAILABLE_INVENTORY_SALES
	, null as LY_AVAILABLE_INVENTORY_SALES
	, null as TY_VS_LY_AVAILABLE_INVENTORY_SALES
	, null as AVAILABLE_DC_INVENTORY_UNITS
	, null as AVAILABLE_RETAIL_INVENTORY_UNITS
	, null as TY_INVENTORY_ON_DIRECT_ORDER_UNITS
	, null as LY_INVENTORY_ON_DIRECT_ORDER_UNITS
	, null as TY_VS_LY_INVENTORY_ON_DIRECT_ORDER_UNITS
	, null as TY_INVENTORY_ON_DIRECT_ORDER_SALES
	, null as LY_INVENTORY_ON_DIRECT_ORDER_SALES
	, null as TY_VS_LY_INVENTORY_ON_DIRECT_ORDER_SALES
	, null as TY_INVENTORY_UNITS_IN_REQ
	, null as LY_INVENTORY_UNITS_IN_REQ
	, null as TY_VS_LY_INVENTORY_UNITS_IN_REQ
	, null as TY_INVENTORY_UNITS_ON_BILL
	, null as LY_INVENTORY_UNITS_ON_BILL
	, null as TY_VS_LY_INVENTORY_UNITS_ON_BILL
	, null as TY_SALES_UNITS
	, null as LY_SALES_UNITS
	, null as TY_VS_LY_SALES_UNITS
	, null as TY_SALES
	, null as LY_SALES
	, null as TY_VS_LY_SALES
	, null as GROSS_SALES
	, null as TY_FULFILLED_INTERNET_UNITS
	, null as LY_FULFILLED_INTERNET_UNITS
	, null as TY_VS_LY_FULFILLED_INTERNET_UNITS
	, null as TY_FULFILLED_INTERNET_SALES
	, null as LY_FULFILLED_INTERNET_SALES
	, null as TY_VS_LY_FULFILLED_INTERNET_SALES
	, null as TY_AVG_INVENTORY_ON_HAND_UNITS
	, null as LY_AVG_INVENTORY_ON_HAND_UNITS
	, null as TY_VS_LY_AVG_INVENTORY_ON_HAND_UNITS
	, null as TY_AVG_INVENTORY_ON_HAND_SALES
	, null as LY_AVG_INVENTORY_ON_HAND_SALES
	, null as TY_VS_LY_AVG_INVENTORY_ON_HAND_SALES
	, null as TY_AVERAGE_INVENTORY_ON_DIRECT_ORDER_UNITS
	, null as LY_AVERAGE_INVENTORY_ON_DIRECT_ORDER_UNITS
	, null as TY_VS_LY_AVERAGE_INVENTORY_ON_DIRECT_ORDER_UNITS
	, null as TY_AVERAGE_INVENTORY_ON_DIRECT_ORDER_SALES
	, null as LY_AVERAGE_INVENTORY_ON_DIRECT_ORDER_SALES
	, null as TY_VS_LY_AVERAGE_INVENTORY_ON_DIRECT_ORDER_SALES
	, null as TY_AVERAGE_INVENTORY_ON_REQUISITION_UNITS
	, null as LY_AVERAGE_INVENTORY_ON_REQUISITION_UNITS
	, null as TY_VS_LY_AVERAGE_INVENTORY_ON_REQUISITION_UNITS
	, null as TY_AVERAGE_INVENTORY_ON_REQUISITION_SALES
	, null as LY_AVERAGE_INVENTORY_ON_REQUISITION_SALES
	, null as TY_VS_LY_AVERAGE_INVENTORY_ON_REQUISITION_SALES
	, null as IN_STOCK_PERCENTAGE
	, null as AVERAGE_YEAR_TO_DATE_SALES
	, null as TY_YEAR_TO_DATE_SALES_UNITS
	, null as LY_YEAR_TO_DATE_SALES_UNITS
	, null as TY_VS_LY_YEAR_TO_DATE_SALES_UNITS
	, null as WEEKS_OF_SUPPLY_ON_HAND
	, null as WEEKS_OF_SUPPLY_ON_ORDER
	, null as TY_JDA_LOST_SALES
	, null as TY_JDA_SERVICE_LEVEL
	, null as LY_TURN_RATE
	, null as TY_TURN_RATE
	, null as START_DATE	
	, null as PSA_LOAD_DTS
	, null as PSA_RECORD_SOURCE
	, 'USAZET.SNOWFLAKE.FBIN.DERIVED' AS REC_SRC
        , DECODE(GR.VALUE::varchar, 0, 'GHOST RECORD-SYSTEM', -1, 'GHOST RECORD-nullkey-required', -2, 'GHOST RECORD-nullkey-optional')  AS  BKCC
        , ''::BINARY as HASH_DIFF
        FROM
        TABLE(strtok_split_to_table('0|-1|-2', '|')) AS GR
{% endif %}