---- SRC LAYER ----
WITH
SRC_SSA            as ( SELECT * FROM {{ ref('v_psa_stg_inventory_yale__amazon_fivetran') }} as SRC 
                         {% if is_incremental() %}
                         WHERE SRC.LOAD_DTS > (SELECT DATEADD('HOUR', '-1', MAX(LOAD_DTS)) FROM {{this}})
                         {% endif %}  )

/*
SRC_SSA            as ( SELECT * FROM STAGING.v_psa_stg_inventory_yale__amazon_fivetran )
*/
---- LOGIC LAYER ----

, LOGIC_SSA as (
    SELECT
        STORE_HK
      , LOAD_DTS
      , REPORT_END_DATE
      , VENDORCENTRAL_ACCOUNT
      , ASIN
      , REPORT_START_DATE
      , NET_RECEIVED_INV_AMT
      , NET_RECEIVED_INV_CURRCD
      , NET_RECEIVED_INV_UNITS
      , OPEN_PO_UNITS
      , AVG_VENDOR_LEADTIME_DAYS
      , SELL_THROUGH_RATE
      , UNFILLED_CUST_ORDRD_UNITS
      , SELLABLE_OH_INV_AMT
      , SELLABLE_OH_INV_CURRCODE
      , SELLABLE_OH_INV_UNITS
      , UNSELLABLE_OH_INV_AMT
      , UNSELLABLE_OH_INV_CURRCODE
      , UNSELLABLE_OH_INV_UNITS
      , AGED_90DAYS_SELLABLE_INVAMT
      , AGED_90DAYS_SELLABLE_INVCURRCD
      , AGED_90DAYS_SELLABLE_INVUNITS
      , UNHEALTHY_INV_AMT
      , UNHEALTHY_INV_CURRCODE
      , UNHEALTHY_INV_UNITS
      , PSA_LOAD_DTS
      , PSA_RECORD_SOURCE
      , PSA_DELETE_IND
      , REC_SRC
      , BKCC
      , HASHDIFF
    FROM SRC_SSA
)
---- RENAME LAYER ----

, RENAME_SSA as (
    SELECT
        STORE_HK
      , LOAD_DTS
      , REPORT_END_DATE
      , VENDORCENTRAL_ACCOUNT
      , ASIN
      , REPORT_START_DATE
      , NET_RECEIVED_INV_AMT
      , NET_RECEIVED_INV_CURRCD
      , NET_RECEIVED_INV_UNITS
      , OPEN_PO_UNITS
      , AVG_VENDOR_LEADTIME_DAYS
      , SELL_THROUGH_RATE
      , UNFILLED_CUST_ORDRD_UNITS
      , SELLABLE_OH_INV_AMT
      , SELLABLE_OH_INV_CURRCODE
      , SELLABLE_OH_INV_UNITS
      , UNSELLABLE_OH_INV_AMT
      , UNSELLABLE_OH_INV_CURRCODE
      , UNSELLABLE_OH_INV_UNITS
      , AGED_90DAYS_SELLABLE_INVAMT
      , AGED_90DAYS_SELLABLE_INVCURRCD
      , AGED_90DAYS_SELLABLE_INVUNITS
      , UNHEALTHY_INV_AMT
      , UNHEALTHY_INV_CURRCODE
      , UNHEALTHY_INV_UNITS
      , PSA_LOAD_DTS
      , PSA_RECORD_SOURCE
      , PSA_DELETE_IND
      , REC_SRC
      , BKCC
      , HASHDIFF
    FROM LOGIC_SSA
)
---- FILTER LAYER ----

, FILTER_SSA as (
    SELECT *
    FROM RENAME_SSA
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM FILTER_SSA
)

---- FINAL LAYER ----
SELECT
          STORE_HK
        , LOAD_DTS
        , REPORT_END_DATE
        , VENDORCENTRAL_ACCOUNT
        , ASIN
        , REPORT_START_DATE
        , NET_RECEIVED_INV_AMT
        , NET_RECEIVED_INV_CURRCD
        , NET_RECEIVED_INV_UNITS
        , OPEN_PO_UNITS
        , AVG_VENDOR_LEADTIME_DAYS
        , SELL_THROUGH_RATE
        , UNFILLED_CUST_ORDRD_UNITS
        , SELLABLE_OH_INV_AMT
        , SELLABLE_OH_INV_CURRCODE
        , SELLABLE_OH_INV_UNITS
        , UNSELLABLE_OH_INV_AMT
        , UNSELLABLE_OH_INV_CURRCODE
        , UNSELLABLE_OH_INV_UNITS
        , AGED_90DAYS_SELLABLE_INVAMT
        , AGED_90DAYS_SELLABLE_INVCURRCD
        , AGED_90DAYS_SELLABLE_INVUNITS
        , UNHEALTHY_INV_AMT
        , UNHEALTHY_INV_CURRCODE
        , UNHEALTHY_INV_UNITS
        , PSA_LOAD_DTS
        , PSA_RECORD_SOURCE
        , PSA_DELETE_IND
        , REC_SRC
        , BKCC
        , HASHDIFF
FROM JOIN_RESULT
{% if is_incremental() %}
WHERE NOT EXISTS (
    SELECT 1 
    FROM {{ this }} existing
    WHERE existing.STORE_HK = JOIN_RESULT.STORE_HK 
	AND existing.REPORT_END_DATE=JOIN_RESULT.REPORT_END_DATE
	AND existing.VENDORCENTRAL_ACCOUNT=JOIN_RESULT.VENDORCENTRAL_ACCOUNT
	AND existing.ASIN=JOIN_RESULT.ASIN
	AND existing.LOAD_DTS=JOIN_RESULT.LOAD_DTS	
    AND existing.HASHDIFF = JOIN_RESULT.HASHDIFF	
)
{% endif %}
qualify 1 = row_number() over (partition by STORE_HK,REPORT_END_DATE,ASIN, VENDORCENTRAL_ACCOUNT, HASHDIFF order by PSA_LOAD_DTS desc) 
{% if not is_incremental() %}
union all
SELECT MD5_BINARY(GR.VALUE::varchar) AS STORE_HK
, CONVERT_TIMEZONE('UTC','1900-01-01'::TIMESTAMP) as LOAD_DTS
, GR.VALUE::varchar as REPORT_END_DATE
, GR.VALUE::varchar as VENDORCENTRAL_ACCOUNT
, GR.VALUE::varchar as ASIN
, null as REPORT_START_DATE
, null as NET_RECEIVED_INV_AMT
, null as NET_RECEIVED_INV_CURRCD
, null as NET_RECEIVED_INV_UNITS
, null as OPEN_PO_UNITS
, null as AVG_VENDOR_LEADTIME_DAYS
, null as SELL_THROUGH_RATE
, null as UNFILLED_CUST_ORDRD_UNITS
, null as SELLABLE_OH_INV_AMT
, null as SELLABLE_OH_INV_CURRCODE
, null as SELLABLE_OH_INV_UNITS
, null as UNSELLABLE_OH_INV_AMT
, null as UNSELLABLE_OH_INV_CURRCODE
, null as UNSELLABLE_OH_INV_UNITS
, null as AGED_90DAYS_SELLABLE_INVAMT
, null as AGED_90DAYS_SELLABLE_INVCURRCD
, null as AGED_90DAYS_SELLABLE_INVUNITS
, null as UNHEALTHY_INV_AMT
, null as UNHEALTHY_INV_CURRCODE
, null as UNHEALTHY_INV_UNITS
, null as PSA_LOAD_DTS
, null as PSA_RECORD_SOURCE
, null as PSA_DELETE_IND
, 'USAZET.SNOWFLAKE.FBIN.DERIVED' AS REC_SRC
, DECODE(GR.VALUE::varchar, 0, 'GHOST RECORD-SYSTEM', -1, 'GHOST RECORD-nullkey-required', -2, 'GHOST RECORD-nullkey-optional')  AS  BKCC
, ''::BINARY as HASH_DIFF
        FROM
        TABLE(strtok_split_to_table('0|-1|-2', '|')) AS GR
{% endif %}