---- SRC LAYER ----
WITH
SRC_SCUSTFB        as ( SELECT * FROM {{ ref('v_psa_stg_customer__fib_ocf') }} as SRC 
                         {% if is_incremental() %}
                         WHERE SRC.LOAD_DTS > (SELECT DATEADD('HOUR', '-1', MAX(LOAD_DTS)) FROM {{this}})
                         {% endif %}  )

/*
SRC_SCUSTFB        as ( SELECT * FROM STAGING.v_psa_stg_customer__fib_ocf )
*/
---- LOGIC LAYER ----

, LOGIC_SCUSTFB as (
    SELECT
        CUSTOMER_HK
      , CUST_ACCOUNT_ID
      , ACCOUNT_NUMBER
      , AUTOPAY_FLAG
      , LAST_BATCH_ID
      , ATTRIBUTE_3
      , ATTRIBUTE_4
      , ATTRIBUTE_5
      , ATTRIBUTE_6
      , ATTRIBUTE_7
      , ATTRIBUTE_8
      , CREATION_DATE
      , CREATED_BY
      , LAST_UPDATE_LOGIN
      , REQUEST_ID
      , JOB_DEFINITION_NAME
      , JOB_DEFINITION_PACKAGE
      , ATTRIBUTE_CATEGORY
      , GLOBAL_ATTRIBUTE_3
      , GLOBAL_ATTRIBUTE_4
      , GLOBAL_ATTRIBUTE_5
      , GLOBAL_ATTRIBUTE_6
      , GLOBAL_ATTRIBUTE_7
      , STATUS
      , CUSTOMER_TYPE
      , CUSTOMER_CLASS_CODE
      , TAX_CODE
      , TAX_HEADER_LEVEL_FLAG
      , TAX_ROUNDING_RULE
      , ATTRIBUTE_10
      , ATTRIBUTE_11
      , ATTRIBUTE_12
      , ATTRIBUTE_1
      , ATTRIBUTE_2
      , ATTRIBUTE_13
      , ATTRIBUTE_14
      , ATTRIBUTE_15
      , ATTRIBUTE_16
      , ATTRIBUTE_17
      , ATTRIBUTE_18
      , ATTRIBUTE_9
      , PARTY_ID
      , LAST_UPDATE_DATE
      , LAST_UPDATED_BY
      , GLOBAL_ATTRIBUTE_DATE_1
      , GLOBAL_ATTRIBUTE_DATE_5
      , GLOBAL_ATTRIBUTE_CATEGORY
      , GLOBAL_ATTRIBUTE_1
      , GLOBAL_ATTRIBUTE_2
      , GLOBAL_ATTRIBUTE_8
      , GLOBAL_ATTRIBUTE_9
      , GLOBAL_ATTRIBUTE_NUMBER_2
      , GLOBAL_ATTRIBUTE_NUMBER_3
      , GLOBAL_ATTRIBUTE_NUMBER_4
      , GLOBAL_ATTRIBUTE_NUMBER_5
      , GLOBAL_ATTRIBUTE_10
      , GLOBAL_ATTRIBUTE_11
      , GLOBAL_ATTRIBUTE_12
      , GLOBAL_ATTRIBUTE_13
      , GLOBAL_ATTRIBUTE_14
      , GLOBAL_ATTRIBUTE_15
      , GLOBAL_ATTRIBUTE_NUMBER_1
      , GLOBAL_ATTRIBUTE_DATE_2
      , GLOBAL_ATTRIBUTE_DATE_3
      , GLOBAL_ATTRIBUTE_DATE_4
      , ATTRIBUTE_19
      , ATTRIBUTE_20
      , ORIG_SYSTEM_REFERENCE
      , COTERMINATE_DAY_MONTH
      , ACCOUNT_ESTABLISHED_DATE
      , HELD_BILL_EXPIRATION_DATE
      , HOLD_BILL_FLAG
      , ACCOUNT_NAME
      , DEPOSIT_REFUND_METHOD
      , NPA_NUMBER
      , SOURCE_CODE
      , COMMENTS
      , DATE_TYPE_PREFERENCE
      , OBJECT_VERSION_NUMBER
      , CREATED_BY_MODULE
      , SELLING_PARTY_ID
      , CONFLICT_ID
      , USER_LAST_UPDATE_DATE
      , ATTRIBUTE_NUMBER_8
      , ATTRIBUTE_NUMBER_9
      , ATTRIBUTE_NUMBER_10
      , ATTRIBUTE_NUMBER_11
      , ATTRIBUTE_NUMBER_12
      , ATTRIBUTE_DATE_1
      , ATTRIBUTE_DATE_2
      , ATTRIBUTE_DATE_3
      , ATTRIBUTE_DATE_4
      , ATTRIBUTE_DATE_5
      , ARRIVALSETS_INCLUDE_LINES_FLAG
      , STATUS_UPDATE_DATE
      , ATTRIBUTE_21
      , ATTRIBUTE_22
      , ATTRIBUTE_23
      , ATTRIBUTE_24
      , ATTRIBUTE_28
      , ATTRIBUTE_29
      , ATTRIBUTE_30
      , ATTRIBUTE_NUMBER_2
      , ATTRIBUTE_NUMBER_3
      , ATTRIBUTE_NUMBER_4
      , ATTRIBUTE_NUMBER_5
      , ATTRIBUTE_NUMBER_6
      , ATTRIBUTE_NUMBER_7
      , ATTRIBUTE_DATE_6
      , ATTRIBUTE_DATE_7
      , ATTRIBUTE_DATE_8
      , ATTRIBUTE_DATE_9
      , ATTRIBUTE_DATE_10
      , ATTRIBUTE_25
      , ATTRIBUTE_26
      , ATTRIBUTE_27
      , CPDRF_VER_SOR
      , CPDRF_VER_PILLAR
      , CPDRF_LAST_UPD
      , ATTRIBUTE_NUMBER_1
      , ATTRIBUTE_DATE_11
      , ATTRIBUTE_DATE_12
      , ACCOUNT_TERMINATION_DATE
      , GLOBAL_ATTRIBUTE_17
      , GLOBAL_ATTRIBUTE_18
      , GLOBAL_ATTRIBUTE_19
      , GLOBAL_ATTRIBUTE_20
      , GLOBAL_ATTRIBUTE_21
      , GLOBAL_ATTRIBUTE_22
      , GLOBAL_ATTRIBUTE_23
      , GLOBAL_ATTRIBUTE_24
      , GLOBAL_ATTRIBUTE_25
      , GLOBAL_ATTRIBUTE_26
      , GLOBAL_ATTRIBUTE_27
      , GLOBAL_ATTRIBUTE_28
      , GLOBAL_ATTRIBUTE_29
      , GLOBAL_ATTRIBUTE_30
      , GLOBAL_ATTRIBUTE_16
      , _FIVETRAN_DELETED
      , _FIVETRAN_SYNCED
      , PSA_DELETE_IND
      , PSA_LOAD_DTS
      , PSA_RECORD_SOURCE
      , LOAD_DTS
      , REC_SRC
      , HASHDIFF
    FROM SRC_SCUSTFB
)
---- RENAME LAYER ----

, RENAME_SCUSTFB as (
    SELECT
        CUSTOMER_HK
      , CUST_ACCOUNT_ID
      , ACCOUNT_NUMBER
      , AUTOPAY_FLAG
      , LAST_BATCH_ID
      , ATTRIBUTE_3
      , ATTRIBUTE_4
      , ATTRIBUTE_5
      , ATTRIBUTE_6
      , ATTRIBUTE_7
      , ATTRIBUTE_8
      , CREATION_DATE
      , CREATED_BY
      , LAST_UPDATE_LOGIN
      , REQUEST_ID
      , JOB_DEFINITION_NAME
      , JOB_DEFINITION_PACKAGE
      , ATTRIBUTE_CATEGORY
      , GLOBAL_ATTRIBUTE_3
      , GLOBAL_ATTRIBUTE_4
      , GLOBAL_ATTRIBUTE_5
      , GLOBAL_ATTRIBUTE_6
      , GLOBAL_ATTRIBUTE_7
      , STATUS
      , CUSTOMER_TYPE
      , CUSTOMER_CLASS_CODE
      , TAX_CODE
      , TAX_HEADER_LEVEL_FLAG
      , TAX_ROUNDING_RULE
      , ATTRIBUTE_10
      , ATTRIBUTE_11
      , ATTRIBUTE_12
      , ATTRIBUTE_1
      , ATTRIBUTE_2
      , ATTRIBUTE_13
      , ATTRIBUTE_14
      , ATTRIBUTE_15
      , ATTRIBUTE_16
      , ATTRIBUTE_17
      , ATTRIBUTE_18
      , ATTRIBUTE_9
      , PARTY_ID
      , LAST_UPDATE_DATE
      , LAST_UPDATED_BY
      , GLOBAL_ATTRIBUTE_DATE_1
      , GLOBAL_ATTRIBUTE_DATE_5
      , GLOBAL_ATTRIBUTE_CATEGORY
      , GLOBAL_ATTRIBUTE_1
      , GLOBAL_ATTRIBUTE_2
      , GLOBAL_ATTRIBUTE_8
      , GLOBAL_ATTRIBUTE_9
      , GLOBAL_ATTRIBUTE_NUMBER_2
      , GLOBAL_ATTRIBUTE_NUMBER_3
      , GLOBAL_ATTRIBUTE_NUMBER_4
      , GLOBAL_ATTRIBUTE_NUMBER_5
      , GLOBAL_ATTRIBUTE_10
      , GLOBAL_ATTRIBUTE_11
      , GLOBAL_ATTRIBUTE_12
      , GLOBAL_ATTRIBUTE_13
      , GLOBAL_ATTRIBUTE_14
      , GLOBAL_ATTRIBUTE_15
      , GLOBAL_ATTRIBUTE_NUMBER_1
      , GLOBAL_ATTRIBUTE_DATE_2
      , GLOBAL_ATTRIBUTE_DATE_3
      , GLOBAL_ATTRIBUTE_DATE_4
      , ATTRIBUTE_19
      , ATTRIBUTE_20
      , ORIG_SYSTEM_REFERENCE
      , COTERMINATE_DAY_MONTH
      , ACCOUNT_ESTABLISHED_DATE
      , HELD_BILL_EXPIRATION_DATE
      , HOLD_BILL_FLAG
      , ACCOUNT_NAME
      , DEPOSIT_REFUND_METHOD
      , NPA_NUMBER
      , SOURCE_CODE
      , COMMENTS
      , DATE_TYPE_PREFERENCE
      , OBJECT_VERSION_NUMBER
      , CREATED_BY_MODULE
      , SELLING_PARTY_ID
      , CONFLICT_ID
      , USER_LAST_UPDATE_DATE
      , ATTRIBUTE_NUMBER_8
      , ATTRIBUTE_NUMBER_9
      , ATTRIBUTE_NUMBER_10
      , ATTRIBUTE_NUMBER_11
      , ATTRIBUTE_NUMBER_12
      , ATTRIBUTE_DATE_1
      , ATTRIBUTE_DATE_2
      , ATTRIBUTE_DATE_3
      , ATTRIBUTE_DATE_4
      , ATTRIBUTE_DATE_5
      , ARRIVALSETS_INCLUDE_LINES_FLAG
      , STATUS_UPDATE_DATE
      , ATTRIBUTE_21
      , ATTRIBUTE_22
      , ATTRIBUTE_23
      , ATTRIBUTE_24
      , ATTRIBUTE_28
      , ATTRIBUTE_29
      , ATTRIBUTE_30
      , ATTRIBUTE_NUMBER_2
      , ATTRIBUTE_NUMBER_3
      , ATTRIBUTE_NUMBER_4
      , ATTRIBUTE_NUMBER_5
      , ATTRIBUTE_NUMBER_6
      , ATTRIBUTE_NUMBER_7
      , ATTRIBUTE_DATE_6
      , ATTRIBUTE_DATE_7
      , ATTRIBUTE_DATE_8
      , ATTRIBUTE_DATE_9
      , ATTRIBUTE_DATE_10
      , ATTRIBUTE_25
      , ATTRIBUTE_26
      , ATTRIBUTE_27
      , CPDRF_VER_SOR
      , CPDRF_VER_PILLAR
      , CPDRF_LAST_UPD
      , ATTRIBUTE_NUMBER_1
      , ATTRIBUTE_DATE_11
      , ATTRIBUTE_DATE_12
      , ACCOUNT_TERMINATION_DATE
      , GLOBAL_ATTRIBUTE_17
      , GLOBAL_ATTRIBUTE_18
      , GLOBAL_ATTRIBUTE_19
      , GLOBAL_ATTRIBUTE_20
      , GLOBAL_ATTRIBUTE_21
      , GLOBAL_ATTRIBUTE_22
      , GLOBAL_ATTRIBUTE_23
      , GLOBAL_ATTRIBUTE_24
      , GLOBAL_ATTRIBUTE_25
      , GLOBAL_ATTRIBUTE_26
      , GLOBAL_ATTRIBUTE_27
      , GLOBAL_ATTRIBUTE_28
      , GLOBAL_ATTRIBUTE_29
      , GLOBAL_ATTRIBUTE_30
      , GLOBAL_ATTRIBUTE_16
      , _FIVETRAN_DELETED
      , _FIVETRAN_SYNCED
      , PSA_DELETE_IND
      , PSA_LOAD_DTS
      , PSA_RECORD_SOURCE
      , LOAD_DTS
      , REC_SRC
      , HASHDIFF
    FROM LOGIC_SCUSTFB
)
---- FILTER LAYER ----

, FILTER_SCUSTFB as (
    SELECT *
    FROM RENAME_SCUSTFB
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM FILTER_SCUSTFB
)

---- FINAL LAYER ----
SELECT
          CUSTOMER_HK
        , CUST_ACCOUNT_ID
        , ACCOUNT_NUMBER
        , AUTOPAY_FLAG
        , LAST_BATCH_ID
        , ATTRIBUTE_3
        , ATTRIBUTE_4
        , ATTRIBUTE_5
        , ATTRIBUTE_6
        , ATTRIBUTE_7
        , ATTRIBUTE_8
        , CREATION_DATE
        , CREATED_BY
        , LAST_UPDATE_LOGIN
        , REQUEST_ID
        , JOB_DEFINITION_NAME
        , JOB_DEFINITION_PACKAGE
        , ATTRIBUTE_CATEGORY
        , GLOBAL_ATTRIBUTE_3
        , GLOBAL_ATTRIBUTE_4
        , GLOBAL_ATTRIBUTE_5
        , GLOBAL_ATTRIBUTE_6
        , GLOBAL_ATTRIBUTE_7
        , STATUS
        , CUSTOMER_TYPE
        , CUSTOMER_CLASS_CODE
        , TAX_CODE
        , TAX_HEADER_LEVEL_FLAG
        , TAX_ROUNDING_RULE
        , ATTRIBUTE_10
        , ATTRIBUTE_11
        , ATTRIBUTE_12
        , ATTRIBUTE_1
        , ATTRIBUTE_2
        , ATTRIBUTE_13
        , ATTRIBUTE_14
        , ATTRIBUTE_15
        , ATTRIBUTE_16
        , ATTRIBUTE_17
        , ATTRIBUTE_18
        , ATTRIBUTE_9
        , PARTY_ID
        , LAST_UPDATE_DATE
        , LAST_UPDATED_BY
        , GLOBAL_ATTRIBUTE_DATE_1
        , GLOBAL_ATTRIBUTE_DATE_5
        , GLOBAL_ATTRIBUTE_CATEGORY
        , GLOBAL_ATTRIBUTE_1
        , GLOBAL_ATTRIBUTE_2
        , GLOBAL_ATTRIBUTE_8
        , GLOBAL_ATTRIBUTE_9
        , GLOBAL_ATTRIBUTE_NUMBER_2
        , GLOBAL_ATTRIBUTE_NUMBER_3
        , GLOBAL_ATTRIBUTE_NUMBER_4
        , GLOBAL_ATTRIBUTE_NUMBER_5
        , GLOBAL_ATTRIBUTE_10
        , GLOBAL_ATTRIBUTE_11
        , GLOBAL_ATTRIBUTE_12
        , GLOBAL_ATTRIBUTE_13
        , GLOBAL_ATTRIBUTE_14
        , GLOBAL_ATTRIBUTE_15
        , GLOBAL_ATTRIBUTE_NUMBER_1
        , GLOBAL_ATTRIBUTE_DATE_2
        , GLOBAL_ATTRIBUTE_DATE_3
        , GLOBAL_ATTRIBUTE_DATE_4
        , ATTRIBUTE_19
        , ATTRIBUTE_20
        , ORIG_SYSTEM_REFERENCE
        , COTERMINATE_DAY_MONTH
        , ACCOUNT_ESTABLISHED_DATE
        , HELD_BILL_EXPIRATION_DATE
        , HOLD_BILL_FLAG
        , ACCOUNT_NAME
        , DEPOSIT_REFUND_METHOD
        , NPA_NUMBER
        , SOURCE_CODE
        , COMMENTS
        , DATE_TYPE_PREFERENCE
        , OBJECT_VERSION_NUMBER
        , CREATED_BY_MODULE
        , SELLING_PARTY_ID
        , CONFLICT_ID
        , USER_LAST_UPDATE_DATE
        , ATTRIBUTE_NUMBER_8
        , ATTRIBUTE_NUMBER_9
        , ATTRIBUTE_NUMBER_10
        , ATTRIBUTE_NUMBER_11
        , ATTRIBUTE_NUMBER_12
        , ATTRIBUTE_DATE_1
        , ATTRIBUTE_DATE_2
        , ATTRIBUTE_DATE_3
        , ATTRIBUTE_DATE_4
        , ATTRIBUTE_DATE_5
        , ARRIVALSETS_INCLUDE_LINES_FLAG
        , STATUS_UPDATE_DATE
        , ATTRIBUTE_21
        , ATTRIBUTE_22
        , ATTRIBUTE_23
        , ATTRIBUTE_24
        , ATTRIBUTE_28
        , ATTRIBUTE_29
        , ATTRIBUTE_30
        , ATTRIBUTE_NUMBER_2
        , ATTRIBUTE_NUMBER_3
        , ATTRIBUTE_NUMBER_4
        , ATTRIBUTE_NUMBER_5
        , ATTRIBUTE_NUMBER_6
        , ATTRIBUTE_NUMBER_7
        , ATTRIBUTE_DATE_6
        , ATTRIBUTE_DATE_7
        , ATTRIBUTE_DATE_8
        , ATTRIBUTE_DATE_9
        , ATTRIBUTE_DATE_10
        , ATTRIBUTE_25
        , ATTRIBUTE_26
        , ATTRIBUTE_27
        , CPDRF_VER_SOR
        , CPDRF_VER_PILLAR
        , CPDRF_LAST_UPD
        , ATTRIBUTE_NUMBER_1
        , ATTRIBUTE_DATE_11
        , ATTRIBUTE_DATE_12
        , ACCOUNT_TERMINATION_DATE
        , GLOBAL_ATTRIBUTE_17
        , GLOBAL_ATTRIBUTE_18
        , GLOBAL_ATTRIBUTE_19
        , GLOBAL_ATTRIBUTE_20
        , GLOBAL_ATTRIBUTE_21
        , GLOBAL_ATTRIBUTE_22
        , GLOBAL_ATTRIBUTE_23
        , GLOBAL_ATTRIBUTE_24
        , GLOBAL_ATTRIBUTE_25
        , GLOBAL_ATTRIBUTE_26
        , GLOBAL_ATTRIBUTE_27
        , GLOBAL_ATTRIBUTE_28
        , GLOBAL_ATTRIBUTE_29
        , GLOBAL_ATTRIBUTE_30
        , GLOBAL_ATTRIBUTE_16
        , _FIVETRAN_DELETED
        , _FIVETRAN_SYNCED
        , PSA_DELETE_IND
        , PSA_LOAD_DTS
        , PSA_RECORD_SOURCE
        , LOAD_DTS
        , REC_SRC
        , HASHDIFF
FROM JOIN_RESULT
{% if is_incremental() %}
WHERE NOT EXISTS (
    SELECT 1 
    FROM {{ this }} existing
    WHERE existing.CUSTOMER_HK = JOIN_RESULT.CUSTOMER_HK
    AND existing.HASHDIFF = JOIN_RESULT.HASHDIFF
)
{% endif %}
{% if not is_incremental() %}

/* The following qualifier is implemented to prevent multiple loads of touched records during the initial build, such as multiple rows per HK and hashdiff. */
qualify 1 = row_number() over (partition by CUSTOMER_HK, HASHDIFF order by PSA_LOAD_DTS)

union all
SELECT 
MD5_BINARY(GR.VALUE) AS CUSTOMER_HK,
GR.VALUE::number AS CUST_ACCOUNT_ID,
GR.VALUE::text AS ACCOUNT_NUMBER,
NULL AS AUTOPAY_FLAG,
NULL AS LAST_BATCH_ID,
NULL AS ATTRIBUTE_3,
NULL AS ATTRIBUTE_4,
NULL AS ATTRIBUTE_5,
NULL AS ATTRIBUTE_6,
NULL AS ATTRIBUTE_7,
NULL AS ATTRIBUTE_8,
NULL AS CREATION_DATE,
NULL AS CREATED_BY,
NULL AS LAST_UPDATE_LOGIN,
NULL AS REQUEST_ID,
NULL AS JOB_DEFINITION_NAME,
NULL AS JOB_DEFINITION_PACKAGE,
NULL AS ATTRIBUTE_CATEGORY,
NULL AS GLOBAL_ATTRIBUTE_3,
NULL AS GLOBAL_ATTRIBUTE_4,
NULL AS GLOBAL_ATTRIBUTE_5,
NULL AS GLOBAL_ATTRIBUTE_6,
NULL AS GLOBAL_ATTRIBUTE_7,
NULL AS STATUS,
NULL AS CUSTOMER_TYPE,
NULL AS CUSTOMER_CLASS_CODE,
NULL AS TAX_CODE,
NULL AS TAX_HEADER_LEVEL_FLAG,
NULL AS TAX_ROUNDING_RULE,
NULL AS ATTRIBUTE_10,
NULL AS ATTRIBUTE_11,
NULL AS ATTRIBUTE_12,
NULL AS ATTRIBUTE_1,
NULL AS ATTRIBUTE_2,
NULL AS ATTRIBUTE_13,
NULL AS ATTRIBUTE_14,
NULL AS ATTRIBUTE_15,
NULL AS ATTRIBUTE_16,
NULL AS ATTRIBUTE_17,
NULL AS ATTRIBUTE_18,
NULL AS ATTRIBUTE_9,
NULL AS PARTY_ID,
NULL AS LAST_UPDATE_DATE,
NULL AS LAST_UPDATED_BY,
NULL AS GLOBAL_ATTRIBUTE_DATE_1,
NULL AS GLOBAL_ATTRIBUTE_DATE_5,
NULL AS GLOBAL_ATTRIBUTE_CATEGORY,
NULL AS GLOBAL_ATTRIBUTE_1,
NULL AS GLOBAL_ATTRIBUTE_2,
NULL AS GLOBAL_ATTRIBUTE_8,
NULL AS GLOBAL_ATTRIBUTE_9,
NULL AS GLOBAL_ATTRIBUTE_NUMBER_2,
NULL AS GLOBAL_ATTRIBUTE_NUMBER_3,
NULL AS GLOBAL_ATTRIBUTE_NUMBER_4,
NULL AS GLOBAL_ATTRIBUTE_NUMBER_5,
NULL AS GLOBAL_ATTRIBUTE_10,
NULL AS GLOBAL_ATTRIBUTE_11,
NULL AS GLOBAL_ATTRIBUTE_12,
NULL AS GLOBAL_ATTRIBUTE_13,
NULL AS GLOBAL_ATTRIBUTE_14,
NULL AS GLOBAL_ATTRIBUTE_15,
NULL AS GLOBAL_ATTRIBUTE_NUMBER_1,
NULL AS GLOBAL_ATTRIBUTE_DATE_2,
NULL AS GLOBAL_ATTRIBUTE_DATE_3,
NULL AS GLOBAL_ATTRIBUTE_DATE_4,
NULL AS ATTRIBUTE_19,
NULL AS ATTRIBUTE_20,
NULL AS ORIG_SYSTEM_REFERENCE,
NULL AS COTERMINATE_DAY_MONTH,
NULL AS ACCOUNT_ESTABLISHED_DATE,
NULL AS HELD_BILL_EXPIRATION_DATE,
NULL AS HOLD_BILL_FLAG,
NULL AS ACCOUNT_NAME,
NULL AS DEPOSIT_REFUND_METHOD,
NULL AS NPA_NUMBER,
NULL AS SOURCE_CODE,
NULL AS COMMENTS,
NULL AS DATE_TYPE_PREFERENCE,
NULL AS OBJECT_VERSION_NUMBER,
NULL AS CREATED_BY_MODULE,
NULL AS SELLING_PARTY_ID,
NULL AS CONFLICT_ID,
NULL AS USER_LAST_UPDATE_DATE,
NULL AS ATTRIBUTE_NUMBER_8,
NULL AS ATTRIBUTE_NUMBER_9,
NULL AS ATTRIBUTE_NUMBER_10,
NULL AS ATTRIBUTE_NUMBER_11,
NULL AS ATTRIBUTE_NUMBER_12,
NULL AS ATTRIBUTE_DATE_1,
NULL AS ATTRIBUTE_DATE_2,
NULL AS ATTRIBUTE_DATE_3,
NULL AS ATTRIBUTE_DATE_4,
NULL AS ATTRIBUTE_DATE_5,
NULL AS ARRIVALSETS_INCLUDE_LINES_FLAG,
NULL AS STATUS_UPDATE_DATE,
NULL AS ATTRIBUTE_21,
NULL AS ATTRIBUTE_22,
NULL AS ATTRIBUTE_23,
NULL AS ATTRIBUTE_24,
NULL AS ATTRIBUTE_28,
NULL AS ATTRIBUTE_29,
NULL AS ATTRIBUTE_30,
NULL AS ATTRIBUTE_NUMBER_2,
NULL AS ATTRIBUTE_NUMBER_3,
NULL AS ATTRIBUTE_NUMBER_4,
NULL AS ATTRIBUTE_NUMBER_5,
NULL AS ATTRIBUTE_NUMBER_6,
NULL AS ATTRIBUTE_NUMBER_7,
NULL AS ATTRIBUTE_DATE_6,
NULL AS ATTRIBUTE_DATE_7,
NULL AS ATTRIBUTE_DATE_8,
NULL AS ATTRIBUTE_DATE_9,
NULL AS ATTRIBUTE_DATE_10,
NULL AS ATTRIBUTE_25,
NULL AS ATTRIBUTE_26,
NULL AS ATTRIBUTE_27,
NULL AS CPDRF_VER_SOR,
NULL AS CPDRF_VER_PILLAR,
NULL AS CPDRF_LAST_UPD,
NULL AS ATTRIBUTE_NUMBER_1,
NULL AS ATTRIBUTE_DATE_11,
NULL AS ATTRIBUTE_DATE_12,
NULL AS ACCOUNT_TERMINATION_DATE,
NULL AS GLOBAL_ATTRIBUTE_17,
NULL AS GLOBAL_ATTRIBUTE_18,
NULL AS GLOBAL_ATTRIBUTE_19,
NULL AS GLOBAL_ATTRIBUTE_20,
NULL AS GLOBAL_ATTRIBUTE_21,
NULL AS GLOBAL_ATTRIBUTE_22,
NULL AS GLOBAL_ATTRIBUTE_23,
NULL AS GLOBAL_ATTRIBUTE_24,
NULL AS GLOBAL_ATTRIBUTE_25,
NULL AS GLOBAL_ATTRIBUTE_26,
NULL AS GLOBAL_ATTRIBUTE_27,
NULL AS GLOBAL_ATTRIBUTE_28,
NULL AS GLOBAL_ATTRIBUTE_29,
NULL AS GLOBAL_ATTRIBUTE_30,
NULL AS GLOBAL_ATTRIBUTE_16,
NULL AS _FIVETRAN_DELETED,
NULL AS _FIVETRAN_SYNCED,
'N' AS PSA_DELETE_IND,
'1900-01-01'::TIMESTAMP AS PSA_LOAD_DTS,
NULL AS PSA_RECORD_SOURCE,
CONVERT_TIMEZONE('UTC','1900-01-01'::TIMESTAMP) AS LOAD_DTS,
'USAZET.SNOWFLAKE.FBIN.DERIVED' AS REC_SRC,
''::BINARY AS HASHDIFF
FROM
TABLE(strtok_split_to_table('0|-1|-2', '|')) AS GR
{% endif %}
