---- SRC LAYER ----
WITH
SRC_SEMTK          as ( SELECT * FROM {{ ref('v_psa_stg_plant__emtk_ebs') }} as SRC 
                         {% if is_incremental() %}
                         WHERE SRC.LOAD_DTS > (SELECT DATEADD('HOUR', '-1', MAX(LOAD_DTS)) FROM {{this}})
                         {% endif %}  )

/*
SRC_SEMTK          as ( SELECT * FROM STAGING.v_psa_stg_plant__emtk_ebs )
*/
---- LOGIC LAYER ----

, LOGIC_SEMTK as (
    SELECT
        PLANT_HK
      , ORGANIZATION_CODE
      , ORGANIZATION_ID
      , LAST_UPDATE_DATE
      , LAST_UPDATED_BY
      , CREATION_DATE
      , CREATED_BY
      , LAST_UPDATE_LOGIN
      , MASTER_ORGANIZATION_ID
      , PRIMARY_COST_METHOD
      , COST_ORGANIZATION_ID
      , DEFAULT_MATERIAL_COST_ID
      , CALENDAR_EXCEPTION_SET_ID
      , CALENDAR_CODE
      , GENERAL_LEDGER_UPDATE_CODE
      , DEFAULT_ATP_RULE_ID
      , DEFAULT_PICKING_RULE_ID
      , DEFAULT_LOCATOR_ORDER_VALUE
      , DEFAULT_SUBINV_ORDER_VALUE
      , NEGATIVE_INV_RECEIPT_CODE
      , STOCK_LOCATOR_CONTROL_CODE
      , MATERIAL_ACCOUNT
      , MATERIAL_OVERHEAD_ACCOUNT
      , MATL_OVHD_ABSORPTION_ACCT
      , RESOURCE_ACCOUNT
      , PURCHASE_PRICE_VAR_ACCOUNT
      , AP_ACCRUAL_ACCOUNT
      , OVERHEAD_ACCOUNT
      , OUTSIDE_PROCESSING_ACCOUNT
      , INTRANSIT_INV_ACCOUNT
      , INTERORG_RECEIVABLES_ACCOUNT
      , INTERORG_PRICE_VAR_ACCOUNT
      , INTERORG_PAYABLES_ACCOUNT
      , COST_OF_SALES_ACCOUNT
      , ENCUMBRANCE_ACCOUNT
      , PROJECT_COST_ACCOUNT
      , INTERORG_TRANSFER_CR_ACCOUNT
      , MATL_INTERORG_TRANSFER_CODE
      , INTERORG_TRNSFR_CHARGE_PERCENT
      , SOURCE_ORGANIZATION_ID
      , SOURCE_SUBINVENTORY
      , SOURCE_TYPE
      , ORG_MAX_WEIGHT
      , ORG_MAX_WEIGHT_UOM_CODE
      , ORG_MAX_VOLUME
      , ORG_MAX_VOLUME_UOM_CODE
      , SERIAL_NUMBER_TYPE
      , AUTO_SERIAL_ALPHA_PREFIX
      , START_AUTO_SERIAL_NUMBER
      , AUTO_LOT_ALPHA_PREFIX
      , LOT_NUMBER_UNIQUENESS
      , LOT_NUMBER_GENERATION
      , LOT_NUMBER_ZERO_PADDING
      , LOT_NUMBER_LENGTH
      , STARTING_REVISION
      , ATTRIBUTE_CATEGORY
      , ATTRIBUTE1
      , ATTRIBUTE2
      , ATTRIBUTE3
      , ATTRIBUTE4
      , ATTRIBUTE5
      , ATTRIBUTE6
      , ATTRIBUTE7
      , ATTRIBUTE8
      , ATTRIBUTE9
      , ATTRIBUTE10
      , ATTRIBUTE11
      , ATTRIBUTE12
      , ATTRIBUTE13
      , ATTRIBUTE14
      , ATTRIBUTE15
      , DEFAULT_DEMAND_CLASS
      , ENCUMBRANCE_REVERSAL_FLAG
      , MAINTAIN_FIFO_QTY_STACK_TYPE
      , INVOICE_PRICE_VAR_ACCOUNT
      , AVERAGE_COST_VAR_ACCOUNT
      , SALES_ACCOUNT
      , EXPENSE_ACCOUNT
      , SERIAL_NUMBER_GENERATION
      , REQUEST_ID
      , PROGRAM_APPLICATION_ID
      , PROGRAM_ID
      , PROGRAM_UPDATE_DATE
      , GLOBAL_ATTRIBUTE_CATEGORY
      , GLOBAL_ATTRIBUTE1
      , GLOBAL_ATTRIBUTE2
      , GLOBAL_ATTRIBUTE3
      , GLOBAL_ATTRIBUTE4
      , GLOBAL_ATTRIBUTE5
      , GLOBAL_ATTRIBUTE6
      , GLOBAL_ATTRIBUTE7
      , GLOBAL_ATTRIBUTE8
      , GLOBAL_ATTRIBUTE9
      , GLOBAL_ATTRIBUTE10
      , GLOBAL_ATTRIBUTE11
      , GLOBAL_ATTRIBUTE12
      , GLOBAL_ATTRIBUTE13
      , GLOBAL_ATTRIBUTE14
      , GLOBAL_ATTRIBUTE15
      , GLOBAL_ATTRIBUTE16
      , GLOBAL_ATTRIBUTE17
      , GLOBAL_ATTRIBUTE18
      , GLOBAL_ATTRIBUTE19
      , GLOBAL_ATTRIBUTE20
      , MAT_OVHD_COST_TYPE_ID
      , PROJECT_REFERENCE_ENABLED
      , PM_COST_COLLECTION_ENABLED
      , PROJECT_CONTROL_LEVEL
      , AVG_RATES_COST_TYPE_ID
      , TXN_APPROVAL_TIMEOUT_PERIOD
      , MO_SOURCE_REQUIRED
      , MO_PICK_CONFIRM_REQUIRED
      , MO_APPROVAL_TIMEOUT_ACTION
      , BORRPAY_MATL_VAR_ACCOUNT
      , BORRPAY_MOH_VAR_ACCOUNT
      , BORRPAY_RES_VAR_ACCOUNT
      , BORRPAY_OSP_VAR_ACCOUNT
      , BORRPAY_OVH_VAR_ACCOUNT
      , PROCESS_ENABLED_FLAG
      , PROCESS_ORGN_CODE
      , WSM_ENABLED_FLAG
      , DEFAULT_COST_GROUP_ID
      , LPN_PREFIX
      , LPN_SUFFIX
      , LPN_STARTING_NUMBER
      , WMS_ENABLED_FLAG
      , PREGEN_PUTAWAY_TASKS_FLAG
      , REGENERATION_INTERVAL
      , TIMEZONE_ID
      , MAX_PICKS_BATCH
      , DEFAULT_WMS_PICKING_RULE_ID
      , DEFAULT_PUT_AWAY_RULE_ID
      , DEFAULT_TASK_ASSIGN_RULE_ID
      , DEFAULT_LABEL_COMP_RULE_ID
      , DEFAULT_CARTON_RULE_ID
      , DEFAULT_CYC_COUNT_HEADER_ID
      , CROSSDOCK_FLAG
      , CARTONIZATION_FLAG
      , COST_CUTOFF_DATE
      , ENABLE_COSTING_BY_CATEGORY
      , COST_GROUP_ACCOUNTING
      , ALLOCATE_SERIAL_FLAG
      , DEFAULT_PICK_TASK_TYPE_ID
      , DEFAULT_CC_TASK_TYPE_ID
      , DEFAULT_PUTAWAY_TASK_TYPE_ID
      , DEFAULT_REPL_TASK_TYPE_ID
      , EAM_ENABLED_FLAG
      , MAINT_ORGANIZATION_ID
      , PRIORITIZE_WIP_JOBS
      , DEFAULT_CROSSDOCK_SUBINVENTORY
      , SKIP_TASK_WAITING_MINUTES
      , QA_SKIPPING_INSP_FLAG
      , DEFAULT_CROSSDOCK_LOCATOR_ID
      , DEFAULT_MOXFER_TASK_TYPE_ID
      , DEFAULT_MOISSUE_TASK_TYPE_ID
      , DEFAULT_MATL_OVHD_COST_ID
      , DISTRIBUTED_ORGANIZATION_FLAG
      , CARRIER_MANIFESTING_FLAG
      , DISTRIBUTION_ACCOUNT_ID
      , DIRECT_SHIPPING_ALLOWED
      , DEFAULT_PICK_OP_PLAN_ID
      , MAX_CLUSTERS_ALLOWED
      , CONSIGNED_FLAG
      , CARTONIZE_SALES_ORDERS
      , CARTONIZE_MANUFACTURING
      , DEFER_LOGICAL_TRANSACTIONS
      , WIP_OVERPICK_ENABLED
      , OVPK_TRANSFER_ORDERS_ENABLED
      , TOTAL_LPN_LENGTH
      , UCC_128_SUFFIX_FLAG
      , WCS_ENABLED
      , AUTO_DEL_ALLOC_FLAG
      , RFID_VERIF_PCNT_THRESHOLD
      , OPSM_ENABLED_FLAG
      , ALLOW_DIFFERENT_STATUS
      , CHILD_LOT_ALPHA_PREFIX
      , CHILD_LOT_NUMBER_LENGTH
      , CHILD_LOT_VALIDATION_FLAG
      , CHILD_LOT_ZERO_PADDING_FLAG
      , COPY_LOT_ATTRIBUTE_FLAG
      , CREATE_LOT_UOM_CONVERSION
      , GENEALOGY_FORMULA_SECURITY
      , PARENT_CHILD_GENERATION_FLAG
      , RULES_OVERRIDE_LOT_RESERVATION
      , YARD_MANAGEMENT_ENABLED_FLAG
      , TRADING_PARTNER_ORG_FLAG
      , DEFERRED_COGS_ACCOUNT
      , DEFAULT_CROSSDOCK_CRITERIA_ID
      , ENFORCE_LOCATOR_ALIS_UNQ_FLAG
      , EPC_GENERATION_ENABLED_FLAG
      , COMPANY_PREFIX
      , COMPANY_PREFIX_INDEX
      , COMMERCIAL_GOVT_ENTITY_NUMBER
      , LABOR_MANAGEMENT_ENABLED_FLAG
      , DEFAULT_STATUS_ID
      , LCM_ENABLED_FLAG
      , LCM_VAR_ACCOUNT
      , ALLOCATE_LOT_FLAG
      , CAT_WT_ACCOUNT
      , YARD_ORG_ID
      , YMS_COSTING_ENABLED
      , YMS_DEFAULT_SUBINV
      , YMS_DEFAULT_LOCATOR
      , DAILY_CAL_START_TIME
      , DAILY_CAL_END_TIME
      , TRADING_PARTNER_ORG_TYPE
      , DISPATCH_INBOUND_TASK
      , ENABLE_EKANBAN
      , PICK_VERIFY_SO_ENABLED
      , PICK_VERIFY_MO_ENABLED
      , PICK_VERIFY_CATEGORY_SET_ID
      , PICK_VERIFY_WT_TOLERANCE_POS
      , PICK_VERIFY_WT_TOLERANCE_NEG
      , CC_WORKFLOW_ENABLED_FLAG
      , CC_APPROVAL_TIMEOUT_PERIOD
      , CC_APPROVAL_TIMEOUT_ACTION
      , _FIVETRAN_DELETED
      , _FIVETRAN_ID
      , _FIVETRAN_SYNCED
      , PSA_DELETE_IND
      , PSA_LOAD_DTS
      , PSA_RECORD_SOURCE
      , LOAD_DTS
      , REC_SRC
      , BKCC
      , HASHDIFF
    FROM SRC_SEMTK
)
---- RENAME LAYER ----

, RENAME_SEMTK as (
    SELECT
        PLANT_HK
      , ORGANIZATION_CODE
      , ORGANIZATION_ID
      , LAST_UPDATE_DATE
      , LAST_UPDATED_BY
      , CREATION_DATE
      , CREATED_BY
      , LAST_UPDATE_LOGIN
      , MASTER_ORGANIZATION_ID
      , PRIMARY_COST_METHOD
      , COST_ORGANIZATION_ID
      , DEFAULT_MATERIAL_COST_ID
      , CALENDAR_EXCEPTION_SET_ID
      , CALENDAR_CODE
      , GENERAL_LEDGER_UPDATE_CODE
      , DEFAULT_ATP_RULE_ID
      , DEFAULT_PICKING_RULE_ID
      , DEFAULT_LOCATOR_ORDER_VALUE
      , DEFAULT_SUBINV_ORDER_VALUE
      , NEGATIVE_INV_RECEIPT_CODE
      , STOCK_LOCATOR_CONTROL_CODE
      , MATERIAL_ACCOUNT
      , MATERIAL_OVERHEAD_ACCOUNT
      , MATL_OVHD_ABSORPTION_ACCT
      , RESOURCE_ACCOUNT
      , PURCHASE_PRICE_VAR_ACCOUNT
      , AP_ACCRUAL_ACCOUNT
      , OVERHEAD_ACCOUNT
      , OUTSIDE_PROCESSING_ACCOUNT
      , INTRANSIT_INV_ACCOUNT
      , INTERORG_RECEIVABLES_ACCOUNT
      , INTERORG_PRICE_VAR_ACCOUNT
      , INTERORG_PAYABLES_ACCOUNT
      , COST_OF_SALES_ACCOUNT
      , ENCUMBRANCE_ACCOUNT
      , PROJECT_COST_ACCOUNT
      , INTERORG_TRANSFER_CR_ACCOUNT
      , MATL_INTERORG_TRANSFER_CODE
      , INTERORG_TRNSFR_CHARGE_PERCENT
      , SOURCE_ORGANIZATION_ID
      , SOURCE_SUBINVENTORY
      , SOURCE_TYPE
      , ORG_MAX_WEIGHT
      , ORG_MAX_WEIGHT_UOM_CODE
      , ORG_MAX_VOLUME
      , ORG_MAX_VOLUME_UOM_CODE
      , SERIAL_NUMBER_TYPE
      , AUTO_SERIAL_ALPHA_PREFIX
      , START_AUTO_SERIAL_NUMBER
      , AUTO_LOT_ALPHA_PREFIX
      , LOT_NUMBER_UNIQUENESS
      , LOT_NUMBER_GENERATION
      , LOT_NUMBER_ZERO_PADDING
      , LOT_NUMBER_LENGTH
      , STARTING_REVISION
      , ATTRIBUTE_CATEGORY
      , ATTRIBUTE1
      , ATTRIBUTE2
      , ATTRIBUTE3
      , ATTRIBUTE4
      , ATTRIBUTE5
      , ATTRIBUTE6
      , ATTRIBUTE7
      , ATTRIBUTE8
      , ATTRIBUTE9
      , ATTRIBUTE10
      , ATTRIBUTE11
      , ATTRIBUTE12
      , ATTRIBUTE13
      , ATTRIBUTE14
      , ATTRIBUTE15
      , DEFAULT_DEMAND_CLASS
      , ENCUMBRANCE_REVERSAL_FLAG
      , MAINTAIN_FIFO_QTY_STACK_TYPE
      , INVOICE_PRICE_VAR_ACCOUNT
      , AVERAGE_COST_VAR_ACCOUNT
      , SALES_ACCOUNT
      , EXPENSE_ACCOUNT
      , SERIAL_NUMBER_GENERATION
      , REQUEST_ID
      , PROGRAM_APPLICATION_ID
      , PROGRAM_ID
      , PROGRAM_UPDATE_DATE
      , GLOBAL_ATTRIBUTE_CATEGORY
      , GLOBAL_ATTRIBUTE1
      , GLOBAL_ATTRIBUTE2
      , GLOBAL_ATTRIBUTE3
      , GLOBAL_ATTRIBUTE4
      , GLOBAL_ATTRIBUTE5
      , GLOBAL_ATTRIBUTE6
      , GLOBAL_ATTRIBUTE7
      , GLOBAL_ATTRIBUTE8
      , GLOBAL_ATTRIBUTE9
      , GLOBAL_ATTRIBUTE10
      , GLOBAL_ATTRIBUTE11
      , GLOBAL_ATTRIBUTE12
      , GLOBAL_ATTRIBUTE13
      , GLOBAL_ATTRIBUTE14
      , GLOBAL_ATTRIBUTE15
      , GLOBAL_ATTRIBUTE16
      , GLOBAL_ATTRIBUTE17
      , GLOBAL_ATTRIBUTE18
      , GLOBAL_ATTRIBUTE19
      , GLOBAL_ATTRIBUTE20
      , MAT_OVHD_COST_TYPE_ID
      , PROJECT_REFERENCE_ENABLED
      , PM_COST_COLLECTION_ENABLED
      , PROJECT_CONTROL_LEVEL
      , AVG_RATES_COST_TYPE_ID
      , TXN_APPROVAL_TIMEOUT_PERIOD
      , MO_SOURCE_REQUIRED
      , MO_PICK_CONFIRM_REQUIRED
      , MO_APPROVAL_TIMEOUT_ACTION
      , BORRPAY_MATL_VAR_ACCOUNT
      , BORRPAY_MOH_VAR_ACCOUNT
      , BORRPAY_RES_VAR_ACCOUNT
      , BORRPAY_OSP_VAR_ACCOUNT
      , BORRPAY_OVH_VAR_ACCOUNT
      , PROCESS_ENABLED_FLAG
      , PROCESS_ORGN_CODE
      , WSM_ENABLED_FLAG
      , DEFAULT_COST_GROUP_ID
      , LPN_PREFIX
      , LPN_SUFFIX
      , LPN_STARTING_NUMBER
      , WMS_ENABLED_FLAG
      , PREGEN_PUTAWAY_TASKS_FLAG
      , REGENERATION_INTERVAL
      , TIMEZONE_ID
      , MAX_PICKS_BATCH
      , DEFAULT_WMS_PICKING_RULE_ID
      , DEFAULT_PUT_AWAY_RULE_ID
      , DEFAULT_TASK_ASSIGN_RULE_ID
      , DEFAULT_LABEL_COMP_RULE_ID
      , DEFAULT_CARTON_RULE_ID
      , DEFAULT_CYC_COUNT_HEADER_ID
      , CROSSDOCK_FLAG
      , CARTONIZATION_FLAG
      , COST_CUTOFF_DATE
      , ENABLE_COSTING_BY_CATEGORY
      , COST_GROUP_ACCOUNTING
      , ALLOCATE_SERIAL_FLAG
      , DEFAULT_PICK_TASK_TYPE_ID
      , DEFAULT_CC_TASK_TYPE_ID
      , DEFAULT_PUTAWAY_TASK_TYPE_ID
      , DEFAULT_REPL_TASK_TYPE_ID
      , EAM_ENABLED_FLAG
      , MAINT_ORGANIZATION_ID
      , PRIORITIZE_WIP_JOBS
      , DEFAULT_CROSSDOCK_SUBINVENTORY
      , SKIP_TASK_WAITING_MINUTES
      , QA_SKIPPING_INSP_FLAG
      , DEFAULT_CROSSDOCK_LOCATOR_ID
      , DEFAULT_MOXFER_TASK_TYPE_ID
      , DEFAULT_MOISSUE_TASK_TYPE_ID
      , DEFAULT_MATL_OVHD_COST_ID
      , DISTRIBUTED_ORGANIZATION_FLAG
      , CARRIER_MANIFESTING_FLAG
      , DISTRIBUTION_ACCOUNT_ID
      , DIRECT_SHIPPING_ALLOWED
      , DEFAULT_PICK_OP_PLAN_ID
      , MAX_CLUSTERS_ALLOWED
      , CONSIGNED_FLAG
      , CARTONIZE_SALES_ORDERS
      , CARTONIZE_MANUFACTURING
      , DEFER_LOGICAL_TRANSACTIONS
      , WIP_OVERPICK_ENABLED
      , OVPK_TRANSFER_ORDERS_ENABLED
      , TOTAL_LPN_LENGTH
      , UCC_128_SUFFIX_FLAG
      , WCS_ENABLED
      , AUTO_DEL_ALLOC_FLAG
      , RFID_VERIF_PCNT_THRESHOLD
      , OPSM_ENABLED_FLAG
      , ALLOW_DIFFERENT_STATUS
      , CHILD_LOT_ALPHA_PREFIX
      , CHILD_LOT_NUMBER_LENGTH
      , CHILD_LOT_VALIDATION_FLAG
      , CHILD_LOT_ZERO_PADDING_FLAG
      , COPY_LOT_ATTRIBUTE_FLAG
      , CREATE_LOT_UOM_CONVERSION
      , GENEALOGY_FORMULA_SECURITY
      , PARENT_CHILD_GENERATION_FLAG
      , RULES_OVERRIDE_LOT_RESERVATION
      , YARD_MANAGEMENT_ENABLED_FLAG
      , TRADING_PARTNER_ORG_FLAG
      , DEFERRED_COGS_ACCOUNT
      , DEFAULT_CROSSDOCK_CRITERIA_ID
      , ENFORCE_LOCATOR_ALIS_UNQ_FLAG
      , EPC_GENERATION_ENABLED_FLAG
      , COMPANY_PREFIX
      , COMPANY_PREFIX_INDEX
      , COMMERCIAL_GOVT_ENTITY_NUMBER
      , LABOR_MANAGEMENT_ENABLED_FLAG
      , DEFAULT_STATUS_ID
      , LCM_ENABLED_FLAG
      , LCM_VAR_ACCOUNT
      , ALLOCATE_LOT_FLAG
      , CAT_WT_ACCOUNT
      , YARD_ORG_ID
      , YMS_COSTING_ENABLED
      , YMS_DEFAULT_SUBINV
      , YMS_DEFAULT_LOCATOR
      , DAILY_CAL_START_TIME
      , DAILY_CAL_END_TIME
      , TRADING_PARTNER_ORG_TYPE
      , DISPATCH_INBOUND_TASK
      , ENABLE_EKANBAN
      , PICK_VERIFY_SO_ENABLED
      , PICK_VERIFY_MO_ENABLED
      , PICK_VERIFY_CATEGORY_SET_ID
      , PICK_VERIFY_WT_TOLERANCE_POS
      , PICK_VERIFY_WT_TOLERANCE_NEG
      , CC_WORKFLOW_ENABLED_FLAG
      , CC_APPROVAL_TIMEOUT_PERIOD
      , CC_APPROVAL_TIMEOUT_ACTION
      , _FIVETRAN_DELETED
      , _FIVETRAN_ID
      , _FIVETRAN_SYNCED
      , PSA_DELETE_IND
      , PSA_LOAD_DTS
      , PSA_RECORD_SOURCE
      , LOAD_DTS
      , REC_SRC
      , BKCC
      , HASHDIFF
    FROM LOGIC_SEMTK
)
---- FILTER LAYER ----

, FILTER_SEMTK as (
    SELECT *
    FROM RENAME_SEMTK
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM FILTER_SEMTK
)

---- FINAL LAYER ----
SELECT
          PLANT_HK
        , ORGANIZATION_CODE
        , ORGANIZATION_ID
        , LAST_UPDATE_DATE
        , LAST_UPDATED_BY
        , CREATION_DATE
        , CREATED_BY
        , LAST_UPDATE_LOGIN
        , MASTER_ORGANIZATION_ID
        , PRIMARY_COST_METHOD
        , COST_ORGANIZATION_ID
        , DEFAULT_MATERIAL_COST_ID
        , CALENDAR_EXCEPTION_SET_ID
        , CALENDAR_CODE
        , GENERAL_LEDGER_UPDATE_CODE
        , DEFAULT_ATP_RULE_ID
        , DEFAULT_PICKING_RULE_ID
        , DEFAULT_LOCATOR_ORDER_VALUE
        , DEFAULT_SUBINV_ORDER_VALUE
        , NEGATIVE_INV_RECEIPT_CODE
        , STOCK_LOCATOR_CONTROL_CODE
        , MATERIAL_ACCOUNT
        , MATERIAL_OVERHEAD_ACCOUNT
        , MATL_OVHD_ABSORPTION_ACCT
        , RESOURCE_ACCOUNT
        , PURCHASE_PRICE_VAR_ACCOUNT
        , AP_ACCRUAL_ACCOUNT
        , OVERHEAD_ACCOUNT
        , OUTSIDE_PROCESSING_ACCOUNT
        , INTRANSIT_INV_ACCOUNT
        , INTERORG_RECEIVABLES_ACCOUNT
        , INTERORG_PRICE_VAR_ACCOUNT
        , INTERORG_PAYABLES_ACCOUNT
        , COST_OF_SALES_ACCOUNT
        , ENCUMBRANCE_ACCOUNT
        , PROJECT_COST_ACCOUNT
        , INTERORG_TRANSFER_CR_ACCOUNT
        , MATL_INTERORG_TRANSFER_CODE
        , INTERORG_TRNSFR_CHARGE_PERCENT
        , SOURCE_ORGANIZATION_ID
        , SOURCE_SUBINVENTORY
        , SOURCE_TYPE
        , ORG_MAX_WEIGHT
        , ORG_MAX_WEIGHT_UOM_CODE
        , ORG_MAX_VOLUME
        , ORG_MAX_VOLUME_UOM_CODE
        , SERIAL_NUMBER_TYPE
        , AUTO_SERIAL_ALPHA_PREFIX
        , START_AUTO_SERIAL_NUMBER
        , AUTO_LOT_ALPHA_PREFIX
        , LOT_NUMBER_UNIQUENESS
        , LOT_NUMBER_GENERATION
        , LOT_NUMBER_ZERO_PADDING
        , LOT_NUMBER_LENGTH
        , STARTING_REVISION
        , ATTRIBUTE_CATEGORY
        , ATTRIBUTE1
        , ATTRIBUTE2
        , ATTRIBUTE3
        , ATTRIBUTE4
        , ATTRIBUTE5
        , ATTRIBUTE6
        , ATTRIBUTE7
        , ATTRIBUTE8
        , ATTRIBUTE9
        , ATTRIBUTE10
        , ATTRIBUTE11
        , ATTRIBUTE12
        , ATTRIBUTE13
        , ATTRIBUTE14
        , ATTRIBUTE15
        , DEFAULT_DEMAND_CLASS
        , ENCUMBRANCE_REVERSAL_FLAG
        , MAINTAIN_FIFO_QTY_STACK_TYPE
        , INVOICE_PRICE_VAR_ACCOUNT
        , AVERAGE_COST_VAR_ACCOUNT
        , SALES_ACCOUNT
        , EXPENSE_ACCOUNT
        , SERIAL_NUMBER_GENERATION
        , REQUEST_ID
        , PROGRAM_APPLICATION_ID
        , PROGRAM_ID
        , PROGRAM_UPDATE_DATE
        , GLOBAL_ATTRIBUTE_CATEGORY
        , GLOBAL_ATTRIBUTE1
        , GLOBAL_ATTRIBUTE2
        , GLOBAL_ATTRIBUTE3
        , GLOBAL_ATTRIBUTE4
        , GLOBAL_ATTRIBUTE5
        , GLOBAL_ATTRIBUTE6
        , GLOBAL_ATTRIBUTE7
        , GLOBAL_ATTRIBUTE8
        , GLOBAL_ATTRIBUTE9
        , GLOBAL_ATTRIBUTE10
        , GLOBAL_ATTRIBUTE11
        , GLOBAL_ATTRIBUTE12
        , GLOBAL_ATTRIBUTE13
        , GLOBAL_ATTRIBUTE14
        , GLOBAL_ATTRIBUTE15
        , GLOBAL_ATTRIBUTE16
        , GLOBAL_ATTRIBUTE17
        , GLOBAL_ATTRIBUTE18
        , GLOBAL_ATTRIBUTE19
        , GLOBAL_ATTRIBUTE20
        , MAT_OVHD_COST_TYPE_ID
        , PROJECT_REFERENCE_ENABLED
        , PM_COST_COLLECTION_ENABLED
        , PROJECT_CONTROL_LEVEL
        , AVG_RATES_COST_TYPE_ID
        , TXN_APPROVAL_TIMEOUT_PERIOD
        , MO_SOURCE_REQUIRED
        , MO_PICK_CONFIRM_REQUIRED
        , MO_APPROVAL_TIMEOUT_ACTION
        , BORRPAY_MATL_VAR_ACCOUNT
        , BORRPAY_MOH_VAR_ACCOUNT
        , BORRPAY_RES_VAR_ACCOUNT
        , BORRPAY_OSP_VAR_ACCOUNT
        , BORRPAY_OVH_VAR_ACCOUNT
        , PROCESS_ENABLED_FLAG
        , PROCESS_ORGN_CODE
        , WSM_ENABLED_FLAG
        , DEFAULT_COST_GROUP_ID
        , LPN_PREFIX
        , LPN_SUFFIX
        , LPN_STARTING_NUMBER
        , WMS_ENABLED_FLAG
        , PREGEN_PUTAWAY_TASKS_FLAG
        , REGENERATION_INTERVAL
        , TIMEZONE_ID
        , MAX_PICKS_BATCH
        , DEFAULT_WMS_PICKING_RULE_ID
        , DEFAULT_PUT_AWAY_RULE_ID
        , DEFAULT_TASK_ASSIGN_RULE_ID
        , DEFAULT_LABEL_COMP_RULE_ID
        , DEFAULT_CARTON_RULE_ID
        , DEFAULT_CYC_COUNT_HEADER_ID
        , CROSSDOCK_FLAG
        , CARTONIZATION_FLAG
        , COST_CUTOFF_DATE
        , ENABLE_COSTING_BY_CATEGORY
        , COST_GROUP_ACCOUNTING
        , ALLOCATE_SERIAL_FLAG
        , DEFAULT_PICK_TASK_TYPE_ID
        , DEFAULT_CC_TASK_TYPE_ID
        , DEFAULT_PUTAWAY_TASK_TYPE_ID
        , DEFAULT_REPL_TASK_TYPE_ID
        , EAM_ENABLED_FLAG
        , MAINT_ORGANIZATION_ID
        , PRIORITIZE_WIP_JOBS
        , DEFAULT_CROSSDOCK_SUBINVENTORY
        , SKIP_TASK_WAITING_MINUTES
        , QA_SKIPPING_INSP_FLAG
        , DEFAULT_CROSSDOCK_LOCATOR_ID
        , DEFAULT_MOXFER_TASK_TYPE_ID
        , DEFAULT_MOISSUE_TASK_TYPE_ID
        , DEFAULT_MATL_OVHD_COST_ID
        , DISTRIBUTED_ORGANIZATION_FLAG
        , CARRIER_MANIFESTING_FLAG
        , DISTRIBUTION_ACCOUNT_ID
        , DIRECT_SHIPPING_ALLOWED
        , DEFAULT_PICK_OP_PLAN_ID
        , MAX_CLUSTERS_ALLOWED
        , CONSIGNED_FLAG
        , CARTONIZE_SALES_ORDERS
        , CARTONIZE_MANUFACTURING
        , DEFER_LOGICAL_TRANSACTIONS
        , WIP_OVERPICK_ENABLED
        , OVPK_TRANSFER_ORDERS_ENABLED
        , TOTAL_LPN_LENGTH
        , UCC_128_SUFFIX_FLAG
        , WCS_ENABLED
        , AUTO_DEL_ALLOC_FLAG
        , RFID_VERIF_PCNT_THRESHOLD
        , OPSM_ENABLED_FLAG
        , ALLOW_DIFFERENT_STATUS
        , CHILD_LOT_ALPHA_PREFIX
        , CHILD_LOT_NUMBER_LENGTH
        , CHILD_LOT_VALIDATION_FLAG
        , CHILD_LOT_ZERO_PADDING_FLAG
        , COPY_LOT_ATTRIBUTE_FLAG
        , CREATE_LOT_UOM_CONVERSION
        , GENEALOGY_FORMULA_SECURITY
        , PARENT_CHILD_GENERATION_FLAG
        , RULES_OVERRIDE_LOT_RESERVATION
        , YARD_MANAGEMENT_ENABLED_FLAG
        , TRADING_PARTNER_ORG_FLAG
        , DEFERRED_COGS_ACCOUNT
        , DEFAULT_CROSSDOCK_CRITERIA_ID
        , ENFORCE_LOCATOR_ALIS_UNQ_FLAG
        , EPC_GENERATION_ENABLED_FLAG
        , COMPANY_PREFIX
        , COMPANY_PREFIX_INDEX
        , COMMERCIAL_GOVT_ENTITY_NUMBER
        , LABOR_MANAGEMENT_ENABLED_FLAG
        , DEFAULT_STATUS_ID
        , LCM_ENABLED_FLAG
        , LCM_VAR_ACCOUNT
        , ALLOCATE_LOT_FLAG
        , CAT_WT_ACCOUNT
        , YARD_ORG_ID
        , YMS_COSTING_ENABLED
        , YMS_DEFAULT_SUBINV
        , YMS_DEFAULT_LOCATOR
        , DAILY_CAL_START_TIME
        , DAILY_CAL_END_TIME
        , TRADING_PARTNER_ORG_TYPE
        , DISPATCH_INBOUND_TASK
        , ENABLE_EKANBAN
        , PICK_VERIFY_SO_ENABLED
        , PICK_VERIFY_MO_ENABLED
        , PICK_VERIFY_CATEGORY_SET_ID
        , PICK_VERIFY_WT_TOLERANCE_POS
        , PICK_VERIFY_WT_TOLERANCE_NEG
        , CC_WORKFLOW_ENABLED_FLAG
        , CC_APPROVAL_TIMEOUT_PERIOD
        , CC_APPROVAL_TIMEOUT_ACTION
        , _FIVETRAN_DELETED
        , _FIVETRAN_ID
        , _FIVETRAN_SYNCED
        , PSA_DELETE_IND
        , PSA_LOAD_DTS
        , PSA_RECORD_SOURCE
        , LOAD_DTS
        , REC_SRC
        , BKCC
        , HASHDIFF
FROM JOIN_RESULT
{% if is_incremental() %}
WHERE NOT EXISTS (
    SELECT 1 
    FROM {{ this }} existing
    WHERE existing.PLANT_HK = JOIN_RESULT.PLANT_HK 
    AND existing.HASHDIFF = JOIN_RESULT.HASHDIFF
)
{% endif %}
{% if not is_incremental() %}

/* The following qualifier is implemented to prevent multiple loads of touched records during the initial build, such as multiple rows per HK and hashdiff. */
qualify 1 = row_number() over (partition by PLANT_HK, HASHDIFF order by PSA_LOAD_DTS)

union all
SELECT 
MD5_BINARY(GR.VALUE) AS PLANT_HK,
GR.VALUE::text AS ORGANIZATION_CODE,
GR.VALUE::number AS ORGANIZATION_ID,
NULL AS LAST_UPDATE_DATE,
NULL AS LAST_UPDATED_BY,
NULL AS CREATION_DATE,
NULL AS CREATED_BY,
NULL AS LAST_UPDATE_LOGIN,
NULL AS MASTER_ORGANIZATION_ID,
NULL AS PRIMARY_COST_METHOD,
NULL AS COST_ORGANIZATION_ID,
NULL AS DEFAULT_MATERIAL_COST_ID,
NULL AS CALENDAR_EXCEPTION_SET_ID,
NULL AS CALENDAR_CODE,
NULL AS GENERAL_LEDGER_UPDATE_CODE,
NULL AS DEFAULT_ATP_RULE_ID,
NULL AS DEFAULT_PICKING_RULE_ID,
NULL AS DEFAULT_LOCATOR_ORDER_VALUE,
NULL AS DEFAULT_SUBINV_ORDER_VALUE,
NULL AS NEGATIVE_INV_RECEIPT_CODE,
NULL AS STOCK_LOCATOR_CONTROL_CODE,
NULL AS MATERIAL_ACCOUNT,
NULL AS MATERIAL_OVERHEAD_ACCOUNT,
NULL AS MATL_OVHD_ABSORPTION_ACCT,
NULL AS RESOURCE_ACCOUNT,
NULL AS PURCHASE_PRICE_VAR_ACCOUNT,
NULL AS AP_ACCRUAL_ACCOUNT,
NULL AS OVERHEAD_ACCOUNT,
NULL AS OUTSIDE_PROCESSING_ACCOUNT,
NULL AS INTRANSIT_INV_ACCOUNT,
NULL AS INTERORG_RECEIVABLES_ACCOUNT,
NULL AS INTERORG_PRICE_VAR_ACCOUNT,
NULL AS INTERORG_PAYABLES_ACCOUNT,
NULL AS COST_OF_SALES_ACCOUNT,
NULL AS ENCUMBRANCE_ACCOUNT,
NULL AS PROJECT_COST_ACCOUNT,
NULL AS INTERORG_TRANSFER_CR_ACCOUNT,
NULL AS MATL_INTERORG_TRANSFER_CODE,
NULL AS INTERORG_TRNSFR_CHARGE_PERCENT,
NULL AS SOURCE_ORGANIZATION_ID,
NULL AS SOURCE_SUBINVENTORY,
NULL AS SOURCE_TYPE,
NULL AS ORG_MAX_WEIGHT,
NULL AS ORG_MAX_WEIGHT_UOM_CODE,
NULL AS ORG_MAX_VOLUME,
NULL AS ORG_MAX_VOLUME_UOM_CODE,
NULL AS SERIAL_NUMBER_TYPE,
NULL AS AUTO_SERIAL_ALPHA_PREFIX,
NULL AS START_AUTO_SERIAL_NUMBER,
NULL AS AUTO_LOT_ALPHA_PREFIX,
NULL AS LOT_NUMBER_UNIQUENESS,
NULL AS LOT_NUMBER_GENERATION,
NULL AS LOT_NUMBER_ZERO_PADDING,
NULL AS LOT_NUMBER_LENGTH,
NULL AS STARTING_REVISION,
NULL AS ATTRIBUTE_CATEGORY,
NULL AS ATTRIBUTE1,
NULL AS ATTRIBUTE2,
NULL AS ATTRIBUTE3,
NULL AS ATTRIBUTE4,
NULL AS ATTRIBUTE5,
NULL AS ATTRIBUTE6,
NULL AS ATTRIBUTE7,
NULL AS ATTRIBUTE8,
NULL AS ATTRIBUTE9,
NULL AS ATTRIBUTE10,
NULL AS ATTRIBUTE11,
NULL AS ATTRIBUTE12,
NULL AS ATTRIBUTE13,
NULL AS ATTRIBUTE14,
NULL AS ATTRIBUTE15,
NULL AS DEFAULT_DEMAND_CLASS,
NULL AS ENCUMBRANCE_REVERSAL_FLAG,
NULL AS MAINTAIN_FIFO_QTY_STACK_TYPE,
NULL AS INVOICE_PRICE_VAR_ACCOUNT,
NULL AS AVERAGE_COST_VAR_ACCOUNT,
NULL AS SALES_ACCOUNT,
NULL AS EXPENSE_ACCOUNT,
NULL AS SERIAL_NUMBER_GENERATION,
NULL AS REQUEST_ID,
NULL AS PROGRAM_APPLICATION_ID,
NULL AS PROGRAM_ID,
NULL AS PROGRAM_UPDATE_DATE,
NULL AS GLOBAL_ATTRIBUTE_CATEGORY,
NULL AS GLOBAL_ATTRIBUTE1,
NULL AS GLOBAL_ATTRIBUTE2,
NULL AS GLOBAL_ATTRIBUTE3,
NULL AS GLOBAL_ATTRIBUTE4,
NULL AS GLOBAL_ATTRIBUTE5,
NULL AS GLOBAL_ATTRIBUTE6,
NULL AS GLOBAL_ATTRIBUTE7,
NULL AS GLOBAL_ATTRIBUTE8,
NULL AS GLOBAL_ATTRIBUTE9,
NULL AS GLOBAL_ATTRIBUTE10,
NULL AS GLOBAL_ATTRIBUTE11,
NULL AS GLOBAL_ATTRIBUTE12,
NULL AS GLOBAL_ATTRIBUTE13,
NULL AS GLOBAL_ATTRIBUTE14,
NULL AS GLOBAL_ATTRIBUTE15,
NULL AS GLOBAL_ATTRIBUTE16,
NULL AS GLOBAL_ATTRIBUTE17,
NULL AS GLOBAL_ATTRIBUTE18,
NULL AS GLOBAL_ATTRIBUTE19,
NULL AS GLOBAL_ATTRIBUTE20,
NULL AS MAT_OVHD_COST_TYPE_ID,
NULL AS PROJECT_REFERENCE_ENABLED,
NULL AS PM_COST_COLLECTION_ENABLED,
NULL AS PROJECT_CONTROL_LEVEL,
NULL AS AVG_RATES_COST_TYPE_ID,
NULL AS TXN_APPROVAL_TIMEOUT_PERIOD,
NULL AS MO_SOURCE_REQUIRED,
NULL AS MO_PICK_CONFIRM_REQUIRED,
NULL AS MO_APPROVAL_TIMEOUT_ACTION,
NULL AS BORRPAY_MATL_VAR_ACCOUNT,
NULL AS BORRPAY_MOH_VAR_ACCOUNT,
NULL AS BORRPAY_RES_VAR_ACCOUNT,
NULL AS BORRPAY_OSP_VAR_ACCOUNT,
NULL AS BORRPAY_OVH_VAR_ACCOUNT,
NULL AS PROCESS_ENABLED_FLAG,
NULL AS PROCESS_ORGN_CODE,
NULL AS WSM_ENABLED_FLAG,
NULL AS DEFAULT_COST_GROUP_ID,
NULL AS LPN_PREFIX,
NULL AS LPN_SUFFIX,
NULL AS LPN_STARTING_NUMBER,
NULL AS WMS_ENABLED_FLAG,
NULL AS PREGEN_PUTAWAY_TASKS_FLAG,
NULL AS REGENERATION_INTERVAL,
NULL AS TIMEZONE_ID,
NULL AS MAX_PICKS_BATCH,
NULL AS DEFAULT_WMS_PICKING_RULE_ID,
NULL AS DEFAULT_PUT_AWAY_RULE_ID,
NULL AS DEFAULT_TASK_ASSIGN_RULE_ID,
NULL AS DEFAULT_LABEL_COMP_RULE_ID,
NULL AS DEFAULT_CARTON_RULE_ID,
NULL AS DEFAULT_CYC_COUNT_HEADER_ID,
NULL AS CROSSDOCK_FLAG,
NULL AS CARTONIZATION_FLAG,
NULL AS COST_CUTOFF_DATE,
NULL AS ENABLE_COSTING_BY_CATEGORY,
NULL AS COST_GROUP_ACCOUNTING,
NULL AS ALLOCATE_SERIAL_FLAG,
NULL AS DEFAULT_PICK_TASK_TYPE_ID,
NULL AS DEFAULT_CC_TASK_TYPE_ID,
NULL AS DEFAULT_PUTAWAY_TASK_TYPE_ID,
NULL AS DEFAULT_REPL_TASK_TYPE_ID,
NULL AS EAM_ENABLED_FLAG,
NULL AS MAINT_ORGANIZATION_ID,
NULL AS PRIORITIZE_WIP_JOBS,
NULL AS DEFAULT_CROSSDOCK_SUBINVENTORY,
NULL AS SKIP_TASK_WAITING_MINUTES,
NULL AS QA_SKIPPING_INSP_FLAG,
NULL AS DEFAULT_CROSSDOCK_LOCATOR_ID,
NULL AS DEFAULT_MOXFER_TASK_TYPE_ID,
NULL AS DEFAULT_MOISSUE_TASK_TYPE_ID,
NULL AS DEFAULT_MATL_OVHD_COST_ID,
NULL AS DISTRIBUTED_ORGANIZATION_FLAG,
NULL AS CARRIER_MANIFESTING_FLAG,
NULL AS DISTRIBUTION_ACCOUNT_ID,
NULL AS DIRECT_SHIPPING_ALLOWED,
NULL AS DEFAULT_PICK_OP_PLAN_ID,
NULL AS MAX_CLUSTERS_ALLOWED,
NULL AS CONSIGNED_FLAG,
NULL AS CARTONIZE_SALES_ORDERS,
NULL AS CARTONIZE_MANUFACTURING,
NULL AS DEFER_LOGICAL_TRANSACTIONS,
NULL AS WIP_OVERPICK_ENABLED,
NULL AS OVPK_TRANSFER_ORDERS_ENABLED,
NULL AS TOTAL_LPN_LENGTH,
NULL AS UCC_128_SUFFIX_FLAG,
NULL AS WCS_ENABLED,
NULL AS AUTO_DEL_ALLOC_FLAG,
NULL AS RFID_VERIF_PCNT_THRESHOLD,
NULL AS OPSM_ENABLED_FLAG,
NULL AS ALLOW_DIFFERENT_STATUS,
NULL AS CHILD_LOT_ALPHA_PREFIX,
NULL AS CHILD_LOT_NUMBER_LENGTH,
NULL AS CHILD_LOT_VALIDATION_FLAG,
NULL AS CHILD_LOT_ZERO_PADDING_FLAG,
NULL AS COPY_LOT_ATTRIBUTE_FLAG,
NULL AS CREATE_LOT_UOM_CONVERSION,
NULL AS GENEALOGY_FORMULA_SECURITY,
NULL AS PARENT_CHILD_GENERATION_FLAG,
NULL AS RULES_OVERRIDE_LOT_RESERVATION,
NULL AS YARD_MANAGEMENT_ENABLED_FLAG,
NULL AS TRADING_PARTNER_ORG_FLAG,
NULL AS DEFERRED_COGS_ACCOUNT,
NULL AS DEFAULT_CROSSDOCK_CRITERIA_ID,
NULL AS ENFORCE_LOCATOR_ALIS_UNQ_FLAG,
NULL AS EPC_GENERATION_ENABLED_FLAG,
NULL AS COMPANY_PREFIX,
NULL AS COMPANY_PREFIX_INDEX,
NULL AS COMMERCIAL_GOVT_ENTITY_NUMBER,
NULL AS LABOR_MANAGEMENT_ENABLED_FLAG,
NULL AS DEFAULT_STATUS_ID,
NULL AS LCM_ENABLED_FLAG,
NULL AS LCM_VAR_ACCOUNT,
NULL AS ALLOCATE_LOT_FLAG,
NULL AS CAT_WT_ACCOUNT,
NULL AS YARD_ORG_ID,
NULL AS YMS_COSTING_ENABLED,
NULL AS YMS_DEFAULT_SUBINV,
NULL AS YMS_DEFAULT_LOCATOR,
NULL AS DAILY_CAL_START_TIME,
NULL AS DAILY_CAL_END_TIME,
NULL AS TRADING_PARTNER_ORG_TYPE,
NULL AS DISPATCH_INBOUND_TASK,
NULL AS ENABLE_EKANBAN,
NULL AS PICK_VERIFY_SO_ENABLED,
NULL AS PICK_VERIFY_MO_ENABLED,
NULL AS PICK_VERIFY_CATEGORY_SET_ID,
NULL AS PICK_VERIFY_WT_TOLERANCE_POS,
NULL AS PICK_VERIFY_WT_TOLERANCE_NEG,
NULL AS CC_WORKFLOW_ENABLED_FLAG,
NULL AS CC_APPROVAL_TIMEOUT_PERIOD,
NULL AS CC_APPROVAL_TIMEOUT_ACTION,
NULL AS _FIVETRAN_DELETED,
NULL AS _FIVETRAN_ID,
NULL AS _FIVETRAN_SYNCED,
'N' AS PSA_DELETE_IND,
'1900-01-01'::TIMESTAMP AS PSA_LOAD_DTS,
NULL AS PSA_RECORD_SOURCE,
CONVERT_TIMEZONE('UTC','1900-01-01'::TIMESTAMP) AS LOAD_DTS,
'USAZET.SNOWFLAKE.FBIN.DERIVED' AS REC_SRC,
DECODE(GR.VALUE, 0, 'GHOST RECORD-SYSTEM', -1, 'GHOST RECORD-nullkey-required', -2, 'GHOST RECORD-nullkey-optional') AS BKCC,
''::BINARY AS HASHDIFF
FROM
TABLE(strtok_split_to_table('0|-1|-2', '|')) AS GR
{% endif %}
