---- SRC LAYER ----
WITH
SRC_STSM           as ( SELECT * FROM {{ ref('v_psa_stg_sales_inventory__tsm_lowes') }} as SRC 
                         {% if is_incremental() %}
                         WHERE SRC.LOAD_DTS > (SELECT DATEADD('HOUR', '-1', MAX(LOAD_DTS)) FROM {{this}})
                         {% endif %}  )

/*
SRC_STSM           as ( SELECT * FROM STAGING.v_psa_stg_sales_inventory__tsm_lowes )
*/
---- LOGIC LAYER ----

, LOGIC_STSM as (
    SELECT
        STORE_HK
      , ITEM_NUMBER
      , END_DATE
      , END_DATE_DT
      , _LINE
      , _FILE
      , LOAD_DTS
      , _MODIFIED
      , ITEM_NAME
      , ADVERTISING_PATCH_AREA_ID
      , DISTRICT_ID
      , DIVISION_DESC
      , GEO_ZONE_ID
      , LOCATION_DESC
      , LOCATION_TYPE_DESC
      , REGION_DESC
      , STATE_ID
      , SUPPORTING_FDC_ID
      , SUPPORTING_FDC_DESC
      , SUPPORTING_REGIONAL_DISTRIBUTION_CENTER_ID
      , SALES_UNITS_TY
      , SALES_UNITS_LY
      , INTERNET_UNITS_TY
      , INTERNET_UNITS_LY
      , AVAILABLE_INVENTORY_UNITS_TY
      , AVAILABLE_INVENTORY_UNITS_LY
      , AVAILABLE_INVENTORY_UNITS_DC_
      , AVAILABLE_INVENTORY_UNITS_RETAIL_STORES
      , INVENTORY_ON_DIRECT_ORDER_UNITS_TY
      , INVENTORY_ON_DIRECT_ORDER_UNITS_LY
      , INVENTORY_ON_DIRECT_ORDER_LY
      , INVENTORY_UNITS_IN_REQ_TY
      , INVENTORY_UNITS_IN_REQ_LY
      , INVENTORY_UNITS_ON_BILL_TY
      , INVENTORY_UNITS_ON_BILL_LY
      , AVG_INVENTORY_ON_HAND_UNITS_TY
      , AVG_INVENTORY_ON_HAND_UNITS_LY
      , AVG_INVENTORY_ON_DIRECT_ORDER_UNITS_TY
      , AVG_INVENTORY_ON_DIRECT_ORDER_UNITS_LY
      , AVG_INVENTORY_ON_REQUISITION_UNITS_TY
      , AVG_INVENTORY_ON_REQUISITION_UNITS_LY
      , WEEKS_OF_SUPPLY_ON_HAND
      , WEEKS_OF_SUPPLY_ON_ORDER
      , JDA_LOST_SALES_UNITS_TY_WEEKLY_
      , TURN_RATES_WEEKLY_
      , _FIVETRAN_SYNCED
      , TY_TURN_RATE
      , LY_TURN_RATE
      , YTD_TOTAL_SALES_
      , GROSS_TRANSACTION_SALES_UNITS_TY
      , GROSS_TRANSACTION_SALES_UNITS_LY
      , GROSS_TRANSACTION_SALES_UNITS_CHANGE
      , YTD_WEEKLY_AVERAGE_SALES_
      , INVENTORY_ON_DIRECT_ORDER_TY
      , SALES_UNITS_TY_VS_LY
      , AVG_INVENTORY_ON_DIRECT_ORDER_LY
      , INTERNET_UNITS_TY_VS_LY
      , AVG_INVENTORY_ON_HAND_LY
      , AVG_INVENTORY_ON_REQUISITION_LY
      , SALES_TY_VS_LY
      , SALES_TY
      , YTD_SALES_
      , AVG_INVENTORY_ON_HAND_TY
      , AVAILABLE_INVENTORY_LY
      , INTERNET_SALES_LY
      , AVG_INVENTORY_ON_REQUISITION_TY
      , YTD_TY_VS_LY
      , SALES_LY
      , LYTD_SALES_
      , INTERNET_SALES_TY_VS_LY
      , AVAILABLE_INVENTORY_TY
      , INTERNET_SALES_TY
      , GROSS_TRANSACTIONS_SALES_
      , AVG_INVENTORY_ON_DIRECT_ORDER_TY
      , LYTD_UNITS
      , YTD_UNITS
      , AVAILABLE_INVENTORY_UNITS_N_RETAIL_STORES
      , YTD_WEEKLY_AVERAGE_UNITS
      , START_DATE
      , PSA_LOAD_DTS
      , PSA_RECORD_SOURCE
      , REC_SRC
      , BKCC
      , HASHDIFF
    FROM SRC_STSM
)
---- RENAME LAYER ----

, RENAME_STSM as (
    SELECT
        STORE_HK
      , ITEM_NUMBER
      , END_DATE
      , END_DATE_DT
      , _LINE
      , _FILE
      , LOAD_DTS
      , _MODIFIED
      , ITEM_NAME
      , ADVERTISING_PATCH_AREA_ID
      , DISTRICT_ID
      , DIVISION_DESC
      , GEO_ZONE_ID
      , LOCATION_DESC
      , LOCATION_TYPE_DESC
      , REGION_DESC
      , STATE_ID
      , SUPPORTING_FDC_ID
      , SUPPORTING_FDC_DESC
      , SUPPORTING_REGIONAL_DISTRIBUTION_CENTER_ID
      , SALES_UNITS_TY
      , SALES_UNITS_LY
      , INTERNET_UNITS_TY
      , INTERNET_UNITS_LY
      , AVAILABLE_INVENTORY_UNITS_TY
      , AVAILABLE_INVENTORY_UNITS_LY
      , AVAILABLE_INVENTORY_UNITS_DC_
      , AVAILABLE_INVENTORY_UNITS_RETAIL_STORES
      , INVENTORY_ON_DIRECT_ORDER_UNITS_TY
      , INVENTORY_ON_DIRECT_ORDER_UNITS_LY
      , INVENTORY_ON_DIRECT_ORDER_LY
      , INVENTORY_UNITS_IN_REQ_TY
      , INVENTORY_UNITS_IN_REQ_LY
      , INVENTORY_UNITS_ON_BILL_TY
      , INVENTORY_UNITS_ON_BILL_LY
      , AVG_INVENTORY_ON_HAND_UNITS_TY
      , AVG_INVENTORY_ON_HAND_UNITS_LY
      , AVG_INVENTORY_ON_DIRECT_ORDER_UNITS_TY
      , AVG_INVENTORY_ON_DIRECT_ORDER_UNITS_LY
      , AVG_INVENTORY_ON_REQUISITION_UNITS_TY
      , AVG_INVENTORY_ON_REQUISITION_UNITS_LY
      , WEEKS_OF_SUPPLY_ON_HAND
      , WEEKS_OF_SUPPLY_ON_ORDER
      , JDA_LOST_SALES_UNITS_TY_WEEKLY_
      , TURN_RATES_WEEKLY_
      , _FIVETRAN_SYNCED
      , TY_TURN_RATE
      , LY_TURN_RATE
      , YTD_TOTAL_SALES_
      , GROSS_TRANSACTION_SALES_UNITS_TY
      , GROSS_TRANSACTION_SALES_UNITS_LY
      , GROSS_TRANSACTION_SALES_UNITS_CHANGE
      , YTD_WEEKLY_AVERAGE_SALES_
      , INVENTORY_ON_DIRECT_ORDER_TY
      , SALES_UNITS_TY_VS_LY
      , AVG_INVENTORY_ON_DIRECT_ORDER_LY
      , INTERNET_UNITS_TY_VS_LY
      , AVG_INVENTORY_ON_HAND_LY
      , AVG_INVENTORY_ON_REQUISITION_LY
      , SALES_TY_VS_LY
      , SALES_TY
      , YTD_SALES_
      , AVG_INVENTORY_ON_HAND_TY
      , AVAILABLE_INVENTORY_LY
      , INTERNET_SALES_LY
      , AVG_INVENTORY_ON_REQUISITION_TY
      , YTD_TY_VS_LY
      , SALES_LY
      , LYTD_SALES_
      , INTERNET_SALES_TY_VS_LY
      , AVAILABLE_INVENTORY_TY
      , INTERNET_SALES_TY
      , GROSS_TRANSACTIONS_SALES_
      , AVG_INVENTORY_ON_DIRECT_ORDER_TY
      , LYTD_UNITS
      , YTD_UNITS
      , AVAILABLE_INVENTORY_UNITS_N_RETAIL_STORES
      , YTD_WEEKLY_AVERAGE_UNITS
      , START_DATE
      , PSA_LOAD_DTS
      , PSA_RECORD_SOURCE
      , REC_SRC
      , BKCC
      , HASHDIFF
    FROM LOGIC_STSM
)
---- FILTER LAYER ----

, FILTER_STSM as (
    SELECT *
    FROM RENAME_STSM
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM FILTER_STSM
)

---- FINAL LAYER ----
SELECT
          STORE_HK
        , ITEM_NUMBER
        , END_DATE
        , END_DATE_DT
        , _LINE
        , _FILE
        , LOAD_DTS
        , _MODIFIED
        , ITEM_NAME
        , ADVERTISING_PATCH_AREA_ID
        , DISTRICT_ID
        , DIVISION_DESC
        , GEO_ZONE_ID
        , LOCATION_DESC
        , LOCATION_TYPE_DESC
        , REGION_DESC
        , STATE_ID
        , SUPPORTING_FDC_ID
        , SUPPORTING_FDC_DESC
        , SUPPORTING_REGIONAL_DISTRIBUTION_CENTER_ID
        , SALES_UNITS_TY
        , SALES_UNITS_LY
        , INTERNET_UNITS_TY
        , INTERNET_UNITS_LY
        , AVAILABLE_INVENTORY_UNITS_TY
        , AVAILABLE_INVENTORY_UNITS_LY
        , AVAILABLE_INVENTORY_UNITS_DC_
        , AVAILABLE_INVENTORY_UNITS_RETAIL_STORES
        , INVENTORY_ON_DIRECT_ORDER_UNITS_TY
        , INVENTORY_ON_DIRECT_ORDER_UNITS_LY
        , INVENTORY_ON_DIRECT_ORDER_LY
        , INVENTORY_UNITS_IN_REQ_TY
        , INVENTORY_UNITS_IN_REQ_LY
        , INVENTORY_UNITS_ON_BILL_TY
        , INVENTORY_UNITS_ON_BILL_LY
        , AVG_INVENTORY_ON_HAND_UNITS_TY
        , AVG_INVENTORY_ON_HAND_UNITS_LY
        , AVG_INVENTORY_ON_DIRECT_ORDER_UNITS_TY
        , AVG_INVENTORY_ON_DIRECT_ORDER_UNITS_LY
        , AVG_INVENTORY_ON_REQUISITION_UNITS_TY
        , AVG_INVENTORY_ON_REQUISITION_UNITS_LY
        , WEEKS_OF_SUPPLY_ON_HAND
        , WEEKS_OF_SUPPLY_ON_ORDER
        , JDA_LOST_SALES_UNITS_TY_WEEKLY_
        , TURN_RATES_WEEKLY_
        , _FIVETRAN_SYNCED
        , TY_TURN_RATE
        , LY_TURN_RATE
        , YTD_TOTAL_SALES_
        , GROSS_TRANSACTION_SALES_UNITS_TY
        , GROSS_TRANSACTION_SALES_UNITS_LY
        , GROSS_TRANSACTION_SALES_UNITS_CHANGE
        , YTD_WEEKLY_AVERAGE_SALES_
        , INVENTORY_ON_DIRECT_ORDER_TY
        , SALES_UNITS_TY_VS_LY
        , AVG_INVENTORY_ON_DIRECT_ORDER_LY
        , INTERNET_UNITS_TY_VS_LY
        , AVG_INVENTORY_ON_HAND_LY
        , AVG_INVENTORY_ON_REQUISITION_LY
        , SALES_TY_VS_LY
        , SALES_TY
        , YTD_SALES_
        , AVG_INVENTORY_ON_HAND_TY
        , AVAILABLE_INVENTORY_LY
        , INTERNET_SALES_LY
        , AVG_INVENTORY_ON_REQUISITION_TY
        , YTD_TY_VS_LY
        , SALES_LY
        , LYTD_SALES_
        , INTERNET_SALES_TY_VS_LY
        , AVAILABLE_INVENTORY_TY
        , INTERNET_SALES_TY
        , GROSS_TRANSACTIONS_SALES_
        , AVG_INVENTORY_ON_DIRECT_ORDER_TY
        , LYTD_UNITS
        , YTD_UNITS
        , AVAILABLE_INVENTORY_UNITS_N_RETAIL_STORES
        , YTD_WEEKLY_AVERAGE_UNITS
        , START_DATE
        , PSA_LOAD_DTS
        , PSA_RECORD_SOURCE
        , REC_SRC
        , BKCC
        , HASHDIFF
FROM JOIN_RESULT
{% if is_incremental() %}
WHERE NOT EXISTS (
    SELECT 1 
    FROM {{ this }} existing
    WHERE existing.STORE_HK = JOIN_RESULT.STORE_HK 
	AND existing.ITEM_NUMBER = JOIN_RESULT.ITEM_NUMBER 
	AND existing.END_DATE = JOIN_RESULT.END_DATE 
                AND existing._FILE = JOIN_RESULT._FILE
	AND existing._LINE = JOIN_RESULT._LINE
    AND existing.HASHDIFF = JOIN_RESULT.HASHDIFF	
)
{% endif %}
 
{% if not is_incremental() %}
qualify 1=row_number() over(partition by store_hk,item_number,end_date,_file,_LINE,hashdiff order by psa_load_dts)
union all
SELECT MD5_BINARY(GR.VALUE::varchar) AS STORE_HK
, GR.VALUE::varchar as ITEM_NUMBER
, '1900-01-01' as END_DATE
, null as END_DATE_DT
, GR.VALUE::varchar as _LINE
, GR.VALUE::varchar as _FILE
, CONVERT_TIMEZONE('UTC','1900-01-01'::TIMESTAMP) as LOAD_DTS
, null as _MODIFIED
, null as ITEM_NAME
, null as ADVERTISING_PATCH_AREA_ID
, null as DISTRICT_ID
, null as DIVISION_DESC
, null as GEO_ZONE_ID
, null as LOCATION_DESC
, null as LOCATION_TYPE_DESC
, null as REGION_DESC
, null as STATE_ID
, null as SUPPORTING_FDC_ID
, null as SUPPORTING_FDC_DESC
, null as SUPPORTING_REGIONAL_DISTRIBUTION_CENTER_ID
, null as SALES_UNITS_TY
, null as SALES_UNITS_LY
, null as INTERNET_UNITS_TY
, null as INTERNET_UNITS_LY
, null as AVAILABLE_INVENTORY_UNITS_TY
, null as AVAILABLE_INVENTORY_UNITS_LY
, null as AVAILABLE_INVENTORY_UNITS_DC_
, null as AVAILABLE_INVENTORY_UNITS_RETAIL_STORES
, null as INVENTORY_ON_DIRECT_ORDER_UNITS_TY
, null as INVENTORY_ON_DIRECT_ORDER_UNITS_LY
, null as INVENTORY_ON_DIRECT_ORDER_LY
, null as INVENTORY_UNITS_IN_REQ_TY
, null as INVENTORY_UNITS_IN_REQ_LY
, null as INVENTORY_UNITS_ON_BILL_TY
, null as INVENTORY_UNITS_ON_BILL_LY
, null as AVG_INVENTORY_ON_HAND_UNITS_TY
, null as AVG_INVENTORY_ON_HAND_UNITS_LY
, null as AVG_INVENTORY_ON_DIRECT_ORDER_UNITS_TY
, null as AVG_INVENTORY_ON_DIRECT_ORDER_UNITS_LY
, null as AVG_INVENTORY_ON_REQUISITION_UNITS_TY
, null as AVG_INVENTORY_ON_REQUISITION_UNITS_LY
, null as WEEKS_OF_SUPPLY_ON_HAND
, null as WEEKS_OF_SUPPLY_ON_ORDER
, null as JDA_LOST_SALES_UNITS_TY_WEEKLY_
, null as TURN_RATES_WEEKLY_
, null as _FIVETRAN_SYNCED
, null as TY_TURN_RATE
, null as LY_TURN_RATE
, null as YTD_TOTAL_SALES_
, null as GROSS_TRANSACTION_SALES_UNITS_TY
, null as GROSS_TRANSACTION_SALES_UNITS_LY
, null as GROSS_TRANSACTION_SALES_UNITS_CHANGE
, null as YTD_WEEKLY_AVERAGE_SALES_
, null as INVENTORY_ON_DIRECT_ORDER_TY
, null as SALES_UNITS_TY_VS_LY
, null as AVG_INVENTORY_ON_DIRECT_ORDER_LY
, null as INTERNET_UNITS_TY_VS_LY
, null as AVG_INVENTORY_ON_HAND_LY
, null as AVG_INVENTORY_ON_REQUISITION_LY
, null as SALES_TY_VS_LY
, null as SALES_TY
, null as YTD_SALES_
, null as AVG_INVENTORY_ON_HAND_TY
, null as AVAILABLE_INVENTORY_LY
, null as INTERNET_SALES_LY
, null as AVG_INVENTORY_ON_REQUISITION_TY
, null as YTD_TY_VS_LY
, null as SALES_LY
, null as LYTD_SALES_
, null as INTERNET_SALES_TY_VS_LY
, null as AVAILABLE_INVENTORY_TY
, null as INTERNET_SALES_TY
, null as GROSS_TRANSACTIONS_SALES_
, null as AVG_INVENTORY_ON_DIRECT_ORDER_TY
, null as LYTD_UNITS
, null as YTD_UNITS
, null as AVAILABLE_INVENTORY_UNITS_N_RETAIL_STORES
, null as YTD_WEEKLY_AVERAGE_UNITS
, null as START_DATE
, null as PSA_LOAD_DTS
, null as PSA_RECORD_SOURCE
, 'USAZET.SNOWFLAKE.FBIN.DERIVED' AS REC_SRC
, DECODE(GR.VALUE::varchar, 0, 'GHOST RECORD-SYSTEM', -1, 'GHOST RECORD-nullkey-required', -2, 'GHOST RECORD-nullkey-optional')  AS  BKCC
        , ''::BINARY as HASH_DIFF
        FROM
        TABLE(strtok_split_to_table('0|-1|-2', '|')) AS GR
{% endif %}