---- SRC LAYER ----
WITH
SRC_a              as ( SELECT * FROM {{ ref('v_psa_stg_po_item__fib_ocf') }} as SRC 
                         {% if is_incremental() %}
                              where src.load_dts > (select dateadd('HOUR',-1,max(load_dts)) from {{ this }})
                            {% endif %}   )

/*
SRC_a              as ( SELECT * FROM staging.v_psa_stg_po_item__fib_ocf )
*/
---- LOGIC LAYER ----

, LOGIC_a as (
    SELECT
        PO_ITEM_HK
      , PO_HEADER_ID
      , LINE_NUM
      , PO_LINE_ID
      , CREATION_DATE
      , SOLDTO_BU_ID
      , SH_ATTRIBUTE_8
      , ATTRIBUTE_10
      , ATTRIBUTE_13
      , SH_ATTRIBUTE_NUMBER_4
      , GLOBAL_ATTRIBUTE_7
      , SVC_COMPLETION_NOTIF_SENT
      , ATTRIBUTE_20
      , TAX_NAME
      , SH_ATTRIBUTE_DATE_6
      , NOTE_TO_VENDOR
      , SHIPPING_UOM_QUANTITY
      , ATTRIBUTE_4
      , SH_ATTRIBUTE_7
      , SH_ATTRIBUTE_13
      , COMPONENT_AMOUNT_RELEASED
      , GLOBAL_ATTRIBUTE_10
      , CONFIGURED_ITEM_FLAG
      , ATTRIBUTE_DATE_6
      , CREDIT_FLAG
      , MANUFACTURER
      , AGING_PERIOD_DAYS
      , FUNDS_STATUS
      , SH_ATTRIBUTE_TIMESTAMP_3
      , ATTRIBUTE_NUMBER_7
      , SH_ATTRIBUTE_NUMBER_2
      , ATTRIBUTE_NUMBER_4
      , GLOBAL_ATTRIBUTE_19
      , PARENT_ITEM_ID
      , SH_ATTRIBUTE_CATEGORY
      , OBJECT_VERSION_NUMBER
      , SH_ATTRIBUTE_TIMESTAMP_1
      , ATTRIBUTE_12
      , GLOBAL_ATTRIBUTE_13
      , SH_ATTRIBUTE_TIMESTAMP_6
      , ATTRIBUTE_DATE_2
      , GLOBAL_ATTRIBUTE_15
      , PROGRAM_APP_NAME
      , COMMITTED_AMOUNT
      , ATTRIBUTE_DATE_10
      , SH_ATTRIBUTE_NUMBER_10
      , CREATED_BY
      , DISCOUNT_TYPE
      , GLOBAL_ATTRIBUTE_DATE_4
      , CANCEL_FLAG
      , OVER_TOLERANCE_ERROR_FLAG
      , ATTRIBUTE_TIMESTAMP_6
      , MARKET_PRICE
      , SH_ATTRIBUTE_TIMESTAMP_9
      , SH_ATTRIBUTE_TIMESTAMP_7
      , NOT_TO_EXCEED_PRICE
      , ATTRIBUTE_NUMBER_9
      , PJC_CONTEXT_CATEGORY
      , SH_ATTRIBUTE_20
      , QTY_RCV_TOLERANCE
      , ATTRIBUTE_NUMBER_3
      , CANCELLED_BY
      , ATTRIBUTE_TIMESTAMP_3
      , CONTRACT_ID
      , JOB_ID
      , DISCOUNT
      , SHIPPING_UOM_CODE
      , CONTRACTOR_LAST_NAME
      , SECONDARY_UOM_CODE
      , DISCOUNT_REASON
      , SH_ATTRIBUTE_NUMBER_7
      , GLOBAL_ATTRIBUTE_DATE_2
      , SH_ATTRIBUTE_2
      , ATTRIBUTE_11
      , CATALOG_NAME
      , ATTRIBUTE_17
      , SH_ATTRIBUTE_DATE_3
      , ATTRIBUTE_TIMESTAMP_8
      , LINE_REFERENCE_NUM
      , GLOBAL_ATTRIBUTE_1
      , GLOBAL_ATTRIBUTE_NUMBER_5
      , SH_ATTRIBUTE_DATE_2
      , CLOSED_REASON
      , LINE_TYPE_ID
      , JOB_DEFINITION_PACKAGE
      , PRICE_TYPE_LOOKUP_CODE
      , ATTRIBUTE_16
      , MANUFACTURER_PART_NUM
      , RECOUPMENT_RATE
      , GLOBAL_ATTRIBUTE_8
      , CANCEL_REASON
      , BID_NUMBER
      , GLOBAL_ATTRIBUTE_3
      , START_DATE
      , UN_NUMBER_ID
      , QUANTITY_COMMITTED
      , ATTRIBUTE_NUMBER_2
      , ALLOW_PRICE_OVERRIDE_FLAG
      , UNIT_PRICE
      , ATTRIBUTE_TIMESTAMP_9
      , BASE_UOM
      , FIRM_DATE
      , SH_ATTRIBUTE_NUMBER_1
      , SH_ATTRIBUTE_DATE_4
      , MIN_RELEASE_AMOUNT
      , SH_ATTRIBUTE_9
      , ATTRIBUTE_18
      , PRC_BU_ID
      , GLOBAL_ATTRIBUTE_NUMBER_3
      , ITEM_REVISION
      , SH_ATTRIBUTE_DATE_8
      , FROM_HEADER_ID
      , HAZARD_CLASS_ID
      , LIST_PRICE
      , SH_ATTRIBUTE_4
      , REQUEST_ID
      , ATTRIBUTE_2
      , AMOUNT_RELEASED
      , TAX_CODE_ID
      , BASE_MODEL_ID
      , ATTRIBUTE_DATE_4
      , TAX_ATTRIBUTE_UPDATE_CODE
      , ATTRIBUTE_TIMESTAMP_7
      , SOURCE_DOC_REV_NUM
      , RETAINAGE_RATE
      , LAST_UPDATE_DATE
      , CONTRACTOR_FIRST_NAME
      , TAX_EXCLUSIVE_PRICE
      , ATTRIBUTE_5
      , ATTRIBUTE_NUMBER_8
      , CONSIGNMENT_LINE_FLAG
      , FROM_LINE_LOCATION_ID
      , WORK_ORDER_PRODUCT
      , REQ_BU_ID
      , SH_ATTRIBUTE_11
      , ATTRIBUTE_NUMBER_5
      , ATTRIBUTE_19
      , SH_ATTRIBUTE_NUMBER_9
      , TOP_MODEL_ID
      , FIRM_STATUS_LOOKUP_CODE
      , SH_ATTRIBUTE_TIMESTAMP_10
      , SH_ATTRIBUTE_10
      , SH_ATTRIBUTE_DATE_9
      , VENDOR_PRODUCT_NUM
      , CAPITAL_EXPENSE_FLAG
      , ITEM_DESCRIPTION
      , ATTRIBUTE_7
      , RETROACTIVE_DATE
      , FROM_LINE_ID
      , SH_ATTRIBUTE_TIMESTAMP_8
      , NEXT_CONSUMPTION_ADV_GEN_DATE
      , PROGRESS_PAYMENT_RATE
      , SH_ATTRIBUTE_DATE_10
      , GLOBAL_ATTRIBUTE_6
      , ATTRIBUTE_8
      , UNORDERED_FLAG
      , SUPPLIER_PARENT_ITEM
      , SH_ATTRIBUTE_14
      , GLOBAL_ATTRIBUTE_5
      , SH_ATTRIBUTE_NUMBER_3
      , ATTRIBUTE_DATE_7
      , ATTRIBUTE_3
      , ATTRIBUTE_DATE_8
      , SH_ATTRIBUTE_19
      , SH_ATTRIBUTE_DATE_1
      , LAST_UPDATE_LOGIN
      , OKE_CONTRACT_HEADER_ID
      , SH_ATTRIBUTE_16
      , ATTRIBUTE_9
      , CANCEL_DATE
      , NEGOTIATED_BY_PREPARER_FLAG
      , ITEM_ID
      , ATTRIBUTE_DATE_3
      , LIST_PRICE_PER_UNIT
      , SECONDARY_QUANTITY
      , ATTRIBUTE_DATE_5
      , SH_ATTRIBUTE_TIMESTAMP_5
      , TYPE_1099
      , ATTRIBUTE_TIMESTAMP_1
      , GLOBAL_ATTRIBUTE_NUMBER_1
      , SH_ATTRIBUTE_15
      , GLOBAL_ATTRIBUTE_DATE_1
      , ATTRIBUTE_TIMESTAMP_5
      , ATTRIBUTE_TIMESTAMP_4
      , JOB_DEFINITION_NAME
      , SH_ATTRIBUTE_17
      , PURCHASE_BASIS
      , GLOBAL_ATTRIBUTE_18
      , GLOBAL_ATTRIBUTE_NUMBER_2
      , SH_ATTRIBUTE_18
      , SH_ATTRIBUTE_6
      , GLOBAL_ATTRIBUTE_DATE_5
      , AUCTION_DISPLAY_NUMBER
      , ATTRIBUTE_14
      , SH_ATTRIBUTE_5
      , ATTRIBUTE_6
      , SH_ATTRIBUTE_DATE_7
      , SH_ATTRIBUTE_1
      , ATTRIBUTE_NUMBER_1
      , GLOBAL_ATTRIBUTE_17
      , GLOBAL_ATTRIBUTE_2
      , OPTIONS_PRICE
      , CLOSED_DATE
      , ORDER_TYPE_LOOKUP_CODE
      , ATTRIBUTE_NUMBER_10
      , EXPIRATION_DATE
      , UOM_CODE
      , ATTRIBUTE_CATEGORY
      , SH_ATTRIBUTE_TIMESTAMP_4
      , PRICE_BREAK_LOOKUP_CODE
      , SH_ATTRIBUTE_12
      , GLOBAL_ATTRIBUTE_20
      , BID_LINE_NUMBER
      , SH_ATTRIBUTE_DATE_5
      , LINE_STATUS
      , ALLOW_DESCRIPTION_UPDATE_FLAG
      , OKE_CONTRACT_VERSION_ID
      , SH_ATTRIBUTE_NUMBER_8
      , CATEGORY_ID
      , ATTRIBUTE_15
      , BASE_QTY
      , ATTRIBUTE_TIMESTAMP_2
      , PROGRAM_NAME
      , MAX_RETAINAGE_AMOUNT
      , BASE_UNIT_PRICE
      , SH_ATTRIBUTE_NUMBER_6
      , REFERENCE_NUM
      , AUCTION_HEADER_ID
      , ATTRIBUTE_DATE_1
      , GLOBAL_ATTRIBUTE_4
      , GLOBAL_ATTRIBUTE_CATEGORY
      , ATTRIBUTE_1
      , SH_ATTRIBUTE_NUMBER_5
      , CLOSED_BY
      , GLOBAL_ATTRIBUTE_16
      , GLOBAL_ATTRIBUTE_9
      , GLOBAL_ATTRIBUTE_11
      , AUCTION_LINE_NUMBER
      , ATTRIBUTE_TIMESTAMP_10
      , GLOBAL_ATTRIBUTE_14
      , SH_ATTRIBUTE_3
      , GOVERNMENT_CONTEXT
      , SH_ATTRIBUTE_TIMESTAMP_2
      , ATTRIBUTE_NUMBER_6
      , TAXABLE_FLAG
      , MANUAL_PRICE_CHANGE_FLAG
      , GLOBAL_ATTRIBUTE_NUMBER_4
      , SVC_AMOUNT_NOTIF_SENT
      , QC_GRADE
      , SUPPLIER_PART_AUXID
      , LAST_UPDATED_PROGRAM
      , AMOUNT
      , PREFERRED_GRADE
      , GLOBAL_ATTRIBUTE_DATE_3
      , MATCHING_BASIS
      , SUPPLIER_TOP_MODEL
      , LAST_UPDATED_BY
      , GLOBAL_ATTRIBUTE_12
      , BASE_MODEL_PRICE
      , ATTRIBUTE_DATE_9
      , SUPPLIER_REF_NUMBER
      , QUANTITY
      , LINE_START_DATE
      , _FIVETRAN_DELETED
      , _FIVETRAN_SYNCED
      , PSA_DELETE_IND
      , PSA_LOAD_DTS
      , PSA_RECORD_SOURCE
      , LOAD_DTS
      , REC_SRC
      , BKCC
      , HASHDIFF
    FROM SRC_a
)
---- RENAME LAYER ----

, RENAME_a as (
    SELECT
        PO_ITEM_HK
      , PO_HEADER_ID
      , LINE_NUM
      , PO_LINE_ID
      , CREATION_DATE
      , SOLDTO_BU_ID
      , SH_ATTRIBUTE_8
      , ATTRIBUTE_10
      , ATTRIBUTE_13
      , SH_ATTRIBUTE_NUMBER_4
      , GLOBAL_ATTRIBUTE_7
      , SVC_COMPLETION_NOTIF_SENT
      , ATTRIBUTE_20
      , TAX_NAME
      , SH_ATTRIBUTE_DATE_6
      , NOTE_TO_VENDOR
      , SHIPPING_UOM_QUANTITY
      , ATTRIBUTE_4
      , SH_ATTRIBUTE_7
      , SH_ATTRIBUTE_13
      , COMPONENT_AMOUNT_RELEASED
      , GLOBAL_ATTRIBUTE_10
      , CONFIGURED_ITEM_FLAG
      , ATTRIBUTE_DATE_6
      , CREDIT_FLAG
      , MANUFACTURER
      , AGING_PERIOD_DAYS
      , FUNDS_STATUS
      , SH_ATTRIBUTE_TIMESTAMP_3
      , ATTRIBUTE_NUMBER_7
      , SH_ATTRIBUTE_NUMBER_2
      , ATTRIBUTE_NUMBER_4
      , GLOBAL_ATTRIBUTE_19
      , PARENT_ITEM_ID
      , SH_ATTRIBUTE_CATEGORY
      , OBJECT_VERSION_NUMBER
      , SH_ATTRIBUTE_TIMESTAMP_1
      , ATTRIBUTE_12
      , GLOBAL_ATTRIBUTE_13
      , SH_ATTRIBUTE_TIMESTAMP_6
      , ATTRIBUTE_DATE_2
      , GLOBAL_ATTRIBUTE_15
      , PROGRAM_APP_NAME
      , COMMITTED_AMOUNT
      , ATTRIBUTE_DATE_10
      , SH_ATTRIBUTE_NUMBER_10
      , CREATED_BY
      , DISCOUNT_TYPE
      , GLOBAL_ATTRIBUTE_DATE_4
      , CANCEL_FLAG
      , OVER_TOLERANCE_ERROR_FLAG
      , ATTRIBUTE_TIMESTAMP_6
      , MARKET_PRICE
      , SH_ATTRIBUTE_TIMESTAMP_9
      , SH_ATTRIBUTE_TIMESTAMP_7
      , NOT_TO_EXCEED_PRICE
      , ATTRIBUTE_NUMBER_9
      , PJC_CONTEXT_CATEGORY
      , SH_ATTRIBUTE_20
      , QTY_RCV_TOLERANCE
      , ATTRIBUTE_NUMBER_3
      , CANCELLED_BY
      , ATTRIBUTE_TIMESTAMP_3
      , CONTRACT_ID
      , JOB_ID
      , DISCOUNT
      , SHIPPING_UOM_CODE
      , CONTRACTOR_LAST_NAME
      , SECONDARY_UOM_CODE
      , DISCOUNT_REASON
      , SH_ATTRIBUTE_NUMBER_7
      , GLOBAL_ATTRIBUTE_DATE_2
      , SH_ATTRIBUTE_2
      , ATTRIBUTE_11
      , CATALOG_NAME
      , ATTRIBUTE_17
      , SH_ATTRIBUTE_DATE_3
      , ATTRIBUTE_TIMESTAMP_8
      , LINE_REFERENCE_NUM
      , GLOBAL_ATTRIBUTE_1
      , GLOBAL_ATTRIBUTE_NUMBER_5
      , SH_ATTRIBUTE_DATE_2
      , CLOSED_REASON
      , LINE_TYPE_ID
      , JOB_DEFINITION_PACKAGE
      , PRICE_TYPE_LOOKUP_CODE
      , ATTRIBUTE_16
      , MANUFACTURER_PART_NUM
      , RECOUPMENT_RATE
      , GLOBAL_ATTRIBUTE_8
      , CANCEL_REASON
      , BID_NUMBER
      , GLOBAL_ATTRIBUTE_3
      , START_DATE
      , UN_NUMBER_ID
      , QUANTITY_COMMITTED
      , ATTRIBUTE_NUMBER_2
      , ALLOW_PRICE_OVERRIDE_FLAG
      , UNIT_PRICE
      , ATTRIBUTE_TIMESTAMP_9
      , BASE_UOM
      , FIRM_DATE
      , SH_ATTRIBUTE_NUMBER_1
      , SH_ATTRIBUTE_DATE_4
      , MIN_RELEASE_AMOUNT
      , SH_ATTRIBUTE_9
      , ATTRIBUTE_18
      , PRC_BU_ID
      , GLOBAL_ATTRIBUTE_NUMBER_3
      , ITEM_REVISION
      , SH_ATTRIBUTE_DATE_8
      , FROM_HEADER_ID
      , HAZARD_CLASS_ID
      , LIST_PRICE
      , SH_ATTRIBUTE_4
      , REQUEST_ID
      , ATTRIBUTE_2
      , AMOUNT_RELEASED
      , TAX_CODE_ID
      , BASE_MODEL_ID
      , ATTRIBUTE_DATE_4
      , TAX_ATTRIBUTE_UPDATE_CODE
      , ATTRIBUTE_TIMESTAMP_7
      , SOURCE_DOC_REV_NUM
      , RETAINAGE_RATE
      , LAST_UPDATE_DATE
      , CONTRACTOR_FIRST_NAME
      , TAX_EXCLUSIVE_PRICE
      , ATTRIBUTE_5
      , ATTRIBUTE_NUMBER_8
      , CONSIGNMENT_LINE_FLAG
      , FROM_LINE_LOCATION_ID
      , WORK_ORDER_PRODUCT
      , REQ_BU_ID
      , SH_ATTRIBUTE_11
      , ATTRIBUTE_NUMBER_5
      , ATTRIBUTE_19
      , SH_ATTRIBUTE_NUMBER_9
      , TOP_MODEL_ID
      , FIRM_STATUS_LOOKUP_CODE
      , SH_ATTRIBUTE_TIMESTAMP_10
      , SH_ATTRIBUTE_10
      , SH_ATTRIBUTE_DATE_9
      , VENDOR_PRODUCT_NUM
      , CAPITAL_EXPENSE_FLAG
      , ITEM_DESCRIPTION
      , ATTRIBUTE_7
      , RETROACTIVE_DATE
      , FROM_LINE_ID
      , SH_ATTRIBUTE_TIMESTAMP_8
      , NEXT_CONSUMPTION_ADV_GEN_DATE
      , PROGRESS_PAYMENT_RATE
      , SH_ATTRIBUTE_DATE_10
      , GLOBAL_ATTRIBUTE_6
      , ATTRIBUTE_8
      , UNORDERED_FLAG
      , SUPPLIER_PARENT_ITEM
      , SH_ATTRIBUTE_14
      , GLOBAL_ATTRIBUTE_5
      , SH_ATTRIBUTE_NUMBER_3
      , ATTRIBUTE_DATE_7
      , ATTRIBUTE_3
      , ATTRIBUTE_DATE_8
      , SH_ATTRIBUTE_19
      , SH_ATTRIBUTE_DATE_1
      , LAST_UPDATE_LOGIN
      , OKE_CONTRACT_HEADER_ID
      , SH_ATTRIBUTE_16
      , ATTRIBUTE_9
      , CANCEL_DATE
      , NEGOTIATED_BY_PREPARER_FLAG
      , ITEM_ID
      , ATTRIBUTE_DATE_3
      , LIST_PRICE_PER_UNIT
      , SECONDARY_QUANTITY
      , ATTRIBUTE_DATE_5
      , SH_ATTRIBUTE_TIMESTAMP_5
      , TYPE_1099
      , ATTRIBUTE_TIMESTAMP_1
      , GLOBAL_ATTRIBUTE_NUMBER_1
      , SH_ATTRIBUTE_15
      , GLOBAL_ATTRIBUTE_DATE_1
      , ATTRIBUTE_TIMESTAMP_5
      , ATTRIBUTE_TIMESTAMP_4
      , JOB_DEFINITION_NAME
      , SH_ATTRIBUTE_17
      , PURCHASE_BASIS
      , GLOBAL_ATTRIBUTE_18
      , GLOBAL_ATTRIBUTE_NUMBER_2
      , SH_ATTRIBUTE_18
      , SH_ATTRIBUTE_6
      , GLOBAL_ATTRIBUTE_DATE_5
      , AUCTION_DISPLAY_NUMBER
      , ATTRIBUTE_14
      , SH_ATTRIBUTE_5
      , ATTRIBUTE_6
      , SH_ATTRIBUTE_DATE_7
      , SH_ATTRIBUTE_1
      , ATTRIBUTE_NUMBER_1
      , GLOBAL_ATTRIBUTE_17
      , GLOBAL_ATTRIBUTE_2
      , OPTIONS_PRICE
      , CLOSED_DATE
      , ORDER_TYPE_LOOKUP_CODE
      , ATTRIBUTE_NUMBER_10
      , EXPIRATION_DATE
      , UOM_CODE
      , ATTRIBUTE_CATEGORY
      , SH_ATTRIBUTE_TIMESTAMP_4
      , PRICE_BREAK_LOOKUP_CODE
      , SH_ATTRIBUTE_12
      , GLOBAL_ATTRIBUTE_20
      , BID_LINE_NUMBER
      , SH_ATTRIBUTE_DATE_5
      , LINE_STATUS
      , ALLOW_DESCRIPTION_UPDATE_FLAG
      , OKE_CONTRACT_VERSION_ID
      , SH_ATTRIBUTE_NUMBER_8
      , CATEGORY_ID
      , ATTRIBUTE_15
      , BASE_QTY
      , ATTRIBUTE_TIMESTAMP_2
      , PROGRAM_NAME
      , MAX_RETAINAGE_AMOUNT
      , BASE_UNIT_PRICE
      , SH_ATTRIBUTE_NUMBER_6
      , REFERENCE_NUM
      , AUCTION_HEADER_ID
      , ATTRIBUTE_DATE_1
      , GLOBAL_ATTRIBUTE_4
      , GLOBAL_ATTRIBUTE_CATEGORY
      , ATTRIBUTE_1
      , SH_ATTRIBUTE_NUMBER_5
      , CLOSED_BY
      , GLOBAL_ATTRIBUTE_16
      , GLOBAL_ATTRIBUTE_9
      , GLOBAL_ATTRIBUTE_11
      , AUCTION_LINE_NUMBER
      , ATTRIBUTE_TIMESTAMP_10
      , GLOBAL_ATTRIBUTE_14
      , SH_ATTRIBUTE_3
      , GOVERNMENT_CONTEXT
      , SH_ATTRIBUTE_TIMESTAMP_2
      , ATTRIBUTE_NUMBER_6
      , TAXABLE_FLAG
      , MANUAL_PRICE_CHANGE_FLAG
      , GLOBAL_ATTRIBUTE_NUMBER_4
      , SVC_AMOUNT_NOTIF_SENT
      , QC_GRADE
      , SUPPLIER_PART_AUXID
      , LAST_UPDATED_PROGRAM
      , AMOUNT
      , PREFERRED_GRADE
      , GLOBAL_ATTRIBUTE_DATE_3
      , MATCHING_BASIS
      , SUPPLIER_TOP_MODEL
      , LAST_UPDATED_BY
      , GLOBAL_ATTRIBUTE_12
      , BASE_MODEL_PRICE
      , ATTRIBUTE_DATE_9
      , SUPPLIER_REF_NUMBER
      , QUANTITY
      , LINE_START_DATE
      , _FIVETRAN_DELETED
      , _FIVETRAN_SYNCED
      , PSA_DELETE_IND
      , PSA_LOAD_DTS
      , PSA_RECORD_SOURCE
      , LOAD_DTS
      , REC_SRC
      , BKCC
      , HASHDIFF
    FROM LOGIC_a
)
---- FILTER LAYER ----

, FILTER_a as (
    SELECT *
    FROM RENAME_a
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM FILTER_a
)

---- FINAL LAYER ----
SELECT
          PO_ITEM_HK
        , PO_HEADER_ID
        , LINE_NUM
        , PO_LINE_ID
        , CREATION_DATE
        , SOLDTO_BU_ID
        , SH_ATTRIBUTE_8
        , ATTRIBUTE_10
        , ATTRIBUTE_13
        , SH_ATTRIBUTE_NUMBER_4
        , GLOBAL_ATTRIBUTE_7
        , SVC_COMPLETION_NOTIF_SENT
        , ATTRIBUTE_20
        , TAX_NAME
        , SH_ATTRIBUTE_DATE_6
        , NOTE_TO_VENDOR
        , SHIPPING_UOM_QUANTITY
        , ATTRIBUTE_4
        , SH_ATTRIBUTE_7
        , SH_ATTRIBUTE_13
        , COMPONENT_AMOUNT_RELEASED
        , GLOBAL_ATTRIBUTE_10
        , CONFIGURED_ITEM_FLAG
        , ATTRIBUTE_DATE_6
        , CREDIT_FLAG
        , MANUFACTURER
        , AGING_PERIOD_DAYS
        , FUNDS_STATUS
        , SH_ATTRIBUTE_TIMESTAMP_3
        , ATTRIBUTE_NUMBER_7
        , SH_ATTRIBUTE_NUMBER_2
        , ATTRIBUTE_NUMBER_4
        , GLOBAL_ATTRIBUTE_19
        , PARENT_ITEM_ID
        , SH_ATTRIBUTE_CATEGORY
        , OBJECT_VERSION_NUMBER
        , SH_ATTRIBUTE_TIMESTAMP_1
        , ATTRIBUTE_12
        , GLOBAL_ATTRIBUTE_13
        , SH_ATTRIBUTE_TIMESTAMP_6
        , ATTRIBUTE_DATE_2
        , GLOBAL_ATTRIBUTE_15
        , PROGRAM_APP_NAME
        , COMMITTED_AMOUNT
        , ATTRIBUTE_DATE_10
        , SH_ATTRIBUTE_NUMBER_10
        , CREATED_BY
        , DISCOUNT_TYPE
        , GLOBAL_ATTRIBUTE_DATE_4
        , CANCEL_FLAG
        , OVER_TOLERANCE_ERROR_FLAG
        , ATTRIBUTE_TIMESTAMP_6
        , MARKET_PRICE
        , SH_ATTRIBUTE_TIMESTAMP_9
        , SH_ATTRIBUTE_TIMESTAMP_7
        , NOT_TO_EXCEED_PRICE
        , ATTRIBUTE_NUMBER_9
        , PJC_CONTEXT_CATEGORY
        , SH_ATTRIBUTE_20
        , QTY_RCV_TOLERANCE
        , ATTRIBUTE_NUMBER_3
        , CANCELLED_BY
        , ATTRIBUTE_TIMESTAMP_3
        , CONTRACT_ID
        , JOB_ID
        , DISCOUNT
        , SHIPPING_UOM_CODE
        , CONTRACTOR_LAST_NAME
        , SECONDARY_UOM_CODE
        , DISCOUNT_REASON
        , SH_ATTRIBUTE_NUMBER_7
        , GLOBAL_ATTRIBUTE_DATE_2
        , SH_ATTRIBUTE_2
        , ATTRIBUTE_11
        , CATALOG_NAME
        , ATTRIBUTE_17
        , SH_ATTRIBUTE_DATE_3
        , ATTRIBUTE_TIMESTAMP_8
        , LINE_REFERENCE_NUM
        , GLOBAL_ATTRIBUTE_1
        , GLOBAL_ATTRIBUTE_NUMBER_5
        , SH_ATTRIBUTE_DATE_2
        , CLOSED_REASON
        , LINE_TYPE_ID
        , JOB_DEFINITION_PACKAGE
        , PRICE_TYPE_LOOKUP_CODE
        , ATTRIBUTE_16
        , MANUFACTURER_PART_NUM
        , RECOUPMENT_RATE
        , GLOBAL_ATTRIBUTE_8
        , CANCEL_REASON
        , BID_NUMBER
        , GLOBAL_ATTRIBUTE_3
        , START_DATE
        , UN_NUMBER_ID
        , QUANTITY_COMMITTED
        , ATTRIBUTE_NUMBER_2
        , ALLOW_PRICE_OVERRIDE_FLAG
        , UNIT_PRICE
        , ATTRIBUTE_TIMESTAMP_9
        , BASE_UOM
        , FIRM_DATE
        , SH_ATTRIBUTE_NUMBER_1
        , SH_ATTRIBUTE_DATE_4
        , MIN_RELEASE_AMOUNT
        , SH_ATTRIBUTE_9
        , ATTRIBUTE_18
        , PRC_BU_ID
        , GLOBAL_ATTRIBUTE_NUMBER_3
        , ITEM_REVISION
        , SH_ATTRIBUTE_DATE_8
        , FROM_HEADER_ID
        , HAZARD_CLASS_ID
        , LIST_PRICE
        , SH_ATTRIBUTE_4
        , REQUEST_ID
        , ATTRIBUTE_2
        , AMOUNT_RELEASED
        , TAX_CODE_ID
        , BASE_MODEL_ID
        , ATTRIBUTE_DATE_4
        , TAX_ATTRIBUTE_UPDATE_CODE
        , ATTRIBUTE_TIMESTAMP_7
        , SOURCE_DOC_REV_NUM
        , RETAINAGE_RATE
        , LAST_UPDATE_DATE
        , CONTRACTOR_FIRST_NAME
        , TAX_EXCLUSIVE_PRICE
        , ATTRIBUTE_5
        , ATTRIBUTE_NUMBER_8
        , CONSIGNMENT_LINE_FLAG
        , FROM_LINE_LOCATION_ID
        , WORK_ORDER_PRODUCT
        , REQ_BU_ID
        , SH_ATTRIBUTE_11
        , ATTRIBUTE_NUMBER_5
        , ATTRIBUTE_19
        , SH_ATTRIBUTE_NUMBER_9
        , TOP_MODEL_ID
        , FIRM_STATUS_LOOKUP_CODE
        , SH_ATTRIBUTE_TIMESTAMP_10
        , SH_ATTRIBUTE_10
        , SH_ATTRIBUTE_DATE_9
        , VENDOR_PRODUCT_NUM
        , CAPITAL_EXPENSE_FLAG
        , ITEM_DESCRIPTION
        , ATTRIBUTE_7
        , RETROACTIVE_DATE
        , FROM_LINE_ID
        , SH_ATTRIBUTE_TIMESTAMP_8
        , NEXT_CONSUMPTION_ADV_GEN_DATE
        , PROGRESS_PAYMENT_RATE
        , SH_ATTRIBUTE_DATE_10
        , GLOBAL_ATTRIBUTE_6
        , ATTRIBUTE_8
        , UNORDERED_FLAG
        , SUPPLIER_PARENT_ITEM
        , SH_ATTRIBUTE_14
        , GLOBAL_ATTRIBUTE_5
        , SH_ATTRIBUTE_NUMBER_3
        , ATTRIBUTE_DATE_7
        , ATTRIBUTE_3
        , ATTRIBUTE_DATE_8
        , SH_ATTRIBUTE_19
        , SH_ATTRIBUTE_DATE_1
        , LAST_UPDATE_LOGIN
        , OKE_CONTRACT_HEADER_ID
        , SH_ATTRIBUTE_16
        , ATTRIBUTE_9
        , CANCEL_DATE
        , NEGOTIATED_BY_PREPARER_FLAG
        , ITEM_ID
        , ATTRIBUTE_DATE_3
        , LIST_PRICE_PER_UNIT
        , SECONDARY_QUANTITY
        , ATTRIBUTE_DATE_5
        , SH_ATTRIBUTE_TIMESTAMP_5
        , TYPE_1099
        , ATTRIBUTE_TIMESTAMP_1
        , GLOBAL_ATTRIBUTE_NUMBER_1
        , SH_ATTRIBUTE_15
        , GLOBAL_ATTRIBUTE_DATE_1
        , ATTRIBUTE_TIMESTAMP_5
        , ATTRIBUTE_TIMESTAMP_4
        , JOB_DEFINITION_NAME
        , SH_ATTRIBUTE_17
        , PURCHASE_BASIS
        , GLOBAL_ATTRIBUTE_18
        , GLOBAL_ATTRIBUTE_NUMBER_2
        , SH_ATTRIBUTE_18
        , SH_ATTRIBUTE_6
        , GLOBAL_ATTRIBUTE_DATE_5
        , AUCTION_DISPLAY_NUMBER
        , ATTRIBUTE_14
        , SH_ATTRIBUTE_5
        , ATTRIBUTE_6
        , SH_ATTRIBUTE_DATE_7
        , SH_ATTRIBUTE_1
        , ATTRIBUTE_NUMBER_1
        , GLOBAL_ATTRIBUTE_17
        , GLOBAL_ATTRIBUTE_2
        , OPTIONS_PRICE
        , CLOSED_DATE
        , ORDER_TYPE_LOOKUP_CODE
        , ATTRIBUTE_NUMBER_10
        , EXPIRATION_DATE
        , UOM_CODE
        , ATTRIBUTE_CATEGORY
        , SH_ATTRIBUTE_TIMESTAMP_4
        , PRICE_BREAK_LOOKUP_CODE
        , SH_ATTRIBUTE_12
        , GLOBAL_ATTRIBUTE_20
        , BID_LINE_NUMBER
        , SH_ATTRIBUTE_DATE_5
        , LINE_STATUS
        , ALLOW_DESCRIPTION_UPDATE_FLAG
        , OKE_CONTRACT_VERSION_ID
        , SH_ATTRIBUTE_NUMBER_8
        , CATEGORY_ID
        , ATTRIBUTE_15
        , BASE_QTY
        , ATTRIBUTE_TIMESTAMP_2
        , PROGRAM_NAME
        , MAX_RETAINAGE_AMOUNT
        , BASE_UNIT_PRICE
        , SH_ATTRIBUTE_NUMBER_6
        , REFERENCE_NUM
        , AUCTION_HEADER_ID
        , ATTRIBUTE_DATE_1
        , GLOBAL_ATTRIBUTE_4
        , GLOBAL_ATTRIBUTE_CATEGORY
        , ATTRIBUTE_1
        , SH_ATTRIBUTE_NUMBER_5
        , CLOSED_BY
        , GLOBAL_ATTRIBUTE_16
        , GLOBAL_ATTRIBUTE_9
        , GLOBAL_ATTRIBUTE_11
        , AUCTION_LINE_NUMBER
        , ATTRIBUTE_TIMESTAMP_10
        , GLOBAL_ATTRIBUTE_14
        , SH_ATTRIBUTE_3
        , GOVERNMENT_CONTEXT
        , SH_ATTRIBUTE_TIMESTAMP_2
        , ATTRIBUTE_NUMBER_6
        , TAXABLE_FLAG
        , MANUAL_PRICE_CHANGE_FLAG
        , GLOBAL_ATTRIBUTE_NUMBER_4
        , SVC_AMOUNT_NOTIF_SENT
        , QC_GRADE
        , SUPPLIER_PART_AUXID
        , LAST_UPDATED_PROGRAM
        , AMOUNT
        , PREFERRED_GRADE
        , GLOBAL_ATTRIBUTE_DATE_3
        , MATCHING_BASIS
        , SUPPLIER_TOP_MODEL
        , LAST_UPDATED_BY
        , GLOBAL_ATTRIBUTE_12
        , BASE_MODEL_PRICE
        , ATTRIBUTE_DATE_9
        , SUPPLIER_REF_NUMBER
        , QUANTITY
        , LINE_START_DATE
        , _FIVETRAN_DELETED
        , _FIVETRAN_SYNCED
        , PSA_DELETE_IND
        , PSA_LOAD_DTS
        , PSA_RECORD_SOURCE
        , LOAD_DTS
        , REC_SRC
        , BKCC
        , HASHDIFF
FROM JOIN_RESULT
{% if is_incremental() %}
WHERE NOT EXISTS (
    SELECT 1 
    FROM {{ this }} existing
    WHERE existing.PO_ITEM_HK = JOIN_RESULT.PO_ITEM_HK 
    AND existing.HASHDIFF = JOIN_RESULT.HASHDIFF
)
{% endif %}
{% if not is_incremental() %}

/* The following qualifier is implemented to prevent multiple loads of touched records during the initial build, such as multiple rows per HK and hashdiff. */
qualify 1 = row_number() over (partition by PO_ITEM_HK, HASHDIFF order by PSA_LOAD_DTS)

union all
SELECT 
MD5_BINARY(GR.VALUE) AS PO_ITEM_HK,
GR.VALUE::number AS PO_HEADER_ID,
GR.VALUE::number AS LINE_NUM,
NULL AS PO_LINE_ID,
NULL AS CREATION_DATE,
NULL AS SOLDTO_BU_ID,
NULL AS SH_ATTRIBUTE_8,
NULL AS ATTRIBUTE_10,
NULL AS ATTRIBUTE_13,
NULL AS SH_ATTRIBUTE_NUMBER_4,
NULL AS GLOBAL_ATTRIBUTE_7,
NULL AS SVC_COMPLETION_NOTIF_SENT,
NULL AS ATTRIBUTE_20,
NULL AS TAX_NAME,
NULL AS SH_ATTRIBUTE_DATE_6,
NULL AS NOTE_TO_VENDOR,
NULL AS SHIPPING_UOM_QUANTITY,
NULL AS ATTRIBUTE_4,
NULL AS SH_ATTRIBUTE_7,
NULL AS SH_ATTRIBUTE_13,
NULL AS COMPONENT_AMOUNT_RELEASED,
NULL AS GLOBAL_ATTRIBUTE_10,
NULL AS CONFIGURED_ITEM_FLAG,
NULL AS ATTRIBUTE_DATE_6,
NULL AS CREDIT_FLAG,
NULL AS MANUFACTURER,
NULL AS AGING_PERIOD_DAYS,
NULL AS FUNDS_STATUS,
NULL AS SH_ATTRIBUTE_TIMESTAMP_3,
NULL AS ATTRIBUTE_NUMBER_7,
NULL AS SH_ATTRIBUTE_NUMBER_2,
NULL AS ATTRIBUTE_NUMBER_4,
NULL AS GLOBAL_ATTRIBUTE_19,
NULL AS PARENT_ITEM_ID,
NULL AS SH_ATTRIBUTE_CATEGORY,
NULL AS OBJECT_VERSION_NUMBER,
NULL AS SH_ATTRIBUTE_TIMESTAMP_1,
NULL AS ATTRIBUTE_12,
NULL AS GLOBAL_ATTRIBUTE_13,
NULL AS SH_ATTRIBUTE_TIMESTAMP_6,
NULL AS ATTRIBUTE_DATE_2,
NULL AS GLOBAL_ATTRIBUTE_15,
NULL AS PROGRAM_APP_NAME,
NULL AS COMMITTED_AMOUNT,
NULL AS ATTRIBUTE_DATE_10,
NULL AS SH_ATTRIBUTE_NUMBER_10,
NULL AS CREATED_BY,
NULL AS DISCOUNT_TYPE,
NULL AS GLOBAL_ATTRIBUTE_DATE_4,
NULL AS CANCEL_FLAG,
NULL AS OVER_TOLERANCE_ERROR_FLAG,
NULL AS ATTRIBUTE_TIMESTAMP_6,
NULL AS MARKET_PRICE,
NULL AS SH_ATTRIBUTE_TIMESTAMP_9,
NULL AS SH_ATTRIBUTE_TIMESTAMP_7,
NULL AS NOT_TO_EXCEED_PRICE,
NULL AS ATTRIBUTE_NUMBER_9,
NULL AS PJC_CONTEXT_CATEGORY,
NULL AS SH_ATTRIBUTE_20,
NULL AS QTY_RCV_TOLERANCE,
NULL AS ATTRIBUTE_NUMBER_3,
NULL AS CANCELLED_BY,
NULL AS ATTRIBUTE_TIMESTAMP_3,
NULL AS CONTRACT_ID,
NULL AS JOB_ID,
NULL AS DISCOUNT,
NULL AS SHIPPING_UOM_CODE,
NULL AS CONTRACTOR_LAST_NAME,
NULL AS SECONDARY_UOM_CODE,
NULL AS DISCOUNT_REASON,
NULL AS SH_ATTRIBUTE_NUMBER_7,
NULL AS GLOBAL_ATTRIBUTE_DATE_2,
NULL AS SH_ATTRIBUTE_2,
NULL AS ATTRIBUTE_11,
NULL AS CATALOG_NAME,
NULL AS ATTRIBUTE_17,
NULL AS SH_ATTRIBUTE_DATE_3,
NULL AS ATTRIBUTE_TIMESTAMP_8,
NULL AS LINE_REFERENCE_NUM,
NULL AS GLOBAL_ATTRIBUTE_1,
NULL AS GLOBAL_ATTRIBUTE_NUMBER_5,
NULL AS SH_ATTRIBUTE_DATE_2,
NULL AS CLOSED_REASON,
NULL AS LINE_TYPE_ID,
NULL AS JOB_DEFINITION_PACKAGE,
NULL AS PRICE_TYPE_LOOKUP_CODE,
NULL AS ATTRIBUTE_16,
NULL AS MANUFACTURER_PART_NUM,
NULL AS RECOUPMENT_RATE,
NULL AS GLOBAL_ATTRIBUTE_8,
NULL AS CANCEL_REASON,
NULL AS BID_NUMBER,
NULL AS GLOBAL_ATTRIBUTE_3,
NULL AS START_DATE,
NULL AS UN_NUMBER_ID,
NULL AS QUANTITY_COMMITTED,
NULL AS ATTRIBUTE_NUMBER_2,
NULL AS ALLOW_PRICE_OVERRIDE_FLAG,
NULL AS UNIT_PRICE,
NULL AS ATTRIBUTE_TIMESTAMP_9,
NULL AS BASE_UOM,
NULL AS FIRM_DATE,
NULL AS SH_ATTRIBUTE_NUMBER_1,
NULL AS SH_ATTRIBUTE_DATE_4,
NULL AS MIN_RELEASE_AMOUNT,
NULL AS SH_ATTRIBUTE_9,
NULL AS ATTRIBUTE_18,
NULL AS PRC_BU_ID,
NULL AS GLOBAL_ATTRIBUTE_NUMBER_3,
NULL AS ITEM_REVISION,
NULL AS SH_ATTRIBUTE_DATE_8,
NULL AS FROM_HEADER_ID,
NULL AS HAZARD_CLASS_ID,
NULL AS LIST_PRICE,
NULL AS SH_ATTRIBUTE_4,
NULL AS REQUEST_ID,
NULL AS ATTRIBUTE_2,
NULL AS AMOUNT_RELEASED,
NULL AS TAX_CODE_ID,
NULL AS BASE_MODEL_ID,
NULL AS ATTRIBUTE_DATE_4,
NULL AS TAX_ATTRIBUTE_UPDATE_CODE,
NULL AS ATTRIBUTE_TIMESTAMP_7,
NULL AS SOURCE_DOC_REV_NUM,
NULL AS RETAINAGE_RATE,
NULL AS LAST_UPDATE_DATE,
NULL AS CONTRACTOR_FIRST_NAME,
NULL AS TAX_EXCLUSIVE_PRICE,
NULL AS ATTRIBUTE_5,
NULL AS ATTRIBUTE_NUMBER_8,
NULL AS CONSIGNMENT_LINE_FLAG,
NULL AS FROM_LINE_LOCATION_ID,
NULL AS WORK_ORDER_PRODUCT,
NULL AS REQ_BU_ID,
NULL AS SH_ATTRIBUTE_11,
NULL AS ATTRIBUTE_NUMBER_5,
NULL AS ATTRIBUTE_19,
NULL AS SH_ATTRIBUTE_NUMBER_9,
NULL AS TOP_MODEL_ID,
NULL AS FIRM_STATUS_LOOKUP_CODE,
NULL AS SH_ATTRIBUTE_TIMESTAMP_10,
NULL AS SH_ATTRIBUTE_10,
NULL AS SH_ATTRIBUTE_DATE_9,
NULL AS VENDOR_PRODUCT_NUM,
NULL AS CAPITAL_EXPENSE_FLAG,
NULL AS ITEM_DESCRIPTION,
NULL AS ATTRIBUTE_7,
NULL AS RETROACTIVE_DATE,
NULL AS FROM_LINE_ID,
NULL AS SH_ATTRIBUTE_TIMESTAMP_8,
NULL AS NEXT_CONSUMPTION_ADV_GEN_DATE,
NULL AS PROGRESS_PAYMENT_RATE,
NULL AS SH_ATTRIBUTE_DATE_10,
NULL AS GLOBAL_ATTRIBUTE_6,
NULL AS ATTRIBUTE_8,
NULL AS UNORDERED_FLAG,
NULL AS SUPPLIER_PARENT_ITEM,
NULL AS SH_ATTRIBUTE_14,
NULL AS GLOBAL_ATTRIBUTE_5,
NULL AS SH_ATTRIBUTE_NUMBER_3,
NULL AS ATTRIBUTE_DATE_7,
NULL AS ATTRIBUTE_3,
NULL AS ATTRIBUTE_DATE_8,
NULL AS SH_ATTRIBUTE_19,
NULL AS SH_ATTRIBUTE_DATE_1,
NULL AS LAST_UPDATE_LOGIN,
NULL AS OKE_CONTRACT_HEADER_ID,
NULL AS SH_ATTRIBUTE_16,
NULL AS ATTRIBUTE_9,
NULL AS CANCEL_DATE,
NULL AS NEGOTIATED_BY_PREPARER_FLAG,
NULL AS ITEM_ID,
NULL AS ATTRIBUTE_DATE_3,
NULL AS LIST_PRICE_PER_UNIT,
NULL AS SECONDARY_QUANTITY,
NULL AS ATTRIBUTE_DATE_5,
NULL AS SH_ATTRIBUTE_TIMESTAMP_5,
NULL AS TYPE_1099,
NULL AS ATTRIBUTE_TIMESTAMP_1,
NULL AS GLOBAL_ATTRIBUTE_NUMBER_1,
NULL AS SH_ATTRIBUTE_15,
NULL AS GLOBAL_ATTRIBUTE_DATE_1,
NULL AS ATTRIBUTE_TIMESTAMP_5,
NULL AS ATTRIBUTE_TIMESTAMP_4,
NULL AS JOB_DEFINITION_NAME,
NULL AS SH_ATTRIBUTE_17,
NULL AS PURCHASE_BASIS,
NULL AS GLOBAL_ATTRIBUTE_18,
NULL AS GLOBAL_ATTRIBUTE_NUMBER_2,
NULL AS SH_ATTRIBUTE_18,
NULL AS SH_ATTRIBUTE_6,
NULL AS GLOBAL_ATTRIBUTE_DATE_5,
NULL AS AUCTION_DISPLAY_NUMBER,
NULL AS ATTRIBUTE_14,
NULL AS SH_ATTRIBUTE_5,
NULL AS ATTRIBUTE_6,
NULL AS SH_ATTRIBUTE_DATE_7,
NULL AS SH_ATTRIBUTE_1,
NULL AS ATTRIBUTE_NUMBER_1,
NULL AS GLOBAL_ATTRIBUTE_17,
NULL AS GLOBAL_ATTRIBUTE_2,
NULL AS OPTIONS_PRICE,
NULL AS CLOSED_DATE,
NULL AS ORDER_TYPE_LOOKUP_CODE,
NULL AS ATTRIBUTE_NUMBER_10,
NULL AS EXPIRATION_DATE,
NULL AS UOM_CODE,
NULL AS ATTRIBUTE_CATEGORY,
NULL AS SH_ATTRIBUTE_TIMESTAMP_4,
NULL AS PRICE_BREAK_LOOKUP_CODE,
NULL AS SH_ATTRIBUTE_12,
NULL AS GLOBAL_ATTRIBUTE_20,
NULL AS BID_LINE_NUMBER,
NULL AS SH_ATTRIBUTE_DATE_5,
NULL AS LINE_STATUS,
NULL AS ALLOW_DESCRIPTION_UPDATE_FLAG,
NULL AS OKE_CONTRACT_VERSION_ID,
NULL AS SH_ATTRIBUTE_NUMBER_8,
NULL AS CATEGORY_ID,
NULL AS ATTRIBUTE_15,
NULL AS BASE_QTY,
NULL AS ATTRIBUTE_TIMESTAMP_2,
NULL AS PROGRAM_NAME,
NULL AS MAX_RETAINAGE_AMOUNT,
NULL AS BASE_UNIT_PRICE,
NULL AS SH_ATTRIBUTE_NUMBER_6,
NULL AS REFERENCE_NUM,
NULL AS AUCTION_HEADER_ID,
NULL AS ATTRIBUTE_DATE_1,
NULL AS GLOBAL_ATTRIBUTE_4,
NULL AS GLOBAL_ATTRIBUTE_CATEGORY,
NULL AS ATTRIBUTE_1,
NULL AS SH_ATTRIBUTE_NUMBER_5,
NULL AS CLOSED_BY,
NULL AS GLOBAL_ATTRIBUTE_16,
NULL AS GLOBAL_ATTRIBUTE_9,
NULL AS GLOBAL_ATTRIBUTE_11,
NULL AS AUCTION_LINE_NUMBER,
NULL AS ATTRIBUTE_TIMESTAMP_10,
NULL AS GLOBAL_ATTRIBUTE_14,
NULL AS SH_ATTRIBUTE_3,
NULL AS GOVERNMENT_CONTEXT,
NULL AS SH_ATTRIBUTE_TIMESTAMP_2,
NULL AS ATTRIBUTE_NUMBER_6,
NULL AS TAXABLE_FLAG,
NULL AS MANUAL_PRICE_CHANGE_FLAG,
NULL AS GLOBAL_ATTRIBUTE_NUMBER_4,
NULL AS SVC_AMOUNT_NOTIF_SENT,
NULL AS QC_GRADE,
NULL AS SUPPLIER_PART_AUXID,
NULL AS LAST_UPDATED_PROGRAM,
NULL AS AMOUNT,
NULL AS PREFERRED_GRADE,
NULL AS GLOBAL_ATTRIBUTE_DATE_3,
NULL AS MATCHING_BASIS,
NULL AS SUPPLIER_TOP_MODEL,
NULL AS LAST_UPDATED_BY,
NULL AS GLOBAL_ATTRIBUTE_12,
NULL AS BASE_MODEL_PRICE,
NULL AS ATTRIBUTE_DATE_9,
NULL AS SUPPLIER_REF_NUMBER,
NULL AS QUANTITY,
NULL AS LINE_START_DATE,
NULL AS _FIVETRAN_DELETED,
NULL AS _FIVETRAN_SYNCED,
'N' AS PSA_DELETE_IND,
'1900-01-01'::TIMESTAMP AS PSA_LOAD_DTS,
NULL AS PSA_RECORD_SOURCE,
CONVERT_TIMEZONE('UTC','1900-01-01'::TIMESTAMP) AS LOAD_DTS,
'USAZET.SNOWFLAKE.FBIN.DERIVED' AS REC_SRC,
DECODE(GR.VALUE, 0, 'GHOST RECORD-SYSTEM', -1, 'GHOST RECORD-nullkey-required', -2, 'GHOST RECORD-nullkey-optional') AS BKCC,
''::BINARY AS HASHDIFF
FROM
TABLE(strtok_split_to_table('0|-1|-2', '|')) AS GR
{% endif %}
