---- SRC LAYER ----
WITH
SRC_SFIB           as ( SELECT * FROM {{ ref('v_psa_stg_supplier__fib_ocf') }} as SRC 
                         {% if is_incremental() %}
                         WHERE SRC.LOAD_DTS > (SELECT DATEADD('HOUR', '-1', MAX(LOAD_DTS)) FROM {{this}})
                         {% endif %}  )

/*
SRC_SFIB           as ( SELECT * FROM STAGING.v_psa_stg_supplier__fib_ocf )
*/
---- LOGIC LAYER ----

, LOGIC_SFIB as (
    SELECT
        SUPPLIER_HK
      , SEGMENT_1
      , VENDOR_ID
      , LOAD_DTS
      , ATTRIBUTE_TIMESTAMP_10
      , GLOBAL_ATTRIBUTE_20
      , WOMEN_OWNED_FLAG
      , GLOBAL_ATTRIBUTE_6
      , ATTRIBUTE_DATE_1
      , ATTRIBUTE_5
      , ATTRIBUTE_TIMESTAMP_7
      , GLOBAL_ATTRIBUTE_2
      , AMOUNT_INCLUDES_TAX_FLAG
      , GLOBAL_ATTRIBUTE_17
      , INCOME_TAX_ID_FLAG
      , ATTRIBUTE_TIMESTAMP_8
      , ATTRIBUTE_TIMESTAMP_1
      , ATTRIBUTE_CATEGORY
      , ENABLED_FLAG
      , ATTRIBUTE_12
      , ATTRIBUTE_NUMBER_4
      , CREATION_DATE
      , CREATION_SOURCE
      , NAME_CONTROL
      , AP_TAX_ROUNDING_RULE
      , MINORITY_GROUP_LOOKUP_CODE
      , BC_NOT_APPLICABLE_FLAG
      , END_DATE_ACTIVE
      , WITHHOLDING_START_DATE
      , GLOBAL_ATTRIBUTE_5
      , GLOBAL_ATTRIBUTE_3
      , ATTRIBUTE_DATE_2
      , SPEND_AUTH_REVIEW_STATUS
      , GLOBAL_ATTRIBUTE_DATE_8
      , GLOBAL_ATTRIBUTE_12
      , GLOBAL_ATTRIBUTE_DATE_5
      , LAST_UPDATE_DATE
      , DF_NAICS_CODE
      , ATTRIBUTE_19
      , WITHHOLDING_STATUS_LOOKUP_CODE
      , GLOBAL_ATTRIBUTE_15
      , ATTRIBUTE_DATE_6
      , GLOBAL_ATTRIBUTE_1
      , ATTRIBUTE_20
      , ATTRIBUTE_NUMBER_7
      , ATTRIBUTE_NUMBER_5
      , DF_LAST_SYNC_DATE
      , SPEND_AUTH_JUSTIFICATION
      , SUPPLIER_LOCKED_FLAG
      , GLOBAL_ATTRIBUTE_NUMBER_8
      , DATAFOX_COMPANY_ID
      , GLOBAL_ATTRIBUTE_NUMBER_7
      , GLOBAL_ATTRIBUTE_TIMESTAMP_7
      , ATTRIBUTE_TIMESTAMP_6
      , GLOBAL_ATTRIBUTE_8
      , ATTRIBUTE_2
      , ATTRIBUTE_11
      , AUTO_TAX_CALC_OVERRIDE
      , ATTRIBUTE_NUMBER_1
      , STANDARD_INDUSTRY_CLASS
      , CUSTOMER_NUM
      , CREATED_BY
      , GLOBAL_ATTRIBUTE_TIMESTAMP_5
      , ATTRIBUTE_18
      , ATTRIBUTE_9
      , PARTY_ID
      , DF_SCORE
      , JOB_DEFINITION_PACKAGE
      , ATTRIBUTE_TIMESTAMP_5
      , ATTRIBUTE_DATE_10
      , REVIEW_TYPE
      , PROGRAM_UPDATE_DATE
      , REBUILD_INDEX
      , ATTRIBUTE_NUMBER_6
      , PARENT_PARTY_ID
      , DF_LEGAL_NAME
      , ATTRIBUTE_8
      , MIN_ORDER_AMOUNT
      , ONE_TIME_FLAG
      , ATTRIBUTE_17
      , ATTRIBUTE_TIMESTAMP_2
      , VAT_REGISTRATION_NUM
      , ATTRIBUTE_15
      , GLOBAL_ATTRIBUTE_4
      , GLOBAL_ATTRIBUTE_DATE_7
      , GLOBAL_ATTRIBUTE_NUMBER_4
      , ATTRIBUTE_4
      , GLOBAL_ATTRIBUTE_11
      , GLOBAL_ATTRIBUTE_TIMESTAMP_8
      , OFFSET_VAT_CODE
      , DF_COMPANY_NAME
      , ATTRIBUTE_3
      , DENIED_PARTY_FLAG
      , SMALL_BUSINESS_FLAG
      , GLOBAL_ATTRIBUTE_TIMESTAMP_10
      , GLOBAL_ATTRIBUTE_DATE_3
      , BUSINESS_RELATIONSHIP
      , EXTERNAL_SYSTEM_ID
      , ATTRIBUTE_10
      , LAST_UPDATE_LOGIN
      , NI_NUMBER
      , DF_CORPORATE_WEBSITE
      , DF_INDUSTRY_CATEGORY_CODE
      , CORPORATE_WEBSITE
      , ATTRIBUTE_NUMBER_3
      , DF_LINKED_ADDRESS_ID
      , ATTRIBUTE_TIMESTAMP_3
      , AUTO_TAX_CALC_FLAG
      , GLOBAL_ATTRIBUTE_TIMESTAMP_9
      , START_DATE_ACTIVE
      , GLOBAL_ATTRIBUTE_14
      , GLOBAL_ATTRIBUTE_19
      , ATTRIBUTE_7
      , GLOBAL_ATTRIBUTE_TIMESTAMP_6
      , ORGANIZATION_TYPE_LOOKUP_CODE
      , GLOBAL_ATTRIBUTE_DATE_6
      , ATTRIBUTE_DATE_9
      , ATTRIBUTE_DATE_3
      , ATTRIBUTE_13
      , ATTRIBUTE_NUMBER_9
      , REQUEST_ID
      , GLOBAL_ATTRIBUTE_18
      , PROGRAM_ID
      , GLOBAL_ATTRIBUTE_TIMESTAMP_3
      , ATTRIBUTE_DATE_4
      , GLOBAL_ATTRIBUTE_CATEGORY
      , PROGRAM_APPLICATION_ID
      , GLOBAL_ATTRIBUTE_NUMBER_1
      , NI_NUMBER_FLAG
      , GLOBAL_ATTRIBUTE_NUMBER_3
      , GLOBAL_ATTRIBUTE_DATE_9
      , GLOBAL_ATTRIBUTE_DATE_1
      , GLOBAL_ATTRIBUTE_NUMBER_6
      , ATTRIBUTE_DATE_5
      , TAXPAYER_COUNTRY
      , AWT_GROUP_ID
      , ATTRIBUTE_6
      , OBN_MATCHED_STATUS
      , ATTRIBUTE_TIMESTAMP_9
      , STATE_REPORTABLE_FLAG
      , ATTRIBUTE_14
      , GLOBAL_ATTRIBUTE_9
      , ATTRIBUTE_16
      , EXTERNAL_SYSTEM
      , ATTRIBUTE_1
      , VAT_CODE
      , GLOBAL_ATTRIBUTE_DATE_4
      , VENDOR_TYPE_LOOKUP_CODE
      , ALLOW_AWT_FLAG
      , GLOBAL_ATTRIBUTE_NUMBER_10
      , GLOBAL_ATTRIBUTE_TIMESTAMP_4
      , LAST_UPDATED_BY
      , PARENT_VENDOR_ID
      , ATTRIBUTE_NUMBER_2
      , EMPLOYEE_ID
      , GLOBAL_ATTRIBUTE_TIMESTAMP_1
      , GLOBAL_ATTRIBUTE_NUMBER_9
      , DF_TAXPAYER_COUNTRY
      , DF_INDUSTRY_SUB_CATEGORY_CODE
      , GLOBAL_ATTRIBUTE_7
      , GLOBAL_ATTRIBUTE_NUMBER_5
      , TAX_REPORTING_NAME
      , GLOBAL_ATTRIBUTE_13
      , GLOBAL_ATTRIBUTE_DATE_10
      , CHANGE_REQ_NUMBER
      , SET_OF_BOOKS_ID
      , CREATED_BY_REST_FLAG
      , GLOBAL_ATTRIBUTE_10
      , GLOBAL_ATTRIBUTE_DATE_2
      , ATTRIBUTE_TIMESTAMP_4
      , ATTRIBUTE_DATE_8
      , BANK_CHARGE_BEARER
      , ATTRIBUTE_DATE_7
      , JOB_DEFINITION_NAME
      , FEDERAL_REPORTABLE_FLAG
      , GLOBAL_ATTRIBUTE_16
      , TYPE_1099
      , GLOBAL_ATTRIBUTE_NUMBER_2
      , OBJECT_VERSION_NUMBER
      , SUMMARY_FLAG
      , ATTRIBUTE_NUMBER_8
      , TAX_VERIFICATION_DATE
      , ATTRIBUTE_NUMBER_10
      , GLOBAL_ATTRIBUTE_TIMESTAMP_2
      , OFFSET_TAX_FLAG
      , _FIVETRAN_DELETED
      , _FIVETRAN_SYNCED
      , PSA_LOAD_DTS
      , PSA_DELETE_IND
      , PSA_RECORD_SOURCE
      , REC_SRC
      , BKCC
      , HASHDIFF
    FROM SRC_SFIB
)
---- RENAME LAYER ----

, RENAME_SFIB as (
    SELECT
        SUPPLIER_HK
      , SEGMENT_1
      , VENDOR_ID
      , LOAD_DTS
      , ATTRIBUTE_TIMESTAMP_10
      , GLOBAL_ATTRIBUTE_20
      , WOMEN_OWNED_FLAG
      , GLOBAL_ATTRIBUTE_6
      , ATTRIBUTE_DATE_1
      , ATTRIBUTE_5
      , ATTRIBUTE_TIMESTAMP_7
      , GLOBAL_ATTRIBUTE_2
      , AMOUNT_INCLUDES_TAX_FLAG
      , GLOBAL_ATTRIBUTE_17
      , INCOME_TAX_ID_FLAG
      , ATTRIBUTE_TIMESTAMP_8
      , ATTRIBUTE_TIMESTAMP_1
      , ATTRIBUTE_CATEGORY
      , ENABLED_FLAG
      , ATTRIBUTE_12
      , ATTRIBUTE_NUMBER_4
      , CREATION_DATE
      , CREATION_SOURCE
      , NAME_CONTROL
      , AP_TAX_ROUNDING_RULE
      , MINORITY_GROUP_LOOKUP_CODE
      , BC_NOT_APPLICABLE_FLAG
      , END_DATE_ACTIVE
      , WITHHOLDING_START_DATE
      , GLOBAL_ATTRIBUTE_5
      , GLOBAL_ATTRIBUTE_3
      , ATTRIBUTE_DATE_2
      , SPEND_AUTH_REVIEW_STATUS
      , GLOBAL_ATTRIBUTE_DATE_8
      , GLOBAL_ATTRIBUTE_12
      , GLOBAL_ATTRIBUTE_DATE_5
      , LAST_UPDATE_DATE
      , DF_NAICS_CODE
      , ATTRIBUTE_19
      , WITHHOLDING_STATUS_LOOKUP_CODE
      , GLOBAL_ATTRIBUTE_15
      , ATTRIBUTE_DATE_6
      , GLOBAL_ATTRIBUTE_1
      , ATTRIBUTE_20
      , ATTRIBUTE_NUMBER_7
      , ATTRIBUTE_NUMBER_5
      , DF_LAST_SYNC_DATE
      , SPEND_AUTH_JUSTIFICATION
      , SUPPLIER_LOCKED_FLAG
      , GLOBAL_ATTRIBUTE_NUMBER_8
      , DATAFOX_COMPANY_ID
      , GLOBAL_ATTRIBUTE_NUMBER_7
      , GLOBAL_ATTRIBUTE_TIMESTAMP_7
      , ATTRIBUTE_TIMESTAMP_6
      , GLOBAL_ATTRIBUTE_8
      , ATTRIBUTE_2
      , ATTRIBUTE_11
      , AUTO_TAX_CALC_OVERRIDE
      , ATTRIBUTE_NUMBER_1
      , STANDARD_INDUSTRY_CLASS
      , CUSTOMER_NUM
      , CREATED_BY
      , GLOBAL_ATTRIBUTE_TIMESTAMP_5
      , ATTRIBUTE_18
      , ATTRIBUTE_9
      , PARTY_ID
      , DF_SCORE
      , JOB_DEFINITION_PACKAGE
      , ATTRIBUTE_TIMESTAMP_5
      , ATTRIBUTE_DATE_10
      , REVIEW_TYPE
      , PROGRAM_UPDATE_DATE
      , REBUILD_INDEX
      , ATTRIBUTE_NUMBER_6
      , PARENT_PARTY_ID
      , DF_LEGAL_NAME
      , ATTRIBUTE_8
      , MIN_ORDER_AMOUNT
      , ONE_TIME_FLAG
      , ATTRIBUTE_17
      , ATTRIBUTE_TIMESTAMP_2
      , VAT_REGISTRATION_NUM
      , ATTRIBUTE_15
      , GLOBAL_ATTRIBUTE_4
      , GLOBAL_ATTRIBUTE_DATE_7
      , GLOBAL_ATTRIBUTE_NUMBER_4
      , ATTRIBUTE_4
      , GLOBAL_ATTRIBUTE_11
      , GLOBAL_ATTRIBUTE_TIMESTAMP_8
      , OFFSET_VAT_CODE
      , DF_COMPANY_NAME
      , ATTRIBUTE_3
      , DENIED_PARTY_FLAG
      , SMALL_BUSINESS_FLAG
      , GLOBAL_ATTRIBUTE_TIMESTAMP_10
      , GLOBAL_ATTRIBUTE_DATE_3
      , BUSINESS_RELATIONSHIP
      , EXTERNAL_SYSTEM_ID
      , ATTRIBUTE_10
      , LAST_UPDATE_LOGIN
      , NI_NUMBER
      , DF_CORPORATE_WEBSITE
      , DF_INDUSTRY_CATEGORY_CODE
      , CORPORATE_WEBSITE
      , ATTRIBUTE_NUMBER_3
      , DF_LINKED_ADDRESS_ID
      , ATTRIBUTE_TIMESTAMP_3
      , AUTO_TAX_CALC_FLAG
      , GLOBAL_ATTRIBUTE_TIMESTAMP_9
      , START_DATE_ACTIVE
      , GLOBAL_ATTRIBUTE_14
      , GLOBAL_ATTRIBUTE_19
      , ATTRIBUTE_7
      , GLOBAL_ATTRIBUTE_TIMESTAMP_6
      , ORGANIZATION_TYPE_LOOKUP_CODE
      , GLOBAL_ATTRIBUTE_DATE_6
      , ATTRIBUTE_DATE_9
      , ATTRIBUTE_DATE_3
      , ATTRIBUTE_13
      , ATTRIBUTE_NUMBER_9
      , REQUEST_ID
      , GLOBAL_ATTRIBUTE_18
      , PROGRAM_ID
      , GLOBAL_ATTRIBUTE_TIMESTAMP_3
      , ATTRIBUTE_DATE_4
      , GLOBAL_ATTRIBUTE_CATEGORY
      , PROGRAM_APPLICATION_ID
      , GLOBAL_ATTRIBUTE_NUMBER_1
      , NI_NUMBER_FLAG
      , GLOBAL_ATTRIBUTE_NUMBER_3
      , GLOBAL_ATTRIBUTE_DATE_9
      , GLOBAL_ATTRIBUTE_DATE_1
      , GLOBAL_ATTRIBUTE_NUMBER_6
      , ATTRIBUTE_DATE_5
      , TAXPAYER_COUNTRY
      , AWT_GROUP_ID
      , ATTRIBUTE_6
      , OBN_MATCHED_STATUS
      , ATTRIBUTE_TIMESTAMP_9
      , STATE_REPORTABLE_FLAG
      , ATTRIBUTE_14
      , GLOBAL_ATTRIBUTE_9
      , ATTRIBUTE_16
      , EXTERNAL_SYSTEM
      , ATTRIBUTE_1
      , VAT_CODE
      , GLOBAL_ATTRIBUTE_DATE_4
      , VENDOR_TYPE_LOOKUP_CODE
      , ALLOW_AWT_FLAG
      , GLOBAL_ATTRIBUTE_NUMBER_10
      , GLOBAL_ATTRIBUTE_TIMESTAMP_4
      , LAST_UPDATED_BY
      , PARENT_VENDOR_ID
      , ATTRIBUTE_NUMBER_2
      , EMPLOYEE_ID
      , GLOBAL_ATTRIBUTE_TIMESTAMP_1
      , GLOBAL_ATTRIBUTE_NUMBER_9
      , DF_TAXPAYER_COUNTRY
      , DF_INDUSTRY_SUB_CATEGORY_CODE
      , GLOBAL_ATTRIBUTE_7
      , GLOBAL_ATTRIBUTE_NUMBER_5
      , TAX_REPORTING_NAME
      , GLOBAL_ATTRIBUTE_13
      , GLOBAL_ATTRIBUTE_DATE_10
      , CHANGE_REQ_NUMBER
      , SET_OF_BOOKS_ID
      , CREATED_BY_REST_FLAG
      , GLOBAL_ATTRIBUTE_10
      , GLOBAL_ATTRIBUTE_DATE_2
      , ATTRIBUTE_TIMESTAMP_4
      , ATTRIBUTE_DATE_8
      , BANK_CHARGE_BEARER
      , ATTRIBUTE_DATE_7
      , JOB_DEFINITION_NAME
      , FEDERAL_REPORTABLE_FLAG
      , GLOBAL_ATTRIBUTE_16
      , TYPE_1099
      , GLOBAL_ATTRIBUTE_NUMBER_2
      , OBJECT_VERSION_NUMBER
      , SUMMARY_FLAG
      , ATTRIBUTE_NUMBER_8
      , TAX_VERIFICATION_DATE
      , ATTRIBUTE_NUMBER_10
      , GLOBAL_ATTRIBUTE_TIMESTAMP_2
      , OFFSET_TAX_FLAG
      , _FIVETRAN_DELETED
      , _FIVETRAN_SYNCED
      , PSA_LOAD_DTS
      , PSA_DELETE_IND
      , PSA_RECORD_SOURCE
      , REC_SRC
      , BKCC
      , HASHDIFF
    FROM LOGIC_SFIB
)
---- FILTER LAYER ----

, FILTER_SFIB as (
    SELECT *
    FROM RENAME_SFIB
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM FILTER_SFIB
)

---- FINAL LAYER ----
SELECT
          SUPPLIER_HK
        , SEGMENT_1
        , VENDOR_ID
        , LOAD_DTS
        , ATTRIBUTE_TIMESTAMP_10
        , GLOBAL_ATTRIBUTE_20
        , WOMEN_OWNED_FLAG
        , GLOBAL_ATTRIBUTE_6
        , ATTRIBUTE_DATE_1
        , ATTRIBUTE_5
        , ATTRIBUTE_TIMESTAMP_7
        , GLOBAL_ATTRIBUTE_2
        , AMOUNT_INCLUDES_TAX_FLAG
        , GLOBAL_ATTRIBUTE_17
        , INCOME_TAX_ID_FLAG
        , ATTRIBUTE_TIMESTAMP_8
        , ATTRIBUTE_TIMESTAMP_1
        , ATTRIBUTE_CATEGORY
        , ENABLED_FLAG
        , ATTRIBUTE_12
        , ATTRIBUTE_NUMBER_4
        , CREATION_DATE
        , CREATION_SOURCE
        , NAME_CONTROL
        , AP_TAX_ROUNDING_RULE
        , MINORITY_GROUP_LOOKUP_CODE
        , BC_NOT_APPLICABLE_FLAG
        , END_DATE_ACTIVE
        , WITHHOLDING_START_DATE
        , GLOBAL_ATTRIBUTE_5
        , GLOBAL_ATTRIBUTE_3
        , ATTRIBUTE_DATE_2
        , SPEND_AUTH_REVIEW_STATUS
        , GLOBAL_ATTRIBUTE_DATE_8
        , GLOBAL_ATTRIBUTE_12
        , GLOBAL_ATTRIBUTE_DATE_5
        , LAST_UPDATE_DATE
        , DF_NAICS_CODE
        , ATTRIBUTE_19
        , WITHHOLDING_STATUS_LOOKUP_CODE
        , GLOBAL_ATTRIBUTE_15
        , ATTRIBUTE_DATE_6
        , GLOBAL_ATTRIBUTE_1
        , ATTRIBUTE_20
        , ATTRIBUTE_NUMBER_7
        , ATTRIBUTE_NUMBER_5
        , DF_LAST_SYNC_DATE
        , SPEND_AUTH_JUSTIFICATION
        , SUPPLIER_LOCKED_FLAG
        , GLOBAL_ATTRIBUTE_NUMBER_8
        , DATAFOX_COMPANY_ID
        , GLOBAL_ATTRIBUTE_NUMBER_7
        , GLOBAL_ATTRIBUTE_TIMESTAMP_7
        , ATTRIBUTE_TIMESTAMP_6
        , GLOBAL_ATTRIBUTE_8
        , ATTRIBUTE_2
        , ATTRIBUTE_11
        , AUTO_TAX_CALC_OVERRIDE
        , ATTRIBUTE_NUMBER_1
        , STANDARD_INDUSTRY_CLASS
        , CUSTOMER_NUM
        , CREATED_BY
        , GLOBAL_ATTRIBUTE_TIMESTAMP_5
        , ATTRIBUTE_18
        , ATTRIBUTE_9
        , PARTY_ID
        , DF_SCORE
        , JOB_DEFINITION_PACKAGE
        , ATTRIBUTE_TIMESTAMP_5
        , ATTRIBUTE_DATE_10
        , REVIEW_TYPE
        , PROGRAM_UPDATE_DATE
        , REBUILD_INDEX
        , ATTRIBUTE_NUMBER_6
        , PARENT_PARTY_ID
        , DF_LEGAL_NAME
        , ATTRIBUTE_8
        , MIN_ORDER_AMOUNT
        , ONE_TIME_FLAG
        , ATTRIBUTE_17
        , ATTRIBUTE_TIMESTAMP_2
        , VAT_REGISTRATION_NUM
        , ATTRIBUTE_15
        , GLOBAL_ATTRIBUTE_4
        , GLOBAL_ATTRIBUTE_DATE_7
        , GLOBAL_ATTRIBUTE_NUMBER_4
        , ATTRIBUTE_4
        , GLOBAL_ATTRIBUTE_11
        , GLOBAL_ATTRIBUTE_TIMESTAMP_8
        , OFFSET_VAT_CODE
        , DF_COMPANY_NAME
        , ATTRIBUTE_3
        , DENIED_PARTY_FLAG
        , SMALL_BUSINESS_FLAG
        , GLOBAL_ATTRIBUTE_TIMESTAMP_10
        , GLOBAL_ATTRIBUTE_DATE_3
        , BUSINESS_RELATIONSHIP
        , EXTERNAL_SYSTEM_ID
        , ATTRIBUTE_10
        , LAST_UPDATE_LOGIN
        , NI_NUMBER
        , DF_CORPORATE_WEBSITE
        , DF_INDUSTRY_CATEGORY_CODE
        , CORPORATE_WEBSITE
        , ATTRIBUTE_NUMBER_3
        , DF_LINKED_ADDRESS_ID
        , ATTRIBUTE_TIMESTAMP_3
        , AUTO_TAX_CALC_FLAG
        , GLOBAL_ATTRIBUTE_TIMESTAMP_9
        , START_DATE_ACTIVE
        , GLOBAL_ATTRIBUTE_14
        , GLOBAL_ATTRIBUTE_19
        , ATTRIBUTE_7
        , GLOBAL_ATTRIBUTE_TIMESTAMP_6
        , ORGANIZATION_TYPE_LOOKUP_CODE
        , GLOBAL_ATTRIBUTE_DATE_6
        , ATTRIBUTE_DATE_9
        , ATTRIBUTE_DATE_3
        , ATTRIBUTE_13
        , ATTRIBUTE_NUMBER_9
        , REQUEST_ID
        , GLOBAL_ATTRIBUTE_18
        , PROGRAM_ID
        , GLOBAL_ATTRIBUTE_TIMESTAMP_3
        , ATTRIBUTE_DATE_4
        , GLOBAL_ATTRIBUTE_CATEGORY
        , PROGRAM_APPLICATION_ID
        , GLOBAL_ATTRIBUTE_NUMBER_1
        , NI_NUMBER_FLAG
        , GLOBAL_ATTRIBUTE_NUMBER_3
        , GLOBAL_ATTRIBUTE_DATE_9
        , GLOBAL_ATTRIBUTE_DATE_1
        , GLOBAL_ATTRIBUTE_NUMBER_6
        , ATTRIBUTE_DATE_5
        , TAXPAYER_COUNTRY
        , AWT_GROUP_ID
        , ATTRIBUTE_6
        , OBN_MATCHED_STATUS
        , ATTRIBUTE_TIMESTAMP_9
        , STATE_REPORTABLE_FLAG
        , ATTRIBUTE_14
        , GLOBAL_ATTRIBUTE_9
        , ATTRIBUTE_16
        , EXTERNAL_SYSTEM
        , ATTRIBUTE_1
        , VAT_CODE
        , GLOBAL_ATTRIBUTE_DATE_4
        , VENDOR_TYPE_LOOKUP_CODE
        , ALLOW_AWT_FLAG
        , GLOBAL_ATTRIBUTE_NUMBER_10
        , GLOBAL_ATTRIBUTE_TIMESTAMP_4
        , LAST_UPDATED_BY
        , PARENT_VENDOR_ID
        , ATTRIBUTE_NUMBER_2
        , EMPLOYEE_ID
        , GLOBAL_ATTRIBUTE_TIMESTAMP_1
        , GLOBAL_ATTRIBUTE_NUMBER_9
        , DF_TAXPAYER_COUNTRY
        , DF_INDUSTRY_SUB_CATEGORY_CODE
        , GLOBAL_ATTRIBUTE_7
        , GLOBAL_ATTRIBUTE_NUMBER_5
        , TAX_REPORTING_NAME
        , GLOBAL_ATTRIBUTE_13
        , GLOBAL_ATTRIBUTE_DATE_10
        , CHANGE_REQ_NUMBER
        , SET_OF_BOOKS_ID
        , CREATED_BY_REST_FLAG
        , GLOBAL_ATTRIBUTE_10
        , GLOBAL_ATTRIBUTE_DATE_2
        , ATTRIBUTE_TIMESTAMP_4
        , ATTRIBUTE_DATE_8
        , BANK_CHARGE_BEARER
        , ATTRIBUTE_DATE_7
        , JOB_DEFINITION_NAME
        , FEDERAL_REPORTABLE_FLAG
        , GLOBAL_ATTRIBUTE_16
        , TYPE_1099
        , GLOBAL_ATTRIBUTE_NUMBER_2
        , OBJECT_VERSION_NUMBER
        , SUMMARY_FLAG
        , ATTRIBUTE_NUMBER_8
        , TAX_VERIFICATION_DATE
        , ATTRIBUTE_NUMBER_10
        , GLOBAL_ATTRIBUTE_TIMESTAMP_2
        , OFFSET_TAX_FLAG
        , _FIVETRAN_DELETED
        , _FIVETRAN_SYNCED
        , PSA_LOAD_DTS
        , PSA_DELETE_IND
        , PSA_RECORD_SOURCE
        , REC_SRC
        , BKCC
        , HASHDIFF
FROM JOIN_RESULT
{% if is_incremental() %}
WHERE NOT EXISTS (
    SELECT 1 
    FROM {{ this }} existing
    WHERE existing.SUPPLIER_HK = JOIN_RESULT.SUPPLIER_HK 
    AND existing.HASHDIFF = JOIN_RESULT.HASHDIFF
)
{% endif %}
{% if not is_incremental() %}

/* The following qualifier is implemented to prevent multiple loads of touched records during the initial build, such as multiple rows per HK and hashdiff. */
qualify 1 = row_number() over (partition by SUPPLIER_HK, HASHDIFF order by PSA_LOAD_DTS)

union all
SELECT 
MD5_BINARY(GR.VALUE) AS SUPPLIER_HK,
GR.VALUE::text AS SEGMENT_1,
NULL AS VENDOR_ID,
CONVERT_TIMEZONE('UTC','1900-01-01'::TIMESTAMP) AS LOAD_DTS,
NULL AS ATTRIBUTE_TIMESTAMP_10,
NULL AS GLOBAL_ATTRIBUTE_20,
NULL AS WOMEN_OWNED_FLAG,
NULL AS GLOBAL_ATTRIBUTE_6,
NULL AS ATTRIBUTE_DATE_1,
NULL AS ATTRIBUTE_5,
NULL AS ATTRIBUTE_TIMESTAMP_7,
NULL AS GLOBAL_ATTRIBUTE_2,
NULL AS AMOUNT_INCLUDES_TAX_FLAG,
NULL AS GLOBAL_ATTRIBUTE_17,
NULL AS INCOME_TAX_ID_FLAG,
NULL AS ATTRIBUTE_TIMESTAMP_8,
NULL AS ATTRIBUTE_TIMESTAMP_1,
NULL AS ATTRIBUTE_CATEGORY,
NULL AS ENABLED_FLAG,
NULL AS ATTRIBUTE_12,
NULL AS ATTRIBUTE_NUMBER_4,
NULL AS CREATION_DATE,
NULL AS CREATION_SOURCE,
NULL AS NAME_CONTROL,
NULL AS AP_TAX_ROUNDING_RULE,
NULL AS MINORITY_GROUP_LOOKUP_CODE,
NULL AS BC_NOT_APPLICABLE_FLAG,
NULL AS END_DATE_ACTIVE,
NULL AS WITHHOLDING_START_DATE,
NULL AS GLOBAL_ATTRIBUTE_5,
NULL AS GLOBAL_ATTRIBUTE_3,
NULL AS ATTRIBUTE_DATE_2,
NULL AS SPEND_AUTH_REVIEW_STATUS,
NULL AS GLOBAL_ATTRIBUTE_DATE_8,
NULL AS GLOBAL_ATTRIBUTE_12,
NULL AS GLOBAL_ATTRIBUTE_DATE_5,
NULL AS LAST_UPDATE_DATE,
NULL AS DF_NAICS_CODE,
NULL AS ATTRIBUTE_19,
NULL AS WITHHOLDING_STATUS_LOOKUP_CODE,
NULL AS GLOBAL_ATTRIBUTE_15,
NULL AS ATTRIBUTE_DATE_6,
NULL AS GLOBAL_ATTRIBUTE_1,
NULL AS ATTRIBUTE_20,
NULL AS ATTRIBUTE_NUMBER_7,
NULL AS ATTRIBUTE_NUMBER_5,
NULL AS DF_LAST_SYNC_DATE,
NULL AS SPEND_AUTH_JUSTIFICATION,
NULL AS SUPPLIER_LOCKED_FLAG,
NULL AS GLOBAL_ATTRIBUTE_NUMBER_8,
NULL AS DATAFOX_COMPANY_ID,
NULL AS GLOBAL_ATTRIBUTE_NUMBER_7,
NULL AS GLOBAL_ATTRIBUTE_TIMESTAMP_7,
NULL AS ATTRIBUTE_TIMESTAMP_6,
NULL AS GLOBAL_ATTRIBUTE_8,
NULL AS ATTRIBUTE_2,
NULL AS ATTRIBUTE_11,
NULL AS AUTO_TAX_CALC_OVERRIDE,
NULL AS ATTRIBUTE_NUMBER_1,
NULL AS STANDARD_INDUSTRY_CLASS,
NULL AS CUSTOMER_NUM,
NULL AS CREATED_BY,
NULL AS GLOBAL_ATTRIBUTE_TIMESTAMP_5,
NULL AS ATTRIBUTE_18,
NULL AS ATTRIBUTE_9,
NULL AS PARTY_ID,
NULL AS DF_SCORE,
NULL AS JOB_DEFINITION_PACKAGE,
NULL AS ATTRIBUTE_TIMESTAMP_5,
NULL AS ATTRIBUTE_DATE_10,
NULL AS REVIEW_TYPE,
NULL AS PROGRAM_UPDATE_DATE,
NULL AS REBUILD_INDEX,
NULL AS ATTRIBUTE_NUMBER_6,
NULL AS PARENT_PARTY_ID,
NULL AS DF_LEGAL_NAME,
NULL AS ATTRIBUTE_8,
NULL AS MIN_ORDER_AMOUNT,
NULL AS ONE_TIME_FLAG,
NULL AS ATTRIBUTE_17,
NULL AS ATTRIBUTE_TIMESTAMP_2,
NULL AS VAT_REGISTRATION_NUM,
NULL AS ATTRIBUTE_15,
NULL AS GLOBAL_ATTRIBUTE_4,
NULL AS GLOBAL_ATTRIBUTE_DATE_7,
NULL AS GLOBAL_ATTRIBUTE_NUMBER_4,
NULL AS ATTRIBUTE_4,
NULL AS GLOBAL_ATTRIBUTE_11,
NULL AS GLOBAL_ATTRIBUTE_TIMESTAMP_8,
NULL AS OFFSET_VAT_CODE,
NULL AS DF_COMPANY_NAME,
NULL AS ATTRIBUTE_3,
NULL AS DENIED_PARTY_FLAG,
NULL AS SMALL_BUSINESS_FLAG,
NULL AS GLOBAL_ATTRIBUTE_TIMESTAMP_10,
NULL AS GLOBAL_ATTRIBUTE_DATE_3,
NULL AS BUSINESS_RELATIONSHIP,
NULL AS EXTERNAL_SYSTEM_ID,
NULL AS ATTRIBUTE_10,
NULL AS LAST_UPDATE_LOGIN,
NULL AS NI_NUMBER,
NULL AS DF_CORPORATE_WEBSITE,
NULL AS DF_INDUSTRY_CATEGORY_CODE,
NULL AS CORPORATE_WEBSITE,
NULL AS ATTRIBUTE_NUMBER_3,
NULL AS DF_LINKED_ADDRESS_ID,
NULL AS ATTRIBUTE_TIMESTAMP_3,
NULL AS AUTO_TAX_CALC_FLAG,
NULL AS GLOBAL_ATTRIBUTE_TIMESTAMP_9,
NULL AS START_DATE_ACTIVE,
NULL AS GLOBAL_ATTRIBUTE_14,
NULL AS GLOBAL_ATTRIBUTE_19,
NULL AS ATTRIBUTE_7,
NULL AS GLOBAL_ATTRIBUTE_TIMESTAMP_6,
NULL AS ORGANIZATION_TYPE_LOOKUP_CODE,
NULL AS GLOBAL_ATTRIBUTE_DATE_6,
NULL AS ATTRIBUTE_DATE_9,
NULL AS ATTRIBUTE_DATE_3,
NULL AS ATTRIBUTE_13,
NULL AS ATTRIBUTE_NUMBER_9,
NULL AS REQUEST_ID,
NULL AS GLOBAL_ATTRIBUTE_18,
NULL AS PROGRAM_ID,
NULL AS GLOBAL_ATTRIBUTE_TIMESTAMP_3,
NULL AS ATTRIBUTE_DATE_4,
NULL AS GLOBAL_ATTRIBUTE_CATEGORY,
NULL AS PROGRAM_APPLICATION_ID,
NULL AS GLOBAL_ATTRIBUTE_NUMBER_1,
NULL AS NI_NUMBER_FLAG,
NULL AS GLOBAL_ATTRIBUTE_NUMBER_3,
NULL AS GLOBAL_ATTRIBUTE_DATE_9,
NULL AS GLOBAL_ATTRIBUTE_DATE_1,
NULL AS GLOBAL_ATTRIBUTE_NUMBER_6,
NULL AS ATTRIBUTE_DATE_5,
NULL AS TAXPAYER_COUNTRY,
NULL AS AWT_GROUP_ID,
NULL AS ATTRIBUTE_6,
NULL AS OBN_MATCHED_STATUS,
NULL AS ATTRIBUTE_TIMESTAMP_9,
NULL AS STATE_REPORTABLE_FLAG,
NULL AS ATTRIBUTE_14,
NULL AS GLOBAL_ATTRIBUTE_9,
NULL AS ATTRIBUTE_16,
NULL AS EXTERNAL_SYSTEM,
NULL AS ATTRIBUTE_1,
NULL AS VAT_CODE,
NULL AS GLOBAL_ATTRIBUTE_DATE_4,
NULL AS VENDOR_TYPE_LOOKUP_CODE,
NULL AS ALLOW_AWT_FLAG,
NULL AS GLOBAL_ATTRIBUTE_NUMBER_10,
NULL AS GLOBAL_ATTRIBUTE_TIMESTAMP_4,
NULL AS LAST_UPDATED_BY,
NULL AS PARENT_VENDOR_ID,
NULL AS ATTRIBUTE_NUMBER_2,
NULL AS EMPLOYEE_ID,
NULL AS GLOBAL_ATTRIBUTE_TIMESTAMP_1,
NULL AS GLOBAL_ATTRIBUTE_NUMBER_9,
NULL AS DF_TAXPAYER_COUNTRY,
NULL AS DF_INDUSTRY_SUB_CATEGORY_CODE,
NULL AS GLOBAL_ATTRIBUTE_7,
NULL AS GLOBAL_ATTRIBUTE_NUMBER_5,
NULL AS TAX_REPORTING_NAME,
NULL AS GLOBAL_ATTRIBUTE_13,
NULL AS GLOBAL_ATTRIBUTE_DATE_10,
NULL AS CHANGE_REQ_NUMBER,
NULL AS SET_OF_BOOKS_ID,
NULL AS CREATED_BY_REST_FLAG,
NULL AS GLOBAL_ATTRIBUTE_10,
NULL AS GLOBAL_ATTRIBUTE_DATE_2,
NULL AS ATTRIBUTE_TIMESTAMP_4,
NULL AS ATTRIBUTE_DATE_8,
NULL AS BANK_CHARGE_BEARER,
NULL AS ATTRIBUTE_DATE_7,
NULL AS JOB_DEFINITION_NAME,
NULL AS FEDERAL_REPORTABLE_FLAG,
NULL AS GLOBAL_ATTRIBUTE_16,
NULL AS TYPE_1099,
NULL AS GLOBAL_ATTRIBUTE_NUMBER_2,
NULL AS OBJECT_VERSION_NUMBER,
NULL AS SUMMARY_FLAG,
NULL AS ATTRIBUTE_NUMBER_8,
NULL AS TAX_VERIFICATION_DATE,
NULL AS ATTRIBUTE_NUMBER_10,
NULL AS GLOBAL_ATTRIBUTE_TIMESTAMP_2,
NULL AS OFFSET_TAX_FLAG,
NULL AS _FIVETRAN_DELETED,
NULL AS _FIVETRAN_SYNCED,
'1900-01-01'::TIMESTAMP AS PSA_LOAD_DTS,
'N' AS PSA_DELETE_IND,
NULL AS PSA_RECORD_SOURCE,
'USAZET.SNOWFLAKE.FBIN.DERIVED' AS REC_SRC,
DECODE(GR.VALUE, 0, 'GHOST RECORD-SYSTEM', -1, 'GHOST RECORD-nullkey-required', -2, 'GHOST RECORD-nullkey-optional') AS BKCC,
''::BINARY AS HASHDIFF
FROM
TABLE(strtok_split_to_table('0|-1|-2', '|')) AS GR
{% endif %}
