---- SRC LAYER ----
WITH
SRC_SRC            as ( SELECT * FROM {{ ref('v_psa_stg_supplier_invoice__emtk_ebs') }} as SRC 
{% if is_incremental() %}
      where src.load_dts > (select dateadd('HOUR',-1,max(load_dts)) from {{ this }})
    {% endif %} )

/*
SRC_SRC            as ( SELECT * FROM int_staging_views.v_psa_stg_supplier_invoice__emtk_ebs )
*/
---- LOGIC LAYER ----

, LOGIC_SRC as (
    SELECT
        SUPPLIER_INVOICE_HK
      , INVOICE_ID
      , LAST_UPDATE_DATE
      , LAST_UPDATED_BY
      , VENDOR_ID
      , INVOICE_NUM
      , SET_OF_BOOKS_ID
      , INVOICE_CURRENCY_CODE
      , PAYMENT_CURRENCY_CODE
      , PAYMENT_CROSS_RATE
      , INVOICE_AMOUNT
      , VENDOR_SITE_ID
      , AMOUNT_PAID
      , DISCOUNT_AMOUNT_TAKEN
      , INVOICE_DATE
      , SOURCE
      , INVOICE_TYPE_LOOKUP_CODE
      , DESCRIPTION
      , BATCH_ID
      , AMOUNT_APPLICABLE_TO_DISCOUNT
      , TAX_AMOUNT
      , TERMS_ID
      , TERMS_DATE
      , PAYMENT_METHOD_LOOKUP_CODE
      , ACCTS_PAY_CODE_COMBINATION_ID
      , PAYMENT_STATUS_FLAG
      , CREATION_DATE
      , CREATED_BY
      , BASE_AMOUNT
      , VAT_CODE
      , LAST_UPDATE_LOGIN
      , EXCLUSIVE_PAYMENT_FLAG
      , PO_HEADER_ID
      , FREIGHT_AMOUNT
      , GOODS_RECEIVED_DATE
      , INVOICE_RECEIVED_DATE
      , VOUCHER_NUM
      , APPROVED_AMOUNT
      , RECURRING_PAYMENT_ID
      , EXCHANGE_RATE
      , EXCHANGE_RATE_TYPE
      , EXCHANGE_DATE
      , EARLIEST_SETTLEMENT_DATE
      , ORIGINAL_PREPAYMENT_AMOUNT
      , DOC_SEQUENCE_ID
      , DOC_SEQUENCE_VALUE
      , DOC_CATEGORY_CODE
      , ATTRIBUTE1
      , ATTRIBUTE2
      , ATTRIBUTE3
      , ATTRIBUTE4
      , ATTRIBUTE5
      , ATTRIBUTE6
      , ATTRIBUTE7
      , ATTRIBUTE8
      , ATTRIBUTE9
      , ATTRIBUTE10
      , ATTRIBUTE11
      , ATTRIBUTE12
      , ATTRIBUTE13
      , ATTRIBUTE14
      , ATTRIBUTE15
      , ATTRIBUTE_CATEGORY
      , APPROVAL_STATUS
      , APPROVAL_DESCRIPTION
      , INVOICE_DISTRIBUTION_TOTAL
      , POSTING_STATUS
      , PREPAY_FLAG
      , AUTHORIZED_BY
      , CANCELLED_DATE
      , CANCELLED_BY
      , CANCELLED_AMOUNT
      , TEMP_CANCELLED_AMOUNT
      , PROJECT_ACCOUNTING_CONTEXT
      , USSGL_TRANSACTION_CODE
      , USSGL_TRX_CODE_CONTEXT
      , PROJECT_ID
      , TASK_ID
      , EXPENDITURE_TYPE
      , EXPENDITURE_ITEM_DATE
      , PA_QUANTITY
      , EXPENDITURE_ORGANIZATION_ID
      , PA_DEFAULT_DIST_CCID
      , VENDOR_PREPAY_AMOUNT
      , PAYMENT_AMOUNT_TOTAL
      , AWT_FLAG
      , AWT_GROUP_ID
      , REFERENCE_1
      , REFERENCE_2
      , ORG_ID
      , PRE_WITHHOLDING_AMOUNT
      , GLOBAL_ATTRIBUTE_CATEGORY
      , GLOBAL_ATTRIBUTE1
      , GLOBAL_ATTRIBUTE2
      , GLOBAL_ATTRIBUTE3
      , GLOBAL_ATTRIBUTE4
      , GLOBAL_ATTRIBUTE5
      , GLOBAL_ATTRIBUTE6
      , GLOBAL_ATTRIBUTE7
      , GLOBAL_ATTRIBUTE8
      , GLOBAL_ATTRIBUTE9
      , GLOBAL_ATTRIBUTE10
      , GLOBAL_ATTRIBUTE11
      , GLOBAL_ATTRIBUTE12
      , GLOBAL_ATTRIBUTE13
      , GLOBAL_ATTRIBUTE14
      , GLOBAL_ATTRIBUTE15
      , GLOBAL_ATTRIBUTE16
      , GLOBAL_ATTRIBUTE17
      , GLOBAL_ATTRIBUTE18
      , GLOBAL_ATTRIBUTE19
      , GLOBAL_ATTRIBUTE20
      , AUTO_TAX_CALC_FLAG
      , PAYMENT_CROSS_RATE_TYPE
      , PAYMENT_CROSS_RATE_DATE
      , PAY_CURR_INVOICE_AMOUNT
      , MRC_BASE_AMOUNT
      , MRC_EXCHANGE_RATE
      , MRC_EXCHANGE_RATE_TYPE
      , MRC_EXCHANGE_DATE
      , GL_DATE
      , AWARD_ID
      , PAID_ON_BEHALF_EMPLOYEE_ID
      , AMT_DUE_CCARD_COMPANY
      , AMT_DUE_EMPLOYEE
      , APPROVAL_READY_FLAG
      , APPROVAL_ITERATION
      , WFAPPROVAL_STATUS
      , REQUESTER_ID
      , VALIDATION_REQUEST_ID
      , VALIDATED_TAX_AMOUNT
      , QUICK_CREDIT
      , CREDITED_INVOICE_ID
      , DISTRIBUTION_SET_ID
      , APPLICATION_ID
      , PRODUCT_TABLE
      , REFERENCE_KEY1
      , REFERENCE_KEY2
      , REFERENCE_KEY3
      , REFERENCE_KEY4
      , REFERENCE_KEY5
      , TOTAL_TAX_AMOUNT
      , SELF_ASSESSED_TAX_AMOUNT
      , TAX_RELATED_INVOICE_ID
      , TRX_BUSINESS_CATEGORY
      , USER_DEFINED_FISC_CLASS
      , TAXATION_COUNTRY
      , DOCUMENT_SUB_TYPE
      , SUPPLIER_TAX_INVOICE_NUMBER
      , SUPPLIER_TAX_INVOICE_DATE
      , SUPPLIER_TAX_EXCHANGE_RATE
      , TAX_INVOICE_RECORDING_DATE
      , TAX_INVOICE_INTERNAL_SEQ
      , LEGAL_ENTITY_ID
      , HISTORICAL_FLAG
      , FORCE_REVALIDATION_FLAG
      , BANK_CHARGE_BEARER
      , REMITTANCE_MESSAGE1
      , REMITTANCE_MESSAGE2
      , REMITTANCE_MESSAGE3
      , UNIQUE_REMITTANCE_IDENTIFIER
      , URI_CHECK_DIGIT
      , SETTLEMENT_PRIORITY
      , PAYMENT_REASON_CODE
      , PAYMENT_REASON_COMMENTS
      , PAYMENT_METHOD_CODE
      , DELIVERY_CHANNEL_CODE
      , QUICK_PO_HEADER_ID
      , NET_OF_RETAINAGE_FLAG
      , RELEASE_AMOUNT_NET_OF_TAX
      , CONTROL_AMOUNT
      , PARTY_ID
      , PARTY_SITE_ID
      , PAY_PROC_TRXN_TYPE_CODE
      , PAYMENT_FUNCTION
      , CUST_REGISTRATION_CODE
      , CUST_REGISTRATION_NUMBER
      , PORT_OF_ENTRY_CODE
      , EXTERNAL_BANK_ACCOUNT_ID
      , VENDOR_CONTACT_ID
      , INTERNAL_CONTACT_EMAIL
      , DISC_IS_INV_LESS_TAX_FLAG
      , EXCLUDE_FREIGHT_FROM_DISCOUNT
      , PAY_AWT_GROUP_ID
      , REMIT_TO_SUPPLIER_NAME
      , REMIT_TO_SUPPLIER_ID
      , REMIT_TO_SUPPLIER_SITE
      , REMIT_TO_SUPPLIER_SITE_ID
      , RELATIONSHIP_ID
      , ORIGINAL_INVOICE_AMOUNT
      , DISPUTE_REASON
      , PO_MATCHED_FLAG
      , VALIDATION_WORKER_ID
      , PAY_GROUP_LOOKUP_CODE_1
      , PSA_DELETE_IND
      , PSA_LOAD_DTS
      , PSA_RECORD_SOURCE
      , _FIVETRAN_SYNCED
      , _FIVETRAN_ID
      , _FIVETRAN_DELETED
      , LOAD_DTS
      , REC_SRC
      , BKCC
      , HASHDIFF
    FROM SRC_SRC
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM LOGIC_SRC
)

---- FINAL LAYER ----
SELECT
          SUPPLIER_INVOICE_HK
        , INVOICE_ID
        , LAST_UPDATE_DATE
        , LAST_UPDATED_BY
        , VENDOR_ID
        , INVOICE_NUM
        , SET_OF_BOOKS_ID
        , INVOICE_CURRENCY_CODE
        , PAYMENT_CURRENCY_CODE
        , PAYMENT_CROSS_RATE
        , INVOICE_AMOUNT
        , VENDOR_SITE_ID
        , AMOUNT_PAID
        , DISCOUNT_AMOUNT_TAKEN
        , INVOICE_DATE
        , SOURCE
        , INVOICE_TYPE_LOOKUP_CODE
        , DESCRIPTION
        , BATCH_ID
        , AMOUNT_APPLICABLE_TO_DISCOUNT
        , TAX_AMOUNT
        , TERMS_ID
        , TERMS_DATE
        , PAYMENT_METHOD_LOOKUP_CODE
        , ACCTS_PAY_CODE_COMBINATION_ID
        , PAYMENT_STATUS_FLAG
        , CREATION_DATE
        , CREATED_BY
        , BASE_AMOUNT
        , VAT_CODE
        , LAST_UPDATE_LOGIN
        , EXCLUSIVE_PAYMENT_FLAG
        , PO_HEADER_ID
        , FREIGHT_AMOUNT
        , GOODS_RECEIVED_DATE
        , INVOICE_RECEIVED_DATE
        , VOUCHER_NUM
        , APPROVED_AMOUNT
        , RECURRING_PAYMENT_ID
        , EXCHANGE_RATE
        , EXCHANGE_RATE_TYPE
        , EXCHANGE_DATE
        , EARLIEST_SETTLEMENT_DATE
        , ORIGINAL_PREPAYMENT_AMOUNT
        , DOC_SEQUENCE_ID
        , DOC_SEQUENCE_VALUE
        , DOC_CATEGORY_CODE
        , ATTRIBUTE1
        , ATTRIBUTE2
        , ATTRIBUTE3
        , ATTRIBUTE4
        , ATTRIBUTE5
        , ATTRIBUTE6
        , ATTRIBUTE7
        , ATTRIBUTE8
        , ATTRIBUTE9
        , ATTRIBUTE10
        , ATTRIBUTE11
        , ATTRIBUTE12
        , ATTRIBUTE13
        , ATTRIBUTE14
        , ATTRIBUTE15
        , ATTRIBUTE_CATEGORY
        , APPROVAL_STATUS
        , APPROVAL_DESCRIPTION
        , INVOICE_DISTRIBUTION_TOTAL
        , POSTING_STATUS
        , PREPAY_FLAG
        , AUTHORIZED_BY
        , CANCELLED_DATE
        , CANCELLED_BY
        , CANCELLED_AMOUNT
        , TEMP_CANCELLED_AMOUNT
        , PROJECT_ACCOUNTING_CONTEXT
        , USSGL_TRANSACTION_CODE
        , USSGL_TRX_CODE_CONTEXT
        , PROJECT_ID
        , TASK_ID
        , EXPENDITURE_TYPE
        , EXPENDITURE_ITEM_DATE
        , PA_QUANTITY
        , EXPENDITURE_ORGANIZATION_ID
        , PA_DEFAULT_DIST_CCID
        , VENDOR_PREPAY_AMOUNT
        , PAYMENT_AMOUNT_TOTAL
        , AWT_FLAG
        , AWT_GROUP_ID
        , REFERENCE_1
        , REFERENCE_2
        , ORG_ID
        , PRE_WITHHOLDING_AMOUNT
        , GLOBAL_ATTRIBUTE_CATEGORY
        , GLOBAL_ATTRIBUTE1
        , GLOBAL_ATTRIBUTE2
        , GLOBAL_ATTRIBUTE3
        , GLOBAL_ATTRIBUTE4
        , GLOBAL_ATTRIBUTE5
        , GLOBAL_ATTRIBUTE6
        , GLOBAL_ATTRIBUTE7
        , GLOBAL_ATTRIBUTE8
        , GLOBAL_ATTRIBUTE9
        , GLOBAL_ATTRIBUTE10
        , GLOBAL_ATTRIBUTE11
        , GLOBAL_ATTRIBUTE12
        , GLOBAL_ATTRIBUTE13
        , GLOBAL_ATTRIBUTE14
        , GLOBAL_ATTRIBUTE15
        , GLOBAL_ATTRIBUTE16
        , GLOBAL_ATTRIBUTE17
        , GLOBAL_ATTRIBUTE18
        , GLOBAL_ATTRIBUTE19
        , GLOBAL_ATTRIBUTE20
        , AUTO_TAX_CALC_FLAG
        , PAYMENT_CROSS_RATE_TYPE
        , PAYMENT_CROSS_RATE_DATE
        , PAY_CURR_INVOICE_AMOUNT
        , MRC_BASE_AMOUNT
        , MRC_EXCHANGE_RATE
        , MRC_EXCHANGE_RATE_TYPE
        , MRC_EXCHANGE_DATE
        , GL_DATE
        , AWARD_ID
        , PAID_ON_BEHALF_EMPLOYEE_ID
        , AMT_DUE_CCARD_COMPANY
        , AMT_DUE_EMPLOYEE
        , APPROVAL_READY_FLAG
        , APPROVAL_ITERATION
        , WFAPPROVAL_STATUS
        , REQUESTER_ID
        , VALIDATION_REQUEST_ID
        , VALIDATED_TAX_AMOUNT
        , QUICK_CREDIT
        , CREDITED_INVOICE_ID
        , DISTRIBUTION_SET_ID
        , APPLICATION_ID
        , PRODUCT_TABLE
        , REFERENCE_KEY1
        , REFERENCE_KEY2
        , REFERENCE_KEY3
        , REFERENCE_KEY4
        , REFERENCE_KEY5
        , TOTAL_TAX_AMOUNT
        , SELF_ASSESSED_TAX_AMOUNT
        , TAX_RELATED_INVOICE_ID
        , TRX_BUSINESS_CATEGORY
        , USER_DEFINED_FISC_CLASS
        , TAXATION_COUNTRY
        , DOCUMENT_SUB_TYPE
        , SUPPLIER_TAX_INVOICE_NUMBER
        , SUPPLIER_TAX_INVOICE_DATE
        , SUPPLIER_TAX_EXCHANGE_RATE
        , TAX_INVOICE_RECORDING_DATE
        , TAX_INVOICE_INTERNAL_SEQ
        , LEGAL_ENTITY_ID
        , HISTORICAL_FLAG
        , FORCE_REVALIDATION_FLAG
        , BANK_CHARGE_BEARER
        , REMITTANCE_MESSAGE1
        , REMITTANCE_MESSAGE2
        , REMITTANCE_MESSAGE3
        , UNIQUE_REMITTANCE_IDENTIFIER
        , URI_CHECK_DIGIT
        , SETTLEMENT_PRIORITY
        , PAYMENT_REASON_CODE
        , PAYMENT_REASON_COMMENTS
        , PAYMENT_METHOD_CODE
        , DELIVERY_CHANNEL_CODE
        , QUICK_PO_HEADER_ID
        , NET_OF_RETAINAGE_FLAG
        , RELEASE_AMOUNT_NET_OF_TAX
        , CONTROL_AMOUNT
        , PARTY_ID
        , PARTY_SITE_ID
        , PAY_PROC_TRXN_TYPE_CODE
        , PAYMENT_FUNCTION
        , CUST_REGISTRATION_CODE
        , CUST_REGISTRATION_NUMBER
        , PORT_OF_ENTRY_CODE
        , EXTERNAL_BANK_ACCOUNT_ID
        , VENDOR_CONTACT_ID
        , INTERNAL_CONTACT_EMAIL
        , DISC_IS_INV_LESS_TAX_FLAG
        , EXCLUDE_FREIGHT_FROM_DISCOUNT
        , PAY_AWT_GROUP_ID
        , REMIT_TO_SUPPLIER_NAME
        , REMIT_TO_SUPPLIER_ID
        , REMIT_TO_SUPPLIER_SITE
        , REMIT_TO_SUPPLIER_SITE_ID
        , RELATIONSHIP_ID
        , ORIGINAL_INVOICE_AMOUNT
        , DISPUTE_REASON
        , PO_MATCHED_FLAG
        , VALIDATION_WORKER_ID
        , PAY_GROUP_LOOKUP_CODE_1
        , PSA_DELETE_IND
        , PSA_LOAD_DTS
        , PSA_RECORD_SOURCE
        , _FIVETRAN_SYNCED
        , _FIVETRAN_ID
        , _FIVETRAN_DELETED
        , LOAD_DTS
        , REC_SRC
        , BKCC
        , HASHDIFF
FROM JOIN_RESULT
{% if is_incremental() %}
WHERE NOT EXISTS (
    SELECT 1
    FROM {{ this }} existing
    WHERE existing.SUPPLIER_INVOICE_HK = JOIN_RESULT.SUPPLIER_INVOICE_HK
      AND existing.HASHDIFF = JOIN_RESULT.HASHDIFF
)
{% endif %}
{% if not is_incremental() %}

/* The following qualifier is implemented to prevent multiple loads of touched records during the initial build, such as multiple rows per HK and hashdiff. */
qualify 1 = row_number() over (partition by SUPPLIER_INVOICE_HK, HASHDIFF order by PSA_LOAD_DTS)

union all
SELECT 
MD5_BINARY(GR.VALUE) AS SUPPLIER_INVOICE_HK,
NULL AS INVOICE_ID,
NULL AS LAST_UPDATE_DATE,
NULL AS LAST_UPDATED_BY,
NULL AS VENDOR_ID,
NULL AS INVOICE_NUM,
NULL AS SET_OF_BOOKS_ID,
NULL AS INVOICE_CURRENCY_CODE,
NULL AS PAYMENT_CURRENCY_CODE,
NULL AS PAYMENT_CROSS_RATE,
NULL AS INVOICE_AMOUNT,
NULL AS VENDOR_SITE_ID,
NULL AS AMOUNT_PAID,
NULL AS DISCOUNT_AMOUNT_TAKEN,
NULL AS INVOICE_DATE,
NULL AS SOURCE,
NULL AS INVOICE_TYPE_LOOKUP_CODE,
NULL AS DESCRIPTION,
NULL AS BATCH_ID,
NULL AS AMOUNT_APPLICABLE_TO_DISCOUNT,
NULL AS TAX_AMOUNT,
NULL AS TERMS_ID,
NULL AS TERMS_DATE,
NULL AS PAYMENT_METHOD_LOOKUP_CODE,
NULL AS ACCTS_PAY_CODE_COMBINATION_ID,
NULL AS PAYMENT_STATUS_FLAG,
NULL AS CREATION_DATE,
NULL AS CREATED_BY,
NULL AS BASE_AMOUNT,
NULL AS VAT_CODE,
NULL AS LAST_UPDATE_LOGIN,
NULL AS EXCLUSIVE_PAYMENT_FLAG,
NULL AS PO_HEADER_ID,
NULL AS FREIGHT_AMOUNT,
NULL AS GOODS_RECEIVED_DATE,
NULL AS INVOICE_RECEIVED_DATE,
NULL AS VOUCHER_NUM,
NULL AS APPROVED_AMOUNT,
NULL AS RECURRING_PAYMENT_ID,
NULL AS EXCHANGE_RATE,
NULL AS EXCHANGE_RATE_TYPE,
NULL AS EXCHANGE_DATE,
NULL AS EARLIEST_SETTLEMENT_DATE,
NULL AS ORIGINAL_PREPAYMENT_AMOUNT,
NULL AS DOC_SEQUENCE_ID,
NULL AS DOC_SEQUENCE_VALUE,
NULL AS DOC_CATEGORY_CODE,
NULL AS ATTRIBUTE1,
NULL AS ATTRIBUTE2,
NULL AS ATTRIBUTE3,
NULL AS ATTRIBUTE4,
NULL AS ATTRIBUTE5,
NULL AS ATTRIBUTE6,
NULL AS ATTRIBUTE7,
NULL AS ATTRIBUTE8,
NULL AS ATTRIBUTE9,
NULL AS ATTRIBUTE10,
NULL AS ATTRIBUTE11,
NULL AS ATTRIBUTE12,
NULL AS ATTRIBUTE13,
NULL AS ATTRIBUTE14,
NULL AS ATTRIBUTE15,
NULL AS ATTRIBUTE_CATEGORY,
NULL AS APPROVAL_STATUS,
NULL AS APPROVAL_DESCRIPTION,
NULL AS INVOICE_DISTRIBUTION_TOTAL,
NULL AS POSTING_STATUS,
NULL AS PREPAY_FLAG,
NULL AS AUTHORIZED_BY,
NULL AS CANCELLED_DATE,
NULL AS CANCELLED_BY,
NULL AS CANCELLED_AMOUNT,
NULL AS TEMP_CANCELLED_AMOUNT,
NULL AS PROJECT_ACCOUNTING_CONTEXT,
NULL AS USSGL_TRANSACTION_CODE,
NULL AS USSGL_TRX_CODE_CONTEXT,
NULL AS PROJECT_ID,
NULL AS TASK_ID,
NULL AS EXPENDITURE_TYPE,
NULL AS EXPENDITURE_ITEM_DATE,
NULL AS PA_QUANTITY,
NULL AS EXPENDITURE_ORGANIZATION_ID,
NULL AS PA_DEFAULT_DIST_CCID,
NULL AS VENDOR_PREPAY_AMOUNT,
NULL AS PAYMENT_AMOUNT_TOTAL,
NULL AS AWT_FLAG,
NULL AS AWT_GROUP_ID,
NULL AS REFERENCE_1,
NULL AS REFERENCE_2,
NULL AS ORG_ID,
NULL AS PRE_WITHHOLDING_AMOUNT,
NULL AS GLOBAL_ATTRIBUTE_CATEGORY,
NULL AS GLOBAL_ATTRIBUTE1,
NULL AS GLOBAL_ATTRIBUTE2,
NULL AS GLOBAL_ATTRIBUTE3,
NULL AS GLOBAL_ATTRIBUTE4,
NULL AS GLOBAL_ATTRIBUTE5,
NULL AS GLOBAL_ATTRIBUTE6,
NULL AS GLOBAL_ATTRIBUTE7,
NULL AS GLOBAL_ATTRIBUTE8,
NULL AS GLOBAL_ATTRIBUTE9,
NULL AS GLOBAL_ATTRIBUTE10,
NULL AS GLOBAL_ATTRIBUTE11,
NULL AS GLOBAL_ATTRIBUTE12,
NULL AS GLOBAL_ATTRIBUTE13,
NULL AS GLOBAL_ATTRIBUTE14,
NULL AS GLOBAL_ATTRIBUTE15,
NULL AS GLOBAL_ATTRIBUTE16,
NULL AS GLOBAL_ATTRIBUTE17,
NULL AS GLOBAL_ATTRIBUTE18,
NULL AS GLOBAL_ATTRIBUTE19,
NULL AS GLOBAL_ATTRIBUTE20,
NULL AS AUTO_TAX_CALC_FLAG,
NULL AS PAYMENT_CROSS_RATE_TYPE,
NULL AS PAYMENT_CROSS_RATE_DATE,
NULL AS PAY_CURR_INVOICE_AMOUNT,
NULL AS MRC_BASE_AMOUNT,
NULL AS MRC_EXCHANGE_RATE,
NULL AS MRC_EXCHANGE_RATE_TYPE,
NULL AS MRC_EXCHANGE_DATE,
NULL AS GL_DATE,
NULL AS AWARD_ID,
NULL AS PAID_ON_BEHALF_EMPLOYEE_ID,
NULL AS AMT_DUE_CCARD_COMPANY,
NULL AS AMT_DUE_EMPLOYEE,
NULL AS APPROVAL_READY_FLAG,
NULL AS APPROVAL_ITERATION,
NULL AS WFAPPROVAL_STATUS,
NULL AS REQUESTER_ID,
NULL AS VALIDATION_REQUEST_ID,
NULL AS VALIDATED_TAX_AMOUNT,
NULL AS QUICK_CREDIT,
NULL AS CREDITED_INVOICE_ID,
NULL AS DISTRIBUTION_SET_ID,
NULL AS APPLICATION_ID,
NULL AS PRODUCT_TABLE,
NULL AS REFERENCE_KEY1,
NULL AS REFERENCE_KEY2,
NULL AS REFERENCE_KEY3,
NULL AS REFERENCE_KEY4,
NULL AS REFERENCE_KEY5,
NULL AS TOTAL_TAX_AMOUNT,
NULL AS SELF_ASSESSED_TAX_AMOUNT,
NULL AS TAX_RELATED_INVOICE_ID,
NULL AS TRX_BUSINESS_CATEGORY,
NULL AS USER_DEFINED_FISC_CLASS,
NULL AS TAXATION_COUNTRY,
NULL AS DOCUMENT_SUB_TYPE,
NULL AS SUPPLIER_TAX_INVOICE_NUMBER,
NULL AS SUPPLIER_TAX_INVOICE_DATE,
NULL AS SUPPLIER_TAX_EXCHANGE_RATE,
NULL AS TAX_INVOICE_RECORDING_DATE,
NULL AS TAX_INVOICE_INTERNAL_SEQ,
NULL AS LEGAL_ENTITY_ID,
NULL AS HISTORICAL_FLAG,
NULL AS FORCE_REVALIDATION_FLAG,
NULL AS BANK_CHARGE_BEARER,
NULL AS REMITTANCE_MESSAGE1,
NULL AS REMITTANCE_MESSAGE2,
NULL AS REMITTANCE_MESSAGE3,
NULL AS UNIQUE_REMITTANCE_IDENTIFIER,
NULL AS URI_CHECK_DIGIT,
NULL AS SETTLEMENT_PRIORITY,
NULL AS PAYMENT_REASON_CODE,
NULL AS PAYMENT_REASON_COMMENTS,
NULL AS PAYMENT_METHOD_CODE,
NULL AS DELIVERY_CHANNEL_CODE,
NULL AS QUICK_PO_HEADER_ID,
NULL AS NET_OF_RETAINAGE_FLAG,
NULL AS RELEASE_AMOUNT_NET_OF_TAX,
NULL AS CONTROL_AMOUNT,
NULL AS PARTY_ID,
NULL AS PARTY_SITE_ID,
NULL AS PAY_PROC_TRXN_TYPE_CODE,
NULL AS PAYMENT_FUNCTION,
NULL AS CUST_REGISTRATION_CODE,
NULL AS CUST_REGISTRATION_NUMBER,
NULL AS PORT_OF_ENTRY_CODE,
NULL AS EXTERNAL_BANK_ACCOUNT_ID,
NULL AS VENDOR_CONTACT_ID,
NULL AS INTERNAL_CONTACT_EMAIL,
NULL AS DISC_IS_INV_LESS_TAX_FLAG,
NULL AS EXCLUDE_FREIGHT_FROM_DISCOUNT,
NULL AS PAY_AWT_GROUP_ID,
NULL AS REMIT_TO_SUPPLIER_NAME,
NULL AS REMIT_TO_SUPPLIER_ID,
NULL AS REMIT_TO_SUPPLIER_SITE,
NULL AS REMIT_TO_SUPPLIER_SITE_ID,
NULL AS RELATIONSHIP_ID,
NULL AS ORIGINAL_INVOICE_AMOUNT,
NULL AS DISPUTE_REASON,
NULL AS PO_MATCHED_FLAG,
NULL AS VALIDATION_WORKER_ID,
NULL AS PAY_GROUP_LOOKUP_CODE_1,
'N' AS PSA_DELETE_IND,
'1900-01-01'::TIMESTAMP AS PSA_LOAD_DTS,
NULL AS PSA_RECORD_SOURCE,
NULL AS _FIVETRAN_SYNCED,
NULL AS _FIVETRAN_ID,
NULL AS _FIVETRAN_DELETED,
'1900-01-01T00:00:00'::TIMESTAMP_NTZ AS LOAD_DTS,
'USAZET.SNOWFLAKE.FBIN.DERIVED' AS REC_SRC,
DECODE(GR.VALUE, 0, 'GHOST RECORD-SYSTEM', -1, 'GHOST RECORD-nullkey-required', -2, 'GHOST RECORD-nullkey-optional') AS BKCC,
MD5_BINARY('') AS HASHDIFF
FROM
TABLE(strtok_split_to_table('0|-1|-2', '|')) AS GR
{% endif %}
