---- SRC LAYER ----
WITH
SRC_s              as ( SELECT * FROM {{ ref('v_psa_stg_vendor_retail_procurement_order__amazon') }} as SRC 
                        {% if is_incremental() %}
                        WHERE SRC.LOAD_DTS > (SELECT DATEADD('HOUR', '-1', MAX(LOAD_DTS)) FROM {{this}}){% endif %} )

/*
SRC_s              as ( SELECT * FROM STAGING.V_PSA_STG_VENDOR_RETAIL_PROCUREMENT_ORDER__AMAZON )
*/
---- LOGIC LAYER ----

, LOGIC_s as (
    SELECT
        VENDOR_ORDER_HK
      , PURCHASE_ORDER_DATE
      , PURCHASE_ORDER_NUMBER
      , PURCHASE_ORDER_STATE
      , PURCHASE_ORDER_CHANGED_DATE
      , PURCHASE_ORDER_STATE_CHANGED_DATE
      , PURCHASE_ORDER_TYPE
      , METHOD_OF_PAYMENT
      , INTERNATIONAL_COMMERCIAL_TERMS
      , PORT_OF_DELIVERY
      , IMPORT_CONTAINERS
      , SHIPPING_INSTRUCTIONS
      , SEAL_NUMBER
      , BILLABLE_WEIGHT_UNIT_OF_MEASURE
      , BILLABLE_WEIGHT_VALUE
      , ESTIMATED_SHIP_BY_DATE
      , HANDLING_INSTRUCTIONS
      , DEAL_CODE
      , PAYMENT_METHOD
      , BUYING_PARTY_PARTY_ID
      , BUYING_PARTY_NAME
      , BUYING_PARTY_ADDRESS_LINE_1
      , BUYING_PARTY_ADDRESS_LINE_2
      , BUYING_PARTY_ADDRESS_LINE_3
      , BUYING_PARTY_CITY
      , BUYING_PARTY_DISTRICT_OR_COUNTY
      , BUYING_PARTY_COUNTRY
      , BUYING_PARTY_DISTRICT
      , BUYING_PARTY_STATE_OR_REGION
      , BUYING_PARTY_MUNICIPALITY
      , BUYING_PARTY_POSTAL_CODE
      , BUYING_PARTY_COUNTRY_CODE
      , BUYING_PARTY_PHONE
      , BUYING_PARTY_ADDRESS_TYPE
      , BUYING_PARTY_TAX_REGISTRATION_TYPE
      , BUYING_PARTY_TAX_REGISTRATION_NUMBER
      , SELLING_PARTY_PARTY_ID
      , SELLING_PARTY_NAME
      , SELLING_PARTY_ADDRESS_LINE_1
      , SELLING_PARTY_ADDRESS_LINE_2
      , SELLING_PARTY_ADDRESS_LINE_3
      , SELLING_PARTY_CITY
      , SELLING_PARTY_DISTRICT_OR_COUNTY
      , SELLING_PARTY_COUNTRY
      , SELLING_PARTY_DISTRICT
      , SELLING_PARTY_STATE_OR_REGION
      , SELLING_PARTY_MUNICIPALITY
      , SELLING_PARTY_POSTAL_CODE
      , SELLING_PARTY_COUNTRY_CODE
      , SELLING_PARTY_PHONE
      , SELLING_PARTY_ADDRESS_TYPE
      , SELLING_PARTY_TAX_REGISTRATION_TYPE
      , SELLING_PARTY_TAX_REGISTRATION_NUMBER
      , SHIP_TO_PARTY_PARTY_ID
      , SHIP_TO_PARTY_NAME
      , SHIP_TO_PARTY_ADDRESS_LINE_1
      , SHIP_TO_PARTY_ADDRESS_LINE_2
      , SHIP_TO_PARTY_ADDRESS_LINE_3
      , SHIP_TO_PARTY_CITY
      , SHIP_TO_PARTY_DISTRICT_OR_COUNTY
      , SHIP_TO_PARTY_COUNTRY
      , SHIP_TO_PARTY_DISTRICT
      , SHIP_TO_PARTY_STATE_OR_REGION
      , SHIP_TO_PARTY_MUNICIPALITY
      , SHIP_TO_PARTY_POSTAL_CODE
      , SHIP_TO_PARTY_COUNTRY_CODE
      , SHIP_TO_PARTY_PHONE
      , SHIP_TO_PARTY_ADDRESS_TYPE
      , SHIP_TO_PARTY_TAX_REGISTRATION_TYPE
      , SHIP_TO_PARTY_TAX_REGISTRATION_NUMBER
      , BILL_TO_PARTY_PARTY_ID
      , BILL_TO_PARTY_NAME
      , BILL_TO_PARTY_ADDRESS_LINE_1
      , BILL_TO_PARTY_ADDRESS_LINE_2
      , BILL_TO_PARTY_ADDRESS_LINE_3
      , BILL_TO_PARTY_CITY
      , BILL_TO_PARTY_DISTRICT_OR_COUNTY
      , BILL_TO_PARTY_COUNTRY
      , BILL_TO_PARTY_DISTRICT
      , BILL_TO_PARTY_STATE_OR_REGION
      , BILL_TO_PARTY_MUNICIPALITY
      , BILL_TO_PARTY_POSTAL_CODE
      , BILL_TO_PARTY_COUNTRY_CODE
      , BILL_TO_PARTY_PHONE
      , BILL_TO_PARTY_ADDRESS_TYPE
      , BILL_TO_PARTY_TAX_REGISTRATION_TYPE
      , BILL_TO_PARTY_TAX_REGISTRATION_NUMBER
      , SHIP_WINDOW
      , DELIVERY_WINDOW
      , _FIVETRAN_SYNCED
      , PSA_LOAD_DTS
      , PSA_RECORD_SOURCE
      , PSA_DELETE_IND
      , LOAD_DTS
      , HASHDIFF
      , REC_SRC
    FROM SRC_s
)
---- RENAME LAYER ----

, RENAME_s as (
    SELECT
        VENDOR_ORDER_HK
      , PURCHASE_ORDER_DATE
      , PURCHASE_ORDER_NUMBER
      , PURCHASE_ORDER_STATE
      , PURCHASE_ORDER_CHANGED_DATE
      , PURCHASE_ORDER_STATE_CHANGED_DATE
      , PURCHASE_ORDER_TYPE
      , METHOD_OF_PAYMENT
      , INTERNATIONAL_COMMERCIAL_TERMS
      , PORT_OF_DELIVERY
      , IMPORT_CONTAINERS
      , SHIPPING_INSTRUCTIONS
      , SEAL_NUMBER
      , BILLABLE_WEIGHT_UNIT_OF_MEASURE
      , BILLABLE_WEIGHT_VALUE
      , ESTIMATED_SHIP_BY_DATE
      , HANDLING_INSTRUCTIONS
      , DEAL_CODE
      , PAYMENT_METHOD
      , BUYING_PARTY_PARTY_ID
      , BUYING_PARTY_NAME
      , BUYING_PARTY_ADDRESS_LINE_1
      , BUYING_PARTY_ADDRESS_LINE_2
      , BUYING_PARTY_ADDRESS_LINE_3
      , BUYING_PARTY_CITY
      , BUYING_PARTY_DISTRICT_OR_COUNTY
      , BUYING_PARTY_COUNTRY
      , BUYING_PARTY_DISTRICT
      , BUYING_PARTY_STATE_OR_REGION
      , BUYING_PARTY_MUNICIPALITY
      , BUYING_PARTY_POSTAL_CODE
      , BUYING_PARTY_COUNTRY_CODE
      , BUYING_PARTY_PHONE
      , BUYING_PARTY_ADDRESS_TYPE
      , BUYING_PARTY_TAX_REGISTRATION_TYPE
      , BUYING_PARTY_TAX_REGISTRATION_NUMBER
      , SELLING_PARTY_PARTY_ID
      , SELLING_PARTY_NAME
      , SELLING_PARTY_ADDRESS_LINE_1
      , SELLING_PARTY_ADDRESS_LINE_2
      , SELLING_PARTY_ADDRESS_LINE_3
      , SELLING_PARTY_CITY
      , SELLING_PARTY_DISTRICT_OR_COUNTY
      , SELLING_PARTY_COUNTRY
      , SELLING_PARTY_DISTRICT
      , SELLING_PARTY_STATE_OR_REGION
      , SELLING_PARTY_MUNICIPALITY
      , SELLING_PARTY_POSTAL_CODE
      , SELLING_PARTY_COUNTRY_CODE
      , SELLING_PARTY_PHONE
      , SELLING_PARTY_ADDRESS_TYPE
      , SELLING_PARTY_TAX_REGISTRATION_TYPE
      , SELLING_PARTY_TAX_REGISTRATION_NUMBER
      , SHIP_TO_PARTY_PARTY_ID
      , SHIP_TO_PARTY_NAME
      , SHIP_TO_PARTY_ADDRESS_LINE_1
      , SHIP_TO_PARTY_ADDRESS_LINE_2
      , SHIP_TO_PARTY_ADDRESS_LINE_3
      , SHIP_TO_PARTY_CITY
      , SHIP_TO_PARTY_DISTRICT_OR_COUNTY
      , SHIP_TO_PARTY_COUNTRY
      , SHIP_TO_PARTY_DISTRICT
      , SHIP_TO_PARTY_STATE_OR_REGION
      , SHIP_TO_PARTY_MUNICIPALITY
      , SHIP_TO_PARTY_POSTAL_CODE
      , SHIP_TO_PARTY_COUNTRY_CODE
      , SHIP_TO_PARTY_PHONE
      , SHIP_TO_PARTY_ADDRESS_TYPE
      , SHIP_TO_PARTY_TAX_REGISTRATION_TYPE
      , SHIP_TO_PARTY_TAX_REGISTRATION_NUMBER
      , BILL_TO_PARTY_PARTY_ID
      , BILL_TO_PARTY_NAME
      , BILL_TO_PARTY_ADDRESS_LINE_1
      , BILL_TO_PARTY_ADDRESS_LINE_2
      , BILL_TO_PARTY_ADDRESS_LINE_3
      , BILL_TO_PARTY_CITY
      , BILL_TO_PARTY_DISTRICT_OR_COUNTY
      , BILL_TO_PARTY_COUNTRY
      , BILL_TO_PARTY_DISTRICT
      , BILL_TO_PARTY_STATE_OR_REGION
      , BILL_TO_PARTY_MUNICIPALITY
      , BILL_TO_PARTY_POSTAL_CODE
      , BILL_TO_PARTY_COUNTRY_CODE
      , BILL_TO_PARTY_PHONE
      , BILL_TO_PARTY_ADDRESS_TYPE
      , BILL_TO_PARTY_TAX_REGISTRATION_TYPE
      , BILL_TO_PARTY_TAX_REGISTRATION_NUMBER
      , SHIP_WINDOW
      , DELIVERY_WINDOW
      , _FIVETRAN_SYNCED
      , PSA_LOAD_DTS
      , PSA_RECORD_SOURCE
      , PSA_DELETE_IND
      , LOAD_DTS
      , HASHDIFF
      , REC_SRC
    FROM LOGIC_s
)
---- FILTER LAYER ----

, FILTER_s as (
    SELECT *
    FROM RENAME_s
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM FILTER_s
)

---- FINAL LAYER ----
SELECT
          VENDOR_ORDER_HK
        , PURCHASE_ORDER_DATE
        , PURCHASE_ORDER_NUMBER
        , PURCHASE_ORDER_STATE
        , PURCHASE_ORDER_CHANGED_DATE
        , PURCHASE_ORDER_STATE_CHANGED_DATE
        , PURCHASE_ORDER_TYPE
        , METHOD_OF_PAYMENT
        , INTERNATIONAL_COMMERCIAL_TERMS
        , PORT_OF_DELIVERY
        , IMPORT_CONTAINERS
        , SHIPPING_INSTRUCTIONS
        , SEAL_NUMBER
        , BILLABLE_WEIGHT_UNIT_OF_MEASURE
        , BILLABLE_WEIGHT_VALUE
        , ESTIMATED_SHIP_BY_DATE
        , HANDLING_INSTRUCTIONS
        , DEAL_CODE
        , PAYMENT_METHOD
        , BUYING_PARTY_PARTY_ID
        , BUYING_PARTY_NAME
        , BUYING_PARTY_ADDRESS_LINE_1
        , BUYING_PARTY_ADDRESS_LINE_2
        , BUYING_PARTY_ADDRESS_LINE_3
        , BUYING_PARTY_CITY
        , BUYING_PARTY_DISTRICT_OR_COUNTY
        , BUYING_PARTY_COUNTRY
        , BUYING_PARTY_DISTRICT
        , BUYING_PARTY_STATE_OR_REGION
        , BUYING_PARTY_MUNICIPALITY
        , BUYING_PARTY_POSTAL_CODE
        , BUYING_PARTY_COUNTRY_CODE
        , BUYING_PARTY_PHONE
        , BUYING_PARTY_ADDRESS_TYPE
        , BUYING_PARTY_TAX_REGISTRATION_TYPE
        , BUYING_PARTY_TAX_REGISTRATION_NUMBER
        , SELLING_PARTY_PARTY_ID
        , SELLING_PARTY_NAME
        , SELLING_PARTY_ADDRESS_LINE_1
        , SELLING_PARTY_ADDRESS_LINE_2
        , SELLING_PARTY_ADDRESS_LINE_3
        , SELLING_PARTY_CITY
        , SELLING_PARTY_DISTRICT_OR_COUNTY
        , SELLING_PARTY_COUNTRY
        , SELLING_PARTY_DISTRICT
        , SELLING_PARTY_STATE_OR_REGION
        , SELLING_PARTY_MUNICIPALITY
        , SELLING_PARTY_POSTAL_CODE
        , SELLING_PARTY_COUNTRY_CODE
        , SELLING_PARTY_PHONE
        , SELLING_PARTY_ADDRESS_TYPE
        , SELLING_PARTY_TAX_REGISTRATION_TYPE
        , SELLING_PARTY_TAX_REGISTRATION_NUMBER
        , SHIP_TO_PARTY_PARTY_ID
        , SHIP_TO_PARTY_NAME
        , SHIP_TO_PARTY_ADDRESS_LINE_1
        , SHIP_TO_PARTY_ADDRESS_LINE_2
        , SHIP_TO_PARTY_ADDRESS_LINE_3
        , SHIP_TO_PARTY_CITY
        , SHIP_TO_PARTY_DISTRICT_OR_COUNTY
        , SHIP_TO_PARTY_COUNTRY
        , SHIP_TO_PARTY_DISTRICT
        , SHIP_TO_PARTY_STATE_OR_REGION
        , SHIP_TO_PARTY_MUNICIPALITY
        , SHIP_TO_PARTY_POSTAL_CODE
        , SHIP_TO_PARTY_COUNTRY_CODE
        , SHIP_TO_PARTY_PHONE
        , SHIP_TO_PARTY_ADDRESS_TYPE
        , SHIP_TO_PARTY_TAX_REGISTRATION_TYPE
        , SHIP_TO_PARTY_TAX_REGISTRATION_NUMBER
        , BILL_TO_PARTY_PARTY_ID
        , BILL_TO_PARTY_NAME
        , BILL_TO_PARTY_ADDRESS_LINE_1
        , BILL_TO_PARTY_ADDRESS_LINE_2
        , BILL_TO_PARTY_ADDRESS_LINE_3
        , BILL_TO_PARTY_CITY
        , BILL_TO_PARTY_DISTRICT_OR_COUNTY
        , BILL_TO_PARTY_COUNTRY
        , BILL_TO_PARTY_DISTRICT
        , BILL_TO_PARTY_STATE_OR_REGION
        , BILL_TO_PARTY_MUNICIPALITY
        , BILL_TO_PARTY_POSTAL_CODE
        , BILL_TO_PARTY_COUNTRY_CODE
        , BILL_TO_PARTY_PHONE
        , BILL_TO_PARTY_ADDRESS_TYPE
        , BILL_TO_PARTY_TAX_REGISTRATION_TYPE
        , BILL_TO_PARTY_TAX_REGISTRATION_NUMBER
        , SHIP_WINDOW
        , DELIVERY_WINDOW
        , _FIVETRAN_SYNCED
        , PSA_LOAD_DTS
        , PSA_RECORD_SOURCE
        , PSA_DELETE_IND
        , LOAD_DTS
        , HASHDIFF
        , REC_SRC
FROM JOIN_RESULT
{% if is_incremental() %}
WHERE NOT EXISTS (
    SELECT 1 
    FROM {{ this }} existing
    WHERE existing.VENDOR_ORDER_HK = JOIN_RESULT.VENDOR_ORDER_HK  AND existing.HASHDIFF = JOIN_RESULT.HASHDIFF
)
{% endif %}
{% if not is_incremental() %}

/* The following qualifier is implemented to prevent multiple loads of touched records during the initial build, such as multiple rows per HK and hashdiff. */
qualify 1 = row_number() over (partition by VENDOR_ORDER_HK, HASHDIFF order by PSA_LOAD_DTS)

union all
SELECT 
MD5_BINARY(GR.VALUE) AS VENDOR_ORDER_HK,
GR.VALUE::text AS PURCHASE_ORDER_DATE,
GR.VALUE::text AS PURCHASE_ORDER_NUMBER,
NULL AS PURCHASE_ORDER_STATE,
NULL AS PURCHASE_ORDER_CHANGED_DATE,
NULL AS PURCHASE_ORDER_STATE_CHANGED_DATE,
NULL AS PURCHASE_ORDER_TYPE,
NULL AS METHOD_OF_PAYMENT,
NULL AS INTERNATIONAL_COMMERCIAL_TERMS,
NULL AS PORT_OF_DELIVERY,
NULL AS IMPORT_CONTAINERS,
NULL AS SHIPPING_INSTRUCTIONS,
NULL AS SEAL_NUMBER,
NULL AS BILLABLE_WEIGHT_UNIT_OF_MEASURE,
NULL AS BILLABLE_WEIGHT_VALUE,
NULL AS ESTIMATED_SHIP_BY_DATE,
NULL AS HANDLING_INSTRUCTIONS,
NULL AS DEAL_CODE,
NULL AS PAYMENT_METHOD,
NULL AS BUYING_PARTY_PARTY_ID,
NULL AS BUYING_PARTY_NAME,
NULL AS BUYING_PARTY_ADDRESS_LINE_1,
NULL AS BUYING_PARTY_ADDRESS_LINE_2,
NULL AS BUYING_PARTY_ADDRESS_LINE_3,
NULL AS BUYING_PARTY_CITY,
NULL AS BUYING_PARTY_DISTRICT_OR_COUNTY,
NULL AS BUYING_PARTY_COUNTRY,
NULL AS BUYING_PARTY_DISTRICT,
NULL AS BUYING_PARTY_STATE_OR_REGION,
NULL AS BUYING_PARTY_MUNICIPALITY,
NULL AS BUYING_PARTY_POSTAL_CODE,
NULL AS BUYING_PARTY_COUNTRY_CODE,
NULL AS BUYING_PARTY_PHONE,
NULL AS BUYING_PARTY_ADDRESS_TYPE,
NULL AS BUYING_PARTY_TAX_REGISTRATION_TYPE,
NULL AS BUYING_PARTY_TAX_REGISTRATION_NUMBER,
NULL AS SELLING_PARTY_PARTY_ID,
NULL AS SELLING_PARTY_NAME,
NULL AS SELLING_PARTY_ADDRESS_LINE_1,
NULL AS SELLING_PARTY_ADDRESS_LINE_2,
NULL AS SELLING_PARTY_ADDRESS_LINE_3,
NULL AS SELLING_PARTY_CITY,
NULL AS SELLING_PARTY_DISTRICT_OR_COUNTY,
NULL AS SELLING_PARTY_COUNTRY,
NULL AS SELLING_PARTY_DISTRICT,
NULL AS SELLING_PARTY_STATE_OR_REGION,
NULL AS SELLING_PARTY_MUNICIPALITY,
NULL AS SELLING_PARTY_POSTAL_CODE,
NULL AS SELLING_PARTY_COUNTRY_CODE,
NULL AS SELLING_PARTY_PHONE,
NULL AS SELLING_PARTY_ADDRESS_TYPE,
NULL AS SELLING_PARTY_TAX_REGISTRATION_TYPE,
NULL AS SELLING_PARTY_TAX_REGISTRATION_NUMBER,
NULL AS SHIP_TO_PARTY_PARTY_ID,
NULL AS SHIP_TO_PARTY_NAME,
NULL AS SHIP_TO_PARTY_ADDRESS_LINE_1,
NULL AS SHIP_TO_PARTY_ADDRESS_LINE_2,
NULL AS SHIP_TO_PARTY_ADDRESS_LINE_3,
NULL AS SHIP_TO_PARTY_CITY,
NULL AS SHIP_TO_PARTY_DISTRICT_OR_COUNTY,
NULL AS SHIP_TO_PARTY_COUNTRY,
NULL AS SHIP_TO_PARTY_DISTRICT,
NULL AS SHIP_TO_PARTY_STATE_OR_REGION,
NULL AS SHIP_TO_PARTY_MUNICIPALITY,
NULL AS SHIP_TO_PARTY_POSTAL_CODE,
NULL AS SHIP_TO_PARTY_COUNTRY_CODE,
NULL AS SHIP_TO_PARTY_PHONE,
NULL AS SHIP_TO_PARTY_ADDRESS_TYPE,
NULL AS SHIP_TO_PARTY_TAX_REGISTRATION_TYPE,
NULL AS SHIP_TO_PARTY_TAX_REGISTRATION_NUMBER,
NULL AS BILL_TO_PARTY_PARTY_ID,
NULL AS BILL_TO_PARTY_NAME,
NULL AS BILL_TO_PARTY_ADDRESS_LINE_1,
NULL AS BILL_TO_PARTY_ADDRESS_LINE_2,
NULL AS BILL_TO_PARTY_ADDRESS_LINE_3,
NULL AS BILL_TO_PARTY_CITY,
NULL AS BILL_TO_PARTY_DISTRICT_OR_COUNTY,
NULL AS BILL_TO_PARTY_COUNTRY,
NULL AS BILL_TO_PARTY_DISTRICT,
NULL AS BILL_TO_PARTY_STATE_OR_REGION,
NULL AS BILL_TO_PARTY_MUNICIPALITY,
NULL AS BILL_TO_PARTY_POSTAL_CODE,
NULL AS BILL_TO_PARTY_COUNTRY_CODE,
NULL AS BILL_TO_PARTY_PHONE,
NULL AS BILL_TO_PARTY_ADDRESS_TYPE,
NULL AS BILL_TO_PARTY_TAX_REGISTRATION_TYPE,
NULL AS BILL_TO_PARTY_TAX_REGISTRATION_NUMBER,
NULL AS SHIP_WINDOW,
NULL AS DELIVERY_WINDOW,
NULL AS _FIVETRAN_SYNCED,
'1900-01-01'::TIMESTAMP AS PSA_LOAD_DTS,
'psa_record_source' AS PSA_RECORD_SOURCE,
'N' AS PSA_DELETE_IND,
CONVERT_TIMEZONE('UTC','1900-01-01'::TIMESTAMP) AS LOAD_DTS,
''::BINARY AS HASHDIFF,
'USAZET.SNOWFLAKE.FBIN.DERIVED' AS REC_SRC
FROM
TABLE(strtok_split_to_table('0|-1|-2', '|')) AS GR
{% endif %}
