---- SRC LAYER ----
WITH
SRC_SLTAPI         as ( SELECT * FROM {{ ref('v_psa_stg_sales_inventory__thermatru_lowes_ft_api') }} as SRC 
                         {% if is_incremental() %}
                         WHERE SRC.LOAD_DTS > (SELECT DATEADD('HOUR', '-1', MAX(LOAD_DTS)) FROM {{this}})
                         {% endif %}  )

/*
SRC_SLTAPI         as ( SELECT * FROM STAGING.v_psa_stg_sales_inventory__thermatru_lowes_ft_api )
*/
---- LOGIC LAYER ----

, LOGIC_SLTAPI as (
    SELECT
        STORE_HK
      , END_DATE
      , ITEM_ID
      , LOCATION_ID
      , START_DATE
      , ITEM_NAME
      , LOCATION_NAME
      , TY_SALES_UNITS
      , LY_SALES_UNITS
      , TY_VS_LY_SALES_UNITS
      , TY_SALES
      , LY_SALES
      , TY_VS_LY_SALES
      , GROSS_SALES
      , GROSS_ITEM_QUANTITY
      , LY_GROSS_ITEM_QUANTITY
      , GROSS_SALES_UNIT_PERCENTAGE
      , TY_FULFILLED_INTERNET_UNITS
      , LY_FULFILLED_INTERNET_UNITS
      , TY_VS_LY_FULFILLED_INTERNET_UNITS
      , TY_FULFILLED_INTERNET_SALES
      , LY_FULFILLED_INTERNET_SALES
      , TY_VS_LY_FULFILLED_INTERNET_SALES
      , TY_AVG_INVENTORY_ON_HAND_UNITS
      , LY_AVG_INVENTORY_ON_HAND_UNITS
      , TY_VS_LY_AVG_INVENTORY_ON_HAND_UNITS
      , TY_AVG_INVENTORY_ON_HAND_SALES
      , LY_AVG_INVENTORY_ON_HAND_SALES
      , TY_VS_LY_AVG_INVENTORY_ON_HAND_SALES
      , TY_AVERAGE_INVENTORY_ON_DIRECT_ORDER_UNITS
      , LY_AVERAGE_INVENTORY_ON_DIRECT_ORDER_UNITS
      , TY_VS_LY_AVERAGE_INVENTORY_ON_DIRECT_ORDER_UNITS
      , TY_AVERAGE_INVENTORY_ON_DIRECT_ORDER_SALES
      , LY_AVERAGE_INVENTORY_ON_DIRECT_ORDER_SALES
      , TY_VS_LY_AVERAGE_INVENTORY_ON_DIRECT_ORDER_SALES
      , TY_AVERAGE_INVENTORY_ON_REQUISITION_UNITS
      , LY_AVERAGE_INVENTORY_ON_REQUISITION_UNITS
      , TY_VS_LY_AVERAGE_INVENTORY_ON_REQUISITION_UNITS
      , TY_AVERAGE_INVENTORY_ON_REQUISITION_SALES
      , LY_AVERAGE_INVENTORY_ON_REQUISITION_SALES
      , TY_VS_LY_AVERAGE_INVENTORY_ON_REQUISITION_SALES
      , IN_STOCK_PERCENTAGE
      , TY_AVAILABLE_INVENTORY_UNITS
      , LY_AVAILABLE_INVENTORY_UNITS
      , TY_VS_LY_AVAILABLE_INVENTORY_UNITS
      , TY_AVAILABLE_INVENTORY_SALES
      , LY_AVAILABLE_INVENTORY_SALES
      , TY_VS_LY_AVAILABLE_INVENTORY_SALES
      , AVAILABLE_DC_INVENTORY_UNITS
      , AVAILABLE_RETAIL_INVENTORY_UNITS
      , TY_INVENTORY_ON_DIRECT_ORDER_UNITS
      , LY_INVENTORY_ON_DIRECT_ORDER_UNITS
      , TY_VS_LY_INVENTORY_ON_DIRECT_ORDER_UNITS
      , TY_INVENTORY_ON_DIRECT_ORDER_SALES
      , LY_INVENTORY_ON_DIRECT_ORDER_SALES
      , TY_VS_LY_INVENTORY_ON_DIRECT_ORDER_SALES
      , TY_INVENTORY_UNITS_IN_REQ
      , LY_INVENTORY_UNITS_IN_REQ
      , TY_VS_LY_INVENTORY_UNITS_IN_REQ
      , TY_INVENTORY_UNITS_ON_BILL
      , LY_INVENTORY_UNITS_ON_BILL
      , TY_VS_LY_INVENTORY_UNITS_ON_BILL
      , AVERAGE_YEAR_TO_DATE_SALES
      , TY_YEAR_TO_DATE_SALES_UNITS
      , LY_YEAR_TO_DATE_SALES_UNITS
      , TY_VS_LY_YEAR_TO_DATE_SALES_UNITS
      , YEAR_TO_DATE_TOTAL_SALES
      , YEAR_TO_DATE_LY_TOTAL_SALES
      , YEAR_TO_DATE_TOTAL_SALES_PERCENTAGE
      , YEAR_TO_DATE_WEEKLY_AVERAGE_SALES
      , WEEKS_OF_SUPPLY_ON_HAND
      , WEEKS_OF_SUPPLY_ON_ORDER
      , TY_JDA_LOST_SALES
      , TY_JDA_SERVICE_LEVEL
      , LY_TURN_RATE
      , TY_TURN_RATE
      , VBU_NUMBER
      , WEEKS_OF_SUPPLY_IN_STOCK
      , _FIVETRAN_SYNCED
      , _FIVETRAN_DELETED
      , PSA_LOAD_DTS
      , PSA_RECORD_SOURCE
      , PSA_DELETE_IND
      , LOAD_DTS
      , REC_SRC
      , HASHDIFF
    FROM SRC_SLTAPI
)
---- RENAME LAYER ----

, RENAME_SLTAPI as (
    SELECT
        STORE_HK
      , END_DATE
      , ITEM_ID
      , LOCATION_ID
      , START_DATE
      , ITEM_NAME
      , LOCATION_NAME
      , TY_SALES_UNITS
      , LY_SALES_UNITS
      , TY_VS_LY_SALES_UNITS
      , TY_SALES
      , LY_SALES
      , TY_VS_LY_SALES
      , GROSS_SALES
      , GROSS_ITEM_QUANTITY
      , LY_GROSS_ITEM_QUANTITY
      , GROSS_SALES_UNIT_PERCENTAGE
      , TY_FULFILLED_INTERNET_UNITS
      , LY_FULFILLED_INTERNET_UNITS
      , TY_VS_LY_FULFILLED_INTERNET_UNITS
      , TY_FULFILLED_INTERNET_SALES
      , LY_FULFILLED_INTERNET_SALES
      , TY_VS_LY_FULFILLED_INTERNET_SALES
      , TY_AVG_INVENTORY_ON_HAND_UNITS
      , LY_AVG_INVENTORY_ON_HAND_UNITS
      , TY_VS_LY_AVG_INVENTORY_ON_HAND_UNITS
      , TY_AVG_INVENTORY_ON_HAND_SALES
      , LY_AVG_INVENTORY_ON_HAND_SALES
      , TY_VS_LY_AVG_INVENTORY_ON_HAND_SALES
      , TY_AVERAGE_INVENTORY_ON_DIRECT_ORDER_UNITS
      , LY_AVERAGE_INVENTORY_ON_DIRECT_ORDER_UNITS
      , TY_VS_LY_AVERAGE_INVENTORY_ON_DIRECT_ORDER_UNITS
      , TY_AVERAGE_INVENTORY_ON_DIRECT_ORDER_SALES
      , LY_AVERAGE_INVENTORY_ON_DIRECT_ORDER_SALES
      , TY_VS_LY_AVERAGE_INVENTORY_ON_DIRECT_ORDER_SALES
      , TY_AVERAGE_INVENTORY_ON_REQUISITION_UNITS
      , LY_AVERAGE_INVENTORY_ON_REQUISITION_UNITS
      , TY_VS_LY_AVERAGE_INVENTORY_ON_REQUISITION_UNITS
      , TY_AVERAGE_INVENTORY_ON_REQUISITION_SALES
      , LY_AVERAGE_INVENTORY_ON_REQUISITION_SALES
      , TY_VS_LY_AVERAGE_INVENTORY_ON_REQUISITION_SALES
      , IN_STOCK_PERCENTAGE
      , TY_AVAILABLE_INVENTORY_UNITS
      , LY_AVAILABLE_INVENTORY_UNITS
      , TY_VS_LY_AVAILABLE_INVENTORY_UNITS
      , TY_AVAILABLE_INVENTORY_SALES
      , LY_AVAILABLE_INVENTORY_SALES
      , TY_VS_LY_AVAILABLE_INVENTORY_SALES
      , AVAILABLE_DC_INVENTORY_UNITS
      , AVAILABLE_RETAIL_INVENTORY_UNITS
      , TY_INVENTORY_ON_DIRECT_ORDER_UNITS
      , LY_INVENTORY_ON_DIRECT_ORDER_UNITS
      , TY_VS_LY_INVENTORY_ON_DIRECT_ORDER_UNITS
      , TY_INVENTORY_ON_DIRECT_ORDER_SALES
      , LY_INVENTORY_ON_DIRECT_ORDER_SALES
      , TY_VS_LY_INVENTORY_ON_DIRECT_ORDER_SALES
      , TY_INVENTORY_UNITS_IN_REQ
      , LY_INVENTORY_UNITS_IN_REQ
      , TY_VS_LY_INVENTORY_UNITS_IN_REQ
      , TY_INVENTORY_UNITS_ON_BILL
      , LY_INVENTORY_UNITS_ON_BILL
      , TY_VS_LY_INVENTORY_UNITS_ON_BILL
      , AVERAGE_YEAR_TO_DATE_SALES
      , TY_YEAR_TO_DATE_SALES_UNITS
      , LY_YEAR_TO_DATE_SALES_UNITS
      , TY_VS_LY_YEAR_TO_DATE_SALES_UNITS
      , YEAR_TO_DATE_TOTAL_SALES
      , YEAR_TO_DATE_LY_TOTAL_SALES
      , YEAR_TO_DATE_TOTAL_SALES_PERCENTAGE
      , YEAR_TO_DATE_WEEKLY_AVERAGE_SALES
      , WEEKS_OF_SUPPLY_ON_HAND
      , WEEKS_OF_SUPPLY_ON_ORDER
      , TY_JDA_LOST_SALES
      , TY_JDA_SERVICE_LEVEL
      , LY_TURN_RATE
      , TY_TURN_RATE
      , VBU_NUMBER
      , WEEKS_OF_SUPPLY_IN_STOCK
      , _FIVETRAN_SYNCED
      , _FIVETRAN_DELETED
      , PSA_LOAD_DTS
      , PSA_RECORD_SOURCE
      , PSA_DELETE_IND
      , LOAD_DTS
      , REC_SRC
      , HASHDIFF
    FROM LOGIC_SLTAPI
)
---- FILTER LAYER ----

, FILTER_SLTAPI as (
    SELECT *
    FROM RENAME_SLTAPI
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM FILTER_SLTAPI
)

---- FINAL LAYER ----
SELECT
          STORE_HK
        , END_DATE
        , ITEM_ID
        , LOCATION_ID
        , START_DATE
        , ITEM_NAME
        , LOCATION_NAME
        , TY_SALES_UNITS
        , LY_SALES_UNITS
        , TY_VS_LY_SALES_UNITS
        , TY_SALES
        , LY_SALES
        , TY_VS_LY_SALES
        , GROSS_SALES
        , GROSS_ITEM_QUANTITY
        , LY_GROSS_ITEM_QUANTITY
        , GROSS_SALES_UNIT_PERCENTAGE
        , TY_FULFILLED_INTERNET_UNITS
        , LY_FULFILLED_INTERNET_UNITS
        , TY_VS_LY_FULFILLED_INTERNET_UNITS
        , TY_FULFILLED_INTERNET_SALES
        , LY_FULFILLED_INTERNET_SALES
        , TY_VS_LY_FULFILLED_INTERNET_SALES
        , TY_AVG_INVENTORY_ON_HAND_UNITS
        , LY_AVG_INVENTORY_ON_HAND_UNITS
        , TY_VS_LY_AVG_INVENTORY_ON_HAND_UNITS
        , TY_AVG_INVENTORY_ON_HAND_SALES
        , LY_AVG_INVENTORY_ON_HAND_SALES
        , TY_VS_LY_AVG_INVENTORY_ON_HAND_SALES
        , TY_AVERAGE_INVENTORY_ON_DIRECT_ORDER_UNITS
        , LY_AVERAGE_INVENTORY_ON_DIRECT_ORDER_UNITS
        , TY_VS_LY_AVERAGE_INVENTORY_ON_DIRECT_ORDER_UNITS
        , TY_AVERAGE_INVENTORY_ON_DIRECT_ORDER_SALES
        , LY_AVERAGE_INVENTORY_ON_DIRECT_ORDER_SALES
        , TY_VS_LY_AVERAGE_INVENTORY_ON_DIRECT_ORDER_SALES
        , TY_AVERAGE_INVENTORY_ON_REQUISITION_UNITS
        , LY_AVERAGE_INVENTORY_ON_REQUISITION_UNITS
        , TY_VS_LY_AVERAGE_INVENTORY_ON_REQUISITION_UNITS
        , TY_AVERAGE_INVENTORY_ON_REQUISITION_SALES
        , LY_AVERAGE_INVENTORY_ON_REQUISITION_SALES
        , TY_VS_LY_AVERAGE_INVENTORY_ON_REQUISITION_SALES
        , IN_STOCK_PERCENTAGE
        , TY_AVAILABLE_INVENTORY_UNITS
        , LY_AVAILABLE_INVENTORY_UNITS
        , TY_VS_LY_AVAILABLE_INVENTORY_UNITS
        , TY_AVAILABLE_INVENTORY_SALES
        , LY_AVAILABLE_INVENTORY_SALES
        , TY_VS_LY_AVAILABLE_INVENTORY_SALES
        , AVAILABLE_DC_INVENTORY_UNITS
        , AVAILABLE_RETAIL_INVENTORY_UNITS
        , TY_INVENTORY_ON_DIRECT_ORDER_UNITS
        , LY_INVENTORY_ON_DIRECT_ORDER_UNITS
        , TY_VS_LY_INVENTORY_ON_DIRECT_ORDER_UNITS
        , TY_INVENTORY_ON_DIRECT_ORDER_SALES
        , LY_INVENTORY_ON_DIRECT_ORDER_SALES
        , TY_VS_LY_INVENTORY_ON_DIRECT_ORDER_SALES
        , TY_INVENTORY_UNITS_IN_REQ
        , LY_INVENTORY_UNITS_IN_REQ
        , TY_VS_LY_INVENTORY_UNITS_IN_REQ
        , TY_INVENTORY_UNITS_ON_BILL
        , LY_INVENTORY_UNITS_ON_BILL
        , TY_VS_LY_INVENTORY_UNITS_ON_BILL
        , AVERAGE_YEAR_TO_DATE_SALES
        , TY_YEAR_TO_DATE_SALES_UNITS
        , LY_YEAR_TO_DATE_SALES_UNITS
        , TY_VS_LY_YEAR_TO_DATE_SALES_UNITS
        , YEAR_TO_DATE_TOTAL_SALES
        , YEAR_TO_DATE_LY_TOTAL_SALES
        , YEAR_TO_DATE_TOTAL_SALES_PERCENTAGE
        , YEAR_TO_DATE_WEEKLY_AVERAGE_SALES
        , WEEKS_OF_SUPPLY_ON_HAND
        , WEEKS_OF_SUPPLY_ON_ORDER
        , TY_JDA_LOST_SALES
        , TY_JDA_SERVICE_LEVEL
        , LY_TURN_RATE
        , TY_TURN_RATE
        , VBU_NUMBER
        , WEEKS_OF_SUPPLY_IN_STOCK
        , _FIVETRAN_SYNCED
        , _FIVETRAN_DELETED
        , PSA_LOAD_DTS
        , PSA_RECORD_SOURCE
        , PSA_DELETE_IND
        , LOAD_DTS
        , REC_SRC
        , HASHDIFF
FROM JOIN_RESULT
{% if is_incremental() %}
WHERE NOT EXISTS (
    SELECT 1 
    FROM {{ this }} existing
    WHERE existing.STORE_HK = JOIN_RESULT.STORE_HK
	AND existing.ITEM_ID = JOIN_RESULT.ITEM_ID
	AND existing.START_DATE = JOIN_RESULT.START_DATE
	AND existing.END_DATE = JOIN_RESULT.END_DATE
	AND existing.HASHDIFF = JOIN_RESULT.HASHDIFF
)
{% endif %}
{% if not is_incremental() %}

/* The following qualifier is implemented to prevent multiple loads of touched records during the initial build, such as multiple rows per HK and hashdiff. */
qualify 1 = row_number() over (partition by STORE_HK, ITEM_ID, START_DATE, END_DATE, HASHDIFF order by PSA_LOAD_DTS)

union all
SELECT 
MD5_BINARY(GR.VALUE) AS STORE_HK,
GR.VALUE::text AS END_DATE,
GR.VALUE::text AS ITEM_ID,
GR.VALUE::text AS LOCATION_ID,
GR.VALUE::text AS START_DATE,
NULL AS ITEM_NAME,
NULL AS LOCATION_NAME,
NULL AS TY_SALES_UNITS,
NULL AS LY_SALES_UNITS,
NULL AS TY_VS_LY_SALES_UNITS,
NULL AS TY_SALES,
NULL AS LY_SALES,
NULL AS TY_VS_LY_SALES,
NULL AS GROSS_SALES,
NULL AS GROSS_ITEM_QUANTITY,
NULL AS LY_GROSS_ITEM_QUANTITY,
NULL AS GROSS_SALES_UNIT_PERCENTAGE,
NULL AS TY_FULFILLED_INTERNET_UNITS,
NULL AS LY_FULFILLED_INTERNET_UNITS,
NULL AS TY_VS_LY_FULFILLED_INTERNET_UNITS,
NULL AS TY_FULFILLED_INTERNET_SALES,
NULL AS LY_FULFILLED_INTERNET_SALES,
NULL AS TY_VS_LY_FULFILLED_INTERNET_SALES,
NULL AS TY_AVG_INVENTORY_ON_HAND_UNITS,
NULL AS LY_AVG_INVENTORY_ON_HAND_UNITS,
NULL AS TY_VS_LY_AVG_INVENTORY_ON_HAND_UNITS,
NULL AS TY_AVG_INVENTORY_ON_HAND_SALES,
NULL AS LY_AVG_INVENTORY_ON_HAND_SALES,
NULL AS TY_VS_LY_AVG_INVENTORY_ON_HAND_SALES,
NULL AS TY_AVERAGE_INVENTORY_ON_DIRECT_ORDER_UNITS,
NULL AS LY_AVERAGE_INVENTORY_ON_DIRECT_ORDER_UNITS,
NULL AS TY_VS_LY_AVERAGE_INVENTORY_ON_DIRECT_ORDER_UNITS,
NULL AS TY_AVERAGE_INVENTORY_ON_DIRECT_ORDER_SALES,
NULL AS LY_AVERAGE_INVENTORY_ON_DIRECT_ORDER_SALES,
NULL AS TY_VS_LY_AVERAGE_INVENTORY_ON_DIRECT_ORDER_SALES,
NULL AS TY_AVERAGE_INVENTORY_ON_REQUISITION_UNITS,
NULL AS LY_AVERAGE_INVENTORY_ON_REQUISITION_UNITS,
NULL AS TY_VS_LY_AVERAGE_INVENTORY_ON_REQUISITION_UNITS,
NULL AS TY_AVERAGE_INVENTORY_ON_REQUISITION_SALES,
NULL AS LY_AVERAGE_INVENTORY_ON_REQUISITION_SALES,
NULL AS TY_VS_LY_AVERAGE_INVENTORY_ON_REQUISITION_SALES,
NULL AS IN_STOCK_PERCENTAGE,
NULL AS TY_AVAILABLE_INVENTORY_UNITS,
NULL AS LY_AVAILABLE_INVENTORY_UNITS,
NULL AS TY_VS_LY_AVAILABLE_INVENTORY_UNITS,
NULL AS TY_AVAILABLE_INVENTORY_SALES,
NULL AS LY_AVAILABLE_INVENTORY_SALES,
NULL AS TY_VS_LY_AVAILABLE_INVENTORY_SALES,
NULL AS AVAILABLE_DC_INVENTORY_UNITS,
NULL AS AVAILABLE_RETAIL_INVENTORY_UNITS,
NULL AS TY_INVENTORY_ON_DIRECT_ORDER_UNITS,
NULL AS LY_INVENTORY_ON_DIRECT_ORDER_UNITS,
NULL AS TY_VS_LY_INVENTORY_ON_DIRECT_ORDER_UNITS,
NULL AS TY_INVENTORY_ON_DIRECT_ORDER_SALES,
NULL AS LY_INVENTORY_ON_DIRECT_ORDER_SALES,
NULL AS TY_VS_LY_INVENTORY_ON_DIRECT_ORDER_SALES,
NULL AS TY_INVENTORY_UNITS_IN_REQ,
NULL AS LY_INVENTORY_UNITS_IN_REQ,
NULL AS TY_VS_LY_INVENTORY_UNITS_IN_REQ,
NULL AS TY_INVENTORY_UNITS_ON_BILL,
NULL AS LY_INVENTORY_UNITS_ON_BILL,
NULL AS TY_VS_LY_INVENTORY_UNITS_ON_BILL,
NULL AS AVERAGE_YEAR_TO_DATE_SALES,
NULL AS TY_YEAR_TO_DATE_SALES_UNITS,
NULL AS LY_YEAR_TO_DATE_SALES_UNITS,
NULL AS TY_VS_LY_YEAR_TO_DATE_SALES_UNITS,
NULL AS YEAR_TO_DATE_TOTAL_SALES,
NULL AS YEAR_TO_DATE_LY_TOTAL_SALES,
NULL AS YEAR_TO_DATE_TOTAL_SALES_PERCENTAGE,
NULL AS YEAR_TO_DATE_WEEKLY_AVERAGE_SALES,
NULL AS WEEKS_OF_SUPPLY_ON_HAND,
NULL AS WEEKS_OF_SUPPLY_ON_ORDER,
NULL AS TY_JDA_LOST_SALES,
NULL AS TY_JDA_SERVICE_LEVEL,
NULL AS LY_TURN_RATE,
NULL AS TY_TURN_RATE,
NULL AS VBU_NUMBER,
NULL AS WEEKS_OF_SUPPLY_IN_STOCK,
NULL AS _FIVETRAN_SYNCED,
NULL AS _FIVETRAN_DELETED,
'1900-01-01'::TIMESTAMP AS PSA_LOAD_DTS,
NULL AS PSA_RECORD_SOURCE,
'N' AS PSA_DELETE_IND,
CONVERT_TIMEZONE('UTC','1900-01-01'::TIMESTAMP) AS LOAD_DTS,
'USAZET.SNOWFLAKE.FBIN.DERIVED' AS REC_SRC,
''::BINARY AS HASHDIFF
FROM
TABLE(strtok_split_to_table('0|-1|-2', '|')) AS GR
{% endif %}
