---- SRC LAYER ----
WITH
SRC_SRC            as ( SELECT * FROM {{ ref('v_psa_stg_supplier_invoice_line__fib_ocf') }} as SRC 
{% if is_incremental() %}
      where src.load_dts > (select dateadd('HOUR',-1,max(load_dts)) from {{ this }})
    {% endif %} )

/*
SRC_SRC            as ( SELECT * FROM int_staging_views.v_psa_stg_supplier_invoice_line__fib_ocf )
*/
---- LOGIC LAYER ----

, LOGIC_SRC as (
    SELECT
        SUPPLIER_INVOICE_LINE_HK
      , INVOICE_ID
      , LINE_NUMBER
      , ATTRIBUTE_6
      , ATTRIBUTE_7
      , ORIGINAL_BASE_AMOUNT
      , INCOME_TAX_REGION
      , GLOBAL_ATTRIBUTE_DATE_1
      , PJC_CONTEXT_CATEGORY
      , PJC_PROJECT_ID
      , PJC_RESERVED_ATTRIBUTE_8
      , PJC_RESERVED_ATTRIBUTE_9
      , PJC_RESERVED_ATTRIBUTE_10
      , PJC_USER_DEF_ATTRIBUTE_1
      , PJC_USER_DEF_ATTRIBUTE_2
      , GLOBAL_ATTRIBUTE_7
      , GLOBAL_ATTRIBUTE_8
      , ATTRIBUTE_DATE_4
      , PJC_FUNDING_ALLOCATION_ID
      , PJC_TASK_ID
      , PJC_EXPENDITURE_TYPE_ID
      , PJC_EXPENDITURE_ITEM_DATE
      , PJC_RESERVED_ATTRIBUTE_1
      , PJC_RESERVED_ATTRIBUTE_5
      , PJC_RESERVED_ATTRIBUTE_6
      , SOURCE_TRX_LEVEL_TYPE
      , RETAINED_AMOUNT
      , RETAINED_AMOUNT_REMAINING
      , RETAINED_INVOICE_ID
      , RETAINED_LINE_NUMBER
      , LINE_SELECTED_FOR_RELEASE_FLAG
      , PJC_USER_DEF_ATTRIBUTE_3
      , PJC_USER_DEF_ATTRIBUTE_4
      , PJC_USER_DEF_ATTRIBUTE_5
      , DEF_ACCTG_NUMBER_OF_PERIODS
      , DEF_ACCTG_PERIOD_TYPE
      , SET_OF_BOOKS_ID
      , MODEL_NUMBER
      , LINE_TYPE_LOOKUP_CODE
      , DISTRIBUTION_SET_ID
      , QUANTITY_INVOICED
      , UNIT_MEAS_LOOKUP_CODE
      , UNIT_PRICE
      , SHIP_FROM_LOCATION_ID
      , TASK_ID
      , EXPENDITURE_TYPE
      , EXPENDITURE_ITEM_DATE
      , CORRECTED_LINE_NUMBER
      , PO_HEADER_ID
      , PO_LINE_LOCATION_ID
      , BASE_AMOUNT
      , ROUNDING_AMT
      , AMOUNT
      , CONSUMPTION_ADVICE_LINE_ID
      , GLOBAL_ATTRIBUTE_NUMBER_4
      , GLOBAL_ATTRIBUTE_NUMBER_5
      , OBJECT_VERSION_NUMBER
      , JOB_DEFINITION_NAME
      , GLOBAL_ATTRIBUTE_NUMBER_3
      , INVOICE_INCLUDES_PREPAY_FLAG
      , PA_CC_AR_INVOICE_ID
      , WEB_PARAMETER_ID
      , ADJUSTMENT_REASON
      , MERCHANT_DOCUMENT_NUMBER
      , TRANSACTION_LINE_GEOGRAPHY_ID
      , GLOBAL_ATTRIBUTE_5
      , ATTRIBUTE_DATE_5
      , GLOBAL_ATTRIBUTE_NUMBER_1
      , GLOBAL_ATTRIBUTE_6
      , GLOBAL_ATTRIBUTE_18
      , GLOBAL_ATTRIBUTE_19
      , GLOBAL_ATTRIBUTE_20
      , LINE_SELECTED_FOR_APPL_FLAG
      , PA_CC_PROCESSED_CODE
      , AWARD_ID
      , PA_CC_AR_INVOICE_LINE_NUM
      , AWT_GROUP_ID
      , REFERENCE_1
      , REFERENCE_2
      , RECEIPT_VERIFIED_FLAG
      , RECEIPT_REQUIRED_FLAG
      , RECEIPT_MISSING_FLAG
      , START_EXPENSE_DATE
      , END_EXPENSE_DATE
      , PREPAY_APPL_REQUEST_ID
      , APPLICATION_ID
      , REFERENCE_KEY_1
      , REFERENCE_KEY_2
      , REFERENCE_KEY_3
      , PRODUCT_TABLE
      , ATTRIBUTE_14
      , ATTRIBUTE_15
      , PA_QUANTITY
      , COMPANY_PREPAID_INVOICE_ID
      , CC_REVERSAL_FLAG
      , ATTRIBUTE_3
      , ATTRIBUTE_4
      , ATTRIBUTE_5
      , ATTRIBUTE_10
      , ATTRIBUTE_11
      , ATTRIBUTE_12
      , ATTRIBUTE_8
      , ATTRIBUTE_9
      , GLOBAL_ATTRIBUTE_4
      , PJC_RESERVED_ATTRIBUTE_7
      , PJC_CONTRACT_ID
      , PJC_CONTRACT_LINE_ID
      , BUDGET_DATE
      , FUNDS_STATUS
      , PERIOD_NAME
      , DEFERRED_ACCTG_FLAG
      , DEF_ACCTG_START_DATE
      , PJC_USER_DEF_ATTRIBUTE_8
      , PJC_USER_DEF_ATTRIBUTE_9
      , PJC_USER_DEF_ATTRIBUTE_10
      , ATTRIBUTE_NUMBER_1
      , ATTRIBUTE_NUMBER_2
      , ATTRIBUTE_NUMBER_3
      , ATTRIBUTE_NUMBER_4
      , ATTRIBUTE_NUMBER_5
      , GLOBAL_ATTRIBUTE_13
      , PRORATE_ACROSS_ALL_ITEMS
      , WARRANTY_NUMBER
      , ACCOUNT_SEGMENT
      , DEF_ACCTG_END_DATE
      , TOTAL_REC_TAX_AMOUNT
      , PJC_USER_DEF_ATTRIBUTE_6
      , PJC_USER_DEF_ATTRIBUTE_7
      , ATTRIBUTE_13
      , COST_FACTOR_ID
      , CONTROL_AMOUNT
      , ASSESSABLE_VALUE
      , BALANCING_SEGMENT
      , COST_CENTER_SEGMENT
      , OVERLAY_DIST_CODE_CONCAT
      , DEFAULT_DIST_CCID
      , ACCOUNTING_DATE
      , GLOBAL_ATTRIBUTE_10
      , GLOBAL_ATTRIBUTE_11
      , GLOBAL_ATTRIBUTE_12
      , INCLUDED_TAX_AMOUNT
      , PJC_RESERVED_ATTRIBUTE_2
      , PJC_RESERVED_ATTRIBUTE_3
      , PJC_RESERVED_ATTRIBUTE_4
      , PURCHASING_CATEGORY_ID
      , ORIGINAL_ROUNDING_AMT
      , CANCELLED_FLAG
      , TYPE_1099
      , DISCARDED_FLAG
      , ORIGINAL_AMOUNT
      , WFAPPROVAL_STATUS
      , USSGL_TRANSACTION_CODE
      , JUSTIFICATION
      , EXPENSE_GROUP
      , PO_RELEASE_ID
      , PO_LINE_ID
      , CREATION_DATE
      , CREATED_BY
      , LAST_UPDATED_BY
      , EXPENDITURE_ORGANIZATION_ID
      , CREDIT_CARD_TRX_ID
      , LAST_UPDATE_LOGIN
      , PROGRAM_APPLICATION_ID
      , LAST_UPDATE_DATE
      , ACC_REFERENCE_VALUE_1
      , GLOBAL_ATTRIBUTE_DATE_2
      , GLOBAL_ATTRIBUTE_DATE_3
      , GLOBAL_ATTRIBUTE_DATE_4
      , GLOBAL_ATTRIBUTE_DATE_5
      , CORRECTED_INV_ID
      , TOTAL_NREC_TAX_AMOUNT
      , MATCH_TYPE
      , RCV_TRANSACTION_ID
      , FINAL_MATCH_FLAG
      , ASSETS_TRACKING_FLAG
      , ASSET_BOOK_TYPE_CODE
      , ASSET_CATEGORY_ID
      , PO_DISTRIBUTION_ID
      , REFERENCE_KEY_4
      , REFERENCE_KEY_5
      , TAX_ALREADY_CALCULATED_FLAG
      , SHIP_TO_LOCATION_ID
      , TOTAL_REC_TAX_AMT_FUNCL_CURR
      , TOTAL_NREC_TAX_AMT_FUNCL_CURR
      , GLOBAL_ATTRIBUTE_9
      , INTENDED_USE_CLASSIF_ID
      , PRIMARY_INTENDED_USE
      , TAX
      , TAX_JURISDICTION_CODE
      , REQUESTER_ID
      , DESCRIPTION
      , LINE_SOURCE
      , ORG_ID
      , LINE_GROUP_NUMBER
      , INVENTORY_ITEM_ID
      , ITEM_DESCRIPTION
      , FISCAL_CHARGE_TYPE
      , GLOBAL_ATTRIBUTE_1
      , GLOBAL_ATTRIBUTE_2
      , RECEIPT_CURRENCY_CODE
      , RECEIPT_CONVERSION_RATE
      , RECEIPT_CURRENCY_AMOUNT
      , DAILY_AMOUNT
      , PROGRAM_ID
      , PROGRAM_UPDATE_DATE
      , REQUEST_ID
      , GLOBAL_ATTRIBUTE_16
      , GLOBAL_ATTRIBUTE_17
      , GLOBAL_ATTRIBUTE_14
      , GLOBAL_ATTRIBUTE_15
      , GLOBAL_ATTRIBUTE_CATEGORY
      , GLOBAL_ATTRIBUTE_3
      , DEF_ACCTG_ACCRUAL_CCID
      , SHIP_TO_CUST_LOCATION_ID
      , STAT_AMOUNT
      , PREPAY_INVOICE_ID
      , PREPAY_LINE_NUMBER
      , PROJECT_ID
      , GENERATE_DISTS
      , TAX_REGIME_CODE
      , SERIAL_NUMBER
      , MANUFACTURER
      , JOB_DEFINITION_PACKAGE
      , FINAL_DISCHARGE_LOCATION_ID
      , FOS_XFACE_FLAG
      , MATCHING_RULE_SET_ID
      , MATCHING_RULE_ID
      , RCV_SHIPMENT_LINE_ID
      , PJC_ORGANIZATION_ID
      , TAX_STATUS_CODE
      , TAX_RATE
      , TAX_CODE_ID
      , HISTORICAL_FLAG
      , DISPUTABLE_FLAG
      , USER_DEFINED_FISC_CLASS
      , TRX_BUSINESS_CATEGORY
      , SUMMARY_TAX_LINE_ID
      , PRODUCT_TYPE
      , PRODUCT_CATEGORY
      , TAX_RATE_ID
      , TAX_RATE_CODE
      , PRODUCT_FISC_CLASSIFICATION
      , PROD_FC_CATEG_ID
      , LINE_OWNER_ROLE
      , MERCHANT_NAME
      , MERCHANT_REFERENCE
      , MERCHANT_TAX_REG_NUMBER
      , MERCHANT_TAXPAYER_ID
      , PJC_BILLABLE_FLAG
      , PJC_CAPITALIZABLE_FLAG
      , PJC_WORK_TYPE_ID
      , ATTRIBUTE_CATEGORY
      , ATTRIBUTE_1
      , ATTRIBUTE_2
      , GLOBAL_ATTRIBUTE_NUMBER_2
      , TAX_CLASSIFICATION_CODE
      , SOURCE_EVENT_CLASS_CODE
      , SOURCE_ENTITY_CODE
      , SOURCE_TRX_ID
      , COUNTRY_OF_SUPPLY
      , ATTRIBUTE_DATE_1
      , ATTRIBUTE_DATE_2
      , ATTRIBUTE_DATE_3
      , SOURCE_LINE_ID
      , SOURCE_APPLICATION_ID
      , CONSUMPTION_ADVICE_HEADER_ID
      , LCM_ENABLED_FLAG
      , PSA_DELETE_IND
      , PSA_LOAD_DTS
      , PSA_RECORD_SOURCE
      , _FIVETRAN_SYNCED
      , _FIVETRAN_DELETED
      , LOAD_DTS
      , REC_SRC
      , BKCC
      , HASHDIFF
    FROM SRC_SRC
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM LOGIC_SRC
)

---- FINAL LAYER ----
SELECT
          SUPPLIER_INVOICE_LINE_HK
        , INVOICE_ID
        , LINE_NUMBER
        , ATTRIBUTE_6
        , ATTRIBUTE_7
        , ORIGINAL_BASE_AMOUNT
        , INCOME_TAX_REGION
        , GLOBAL_ATTRIBUTE_DATE_1
        , PJC_CONTEXT_CATEGORY
        , PJC_PROJECT_ID
        , PJC_RESERVED_ATTRIBUTE_8
        , PJC_RESERVED_ATTRIBUTE_9
        , PJC_RESERVED_ATTRIBUTE_10
        , PJC_USER_DEF_ATTRIBUTE_1
        , PJC_USER_DEF_ATTRIBUTE_2
        , GLOBAL_ATTRIBUTE_7
        , GLOBAL_ATTRIBUTE_8
        , ATTRIBUTE_DATE_4
        , PJC_FUNDING_ALLOCATION_ID
        , PJC_TASK_ID
        , PJC_EXPENDITURE_TYPE_ID
        , PJC_EXPENDITURE_ITEM_DATE
        , PJC_RESERVED_ATTRIBUTE_1
        , PJC_RESERVED_ATTRIBUTE_5
        , PJC_RESERVED_ATTRIBUTE_6
        , SOURCE_TRX_LEVEL_TYPE
        , RETAINED_AMOUNT
        , RETAINED_AMOUNT_REMAINING
        , RETAINED_INVOICE_ID
        , RETAINED_LINE_NUMBER
        , LINE_SELECTED_FOR_RELEASE_FLAG
        , PJC_USER_DEF_ATTRIBUTE_3
        , PJC_USER_DEF_ATTRIBUTE_4
        , PJC_USER_DEF_ATTRIBUTE_5
        , DEF_ACCTG_NUMBER_OF_PERIODS
        , DEF_ACCTG_PERIOD_TYPE
        , SET_OF_BOOKS_ID
        , MODEL_NUMBER
        , LINE_TYPE_LOOKUP_CODE
        , DISTRIBUTION_SET_ID
        , QUANTITY_INVOICED
        , UNIT_MEAS_LOOKUP_CODE
        , UNIT_PRICE
        , SHIP_FROM_LOCATION_ID
        , TASK_ID
        , EXPENDITURE_TYPE
        , EXPENDITURE_ITEM_DATE
        , CORRECTED_LINE_NUMBER
        , PO_HEADER_ID
        , PO_LINE_LOCATION_ID
        , BASE_AMOUNT
        , ROUNDING_AMT
        , AMOUNT
        , CONSUMPTION_ADVICE_LINE_ID
        , GLOBAL_ATTRIBUTE_NUMBER_4
        , GLOBAL_ATTRIBUTE_NUMBER_5
        , OBJECT_VERSION_NUMBER
        , JOB_DEFINITION_NAME
        , GLOBAL_ATTRIBUTE_NUMBER_3
        , INVOICE_INCLUDES_PREPAY_FLAG
        , PA_CC_AR_INVOICE_ID
        , WEB_PARAMETER_ID
        , ADJUSTMENT_REASON
        , MERCHANT_DOCUMENT_NUMBER
        , TRANSACTION_LINE_GEOGRAPHY_ID
        , GLOBAL_ATTRIBUTE_5
        , ATTRIBUTE_DATE_5
        , GLOBAL_ATTRIBUTE_NUMBER_1
        , GLOBAL_ATTRIBUTE_6
        , GLOBAL_ATTRIBUTE_18
        , GLOBAL_ATTRIBUTE_19
        , GLOBAL_ATTRIBUTE_20
        , LINE_SELECTED_FOR_APPL_FLAG
        , PA_CC_PROCESSED_CODE
        , AWARD_ID
        , PA_CC_AR_INVOICE_LINE_NUM
        , AWT_GROUP_ID
        , REFERENCE_1
        , REFERENCE_2
        , RECEIPT_VERIFIED_FLAG
        , RECEIPT_REQUIRED_FLAG
        , RECEIPT_MISSING_FLAG
        , START_EXPENSE_DATE
        , END_EXPENSE_DATE
        , PREPAY_APPL_REQUEST_ID
        , APPLICATION_ID
        , REFERENCE_KEY_1
        , REFERENCE_KEY_2
        , REFERENCE_KEY_3
        , PRODUCT_TABLE
        , ATTRIBUTE_14
        , ATTRIBUTE_15
        , PA_QUANTITY
        , COMPANY_PREPAID_INVOICE_ID
        , CC_REVERSAL_FLAG
        , ATTRIBUTE_3
        , ATTRIBUTE_4
        , ATTRIBUTE_5
        , ATTRIBUTE_10
        , ATTRIBUTE_11
        , ATTRIBUTE_12
        , ATTRIBUTE_8
        , ATTRIBUTE_9
        , GLOBAL_ATTRIBUTE_4
        , PJC_RESERVED_ATTRIBUTE_7
        , PJC_CONTRACT_ID
        , PJC_CONTRACT_LINE_ID
        , BUDGET_DATE
        , FUNDS_STATUS
        , PERIOD_NAME
        , DEFERRED_ACCTG_FLAG
        , DEF_ACCTG_START_DATE
        , PJC_USER_DEF_ATTRIBUTE_8
        , PJC_USER_DEF_ATTRIBUTE_9
        , PJC_USER_DEF_ATTRIBUTE_10
        , ATTRIBUTE_NUMBER_1
        , ATTRIBUTE_NUMBER_2
        , ATTRIBUTE_NUMBER_3
        , ATTRIBUTE_NUMBER_4
        , ATTRIBUTE_NUMBER_5
        , GLOBAL_ATTRIBUTE_13
        , PRORATE_ACROSS_ALL_ITEMS
        , WARRANTY_NUMBER
        , ACCOUNT_SEGMENT
        , DEF_ACCTG_END_DATE
        , TOTAL_REC_TAX_AMOUNT
        , PJC_USER_DEF_ATTRIBUTE_6
        , PJC_USER_DEF_ATTRIBUTE_7
        , ATTRIBUTE_13
        , COST_FACTOR_ID
        , CONTROL_AMOUNT
        , ASSESSABLE_VALUE
        , BALANCING_SEGMENT
        , COST_CENTER_SEGMENT
        , OVERLAY_DIST_CODE_CONCAT
        , DEFAULT_DIST_CCID
        , ACCOUNTING_DATE
        , GLOBAL_ATTRIBUTE_10
        , GLOBAL_ATTRIBUTE_11
        , GLOBAL_ATTRIBUTE_12
        , INCLUDED_TAX_AMOUNT
        , PJC_RESERVED_ATTRIBUTE_2
        , PJC_RESERVED_ATTRIBUTE_3
        , PJC_RESERVED_ATTRIBUTE_4
        , PURCHASING_CATEGORY_ID
        , ORIGINAL_ROUNDING_AMT
        , CANCELLED_FLAG
        , TYPE_1099
        , DISCARDED_FLAG
        , ORIGINAL_AMOUNT
        , WFAPPROVAL_STATUS
        , USSGL_TRANSACTION_CODE
        , JUSTIFICATION
        , EXPENSE_GROUP
        , PO_RELEASE_ID
        , PO_LINE_ID
        , CREATION_DATE
        , CREATED_BY
        , LAST_UPDATED_BY
        , EXPENDITURE_ORGANIZATION_ID
        , CREDIT_CARD_TRX_ID
        , LAST_UPDATE_LOGIN
        , PROGRAM_APPLICATION_ID
        , LAST_UPDATE_DATE
        , ACC_REFERENCE_VALUE_1
        , GLOBAL_ATTRIBUTE_DATE_2
        , GLOBAL_ATTRIBUTE_DATE_3
        , GLOBAL_ATTRIBUTE_DATE_4
        , GLOBAL_ATTRIBUTE_DATE_5
        , CORRECTED_INV_ID
        , TOTAL_NREC_TAX_AMOUNT
        , MATCH_TYPE
        , RCV_TRANSACTION_ID
        , FINAL_MATCH_FLAG
        , ASSETS_TRACKING_FLAG
        , ASSET_BOOK_TYPE_CODE
        , ASSET_CATEGORY_ID
        , PO_DISTRIBUTION_ID
        , REFERENCE_KEY_4
        , REFERENCE_KEY_5
        , TAX_ALREADY_CALCULATED_FLAG
        , SHIP_TO_LOCATION_ID
        , TOTAL_REC_TAX_AMT_FUNCL_CURR
        , TOTAL_NREC_TAX_AMT_FUNCL_CURR
        , GLOBAL_ATTRIBUTE_9
        , INTENDED_USE_CLASSIF_ID
        , PRIMARY_INTENDED_USE
        , TAX
        , TAX_JURISDICTION_CODE
        , REQUESTER_ID
        , DESCRIPTION
        , LINE_SOURCE
        , ORG_ID
        , LINE_GROUP_NUMBER
        , INVENTORY_ITEM_ID
        , ITEM_DESCRIPTION
        , FISCAL_CHARGE_TYPE
        , GLOBAL_ATTRIBUTE_1
        , GLOBAL_ATTRIBUTE_2
        , RECEIPT_CURRENCY_CODE
        , RECEIPT_CONVERSION_RATE
        , RECEIPT_CURRENCY_AMOUNT
        , DAILY_AMOUNT
        , PROGRAM_ID
        , PROGRAM_UPDATE_DATE
        , REQUEST_ID
        , GLOBAL_ATTRIBUTE_16
        , GLOBAL_ATTRIBUTE_17
        , GLOBAL_ATTRIBUTE_14
        , GLOBAL_ATTRIBUTE_15
        , GLOBAL_ATTRIBUTE_CATEGORY
        , GLOBAL_ATTRIBUTE_3
        , DEF_ACCTG_ACCRUAL_CCID
        , SHIP_TO_CUST_LOCATION_ID
        , STAT_AMOUNT
        , PREPAY_INVOICE_ID
        , PREPAY_LINE_NUMBER
        , PROJECT_ID
        , GENERATE_DISTS
        , TAX_REGIME_CODE
        , SERIAL_NUMBER
        , MANUFACTURER
        , JOB_DEFINITION_PACKAGE
        , FINAL_DISCHARGE_LOCATION_ID
        , FOS_XFACE_FLAG
        , MATCHING_RULE_SET_ID
        , MATCHING_RULE_ID
        , RCV_SHIPMENT_LINE_ID
        , PJC_ORGANIZATION_ID
        , TAX_STATUS_CODE
        , TAX_RATE
        , TAX_CODE_ID
        , HISTORICAL_FLAG
        , DISPUTABLE_FLAG
        , USER_DEFINED_FISC_CLASS
        , TRX_BUSINESS_CATEGORY
        , SUMMARY_TAX_LINE_ID
        , PRODUCT_TYPE
        , PRODUCT_CATEGORY
        , TAX_RATE_ID
        , TAX_RATE_CODE
        , PRODUCT_FISC_CLASSIFICATION
        , PROD_FC_CATEG_ID
        , LINE_OWNER_ROLE
        , MERCHANT_NAME
        , MERCHANT_REFERENCE
        , MERCHANT_TAX_REG_NUMBER
        , MERCHANT_TAXPAYER_ID
        , PJC_BILLABLE_FLAG
        , PJC_CAPITALIZABLE_FLAG
        , PJC_WORK_TYPE_ID
        , ATTRIBUTE_CATEGORY
        , ATTRIBUTE_1
        , ATTRIBUTE_2
        , GLOBAL_ATTRIBUTE_NUMBER_2
        , TAX_CLASSIFICATION_CODE
        , SOURCE_EVENT_CLASS_CODE
        , SOURCE_ENTITY_CODE
        , SOURCE_TRX_ID
        , COUNTRY_OF_SUPPLY
        , ATTRIBUTE_DATE_1
        , ATTRIBUTE_DATE_2
        , ATTRIBUTE_DATE_3
        , SOURCE_LINE_ID
        , SOURCE_APPLICATION_ID
        , CONSUMPTION_ADVICE_HEADER_ID
        , LCM_ENABLED_FLAG
        , PSA_DELETE_IND
        , PSA_LOAD_DTS
        , PSA_RECORD_SOURCE
        , _FIVETRAN_SYNCED
        , _FIVETRAN_DELETED
        , LOAD_DTS
        , REC_SRC
        , BKCC
        , HASHDIFF
FROM JOIN_RESULT
{% if is_incremental() %}
WHERE NOT EXISTS (
    SELECT 1
    FROM {{ this }} existing
    WHERE existing.SUPPLIER_INVOICE_LINE_HK = JOIN_RESULT.SUPPLIER_INVOICE_LINE_HK
      AND existing.HASHDIFF = JOIN_RESULT.HASHDIFF
)
{% endif %}
{% if not is_incremental() %}

/* The following qualifier is implemented to prevent multiple loads of touched records during the initial build, such as multiple rows per HK and hashdiff. */
qualify 1 = row_number() over (partition by SUPPLIER_INVOICE_LINE_HK, HASHDIFF order by PSA_LOAD_DTS)

union all
SELECT 
MD5_BINARY(GR.VALUE) AS SUPPLIER_INVOICE_LINE_HK,
NULL AS INVOICE_ID,
NULL AS LINE_NUMBER,
NULL AS ATTRIBUTE_6,
NULL AS ATTRIBUTE_7,
NULL AS ORIGINAL_BASE_AMOUNT,
NULL AS INCOME_TAX_REGION,
NULL AS GLOBAL_ATTRIBUTE_DATE_1,
NULL AS PJC_CONTEXT_CATEGORY,
NULL AS PJC_PROJECT_ID,
NULL AS PJC_RESERVED_ATTRIBUTE_8,
NULL AS PJC_RESERVED_ATTRIBUTE_9,
NULL AS PJC_RESERVED_ATTRIBUTE_10,
NULL AS PJC_USER_DEF_ATTRIBUTE_1,
NULL AS PJC_USER_DEF_ATTRIBUTE_2,
NULL AS GLOBAL_ATTRIBUTE_7,
NULL AS GLOBAL_ATTRIBUTE_8,
NULL AS ATTRIBUTE_DATE_4,
NULL AS PJC_FUNDING_ALLOCATION_ID,
NULL AS PJC_TASK_ID,
NULL AS PJC_EXPENDITURE_TYPE_ID,
NULL AS PJC_EXPENDITURE_ITEM_DATE,
NULL AS PJC_RESERVED_ATTRIBUTE_1,
NULL AS PJC_RESERVED_ATTRIBUTE_5,
NULL AS PJC_RESERVED_ATTRIBUTE_6,
NULL AS SOURCE_TRX_LEVEL_TYPE,
NULL AS RETAINED_AMOUNT,
NULL AS RETAINED_AMOUNT_REMAINING,
NULL AS RETAINED_INVOICE_ID,
NULL AS RETAINED_LINE_NUMBER,
NULL AS LINE_SELECTED_FOR_RELEASE_FLAG,
NULL AS PJC_USER_DEF_ATTRIBUTE_3,
NULL AS PJC_USER_DEF_ATTRIBUTE_4,
NULL AS PJC_USER_DEF_ATTRIBUTE_5,
NULL AS DEF_ACCTG_NUMBER_OF_PERIODS,
NULL AS DEF_ACCTG_PERIOD_TYPE,
NULL AS SET_OF_BOOKS_ID,
NULL AS MODEL_NUMBER,
NULL AS LINE_TYPE_LOOKUP_CODE,
NULL AS DISTRIBUTION_SET_ID,
NULL AS QUANTITY_INVOICED,
NULL AS UNIT_MEAS_LOOKUP_CODE,
NULL AS UNIT_PRICE,
NULL AS SHIP_FROM_LOCATION_ID,
NULL AS TASK_ID,
NULL AS EXPENDITURE_TYPE,
NULL AS EXPENDITURE_ITEM_DATE,
NULL AS CORRECTED_LINE_NUMBER,
NULL AS PO_HEADER_ID,
NULL AS PO_LINE_LOCATION_ID,
NULL AS BASE_AMOUNT,
NULL AS ROUNDING_AMT,
NULL AS AMOUNT,
NULL AS CONSUMPTION_ADVICE_LINE_ID,
NULL AS GLOBAL_ATTRIBUTE_NUMBER_4,
NULL AS GLOBAL_ATTRIBUTE_NUMBER_5,
NULL AS OBJECT_VERSION_NUMBER,
NULL AS JOB_DEFINITION_NAME,
NULL AS GLOBAL_ATTRIBUTE_NUMBER_3,
NULL AS INVOICE_INCLUDES_PREPAY_FLAG,
NULL AS PA_CC_AR_INVOICE_ID,
NULL AS WEB_PARAMETER_ID,
NULL AS ADJUSTMENT_REASON,
NULL AS MERCHANT_DOCUMENT_NUMBER,
NULL AS TRANSACTION_LINE_GEOGRAPHY_ID,
NULL AS GLOBAL_ATTRIBUTE_5,
NULL AS ATTRIBUTE_DATE_5,
NULL AS GLOBAL_ATTRIBUTE_NUMBER_1,
NULL AS GLOBAL_ATTRIBUTE_6,
NULL AS GLOBAL_ATTRIBUTE_18,
NULL AS GLOBAL_ATTRIBUTE_19,
NULL AS GLOBAL_ATTRIBUTE_20,
NULL AS LINE_SELECTED_FOR_APPL_FLAG,
NULL AS PA_CC_PROCESSED_CODE,
NULL AS AWARD_ID,
NULL AS PA_CC_AR_INVOICE_LINE_NUM,
NULL AS AWT_GROUP_ID,
NULL AS REFERENCE_1,
NULL AS REFERENCE_2,
NULL AS RECEIPT_VERIFIED_FLAG,
NULL AS RECEIPT_REQUIRED_FLAG,
NULL AS RECEIPT_MISSING_FLAG,
NULL AS START_EXPENSE_DATE,
NULL AS END_EXPENSE_DATE,
NULL AS PREPAY_APPL_REQUEST_ID,
NULL AS APPLICATION_ID,
NULL AS REFERENCE_KEY_1,
NULL AS REFERENCE_KEY_2,
NULL AS REFERENCE_KEY_3,
NULL AS PRODUCT_TABLE,
NULL AS ATTRIBUTE_14,
NULL AS ATTRIBUTE_15,
NULL AS PA_QUANTITY,
NULL AS COMPANY_PREPAID_INVOICE_ID,
NULL AS CC_REVERSAL_FLAG,
NULL AS ATTRIBUTE_3,
NULL AS ATTRIBUTE_4,
NULL AS ATTRIBUTE_5,
NULL AS ATTRIBUTE_10,
NULL AS ATTRIBUTE_11,
NULL AS ATTRIBUTE_12,
NULL AS ATTRIBUTE_8,
NULL AS ATTRIBUTE_9,
NULL AS GLOBAL_ATTRIBUTE_4,
NULL AS PJC_RESERVED_ATTRIBUTE_7,
NULL AS PJC_CONTRACT_ID,
NULL AS PJC_CONTRACT_LINE_ID,
NULL AS BUDGET_DATE,
NULL AS FUNDS_STATUS,
NULL AS PERIOD_NAME,
NULL AS DEFERRED_ACCTG_FLAG,
NULL AS DEF_ACCTG_START_DATE,
NULL AS PJC_USER_DEF_ATTRIBUTE_8,
NULL AS PJC_USER_DEF_ATTRIBUTE_9,
NULL AS PJC_USER_DEF_ATTRIBUTE_10,
NULL AS ATTRIBUTE_NUMBER_1,
NULL AS ATTRIBUTE_NUMBER_2,
NULL AS ATTRIBUTE_NUMBER_3,
NULL AS ATTRIBUTE_NUMBER_4,
NULL AS ATTRIBUTE_NUMBER_5,
NULL AS GLOBAL_ATTRIBUTE_13,
NULL AS PRORATE_ACROSS_ALL_ITEMS,
NULL AS WARRANTY_NUMBER,
NULL AS ACCOUNT_SEGMENT,
NULL AS DEF_ACCTG_END_DATE,
NULL AS TOTAL_REC_TAX_AMOUNT,
NULL AS PJC_USER_DEF_ATTRIBUTE_6,
NULL AS PJC_USER_DEF_ATTRIBUTE_7,
NULL AS ATTRIBUTE_13,
NULL AS COST_FACTOR_ID,
NULL AS CONTROL_AMOUNT,
NULL AS ASSESSABLE_VALUE,
NULL AS BALANCING_SEGMENT,
NULL AS COST_CENTER_SEGMENT,
NULL AS OVERLAY_DIST_CODE_CONCAT,
NULL AS DEFAULT_DIST_CCID,
NULL AS ACCOUNTING_DATE,
NULL AS GLOBAL_ATTRIBUTE_10,
NULL AS GLOBAL_ATTRIBUTE_11,
NULL AS GLOBAL_ATTRIBUTE_12,
NULL AS INCLUDED_TAX_AMOUNT,
NULL AS PJC_RESERVED_ATTRIBUTE_2,
NULL AS PJC_RESERVED_ATTRIBUTE_3,
NULL AS PJC_RESERVED_ATTRIBUTE_4,
NULL AS PURCHASING_CATEGORY_ID,
NULL AS ORIGINAL_ROUNDING_AMT,
NULL AS CANCELLED_FLAG,
NULL AS TYPE_1099,
NULL AS DISCARDED_FLAG,
NULL AS ORIGINAL_AMOUNT,
NULL AS WFAPPROVAL_STATUS,
NULL AS USSGL_TRANSACTION_CODE,
NULL AS JUSTIFICATION,
NULL AS EXPENSE_GROUP,
NULL AS PO_RELEASE_ID,
NULL AS PO_LINE_ID,
NULL AS CREATION_DATE,
NULL AS CREATED_BY,
NULL AS LAST_UPDATED_BY,
NULL AS EXPENDITURE_ORGANIZATION_ID,
NULL AS CREDIT_CARD_TRX_ID,
NULL AS LAST_UPDATE_LOGIN,
NULL AS PROGRAM_APPLICATION_ID,
NULL AS LAST_UPDATE_DATE,
NULL AS ACC_REFERENCE_VALUE_1,
NULL AS GLOBAL_ATTRIBUTE_DATE_2,
NULL AS GLOBAL_ATTRIBUTE_DATE_3,
NULL AS GLOBAL_ATTRIBUTE_DATE_4,
NULL AS GLOBAL_ATTRIBUTE_DATE_5,
NULL AS CORRECTED_INV_ID,
NULL AS TOTAL_NREC_TAX_AMOUNT,
NULL AS MATCH_TYPE,
NULL AS RCV_TRANSACTION_ID,
NULL AS FINAL_MATCH_FLAG,
NULL AS ASSETS_TRACKING_FLAG,
NULL AS ASSET_BOOK_TYPE_CODE,
NULL AS ASSET_CATEGORY_ID,
NULL AS PO_DISTRIBUTION_ID,
NULL AS REFERENCE_KEY_4,
NULL AS REFERENCE_KEY_5,
NULL AS TAX_ALREADY_CALCULATED_FLAG,
NULL AS SHIP_TO_LOCATION_ID,
NULL AS TOTAL_REC_TAX_AMT_FUNCL_CURR,
NULL AS TOTAL_NREC_TAX_AMT_FUNCL_CURR,
NULL AS GLOBAL_ATTRIBUTE_9,
NULL AS INTENDED_USE_CLASSIF_ID,
NULL AS PRIMARY_INTENDED_USE,
NULL AS TAX,
NULL AS TAX_JURISDICTION_CODE,
NULL AS REQUESTER_ID,
NULL AS DESCRIPTION,
NULL AS LINE_SOURCE,
NULL AS ORG_ID,
NULL AS LINE_GROUP_NUMBER,
NULL AS INVENTORY_ITEM_ID,
NULL AS ITEM_DESCRIPTION,
NULL AS FISCAL_CHARGE_TYPE,
NULL AS GLOBAL_ATTRIBUTE_1,
NULL AS GLOBAL_ATTRIBUTE_2,
NULL AS RECEIPT_CURRENCY_CODE,
NULL AS RECEIPT_CONVERSION_RATE,
NULL AS RECEIPT_CURRENCY_AMOUNT,
NULL AS DAILY_AMOUNT,
NULL AS PROGRAM_ID,
NULL AS PROGRAM_UPDATE_DATE,
NULL AS REQUEST_ID,
NULL AS GLOBAL_ATTRIBUTE_16,
NULL AS GLOBAL_ATTRIBUTE_17,
NULL AS GLOBAL_ATTRIBUTE_14,
NULL AS GLOBAL_ATTRIBUTE_15,
NULL AS GLOBAL_ATTRIBUTE_CATEGORY,
NULL AS GLOBAL_ATTRIBUTE_3,
NULL AS DEF_ACCTG_ACCRUAL_CCID,
NULL AS SHIP_TO_CUST_LOCATION_ID,
NULL AS STAT_AMOUNT,
NULL AS PREPAY_INVOICE_ID,
NULL AS PREPAY_LINE_NUMBER,
NULL AS PROJECT_ID,
NULL AS GENERATE_DISTS,
NULL AS TAX_REGIME_CODE,
NULL AS SERIAL_NUMBER,
NULL AS MANUFACTURER,
NULL AS JOB_DEFINITION_PACKAGE,
NULL AS FINAL_DISCHARGE_LOCATION_ID,
NULL AS FOS_XFACE_FLAG,
NULL AS MATCHING_RULE_SET_ID,
NULL AS MATCHING_RULE_ID,
NULL AS RCV_SHIPMENT_LINE_ID,
NULL AS PJC_ORGANIZATION_ID,
NULL AS TAX_STATUS_CODE,
NULL AS TAX_RATE,
NULL AS TAX_CODE_ID,
NULL AS HISTORICAL_FLAG,
NULL AS DISPUTABLE_FLAG,
NULL AS USER_DEFINED_FISC_CLASS,
NULL AS TRX_BUSINESS_CATEGORY,
NULL AS SUMMARY_TAX_LINE_ID,
NULL AS PRODUCT_TYPE,
NULL AS PRODUCT_CATEGORY,
NULL AS TAX_RATE_ID,
NULL AS TAX_RATE_CODE,
NULL AS PRODUCT_FISC_CLASSIFICATION,
NULL AS PROD_FC_CATEG_ID,
NULL AS LINE_OWNER_ROLE,
NULL AS MERCHANT_NAME,
NULL AS MERCHANT_REFERENCE,
NULL AS MERCHANT_TAX_REG_NUMBER,
NULL AS MERCHANT_TAXPAYER_ID,
NULL AS PJC_BILLABLE_FLAG,
NULL AS PJC_CAPITALIZABLE_FLAG,
NULL AS PJC_WORK_TYPE_ID,
NULL AS ATTRIBUTE_CATEGORY,
NULL AS ATTRIBUTE_1,
NULL AS ATTRIBUTE_2,
NULL AS GLOBAL_ATTRIBUTE_NUMBER_2,
NULL AS TAX_CLASSIFICATION_CODE,
NULL AS SOURCE_EVENT_CLASS_CODE,
NULL AS SOURCE_ENTITY_CODE,
NULL AS SOURCE_TRX_ID,
NULL AS COUNTRY_OF_SUPPLY,
NULL AS ATTRIBUTE_DATE_1,
NULL AS ATTRIBUTE_DATE_2,
NULL AS ATTRIBUTE_DATE_3,
NULL AS SOURCE_LINE_ID,
NULL AS SOURCE_APPLICATION_ID,
NULL AS CONSUMPTION_ADVICE_HEADER_ID,
NULL AS LCM_ENABLED_FLAG,
'N' AS PSA_DELETE_IND,
'1900-01-01'::TIMESTAMP AS PSA_LOAD_DTS,
NULL AS PSA_RECORD_SOURCE,
NULL AS _FIVETRAN_SYNCED,
NULL AS _FIVETRAN_DELETED,
'1900-01-01T00:00:00'::TIMESTAMP_NTZ AS LOAD_DTS,
'USAZET.SNOWFLAKE.FBIN.DERIVED' AS REC_SRC,
DECODE(GR.VALUE, 0, 'GHOST RECORD-SYSTEM', -1, 'GHOST RECORD-nullkey-required', -2, 'GHOST RECORD-nullkey-optional') AS BKCC,
MD5_BINARY('') AS HASHDIFF
FROM
TABLE(strtok_split_to_table('0|-1|-2', '|')) AS GR
{% endif %}
