---- SRC LAYER ----
WITH
SRC_a              as ( SELECT * FROM {{ ref('v_psa_stg_po_item_schedule_lines__lrsn_psft') }} as SRC 
                         {% if is_incremental() %}
                              where src.load_dts > (select dateadd('HOUR',-1,max(load_dts)) from {{ this }})
                            {% endif %}   )

/*
SRC_a              as ( SELECT * FROM staging.v_psa_stg_po_item_schedule_lines__lrsn_psft )
*/
---- LOGIC LAYER ----

, LOGIC_a as (
    SELECT
        PO_ITEM_HK
      , BUSINESS_UNIT
      , PO_ID
      , LINE_NBR
      , SCHED_NBR
      , CANCEL_STATUS
      , BAL_STATUS
      , CHANGE_STATUS
      , CHNG_ORD_SEQ
      , PRICE_PO
      , PRICE_PO_BSE
      , CUSTOM_PRICE
      , ZERO_PRICE_IND
      , DUE_DT
      , DUE_TIME
      , SHIPTO_SETID
      , SHIPTO_ID
      , ORIG_PROM_DT
      , QTY_PO
      , CURRENCY_CD
      , MERCHANDISE_AMT
      , CURRENCY_CD_BASE
      , MERCH_AMT_BSE
      , CONVERSION_RATE
      , FREIGHT_TERMS
      , SHIP_TYPE_ID
      , DISTRIB_MTHD_FLG
      , LIQUIDATE_METHOD
      , UNIT_PRC_TOL
      , UNIT_PRC_TOL_BSE
      , PCT_UNIT_PRC_TOL
      , EXT_PRC_TOL
      , EXT_PRC_TOL_BSE
      , PCT_EXT_PRC_TOL
      , QTY_RECV_TOL_PCT
      , PCT_UNDER_QTY
      , MATCH_STATUS_LN_PO
      , MATCH_LINE_OPT
      , BUSINESS_UNIT_OM
      , ORDER_NO
      , ORDER_INT_LINE_NO
      , SCHED_LINE_NBR
      , SHIP_TO_CUST_ID
      , BUSINESS_UNIT_IN
      , PRODUCTION_ID
      , OP_SEQUENCE
      , FROZEN_FLG
      , PLAN_CHANGE_FLG
      , NET_CHANGE_EP
      , WORK_ORDER_ID
      , CARRIER_ID
      , SUT_BASE_ID
      , TAX_CD_SUT
      , ULTIMATE_USE_CD
      , SUT_EXCPTN_TYPE
      , SUT_EXCPTN_CERTIF
      , SUT_APPLICABILITY
      , VAT_RCRD_INPT_FLG
      , VAT_RCRD_OUTPT_FLG
      , VAT_DCLRTN_POINT
      , VAT_CALC_GROSS_NET
      , VAT_CALC_FRGHT_FLG
      , VAT_CALC_MISC_FLG
      , VAT_RECALC_FLG
      , VAT_TREATMENT_GRP
      , VAT_TREATMENT
      , COUNTRY_LOC_BUYER
      , STATE_LOC_BUYER
      , COUNTRY_LOC_SELLER
      , STATE_LOC_SELLER
      , VAT_SVC_SUPPLY_FLG
      , VAT_SERVICE_TYPE
      , COUNTRY_VAT_PERFRM
      , STATE_VAT_PERFRM
      , COUNTRY_VAT_SUPPLY
      , STATE_VAT_SUPPLY
      , STATE_VAT_DEFAULT
      , STATE_SHIP_FROM
      , STATE_SHIP_TO
      , VAT_EXCPTN_TYPE
      , VAT_EXCPTN_CERTIF
      , COUNTRY_SHIP_TO
      , COUNTRY_SHIP_FROM
      , COUNTRY_VAT_SHIPTO
      , COUNTRY_VAT_BILLTO
      , COUNTRY_VAT_BILLFR
      , VAT_RGSTRN_SELLER
      , VAT_TXN_TYPE_CD
      , VAT_APPLICABILITY
      , TAX_CD_VAT
      , VAT_USE_ID
      , IST_TXN_FLG
      , VAT_CALC_TYPE
      , BUSINESS_UNIT_RTV
      , RTV_ID
      , RTV_LN_NBR
      , RTV_VERIFIED
      , SHIP_DATE
      , UNIT_PRC_TOL_L
      , PCT_UNIT_PRC_TOL_L
      , EXT_PRC_TOL_L
      , PCT_EXT_PRC_TOL_L
      , UNIT_PRC_TOL_BSE_L
      , EXT_PRC_TOL_BSE_L
      , RJCT_OVER_TOL_FLAG
      , REJECT_DAYS
      , TAX_VAT_FLG
      , TAX_FRGHT_FLG
      , TAX_MISC_FLG
      , TRFT_RULE_CD
      , QTY_RFQ
      , SHIP_ID_EST
      , X_VENDOR_SETID
      , X_VENDOR_ID
      , X_VNDR_LOC
      , FRT_CHRG_METHOD
      , FRT_CHRG_OVERRIDE
      , VAT_ROUND_RULE
      , REVISION
      , PUBLISHED_SHIPTO
      , BCKORD_ORG_SCHED
      , BUSINESS_UNIT_SS
      , AUC_ID
      , AUC_LINE_NBR
      , AUC_SCHED_NBR
      , USER_SCHED_CHAR1
      , CUSTOM_C100_C1
      , CUSTOM_C100_C2
      , CUSTOM_C100_C3
      , CUSTOM_DATE_C1
      , CUSTOM_DATE_C2
      , CUSTOM_C1_C
      , VAT_RVRSE_CHG_GDS
      , PRICE_INITIAL
      , _FIVETRAN_ID
      , _FIVETRAN_DELETED
      , _FIVETRAN_SYNCED
      , PSA_DELETE_IND
      , PSA_LOAD_DTS
      , PSA_RECORD_SOURCE
      , LOAD_DTS
      , REC_SRC
      , BKCC
      , HASHDIFF
    FROM SRC_a
)
---- RENAME LAYER ----

, RENAME_a as (
    SELECT
        PO_ITEM_HK
      , BUSINESS_UNIT
      , PO_ID
      , LINE_NBR
      , SCHED_NBR
      , CANCEL_STATUS
      , BAL_STATUS
      , CHANGE_STATUS
      , CHNG_ORD_SEQ
      , PRICE_PO
      , PRICE_PO_BSE
      , CUSTOM_PRICE
      , ZERO_PRICE_IND
      , DUE_DT
      , DUE_TIME
      , SHIPTO_SETID
      , SHIPTO_ID
      , ORIG_PROM_DT
      , QTY_PO
      , CURRENCY_CD
      , MERCHANDISE_AMT
      , CURRENCY_CD_BASE
      , MERCH_AMT_BSE
      , CONVERSION_RATE
      , FREIGHT_TERMS
      , SHIP_TYPE_ID
      , DISTRIB_MTHD_FLG
      , LIQUIDATE_METHOD
      , UNIT_PRC_TOL
      , UNIT_PRC_TOL_BSE
      , PCT_UNIT_PRC_TOL
      , EXT_PRC_TOL
      , EXT_PRC_TOL_BSE
      , PCT_EXT_PRC_TOL
      , QTY_RECV_TOL_PCT
      , PCT_UNDER_QTY
      , MATCH_STATUS_LN_PO
      , MATCH_LINE_OPT
      , BUSINESS_UNIT_OM
      , ORDER_NO
      , ORDER_INT_LINE_NO
      , SCHED_LINE_NBR
      , SHIP_TO_CUST_ID
      , BUSINESS_UNIT_IN
      , PRODUCTION_ID
      , OP_SEQUENCE
      , FROZEN_FLG
      , PLAN_CHANGE_FLG
      , NET_CHANGE_EP
      , WORK_ORDER_ID
      , CARRIER_ID
      , SUT_BASE_ID
      , TAX_CD_SUT
      , ULTIMATE_USE_CD
      , SUT_EXCPTN_TYPE
      , SUT_EXCPTN_CERTIF
      , SUT_APPLICABILITY
      , VAT_RCRD_INPT_FLG
      , VAT_RCRD_OUTPT_FLG
      , VAT_DCLRTN_POINT
      , VAT_CALC_GROSS_NET
      , VAT_CALC_FRGHT_FLG
      , VAT_CALC_MISC_FLG
      , VAT_RECALC_FLG
      , VAT_TREATMENT_GRP
      , VAT_TREATMENT
      , COUNTRY_LOC_BUYER
      , STATE_LOC_BUYER
      , COUNTRY_LOC_SELLER
      , STATE_LOC_SELLER
      , VAT_SVC_SUPPLY_FLG
      , VAT_SERVICE_TYPE
      , COUNTRY_VAT_PERFRM
      , STATE_VAT_PERFRM
      , COUNTRY_VAT_SUPPLY
      , STATE_VAT_SUPPLY
      , STATE_VAT_DEFAULT
      , STATE_SHIP_FROM
      , STATE_SHIP_TO
      , VAT_EXCPTN_TYPE
      , VAT_EXCPTN_CERTIF
      , COUNTRY_SHIP_TO
      , COUNTRY_SHIP_FROM
      , COUNTRY_VAT_SHIPTO
      , COUNTRY_VAT_BILLTO
      , COUNTRY_VAT_BILLFR
      , VAT_RGSTRN_SELLER
      , VAT_TXN_TYPE_CD
      , VAT_APPLICABILITY
      , TAX_CD_VAT
      , VAT_USE_ID
      , IST_TXN_FLG
      , VAT_CALC_TYPE
      , BUSINESS_UNIT_RTV
      , RTV_ID
      , RTV_LN_NBR
      , RTV_VERIFIED
      , SHIP_DATE
      , UNIT_PRC_TOL_L
      , PCT_UNIT_PRC_TOL_L
      , EXT_PRC_TOL_L
      , PCT_EXT_PRC_TOL_L
      , UNIT_PRC_TOL_BSE_L
      , EXT_PRC_TOL_BSE_L
      , RJCT_OVER_TOL_FLAG
      , REJECT_DAYS
      , TAX_VAT_FLG
      , TAX_FRGHT_FLG
      , TAX_MISC_FLG
      , TRFT_RULE_CD
      , QTY_RFQ
      , SHIP_ID_EST
      , X_VENDOR_SETID
      , X_VENDOR_ID
      , X_VNDR_LOC
      , FRT_CHRG_METHOD
      , FRT_CHRG_OVERRIDE
      , VAT_ROUND_RULE
      , REVISION
      , PUBLISHED_SHIPTO
      , BCKORD_ORG_SCHED
      , BUSINESS_UNIT_SS
      , AUC_ID
      , AUC_LINE_NBR
      , AUC_SCHED_NBR
      , USER_SCHED_CHAR1
      , CUSTOM_C100_C1
      , CUSTOM_C100_C2
      , CUSTOM_C100_C3
      , CUSTOM_DATE_C1
      , CUSTOM_DATE_C2
      , CUSTOM_C1_C
      , VAT_RVRSE_CHG_GDS
      , PRICE_INITIAL
      , _FIVETRAN_ID
      , _FIVETRAN_DELETED
      , _FIVETRAN_SYNCED
      , PSA_DELETE_IND
      , PSA_LOAD_DTS
      , PSA_RECORD_SOURCE
      , LOAD_DTS
      , REC_SRC
      , BKCC
      , HASHDIFF
    FROM LOGIC_a
)
---- FILTER LAYER ----

, FILTER_a as (
    SELECT *
    FROM RENAME_a
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM FILTER_a
)

---- FINAL LAYER ----
SELECT
          PO_ITEM_HK
        , BUSINESS_UNIT
        , PO_ID
        , LINE_NBR
        , SCHED_NBR
        , CANCEL_STATUS
        , BAL_STATUS
        , CHANGE_STATUS
        , CHNG_ORD_SEQ
        , PRICE_PO
        , PRICE_PO_BSE
        , CUSTOM_PRICE
        , ZERO_PRICE_IND
        , DUE_DT
        , DUE_TIME
        , SHIPTO_SETID
        , SHIPTO_ID
        , ORIG_PROM_DT
        , QTY_PO
        , CURRENCY_CD
        , MERCHANDISE_AMT
        , CURRENCY_CD_BASE
        , MERCH_AMT_BSE
        , CONVERSION_RATE
        , FREIGHT_TERMS
        , SHIP_TYPE_ID
        , DISTRIB_MTHD_FLG
        , LIQUIDATE_METHOD
        , UNIT_PRC_TOL
        , UNIT_PRC_TOL_BSE
        , PCT_UNIT_PRC_TOL
        , EXT_PRC_TOL
        , EXT_PRC_TOL_BSE
        , PCT_EXT_PRC_TOL
        , QTY_RECV_TOL_PCT
        , PCT_UNDER_QTY
        , MATCH_STATUS_LN_PO
        , MATCH_LINE_OPT
        , BUSINESS_UNIT_OM
        , ORDER_NO
        , ORDER_INT_LINE_NO
        , SCHED_LINE_NBR
        , SHIP_TO_CUST_ID
        , BUSINESS_UNIT_IN
        , PRODUCTION_ID
        , OP_SEQUENCE
        , FROZEN_FLG
        , PLAN_CHANGE_FLG
        , NET_CHANGE_EP
        , WORK_ORDER_ID
        , CARRIER_ID
        , SUT_BASE_ID
        , TAX_CD_SUT
        , ULTIMATE_USE_CD
        , SUT_EXCPTN_TYPE
        , SUT_EXCPTN_CERTIF
        , SUT_APPLICABILITY
        , VAT_RCRD_INPT_FLG
        , VAT_RCRD_OUTPT_FLG
        , VAT_DCLRTN_POINT
        , VAT_CALC_GROSS_NET
        , VAT_CALC_FRGHT_FLG
        , VAT_CALC_MISC_FLG
        , VAT_RECALC_FLG
        , VAT_TREATMENT_GRP
        , VAT_TREATMENT
        , COUNTRY_LOC_BUYER
        , STATE_LOC_BUYER
        , COUNTRY_LOC_SELLER
        , STATE_LOC_SELLER
        , VAT_SVC_SUPPLY_FLG
        , VAT_SERVICE_TYPE
        , COUNTRY_VAT_PERFRM
        , STATE_VAT_PERFRM
        , COUNTRY_VAT_SUPPLY
        , STATE_VAT_SUPPLY
        , STATE_VAT_DEFAULT
        , STATE_SHIP_FROM
        , STATE_SHIP_TO
        , VAT_EXCPTN_TYPE
        , VAT_EXCPTN_CERTIF
        , COUNTRY_SHIP_TO
        , COUNTRY_SHIP_FROM
        , COUNTRY_VAT_SHIPTO
        , COUNTRY_VAT_BILLTO
        , COUNTRY_VAT_BILLFR
        , VAT_RGSTRN_SELLER
        , VAT_TXN_TYPE_CD
        , VAT_APPLICABILITY
        , TAX_CD_VAT
        , VAT_USE_ID
        , IST_TXN_FLG
        , VAT_CALC_TYPE
        , BUSINESS_UNIT_RTV
        , RTV_ID
        , RTV_LN_NBR
        , RTV_VERIFIED
        , SHIP_DATE
        , UNIT_PRC_TOL_L
        , PCT_UNIT_PRC_TOL_L
        , EXT_PRC_TOL_L
        , PCT_EXT_PRC_TOL_L
        , UNIT_PRC_TOL_BSE_L
        , EXT_PRC_TOL_BSE_L
        , RJCT_OVER_TOL_FLAG
        , REJECT_DAYS
        , TAX_VAT_FLG
        , TAX_FRGHT_FLG
        , TAX_MISC_FLG
        , TRFT_RULE_CD
        , QTY_RFQ
        , SHIP_ID_EST
        , X_VENDOR_SETID
        , X_VENDOR_ID
        , X_VNDR_LOC
        , FRT_CHRG_METHOD
        , FRT_CHRG_OVERRIDE
        , VAT_ROUND_RULE
        , REVISION
        , PUBLISHED_SHIPTO
        , BCKORD_ORG_SCHED
        , BUSINESS_UNIT_SS
        , AUC_ID
        , AUC_LINE_NBR
        , AUC_SCHED_NBR
        , USER_SCHED_CHAR1
        , CUSTOM_C100_C1
        , CUSTOM_C100_C2
        , CUSTOM_C100_C3
        , CUSTOM_DATE_C1
        , CUSTOM_DATE_C2
        , CUSTOM_C1_C
        , VAT_RVRSE_CHG_GDS
        , PRICE_INITIAL
        , _FIVETRAN_ID
        , _FIVETRAN_DELETED
        , _FIVETRAN_SYNCED
        , PSA_DELETE_IND
        , PSA_LOAD_DTS
        , PSA_RECORD_SOURCE
        , LOAD_DTS
        , REC_SRC
        , BKCC
        , HASHDIFF
FROM JOIN_RESULT
{% if is_incremental() %}
WHERE NOT EXISTS (
    SELECT 1 
    FROM {{ this }} existing
    WHERE existing.PO_ITEM_HK = JOIN_RESULT.PO_ITEM_HK 
   AND existing.SCHED_NBR = JOIN_RESULT.SCHED_NBR
    AND existing.HASHDIFF = JOIN_RESULT.HASHDIFF
)
{% endif %}
{% if not is_incremental() %}

/* The following qualifier is implemented to prevent multiple loads of touched records during the initial build, such as multiple rows per HK and hashdiff. */
qualify 1 = row_number() over (partition by PO_ITEM_HK, SCHED_NBR, HASHDIFF order by PSA_LOAD_DTS)

union all
SELECT 
MD5_BINARY(GR.VALUE) AS PO_ITEM_HK,
GR.VALUE::text AS BUSINESS_UNIT,
GR.VALUE::text AS PO_ID,
GR.VALUE::number AS LINE_NBR,
GR.VALUE::number AS SCHED_NBR,
NULL AS CANCEL_STATUS,
NULL AS BAL_STATUS,
NULL AS CHANGE_STATUS,
NULL AS CHNG_ORD_SEQ,
NULL AS PRICE_PO,
NULL AS PRICE_PO_BSE,
NULL AS CUSTOM_PRICE,
NULL AS ZERO_PRICE_IND,
NULL AS DUE_DT,
NULL AS DUE_TIME,
NULL AS SHIPTO_SETID,
NULL AS SHIPTO_ID,
NULL AS ORIG_PROM_DT,
NULL AS QTY_PO,
NULL AS CURRENCY_CD,
NULL AS MERCHANDISE_AMT,
NULL AS CURRENCY_CD_BASE,
NULL AS MERCH_AMT_BSE,
NULL AS CONVERSION_RATE,
NULL AS FREIGHT_TERMS,
NULL AS SHIP_TYPE_ID,
NULL AS DISTRIB_MTHD_FLG,
NULL AS LIQUIDATE_METHOD,
NULL AS UNIT_PRC_TOL,
NULL AS UNIT_PRC_TOL_BSE,
NULL AS PCT_UNIT_PRC_TOL,
NULL AS EXT_PRC_TOL,
NULL AS EXT_PRC_TOL_BSE,
NULL AS PCT_EXT_PRC_TOL,
NULL AS QTY_RECV_TOL_PCT,
NULL AS PCT_UNDER_QTY,
NULL AS MATCH_STATUS_LN_PO,
NULL AS MATCH_LINE_OPT,
NULL AS BUSINESS_UNIT_OM,
NULL AS ORDER_NO,
NULL AS ORDER_INT_LINE_NO,
NULL AS SCHED_LINE_NBR,
NULL AS SHIP_TO_CUST_ID,
NULL AS BUSINESS_UNIT_IN,
NULL AS PRODUCTION_ID,
NULL AS OP_SEQUENCE,
NULL AS FROZEN_FLG,
NULL AS PLAN_CHANGE_FLG,
NULL AS NET_CHANGE_EP,
NULL AS WORK_ORDER_ID,
NULL AS CARRIER_ID,
NULL AS SUT_BASE_ID,
NULL AS TAX_CD_SUT,
NULL AS ULTIMATE_USE_CD,
NULL AS SUT_EXCPTN_TYPE,
NULL AS SUT_EXCPTN_CERTIF,
NULL AS SUT_APPLICABILITY,
NULL AS VAT_RCRD_INPT_FLG,
NULL AS VAT_RCRD_OUTPT_FLG,
NULL AS VAT_DCLRTN_POINT,
NULL AS VAT_CALC_GROSS_NET,
NULL AS VAT_CALC_FRGHT_FLG,
NULL AS VAT_CALC_MISC_FLG,
NULL AS VAT_RECALC_FLG,
NULL AS VAT_TREATMENT_GRP,
NULL AS VAT_TREATMENT,
NULL AS COUNTRY_LOC_BUYER,
NULL AS STATE_LOC_BUYER,
NULL AS COUNTRY_LOC_SELLER,
NULL AS STATE_LOC_SELLER,
NULL AS VAT_SVC_SUPPLY_FLG,
NULL AS VAT_SERVICE_TYPE,
NULL AS COUNTRY_VAT_PERFRM,
NULL AS STATE_VAT_PERFRM,
NULL AS COUNTRY_VAT_SUPPLY,
NULL AS STATE_VAT_SUPPLY,
NULL AS STATE_VAT_DEFAULT,
NULL AS STATE_SHIP_FROM,
NULL AS STATE_SHIP_TO,
NULL AS VAT_EXCPTN_TYPE,
NULL AS VAT_EXCPTN_CERTIF,
NULL AS COUNTRY_SHIP_TO,
NULL AS COUNTRY_SHIP_FROM,
NULL AS COUNTRY_VAT_SHIPTO,
NULL AS COUNTRY_VAT_BILLTO,
NULL AS COUNTRY_VAT_BILLFR,
NULL AS VAT_RGSTRN_SELLER,
NULL AS VAT_TXN_TYPE_CD,
NULL AS VAT_APPLICABILITY,
NULL AS TAX_CD_VAT,
NULL AS VAT_USE_ID,
NULL AS IST_TXN_FLG,
NULL AS VAT_CALC_TYPE,
NULL AS BUSINESS_UNIT_RTV,
NULL AS RTV_ID,
NULL AS RTV_LN_NBR,
NULL AS RTV_VERIFIED,
NULL AS SHIP_DATE,
NULL AS UNIT_PRC_TOL_L,
NULL AS PCT_UNIT_PRC_TOL_L,
NULL AS EXT_PRC_TOL_L,
NULL AS PCT_EXT_PRC_TOL_L,
NULL AS UNIT_PRC_TOL_BSE_L,
NULL AS EXT_PRC_TOL_BSE_L,
NULL AS RJCT_OVER_TOL_FLAG,
NULL AS REJECT_DAYS,
NULL AS TAX_VAT_FLG,
NULL AS TAX_FRGHT_FLG,
NULL AS TAX_MISC_FLG,
NULL AS TRFT_RULE_CD,
NULL AS QTY_RFQ,
NULL AS SHIP_ID_EST,
NULL AS X_VENDOR_SETID,
NULL AS X_VENDOR_ID,
NULL AS X_VNDR_LOC,
NULL AS FRT_CHRG_METHOD,
NULL AS FRT_CHRG_OVERRIDE,
NULL AS VAT_ROUND_RULE,
NULL AS REVISION,
NULL AS PUBLISHED_SHIPTO,
NULL AS BCKORD_ORG_SCHED,
NULL AS BUSINESS_UNIT_SS,
NULL AS AUC_ID,
NULL AS AUC_LINE_NBR,
NULL AS AUC_SCHED_NBR,
NULL AS USER_SCHED_CHAR1,
NULL AS CUSTOM_C100_C1,
NULL AS CUSTOM_C100_C2,
NULL AS CUSTOM_C100_C3,
NULL AS CUSTOM_DATE_C1,
NULL AS CUSTOM_DATE_C2,
NULL AS CUSTOM_C1_C,
NULL AS VAT_RVRSE_CHG_GDS,
NULL AS PRICE_INITIAL,
NULL AS _FIVETRAN_ID,
NULL AS _FIVETRAN_DELETED,
NULL AS _FIVETRAN_SYNCED,
'N' AS PSA_DELETE_IND,
'1900-01-01'::TIMESTAMP AS PSA_LOAD_DTS,
NULL AS PSA_RECORD_SOURCE,
CONVERT_TIMEZONE('UTC','1900-01-01'::TIMESTAMP) AS LOAD_DTS,
'USAZET.SNOWFLAKE.FBIN.DERIVED' AS REC_SRC,
DECODE(GR.VALUE, 0, 'GHOST RECORD-SYSTEM', -1, 'GHOST RECORD-nullkey-required', -2, 'GHOST RECORD-nullkey-optional') AS BKCC,
''::BINARY AS HASHDIFF
FROM
TABLE(strtok_split_to_table('0|-1|-2', '|')) AS GR
{% endif %}
