---- SRC LAYER ----
WITH
SRC_SEMTK          as ( SELECT * FROM {{ ref('v_psa_stg_plant_item__emtk_ebs') }} as SRC 
                         {% if is_incremental() %}
                         WHERE SRC.LOAD_DTS > (SELECT DATEADD('HOUR', '-1', MAX(LOAD_DTS)) FROM {{this}})
                         {% endif %}  )

/*
SRC_SEMTK          as ( SELECT * FROM STAGING.v_psa_stg_plant_item__emtk_ebs )
*/
---- LOGIC LAYER ----

, LOGIC_SEMTK as (
    SELECT
        ITEM_HK
      , SEGMENT1
      , INVENTORY_ITEM_ID
      , ORGANIZATION_ID
      , LAST_UPDATE_DATE
      , LAST_UPDATED_BY
      , CREATION_DATE
      , CREATED_BY
      , LAST_UPDATE_LOGIN
      , SUMMARY_FLAG
      , ENABLED_FLAG
      , START_DATE_ACTIVE
      , END_DATE_ACTIVE
      , DESCRIPTION
      , BUYER_ID
      , ACCOUNTING_RULE_ID
      , INVOICING_RULE_ID
      , SEGMENT2
      , SEGMENT3
      , SEGMENT4
      , SEGMENT5
      , SEGMENT6
      , SEGMENT7
      , SEGMENT8
      , SEGMENT9
      , SEGMENT10
      , SEGMENT11
      , SEGMENT12
      , SEGMENT13
      , SEGMENT14
      , SEGMENT15
      , SEGMENT16
      , SEGMENT17
      , SEGMENT18
      , SEGMENT19
      , SEGMENT20
      , ATTRIBUTE_CATEGORY
      , ATTRIBUTE1
      , ATTRIBUTE2
      , ATTRIBUTE3
      , ATTRIBUTE4
      , ATTRIBUTE5
      , ATTRIBUTE6
      , ATTRIBUTE7
      , ATTRIBUTE8
      , ATTRIBUTE9
      , ATTRIBUTE10
      , ATTRIBUTE11
      , ATTRIBUTE12
      , ATTRIBUTE13
      , ATTRIBUTE14
      , ATTRIBUTE15
      , PURCHASING_ITEM_FLAG
      , SHIPPABLE_ITEM_FLAG
      , CUSTOMER_ORDER_FLAG
      , INTERNAL_ORDER_FLAG
      , SERVICE_ITEM_FLAG
      , INVENTORY_ITEM_FLAG
      , ENG_ITEM_FLAG
      , INVENTORY_ASSET_FLAG
      , PURCHASING_ENABLED_FLAG
      , CUSTOMER_ORDER_ENABLED_FLAG
      , INTERNAL_ORDER_ENABLED_FLAG
      , SO_TRANSACTIONS_FLAG
      , MTL_TRANSACTIONS_ENABLED_FLAG
      , STOCK_ENABLED_FLAG
      , BOM_ENABLED_FLAG
      , BUILD_IN_WIP_FLAG
      , REVISION_QTY_CONTROL_CODE
      , ITEM_CATALOG_GROUP_ID
      , CATALOG_STATUS_FLAG
      , RETURNABLE_FLAG
      , DEFAULT_SHIPPING_ORG
      , COLLATERAL_FLAG
      , TAXABLE_FLAG
      , QTY_RCV_EXCEPTION_CODE
      , ALLOW_ITEM_DESC_UPDATE_FLAG
      , INSPECTION_REQUIRED_FLAG
      , RECEIPT_REQUIRED_FLAG
      , MARKET_PRICE
      , HAZARD_CLASS_ID
      , RFQ_REQUIRED_FLAG
      , QTY_RCV_TOLERANCE
      , LIST_PRICE_PER_UNIT
      , UN_NUMBER_ID
      , PRICE_TOLERANCE_PERCENT
      , ASSET_CATEGORY_ID
      , ROUNDING_FACTOR
      , UNIT_OF_ISSUE
      , ENFORCE_SHIP_TO_LOCATION_CODE
      , ALLOW_SUBSTITUTE_RECEIPTS_FLAG
      , ALLOW_UNORDERED_RECEIPTS_FLAG
      , ALLOW_EXPRESS_DELIVERY_FLAG
      , DAYS_EARLY_RECEIPT_ALLOWED
      , DAYS_LATE_RECEIPT_ALLOWED
      , RECEIPT_DAYS_EXCEPTION_CODE
      , RECEIVING_ROUTING_ID
      , INVOICE_CLOSE_TOLERANCE
      , RECEIVE_CLOSE_TOLERANCE
      , AUTO_LOT_ALPHA_PREFIX
      , START_AUTO_LOT_NUMBER
      , LOT_CONTROL_CODE
      , SHELF_LIFE_CODE
      , SHELF_LIFE_DAYS
      , SERIAL_NUMBER_CONTROL_CODE
      , START_AUTO_SERIAL_NUMBER
      , AUTO_SERIAL_ALPHA_PREFIX
      , SOURCE_TYPE
      , SOURCE_ORGANIZATION_ID
      , SOURCE_SUBINVENTORY
      , EXPENSE_ACCOUNT
      , ENCUMBRANCE_ACCOUNT
      , RESTRICT_SUBINVENTORIES_CODE
      , UNIT_WEIGHT
      , WEIGHT_UOM_CODE
      , VOLUME_UOM_CODE
      , UNIT_VOLUME
      , RESTRICT_LOCATORS_CODE
      , LOCATION_CONTROL_CODE
      , SHRINKAGE_RATE
      , ACCEPTABLE_EARLY_DAYS
      , PLANNING_TIME_FENCE_CODE
      , DEMAND_TIME_FENCE_CODE
      , LEAD_TIME_LOT_SIZE
      , STD_LOT_SIZE
      , CUM_MANUFACTURING_LEAD_TIME
      , OVERRUN_PERCENTAGE
      , MRP_CALCULATE_ATP_FLAG
      , ACCEPTABLE_RATE_INCREASE
      , ACCEPTABLE_RATE_DECREASE
      , CUMULATIVE_TOTAL_LEAD_TIME
      , PLANNING_TIME_FENCE_DAYS
      , DEMAND_TIME_FENCE_DAYS
      , END_ASSEMBLY_PEGGING_FLAG
      , REPETITIVE_PLANNING_FLAG
      , PLANNING_EXCEPTION_SET
      , BOM_ITEM_TYPE
      , PICK_COMPONENTS_FLAG
      , REPLENISH_TO_ORDER_FLAG
      , BASE_ITEM_ID
      , ATP_COMPONENTS_FLAG
      , ATP_FLAG
      , FIXED_LEAD_TIME
      , VARIABLE_LEAD_TIME
      , WIP_SUPPLY_LOCATOR_ID
      , WIP_SUPPLY_TYPE
      , WIP_SUPPLY_SUBINVENTORY
      , PRIMARY_UOM_CODE
      , PRIMARY_UNIT_OF_MEASURE
      , ALLOWED_UNITS_LOOKUP_CODE
      , COST_OF_SALES_ACCOUNT
      , SALES_ACCOUNT
      , DEFAULT_INCLUDE_IN_ROLLUP_FLAG
      , INVENTORY_ITEM_STATUS_CODE
      , INVENTORY_PLANNING_CODE
      , PLANNER_CODE
      , PLANNING_MAKE_BUY_CODE
      , FIXED_LOT_MULTIPLIER
      , ROUNDING_CONTROL_TYPE
      , CARRYING_COST
      , POSTPROCESSING_LEAD_TIME
      , PREPROCESSING_LEAD_TIME
      , FULL_LEAD_TIME
      , ORDER_COST
      , MRP_SAFETY_STOCK_PERCENT
      , MRP_SAFETY_STOCK_CODE
      , MIN_MINMAX_QUANTITY
      , MAX_MINMAX_QUANTITY
      , MINIMUM_ORDER_QUANTITY
      , FIXED_ORDER_QUANTITY
      , FIXED_DAYS_SUPPLY
      , MAXIMUM_ORDER_QUANTITY
      , ATP_RULE_ID
      , PICKING_RULE_ID
      , RESERVABLE_TYPE
      , POSITIVE_MEASUREMENT_ERROR
      , NEGATIVE_MEASUREMENT_ERROR
      , ENGINEERING_ECN_CODE
      , ENGINEERING_ITEM_ID
      , ENGINEERING_DATE
      , SERVICE_STARTING_DELAY
      , VENDOR_WARRANTY_FLAG
      , SERVICEABLE_COMPONENT_FLAG
      , SERVICEABLE_PRODUCT_FLAG
      , BASE_WARRANTY_SERVICE_ID
      , PAYMENT_TERMS_ID
      , PREVENTIVE_MAINTENANCE_FLAG
      , PRIMARY_SPECIALIST_ID
      , SECONDARY_SPECIALIST_ID
      , SERVICEABLE_ITEM_CLASS_ID
      , TIME_BILLABLE_FLAG
      , MATERIAL_BILLABLE_FLAG
      , EXPENSE_BILLABLE_FLAG
      , PRORATE_SERVICE_FLAG
      , COVERAGE_SCHEDULE_ID
      , SERVICE_DURATION_PERIOD_CODE
      , SERVICE_DURATION
      , WARRANTY_VENDOR_ID
      , MAX_WARRANTY_AMOUNT
      , RESPONSE_TIME_PERIOD_CODE
      , RESPONSE_TIME_VALUE
      , NEW_REVISION_CODE
      , INVOICEABLE_ITEM_FLAG
      , TAX_CODE
      , INVOICE_ENABLED_FLAG
      , MUST_USE_APPROVED_VENDOR_FLAG
      , REQUEST_ID
      , PROGRAM_APPLICATION_ID
      , PROGRAM_ID
      , PROGRAM_UPDATE_DATE
      , OUTSIDE_OPERATION_FLAG
      , OUTSIDE_OPERATION_UOM_TYPE
      , SAFETY_STOCK_BUCKET_DAYS
      , AUTO_REDUCE_MPS
      , COSTING_ENABLED_FLAG
      , AUTO_CREATED_CONFIG_FLAG
      , CYCLE_COUNT_ENABLED_FLAG
      , ITEM_TYPE
      , MODEL_CONFIG_CLAUSE_NAME
      , SHIP_MODEL_COMPLETE_FLAG
      , MRP_PLANNING_CODE
      , RETURN_INSPECTION_REQUIREMENT
      , ATO_FORECAST_CONTROL
      , RELEASE_TIME_FENCE_CODE
      , RELEASE_TIME_FENCE_DAYS
      , CONTAINER_ITEM_FLAG
      , VEHICLE_ITEM_FLAG
      , MAXIMUM_LOAD_WEIGHT
      , MINIMUM_FILL_PERCENT
      , CONTAINER_TYPE_CODE
      , INTERNAL_VOLUME
      , WH_UPDATE_DATE
      , PRODUCT_FAMILY_ITEM_ID
      , GLOBAL_ATTRIBUTE_CATEGORY
      , GLOBAL_ATTRIBUTE1
      , GLOBAL_ATTRIBUTE2
      , GLOBAL_ATTRIBUTE3
      , GLOBAL_ATTRIBUTE4
      , GLOBAL_ATTRIBUTE5
      , GLOBAL_ATTRIBUTE6
      , GLOBAL_ATTRIBUTE7
      , GLOBAL_ATTRIBUTE8
      , GLOBAL_ATTRIBUTE9
      , GLOBAL_ATTRIBUTE10
      , PURCHASING_TAX_CODE
      , OVERCOMPLETION_TOLERANCE_TYPE
      , OVERCOMPLETION_TOLERANCE_VALUE
      , EFFECTIVITY_CONTROL
      , CHECK_SHORTAGES_FLAG
      , OVER_SHIPMENT_TOLERANCE
      , UNDER_SHIPMENT_TOLERANCE
      , OVER_RETURN_TOLERANCE
      , UNDER_RETURN_TOLERANCE
      , EQUIPMENT_TYPE
      , RECOVERED_PART_DISP_CODE
      , DEFECT_TRACKING_ON_FLAG
      , USAGE_ITEM_FLAG
      , EVENT_FLAG
      , ELECTRONIC_FLAG
      , DOWNLOADABLE_FLAG
      , VOL_DISCOUNT_EXEMPT_FLAG
      , COUPON_EXEMPT_FLAG
      , COMMS_NL_TRACKABLE_FLAG
      , ASSET_CREATION_CODE
      , COMMS_ACTIVATION_REQD_FLAG
      , ORDERABLE_ON_WEB_FLAG
      , BACK_ORDERABLE_FLAG
      , WEB_STATUS
      , INDIVISIBLE_FLAG
      , DIMENSION_UOM_CODE
      , UNIT_LENGTH
      , UNIT_WIDTH
      , UNIT_HEIGHT
      , BULK_PICKED_FLAG
      , LOT_STATUS_ENABLED
      , DEFAULT_LOT_STATUS_ID
      , SERIAL_STATUS_ENABLED
      , DEFAULT_SERIAL_STATUS_ID
      , LOT_SPLIT_ENABLED
      , LOT_MERGE_ENABLED
      , INVENTORY_CARRY_PENALTY
      , OPERATION_SLACK_PENALTY
      , FINANCING_ALLOWED_FLAG
      , EAM_ITEM_TYPE
      , EAM_ACTIVITY_TYPE_CODE
      , EAM_ACTIVITY_CAUSE_CODE
      , EAM_ACT_NOTIFICATION_FLAG
      , EAM_ACT_SHUTDOWN_STATUS
      , DUAL_UOM_CONTROL
      , SECONDARY_UOM_CODE
      , DUAL_UOM_DEVIATION_HIGH
      , DUAL_UOM_DEVIATION_LOW
      , CONTRACT_ITEM_TYPE_CODE
      , SUBSCRIPTION_DEPEND_FLAG
      , SERV_REQ_ENABLED_CODE
      , SERV_BILLING_ENABLED_FLAG
      , SERV_IMPORTANCE_LEVEL
      , PLANNED_INV_POINT_FLAG
      , LOT_TRANSLATE_ENABLED
      , DEFAULT_SO_SOURCE_TYPE
      , CREATE_SUPPLY_FLAG
      , SUBSTITUTION_WINDOW_CODE
      , SUBSTITUTION_WINDOW_DAYS
      , IB_ITEM_INSTANCE_CLASS
      , CONFIG_MODEL_TYPE
      , LOT_SUBSTITUTION_ENABLED
      , MINIMUM_LICENSE_QUANTITY
      , EAM_ACTIVITY_SOURCE_CODE
      , LIFECYCLE_ID
      , CURRENT_PHASE_ID
      , OBJECT_VERSION_NUMBER
      , TRACKING_QUANTITY_IND
      , ONT_PRICING_QTY_SOURCE
      , SECONDARY_DEFAULT_IND
      , OPTION_SPECIFIC_SOURCED
      , APPROVAL_STATUS
      , VMI_MINIMUM_UNITS
      , VMI_MINIMUM_DAYS
      , VMI_MAXIMUM_UNITS
      , VMI_MAXIMUM_DAYS
      , VMI_FIXED_ORDER_QUANTITY
      , SO_AUTHORIZATION_FLAG
      , CONSIGNED_FLAG
      , ASN_AUTOEXPIRE_FLAG
      , VMI_FORECAST_TYPE
      , FORECAST_HORIZON
      , EXCLUDE_FROM_BUDGET_FLAG
      , DAYS_TGT_INV_SUPPLY
      , DAYS_TGT_INV_WINDOW
      , DAYS_MAX_INV_SUPPLY
      , DAYS_MAX_INV_WINDOW
      , DRP_PLANNED_FLAG
      , CRITICAL_COMPONENT_FLAG
      , CONTINOUS_TRANSFER
      , CONVERGENCE
      , DIVERGENCE
      , CONFIG_ORGS
      , CONFIG_MATCH
      , GLOBAL_ATTRIBUTE11
      , GLOBAL_ATTRIBUTE12
      , GLOBAL_ATTRIBUTE13
      , GLOBAL_ATTRIBUTE14
      , GLOBAL_ATTRIBUTE15
      , GLOBAL_ATTRIBUTE16
      , GLOBAL_ATTRIBUTE17
      , GLOBAL_ATTRIBUTE18
      , GLOBAL_ATTRIBUTE19
      , GLOBAL_ATTRIBUTE20
      , ATTRIBUTE16
      , ATTRIBUTE17
      , ATTRIBUTE18
      , ATTRIBUTE19
      , ATTRIBUTE20
      , ATTRIBUTE21
      , ATTRIBUTE22
      , ATTRIBUTE23
      , ATTRIBUTE24
      , ATTRIBUTE25
      , ATTRIBUTE26
      , ATTRIBUTE27
      , ATTRIBUTE28
      , ATTRIBUTE29
      , ATTRIBUTE30
      , CAS_NUMBER
      , CHILD_LOT_FLAG
      , CHILD_LOT_PREFIX
      , CHILD_LOT_STARTING_NUMBER
      , CHILD_LOT_VALIDATION_FLAG
      , COPY_LOT_ATTRIBUTE_FLAG
      , DEFAULT_GRADE
      , EXPIRATION_ACTION_CODE
      , EXPIRATION_ACTION_INTERVAL
      , GRADE_CONTROL_FLAG
      , HAZARDOUS_MATERIAL_FLAG
      , HOLD_DAYS
      , LOT_DIVISIBLE_FLAG
      , MATURITY_DAYS
      , PARENT_CHILD_GENERATION_FLAG
      , PROCESS_COSTING_ENABLED_FLAG
      , PROCESS_EXECUTION_ENABLED_FLAG
      , PROCESS_QUALITY_ENABLED_FLAG
      , PROCESS_SUPPLY_LOCATOR_ID
      , PROCESS_SUPPLY_SUBINVENTORY
      , PROCESS_YIELD_LOCATOR_ID
      , PROCESS_YIELD_SUBINVENTORY
      , RECIPE_ENABLED_FLAG
      , RETEST_INTERVAL
      , CHARGE_PERIODICITY_CODE
      , REPAIR_LEADTIME
      , REPAIR_YIELD
      , PREPOSITION_POINT
      , REPAIR_PROGRAM
      , SUBCONTRACTING_COMPONENT
      , OUTSOURCED_ASSEMBLY
      , EGO_MASTER_ITEMS_DFF_CTX
      , GDSN_OUTBOUND_ENABLED_FLAG
      , TRADE_ITEM_DESCRIPTOR
      , STYLE_ITEM_ID
      , STYLE_ITEM_FLAG
      , LAST_SUBMITTED_NIR_ID
      , DEFAULT_MATERIAL_STATUS_ID
      , SERIAL_TAGGING_FLAG
      , IB_ITEM_TRACKING_LEVEL
      , MCC_CLASSIFICATION_TYPE
      , MCC_CONTROL_CODE
      , MCC_TRACKING_CODE
      , GLOBAL_ATTRIBUTE21
      , GLOBAL_ATTRIBUTE22
      , GLOBAL_ATTRIBUTE23
      , GLOBAL_ATTRIBUTE24
      , GLOBAL_ATTRIBUTE25
      , GLOBAL_ATTRIBUTE26
      , GLOBAL_ATTRIBUTE27
      , GLOBAL_ATTRIBUTE28
      , GLOBAL_ATTRIBUTE29
      , GLOBAL_ATTRIBUTE30
      , GLOBAL_ATTRIBUTE31
      , GLOBAL_ATTRIBUTE32
      , GLOBAL_ATTRIBUTE33
      , GLOBAL_ATTRIBUTE34
      , GLOBAL_ATTRIBUTE35
      , GLOBAL_ATTRIBUTE36
      , GLOBAL_ATTRIBUTE37
      , GLOBAL_ATTRIBUTE38
      , GLOBAL_ATTRIBUTE39
      , GLOBAL_ATTRIBUTE40
      , _FIVETRAN_DELETED
      , _FIVETRAN_ID
      , _FIVETRAN_SYNCED
      , PSA_DELETE_IND
      , PSA_LOAD_DTS
      , PSA_RECORD_SOURCE
      , LOAD_DTS
      , REC_SRC
      , BKCC
      , HASHDIFF
    FROM SRC_SEMTK
)
---- RENAME LAYER ----

, RENAME_SEMTK as (
    SELECT
        ITEM_HK
      , SEGMENT1
      , INVENTORY_ITEM_ID
      , ORGANIZATION_ID
      , LAST_UPDATE_DATE
      , LAST_UPDATED_BY
      , CREATION_DATE
      , CREATED_BY
      , LAST_UPDATE_LOGIN
      , SUMMARY_FLAG
      , ENABLED_FLAG
      , START_DATE_ACTIVE
      , END_DATE_ACTIVE
      , DESCRIPTION
      , BUYER_ID
      , ACCOUNTING_RULE_ID
      , INVOICING_RULE_ID
      , SEGMENT2
      , SEGMENT3
      , SEGMENT4
      , SEGMENT5
      , SEGMENT6
      , SEGMENT7
      , SEGMENT8
      , SEGMENT9
      , SEGMENT10
      , SEGMENT11
      , SEGMENT12
      , SEGMENT13
      , SEGMENT14
      , SEGMENT15
      , SEGMENT16
      , SEGMENT17
      , SEGMENT18
      , SEGMENT19
      , SEGMENT20
      , ATTRIBUTE_CATEGORY
      , ATTRIBUTE1
      , ATTRIBUTE2
      , ATTRIBUTE3
      , ATTRIBUTE4
      , ATTRIBUTE5
      , ATTRIBUTE6
      , ATTRIBUTE7
      , ATTRIBUTE8
      , ATTRIBUTE9
      , ATTRIBUTE10
      , ATTRIBUTE11
      , ATTRIBUTE12
      , ATTRIBUTE13
      , ATTRIBUTE14
      , ATTRIBUTE15
      , PURCHASING_ITEM_FLAG
      , SHIPPABLE_ITEM_FLAG
      , CUSTOMER_ORDER_FLAG
      , INTERNAL_ORDER_FLAG
      , SERVICE_ITEM_FLAG
      , INVENTORY_ITEM_FLAG
      , ENG_ITEM_FLAG
      , INVENTORY_ASSET_FLAG
      , PURCHASING_ENABLED_FLAG
      , CUSTOMER_ORDER_ENABLED_FLAG
      , INTERNAL_ORDER_ENABLED_FLAG
      , SO_TRANSACTIONS_FLAG
      , MTL_TRANSACTIONS_ENABLED_FLAG
      , STOCK_ENABLED_FLAG
      , BOM_ENABLED_FLAG
      , BUILD_IN_WIP_FLAG
      , REVISION_QTY_CONTROL_CODE
      , ITEM_CATALOG_GROUP_ID
      , CATALOG_STATUS_FLAG
      , RETURNABLE_FLAG
      , DEFAULT_SHIPPING_ORG
      , COLLATERAL_FLAG
      , TAXABLE_FLAG
      , QTY_RCV_EXCEPTION_CODE
      , ALLOW_ITEM_DESC_UPDATE_FLAG
      , INSPECTION_REQUIRED_FLAG
      , RECEIPT_REQUIRED_FLAG
      , MARKET_PRICE
      , HAZARD_CLASS_ID
      , RFQ_REQUIRED_FLAG
      , QTY_RCV_TOLERANCE
      , LIST_PRICE_PER_UNIT
      , UN_NUMBER_ID
      , PRICE_TOLERANCE_PERCENT
      , ASSET_CATEGORY_ID
      , ROUNDING_FACTOR
      , UNIT_OF_ISSUE
      , ENFORCE_SHIP_TO_LOCATION_CODE
      , ALLOW_SUBSTITUTE_RECEIPTS_FLAG
      , ALLOW_UNORDERED_RECEIPTS_FLAG
      , ALLOW_EXPRESS_DELIVERY_FLAG
      , DAYS_EARLY_RECEIPT_ALLOWED
      , DAYS_LATE_RECEIPT_ALLOWED
      , RECEIPT_DAYS_EXCEPTION_CODE
      , RECEIVING_ROUTING_ID
      , INVOICE_CLOSE_TOLERANCE
      , RECEIVE_CLOSE_TOLERANCE
      , AUTO_LOT_ALPHA_PREFIX
      , START_AUTO_LOT_NUMBER
      , LOT_CONTROL_CODE
      , SHELF_LIFE_CODE
      , SHELF_LIFE_DAYS
      , SERIAL_NUMBER_CONTROL_CODE
      , START_AUTO_SERIAL_NUMBER
      , AUTO_SERIAL_ALPHA_PREFIX
      , SOURCE_TYPE
      , SOURCE_ORGANIZATION_ID
      , SOURCE_SUBINVENTORY
      , EXPENSE_ACCOUNT
      , ENCUMBRANCE_ACCOUNT
      , RESTRICT_SUBINVENTORIES_CODE
      , UNIT_WEIGHT
      , WEIGHT_UOM_CODE
      , VOLUME_UOM_CODE
      , UNIT_VOLUME
      , RESTRICT_LOCATORS_CODE
      , LOCATION_CONTROL_CODE
      , SHRINKAGE_RATE
      , ACCEPTABLE_EARLY_DAYS
      , PLANNING_TIME_FENCE_CODE
      , DEMAND_TIME_FENCE_CODE
      , LEAD_TIME_LOT_SIZE
      , STD_LOT_SIZE
      , CUM_MANUFACTURING_LEAD_TIME
      , OVERRUN_PERCENTAGE
      , MRP_CALCULATE_ATP_FLAG
      , ACCEPTABLE_RATE_INCREASE
      , ACCEPTABLE_RATE_DECREASE
      , CUMULATIVE_TOTAL_LEAD_TIME
      , PLANNING_TIME_FENCE_DAYS
      , DEMAND_TIME_FENCE_DAYS
      , END_ASSEMBLY_PEGGING_FLAG
      , REPETITIVE_PLANNING_FLAG
      , PLANNING_EXCEPTION_SET
      , BOM_ITEM_TYPE
      , PICK_COMPONENTS_FLAG
      , REPLENISH_TO_ORDER_FLAG
      , BASE_ITEM_ID
      , ATP_COMPONENTS_FLAG
      , ATP_FLAG
      , FIXED_LEAD_TIME
      , VARIABLE_LEAD_TIME
      , WIP_SUPPLY_LOCATOR_ID
      , WIP_SUPPLY_TYPE
      , WIP_SUPPLY_SUBINVENTORY
      , PRIMARY_UOM_CODE
      , PRIMARY_UNIT_OF_MEASURE
      , ALLOWED_UNITS_LOOKUP_CODE
      , COST_OF_SALES_ACCOUNT
      , SALES_ACCOUNT
      , DEFAULT_INCLUDE_IN_ROLLUP_FLAG
      , INVENTORY_ITEM_STATUS_CODE
      , INVENTORY_PLANNING_CODE
      , PLANNER_CODE
      , PLANNING_MAKE_BUY_CODE
      , FIXED_LOT_MULTIPLIER
      , ROUNDING_CONTROL_TYPE
      , CARRYING_COST
      , POSTPROCESSING_LEAD_TIME
      , PREPROCESSING_LEAD_TIME
      , FULL_LEAD_TIME
      , ORDER_COST
      , MRP_SAFETY_STOCK_PERCENT
      , MRP_SAFETY_STOCK_CODE
      , MIN_MINMAX_QUANTITY
      , MAX_MINMAX_QUANTITY
      , MINIMUM_ORDER_QUANTITY
      , FIXED_ORDER_QUANTITY
      , FIXED_DAYS_SUPPLY
      , MAXIMUM_ORDER_QUANTITY
      , ATP_RULE_ID
      , PICKING_RULE_ID
      , RESERVABLE_TYPE
      , POSITIVE_MEASUREMENT_ERROR
      , NEGATIVE_MEASUREMENT_ERROR
      , ENGINEERING_ECN_CODE
      , ENGINEERING_ITEM_ID
      , ENGINEERING_DATE
      , SERVICE_STARTING_DELAY
      , VENDOR_WARRANTY_FLAG
      , SERVICEABLE_COMPONENT_FLAG
      , SERVICEABLE_PRODUCT_FLAG
      , BASE_WARRANTY_SERVICE_ID
      , PAYMENT_TERMS_ID
      , PREVENTIVE_MAINTENANCE_FLAG
      , PRIMARY_SPECIALIST_ID
      , SECONDARY_SPECIALIST_ID
      , SERVICEABLE_ITEM_CLASS_ID
      , TIME_BILLABLE_FLAG
      , MATERIAL_BILLABLE_FLAG
      , EXPENSE_BILLABLE_FLAG
      , PRORATE_SERVICE_FLAG
      , COVERAGE_SCHEDULE_ID
      , SERVICE_DURATION_PERIOD_CODE
      , SERVICE_DURATION
      , WARRANTY_VENDOR_ID
      , MAX_WARRANTY_AMOUNT
      , RESPONSE_TIME_PERIOD_CODE
      , RESPONSE_TIME_VALUE
      , NEW_REVISION_CODE
      , INVOICEABLE_ITEM_FLAG
      , TAX_CODE
      , INVOICE_ENABLED_FLAG
      , MUST_USE_APPROVED_VENDOR_FLAG
      , REQUEST_ID
      , PROGRAM_APPLICATION_ID
      , PROGRAM_ID
      , PROGRAM_UPDATE_DATE
      , OUTSIDE_OPERATION_FLAG
      , OUTSIDE_OPERATION_UOM_TYPE
      , SAFETY_STOCK_BUCKET_DAYS
      , AUTO_REDUCE_MPS
      , COSTING_ENABLED_FLAG
      , AUTO_CREATED_CONFIG_FLAG
      , CYCLE_COUNT_ENABLED_FLAG
      , ITEM_TYPE
      , MODEL_CONFIG_CLAUSE_NAME
      , SHIP_MODEL_COMPLETE_FLAG
      , MRP_PLANNING_CODE
      , RETURN_INSPECTION_REQUIREMENT
      , ATO_FORECAST_CONTROL
      , RELEASE_TIME_FENCE_CODE
      , RELEASE_TIME_FENCE_DAYS
      , CONTAINER_ITEM_FLAG
      , VEHICLE_ITEM_FLAG
      , MAXIMUM_LOAD_WEIGHT
      , MINIMUM_FILL_PERCENT
      , CONTAINER_TYPE_CODE
      , INTERNAL_VOLUME
      , WH_UPDATE_DATE
      , PRODUCT_FAMILY_ITEM_ID
      , GLOBAL_ATTRIBUTE_CATEGORY
      , GLOBAL_ATTRIBUTE1
      , GLOBAL_ATTRIBUTE2
      , GLOBAL_ATTRIBUTE3
      , GLOBAL_ATTRIBUTE4
      , GLOBAL_ATTRIBUTE5
      , GLOBAL_ATTRIBUTE6
      , GLOBAL_ATTRIBUTE7
      , GLOBAL_ATTRIBUTE8
      , GLOBAL_ATTRIBUTE9
      , GLOBAL_ATTRIBUTE10
      , PURCHASING_TAX_CODE
      , OVERCOMPLETION_TOLERANCE_TYPE
      , OVERCOMPLETION_TOLERANCE_VALUE
      , EFFECTIVITY_CONTROL
      , CHECK_SHORTAGES_FLAG
      , OVER_SHIPMENT_TOLERANCE
      , UNDER_SHIPMENT_TOLERANCE
      , OVER_RETURN_TOLERANCE
      , UNDER_RETURN_TOLERANCE
      , EQUIPMENT_TYPE
      , RECOVERED_PART_DISP_CODE
      , DEFECT_TRACKING_ON_FLAG
      , USAGE_ITEM_FLAG
      , EVENT_FLAG
      , ELECTRONIC_FLAG
      , DOWNLOADABLE_FLAG
      , VOL_DISCOUNT_EXEMPT_FLAG
      , COUPON_EXEMPT_FLAG
      , COMMS_NL_TRACKABLE_FLAG
      , ASSET_CREATION_CODE
      , COMMS_ACTIVATION_REQD_FLAG
      , ORDERABLE_ON_WEB_FLAG
      , BACK_ORDERABLE_FLAG
      , WEB_STATUS
      , INDIVISIBLE_FLAG
      , DIMENSION_UOM_CODE
      , UNIT_LENGTH
      , UNIT_WIDTH
      , UNIT_HEIGHT
      , BULK_PICKED_FLAG
      , LOT_STATUS_ENABLED
      , DEFAULT_LOT_STATUS_ID
      , SERIAL_STATUS_ENABLED
      , DEFAULT_SERIAL_STATUS_ID
      , LOT_SPLIT_ENABLED
      , LOT_MERGE_ENABLED
      , INVENTORY_CARRY_PENALTY
      , OPERATION_SLACK_PENALTY
      , FINANCING_ALLOWED_FLAG
      , EAM_ITEM_TYPE
      , EAM_ACTIVITY_TYPE_CODE
      , EAM_ACTIVITY_CAUSE_CODE
      , EAM_ACT_NOTIFICATION_FLAG
      , EAM_ACT_SHUTDOWN_STATUS
      , DUAL_UOM_CONTROL
      , SECONDARY_UOM_CODE
      , DUAL_UOM_DEVIATION_HIGH
      , DUAL_UOM_DEVIATION_LOW
      , CONTRACT_ITEM_TYPE_CODE
      , SUBSCRIPTION_DEPEND_FLAG
      , SERV_REQ_ENABLED_CODE
      , SERV_BILLING_ENABLED_FLAG
      , SERV_IMPORTANCE_LEVEL
      , PLANNED_INV_POINT_FLAG
      , LOT_TRANSLATE_ENABLED
      , DEFAULT_SO_SOURCE_TYPE
      , CREATE_SUPPLY_FLAG
      , SUBSTITUTION_WINDOW_CODE
      , SUBSTITUTION_WINDOW_DAYS
      , IB_ITEM_INSTANCE_CLASS
      , CONFIG_MODEL_TYPE
      , LOT_SUBSTITUTION_ENABLED
      , MINIMUM_LICENSE_QUANTITY
      , EAM_ACTIVITY_SOURCE_CODE
      , LIFECYCLE_ID
      , CURRENT_PHASE_ID
      , OBJECT_VERSION_NUMBER
      , TRACKING_QUANTITY_IND
      , ONT_PRICING_QTY_SOURCE
      , SECONDARY_DEFAULT_IND
      , OPTION_SPECIFIC_SOURCED
      , APPROVAL_STATUS
      , VMI_MINIMUM_UNITS
      , VMI_MINIMUM_DAYS
      , VMI_MAXIMUM_UNITS
      , VMI_MAXIMUM_DAYS
      , VMI_FIXED_ORDER_QUANTITY
      , SO_AUTHORIZATION_FLAG
      , CONSIGNED_FLAG
      , ASN_AUTOEXPIRE_FLAG
      , VMI_FORECAST_TYPE
      , FORECAST_HORIZON
      , EXCLUDE_FROM_BUDGET_FLAG
      , DAYS_TGT_INV_SUPPLY
      , DAYS_TGT_INV_WINDOW
      , DAYS_MAX_INV_SUPPLY
      , DAYS_MAX_INV_WINDOW
      , DRP_PLANNED_FLAG
      , CRITICAL_COMPONENT_FLAG
      , CONTINOUS_TRANSFER
      , CONVERGENCE
      , DIVERGENCE
      , CONFIG_ORGS
      , CONFIG_MATCH
      , GLOBAL_ATTRIBUTE11
      , GLOBAL_ATTRIBUTE12
      , GLOBAL_ATTRIBUTE13
      , GLOBAL_ATTRIBUTE14
      , GLOBAL_ATTRIBUTE15
      , GLOBAL_ATTRIBUTE16
      , GLOBAL_ATTRIBUTE17
      , GLOBAL_ATTRIBUTE18
      , GLOBAL_ATTRIBUTE19
      , GLOBAL_ATTRIBUTE20
      , ATTRIBUTE16
      , ATTRIBUTE17
      , ATTRIBUTE18
      , ATTRIBUTE19
      , ATTRIBUTE20
      , ATTRIBUTE21
      , ATTRIBUTE22
      , ATTRIBUTE23
      , ATTRIBUTE24
      , ATTRIBUTE25
      , ATTRIBUTE26
      , ATTRIBUTE27
      , ATTRIBUTE28
      , ATTRIBUTE29
      , ATTRIBUTE30
      , CAS_NUMBER
      , CHILD_LOT_FLAG
      , CHILD_LOT_PREFIX
      , CHILD_LOT_STARTING_NUMBER
      , CHILD_LOT_VALIDATION_FLAG
      , COPY_LOT_ATTRIBUTE_FLAG
      , DEFAULT_GRADE
      , EXPIRATION_ACTION_CODE
      , EXPIRATION_ACTION_INTERVAL
      , GRADE_CONTROL_FLAG
      , HAZARDOUS_MATERIAL_FLAG
      , HOLD_DAYS
      , LOT_DIVISIBLE_FLAG
      , MATURITY_DAYS
      , PARENT_CHILD_GENERATION_FLAG
      , PROCESS_COSTING_ENABLED_FLAG
      , PROCESS_EXECUTION_ENABLED_FLAG
      , PROCESS_QUALITY_ENABLED_FLAG
      , PROCESS_SUPPLY_LOCATOR_ID
      , PROCESS_SUPPLY_SUBINVENTORY
      , PROCESS_YIELD_LOCATOR_ID
      , PROCESS_YIELD_SUBINVENTORY
      , RECIPE_ENABLED_FLAG
      , RETEST_INTERVAL
      , CHARGE_PERIODICITY_CODE
      , REPAIR_LEADTIME
      , REPAIR_YIELD
      , PREPOSITION_POINT
      , REPAIR_PROGRAM
      , SUBCONTRACTING_COMPONENT
      , OUTSOURCED_ASSEMBLY
      , EGO_MASTER_ITEMS_DFF_CTX
      , GDSN_OUTBOUND_ENABLED_FLAG
      , TRADE_ITEM_DESCRIPTOR
      , STYLE_ITEM_ID
      , STYLE_ITEM_FLAG
      , LAST_SUBMITTED_NIR_ID
      , DEFAULT_MATERIAL_STATUS_ID
      , SERIAL_TAGGING_FLAG
      , IB_ITEM_TRACKING_LEVEL
      , MCC_CLASSIFICATION_TYPE
      , MCC_CONTROL_CODE
      , MCC_TRACKING_CODE
      , GLOBAL_ATTRIBUTE21
      , GLOBAL_ATTRIBUTE22
      , GLOBAL_ATTRIBUTE23
      , GLOBAL_ATTRIBUTE24
      , GLOBAL_ATTRIBUTE25
      , GLOBAL_ATTRIBUTE26
      , GLOBAL_ATTRIBUTE27
      , GLOBAL_ATTRIBUTE28
      , GLOBAL_ATTRIBUTE29
      , GLOBAL_ATTRIBUTE30
      , GLOBAL_ATTRIBUTE31
      , GLOBAL_ATTRIBUTE32
      , GLOBAL_ATTRIBUTE33
      , GLOBAL_ATTRIBUTE34
      , GLOBAL_ATTRIBUTE35
      , GLOBAL_ATTRIBUTE36
      , GLOBAL_ATTRIBUTE37
      , GLOBAL_ATTRIBUTE38
      , GLOBAL_ATTRIBUTE39
      , GLOBAL_ATTRIBUTE40
      , _FIVETRAN_DELETED
      , _FIVETRAN_ID
      , _FIVETRAN_SYNCED
      , PSA_DELETE_IND
      , PSA_LOAD_DTS
      , PSA_RECORD_SOURCE
      , LOAD_DTS
      , REC_SRC
      , BKCC
      , HASHDIFF
    FROM LOGIC_SEMTK
)
---- FILTER LAYER ----

, FILTER_SEMTK as (
    SELECT *
    FROM RENAME_SEMTK
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM FILTER_SEMTK
)

---- FINAL LAYER ----
SELECT
          ITEM_HK
        , SEGMENT1
        , INVENTORY_ITEM_ID
        , ORGANIZATION_ID
        , LAST_UPDATE_DATE
        , LAST_UPDATED_BY
        , CREATION_DATE
        , CREATED_BY
        , LAST_UPDATE_LOGIN
        , SUMMARY_FLAG
        , ENABLED_FLAG
        , START_DATE_ACTIVE
        , END_DATE_ACTIVE
        , DESCRIPTION
        , BUYER_ID
        , ACCOUNTING_RULE_ID
        , INVOICING_RULE_ID
        , SEGMENT2
        , SEGMENT3
        , SEGMENT4
        , SEGMENT5
        , SEGMENT6
        , SEGMENT7
        , SEGMENT8
        , SEGMENT9
        , SEGMENT10
        , SEGMENT11
        , SEGMENT12
        , SEGMENT13
        , SEGMENT14
        , SEGMENT15
        , SEGMENT16
        , SEGMENT17
        , SEGMENT18
        , SEGMENT19
        , SEGMENT20
        , ATTRIBUTE_CATEGORY
        , ATTRIBUTE1
        , ATTRIBUTE2
        , ATTRIBUTE3
        , ATTRIBUTE4
        , ATTRIBUTE5
        , ATTRIBUTE6
        , ATTRIBUTE7
        , ATTRIBUTE8
        , ATTRIBUTE9
        , ATTRIBUTE10
        , ATTRIBUTE11
        , ATTRIBUTE12
        , ATTRIBUTE13
        , ATTRIBUTE14
        , ATTRIBUTE15
        , PURCHASING_ITEM_FLAG
        , SHIPPABLE_ITEM_FLAG
        , CUSTOMER_ORDER_FLAG
        , INTERNAL_ORDER_FLAG
        , SERVICE_ITEM_FLAG
        , INVENTORY_ITEM_FLAG
        , ENG_ITEM_FLAG
        , INVENTORY_ASSET_FLAG
        , PURCHASING_ENABLED_FLAG
        , CUSTOMER_ORDER_ENABLED_FLAG
        , INTERNAL_ORDER_ENABLED_FLAG
        , SO_TRANSACTIONS_FLAG
        , MTL_TRANSACTIONS_ENABLED_FLAG
        , STOCK_ENABLED_FLAG
        , BOM_ENABLED_FLAG
        , BUILD_IN_WIP_FLAG
        , REVISION_QTY_CONTROL_CODE
        , ITEM_CATALOG_GROUP_ID
        , CATALOG_STATUS_FLAG
        , RETURNABLE_FLAG
        , DEFAULT_SHIPPING_ORG
        , COLLATERAL_FLAG
        , TAXABLE_FLAG
        , QTY_RCV_EXCEPTION_CODE
        , ALLOW_ITEM_DESC_UPDATE_FLAG
        , INSPECTION_REQUIRED_FLAG
        , RECEIPT_REQUIRED_FLAG
        , MARKET_PRICE
        , HAZARD_CLASS_ID
        , RFQ_REQUIRED_FLAG
        , QTY_RCV_TOLERANCE
        , LIST_PRICE_PER_UNIT
        , UN_NUMBER_ID
        , PRICE_TOLERANCE_PERCENT
        , ASSET_CATEGORY_ID
        , ROUNDING_FACTOR
        , UNIT_OF_ISSUE
        , ENFORCE_SHIP_TO_LOCATION_CODE
        , ALLOW_SUBSTITUTE_RECEIPTS_FLAG
        , ALLOW_UNORDERED_RECEIPTS_FLAG
        , ALLOW_EXPRESS_DELIVERY_FLAG
        , DAYS_EARLY_RECEIPT_ALLOWED
        , DAYS_LATE_RECEIPT_ALLOWED
        , RECEIPT_DAYS_EXCEPTION_CODE
        , RECEIVING_ROUTING_ID
        , INVOICE_CLOSE_TOLERANCE
        , RECEIVE_CLOSE_TOLERANCE
        , AUTO_LOT_ALPHA_PREFIX
        , START_AUTO_LOT_NUMBER
        , LOT_CONTROL_CODE
        , SHELF_LIFE_CODE
        , SHELF_LIFE_DAYS
        , SERIAL_NUMBER_CONTROL_CODE
        , START_AUTO_SERIAL_NUMBER
        , AUTO_SERIAL_ALPHA_PREFIX
        , SOURCE_TYPE
        , SOURCE_ORGANIZATION_ID
        , SOURCE_SUBINVENTORY
        , EXPENSE_ACCOUNT
        , ENCUMBRANCE_ACCOUNT
        , RESTRICT_SUBINVENTORIES_CODE
        , UNIT_WEIGHT
        , WEIGHT_UOM_CODE
        , VOLUME_UOM_CODE
        , UNIT_VOLUME
        , RESTRICT_LOCATORS_CODE
        , LOCATION_CONTROL_CODE
        , SHRINKAGE_RATE
        , ACCEPTABLE_EARLY_DAYS
        , PLANNING_TIME_FENCE_CODE
        , DEMAND_TIME_FENCE_CODE
        , LEAD_TIME_LOT_SIZE
        , STD_LOT_SIZE
        , CUM_MANUFACTURING_LEAD_TIME
        , OVERRUN_PERCENTAGE
        , MRP_CALCULATE_ATP_FLAG
        , ACCEPTABLE_RATE_INCREASE
        , ACCEPTABLE_RATE_DECREASE
        , CUMULATIVE_TOTAL_LEAD_TIME
        , PLANNING_TIME_FENCE_DAYS
        , DEMAND_TIME_FENCE_DAYS
        , END_ASSEMBLY_PEGGING_FLAG
        , REPETITIVE_PLANNING_FLAG
        , PLANNING_EXCEPTION_SET
        , BOM_ITEM_TYPE
        , PICK_COMPONENTS_FLAG
        , REPLENISH_TO_ORDER_FLAG
        , BASE_ITEM_ID
        , ATP_COMPONENTS_FLAG
        , ATP_FLAG
        , FIXED_LEAD_TIME
        , VARIABLE_LEAD_TIME
        , WIP_SUPPLY_LOCATOR_ID
        , WIP_SUPPLY_TYPE
        , WIP_SUPPLY_SUBINVENTORY
        , PRIMARY_UOM_CODE
        , PRIMARY_UNIT_OF_MEASURE
        , ALLOWED_UNITS_LOOKUP_CODE
        , COST_OF_SALES_ACCOUNT
        , SALES_ACCOUNT
        , DEFAULT_INCLUDE_IN_ROLLUP_FLAG
        , INVENTORY_ITEM_STATUS_CODE
        , INVENTORY_PLANNING_CODE
        , PLANNER_CODE
        , PLANNING_MAKE_BUY_CODE
        , FIXED_LOT_MULTIPLIER
        , ROUNDING_CONTROL_TYPE
        , CARRYING_COST
        , POSTPROCESSING_LEAD_TIME
        , PREPROCESSING_LEAD_TIME
        , FULL_LEAD_TIME
        , ORDER_COST
        , MRP_SAFETY_STOCK_PERCENT
        , MRP_SAFETY_STOCK_CODE
        , MIN_MINMAX_QUANTITY
        , MAX_MINMAX_QUANTITY
        , MINIMUM_ORDER_QUANTITY
        , FIXED_ORDER_QUANTITY
        , FIXED_DAYS_SUPPLY
        , MAXIMUM_ORDER_QUANTITY
        , ATP_RULE_ID
        , PICKING_RULE_ID
        , RESERVABLE_TYPE
        , POSITIVE_MEASUREMENT_ERROR
        , NEGATIVE_MEASUREMENT_ERROR
        , ENGINEERING_ECN_CODE
        , ENGINEERING_ITEM_ID
        , ENGINEERING_DATE
        , SERVICE_STARTING_DELAY
        , VENDOR_WARRANTY_FLAG
        , SERVICEABLE_COMPONENT_FLAG
        , SERVICEABLE_PRODUCT_FLAG
        , BASE_WARRANTY_SERVICE_ID
        , PAYMENT_TERMS_ID
        , PREVENTIVE_MAINTENANCE_FLAG
        , PRIMARY_SPECIALIST_ID
        , SECONDARY_SPECIALIST_ID
        , SERVICEABLE_ITEM_CLASS_ID
        , TIME_BILLABLE_FLAG
        , MATERIAL_BILLABLE_FLAG
        , EXPENSE_BILLABLE_FLAG
        , PRORATE_SERVICE_FLAG
        , COVERAGE_SCHEDULE_ID
        , SERVICE_DURATION_PERIOD_CODE
        , SERVICE_DURATION
        , WARRANTY_VENDOR_ID
        , MAX_WARRANTY_AMOUNT
        , RESPONSE_TIME_PERIOD_CODE
        , RESPONSE_TIME_VALUE
        , NEW_REVISION_CODE
        , INVOICEABLE_ITEM_FLAG
        , TAX_CODE
        , INVOICE_ENABLED_FLAG
        , MUST_USE_APPROVED_VENDOR_FLAG
        , REQUEST_ID
        , PROGRAM_APPLICATION_ID
        , PROGRAM_ID
        , PROGRAM_UPDATE_DATE
        , OUTSIDE_OPERATION_FLAG
        , OUTSIDE_OPERATION_UOM_TYPE
        , SAFETY_STOCK_BUCKET_DAYS
        , AUTO_REDUCE_MPS
        , COSTING_ENABLED_FLAG
        , AUTO_CREATED_CONFIG_FLAG
        , CYCLE_COUNT_ENABLED_FLAG
        , ITEM_TYPE
        , MODEL_CONFIG_CLAUSE_NAME
        , SHIP_MODEL_COMPLETE_FLAG
        , MRP_PLANNING_CODE
        , RETURN_INSPECTION_REQUIREMENT
        , ATO_FORECAST_CONTROL
        , RELEASE_TIME_FENCE_CODE
        , RELEASE_TIME_FENCE_DAYS
        , CONTAINER_ITEM_FLAG
        , VEHICLE_ITEM_FLAG
        , MAXIMUM_LOAD_WEIGHT
        , MINIMUM_FILL_PERCENT
        , CONTAINER_TYPE_CODE
        , INTERNAL_VOLUME
        , WH_UPDATE_DATE
        , PRODUCT_FAMILY_ITEM_ID
        , GLOBAL_ATTRIBUTE_CATEGORY
        , GLOBAL_ATTRIBUTE1
        , GLOBAL_ATTRIBUTE2
        , GLOBAL_ATTRIBUTE3
        , GLOBAL_ATTRIBUTE4
        , GLOBAL_ATTRIBUTE5
        , GLOBAL_ATTRIBUTE6
        , GLOBAL_ATTRIBUTE7
        , GLOBAL_ATTRIBUTE8
        , GLOBAL_ATTRIBUTE9
        , GLOBAL_ATTRIBUTE10
        , PURCHASING_TAX_CODE
        , OVERCOMPLETION_TOLERANCE_TYPE
        , OVERCOMPLETION_TOLERANCE_VALUE
        , EFFECTIVITY_CONTROL
        , CHECK_SHORTAGES_FLAG
        , OVER_SHIPMENT_TOLERANCE
        , UNDER_SHIPMENT_TOLERANCE
        , OVER_RETURN_TOLERANCE
        , UNDER_RETURN_TOLERANCE
        , EQUIPMENT_TYPE
        , RECOVERED_PART_DISP_CODE
        , DEFECT_TRACKING_ON_FLAG
        , USAGE_ITEM_FLAG
        , EVENT_FLAG
        , ELECTRONIC_FLAG
        , DOWNLOADABLE_FLAG
        , VOL_DISCOUNT_EXEMPT_FLAG
        , COUPON_EXEMPT_FLAG
        , COMMS_NL_TRACKABLE_FLAG
        , ASSET_CREATION_CODE
        , COMMS_ACTIVATION_REQD_FLAG
        , ORDERABLE_ON_WEB_FLAG
        , BACK_ORDERABLE_FLAG
        , WEB_STATUS
        , INDIVISIBLE_FLAG
        , DIMENSION_UOM_CODE
        , UNIT_LENGTH
        , UNIT_WIDTH
        , UNIT_HEIGHT
        , BULK_PICKED_FLAG
        , LOT_STATUS_ENABLED
        , DEFAULT_LOT_STATUS_ID
        , SERIAL_STATUS_ENABLED
        , DEFAULT_SERIAL_STATUS_ID
        , LOT_SPLIT_ENABLED
        , LOT_MERGE_ENABLED
        , INVENTORY_CARRY_PENALTY
        , OPERATION_SLACK_PENALTY
        , FINANCING_ALLOWED_FLAG
        , EAM_ITEM_TYPE
        , EAM_ACTIVITY_TYPE_CODE
        , EAM_ACTIVITY_CAUSE_CODE
        , EAM_ACT_NOTIFICATION_FLAG
        , EAM_ACT_SHUTDOWN_STATUS
        , DUAL_UOM_CONTROL
        , SECONDARY_UOM_CODE
        , DUAL_UOM_DEVIATION_HIGH
        , DUAL_UOM_DEVIATION_LOW
        , CONTRACT_ITEM_TYPE_CODE
        , SUBSCRIPTION_DEPEND_FLAG
        , SERV_REQ_ENABLED_CODE
        , SERV_BILLING_ENABLED_FLAG
        , SERV_IMPORTANCE_LEVEL
        , PLANNED_INV_POINT_FLAG
        , LOT_TRANSLATE_ENABLED
        , DEFAULT_SO_SOURCE_TYPE
        , CREATE_SUPPLY_FLAG
        , SUBSTITUTION_WINDOW_CODE
        , SUBSTITUTION_WINDOW_DAYS
        , IB_ITEM_INSTANCE_CLASS
        , CONFIG_MODEL_TYPE
        , LOT_SUBSTITUTION_ENABLED
        , MINIMUM_LICENSE_QUANTITY
        , EAM_ACTIVITY_SOURCE_CODE
        , LIFECYCLE_ID
        , CURRENT_PHASE_ID
        , OBJECT_VERSION_NUMBER
        , TRACKING_QUANTITY_IND
        , ONT_PRICING_QTY_SOURCE
        , SECONDARY_DEFAULT_IND
        , OPTION_SPECIFIC_SOURCED
        , APPROVAL_STATUS
        , VMI_MINIMUM_UNITS
        , VMI_MINIMUM_DAYS
        , VMI_MAXIMUM_UNITS
        , VMI_MAXIMUM_DAYS
        , VMI_FIXED_ORDER_QUANTITY
        , SO_AUTHORIZATION_FLAG
        , CONSIGNED_FLAG
        , ASN_AUTOEXPIRE_FLAG
        , VMI_FORECAST_TYPE
        , FORECAST_HORIZON
        , EXCLUDE_FROM_BUDGET_FLAG
        , DAYS_TGT_INV_SUPPLY
        , DAYS_TGT_INV_WINDOW
        , DAYS_MAX_INV_SUPPLY
        , DAYS_MAX_INV_WINDOW
        , DRP_PLANNED_FLAG
        , CRITICAL_COMPONENT_FLAG
        , CONTINOUS_TRANSFER
        , CONVERGENCE
        , DIVERGENCE
        , CONFIG_ORGS
        , CONFIG_MATCH
        , GLOBAL_ATTRIBUTE11
        , GLOBAL_ATTRIBUTE12
        , GLOBAL_ATTRIBUTE13
        , GLOBAL_ATTRIBUTE14
        , GLOBAL_ATTRIBUTE15
        , GLOBAL_ATTRIBUTE16
        , GLOBAL_ATTRIBUTE17
        , GLOBAL_ATTRIBUTE18
        , GLOBAL_ATTRIBUTE19
        , GLOBAL_ATTRIBUTE20
        , ATTRIBUTE16
        , ATTRIBUTE17
        , ATTRIBUTE18
        , ATTRIBUTE19
        , ATTRIBUTE20
        , ATTRIBUTE21
        , ATTRIBUTE22
        , ATTRIBUTE23
        , ATTRIBUTE24
        , ATTRIBUTE25
        , ATTRIBUTE26
        , ATTRIBUTE27
        , ATTRIBUTE28
        , ATTRIBUTE29
        , ATTRIBUTE30
        , CAS_NUMBER
        , CHILD_LOT_FLAG
        , CHILD_LOT_PREFIX
        , CHILD_LOT_STARTING_NUMBER
        , CHILD_LOT_VALIDATION_FLAG
        , COPY_LOT_ATTRIBUTE_FLAG
        , DEFAULT_GRADE
        , EXPIRATION_ACTION_CODE
        , EXPIRATION_ACTION_INTERVAL
        , GRADE_CONTROL_FLAG
        , HAZARDOUS_MATERIAL_FLAG
        , HOLD_DAYS
        , LOT_DIVISIBLE_FLAG
        , MATURITY_DAYS
        , PARENT_CHILD_GENERATION_FLAG
        , PROCESS_COSTING_ENABLED_FLAG
        , PROCESS_EXECUTION_ENABLED_FLAG
        , PROCESS_QUALITY_ENABLED_FLAG
        , PROCESS_SUPPLY_LOCATOR_ID
        , PROCESS_SUPPLY_SUBINVENTORY
        , PROCESS_YIELD_LOCATOR_ID
        , PROCESS_YIELD_SUBINVENTORY
        , RECIPE_ENABLED_FLAG
        , RETEST_INTERVAL
        , CHARGE_PERIODICITY_CODE
        , REPAIR_LEADTIME
        , REPAIR_YIELD
        , PREPOSITION_POINT
        , REPAIR_PROGRAM
        , SUBCONTRACTING_COMPONENT
        , OUTSOURCED_ASSEMBLY
        , EGO_MASTER_ITEMS_DFF_CTX
        , GDSN_OUTBOUND_ENABLED_FLAG
        , TRADE_ITEM_DESCRIPTOR
        , STYLE_ITEM_ID
        , STYLE_ITEM_FLAG
        , LAST_SUBMITTED_NIR_ID
        , DEFAULT_MATERIAL_STATUS_ID
        , SERIAL_TAGGING_FLAG
        , IB_ITEM_TRACKING_LEVEL
        , MCC_CLASSIFICATION_TYPE
        , MCC_CONTROL_CODE
        , MCC_TRACKING_CODE
        , GLOBAL_ATTRIBUTE21
        , GLOBAL_ATTRIBUTE22
        , GLOBAL_ATTRIBUTE23
        , GLOBAL_ATTRIBUTE24
        , GLOBAL_ATTRIBUTE25
        , GLOBAL_ATTRIBUTE26
        , GLOBAL_ATTRIBUTE27
        , GLOBAL_ATTRIBUTE28
        , GLOBAL_ATTRIBUTE29
        , GLOBAL_ATTRIBUTE30
        , GLOBAL_ATTRIBUTE31
        , GLOBAL_ATTRIBUTE32
        , GLOBAL_ATTRIBUTE33
        , GLOBAL_ATTRIBUTE34
        , GLOBAL_ATTRIBUTE35
        , GLOBAL_ATTRIBUTE36
        , GLOBAL_ATTRIBUTE37
        , GLOBAL_ATTRIBUTE38
        , GLOBAL_ATTRIBUTE39
        , GLOBAL_ATTRIBUTE40
        , _FIVETRAN_DELETED
        , _FIVETRAN_ID
        , _FIVETRAN_SYNCED
        , PSA_DELETE_IND
        , PSA_LOAD_DTS
        , PSA_RECORD_SOURCE
        , LOAD_DTS
        , REC_SRC
        , BKCC
        , HASHDIFF
FROM JOIN_RESULT
{% if is_incremental() %}
WHERE NOT EXISTS (
    SELECT 1 
    FROM {{ this }} existing
    WHERE existing.ITEM_HK= JOIN_RESULT.ITEM_HK
     AND existing.INVENTORY_ITEM_ID = JOIN_RESULT.INVENTORY_ITEM_ID 
     AND existing.ORGANIZATION_ID = JOIN_RESULT.ORGANIZATION_ID 
    AND existing.HASHDIFF = JOIN_RESULT.HASHDIFF
)
{% endif %}
{% if not is_incremental() %}

/* The following qualifier is implemented to prevent multiple loads of touched records during the initial build, such as multiple rows per HK and hashdiff. */
qualify 1 = row_number() over (partition by ITEM_HK, INVENTORY_ITEM_ID, ORGANIZATION_ID, HASHDIFF order by PSA_LOAD_DTS)

union all
SELECT 
MD5_BINARY(GR.VALUE) AS ITEM_HK,
GR.VALUE::text AS SEGMENT1,
GR.VALUE::number AS INVENTORY_ITEM_ID,
GR.VALUE::number AS ORGANIZATION_ID,
NULL AS LAST_UPDATE_DATE,
NULL AS LAST_UPDATED_BY,
NULL AS CREATION_DATE,
NULL AS CREATED_BY,
NULL AS LAST_UPDATE_LOGIN,
NULL AS SUMMARY_FLAG,
NULL AS ENABLED_FLAG,
NULL AS START_DATE_ACTIVE,
NULL AS END_DATE_ACTIVE,
NULL AS DESCRIPTION,
NULL AS BUYER_ID,
NULL AS ACCOUNTING_RULE_ID,
NULL AS INVOICING_RULE_ID,
NULL AS SEGMENT2,
NULL AS SEGMENT3,
NULL AS SEGMENT4,
NULL AS SEGMENT5,
NULL AS SEGMENT6,
NULL AS SEGMENT7,
NULL AS SEGMENT8,
NULL AS SEGMENT9,
NULL AS SEGMENT10,
NULL AS SEGMENT11,
NULL AS SEGMENT12,
NULL AS SEGMENT13,
NULL AS SEGMENT14,
NULL AS SEGMENT15,
NULL AS SEGMENT16,
NULL AS SEGMENT17,
NULL AS SEGMENT18,
NULL AS SEGMENT19,
NULL AS SEGMENT20,
NULL AS ATTRIBUTE_CATEGORY,
NULL AS ATTRIBUTE1,
NULL AS ATTRIBUTE2,
NULL AS ATTRIBUTE3,
NULL AS ATTRIBUTE4,
NULL AS ATTRIBUTE5,
NULL AS ATTRIBUTE6,
NULL AS ATTRIBUTE7,
NULL AS ATTRIBUTE8,
NULL AS ATTRIBUTE9,
NULL AS ATTRIBUTE10,
NULL AS ATTRIBUTE11,
NULL AS ATTRIBUTE12,
NULL AS ATTRIBUTE13,
NULL AS ATTRIBUTE14,
NULL AS ATTRIBUTE15,
NULL AS PURCHASING_ITEM_FLAG,
NULL AS SHIPPABLE_ITEM_FLAG,
NULL AS CUSTOMER_ORDER_FLAG,
NULL AS INTERNAL_ORDER_FLAG,
NULL AS SERVICE_ITEM_FLAG,
NULL AS INVENTORY_ITEM_FLAG,
NULL AS ENG_ITEM_FLAG,
NULL AS INVENTORY_ASSET_FLAG,
NULL AS PURCHASING_ENABLED_FLAG,
NULL AS CUSTOMER_ORDER_ENABLED_FLAG,
NULL AS INTERNAL_ORDER_ENABLED_FLAG,
NULL AS SO_TRANSACTIONS_FLAG,
NULL AS MTL_TRANSACTIONS_ENABLED_FLAG,
NULL AS STOCK_ENABLED_FLAG,
NULL AS BOM_ENABLED_FLAG,
NULL AS BUILD_IN_WIP_FLAG,
NULL AS REVISION_QTY_CONTROL_CODE,
NULL AS ITEM_CATALOG_GROUP_ID,
NULL AS CATALOG_STATUS_FLAG,
NULL AS RETURNABLE_FLAG,
NULL AS DEFAULT_SHIPPING_ORG,
NULL AS COLLATERAL_FLAG,
NULL AS TAXABLE_FLAG,
NULL AS QTY_RCV_EXCEPTION_CODE,
NULL AS ALLOW_ITEM_DESC_UPDATE_FLAG,
NULL AS INSPECTION_REQUIRED_FLAG,
NULL AS RECEIPT_REQUIRED_FLAG,
NULL AS MARKET_PRICE,
NULL AS HAZARD_CLASS_ID,
NULL AS RFQ_REQUIRED_FLAG,
NULL AS QTY_RCV_TOLERANCE,
NULL AS LIST_PRICE_PER_UNIT,
NULL AS UN_NUMBER_ID,
NULL AS PRICE_TOLERANCE_PERCENT,
NULL AS ASSET_CATEGORY_ID,
NULL AS ROUNDING_FACTOR,
NULL AS UNIT_OF_ISSUE,
NULL AS ENFORCE_SHIP_TO_LOCATION_CODE,
NULL AS ALLOW_SUBSTITUTE_RECEIPTS_FLAG,
NULL AS ALLOW_UNORDERED_RECEIPTS_FLAG,
NULL AS ALLOW_EXPRESS_DELIVERY_FLAG,
NULL AS DAYS_EARLY_RECEIPT_ALLOWED,
NULL AS DAYS_LATE_RECEIPT_ALLOWED,
NULL AS RECEIPT_DAYS_EXCEPTION_CODE,
NULL AS RECEIVING_ROUTING_ID,
NULL AS INVOICE_CLOSE_TOLERANCE,
NULL AS RECEIVE_CLOSE_TOLERANCE,
NULL AS AUTO_LOT_ALPHA_PREFIX,
NULL AS START_AUTO_LOT_NUMBER,
NULL AS LOT_CONTROL_CODE,
NULL AS SHELF_LIFE_CODE,
NULL AS SHELF_LIFE_DAYS,
NULL AS SERIAL_NUMBER_CONTROL_CODE,
NULL AS START_AUTO_SERIAL_NUMBER,
NULL AS AUTO_SERIAL_ALPHA_PREFIX,
NULL AS SOURCE_TYPE,
NULL AS SOURCE_ORGANIZATION_ID,
NULL AS SOURCE_SUBINVENTORY,
NULL AS EXPENSE_ACCOUNT,
NULL AS ENCUMBRANCE_ACCOUNT,
NULL AS RESTRICT_SUBINVENTORIES_CODE,
NULL AS UNIT_WEIGHT,
NULL AS WEIGHT_UOM_CODE,
NULL AS VOLUME_UOM_CODE,
NULL AS UNIT_VOLUME,
NULL AS RESTRICT_LOCATORS_CODE,
NULL AS LOCATION_CONTROL_CODE,
NULL AS SHRINKAGE_RATE,
NULL AS ACCEPTABLE_EARLY_DAYS,
NULL AS PLANNING_TIME_FENCE_CODE,
NULL AS DEMAND_TIME_FENCE_CODE,
NULL AS LEAD_TIME_LOT_SIZE,
NULL AS STD_LOT_SIZE,
NULL AS CUM_MANUFACTURING_LEAD_TIME,
NULL AS OVERRUN_PERCENTAGE,
NULL AS MRP_CALCULATE_ATP_FLAG,
NULL AS ACCEPTABLE_RATE_INCREASE,
NULL AS ACCEPTABLE_RATE_DECREASE,
NULL AS CUMULATIVE_TOTAL_LEAD_TIME,
NULL AS PLANNING_TIME_FENCE_DAYS,
NULL AS DEMAND_TIME_FENCE_DAYS,
NULL AS END_ASSEMBLY_PEGGING_FLAG,
NULL AS REPETITIVE_PLANNING_FLAG,
NULL AS PLANNING_EXCEPTION_SET,
NULL AS BOM_ITEM_TYPE,
NULL AS PICK_COMPONENTS_FLAG,
NULL AS REPLENISH_TO_ORDER_FLAG,
NULL AS BASE_ITEM_ID,
NULL AS ATP_COMPONENTS_FLAG,
NULL AS ATP_FLAG,
NULL AS FIXED_LEAD_TIME,
NULL AS VARIABLE_LEAD_TIME,
NULL AS WIP_SUPPLY_LOCATOR_ID,
NULL AS WIP_SUPPLY_TYPE,
NULL AS WIP_SUPPLY_SUBINVENTORY,
NULL AS PRIMARY_UOM_CODE,
NULL AS PRIMARY_UNIT_OF_MEASURE,
NULL AS ALLOWED_UNITS_LOOKUP_CODE,
NULL AS COST_OF_SALES_ACCOUNT,
NULL AS SALES_ACCOUNT,
NULL AS DEFAULT_INCLUDE_IN_ROLLUP_FLAG,
NULL AS INVENTORY_ITEM_STATUS_CODE,
NULL AS INVENTORY_PLANNING_CODE,
NULL AS PLANNER_CODE,
NULL AS PLANNING_MAKE_BUY_CODE,
NULL AS FIXED_LOT_MULTIPLIER,
NULL AS ROUNDING_CONTROL_TYPE,
NULL AS CARRYING_COST,
NULL AS POSTPROCESSING_LEAD_TIME,
NULL AS PREPROCESSING_LEAD_TIME,
NULL AS FULL_LEAD_TIME,
NULL AS ORDER_COST,
NULL AS MRP_SAFETY_STOCK_PERCENT,
NULL AS MRP_SAFETY_STOCK_CODE,
NULL AS MIN_MINMAX_QUANTITY,
NULL AS MAX_MINMAX_QUANTITY,
NULL AS MINIMUM_ORDER_QUANTITY,
NULL AS FIXED_ORDER_QUANTITY,
NULL AS FIXED_DAYS_SUPPLY,
NULL AS MAXIMUM_ORDER_QUANTITY,
NULL AS ATP_RULE_ID,
NULL AS PICKING_RULE_ID,
NULL AS RESERVABLE_TYPE,
NULL AS POSITIVE_MEASUREMENT_ERROR,
NULL AS NEGATIVE_MEASUREMENT_ERROR,
NULL AS ENGINEERING_ECN_CODE,
NULL AS ENGINEERING_ITEM_ID,
NULL AS ENGINEERING_DATE,
NULL AS SERVICE_STARTING_DELAY,
NULL AS VENDOR_WARRANTY_FLAG,
NULL AS SERVICEABLE_COMPONENT_FLAG,
NULL AS SERVICEABLE_PRODUCT_FLAG,
NULL AS BASE_WARRANTY_SERVICE_ID,
NULL AS PAYMENT_TERMS_ID,
NULL AS PREVENTIVE_MAINTENANCE_FLAG,
NULL AS PRIMARY_SPECIALIST_ID,
NULL AS SECONDARY_SPECIALIST_ID,
NULL AS SERVICEABLE_ITEM_CLASS_ID,
NULL AS TIME_BILLABLE_FLAG,
NULL AS MATERIAL_BILLABLE_FLAG,
NULL AS EXPENSE_BILLABLE_FLAG,
NULL AS PRORATE_SERVICE_FLAG,
NULL AS COVERAGE_SCHEDULE_ID,
NULL AS SERVICE_DURATION_PERIOD_CODE,
NULL AS SERVICE_DURATION,
NULL AS WARRANTY_VENDOR_ID,
NULL AS MAX_WARRANTY_AMOUNT,
NULL AS RESPONSE_TIME_PERIOD_CODE,
NULL AS RESPONSE_TIME_VALUE,
NULL AS NEW_REVISION_CODE,
NULL AS INVOICEABLE_ITEM_FLAG,
NULL AS TAX_CODE,
NULL AS INVOICE_ENABLED_FLAG,
NULL AS MUST_USE_APPROVED_VENDOR_FLAG,
NULL AS REQUEST_ID,
NULL AS PROGRAM_APPLICATION_ID,
NULL AS PROGRAM_ID,
NULL AS PROGRAM_UPDATE_DATE,
NULL AS OUTSIDE_OPERATION_FLAG,
NULL AS OUTSIDE_OPERATION_UOM_TYPE,
NULL AS SAFETY_STOCK_BUCKET_DAYS,
NULL AS AUTO_REDUCE_MPS,
NULL AS COSTING_ENABLED_FLAG,
NULL AS AUTO_CREATED_CONFIG_FLAG,
NULL AS CYCLE_COUNT_ENABLED_FLAG,
NULL AS ITEM_TYPE,
NULL AS MODEL_CONFIG_CLAUSE_NAME,
NULL AS SHIP_MODEL_COMPLETE_FLAG,
NULL AS MRP_PLANNING_CODE,
NULL AS RETURN_INSPECTION_REQUIREMENT,
NULL AS ATO_FORECAST_CONTROL,
NULL AS RELEASE_TIME_FENCE_CODE,
NULL AS RELEASE_TIME_FENCE_DAYS,
NULL AS CONTAINER_ITEM_FLAG,
NULL AS VEHICLE_ITEM_FLAG,
NULL AS MAXIMUM_LOAD_WEIGHT,
NULL AS MINIMUM_FILL_PERCENT,
NULL AS CONTAINER_TYPE_CODE,
NULL AS INTERNAL_VOLUME,
NULL AS WH_UPDATE_DATE,
NULL AS PRODUCT_FAMILY_ITEM_ID,
NULL AS GLOBAL_ATTRIBUTE_CATEGORY,
NULL AS GLOBAL_ATTRIBUTE1,
NULL AS GLOBAL_ATTRIBUTE2,
NULL AS GLOBAL_ATTRIBUTE3,
NULL AS GLOBAL_ATTRIBUTE4,
NULL AS GLOBAL_ATTRIBUTE5,
NULL AS GLOBAL_ATTRIBUTE6,
NULL AS GLOBAL_ATTRIBUTE7,
NULL AS GLOBAL_ATTRIBUTE8,
NULL AS GLOBAL_ATTRIBUTE9,
NULL AS GLOBAL_ATTRIBUTE10,
NULL AS PURCHASING_TAX_CODE,
NULL AS OVERCOMPLETION_TOLERANCE_TYPE,
NULL AS OVERCOMPLETION_TOLERANCE_VALUE,
NULL AS EFFECTIVITY_CONTROL,
NULL AS CHECK_SHORTAGES_FLAG,
NULL AS OVER_SHIPMENT_TOLERANCE,
NULL AS UNDER_SHIPMENT_TOLERANCE,
NULL AS OVER_RETURN_TOLERANCE,
NULL AS UNDER_RETURN_TOLERANCE,
NULL AS EQUIPMENT_TYPE,
NULL AS RECOVERED_PART_DISP_CODE,
NULL AS DEFECT_TRACKING_ON_FLAG,
NULL AS USAGE_ITEM_FLAG,
NULL AS EVENT_FLAG,
NULL AS ELECTRONIC_FLAG,
NULL AS DOWNLOADABLE_FLAG,
NULL AS VOL_DISCOUNT_EXEMPT_FLAG,
NULL AS COUPON_EXEMPT_FLAG,
NULL AS COMMS_NL_TRACKABLE_FLAG,
NULL AS ASSET_CREATION_CODE,
NULL AS COMMS_ACTIVATION_REQD_FLAG,
NULL AS ORDERABLE_ON_WEB_FLAG,
NULL AS BACK_ORDERABLE_FLAG,
NULL AS WEB_STATUS,
NULL AS INDIVISIBLE_FLAG,
NULL AS DIMENSION_UOM_CODE,
NULL AS UNIT_LENGTH,
NULL AS UNIT_WIDTH,
NULL AS UNIT_HEIGHT,
NULL AS BULK_PICKED_FLAG,
NULL AS LOT_STATUS_ENABLED,
NULL AS DEFAULT_LOT_STATUS_ID,
NULL AS SERIAL_STATUS_ENABLED,
NULL AS DEFAULT_SERIAL_STATUS_ID,
NULL AS LOT_SPLIT_ENABLED,
NULL AS LOT_MERGE_ENABLED,
NULL AS INVENTORY_CARRY_PENALTY,
NULL AS OPERATION_SLACK_PENALTY,
NULL AS FINANCING_ALLOWED_FLAG,
NULL AS EAM_ITEM_TYPE,
NULL AS EAM_ACTIVITY_TYPE_CODE,
NULL AS EAM_ACTIVITY_CAUSE_CODE,
NULL AS EAM_ACT_NOTIFICATION_FLAG,
NULL AS EAM_ACT_SHUTDOWN_STATUS,
NULL AS DUAL_UOM_CONTROL,
NULL AS SECONDARY_UOM_CODE,
NULL AS DUAL_UOM_DEVIATION_HIGH,
NULL AS DUAL_UOM_DEVIATION_LOW,
NULL AS CONTRACT_ITEM_TYPE_CODE,
NULL AS SUBSCRIPTION_DEPEND_FLAG,
NULL AS SERV_REQ_ENABLED_CODE,
NULL AS SERV_BILLING_ENABLED_FLAG,
NULL AS SERV_IMPORTANCE_LEVEL,
NULL AS PLANNED_INV_POINT_FLAG,
NULL AS LOT_TRANSLATE_ENABLED,
NULL AS DEFAULT_SO_SOURCE_TYPE,
NULL AS CREATE_SUPPLY_FLAG,
NULL AS SUBSTITUTION_WINDOW_CODE,
NULL AS SUBSTITUTION_WINDOW_DAYS,
NULL AS IB_ITEM_INSTANCE_CLASS,
NULL AS CONFIG_MODEL_TYPE,
NULL AS LOT_SUBSTITUTION_ENABLED,
NULL AS MINIMUM_LICENSE_QUANTITY,
NULL AS EAM_ACTIVITY_SOURCE_CODE,
NULL AS LIFECYCLE_ID,
NULL AS CURRENT_PHASE_ID,
NULL AS OBJECT_VERSION_NUMBER,
NULL AS TRACKING_QUANTITY_IND,
NULL AS ONT_PRICING_QTY_SOURCE,
NULL AS SECONDARY_DEFAULT_IND,
NULL AS OPTION_SPECIFIC_SOURCED,
NULL AS APPROVAL_STATUS,
NULL AS VMI_MINIMUM_UNITS,
NULL AS VMI_MINIMUM_DAYS,
NULL AS VMI_MAXIMUM_UNITS,
NULL AS VMI_MAXIMUM_DAYS,
NULL AS VMI_FIXED_ORDER_QUANTITY,
NULL AS SO_AUTHORIZATION_FLAG,
NULL AS CONSIGNED_FLAG,
NULL AS ASN_AUTOEXPIRE_FLAG,
NULL AS VMI_FORECAST_TYPE,
NULL AS FORECAST_HORIZON,
NULL AS EXCLUDE_FROM_BUDGET_FLAG,
NULL AS DAYS_TGT_INV_SUPPLY,
NULL AS DAYS_TGT_INV_WINDOW,
NULL AS DAYS_MAX_INV_SUPPLY,
NULL AS DAYS_MAX_INV_WINDOW,
NULL AS DRP_PLANNED_FLAG,
NULL AS CRITICAL_COMPONENT_FLAG,
NULL AS CONTINOUS_TRANSFER,
NULL AS CONVERGENCE,
NULL AS DIVERGENCE,
NULL AS CONFIG_ORGS,
NULL AS CONFIG_MATCH,
NULL AS GLOBAL_ATTRIBUTE11,
NULL AS GLOBAL_ATTRIBUTE12,
NULL AS GLOBAL_ATTRIBUTE13,
NULL AS GLOBAL_ATTRIBUTE14,
NULL AS GLOBAL_ATTRIBUTE15,
NULL AS GLOBAL_ATTRIBUTE16,
NULL AS GLOBAL_ATTRIBUTE17,
NULL AS GLOBAL_ATTRIBUTE18,
NULL AS GLOBAL_ATTRIBUTE19,
NULL AS GLOBAL_ATTRIBUTE20,
NULL AS ATTRIBUTE16,
NULL AS ATTRIBUTE17,
NULL AS ATTRIBUTE18,
NULL AS ATTRIBUTE19,
NULL AS ATTRIBUTE20,
NULL AS ATTRIBUTE21,
NULL AS ATTRIBUTE22,
NULL AS ATTRIBUTE23,
NULL AS ATTRIBUTE24,
NULL AS ATTRIBUTE25,
NULL AS ATTRIBUTE26,
NULL AS ATTRIBUTE27,
NULL AS ATTRIBUTE28,
NULL AS ATTRIBUTE29,
NULL AS ATTRIBUTE30,
NULL AS CAS_NUMBER,
NULL AS CHILD_LOT_FLAG,
NULL AS CHILD_LOT_PREFIX,
NULL AS CHILD_LOT_STARTING_NUMBER,
NULL AS CHILD_LOT_VALIDATION_FLAG,
NULL AS COPY_LOT_ATTRIBUTE_FLAG,
NULL AS DEFAULT_GRADE,
NULL AS EXPIRATION_ACTION_CODE,
NULL AS EXPIRATION_ACTION_INTERVAL,
NULL AS GRADE_CONTROL_FLAG,
NULL AS HAZARDOUS_MATERIAL_FLAG,
NULL AS HOLD_DAYS,
NULL AS LOT_DIVISIBLE_FLAG,
NULL AS MATURITY_DAYS,
NULL AS PARENT_CHILD_GENERATION_FLAG,
NULL AS PROCESS_COSTING_ENABLED_FLAG,
NULL AS PROCESS_EXECUTION_ENABLED_FLAG,
NULL AS PROCESS_QUALITY_ENABLED_FLAG,
NULL AS PROCESS_SUPPLY_LOCATOR_ID,
NULL AS PROCESS_SUPPLY_SUBINVENTORY,
NULL AS PROCESS_YIELD_LOCATOR_ID,
NULL AS PROCESS_YIELD_SUBINVENTORY,
NULL AS RECIPE_ENABLED_FLAG,
NULL AS RETEST_INTERVAL,
NULL AS CHARGE_PERIODICITY_CODE,
NULL AS REPAIR_LEADTIME,
NULL AS REPAIR_YIELD,
NULL AS PREPOSITION_POINT,
NULL AS REPAIR_PROGRAM,
NULL AS SUBCONTRACTING_COMPONENT,
NULL AS OUTSOURCED_ASSEMBLY,
NULL AS EGO_MASTER_ITEMS_DFF_CTX,
NULL AS GDSN_OUTBOUND_ENABLED_FLAG,
NULL AS TRADE_ITEM_DESCRIPTOR,
NULL AS STYLE_ITEM_ID,
NULL AS STYLE_ITEM_FLAG,
NULL AS LAST_SUBMITTED_NIR_ID,
NULL AS DEFAULT_MATERIAL_STATUS_ID,
NULL AS SERIAL_TAGGING_FLAG,
NULL AS IB_ITEM_TRACKING_LEVEL,
NULL AS MCC_CLASSIFICATION_TYPE,
NULL AS MCC_CONTROL_CODE,
NULL AS MCC_TRACKING_CODE,
NULL AS GLOBAL_ATTRIBUTE21,
NULL AS GLOBAL_ATTRIBUTE22,
NULL AS GLOBAL_ATTRIBUTE23,
NULL AS GLOBAL_ATTRIBUTE24,
NULL AS GLOBAL_ATTRIBUTE25,
NULL AS GLOBAL_ATTRIBUTE26,
NULL AS GLOBAL_ATTRIBUTE27,
NULL AS GLOBAL_ATTRIBUTE28,
NULL AS GLOBAL_ATTRIBUTE29,
NULL AS GLOBAL_ATTRIBUTE30,
NULL AS GLOBAL_ATTRIBUTE31,
NULL AS GLOBAL_ATTRIBUTE32,
NULL AS GLOBAL_ATTRIBUTE33,
NULL AS GLOBAL_ATTRIBUTE34,
NULL AS GLOBAL_ATTRIBUTE35,
NULL AS GLOBAL_ATTRIBUTE36,
NULL AS GLOBAL_ATTRIBUTE37,
NULL AS GLOBAL_ATTRIBUTE38,
NULL AS GLOBAL_ATTRIBUTE39,
NULL AS GLOBAL_ATTRIBUTE40,
NULL AS _FIVETRAN_DELETED,
NULL AS _FIVETRAN_ID,
NULL AS _FIVETRAN_SYNCED,
'N' AS PSA_DELETE_IND,
'1900-01-01'::TIMESTAMP AS PSA_LOAD_DTS,
NULL AS PSA_RECORD_SOURCE,
CONVERT_TIMEZONE('UTC','1900-01-01'::TIMESTAMP) AS LOAD_DTS,
'USAZET.SNOWFLAKE.FBIN.DERIVED' AS REC_SRC,
DECODE(GR.VALUE, 0, 'GHOST RECORD-SYSTEM', -1, 'GHOST RECORD-nullkey-required', -2, 'GHOST RECORD-nullkey-optional') AS BKCC,
''::BINARY AS HASHDIFF
FROM
TABLE(strtok_split_to_table('0|-1|-2', '|')) AS GR
{% endif %}
