---- SRC LAYER ----
WITH
SRC_SML            as ( SELECT * FROM {{ ref('v_psa_stg_legal_entity__ml_ebs') }} as SRC 
                         {% if is_incremental() %}
                         WHERE SRC.LOAD_DTS > (SELECT DATEADD('HOUR', '-1', MAX(LOAD_DTS)) FROM {{this}})
                         {% endif %}  )

/*
SRC_SML            as ( SELECT * FROM STAGING.v_psa_stg_legal_entity__ml_ebs )
*/
---- LOGIC LAYER ----

, LOGIC_SML as (
    SELECT
        LEGAL_ENTITY_HK
      , LOAD_DTS
      , ORGANIZATION_ID
      , ATTRIBUTE30
      , BUSINESS_GROUP_ID
      , LAST_UPDATE_DATE
      , PROGRAM_ID
      , INTERNAL_ADDRESS_LINE
      , OBJECT_VERSION_NUMBER
      , ATTRIBUTE29
      , ATTRIBUTE28
      , ATTRIBUTE27
      , ATTRIBUTE26
      , TYPE
      , ATTRIBUTE3
      , CREATED_BY
      , ATTRIBUTE2
      , LAST_UPDATED_BY
      , ATTRIBUTE1
      , INTERNAL_EXTERNAL_FLAG
      , CREATION_DATE
      , ATTRIBUTE9
      , ATTRIBUTE8
      , ATTRIBUTE7
      , ATTRIBUTE6
      , PROGRAM_UPDATE_DATE
      , ATTRIBUTE5
      , NAME
      , ATTRIBUTE4
      , ATTRIBUTE_CATEGORY
      , PROGRAM_APPLICATION_ID
      , PARTY_ID
      , ATTRIBUTE10
      , ATTRIBUTE14
      , ATTRIBUTE13
      , ATTRIBUTE12
      , ATTRIBUTE11
      , REQUEST_ID
      , LOCATION_ID
      , ATTRIBUTE21
      , SOFT_CODING_KEYFLEX_ID
      , COST_ALLOCATION_KEYFLEX_ID
      , ATTRIBUTE20
      , ATTRIBUTE25
      , DATE_FROM
      , ATTRIBUTE24
      , ATTRIBUTE23
      , ATTRIBUTE22
      , LAST_UPDATE_LOGIN
      , ATTRIBUTE18
      , ATTRIBUTE17
      , ATTRIBUTE16
      , ATTRIBUTE15
      , DATE_TO
      , ATTRIBUTE19
      , _FIVETRAN_DELETED
      , _FIVETRAN_SYNCED
      , PSA_LOAD_DTS
      , PSA_DELETE_IND
      , REC_SRC
      , BKCC
      , HASHDIFF
    FROM SRC_SML
)
---- RENAME LAYER ----

, RENAME_SML as (
    SELECT
        LEGAL_ENTITY_HK
      , LOAD_DTS
      , ORGANIZATION_ID
      , ATTRIBUTE30
      , BUSINESS_GROUP_ID
      , LAST_UPDATE_DATE
      , PROGRAM_ID
      , INTERNAL_ADDRESS_LINE
      , OBJECT_VERSION_NUMBER
      , ATTRIBUTE29
      , ATTRIBUTE28
      , ATTRIBUTE27
      , ATTRIBUTE26
      , TYPE
      , ATTRIBUTE3
      , CREATED_BY
      , ATTRIBUTE2
      , LAST_UPDATED_BY
      , ATTRIBUTE1
      , INTERNAL_EXTERNAL_FLAG
      , CREATION_DATE
      , ATTRIBUTE9
      , ATTRIBUTE8
      , ATTRIBUTE7
      , ATTRIBUTE6
      , PROGRAM_UPDATE_DATE
      , ATTRIBUTE5
      , NAME
      , ATTRIBUTE4
      , ATTRIBUTE_CATEGORY
      , PROGRAM_APPLICATION_ID
      , PARTY_ID
      , ATTRIBUTE10
      , ATTRIBUTE14
      , ATTRIBUTE13
      , ATTRIBUTE12
      , ATTRIBUTE11
      , REQUEST_ID
      , LOCATION_ID
      , ATTRIBUTE21
      , SOFT_CODING_KEYFLEX_ID
      , COST_ALLOCATION_KEYFLEX_ID
      , ATTRIBUTE20
      , ATTRIBUTE25
      , DATE_FROM
      , ATTRIBUTE24
      , ATTRIBUTE23
      , ATTRIBUTE22
      , LAST_UPDATE_LOGIN
      , ATTRIBUTE18
      , ATTRIBUTE17
      , ATTRIBUTE16
      , ATTRIBUTE15
      , DATE_TO
      , ATTRIBUTE19
      , _FIVETRAN_DELETED
      , _FIVETRAN_SYNCED
      , PSA_LOAD_DTS
      , PSA_DELETE_IND
      , REC_SRC
      , BKCC
      , HASHDIFF
    FROM LOGIC_SML
)
---- FILTER LAYER ----

, FILTER_SML as (
    SELECT *
    FROM RENAME_SML
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM FILTER_SML
)

---- FINAL LAYER ----
SELECT
          LEGAL_ENTITY_HK
        , LOAD_DTS
        , ORGANIZATION_ID
        , ATTRIBUTE30
        , BUSINESS_GROUP_ID
        , LAST_UPDATE_DATE
        , PROGRAM_ID
        , INTERNAL_ADDRESS_LINE
        , OBJECT_VERSION_NUMBER
        , ATTRIBUTE29
        , ATTRIBUTE28
        , ATTRIBUTE27
        , ATTRIBUTE26
        , TYPE
        , ATTRIBUTE3
        , CREATED_BY
        , ATTRIBUTE2
        , LAST_UPDATED_BY
        , ATTRIBUTE1
        , INTERNAL_EXTERNAL_FLAG
        , CREATION_DATE
        , ATTRIBUTE9
        , ATTRIBUTE8
        , ATTRIBUTE7
        , ATTRIBUTE6
        , PROGRAM_UPDATE_DATE
        , ATTRIBUTE5
        , NAME
        , ATTRIBUTE4
        , ATTRIBUTE_CATEGORY
        , PROGRAM_APPLICATION_ID
        , PARTY_ID
        , ATTRIBUTE10
        , ATTRIBUTE14
        , ATTRIBUTE13
        , ATTRIBUTE12
        , ATTRIBUTE11
        , REQUEST_ID
        , LOCATION_ID
        , ATTRIBUTE21
        , SOFT_CODING_KEYFLEX_ID
        , COST_ALLOCATION_KEYFLEX_ID
        , ATTRIBUTE20
        , ATTRIBUTE25
        , DATE_FROM
        , ATTRIBUTE24
        , ATTRIBUTE23
        , ATTRIBUTE22
        , LAST_UPDATE_LOGIN
        , ATTRIBUTE18
        , ATTRIBUTE17
        , ATTRIBUTE16
        , ATTRIBUTE15
        , DATE_TO
        , ATTRIBUTE19
        , _FIVETRAN_DELETED
        , _FIVETRAN_SYNCED
        , PSA_LOAD_DTS
        , PSA_DELETE_IND
        , REC_SRC
        , BKCC
        , HASHDIFF
FROM JOIN_RESULT
{% if is_incremental() %}
WHERE NOT EXISTS (
    SELECT 1 
    FROM {{ this }} existing
    WHERE existing.LEGAL_ENTITY_HK = JOIN_RESULT.LEGAL_ENTITY_HK 
    AND existing.HASHDIFF = JOIN_RESULT.HASHDIFF
)
{% endif %} 


{% if not is_incremental() %}
/* The following qualifier is implemented to prevent multiple loads of touched records during the initial build, such as multiple rows per HK and hashdiff. */
qualify 1= row_number()over(partition by LEGAL_ENTITY_HK, HASHDIFF order by PSA_LOAD_DTS)

union all
    SELECT 
    MD5_BINARY(GR.VALUE) LEGAL_ENTITY_HK
, CONVERT_TIMEZONE('UTC','1900-01-01'::TIMESTAMP) as LOAD_DTS
, GR.VALUE::NUMBER AS ORGANIZATION_ID
, NULL AS ATTRIBUTE30
, NULL AS BUSINESS_GROUP_ID
, NULL AS LAST_UPDATE_DATE
, NULL AS PROGRAM_ID
, NULL AS INTERNAL_ADDRESS_LINE
, NULL AS OBJECT_VERSION_NUMBER
, NULL AS ATTRIBUTE29
, NULL AS ATTRIBUTE28
, NULL AS ATTRIBUTE27
, NULL AS ATTRIBUTE26
, NULL AS TYPE
, NULL AS ATTRIBUTE3
, NULL AS CREATED_BY
, NULL AS ATTRIBUTE2
, NULL AS LAST_UPDATED_BY
, NULL AS ATTRIBUTE1
, NULL AS INTERNAL_EXTERNAL_FLAG
, NULL AS CREATION_DATE
, NULL AS ATTRIBUTE9
, NULL AS ATTRIBUTE8
, NULL AS ATTRIBUTE7
, NULL AS ATTRIBUTE6
, NULL AS PROGRAM_UPDATE_DATE
, NULL AS ATTRIBUTE5
, NULL AS NAME
, NULL AS ATTRIBUTE4
, NULL AS ATTRIBUTE_CATEGORY
, NULL AS PROGRAM_APPLICATION_ID
, NULL AS PARTY_ID
, NULL AS ATTRIBUTE10
, NULL AS ATTRIBUTE14
, NULL AS ATTRIBUTE13
, NULL AS ATTRIBUTE12
, NULL AS ATTRIBUTE11
, NULL AS REQUEST_ID
, NULL AS LOCATION_ID
, NULL AS ATTRIBUTE21
, NULL AS SOFT_CODING_KEYFLEX_ID
, NULL AS COST_ALLOCATION_KEYFLEX_ID
, NULL AS ATTRIBUTE20
, NULL AS ATTRIBUTE25
, NULL AS DATE_FROM
, NULL AS ATTRIBUTE24
, NULL AS ATTRIBUTE23
, NULL AS ATTRIBUTE22
, NULL AS LAST_UPDATE_LOGIN
, NULL AS ATTRIBUTE18
, NULL AS ATTRIBUTE17
, NULL AS ATTRIBUTE16
, NULL AS ATTRIBUTE15
, NULL AS DATE_TO
, NULL AS ATTRIBUTE19
, NULL AS _FIVETRAN_DELETED
, NULL AS _FIVETRAN_SYNCED
, '1900-01-01'::TIMESTAMP AS PSA_LOAD_DTS
, 'N' AS PSA_DELETE_IND
, 'USAZET.SNOWFLAKE.FBIN.DERIVED' AS REC_SRC
, DECODE(GR.VALUE, 0, 'GHOST RECORD-SYSTEM', -1, 'GHOST RECORD-nullkey-required', -2, 'GHOST RECORD-nullkey-optional')  AS  BKCC
, ''::BINARY as HASHDIFF
FROM
TABLE(strtok_split_to_table('0|-1|-2', '|')) AS GR
{% endif %}