---- SRC LAYER ----
WITH
SRC_SRC            as ( SELECT * FROM {{ ref('v_psa_stg_supplier_invoice__ml_ebs') }} as SRC 
{% if is_incremental() %}
      where src.load_dts > (select dateadd('HOUR',-1,max(load_dts)) from {{ this }})
    {% endif %} )

/*
SRC_SRC            as ( SELECT * FROM int_staging_views.v_psa_stg_supplier_invoice__ml_ebs )
*/
---- LOGIC LAYER ----

, LOGIC_SRC as (
    SELECT
        SUPPLIER_INVOICE_HK
      , INVOICE_ID
      , HISTORICAL_FLAG
      , FREIGHT_AMOUNT
      , PAYMENT_STATUS_FLAG
      , APPROVAL_ITERATION
      , INVOICE_DATE
      , TAX_AMOUNT
      , QUICK_PO_HEADER_ID
      , DISPUTE_REASON
      , ATTRIBUTE3
      , ATTRIBUTE2
      , ATTRIBUTE1
      , AUTHORIZED_BY
      , PARTY_SITE_ID
      , ATTRIBUTE9
      , ATTRIBUTE8
      , ATTRIBUTE7
      , PAY_PROC_TRXN_TYPE_CODE
      , GL_DATE
      , ATTRIBUTE6
      , MRC_EXCHANGE_RATE_TYPE
      , ATTRIBUTE5
      , VENDOR_ID
      , ATTRIBUTE4
      , SUPPLIER_TAX_INVOICE_DATE
      , INVOICE_NUM
      , SOURCE
      , ATTRIBUTE10
      , EXCLUSIVE_PAYMENT_FLAG
      , SETTLEMENT_PRIORITY
      , ATTRIBUTE14
      , ATTRIBUTE13
      , ATTRIBUTE12
      , ATTRIBUTE11
      , UNIQUE_REMITTANCE_IDENTIFIER
      , APPROVAL_STATUS
      , TOTAL_TAX_AMOUNT
      , EXTERNAL_BANK_ACCOUNT_ID
      , NET_OF_RETAINAGE_FLAG
      , DESCRIPTION
      , MRC_EXCHANGE_DATE
      , APPROVAL_DESCRIPTION
      , APPROVAL_READY_FLAG
      , RECURRING_PAYMENT_ID
      , SUPPLIER_TAX_EXCHANGE_RATE
      , CANCELLED_AMOUNT
      , REMIT_TO_SUPPLIER_SITE_ID
      , INVOICE_AMOUNT
      , WFAPPROVAL_STATUS
      , ATTRIBUTE15
      , INVOICE_CURRENCY_CODE
      , CUST_REGISTRATION_NUMBER
      , DISTRIBUTION_SET_ID
      , DOCUMENT_SUB_TYPE
      , PA_QUANTITY
      , GLOBAL_ATTRIBUTE10
      , PORT_OF_ENTRY_CODE
      , INVOICE_TYPE_LOOKUP_CODE
      , PROJECT_ACCOUNTING_CONTEXT
      , LAST_UPDATED_BY
      , USER_DEFINED_FISC_CLASS
      , TERMS_ID
      , PAYMENT_AMOUNT_TOTAL
      , PAYMENT_CROSS_RATE_TYPE
      , AUTO_TAX_CALC_FLAG
      , EXCLUDE_FREIGHT_FROM_DISCOUNT
      , PARTY_ID
      , PAY_AWT_GROUP_ID
      , PAYMENT_FUNCTION
      , PRODUCT_TABLE
      , SET_OF_BOOKS_ID
      , BANK_CHARGE_BEARER
      , VENDOR_SITE_ID
      , PAYMENT_METHOD_LOOKUP_CODE
      , PAYMENT_CROSS_RATE_DATE
      , DOC_SEQUENCE_VALUE
      , REFERENCE_KEY1
      , DELIVERY_CHANNEL_CODE
      , REFERENCE_KEY2
      , REFERENCE_KEY3
      , REFERENCE_KEY4
      , REFERENCE_KEY5
      , GLOBAL_ATTRIBUTE_CATEGORY
      , QUICK_CREDIT
      , DOC_SEQUENCE_ID
      , APPROVED_AMOUNT
      , INTERNAL_CONTACT_EMAIL
      , REQUESTER_ID
      , URI_CHECK_DIGIT
      , ORG_ID
      , PAID_ON_BEHALF_EMPLOYEE_ID
      , PAYMENT_CROSS_RATE
      , AMOUNT_APPLICABLE_TO_DISCOUNT
      , TRX_BUSINESS_CATEGORY
      , GLOBAL_ATTRIBUTE5
      , GLOBAL_ATTRIBUTE4
      , REMIT_TO_SUPPLIER_SITE
      , GLOBAL_ATTRIBUTE7
      , VALIDATION_WORKER_ID
      , GLOBAL_ATTRIBUTE6
      , PAYMENT_METHOD_CODE
      , GLOBAL_ATTRIBUTE1
      , GLOBAL_ATTRIBUTE3
      , GLOBAL_ATTRIBUTE2
      , AWT_GROUP_ID
      , GLOBAL_ATTRIBUTE9
      , GLOBAL_ATTRIBUTE8
      , USSGL_TRANSACTION_CODE
      , DOC_CATEGORY_CODE
      , AWT_FLAG
      , CUST_REGISTRATION_CODE
      , TEMP_CANCELLED_AMOUNT
      , PREPAY_FLAG
      , ACCTS_PAY_CODE_COMBINATION_ID
      , TASK_ID
      , REFERENCE_1
      , REFERENCE_2
      , REMITTANCE_MESSAGE3
      , REMITTANCE_MESSAGE2
      , SUPPLIER_TAX_INVOICE_NUMBER
      , REMITTANCE_MESSAGE1
      , EXPENDITURE_TYPE
      , INVOICE_DISTRIBUTION_TOTAL
      , MRC_EXCHANGE_RATE
      , PROJECT_ID
      , VOUCHER_NUM
      , RELEASE_AMOUNT_NET_OF_TAX
      , GLOBAL_ATTRIBUTE20
      , TAX_RELATED_INVOICE_ID
      , USSGL_TRX_CODE_CONTEXT
      , TERMS_DATE
      , GLOBAL_ATTRIBUTE17
      , GLOBAL_ATTRIBUTE18
      , GLOBAL_ATTRIBUTE15
      , GLOBAL_ATTRIBUTE16
      , GLOBAL_ATTRIBUTE13
      , PO_HEADER_ID
      , GLOBAL_ATTRIBUTE14
      , PRE_WITHHOLDING_AMOUNT
      , GLOBAL_ATTRIBUTE11
      , AMT_DUE_EMPLOYEE
      , FORCE_REVALIDATION_FLAG
      , GLOBAL_ATTRIBUTE12
      , CONTROL_AMOUNT
      , GLOBAL_ATTRIBUTE19
      , MRC_BASE_AMOUNT
      , ORIGINAL_PREPAYMENT_AMOUNT
      , VENDOR_CONTACT_ID
      , EXPENDITURE_ORGANIZATION_ID
      , EXCHANGE_DATE
      , CREATED_BY
      , REMIT_TO_SUPPLIER_ID
      , AWARD_ID
      , SELF_ASSESSED_TAX_AMOUNT
      , CANCELLED_BY
      , LEGAL_ENTITY_ID
      , DISC_IS_INV_LESS_TAX_FLAG
      , DISCOUNT_AMOUNT_TAKEN
      , VAT_CODE
      , ATTRIBUTE_CATEGORY
      , AMOUNT_PAID
      , VENDOR_PREPAY_AMOUNT
      , PAYMENT_REASON_COMMENTS
      , PAY_CURR_INVOICE_AMOUNT
      , CREDITED_INVOICE_ID
      , BASE_AMOUNT
      , EXPENDITURE_ITEM_DATE
      , ORIGINAL_INVOICE_AMOUNT
      , APPLICATION_ID
      , BATCH_ID
      , TAX_INVOICE_INTERNAL_SEQ
      , PAYMENT_CURRENCY_CODE
      , EXCHANGE_RATE_TYPE
      , POSTING_STATUS
      , VALIDATED_TAX_AMOUNT
      , PAYMENT_REASON_CODE
      , REMIT_TO_SUPPLIER_NAME
      , LAST_UPDATE_LOGIN
      , PO_MATCHED_FLAG
      , TAXATION_COUNTRY
      , VALIDATION_REQUEST_ID
      , RELATIONSHIP_ID
      , AMT_DUE_CCARD_COMPANY
      , PA_DEFAULT_DIST_CCID
      , PAY_GROUP_LOOKUP_CODE
      , TAX_INVOICE_RECORDING_DATE
      , INVOICE_RECEIVED_DATE
      , EXCHANGE_RATE
      , CANCELLED_DATE
      , CREATION_DATE
      , GOODS_RECEIVED_DATE
      , LAST_UPDATE_DATE
      , EARLIEST_SETTLEMENT_DATE
      , PSA_DELETE_IND
      , PSA_LOAD_DTS
      , PSA_RECORD_SOURCE
      , _FIVETRAN_SYNCED
      , _FIVETRAN_ID
      , _FIVETRAN_DELETED
      , LOAD_DTS
      , REC_SRC
      , BKCC
      , HASHDIFF
    FROM SRC_SRC
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM LOGIC_SRC
)

---- FINAL LAYER ----
SELECT
          SUPPLIER_INVOICE_HK
        , INVOICE_ID
        , HISTORICAL_FLAG
        , FREIGHT_AMOUNT
        , PAYMENT_STATUS_FLAG
        , APPROVAL_ITERATION
        , INVOICE_DATE
        , TAX_AMOUNT
        , QUICK_PO_HEADER_ID
        , DISPUTE_REASON
        , ATTRIBUTE3
        , ATTRIBUTE2
        , ATTRIBUTE1
        , AUTHORIZED_BY
        , PARTY_SITE_ID
        , ATTRIBUTE9
        , ATTRIBUTE8
        , ATTRIBUTE7
        , PAY_PROC_TRXN_TYPE_CODE
        , GL_DATE
        , ATTRIBUTE6
        , MRC_EXCHANGE_RATE_TYPE
        , ATTRIBUTE5
        , VENDOR_ID
        , ATTRIBUTE4
        , SUPPLIER_TAX_INVOICE_DATE
        , INVOICE_NUM
        , SOURCE
        , ATTRIBUTE10
        , EXCLUSIVE_PAYMENT_FLAG
        , SETTLEMENT_PRIORITY
        , ATTRIBUTE14
        , ATTRIBUTE13
        , ATTRIBUTE12
        , ATTRIBUTE11
        , UNIQUE_REMITTANCE_IDENTIFIER
        , APPROVAL_STATUS
        , TOTAL_TAX_AMOUNT
        , EXTERNAL_BANK_ACCOUNT_ID
        , NET_OF_RETAINAGE_FLAG
        , DESCRIPTION
        , MRC_EXCHANGE_DATE
        , APPROVAL_DESCRIPTION
        , APPROVAL_READY_FLAG
        , RECURRING_PAYMENT_ID
        , SUPPLIER_TAX_EXCHANGE_RATE
        , CANCELLED_AMOUNT
        , REMIT_TO_SUPPLIER_SITE_ID
        , INVOICE_AMOUNT
        , WFAPPROVAL_STATUS
        , ATTRIBUTE15
        , INVOICE_CURRENCY_CODE
        , CUST_REGISTRATION_NUMBER
        , DISTRIBUTION_SET_ID
        , DOCUMENT_SUB_TYPE
        , PA_QUANTITY
        , GLOBAL_ATTRIBUTE10
        , PORT_OF_ENTRY_CODE
        , INVOICE_TYPE_LOOKUP_CODE
        , PROJECT_ACCOUNTING_CONTEXT
        , LAST_UPDATED_BY
        , USER_DEFINED_FISC_CLASS
        , TERMS_ID
        , PAYMENT_AMOUNT_TOTAL
        , PAYMENT_CROSS_RATE_TYPE
        , AUTO_TAX_CALC_FLAG
        , EXCLUDE_FREIGHT_FROM_DISCOUNT
        , PARTY_ID
        , PAY_AWT_GROUP_ID
        , PAYMENT_FUNCTION
        , PRODUCT_TABLE
        , SET_OF_BOOKS_ID
        , BANK_CHARGE_BEARER
        , VENDOR_SITE_ID
        , PAYMENT_METHOD_LOOKUP_CODE
        , PAYMENT_CROSS_RATE_DATE
        , DOC_SEQUENCE_VALUE
        , REFERENCE_KEY1
        , DELIVERY_CHANNEL_CODE
        , REFERENCE_KEY2
        , REFERENCE_KEY3
        , REFERENCE_KEY4
        , REFERENCE_KEY5
        , GLOBAL_ATTRIBUTE_CATEGORY
        , QUICK_CREDIT
        , DOC_SEQUENCE_ID
        , APPROVED_AMOUNT
        , INTERNAL_CONTACT_EMAIL
        , REQUESTER_ID
        , URI_CHECK_DIGIT
        , ORG_ID
        , PAID_ON_BEHALF_EMPLOYEE_ID
        , PAYMENT_CROSS_RATE
        , AMOUNT_APPLICABLE_TO_DISCOUNT
        , TRX_BUSINESS_CATEGORY
        , GLOBAL_ATTRIBUTE5
        , GLOBAL_ATTRIBUTE4
        , REMIT_TO_SUPPLIER_SITE
        , GLOBAL_ATTRIBUTE7
        , VALIDATION_WORKER_ID
        , GLOBAL_ATTRIBUTE6
        , PAYMENT_METHOD_CODE
        , GLOBAL_ATTRIBUTE1
        , GLOBAL_ATTRIBUTE3
        , GLOBAL_ATTRIBUTE2
        , AWT_GROUP_ID
        , GLOBAL_ATTRIBUTE9
        , GLOBAL_ATTRIBUTE8
        , USSGL_TRANSACTION_CODE
        , DOC_CATEGORY_CODE
        , AWT_FLAG
        , CUST_REGISTRATION_CODE
        , TEMP_CANCELLED_AMOUNT
        , PREPAY_FLAG
        , ACCTS_PAY_CODE_COMBINATION_ID
        , TASK_ID
        , REFERENCE_1
        , REFERENCE_2
        , REMITTANCE_MESSAGE3
        , REMITTANCE_MESSAGE2
        , SUPPLIER_TAX_INVOICE_NUMBER
        , REMITTANCE_MESSAGE1
        , EXPENDITURE_TYPE
        , INVOICE_DISTRIBUTION_TOTAL
        , MRC_EXCHANGE_RATE
        , PROJECT_ID
        , VOUCHER_NUM
        , RELEASE_AMOUNT_NET_OF_TAX
        , GLOBAL_ATTRIBUTE20
        , TAX_RELATED_INVOICE_ID
        , USSGL_TRX_CODE_CONTEXT
        , TERMS_DATE
        , GLOBAL_ATTRIBUTE17
        , GLOBAL_ATTRIBUTE18
        , GLOBAL_ATTRIBUTE15
        , GLOBAL_ATTRIBUTE16
        , GLOBAL_ATTRIBUTE13
        , PO_HEADER_ID
        , GLOBAL_ATTRIBUTE14
        , PRE_WITHHOLDING_AMOUNT
        , GLOBAL_ATTRIBUTE11
        , AMT_DUE_EMPLOYEE
        , FORCE_REVALIDATION_FLAG
        , GLOBAL_ATTRIBUTE12
        , CONTROL_AMOUNT
        , GLOBAL_ATTRIBUTE19
        , MRC_BASE_AMOUNT
        , ORIGINAL_PREPAYMENT_AMOUNT
        , VENDOR_CONTACT_ID
        , EXPENDITURE_ORGANIZATION_ID
        , EXCHANGE_DATE
        , CREATED_BY
        , REMIT_TO_SUPPLIER_ID
        , AWARD_ID
        , SELF_ASSESSED_TAX_AMOUNT
        , CANCELLED_BY
        , LEGAL_ENTITY_ID
        , DISC_IS_INV_LESS_TAX_FLAG
        , DISCOUNT_AMOUNT_TAKEN
        , VAT_CODE
        , ATTRIBUTE_CATEGORY
        , AMOUNT_PAID
        , VENDOR_PREPAY_AMOUNT
        , PAYMENT_REASON_COMMENTS
        , PAY_CURR_INVOICE_AMOUNT
        , CREDITED_INVOICE_ID
        , BASE_AMOUNT
        , EXPENDITURE_ITEM_DATE
        , ORIGINAL_INVOICE_AMOUNT
        , APPLICATION_ID
        , BATCH_ID
        , TAX_INVOICE_INTERNAL_SEQ
        , PAYMENT_CURRENCY_CODE
        , EXCHANGE_RATE_TYPE
        , POSTING_STATUS
        , VALIDATED_TAX_AMOUNT
        , PAYMENT_REASON_CODE
        , REMIT_TO_SUPPLIER_NAME
        , LAST_UPDATE_LOGIN
        , PO_MATCHED_FLAG
        , TAXATION_COUNTRY
        , VALIDATION_REQUEST_ID
        , RELATIONSHIP_ID
        , AMT_DUE_CCARD_COMPANY
        , PA_DEFAULT_DIST_CCID
        , PAY_GROUP_LOOKUP_CODE
        , TAX_INVOICE_RECORDING_DATE
        , INVOICE_RECEIVED_DATE
        , EXCHANGE_RATE
        , CANCELLED_DATE
        , CREATION_DATE
        , GOODS_RECEIVED_DATE
        , LAST_UPDATE_DATE
        , EARLIEST_SETTLEMENT_DATE
        , PSA_DELETE_IND
        , PSA_LOAD_DTS
        , PSA_RECORD_SOURCE
        , _FIVETRAN_SYNCED
        , _FIVETRAN_ID
        , _FIVETRAN_DELETED
        , LOAD_DTS
        , REC_SRC
        , BKCC
        , HASHDIFF
FROM JOIN_RESULT
{% if is_incremental() %}
WHERE NOT EXISTS (
    SELECT 1
    FROM {{ this }} existing
    WHERE existing.SUPPLIER_INVOICE_HK = JOIN_RESULT.SUPPLIER_INVOICE_HK
      AND existing.HASHDIFF = JOIN_RESULT.HASHDIFF
)
{% endif %}
{% if not is_incremental() %}

/* The following qualifier is implemented to prevent multiple loads of touched records during the initial build, such as multiple rows per HK and hashdiff. */
qualify 1 = row_number() over (partition by SUPPLIER_INVOICE_HK, HASHDIFF order by PSA_LOAD_DTS)

union all
SELECT 
MD5_BINARY(GR.VALUE) AS SUPPLIER_INVOICE_HK,
NULL AS INVOICE_ID,
NULL AS HISTORICAL_FLAG,
NULL AS FREIGHT_AMOUNT,
NULL AS PAYMENT_STATUS_FLAG,
NULL AS APPROVAL_ITERATION,
NULL AS INVOICE_DATE,
NULL AS TAX_AMOUNT,
NULL AS QUICK_PO_HEADER_ID,
NULL AS DISPUTE_REASON,
NULL AS ATTRIBUTE3,
NULL AS ATTRIBUTE2,
NULL AS ATTRIBUTE1,
NULL AS AUTHORIZED_BY,
NULL AS PARTY_SITE_ID,
NULL AS ATTRIBUTE9,
NULL AS ATTRIBUTE8,
NULL AS ATTRIBUTE7,
NULL AS PAY_PROC_TRXN_TYPE_CODE,
NULL AS GL_DATE,
NULL AS ATTRIBUTE6,
NULL AS MRC_EXCHANGE_RATE_TYPE,
NULL AS ATTRIBUTE5,
NULL AS VENDOR_ID,
NULL AS ATTRIBUTE4,
NULL AS SUPPLIER_TAX_INVOICE_DATE,
NULL AS INVOICE_NUM,
NULL AS SOURCE,
NULL AS ATTRIBUTE10,
NULL AS EXCLUSIVE_PAYMENT_FLAG,
NULL AS SETTLEMENT_PRIORITY,
NULL AS ATTRIBUTE14,
NULL AS ATTRIBUTE13,
NULL AS ATTRIBUTE12,
NULL AS ATTRIBUTE11,
NULL AS UNIQUE_REMITTANCE_IDENTIFIER,
NULL AS APPROVAL_STATUS,
NULL AS TOTAL_TAX_AMOUNT,
NULL AS EXTERNAL_BANK_ACCOUNT_ID,
NULL AS NET_OF_RETAINAGE_FLAG,
NULL AS DESCRIPTION,
NULL AS MRC_EXCHANGE_DATE,
NULL AS APPROVAL_DESCRIPTION,
NULL AS APPROVAL_READY_FLAG,
NULL AS RECURRING_PAYMENT_ID,
NULL AS SUPPLIER_TAX_EXCHANGE_RATE,
NULL AS CANCELLED_AMOUNT,
NULL AS REMIT_TO_SUPPLIER_SITE_ID,
NULL AS INVOICE_AMOUNT,
NULL AS WFAPPROVAL_STATUS,
NULL AS ATTRIBUTE15,
NULL AS INVOICE_CURRENCY_CODE,
NULL AS CUST_REGISTRATION_NUMBER,
NULL AS DISTRIBUTION_SET_ID,
NULL AS DOCUMENT_SUB_TYPE,
NULL AS PA_QUANTITY,
NULL AS GLOBAL_ATTRIBUTE10,
NULL AS PORT_OF_ENTRY_CODE,
NULL AS INVOICE_TYPE_LOOKUP_CODE,
NULL AS PROJECT_ACCOUNTING_CONTEXT,
NULL AS LAST_UPDATED_BY,
NULL AS USER_DEFINED_FISC_CLASS,
NULL AS TERMS_ID,
NULL AS PAYMENT_AMOUNT_TOTAL,
NULL AS PAYMENT_CROSS_RATE_TYPE,
NULL AS AUTO_TAX_CALC_FLAG,
NULL AS EXCLUDE_FREIGHT_FROM_DISCOUNT,
NULL AS PARTY_ID,
NULL AS PAY_AWT_GROUP_ID,
NULL AS PAYMENT_FUNCTION,
NULL AS PRODUCT_TABLE,
NULL AS SET_OF_BOOKS_ID,
NULL AS BANK_CHARGE_BEARER,
NULL AS VENDOR_SITE_ID,
NULL AS PAYMENT_METHOD_LOOKUP_CODE,
NULL AS PAYMENT_CROSS_RATE_DATE,
NULL AS DOC_SEQUENCE_VALUE,
NULL AS REFERENCE_KEY1,
NULL AS DELIVERY_CHANNEL_CODE,
NULL AS REFERENCE_KEY2,
NULL AS REFERENCE_KEY3,
NULL AS REFERENCE_KEY4,
NULL AS REFERENCE_KEY5,
NULL AS GLOBAL_ATTRIBUTE_CATEGORY,
NULL AS QUICK_CREDIT,
NULL AS DOC_SEQUENCE_ID,
NULL AS APPROVED_AMOUNT,
NULL AS INTERNAL_CONTACT_EMAIL,
NULL AS REQUESTER_ID,
NULL AS URI_CHECK_DIGIT,
NULL AS ORG_ID,
NULL AS PAID_ON_BEHALF_EMPLOYEE_ID,
NULL AS PAYMENT_CROSS_RATE,
NULL AS AMOUNT_APPLICABLE_TO_DISCOUNT,
NULL AS TRX_BUSINESS_CATEGORY,
NULL AS GLOBAL_ATTRIBUTE5,
NULL AS GLOBAL_ATTRIBUTE4,
NULL AS REMIT_TO_SUPPLIER_SITE,
NULL AS GLOBAL_ATTRIBUTE7,
NULL AS VALIDATION_WORKER_ID,
NULL AS GLOBAL_ATTRIBUTE6,
NULL AS PAYMENT_METHOD_CODE,
NULL AS GLOBAL_ATTRIBUTE1,
NULL AS GLOBAL_ATTRIBUTE3,
NULL AS GLOBAL_ATTRIBUTE2,
NULL AS AWT_GROUP_ID,
NULL AS GLOBAL_ATTRIBUTE9,
NULL AS GLOBAL_ATTRIBUTE8,
NULL AS USSGL_TRANSACTION_CODE,
NULL AS DOC_CATEGORY_CODE,
NULL AS AWT_FLAG,
NULL AS CUST_REGISTRATION_CODE,
NULL AS TEMP_CANCELLED_AMOUNT,
NULL AS PREPAY_FLAG,
NULL AS ACCTS_PAY_CODE_COMBINATION_ID,
NULL AS TASK_ID,
NULL AS REFERENCE_1,
NULL AS REFERENCE_2,
NULL AS REMITTANCE_MESSAGE3,
NULL AS REMITTANCE_MESSAGE2,
NULL AS SUPPLIER_TAX_INVOICE_NUMBER,
NULL AS REMITTANCE_MESSAGE1,
NULL AS EXPENDITURE_TYPE,
NULL AS INVOICE_DISTRIBUTION_TOTAL,
NULL AS MRC_EXCHANGE_RATE,
NULL AS PROJECT_ID,
NULL AS VOUCHER_NUM,
NULL AS RELEASE_AMOUNT_NET_OF_TAX,
NULL AS GLOBAL_ATTRIBUTE20,
NULL AS TAX_RELATED_INVOICE_ID,
NULL AS USSGL_TRX_CODE_CONTEXT,
NULL AS TERMS_DATE,
NULL AS GLOBAL_ATTRIBUTE17,
NULL AS GLOBAL_ATTRIBUTE18,
NULL AS GLOBAL_ATTRIBUTE15,
NULL AS GLOBAL_ATTRIBUTE16,
NULL AS GLOBAL_ATTRIBUTE13,
NULL AS PO_HEADER_ID,
NULL AS GLOBAL_ATTRIBUTE14,
NULL AS PRE_WITHHOLDING_AMOUNT,
NULL AS GLOBAL_ATTRIBUTE11,
NULL AS AMT_DUE_EMPLOYEE,
NULL AS FORCE_REVALIDATION_FLAG,
NULL AS GLOBAL_ATTRIBUTE12,
NULL AS CONTROL_AMOUNT,
NULL AS GLOBAL_ATTRIBUTE19,
NULL AS MRC_BASE_AMOUNT,
NULL AS ORIGINAL_PREPAYMENT_AMOUNT,
NULL AS VENDOR_CONTACT_ID,
NULL AS EXPENDITURE_ORGANIZATION_ID,
NULL AS EXCHANGE_DATE,
NULL AS CREATED_BY,
NULL AS REMIT_TO_SUPPLIER_ID,
NULL AS AWARD_ID,
NULL AS SELF_ASSESSED_TAX_AMOUNT,
NULL AS CANCELLED_BY,
NULL AS LEGAL_ENTITY_ID,
NULL AS DISC_IS_INV_LESS_TAX_FLAG,
NULL AS DISCOUNT_AMOUNT_TAKEN,
NULL AS VAT_CODE,
NULL AS ATTRIBUTE_CATEGORY,
NULL AS AMOUNT_PAID,
NULL AS VENDOR_PREPAY_AMOUNT,
NULL AS PAYMENT_REASON_COMMENTS,
NULL AS PAY_CURR_INVOICE_AMOUNT,
NULL AS CREDITED_INVOICE_ID,
NULL AS BASE_AMOUNT,
NULL AS EXPENDITURE_ITEM_DATE,
NULL AS ORIGINAL_INVOICE_AMOUNT,
NULL AS APPLICATION_ID,
NULL AS BATCH_ID,
NULL AS TAX_INVOICE_INTERNAL_SEQ,
NULL AS PAYMENT_CURRENCY_CODE,
NULL AS EXCHANGE_RATE_TYPE,
NULL AS POSTING_STATUS,
NULL AS VALIDATED_TAX_AMOUNT,
NULL AS PAYMENT_REASON_CODE,
NULL AS REMIT_TO_SUPPLIER_NAME,
NULL AS LAST_UPDATE_LOGIN,
NULL AS PO_MATCHED_FLAG,
NULL AS TAXATION_COUNTRY,
NULL AS VALIDATION_REQUEST_ID,
NULL AS RELATIONSHIP_ID,
NULL AS AMT_DUE_CCARD_COMPANY,
NULL AS PA_DEFAULT_DIST_CCID,
NULL AS PAY_GROUP_LOOKUP_CODE,
NULL AS TAX_INVOICE_RECORDING_DATE,
NULL AS INVOICE_RECEIVED_DATE,
NULL AS EXCHANGE_RATE,
NULL AS CANCELLED_DATE,
NULL AS CREATION_DATE,
NULL AS GOODS_RECEIVED_DATE,
NULL AS LAST_UPDATE_DATE,
NULL AS EARLIEST_SETTLEMENT_DATE,
'N' AS PSA_DELETE_IND,
'1900-01-01'::TIMESTAMP AS PSA_LOAD_DTS,
NULL AS PSA_RECORD_SOURCE,
NULL AS _FIVETRAN_SYNCED,
NULL AS _FIVETRAN_ID,
NULL AS _FIVETRAN_DELETED,
'1900-01-01T00:00:00'::TIMESTAMP_NTZ AS LOAD_DTS,
'USAZET.SNOWFLAKE.FBIN.DERIVED' AS REC_SRC,
DECODE(GR.VALUE, 0, 'GHOST RECORD-SYSTEM', -1, 'GHOST RECORD-nullkey-required', -2, 'GHOST RECORD-nullkey-optional') AS BKCC,
MD5_BINARY('') AS HASHDIFF
FROM
TABLE(strtok_split_to_table('0|-1|-2', '|')) AS GR
{% endif %}
