---- SRC LAYER ----
WITH
SRC_SITMFB         as ( SELECT * FROM {{ ref('v_psa_stg_item_attributes__fib_ocf') }} as SRC 
                         {% if is_incremental() %}
                         WHERE SRC.LOAD_DTS > (SELECT DATEADD('HOUR', '-1', MAX(LOAD_DTS)) FROM {{this}})
                         {% endif %}  )

/*
SRC_SITMFB         as ( SELECT * FROM STAGING.v_psa_stg_ITEM_attributes__fib_ocf )
*/
---- LOGIC LAYER ----

, LOGIC_SITMFB as (
    SELECT
        ITEM_HK
      , INVENTORY_ITEM_ID
      , ORGANIZATION_ID
      , EFF_LINE_ID
      , CHANGE_LINE_ID
      , VERSION_START_DATE
      , ATTRIBUTE_CHAR_25
      , ATTRIBUTE_NUMBER_2_UOM
      , ATTRIBUTE_CHAR_37
      , ATTRIBUTE_CHAR_39
      , ATTRIBUTE_CHAR_11
      , ATTRIBUTE_NUMBER_12
      , ATTRIBUTE_DATE_4
      , ATTRIBUTE_NUMBER_14
      , ATTRIBUTE_CHAR_24
      , ATTRIBUTE_DATE_3
      , ATTRIBUTE_NUMBER_18
      , ATTRIBUTE_CHAR_5
      , ATTRIBUTE_CHAR_12
      , ATTRIBUTE_NUMBER_20_UOM
      , ACD_TYPE
      , ATTRIBUTE_DATE_2
      , ATTRIBUTE_TIMESTAMP_2
      , ATTRIBUTE_CHAR_27
      , ATTRIBUTE_CHAR_13
      , ATTRIBUTE_NUMBER_16
      , ATTRIBUTE_NUMBER_2
      , ATTRIBUTE_NUMBER_7
      , ATTRIBUTE_CHAR_9
      , ATTRIBUTE_CHAR_30
      , ATTRIBUTE_NUMBER_18_UOM
      , ATTRIBUTE_NUMBER_10
      , ATTRIBUTE_CHAR_8
      , ATTRIBUTE_CHAR_15
      , ATTRIBUTE_CHAR_26
      , ATTRIBUTE_TIMESTAMP_9
      , ATTRIBUTE_CHAR_2
      , ATTRIBUTE_CHAR_29
      , CONTEXT_CODE
      , ATTRIBUTE_NUMBER_1_UOM
      , ATTRIBUTE_NUMBER_17_UOM
      , ATTRIBUTE_NUMBER_1
      , ATTRIBUTE_NUMBER_19_UOM
      , ATTRIBUTE_NUMBER_6_UOM
      , ATTRIBUTE_NUMBER_10_UOM
      , ATTRIBUTE_NUMBER_5
      , ATTRIBUTE_NUMBER_7_UOM
      , ATTRIBUTE_NUMBER_11
      , CATEGORY_CODE
      , ATTRIBUTE_NUMBER_14_UOM
      , IMPLEMENTATION_DATE
      , ATTRIBUTE_NUMBER_17
      , ATTRIBUTE_CHAR_33
      , ATTRIBUTE_DATE_10
      , ATTRIBUTE_NUMBER_8_UOM
      , ATTRIBUTE_CHAR_23
      , ATTRIBUTE_DATE_6
      , ATTRIBUTE_DATE_7
      , CHANGE_BIT_MAP
      , ATTRIBUTE_NUMBER_4_UOM
      , ATTRIBUTE_CHAR_1
      , ATTRIBUTE_CHAR_34
      , ATTRIBUTE_NUMBER_16_UOM
      , ATTRIBUTE_CHAR_28
      , ATTRIBUTE_NUMBER_3
      , ATTRIBUTE_CHAR_6
      , ATTRIBUTE_CHAR_22
      , ATTRIBUTE_CHAR_35
      , ATTRIBUTE_CHAR_36
      , CREATED_BY
      , ATTRIBUTE_NUMBER_9
      , ATTRIBUTE_CHAR_38
      , ATTRIBUTE_TIMESTAMP_8
      , ATTRIBUTE_DATE_1
      , ATTRIBUTE_NUMBER_19
      , LAST_UPDATED_BY
      , ATTRIBUTE_CHAR_10
      , ATTRIBUTE_NUMBER_11_UOM
      , ATTRIBUTE_CHAR_16
      , ATTRIBUTE_NUMBER_20
      , VERSION_ID
      , ATTRIBUTE_CHAR_20
      , VERSION_END_DATE
      , PROGRAM_APP_NAME
      , ATTRIBUTE_TIMESTAMP_10
      , ATTRIBUTE_TIMESTAMP_4
      , ATTRIBUTE_NUMBER_9_UOM
      , ATTRIBUTE_TIMESTAMP_7
      , ATTRIBUTE_CHAR_32
      , ATTRIBUTE_CHAR_17
      , ATTRIBUTE_TIMESTAMP_5
      , ATTRIBUTE_NUMBER_5_UOM
      , ATTRIBUTE_DATE_5
      , ATTRIBUTE_NUMBER_6
      , REQUEST_ID
      , LAST_UPDATE_LOGIN
      , ATTRIBUTE_CHAR_31
      , ATTRIBUTE_CHAR_21
      , ATTRIBUTE_NUMBER_13
      , CREATION_DATE
      , ATTRIBUTE_TIMESTAMP_3
      , ATTRIBUTE_NUMBER_3_UOM
      , ATTRIBUTE_NUMBER_13_UOM
      , ATTRIBUTE_NUMBER_15_UOM
      , ATTRIBUTE_CHAR_14
      , ATTRIBUTE_NUMBER_15
      , ATTRIBUTE_CHAR_3
      , ATTRIBUTE_CHAR_4
      , ATTRIBUTE_CHAR_19
      , ATTRIBUTE_DATE_8
      , OBJECT_VERSION_NUMBER
      , ATTRIBUTE_CHAR_40
      , ATTRIBUTE_NUMBER_12_UOM
      , ATTRIBUTE_DATE_9
      , ATTRIBUTE_CHAR_7
      , LAST_UPDATE_DATE
      , ATTRIBUTE_NUMBER_4
      , ATTRIBUTE_TIMESTAMP_6
      , ATTRIBUTE_TIMESTAMP_1
      , ATTRIBUTE_CHAR_18
      , PROGRAM_NAME
      , ATTRIBUTE_NUMBER_8
      , _FIVETRAN_DELETED
      , _FIVETRAN_SYNCED
      , PSA_DELETE_IND
      , PSA_LOAD_DTS
      , PSA_RECORD_SOURCE
      , LOAD_DTS
      , REC_SRC
      , HASHDIFF
    FROM SRC_SITMFB
)
---- RENAME LAYER ----

, RENAME_SITMFB as (
    SELECT
        ITEM_HK
      , INVENTORY_ITEM_ID
      , ORGANIZATION_ID
      , EFF_LINE_ID
      , CHANGE_LINE_ID
      , VERSION_START_DATE
      , ATTRIBUTE_CHAR_25
      , ATTRIBUTE_NUMBER_2_UOM
      , ATTRIBUTE_CHAR_37
      , ATTRIBUTE_CHAR_39
      , ATTRIBUTE_CHAR_11
      , ATTRIBUTE_NUMBER_12
      , ATTRIBUTE_DATE_4
      , ATTRIBUTE_NUMBER_14
      , ATTRIBUTE_CHAR_24
      , ATTRIBUTE_DATE_3
      , ATTRIBUTE_NUMBER_18
      , ATTRIBUTE_CHAR_5
      , ATTRIBUTE_CHAR_12
      , ATTRIBUTE_NUMBER_20_UOM
      , ACD_TYPE
      , ATTRIBUTE_DATE_2
      , ATTRIBUTE_TIMESTAMP_2
      , ATTRIBUTE_CHAR_27
      , ATTRIBUTE_CHAR_13
      , ATTRIBUTE_NUMBER_16
      , ATTRIBUTE_NUMBER_2
      , ATTRIBUTE_NUMBER_7
      , ATTRIBUTE_CHAR_9
      , ATTRIBUTE_CHAR_30
      , ATTRIBUTE_NUMBER_18_UOM
      , ATTRIBUTE_NUMBER_10
      , ATTRIBUTE_CHAR_8
      , ATTRIBUTE_CHAR_15
      , ATTRIBUTE_CHAR_26
      , ATTRIBUTE_TIMESTAMP_9
      , ATTRIBUTE_CHAR_2
      , ATTRIBUTE_CHAR_29
      , CONTEXT_CODE
      , ATTRIBUTE_NUMBER_1_UOM
      , ATTRIBUTE_NUMBER_17_UOM
      , ATTRIBUTE_NUMBER_1
      , ATTRIBUTE_NUMBER_19_UOM
      , ATTRIBUTE_NUMBER_6_UOM
      , ATTRIBUTE_NUMBER_10_UOM
      , ATTRIBUTE_NUMBER_5
      , ATTRIBUTE_NUMBER_7_UOM
      , ATTRIBUTE_NUMBER_11
      , CATEGORY_CODE
      , ATTRIBUTE_NUMBER_14_UOM
      , IMPLEMENTATION_DATE
      , ATTRIBUTE_NUMBER_17
      , ATTRIBUTE_CHAR_33
      , ATTRIBUTE_DATE_10
      , ATTRIBUTE_NUMBER_8_UOM
      , ATTRIBUTE_CHAR_23
      , ATTRIBUTE_DATE_6
      , ATTRIBUTE_DATE_7
      , CHANGE_BIT_MAP
      , ATTRIBUTE_NUMBER_4_UOM
      , ATTRIBUTE_CHAR_1
      , ATTRIBUTE_CHAR_34
      , ATTRIBUTE_NUMBER_16_UOM
      , ATTRIBUTE_CHAR_28
      , ATTRIBUTE_NUMBER_3
      , ATTRIBUTE_CHAR_6
      , ATTRIBUTE_CHAR_22
      , ATTRIBUTE_CHAR_35
      , ATTRIBUTE_CHAR_36
      , CREATED_BY
      , ATTRIBUTE_NUMBER_9
      , ATTRIBUTE_CHAR_38
      , ATTRIBUTE_TIMESTAMP_8
      , ATTRIBUTE_DATE_1
      , ATTRIBUTE_NUMBER_19
      , LAST_UPDATED_BY
      , ATTRIBUTE_CHAR_10
      , ATTRIBUTE_NUMBER_11_UOM
      , ATTRIBUTE_CHAR_16
      , ATTRIBUTE_NUMBER_20
      , VERSION_ID
      , ATTRIBUTE_CHAR_20
      , VERSION_END_DATE
      , PROGRAM_APP_NAME
      , ATTRIBUTE_TIMESTAMP_10
      , ATTRIBUTE_TIMESTAMP_4
      , ATTRIBUTE_NUMBER_9_UOM
      , ATTRIBUTE_TIMESTAMP_7
      , ATTRIBUTE_CHAR_32
      , ATTRIBUTE_CHAR_17
      , ATTRIBUTE_TIMESTAMP_5
      , ATTRIBUTE_NUMBER_5_UOM
      , ATTRIBUTE_DATE_5
      , ATTRIBUTE_NUMBER_6
      , REQUEST_ID
      , LAST_UPDATE_LOGIN
      , ATTRIBUTE_CHAR_31
      , ATTRIBUTE_CHAR_21
      , ATTRIBUTE_NUMBER_13
      , CREATION_DATE
      , ATTRIBUTE_TIMESTAMP_3
      , ATTRIBUTE_NUMBER_3_UOM
      , ATTRIBUTE_NUMBER_13_UOM
      , ATTRIBUTE_NUMBER_15_UOM
      , ATTRIBUTE_CHAR_14
      , ATTRIBUTE_NUMBER_15
      , ATTRIBUTE_CHAR_3
      , ATTRIBUTE_CHAR_4
      , ATTRIBUTE_CHAR_19
      , ATTRIBUTE_DATE_8
      , OBJECT_VERSION_NUMBER
      , ATTRIBUTE_CHAR_40
      , ATTRIBUTE_NUMBER_12_UOM
      , ATTRIBUTE_DATE_9
      , ATTRIBUTE_CHAR_7
      , LAST_UPDATE_DATE
      , ATTRIBUTE_NUMBER_4
      , ATTRIBUTE_TIMESTAMP_6
      , ATTRIBUTE_TIMESTAMP_1
      , ATTRIBUTE_CHAR_18
      , PROGRAM_NAME
      , ATTRIBUTE_NUMBER_8
      , _FIVETRAN_DELETED
      , _FIVETRAN_SYNCED
      , PSA_DELETE_IND
      , PSA_LOAD_DTS
      , PSA_RECORD_SOURCE
      , LOAD_DTS
      , REC_SRC
      , HASHDIFF
    FROM LOGIC_SITMFB
)
---- FILTER LAYER ----

, FILTER_SITMFB as (
    SELECT *
    FROM RENAME_SITMFB
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM FILTER_SITMFB
)

---- FINAL LAYER ----
SELECT
          ITEM_HK
        , INVENTORY_ITEM_ID
        , ORGANIZATION_ID
        , EFF_LINE_ID
        , CHANGE_LINE_ID
        , VERSION_START_DATE
        , ATTRIBUTE_CHAR_25
        , ATTRIBUTE_NUMBER_2_UOM
        , ATTRIBUTE_CHAR_37
        , ATTRIBUTE_CHAR_39
        , ATTRIBUTE_CHAR_11
        , ATTRIBUTE_NUMBER_12
        , ATTRIBUTE_DATE_4
        , ATTRIBUTE_NUMBER_14
        , ATTRIBUTE_CHAR_24
        , ATTRIBUTE_DATE_3
        , ATTRIBUTE_NUMBER_18
        , ATTRIBUTE_CHAR_5
        , ATTRIBUTE_CHAR_12
        , ATTRIBUTE_NUMBER_20_UOM
        , ACD_TYPE
        , ATTRIBUTE_DATE_2
        , ATTRIBUTE_TIMESTAMP_2
        , ATTRIBUTE_CHAR_27
        , ATTRIBUTE_CHAR_13
        , ATTRIBUTE_NUMBER_16
        , ATTRIBUTE_NUMBER_2
        , ATTRIBUTE_NUMBER_7
        , ATTRIBUTE_CHAR_9
        , ATTRIBUTE_CHAR_30
        , ATTRIBUTE_NUMBER_18_UOM
        , ATTRIBUTE_NUMBER_10
        , ATTRIBUTE_CHAR_8
        , ATTRIBUTE_CHAR_15
        , ATTRIBUTE_CHAR_26
        , ATTRIBUTE_TIMESTAMP_9
        , ATTRIBUTE_CHAR_2
        , ATTRIBUTE_CHAR_29
        , CONTEXT_CODE
        , ATTRIBUTE_NUMBER_1_UOM
        , ATTRIBUTE_NUMBER_17_UOM
        , ATTRIBUTE_NUMBER_1
        , ATTRIBUTE_NUMBER_19_UOM
        , ATTRIBUTE_NUMBER_6_UOM
        , ATTRIBUTE_NUMBER_10_UOM
        , ATTRIBUTE_NUMBER_5
        , ATTRIBUTE_NUMBER_7_UOM
        , ATTRIBUTE_NUMBER_11
        , CATEGORY_CODE
        , ATTRIBUTE_NUMBER_14_UOM
        , IMPLEMENTATION_DATE
        , ATTRIBUTE_NUMBER_17
        , ATTRIBUTE_CHAR_33
        , ATTRIBUTE_DATE_10
        , ATTRIBUTE_NUMBER_8_UOM
        , ATTRIBUTE_CHAR_23
        , ATTRIBUTE_DATE_6
        , ATTRIBUTE_DATE_7
        , CHANGE_BIT_MAP
        , ATTRIBUTE_NUMBER_4_UOM
        , ATTRIBUTE_CHAR_1
        , ATTRIBUTE_CHAR_34
        , ATTRIBUTE_NUMBER_16_UOM
        , ATTRIBUTE_CHAR_28
        , ATTRIBUTE_NUMBER_3
        , ATTRIBUTE_CHAR_6
        , ATTRIBUTE_CHAR_22
        , ATTRIBUTE_CHAR_35
        , ATTRIBUTE_CHAR_36
        , CREATED_BY
        , ATTRIBUTE_NUMBER_9
        , ATTRIBUTE_CHAR_38
        , ATTRIBUTE_TIMESTAMP_8
        , ATTRIBUTE_DATE_1
        , ATTRIBUTE_NUMBER_19
        , LAST_UPDATED_BY
        , ATTRIBUTE_CHAR_10
        , ATTRIBUTE_NUMBER_11_UOM
        , ATTRIBUTE_CHAR_16
        , ATTRIBUTE_NUMBER_20
        , VERSION_ID
        , ATTRIBUTE_CHAR_20
        , VERSION_END_DATE
        , PROGRAM_APP_NAME
        , ATTRIBUTE_TIMESTAMP_10
        , ATTRIBUTE_TIMESTAMP_4
        , ATTRIBUTE_NUMBER_9_UOM
        , ATTRIBUTE_TIMESTAMP_7
        , ATTRIBUTE_CHAR_32
        , ATTRIBUTE_CHAR_17
        , ATTRIBUTE_TIMESTAMP_5
        , ATTRIBUTE_NUMBER_5_UOM
        , ATTRIBUTE_DATE_5
        , ATTRIBUTE_NUMBER_6
        , REQUEST_ID
        , LAST_UPDATE_LOGIN
        , ATTRIBUTE_CHAR_31
        , ATTRIBUTE_CHAR_21
        , ATTRIBUTE_NUMBER_13
        , CREATION_DATE
        , ATTRIBUTE_TIMESTAMP_3
        , ATTRIBUTE_NUMBER_3_UOM
        , ATTRIBUTE_NUMBER_13_UOM
        , ATTRIBUTE_NUMBER_15_UOM
        , ATTRIBUTE_CHAR_14
        , ATTRIBUTE_NUMBER_15
        , ATTRIBUTE_CHAR_3
        , ATTRIBUTE_CHAR_4
        , ATTRIBUTE_CHAR_19
        , ATTRIBUTE_DATE_8
        , OBJECT_VERSION_NUMBER
        , ATTRIBUTE_CHAR_40
        , ATTRIBUTE_NUMBER_12_UOM
        , ATTRIBUTE_DATE_9
        , ATTRIBUTE_CHAR_7
        , LAST_UPDATE_DATE
        , ATTRIBUTE_NUMBER_4
        , ATTRIBUTE_TIMESTAMP_6
        , ATTRIBUTE_TIMESTAMP_1
        , ATTRIBUTE_CHAR_18
        , PROGRAM_NAME
        , ATTRIBUTE_NUMBER_8
        , _FIVETRAN_DELETED
        , _FIVETRAN_SYNCED
        , PSA_DELETE_IND
        , PSA_LOAD_DTS
        , PSA_RECORD_SOURCE
        , LOAD_DTS
        , REC_SRC
        , HASHDIFF
FROM JOIN_RESULT
{% if is_incremental() %}
WHERE NOT EXISTS (
    SELECT 1 
    FROM {{ this }} existing
    WHERE existing.ITEM_HK= JOIN_RESULT.ITEM_HK
     AND existing.INVENTORY_ITEM_ID = JOIN_RESULT.INVENTORY_ITEM_ID 
     AND existing.ORGANIZATION_ID = JOIN_RESULT.ORGANIZATION_ID 
     AND existing.EFF_LINE_ID = JOIN_RESULT.EFF_LINE_ID
    AND existing.HASHDIFF = JOIN_RESULT.HASHDIFF
)
{% endif %} 
{% if not is_incremental() %}
/*the following qualify is to restrict multiple loads of touched records during the initial build. Ex: multiple row per hk, hashdiff */
qualify 1= row_number()over(partition by ITEM_HK, INVENTORY_ITEM_ID ,ORGANIZATION_ID,EFF_LINE_ID,HASHDIFF order by PSA_LOAD_DTS)
union all
    SELECT        MD5_BINARY(GR.VALUE) AS ITEM_HK
    ,  GR.VALUE::NUMBER as INVENTORY_ITEM_ID
    , GR.VALUE::NUMBER as ORGANIZATION_ID
    , GR.VALUE::NUMBER as EFF_LINE_ID
    , null as CHANGE_LINE_ID
    , null as VERSION_START_DATE
    , null as ATTRIBUTE_CHAR_25
    , null as ATTRIBUTE_NUMBER_2_UOM
    , null as ATTRIBUTE_CHAR_37
    , null as ATTRIBUTE_CHAR_39
    , null as ATTRIBUTE_CHAR_11
    , null as ATTRIBUTE_NUMBER_12
    , null as ATTRIBUTE_DATE_4
    , null as ATTRIBUTE_NUMBER_14
    , null as ATTRIBUTE_CHAR_24
    , null as ATTRIBUTE_DATE_3
    , null as ATTRIBUTE_NUMBER_18
    , null as ATTRIBUTE_CHAR_5
    , null as ATTRIBUTE_CHAR_12
    , null as ATTRIBUTE_NUMBER_20_UOM
    , null as ACD_TYPE
    , null as ATTRIBUTE_DATE_2
    , null as ATTRIBUTE_TIMESTAMP_2
    , null as ATTRIBUTE_CHAR_27
    , null as ATTRIBUTE_CHAR_13
    , null as ATTRIBUTE_NUMBER_16
    , null as ATTRIBUTE_NUMBER_2
    , null as ATTRIBUTE_NUMBER_7
    , null as ATTRIBUTE_CHAR_9
    , null as ATTRIBUTE_CHAR_30
    , null as ATTRIBUTE_NUMBER_18_UOM
    , null as ATTRIBUTE_NUMBER_10
    , null as ATTRIBUTE_CHAR_8
    , null as ATTRIBUTE_CHAR_15
    , null as ATTRIBUTE_CHAR_26
    , null as ATTRIBUTE_TIMESTAMP_9
    , null as ATTRIBUTE_CHAR_2
    , null as ATTRIBUTE_CHAR_29
    , null as CONTEXT_CODE
    , null as ATTRIBUTE_NUMBER_1_UOM
    , null as ATTRIBUTE_NUMBER_17_UOM
    , null as ATTRIBUTE_NUMBER_1
    , null as ATTRIBUTE_NUMBER_19_UOM
    , null as ATTRIBUTE_NUMBER_6_UOM
    , null as ATTRIBUTE_NUMBER_10_UOM
    , null as ATTRIBUTE_NUMBER_5
    , null as ATTRIBUTE_NUMBER_7_UOM
    , null as ATTRIBUTE_NUMBER_11
    , null as CATEGORY_CODE
    , null as ATTRIBUTE_NUMBER_14_UOM
    , null as IMPLEMENTATION_DATE
    , null as ATTRIBUTE_NUMBER_17
    , null as ATTRIBUTE_CHAR_33
    , null as ATTRIBUTE_DATE_10
    , null as ATTRIBUTE_NUMBER_8_UOM
    , null as ATTRIBUTE_CHAR_23
    , null as ATTRIBUTE_DATE_6
    , null as ATTRIBUTE_DATE_7
    , null as CHANGE_BIT_MAP
    , null as ATTRIBUTE_NUMBER_4_UOM
    , null as ATTRIBUTE_CHAR_1
    , null as ATTRIBUTE_CHAR_34
    , null as ATTRIBUTE_NUMBER_16_UOM
    , null as ATTRIBUTE_CHAR_28
    , null as ATTRIBUTE_NUMBER_3
    , null as ATTRIBUTE_CHAR_6
    , null as ATTRIBUTE_CHAR_22
    , null as ATTRIBUTE_CHAR_35
    , null as ATTRIBUTE_CHAR_36
    , null as CREATED_BY
    , null as ATTRIBUTE_NUMBER_9
    , null as ATTRIBUTE_CHAR_38
    , null as ATTRIBUTE_TIMESTAMP_8
    , null as ATTRIBUTE_DATE_1
    , null as ATTRIBUTE_NUMBER_19
    , null as LAST_UPDATED_BY
    , null as ATTRIBUTE_CHAR_10
    , null as ATTRIBUTE_NUMBER_11_UOM
    , null as ATTRIBUTE_CHAR_16
    , null as ATTRIBUTE_NUMBER_20
    , null as VERSION_ID
    , null as ATTRIBUTE_CHAR_20
    , null as VERSION_END_DATE
    , null as PROGRAM_APP_NAME
    , null as ATTRIBUTE_TIMESTAMP_10
    , null as ATTRIBUTE_TIMESTAMP_4
    , null as ATTRIBUTE_NUMBER_9_UOM
    , null as ATTRIBUTE_TIMESTAMP_7
    , null as ATTRIBUTE_CHAR_32
    , null as ATTRIBUTE_CHAR_17
    , null as ATTRIBUTE_TIMESTAMP_5
    , null as ATTRIBUTE_NUMBER_5_UOM
    , null as ATTRIBUTE_DATE_5
    , null as ATTRIBUTE_NUMBER_6
    , null as REQUEST_ID
    , null as LAST_UPDATE_LOGIN
    , null as ATTRIBUTE_CHAR_31
    , null as ATTRIBUTE_CHAR_21
    , null as ATTRIBUTE_NUMBER_13
    , null as CREATION_DATE
    , null as ATTRIBUTE_TIMESTAMP_3
    , null as ATTRIBUTE_NUMBER_3_UOM
    , null as ATTRIBUTE_NUMBER_13_UOM
    , null as ATTRIBUTE_NUMBER_15_UOM
    , null as ATTRIBUTE_CHAR_14
    , null as ATTRIBUTE_NUMBER_15
    , null as ATTRIBUTE_CHAR_3
    , null as ATTRIBUTE_CHAR_4
    , null as ATTRIBUTE_CHAR_19
    , null as ATTRIBUTE_DATE_8
    , null as OBJECT_VERSION_NUMBER
    , null as ATTRIBUTE_CHAR_40
    , null as ATTRIBUTE_NUMBER_12_UOM
    , null as ATTRIBUTE_DATE_9
    , null as ATTRIBUTE_CHAR_7
    , null as LAST_UPDATE_DATE
    , null as ATTRIBUTE_NUMBER_4
    , null as ATTRIBUTE_TIMESTAMP_6
    , null as ATTRIBUTE_TIMESTAMP_1
    , null as ATTRIBUTE_CHAR_18
    , null as PROGRAM_NAME
    , null as ATTRIBUTE_NUMBER_8
    , null as _FIVETRAN_DELETED
    , null as _FIVETRAN_SYNCED
    , null as PSA_DELETE_IND
    , null as PSA_LOAD_DTS
    , null as PSA_RECORD_SOURCE, CONVERT_TIMEZONE('UTC','1900-01-01'::TIMESTAMP)::TIMESTAMP as LOAD_DTS
,'USAZET.SNOWFLAKE.FBIN.DERIVED' AS REC_SRC
, ''::BINARY as HASHDIFF
  FROM
        TABLE(strtok_split_to_table('0|-1|-2', '|')) AS GR
{% endif %}