---- SRC LAYER ----
WITH
SRC_SML            as ( SELECT * FROM {{ ref('v_psa_stg_supplier__ml_ebs') }} as SRC 
                         {% if is_incremental() %}
                         WHERE SRC.LOAD_DTS > (SELECT DATEADD('HOUR', '-1', MAX(LOAD_DTS)) FROM {{this}})
                         {% endif %}  )

/*
SRC_SML            as ( SELECT * FROM STAGING.v_psa_stg_supplier__ml_ebs )
*/
---- LOGIC LAYER ----

, LOGIC_SML as (
    SELECT
        SUPPLIER_HK
      , SEGMENT1
      , VENDOR_ID
      , LOAD_DTS
      , CHECK_DIGITS
      , ALWAYS_TAKE_DISC_FLAG
      , UNIQUE_TAX_REFERENCE_NUM
      , FREIGHT_TERMS_LOOKUP_CODE
      , AUTO_TAX_CALC_OVERRIDE
      , HOLD_BY
      , BANK_NUM
      , EDI_REMITTANCE_INSTRUCTION
      , EXPENSE_CODE_COMBINATION_ID
      , OFFSET_TAX_FLAG
      , PROGRAM_ID
      , PAY_DATE_BASIS_LOOKUP_CODE
      , GLOBAL_ATTRIBUTE5
      , GLOBAL_ATTRIBUTE4
      , GLOBAL_ATTRIBUTE7
      , GLOBAL_ATTRIBUTE6
      , EDI_TRANSACTION_HANDLING
      , SEGMENT4
      , GLOBAL_ATTRIBUTE1
      , SEGMENT3
      , GLOBAL_ATTRIBUTE3
      , MINORITY_GROUP_LOOKUP_CODE
      , SEGMENT5
      , GLOBAL_ATTRIBUTE2
      , BANK_BRANCH_TYPE
      , AWT_GROUP_ID
      , GLOBAL_ATTRIBUTE9
      , MATCH_STATUS_FLAG
      , GLOBAL_ATTRIBUTE8
      , TCA_SYNC_VAT_REG_NUM
      , ATTRIBUTE3
      , DAYS_LATE_RECEIPT_ALLOWED
      , ATTRIBUTE2
      , ATTRIBUTE1
      , INVOICE_AMOUNT_LIMIT
      , AP_TAX_ROUNDING_RULE
      , NI_NUMBER
      , EDI_REMITTANCE_METHOD
      , AMOUNT_INCLUDES_TAX_FLAG
      , ATTRIBUTE9
      , ATTRIBUTE8
      , COMPANY_REGISTRATION_NUMBER
      , ATTRIBUTE7
      , QTY_RCV_EXCEPTION_CODE
      , ATTRIBUTE6
      , ATTRIBUTE5
      , ATTRIBUTE4
      , CREDIT_LIMIT
      , TCA_SYNC_NUM_1099
      , OFFSET_VAT_CODE
      , SMALL_BUSINESS_FLAG
      , ACCTS_PAY_CODE_COMBINATION_ID
      , DISC_LOST_CODE_COMBINATION_ID
      , ATTRIBUTE10
      , EXCLUSIVE_PAYMENT_FLAG
      , NAME_CONTROL
      , ATTRIBUTE14
      , ATTRIBUTE13
      , EDI_PAYMENT_FORMAT
      , ATTRIBUTE12
      , ATTRIBUTE11
      , WITHHOLDING_STATUS_LOOKUP_CODE
      , TRADING_NAME
      , BILL_TO_LOCATION_ID
      , EXCHANGE_DATE_LOOKUP_CODE
      , EDI_PAYMENT_METHOD
      , PREPAY_CODE_COMBINATION_ID
      , LAST_NAME
      , PRICE_TOLERANCE
      , BUS_CLASS_LAST_CERTIFIED_DATE
      , HOLD_DATE
      , PARENT_PARTY_ID
      , CUSTOMER_NUM
      , STATE_REPORTABLE_FLAG
      , BANK_NUMBER
      , GLOBAL_ATTRIBUTE20
      , VENDOR_NAME_ALT
      , PARENT_VENDOR_ID
      , VENDOR_TYPE_LOOKUP_CODE
      , GLOBAL_ATTRIBUTE17
      , GLOBAL_ATTRIBUTE18
      , CIS_ENABLED_FLAG
      , GLOBAL_ATTRIBUTE15
      , GLOBAL_ATTRIBUTE16
      , GLOBAL_ATTRIBUTE13
      , GLOBAL_ATTRIBUTE14
      , GLOBAL_ATTRIBUTE11
      , BANK_ACCOUNT_TYPE
      , GLOBAL_ATTRIBUTE12
      , ORGANIZATION_TYPE_LOOKUP_CODE
      , RECEIVING_ROUTING_ID
      , ATTRIBUTE15
      , NUM_1099
      , ALLOW_AWT_FLAG
      , INVOICE_CURRENCY_CODE
      , GLOBAL_ATTRIBUTE19
      , CREATE_DEBIT_MEMO_FLAG
      , VENDOR_NAME
      , DISTRIBUTION_SET_ID
      , EMPLOYEE_ID
      , GLOBAL_ATTRIBUTE10
      , BANK_ACCOUNT_NUM
      , AUTO_CALCULATE_INTEREST_FLAG
      , SECOND_NAME
      , BANK_ACCOUNT_NAME
      , TAX_VERIFICATION_DATE
      , SALUTATION
      , NATIONAL_INSURANCE_NUMBER
      , HOLD_FLAG
      , INSPECTION_REQUIRED_FLAG
      , WORK_REFERENCE
      , SHIP_TO_LOCATION_ID
      , ONE_TIME_FLAG
      , FUTURE_DATED_PAYMENT_CCID
      , WOMEN_OWNED_FLAG
      , CREATED_BY
      , LAST_UPDATED_BY
      , HOLD_REASON
      , WITHHOLDING_START_DATE
      , VAT_CODE
      , VERIFICATION_NUMBER
      , PARTNERSHIP_NAME
      , RECEIPT_REQUIRED_FLAG
      , FEDERAL_REPORTABLE_FLAG
      , INDIVIDUAL_1099
      , TCA_SYNC_VENDOR_NAME
      , ENFORCE_SHIP_TO_LOCATION_CODE
      , TAX_REPORTING_NAME
      , TERMS_ID
      , ATTRIBUTE_CATEGORY
      , PROGRAM_APPLICATION_ID
      , VALIDATION_NUMBER
      , AUTO_TAX_CALC_FLAG
      , EXCLUDE_FREIGHT_FROM_DISCOUNT
      , BUS_CLASS_LAST_CERTIFIED_BY
      , TERMS_DATE_BASIS
      , PARTY_ID
      , PAY_AWT_GROUP_ID
      , PURCHASING_HOLD_REASON
      , ALLOW_SUBSTITUTE_RECEIPTS_FLAG
      , CREDIT_STATUS_LOOKUP_CODE
      , VAT_REGISTRATION_NUM
      , SET_OF_BOOKS_ID
      , PARTNERSHIP_UTR
      , REQUEST_ID
      , BANK_CHARGE_BEARER
      , FIRST_NAME
      , HOLD_FUTURE_PAYMENTS_FLAG
      , PAYMENT_PRIORITY
      , RECEIPT_DAYS_EXCEPTION_CODE
      , DISC_TAKEN_CODE_COMBINATION_ID
      , PAYMENT_METHOD_LOOKUP_CODE
      , CIS_PARENT_VENDOR_ID
      , TYPE_1099
      , STANDARD_INDUSTRY_CLASS
      , VERIFICATION_REQUEST_ID
      , PAYMENT_CURRENCY_CODE
      , HOLD_ALL_PAYMENTS_FLAG
      , CIS_VERIFICATION_DATE
      , SUMMARY_FLAG
      , QTY_RCV_TOLERANCE
      , ALLOW_UNORDERED_RECEIPTS_FLAG
      , SEGMENT2
      , LAST_UPDATE_LOGIN
      , MATCH_OPTION
      , ENABLED_FLAG
      , GLOBAL_ATTRIBUTE_CATEGORY
      , SHIP_VIA_LOOKUP_CODE
      , FOB_LOOKUP_CODE
      , DAYS_EARLY_RECEIPT_ALLOWED
      , HOLD_UNMATCHED_INVOICES_FLAG
      , MIN_ORDER_AMOUNT
      , PAY_GROUP_LOOKUP_CODE
      , _FIVETRAN_DELETED
      , _FIVETRAN_ID
      , _FIVETRAN_SYNCED
      , PROGRAM_UPDATE_DATE
      , START_DATE_ACTIVE
      , END_DATE_ACTIVE
      , CREATION_DATE
      , LAST_UPDATE_DATE
      , PSA_LOAD_DTS
      , PSA_DELETE_IND
      , REC_SRC
      , BKCC
      , HASHDIFF
    FROM SRC_SML
)
---- RENAME LAYER ----

, RENAME_SML as (
    SELECT
        SUPPLIER_HK
      , SEGMENT1
      , VENDOR_ID
      , LOAD_DTS
      , CHECK_DIGITS
      , ALWAYS_TAKE_DISC_FLAG
      , UNIQUE_TAX_REFERENCE_NUM
      , FREIGHT_TERMS_LOOKUP_CODE
      , AUTO_TAX_CALC_OVERRIDE
      , HOLD_BY
      , BANK_NUM
      , EDI_REMITTANCE_INSTRUCTION
      , EXPENSE_CODE_COMBINATION_ID
      , OFFSET_TAX_FLAG
      , PROGRAM_ID
      , PAY_DATE_BASIS_LOOKUP_CODE
      , GLOBAL_ATTRIBUTE5
      , GLOBAL_ATTRIBUTE4
      , GLOBAL_ATTRIBUTE7
      , GLOBAL_ATTRIBUTE6
      , EDI_TRANSACTION_HANDLING
      , SEGMENT4
      , GLOBAL_ATTRIBUTE1
      , SEGMENT3
      , GLOBAL_ATTRIBUTE3
      , MINORITY_GROUP_LOOKUP_CODE
      , SEGMENT5
      , GLOBAL_ATTRIBUTE2
      , BANK_BRANCH_TYPE
      , AWT_GROUP_ID
      , GLOBAL_ATTRIBUTE9
      , MATCH_STATUS_FLAG
      , GLOBAL_ATTRIBUTE8
      , TCA_SYNC_VAT_REG_NUM
      , ATTRIBUTE3
      , DAYS_LATE_RECEIPT_ALLOWED
      , ATTRIBUTE2
      , ATTRIBUTE1
      , INVOICE_AMOUNT_LIMIT
      , AP_TAX_ROUNDING_RULE
      , NI_NUMBER
      , EDI_REMITTANCE_METHOD
      , AMOUNT_INCLUDES_TAX_FLAG
      , ATTRIBUTE9
      , ATTRIBUTE8
      , COMPANY_REGISTRATION_NUMBER
      , ATTRIBUTE7
      , QTY_RCV_EXCEPTION_CODE
      , ATTRIBUTE6
      , ATTRIBUTE5
      , ATTRIBUTE4
      , CREDIT_LIMIT
      , TCA_SYNC_NUM_1099
      , OFFSET_VAT_CODE
      , SMALL_BUSINESS_FLAG
      , ACCTS_PAY_CODE_COMBINATION_ID
      , DISC_LOST_CODE_COMBINATION_ID
      , ATTRIBUTE10
      , EXCLUSIVE_PAYMENT_FLAG
      , NAME_CONTROL
      , ATTRIBUTE14
      , ATTRIBUTE13
      , EDI_PAYMENT_FORMAT
      , ATTRIBUTE12
      , ATTRIBUTE11
      , WITHHOLDING_STATUS_LOOKUP_CODE
      , TRADING_NAME
      , BILL_TO_LOCATION_ID
      , EXCHANGE_DATE_LOOKUP_CODE
      , EDI_PAYMENT_METHOD
      , PREPAY_CODE_COMBINATION_ID
      , LAST_NAME
      , PRICE_TOLERANCE
      , BUS_CLASS_LAST_CERTIFIED_DATE
      , HOLD_DATE
      , PARENT_PARTY_ID
      , CUSTOMER_NUM
      , STATE_REPORTABLE_FLAG
      , BANK_NUMBER
      , GLOBAL_ATTRIBUTE20
      , VENDOR_NAME_ALT
      , PARENT_VENDOR_ID
      , VENDOR_TYPE_LOOKUP_CODE
      , GLOBAL_ATTRIBUTE17
      , GLOBAL_ATTRIBUTE18
      , CIS_ENABLED_FLAG
      , GLOBAL_ATTRIBUTE15
      , GLOBAL_ATTRIBUTE16
      , GLOBAL_ATTRIBUTE13
      , GLOBAL_ATTRIBUTE14
      , GLOBAL_ATTRIBUTE11
      , BANK_ACCOUNT_TYPE
      , GLOBAL_ATTRIBUTE12
      , ORGANIZATION_TYPE_LOOKUP_CODE
      , RECEIVING_ROUTING_ID
      , ATTRIBUTE15
      , NUM_1099
      , ALLOW_AWT_FLAG
      , INVOICE_CURRENCY_CODE
      , GLOBAL_ATTRIBUTE19
      , CREATE_DEBIT_MEMO_FLAG
      , VENDOR_NAME
      , DISTRIBUTION_SET_ID
      , EMPLOYEE_ID
      , GLOBAL_ATTRIBUTE10
      , BANK_ACCOUNT_NUM
      , AUTO_CALCULATE_INTEREST_FLAG
      , SECOND_NAME
      , BANK_ACCOUNT_NAME
      , TAX_VERIFICATION_DATE
      , SALUTATION
      , NATIONAL_INSURANCE_NUMBER
      , HOLD_FLAG
      , INSPECTION_REQUIRED_FLAG
      , WORK_REFERENCE
      , SHIP_TO_LOCATION_ID
      , ONE_TIME_FLAG
      , FUTURE_DATED_PAYMENT_CCID
      , WOMEN_OWNED_FLAG
      , CREATED_BY
      , LAST_UPDATED_BY
      , HOLD_REASON
      , WITHHOLDING_START_DATE
      , VAT_CODE
      , VERIFICATION_NUMBER
      , PARTNERSHIP_NAME
      , RECEIPT_REQUIRED_FLAG
      , FEDERAL_REPORTABLE_FLAG
      , INDIVIDUAL_1099
      , TCA_SYNC_VENDOR_NAME
      , ENFORCE_SHIP_TO_LOCATION_CODE
      , TAX_REPORTING_NAME
      , TERMS_ID
      , ATTRIBUTE_CATEGORY
      , PROGRAM_APPLICATION_ID
      , VALIDATION_NUMBER
      , AUTO_TAX_CALC_FLAG
      , EXCLUDE_FREIGHT_FROM_DISCOUNT
      , BUS_CLASS_LAST_CERTIFIED_BY
      , TERMS_DATE_BASIS
      , PARTY_ID
      , PAY_AWT_GROUP_ID
      , PURCHASING_HOLD_REASON
      , ALLOW_SUBSTITUTE_RECEIPTS_FLAG
      , CREDIT_STATUS_LOOKUP_CODE
      , VAT_REGISTRATION_NUM
      , SET_OF_BOOKS_ID
      , PARTNERSHIP_UTR
      , REQUEST_ID
      , BANK_CHARGE_BEARER
      , FIRST_NAME
      , HOLD_FUTURE_PAYMENTS_FLAG
      , PAYMENT_PRIORITY
      , RECEIPT_DAYS_EXCEPTION_CODE
      , DISC_TAKEN_CODE_COMBINATION_ID
      , PAYMENT_METHOD_LOOKUP_CODE
      , CIS_PARENT_VENDOR_ID
      , TYPE_1099
      , STANDARD_INDUSTRY_CLASS
      , VERIFICATION_REQUEST_ID
      , PAYMENT_CURRENCY_CODE
      , HOLD_ALL_PAYMENTS_FLAG
      , CIS_VERIFICATION_DATE
      , SUMMARY_FLAG
      , QTY_RCV_TOLERANCE
      , ALLOW_UNORDERED_RECEIPTS_FLAG
      , SEGMENT2
      , LAST_UPDATE_LOGIN
      , MATCH_OPTION
      , ENABLED_FLAG
      , GLOBAL_ATTRIBUTE_CATEGORY
      , SHIP_VIA_LOOKUP_CODE
      , FOB_LOOKUP_CODE
      , DAYS_EARLY_RECEIPT_ALLOWED
      , HOLD_UNMATCHED_INVOICES_FLAG
      , MIN_ORDER_AMOUNT
      , PAY_GROUP_LOOKUP_CODE
      , _FIVETRAN_DELETED
      , _FIVETRAN_ID
      , _FIVETRAN_SYNCED
      , PROGRAM_UPDATE_DATE
      , START_DATE_ACTIVE
      , END_DATE_ACTIVE
      , CREATION_DATE
      , LAST_UPDATE_DATE
      , PSA_LOAD_DTS
      , PSA_DELETE_IND
      , REC_SRC
      , BKCC
      , HASHDIFF
    FROM LOGIC_SML
)
---- FILTER LAYER ----

, FILTER_SML as (
    SELECT *
    FROM RENAME_SML
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM FILTER_SML
)

---- FINAL LAYER ----
SELECT
          SUPPLIER_HK
        , SEGMENT1
        , VENDOR_ID
        , LOAD_DTS
        , CHECK_DIGITS
        , ALWAYS_TAKE_DISC_FLAG
        , UNIQUE_TAX_REFERENCE_NUM
        , FREIGHT_TERMS_LOOKUP_CODE
        , AUTO_TAX_CALC_OVERRIDE
        , HOLD_BY
        , BANK_NUM
        , EDI_REMITTANCE_INSTRUCTION
        , EXPENSE_CODE_COMBINATION_ID
        , OFFSET_TAX_FLAG
        , PROGRAM_ID
        , PAY_DATE_BASIS_LOOKUP_CODE
        , GLOBAL_ATTRIBUTE5
        , GLOBAL_ATTRIBUTE4
        , GLOBAL_ATTRIBUTE7
        , GLOBAL_ATTRIBUTE6
        , EDI_TRANSACTION_HANDLING
        , SEGMENT4
        , GLOBAL_ATTRIBUTE1
        , SEGMENT3
        , GLOBAL_ATTRIBUTE3
        , MINORITY_GROUP_LOOKUP_CODE
        , SEGMENT5
        , GLOBAL_ATTRIBUTE2
        , BANK_BRANCH_TYPE
        , AWT_GROUP_ID
        , GLOBAL_ATTRIBUTE9
        , MATCH_STATUS_FLAG
        , GLOBAL_ATTRIBUTE8
        , TCA_SYNC_VAT_REG_NUM
        , ATTRIBUTE3
        , DAYS_LATE_RECEIPT_ALLOWED
        , ATTRIBUTE2
        , ATTRIBUTE1
        , INVOICE_AMOUNT_LIMIT
        , AP_TAX_ROUNDING_RULE
        , NI_NUMBER
        , EDI_REMITTANCE_METHOD
        , AMOUNT_INCLUDES_TAX_FLAG
        , ATTRIBUTE9
        , ATTRIBUTE8
        , COMPANY_REGISTRATION_NUMBER
        , ATTRIBUTE7
        , QTY_RCV_EXCEPTION_CODE
        , ATTRIBUTE6
        , ATTRIBUTE5
        , ATTRIBUTE4
        , CREDIT_LIMIT
        , TCA_SYNC_NUM_1099
        , OFFSET_VAT_CODE
        , SMALL_BUSINESS_FLAG
        , ACCTS_PAY_CODE_COMBINATION_ID
        , DISC_LOST_CODE_COMBINATION_ID
        , ATTRIBUTE10
        , EXCLUSIVE_PAYMENT_FLAG
        , NAME_CONTROL
        , ATTRIBUTE14
        , ATTRIBUTE13
        , EDI_PAYMENT_FORMAT
        , ATTRIBUTE12
        , ATTRIBUTE11
        , WITHHOLDING_STATUS_LOOKUP_CODE
        , TRADING_NAME
        , BILL_TO_LOCATION_ID
        , EXCHANGE_DATE_LOOKUP_CODE
        , EDI_PAYMENT_METHOD
        , PREPAY_CODE_COMBINATION_ID
        , LAST_NAME
        , PRICE_TOLERANCE
        , BUS_CLASS_LAST_CERTIFIED_DATE
        , HOLD_DATE
        , PARENT_PARTY_ID
        , CUSTOMER_NUM
        , STATE_REPORTABLE_FLAG
        , BANK_NUMBER
        , GLOBAL_ATTRIBUTE20
        , VENDOR_NAME_ALT
        , PARENT_VENDOR_ID
        , VENDOR_TYPE_LOOKUP_CODE
        , GLOBAL_ATTRIBUTE17
        , GLOBAL_ATTRIBUTE18
        , CIS_ENABLED_FLAG
        , GLOBAL_ATTRIBUTE15
        , GLOBAL_ATTRIBUTE16
        , GLOBAL_ATTRIBUTE13
        , GLOBAL_ATTRIBUTE14
        , GLOBAL_ATTRIBUTE11
        , BANK_ACCOUNT_TYPE
        , GLOBAL_ATTRIBUTE12
        , ORGANIZATION_TYPE_LOOKUP_CODE
        , RECEIVING_ROUTING_ID
        , ATTRIBUTE15
        , NUM_1099
        , ALLOW_AWT_FLAG
        , INVOICE_CURRENCY_CODE
        , GLOBAL_ATTRIBUTE19
        , CREATE_DEBIT_MEMO_FLAG
        , VENDOR_NAME
        , DISTRIBUTION_SET_ID
        , EMPLOYEE_ID
        , GLOBAL_ATTRIBUTE10
        , BANK_ACCOUNT_NUM
        , AUTO_CALCULATE_INTEREST_FLAG
        , SECOND_NAME
        , BANK_ACCOUNT_NAME
        , TAX_VERIFICATION_DATE
        , SALUTATION
        , NATIONAL_INSURANCE_NUMBER
        , HOLD_FLAG
        , INSPECTION_REQUIRED_FLAG
        , WORK_REFERENCE
        , SHIP_TO_LOCATION_ID
        , ONE_TIME_FLAG
        , FUTURE_DATED_PAYMENT_CCID
        , WOMEN_OWNED_FLAG
        , CREATED_BY
        , LAST_UPDATED_BY
        , HOLD_REASON
        , WITHHOLDING_START_DATE
        , VAT_CODE
        , VERIFICATION_NUMBER
        , PARTNERSHIP_NAME
        , RECEIPT_REQUIRED_FLAG
        , FEDERAL_REPORTABLE_FLAG
        , INDIVIDUAL_1099
        , TCA_SYNC_VENDOR_NAME
        , ENFORCE_SHIP_TO_LOCATION_CODE
        , TAX_REPORTING_NAME
        , TERMS_ID
        , ATTRIBUTE_CATEGORY
        , PROGRAM_APPLICATION_ID
        , VALIDATION_NUMBER
        , AUTO_TAX_CALC_FLAG
        , EXCLUDE_FREIGHT_FROM_DISCOUNT
        , BUS_CLASS_LAST_CERTIFIED_BY
        , TERMS_DATE_BASIS
        , PARTY_ID
        , PAY_AWT_GROUP_ID
        , PURCHASING_HOLD_REASON
        , ALLOW_SUBSTITUTE_RECEIPTS_FLAG
        , CREDIT_STATUS_LOOKUP_CODE
        , VAT_REGISTRATION_NUM
        , SET_OF_BOOKS_ID
        , PARTNERSHIP_UTR
        , REQUEST_ID
        , BANK_CHARGE_BEARER
        , FIRST_NAME
        , HOLD_FUTURE_PAYMENTS_FLAG
        , PAYMENT_PRIORITY
        , RECEIPT_DAYS_EXCEPTION_CODE
        , DISC_TAKEN_CODE_COMBINATION_ID
        , PAYMENT_METHOD_LOOKUP_CODE
        , CIS_PARENT_VENDOR_ID
        , TYPE_1099
        , STANDARD_INDUSTRY_CLASS
        , VERIFICATION_REQUEST_ID
        , PAYMENT_CURRENCY_CODE
        , HOLD_ALL_PAYMENTS_FLAG
        , CIS_VERIFICATION_DATE
        , SUMMARY_FLAG
        , QTY_RCV_TOLERANCE
        , ALLOW_UNORDERED_RECEIPTS_FLAG
        , SEGMENT2
        , LAST_UPDATE_LOGIN
        , MATCH_OPTION
        , ENABLED_FLAG
        , GLOBAL_ATTRIBUTE_CATEGORY
        , SHIP_VIA_LOOKUP_CODE
        , FOB_LOOKUP_CODE
        , DAYS_EARLY_RECEIPT_ALLOWED
        , HOLD_UNMATCHED_INVOICES_FLAG
        , MIN_ORDER_AMOUNT
        , PAY_GROUP_LOOKUP_CODE
        , _FIVETRAN_DELETED
        , _FIVETRAN_ID
        , _FIVETRAN_SYNCED
        , PROGRAM_UPDATE_DATE
        , START_DATE_ACTIVE
        , END_DATE_ACTIVE
        , CREATION_DATE
        , LAST_UPDATE_DATE
        , PSA_LOAD_DTS
        , PSA_DELETE_IND
        , REC_SRC
        , BKCC
        , HASHDIFF
FROM JOIN_RESULT
{% if is_incremental() %}
WHERE NOT EXISTS (
    SELECT 1 
    FROM {{ this }} existing
    WHERE existing.SUPPLIER_HK = JOIN_RESULT.SUPPLIER_HK 
    AND existing.HASHDIFF = JOIN_RESULT.HASHDIFF
)
{% endif %} 
{% if not is_incremental() %}
/* The following qualifier is implemented to prevent multiple loads of touched records during the initial build, such as multiple rows per HK and hashdiff. */
qualify 1= row_number()over(partition by SUPPLIER_HK, HASHDIFF order by PSA_LOAD_DTS)

union all
    SELECT MD5_BINARY(GR.VALUE) SUPPLIER_HK
        , GR.VALUE as SEGMENT1
        , null as VENDOR_ID
        , CONVERT_TIMEZONE('UTC','1900-01-01'::TIMESTAMP) as LOAD_DTS
        , null as CHECK_DIGITS
        , null as ALWAYS_TAKE_DISC_FLAG
        , null as UNIQUE_TAX_REFERENCE_NUM
        , null as FREIGHT_TERMS_LOOKUP_CODE
        , null as AUTO_TAX_CALC_OVERRIDE
        , null as HOLD_BY
        , null as BANK_NUM
        , null as EDI_REMITTANCE_INSTRUCTION
        , null as EXPENSE_CODE_COMBINATION_ID
        , null as OFFSET_TAX_FLAG
        , null as PROGRAM_ID
        , null as PAY_DATE_BASIS_LOOKUP_CODE
        , null as GLOBAL_ATTRIBUTE5
        , null as GLOBAL_ATTRIBUTE4
        , null as GLOBAL_ATTRIBUTE7
        , null as GLOBAL_ATTRIBUTE6
        , null as EDI_TRANSACTION_HANDLING
        , null as SEGMENT4
        , null as GLOBAL_ATTRIBUTE1
        , null as SEGMENT3
        , null as GLOBAL_ATTRIBUTE3
        , null as MINORITY_GROUP_LOOKUP_CODE
        , null as SEGMENT5
        , null as GLOBAL_ATTRIBUTE2
        , null as BANK_BRANCH_TYPE
        , null as AWT_GROUP_ID
        , null as GLOBAL_ATTRIBUTE9
        , null as MATCH_STATUS_FLAG
        , null as GLOBAL_ATTRIBUTE8
        , null as TCA_SYNC_VAT_REG_NUM
        , null as ATTRIBUTE3
        , null as DAYS_LATE_RECEIPT_ALLOWED
        , null as ATTRIBUTE2
        , null as ATTRIBUTE1
        , null as INVOICE_AMOUNT_LIMIT
        , null as AP_TAX_ROUNDING_RULE
        , null as NI_NUMBER
        , null as EDI_REMITTANCE_METHOD
        , null as AMOUNT_INCLUDES_TAX_FLAG
        , null as ATTRIBUTE9
        , null as ATTRIBUTE8
        , null as COMPANY_REGISTRATION_NUMBER
        , null as ATTRIBUTE7
        , null as QTY_RCV_EXCEPTION_CODE
        , null as ATTRIBUTE6
        , null as ATTRIBUTE5
        , null as ATTRIBUTE4
        , null as CREDIT_LIMIT
        , null as TCA_SYNC_NUM_1099
        , null as OFFSET_VAT_CODE
        , null as SMALL_BUSINESS_FLAG
        , null as ACCTS_PAY_CODE_COMBINATION_ID
        , null as DISC_LOST_CODE_COMBINATION_ID
        , null as ATTRIBUTE10
        , null as EXCLUSIVE_PAYMENT_FLAG
        , null as NAME_CONTROL
        , null as ATTRIBUTE14
        , null as ATTRIBUTE13
        , null as EDI_PAYMENT_FORMAT
        , null as ATTRIBUTE12
        , null as ATTRIBUTE11
        , null as WITHHOLDING_STATUS_LOOKUP_CODE
        , null as TRADING_NAME
        , null as BILL_TO_LOCATION_ID
        , null as EXCHANGE_DATE_LOOKUP_CODE
        , null as EDI_PAYMENT_METHOD
        , null as PREPAY_CODE_COMBINATION_ID
        , null as LAST_NAME
        , null as PRICE_TOLERANCE
        , null as BUS_CLASS_LAST_CERTIFIED_DATE
        , null as HOLD_DATE
        , null as PARENT_PARTY_ID
        , null as CUSTOMER_NUM
        , null as STATE_REPORTABLE_FLAG
        , null as BANK_NUMBER
        , null as GLOBAL_ATTRIBUTE20
        , null as VENDOR_NAME_ALT
        , null as PARENT_VENDOR_ID
        , null as VENDOR_TYPE_LOOKUP_CODE
        , null as GLOBAL_ATTRIBUTE17
        , null as GLOBAL_ATTRIBUTE18
        , null as CIS_ENABLED_FLAG
        , null as GLOBAL_ATTRIBUTE15
        , null as GLOBAL_ATTRIBUTE16
        , null as GLOBAL_ATTRIBUTE13
        , null as GLOBAL_ATTRIBUTE14
        , null as GLOBAL_ATTRIBUTE11
        , null as BANK_ACCOUNT_TYPE
        , null as GLOBAL_ATTRIBUTE12
        , null as ORGANIZATION_TYPE_LOOKUP_CODE
        , null as RECEIVING_ROUTING_ID
        , null as ATTRIBUTE15
        , null as NUM_1099
        , null as ALLOW_AWT_FLAG
        , null as INVOICE_CURRENCY_CODE
        , null as GLOBAL_ATTRIBUTE19
        , null as CREATE_DEBIT_MEMO_FLAG
        , null as VENDOR_NAME
        , null as DISTRIBUTION_SET_ID
        , null as EMPLOYEE_ID
        , null as GLOBAL_ATTRIBUTE10
        , null as BANK_ACCOUNT_NUM
        , null as AUTO_CALCULATE_INTEREST_FLAG
        , null as SECOND_NAME
        , null as BANK_ACCOUNT_NAME
        , null as TAX_VERIFICATION_DATE
        , null as SALUTATION
        , null as NATIONAL_INSURANCE_NUMBER
        , null as HOLD_FLAG
        , null as INSPECTION_REQUIRED_FLAG
        , null as WORK_REFERENCE
        , null as SHIP_TO_LOCATION_ID
        , null as ONE_TIME_FLAG
        , null as FUTURE_DATED_PAYMENT_CCID
        , null as WOMEN_OWNED_FLAG
        , null as CREATED_BY
        , null as LAST_UPDATED_BY
        , null as HOLD_REASON
        , null as WITHHOLDING_START_DATE
        , null as VAT_CODE
        , null as VERIFICATION_NUMBER
        , null as PARTNERSHIP_NAME
        , null as RECEIPT_REQUIRED_FLAG
        , null as FEDERAL_REPORTABLE_FLAG
        , null as INDIVIDUAL_1099
        , null as TCA_SYNC_VENDOR_NAME
        , null as ENFORCE_SHIP_TO_LOCATION_CODE
        , null as TAX_REPORTING_NAME
        , null as TERMS_ID
        , null as ATTRIBUTE_CATEGORY
        , null as PROGRAM_APPLICATION_ID
        , null as VALIDATION_NUMBER
        , null as AUTO_TAX_CALC_FLAG
        , null as EXCLUDE_FREIGHT_FROM_DISCOUNT
        , null as BUS_CLASS_LAST_CERTIFIED_BY
        , null as TERMS_DATE_BASIS
        , null as PARTY_ID
        , null as PAY_AWT_GROUP_ID
        , null as PURCHASING_HOLD_REASON
        , null as ALLOW_SUBSTITUTE_RECEIPTS_FLAG
        , null as CREDIT_STATUS_LOOKUP_CODE
        , null as VAT_REGISTRATION_NUM
        , null as SET_OF_BOOKS_ID
        , null as PARTNERSHIP_UTR
        , null as REQUEST_ID
        , null as BANK_CHARGE_BEARER
        , null as FIRST_NAME
        , null as HOLD_FUTURE_PAYMENTS_FLAG
        , null as PAYMENT_PRIORITY
        , null as RECEIPT_DAYS_EXCEPTION_CODE
        , null as DISC_TAKEN_CODE_COMBINATION_ID
        , null as PAYMENT_METHOD_LOOKUP_CODE
        , null as CIS_PARENT_VENDOR_ID
        , null as TYPE_1099
        , null as STANDARD_INDUSTRY_CLASS
        , null as VERIFICATION_REQUEST_ID
        , null as PAYMENT_CURRENCY_CODE
        , null as HOLD_ALL_PAYMENTS_FLAG
        , null as CIS_VERIFICATION_DATE
        , null as SUMMARY_FLAG
        , null as QTY_RCV_TOLERANCE
        , null as ALLOW_UNORDERED_RECEIPTS_FLAG
        , null as SEGMENT2
        , null as LAST_UPDATE_LOGIN
        , null as MATCH_OPTION
        , null as ENABLED_FLAG
        , null as GLOBAL_ATTRIBUTE_CATEGORY
        , null as SHIP_VIA_LOOKUP_CODE
        , null as FOB_LOOKUP_CODE
        , null as DAYS_EARLY_RECEIPT_ALLOWED
        , null as HOLD_UNMATCHED_INVOICES_FLAG
        , null as MIN_ORDER_AMOUNT
        , null as PAY_GROUP_LOOKUP_CODE
        , null as _FIVETRAN_DELETED
        , null as _FIVETRAN_ID
        , null as _FIVETRAN_SYNCED
        , null as PROGRAM_UPDATE_DATE
        , null as START_DATE_ACTIVE
        , null as END_DATE_ACTIVE
        , null as CREATION_DATE
        , null as LAST_UPDATE_DATE
        , '1900-01-01'::TIMESTAMP AS PSA_LOAD_DTS
        , 'N' AS PSA_DELETE_IND
        , 'USAZET.SNOWFLAKE.FBIN.DERIVED' AS REC_SRC
        , DECODE(GR.VALUE, 0, 'GHOST RECORD-SYSTEM', -1, 'GHOST RECORD-nullkey-required', -2, 'GHOST RECORD-nullkey-optional')  AS  BKCC
        , ''::BINARY as HASH_DIFF
        FROM
        TABLE(strtok_split_to_table('0|-1|-2', '|')) AS GR
{% endif %}