---- SRC LAYER ----
WITH
SRC_SORDHML        as ( SELECT * FROM {{ ref('v_psa_stg_order_header__ml_ebs') }} as SRC 
                         {% if is_incremental() %}
                         WHERE SRC.LOAD_DTS > (SELECT DATEADD('HOUR', '-1', MAX(LOAD_DTS)) FROM {{this}})
                         {% endif %}  )

/*
SRC_SORDHML        as ( SELECT * FROM STAGING.v_psa_stg_order_header__ML_EBS )
*/
---- LOGIC LAYER ----

, LOGIC_SORDHML as (
    SELECT
        ORDER_HEADER_HK
      , ORDER_NUMBER
      , HEADER_ID
      , SOLD_TO_PHONE_ID
      , ORG_ID
      , SOURCE_DOCUMENT_VERSION_NUMBER
      , IB_CURRENT_LOCATION
      , CONVERSION_RATE_DATE
      , PROGRAM_ID
      , CONTEXT
      , SHIPMENT_PRIORITY_CODE
      , CANCELLED_FLAG
      , DELIVER_TO_ORG_ID
      , PARTIAL_SHIPMENTS_ALLOWED
      , DELIVER_TO_CONTACT_ID
      , CUSTOMER_SIGNATURE_DATE
      , GLOBAL_ATTRIBUTE5
      , GLOBAL_ATTRIBUTE4
      , GLOBAL_ATTRIBUTE7
      , GLOBAL_ATTRIBUTE6
      , GLOBAL_ATTRIBUTE1
      , ORDER_FIRMED_DATE
      , GLOBAL_ATTRIBUTE3
      , GLOBAL_ATTRIBUTE2
      , PAYMENT_TYPE_CODE
      , UPGRADED_FLAG
      , FOB_POINT_CODE
      , GLOBAL_ATTRIBUTE9
      , GLOBAL_ATTRIBUTE8
      , TAX_EXEMPT_REASON_CODE
      , ORDER_SOURCE_ID
      , ATTRIBUTE3
      , ATTRIBUTE2
      , DEFAULT_FULFILLMENT_SET
      , ATTRIBUTE1
      , CREDIT_CARD_APPROVAL_CODE
      , TP_ATTRIBUTE15
      , FREIGHT_CARRIER_CODE
      , TP_ATTRIBUTE14
      , CREDIT_CARD_EXPIRATION_DATE
      , LAST_ACK_DATE
      , TP_ATTRIBUTE13
      , TP_ATTRIBUTE12
      , TP_ATTRIBUTE11
      , TP_ATTRIBUTE10
      , ATTRIBUTE9
      , BOOKED_FLAG
      , ATTRIBUTE8
      , ATTRIBUTE7
      , ATTRIBUTE6
      , SUPPLIER_SIGNATURE_DATE
      , ATTRIBUTE5
      , ATTRIBUTE4
      , CUST_PO_NUMBER
      , TRANSACTION_PHASE_CODE
      , AGREEMENT_ID
      , CONVERSION_TYPE_CODE
      , SHIP_TOLERANCE_BELOW
      , BLANKET_NUMBER
      , TRANSACTIONAL_CURR_CODE
      , ORDER_CATEGORY_CODE
      , ATTRIBUTE10
      , ORIG_SYS_DOCUMENT_REF
      , SHIP_TO_CONTACT_ID
      , TP_CONTEXT
      , ATTRIBUTE14
      , CUSTOMER_SIGNATURE
      , ATTRIBUTE13
      , CUSTOMER_PAYMENT_TERM_ID
      , ATTRIBUTE12
      , ATTRIBUTE11
      , IB_INSTALLED_AT_LOCATION
      , DROP_SHIP_FLAG
      , SHIP_TOLERANCE_ABOVE
      , FLOW_STATUS_CODE
      , VERSION_NUMBER
      , SALES_CHANNEL_CODE
      , SOLD_TO_CONTACT_ID
      , CHECK_NUMBER
      , SALESREP_ID
      , ACCOUNTING_RULE_DURATION
      , ORDER_TYPE_ID
      , LINE_SET_NAME
      , INVOICE_TO_CONTACT_ID
      , ATTRIBUTE20
      , SUPPLIER_SIGNATURE
      , GLOBAL_ATTRIBUTE20
      , SALES_DOCUMENT_NAME
      , GLOBAL_ATTRIBUTE17
      , GLOBAL_ATTRIBUTE18
      , GLOBAL_ATTRIBUTE15
      , GLOBAL_ATTRIBUTE16
      , GLOBAL_ATTRIBUTE13
      , GLOBAL_ATTRIBUTE14
      , RETURN_REASON_CODE
      , GLOBAL_ATTRIBUTE11
      , GLOBAL_ATTRIBUTE12
      , ATTRIBUTE18
      , ATTRIBUTE17
      , ATTRIBUTE16
      , ATTRIBUTE15
      , GLOBAL_ATTRIBUTE19
      , ATTRIBUTE19
      , FIRST_ACK_CODE
      , TAX_POINT_CODE
      , USER_STATUS_CODE
      , GLOBAL_ATTRIBUTE10
      , LOCK_CONTROL
      , SHIP_TO_ORG_ID
      , INVOICE_TO_ORG_ID
      , CHANGE_SEQUENCE
      , TP_ATTRIBUTE9
      , SOURCE_DOCUMENT_TYPE_ID
      , SOLD_TO_SITE_USE_ID
      , SOLD_FROM_ORG_ID
      , CREATED_BY
      , SHIPPING_INSTRUCTIONS
      , LAST_UPDATED_BY
      , EARLIEST_SCHEDULE_LIMIT
      , PAYMENT_TERM_ID
      , SHIPPING_METHOD_CODE
      , SOURCE_DOCUMENT_ID
      , PRICE_LIST_ID
      , TP_ATTRIBUTE8
      , INVOICING_RULE_ID
      , TP_ATTRIBUTE7
      , TP_ATTRIBUTE6
      , TP_ATTRIBUTE5
      , TP_ATTRIBUTE4
      , FULFILLMENT_SET_NAME
      , TP_ATTRIBUTE3
      , TP_ATTRIBUTE2
      , TP_ATTRIBUTE1
      , CUSTOMER_PREFERENCE_SET_CODE
      , END_CUSTOMER_CONTACT_ID
      , CREDIT_CARD_HOLDER_NAME
      , PAYMENT_AMOUNT
      , PROGRAM_APPLICATION_ID
      , PACKING_INSTRUCTIONS
      , END_CUSTOMER_ID
      , OPEN_FLAG
      , CREDIT_CARD_CODE
      , SHIP_FROM_ORG_ID
      , IB_OWNER
      , FIRST_ACK_DATE
      , QUOTE_NUMBER
      , SALES_DOCUMENT_TYPE_CODE
      , TAX_EXEMPT_NUMBER
      , REQUEST_ID
      , BATCH_ID
      , MARKETING_SOURCE_CODE_ID
      , DRAFT_SUBMITTED_FLAG
      , XML_MESSAGE_ID
      , LATEST_SCHEDULE_LIMIT
      , TAX_EXEMPT_FLAG
      , CREDIT_CARD_NUMBER
      , LAST_ACK_CODE
      , SOLD_TO_ORG_ID
      , CONVERSION_RATE
      , PRICE_REQUEST_CODE
      , ORDER_DATE_TYPE_CODE
      , LAST_UPDATE_LOGIN
      , ACCOUNTING_RULE_ID
      , END_CUSTOMER_SITE_USE_ID
      , GLOBAL_ATTRIBUTE_CATEGORY
      , DEMAND_CLASS_CODE
      , FREIGHT_TERMS_CODE
      , PROGRAM_UPDATE_DATE
      , MINISITE_ID
      , CREDIT_CARD_APPROVAL_DATE
      , BOOKED_DATE
      , ORDERED_DATE
      , REQUEST_DATE
      , CREATION_DATE
      , QUOTE_DATE
      , PRICING_DATE
      , EXPIRATION_DATE
      , LAST_UPDATE_DATE
      , _FIVETRAN_DELETED
      , _FIVETRAN_ID
      , _FIVETRAN_SYNCED
      , PSA_LOAD_DTS
      , PSA_RECORD_SOURCE
      , PSA_DELETE_IND
      , LOAD_DTS
      , REC_SRC
      , HASHDIFF
    FROM SRC_SORDHML
)
---- RENAME LAYER ----

, RENAME_SORDHML as (
    SELECT
        ORDER_HEADER_HK
      , ORDER_NUMBER
      , HEADER_ID
      , SOLD_TO_PHONE_ID
      , ORG_ID
      , SOURCE_DOCUMENT_VERSION_NUMBER
      , IB_CURRENT_LOCATION
      , CONVERSION_RATE_DATE
      , PROGRAM_ID
      , CONTEXT
      , SHIPMENT_PRIORITY_CODE
      , CANCELLED_FLAG
      , DELIVER_TO_ORG_ID
      , PARTIAL_SHIPMENTS_ALLOWED
      , DELIVER_TO_CONTACT_ID
      , CUSTOMER_SIGNATURE_DATE
      , GLOBAL_ATTRIBUTE5
      , GLOBAL_ATTRIBUTE4
      , GLOBAL_ATTRIBUTE7
      , GLOBAL_ATTRIBUTE6
      , GLOBAL_ATTRIBUTE1
      , ORDER_FIRMED_DATE
      , GLOBAL_ATTRIBUTE3
      , GLOBAL_ATTRIBUTE2
      , PAYMENT_TYPE_CODE
      , UPGRADED_FLAG
      , FOB_POINT_CODE
      , GLOBAL_ATTRIBUTE9
      , GLOBAL_ATTRIBUTE8
      , TAX_EXEMPT_REASON_CODE
      , ORDER_SOURCE_ID
      , ATTRIBUTE3
      , ATTRIBUTE2
      , DEFAULT_FULFILLMENT_SET
      , ATTRIBUTE1
      , CREDIT_CARD_APPROVAL_CODE
      , TP_ATTRIBUTE15
      , FREIGHT_CARRIER_CODE
      , TP_ATTRIBUTE14
      , CREDIT_CARD_EXPIRATION_DATE
      , LAST_ACK_DATE
      , TP_ATTRIBUTE13
      , TP_ATTRIBUTE12
      , TP_ATTRIBUTE11
      , TP_ATTRIBUTE10
      , ATTRIBUTE9
      , BOOKED_FLAG
      , ATTRIBUTE8
      , ATTRIBUTE7
      , ATTRIBUTE6
      , SUPPLIER_SIGNATURE_DATE
      , ATTRIBUTE5
      , ATTRIBUTE4
      , CUST_PO_NUMBER
      , TRANSACTION_PHASE_CODE
      , AGREEMENT_ID
      , CONVERSION_TYPE_CODE
      , SHIP_TOLERANCE_BELOW
      , BLANKET_NUMBER
      , TRANSACTIONAL_CURR_CODE
      , ORDER_CATEGORY_CODE
      , ATTRIBUTE10
      , ORIG_SYS_DOCUMENT_REF
      , SHIP_TO_CONTACT_ID
      , TP_CONTEXT
      , ATTRIBUTE14
      , CUSTOMER_SIGNATURE
      , ATTRIBUTE13
      , CUSTOMER_PAYMENT_TERM_ID
      , ATTRIBUTE12
      , ATTRIBUTE11
      , IB_INSTALLED_AT_LOCATION
      , DROP_SHIP_FLAG
      , SHIP_TOLERANCE_ABOVE
      , FLOW_STATUS_CODE
      , VERSION_NUMBER
      , SALES_CHANNEL_CODE
      , SOLD_TO_CONTACT_ID
      , CHECK_NUMBER
      , SALESREP_ID
      , ACCOUNTING_RULE_DURATION
      , ORDER_TYPE_ID
      , LINE_SET_NAME
      , INVOICE_TO_CONTACT_ID
      , ATTRIBUTE20
      , SUPPLIER_SIGNATURE
      , GLOBAL_ATTRIBUTE20
      , SALES_DOCUMENT_NAME
      , GLOBAL_ATTRIBUTE17
      , GLOBAL_ATTRIBUTE18
      , GLOBAL_ATTRIBUTE15
      , GLOBAL_ATTRIBUTE16
      , GLOBAL_ATTRIBUTE13
      , GLOBAL_ATTRIBUTE14
      , RETURN_REASON_CODE
      , GLOBAL_ATTRIBUTE11
      , GLOBAL_ATTRIBUTE12
      , ATTRIBUTE18
      , ATTRIBUTE17
      , ATTRIBUTE16
      , ATTRIBUTE15
      , GLOBAL_ATTRIBUTE19
      , ATTRIBUTE19
      , FIRST_ACK_CODE
      , TAX_POINT_CODE
      , USER_STATUS_CODE
      , GLOBAL_ATTRIBUTE10
      , LOCK_CONTROL
      , SHIP_TO_ORG_ID
      , INVOICE_TO_ORG_ID
      , CHANGE_SEQUENCE
      , TP_ATTRIBUTE9
      , SOURCE_DOCUMENT_TYPE_ID
      , SOLD_TO_SITE_USE_ID
      , SOLD_FROM_ORG_ID
      , CREATED_BY
      , SHIPPING_INSTRUCTIONS
      , LAST_UPDATED_BY
      , EARLIEST_SCHEDULE_LIMIT
      , PAYMENT_TERM_ID
      , SHIPPING_METHOD_CODE
      , SOURCE_DOCUMENT_ID
      , PRICE_LIST_ID
      , TP_ATTRIBUTE8
      , INVOICING_RULE_ID
      , TP_ATTRIBUTE7
      , TP_ATTRIBUTE6
      , TP_ATTRIBUTE5
      , TP_ATTRIBUTE4
      , FULFILLMENT_SET_NAME
      , TP_ATTRIBUTE3
      , TP_ATTRIBUTE2
      , TP_ATTRIBUTE1
      , CUSTOMER_PREFERENCE_SET_CODE
      , END_CUSTOMER_CONTACT_ID
      , CREDIT_CARD_HOLDER_NAME
      , PAYMENT_AMOUNT
      , PROGRAM_APPLICATION_ID
      , PACKING_INSTRUCTIONS
      , END_CUSTOMER_ID
      , OPEN_FLAG
      , CREDIT_CARD_CODE
      , SHIP_FROM_ORG_ID
      , IB_OWNER
      , FIRST_ACK_DATE
      , QUOTE_NUMBER
      , SALES_DOCUMENT_TYPE_CODE
      , TAX_EXEMPT_NUMBER
      , REQUEST_ID
      , BATCH_ID
      , MARKETING_SOURCE_CODE_ID
      , DRAFT_SUBMITTED_FLAG
      , XML_MESSAGE_ID
      , LATEST_SCHEDULE_LIMIT
      , TAX_EXEMPT_FLAG
      , CREDIT_CARD_NUMBER
      , LAST_ACK_CODE
      , SOLD_TO_ORG_ID
      , CONVERSION_RATE
      , PRICE_REQUEST_CODE
      , ORDER_DATE_TYPE_CODE
      , LAST_UPDATE_LOGIN
      , ACCOUNTING_RULE_ID
      , END_CUSTOMER_SITE_USE_ID
      , GLOBAL_ATTRIBUTE_CATEGORY
      , DEMAND_CLASS_CODE
      , FREIGHT_TERMS_CODE
      , PROGRAM_UPDATE_DATE
      , MINISITE_ID
      , CREDIT_CARD_APPROVAL_DATE
      , BOOKED_DATE
      , ORDERED_DATE
      , REQUEST_DATE
      , CREATION_DATE
      , QUOTE_DATE
      , PRICING_DATE
      , EXPIRATION_DATE
      , LAST_UPDATE_DATE
      , _FIVETRAN_DELETED
      , _FIVETRAN_ID
      , _FIVETRAN_SYNCED
      , PSA_LOAD_DTS
      , PSA_RECORD_SOURCE
      , PSA_DELETE_IND
      , LOAD_DTS
      , REC_SRC
      , HASHDIFF
    FROM LOGIC_SORDHML
)
---- FILTER LAYER ----

, FILTER_SORDHML as (
    SELECT *
    FROM RENAME_SORDHML
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM FILTER_SORDHML
)

---- FINAL LAYER ----
SELECT
          ORDER_HEADER_HK
        , ORDER_NUMBER
        , HEADER_ID
        , SOLD_TO_PHONE_ID
        , ORG_ID
        , SOURCE_DOCUMENT_VERSION_NUMBER
        , IB_CURRENT_LOCATION
        , CONVERSION_RATE_DATE
        , PROGRAM_ID
        , CONTEXT
        , SHIPMENT_PRIORITY_CODE
        , CANCELLED_FLAG
        , DELIVER_TO_ORG_ID
        , PARTIAL_SHIPMENTS_ALLOWED
        , DELIVER_TO_CONTACT_ID
        , CUSTOMER_SIGNATURE_DATE
        , GLOBAL_ATTRIBUTE5
        , GLOBAL_ATTRIBUTE4
        , GLOBAL_ATTRIBUTE7
        , GLOBAL_ATTRIBUTE6
        , GLOBAL_ATTRIBUTE1
        , ORDER_FIRMED_DATE
        , GLOBAL_ATTRIBUTE3
        , GLOBAL_ATTRIBUTE2
        , PAYMENT_TYPE_CODE
        , UPGRADED_FLAG
        , FOB_POINT_CODE
        , GLOBAL_ATTRIBUTE9
        , GLOBAL_ATTRIBUTE8
        , TAX_EXEMPT_REASON_CODE
        , ORDER_SOURCE_ID
        , ATTRIBUTE3
        , ATTRIBUTE2
        , DEFAULT_FULFILLMENT_SET
        , ATTRIBUTE1
        , CREDIT_CARD_APPROVAL_CODE
        , TP_ATTRIBUTE15
        , FREIGHT_CARRIER_CODE
        , TP_ATTRIBUTE14
        , CREDIT_CARD_EXPIRATION_DATE
        , LAST_ACK_DATE
        , TP_ATTRIBUTE13
        , TP_ATTRIBUTE12
        , TP_ATTRIBUTE11
        , TP_ATTRIBUTE10
        , ATTRIBUTE9
        , BOOKED_FLAG
        , ATTRIBUTE8
        , ATTRIBUTE7
        , ATTRIBUTE6
        , SUPPLIER_SIGNATURE_DATE
        , ATTRIBUTE5
        , ATTRIBUTE4
        , CUST_PO_NUMBER
        , TRANSACTION_PHASE_CODE
        , AGREEMENT_ID
        , CONVERSION_TYPE_CODE
        , SHIP_TOLERANCE_BELOW
        , BLANKET_NUMBER
        , TRANSACTIONAL_CURR_CODE
        , ORDER_CATEGORY_CODE
        , ATTRIBUTE10
        , ORIG_SYS_DOCUMENT_REF
        , SHIP_TO_CONTACT_ID
        , TP_CONTEXT
        , ATTRIBUTE14
        , CUSTOMER_SIGNATURE
        , ATTRIBUTE13
        , CUSTOMER_PAYMENT_TERM_ID
        , ATTRIBUTE12
        , ATTRIBUTE11
        , IB_INSTALLED_AT_LOCATION
        , DROP_SHIP_FLAG
        , SHIP_TOLERANCE_ABOVE
        , FLOW_STATUS_CODE
        , VERSION_NUMBER
        , SALES_CHANNEL_CODE
        , SOLD_TO_CONTACT_ID
        , CHECK_NUMBER
        , SALESREP_ID
        , ACCOUNTING_RULE_DURATION
        , ORDER_TYPE_ID
        , LINE_SET_NAME
        , INVOICE_TO_CONTACT_ID
        , ATTRIBUTE20
        , SUPPLIER_SIGNATURE
        , GLOBAL_ATTRIBUTE20
        , SALES_DOCUMENT_NAME
        , GLOBAL_ATTRIBUTE17
        , GLOBAL_ATTRIBUTE18
        , GLOBAL_ATTRIBUTE15
        , GLOBAL_ATTRIBUTE16
        , GLOBAL_ATTRIBUTE13
        , GLOBAL_ATTRIBUTE14
        , RETURN_REASON_CODE
        , GLOBAL_ATTRIBUTE11
        , GLOBAL_ATTRIBUTE12
        , ATTRIBUTE18
        , ATTRIBUTE17
        , ATTRIBUTE16
        , ATTRIBUTE15
        , GLOBAL_ATTRIBUTE19
        , ATTRIBUTE19
        , FIRST_ACK_CODE
        , TAX_POINT_CODE
        , USER_STATUS_CODE
        , GLOBAL_ATTRIBUTE10
        , LOCK_CONTROL
        , SHIP_TO_ORG_ID
        , INVOICE_TO_ORG_ID
        , CHANGE_SEQUENCE
        , TP_ATTRIBUTE9
        , SOURCE_DOCUMENT_TYPE_ID
        , SOLD_TO_SITE_USE_ID
        , SOLD_FROM_ORG_ID
        , CREATED_BY
        , SHIPPING_INSTRUCTIONS
        , LAST_UPDATED_BY
        , EARLIEST_SCHEDULE_LIMIT
        , PAYMENT_TERM_ID
        , SHIPPING_METHOD_CODE
        , SOURCE_DOCUMENT_ID
        , PRICE_LIST_ID
        , TP_ATTRIBUTE8
        , INVOICING_RULE_ID
        , TP_ATTRIBUTE7
        , TP_ATTRIBUTE6
        , TP_ATTRIBUTE5
        , TP_ATTRIBUTE4
        , FULFILLMENT_SET_NAME
        , TP_ATTRIBUTE3
        , TP_ATTRIBUTE2
        , TP_ATTRIBUTE1
        , CUSTOMER_PREFERENCE_SET_CODE
        , END_CUSTOMER_CONTACT_ID
        , CREDIT_CARD_HOLDER_NAME
        , PAYMENT_AMOUNT
        , PROGRAM_APPLICATION_ID
        , PACKING_INSTRUCTIONS
        , END_CUSTOMER_ID
        , OPEN_FLAG
        , CREDIT_CARD_CODE
        , SHIP_FROM_ORG_ID
        , IB_OWNER
        , FIRST_ACK_DATE
        , QUOTE_NUMBER
        , SALES_DOCUMENT_TYPE_CODE
        , TAX_EXEMPT_NUMBER
        , REQUEST_ID
        , BATCH_ID
        , MARKETING_SOURCE_CODE_ID
        , DRAFT_SUBMITTED_FLAG
        , XML_MESSAGE_ID
        , LATEST_SCHEDULE_LIMIT
        , TAX_EXEMPT_FLAG
        , CREDIT_CARD_NUMBER
        , LAST_ACK_CODE
        , SOLD_TO_ORG_ID
        , CONVERSION_RATE
        , PRICE_REQUEST_CODE
        , ORDER_DATE_TYPE_CODE
        , LAST_UPDATE_LOGIN
        , ACCOUNTING_RULE_ID
        , END_CUSTOMER_SITE_USE_ID
        , GLOBAL_ATTRIBUTE_CATEGORY
        , DEMAND_CLASS_CODE
        , FREIGHT_TERMS_CODE
        , PROGRAM_UPDATE_DATE
        , MINISITE_ID
        , CREDIT_CARD_APPROVAL_DATE
        , BOOKED_DATE
        , ORDERED_DATE
        , REQUEST_DATE
        , CREATION_DATE
        , QUOTE_DATE
        , PRICING_DATE
        , EXPIRATION_DATE
        , LAST_UPDATE_DATE
        , _FIVETRAN_DELETED
        , _FIVETRAN_ID
        , _FIVETRAN_SYNCED
        , PSA_LOAD_DTS
        , PSA_RECORD_SOURCE
        , PSA_DELETE_IND
        , LOAD_DTS
        , REC_SRC
        , HASHDIFF
FROM JOIN_RESULT
{% if is_incremental() %}
WHERE NOT EXISTS (
    SELECT 1 
    FROM {{ this }} existing
    WHERE existing.ORDER_HEADER_HK= JOIN_RESULT.ORDER_HEADER_HK
    AND existing.HASHDIFF = JOIN_RESULT.HASHDIFF
)
{% endif %} 
{% if not is_incremental() %}
/*the following qualify is to restrict multiple loads of touched records during the initial build. Ex: multiple row per hk, hashdiff */
qualify 1= row_number()over(partition by ORDER_HEADER_HK, HASHDIFF order by PSA_LOAD_DTS)
union all
    SELECT        
    MD5_BINARY(GR.VALUE) AS ORDER_HEADER_HK
, GR.VALUE::NUMBER as ORDER_NUMBER
    , null as HEADER_ID
    , null as SOLD_TO_PHONE_ID
    , null as ORG_ID
    , null as SOURCE_DOCUMENT_VERSION_NUMBER
    , null as IB_CURRENT_LOCATION
    , null as CONVERSION_RATE_DATE
    , null as PROGRAM_ID
    , null as CONTEXT
    , null as SHIPMENT_PRIORITY_CODE
    , null as CANCELLED_FLAG
    , null as DELIVER_TO_ORG_ID
    , null as PARTIAL_SHIPMENTS_ALLOWED
    , null as DELIVER_TO_CONTACT_ID
    , null as CUSTOMER_SIGNATURE_DATE
    , null as GLOBAL_ATTRIBUTE5
    , null as GLOBAL_ATTRIBUTE4
    , null as GLOBAL_ATTRIBUTE7
    , null as GLOBAL_ATTRIBUTE6
    , null as GLOBAL_ATTRIBUTE1
    , null as ORDER_FIRMED_DATE
    , null as GLOBAL_ATTRIBUTE3
    , null as GLOBAL_ATTRIBUTE2
    , null as PAYMENT_TYPE_CODE
    , null as UPGRADED_FLAG
    , null as FOB_POINT_CODE
    , null as GLOBAL_ATTRIBUTE9
    , null as GLOBAL_ATTRIBUTE8
    , null as TAX_EXEMPT_REASON_CODE
    , null as ORDER_SOURCE_ID
    , null as ATTRIBUTE3
    , null as ATTRIBUTE2
    , null as DEFAULT_FULFILLMENT_SET
    , null as ATTRIBUTE1
    , null as CREDIT_CARD_APPROVAL_CODE
    , null as TP_ATTRIBUTE15
    , null as FREIGHT_CARRIER_CODE
    , null as TP_ATTRIBUTE14
    , null as CREDIT_CARD_EXPIRATION_DATE
    , null as LAST_ACK_DATE
    , null as TP_ATTRIBUTE13
    , null as TP_ATTRIBUTE12
    , null as TP_ATTRIBUTE11
    , null as TP_ATTRIBUTE10
    , null as ATTRIBUTE9
    , null as BOOKED_FLAG
    , null as ATTRIBUTE8
    , null as ATTRIBUTE7
    , null as ATTRIBUTE6
    , null as SUPPLIER_SIGNATURE_DATE
    , null as ATTRIBUTE5
    , null as ATTRIBUTE4
    , null as CUST_PO_NUMBER
    , null as TRANSACTION_PHASE_CODE
    , null as AGREEMENT_ID
    , null as CONVERSION_TYPE_CODE
    , null as SHIP_TOLERANCE_BELOW
    , null as BLANKET_NUMBER
    , null as TRANSACTIONAL_CURR_CODE
    , null as ORDER_CATEGORY_CODE
    , null as ATTRIBUTE10
    , null as ORIG_SYS_DOCUMENT_REF
    , null as SHIP_TO_CONTACT_ID
    , null as TP_CONTEXT
    , null as ATTRIBUTE14
    , null as CUSTOMER_SIGNATURE
    , null as ATTRIBUTE13
    , null as CUSTOMER_PAYMENT_TERM_ID
    , null as ATTRIBUTE12
    , null as ATTRIBUTE11
    , null as IB_INSTALLED_AT_LOCATION
    , null as DROP_SHIP_FLAG
    , null as SHIP_TOLERANCE_ABOVE
    , null as FLOW_STATUS_CODE
    , null as VERSION_NUMBER
    , null as SALES_CHANNEL_CODE
    , null as SOLD_TO_CONTACT_ID
    , null as CHECK_NUMBER
    , null as SALESREP_ID
    , null as ACCOUNTING_RULE_DURATION
    , null as ORDER_TYPE_ID
    , null as LINE_SET_NAME
    , null as INVOICE_TO_CONTACT_ID
    , null as ATTRIBUTE20
    , null as SUPPLIER_SIGNATURE
    , null as GLOBAL_ATTRIBUTE20
    , null as SALES_DOCUMENT_NAME
    , null as GLOBAL_ATTRIBUTE17
    , null as GLOBAL_ATTRIBUTE18
    , null as GLOBAL_ATTRIBUTE15
    , null as GLOBAL_ATTRIBUTE16
    , null as GLOBAL_ATTRIBUTE13
    , null as GLOBAL_ATTRIBUTE14
    , null as RETURN_REASON_CODE
    , null as GLOBAL_ATTRIBUTE11
    , null as GLOBAL_ATTRIBUTE12
    , null as ATTRIBUTE18
    , null as ATTRIBUTE17
    , null as ATTRIBUTE16
    , null as ATTRIBUTE15
    , null as GLOBAL_ATTRIBUTE19
    , null as ATTRIBUTE19
    , null as FIRST_ACK_CODE
    , null as TAX_POINT_CODE
    , null as USER_STATUS_CODE
    , null as GLOBAL_ATTRIBUTE10
    , null as LOCK_CONTROL
    , null as SHIP_TO_ORG_ID
    , null as INVOICE_TO_ORG_ID
    , null as CHANGE_SEQUENCE
    , null as TP_ATTRIBUTE9
    , null as SOURCE_DOCUMENT_TYPE_ID
    , null as SOLD_TO_SITE_USE_ID
    , null as SOLD_FROM_ORG_ID
    , null as CREATED_BY
    , null as SHIPPING_INSTRUCTIONS
    , null as LAST_UPDATED_BY
    , null as EARLIEST_SCHEDULE_LIMIT
    , null as PAYMENT_TERM_ID
    , null as SHIPPING_METHOD_CODE
    , null as SOURCE_DOCUMENT_ID
    , null as PRICE_LIST_ID
    , null as TP_ATTRIBUTE8
    , null as INVOICING_RULE_ID
    , null as TP_ATTRIBUTE7
    , null as TP_ATTRIBUTE6
    , null as TP_ATTRIBUTE5
    , null as TP_ATTRIBUTE4
    , null as FULFILLMENT_SET_NAME
    , null as TP_ATTRIBUTE3
    , null as TP_ATTRIBUTE2
    , null as TP_ATTRIBUTE1
    , null as CUSTOMER_PREFERENCE_SET_CODE
    , null as END_CUSTOMER_CONTACT_ID
    , null as CREDIT_CARD_HOLDER_NAME
    , null as PAYMENT_AMOUNT
    , null as PROGRAM_APPLICATION_ID
    , null as PACKING_INSTRUCTIONS
    , null as END_CUSTOMER_ID
    , null as OPEN_FLAG
    , null as CREDIT_CARD_CODE
    , null as SHIP_FROM_ORG_ID
    , null as IB_OWNER
    , null as FIRST_ACK_DATE
    , null as QUOTE_NUMBER
    , null as SALES_DOCUMENT_TYPE_CODE
    , null as TAX_EXEMPT_NUMBER
    , null as REQUEST_ID
    , null as BATCH_ID
    , null as MARKETING_SOURCE_CODE_ID
    , null as DRAFT_SUBMITTED_FLAG
    , null as XML_MESSAGE_ID
    , null as LATEST_SCHEDULE_LIMIT
    , null as TAX_EXEMPT_FLAG
    , null as CREDIT_CARD_NUMBER
    , null as LAST_ACK_CODE
    , null as SOLD_TO_ORG_ID
    , null as CONVERSION_RATE
    , null as PRICE_REQUEST_CODE
    , null as ORDER_DATE_TYPE_CODE
    , null as LAST_UPDATE_LOGIN
    , null as ACCOUNTING_RULE_ID
    , null as END_CUSTOMER_SITE_USE_ID
    , null as GLOBAL_ATTRIBUTE_CATEGORY
    , null as DEMAND_CLASS_CODE
    , null as FREIGHT_TERMS_CODE
    , null as PROGRAM_UPDATE_DATE
    , null as MINISITE_ID
    , null as CREDIT_CARD_APPROVAL_DATE
    , null as BOOKED_DATE
    , null as ORDERED_DATE
    , null as REQUEST_DATE
    , null as CREATION_DATE
    , null as QUOTE_DATE
    , null as PRICING_DATE
    , null as EXPIRATION_DATE
    , null as LAST_UPDATE_DATE
    , null as _FIVETRAN_DELETED
    , null as _FIVETRAN_ID
    , null as _FIVETRAN_SYNCED
    , null as PSA_LOAD_DTS
    , null as PSA_RECORD_SOURCE
    , null as PSA_DELETE_IND
,  CONVERT_TIMEZONE('UTC','1900-01-01'::TIMESTAMP) as  LOAD_DTS
,'USAZET.SNOWFLAKE.FBIN.DERIVED' AS REC_SRC
, ''::BINARY as HASHDIFF FROM
        TABLE(strtok_split_to_table('0|-1|-2', '|')) AS GR
{% endif %}