---- SRC LAYER ----
WITH
SRC_psa_addr       as ( SELECT * FROM {{ ref('v_psa_stg_customer_site_address__ml_ebs') }} as SRC 
                        {% if is_incremental() %}
                        WHERE SRC.LOAD_DTS > (SELECT DATEADD('HOUR', '-1', MAX(LOAD_DTS)) FROM {{this}}){% endif %} )

/*
SRC_psa_addr       as ( SELECT * FROM STAGING.V_PSA_STG_CUSTOMER_SITE_ADDRESS__ML_EBS )
*/
---- LOGIC LAYER ----

, LOGIC_psa_addr as (
    SELECT
        CUSTOMER_SITE_HK
      , ACCOUNT_NUMBER
      , CUST_ACCT_SITE_ID
      , LOCATION_ID
      , RURAL_ROUTE_NUMBER
      , SALES_TAX_INSIDE_CITY_LIMITS
      , STREET_SUFFIX
      , PROGRAM_ID
      , DO_NOT_VALIDATE_FLAG
      , GLOBAL_ATTRIBUTE5
      , GLOBAL_ATTRIBUTE4
      , POSITION
      , GLOBAL_ATTRIBUTE7
      , FLOOR
      , GLOBAL_ATTRIBUTE6
      , GLOBAL_ATTRIBUTE1
      , GLOBAL_ATTRIBUTE3
      , GLOBAL_ATTRIBUTE2
      , ADDRESS_KEY
      , GLOBAL_ATTRIBUTE9
      , GLOBAL_ATTRIBUTE8
      , CONTENT_SOURCE_TYPE
      , ATTRIBUTE3
      , LANGUAGE
      , CREATED_BY_MODULE
      , ATTRIBUTE2
      , ORIG_SYSTEM_REFERENCE
      , ATTRIBUTE1
      , ATTRIBUTE9
      , ATTRIBUTE8
      , ATTRIBUTE7
      , ATTRIBUTE6
      , ATTRIBUTE5
      , ATTRIBUTE4
      , SHORT_DESCRIPTION
      , ADDRESS_ERROR_CODE
      , ATTRIBUTE10
      , HOUSE_NUMBER
      , ADDRESS_LINES_PHONETIC
      , ATTRIBUTE14
      , ATTRIBUTE13
      , ATTRIBUTE12
      , ATTRIBUTE11
      , DELIVERY_POINT_CODE
      , SECONDARY_SUFFIX_ELEMENT
      , TIMEZONE_ID
      , SALES_TAX_GEOCODE
      , POSTAL_CODE
      , POST_OFFICE
      , DESCRIPTION
      , ADDRESS_EFFECTIVE_DATE
      , ATTRIBUTE20
      , SUITE
      , GEOMETRY_STATUS_CODE
      , GLOBAL_ATTRIBUTE20
      , STREET
      , GLOBAL_ATTRIBUTE17
      , GLOBAL_ATTRIBUTE18
      , GLOBAL_ATTRIBUTE15
      , GLOBAL_ATTRIBUTE16
      , GLOBAL_ATTRIBUTE13
      , CITY
      , FA_LOCATION_ID
      , GLOBAL_ATTRIBUTE14
      , GLOBAL_ATTRIBUTE11
      , GLOBAL_ATTRIBUTE12
      , ATTRIBUTE18
      , ATTRIBUTE17
      , ATTRIBUTE16
      , ATTRIBUTE15
      , GLOBAL_ATTRIBUTE19
      , ATTRIBUTE19
      , POSTAL_PLUS4_CODE
      , RURAL_ROUTE_TYPE
      , STREET_NUMBER
      , OVERSEAS_ADDRESS_FLAG
      , GLOBAL_ATTRIBUTE10
      , LAST_UPDATE_DATE
      , GEOMETRY_SOURCE
      , LOCATION_DIRECTIONS
      , OBJECT_VERSION_NUMBER
      , COUNTRY
      , LIFE_CYCLE_STATUS
      , COUNTY
      , CREATED_BY
      , LAST_UPDATED_BY
      , CREATION_DATE
      , PROGRAM_UPDATE_DATE
      , APARTMENT_FLAG
      , ATTRIBUTE_CATEGORY
      , ACTUAL_CONTENT_SOURCE
      , PROGRAM_APPLICATION_ID
      , LOC_HIERARCHY_ID
      , VALIDATION_STATUS_CODE
      , APPLICATION_ID
      , STATE
      , REQUEST_ID
      , APARTMENT_NUMBER
      , ADDRESS_STYLE
      , DATE_VALIDATED
      , TIME_ZONE
      , BUILDING
      , ADDRESS1
      , ADDRESS_EXPIRATION_DATE
      , ADDRESS3
      , ADDRESS2
      , ADDRESS4
      , DODAAC
      , LAST_UPDATE_LOGIN
      , PO_BOX_NUMBER
      , CLLI_CODE
      , GLOBAL_ATTRIBUTE_CATEGORY
      , VALIDATED_FLAG
      , WH_UPDATE_DATE
      , PROVINCE
      , ROOM
      , TRAILING_DIRECTORY_CODE
      , _FIVETRAN_DELETED
      , _FIVETRAN_SYNCED
      , PSA_DELETE_IND
      , PSA_LOAD_DTS
      , PSA_RECORD_SOURCE
      , LOAD_DTS
      , REC_SRC
      , HASHDIFF
      , BKCC
    FROM SRC_psa_addr
)
---- RENAME LAYER ----

, RENAME_psa_addr as (
    SELECT
        CUSTOMER_SITE_HK
      , ACCOUNT_NUMBER
      , CUST_ACCT_SITE_ID
      , LOCATION_ID
      , RURAL_ROUTE_NUMBER
      , SALES_TAX_INSIDE_CITY_LIMITS
      , STREET_SUFFIX
      , PROGRAM_ID
      , DO_NOT_VALIDATE_FLAG
      , GLOBAL_ATTRIBUTE5
      , GLOBAL_ATTRIBUTE4
      , POSITION
      , GLOBAL_ATTRIBUTE7
      , FLOOR
      , GLOBAL_ATTRIBUTE6
      , GLOBAL_ATTRIBUTE1
      , GLOBAL_ATTRIBUTE3
      , GLOBAL_ATTRIBUTE2
      , ADDRESS_KEY
      , GLOBAL_ATTRIBUTE9
      , GLOBAL_ATTRIBUTE8
      , CONTENT_SOURCE_TYPE
      , ATTRIBUTE3
      , LANGUAGE
      , CREATED_BY_MODULE
      , ATTRIBUTE2
      , ORIG_SYSTEM_REFERENCE
      , ATTRIBUTE1
      , ATTRIBUTE9
      , ATTRIBUTE8
      , ATTRIBUTE7
      , ATTRIBUTE6
      , ATTRIBUTE5
      , ATTRIBUTE4
      , SHORT_DESCRIPTION
      , ADDRESS_ERROR_CODE
      , ATTRIBUTE10
      , HOUSE_NUMBER
      , ADDRESS_LINES_PHONETIC
      , ATTRIBUTE14
      , ATTRIBUTE13
      , ATTRIBUTE12
      , ATTRIBUTE11
      , DELIVERY_POINT_CODE
      , SECONDARY_SUFFIX_ELEMENT
      , TIMEZONE_ID
      , SALES_TAX_GEOCODE
      , POSTAL_CODE
      , POST_OFFICE
      , DESCRIPTION
      , ADDRESS_EFFECTIVE_DATE
      , ATTRIBUTE20
      , SUITE
      , GEOMETRY_STATUS_CODE
      , GLOBAL_ATTRIBUTE20
      , STREET
      , GLOBAL_ATTRIBUTE17
      , GLOBAL_ATTRIBUTE18
      , GLOBAL_ATTRIBUTE15
      , GLOBAL_ATTRIBUTE16
      , GLOBAL_ATTRIBUTE13
      , CITY
      , FA_LOCATION_ID
      , GLOBAL_ATTRIBUTE14
      , GLOBAL_ATTRIBUTE11
      , GLOBAL_ATTRIBUTE12
      , ATTRIBUTE18
      , ATTRIBUTE17
      , ATTRIBUTE16
      , ATTRIBUTE15
      , GLOBAL_ATTRIBUTE19
      , ATTRIBUTE19
      , POSTAL_PLUS4_CODE
      , RURAL_ROUTE_TYPE
      , STREET_NUMBER
      , OVERSEAS_ADDRESS_FLAG
      , GLOBAL_ATTRIBUTE10
      , LAST_UPDATE_DATE
      , GEOMETRY_SOURCE
      , LOCATION_DIRECTIONS
      , OBJECT_VERSION_NUMBER
      , COUNTRY
      , LIFE_CYCLE_STATUS
      , COUNTY
      , CREATED_BY
      , LAST_UPDATED_BY
      , CREATION_DATE
      , PROGRAM_UPDATE_DATE
      , APARTMENT_FLAG
      , ATTRIBUTE_CATEGORY
      , ACTUAL_CONTENT_SOURCE
      , PROGRAM_APPLICATION_ID
      , LOC_HIERARCHY_ID
      , VALIDATION_STATUS_CODE
      , APPLICATION_ID
      , STATE
      , REQUEST_ID
      , APARTMENT_NUMBER
      , ADDRESS_STYLE
      , DATE_VALIDATED
      , TIME_ZONE
      , BUILDING
      , ADDRESS1
      , ADDRESS_EXPIRATION_DATE
      , ADDRESS3
      , ADDRESS2
      , ADDRESS4
      , DODAAC
      , LAST_UPDATE_LOGIN
      , PO_BOX_NUMBER
      , CLLI_CODE
      , GLOBAL_ATTRIBUTE_CATEGORY
      , VALIDATED_FLAG
      , WH_UPDATE_DATE
      , PROVINCE
      , ROOM
      , TRAILING_DIRECTORY_CODE
      , _FIVETRAN_DELETED
      , _FIVETRAN_SYNCED
      , PSA_DELETE_IND
      , PSA_LOAD_DTS
      , PSA_RECORD_SOURCE
      , LOAD_DTS
      , REC_SRC
      , HASHDIFF
      , BKCC
    FROM LOGIC_psa_addr
)
---- FILTER LAYER ----

, FILTER_psa_addr as (
    SELECT *
    FROM RENAME_psa_addr
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM FILTER_psa_addr
)

---- FINAL LAYER ----
SELECT
          CUSTOMER_SITE_HK
        , ACCOUNT_NUMBER
        , CUST_ACCT_SITE_ID
        , LOCATION_ID
        , RURAL_ROUTE_NUMBER
        , SALES_TAX_INSIDE_CITY_LIMITS
        , STREET_SUFFIX
        , PROGRAM_ID
        , DO_NOT_VALIDATE_FLAG
        , GLOBAL_ATTRIBUTE5
        , GLOBAL_ATTRIBUTE4
        , POSITION
        , GLOBAL_ATTRIBUTE7
        , FLOOR
        , GLOBAL_ATTRIBUTE6
        , GLOBAL_ATTRIBUTE1
        , GLOBAL_ATTRIBUTE3
        , GLOBAL_ATTRIBUTE2
        , ADDRESS_KEY
        , GLOBAL_ATTRIBUTE9
        , GLOBAL_ATTRIBUTE8
        , CONTENT_SOURCE_TYPE
        , ATTRIBUTE3
        , LANGUAGE
        , CREATED_BY_MODULE
        , ATTRIBUTE2
        , ORIG_SYSTEM_REFERENCE
        , ATTRIBUTE1
        , ATTRIBUTE9
        , ATTRIBUTE8
        , ATTRIBUTE7
        , ATTRIBUTE6
        , ATTRIBUTE5
        , ATTRIBUTE4
        , SHORT_DESCRIPTION
        , ADDRESS_ERROR_CODE
        , ATTRIBUTE10
        , HOUSE_NUMBER
        , ADDRESS_LINES_PHONETIC
        , ATTRIBUTE14
        , ATTRIBUTE13
        , ATTRIBUTE12
        , ATTRIBUTE11
        , DELIVERY_POINT_CODE
        , SECONDARY_SUFFIX_ELEMENT
        , TIMEZONE_ID
        , SALES_TAX_GEOCODE
        , POSTAL_CODE
        , POST_OFFICE
        , DESCRIPTION
        , ADDRESS_EFFECTIVE_DATE
        , ATTRIBUTE20
        , SUITE
        , GEOMETRY_STATUS_CODE
        , GLOBAL_ATTRIBUTE20
        , STREET
        , GLOBAL_ATTRIBUTE17
        , GLOBAL_ATTRIBUTE18
        , GLOBAL_ATTRIBUTE15
        , GLOBAL_ATTRIBUTE16
        , GLOBAL_ATTRIBUTE13
        , CITY
        , FA_LOCATION_ID
        , GLOBAL_ATTRIBUTE14
        , GLOBAL_ATTRIBUTE11
        , GLOBAL_ATTRIBUTE12
        , ATTRIBUTE18
        , ATTRIBUTE17
        , ATTRIBUTE16
        , ATTRIBUTE15
        , GLOBAL_ATTRIBUTE19
        , ATTRIBUTE19
        , POSTAL_PLUS4_CODE
        , RURAL_ROUTE_TYPE
        , STREET_NUMBER
        , OVERSEAS_ADDRESS_FLAG
        , GLOBAL_ATTRIBUTE10
        , LAST_UPDATE_DATE
        , GEOMETRY_SOURCE
        , LOCATION_DIRECTIONS
        , OBJECT_VERSION_NUMBER
        , COUNTRY
        , LIFE_CYCLE_STATUS
        , COUNTY
        , CREATED_BY
        , LAST_UPDATED_BY
        , CREATION_DATE
        , PROGRAM_UPDATE_DATE
        , APARTMENT_FLAG
        , ATTRIBUTE_CATEGORY
        , ACTUAL_CONTENT_SOURCE
        , PROGRAM_APPLICATION_ID
        , LOC_HIERARCHY_ID
        , VALIDATION_STATUS_CODE
        , APPLICATION_ID
        , STATE
        , REQUEST_ID
        , APARTMENT_NUMBER
        , ADDRESS_STYLE
        , DATE_VALIDATED
        , TIME_ZONE
        , BUILDING
        , ADDRESS1
        , ADDRESS_EXPIRATION_DATE
        , ADDRESS3
        , ADDRESS2
        , ADDRESS4
        , DODAAC
        , LAST_UPDATE_LOGIN
        , PO_BOX_NUMBER
        , CLLI_CODE
        , GLOBAL_ATTRIBUTE_CATEGORY
        , VALIDATED_FLAG
        , WH_UPDATE_DATE
        , PROVINCE
        , ROOM
        , TRAILING_DIRECTORY_CODE
        , _FIVETRAN_DELETED
        , _FIVETRAN_SYNCED
        , PSA_DELETE_IND
        , PSA_LOAD_DTS
        , PSA_RECORD_SOURCE
        , LOAD_DTS
        , REC_SRC
        , HASHDIFF
        , BKCC
FROM JOIN_RESULT
{% if is_incremental() %}
WHERE NOT EXISTS (
    SELECT 1 
    FROM {{ this }} existing
    WHERE existing.CUSTOMER_SITE_HK = JOIN_RESULT.CUSTOMER_SITE_HK 
    AND existing.HASHDIFF = JOIN_RESULT.HASHDIFF
)
{% endif %}
{% if not is_incremental() %}

/* The following qualifier is implemented to prevent multiple loads of touched records during the initial build, such as multiple rows per HK and hashdiff. */
qualify 1 = row_number() over (partition by CUSTOMER_SITE_HK, HASHDIFF order by PSA_LOAD_DTS)

union all
SELECT 
MD5_BINARY(GR.VALUE) AS CUSTOMER_SITE_HK,
GR.VALUE::text AS ACCOUNT_NUMBER,
GR.VALUE::number AS CUST_ACCT_SITE_ID,
NULL AS LOCATION_ID,
NULL AS RURAL_ROUTE_NUMBER,
NULL AS SALES_TAX_INSIDE_CITY_LIMITS,
NULL AS STREET_SUFFIX,
NULL AS PROGRAM_ID,
NULL AS DO_NOT_VALIDATE_FLAG,
NULL AS GLOBAL_ATTRIBUTE5,
NULL AS GLOBAL_ATTRIBUTE4,
NULL AS POSITION,
NULL AS GLOBAL_ATTRIBUTE7,
NULL AS FLOOR,
NULL AS GLOBAL_ATTRIBUTE6,
NULL AS GLOBAL_ATTRIBUTE1,
NULL AS GLOBAL_ATTRIBUTE3,
NULL AS GLOBAL_ATTRIBUTE2,
NULL AS ADDRESS_KEY,
NULL AS GLOBAL_ATTRIBUTE9,
NULL AS GLOBAL_ATTRIBUTE8,
NULL AS CONTENT_SOURCE_TYPE,
NULL AS ATTRIBUTE3,
NULL AS LANGUAGE,
NULL AS CREATED_BY_MODULE,
NULL AS ATTRIBUTE2,
NULL AS ORIG_SYSTEM_REFERENCE,
NULL AS ATTRIBUTE1,
NULL AS ATTRIBUTE9,
NULL AS ATTRIBUTE8,
NULL AS ATTRIBUTE7,
NULL AS ATTRIBUTE6,
NULL AS ATTRIBUTE5,
NULL AS ATTRIBUTE4,
NULL AS SHORT_DESCRIPTION,
NULL AS ADDRESS_ERROR_CODE,
NULL AS ATTRIBUTE10,
NULL AS HOUSE_NUMBER,
NULL AS ADDRESS_LINES_PHONETIC,
NULL AS ATTRIBUTE14,
NULL AS ATTRIBUTE13,
NULL AS ATTRIBUTE12,
NULL AS ATTRIBUTE11,
NULL AS DELIVERY_POINT_CODE,
NULL AS SECONDARY_SUFFIX_ELEMENT,
NULL AS TIMEZONE_ID,
NULL AS SALES_TAX_GEOCODE,
NULL AS POSTAL_CODE,
NULL AS POST_OFFICE,
NULL AS DESCRIPTION,
NULL AS ADDRESS_EFFECTIVE_DATE,
NULL AS ATTRIBUTE20,
NULL AS SUITE,
NULL AS GEOMETRY_STATUS_CODE,
NULL AS GLOBAL_ATTRIBUTE20,
NULL AS STREET,
NULL AS GLOBAL_ATTRIBUTE17,
NULL AS GLOBAL_ATTRIBUTE18,
NULL AS GLOBAL_ATTRIBUTE15,
NULL AS GLOBAL_ATTRIBUTE16,
NULL AS GLOBAL_ATTRIBUTE13,
NULL AS CITY,
NULL AS FA_LOCATION_ID,
NULL AS GLOBAL_ATTRIBUTE14,
NULL AS GLOBAL_ATTRIBUTE11,
NULL AS GLOBAL_ATTRIBUTE12,
NULL AS ATTRIBUTE18,
NULL AS ATTRIBUTE17,
NULL AS ATTRIBUTE16,
NULL AS ATTRIBUTE15,
NULL AS GLOBAL_ATTRIBUTE19,
NULL AS ATTRIBUTE19,
NULL AS POSTAL_PLUS4_CODE,
NULL AS RURAL_ROUTE_TYPE,
NULL AS STREET_NUMBER,
NULL AS OVERSEAS_ADDRESS_FLAG,
NULL AS GLOBAL_ATTRIBUTE10,
NULL AS LAST_UPDATE_DATE,
NULL AS GEOMETRY_SOURCE,
NULL AS LOCATION_DIRECTIONS,
NULL AS OBJECT_VERSION_NUMBER,
NULL AS COUNTRY,
NULL AS LIFE_CYCLE_STATUS,
NULL AS COUNTY,
NULL AS CREATED_BY,
NULL AS LAST_UPDATED_BY,
NULL AS CREATION_DATE,
NULL AS PROGRAM_UPDATE_DATE,
NULL AS APARTMENT_FLAG,
NULL AS ATTRIBUTE_CATEGORY,
NULL AS ACTUAL_CONTENT_SOURCE,
NULL AS PROGRAM_APPLICATION_ID,
NULL AS LOC_HIERARCHY_ID,
NULL AS VALIDATION_STATUS_CODE,
NULL AS APPLICATION_ID,
NULL AS STATE,
NULL AS REQUEST_ID,
NULL AS APARTMENT_NUMBER,
NULL AS ADDRESS_STYLE,
NULL AS DATE_VALIDATED,
NULL AS TIME_ZONE,
NULL AS BUILDING,
NULL AS ADDRESS1,
NULL AS ADDRESS_EXPIRATION_DATE,
NULL AS ADDRESS3,
NULL AS ADDRESS2,
NULL AS ADDRESS4,
NULL AS DODAAC,
NULL AS LAST_UPDATE_LOGIN,
NULL AS PO_BOX_NUMBER,
NULL AS CLLI_CODE,
NULL AS GLOBAL_ATTRIBUTE_CATEGORY,
NULL AS VALIDATED_FLAG,
NULL AS WH_UPDATE_DATE,
NULL AS PROVINCE,
NULL AS ROOM,
NULL AS TRAILING_DIRECTORY_CODE,
NULL AS _FIVETRAN_DELETED,
NULL AS _FIVETRAN_SYNCED,
'N' AS PSA_DELETE_IND,
'1900-01-01'::TIMESTAMP AS PSA_LOAD_DTS,
NULL AS PSA_RECORD_SOURCE,
CONVERT_TIMEZONE('UTC','1900-01-01'::TIMESTAMP) AS LOAD_DTS,
'USAZET.SNOWFLAKE.FBIN.DERIVED' AS REC_SRC,
''::BINARY AS HASHDIFF,
DECODE(GR.VALUE, 0, 'GHOST RECORD-SYSTEM', -1, 'GHOST RECORD-nullkey-required', -2, 'GHOST RECORD-nullkey-optional') AS BKCC
FROM
TABLE(strtok_split_to_table('0|-1|-2', '|')) AS GR
{% endif %}
