---- SRC LAYER ----
WITH
SRC_SFIB           as ( SELECT * FROM {{ ref('v_psa_stg_legal_entity__fib_ocf') }} as SRC 
                         {% if is_incremental() %}
                         WHERE SRC.LOAD_DTS > (SELECT DATEADD('HOUR', '-1', MAX(LOAD_DTS)) FROM {{this}})
                         {% endif %}  )

/*
SRC_SFIB           as ( SELECT * FROM STAGING.v_psa_stg_legal_entity__fib_ocf )
*/
---- LOGIC LAYER ----

, LOGIC_SFIB as (
    SELECT
        LEGAL_ENTITY_HK
      , LEGAL_ENTITY_IDENTIFIER
      , LEGAL_ENTITY_ID
      , LE_INFORMATION_DATE_4
      , ATTRIBUTE_DATE_3
      , ATTRIBUTE_DATE_4
      , ATTRIBUTE_DATE_5
      , ACTIVITY_CODE
      , SUB_ACTIVITY_CODE
      , LE_INFORMATION_5
      , EFFECTIVE_FROM
      , EFFECTIVE_TO
      , LE_INFORMATION_CONTEXT
      , LE_INFORMATION_1
      , LE_INFORMATION_3
      , PARTY_ID
      , ATTRIBUTE_CATEGORY
      , ATTRIBUTE_1
      , ATTRIBUTE_2
      , ATTRIBUTE_3
      , ATTRIBUTE_4
      , ATTRIBUTE_5
      , LE_INFORMATION_15
      , LE_INFORMATION_16
      , LE_INFORMATION_13
      , LE_INFORMATION_14
      , ATTRIBUTE_DATE_2
      , LE_INFORMATION_17
      , LE_INFORMATION_18
      , NAME
      , GEOGRAPHY_ID
      , TRANSACTING_ENTITY_FLAG
      , ATTRIBUTE_12
      , ATTRIBUTE_13
      , ATTRIBUTE_14
      , LE_INFORMATION_DATE_5
      , TYPE_OF_COMPANY
      , ATTRIBUTE_6
      , ATTRIBUTE_7
      , ATTRIBUTE_8
      , ATTRIBUTE_9
      , ATTRIBUTE_10
      , ATTRIBUTE_11
      , ATTRIBUTE_16
      , ATTRIBUTE_17
      , LE_INFORMATION_8
      , LE_INFORMATION_9
      , LE_INFORMATION_10
      , LE_INFORMATION_11
      , LE_INFORMATION_12
      , ATTRIBUTE_NUMBER_2
      , ATTRIBUTE_NUMBER_3
      , ATTRIBUTE_NUMBER_4
      , ATTRIBUTE_18
      , ATTRIBUTE_15
      , ATTRIBUTE_19
      , ATTRIBUTE_20
      , ATTRIBUTE_NUMBER_1
      , ATTRIBUTE_NUMBER_5
      , ATTRIBUTE_DATE_1
      , LE_INFORMATION_NUMBER_1
      , LE_INFORMATION_NUMBER_2
      , LE_INFORMATION_NUMBER_3
      , LE_INFORMATION_NUMBER_4
      , LE_INFORMATION_NUMBER_5
      , LE_INFORMATION_DATE_1
      , LE_INFORMATION_DATE_2
      , LE_INFORMATION_DATE_3
      , PSU_FLAG
      , LEGAL_EMPLOYER_FLAG
      , PARENT_PSU_ID
      , ENTERPRISE_ID
      , LE_INFORMATION_4
      , LE_INFORMATION_2
      , LE_INFORMATION_6
      , LE_INFORMATION_7
      , LE_INFORMATION_19
      , LE_INFORMATION_20
      , LAST_UPDATED_BY
      , CREATION_DATE
      , LAST_UPDATE_LOGIN
      , LAST_UPDATE_DATE
      , CREATED_BY
      , OBJECT_VERSION_NUMBER
      , _FIVETRAN_DELETED
      , _FIVETRAN_SYNCED
      , PSA_LOAD_DTS
      , PSA_DELETE_IND
      , LOAD_DTS
      , REC_SRC
      , BKCC
      , HASHDIFF
    FROM SRC_SFIB
)
---- RENAME LAYER ----

, RENAME_SFIB as (
    SELECT
        LEGAL_ENTITY_HK
      , LEGAL_ENTITY_IDENTIFIER
      , LEGAL_ENTITY_ID
      , LE_INFORMATION_DATE_4
      , ATTRIBUTE_DATE_3
      , ATTRIBUTE_DATE_4
      , ATTRIBUTE_DATE_5
      , ACTIVITY_CODE
      , SUB_ACTIVITY_CODE
      , LE_INFORMATION_5
      , EFFECTIVE_FROM
      , EFFECTIVE_TO
      , LE_INFORMATION_CONTEXT
      , LE_INFORMATION_1
      , LE_INFORMATION_3
      , PARTY_ID
      , ATTRIBUTE_CATEGORY
      , ATTRIBUTE_1
      , ATTRIBUTE_2
      , ATTRIBUTE_3
      , ATTRIBUTE_4
      , ATTRIBUTE_5
      , LE_INFORMATION_15
      , LE_INFORMATION_16
      , LE_INFORMATION_13
      , LE_INFORMATION_14
      , ATTRIBUTE_DATE_2
      , LE_INFORMATION_17
      , LE_INFORMATION_18
      , NAME
      , GEOGRAPHY_ID
      , TRANSACTING_ENTITY_FLAG
      , ATTRIBUTE_12
      , ATTRIBUTE_13
      , ATTRIBUTE_14
      , LE_INFORMATION_DATE_5
      , TYPE_OF_COMPANY
      , ATTRIBUTE_6
      , ATTRIBUTE_7
      , ATTRIBUTE_8
      , ATTRIBUTE_9
      , ATTRIBUTE_10
      , ATTRIBUTE_11
      , ATTRIBUTE_16
      , ATTRIBUTE_17
      , LE_INFORMATION_8
      , LE_INFORMATION_9
      , LE_INFORMATION_10
      , LE_INFORMATION_11
      , LE_INFORMATION_12
      , ATTRIBUTE_NUMBER_2
      , ATTRIBUTE_NUMBER_3
      , ATTRIBUTE_NUMBER_4
      , ATTRIBUTE_18
      , ATTRIBUTE_15
      , ATTRIBUTE_19
      , ATTRIBUTE_20
      , ATTRIBUTE_NUMBER_1
      , ATTRIBUTE_NUMBER_5
      , ATTRIBUTE_DATE_1
      , LE_INFORMATION_NUMBER_1
      , LE_INFORMATION_NUMBER_2
      , LE_INFORMATION_NUMBER_3
      , LE_INFORMATION_NUMBER_4
      , LE_INFORMATION_NUMBER_5
      , LE_INFORMATION_DATE_1
      , LE_INFORMATION_DATE_2
      , LE_INFORMATION_DATE_3
      , PSU_FLAG
      , LEGAL_EMPLOYER_FLAG
      , PARENT_PSU_ID
      , ENTERPRISE_ID
      , LE_INFORMATION_4
      , LE_INFORMATION_2
      , LE_INFORMATION_6
      , LE_INFORMATION_7
      , LE_INFORMATION_19
      , LE_INFORMATION_20
      , LAST_UPDATED_BY
      , CREATION_DATE
      , LAST_UPDATE_LOGIN
      , LAST_UPDATE_DATE
      , CREATED_BY
      , OBJECT_VERSION_NUMBER
      , _FIVETRAN_DELETED
      , _FIVETRAN_SYNCED
      , PSA_LOAD_DTS
      , PSA_DELETE_IND
      , LOAD_DTS
      , REC_SRC
      , BKCC
      , HASHDIFF
    FROM LOGIC_SFIB
)
---- FILTER LAYER ----

, FILTER_SFIB as (
    SELECT *
    FROM RENAME_SFIB
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM FILTER_SFIB
)

---- FINAL LAYER ----
SELECT
          LEGAL_ENTITY_HK
        , LEGAL_ENTITY_IDENTIFIER
        , LEGAL_ENTITY_ID
        , LE_INFORMATION_DATE_4
        , ATTRIBUTE_DATE_3
        , ATTRIBUTE_DATE_4
        , ATTRIBUTE_DATE_5
        , ACTIVITY_CODE
        , SUB_ACTIVITY_CODE
        , LE_INFORMATION_5
        , EFFECTIVE_FROM
        , EFFECTIVE_TO
        , LE_INFORMATION_CONTEXT
        , LE_INFORMATION_1
        , LE_INFORMATION_3
        , PARTY_ID
        , ATTRIBUTE_CATEGORY
        , ATTRIBUTE_1
        , ATTRIBUTE_2
        , ATTRIBUTE_3
        , ATTRIBUTE_4
        , ATTRIBUTE_5
        , LE_INFORMATION_15
        , LE_INFORMATION_16
        , LE_INFORMATION_13
        , LE_INFORMATION_14
        , ATTRIBUTE_DATE_2
        , LE_INFORMATION_17
        , LE_INFORMATION_18
        , NAME
        , GEOGRAPHY_ID
        , TRANSACTING_ENTITY_FLAG
        , ATTRIBUTE_12
        , ATTRIBUTE_13
        , ATTRIBUTE_14
        , LE_INFORMATION_DATE_5
        , TYPE_OF_COMPANY
        , ATTRIBUTE_6
        , ATTRIBUTE_7
        , ATTRIBUTE_8
        , ATTRIBUTE_9
        , ATTRIBUTE_10
        , ATTRIBUTE_11
        , ATTRIBUTE_16
        , ATTRIBUTE_17
        , LE_INFORMATION_8
        , LE_INFORMATION_9
        , LE_INFORMATION_10
        , LE_INFORMATION_11
        , LE_INFORMATION_12
        , ATTRIBUTE_NUMBER_2
        , ATTRIBUTE_NUMBER_3
        , ATTRIBUTE_NUMBER_4
        , ATTRIBUTE_18
        , ATTRIBUTE_15
        , ATTRIBUTE_19
        , ATTRIBUTE_20
        , ATTRIBUTE_NUMBER_1
        , ATTRIBUTE_NUMBER_5
        , ATTRIBUTE_DATE_1
        , LE_INFORMATION_NUMBER_1
        , LE_INFORMATION_NUMBER_2
        , LE_INFORMATION_NUMBER_3
        , LE_INFORMATION_NUMBER_4
        , LE_INFORMATION_NUMBER_5
        , LE_INFORMATION_DATE_1
        , LE_INFORMATION_DATE_2
        , LE_INFORMATION_DATE_3
        , PSU_FLAG
        , LEGAL_EMPLOYER_FLAG
        , PARENT_PSU_ID
        , ENTERPRISE_ID
        , LE_INFORMATION_4
        , LE_INFORMATION_2
        , LE_INFORMATION_6
        , LE_INFORMATION_7
        , LE_INFORMATION_19
        , LE_INFORMATION_20
        , LAST_UPDATED_BY
        , CREATION_DATE
        , LAST_UPDATE_LOGIN
        , LAST_UPDATE_DATE
        , CREATED_BY
        , OBJECT_VERSION_NUMBER
        , _FIVETRAN_DELETED
        , _FIVETRAN_SYNCED
        , PSA_LOAD_DTS
        , PSA_DELETE_IND
        , LOAD_DTS
        , REC_SRC
        , BKCC
        , HASHDIFF
FROM JOIN_RESULT
{% if is_incremental() %}
WHERE NOT EXISTS (
    SELECT 1 
    FROM {{ this }} existing
    WHERE existing.LEGAL_ENTITY_HK = JOIN_RESULT.LEGAL_ENTITY_HK 
    AND existing.HASHDIFF = JOIN_RESULT.HASHDIFF
)
{% endif %}
{% if not is_incremental() %}
/* The following qualifier is implemented to prevent multiple loads of touched records during the initial build, such as multiple rows per HK and hashdiff. */
qualify 1 = row_number() over (partition by LEGAL_ENTITY_HK, HASHDIFF order by PSA_LOAD_DTS desc)

union all
SELECT 
MD5_BINARY(GR.VALUE) AS LEGAL_ENTITY_HK,
GR.VALUE::text AS LEGAL_ENTITY_IDENTIFIER,
GR.VALUE::number AS LEGAL_ENTITY_ID,
NULL AS LE_INFORMATION_DATE_4,
NULL AS ATTRIBUTE_DATE_3,
NULL AS ATTRIBUTE_DATE_4,
NULL AS ATTRIBUTE_DATE_5,
NULL AS ACTIVITY_CODE,
NULL AS SUB_ACTIVITY_CODE,
NULL AS LE_INFORMATION_5,
NULL AS EFFECTIVE_FROM,
NULL AS EFFECTIVE_TO,
NULL AS LE_INFORMATION_CONTEXT,
NULL AS LE_INFORMATION_1,
NULL AS LE_INFORMATION_3,
NULL AS PARTY_ID,
NULL AS ATTRIBUTE_CATEGORY,
NULL AS ATTRIBUTE_1,
NULL AS ATTRIBUTE_2,
NULL AS ATTRIBUTE_3,
NULL AS ATTRIBUTE_4,
NULL AS ATTRIBUTE_5,
NULL AS LE_INFORMATION_15,
NULL AS LE_INFORMATION_16,
NULL AS LE_INFORMATION_13,
NULL AS LE_INFORMATION_14,
NULL AS ATTRIBUTE_DATE_2,
NULL AS LE_INFORMATION_17,
NULL AS LE_INFORMATION_18,
NULL AS NAME,
NULL AS GEOGRAPHY_ID,
NULL AS TRANSACTING_ENTITY_FLAG,
NULL AS ATTRIBUTE_12,
NULL AS ATTRIBUTE_13,
NULL AS ATTRIBUTE_14,
NULL AS LE_INFORMATION_DATE_5,
NULL AS TYPE_OF_COMPANY,
NULL AS ATTRIBUTE_6,
NULL AS ATTRIBUTE_7,
NULL AS ATTRIBUTE_8,
NULL AS ATTRIBUTE_9,
NULL AS ATTRIBUTE_10,
NULL AS ATTRIBUTE_11,
NULL AS ATTRIBUTE_16,
NULL AS ATTRIBUTE_17,
NULL AS LE_INFORMATION_8,
NULL AS LE_INFORMATION_9,
NULL AS LE_INFORMATION_10,
NULL AS LE_INFORMATION_11,
NULL AS LE_INFORMATION_12,
NULL AS ATTRIBUTE_NUMBER_2,
NULL AS ATTRIBUTE_NUMBER_3,
NULL AS ATTRIBUTE_NUMBER_4,
NULL AS ATTRIBUTE_18,
NULL AS ATTRIBUTE_15,
NULL AS ATTRIBUTE_19,
NULL AS ATTRIBUTE_20,
NULL AS ATTRIBUTE_NUMBER_1,
NULL AS ATTRIBUTE_NUMBER_5,
NULL AS ATTRIBUTE_DATE_1,
NULL AS LE_INFORMATION_NUMBER_1,
NULL AS LE_INFORMATION_NUMBER_2,
NULL AS LE_INFORMATION_NUMBER_3,
NULL AS LE_INFORMATION_NUMBER_4,
NULL AS LE_INFORMATION_NUMBER_5,
NULL AS LE_INFORMATION_DATE_1,
NULL AS LE_INFORMATION_DATE_2,
NULL AS LE_INFORMATION_DATE_3,
NULL AS PSU_FLAG,
NULL AS LEGAL_EMPLOYER_FLAG,
NULL AS PARENT_PSU_ID,
NULL AS ENTERPRISE_ID,
NULL AS LE_INFORMATION_4,
NULL AS LE_INFORMATION_2,
NULL AS LE_INFORMATION_6,
NULL AS LE_INFORMATION_7,
NULL AS LE_INFORMATION_19,
NULL AS LE_INFORMATION_20,
NULL AS LAST_UPDATED_BY,
NULL AS CREATION_DATE,
NULL AS LAST_UPDATE_LOGIN,
NULL AS LAST_UPDATE_DATE,
NULL AS CREATED_BY,
NULL AS OBJECT_VERSION_NUMBER,
NULL AS _FIVETRAN_DELETED,
NULL AS _FIVETRAN_SYNCED,
'1900-01-01'::TIMESTAMP AS PSA_LOAD_DTS,
'N' AS PSA_DELETE_IND,
CONVERT_TIMEZONE('UTC','1900-01-01'::TIMESTAMP) AS LOAD_DTS,
'USAZET.SNOWFLAKE.FBIN.DERIVED' AS REC_SRC,
DECODE(GR.VALUE, 0, 'GHOST RECORD-SYSTEM', -1, 'GHOST RECORD-nullkey-required', -2, 'GHOST RECORD-nullkey-optional') AS BKCC,
''::BINARY AS HASHDIFF
FROM
TABLE(strtok_split_to_table('0|-1|-2', '|')) AS GR
{% endif %}
