---- SRC LAYER ----
WITH
SRC_SORDLML        as ( SELECT ORDER_LINE_HK , ORDER_LINE_BK , LINE_ID , SERVICE_REFERENCE_TYPE_CODE , SUBINVENTORY , SOURCE_DOCUMENT_VERSION_NUMBER , UNIT_COST , PRICING_ATTRIBUTE1 , PRICING_ATTRIBUTE2 , INDUSTRY_ATTRIBUTE1 , CUSTOMER_DOCK_CODE , INDUSTRY_ATTRIBUTE2 , IB_CURRENT_LOCATION , INDUSTRY_ATTRIBUTE3 , INDUSTRY_ATTRIBUTE4 , INDUSTRY_ATTRIBUTE5 , INDUSTRY_ATTRIBUTE6 , INDUSTRY_ATTRIBUTE7 , INDUSTRY_ATTRIBUTE8 , PROGRAM_ID , CONTEXT , INDUSTRY_ATTRIBUTE9 , SHIPMENT_PRIORITY_CODE , ARRIVAL_SET_ID , DELIVER_TO_ORG_ID , MFG_LEAD_TIME , BLANKET_VERSION_NUMBER , SHIPPING_INTERFACED_FLAG , UNIT_SELLING_PRICE , PAYMENT_TYPE_CODE , PRICING_ATTRIBUTE5 , PRICING_ATTRIBUTE6 , PRICING_ATTRIBUTE3 , PRICING_ATTRIBUTE4 , REVREC_COMMENTS , PRICING_ATTRIBUTE9 , PRICING_ATTRIBUTE7 , PRICING_ATTRIBUTE8 , ATTRIBUTE3 , ATTRIBUTE2 , TP_ATTRIBUTE15 , ORDER_QUANTITY_UOM , ATTRIBUTE1 , TP_ATTRIBUTE14 , FREIGHT_CARRIER_CODE , TP_ATTRIBUTE13 , TP_ATTRIBUTE12 , TP_ATTRIBUTE11 , TP_ATTRIBUTE10 , EARLIEST_SHIP_DATE , CALCULATE_PRICE_FLAG , ORDERED_QUANTITY_UOM2 , ATTRIBUTE9 , SCHEDULE_SHIP_DATE , ATTRIBUTE8 , ATTRIBUTE7 , ATTRIBUTE6 , SHIP_SET_ID , ITEM_IDENTIFIER_TYPE , ATTRIBUTE5 , SCHEDULE_ARRIVAL_DATE , ATTRIBUTE4 , TRANSACTION_PHASE_CODE , CUST_PO_NUMBER , REFERENCE_CUSTOMER_TRX_LINE_ID , SHIP_TOLERANCE_BELOW , ORDERED_QUANTITY , TAX_DATE , ATTRIBUTE10 , ORIG_SYS_DOCUMENT_REF , OPTION_FLAG , ATTRIBUTE14 , ATTRIBUTE13 , ATTRIBUTE12 , ATTRIBUTE11 , DROP_SHIP_FLAG , SHIP_TOLERANCE_ABOVE , UNIT_SELLING_PRICE_PER_PQTY , CONFIGURATION_ID , CONFIG_HEADER_ID , FLOW_STATUS_CODE , COMPONENT_SEQUENCE_ID , FULFILLED_FLAG , ACCOUNTING_RULE_DURATION , CONFIG_REV_NBR , CUSTOMER_JOB , ATTRIBUTE20 , SHIP_MODEL_COMPLETE_FLAG , SERVICE_CREDIT_ELIGIBLE_CODE , CUSTOMER_TRX_LINE_ID , ITEM_REVISION , SOURCE_TYPE_CODE , REVREC_REFERENCE_DOCUMENT , CANCELLED_QUANTITY2 , ACTUAL_SHIPMENT_DATE , SPLIT_BY , FULFILLMENT_DATE , SERVICE_END_DATE , SHIPPED_QUANTITY2 , EXPLOSION_DATE , CUSTOMER_LINE_NUMBER , RLA_SCHEDULE_TYPE_CODE , RETURN_REASON_CODE , ATTRIBUTE18 , SORT_ORDER , ATTRIBUTE17 , ATTRIBUTE16 , UNIT_SELLING_PERCENT , ATTRIBUTE15 , ATTRIBUTE19 , VEH_CUS_ITEM_CUM_KEY_ID , REVREC_SIGNATURE_DATE , FIRST_ACK_CODE , ORIG_SYS_LINE_REF , PRE_EXPLODED_FLAG , LINE_SET_ID , RETURN_CONTEXT , TAX_POINT_CODE , GLOBAL_ATTRIBUTE10 , ORIGINAL_ITEM_IDENTIFIER_TYPE , PROMISE_DATE , USER_ITEM_DESCRIPTION , LOCK_CONTROL , REVREC_SIGNATURE , REFERENCE_HEADER_ID , INTMED_SHIP_TO_CONTACT_ID , ORIGINAL_INVENTORY_ITEM_ID , CUST_MODEL_SERIAL_NUMBER , CHANGE_SEQUENCE , TP_ATTRIBUTE9 , UNIT_LIST_PRICE , RETROBILL_REQUEST_ID , SOLD_FROM_ORG_ID , EARLIEST_ACCEPTABLE_DATE , LAST_UPDATED_BY , PAYMENT_TERM_ID , ITEM_SUBSTITUTION_TYPE_CODE , UNIT_PERCENT_BASE_PRICE , PLANNING_PRIORITY , TP_ATTRIBUTE8 , LATEST_ACCEPTABLE_DATE , TP_ATTRIBUTE7 , TP_ATTRIBUTE6 , SHIPPABLE_FLAG , TP_ATTRIBUTE5 , TP_ATTRIBUTE4 , TP_ATTRIBUTE3 , TP_ATTRIBUTE2 , TP_ATTRIBUTE1 , END_CUSTOMER_CONTACT_ID , LINK_TO_LINE_ID , ORIGINAL_ORDERED_ITEM , UNIT_LIST_PERCENT , ORIGINAL_LIST_PRICE , SHIPPING_QUANTITY_UOM , RETURN_ATTRIBUTE8 , RETURN_ATTRIBUTE7 , SHIPPING_QUANTITY_UOM2 , IB_OWNER , REVREC_IMPLICIT_FLAG , RETURN_ATTRIBUTE6 , FIRST_ACK_DATE , RETURN_ATTRIBUTE5 , SHIPPING_QUANTITY2 , RETURN_ATTRIBUTE9 , TAX_EXEMPT_NUMBER , RETURN_ATTRIBUTE4 , LINE_CATEGORY_CODE , RETURN_ATTRIBUTE3 , INDUSTRY_CONTEXT , RETURN_ATTRIBUTE2 , SERVICE_PERIOD , REVENUE_AMOUNT , RETURN_ATTRIBUTE1 , CREDIT_INVOICE_LINE_ID , MODEL_GROUP_NUMBER , INTMED_SHIP_TO_ORG_ID , TAX_EXEMPT_FLAG , SOLD_TO_ORG_ID , PRICE_REQUEST_CODE , RETURN_ATTRIBUTE14 , SHIPPING_QUANTITY , RETURN_ATTRIBUTE15 , CANCELLED_QUANTITY , PRICING_CONTEXT , DEMAND_BUCKET_TYPE_CODE , GLOBAL_ATTRIBUTE_CATEGORY , RETURN_ATTRIBUTE10 , RETURN_ATTRIBUTE11 , RETURN_ATTRIBUTE12 , REQUEST_DATE , RETURN_ATTRIBUTE13 , TAX_RATE , INDUSTRY_ATTRIBUTE26 , INDUSTRY_ATTRIBUTE25 , INDUSTRY_ATTRIBUTE24 , ORG_ID , INDUSTRY_ATTRIBUTE23 , INDUSTRY_ATTRIBUTE22 , COMPONENT_NUMBER , INDUSTRY_ATTRIBUTE21 , INDUSTRY_ATTRIBUTE20 , SCHEDULE_STATUS_CODE , CANCELLED_FLAG , GLOBAL_ATTRIBUTE5 , DELIVER_TO_CONTACT_ID , GLOBAL_ATTRIBUTE4 , INVOICE_INTERFACE_STATUS_CODE , GLOBAL_ATTRIBUTE7 , OVERRIDE_ATP_DATE_CODE , AUTO_SELECTED_QUANTITY , GLOBAL_ATTRIBUTE6 , GLOBAL_ATTRIBUTE1 , ORDER_FIRMED_DATE , GLOBAL_ATTRIBUTE3 , GLOBAL_ATTRIBUTE2 , UPGRADED_FLAG , TOP_MODEL_LINE_ID , GLOBAL_ATTRIBUTE9 , INDUSTRY_ATTRIBUTE19 , FOB_POINT_CODE , GLOBAL_ATTRIBUTE8 , INDUSTRY_ATTRIBUTE18 , BLANKET_LINE_NUMBER , MINISITE_ID , INDUSTRY_ATTRIBUTE17 , TAX_EXEMPT_REASON_CODE , INDUSTRY_ATTRIBUTE16 , ORDER_SOURCE_ID , ACTUAL_FULFILLMENT_DATE , TAX_VALUE , LAST_ACK_DATE , INDUSTRY_ATTRIBUTE30 , BOOKED_FLAG , END_ITEM_UNIT_NUMBER , ACTUAL_ARRIVAL_DATE , AGREEMENT_ID , LATE_DEMAND_PENALTY_FACTOR , INVENTORY_ITEM_ID , BLANKET_NUMBER , CONFIG_DISPLAY_SEQUENCE , INDUSTRY_ATTRIBUTE29 , INDUSTRY_ATTRIBUTE28 , TASK_ID , INDUSTRY_ATTRIBUTE27 , TP_CONTEXT , SHIP_TO_CONTACT_ID , REVREC_EXPIRATION_DAYS , CUSTOMER_PAYMENT_TERM_ID , REFERENCE_TYPE , IB_INSTALLED_AT_LOCATION , RE_SOURCE_FLAG , MODEL_REMNANT_FLAG , LINE_NUMBER , COMMITMENT_ID , CUSTOMER_PRODUCTION_LINE , OPTION_NUMBER , ITEM_TYPE_CODE , ORDERED_ITEM , PRICING_QUANTITY_UOM , SHIPPED_QUANTITY , BYPASS_SCH_FLAG , SALESREP_ID , PRICING_ATTRIBUTE10 , CUSTOMER_ITEM_NET_PRICE , PROJECT_ID , ORDERED_QUANTITY2 , INDUSTRY_ATTRIBUTE15 , INDUSTRY_ATTRIBUTE14 , INVOICE_TO_CONTACT_ID , INDUSTRY_ATTRIBUTE13 , COMPONENT_CODE , INDUSTRY_ATTRIBUTE12 , INDUSTRY_ATTRIBUTE11 , UNIT_LIST_PRICE_PER_PQTY , INDUSTRY_ATTRIBUTE10 , GLOBAL_ATTRIBUTE20 , HEADER_ID , CUST_PRODUCTION_SEQ_NUM , GLOBAL_ATTRIBUTE17 , GLOBAL_ATTRIBUTE18 , GLOBAL_ATTRIBUTE15 , GLOBAL_ATTRIBUTE16 , GLOBAL_ATTRIBUTE13 , GLOBAL_ATTRIBUTE14 , GLOBAL_ATTRIBUTE11 , SPLIT_FROM_LINE_ID , GLOBAL_ATTRIBUTE12 , SOURCE_DOCUMENT_LINE_ID , ACCEPTED_QUANTITY , REVREC_EVENT_CODE , GLOBAL_ATTRIBUTE19 , EQUIPMENT_ID , AUTHORIZED_TO_SHIP_FLAG , DELIVERY_LEAD_TIME , FULFILLED_QUANTITY2 , VISIBLE_DEMAND_FLAG , LAST_UPDATE_DATE , SERVICE_REFERENCE_LINE_ID , INVOICED_QUANTITY , SHIP_TO_ORG_ID , INVOICE_TO_ORG_ID , SOURCE_DOCUMENT_TYPE_ID , ITEM_RELATIONSHIP_TYPE , SHIPMENT_NUMBER , SHIPPING_INSTRUCTIONS , CREATED_BY , SHIPPING_METHOD_CODE , SOURCE_DOCUMENT_ID , CUSTOMER_SHIPMENT_NUMBER , CREATION_DATE , PRICE_LIST_ID , INVOICING_RULE_ID , REFERENCE_LINE_ID , CHARGE_PERIODICITY_CODE , ATO_LINE_ID , PROGRAM_UPDATE_DATE , DEP_PLAN_REQUIRED_FLAG , SERVICE_TXN_COMMENTS , PROGRAM_APPLICATION_ID , PACKING_INSTRUCTIONS , END_CUSTOMER_ID , LINE_TYPE_ID , OPEN_FLAG , MFG_COMPONENT_SEQUENCE_ID , PREFERRED_GRADE , SHIP_FROM_ORG_ID , SALES_DOCUMENT_TYPE_CODE , SERVICE_TXN_REASON_CODE , FULFILLMENT_METHOD_CODE , REQUEST_ID , CONTINGENCY_ID , MARKETING_SOURCE_CODE_ID , SERVICE_REFERENCE_SYSTEM_ID , ORIGINAL_ORDERED_ITEM_ID , FULFILLED_QUANTITY , PRICING_DATE , SERVICE_START_DATE , OVER_SHIP_REASON_CODE , LAST_ACK_CODE , SERVICE_DURATION , SERVICE_NUMBER , LAST_UPDATE_LOGIN , ACCOUNTING_RULE_ID , END_CUSTOMER_SITE_USE_ID , FIRM_DEMAND_FLAG , ACCEPTED_BY , SERVICE_COTERMINATE_FLAG , DEMAND_CLASS_CODE , OVER_SHIP_RESOLVED_FLAG , ORIG_SYS_SHIPMENT_REF , ORDERED_ITEM_ID , TAX_CODE , FREIGHT_TERMS_CODE , PRICING_QUANTITY , _FIVETRAN_DELETED , _FIVETRAN_ID , _FIVETRAN_SYNCED , PSA_LOAD_DTS , PSA_RECORD_SOURCE , PSA_DELETE_IND , LOAD_DTS , REC_SRC , BKCC , HASHDIFF FROM {{ ref('v_psa_stg_order_line__ml_ebs') }} as SRC 
                         {% if is_incremental() %}
                         WHERE SRC.LOAD_DTS > (SELECT DATEADD('HOUR', '-1', MAX(LOAD_DTS)) FROM {{this}})
                         {% endif %}  )
/*
SRC_SORDLML        as ( SELECT * FROM STAGING.v_psa_stg_order_line__ml_ebs )
*/
---- LOGIC LAYER ----

, LOGIC_SORDLML as (
    SELECT
        ORDER_LINE_HK
      , ORDER_LINE_BK  
      , LINE_ID
      , SERVICE_REFERENCE_TYPE_CODE
      , SUBINVENTORY
      , SOURCE_DOCUMENT_VERSION_NUMBER
      , UNIT_COST
      , PRICING_ATTRIBUTE1
      , PRICING_ATTRIBUTE2
      , INDUSTRY_ATTRIBUTE1
      , CUSTOMER_DOCK_CODE
      , INDUSTRY_ATTRIBUTE2
      , IB_CURRENT_LOCATION
      , INDUSTRY_ATTRIBUTE3
      , INDUSTRY_ATTRIBUTE4
      , INDUSTRY_ATTRIBUTE5
      , INDUSTRY_ATTRIBUTE6
      , INDUSTRY_ATTRIBUTE7
      , INDUSTRY_ATTRIBUTE8
      , PROGRAM_ID
      , CONTEXT
      , INDUSTRY_ATTRIBUTE9
      , SHIPMENT_PRIORITY_CODE
      , ARRIVAL_SET_ID
      , DELIVER_TO_ORG_ID
      , MFG_LEAD_TIME
      , BLANKET_VERSION_NUMBER
      , SHIPPING_INTERFACED_FLAG
      , UNIT_SELLING_PRICE
      , PAYMENT_TYPE_CODE
      , PRICING_ATTRIBUTE5
      , PRICING_ATTRIBUTE6
      , PRICING_ATTRIBUTE3
      , PRICING_ATTRIBUTE4
      , REVREC_COMMENTS
      , PRICING_ATTRIBUTE9
      , PRICING_ATTRIBUTE7
      , PRICING_ATTRIBUTE8
      , ATTRIBUTE3
      , ATTRIBUTE2
      , TP_ATTRIBUTE15
      , ORDER_QUANTITY_UOM
      , ATTRIBUTE1
      , TP_ATTRIBUTE14
      , FREIGHT_CARRIER_CODE
      , TP_ATTRIBUTE13
      , TP_ATTRIBUTE12
      , TP_ATTRIBUTE11
      , TP_ATTRIBUTE10
      , EARLIEST_SHIP_DATE
      , CALCULATE_PRICE_FLAG
      , ORDERED_QUANTITY_UOM2
      , ATTRIBUTE9
      , SCHEDULE_SHIP_DATE
      , ATTRIBUTE8
      , ATTRIBUTE7
      , ATTRIBUTE6
      , SHIP_SET_ID
      , ITEM_IDENTIFIER_TYPE
      , ATTRIBUTE5
      , SCHEDULE_ARRIVAL_DATE
      , ATTRIBUTE4
      , TRANSACTION_PHASE_CODE
      , CUST_PO_NUMBER
      , REFERENCE_CUSTOMER_TRX_LINE_ID
      , SHIP_TOLERANCE_BELOW
      , ORDERED_QUANTITY
      , TAX_DATE
      , ATTRIBUTE10
      , ORIG_SYS_DOCUMENT_REF
      , OPTION_FLAG
      , ATTRIBUTE14
      , ATTRIBUTE13
      , ATTRIBUTE12
      , ATTRIBUTE11
      , DROP_SHIP_FLAG
      , SHIP_TOLERANCE_ABOVE
      , UNIT_SELLING_PRICE_PER_PQTY
      , CONFIGURATION_ID
      , CONFIG_HEADER_ID
      , FLOW_STATUS_CODE
      , COMPONENT_SEQUENCE_ID
      , FULFILLED_FLAG
      , ACCOUNTING_RULE_DURATION
      , CONFIG_REV_NBR
      , CUSTOMER_JOB
      , ATTRIBUTE20
      , SHIP_MODEL_COMPLETE_FLAG
      , SERVICE_CREDIT_ELIGIBLE_CODE
      , CUSTOMER_TRX_LINE_ID
      , ITEM_REVISION
      , SOURCE_TYPE_CODE
      , REVREC_REFERENCE_DOCUMENT
      , CANCELLED_QUANTITY2
      , ACTUAL_SHIPMENT_DATE
      , SPLIT_BY
      , FULFILLMENT_DATE
      , SERVICE_END_DATE
      , SHIPPED_QUANTITY2
      , EXPLOSION_DATE
      , CUSTOMER_LINE_NUMBER
      , RLA_SCHEDULE_TYPE_CODE
      , RETURN_REASON_CODE
      , ATTRIBUTE18
      , SORT_ORDER
      , ATTRIBUTE17
      , ATTRIBUTE16
      , UNIT_SELLING_PERCENT
      , ATTRIBUTE15
      , ATTRIBUTE19
      , VEH_CUS_ITEM_CUM_KEY_ID
      , REVREC_SIGNATURE_DATE
      , FIRST_ACK_CODE
      , ORIG_SYS_LINE_REF
      , PRE_EXPLODED_FLAG
      , LINE_SET_ID
      , RETURN_CONTEXT
      , TAX_POINT_CODE
      , GLOBAL_ATTRIBUTE10
      , ORIGINAL_ITEM_IDENTIFIER_TYPE
      , PROMISE_DATE
      , USER_ITEM_DESCRIPTION
      , LOCK_CONTROL
      , REVREC_SIGNATURE
      , REFERENCE_HEADER_ID
      , INTMED_SHIP_TO_CONTACT_ID
      , ORIGINAL_INVENTORY_ITEM_ID
      , CUST_MODEL_SERIAL_NUMBER
      , CHANGE_SEQUENCE
      , TP_ATTRIBUTE9
      , UNIT_LIST_PRICE
      , RETROBILL_REQUEST_ID
      , SOLD_FROM_ORG_ID
      , EARLIEST_ACCEPTABLE_DATE
      , LAST_UPDATED_BY
      , PAYMENT_TERM_ID
      , ITEM_SUBSTITUTION_TYPE_CODE
      , UNIT_PERCENT_BASE_PRICE
      , PLANNING_PRIORITY
      , TP_ATTRIBUTE8
      , LATEST_ACCEPTABLE_DATE
      , TP_ATTRIBUTE7
      , TP_ATTRIBUTE6
      , SHIPPABLE_FLAG
      , TP_ATTRIBUTE5
      , TP_ATTRIBUTE4
      , TP_ATTRIBUTE3
      , TP_ATTRIBUTE2
      , TP_ATTRIBUTE1
      , END_CUSTOMER_CONTACT_ID
      , LINK_TO_LINE_ID
      , ORIGINAL_ORDERED_ITEM
      , UNIT_LIST_PERCENT
      , ORIGINAL_LIST_PRICE
      , SHIPPING_QUANTITY_UOM
      , RETURN_ATTRIBUTE8
      , RETURN_ATTRIBUTE7
      , SHIPPING_QUANTITY_UOM2
      , IB_OWNER
      , REVREC_IMPLICIT_FLAG
      , RETURN_ATTRIBUTE6
      , FIRST_ACK_DATE
      , RETURN_ATTRIBUTE5
      , SHIPPING_QUANTITY2
      , RETURN_ATTRIBUTE9
      , TAX_EXEMPT_NUMBER
      , RETURN_ATTRIBUTE4
      , LINE_CATEGORY_CODE
      , RETURN_ATTRIBUTE3
      , INDUSTRY_CONTEXT
      , RETURN_ATTRIBUTE2
      , SERVICE_PERIOD
      , REVENUE_AMOUNT
      , RETURN_ATTRIBUTE1
      , CREDIT_INVOICE_LINE_ID
      , MODEL_GROUP_NUMBER
      , INTMED_SHIP_TO_ORG_ID
      , TAX_EXEMPT_FLAG
      , SOLD_TO_ORG_ID
      , PRICE_REQUEST_CODE
      , RETURN_ATTRIBUTE14
      , SHIPPING_QUANTITY
      , RETURN_ATTRIBUTE15
      , CANCELLED_QUANTITY
      , PRICING_CONTEXT
      , DEMAND_BUCKET_TYPE_CODE
      , GLOBAL_ATTRIBUTE_CATEGORY
      , RETURN_ATTRIBUTE10
      , RETURN_ATTRIBUTE11
      , RETURN_ATTRIBUTE12
      , REQUEST_DATE
      , RETURN_ATTRIBUTE13
      , TAX_RATE
      , INDUSTRY_ATTRIBUTE26
      , INDUSTRY_ATTRIBUTE25
      , INDUSTRY_ATTRIBUTE24
      , ORG_ID
      , INDUSTRY_ATTRIBUTE23
      , INDUSTRY_ATTRIBUTE22
      , COMPONENT_NUMBER
      , INDUSTRY_ATTRIBUTE21
      , INDUSTRY_ATTRIBUTE20
      , SCHEDULE_STATUS_CODE
      , CANCELLED_FLAG
      , GLOBAL_ATTRIBUTE5
      , DELIVER_TO_CONTACT_ID
      , GLOBAL_ATTRIBUTE4
      , INVOICE_INTERFACE_STATUS_CODE
      , GLOBAL_ATTRIBUTE7
      , OVERRIDE_ATP_DATE_CODE
      , AUTO_SELECTED_QUANTITY
      , GLOBAL_ATTRIBUTE6
      , GLOBAL_ATTRIBUTE1
      , ORDER_FIRMED_DATE
      , GLOBAL_ATTRIBUTE3
      , GLOBAL_ATTRIBUTE2
      , UPGRADED_FLAG
      , TOP_MODEL_LINE_ID
      , GLOBAL_ATTRIBUTE9
      , INDUSTRY_ATTRIBUTE19
      , FOB_POINT_CODE
      , GLOBAL_ATTRIBUTE8
      , INDUSTRY_ATTRIBUTE18
      , BLANKET_LINE_NUMBER
      , MINISITE_ID
      , INDUSTRY_ATTRIBUTE17
      , TAX_EXEMPT_REASON_CODE
      , INDUSTRY_ATTRIBUTE16
      , ORDER_SOURCE_ID
      , ACTUAL_FULFILLMENT_DATE
      , TAX_VALUE
      , LAST_ACK_DATE
      , INDUSTRY_ATTRIBUTE30
      , BOOKED_FLAG
      , END_ITEM_UNIT_NUMBER
      , ACTUAL_ARRIVAL_DATE
      , AGREEMENT_ID
      , LATE_DEMAND_PENALTY_FACTOR
      , INVENTORY_ITEM_ID
      , BLANKET_NUMBER
      , CONFIG_DISPLAY_SEQUENCE
      , INDUSTRY_ATTRIBUTE29
      , INDUSTRY_ATTRIBUTE28
      , TASK_ID
      , INDUSTRY_ATTRIBUTE27
      , TP_CONTEXT
      , SHIP_TO_CONTACT_ID
      , REVREC_EXPIRATION_DAYS
      , CUSTOMER_PAYMENT_TERM_ID
      , REFERENCE_TYPE
      , IB_INSTALLED_AT_LOCATION
      , RE_SOURCE_FLAG
      , MODEL_REMNANT_FLAG
      , LINE_NUMBER
      , COMMITMENT_ID
      , CUSTOMER_PRODUCTION_LINE
      , OPTION_NUMBER
      , ITEM_TYPE_CODE
      , ORDERED_ITEM
      , PRICING_QUANTITY_UOM
      , SHIPPED_QUANTITY
      , BYPASS_SCH_FLAG
      , SALESREP_ID
      , PRICING_ATTRIBUTE10
      , CUSTOMER_ITEM_NET_PRICE
      , PROJECT_ID
      , ORDERED_QUANTITY2
      , INDUSTRY_ATTRIBUTE15
      , INDUSTRY_ATTRIBUTE14
      , INVOICE_TO_CONTACT_ID
      , INDUSTRY_ATTRIBUTE13
      , COMPONENT_CODE
      , INDUSTRY_ATTRIBUTE12
      , INDUSTRY_ATTRIBUTE11
      , UNIT_LIST_PRICE_PER_PQTY
      , INDUSTRY_ATTRIBUTE10
      , GLOBAL_ATTRIBUTE20
      , HEADER_ID
      , CUST_PRODUCTION_SEQ_NUM
      , GLOBAL_ATTRIBUTE17
      , GLOBAL_ATTRIBUTE18
      , GLOBAL_ATTRIBUTE15
      , GLOBAL_ATTRIBUTE16
      , GLOBAL_ATTRIBUTE13
      , GLOBAL_ATTRIBUTE14
      , GLOBAL_ATTRIBUTE11
      , SPLIT_FROM_LINE_ID
      , GLOBAL_ATTRIBUTE12
      , SOURCE_DOCUMENT_LINE_ID
      , ACCEPTED_QUANTITY
      , REVREC_EVENT_CODE
      , GLOBAL_ATTRIBUTE19
      , EQUIPMENT_ID
      , AUTHORIZED_TO_SHIP_FLAG
      , DELIVERY_LEAD_TIME
      , FULFILLED_QUANTITY2
      , VISIBLE_DEMAND_FLAG
      , LAST_UPDATE_DATE
      , SERVICE_REFERENCE_LINE_ID
      , INVOICED_QUANTITY
      , SHIP_TO_ORG_ID
      , INVOICE_TO_ORG_ID
      , SOURCE_DOCUMENT_TYPE_ID
      , ITEM_RELATIONSHIP_TYPE
      , SHIPMENT_NUMBER
      , SHIPPING_INSTRUCTIONS
      , CREATED_BY
      , SHIPPING_METHOD_CODE
      , SOURCE_DOCUMENT_ID
      , CUSTOMER_SHIPMENT_NUMBER
      , CREATION_DATE
      , PRICE_LIST_ID
      , INVOICING_RULE_ID
      , REFERENCE_LINE_ID
      , CHARGE_PERIODICITY_CODE
      , ATO_LINE_ID
      , PROGRAM_UPDATE_DATE
      , DEP_PLAN_REQUIRED_FLAG
      , SERVICE_TXN_COMMENTS
      , PROGRAM_APPLICATION_ID
      , PACKING_INSTRUCTIONS
      , END_CUSTOMER_ID
      , LINE_TYPE_ID
      , OPEN_FLAG
      , MFG_COMPONENT_SEQUENCE_ID
      , PREFERRED_GRADE
      , SHIP_FROM_ORG_ID
      , SALES_DOCUMENT_TYPE_CODE
      , SERVICE_TXN_REASON_CODE
      , FULFILLMENT_METHOD_CODE
      , REQUEST_ID
      , CONTINGENCY_ID
      , MARKETING_SOURCE_CODE_ID
      , SERVICE_REFERENCE_SYSTEM_ID
      , ORIGINAL_ORDERED_ITEM_ID
      , FULFILLED_QUANTITY
      , PRICING_DATE
      , SERVICE_START_DATE
      , OVER_SHIP_REASON_CODE
      , LAST_ACK_CODE
      , SERVICE_DURATION
      , SERVICE_NUMBER
      , LAST_UPDATE_LOGIN
      , ACCOUNTING_RULE_ID
      , END_CUSTOMER_SITE_USE_ID
      , FIRM_DEMAND_FLAG
      , ACCEPTED_BY
      , SERVICE_COTERMINATE_FLAG
      , DEMAND_CLASS_CODE
      , OVER_SHIP_RESOLVED_FLAG
      , ORIG_SYS_SHIPMENT_REF
      , ORDERED_ITEM_ID
      , TAX_CODE
      , FREIGHT_TERMS_CODE
      , PRICING_QUANTITY
      , _FIVETRAN_DELETED
      , _FIVETRAN_ID
      , _FIVETRAN_SYNCED
      , PSA_LOAD_DTS
      , PSA_RECORD_SOURCE
      , PSA_DELETE_IND
      , LOAD_DTS
      , REC_SRC
      , BKCC
      , HASHDIFF
    FROM SRC_SORDLML
)
---- RENAME LAYER ----

, RENAME_SORDLML as (
    SELECT
        ORDER_LINE_HK
      , ORDER_LINE_BK  
      , LINE_ID
      , SERVICE_REFERENCE_TYPE_CODE
      , SUBINVENTORY
      , SOURCE_DOCUMENT_VERSION_NUMBER
      , UNIT_COST
      , PRICING_ATTRIBUTE1
      , PRICING_ATTRIBUTE2
      , INDUSTRY_ATTRIBUTE1
      , CUSTOMER_DOCK_CODE
      , INDUSTRY_ATTRIBUTE2
      , IB_CURRENT_LOCATION
      , INDUSTRY_ATTRIBUTE3
      , INDUSTRY_ATTRIBUTE4
      , INDUSTRY_ATTRIBUTE5
      , INDUSTRY_ATTRIBUTE6
      , INDUSTRY_ATTRIBUTE7
      , INDUSTRY_ATTRIBUTE8
      , PROGRAM_ID
      , CONTEXT
      , INDUSTRY_ATTRIBUTE9
      , SHIPMENT_PRIORITY_CODE
      , ARRIVAL_SET_ID
      , DELIVER_TO_ORG_ID
      , MFG_LEAD_TIME
      , BLANKET_VERSION_NUMBER
      , SHIPPING_INTERFACED_FLAG
      , UNIT_SELLING_PRICE
      , PAYMENT_TYPE_CODE
      , PRICING_ATTRIBUTE5
      , PRICING_ATTRIBUTE6
      , PRICING_ATTRIBUTE3
      , PRICING_ATTRIBUTE4
      , REVREC_COMMENTS
      , PRICING_ATTRIBUTE9
      , PRICING_ATTRIBUTE7
      , PRICING_ATTRIBUTE8
      , ATTRIBUTE3
      , ATTRIBUTE2
      , TP_ATTRIBUTE15
      , ORDER_QUANTITY_UOM
      , ATTRIBUTE1
      , TP_ATTRIBUTE14
      , FREIGHT_CARRIER_CODE
      , TP_ATTRIBUTE13
      , TP_ATTRIBUTE12
      , TP_ATTRIBUTE11
      , TP_ATTRIBUTE10
      , EARLIEST_SHIP_DATE
      , CALCULATE_PRICE_FLAG
      , ORDERED_QUANTITY_UOM2
      , ATTRIBUTE9
      , SCHEDULE_SHIP_DATE
      , ATTRIBUTE8
      , ATTRIBUTE7
      , ATTRIBUTE6
      , SHIP_SET_ID
      , ITEM_IDENTIFIER_TYPE
      , ATTRIBUTE5
      , SCHEDULE_ARRIVAL_DATE
      , ATTRIBUTE4
      , TRANSACTION_PHASE_CODE
      , CUST_PO_NUMBER
      , REFERENCE_CUSTOMER_TRX_LINE_ID
      , SHIP_TOLERANCE_BELOW
      , ORDERED_QUANTITY
      , TAX_DATE
      , ATTRIBUTE10
      , ORIG_SYS_DOCUMENT_REF
      , OPTION_FLAG
      , ATTRIBUTE14
      , ATTRIBUTE13
      , ATTRIBUTE12
      , ATTRIBUTE11
      , DROP_SHIP_FLAG
      , SHIP_TOLERANCE_ABOVE
      , UNIT_SELLING_PRICE_PER_PQTY
      , CONFIGURATION_ID
      , CONFIG_HEADER_ID
      , FLOW_STATUS_CODE
      , COMPONENT_SEQUENCE_ID
      , FULFILLED_FLAG
      , ACCOUNTING_RULE_DURATION
      , CONFIG_REV_NBR
      , CUSTOMER_JOB
      , ATTRIBUTE20
      , SHIP_MODEL_COMPLETE_FLAG
      , SERVICE_CREDIT_ELIGIBLE_CODE
      , CUSTOMER_TRX_LINE_ID
      , ITEM_REVISION
      , SOURCE_TYPE_CODE
      , REVREC_REFERENCE_DOCUMENT
      , CANCELLED_QUANTITY2
      , ACTUAL_SHIPMENT_DATE
      , SPLIT_BY
      , FULFILLMENT_DATE
      , SERVICE_END_DATE
      , SHIPPED_QUANTITY2
      , EXPLOSION_DATE
      , CUSTOMER_LINE_NUMBER
      , RLA_SCHEDULE_TYPE_CODE
      , RETURN_REASON_CODE
      , ATTRIBUTE18
      , SORT_ORDER
      , ATTRIBUTE17
      , ATTRIBUTE16
      , UNIT_SELLING_PERCENT
      , ATTRIBUTE15
      , ATTRIBUTE19
      , VEH_CUS_ITEM_CUM_KEY_ID
      , REVREC_SIGNATURE_DATE
      , FIRST_ACK_CODE
      , ORIG_SYS_LINE_REF
      , PRE_EXPLODED_FLAG
      , LINE_SET_ID
      , RETURN_CONTEXT
      , TAX_POINT_CODE
      , GLOBAL_ATTRIBUTE10
      , ORIGINAL_ITEM_IDENTIFIER_TYPE
      , PROMISE_DATE
      , USER_ITEM_DESCRIPTION
      , LOCK_CONTROL
      , REVREC_SIGNATURE
      , REFERENCE_HEADER_ID
      , INTMED_SHIP_TO_CONTACT_ID
      , ORIGINAL_INVENTORY_ITEM_ID
      , CUST_MODEL_SERIAL_NUMBER
      , CHANGE_SEQUENCE
      , TP_ATTRIBUTE9
      , UNIT_LIST_PRICE
      , RETROBILL_REQUEST_ID
      , SOLD_FROM_ORG_ID
      , EARLIEST_ACCEPTABLE_DATE
      , LAST_UPDATED_BY
      , PAYMENT_TERM_ID
      , ITEM_SUBSTITUTION_TYPE_CODE
      , UNIT_PERCENT_BASE_PRICE
      , PLANNING_PRIORITY
      , TP_ATTRIBUTE8
      , LATEST_ACCEPTABLE_DATE
      , TP_ATTRIBUTE7
      , TP_ATTRIBUTE6
      , SHIPPABLE_FLAG
      , TP_ATTRIBUTE5
      , TP_ATTRIBUTE4
      , TP_ATTRIBUTE3
      , TP_ATTRIBUTE2
      , TP_ATTRIBUTE1
      , END_CUSTOMER_CONTACT_ID
      , LINK_TO_LINE_ID
      , ORIGINAL_ORDERED_ITEM
      , UNIT_LIST_PERCENT
      , ORIGINAL_LIST_PRICE
      , SHIPPING_QUANTITY_UOM
      , RETURN_ATTRIBUTE8
      , RETURN_ATTRIBUTE7
      , SHIPPING_QUANTITY_UOM2
      , IB_OWNER
      , REVREC_IMPLICIT_FLAG
      , RETURN_ATTRIBUTE6
      , FIRST_ACK_DATE
      , RETURN_ATTRIBUTE5
      , SHIPPING_QUANTITY2
      , RETURN_ATTRIBUTE9
      , TAX_EXEMPT_NUMBER
      , RETURN_ATTRIBUTE4
      , LINE_CATEGORY_CODE
      , RETURN_ATTRIBUTE3
      , INDUSTRY_CONTEXT
      , RETURN_ATTRIBUTE2
      , SERVICE_PERIOD
      , REVENUE_AMOUNT
      , RETURN_ATTRIBUTE1
      , CREDIT_INVOICE_LINE_ID
      , MODEL_GROUP_NUMBER
      , INTMED_SHIP_TO_ORG_ID
      , TAX_EXEMPT_FLAG
      , SOLD_TO_ORG_ID
      , PRICE_REQUEST_CODE
      , RETURN_ATTRIBUTE14
      , SHIPPING_QUANTITY
      , RETURN_ATTRIBUTE15
      , CANCELLED_QUANTITY
      , PRICING_CONTEXT
      , DEMAND_BUCKET_TYPE_CODE
      , GLOBAL_ATTRIBUTE_CATEGORY
      , RETURN_ATTRIBUTE10
      , RETURN_ATTRIBUTE11
      , RETURN_ATTRIBUTE12
      , REQUEST_DATE
      , RETURN_ATTRIBUTE13
      , TAX_RATE
      , INDUSTRY_ATTRIBUTE26
      , INDUSTRY_ATTRIBUTE25
      , INDUSTRY_ATTRIBUTE24
      , ORG_ID
      , INDUSTRY_ATTRIBUTE23
      , INDUSTRY_ATTRIBUTE22
      , COMPONENT_NUMBER
      , INDUSTRY_ATTRIBUTE21
      , INDUSTRY_ATTRIBUTE20
      , SCHEDULE_STATUS_CODE
      , CANCELLED_FLAG
      , GLOBAL_ATTRIBUTE5
      , DELIVER_TO_CONTACT_ID
      , GLOBAL_ATTRIBUTE4
      , INVOICE_INTERFACE_STATUS_CODE
      , GLOBAL_ATTRIBUTE7
      , OVERRIDE_ATP_DATE_CODE
      , AUTO_SELECTED_QUANTITY
      , GLOBAL_ATTRIBUTE6
      , GLOBAL_ATTRIBUTE1
      , ORDER_FIRMED_DATE
      , GLOBAL_ATTRIBUTE3
      , GLOBAL_ATTRIBUTE2
      , UPGRADED_FLAG
      , TOP_MODEL_LINE_ID
      , GLOBAL_ATTRIBUTE9
      , INDUSTRY_ATTRIBUTE19
      , FOB_POINT_CODE
      , GLOBAL_ATTRIBUTE8
      , INDUSTRY_ATTRIBUTE18
      , BLANKET_LINE_NUMBER
      , MINISITE_ID
      , INDUSTRY_ATTRIBUTE17
      , TAX_EXEMPT_REASON_CODE
      , INDUSTRY_ATTRIBUTE16
      , ORDER_SOURCE_ID
      , ACTUAL_FULFILLMENT_DATE
      , TAX_VALUE
      , LAST_ACK_DATE
      , INDUSTRY_ATTRIBUTE30
      , BOOKED_FLAG
      , END_ITEM_UNIT_NUMBER
      , ACTUAL_ARRIVAL_DATE
      , AGREEMENT_ID
      , LATE_DEMAND_PENALTY_FACTOR
      , INVENTORY_ITEM_ID
      , BLANKET_NUMBER
      , CONFIG_DISPLAY_SEQUENCE
      , INDUSTRY_ATTRIBUTE29
      , INDUSTRY_ATTRIBUTE28
      , TASK_ID
      , INDUSTRY_ATTRIBUTE27
      , TP_CONTEXT
      , SHIP_TO_CONTACT_ID
      , REVREC_EXPIRATION_DAYS
      , CUSTOMER_PAYMENT_TERM_ID
      , REFERENCE_TYPE
      , IB_INSTALLED_AT_LOCATION
      , RE_SOURCE_FLAG
      , MODEL_REMNANT_FLAG
      , LINE_NUMBER
      , COMMITMENT_ID
      , CUSTOMER_PRODUCTION_LINE
      , OPTION_NUMBER
      , ITEM_TYPE_CODE
      , ORDERED_ITEM
      , PRICING_QUANTITY_UOM
      , SHIPPED_QUANTITY
      , BYPASS_SCH_FLAG
      , SALESREP_ID
      , PRICING_ATTRIBUTE10
      , CUSTOMER_ITEM_NET_PRICE
      , PROJECT_ID
      , ORDERED_QUANTITY2
      , INDUSTRY_ATTRIBUTE15
      , INDUSTRY_ATTRIBUTE14
      , INVOICE_TO_CONTACT_ID
      , INDUSTRY_ATTRIBUTE13
      , COMPONENT_CODE
      , INDUSTRY_ATTRIBUTE12
      , INDUSTRY_ATTRIBUTE11
      , UNIT_LIST_PRICE_PER_PQTY
      , INDUSTRY_ATTRIBUTE10
      , GLOBAL_ATTRIBUTE20
      , HEADER_ID
      , CUST_PRODUCTION_SEQ_NUM
      , GLOBAL_ATTRIBUTE17
      , GLOBAL_ATTRIBUTE18
      , GLOBAL_ATTRIBUTE15
      , GLOBAL_ATTRIBUTE16
      , GLOBAL_ATTRIBUTE13
      , GLOBAL_ATTRIBUTE14
      , GLOBAL_ATTRIBUTE11
      , SPLIT_FROM_LINE_ID
      , GLOBAL_ATTRIBUTE12
      , SOURCE_DOCUMENT_LINE_ID
      , ACCEPTED_QUANTITY
      , REVREC_EVENT_CODE
      , GLOBAL_ATTRIBUTE19
      , EQUIPMENT_ID
      , AUTHORIZED_TO_SHIP_FLAG
      , DELIVERY_LEAD_TIME
      , FULFILLED_QUANTITY2
      , VISIBLE_DEMAND_FLAG
      , LAST_UPDATE_DATE
      , SERVICE_REFERENCE_LINE_ID
      , INVOICED_QUANTITY
      , SHIP_TO_ORG_ID
      , INVOICE_TO_ORG_ID
      , SOURCE_DOCUMENT_TYPE_ID
      , ITEM_RELATIONSHIP_TYPE
      , SHIPMENT_NUMBER
      , SHIPPING_INSTRUCTIONS
      , CREATED_BY
      , SHIPPING_METHOD_CODE
      , SOURCE_DOCUMENT_ID
      , CUSTOMER_SHIPMENT_NUMBER
      , CREATION_DATE
      , PRICE_LIST_ID
      , INVOICING_RULE_ID
      , REFERENCE_LINE_ID
      , CHARGE_PERIODICITY_CODE
      , ATO_LINE_ID
      , PROGRAM_UPDATE_DATE
      , DEP_PLAN_REQUIRED_FLAG
      , SERVICE_TXN_COMMENTS
      , PROGRAM_APPLICATION_ID
      , PACKING_INSTRUCTIONS
      , END_CUSTOMER_ID
      , LINE_TYPE_ID
      , OPEN_FLAG
      , MFG_COMPONENT_SEQUENCE_ID
      , PREFERRED_GRADE
      , SHIP_FROM_ORG_ID
      , SALES_DOCUMENT_TYPE_CODE
      , SERVICE_TXN_REASON_CODE
      , FULFILLMENT_METHOD_CODE
      , REQUEST_ID
      , CONTINGENCY_ID
      , MARKETING_SOURCE_CODE_ID
      , SERVICE_REFERENCE_SYSTEM_ID
      , ORIGINAL_ORDERED_ITEM_ID
      , FULFILLED_QUANTITY
      , PRICING_DATE
      , SERVICE_START_DATE
      , OVER_SHIP_REASON_CODE
      , LAST_ACK_CODE
      , SERVICE_DURATION
      , SERVICE_NUMBER
      , LAST_UPDATE_LOGIN
      , ACCOUNTING_RULE_ID
      , END_CUSTOMER_SITE_USE_ID
      , FIRM_DEMAND_FLAG
      , ACCEPTED_BY
      , SERVICE_COTERMINATE_FLAG
      , DEMAND_CLASS_CODE
      , OVER_SHIP_RESOLVED_FLAG
      , ORIG_SYS_SHIPMENT_REF
      , ORDERED_ITEM_ID
      , TAX_CODE
      , FREIGHT_TERMS_CODE
      , PRICING_QUANTITY
      , _FIVETRAN_DELETED
      , _FIVETRAN_ID
      , _FIVETRAN_SYNCED
      , PSA_LOAD_DTS
      , PSA_RECORD_SOURCE
      , PSA_DELETE_IND
      , LOAD_DTS
      , REC_SRC
      , BKCC
      , HASHDIFF
    FROM LOGIC_SORDLML
)
---- FILTER LAYER ----

, FILTER_SORDLML as (
    SELECT *
    FROM RENAME_SORDLML
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM FILTER_SORDLML
)

---- FINAL LAYER ----
SELECT
          ORDER_LINE_HK
        , ORDER_LINE_BK  
        , LINE_ID
        , SERVICE_REFERENCE_TYPE_CODE
        , SUBINVENTORY
        , SOURCE_DOCUMENT_VERSION_NUMBER
        , UNIT_COST
        , PRICING_ATTRIBUTE1
        , PRICING_ATTRIBUTE2
        , INDUSTRY_ATTRIBUTE1
        , CUSTOMER_DOCK_CODE
        , INDUSTRY_ATTRIBUTE2
        , IB_CURRENT_LOCATION
        , INDUSTRY_ATTRIBUTE3
        , INDUSTRY_ATTRIBUTE4
        , INDUSTRY_ATTRIBUTE5
        , INDUSTRY_ATTRIBUTE6
        , INDUSTRY_ATTRIBUTE7
        , INDUSTRY_ATTRIBUTE8
        , PROGRAM_ID
        , CONTEXT
        , INDUSTRY_ATTRIBUTE9
        , SHIPMENT_PRIORITY_CODE
        , ARRIVAL_SET_ID
        , DELIVER_TO_ORG_ID
        , MFG_LEAD_TIME
        , BLANKET_VERSION_NUMBER
        , SHIPPING_INTERFACED_FLAG
        , UNIT_SELLING_PRICE
        , PAYMENT_TYPE_CODE
        , PRICING_ATTRIBUTE5
        , PRICING_ATTRIBUTE6
        , PRICING_ATTRIBUTE3
        , PRICING_ATTRIBUTE4
        , REVREC_COMMENTS
        , PRICING_ATTRIBUTE9
        , PRICING_ATTRIBUTE7
        , PRICING_ATTRIBUTE8
        , ATTRIBUTE3
        , ATTRIBUTE2
        , TP_ATTRIBUTE15
        , ORDER_QUANTITY_UOM
        , ATTRIBUTE1
        , TP_ATTRIBUTE14
        , FREIGHT_CARRIER_CODE
        , TP_ATTRIBUTE13
        , TP_ATTRIBUTE12
        , TP_ATTRIBUTE11
        , TP_ATTRIBUTE10
        , EARLIEST_SHIP_DATE
        , CALCULATE_PRICE_FLAG
        , ORDERED_QUANTITY_UOM2
        , ATTRIBUTE9
        , SCHEDULE_SHIP_DATE
        , ATTRIBUTE8
        , ATTRIBUTE7
        , ATTRIBUTE6
        , SHIP_SET_ID
        , ITEM_IDENTIFIER_TYPE
        , ATTRIBUTE5
        , SCHEDULE_ARRIVAL_DATE
        , ATTRIBUTE4
        , TRANSACTION_PHASE_CODE
        , CUST_PO_NUMBER
        , REFERENCE_CUSTOMER_TRX_LINE_ID
        , SHIP_TOLERANCE_BELOW
        , ORDERED_QUANTITY
        , TAX_DATE
        , ATTRIBUTE10
        , ORIG_SYS_DOCUMENT_REF
        , OPTION_FLAG
        , ATTRIBUTE14
        , ATTRIBUTE13
        , ATTRIBUTE12
        , ATTRIBUTE11
        , DROP_SHIP_FLAG
        , SHIP_TOLERANCE_ABOVE
        , UNIT_SELLING_PRICE_PER_PQTY
        , CONFIGURATION_ID
        , CONFIG_HEADER_ID
        , FLOW_STATUS_CODE
        , COMPONENT_SEQUENCE_ID
        , FULFILLED_FLAG
        , ACCOUNTING_RULE_DURATION
        , CONFIG_REV_NBR
        , CUSTOMER_JOB
        , ATTRIBUTE20
        , SHIP_MODEL_COMPLETE_FLAG
        , SERVICE_CREDIT_ELIGIBLE_CODE
        , CUSTOMER_TRX_LINE_ID
        , ITEM_REVISION
        , SOURCE_TYPE_CODE
        , REVREC_REFERENCE_DOCUMENT
        , CANCELLED_QUANTITY2
        , ACTUAL_SHIPMENT_DATE
        , SPLIT_BY
        , FULFILLMENT_DATE
        , SERVICE_END_DATE
        , SHIPPED_QUANTITY2
        , EXPLOSION_DATE
        , CUSTOMER_LINE_NUMBER
        , RLA_SCHEDULE_TYPE_CODE
        , RETURN_REASON_CODE
        , ATTRIBUTE18
        , SORT_ORDER
        , ATTRIBUTE17
        , ATTRIBUTE16
        , UNIT_SELLING_PERCENT
        , ATTRIBUTE15
        , ATTRIBUTE19
        , VEH_CUS_ITEM_CUM_KEY_ID
        , REVREC_SIGNATURE_DATE
        , FIRST_ACK_CODE
        , ORIG_SYS_LINE_REF
        , PRE_EXPLODED_FLAG
        , LINE_SET_ID
        , RETURN_CONTEXT
        , TAX_POINT_CODE
        , GLOBAL_ATTRIBUTE10
        , ORIGINAL_ITEM_IDENTIFIER_TYPE
        , PROMISE_DATE
        , USER_ITEM_DESCRIPTION
        , LOCK_CONTROL
        , REVREC_SIGNATURE
        , REFERENCE_HEADER_ID
        , INTMED_SHIP_TO_CONTACT_ID
        , ORIGINAL_INVENTORY_ITEM_ID
        , CUST_MODEL_SERIAL_NUMBER
        , CHANGE_SEQUENCE
        , TP_ATTRIBUTE9
        , UNIT_LIST_PRICE
        , RETROBILL_REQUEST_ID
        , SOLD_FROM_ORG_ID
        , EARLIEST_ACCEPTABLE_DATE
        , LAST_UPDATED_BY
        , PAYMENT_TERM_ID
        , ITEM_SUBSTITUTION_TYPE_CODE
        , UNIT_PERCENT_BASE_PRICE
        , PLANNING_PRIORITY
        , TP_ATTRIBUTE8
        , LATEST_ACCEPTABLE_DATE
        , TP_ATTRIBUTE7
        , TP_ATTRIBUTE6
        , SHIPPABLE_FLAG
        , TP_ATTRIBUTE5
        , TP_ATTRIBUTE4
        , TP_ATTRIBUTE3
        , TP_ATTRIBUTE2
        , TP_ATTRIBUTE1
        , END_CUSTOMER_CONTACT_ID
        , LINK_TO_LINE_ID
        , ORIGINAL_ORDERED_ITEM
        , UNIT_LIST_PERCENT
        , ORIGINAL_LIST_PRICE
        , SHIPPING_QUANTITY_UOM
        , RETURN_ATTRIBUTE8
        , RETURN_ATTRIBUTE7
        , SHIPPING_QUANTITY_UOM2
        , IB_OWNER
        , REVREC_IMPLICIT_FLAG
        , RETURN_ATTRIBUTE6
        , FIRST_ACK_DATE
        , RETURN_ATTRIBUTE5
        , SHIPPING_QUANTITY2
        , RETURN_ATTRIBUTE9
        , TAX_EXEMPT_NUMBER
        , RETURN_ATTRIBUTE4
        , LINE_CATEGORY_CODE
        , RETURN_ATTRIBUTE3
        , INDUSTRY_CONTEXT
        , RETURN_ATTRIBUTE2
        , SERVICE_PERIOD
        , REVENUE_AMOUNT
        , RETURN_ATTRIBUTE1
        , CREDIT_INVOICE_LINE_ID
        , MODEL_GROUP_NUMBER
        , INTMED_SHIP_TO_ORG_ID
        , TAX_EXEMPT_FLAG
        , SOLD_TO_ORG_ID
        , PRICE_REQUEST_CODE
        , RETURN_ATTRIBUTE14
        , SHIPPING_QUANTITY
        , RETURN_ATTRIBUTE15
        , CANCELLED_QUANTITY
        , PRICING_CONTEXT
        , DEMAND_BUCKET_TYPE_CODE
        , GLOBAL_ATTRIBUTE_CATEGORY
        , RETURN_ATTRIBUTE10
        , RETURN_ATTRIBUTE11
        , RETURN_ATTRIBUTE12
        , REQUEST_DATE
        , RETURN_ATTRIBUTE13
        , TAX_RATE
        , INDUSTRY_ATTRIBUTE26
        , INDUSTRY_ATTRIBUTE25
        , INDUSTRY_ATTRIBUTE24
        , ORG_ID
        , INDUSTRY_ATTRIBUTE23
        , INDUSTRY_ATTRIBUTE22
        , COMPONENT_NUMBER
        , INDUSTRY_ATTRIBUTE21
        , INDUSTRY_ATTRIBUTE20
        , SCHEDULE_STATUS_CODE
        , CANCELLED_FLAG
        , GLOBAL_ATTRIBUTE5
        , DELIVER_TO_CONTACT_ID
        , GLOBAL_ATTRIBUTE4
        , INVOICE_INTERFACE_STATUS_CODE
        , GLOBAL_ATTRIBUTE7
        , OVERRIDE_ATP_DATE_CODE
        , AUTO_SELECTED_QUANTITY
        , GLOBAL_ATTRIBUTE6
        , GLOBAL_ATTRIBUTE1
        , ORDER_FIRMED_DATE
        , GLOBAL_ATTRIBUTE3
        , GLOBAL_ATTRIBUTE2
        , UPGRADED_FLAG
        , TOP_MODEL_LINE_ID
        , GLOBAL_ATTRIBUTE9
        , INDUSTRY_ATTRIBUTE19
        , FOB_POINT_CODE
        , GLOBAL_ATTRIBUTE8
        , INDUSTRY_ATTRIBUTE18
        , BLANKET_LINE_NUMBER
        , MINISITE_ID
        , INDUSTRY_ATTRIBUTE17
        , TAX_EXEMPT_REASON_CODE
        , INDUSTRY_ATTRIBUTE16
        , ORDER_SOURCE_ID
        , ACTUAL_FULFILLMENT_DATE
        , TAX_VALUE
        , LAST_ACK_DATE
        , INDUSTRY_ATTRIBUTE30
        , BOOKED_FLAG
        , END_ITEM_UNIT_NUMBER
        , ACTUAL_ARRIVAL_DATE
        , AGREEMENT_ID
        , LATE_DEMAND_PENALTY_FACTOR
        , INVENTORY_ITEM_ID
        , BLANKET_NUMBER
        , CONFIG_DISPLAY_SEQUENCE
        , INDUSTRY_ATTRIBUTE29
        , INDUSTRY_ATTRIBUTE28
        , TASK_ID
        , INDUSTRY_ATTRIBUTE27
        , TP_CONTEXT
        , SHIP_TO_CONTACT_ID
        , REVREC_EXPIRATION_DAYS
        , CUSTOMER_PAYMENT_TERM_ID
        , REFERENCE_TYPE
        , IB_INSTALLED_AT_LOCATION
        , RE_SOURCE_FLAG
        , MODEL_REMNANT_FLAG
        , LINE_NUMBER
        , COMMITMENT_ID
        , CUSTOMER_PRODUCTION_LINE
        , OPTION_NUMBER
        , ITEM_TYPE_CODE
        , ORDERED_ITEM
        , PRICING_QUANTITY_UOM
        , SHIPPED_QUANTITY
        , BYPASS_SCH_FLAG
        , SALESREP_ID
        , PRICING_ATTRIBUTE10
        , CUSTOMER_ITEM_NET_PRICE
        , PROJECT_ID
        , ORDERED_QUANTITY2
        , INDUSTRY_ATTRIBUTE15
        , INDUSTRY_ATTRIBUTE14
        , INVOICE_TO_CONTACT_ID
        , INDUSTRY_ATTRIBUTE13
        , COMPONENT_CODE
        , INDUSTRY_ATTRIBUTE12
        , INDUSTRY_ATTRIBUTE11
        , UNIT_LIST_PRICE_PER_PQTY
        , INDUSTRY_ATTRIBUTE10
        , GLOBAL_ATTRIBUTE20
        , HEADER_ID
        , CUST_PRODUCTION_SEQ_NUM
        , GLOBAL_ATTRIBUTE17
        , GLOBAL_ATTRIBUTE18
        , GLOBAL_ATTRIBUTE15
        , GLOBAL_ATTRIBUTE16
        , GLOBAL_ATTRIBUTE13
        , GLOBAL_ATTRIBUTE14
        , GLOBAL_ATTRIBUTE11
        , SPLIT_FROM_LINE_ID
        , GLOBAL_ATTRIBUTE12
        , SOURCE_DOCUMENT_LINE_ID
        , ACCEPTED_QUANTITY
        , REVREC_EVENT_CODE
        , GLOBAL_ATTRIBUTE19
        , EQUIPMENT_ID
        , AUTHORIZED_TO_SHIP_FLAG
        , DELIVERY_LEAD_TIME
        , FULFILLED_QUANTITY2
        , VISIBLE_DEMAND_FLAG
        , LAST_UPDATE_DATE
        , SERVICE_REFERENCE_LINE_ID
        , INVOICED_QUANTITY
        , SHIP_TO_ORG_ID
        , INVOICE_TO_ORG_ID
        , SOURCE_DOCUMENT_TYPE_ID
        , ITEM_RELATIONSHIP_TYPE
        , SHIPMENT_NUMBER
        , SHIPPING_INSTRUCTIONS
        , CREATED_BY
        , SHIPPING_METHOD_CODE
        , SOURCE_DOCUMENT_ID
        , CUSTOMER_SHIPMENT_NUMBER
        , CREATION_DATE
        , PRICE_LIST_ID
        , INVOICING_RULE_ID
        , REFERENCE_LINE_ID
        , CHARGE_PERIODICITY_CODE
        , ATO_LINE_ID
        , PROGRAM_UPDATE_DATE
        , DEP_PLAN_REQUIRED_FLAG
        , SERVICE_TXN_COMMENTS
        , PROGRAM_APPLICATION_ID
        , PACKING_INSTRUCTIONS
        , END_CUSTOMER_ID
        , LINE_TYPE_ID
        , OPEN_FLAG
        , MFG_COMPONENT_SEQUENCE_ID
        , PREFERRED_GRADE
        , SHIP_FROM_ORG_ID
        , SALES_DOCUMENT_TYPE_CODE
        , SERVICE_TXN_REASON_CODE
        , FULFILLMENT_METHOD_CODE
        , REQUEST_ID
        , CONTINGENCY_ID
        , MARKETING_SOURCE_CODE_ID
        , SERVICE_REFERENCE_SYSTEM_ID
        , ORIGINAL_ORDERED_ITEM_ID
        , FULFILLED_QUANTITY
        , PRICING_DATE
        , SERVICE_START_DATE
        , OVER_SHIP_REASON_CODE
        , LAST_ACK_CODE
        , SERVICE_DURATION
        , SERVICE_NUMBER
        , LAST_UPDATE_LOGIN
        , ACCOUNTING_RULE_ID
        , END_CUSTOMER_SITE_USE_ID
        , FIRM_DEMAND_FLAG
        , ACCEPTED_BY
        , SERVICE_COTERMINATE_FLAG
        , DEMAND_CLASS_CODE
        , OVER_SHIP_RESOLVED_FLAG
        , ORIG_SYS_SHIPMENT_REF
        , ORDERED_ITEM_ID
        , TAX_CODE
        , FREIGHT_TERMS_CODE
        , PRICING_QUANTITY
        , _FIVETRAN_DELETED
        , _FIVETRAN_ID
        , _FIVETRAN_SYNCED
        , PSA_LOAD_DTS
        , PSA_RECORD_SOURCE
        , PSA_DELETE_IND
        , LOAD_DTS
        , REC_SRC
        , BKCC
        , HASHDIFF
FROM JOIN_RESULT
{% if is_incremental() %}
WHERE NOT EXISTS (
    SELECT 1 
    FROM {{ this }} existing
    WHERE existing.ORDER_LINE_HK = JOIN_RESULT.ORDER_LINE_HK 
    AND existing.HASHDIFF = JOIN_RESULT.HASHDIFF
)
{% endif %} 
{% if not is_incremental() %}
/*the following qualify is to restrict multiple loads of touched records during the initial build. Ex: multiple row per hk, hashdiff */
qualify 1= row_number()over(partition by ORDER_LINE_BK , HASHDIFF order by PSA_LOAD_DTS)
union all
    SELECT        
    MD5_BINARY(GR.VALUE) AS ORDER_LINE_HK
    , null as ORDER_LINE_BK
    , GR.VALUE::NUMBER as LINE_ID
    , null as SERVICE_REFERENCE_TYPE_CODE
    , null as SUBINVENTORY
    , null as SOURCE_DOCUMENT_VERSION_NUMBER
    , null as UNIT_COST
    , null as PRICING_ATTRIBUTE1
    , null as PRICING_ATTRIBUTE2
    , null as INDUSTRY_ATTRIBUTE1
    , null as CUSTOMER_DOCK_CODE
    , null as INDUSTRY_ATTRIBUTE2
    , null as IB_CURRENT_LOCATION
    , null as INDUSTRY_ATTRIBUTE3
    , null as INDUSTRY_ATTRIBUTE4
    , null as INDUSTRY_ATTRIBUTE5
    , null as INDUSTRY_ATTRIBUTE6
    , null as INDUSTRY_ATTRIBUTE7
    , null as INDUSTRY_ATTRIBUTE8
    , null as PROGRAM_ID
    , null as CONTEXT
    , null as INDUSTRY_ATTRIBUTE9
    , null as SHIPMENT_PRIORITY_CODE
    , null as ARRIVAL_SET_ID
    , null as DELIVER_TO_ORG_ID    
    , null as MFG_LEAD_TIME
    , null as BLANKET_VERSION_NUMBER
    , null as SHIPPING_INTERFACED_FLAG
    , null as UNIT_SELLING_PRICE
    , null as PAYMENT_TYPE_CODE
    , null as PRICING_ATTRIBUTE5
    , null as PRICING_ATTRIBUTE6
    , null as PRICING_ATTRIBUTE3
    , null as PRICING_ATTRIBUTE4
    , null as REVREC_COMMENTS
    , null as PRICING_ATTRIBUTE9
    , null as PRICING_ATTRIBUTE7
    , null as PRICING_ATTRIBUTE8
    , null as ATTRIBUTE3
    , null as ATTRIBUTE2
    , null as TP_ATTRIBUTE15
    , null as ORDER_QUANTITY_UOM
    , null as ATTRIBUTE1
    , null as TP_ATTRIBUTE14
    , null as FREIGHT_CARRIER_CODE
    , null as TP_ATTRIBUTE13
    , null as TP_ATTRIBUTE12
    , null as TP_ATTRIBUTE11
    , null as TP_ATTRIBUTE10
    , null as EARLIEST_SHIP_DATE
    , null as CALCULATE_PRICE_FLAG
    , null as ORDERED_QUANTITY_UOM2
    , null as ATTRIBUTE9
    , null as SCHEDULE_SHIP_DATE
    , null as ATTRIBUTE8
    , null as ATTRIBUTE7
    , null as ATTRIBUTE6
    , null as SHIP_SET_ID
    , null as ITEM_IDENTIFIER_TYPE
    , null as ATTRIBUTE5
    , null as SCHEDULE_ARRIVAL_DATE
    , null as ATTRIBUTE4
    , null as TRANSACTION_PHASE_CODE
    , null as CUST_PO_NUMBER
    , null as REFERENCE_CUSTOMER_TRX_LINE_ID
    , null as SHIP_TOLERANCE_BELOW
    , null as ORDERED_QUANTITY
    , null as TAX_DATE
    , null as ATTRIBUTE10
    , null as ORIG_SYS_DOCUMENT_REF
    , null as OPTION_FLAG
    , null as ATTRIBUTE14
    , null as ATTRIBUTE13
    , null as ATTRIBUTE12
    , null as ATTRIBUTE11
    , null as DROP_SHIP_FLAG
    , null as SHIP_TOLERANCE_ABOVE
    , null as UNIT_SELLING_PRICE_PER_PQTY
    , null as CONFIGURATION_ID
    , null as CONFIG_HEADER_ID
    , null as FLOW_STATUS_CODE
    , null as COMPONENT_SEQUENCE_ID
    , null as FULFILLED_FLAG
    , null as ACCOUNTING_RULE_DURATION
    , null as CONFIG_REV_NBR
    , null as CUSTOMER_JOB
    , null as ATTRIBUTE20
    , null as SHIP_MODEL_COMPLETE_FLAG
    , null as SERVICE_CREDIT_ELIGIBLE_CODE
    , null as CUSTOMER_TRX_LINE_ID
    , null as ITEM_REVISION
    , null as SOURCE_TYPE_CODE
    , null as REVREC_REFERENCE_DOCUMENT
    , null as CANCELLED_QUANTITY2
    , null as ACTUAL_SHIPMENT_DATE
    , null as SPLIT_BY
    , null as FULFILLMENT_DATE
    , null as SERVICE_END_DATE
    , null as SHIPPED_QUANTITY2
    , null as EXPLOSION_DATE
    , null as CUSTOMER_LINE_NUMBER
    , null as RLA_SCHEDULE_TYPE_CODE
    , null as RETURN_REASON_CODE
    , null as ATTRIBUTE18
    , null as SORT_ORDER
    , null as ATTRIBUTE17
    , null as ATTRIBUTE16
    , null as UNIT_SELLING_PERCENT
    , null as ATTRIBUTE15
    , null as ATTRIBUTE19
    , null as VEH_CUS_ITEM_CUM_KEY_ID
    , null as REVREC_SIGNATURE_DATE
    , null as FIRST_ACK_CODE
    , null as ORIG_SYS_LINE_REF
    , null as PRE_EXPLODED_FLAG
    , null as LINE_SET_ID
    , null as RETURN_CONTEXT
    , null as TAX_POINT_CODE
    , null as GLOBAL_ATTRIBUTE10
    , null as ORIGINAL_ITEM_IDENTIFIER_TYPE
    , null as PROMISE_DATE
    , null as USER_ITEM_DESCRIPTION
    , null as LOCK_CONTROL
    , null as REVREC_SIGNATURE
    , null as REFERENCE_HEADER_ID
    , null as INTMED_SHIP_TO_CONTACT_ID
    , null as ORIGINAL_INVENTORY_ITEM_ID
    , null as CUST_MODEL_SERIAL_NUMBER
    , null as CHANGE_SEQUENCE
    , null as TP_ATTRIBUTE9
    , null as UNIT_LIST_PRICE
    , null as RETROBILL_REQUEST_ID
    , null as SOLD_FROM_ORG_ID
    , null as EARLIEST_ACCEPTABLE_DATE
    , null as LAST_UPDATED_BY
    , null as PAYMENT_TERM_ID
    , null as ITEM_SUBSTITUTION_TYPE_CODE
    , null as UNIT_PERCENT_BASE_PRICE
    , null as PLANNING_PRIORITY
    , null as TP_ATTRIBUTE8
    , null as LATEST_ACCEPTABLE_DATE
    , null as TP_ATTRIBUTE7
    , null as TP_ATTRIBUTE6
    , null as SHIPPABLE_FLAG
    , null as TP_ATTRIBUTE5
    , null as TP_ATTRIBUTE4
    , null as TP_ATTRIBUTE3
    , null as TP_ATTRIBUTE2
    , null as TP_ATTRIBUTE1
    , null as END_CUSTOMER_CONTACT_ID
    , null as LINK_TO_LINE_ID
    , null as ORIGINAL_ORDERED_ITEM
    , null as UNIT_LIST_PERCENT
    , null as ORIGINAL_LIST_PRICE
    , null as SHIPPING_QUANTITY_UOM
    , null as RETURN_ATTRIBUTE8
    , null as RETURN_ATTRIBUTE7
    , null as SHIPPING_QUANTITY_UOM2
    , null as IB_OWNER
    , null as REVREC_IMPLICIT_FLAG
    , null as RETURN_ATTRIBUTE6
    , null as FIRST_ACK_DATE
    , null as RETURN_ATTRIBUTE5
    , null as SHIPPING_QUANTITY2
    , null as RETURN_ATTRIBUTE9
    , null as TAX_EXEMPT_NUMBER
    , null as RETURN_ATTRIBUTE4
    , null as LINE_CATEGORY_CODE
    , null as RETURN_ATTRIBUTE3
    , null as INDUSTRY_CONTEXT
    , null as RETURN_ATTRIBUTE2
    , null as SERVICE_PERIOD
    , null as REVENUE_AMOUNT
    , null as RETURN_ATTRIBUTE1
    , null as CREDIT_INVOICE_LINE_ID
    , null as MODEL_GROUP_NUMBER
    , null as INTMED_SHIP_TO_ORG_ID
    , null as TAX_EXEMPT_FLAG
    , null as SOLD_TO_ORG_ID
    , null as PRICE_REQUEST_CODE
    , null as RETURN_ATTRIBUTE14
    , null as SHIPPING_QUANTITY
    , null as RETURN_ATTRIBUTE15
    , null as CANCELLED_QUANTITY
    , null as PRICING_CONTEXT
    , null as DEMAND_BUCKET_TYPE_CODE
    , null as GLOBAL_ATTRIBUTE_CATEGORY
    , null as RETURN_ATTRIBUTE10
    , null as RETURN_ATTRIBUTE11
    , null as RETURN_ATTRIBUTE12
    , null as REQUEST_DATE
    , null as RETURN_ATTRIBUTE13
    , null as TAX_RATE
    , null as INDUSTRY_ATTRIBUTE26
    , null as INDUSTRY_ATTRIBUTE25
    , null as INDUSTRY_ATTRIBUTE24
    , null as ORG_ID
    , null as INDUSTRY_ATTRIBUTE23
    , null as INDUSTRY_ATTRIBUTE22
    , null as COMPONENT_NUMBER
    , null as INDUSTRY_ATTRIBUTE21
    , null as INDUSTRY_ATTRIBUTE20
    , null as SCHEDULE_STATUS_CODE
    , null as CANCELLED_FLAG
    , null as GLOBAL_ATTRIBUTE5
    , null as DELIVER_TO_CONTACT_ID
    , null as GLOBAL_ATTRIBUTE4
    , null as INVOICE_INTERFACE_STATUS_CODE
    , null as GLOBAL_ATTRIBUTE7
    , null as OVERRIDE_ATP_DATE_CODE
    , null as AUTO_SELECTED_QUANTITY
    , null as GLOBAL_ATTRIBUTE6
    , null as GLOBAL_ATTRIBUTE1
    , null as ORDER_FIRMED_DATE
    , null as GLOBAL_ATTRIBUTE3
    , null as GLOBAL_ATTRIBUTE2
    , null as UPGRADED_FLAG
    , null as TOP_MODEL_LINE_ID
    , null as GLOBAL_ATTRIBUTE9
    , null as INDUSTRY_ATTRIBUTE19
    , null as FOB_POINT_CODE
    , null as GLOBAL_ATTRIBUTE8
    , null as INDUSTRY_ATTRIBUTE18
    , null as BLANKET_LINE_NUMBER
    , null as MINISITE_ID
    , null as INDUSTRY_ATTRIBUTE17
    , null as TAX_EXEMPT_REASON_CODE
    , null as INDUSTRY_ATTRIBUTE16
    , null as ORDER_SOURCE_ID
    , null as ACTUAL_FULFILLMENT_DATE
    , null as TAX_VALUE
    , null as LAST_ACK_DATE
    , null as INDUSTRY_ATTRIBUTE30
    , null as BOOKED_FLAG
    , null as END_ITEM_UNIT_NUMBER
    , null as ACTUAL_ARRIVAL_DATE
    , null as AGREEMENT_ID
    , null as LATE_DEMAND_PENALTY_FACTOR
    , null as INVENTORY_ITEM_ID
    , null as BLANKET_NUMBER
    , null as CONFIG_DISPLAY_SEQUENCE
    , null as INDUSTRY_ATTRIBUTE29
    , null as INDUSTRY_ATTRIBUTE28
    , null as TASK_ID
    , null as INDUSTRY_ATTRIBUTE27
    , null as TP_CONTEXT
    , null as SHIP_TO_CONTACT_ID
    , null as REVREC_EXPIRATION_DAYS
    , null as CUSTOMER_PAYMENT_TERM_ID
    , null as REFERENCE_TYPE
    , null as IB_INSTALLED_AT_LOCATION
    , null as RE_SOURCE_FLAG
    , null as MODEL_REMNANT_FLAG
    , null as LINE_NUMBER
    , null as COMMITMENT_ID
    , null as CUSTOMER_PRODUCTION_LINE
    , null as OPTION_NUMBER
    , null as ITEM_TYPE_CODE
    , null as ORDERED_ITEM
    , null as PRICING_QUANTITY_UOM
    , null as SHIPPED_QUANTITY
    , null as BYPASS_SCH_FLAG
    , null as SALESREP_ID
    , null as PRICING_ATTRIBUTE10
    , null as CUSTOMER_ITEM_NET_PRICE
    , null as PROJECT_ID
    , null as ORDERED_QUANTITY2
    , null as INDUSTRY_ATTRIBUTE15
    , null as INDUSTRY_ATTRIBUTE14
    , null as INVOICE_TO_CONTACT_ID
    , null as INDUSTRY_ATTRIBUTE13
    , null as COMPONENT_CODE
    , null as INDUSTRY_ATTRIBUTE12
    , null as INDUSTRY_ATTRIBUTE11
    , null as UNIT_LIST_PRICE_PER_PQTY
    , null as INDUSTRY_ATTRIBUTE10
    , null as GLOBAL_ATTRIBUTE20
    , null as HEADER_ID
    , null as CUST_PRODUCTION_SEQ_NUM
    , null as GLOBAL_ATTRIBUTE17
    , null as GLOBAL_ATTRIBUTE18
    , null as GLOBAL_ATTRIBUTE15
    , null as GLOBAL_ATTRIBUTE16
    , null as GLOBAL_ATTRIBUTE13
    , null as GLOBAL_ATTRIBUTE14
    , null as GLOBAL_ATTRIBUTE11
    , null as SPLIT_FROM_LINE_ID
    , null as GLOBAL_ATTRIBUTE12
    , null as SOURCE_DOCUMENT_LINE_ID
    , null as ACCEPTED_QUANTITY
    , null as REVREC_EVENT_CODE
    , null as GLOBAL_ATTRIBUTE19
    , null as EQUIPMENT_ID
    , null as AUTHORIZED_TO_SHIP_FLAG
    , null as DELIVERY_LEAD_TIME
    , null as FULFILLED_QUANTITY2
    , null as VISIBLE_DEMAND_FLAG
    , null as LAST_UPDATE_DATE
    , null as SERVICE_REFERENCE_LINE_ID
    , null as INVOICED_QUANTITY
    , null as SHIP_TO_ORG_ID
    , null as INVOICE_TO_ORG_ID
    , null as SOURCE_DOCUMENT_TYPE_ID
    , null as ITEM_RELATIONSHIP_TYPE
    , null as SHIPMENT_NUMBER
    , null as SHIPPING_INSTRUCTIONS
    , null as CREATED_BY
    , null as SHIPPING_METHOD_CODE
    , null as SOURCE_DOCUMENT_ID
    , null as CUSTOMER_SHIPMENT_NUMBER
    , null as CREATION_DATE
    , null as PRICE_LIST_ID
    , null as INVOICING_RULE_ID
    , null as REFERENCE_LINE_ID
    , null as CHARGE_PERIODICITY_CODE
    , null as ATO_LINE_ID
    , null as PROGRAM_UPDATE_DATE
    , null as DEP_PLAN_REQUIRED_FLAG
    , null as SERVICE_TXN_COMMENTS
    , null as PROGRAM_APPLICATION_ID
    , null as PACKING_INSTRUCTIONS
    , null as END_CUSTOMER_ID
    , null as LINE_TYPE_ID
    , null as OPEN_FLAG
    , null as MFG_COMPONENT_SEQUENCE_ID
    , null as PREFERRED_GRADE
    , null as SHIP_FROM_ORG_ID
    , null as SALES_DOCUMENT_TYPE_CODE
    , null as SERVICE_TXN_REASON_CODE
    , null as FULFILLMENT_METHOD_CODE
    , null as REQUEST_ID
    , null as CONTINGENCY_ID
    , null as MARKETING_SOURCE_CODE_ID
    , null as SERVICE_REFERENCE_SYSTEM_ID
    , null as ORIGINAL_ORDERED_ITEM_ID
    , null as FULFILLED_QUANTITY
    , null as PRICING_DATE
    , null as SERVICE_START_DATE
    , null as OVER_SHIP_REASON_CODE
    , null as LAST_ACK_CODE
    , null as SERVICE_DURATION
    , null as SERVICE_NUMBER
    , null as LAST_UPDATE_LOGIN
    , null as ACCOUNTING_RULE_ID
    , null as END_CUSTOMER_SITE_USE_ID
    , null as FIRM_DEMAND_FLAG
    , null as ACCEPTED_BY
    , null as SERVICE_COTERMINATE_FLAG
    , null as DEMAND_CLASS_CODE
    , null as OVER_SHIP_RESOLVED_FLAG
    , null as ORIG_SYS_SHIPMENT_REF
    , null as ORDERED_ITEM_ID
    , null as TAX_CODE
    , null as FREIGHT_TERMS_CODE
    , null as PRICING_QUANTITY
    , null as _FIVETRAN_DELETED
    , null as _FIVETRAN_ID
    , null as _FIVETRAN_SYNCED
    , null as PSA_LOAD_DTS
    , null as PSA_RECORD_SOURCE
    , null as PSA_DELETE_IND
,  CONVERT_TIMEZONE('UTC','1900-01-01'::TIMESTAMP)  as  LOAD_DTS
, 'USAZET.SNOWFLAKE.FBIN.DERIVED' AS REC_SRC
, DECODE(GR.VALUE, 0, 'GHOST RECORD-SYSTEM', -1, 'GHOST RECORD-nullkey-required', -2, 'GHOST RECORD-nullkey-optional') AS BKCC
        , ''::BINARY as HASHDIFF FROM
        TABLE(strtok_split_to_table('0|-1|-2', '|')) AS GR
{% endif %}