---- SRC LAYER ----
WITH
SRC_bomst          as ( SELECT * FROM {{ ref('v_psa_stg_bom_structures__ml_ebs') }} as SRC 
                         {% if is_incremental() %}
                              where src.load_dts > (select dateadd('HOUR',-1,max(load_dts)) from {{ this }})
                            {% endif %}   )

/*
SRC_bomst          as ( SELECT * FROM staging.V_PSA_STG_BOM_STRUCTURES__ML_EBS )
*/
---- LOGIC LAYER ----

, LOGIC_bomst as (
    SELECT
        BOM_HK
      , BILL_SEQUENCE_ID
      , IS_PREFERRED
      , PK1_VALUE
      , LAST_UPDATE_DATE
      , PROGRAM_ID
      , STRUCTURE_TYPE_ID
      , OBJ_NAME
      , ASSEMBLY_ITEM_ID
      , ORGANIZATION_ID
      , ALTERNATE_BOM_DESIGNATOR
      , PK5_VALUE
      , IMPLEMENTATION_DATE
      , PENDING_FROM_ECN
      , CREATED_BY
      , ATTRIBUTE3
      , LAST_UPDATED_BY
      , ATTRIBUTE2
      , COMMON_ASSEMBLY_ITEM_ID
      , ATTRIBUTE1
      , CREATION_DATE
      , ATTRIBUTE9
      , ATTRIBUTE8
      , ATTRIBUTE7
      , ATTRIBUTE6
      , ATTRIBUTE5
      , PROGRAM_UPDATE_DATE
      , ATTRIBUTE4
      , EFFECTIVITY_CONTROL
      , ATTRIBUTE_CATEGORY
      , PROGRAM_APPLICATION_ID
      , TASK_ID
      , PK4_VALUE
      , SPECIFIC_ASSEMBLY_COMMENT
      , ATTRIBUTE10
      , ATTRIBUTE14
      , ATTRIBUTE13
      , PK3_VALUE
      , ATTRIBUTE12
      , ATTRIBUTE11
      , REQUEST_ID
      , ORIGINAL_SYSTEM_REFERENCE
      , SOURCE_BILL_SEQUENCE_ID
      , NEXT_EXPLODE_DATE
      , COMMON_BILL_SEQUENCE_ID
      , PROJECT_ID
      , PK2_VALUE
      , COMMON_ORGANIZATION_ID
      , LAST_UPDATE_LOGIN
      , ATTRIBUTE15
      , ASSEMBLY_TYPE
      , _FIVETRAN_DELETED
      , _FIVETRAN_ID
      , _FIVETRAN_SYNCED
      , PSA_DELETE_IND
      , PSA_LOAD_DTS
      , PSA_RECORD_SOURCE
      , LOAD_DTS
      , REC_SRC
      , HASHDIFF
    FROM SRC_bomst
)
---- RENAME LAYER ----

, RENAME_bomst as (
    SELECT
        BOM_HK
      , BILL_SEQUENCE_ID
      , IS_PREFERRED
      , PK1_VALUE
      , LAST_UPDATE_DATE
      , PROGRAM_ID
      , STRUCTURE_TYPE_ID
      , OBJ_NAME
      , ASSEMBLY_ITEM_ID
      , ORGANIZATION_ID
      , ALTERNATE_BOM_DESIGNATOR
      , PK5_VALUE
      , IMPLEMENTATION_DATE
      , PENDING_FROM_ECN
      , CREATED_BY
      , ATTRIBUTE3
      , LAST_UPDATED_BY
      , ATTRIBUTE2
      , COMMON_ASSEMBLY_ITEM_ID
      , ATTRIBUTE1
      , CREATION_DATE
      , ATTRIBUTE9
      , ATTRIBUTE8
      , ATTRIBUTE7
      , ATTRIBUTE6
      , ATTRIBUTE5
      , PROGRAM_UPDATE_DATE
      , ATTRIBUTE4
      , EFFECTIVITY_CONTROL
      , ATTRIBUTE_CATEGORY
      , PROGRAM_APPLICATION_ID
      , TASK_ID
      , PK4_VALUE
      , SPECIFIC_ASSEMBLY_COMMENT
      , ATTRIBUTE10
      , ATTRIBUTE14
      , ATTRIBUTE13
      , PK3_VALUE
      , ATTRIBUTE12
      , ATTRIBUTE11
      , REQUEST_ID
      , ORIGINAL_SYSTEM_REFERENCE
      , SOURCE_BILL_SEQUENCE_ID
      , NEXT_EXPLODE_DATE
      , COMMON_BILL_SEQUENCE_ID
      , PROJECT_ID
      , PK2_VALUE
      , COMMON_ORGANIZATION_ID
      , LAST_UPDATE_LOGIN
      , ATTRIBUTE15
      , ASSEMBLY_TYPE
      , _FIVETRAN_DELETED
      , _FIVETRAN_ID
      , _FIVETRAN_SYNCED
      , PSA_DELETE_IND
      , PSA_LOAD_DTS
      , PSA_RECORD_SOURCE
      , LOAD_DTS
      , REC_SRC
      , HASHDIFF
    FROM LOGIC_bomst
)
---- FILTER LAYER ----

, FILTER_bomst as (
    SELECT *
    FROM RENAME_bomst
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM FILTER_bomst
)

---- FINAL LAYER ----
SELECT
          BOM_HK
        , BILL_SEQUENCE_ID
        , IS_PREFERRED
        , PK1_VALUE
        , LAST_UPDATE_DATE
        , PROGRAM_ID
        , STRUCTURE_TYPE_ID
        , OBJ_NAME
        , ASSEMBLY_ITEM_ID
        , ORGANIZATION_ID
        , ALTERNATE_BOM_DESIGNATOR
        , PK5_VALUE
        , IMPLEMENTATION_DATE
        , PENDING_FROM_ECN
        , CREATED_BY
        , ATTRIBUTE3
        , LAST_UPDATED_BY
        , ATTRIBUTE2
        , COMMON_ASSEMBLY_ITEM_ID
        , ATTRIBUTE1
        , CREATION_DATE
        , ATTRIBUTE9
        , ATTRIBUTE8
        , ATTRIBUTE7
        , ATTRIBUTE6
        , ATTRIBUTE5
        , PROGRAM_UPDATE_DATE
        , ATTRIBUTE4
        , EFFECTIVITY_CONTROL
        , ATTRIBUTE_CATEGORY
        , PROGRAM_APPLICATION_ID
        , TASK_ID
        , PK4_VALUE
        , SPECIFIC_ASSEMBLY_COMMENT
        , ATTRIBUTE10
        , ATTRIBUTE14
        , ATTRIBUTE13
        , PK3_VALUE
        , ATTRIBUTE12
        , ATTRIBUTE11
        , REQUEST_ID
        , ORIGINAL_SYSTEM_REFERENCE
        , SOURCE_BILL_SEQUENCE_ID
        , NEXT_EXPLODE_DATE
        , COMMON_BILL_SEQUENCE_ID
        , PROJECT_ID
        , PK2_VALUE
        , COMMON_ORGANIZATION_ID
        , LAST_UPDATE_LOGIN
        , ATTRIBUTE15
        , ASSEMBLY_TYPE
        , _FIVETRAN_DELETED
        , _FIVETRAN_ID
        , _FIVETRAN_SYNCED
        , PSA_DELETE_IND
        , PSA_LOAD_DTS
        , PSA_RECORD_SOURCE
        , LOAD_DTS
        , REC_SRC
        , HASHDIFF
FROM JOIN_RESULT
{% if is_incremental() %}
WHERE NOT EXISTS (
    SELECT 1 
    FROM {{ this }} existing
    WHERE existing.BOM_HK = JOIN_RESULT.BOM_HK 
    AND existing.HASHDIFF = JOIN_RESULT.HASHDIFF
)
{% endif %}
{% if not is_incremental() %}

/* The following qualifier is implemented to prevent multiple loads of touched records during the initial build, such as multiple rows per HK and hashdiff. */
qualify 1 = row_number() over (partition by BOM_HK, BILL_SEQUENCE_ID, PROGRAM_ID, STRUCTURE_TYPE_ID, ASSEMBLY_ITEM_ID, ORGANIZATION_ID, COMMON_ASSEMBLY_ITEM_ID, PROGRAM_APPLICATION_ID, TASK_ID, REQUEST_ID, SOURCE_BILL_SEQUENCE_ID, COMMON_BILL_SEQUENCE_ID, PROJECT_ID, COMMON_ORGANIZATION_ID, _FIVETRAN_ID, HASHDIFF order by PSA_LOAD_DTS)

union all
SELECT 
MD5_BINARY(GR.VALUE) AS BOM_HK,
GR.VALUE::number AS BILL_SEQUENCE_ID,
NULL AS IS_PREFERRED,
NULL AS PK1_VALUE,
NULL AS LAST_UPDATE_DATE,
NULL AS PROGRAM_ID,
NULL AS STRUCTURE_TYPE_ID,
NULL AS OBJ_NAME,
NULL AS ASSEMBLY_ITEM_ID,
NULL AS ORGANIZATION_ID,
NULL AS ALTERNATE_BOM_DESIGNATOR,
NULL AS PK5_VALUE,
NULL AS IMPLEMENTATION_DATE,
NULL AS PENDING_FROM_ECN,
NULL AS CREATED_BY,
NULL AS ATTRIBUTE3,
NULL AS LAST_UPDATED_BY,
NULL AS ATTRIBUTE2,
NULL AS COMMON_ASSEMBLY_ITEM_ID,
NULL AS ATTRIBUTE1,
NULL AS CREATION_DATE,
NULL AS ATTRIBUTE9,
NULL AS ATTRIBUTE8,
NULL AS ATTRIBUTE7,
NULL AS ATTRIBUTE6,
NULL AS ATTRIBUTE5,
NULL AS PROGRAM_UPDATE_DATE,
NULL AS ATTRIBUTE4,
NULL AS EFFECTIVITY_CONTROL,
NULL AS ATTRIBUTE_CATEGORY,
NULL AS PROGRAM_APPLICATION_ID,
NULL AS TASK_ID,
NULL AS PK4_VALUE,
NULL AS SPECIFIC_ASSEMBLY_COMMENT,
NULL AS ATTRIBUTE10,
NULL AS ATTRIBUTE14,
NULL AS ATTRIBUTE13,
NULL AS PK3_VALUE,
NULL AS ATTRIBUTE12,
NULL AS ATTRIBUTE11,
NULL AS REQUEST_ID,
NULL AS ORIGINAL_SYSTEM_REFERENCE,
NULL AS SOURCE_BILL_SEQUENCE_ID,
NULL AS NEXT_EXPLODE_DATE,
NULL AS COMMON_BILL_SEQUENCE_ID,
NULL AS PROJECT_ID,
NULL AS PK2_VALUE,
NULL AS COMMON_ORGANIZATION_ID,
NULL AS LAST_UPDATE_LOGIN,
NULL AS ATTRIBUTE15,
NULL AS ASSEMBLY_TYPE,
NULL AS _FIVETRAN_DELETED,
NULL AS _FIVETRAN_ID,
NULL AS _FIVETRAN_SYNCED,
'N' AS PSA_DELETE_IND,
'1900-01-01'::TIMESTAMP AS PSA_LOAD_DTS,
NULL AS PSA_RECORD_SOURCE,
CONVERT_TIMEZONE('UTC','1900-01-01'::TIMESTAMP) AS LOAD_DTS,
'USAZET.SNOWFLAKE.FBIN.DERIVED' AS REC_SRC,
''::BINARY AS HASHDIFF
FROM
TABLE(strtok_split_to_table('0|-1|-2', '|')) AS GR
{% endif %}
