---- SRC LAYER ----
WITH
SRC_psa_casa       as ( SELECT * FROM {{ ref('v_psa_stg_customer_site__ml_ebs') }} as SRC 
                        {% if is_incremental() %}
                        WHERE SRC.LOAD_DTS > (SELECT DATEADD('HOUR', '-1', MAX(LOAD_DTS)) FROM {{this}}){% endif %} )

/*
SRC_psa_casa       as ( SELECT * FROM STAGING.V_PSA_STG_CUSTOMER_SITE__ML_EBS )
*/
---- LOGIC LAYER ----

, LOGIC_psa_casa as (
    SELECT
        CUSTOMER_SITE_HK
      , ACCOUNT_NUMBER
      , CUST_ACCT_SITE_ID
      , ORG_ID
      , TERRITORY
      , GLOBAL_ATTRIBUTE10
      , LAST_UPDATE_DATE
      , PROGRAM_ID
      , GLOBAL_ATTRIBUTE5
      , GLOBAL_ATTRIBUTE4
      , GLOBAL_ATTRIBUTE7
      , STATUS
      , GLOBAL_ATTRIBUTE6
      , OBJECT_VERSION_NUMBER
      , GLOBAL_ATTRIBUTE1
      , GLOBAL_ATTRIBUTE3
      , GLOBAL_ATTRIBUTE2
      , GLOBAL_ATTRIBUTE9
      , MARKET_FLAG
      , GLOBAL_ATTRIBUTE8
      , TERRITORY_ID
      , BILL_TO_FLAG
      , ATTRIBUTE3
      , LANGUAGE
      , CREATED_BY_MODULE
      , CREATED_BY
      , ATTRIBUTE2
      , ORIG_SYSTEM_REFERENCE
      , LAST_UPDATED_BY
      , ATTRIBUTE1
      , PARTY_SITE_ID
      , CREATION_DATE
      , SHIP_TO_FLAG
      , ATTRIBUTE9
      , ATTRIBUTE8
      , ATTRIBUTE7
      , ATTRIBUTE6
      , ATTRIBUTE5
      , PROGRAM_UPDATE_DATE
      , ATTRIBUTE4
      , ATTRIBUTE_CATEGORY
      , CUSTOMER_CATEGORY_CODE
      , PROGRAM_APPLICATION_ID
      , ECE_TP_LOCATION_CODE
      , ATTRIBUTE10
      , ATTRIBUTE14
      , ATTRIBUTE13
      , CUST_ACCOUNT_ID
      , ATTRIBUTE12
      , ATTRIBUTE11
      , APPLICATION_ID
      , TRANSLATED_CUSTOMER_NAME
      , REQUEST_ID
      , SERVICE_TERRITORY_ID
      , KEY_ACCOUNT_FLAG
      , SECONDARY_SPECIALIST_ID
      , ATTRIBUTE20
      , GLOBAL_ATTRIBUTE20
      , LAST_UPDATE_LOGIN
      , GLOBAL_ATTRIBUTE_CATEGORY
      , TP_HEADER_ID
      , GLOBAL_ATTRIBUTE17
      , WH_UPDATE_DATE
      , GLOBAL_ATTRIBUTE18
      , GLOBAL_ATTRIBUTE15
      , GLOBAL_ATTRIBUTE16
      , GLOBAL_ATTRIBUTE13
      , GLOBAL_ATTRIBUTE14
      , GLOBAL_ATTRIBUTE11
      , PRIMARY_SPECIALIST_ID
      , GLOBAL_ATTRIBUTE12
      , ATTRIBUTE18
      , ATTRIBUTE17
      , ATTRIBUTE16
      , ATTRIBUTE15
      , GLOBAL_ATTRIBUTE19
      , ATTRIBUTE19
      , _FIVETRAN_DELETED
      , _FIVETRAN_SYNCED
      , PSA_LOAD_DTS
      , PSA_RECORD_SOURCE
      , PSA_DELETE_IND
      , LOAD_DTS
      , REC_SRC
      , HASHDIFF
      , BKCC
    FROM SRC_psa_casa
)
---- RENAME LAYER ----

, RENAME_psa_casa as (
    SELECT
        CUSTOMER_SITE_HK
      , ACCOUNT_NUMBER
      , CUST_ACCT_SITE_ID
      , ORG_ID
      , TERRITORY
      , GLOBAL_ATTRIBUTE10
      , LAST_UPDATE_DATE
      , PROGRAM_ID
      , GLOBAL_ATTRIBUTE5
      , GLOBAL_ATTRIBUTE4
      , GLOBAL_ATTRIBUTE7
      , STATUS
      , GLOBAL_ATTRIBUTE6
      , OBJECT_VERSION_NUMBER
      , GLOBAL_ATTRIBUTE1
      , GLOBAL_ATTRIBUTE3
      , GLOBAL_ATTRIBUTE2
      , GLOBAL_ATTRIBUTE9
      , MARKET_FLAG
      , GLOBAL_ATTRIBUTE8
      , TERRITORY_ID
      , BILL_TO_FLAG
      , ATTRIBUTE3
      , LANGUAGE
      , CREATED_BY_MODULE
      , CREATED_BY
      , ATTRIBUTE2
      , ORIG_SYSTEM_REFERENCE
      , LAST_UPDATED_BY
      , ATTRIBUTE1
      , PARTY_SITE_ID
      , CREATION_DATE
      , SHIP_TO_FLAG
      , ATTRIBUTE9
      , ATTRIBUTE8
      , ATTRIBUTE7
      , ATTRIBUTE6
      , ATTRIBUTE5
      , PROGRAM_UPDATE_DATE
      , ATTRIBUTE4
      , ATTRIBUTE_CATEGORY
      , CUSTOMER_CATEGORY_CODE
      , PROGRAM_APPLICATION_ID
      , ECE_TP_LOCATION_CODE
      , ATTRIBUTE10
      , ATTRIBUTE14
      , ATTRIBUTE13
      , CUST_ACCOUNT_ID
      , ATTRIBUTE12
      , ATTRIBUTE11
      , APPLICATION_ID
      , TRANSLATED_CUSTOMER_NAME
      , REQUEST_ID
      , SERVICE_TERRITORY_ID
      , KEY_ACCOUNT_FLAG
      , SECONDARY_SPECIALIST_ID
      , ATTRIBUTE20
      , GLOBAL_ATTRIBUTE20
      , LAST_UPDATE_LOGIN
      , GLOBAL_ATTRIBUTE_CATEGORY
      , TP_HEADER_ID
      , GLOBAL_ATTRIBUTE17
      , WH_UPDATE_DATE
      , GLOBAL_ATTRIBUTE18
      , GLOBAL_ATTRIBUTE15
      , GLOBAL_ATTRIBUTE16
      , GLOBAL_ATTRIBUTE13
      , GLOBAL_ATTRIBUTE14
      , GLOBAL_ATTRIBUTE11
      , PRIMARY_SPECIALIST_ID
      , GLOBAL_ATTRIBUTE12
      , ATTRIBUTE18
      , ATTRIBUTE17
      , ATTRIBUTE16
      , ATTRIBUTE15
      , GLOBAL_ATTRIBUTE19
      , ATTRIBUTE19
      , _FIVETRAN_DELETED
      , _FIVETRAN_SYNCED
      , PSA_LOAD_DTS
      , PSA_RECORD_SOURCE
      , PSA_DELETE_IND
      , LOAD_DTS
      , REC_SRC
      , HASHDIFF
      , BKCC
    FROM LOGIC_psa_casa
)
---- FILTER LAYER ----

, FILTER_psa_casa as (
    SELECT *
    FROM RENAME_psa_casa
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM FILTER_psa_casa
)

---- FINAL LAYER ----
SELECT
          CUSTOMER_SITE_HK
        , ACCOUNT_NUMBER
        , CUST_ACCT_SITE_ID
        , ORG_ID
        , TERRITORY
        , GLOBAL_ATTRIBUTE10
        , LAST_UPDATE_DATE
        , PROGRAM_ID
        , GLOBAL_ATTRIBUTE5
        , GLOBAL_ATTRIBUTE4
        , GLOBAL_ATTRIBUTE7
        , STATUS
        , GLOBAL_ATTRIBUTE6
        , OBJECT_VERSION_NUMBER
        , GLOBAL_ATTRIBUTE1
        , GLOBAL_ATTRIBUTE3
        , GLOBAL_ATTRIBUTE2
        , GLOBAL_ATTRIBUTE9
        , MARKET_FLAG
        , GLOBAL_ATTRIBUTE8
        , TERRITORY_ID
        , BILL_TO_FLAG
        , ATTRIBUTE3
        , LANGUAGE
        , CREATED_BY_MODULE
        , CREATED_BY
        , ATTRIBUTE2
        , ORIG_SYSTEM_REFERENCE
        , LAST_UPDATED_BY
        , ATTRIBUTE1
        , PARTY_SITE_ID
        , CREATION_DATE
        , SHIP_TO_FLAG
        , ATTRIBUTE9
        , ATTRIBUTE8
        , ATTRIBUTE7
        , ATTRIBUTE6
        , ATTRIBUTE5
        , PROGRAM_UPDATE_DATE
        , ATTRIBUTE4
        , ATTRIBUTE_CATEGORY
        , CUSTOMER_CATEGORY_CODE
        , PROGRAM_APPLICATION_ID
        , ECE_TP_LOCATION_CODE
        , ATTRIBUTE10
        , ATTRIBUTE14
        , ATTRIBUTE13
        , CUST_ACCOUNT_ID
        , ATTRIBUTE12
        , ATTRIBUTE11
        , APPLICATION_ID
        , TRANSLATED_CUSTOMER_NAME
        , REQUEST_ID
        , SERVICE_TERRITORY_ID
        , KEY_ACCOUNT_FLAG
        , SECONDARY_SPECIALIST_ID
        , ATTRIBUTE20
        , GLOBAL_ATTRIBUTE20
        , LAST_UPDATE_LOGIN
        , GLOBAL_ATTRIBUTE_CATEGORY
        , TP_HEADER_ID
        , GLOBAL_ATTRIBUTE17
        , WH_UPDATE_DATE
        , GLOBAL_ATTRIBUTE18
        , GLOBAL_ATTRIBUTE15
        , GLOBAL_ATTRIBUTE16
        , GLOBAL_ATTRIBUTE13
        , GLOBAL_ATTRIBUTE14
        , GLOBAL_ATTRIBUTE11
        , PRIMARY_SPECIALIST_ID
        , GLOBAL_ATTRIBUTE12
        , ATTRIBUTE18
        , ATTRIBUTE17
        , ATTRIBUTE16
        , ATTRIBUTE15
        , GLOBAL_ATTRIBUTE19
        , ATTRIBUTE19
        , _FIVETRAN_DELETED
        , _FIVETRAN_SYNCED
        , PSA_LOAD_DTS
        , PSA_RECORD_SOURCE
        , PSA_DELETE_IND
        , LOAD_DTS
        , REC_SRC
        , HASHDIFF
        , BKCC
FROM JOIN_RESULT
{% if is_incremental() %}
WHERE NOT EXISTS (
    SELECT 1 
    FROM {{ this }} existing
    WHERE existing.CUSTOMER_SITE_HK = JOIN_RESULT.CUSTOMER_SITE_HK 
    AND existing.HASHDIFF = JOIN_RESULT.HASHDIFF
)
{% endif %}
{% if not is_incremental() %}

/* The following qualifier is implemented to prevent multiple loads of touched records during the initial build, such as multiple rows per HK and hashdiff. */
qualify 1 = row_number() over (partition by CUSTOMER_SITE_HK, HASHDIFF order by PSA_LOAD_DTS)

union all
SELECT 
MD5_BINARY(GR.VALUE) AS CUSTOMER_SITE_HK,
GR.VALUE::text AS ACCOUNT_NUMBER,
GR.VALUE::number AS CUST_ACCT_SITE_ID,
NULL AS ORG_ID,
NULL AS TERRITORY,
NULL AS GLOBAL_ATTRIBUTE10,
NULL AS LAST_UPDATE_DATE,
NULL AS PROGRAM_ID,
NULL AS GLOBAL_ATTRIBUTE5,
NULL AS GLOBAL_ATTRIBUTE4,
NULL AS GLOBAL_ATTRIBUTE7,
NULL AS STATUS,
NULL AS GLOBAL_ATTRIBUTE6,
NULL AS OBJECT_VERSION_NUMBER,
NULL AS GLOBAL_ATTRIBUTE1,
NULL AS GLOBAL_ATTRIBUTE3,
NULL AS GLOBAL_ATTRIBUTE2,
NULL AS GLOBAL_ATTRIBUTE9,
NULL AS MARKET_FLAG,
NULL AS GLOBAL_ATTRIBUTE8,
NULL AS TERRITORY_ID,
NULL AS BILL_TO_FLAG,
NULL AS ATTRIBUTE3,
NULL AS LANGUAGE,
NULL AS CREATED_BY_MODULE,
NULL AS CREATED_BY,
NULL AS ATTRIBUTE2,
NULL AS ORIG_SYSTEM_REFERENCE,
NULL AS LAST_UPDATED_BY,
NULL AS ATTRIBUTE1,
NULL AS PARTY_SITE_ID,
NULL AS CREATION_DATE,
NULL AS SHIP_TO_FLAG,
NULL AS ATTRIBUTE9,
NULL AS ATTRIBUTE8,
NULL AS ATTRIBUTE7,
NULL AS ATTRIBUTE6,
NULL AS ATTRIBUTE5,
NULL AS PROGRAM_UPDATE_DATE,
NULL AS ATTRIBUTE4,
NULL AS ATTRIBUTE_CATEGORY,
NULL AS CUSTOMER_CATEGORY_CODE,
NULL AS PROGRAM_APPLICATION_ID,
NULL AS ECE_TP_LOCATION_CODE,
NULL AS ATTRIBUTE10,
NULL AS ATTRIBUTE14,
NULL AS ATTRIBUTE13,
NULL AS CUST_ACCOUNT_ID,
NULL AS ATTRIBUTE12,
NULL AS ATTRIBUTE11,
NULL AS APPLICATION_ID,
NULL AS TRANSLATED_CUSTOMER_NAME,
NULL AS REQUEST_ID,
NULL AS SERVICE_TERRITORY_ID,
NULL AS KEY_ACCOUNT_FLAG,
NULL AS SECONDARY_SPECIALIST_ID,
NULL AS ATTRIBUTE20,
NULL AS GLOBAL_ATTRIBUTE20,
NULL AS LAST_UPDATE_LOGIN,
NULL AS GLOBAL_ATTRIBUTE_CATEGORY,
NULL AS TP_HEADER_ID,
NULL AS GLOBAL_ATTRIBUTE17,
NULL AS WH_UPDATE_DATE,
NULL AS GLOBAL_ATTRIBUTE18,
NULL AS GLOBAL_ATTRIBUTE15,
NULL AS GLOBAL_ATTRIBUTE16,
NULL AS GLOBAL_ATTRIBUTE13,
NULL AS GLOBAL_ATTRIBUTE14,
NULL AS GLOBAL_ATTRIBUTE11,
NULL AS PRIMARY_SPECIALIST_ID,
NULL AS GLOBAL_ATTRIBUTE12,
NULL AS ATTRIBUTE18,
NULL AS ATTRIBUTE17,
NULL AS ATTRIBUTE16,
NULL AS ATTRIBUTE15,
NULL AS GLOBAL_ATTRIBUTE19,
NULL AS ATTRIBUTE19,
NULL AS _FIVETRAN_DELETED,
NULL AS _FIVETRAN_SYNCED,
'1900-01-01'::TIMESTAMP AS PSA_LOAD_DTS,
NULL AS PSA_RECORD_SOURCE,
'N' AS PSA_DELETE_IND,
CONVERT_TIMEZONE('UTC','1900-01-01'::TIMESTAMP) AS LOAD_DTS,
'USAZET.SNOWFLAKE.FBIN.DERIVED' AS REC_SRC,
''::BINARY AS HASHDIFF,
DECODE(GR.VALUE, 0, 'GHOST RECORD-SYSTEM', -1, 'GHOST RECORD-nullkey-required', -2, 'GHOST RECORD-nullkey-optional') AS BKCC
FROM
TABLE(strtok_split_to_table('0|-1|-2', '|')) AS GR
{% endif %}
