SELECT * FROM (
    {{ check_column_data_type(
        'fact_installer_order',
        [
            ('ORDER_ID', 'TEXT'),
            ('SHOPIFY_NUMERIC_ID', 'NUMBER'),
            ('ORDER_DATE', 'TIMESTAMP_TZ'),
            ('ORDER_FIRST_NAME', 'TEXT'),
            ('ORDER_LAST_NAME', 'TEXT'),
            ('ORDER_EMAIL', 'TEXT'),
            ('ORDER_PHONE', 'TEXT'),
            ('ORDER_ADDRESS_1', 'TEXT'),
            ('ORDER_ADDRESS_2', 'TEXT'),
            ('ORDER_CITY', 'TEXT'),
            ('ORDER_STATE', 'TEXT'),
            ('ORDER_POSTCODE', 'TEXT'),
            ('ORDER_POSTCODE_ADD_ON', 'TEXT'),
            ('ORDER_STATUS', 'TEXT'),
            ('ORDER_TAG', 'TEXT'),
            ('ORDER_QUANTITY', 'NUMBER'),
            ('RETURN_QUANTITY', 'NUMBER'),
            ('ACTUAL_DELIVERY_DATE', 'TIMESTAMP_TZ'),
            ('SKU', 'TEXT'),
            ('VALVE_SIZE', 'TEXT'),
            ('ORDER_STATUS_MODIFIED', 'TIMESTAMP_TZ'),
            ('LASTMODIFIED', 'TIMESTAMP_TZ'),
            ('IS_PAIRED', 'BOOLEAN'),
            ('PAIRED_DATE', 'DATE'),
            ('MOEN_INSTALL_ACTIVE_DATE', 'DATE'),
            ('SERIAL_ID', 'TEXT'),
            ('DEVICE_ID', 'TEXT'),
            ('INSTALLATION_ADDRESS_LINE1', 'TEXT'),
            ('INSTALLATION_ADDRESS_LINE2', 'TEXT'),
            ('INSTALLATION_CITY', 'TEXT'),
            ('INSTALLATION_STATE', 'TEXT'),
            ('INSTALLATION_ZIP', 'TEXT'),
            ('INSTALLER_NAME', 'TEXT'),
            ('INSTALLER_YA_TAG', 'TEXT'),
            ('INSTALL_PREFERRED_DATE_TIME1', 'TEXT'),
            ('INSTALL_PREFERRED_DATE_TIME2', 'TEXT'),
            ('INSTALL_PREFERRED_DATE_TIME3', 'TEXT'),
            ('INSTALL_CAN_BE_CONTACTED_FLAG', 'TEXT'),
            ('ORDER_LINE_ID', 'NUMBER'),
            ('INSTALLATION_FLAG', 'BOOLEAN'),
            ('HAS_HIGH_RISK_TAG', 'BOOLEAN'),
            ('GRAIN_KEY', 'TEXT'),
            ('BKCC', 'TEXT'),
            ('REC_SRC', 'TEXT'),
            ('PB_LOAD_DTS', 'TIMESTAMP_TZ')
        ]
    ) }}
)