select
	DATEKEY,
	DATE,
	FBIN_CAL_DAY,
	FBIN_CAL_WEEK,
	FBIN_CAL_MONTH,
	FBIN_CAL_QUARTER,
	FBIN_CAL_YEAR,
	FBIN_CAL_QUARTER_YYYYQQ,
	FBIN_CAL_MONTH_YYYYMM,
	FBIN_CAL_WEEK_YYYYWW,
	FBIN_WORKING_DAY_FLAG,
	LOAD_DTS,
	REC_SRC,
	PSA_LOAD_DTS,
	PSA_RECORD_SOURCE
from {{ source('reference__rr', 'ref_date_fbin') }}