select
	DATEKEY,
	DATE,
	FISCAL_455_CAL_DAY as FISCAL_445_CAL_DAY,
	FISCAL_455_CAL_WEEK as FISCAL_445_CAL_WEEK,
	FISCAL_455_CAL_MONTH as FISCAL_445_CAL_MONTH,
	FISCAL_455_CAL_QUARTER as FISCAL_445_CAL_QUARTER,
	FISCAL_455_CAL_YEAR as FISCAL_445_CAL_YEAR,
	FISCAL_445_CAL_QUARTER_YYYYQQ,
	FISCAL_445_CAL_MONTH_YYYYMM,
	FISCAL_445_CAL_WEEK_YYYYWW,
	FISCAL_455_WORKING_DAY_FLAG as FISCAL_445_WORKING_DAY_FLAG,
	LOAD_DTS,
	REC_SRC,
	PSA_LOAD_DTS,
	PSA_RECORD_SOURCE
from {{ source('reference__rr', 'ref_date_fiscal_445') }}