---- SRC LAYER ----
WITH
SRC_L              as ( SELECT CUSTOMER_BILLTO_HK, CUSTOMER_INSURANCEPARTNER_HK, CUSTOMER_PAYER_HK, CUSTOMER_SHIPTO_HK, CUSTOMER_SOLDTO_HK, DISTRIBUTION_CHANNEL_HK,
                        DIVISION_HK, ITEM_HK, LOAD_DTS, ORDER_HEADER_HK, ORDER_LINE_HK, PLANT_HK, REC_SRC, SALES_ORGANIZATION_HK, SO_ITEM_LHK FROM {{ ref('lnk_sales_order_line') }} as SRC  ),
SRC_H_CUSTOMER           as ( SELECT BKCC, REC_SRC, CUSTOMER_HK, CUSTOMER_BK FROM {{ ref('hub_customer_v1') }} as SRC  ),
SRC_H_DISTRIBUTION           as ( SELECT DISTRIBUTION_CHANNEL_HK, DISTRIBUTION_CHANNEL_BK FROM {{ ref('hub_distribution_channel') }} as SRC  ),
SRC_H_DIVISION          as ( SELECT DIVISION_HK, DIVISION_BK FROM {{ ref('hub_division') }} as SRC  ),
SRC_H_ITEM           as ( SELECT ITEM_HK, ITEM_BK FROM {{ ref('hub_item_v1') }} as SRC  ),
SRC_H_ORDER_HEADER           as ( SELECT ORDER_HEADER_HK, ORDER_HEADER_BK FROM {{ ref('hub_order_header') }} as SRC  ),
SRC_H_ORDER_LINE           as ( SELECT ORDER_LINE_HK, ORDER_LINE_BK FROM {{ ref('hub_order_line') }} as SRC  ),
SRC_H_PLANT           as ( SELECT PLANT_HK, PLANT_BK FROM {{ ref('hub_plant_v1') }} as SRC  ),
SRC_H_SALES_ORGANIZATION           as ( SELECT SALES_ORGANIZATION_HK, SALES_ORGANIZATION_BK FROM {{ ref('hub_sales_organization') }} as SRC  ),
SRC_LS             as ( SELECT PSA_DELETE_IND, ORDER_LINE_HK, VRKME, NETWR, KWMENG, MWSBP, ABGRU, ERDAT, MATKL
                        FROM {{ ref('sat_order_line__winn_sap') }} as SRC 
                        QUALIFY 1= ROW_NUMBER() OVER(PARTITION BY ORDER_LINE_HK ORDER BY LOAD_DTS DESC) ),
SRC_LS_HEADER      as ( SELECT ORDER_HEADER_HK, AUART, AUDAT, ZZRSD
                        FROM {{ ref('sat_order_header__winn_sap') }} as SRC 
                        QUALIFY 1= ROW_NUMBER() OVER(PARTITION BY ORDER_HEADER_HK ORDER BY LOAD_DTS DESC) )


/*
SRC_L              as ( SELECT * FROM RAW_VAULT.LNK_SALES_ORDER_LINE ),
SRC_H_CUSTOMER     as ( SELECT * FROM RAW_VAULT.HUB_CUSTOMER ),
SRC_H_DISTRIBUTION as ( SELECT * FROM RAW_VAULT.hub_distribution_channel ),
SRC_H_DIVISION     as ( SELECT * FROM RAW_VAULT.HUB_DIVISION ),
SRC_H_ITEM         as ( SELECT * FROM RAW_VAULT.HUB_ITEM ),
SRC_H_ORDER_HEADER as ( SELECT * FROM RAW_VAULT.HUB_ORDER_HEADER ),
SRC_H_ORDER_LINE   as ( SELECT * FROM RAW_VAULT.HUB_ORDER_LINE ),
SRC_H_PLANT        as ( SELECT * FROM RAW_VAULT.HUB_PLANT ),
SRC_H_SALES_ORG    as ( SELECT * FROM RAW_VAULT.HUB_SALES_ORGANIZATION ),
SRC_LS             as ( SELECT * FROM RAW_VAULT.SAT_ORDER_LINE__WINN_SAP ),
SRC_LS_HEADER      as ( SELECT * FROM RAW_VAULT.SAT_ORDER_HEADER__WINN_SAP )
*/

---- LOGIC LAYER ----

, LOGIC_L as (
    SELECT
        'PB_SALES_ORDER_ITEM'                                                     as PB_REC_SRC
      , CUSTOMER_BILLTO_HK                                                        as L_CUSTOMER_BILLTO_HK
      , CUSTOMER_INSURANCEPARTNER_HK                                              as L_CUSTOMER_INSURANCEPARTNER_HK
      , CUSTOMER_PAYER_HK                                                         as L_CUSTOMER_PAYER_HK
      , CUSTOMER_SHIPTO_HK                                                        as L_CUSTOMER_SHIPTO_HK
      , CUSTOMER_SOLDTO_HK                                                        as L_CUSTOMER_SOLDTO_HK
      , DISTRIBUTION_CHANNEL_HK                                                   as L_DISTRIBUTION_CHANNEL_HK
      , DIVISION_HK                                                               as L_DIVISION_HK
      , ITEM_HK                                                                   as L_ITEM_HK
      , LOAD_DTS
      , ORDER_HEADER_HK                                                           as L_ORDER_HEADER_HK
      , ORDER_LINE_HK                                                             as L_ORDER_LINE_HK
      , PLANT_HK                                                                  as L_PLANT_HK
      , REC_SRC
      , SALES_ORGANIZATION_HK                                                     as L_SALES_ORGANIZATION_HK
      , SO_ITEM_LHK
    FROM SRC_L
)

, LOGIC_H_CUSTOMER as (
    SELECT
        CUSTOMER_BK
      , CUSTOMER_HK
      , BKCC
      , REC_SRC
    FROM SRC_H_CUSTOMER
)

, LOGIC_H_DISTRIBUTION as (
    SELECT
        DISTRIBUTION_CHANNEL_BK
      , DISTRIBUTION_CHANNEL_HK
    FROM SRC_H_DISTRIBUTION
) 

, LOGIC_H_DIVISION as (
    SELECT
        DIVISION_BK
      , DIVISION_HK
    FROM SRC_H_DIVISION
) 

, LOGIC_H_ITEM as (
    SELECT
        ITEM_BK
      , ITEM_HK
    FROM SRC_H_ITEM
) 

, LOGIC_H_ORDER_HEADER as (
    SELECT
        ORDER_HEADER_BK
      , ORDER_HEADER_HK
    FROM SRC_H_ORDER_HEADER
) 


, LOGIC_H_ORDER_LINE as (
    SELECT
        ORDER_LINE_BK
      , ORDER_LINE_HK
    FROM SRC_H_ORDER_LINE
)


, LOGIC_H_PLANT as (
    SELECT
        PLANT_BK
      , PLANT_HK
    FROM SRC_H_PLANT
)

, LOGIC_H_SALES_ORGANIZATION as (
    SELECT
        SALES_ORGANIZATION_BK
      , SALES_ORGANIZATION_HK
    FROM SRC_H_SALES_ORGANIZATION
)


, LOGIC_LS_BASE as (
    SELECT
        ORDER_LINE_HK
      , VRKME AS SOLD_UNIT_OF_MEASURE
      , NETWR AS NET_VALUE_AMOUNT
      , MWSBP AS TAX_AMOUNT
      , KWMENG AS QUANTITY_ORDERED
      , ABGRU AS CANCELLED_REASON
      , ERDAT::INTEGER AS CREATION_DATE__YYYYMMDD
      , MATKL AS MATERIAL_GROUP
      , PSA_DELETE_IND
    FROM SRC_LS
)

, LOGIC_LS_HEADER as (
    SELECT
        ORDER_HEADER_HK
      , AUART AS ORDER_TYPE
      , AUDAT::INTEGER AS ORDER_DATE__YYYYMMDD
      , ZZRSD::INTEGER AS REQUESTED_SHIP_DATE__YYYYMMDD
    FROM SRC_LS_HEADER
)

---- RENAME LAYER ----

, RENAME_L as (
    SELECT
        PB_REC_SRC
      , L_CUSTOMER_BILLTO_HK
      , L_CUSTOMER_INSURANCEPARTNER_HK
      , L_CUSTOMER_PAYER_HK
      , L_CUSTOMER_SHIPTO_HK
      , L_CUSTOMER_SOLDTO_HK
      , L_DISTRIBUTION_CHANNEL_HK
      , L_DIVISION_HK
      , L_ITEM_HK
      , LOAD_DTS
      , L_ORDER_HEADER_HK
      , L_ORDER_LINE_HK
      , L_PLANT_HK
      , REC_SRC
      , L_SALES_ORGANIZATION_HK
      , SO_ITEM_LHK
    FROM LOGIC_L
)

, RENAME_H_CUSTOMER as (
    SELECT
        CUSTOMER_BK
      , CUSTOMER_HK
      , BKCC
      , REC_SRC
    FROM LOGIC_H_CUSTOMER
)

, RENAME_H_DISTRIBUTION as (
    SELECT
        DISTRIBUTION_CHANNEL_BK
      , DISTRIBUTION_CHANNEL_HK
    FROM LOGIC_H_DISTRIBUTION
)

, RENAME_H_DIVISION as (
    SELECT
        DIVISION_BK
      , DIVISION_HK
    FROM LOGIC_H_DIVISION
)

, RENAME_H_ITEM as (
    SELECT
        ITEM_BK
      , ITEM_HK
    FROM LOGIC_H_ITEM
)

, RENAME_H_ORDER_HEADER as (
    SELECT
        ORDER_HEADER_BK
      , ORDER_HEADER_HK
    FROM LOGIC_H_ORDER_HEADER
)

, RENAME_H_ORDER_LINE as (
    SELECT
        ORDER_LINE_BK
      , ORDER_LINE_HK
    FROM LOGIC_H_ORDER_LINE
)

, RENAME_H_PLANT as (
    SELECT
        PLANT_BK
      , PLANT_HK
    FROM LOGIC_H_PLANT
)

, RENAME_H_SALES_ORGANIZATION as (
    SELECT
        SALES_ORGANIZATION_BK
      , SALES_ORGANIZATION_HK
    FROM LOGIC_H_SALES_ORGANIZATION
)

, RENAME_LS as (
    SELECT
        ORDER_LINE_HK
      , SOLD_UNIT_OF_MEASURE
      , NET_VALUE_AMOUNT
      , TAX_AMOUNT
      , QUANTITY_ORDERED
      , CANCELLED_REASON
      , CREATION_DATE__YYYYMMDD
      , MATERIAL_GROUP
      , PSA_DELETE_IND
    FROM LOGIC_LS_BASE
)

, RENAME_LS_HEADER as (
    SELECT
        ORDER_HEADER_HK
      , ORDER_TYPE
      , ORDER_DATE__YYYYMMDD
      , REQUESTED_SHIP_DATE__YYYYMMDD
    FROM LOGIC_LS_HEADER
)

---- FILTER LAYER ----

, FILTER_L as (
    SELECT *
    FROM RENAME_L
    WHERE REC_SRC <> 'USAZET.SNOWFLAKE.FBIN.DERIVED'
)

, FILTER_H_CUSTOMER as (
    SELECT *
    FROM RENAME_H_CUSTOMER
)

, FILTER_H_DISTRIBUTION as (
    SELECT *
    FROM RENAME_H_DISTRIBUTION
)

, FILTER_H_DIVISION as (
    SELECT *
    FROM RENAME_H_DIVISION
)

, FILTER_H_ITEM as (
    SELECT *
    FROM RENAME_H_ITEM
)

, FILTER_H_ORDER_HEADER as (
    SELECT *
    FROM RENAME_H_ORDER_HEADER
)

, FILTER_H_ORDER_LINE as (
    SELECT *
    FROM RENAME_H_ORDER_LINE
)

, FILTER_H_PLANT as (
    SELECT *
    FROM RENAME_H_PLANT
)

, FILTER_H_SALES_ORGANIZATION as (
    SELECT *
    FROM RENAME_H_SALES_ORGANIZATION
)

, FILTER_LS as (
    SELECT *
    FROM RENAME_LS
)

, FILTER_LS_HEADER as (
    SELECT *
    FROM RENAME_LS_HEADER
)


---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT
        FILTER_L.PB_REC_SRC
      , FILTER_L.L_CUSTOMER_BILLTO_HK
      , FILTER_L.L_CUSTOMER_INSURANCEPARTNER_HK
      , FILTER_L.L_CUSTOMER_PAYER_HK
      , FILTER_L.L_CUSTOMER_SHIPTO_HK
      , FILTER_L.L_CUSTOMER_SOLDTO_HK
      , FILTER_L.L_DISTRIBUTION_CHANNEL_HK
      , FILTER_L.L_DIVISION_HK
      , FILTER_L.L_ITEM_HK
      , FILTER_L.LOAD_DTS
      , FILTER_L.L_ORDER_HEADER_HK
      , FILTER_L.L_ORDER_LINE_HK
      , FILTER_L.L_PLANT_HK
      , FILTER_L.REC_SRC
      , FILTER_L.L_SALES_ORGANIZATION_HK
      , FILTER_L.SO_ITEM_LHK
      
      -- Hub Customer (BillTo)
      , H_CUSTOMER_BILLTO.CUSTOMER_HK as CUSTOMER_BILLTO_HK
      , H_CUSTOMER_BILLTO.CUSTOMER_BK as CUSTOMER_BILLTO_BK
      , H_CUSTOMER_BILLTO.BKCC
      
      -- Hub Customer (Payer)
      , H_CUSTOMER_PAYER.CUSTOMER_HK as CUSTOMER_PAYER_HK
      , H_CUSTOMER_PAYER.CUSTOMER_BK as CUSTOMER_PAYER_BK
      
      -- Hub Customer (ShipTo)
      , H_CUSTOMER_SHIPTO.CUSTOMER_HK as CUSTOMER_SHIPTO_HK
      , H_CUSTOMER_SHIPTO.CUSTOMER_BK as CUSTOMER_SHIPTO_BK
      
      -- Hub Customer (SoldTo)
      , H_CUSTOMER_SOLDTO.CUSTOMER_HK as CUSTOMER_SOLDTO_HK
      , H_CUSTOMER_SOLDTO.CUSTOMER_BK as CUSTOMER_SOLDTO_BK
      
      -- Hub Distribution
      , H_DISTRIBUTION.DISTRIBUTION_CHANNEL_HK
      , H_DISTRIBUTION.DISTRIBUTION_CHANNEL_BK
      
      -- Hub Division
      , H_DIVISION.DIVISION_HK
      , H_DIVISION.DIVISION_BK
      
      -- Hub Item
      , H_ITEM.ITEM_HK
      , H_ITEM.ITEM_BK
      
      -- Hub Order Header
      , H_ORDER_HEADER.ORDER_HEADER_HK
      , H_ORDER_HEADER.ORDER_HEADER_BK
      
      -- Hub Order Line
      , H_ORDER_LINE.ORDER_LINE_HK
      , H_ORDER_LINE.ORDER_LINE_BK
      
      -- Hub Plant
      , H_PLANT.PLANT_HK
      , H_PLANT.PLANT_BK
      
      -- Hub Sales Organization
      , H_SALES_ORG.SALES_ORGANIZATION_HK
      , H_SALES_ORG.SALES_ORGANIZATION_BK

      -- Satellite Line Attributes
      , FILTER_LS.PSA_DELETE_IND
      , FILTER_LS.SOLD_UNIT_OF_MEASURE
      , FILTER_LS.NET_VALUE_AMOUNT
      , FILTER_LS.TAX_AMOUNT
      , FILTER_LS.CANCELLED_REASON
      , FILTER_LS.CREATION_DATE__YYYYMMDD
      , FILTER_LS.MATERIAL_GROUP
      , FILTER_LS.QUANTITY_ORDERED

      -- Satellite Header Attributes
      , FILTER_LS_HEADER.ORDER_TYPE
      , FILTER_LS_HEADER.ORDER_DATE__YYYYMMDD
      , FILTER_LS_HEADER.REQUESTED_SHIP_DATE__YYYYMMDD
      
    FROM FILTER_L
    
    INNER JOIN FILTER_H_CUSTOMER as H_CUSTOMER_BILLTO
        ON FILTER_L.L_CUSTOMER_BILLTO_HK = H_CUSTOMER_BILLTO.CUSTOMER_HK
        
    INNER JOIN FILTER_H_CUSTOMER as H_CUSTOMER_PAYER
        ON FILTER_L.L_CUSTOMER_PAYER_HK = H_CUSTOMER_PAYER.CUSTOMER_HK
        
    INNER JOIN FILTER_H_CUSTOMER as H_CUSTOMER_SHIPTO
        ON FILTER_L.L_CUSTOMER_SHIPTO_HK = H_CUSTOMER_SHIPTO.CUSTOMER_HK
        
    INNER JOIN FILTER_H_CUSTOMER as H_CUSTOMER_SOLDTO
        ON FILTER_L.L_CUSTOMER_SOLDTO_HK = H_CUSTOMER_SOLDTO.CUSTOMER_HK
        
    INNER JOIN FILTER_H_DISTRIBUTION as H_DISTRIBUTION
        ON FILTER_L.L_DISTRIBUTION_CHANNEL_HK = H_DISTRIBUTION.DISTRIBUTION_CHANNEL_HK
        
    INNER JOIN FILTER_H_DIVISION as H_DIVISION
        ON FILTER_L.L_DIVISION_HK = H_DIVISION.DIVISION_HK
        
    INNER JOIN FILTER_H_ITEM as H_ITEM
        ON FILTER_L.L_ITEM_HK = H_ITEM.ITEM_HK
        
    INNER JOIN FILTER_H_ORDER_HEADER as H_ORDER_HEADER
        ON FILTER_L.L_ORDER_HEADER_HK = H_ORDER_HEADER.ORDER_HEADER_HK
        
    INNER JOIN FILTER_H_ORDER_LINE as H_ORDER_LINE
        ON FILTER_L.L_ORDER_LINE_HK = H_ORDER_LINE.ORDER_LINE_HK
        
    INNER JOIN FILTER_H_PLANT as H_PLANT
        ON FILTER_L.L_PLANT_HK = H_PLANT.PLANT_HK
        
    INNER JOIN FILTER_H_SALES_ORGANIZATION as H_SALES_ORG
        ON FILTER_L.L_SALES_ORGANIZATION_HK = H_SALES_ORG.SALES_ORGANIZATION_HK
        
    INNER JOIN FILTER_LS
        ON FILTER_L.L_ORDER_LINE_HK = FILTER_LS.ORDER_LINE_HK
        
    INNER JOIN FILTER_LS_HEADER
        ON FILTER_L.L_ORDER_HEADER_HK = FILTER_LS_HEADER.ORDER_HEADER_HK
)

---- FINAL LAYER ----
SELECT
          PB_REC_SRC
        , CASE BKCC WHEN 'Hiding_Tiger' THEN PSA_DELETE_IND END        as PSA_DELETE_IND
        , SEQ8()                                                       as SEQ_ID
        , CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP )                  as PB_LOAD_DTS
        , LOAD_DTS
        , REC_SRC
        , SO_ITEM_LHK
        , CUSTOMER_BILLTO_HK
        , CUSTOMER_BILLTO_BK
        , BKCC
        , CUSTOMER_PAYER_HK
        , CUSTOMER_PAYER_BK
        , CUSTOMER_SHIPTO_HK
        , CUSTOMER_SHIPTO_BK
        , CUSTOMER_SOLDTO_HK
        , CUSTOMER_SOLDTO_BK
        , DISTRIBUTION_CHANNEL_HK
        , DISTRIBUTION_CHANNEL_BK
        , DIVISION_HK
        , DIVISION_BK
        , ITEM_HK
        , ITEM_BK
        , ORDER_HEADER_HK
        , ORDER_HEADER_BK
        , ORDER_LINE_HK
        , ORDER_LINE_BK
        , PLANT_HK
        , PLANT_BK
        , SALES_ORGANIZATION_HK
        , SALES_ORGANIZATION_BK
        , ORDER_TYPE
        , QUANTITY_ORDERED
        , SOLD_UNIT_OF_MEASURE
        , NET_VALUE_AMOUNT
        , TAX_AMOUNT
        , CANCELLED_REASON
        , ORDER_DATE__YYYYMMDD
        , CREATION_DATE__YYYYMMDD
        , REQUESTED_SHIP_DATE__YYYYMMDD
        , MATERIAL_GROUP 
FROM JOIN_RESULT