---- SRC LAYER ----
WITH
SRC_PFD            as ( SELECT BKCC, DEVICE_ID, DEVICE_MODEL, DEVICE_TYPE, ID, INSTALLATION_POINT, IRRIGATION_TYPE, IS_PAIRED, IS_TEST_DEVICE, LOCATION_ID, NICKNAME, PAIRED_DEVICE_BK, PAIRED_DEVICE_HK, PRV_INSTALLATION, PUCK_CONFIGURED_AT, PURCHASE_LOCATION, REC_SRC, REVERT_MINUTES, REVERT_MODE, REVERT_SCHEDULED_AT, SHOULD_INHERIT_SYSTEM_MODE, TARGET_SYSTEM_MODE, TARGET_VALVE_STATE, _FIVETRAN_DELETED, _FIVETRAN_SYNCED FROM {{ ref('pit_stg_paired_device') }} as SRC  )

/*
SRC_PFD            as ( SELECT * FROM BUS_VAULT.PIT_STG_PAIRED_DEVICE )
*/
---- LOGIC LAYER ----

, LOGIC_PFD as (
    SELECT
        PAIRED_DEVICE_HK
      , PAIRED_DEVICE_BK
      , BKCC
      , REC_SRC
      , ID
      , _FIVETRAN_DELETED
      , IS_PAIRED
      , DEVICE_ID
      , LOCATION_ID
      , _FIVETRAN_SYNCED
      , IS_TEST_DEVICE
      , DEVICE_MODEL
      , SHOULD_INHERIT_SYSTEM_MODE
      , NICKNAME
      , DEVICE_TYPE
      , TARGET_VALVE_STATE
      , REVERT_MINUTES
      , REVERT_SCHEDULED_AT
      , REVERT_MODE
      , TARGET_SYSTEM_MODE
      , PRV_INSTALLATION
      , IRRIGATION_TYPE
      , PUCK_CONFIGURED_AT
      , INSTALLATION_POINT
      , PURCHASE_LOCATION
    FROM SRC_PFD
)
---- RENAME LAYER ----

, RENAME_PFD as (
    SELECT
        PAIRED_DEVICE_HK
      , PAIRED_DEVICE_BK
      , BKCC
      , REC_SRC
      , ID
      , _FIVETRAN_DELETED
      , IS_PAIRED
      , DEVICE_ID
      , LOCATION_ID
      , _FIVETRAN_SYNCED
      , IS_TEST_DEVICE
      , DEVICE_MODEL
      , SHOULD_INHERIT_SYSTEM_MODE
      , NICKNAME
      , DEVICE_TYPE
      , TARGET_VALVE_STATE
      , REVERT_MINUTES
      , REVERT_SCHEDULED_AT
      , REVERT_MODE
      , TARGET_SYSTEM_MODE
      , PRV_INSTALLATION
      , IRRIGATION_TYPE
      , PUCK_CONFIGURED_AT
      , INSTALLATION_POINT
      , PURCHASE_LOCATION
    FROM LOGIC_PFD
)
---- FILTER LAYER ----

, FILTER_PFD as (
    SELECT *
    FROM RENAME_PFD
)
---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT * FROM FILTER_PFD
)

---- FINAL LAYER ----
SELECT
              row_number() over(order by 1)                            as SEQ_ID
        , CURRENT_DATE                                                 as SNAPSHOTDATE
        , CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP )                  as PIT_LOAD_DTS
        , PAIRED_DEVICE_HK
        , PAIRED_DEVICE_BK
        , BKCC
        , REC_SRC
        , ID
        , _FIVETRAN_DELETED
        , IS_PAIRED
        , DEVICE_ID
        , LOCATION_ID
        , _FIVETRAN_SYNCED
        , IS_TEST_DEVICE
        , DEVICE_MODEL
        , SHOULD_INHERIT_SYSTEM_MODE
        , NICKNAME
        , DEVICE_TYPE
        , TARGET_VALVE_STATE
        , REVERT_MINUTES
        , REVERT_SCHEDULED_AT
        , REVERT_MODE
        , TARGET_SYSTEM_MODE
        , PRV_INSTALLATION
        , IRRIGATION_TYPE
        , PUCK_CONFIGURED_AT
        , INSTALLATION_POINT
        , PURCHASE_LOCATION
FROM JOIN_RESULT
