{{ config(alias='dim_device_account_subscription') }}
---- SRC LAYER ----
WITH
SRC_DDAS           as ( SELECT ACCOUNT_ID, BKCC, CANCELED_AT, CANCELLATION_REASON, CANCEL_AT_PERIOD_END, CREATED_AT, CURRENT_PERIOD_END, CURRENT_PERIOD_START, DEVICE_ACCOUNT_BK, ENDED_AT, FIVETRAN_DELETED, FIVETRAN_SYNCED, LOCATION_ID, PLAN_ID, REC_SRC, SOURCE_ID, STATUS, STRIPE_CUSTOMER_ID, STRIPE_SUBSCRIPTION_ID, UPDATED_AT FROM {{ ref('dim_device_account_subscription') }} as SRC  )

/*
SRC_DDAS           as ( SELECT * FROM BUS_VAULT.DIM_DEVICE_ACCOUNT_SUBSCRIPTION )
*/
---- LOGIC LAYER ----

, LOGIC_DDAS as (
    SELECT
        DEVICE_ACCOUNT_BK
      , BKCC
      , REC_SRC
      , ACCOUNT_ID
      , FIVETRAN_SYNCED
      , STRIPE_CUSTOMER_ID
      , UPDATED_AT
      , CANCEL_AT_PERIOD_END
      , CANCELED_AT
      , STRIPE_SUBSCRIPTION_ID
      , CURRENT_PERIOD_END
      , PLAN_ID
      , ENDED_AT
      , CURRENT_PERIOD_START
      , LOCATION_ID
      , STATUS
      , FIVETRAN_DELETED
      , CREATED_AT
      , SOURCE_ID
      , CANCELLATION_REASON
    FROM SRC_DDAS
)
---- RENAME LAYER ----

, RENAME_DDAS as (
    SELECT
        DEVICE_ACCOUNT_BK
      , BKCC
      , REC_SRC
      , ACCOUNT_ID
      , FIVETRAN_SYNCED
      , STRIPE_CUSTOMER_ID
      , UPDATED_AT
      , CANCEL_AT_PERIOD_END
      , CANCELED_AT
      , STRIPE_SUBSCRIPTION_ID
      , CURRENT_PERIOD_END
      , PLAN_ID
      , ENDED_AT
      , CURRENT_PERIOD_START
      , LOCATION_ID
      , STATUS
      , FIVETRAN_DELETED
      , CREATED_AT
      , SOURCE_ID
      , CANCELLATION_REASON
    FROM LOGIC_DDAS
)
---- FILTER LAYER ----

, FILTER_DDAS as (
    SELECT *
    FROM RENAME_DDAS
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM FILTER_DDAS
)

---- FINAL LAYER ----
SELECT
          DEVICE_ACCOUNT_BK
        , BKCC
        , REC_SRC
        , ACCOUNT_ID
        , FIVETRAN_SYNCED
        , STRIPE_CUSTOMER_ID
        , UPDATED_AT
        , CANCEL_AT_PERIOD_END
        , CANCELED_AT
        , STRIPE_SUBSCRIPTION_ID
        , CURRENT_PERIOD_END
        , PLAN_ID
        , ENDED_AT
        , CURRENT_PERIOD_START
        , LOCATION_ID
        , STATUS
        , FIVETRAN_DELETED
        , CREATED_AT
        , SOURCE_ID
        , CANCELLATION_REASON
FROM JOIN_RESULT
