{{ config(alias='rep_device_event') }}
---- SRC LAYER ----
WITH
SRC_FDE            as ( SELECT BKCC, CREATED_AT, DEVICE_LOCATION_BK, EVENT, EVENT_DESCRIPTION, PAIRED_DEVICE_BK, REC_SRC, SOURCE FROM {{ ref('im_fact_device_event') }} as SRC  ),
SRC_DD             as ( SELECT DEVICE_ID, DEVICE_MODEL, DEVICE_TYPE, ID, INSTALLATION_POINT, IRRIGATION_TYPE, IS_PAIRED, IS_TEST_DEVICE, NICKNAME, PAIRED_DEVICE_BK, PRV_INSTALLATION, PUCK_CONFIGURED_AT, PURCHASE_LOCATION, SHOULD_INHERIT_SYSTEM_MODE, TARGET_VALVE_STATE FROM {{ ref('im_dim_paired_device') }} as SRC  ),
SRC_DDL            as ( SELECT ACCOUNT_ID, ADDRESS, ADDRESS_2, AREAS, BATHROOMS, BATHROOM_AMENITIES, CITY, CONSUMPTION, COUNTRY, DEVICE_LOCATION_BK, EXPANSION_TANK, GALLONS_PER_DAY_GOAL, GALVANIZED_PLUMBING, HOT_WATER_RECIRCULATION, IS_IRRIGATION_SCHEDULE_ENABLED, IS_PROFILE_COMPLETE, IS_USING_AWAY_SCHEDULE, KITCHEN_AMENITIES, LATITUDE, LOCATION_CLASS, LOCATION_ID, LOCATION_NAME, LOCATION_SIZE, LOCATION_SIZE_CATEGORY, LOCATION_TYPE, LONGITUDE, MERGED_INTO_LOCATION_ID, OCCUPANTS, OUTDOOR_AMENITIES, PARENT_LOCATION_ID, POSTALCODE, PROFILE, PROFILE_COMPLETED, REVERT_MINUTES, REVERT_MODE, REVERT_SCHEDULED_AT, STATE, STORIES, TANKLESS, TARGET_SYSTEM_MODE, TIMEZONE, WATER_FILTERING_SYSTEM, WATER_SHUTOFF_KNOWN, WATER_SOFTENER, WELL_SYSTEM, WHOLE_HOUSE_HUMIDIFIER FROM {{ ref('im_dim_device_location') }} as SRC  )

/*
SRC_FDE            as ( SELECT * FROM connected_device.IM_FACT_DEVICE_EVENT )
SRC_DD             as ( SELECT * FROM connected_device.IM_DIM_PAIRED_DEVICE )
SRC_DDL            as ( SELECT * FROM connected_device.IM_DIM_DEVICE_LOCATION )
*/
---- LOGIC LAYER ----

, LOGIC_FDE as (
    SELECT
        PAIRED_DEVICE_BK                                             as                               FDE_PAIRED_DEVICE_BK
      , DEVICE_LOCATION_BK                                           as                             FDE_DEVICE_LOCATION_BK
      , BKCC
      , REC_SRC
      , EVENT
      , EVENT_DESCRIPTION
      , CREATED_AT
      , SOURCE
    FROM SRC_FDE
)

, LOGIC_DD as (
    SELECT
        PAIRED_DEVICE_BK
      , ID
      , IS_PAIRED
      , DEVICE_ID
      , IS_TEST_DEVICE
      , DEVICE_MODEL
      , SHOULD_INHERIT_SYSTEM_MODE
      , NICKNAME
      , DEVICE_TYPE
      , TARGET_VALVE_STATE
      , PRV_INSTALLATION
      , IRRIGATION_TYPE
      , PUCK_CONFIGURED_AT
      , INSTALLATION_POINT
      , PURCHASE_LOCATION
    FROM SRC_DD
)

, LOGIC_DDL as (
    SELECT
        DEVICE_LOCATION_BK
      , LOCATION_ID
      , ACCOUNT_ID
      , COUNTRY
      , ADDRESS
      , STORIES
      , BATHROOM_AMENITIES
      , CITY
      , LOCATION_SIZE_CATEGORY
      , TIMEZONE
      , GALVANIZED_PLUMBING
      , KITCHEN_AMENITIES
      , LOCATION_TYPE
      , GALLONS_PER_DAY_GOAL
      , IS_PROFILE_COMPLETE
      , OUTDOOR_AMENITIES
      , POSTALCODE
      , STATE
      , OCCUPANTS
      , WATER_SHUTOFF_KNOWN
      , EXPANSION_TANK
      , TANKLESS
      , WATER_FILTERING_SYSTEM
      , WHOLE_HOUSE_HUMIDIFIER
      , HOT_WATER_RECIRCULATION
      , LOCATION_NAME
      , ADDRESS_2
      , LOCATION_SIZE
      , WELL_SYSTEM
      , WATER_SOFTENER
      , PROFILE_COMPLETED
      , CONSUMPTION
      , BATHROOMS
      , IS_USING_AWAY_SCHEDULE
      , PROFILE
      , IS_IRRIGATION_SCHEDULE_ENABLED
      , REVERT_MINUTES
      , REVERT_MODE
      , REVERT_SCHEDULED_AT
      , TARGET_SYSTEM_MODE
      , AREAS
      , MERGED_INTO_LOCATION_ID
      , PARENT_LOCATION_ID
      , LOCATION_CLASS
      , LATITUDE
      , LONGITUDE
    FROM SRC_DDL
)
---- RENAME LAYER ----

, RENAME_DD as (
    SELECT
        PAIRED_DEVICE_BK
      , ID
      , IS_PAIRED
      , DEVICE_ID
      , IS_TEST_DEVICE
      , DEVICE_MODEL
      , SHOULD_INHERIT_SYSTEM_MODE
      , NICKNAME
      , DEVICE_TYPE
      , TARGET_VALVE_STATE
      , PRV_INSTALLATION
      , IRRIGATION_TYPE
      , PUCK_CONFIGURED_AT
      , INSTALLATION_POINT
      , PURCHASE_LOCATION
    FROM LOGIC_DD
)

, RENAME_DDL as (
    SELECT
        DEVICE_LOCATION_BK
      , LOCATION_ID
      , ACCOUNT_ID
      , COUNTRY
      , ADDRESS
      , STORIES
      , BATHROOM_AMENITIES
      , CITY
      , LOCATION_SIZE_CATEGORY
      , TIMEZONE
      , GALVANIZED_PLUMBING
      , KITCHEN_AMENITIES
      , LOCATION_TYPE
      , GALLONS_PER_DAY_GOAL
      , IS_PROFILE_COMPLETE
      , OUTDOOR_AMENITIES
      , POSTALCODE
      , STATE
      , OCCUPANTS
      , WATER_SHUTOFF_KNOWN
      , EXPANSION_TANK
      , TANKLESS
      , WATER_FILTERING_SYSTEM
      , WHOLE_HOUSE_HUMIDIFIER
      , HOT_WATER_RECIRCULATION
      , LOCATION_NAME
      , ADDRESS_2
      , LOCATION_SIZE
      , WELL_SYSTEM
      , WATER_SOFTENER
      , PROFILE_COMPLETED
      , CONSUMPTION
      , BATHROOMS
      , IS_USING_AWAY_SCHEDULE
      , PROFILE
      , IS_IRRIGATION_SCHEDULE_ENABLED
      , REVERT_MINUTES
      , REVERT_MODE
      , REVERT_SCHEDULED_AT
      , TARGET_SYSTEM_MODE
      , AREAS
      , MERGED_INTO_LOCATION_ID
      , PARENT_LOCATION_ID
      , LOCATION_CLASS
      , LATITUDE
      , LONGITUDE
    FROM LOGIC_DDL
)

, RENAME_FDE as (
    SELECT
        FDE_PAIRED_DEVICE_BK
      , FDE_DEVICE_LOCATION_BK
      , BKCC
      , REC_SRC
      , EVENT
      , EVENT_DESCRIPTION
      , CREATED_AT
      , SOURCE
    FROM LOGIC_FDE
)
---- FILTER LAYER ----

, FILTER_FDE as (
    SELECT *
    FROM RENAME_FDE
)

, FILTER_DD as (
    SELECT *
    FROM RENAME_DD
)

, FILTER_DDL as (
    SELECT *
    FROM RENAME_DDL
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM FILTER_FDE
    INNER JOIN FILTER_DD
        ON FDE_PAIRED_DEVICE_BK = PAIRED_DEVICE_BK
    INNER JOIN FILTER_DDL
        ON FDE_DEVICE_LOCATION_BK = DEVICE_LOCATION_BK
)

---- FINAL LAYER ----
SELECT
          PAIRED_DEVICE_BK
        , DEVICE_LOCATION_BK
        , BKCC
        , REC_SRC
        , EVENT
        , EVENT_DESCRIPTION
        , CREATED_AT
        , SOURCE
        , ID
        , IS_PAIRED
        , DEVICE_ID
        , IS_TEST_DEVICE
        , DEVICE_MODEL
        , SHOULD_INHERIT_SYSTEM_MODE
        , NICKNAME
        , DEVICE_TYPE
        , TARGET_VALVE_STATE
        , PRV_INSTALLATION
        , IRRIGATION_TYPE
        , PUCK_CONFIGURED_AT
        , INSTALLATION_POINT
        , PURCHASE_LOCATION
        , LOCATION_ID
        , ACCOUNT_ID
        , COUNTRY
        , ADDRESS
        , STORIES
        , BATHROOM_AMENITIES
        , CITY
        , LOCATION_SIZE_CATEGORY
        , TIMEZONE
        , GALVANIZED_PLUMBING
        , KITCHEN_AMENITIES
        , LOCATION_TYPE
        , GALLONS_PER_DAY_GOAL
        , IS_PROFILE_COMPLETE
        , OUTDOOR_AMENITIES
        , POSTALCODE
        , STATE
        , OCCUPANTS
        , WATER_SHUTOFF_KNOWN
        , EXPANSION_TANK
        , TANKLESS
        , WATER_FILTERING_SYSTEM
        , WHOLE_HOUSE_HUMIDIFIER
        , HOT_WATER_RECIRCULATION
        , LOCATION_NAME
        , ADDRESS_2
        , LOCATION_SIZE
        , WELL_SYSTEM
        , WATER_SOFTENER
        , PROFILE_COMPLETED
        , CONSUMPTION
        , BATHROOMS
        , IS_USING_AWAY_SCHEDULE
        , PROFILE
        , IS_IRRIGATION_SCHEDULE_ENABLED
        , REVERT_MINUTES
        , REVERT_MODE
        , REVERT_SCHEDULED_AT
        , TARGET_SYSTEM_MODE
        , AREAS
        , MERGED_INTO_LOCATION_ID
        , PARENT_LOCATION_ID
        , LOCATION_CLASS
        , LATITUDE
        , LONGITUDE
FROM JOIN_RESULT
