{{ config(alias='fact_ecommerce_traffic_by_session') }}
---- SRC LAYER ----
WITH
SRC_fact_traffic   as ( SELECT BKCC, ECOMMERCE_ACCOUNT_BK, ECOMMERCE_ACCOUNT_COUNTRY, ECOMMERCE_ACCOUNT_HK, ECOMMERCE_ANALYTICS_SERVICE, 
                        ECOMMERCE_PROPERTY_BK, ECOMMERCE_PROPERTY_CURRENCY_CODE, ECOMMERCE_PROPERTY_HK, ECOMMERCE_PROPERTY_ID, ECOMMERCE_PROPERTY_TIMEZONE, 
                        ECOMMERCE_PROPERTY_TYPE, ENGAGED_SESSIONS, ENGAGEMENT_RATE, EVENTS_PER_ENGAGED_SESSION, EVENTS_PER_SESSION, EVENT_COUNT, KEY_EVENTS, 
                        REC_SRC, SESSIONS, SESSIONS_PER_USER, SESSION_CHANNEL_GROUP, SESSION_DATE__YYYYMMDD, TOTAL_REVENUE, TOTAL_USERS, WEEK_ENDING_DATEKEY 
                        FROM {{ ref('fact_ecommerce_traffic_by_session') }} as SRC  )

/*
SRC_fact_traffic   as ( SELECT * FROM bus_vault.fact_ecommerce_traffic_by_session )
*/
---- LOGIC LAYER ----

, LOGIC_fact_traffic as (
    SELECT
        ECOMMERCE_ACCOUNT_HK
      , ECOMMERCE_ACCOUNT_BK
      , ECOMMERCE_PROPERTY_HK
      , ECOMMERCE_PROPERTY_BK
      , ECOMMERCE_ACCOUNT_COUNTRY
      , ECOMMERCE_ANALYTICS_SERVICE
      , ECOMMERCE_PROPERTY_ID
      , ECOMMERCE_PROPERTY_TYPE
      , ECOMMERCE_PROPERTY_TIMEZONE
      , SESSION_DATE__YYYYMMDD
      , WEEK_ENDING_DATEKEY
      , SESSION_CHANNEL_GROUP
      , SESSIONS
      , ENGAGEMENT_RATE
      , KEY_EVENTS
      , TOTAL_USERS
      , ENGAGED_SESSIONS
      , EVENT_COUNT
      , EVENTS_PER_SESSION
      , EVENTS_PER_ENGAGED_SESSION
      , SESSIONS_PER_USER
      , TOTAL_REVENUE
      , ECOMMERCE_PROPERTY_CURRENCY_CODE
      , REC_SRC
      , BKCC
    FROM SRC_fact_traffic
)
---- RENAME LAYER ----

, RENAME_fact_traffic as (
    SELECT
        ECOMMERCE_ACCOUNT_HK
      , ECOMMERCE_ACCOUNT_BK
      , ECOMMERCE_PROPERTY_HK
      , ECOMMERCE_PROPERTY_BK
      , ECOMMERCE_ACCOUNT_COUNTRY
      , ECOMMERCE_ANALYTICS_SERVICE
      , ECOMMERCE_PROPERTY_ID
      , ECOMMERCE_PROPERTY_TYPE
      , ECOMMERCE_PROPERTY_TIMEZONE
      , SESSION_DATE__YYYYMMDD
      , WEEK_ENDING_DATEKEY
      , SESSION_CHANNEL_GROUP
      , SESSIONS
      , ENGAGEMENT_RATE
      , KEY_EVENTS
      , TOTAL_USERS
      , ENGAGED_SESSIONS
      , EVENT_COUNT
      , EVENTS_PER_SESSION
      , EVENTS_PER_ENGAGED_SESSION
      , SESSIONS_PER_USER
      , TOTAL_REVENUE
      , ECOMMERCE_PROPERTY_CURRENCY_CODE
      , REC_SRC
      , BKCC
    FROM LOGIC_fact_traffic
)
---- FILTER LAYER ----

, FILTER_fact_traffic as (
    SELECT *
    FROM RENAME_fact_traffic
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM FILTER_fact_traffic
)

---- FINAL LAYER ----
SELECT
          ECOMMERCE_ACCOUNT_HK
        , ECOMMERCE_ACCOUNT_BK
        , ECOMMERCE_PROPERTY_HK
        , ECOMMERCE_PROPERTY_BK
        , ECOMMERCE_ACCOUNT_COUNTRY
        , ECOMMERCE_ANALYTICS_SERVICE
        , ECOMMERCE_PROPERTY_ID
        , ECOMMERCE_PROPERTY_TYPE
        , ECOMMERCE_PROPERTY_TIMEZONE
        , SESSION_DATE__YYYYMMDD
        , WEEK_ENDING_DATEKEY
        , SESSION_CHANNEL_GROUP
        , SESSIONS
        , ENGAGEMENT_RATE
        , KEY_EVENTS
        , TOTAL_USERS
        , ENGAGED_SESSIONS
        , EVENT_COUNT
        , EVENTS_PER_SESSION
        , EVENTS_PER_ENGAGED_SESSION
        , SESSIONS_PER_USER
        , TOTAL_REVENUE
        , ECOMMERCE_PROPERTY_CURRENCY_CODE
        , REC_SRC
        , BKCC
FROM JOIN_RESULT
