---- SRC LAYER ----
WITH
SRC_fact_traffic   as ( SELECT ECOMMERCE_ACCOUNT_BK, ECOMMERCE_ACCOUNT_COUNTRY, ECOMMERCE_ACCOUNT_HK, ECOMMERCE_ANALYTICS_SERVICE, 
                        ECOMMERCE_PROPERTY_BK, ECOMMERCE_PROPERTY_CURRENCY_CODE, ECOMMERCE_PROPERTY_HK, ECOMMERCE_PROPERTY_TYPE, ENGAGED_SESSIONS, 
                        ENGAGEMENT_RATE, EVENTS_PER_ENGAGED_SESSION, EVENTS_PER_SESSION, EVENT_COUNT, KEY_EVENTS, SESSIONS, SESSIONS_PER_USER, 
                        SESSION_CHANNEL_GROUP, TOTAL_REVENUE, WEEK_ENDING_DATEKEY FROM {{ ref('im_dtc_fact_ecommerce_traffic_by_session') }} as SRC  ),
SRC_dim_date       as ( SELECT DATE, DATE_BK, FISCAL_445_CAL_MONTH, FISCAL_445_CAL_MONTH_YYYYMM, FISCAL_445_CAL_QUARTER, FISCAL_445_CAL_QUARTER_YYYYQQ, 
                        FISCAL_445_CAL_WEEK, FISCAL_445_CAL_WEEK_YYYYWW, FISCAL_445_CAL_YEAR, FISCAL_LAST_12_MONTHS_FLAG, FISCAL_LAST_13_WEEKS_FLAG, 
                        FISCAL_LAST_3_MONTHS_FLAG, FISCAL_LAST_4_WEEKS_FLAG, FISCAL_LAST_MONTH_FLAG, FISCAL_LAST_QUARTER_FLAG, FISCAL_LAST_WEEK_FLAG, 
                        FISCAL_QTD_FLAG, FISCAL_ROLLING_52_WEEK_FLAG, FISCAL_YTD_FLAG, IS_COMPLETED_FISCAL_MONTH, IS_COMPLETED_FISCAL_WEEK, 
                        WEEKS_IN_MONTH FROM {{ ref('im_dtc_dim_date_fiscal_445') }} as SRC  )

/*
SRC_fact_traffic   as ( SELECT * FROM direct_to_consumer.im_dtc_fact_ecommerce_traffic_by_session )
SRC_dim_date       as ( SELECT * FROM direct_to_consumer.im_dtc_dim_date_fiscal_445 )
*/
---- LOGIC LAYER ----

, LOGIC_fact_traffic as (
    SELECT
        ECOMMERCE_ACCOUNT_HK
      , ECOMMERCE_ACCOUNT_BK                                         as                                  ECOMMERCE_ACCOUNT
      , ECOMMERCE_PROPERTY_HK
      , ECOMMERCE_PROPERTY_BK                                        as                                 ECOMMERCE_PROPERTY
      , ECOMMERCE_ACCOUNT_COUNTRY
      , ECOMMERCE_ANALYTICS_SERVICE
      , ECOMMERCE_PROPERTY_TYPE
      , SESSION_CHANNEL_GROUP
      , ECOMMERCE_PROPERTY_CURRENCY_CODE
      , WEEK_ENDING_DATEKEY                                          as                   FACT_TRAFFIC_WEEK_ENDING_DATEKEY
      , SESSIONS
      , ENGAGED_SESSIONS
      , ENGAGEMENT_RATE
      , KEY_EVENTS
      , EVENT_COUNT
      , EVENTS_PER_SESSION
      , EVENTS_PER_ENGAGED_SESSION
      , TOTAL_REVENUE
      , SESSIONS_PER_USER
    FROM SRC_fact_traffic
)

, LOGIC_dim_date as (
    SELECT
        DATE                                                         as                                   WEEK_ENDING_DATE
      , FISCAL_445_CAL_WEEK
      , FISCAL_445_CAL_WEEK_YYYYWW
      , FISCAL_445_CAL_MONTH
      , FISCAL_445_CAL_MONTH_YYYYMM
      , FISCAL_445_CAL_QUARTER
      , FISCAL_445_CAL_QUARTER_YYYYQQ
      , FISCAL_445_CAL_YEAR
      , FISCAL_LAST_WEEK_FLAG
      , FISCAL_LAST_4_WEEKS_FLAG
      , FISCAL_LAST_13_WEEKS_FLAG
      , FISCAL_LAST_MONTH_FLAG
      , FISCAL_LAST_3_MONTHS_FLAG
      , FISCAL_YTD_FLAG
      , FISCAL_ROLLING_52_WEEK_FLAG
      , FISCAL_LAST_QUARTER_FLAG
      , FISCAL_LAST_12_MONTHS_FLAG
      , FISCAL_QTD_FLAG
      , WEEKS_IN_MONTH
      , IS_COMPLETED_FISCAL_MONTH
      , IS_COMPLETED_FISCAL_WEEK
      , DATE_BK                                                      as                                   DIM_DATE_DATE_BK
    FROM SRC_dim_date
)
---- RENAME LAYER ----

, RENAME_fact_traffic as (
    SELECT
        ECOMMERCE_ACCOUNT_HK
      , ECOMMERCE_ACCOUNT
      , ECOMMERCE_PROPERTY_HK
      , ECOMMERCE_PROPERTY
      , ECOMMERCE_ACCOUNT_COUNTRY
      , ECOMMERCE_ANALYTICS_SERVICE
      , ECOMMERCE_PROPERTY_TYPE
      , SESSION_CHANNEL_GROUP
      , ECOMMERCE_PROPERTY_CURRENCY_CODE
      , FACT_TRAFFIC_WEEK_ENDING_DATEKEY
      , SESSIONS
      , ENGAGED_SESSIONS
      , ENGAGEMENT_RATE
      , KEY_EVENTS
      , EVENT_COUNT
      , EVENTS_PER_SESSION
      , EVENTS_PER_ENGAGED_SESSION
      , TOTAL_REVENUE
      , SESSIONS_PER_USER
    FROM LOGIC_fact_traffic
)

, RENAME_dim_date as (
    SELECT
        WEEK_ENDING_DATE
      , FISCAL_445_CAL_WEEK
      , FISCAL_445_CAL_WEEK_YYYYWW
      , FISCAL_445_CAL_MONTH
      , FISCAL_445_CAL_MONTH_YYYYMM
      , FISCAL_445_CAL_QUARTER
      , FISCAL_445_CAL_QUARTER_YYYYQQ
      , FISCAL_445_CAL_YEAR
      , FISCAL_LAST_WEEK_FLAG
      , FISCAL_LAST_4_WEEKS_FLAG
      , FISCAL_LAST_13_WEEKS_FLAG
      , FISCAL_LAST_MONTH_FLAG
      , FISCAL_LAST_3_MONTHS_FLAG
      , FISCAL_YTD_FLAG
      , FISCAL_ROLLING_52_WEEK_FLAG
      , FISCAL_LAST_QUARTER_FLAG
      , FISCAL_LAST_12_MONTHS_FLAG
      , FISCAL_QTD_FLAG
      , WEEKS_IN_MONTH
      , IS_COMPLETED_FISCAL_MONTH
      , IS_COMPLETED_FISCAL_WEEK
      , DIM_DATE_DATE_BK
    FROM LOGIC_dim_date
)
---- FILTER LAYER ----

, FILTER_fact_traffic as (
    SELECT *
    FROM RENAME_fact_traffic
)

, FILTER_dim_date as (
    SELECT *
    FROM RENAME_dim_date
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM FILTER_fact_traffic
    LEFT JOIN FILTER_dim_date
        ON FACT_TRAFFIC_WEEK_ENDING_DATEKEY = DIM_DATE_DATE_BK
)

---- FINAL LAYER ----
SELECT
          ECOMMERCE_ACCOUNT_HK
        , ECOMMERCE_ACCOUNT
        , ECOMMERCE_PROPERTY_HK
        , ECOMMERCE_PROPERTY
        , ECOMMERCE_ACCOUNT_COUNTRY
        , ECOMMERCE_ANALYTICS_SERVICE
        , ECOMMERCE_PROPERTY_TYPE
        , SESSION_CHANNEL_GROUP
        , WEEK_ENDING_DATE
        , FISCAL_445_CAL_WEEK
        , FISCAL_445_CAL_WEEK_YYYYWW
        , FISCAL_445_CAL_MONTH
        , FISCAL_445_CAL_MONTH_YYYYMM
        , FISCAL_445_CAL_QUARTER
        , FISCAL_445_CAL_QUARTER_YYYYQQ
        , FISCAL_445_CAL_YEAR
        , FISCAL_LAST_WEEK_FLAG
        , FISCAL_LAST_4_WEEKS_FLAG
        , FISCAL_LAST_13_WEEKS_FLAG
        , FISCAL_LAST_MONTH_FLAG
        , FISCAL_LAST_3_MONTHS_FLAG
        , FISCAL_YTD_FLAG
        , FISCAL_ROLLING_52_WEEK_FLAG
        , FISCAL_LAST_QUARTER_FLAG
        , FISCAL_LAST_12_MONTHS_FLAG
        , FISCAL_QTD_FLAG
        , WEEKS_IN_MONTH
        , IS_COMPLETED_FISCAL_MONTH
        , IS_COMPLETED_FISCAL_WEEK
        , SUM(SESSIONS)                                                as TOTAL_SESSIONS
        , SUM(ENGAGED_SESSIONS)                                        as TOTAL_ENGAGED_SESSIONS
        , AVG(ENGAGEMENT_RATE)::DECIMAL(28,2)                          as AVG_ENGAGEMENT_RATE
        , SUM(KEY_EVENTS)                                              as TOTAL_KEY_EVENTS
        , SUM(EVENT_COUNT)                                             as TOTAL_EVENT_COUNT
        , AVG(EVENTS_PER_SESSION)::DECIMAL(28,2)                       as AVG_EVENTS_PER_SESSION
        , AVG(EVENTS_PER_ENGAGED_SESSION)::DECIMAL(28,2)               as AVG_EVENTS_PER_ENGAGED_SESSION
        , AVG(SESSIONS_PER_USER)::DECIMAL(28,2)                        as AVG_SESSIONS_PER_USER
        , SUM(TOTAL_REVENUE)                                           as TOTAL_REVENUE
        , ECOMMERCE_PROPERTY_CURRENCY_CODE
FROM JOIN_RESULT
GROUP BY ALL