---- SRC LAYER ----
WITH
SRC_ETSWGA         as ( SELECT BKCC, ECOMMERCE_ACCOUNT_BK, ECOMMERCE_ACCOUNT_COUNTRY, ECOMMERCE_ACCOUNT_HK, ECOMMERCE_ANALYTICS_SERVICE, ECOMMERCE_PROPERTY_BK, 
                        ECOMMERCE_PROPERTY_CURRENCY_CODE, ECOMMERCE_PROPERTY_HK, ECOMMERCE_PROPERTY_ID, ECOMMERCE_PROPERTY_TIMEZONE, ECOMMERCE_PROPERTY_TYPE, 
                        ENGAGED_SESSIONS, ENGAGEMENT_RATE, EVENTS_PER_ENGAGED_SESSION, EVENTS_PER_SESSION, EVENT_COUNT, KEY_EVENTS, LNK_ECOMMERCE_ACCOUNT_PROPERTY_HK, 
                        REC_SRC, SESSIONS, SESSIONS_PER_USER, SESSION_CHANNEL_GROUP, SESSION_DATE__YYYYMMDD, TOTAL_REVENUE, TOTAL_USERS, WEEK_ENDING_DATEKEY 
                        FROM {{ ref('pb_stg_ecommerce_traffic_by_session_winn_ga') }} as SRC  ),
SRC_ETSHWGA        as ( SELECT BKCC, ECOMMERCE_ACCOUNT_BK, ECOMMERCE_ACCOUNT_COUNTRY, ECOMMERCE_ACCOUNT_HK, ECOMMERCE_ANALYTICS_SERVICE, ECOMMERCE_PROPERTY_BK, 
                        ECOMMERCE_PROPERTY_CURRENCY_CODE, ECOMMERCE_PROPERTY_HK, ECOMMERCE_PROPERTY_ID, ECOMMERCE_PROPERTY_TIMEZONE, ECOMMERCE_PROPERTY_TYPE, 
                        ENGAGED_SESSIONS, ENGAGEMENT_RATE, EVENTS_PER_ENGAGED_SESSION, EVENTS_PER_SESSION, EVENT_COUNT, KEY_EVENTS, LNK_ECOMMERCE_ACCOUNT_PROPERTY_HK, 
                        REC_SRC, SESSIONS, SESSIONS_PER_USER, SESSION_CHANNEL_GROUP, SESSION_DATE__YYYYMMDD, TOTAL_REVENUE, TOTAL_USERS, WEEK_ENDING_DATEKEY 
                        FROM {{ ref('pb_stg_ecommerce_traffic_by_session_history_winn_ga') }} as SRC  )

/*
SRC_ETSWGA         as ( SELECT * FROM bus_vault.PB_STG_ECOMMERCE_TRAFFIC_BY_SESSION_WINN_GA )
SRC_ETSHWGA        as ( SELECT * FROM bus_vault.PB_STG_ECOMMERCE_TRAFFIC_BY_SESSION_HISTORY_WINN_GA )
*/
---- LOGIC LAYER ----

, LOGIC_ETSWGA as (
    SELECT
        LNK_ECOMMERCE_ACCOUNT_PROPERTY_HK
      , ECOMMERCE_ACCOUNT_HK
      , ECOMMERCE_ACCOUNT_BK
      , ECOMMERCE_PROPERTY_HK
      , ECOMMERCE_PROPERTY_BK
      , ECOMMERCE_ACCOUNT_COUNTRY
      , ECOMMERCE_ANALYTICS_SERVICE
      , ECOMMERCE_PROPERTY_ID
      , ECOMMERCE_PROPERTY_TYPE
      , ECOMMERCE_PROPERTY_TIMEZONE
      , SESSION_DATE__YYYYMMDD
      , WEEK_ENDING_DATEKEY
      , SESSION_CHANNEL_GROUP
      , SESSIONS
      , ENGAGEMENT_RATE
      , KEY_EVENTS
      , TOTAL_USERS
      , ENGAGED_SESSIONS
      , EVENT_COUNT
      , EVENTS_PER_SESSION
      , EVENTS_PER_ENGAGED_SESSION
      , SESSIONS_PER_USER
      , TOTAL_REVENUE
      , ECOMMERCE_PROPERTY_CURRENCY_CODE
      , REC_SRC
      , BKCC
    FROM SRC_ETSWGA
)

, LOGIC_ETSHWGA as (
    SELECT
        LNK_ECOMMERCE_ACCOUNT_PROPERTY_HK
      , ECOMMERCE_ACCOUNT_HK
      , ECOMMERCE_ACCOUNT_BK
      , ECOMMERCE_PROPERTY_HK
      , ECOMMERCE_PROPERTY_BK
      , ECOMMERCE_ACCOUNT_COUNTRY
      , ECOMMERCE_ANALYTICS_SERVICE
      , ECOMMERCE_PROPERTY_ID
      , ECOMMERCE_PROPERTY_TYPE
      , ECOMMERCE_PROPERTY_TIMEZONE
      , SESSION_DATE__YYYYMMDD
      , WEEK_ENDING_DATEKEY
      , SESSION_CHANNEL_GROUP
      , SESSIONS
      , ENGAGEMENT_RATE
      , KEY_EVENTS
      , TOTAL_USERS
      , ENGAGED_SESSIONS
      , EVENT_COUNT
      , EVENTS_PER_SESSION
      , EVENTS_PER_ENGAGED_SESSION
      , SESSIONS_PER_USER
      , TOTAL_REVENUE
      , ECOMMERCE_PROPERTY_CURRENCY_CODE
      , REC_SRC
      , BKCC
    FROM SRC_ETSHWGA
)
---- RENAME LAYER ----

, RENAME_ETSWGA as (
    SELECT
        LNK_ECOMMERCE_ACCOUNT_PROPERTY_HK
      , ECOMMERCE_ACCOUNT_HK
      , ECOMMERCE_ACCOUNT_BK
      , ECOMMERCE_PROPERTY_HK
      , ECOMMERCE_PROPERTY_BK
      , ECOMMERCE_ACCOUNT_COUNTRY
      , ECOMMERCE_ANALYTICS_SERVICE
      , ECOMMERCE_PROPERTY_ID
      , ECOMMERCE_PROPERTY_TYPE
      , ECOMMERCE_PROPERTY_TIMEZONE
      , SESSION_DATE__YYYYMMDD
      , WEEK_ENDING_DATEKEY
      , SESSION_CHANNEL_GROUP
      , SESSIONS
      , ENGAGEMENT_RATE
      , KEY_EVENTS
      , TOTAL_USERS
      , ENGAGED_SESSIONS
      , EVENT_COUNT
      , EVENTS_PER_SESSION
      , EVENTS_PER_ENGAGED_SESSION
      , SESSIONS_PER_USER
      , TOTAL_REVENUE
      , ECOMMERCE_PROPERTY_CURRENCY_CODE
      , REC_SRC
      , BKCC
    FROM LOGIC_ETSWGA
)

, RENAME_ETSHWGA as (
    SELECT
        LNK_ECOMMERCE_ACCOUNT_PROPERTY_HK
      , ECOMMERCE_ACCOUNT_HK
      , ECOMMERCE_ACCOUNT_BK
      , ECOMMERCE_PROPERTY_HK
      , ECOMMERCE_PROPERTY_BK
      , ECOMMERCE_ACCOUNT_COUNTRY
      , ECOMMERCE_ANALYTICS_SERVICE
      , ECOMMERCE_PROPERTY_ID
      , ECOMMERCE_PROPERTY_TYPE
      , ECOMMERCE_PROPERTY_TIMEZONE
      , SESSION_DATE__YYYYMMDD
      , WEEK_ENDING_DATEKEY
      , SESSION_CHANNEL_GROUP
      , SESSIONS
      , ENGAGEMENT_RATE
      , KEY_EVENTS
      , TOTAL_USERS
      , ENGAGED_SESSIONS
      , EVENT_COUNT
      , EVENTS_PER_SESSION
      , EVENTS_PER_ENGAGED_SESSION
      , SESSIONS_PER_USER
      , TOTAL_REVENUE
      , ECOMMERCE_PROPERTY_CURRENCY_CODE
      , REC_SRC
      , BKCC
    FROM LOGIC_ETSHWGA
)
---- FILTER LAYER ----

, FILTER_ETSWGA as (
    SELECT *
    FROM RENAME_ETSWGA
)

, FILTER_ETSHWGA as (
    SELECT *
    FROM RENAME_ETSHWGA
)
---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT * FROM FILTER_ETSWGA
    UNION ALL
    SELECT * FROM FILTER_ETSHWGA
)

---- FINAL LAYER ----
SELECT
          RANDOM()                                                     as SEQ_ID
        ,  'PB_ECOMMERCE_TRAFFIC_BY_SESSION'                           as PB_REC_SRC
        , CURRENT_DATE                                                 as SNAPSHOTDATE
        , CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP )                  as PB_LOAD_DTS
        , LNK_ECOMMERCE_ACCOUNT_PROPERTY_HK
        , ECOMMERCE_ACCOUNT_HK
        , ECOMMERCE_ACCOUNT_BK
        , ECOMMERCE_PROPERTY_HK
        , ECOMMERCE_PROPERTY_BK
        , ECOMMERCE_ACCOUNT_COUNTRY
        , ECOMMERCE_ANALYTICS_SERVICE
        , ECOMMERCE_PROPERTY_ID
        , ECOMMERCE_PROPERTY_TYPE
        , ECOMMERCE_PROPERTY_TIMEZONE
        , SESSION_DATE__YYYYMMDD
        , WEEK_ENDING_DATEKEY
        , SESSION_CHANNEL_GROUP
        , SESSIONS
        , ENGAGEMENT_RATE
        , KEY_EVENTS
        , TOTAL_USERS
        , ENGAGED_SESSIONS
        , EVENT_COUNT
        , EVENTS_PER_SESSION
        , EVENTS_PER_ENGAGED_SESSION
        , SESSIONS_PER_USER
        , TOTAL_REVENUE
        , ECOMMERCE_PROPERTY_CURRENCY_CODE
        , REC_SRC
        , BKCC
FROM JOIN_RESULT
