with
cte_hz_customer_accounts as (
    select
        hca.competitor_type
        , hca.ship_partial
        , hca.po_effective_date
        , hca.program_id
        , hca.global_attribute5
        , hca.global_attribute4
        , hca.under_return_tolerance
        , hca.global_attribute7
        , hca.global_attribute6
        , hca.global_attribute1
        , hca.global_attribute3
        , hca.global_attribute2
        , hca.freight_term
        , hca.acct_life_cycle_status
        , hca.global_attribute9
        , hca.global_attribute8
        , hca.attribute3
        , hca.created_by_module
        , hca.orig_system_reference
        , hca.attribute2
        , hca.attribute1
        , hca.hotwatch_svc_bal_ind
        , hca.account_replication_key
        , hca.attribute9
        , hca.department
        , hca.attribute8
        , hca.attribute7
        , hca.attribute6
        , hca.attribute5
        , hca.attribute4
        , hca.over_shipment_tolerance
        , hca.watch_balance_indicator
        , hca.deposit_refund_method
        , hca.account_established_date
        , hca.pin_number
        , hca.autopay_flag
        , hca.attribute10
        , hca.attribute14 as key_account_number
        , hca.attribute13
        , hca.cust_account_id
        , hca.attribute12
        , hca.attribute11
        , hca.customer_type
        , hca.high_priority_remarks
        , hca.dormant_account_flag
        , hca.comments
        , hca.write_off_amount
        , hca.dates_positive_tolerance
        , hca.over_return_tolerance
        , hca.credit_classification_code
        , hca.single_user_flag
        , hca.sales_channel_code
        , hca.current_balance
        , hca.secondary_specialist_id
        , hca.restriction_limit_amount
        , hca.order_type_id
        , hca.attribute20
        , hca.suspension_date
        , hca.tax_header_level_flag
        , hca.global_attribute20
        , hca.status_update_date
        , hca.global_attribute17
        , hca.global_attribute18
        , hca.global_attribute15
        , hca.global_attribute16
        , hca.realtime_rate_flag
        , hca.global_attribute13
        , hca.global_attribute14
        , hca.global_attribute11
        , hca.global_attribute12
        , hca.attribute18
        , hca.attribute17
        , hca.attribute16
        , hca.attribute15
        , hca.high_priority_indicator
        , hca.fob_point
        , hca.hotwatch_service_flag
        , hca.global_attribute19
        , hca.attribute19
        , hca.npa_number
        , hca.write_off_payment_amount
        , hca.account_activation_date
        , hca.global_attribute10
        , hca.coterminate_day_month
        , hca.ship_via
        , hca.arrivalsets_include_lines_flag
        , hca.subcategory_code
        , hca.geo_code
        , hca.account_name
        , hca.status
        , hca.source_code
        , hca.notify_flag
        , hca.object_version_number
        , hca.account_number
        , hca.write_off_adjustment_amount
        , hca.ship_sets_include_lines_flag
        , hca.created_by
        , hca.last_updated_by
        , hca.payment_term_id
        , hca.under_shipment_tolerance
        , hca.customer_class_code
        , hca.sched_date_push_flag
        , hca.account_termination_date
        , hca.price_list_id
        , hca.warehouse_id
        , hca.attribute_category
        , hca.selling_party_id
        , hca.program_application_id
        , hca.last_batch_id
        , hca.password_text
        , hca.tax_rounding_rule
        , hca.party_id
        , hca.application_id
        , hca.request_id
        , hca.po_expiration_date
        , hca.date_type_preference
        , hca.account_liable_flag
        , hca.item_cross_ref_pref
        , hca.invoice_quantity_rule
        , hca.hold_bill_flag
        , hca.dates_negative_tolerance
        , hca.last_update_login
        , hca.held_bill_expiration_date
        , hca.global_attribute_category
        , hca.wh_update_date
        , hca.major_account_number
        , hca.pricing_event
        , hca.primary_specialist_id
        , hca.primary_salesrep_id
        , hca.tax_code
        , hca._fivetran_deleted
        , hca._fivetran_synced
        , hca.program_update_date
        , hca.creation_date
        , hca.last_update_date
    from {{ source('bronze_ml_ebs_cust', 'hz_parties') }} as hp
        inner join {{ source('bronze_ml_ebs_cust', 'hz_cust_accounts') }} as hca
            on hp.party_id = hca.party_id
                -- and hp.category_code like 'MLC-ACCOUNT'
)

select * from cte_hz_customer_accounts