---- SRC LAYER ----
WITH
SRC_SQN            as ( SELECT QUALITY_NOTIFICATION_HK , QUALITY_NOTIFICATION_BK , LOAD_DTS , BKCC , REC_SRC FROM {{ ref('v_psa_stg_quality_notifications') }} as SRC 
                        QUALIFY (ROW_NUMBER() OVER(PARTITION BY QUALITY_NOTIFICATION_BK ORDER BY LOAD_DTS ))=1 )

/*
SRC_SQN            as ( SELECT * FROM STAGING.v_psa_stg_quality_notifications )
*/
---- LOGIC LAYER ----

, LOGIC_SQN as (
    SELECT
        QUALITY_NOTIFICATION_HK
      , QUALITY_NOTIFICATION_BK
      , LOAD_DTS
      , BKCC
      , REC_SRC
    FROM SRC_SQN
)
---- RENAME LAYER ----

, RENAME_SQN as (
    SELECT
        QUALITY_NOTIFICATION_HK
      , QUALITY_NOTIFICATION_BK
      , LOAD_DTS
      , BKCC
      , REC_SRC
    FROM LOGIC_SQN
)
---- FILTER LAYER ----

, FILTER_SQN as (
    SELECT *
    FROM RENAME_SQN
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM FILTER_SQN
)

---- FINAL LAYER ----
SELECT
          QUALITY_NOTIFICATION_HK
        , QUALITY_NOTIFICATION_BK
        , LOAD_DTS
        , BKCC
        , REC_SRC
FROM JOIN_RESULT
{% if is_incremental() %}
 WHERE NOT EXISTS (
  SELECT 1 
  FROM {{ this }} existing
  WHERE existing.QUALITY_NOTIFICATION_HK= JOIN_RESULT.QUALITY_NOTIFICATION_HK
 )
 {% endif %}
 QUALIFY ROW_NUMBER() OVER(PARTITION BY QUALITY_NOTIFICATION_BK, BKCC ORDER BY LOAD_DTS)=1
 {% if not is_incremental() %}
 union all
 
 SELECT MD5_BINARY(GR.VALUE) QUALITY_NOTIFICATION_HK
 , GR.VALUE AS QUALITY_NOTIFICATION_BK
 , CONVERT_TIMEZONE('UTC','1900-01-01') as LOAD_DTS 
 , DECODE(GR.VALUE, 0, 'GHOST RECORD-SYSTEM', -1, 'GHOST RECORD-nullkey-required', -2, 'GHOST RECORD-nullkey-optional') AS BKCC
 , 'USAZET.SNOWFLAKE.FBIN.DERIVED' AS REC_SRC
 FROM
 TABLE(strtok_split_to_table('0|-1|-2', '|')) AS GR
 {% endif %}