---- SRC LAYER ----
WITH
SRC_s              as ( SELECT WORK_CENTER_LOCATION_HK, WORK_CENTER_LOCATION_BK, BKCC, LOAD_DTS, REC_SRC FROM {{ ref('v_psa_stg_work_center_capacity__winn_sap') }} as SRC 
                        QUALIFY (ROW_NUMBER() OVER(PARTITION BY WORK_CENTER_LOCATION_HK ORDER BY LOAD_DTS ))=1 ),
SRC_WORK_LOCATION  as ( SELECT WORK_CENTER_LOCATION_HK, WORK_CENTER_LOCATION_BK, BKCC, LOAD_DTS, REC_SRC FROM {{ ref('v_psa_stg_work_center_location__winn_sap') }} as SRC 
                        QUALIFY (ROW_NUMBER() OVER(PARTITION BY WORK_CENTER_LOCATION_HK ORDER BY LOAD_DTS ))=1 ),
SRC_WORK_CAPACITY  as ( SELECT WORK_CENTER_LOCATION_HK, WORK_CENTER_LOCATION_BK, BKCC, LOAD_DTS, REC_SRC FROM {{ ref('v_psa_stg_work_center_capacity_allocation__winn_sap') }} as SRC 
                        QUALIFY (ROW_NUMBER() OVER(PARTITION BY WORK_CENTER_LOCATION_BK ORDER BY LOAD_DTS ))=1 )

/*
SRC_s              as ( SELECT * FROM STAGING.V_PSA_STG_WORK_CENTER_CAPACITY__WINN_SAP )
SRC_WORK_CAPACITY  as ( SELECT * FROM STAGING.v_psa_stg_work_center_capacity_allocation__winn_sap )
*/
---- LOGIC LAYER ----

, LOGIC_s as (
    SELECT
        WORK_CENTER_LOCATION_HK
      , WORK_CENTER_LOCATION_BK
      , BKCC
      , LOAD_DTS
      , REC_SRC
    FROM SRC_s
)

, LOGIC_WORK_LOCATION as (
    SELECT
        WORK_CENTER_LOCATION_HK
      , WORK_CENTER_LOCATION_BK
      , BKCC
      , LOAD_DTS
      , REC_SRC
    FROM SRC_WORK_LOCATION
)

, LOGIC_WORK_CAPACITY as (
    SELECT
        WORK_CENTER_LOCATION_HK
      , WORK_CENTER_LOCATION_BK
      , BKCC
      , LOAD_DTS
      , REC_SRC
    FROM SRC_WORK_CAPACITY
)
---- RENAME LAYER ----

, RENAME_s as (
    SELECT
        WORK_CENTER_LOCATION_HK
      , WORK_CENTER_LOCATION_BK
      , BKCC
      , LOAD_DTS
      , REC_SRC
    FROM LOGIC_s
)

, RENAME_WORK_LOCATION as (
    SELECT
        WORK_CENTER_LOCATION_HK
      , WORK_CENTER_LOCATION_BK
      , BKCC
      , LOAD_DTS
      , REC_SRC
    FROM LOGIC_WORK_LOCATION
)

, RENAME_WORK_CAPACITY as (
    SELECT
        WORK_CENTER_LOCATION_HK
      , WORK_CENTER_LOCATION_BK
      , BKCC
      , LOAD_DTS
      , REC_SRC
    FROM LOGIC_WORK_CAPACITY
)
---- FILTER LAYER ----

, FILTER_s as (
    SELECT *
    FROM RENAME_s
)

, FILTER_WORK_LOCATION as (
    SELECT *
    FROM RENAME_WORK_LOCATION
)

, FILTER_WORK_CAPACITY as (
    SELECT *
    FROM RENAME_WORK_CAPACITY
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM FILTER_s
    UNION ALL
    SELECT *
    FROM FILTER_WORK_LOCATION
    UNION ALL
    SELECT *
    FROM FILTER_WORK_CAPACITY
)

---- FINAL LAYER ----
SELECT
          WORK_CENTER_LOCATION_HK
        , WORK_CENTER_LOCATION_BK
        , BKCC
        , LOAD_DTS
        , REC_SRC
FROM JOIN_RESULT
{% if is_incremental() %}
WHERE NOT EXISTS (
    SELECT 1 
    FROM {{ this }} existing
    WHERE existing.WORK_CENTER_LOCATION_HK = JOIN_RESULT.WORK_CENTER_LOCATION_HK
)
{% endif %}
QUALIFY 1= ROW_NUMBER() OVER (PARTITION BY WORK_CENTER_LOCATION_HK ORDER BY LOAD_DTS)
{% if not is_incremental() %}

union all
SELECT 
MD5_BINARY(GR.VALUE) AS WORK_CENTER_LOCATION_HK,
GR.VALUE::text AS WORK_CENTER_LOCATION_BK,
DECODE(GR.VALUE, 0, 'GHOST RECORD-SYSTEM', -1, 'GHOST RECORD-nullkey-required', -2, 'GHOST RECORD-nullkey-optional') AS BKCC,
CONVERT_TIMEZONE('UTC','1900-01-01'::TIMESTAMP) AS LOAD_DTS,
'USAZET.SNOWFLAKE.FBIN.DERIVED' AS REC_SRC
FROM
TABLE(strtok_split_to_table('0|-1|-2', '|')) AS GR
{% endif %}