---- SRC LAYER ----
WITH
SRC_R              as ( SELECT BKCC, CHANGE_MASTER_BK, CHANGE_MASTER_HK, LOAD_DTS, REC_SRC FROM {{ ref('v_psa_stg_reservation_line__winn_sap') }} as SRC 
                        QUALIFY (ROW_NUMBER() OVER(PARTITION BY CHANGE_MASTER_HK ORDER BY LOAD_DTS ))=1 ),
SRC_PROD_ORDER     as ( SELECT BKCC, LOAD_DTS, REC_SRC, ROUTING_CHANGE_NUMBER_HK, ROUTING_CHANGE_NUMBER_BK, BOM_CHANGE_NUMBER_HK, BOM_CHANGE_NUMBER_BK, ENGINEERING_CHANGE_NUMBER_HK, ENGINEERING_CHANGE_NUMBER_BK FROM {{ ref('v_psa_stg_production_order_header__winn_sap') }} as SRC
                        QUALIFY (ROW_NUMBER() OVER(PARTITION BY ROUTING_CHANGE_NUMBER_BK, BOM_CHANGE_NUMBER_BK, ENGINEERING_CHANGE_NUMBER_BK ORDER BY LOAD_DTS ))=1 ),
SRC_TASKLIST_ITEM  as ( SELECT BKCC, CHANGE_MASTER_BK, CHANGE_MASTER_HK, LOAD_DTS, REC_SRC FROM {{ ref('v_psa_stg_tasklist_assignment__winn_sap') }} as SRC 
                        QUALIFY (ROW_NUMBER() OVER(PARTITION BY CHANGE_MASTER_HK ORDER BY LOAD_DTS ))=1 ),
SRC_TASKLIST_GROUP as ( SELECT BKCC, CHANGE_MASTER_BK, CHANGE_MASTER_HK, LOAD_DTS, REC_SRC FROM {{ ref('v_psa_stg_tasklist_group__winn_sap') }} as SRC 
                        QUALIFY (ROW_NUMBER() OVER(PARTITION BY CHANGE_MASTER_HK ORDER BY LOAD_DTS ))=1 )

/*
SRC_R              as ( SELECT * FROM STAGING.V_PSA_STG_RESERVATION_LINE__WINN_SAP )
,SRC_PROD_ORDER    as ( SELECT * FROM STAGING.v_psa_stg_production_order_header__winn_sap )
,SRC_TASKLIST_ITEM  as ( SELECT * FROM STAGING.v_psa_stg_tasklist_assignment__winn_sap )
,SRC_TASKLIST_GROUP  as ( SELECT * FROM STAGING.v_psa_stg_tasklist_group__winn_sap )
*/
---- LOGIC LAYER ----

, LOGIC_R as (
    SELECT
        CHANGE_MASTER_HK
      , CHANGE_MASTER_BK
      , BKCC
      , LOAD_DTS
      , REC_SRC
    FROM SRC_R
)

, LOGIC_PROD_ORDER as (
    SELECT
        ROUTING_CHANGE_NUMBER_HK as CHANGE_MASTER_HK
      , ROUTING_CHANGE_NUMBER_BK as CHANGE_MASTER_BK
      , BKCC
      , LOAD_DTS
      , REC_SRC
    FROM SRC_PROD_ORDER
)

, LOGIC_PROD_ORDER_2 as (
    SELECT
        BOM_CHANGE_NUMBER_HK as CHANGE_MASTER_HK
      , BOM_CHANGE_NUMBER_BK as CHANGE_MASTER_BK
      , BKCC
      , LOAD_DTS
      , REC_SRC
    FROM SRC_PROD_ORDER
)

, LOGIC_PROD_ORDER_3 as (
    SELECT
        ENGINEERING_CHANGE_NUMBER_HK as CHANGE_MASTER_HK
      , ENGINEERING_CHANGE_NUMBER_BK as CHANGE_MASTER_BK
      , BKCC
      , LOAD_DTS
      , REC_SRC
    FROM SRC_PROD_ORDER
)

, LOGIC_TASKLIST_ITEM as (
    SELECT
        CHANGE_MASTER_HK
      , CHANGE_MASTER_BK
      , BKCC
      , LOAD_DTS
      , REC_SRC
    FROM SRC_TASKLIST_ITEM
)

, LOGIC_TASKLIST_GROUP as (
    SELECT
        CHANGE_MASTER_HK
      , CHANGE_MASTER_BK
      , BKCC
      , LOAD_DTS
      , REC_SRC
    FROM SRC_TASKLIST_GROUP
)
---- RENAME LAYER ----

, RENAME_R as (
    SELECT
        CHANGE_MASTER_HK
      , CHANGE_MASTER_BK
      , BKCC
      , LOAD_DTS
      , REC_SRC
    FROM LOGIC_R
)

, RENAME_PROD_ORDER as (
    SELECT
        CHANGE_MASTER_HK
      , CHANGE_MASTER_BK
      , BKCC
      , LOAD_DTS
      , REC_SRC
    FROM LOGIC_PROD_ORDER
)

, RENAME_PROD_ORDER_2 as (
    SELECT
        CHANGE_MASTER_HK
      , CHANGE_MASTER_BK
      , BKCC
      , LOAD_DTS
      , REC_SRC
    FROM LOGIC_PROD_ORDER_2
)

, RENAME_PROD_ORDER_3 as (
    SELECT
        CHANGE_MASTER_HK
      , CHANGE_MASTER_BK
      , BKCC
      , LOAD_DTS
      , REC_SRC
    FROM LOGIC_PROD_ORDER_3
)

, RENAME_TASKLIST_ITEM as (
    SELECT
        CHANGE_MASTER_HK
      , CHANGE_MASTER_BK
      , BKCC
      , LOAD_DTS
      , REC_SRC
    FROM LOGIC_TASKLIST_ITEM
)

, RENAME_TASKLIST_GROUP as (
    SELECT
        CHANGE_MASTER_HK
      , CHANGE_MASTER_BK
      , BKCC
      , LOAD_DTS
      , REC_SRC
    FROM LOGIC_TASKLIST_GROUP
)
---- FILTER LAYER ----

, FILTER_R as (
    SELECT *
    FROM RENAME_R
)

, FILTER_PROD_ORDER as (
    SELECT *
    FROM RENAME_PROD_ORDER
)

, FILTER_PROD_ORDER_2 as (
    SELECT *
    FROM RENAME_PROD_ORDER_2
)

, FILTER_PROD_ORDER_3 as (
    SELECT *
    FROM RENAME_PROD_ORDER_3
)

, FILTER_TASKLIST_ITEM as (
    SELECT *
    FROM RENAME_TASKLIST_ITEM
)

, FILTER_TASKLIST_GROUP as (
    SELECT *
    FROM RENAME_TASKLIST_GROUP
)
---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM FILTER_R
    UNION ALL
    SELECT *
    FROM FILTER_PROD_ORDER
    UNION ALL
    SELECT *
    FROM FILTER_PROD_ORDER_2
    UNION ALL
    SELECT *
    FROM FILTER_PROD_ORDER_3
    UNION ALL
    SELECT *
    FROM FILTER_TASKLIST_ITEM
    UNION ALL
    SELECT *
    FROM FILTER_TASKLIST_GROUP
)

---- FINAL LAYER ----
SELECT
          CHANGE_MASTER_HK
        , CHANGE_MASTER_BK
        , BKCC
        , LOAD_DTS
        , REC_SRC
FROM JOIN_RESULT
{% if is_incremental() %}
WHERE NOT EXISTS (
    SELECT 1 
    FROM {{ this }} existing
    WHERE existing.CHANGE_MASTER_HK = JOIN_RESULT.CHANGE_MASTER_HK
)
{% endif %}
QUALIFY 1= ROW_NUMBER() OVER (PARTITION BY CHANGE_MASTER_HK ORDER BY LOAD_DTS)
{% if not is_incremental() %}

union all
SELECT 
MD5_BINARY(GR.VALUE) AS CHANGE_MASTER_HK,
GR.VALUE::text AS CHANGE_MASTER_BK,
DECODE(GR.VALUE, 0, 'GHOST RECORD-SYSTEM', -1, 'GHOST RECORD-nullkey-required', -2, 'GHOST RECORD-nullkey-optional') AS BKCC,
CONVERT_TIMEZONE('UTC','1900-01-01'::TIMESTAMP) AS LOAD_DTS,
'USAZET.SNOWFLAKE.FBIN.DERIVED' AS REC_SRC
FROM
TABLE(strtok_split_to_table('0|-1|-2', '|')) AS GR
{% endif %}