---- SRC LAYER ----
WITH
SRC_S              as ( SELECT * FROM {{ source('ml_ebs_ont', 'oe_order_lines_all') }} as SRC  ),
SRC_A              as ( SELECT * FROM {{ ref('ref_business_key_collision') }} as SRC  ),
SRC_S2             as ( SELECT * FROM {{ source('ml_ebs_ont', 'oe_order_headers_all') }} as SRC 
                        qualify 1 = row_number() over (partition by header_id order by psa_load_dts )  )

/*
SRC_S              as ( SELECT * FROM ml_ebs_ont.oe_order_lines_all )
, SRC_A              as ( SELECT * FROM raw_vault.ref_business_key_collision )
, SRC_S2             as ( SELECT * FROM ml_ebs_ont.oe_order_headers_all )
*/
---- LOGIC LAYER ----

, LOGIC_S as (
    SELECT
        to_char(LINE_ID)                                             as                                      ORDER_LINE_BK
      , LINE_ID
      , SERVICE_REFERENCE_TYPE_CODE
      , SUBINVENTORY
      , SOURCE_DOCUMENT_VERSION_NUMBER
      , UNIT_COST
      , PRICING_ATTRIBUTE1
      , PRICING_ATTRIBUTE2
      , INDUSTRY_ATTRIBUTE1
      , CUSTOMER_DOCK_CODE
      , INDUSTRY_ATTRIBUTE2
      , IB_CURRENT_LOCATION
      , INDUSTRY_ATTRIBUTE3
      , INDUSTRY_ATTRIBUTE4
      , INDUSTRY_ATTRIBUTE5
      , INDUSTRY_ATTRIBUTE6
      , INDUSTRY_ATTRIBUTE7
      , INDUSTRY_ATTRIBUTE8
      , PROGRAM_ID
      , CONTEXT
      , INDUSTRY_ATTRIBUTE9
      , SHIPMENT_PRIORITY_CODE
      , ARRIVAL_SET_ID
      , DELIVER_TO_ORG_ID
      , MFG_LEAD_TIME
      , BLANKET_VERSION_NUMBER
      , SHIPPING_INTERFACED_FLAG
      , UNIT_SELLING_PRICE
      , PAYMENT_TYPE_CODE
      , PRICING_ATTRIBUTE5
      , PRICING_ATTRIBUTE6
      , PRICING_ATTRIBUTE3
      , PRICING_ATTRIBUTE4
      , REVREC_COMMENTS
      , PRICING_ATTRIBUTE9
      , PRICING_ATTRIBUTE7
      , PRICING_ATTRIBUTE8
      , ATTRIBUTE3
      , ATTRIBUTE2
      , TP_ATTRIBUTE15
      , ORDER_QUANTITY_UOM
      , ATTRIBUTE1
      , TP_ATTRIBUTE14
      , FREIGHT_CARRIER_CODE
      , TP_ATTRIBUTE13
      , TP_ATTRIBUTE12
      , TP_ATTRIBUTE11
      , TP_ATTRIBUTE10
      , EARLIEST_SHIP_DATE
      , CALCULATE_PRICE_FLAG
      , ORDERED_QUANTITY_UOM2
      , ATTRIBUTE9
      , SCHEDULE_SHIP_DATE
      , ATTRIBUTE8
      , ATTRIBUTE7
      , ATTRIBUTE6
      , SHIP_SET_ID
      , ITEM_IDENTIFIER_TYPE
      , ATTRIBUTE5
      , SCHEDULE_ARRIVAL_DATE
      , ATTRIBUTE4
      , TRANSACTION_PHASE_CODE
      , CUST_PO_NUMBER
      , REFERENCE_CUSTOMER_TRX_LINE_ID
      , SHIP_TOLERANCE_BELOW
      , ORDERED_QUANTITY
      , TAX_DATE
      , ATTRIBUTE10
      , ORIG_SYS_DOCUMENT_REF
      , OPTION_FLAG
      , ATTRIBUTE14
      , ATTRIBUTE13
      , ATTRIBUTE12
      , ATTRIBUTE11
      , DROP_SHIP_FLAG
      , SHIP_TOLERANCE_ABOVE
      , UNIT_SELLING_PRICE_PER_PQTY
      , CONFIGURATION_ID
      , CONFIG_HEADER_ID
      , FLOW_STATUS_CODE
      , COMPONENT_SEQUENCE_ID
      , FULFILLED_FLAG
      , ACCOUNTING_RULE_DURATION
      , CONFIG_REV_NBR
      , CUSTOMER_JOB
      , ATTRIBUTE20
      , SHIP_MODEL_COMPLETE_FLAG
      , SERVICE_CREDIT_ELIGIBLE_CODE
      , CUSTOMER_TRX_LINE_ID
      , ITEM_REVISION
      , SOURCE_TYPE_CODE
      , REVREC_REFERENCE_DOCUMENT
      , CANCELLED_QUANTITY2
      , ACTUAL_SHIPMENT_DATE
      , SPLIT_BY
      , FULFILLMENT_DATE
      , SERVICE_END_DATE
      , SHIPPED_QUANTITY2
      , EXPLOSION_DATE
      , CUSTOMER_LINE_NUMBER
      , RLA_SCHEDULE_TYPE_CODE
      , RETURN_REASON_CODE
      , ATTRIBUTE18
      , SORT_ORDER
      , ATTRIBUTE17
      , ATTRIBUTE16
      , UNIT_SELLING_PERCENT
      , ATTRIBUTE15
      , ATTRIBUTE19
      , VEH_CUS_ITEM_CUM_KEY_ID
      , REVREC_SIGNATURE_DATE
      , FIRST_ACK_CODE
      , ORIG_SYS_LINE_REF
      , PRE_EXPLODED_FLAG
      , LINE_SET_ID
      , RETURN_CONTEXT
      , TAX_POINT_CODE
      , GLOBAL_ATTRIBUTE10
      , ORIGINAL_ITEM_IDENTIFIER_TYPE
      , PROMISE_DATE
      , USER_ITEM_DESCRIPTION
      , LOCK_CONTROL
      , REVREC_SIGNATURE
      , REFERENCE_HEADER_ID
      , INTMED_SHIP_TO_CONTACT_ID
      , ORIGINAL_INVENTORY_ITEM_ID
      , CUST_MODEL_SERIAL_NUMBER
      , CHANGE_SEQUENCE
      , TP_ATTRIBUTE9
      , UNIT_LIST_PRICE
      , RETROBILL_REQUEST_ID
      , SOLD_FROM_ORG_ID
      , EARLIEST_ACCEPTABLE_DATE
      , LAST_UPDATED_BY
      , PAYMENT_TERM_ID
      , ITEM_SUBSTITUTION_TYPE_CODE
      , UNIT_PERCENT_BASE_PRICE
      , PLANNING_PRIORITY
      , TP_ATTRIBUTE8
      , LATEST_ACCEPTABLE_DATE
      , TP_ATTRIBUTE7
      , TP_ATTRIBUTE6
      , SHIPPABLE_FLAG
      , TP_ATTRIBUTE5
      , TP_ATTRIBUTE4
      , TP_ATTRIBUTE3
      , TP_ATTRIBUTE2
      , TP_ATTRIBUTE1
      , END_CUSTOMER_CONTACT_ID
      , LINK_TO_LINE_ID
      , ORIGINAL_ORDERED_ITEM
      , UNIT_LIST_PERCENT
      , ORIGINAL_LIST_PRICE
      , SHIPPING_QUANTITY_UOM
      , RETURN_ATTRIBUTE8
      , RETURN_ATTRIBUTE7
      , SHIPPING_QUANTITY_UOM2
      , IB_OWNER
      , REVREC_IMPLICIT_FLAG
      , RETURN_ATTRIBUTE6
      , FIRST_ACK_DATE
      , RETURN_ATTRIBUTE5
      , SHIPPING_QUANTITY2
      , RETURN_ATTRIBUTE9
      , TAX_EXEMPT_NUMBER
      , RETURN_ATTRIBUTE4
      , LINE_CATEGORY_CODE
      , RETURN_ATTRIBUTE3
      , INDUSTRY_CONTEXT
      , RETURN_ATTRIBUTE2
      , SERVICE_PERIOD
      , REVENUE_AMOUNT
      , RETURN_ATTRIBUTE1
      , CREDIT_INVOICE_LINE_ID
      , MODEL_GROUP_NUMBER
      , INTMED_SHIP_TO_ORG_ID
      , TAX_EXEMPT_FLAG
      , SOLD_TO_ORG_ID
      , PRICE_REQUEST_CODE
      , RETURN_ATTRIBUTE14
      , SHIPPING_QUANTITY
      , RETURN_ATTRIBUTE15
      , CANCELLED_QUANTITY
      , PRICING_CONTEXT
      , DEMAND_BUCKET_TYPE_CODE
      , GLOBAL_ATTRIBUTE_CATEGORY
      , RETURN_ATTRIBUTE10
      , RETURN_ATTRIBUTE11
      , RETURN_ATTRIBUTE12
      , REQUEST_DATE
      , RETURN_ATTRIBUTE13
      , TAX_RATE
      , INDUSTRY_ATTRIBUTE26
      , INDUSTRY_ATTRIBUTE25
      , INDUSTRY_ATTRIBUTE24
      , ORG_ID
      , INDUSTRY_ATTRIBUTE23
      , INDUSTRY_ATTRIBUTE22
      , COMPONENT_NUMBER
      , INDUSTRY_ATTRIBUTE21
      , INDUSTRY_ATTRIBUTE20
      , SCHEDULE_STATUS_CODE
      , CANCELLED_FLAG
      , GLOBAL_ATTRIBUTE5
      , DELIVER_TO_CONTACT_ID
      , GLOBAL_ATTRIBUTE4
      , INVOICE_INTERFACE_STATUS_CODE
      , GLOBAL_ATTRIBUTE7
      , OVERRIDE_ATP_DATE_CODE
      , AUTO_SELECTED_QUANTITY
      , GLOBAL_ATTRIBUTE6
      , GLOBAL_ATTRIBUTE1
      , ORDER_FIRMED_DATE
      , GLOBAL_ATTRIBUTE3
      , GLOBAL_ATTRIBUTE2
      , UPGRADED_FLAG
      , TOP_MODEL_LINE_ID
      , GLOBAL_ATTRIBUTE9
      , INDUSTRY_ATTRIBUTE19
      , FOB_POINT_CODE
      , GLOBAL_ATTRIBUTE8
      , INDUSTRY_ATTRIBUTE18
      , BLANKET_LINE_NUMBER
      , MINISITE_ID
      , INDUSTRY_ATTRIBUTE17
      , TAX_EXEMPT_REASON_CODE
      , INDUSTRY_ATTRIBUTE16
      , ORDER_SOURCE_ID
      , ACTUAL_FULFILLMENT_DATE
      , TAX_VALUE
      , LAST_ACK_DATE
      , INDUSTRY_ATTRIBUTE30
      , BOOKED_FLAG
      , END_ITEM_UNIT_NUMBER
      , ACTUAL_ARRIVAL_DATE
      , AGREEMENT_ID
      , LATE_DEMAND_PENALTY_FACTOR
      , INVENTORY_ITEM_ID
      , BLANKET_NUMBER
      , CONFIG_DISPLAY_SEQUENCE
      , INDUSTRY_ATTRIBUTE29
      , INDUSTRY_ATTRIBUTE28
      , TASK_ID
      , INDUSTRY_ATTRIBUTE27
      , TP_CONTEXT
      , SHIP_TO_CONTACT_ID
      , REVREC_EXPIRATION_DAYS
      , CUSTOMER_PAYMENT_TERM_ID
      , REFERENCE_TYPE
      , IB_INSTALLED_AT_LOCATION
      , RE_SOURCE_FLAG
      , MODEL_REMNANT_FLAG
      , LINE_NUMBER
      , COMMITMENT_ID
      , CUSTOMER_PRODUCTION_LINE
      , OPTION_NUMBER
      , ITEM_TYPE_CODE
      , ORDERED_ITEM
      , PRICING_QUANTITY_UOM
      , SHIPPED_QUANTITY
      , BYPASS_SCH_FLAG
      , SALESREP_ID
      , PRICING_ATTRIBUTE10
      , CUSTOMER_ITEM_NET_PRICE
      , PROJECT_ID
      , ORDERED_QUANTITY2
      , INDUSTRY_ATTRIBUTE15
      , INDUSTRY_ATTRIBUTE14
      , INVOICE_TO_CONTACT_ID
      , INDUSTRY_ATTRIBUTE13
      , COMPONENT_CODE
      , INDUSTRY_ATTRIBUTE12
      , INDUSTRY_ATTRIBUTE11
      , UNIT_LIST_PRICE_PER_PQTY
      , INDUSTRY_ATTRIBUTE10
      , GLOBAL_ATTRIBUTE20
      , HEADER_ID
      , CUST_PRODUCTION_SEQ_NUM
      , GLOBAL_ATTRIBUTE17
      , GLOBAL_ATTRIBUTE18
      , GLOBAL_ATTRIBUTE15
      , GLOBAL_ATTRIBUTE16
      , GLOBAL_ATTRIBUTE13
      , GLOBAL_ATTRIBUTE14
      , GLOBAL_ATTRIBUTE11
      , SPLIT_FROM_LINE_ID
      , GLOBAL_ATTRIBUTE12
      , SOURCE_DOCUMENT_LINE_ID
      , ACCEPTED_QUANTITY
      , REVREC_EVENT_CODE
      , GLOBAL_ATTRIBUTE19
      , EQUIPMENT_ID
      , AUTHORIZED_TO_SHIP_FLAG
      , DELIVERY_LEAD_TIME
      , FULFILLED_QUANTITY2
      , VISIBLE_DEMAND_FLAG
      , LAST_UPDATE_DATE
      , SERVICE_REFERENCE_LINE_ID
      , INVOICED_QUANTITY
      , SHIP_TO_ORG_ID
      , INVOICE_TO_ORG_ID
      , SOURCE_DOCUMENT_TYPE_ID
      , ITEM_RELATIONSHIP_TYPE
      , SHIPMENT_NUMBER
      , SHIPPING_INSTRUCTIONS
      , CREATED_BY
      , SHIPPING_METHOD_CODE
      , SOURCE_DOCUMENT_ID
      , CUSTOMER_SHIPMENT_NUMBER
      , CREATION_DATE
      , PRICE_LIST_ID
      , INVOICING_RULE_ID
      , REFERENCE_LINE_ID
      , CHARGE_PERIODICITY_CODE
      , ATO_LINE_ID
      , PROGRAM_UPDATE_DATE
      , DEP_PLAN_REQUIRED_FLAG
      , SERVICE_TXN_COMMENTS
      , PROGRAM_APPLICATION_ID
      , PACKING_INSTRUCTIONS
      , END_CUSTOMER_ID
      , LINE_TYPE_ID
      , OPEN_FLAG
      , MFG_COMPONENT_SEQUENCE_ID
      , PREFERRED_GRADE
      , SHIP_FROM_ORG_ID
      , SALES_DOCUMENT_TYPE_CODE
      , SERVICE_TXN_REASON_CODE
      , FULFILLMENT_METHOD_CODE
      , REQUEST_ID
      , CONTINGENCY_ID
      , MARKETING_SOURCE_CODE_ID
      , SERVICE_REFERENCE_SYSTEM_ID
      , ORIGINAL_ORDERED_ITEM_ID
      , FULFILLED_QUANTITY
      , PRICING_DATE
      , SERVICE_START_DATE
      , OVER_SHIP_REASON_CODE
      , LAST_ACK_CODE
      , SERVICE_DURATION
      , SERVICE_NUMBER
      , LAST_UPDATE_LOGIN
      , ACCOUNTING_RULE_ID
      , END_CUSTOMER_SITE_USE_ID
      , FIRM_DEMAND_FLAG
      , ACCEPTED_BY
      , SERVICE_COTERMINATE_FLAG
      , DEMAND_CLASS_CODE
      , OVER_SHIP_RESOLVED_FLAG
      , ORIG_SYS_SHIPMENT_REF
      , ORDERED_ITEM_ID
      , TAX_CODE
      , FREIGHT_TERMS_CODE
      , PRICING_QUANTITY
      , _FIVETRAN_DELETED
      , _FIVETRAN_ID
      , _FIVETRAN_SYNCED
      , PSA_LOAD_DTS
      , PSA_RECORD_SOURCE
      , PSA_DELETE_IND
      , CONVERT_TIMEZONE('UTC', _FIVETRAN_SYNCED )                   as                                           LOAD_DTS
    FROM SRC_S
)

, LOGIC_A as (
    SELECT
        REC_SRC
      , BKCC
    FROM SRC_A
)

, LOGIC_S2 as (
    SELECT
        header_id                                                    as                                       S2_header_id
      , ORDER_NUMBER                                                 as                                    S2_ORDER_NUMBER
    FROM SRC_S2
)
---- RENAME LAYER ----

, RENAME_S as (
    SELECT
        ORDER_LINE_BK
      , LINE_ID
      , SERVICE_REFERENCE_TYPE_CODE
      , SUBINVENTORY
      , SOURCE_DOCUMENT_VERSION_NUMBER
      , UNIT_COST
      , PRICING_ATTRIBUTE1
      , PRICING_ATTRIBUTE2
      , INDUSTRY_ATTRIBUTE1
      , CUSTOMER_DOCK_CODE
      , INDUSTRY_ATTRIBUTE2
      , IB_CURRENT_LOCATION
      , INDUSTRY_ATTRIBUTE3
      , INDUSTRY_ATTRIBUTE4
      , INDUSTRY_ATTRIBUTE5
      , INDUSTRY_ATTRIBUTE6
      , INDUSTRY_ATTRIBUTE7
      , INDUSTRY_ATTRIBUTE8
      , PROGRAM_ID
      , CONTEXT
      , INDUSTRY_ATTRIBUTE9
      , SHIPMENT_PRIORITY_CODE
      , ARRIVAL_SET_ID
      , DELIVER_TO_ORG_ID
      , MFG_LEAD_TIME
      , BLANKET_VERSION_NUMBER
      , SHIPPING_INTERFACED_FLAG
      , UNIT_SELLING_PRICE
      , PAYMENT_TYPE_CODE
      , PRICING_ATTRIBUTE5
      , PRICING_ATTRIBUTE6
      , PRICING_ATTRIBUTE3
      , PRICING_ATTRIBUTE4
      , REVREC_COMMENTS
      , PRICING_ATTRIBUTE9
      , PRICING_ATTRIBUTE7
      , PRICING_ATTRIBUTE8
      , ATTRIBUTE3
      , ATTRIBUTE2
      , TP_ATTRIBUTE15
      , ORDER_QUANTITY_UOM
      , ATTRIBUTE1
      , TP_ATTRIBUTE14
      , FREIGHT_CARRIER_CODE
      , TP_ATTRIBUTE13
      , TP_ATTRIBUTE12
      , TP_ATTRIBUTE11
      , TP_ATTRIBUTE10
      , EARLIEST_SHIP_DATE
      , CALCULATE_PRICE_FLAG
      , ORDERED_QUANTITY_UOM2
      , ATTRIBUTE9
      , SCHEDULE_SHIP_DATE
      , ATTRIBUTE8
      , ATTRIBUTE7
      , ATTRIBUTE6
      , SHIP_SET_ID
      , ITEM_IDENTIFIER_TYPE
      , ATTRIBUTE5
      , SCHEDULE_ARRIVAL_DATE
      , ATTRIBUTE4
      , TRANSACTION_PHASE_CODE
      , CUST_PO_NUMBER
      , REFERENCE_CUSTOMER_TRX_LINE_ID
      , SHIP_TOLERANCE_BELOW
      , ORDERED_QUANTITY
      , TAX_DATE
      , ATTRIBUTE10
      , ORIG_SYS_DOCUMENT_REF
      , OPTION_FLAG
      , ATTRIBUTE14
      , ATTRIBUTE13
      , ATTRIBUTE12
      , ATTRIBUTE11
      , DROP_SHIP_FLAG
      , SHIP_TOLERANCE_ABOVE
      , UNIT_SELLING_PRICE_PER_PQTY
      , CONFIGURATION_ID
      , CONFIG_HEADER_ID
      , FLOW_STATUS_CODE
      , COMPONENT_SEQUENCE_ID
      , FULFILLED_FLAG
      , ACCOUNTING_RULE_DURATION
      , CONFIG_REV_NBR
      , CUSTOMER_JOB
      , ATTRIBUTE20
      , SHIP_MODEL_COMPLETE_FLAG
      , SERVICE_CREDIT_ELIGIBLE_CODE
      , CUSTOMER_TRX_LINE_ID
      , ITEM_REVISION
      , SOURCE_TYPE_CODE
      , REVREC_REFERENCE_DOCUMENT
      , CANCELLED_QUANTITY2
      , ACTUAL_SHIPMENT_DATE
      , SPLIT_BY
      , FULFILLMENT_DATE
      , SERVICE_END_DATE
      , SHIPPED_QUANTITY2
      , EXPLOSION_DATE
      , CUSTOMER_LINE_NUMBER
      , RLA_SCHEDULE_TYPE_CODE
      , RETURN_REASON_CODE
      , ATTRIBUTE18
      , SORT_ORDER
      , ATTRIBUTE17
      , ATTRIBUTE16
      , UNIT_SELLING_PERCENT
      , ATTRIBUTE15
      , ATTRIBUTE19
      , VEH_CUS_ITEM_CUM_KEY_ID
      , REVREC_SIGNATURE_DATE
      , FIRST_ACK_CODE
      , ORIG_SYS_LINE_REF
      , PRE_EXPLODED_FLAG
      , LINE_SET_ID
      , RETURN_CONTEXT
      , TAX_POINT_CODE
      , GLOBAL_ATTRIBUTE10
      , ORIGINAL_ITEM_IDENTIFIER_TYPE
      , PROMISE_DATE
      , USER_ITEM_DESCRIPTION
      , LOCK_CONTROL
      , REVREC_SIGNATURE
      , REFERENCE_HEADER_ID
      , INTMED_SHIP_TO_CONTACT_ID
      , ORIGINAL_INVENTORY_ITEM_ID
      , CUST_MODEL_SERIAL_NUMBER
      , CHANGE_SEQUENCE
      , TP_ATTRIBUTE9
      , UNIT_LIST_PRICE
      , RETROBILL_REQUEST_ID
      , SOLD_FROM_ORG_ID
      , EARLIEST_ACCEPTABLE_DATE
      , LAST_UPDATED_BY
      , PAYMENT_TERM_ID
      , ITEM_SUBSTITUTION_TYPE_CODE
      , UNIT_PERCENT_BASE_PRICE
      , PLANNING_PRIORITY
      , TP_ATTRIBUTE8
      , LATEST_ACCEPTABLE_DATE
      , TP_ATTRIBUTE7
      , TP_ATTRIBUTE6
      , SHIPPABLE_FLAG
      , TP_ATTRIBUTE5
      , TP_ATTRIBUTE4
      , TP_ATTRIBUTE3
      , TP_ATTRIBUTE2
      , TP_ATTRIBUTE1
      , END_CUSTOMER_CONTACT_ID
      , LINK_TO_LINE_ID
      , ORIGINAL_ORDERED_ITEM
      , UNIT_LIST_PERCENT
      , ORIGINAL_LIST_PRICE
      , SHIPPING_QUANTITY_UOM
      , RETURN_ATTRIBUTE8
      , RETURN_ATTRIBUTE7
      , SHIPPING_QUANTITY_UOM2
      , IB_OWNER
      , REVREC_IMPLICIT_FLAG
      , RETURN_ATTRIBUTE6
      , FIRST_ACK_DATE
      , RETURN_ATTRIBUTE5
      , SHIPPING_QUANTITY2
      , RETURN_ATTRIBUTE9
      , TAX_EXEMPT_NUMBER
      , RETURN_ATTRIBUTE4
      , LINE_CATEGORY_CODE
      , RETURN_ATTRIBUTE3
      , INDUSTRY_CONTEXT
      , RETURN_ATTRIBUTE2
      , SERVICE_PERIOD
      , REVENUE_AMOUNT
      , RETURN_ATTRIBUTE1
      , CREDIT_INVOICE_LINE_ID
      , MODEL_GROUP_NUMBER
      , INTMED_SHIP_TO_ORG_ID
      , TAX_EXEMPT_FLAG
      , SOLD_TO_ORG_ID
      , PRICE_REQUEST_CODE
      , RETURN_ATTRIBUTE14
      , SHIPPING_QUANTITY
      , RETURN_ATTRIBUTE15
      , CANCELLED_QUANTITY
      , PRICING_CONTEXT
      , DEMAND_BUCKET_TYPE_CODE
      , GLOBAL_ATTRIBUTE_CATEGORY
      , RETURN_ATTRIBUTE10
      , RETURN_ATTRIBUTE11
      , RETURN_ATTRIBUTE12
      , REQUEST_DATE
      , RETURN_ATTRIBUTE13
      , TAX_RATE
      , INDUSTRY_ATTRIBUTE26
      , INDUSTRY_ATTRIBUTE25
      , INDUSTRY_ATTRIBUTE24
      , ORG_ID
      , INDUSTRY_ATTRIBUTE23
      , INDUSTRY_ATTRIBUTE22
      , COMPONENT_NUMBER
      , INDUSTRY_ATTRIBUTE21
      , INDUSTRY_ATTRIBUTE20
      , SCHEDULE_STATUS_CODE
      , CANCELLED_FLAG
      , GLOBAL_ATTRIBUTE5
      , DELIVER_TO_CONTACT_ID
      , GLOBAL_ATTRIBUTE4
      , INVOICE_INTERFACE_STATUS_CODE
      , GLOBAL_ATTRIBUTE7
      , OVERRIDE_ATP_DATE_CODE
      , AUTO_SELECTED_QUANTITY
      , GLOBAL_ATTRIBUTE6
      , GLOBAL_ATTRIBUTE1
      , ORDER_FIRMED_DATE
      , GLOBAL_ATTRIBUTE3
      , GLOBAL_ATTRIBUTE2
      , UPGRADED_FLAG
      , TOP_MODEL_LINE_ID
      , GLOBAL_ATTRIBUTE9
      , INDUSTRY_ATTRIBUTE19
      , FOB_POINT_CODE
      , GLOBAL_ATTRIBUTE8
      , INDUSTRY_ATTRIBUTE18
      , BLANKET_LINE_NUMBER
      , MINISITE_ID
      , INDUSTRY_ATTRIBUTE17
      , TAX_EXEMPT_REASON_CODE
      , INDUSTRY_ATTRIBUTE16
      , ORDER_SOURCE_ID
      , ACTUAL_FULFILLMENT_DATE
      , TAX_VALUE
      , LAST_ACK_DATE
      , INDUSTRY_ATTRIBUTE30
      , BOOKED_FLAG
      , END_ITEM_UNIT_NUMBER
      , ACTUAL_ARRIVAL_DATE
      , AGREEMENT_ID
      , LATE_DEMAND_PENALTY_FACTOR
      , INVENTORY_ITEM_ID
      , BLANKET_NUMBER
      , CONFIG_DISPLAY_SEQUENCE
      , INDUSTRY_ATTRIBUTE29
      , INDUSTRY_ATTRIBUTE28
      , TASK_ID
      , INDUSTRY_ATTRIBUTE27
      , TP_CONTEXT
      , SHIP_TO_CONTACT_ID
      , REVREC_EXPIRATION_DAYS
      , CUSTOMER_PAYMENT_TERM_ID
      , REFERENCE_TYPE
      , IB_INSTALLED_AT_LOCATION
      , RE_SOURCE_FLAG
      , MODEL_REMNANT_FLAG
      , LINE_NUMBER
      , COMMITMENT_ID
      , CUSTOMER_PRODUCTION_LINE
      , OPTION_NUMBER
      , ITEM_TYPE_CODE
      , ORDERED_ITEM
      , PRICING_QUANTITY_UOM
      , SHIPPED_QUANTITY
      , BYPASS_SCH_FLAG
      , SALESREP_ID
      , PRICING_ATTRIBUTE10
      , CUSTOMER_ITEM_NET_PRICE
      , PROJECT_ID
      , ORDERED_QUANTITY2
      , INDUSTRY_ATTRIBUTE15
      , INDUSTRY_ATTRIBUTE14
      , INVOICE_TO_CONTACT_ID
      , INDUSTRY_ATTRIBUTE13
      , COMPONENT_CODE
      , INDUSTRY_ATTRIBUTE12
      , INDUSTRY_ATTRIBUTE11
      , UNIT_LIST_PRICE_PER_PQTY
      , INDUSTRY_ATTRIBUTE10
      , GLOBAL_ATTRIBUTE20
      , HEADER_ID
      , CUST_PRODUCTION_SEQ_NUM
      , GLOBAL_ATTRIBUTE17
      , GLOBAL_ATTRIBUTE18
      , GLOBAL_ATTRIBUTE15
      , GLOBAL_ATTRIBUTE16
      , GLOBAL_ATTRIBUTE13
      , GLOBAL_ATTRIBUTE14
      , GLOBAL_ATTRIBUTE11
      , SPLIT_FROM_LINE_ID
      , GLOBAL_ATTRIBUTE12
      , SOURCE_DOCUMENT_LINE_ID
      , ACCEPTED_QUANTITY
      , REVREC_EVENT_CODE
      , GLOBAL_ATTRIBUTE19
      , EQUIPMENT_ID
      , AUTHORIZED_TO_SHIP_FLAG
      , DELIVERY_LEAD_TIME
      , FULFILLED_QUANTITY2
      , VISIBLE_DEMAND_FLAG
      , LAST_UPDATE_DATE
      , SERVICE_REFERENCE_LINE_ID
      , INVOICED_QUANTITY
      , SHIP_TO_ORG_ID
      , INVOICE_TO_ORG_ID
      , SOURCE_DOCUMENT_TYPE_ID
      , ITEM_RELATIONSHIP_TYPE
      , SHIPMENT_NUMBER
      , SHIPPING_INSTRUCTIONS
      , CREATED_BY
      , SHIPPING_METHOD_CODE
      , SOURCE_DOCUMENT_ID
      , CUSTOMER_SHIPMENT_NUMBER
      , CREATION_DATE
      , PRICE_LIST_ID
      , INVOICING_RULE_ID
      , REFERENCE_LINE_ID
      , CHARGE_PERIODICITY_CODE
      , ATO_LINE_ID
      , PROGRAM_UPDATE_DATE
      , DEP_PLAN_REQUIRED_FLAG
      , SERVICE_TXN_COMMENTS
      , PROGRAM_APPLICATION_ID
      , PACKING_INSTRUCTIONS
      , END_CUSTOMER_ID
      , LINE_TYPE_ID
      , OPEN_FLAG
      , MFG_COMPONENT_SEQUENCE_ID
      , PREFERRED_GRADE
      , SHIP_FROM_ORG_ID
      , SALES_DOCUMENT_TYPE_CODE
      , SERVICE_TXN_REASON_CODE
      , FULFILLMENT_METHOD_CODE
      , REQUEST_ID
      , CONTINGENCY_ID
      , MARKETING_SOURCE_CODE_ID
      , SERVICE_REFERENCE_SYSTEM_ID
      , ORIGINAL_ORDERED_ITEM_ID
      , FULFILLED_QUANTITY
      , PRICING_DATE
      , SERVICE_START_DATE
      , OVER_SHIP_REASON_CODE
      , LAST_ACK_CODE
      , SERVICE_DURATION
      , SERVICE_NUMBER
      , LAST_UPDATE_LOGIN
      , ACCOUNTING_RULE_ID
      , END_CUSTOMER_SITE_USE_ID
      , FIRM_DEMAND_FLAG
      , ACCEPTED_BY
      , SERVICE_COTERMINATE_FLAG
      , DEMAND_CLASS_CODE
      , OVER_SHIP_RESOLVED_FLAG
      , ORIG_SYS_SHIPMENT_REF
      , ORDERED_ITEM_ID
      , TAX_CODE
      , FREIGHT_TERMS_CODE
      , PRICING_QUANTITY
      , _FIVETRAN_DELETED
      , _FIVETRAN_ID
      , _FIVETRAN_SYNCED
      , PSA_LOAD_DTS
      , PSA_RECORD_SOURCE
      , PSA_DELETE_IND
      , LOAD_DTS
    FROM LOGIC_S
)

, RENAME_A as (
    SELECT
        REC_SRC
      , BKCC
    FROM LOGIC_A
)

, RENAME_S2 as (
    SELECT
        S2_header_id
      , S2_ORDER_NUMBER
    FROM LOGIC_S2
)
---- FILTER LAYER ----

, FILTER_S as (
    SELECT *
    FROM RENAME_S
)

, FILTER_A as (
    SELECT *
    FROM RENAME_A
    WHERE rec_src = 'USWIOC.ORCL.EBSPRD.OE_ORDER_LINES_ALL'
)

, FILTER_S2 as (
    SELECT *
    FROM RENAME_S2
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM FILTER_S
    INNER JOIN FILTER_A
        ON '1' = '1'
    LEFT JOIN FILTER_S2
        ON header_id = s2_header_id
)

---- FINAL LAYER ----
SELECT
          ORDER_LINE_BK
        , LINE_ID
        , SERVICE_REFERENCE_TYPE_CODE
        , SUBINVENTORY
        , SOURCE_DOCUMENT_VERSION_NUMBER
        , UNIT_COST
        , PRICING_ATTRIBUTE1
        , PRICING_ATTRIBUTE2
        , INDUSTRY_ATTRIBUTE1
        , CUSTOMER_DOCK_CODE
        , INDUSTRY_ATTRIBUTE2
        , IB_CURRENT_LOCATION
        , INDUSTRY_ATTRIBUTE3
        , INDUSTRY_ATTRIBUTE4
        , INDUSTRY_ATTRIBUTE5
        , INDUSTRY_ATTRIBUTE6
        , INDUSTRY_ATTRIBUTE7
        , INDUSTRY_ATTRIBUTE8
        , PROGRAM_ID
        , CONTEXT
        , INDUSTRY_ATTRIBUTE9
        , SHIPMENT_PRIORITY_CODE
        , ARRIVAL_SET_ID
        , DELIVER_TO_ORG_ID
        , MFG_LEAD_TIME
        , BLANKET_VERSION_NUMBER
        , SHIPPING_INTERFACED_FLAG
        , UNIT_SELLING_PRICE
        , PAYMENT_TYPE_CODE
        , PRICING_ATTRIBUTE5
        , PRICING_ATTRIBUTE6
        , PRICING_ATTRIBUTE3
        , PRICING_ATTRIBUTE4
        , REVREC_COMMENTS
        , PRICING_ATTRIBUTE9
        , PRICING_ATTRIBUTE7
        , PRICING_ATTRIBUTE8
        , ATTRIBUTE3
        , ATTRIBUTE2
        , TP_ATTRIBUTE15
        , ORDER_QUANTITY_UOM
        , ATTRIBUTE1
        , TP_ATTRIBUTE14
        , FREIGHT_CARRIER_CODE
        , TP_ATTRIBUTE13
        , TP_ATTRIBUTE12
        , TP_ATTRIBUTE11
        , TP_ATTRIBUTE10
        , EARLIEST_SHIP_DATE
        , CALCULATE_PRICE_FLAG
        , ORDERED_QUANTITY_UOM2
        , ATTRIBUTE9
        , SCHEDULE_SHIP_DATE
        , ATTRIBUTE8
        , ATTRIBUTE7
        , ATTRIBUTE6
        , SHIP_SET_ID
        , ITEM_IDENTIFIER_TYPE
        , ATTRIBUTE5
        , SCHEDULE_ARRIVAL_DATE
        , ATTRIBUTE4
        , TRANSACTION_PHASE_CODE
        , CUST_PO_NUMBER
        , REFERENCE_CUSTOMER_TRX_LINE_ID
        , SHIP_TOLERANCE_BELOW
        , ORDERED_QUANTITY
        , TAX_DATE
        , ATTRIBUTE10
        , ORIG_SYS_DOCUMENT_REF
        , OPTION_FLAG
        , ATTRIBUTE14
        , ATTRIBUTE13
        , ATTRIBUTE12
        , ATTRIBUTE11
        , DROP_SHIP_FLAG
        , SHIP_TOLERANCE_ABOVE
        , UNIT_SELLING_PRICE_PER_PQTY
        , CONFIGURATION_ID
        , CONFIG_HEADER_ID
        , FLOW_STATUS_CODE
        , COMPONENT_SEQUENCE_ID
        , FULFILLED_FLAG
        , ACCOUNTING_RULE_DURATION
        , CONFIG_REV_NBR
        , CUSTOMER_JOB
        , ATTRIBUTE20
        , SHIP_MODEL_COMPLETE_FLAG
        , SERVICE_CREDIT_ELIGIBLE_CODE
        , CUSTOMER_TRX_LINE_ID
        , ITEM_REVISION
        , SOURCE_TYPE_CODE
        , REVREC_REFERENCE_DOCUMENT
        , CANCELLED_QUANTITY2
        , ACTUAL_SHIPMENT_DATE
        , SPLIT_BY
        , FULFILLMENT_DATE
        , SERVICE_END_DATE
        , SHIPPED_QUANTITY2
        , EXPLOSION_DATE
        , CUSTOMER_LINE_NUMBER
        , RLA_SCHEDULE_TYPE_CODE
        , RETURN_REASON_CODE
        , ATTRIBUTE18
        , SORT_ORDER
        , ATTRIBUTE17
        , ATTRIBUTE16
        , UNIT_SELLING_PERCENT
        , ATTRIBUTE15
        , ATTRIBUTE19
        , VEH_CUS_ITEM_CUM_KEY_ID
        , REVREC_SIGNATURE_DATE
        , FIRST_ACK_CODE
        , ORIG_SYS_LINE_REF
        , PRE_EXPLODED_FLAG
        , LINE_SET_ID
        , RETURN_CONTEXT
        , TAX_POINT_CODE
        , GLOBAL_ATTRIBUTE10
        , ORIGINAL_ITEM_IDENTIFIER_TYPE
        , PROMISE_DATE
        , USER_ITEM_DESCRIPTION
        , LOCK_CONTROL
        , REVREC_SIGNATURE
        , REFERENCE_HEADER_ID
        , INTMED_SHIP_TO_CONTACT_ID
        , ORIGINAL_INVENTORY_ITEM_ID
        , CUST_MODEL_SERIAL_NUMBER
        , CHANGE_SEQUENCE
        , TP_ATTRIBUTE9
        , UNIT_LIST_PRICE
        , RETROBILL_REQUEST_ID
        , SOLD_FROM_ORG_ID
        , EARLIEST_ACCEPTABLE_DATE
        , LAST_UPDATED_BY
        , PAYMENT_TERM_ID
        , ITEM_SUBSTITUTION_TYPE_CODE
        , UNIT_PERCENT_BASE_PRICE
        , PLANNING_PRIORITY
        , TP_ATTRIBUTE8
        , LATEST_ACCEPTABLE_DATE
        , TP_ATTRIBUTE7
        , TP_ATTRIBUTE6
        , SHIPPABLE_FLAG
        , TP_ATTRIBUTE5
        , TP_ATTRIBUTE4
        , TP_ATTRIBUTE3
        , TP_ATTRIBUTE2
        , TP_ATTRIBUTE1
        , END_CUSTOMER_CONTACT_ID
        , LINK_TO_LINE_ID
        , ORIGINAL_ORDERED_ITEM
        , UNIT_LIST_PERCENT
        , ORIGINAL_LIST_PRICE
        , SHIPPING_QUANTITY_UOM
        , RETURN_ATTRIBUTE8
        , RETURN_ATTRIBUTE7
        , SHIPPING_QUANTITY_UOM2
        , IB_OWNER
        , REVREC_IMPLICIT_FLAG
        , RETURN_ATTRIBUTE6
        , FIRST_ACK_DATE
        , RETURN_ATTRIBUTE5
        , SHIPPING_QUANTITY2
        , RETURN_ATTRIBUTE9
        , TAX_EXEMPT_NUMBER
        , RETURN_ATTRIBUTE4
        , LINE_CATEGORY_CODE
        , RETURN_ATTRIBUTE3
        , INDUSTRY_CONTEXT
        , RETURN_ATTRIBUTE2
        , SERVICE_PERIOD
        , REVENUE_AMOUNT
        , RETURN_ATTRIBUTE1
        , CREDIT_INVOICE_LINE_ID
        , MODEL_GROUP_NUMBER
        , INTMED_SHIP_TO_ORG_ID
        , TAX_EXEMPT_FLAG
        , SOLD_TO_ORG_ID
        , PRICE_REQUEST_CODE
        , RETURN_ATTRIBUTE14
        , SHIPPING_QUANTITY
        , RETURN_ATTRIBUTE15
        , CANCELLED_QUANTITY
        , PRICING_CONTEXT
        , DEMAND_BUCKET_TYPE_CODE
        , GLOBAL_ATTRIBUTE_CATEGORY
        , RETURN_ATTRIBUTE10
        , RETURN_ATTRIBUTE11
        , RETURN_ATTRIBUTE12
        , REQUEST_DATE
        , RETURN_ATTRIBUTE13
        , TAX_RATE
        , INDUSTRY_ATTRIBUTE26
        , INDUSTRY_ATTRIBUTE25
        , INDUSTRY_ATTRIBUTE24
        , ORG_ID
        , INDUSTRY_ATTRIBUTE23
        , INDUSTRY_ATTRIBUTE22
        , COMPONENT_NUMBER
        , INDUSTRY_ATTRIBUTE21
        , INDUSTRY_ATTRIBUTE20
        , SCHEDULE_STATUS_CODE
        , CANCELLED_FLAG
        , GLOBAL_ATTRIBUTE5
        , DELIVER_TO_CONTACT_ID
        , GLOBAL_ATTRIBUTE4
        , INVOICE_INTERFACE_STATUS_CODE
        , GLOBAL_ATTRIBUTE7
        , OVERRIDE_ATP_DATE_CODE
        , AUTO_SELECTED_QUANTITY
        , GLOBAL_ATTRIBUTE6
        , GLOBAL_ATTRIBUTE1
        , ORDER_FIRMED_DATE
        , GLOBAL_ATTRIBUTE3
        , GLOBAL_ATTRIBUTE2
        , UPGRADED_FLAG
        , TOP_MODEL_LINE_ID
        , GLOBAL_ATTRIBUTE9
        , INDUSTRY_ATTRIBUTE19
        , FOB_POINT_CODE
        , GLOBAL_ATTRIBUTE8
        , INDUSTRY_ATTRIBUTE18
        , BLANKET_LINE_NUMBER
        , MINISITE_ID
        , INDUSTRY_ATTRIBUTE17
        , TAX_EXEMPT_REASON_CODE
        , INDUSTRY_ATTRIBUTE16
        , ORDER_SOURCE_ID
        , ACTUAL_FULFILLMENT_DATE
        , TAX_VALUE
        , LAST_ACK_DATE
        , INDUSTRY_ATTRIBUTE30
        , BOOKED_FLAG
        , END_ITEM_UNIT_NUMBER
        , ACTUAL_ARRIVAL_DATE
        , AGREEMENT_ID
        , LATE_DEMAND_PENALTY_FACTOR
        , INVENTORY_ITEM_ID
        , BLANKET_NUMBER
        , CONFIG_DISPLAY_SEQUENCE
        , INDUSTRY_ATTRIBUTE29
        , INDUSTRY_ATTRIBUTE28
        , TASK_ID
        , INDUSTRY_ATTRIBUTE27
        , TP_CONTEXT
        , SHIP_TO_CONTACT_ID
        , REVREC_EXPIRATION_DAYS
        , CUSTOMER_PAYMENT_TERM_ID
        , REFERENCE_TYPE
        , IB_INSTALLED_AT_LOCATION
        , RE_SOURCE_FLAG
        , MODEL_REMNANT_FLAG
        , LINE_NUMBER
        , COMMITMENT_ID
        , CUSTOMER_PRODUCTION_LINE
        , OPTION_NUMBER
        , ITEM_TYPE_CODE
        , ORDERED_ITEM
        , PRICING_QUANTITY_UOM
        , SHIPPED_QUANTITY
        , BYPASS_SCH_FLAG
        , SALESREP_ID
        , PRICING_ATTRIBUTE10
        , CUSTOMER_ITEM_NET_PRICE
        , PROJECT_ID
        , ORDERED_QUANTITY2
        , INDUSTRY_ATTRIBUTE15
        , INDUSTRY_ATTRIBUTE14
        , INVOICE_TO_CONTACT_ID
        , INDUSTRY_ATTRIBUTE13
        , COMPONENT_CODE
        , INDUSTRY_ATTRIBUTE12
        , INDUSTRY_ATTRIBUTE11
        , UNIT_LIST_PRICE_PER_PQTY
        , INDUSTRY_ATTRIBUTE10
        , GLOBAL_ATTRIBUTE20
        , HEADER_ID
        , CUST_PRODUCTION_SEQ_NUM
        , GLOBAL_ATTRIBUTE17
        , GLOBAL_ATTRIBUTE18
        , GLOBAL_ATTRIBUTE15
        , GLOBAL_ATTRIBUTE16
        , GLOBAL_ATTRIBUTE13
        , GLOBAL_ATTRIBUTE14
        , GLOBAL_ATTRIBUTE11
        , SPLIT_FROM_LINE_ID
        , GLOBAL_ATTRIBUTE12
        , SOURCE_DOCUMENT_LINE_ID
        , ACCEPTED_QUANTITY
        , REVREC_EVENT_CODE
        , GLOBAL_ATTRIBUTE19
        , EQUIPMENT_ID
        , AUTHORIZED_TO_SHIP_FLAG
        , DELIVERY_LEAD_TIME
        , FULFILLED_QUANTITY2
        , VISIBLE_DEMAND_FLAG
        , LAST_UPDATE_DATE
        , SERVICE_REFERENCE_LINE_ID
        , INVOICED_QUANTITY
        , SHIP_TO_ORG_ID
        , INVOICE_TO_ORG_ID
        , SOURCE_DOCUMENT_TYPE_ID
        , ITEM_RELATIONSHIP_TYPE
        , SHIPMENT_NUMBER
        , SHIPPING_INSTRUCTIONS
        , CREATED_BY
        , SHIPPING_METHOD_CODE
        , SOURCE_DOCUMENT_ID
        , CUSTOMER_SHIPMENT_NUMBER
        , CREATION_DATE
        , PRICE_LIST_ID
        , INVOICING_RULE_ID
        , REFERENCE_LINE_ID
        , CHARGE_PERIODICITY_CODE
        , ATO_LINE_ID
        , PROGRAM_UPDATE_DATE
        , DEP_PLAN_REQUIRED_FLAG
        , SERVICE_TXN_COMMENTS
        , PROGRAM_APPLICATION_ID
        , PACKING_INSTRUCTIONS
        , END_CUSTOMER_ID
        , LINE_TYPE_ID
        , OPEN_FLAG
        , MFG_COMPONENT_SEQUENCE_ID
        , PREFERRED_GRADE
        , SHIP_FROM_ORG_ID
        , SALES_DOCUMENT_TYPE_CODE
        , SERVICE_TXN_REASON_CODE
        , FULFILLMENT_METHOD_CODE
        , REQUEST_ID
        , CONTINGENCY_ID
        , MARKETING_SOURCE_CODE_ID
        , SERVICE_REFERENCE_SYSTEM_ID
        , ORIGINAL_ORDERED_ITEM_ID
        , FULFILLED_QUANTITY
        , PRICING_DATE
        , SERVICE_START_DATE
        , OVER_SHIP_REASON_CODE
        , LAST_ACK_CODE
        , SERVICE_DURATION
        , SERVICE_NUMBER
        , LAST_UPDATE_LOGIN
        , ACCOUNTING_RULE_ID
        , END_CUSTOMER_SITE_USE_ID
        , FIRM_DEMAND_FLAG
        , ACCEPTED_BY
        , SERVICE_COTERMINATE_FLAG
        , DEMAND_CLASS_CODE
        , OVER_SHIP_RESOLVED_FLAG
        , ORIG_SYS_SHIPMENT_REF
        , ORDERED_ITEM_ID
        , TAX_CODE
        , FREIGHT_TERMS_CODE
        , PRICING_QUANTITY
        , _FIVETRAN_DELETED
        , _FIVETRAN_ID
        , _FIVETRAN_SYNCED
        , PSA_LOAD_DTS
        , PSA_RECORD_SOURCE
        , PSA_DELETE_IND
        , LOAD_DTS
        , REC_SRC
        , BKCC
        , to_char(coalesce(S2_ORDER_NUMBER,'-1'))                      as ORDER_HEADER_BK
        , MD5_BINARY(UPPER(CONCAT_WS('||',
          COALESCE(NULLIF(TRIM(CAST(LINE_ID as VARCHAR)),''), '^^')
        , COALESCE(NULLIF(TRIM(CAST(BKCC as VARCHAR)),''), '^^')
        ))) as ORDER_LINE_HK
        , MD5_BINARY(UPPER(CONCAT_WS('||',
          COALESCE(NULLIF(TRIM(CAST(ORDER_HEADER_BK as VARCHAR)),''), '^^')
        , COALESCE(NULLIF(TRIM(CAST(BKCC as VARCHAR)),''), '^^')
        ))) as ORDER_HEADER_HK
        , MD5_BINARY(UPPER(CONCAT_WS('||',
          COALESCE(NULLIF(TRIM(CAST(ORDER_HEADER_BK as VARCHAR)),''), '^^')
        , COALESCE(NULLIF(TRIM(CAST(LINE_ID as VARCHAR)),''), '^^')
        , COALESCE(NULLIF(TRIM(CAST(BKCC as VARCHAR)),''), '^^')
        ))) as ORDER_ORDER_LINE_HK
        , MD5_BINARY(UPPER(NULLIF(CONCAT(
              IFNULL(TRIM(SERVICE_REFERENCE_TYPE_CODE::text), '^^') 
            , '||', IFNULL(TRIM(SUBINVENTORY::text), '^^') 
            , '||', IFNULL(TRIM(SOURCE_DOCUMENT_VERSION_NUMBER::text), '^^') 
            , '||', IFNULL(TRIM(UNIT_COST::text), '^^') 
            , '||', IFNULL(TRIM(PRICING_ATTRIBUTE1::text), '^^') 
            , '||', IFNULL(TRIM(PRICING_ATTRIBUTE2::text), '^^') 
            , '||', IFNULL(TRIM(INDUSTRY_ATTRIBUTE1::text), '^^') 
            , '||', IFNULL(TRIM(CUSTOMER_DOCK_CODE::text), '^^') 
            , '||', IFNULL(TRIM(INDUSTRY_ATTRIBUTE2::text), '^^') 
            , '||', IFNULL(TRIM(IB_CURRENT_LOCATION::text), '^^') 
            , '||', IFNULL(TRIM(INDUSTRY_ATTRIBUTE3::text), '^^') 
            , '||', IFNULL(TRIM(INDUSTRY_ATTRIBUTE4::text), '^^') 
            , '||', IFNULL(TRIM(INDUSTRY_ATTRIBUTE5::text), '^^') 
            , '||', IFNULL(TRIM(INDUSTRY_ATTRIBUTE6::text), '^^') 
            , '||', IFNULL(TRIM(INDUSTRY_ATTRIBUTE7::text), '^^') 
            , '||', IFNULL(TRIM(INDUSTRY_ATTRIBUTE8::text), '^^') 
            , '||', IFNULL(TRIM(PROGRAM_ID::text), '^^') 
            , '||', IFNULL(TRIM(CONTEXT::text), '^^') 
            , '||', IFNULL(TRIM(INDUSTRY_ATTRIBUTE9::text), '^^') 
            , '||', IFNULL(TRIM(SHIPMENT_PRIORITY_CODE::text), '^^') 
            , '||', IFNULL(TRIM(ARRIVAL_SET_ID::text), '^^') 
            , '||', IFNULL(TRIM(DELIVER_TO_ORG_ID::text), '^^') 
            , '||', IFNULL(TRIM(MFG_LEAD_TIME::text), '^^') 
            , '||', IFNULL(TRIM(BLANKET_VERSION_NUMBER::text), '^^') 
            , '||', IFNULL(TRIM(SHIPPING_INTERFACED_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(UNIT_SELLING_PRICE::text), '^^') 
            , '||', IFNULL(TRIM(PAYMENT_TYPE_CODE::text), '^^') 
            , '||', IFNULL(TRIM(PRICING_ATTRIBUTE5::text), '^^') 
            , '||', IFNULL(TRIM(PRICING_ATTRIBUTE6::text), '^^') 
            , '||', IFNULL(TRIM(PRICING_ATTRIBUTE3::text), '^^') 
            , '||', IFNULL(TRIM(PRICING_ATTRIBUTE4::text), '^^') 
            , '||', IFNULL(TRIM(REVREC_COMMENTS::text), '^^') 
            , '||', IFNULL(TRIM(PRICING_ATTRIBUTE9::text), '^^') 
            , '||', IFNULL(TRIM(PRICING_ATTRIBUTE7::text), '^^') 
            , '||', IFNULL(TRIM(PRICING_ATTRIBUTE8::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE3::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE2::text), '^^') 
            , '||', IFNULL(TRIM(TP_ATTRIBUTE15::text), '^^') 
            , '||', IFNULL(TRIM(ORDER_QUANTITY_UOM::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE1::text), '^^') 
            , '||', IFNULL(TRIM(TP_ATTRIBUTE14::text), '^^') 
            , '||', IFNULL(TRIM(FREIGHT_CARRIER_CODE::text), '^^') 
            , '||', IFNULL(TRIM(TP_ATTRIBUTE13::text), '^^') 
            , '||', IFNULL(TRIM(TP_ATTRIBUTE12::text), '^^') 
            , '||', IFNULL(TRIM(TP_ATTRIBUTE11::text), '^^') 
            , '||', IFNULL(TRIM(TP_ATTRIBUTE10::text), '^^') 
            , '||', IFNULL(TRIM(EARLIEST_SHIP_DATE::text), '^^') 
            , '||', IFNULL(TRIM(CALCULATE_PRICE_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(ORDERED_QUANTITY_UOM2::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE9::text), '^^') 
            , '||', IFNULL(TRIM(SCHEDULE_SHIP_DATE::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE8::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE7::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE6::text), '^^') 
            , '||', IFNULL(TRIM(SHIP_SET_ID::text), '^^') 
            , '||', IFNULL(TRIM(ITEM_IDENTIFIER_TYPE::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE5::text), '^^') 
            , '||', IFNULL(TRIM(SCHEDULE_ARRIVAL_DATE::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE4::text), '^^') 
            , '||', IFNULL(TRIM(TRANSACTION_PHASE_CODE::text), '^^') 
            , '||', IFNULL(TRIM(CUST_PO_NUMBER::text), '^^') 
            , '||', IFNULL(TRIM(REFERENCE_CUSTOMER_TRX_LINE_ID::text), '^^') 
            , '||', IFNULL(TRIM(SHIP_TOLERANCE_BELOW::text), '^^') 
            , '||', IFNULL(TRIM(ORDERED_QUANTITY::text), '^^') 
            , '||', IFNULL(TRIM(TAX_DATE::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE10::text), '^^') 
            , '||', IFNULL(TRIM(ORIG_SYS_DOCUMENT_REF::text), '^^') 
            , '||', IFNULL(TRIM(OPTION_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE14::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE13::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE12::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE11::text), '^^') 
            , '||', IFNULL(TRIM(DROP_SHIP_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(SHIP_TOLERANCE_ABOVE::text), '^^') 
            , '||', IFNULL(TRIM(UNIT_SELLING_PRICE_PER_PQTY::text), '^^') 
            , '||', IFNULL(TRIM(CONFIGURATION_ID::text), '^^') 
            , '||', IFNULL(TRIM(CONFIG_HEADER_ID::text), '^^') 
            , '||', IFNULL(TRIM(FLOW_STATUS_CODE::text), '^^') 
            , '||', IFNULL(TRIM(COMPONENT_SEQUENCE_ID::text), '^^') 
            , '||', IFNULL(TRIM(FULFILLED_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(ACCOUNTING_RULE_DURATION::text), '^^') 
            , '||', IFNULL(TRIM(CONFIG_REV_NBR::text), '^^') 
            , '||', IFNULL(TRIM(CUSTOMER_JOB::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE20::text), '^^') 
            , '||', IFNULL(TRIM(SHIP_MODEL_COMPLETE_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(SERVICE_CREDIT_ELIGIBLE_CODE::text), '^^') 
            , '||', IFNULL(TRIM(CUSTOMER_TRX_LINE_ID::text), '^^') 
            , '||', IFNULL(TRIM(ITEM_REVISION::text), '^^') 
            , '||', IFNULL(TRIM(SOURCE_TYPE_CODE::text), '^^') 
            , '||', IFNULL(TRIM(REVREC_REFERENCE_DOCUMENT::text), '^^') 
            , '||', IFNULL(TRIM(CANCELLED_QUANTITY2::text), '^^') 
            , '||', IFNULL(TRIM(ACTUAL_SHIPMENT_DATE::text), '^^') 
            , '||', IFNULL(TRIM(SPLIT_BY::text), '^^') 
            , '||', IFNULL(TRIM(FULFILLMENT_DATE::text), '^^') 
            , '||', IFNULL(TRIM(SERVICE_END_DATE::text), '^^') 
            , '||', IFNULL(TRIM(SHIPPED_QUANTITY2::text), '^^') 
            , '||', IFNULL(TRIM(EXPLOSION_DATE::text), '^^') 
            , '||', IFNULL(TRIM(CUSTOMER_LINE_NUMBER::text), '^^') 
            , '||', IFNULL(TRIM(RLA_SCHEDULE_TYPE_CODE::text), '^^') 
            , '||', IFNULL(TRIM(RETURN_REASON_CODE::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE18::text), '^^') 
            , '||', IFNULL(TRIM(SORT_ORDER::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE17::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE16::text), '^^') 
            , '||', IFNULL(TRIM(UNIT_SELLING_PERCENT::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE15::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE19::text), '^^') 
            , '||', IFNULL(TRIM(VEH_CUS_ITEM_CUM_KEY_ID::text), '^^') 
            , '||', IFNULL(TRIM(REVREC_SIGNATURE_DATE::text), '^^') 
            , '||', IFNULL(TRIM(FIRST_ACK_CODE::text), '^^') 
            , '||', IFNULL(TRIM(ORIG_SYS_LINE_REF::text), '^^') 
            , '||', IFNULL(TRIM(PRE_EXPLODED_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(LINE_SET_ID::text), '^^') 
            , '||', IFNULL(TRIM(RETURN_CONTEXT::text), '^^') 
            , '||', IFNULL(TRIM(TAX_POINT_CODE::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE10::text), '^^') 
            , '||', IFNULL(TRIM(ORIGINAL_ITEM_IDENTIFIER_TYPE::text), '^^') 
            , '||', IFNULL(TRIM(PROMISE_DATE::text), '^^') 
            , '||', IFNULL(TRIM(USER_ITEM_DESCRIPTION::text), '^^') 
            , '||', IFNULL(TRIM(LOCK_CONTROL::text), '^^') 
            , '||', IFNULL(TRIM(REVREC_SIGNATURE::text), '^^') 
            , '||', IFNULL(TRIM(REFERENCE_HEADER_ID::text), '^^') 
            , '||', IFNULL(TRIM(INTMED_SHIP_TO_CONTACT_ID::text), '^^') 
            , '||', IFNULL(TRIM(ORIGINAL_INVENTORY_ITEM_ID::text), '^^') 
            , '||', IFNULL(TRIM(CUST_MODEL_SERIAL_NUMBER::text), '^^') 
            , '||', IFNULL(TRIM(CHANGE_SEQUENCE::text), '^^') 
            , '||', IFNULL(TRIM(TP_ATTRIBUTE9::text), '^^') 
            , '||', IFNULL(TRIM(UNIT_LIST_PRICE::text), '^^') 
            , '||', IFNULL(TRIM(RETROBILL_REQUEST_ID::text), '^^') 
            , '||', IFNULL(TRIM(SOLD_FROM_ORG_ID::text), '^^') 
            , '||', IFNULL(TRIM(EARLIEST_ACCEPTABLE_DATE::text), '^^') 
            , '||', IFNULL(TRIM(LAST_UPDATED_BY::text), '^^') 
            , '||', IFNULL(TRIM(PAYMENT_TERM_ID::text), '^^') 
            , '||', IFNULL(TRIM(ITEM_SUBSTITUTION_TYPE_CODE::text), '^^') 
            , '||', IFNULL(TRIM(UNIT_PERCENT_BASE_PRICE::text), '^^') 
            , '||', IFNULL(TRIM(PLANNING_PRIORITY::text), '^^') 
            , '||', IFNULL(TRIM(TP_ATTRIBUTE8::text), '^^') 
            , '||', IFNULL(TRIM(LATEST_ACCEPTABLE_DATE::text), '^^') 
            , '||', IFNULL(TRIM(TP_ATTRIBUTE7::text), '^^') 
            , '||', IFNULL(TRIM(TP_ATTRIBUTE6::text), '^^') 
            , '||', IFNULL(TRIM(SHIPPABLE_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(TP_ATTRIBUTE5::text), '^^') 
            , '||', IFNULL(TRIM(TP_ATTRIBUTE4::text), '^^') 
            , '||', IFNULL(TRIM(TP_ATTRIBUTE3::text), '^^') 
            , '||', IFNULL(TRIM(TP_ATTRIBUTE2::text), '^^') 
            , '||', IFNULL(TRIM(TP_ATTRIBUTE1::text), '^^') 
            , '||', IFNULL(TRIM(END_CUSTOMER_CONTACT_ID::text), '^^') 
            , '||', IFNULL(TRIM(LINK_TO_LINE_ID::text), '^^') 
            , '||', IFNULL(TRIM(ORIGINAL_ORDERED_ITEM::text), '^^') 
            , '||', IFNULL(TRIM(UNIT_LIST_PERCENT::text), '^^') 
            , '||', IFNULL(TRIM(ORIGINAL_LIST_PRICE::text), '^^') 
            , '||', IFNULL(TRIM(SHIPPING_QUANTITY_UOM::text), '^^') 
            , '||', IFNULL(TRIM(RETURN_ATTRIBUTE8::text), '^^') 
            , '||', IFNULL(TRIM(RETURN_ATTRIBUTE7::text), '^^') 
            , '||', IFNULL(TRIM(SHIPPING_QUANTITY_UOM2::text), '^^') 
            , '||', IFNULL(TRIM(IB_OWNER::text), '^^') 
            , '||', IFNULL(TRIM(REVREC_IMPLICIT_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(RETURN_ATTRIBUTE6::text), '^^') 
            , '||', IFNULL(TRIM(FIRST_ACK_DATE::text), '^^') 
            , '||', IFNULL(TRIM(RETURN_ATTRIBUTE5::text), '^^') 
            , '||', IFNULL(TRIM(SHIPPING_QUANTITY2::text), '^^') 
            , '||', IFNULL(TRIM(RETURN_ATTRIBUTE9::text), '^^') 
            , '||', IFNULL(TRIM(TAX_EXEMPT_NUMBER::text), '^^') 
            , '||', IFNULL(TRIM(RETURN_ATTRIBUTE4::text), '^^') 
            , '||', IFNULL(TRIM(LINE_CATEGORY_CODE::text), '^^') 
            , '||', IFNULL(TRIM(RETURN_ATTRIBUTE3::text), '^^') 
            , '||', IFNULL(TRIM(INDUSTRY_CONTEXT::text), '^^') 
            , '||', IFNULL(TRIM(RETURN_ATTRIBUTE2::text), '^^') 
            , '||', IFNULL(TRIM(SERVICE_PERIOD::text), '^^') 
            , '||', IFNULL(TRIM(REVENUE_AMOUNT::text), '^^') 
            , '||', IFNULL(TRIM(RETURN_ATTRIBUTE1::text), '^^') 
            , '||', IFNULL(TRIM(CREDIT_INVOICE_LINE_ID::text), '^^') 
            , '||', IFNULL(TRIM(MODEL_GROUP_NUMBER::text), '^^') 
            , '||', IFNULL(TRIM(INTMED_SHIP_TO_ORG_ID::text), '^^') 
            , '||', IFNULL(TRIM(TAX_EXEMPT_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(SOLD_TO_ORG_ID::text), '^^') 
            , '||', IFNULL(TRIM(PRICE_REQUEST_CODE::text), '^^') 
            , '||', IFNULL(TRIM(RETURN_ATTRIBUTE14::text), '^^') 
            , '||', IFNULL(TRIM(SHIPPING_QUANTITY::text), '^^') 
            , '||', IFNULL(TRIM(RETURN_ATTRIBUTE15::text), '^^') 
            , '||', IFNULL(TRIM(CANCELLED_QUANTITY::text), '^^') 
            , '||', IFNULL(TRIM(PRICING_CONTEXT::text), '^^') 
            , '||', IFNULL(TRIM(DEMAND_BUCKET_TYPE_CODE::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE_CATEGORY::text), '^^') 
            , '||', IFNULL(TRIM(RETURN_ATTRIBUTE10::text), '^^') 
            , '||', IFNULL(TRIM(RETURN_ATTRIBUTE11::text), '^^') 
            , '||', IFNULL(TRIM(RETURN_ATTRIBUTE12::text), '^^') 
            , '||', IFNULL(TRIM(REQUEST_DATE::text), '^^') 
            , '||', IFNULL(TRIM(RETURN_ATTRIBUTE13::text), '^^') 
            , '||', IFNULL(TRIM(TAX_RATE::text), '^^') 
            , '||', IFNULL(TRIM(INDUSTRY_ATTRIBUTE26::text), '^^') 
            , '||', IFNULL(TRIM(INDUSTRY_ATTRIBUTE25::text), '^^') 
            , '||', IFNULL(TRIM(INDUSTRY_ATTRIBUTE24::text), '^^') 
            , '||', IFNULL(TRIM(ORG_ID::text), '^^') 
            , '||', IFNULL(TRIM(INDUSTRY_ATTRIBUTE23::text), '^^') 
            , '||', IFNULL(TRIM(INDUSTRY_ATTRIBUTE22::text), '^^') 
            , '||', IFNULL(TRIM(COMPONENT_NUMBER::text), '^^') 
            , '||', IFNULL(TRIM(INDUSTRY_ATTRIBUTE21::text), '^^') 
            , '||', IFNULL(TRIM(INDUSTRY_ATTRIBUTE20::text), '^^') 
            , '||', IFNULL(TRIM(SCHEDULE_STATUS_CODE::text), '^^') 
            , '||', IFNULL(TRIM(CANCELLED_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE5::text), '^^') 
            , '||', IFNULL(TRIM(DELIVER_TO_CONTACT_ID::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE4::text), '^^') 
            , '||', IFNULL(TRIM(INVOICE_INTERFACE_STATUS_CODE::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE7::text), '^^') 
            , '||', IFNULL(TRIM(OVERRIDE_ATP_DATE_CODE::text), '^^') 
            , '||', IFNULL(TRIM(AUTO_SELECTED_QUANTITY::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE6::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE1::text), '^^') 
            , '||', IFNULL(TRIM(ORDER_FIRMED_DATE::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE3::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE2::text), '^^') 
            , '||', IFNULL(TRIM(UPGRADED_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(TOP_MODEL_LINE_ID::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE9::text), '^^') 
            , '||', IFNULL(TRIM(INDUSTRY_ATTRIBUTE19::text), '^^') 
            , '||', IFNULL(TRIM(FOB_POINT_CODE::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE8::text), '^^') 
            , '||', IFNULL(TRIM(INDUSTRY_ATTRIBUTE18::text), '^^') 
            , '||', IFNULL(TRIM(BLANKET_LINE_NUMBER::text), '^^') 
            , '||', IFNULL(TRIM(MINISITE_ID::text), '^^') 
            , '||', IFNULL(TRIM(INDUSTRY_ATTRIBUTE17::text), '^^') 
            , '||', IFNULL(TRIM(TAX_EXEMPT_REASON_CODE::text), '^^') 
            , '||', IFNULL(TRIM(INDUSTRY_ATTRIBUTE16::text), '^^') 
            , '||', IFNULL(TRIM(ORDER_SOURCE_ID::text), '^^') 
            , '||', IFNULL(TRIM(ACTUAL_FULFILLMENT_DATE::text), '^^') 
            , '||', IFNULL(TRIM(TAX_VALUE::text), '^^') 
            , '||', IFNULL(TRIM(LAST_ACK_DATE::text), '^^') 
            , '||', IFNULL(TRIM(INDUSTRY_ATTRIBUTE30::text), '^^') 
            , '||', IFNULL(TRIM(BOOKED_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(END_ITEM_UNIT_NUMBER::text), '^^') 
            , '||', IFNULL(TRIM(ACTUAL_ARRIVAL_DATE::text), '^^') 
            , '||', IFNULL(TRIM(AGREEMENT_ID::text), '^^') 
            , '||', IFNULL(TRIM(LATE_DEMAND_PENALTY_FACTOR::text), '^^') 
            , '||', IFNULL(TRIM(INVENTORY_ITEM_ID::text), '^^') 
            , '||', IFNULL(TRIM(BLANKET_NUMBER::text), '^^') 
            , '||', IFNULL(TRIM(CONFIG_DISPLAY_SEQUENCE::text), '^^') 
            , '||', IFNULL(TRIM(INDUSTRY_ATTRIBUTE29::text), '^^') 
            , '||', IFNULL(TRIM(INDUSTRY_ATTRIBUTE28::text), '^^') 
            , '||', IFNULL(TRIM(TASK_ID::text), '^^') 
            , '||', IFNULL(TRIM(INDUSTRY_ATTRIBUTE27::text), '^^') 
            , '||', IFNULL(TRIM(TP_CONTEXT::text), '^^') 
            , '||', IFNULL(TRIM(SHIP_TO_CONTACT_ID::text), '^^') 
            , '||', IFNULL(TRIM(REVREC_EXPIRATION_DAYS::text), '^^') 
            , '||', IFNULL(TRIM(CUSTOMER_PAYMENT_TERM_ID::text), '^^') 
            , '||', IFNULL(TRIM(REFERENCE_TYPE::text), '^^') 
            , '||', IFNULL(TRIM(IB_INSTALLED_AT_LOCATION::text), '^^') 
            , '||', IFNULL(TRIM(RE_SOURCE_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(MODEL_REMNANT_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(LINE_NUMBER::text), '^^') 
            , '||', IFNULL(TRIM(COMMITMENT_ID::text), '^^') 
            , '||', IFNULL(TRIM(CUSTOMER_PRODUCTION_LINE::text), '^^') 
            , '||', IFNULL(TRIM(OPTION_NUMBER::text), '^^') 
            , '||', IFNULL(TRIM(ITEM_TYPE_CODE::text), '^^') 
            , '||', IFNULL(TRIM(ORDERED_ITEM::text), '^^') 
            , '||', IFNULL(TRIM(PRICING_QUANTITY_UOM::text), '^^') 
            , '||', IFNULL(TRIM(SHIPPED_QUANTITY::text), '^^') 
            , '||', IFNULL(TRIM(BYPASS_SCH_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(SALESREP_ID::text), '^^') 
            , '||', IFNULL(TRIM(PRICING_ATTRIBUTE10::text), '^^') 
            , '||', IFNULL(TRIM(CUSTOMER_ITEM_NET_PRICE::text), '^^') 
            , '||', IFNULL(TRIM(PROJECT_ID::text), '^^') 
            , '||', IFNULL(TRIM(ORDERED_QUANTITY2::text), '^^') 
            , '||', IFNULL(TRIM(INDUSTRY_ATTRIBUTE15::text), '^^') 
            , '||', IFNULL(TRIM(INDUSTRY_ATTRIBUTE14::text), '^^') 
            , '||', IFNULL(TRIM(INVOICE_TO_CONTACT_ID::text), '^^') 
            , '||', IFNULL(TRIM(INDUSTRY_ATTRIBUTE13::text), '^^') 
            , '||', IFNULL(TRIM(COMPONENT_CODE::text), '^^') 
            , '||', IFNULL(TRIM(INDUSTRY_ATTRIBUTE12::text), '^^') 
            , '||', IFNULL(TRIM(INDUSTRY_ATTRIBUTE11::text), '^^') 
            , '||', IFNULL(TRIM(UNIT_LIST_PRICE_PER_PQTY::text), '^^') 
            , '||', IFNULL(TRIM(INDUSTRY_ATTRIBUTE10::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE20::text), '^^') 
            , '||', IFNULL(TRIM(HEADER_ID::text), '^^') 
            , '||', IFNULL(TRIM(CUST_PRODUCTION_SEQ_NUM::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE17::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE18::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE15::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE16::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE13::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE14::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE11::text), '^^') 
            , '||', IFNULL(TRIM(SPLIT_FROM_LINE_ID::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE12::text), '^^') 
            , '||', IFNULL(TRIM(SOURCE_DOCUMENT_LINE_ID::text), '^^') 
            , '||', IFNULL(TRIM(ACCEPTED_QUANTITY::text), '^^') 
            , '||', IFNULL(TRIM(REVREC_EVENT_CODE::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE19::text), '^^') 
            , '||', IFNULL(TRIM(EQUIPMENT_ID::text), '^^') 
            , '||', IFNULL(TRIM(AUTHORIZED_TO_SHIP_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(DELIVERY_LEAD_TIME::text), '^^') 
            , '||', IFNULL(TRIM(FULFILLED_QUANTITY2::text), '^^') 
            , '||', IFNULL(TRIM(VISIBLE_DEMAND_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(LAST_UPDATE_DATE::text), '^^') 
            , '||', IFNULL(TRIM(SERVICE_REFERENCE_LINE_ID::text), '^^') 
            , '||', IFNULL(TRIM(INVOICED_QUANTITY::text), '^^') 
            , '||', IFNULL(TRIM(SHIP_TO_ORG_ID::text), '^^') 
            , '||', IFNULL(TRIM(INVOICE_TO_ORG_ID::text), '^^') 
            , '||', IFNULL(TRIM(SOURCE_DOCUMENT_TYPE_ID::text), '^^') 
            , '||', IFNULL(TRIM(ITEM_RELATIONSHIP_TYPE::text), '^^') 
            , '||', IFNULL(TRIM(SHIPMENT_NUMBER::text), '^^') 
            , '||', IFNULL(TRIM(SHIPPING_INSTRUCTIONS::text), '^^') 
            , '||', IFNULL(TRIM(CREATED_BY::text), '^^') 
            , '||', IFNULL(TRIM(SHIPPING_METHOD_CODE::text), '^^') 
            , '||', IFNULL(TRIM(SOURCE_DOCUMENT_ID::text), '^^') 
            , '||', IFNULL(TRIM(CUSTOMER_SHIPMENT_NUMBER::text), '^^') 
            , '||', IFNULL(TRIM(CREATION_DATE::text), '^^') 
            , '||', IFNULL(TRIM(PRICE_LIST_ID::text), '^^') 
            , '||', IFNULL(TRIM(INVOICING_RULE_ID::text), '^^') 
            , '||', IFNULL(TRIM(REFERENCE_LINE_ID::text), '^^') 
            , '||', IFNULL(TRIM(CHARGE_PERIODICITY_CODE::text), '^^') 
            , '||', IFNULL(TRIM(ATO_LINE_ID::text), '^^') 
            , '||', IFNULL(TRIM(PROGRAM_UPDATE_DATE::text), '^^') 
            , '||', IFNULL(TRIM(DEP_PLAN_REQUIRED_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(SERVICE_TXN_COMMENTS::text), '^^') 
            , '||', IFNULL(TRIM(PROGRAM_APPLICATION_ID::text), '^^') 
            , '||', IFNULL(TRIM(PACKING_INSTRUCTIONS::text), '^^') 
            , '||', IFNULL(TRIM(END_CUSTOMER_ID::text), '^^') 
            , '||', IFNULL(TRIM(LINE_TYPE_ID::text), '^^') 
            , '||', IFNULL(TRIM(OPEN_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(MFG_COMPONENT_SEQUENCE_ID::text), '^^') 
            , '||', IFNULL(TRIM(PREFERRED_GRADE::text), '^^') 
            , '||', IFNULL(TRIM(SHIP_FROM_ORG_ID::text), '^^') 
            , '||', IFNULL(TRIM(SALES_DOCUMENT_TYPE_CODE::text), '^^') 
            , '||', IFNULL(TRIM(SERVICE_TXN_REASON_CODE::text), '^^') 
            , '||', IFNULL(TRIM(FULFILLMENT_METHOD_CODE::text), '^^') 
            , '||', IFNULL(TRIM(REQUEST_ID::text), '^^') 
            , '||', IFNULL(TRIM(CONTINGENCY_ID::text), '^^') 
            , '||', IFNULL(TRIM(MARKETING_SOURCE_CODE_ID::text), '^^') 
            , '||', IFNULL(TRIM(SERVICE_REFERENCE_SYSTEM_ID::text), '^^') 
            , '||', IFNULL(TRIM(ORIGINAL_ORDERED_ITEM_ID::text), '^^') 
            , '||', IFNULL(TRIM(FULFILLED_QUANTITY::text), '^^') 
            , '||', IFNULL(TRIM(PRICING_DATE::text), '^^') 
            , '||', IFNULL(TRIM(SERVICE_START_DATE::text), '^^') 
            , '||', IFNULL(TRIM(OVER_SHIP_REASON_CODE::text), '^^') 
            , '||', IFNULL(TRIM(LAST_ACK_CODE::text), '^^') 
            , '||', IFNULL(TRIM(SERVICE_DURATION::text), '^^') 
            , '||', IFNULL(TRIM(SERVICE_NUMBER::text), '^^') 
            , '||', IFNULL(TRIM(LAST_UPDATE_LOGIN::text), '^^') 
            , '||', IFNULL(TRIM(ACCOUNTING_RULE_ID::text), '^^') 
            , '||', IFNULL(TRIM(END_CUSTOMER_SITE_USE_ID::text), '^^') 
            , '||', IFNULL(TRIM(FIRM_DEMAND_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(ACCEPTED_BY::text), '^^') 
            , '||', IFNULL(TRIM(SERVICE_COTERMINATE_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(DEMAND_CLASS_CODE::text), '^^') 
            , '||', IFNULL(TRIM(OVER_SHIP_RESOLVED_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(ORIG_SYS_SHIPMENT_REF::text), '^^') 
            , '||', IFNULL(TRIM(ORDERED_ITEM_ID::text), '^^') 
            , '||', IFNULL(TRIM(TAX_CODE::text), '^^') 
            , '||', IFNULL(TRIM(FREIGHT_TERMS_CODE::text), '^^') 
            , '||', IFNULL(TRIM(PRICING_QUANTITY::text), '^^') 
            , '||', IFNULL(TRIM(_FIVETRAN_DELETED::text), '^^') 
            , '||', IFNULL(TRIM(PSA_DELETE_IND::text), '^^') 
        ), '^^||^^')))  as HASHDIFF
FROM JOIN_RESULT
