---- SRC LAYER ----
WITH
SRC_pb             as ( SELECT ADDITIONAL_PRODUCT_DISPLAY_COST, ADDITIONAL_TRADE_FUNDING_REQUEST, BASE_INVOICE_PRICE, BASE_MATERIAL, BASE_MATERIAL_BK, 
                        BASE_MATERIAL_HK, BASE_RETAIL_PRICE, BILLBACK_AMOUNT, BKCC, BUSINESS_UNIT, COGS_PER_UNIT, DIM_PROMOTION_HK, FUNDING_RATE, 
                        G2N_BEFORE_TRADE_RATE, KEY_ACCOUNT_GROUP_BK, KEY_ACCOUNT_GROUP_HK, LNK_ACCOUNT_BASE_MATERIAL_PROMOTION_HK, PAYMENT_TYPE, 
                        PLANNED_BASE_UNITS, PLANNED_BASE_UPSPW, PLANNED_CM_DOLLARS_BEFORE_TRADE, PLANNED_INCR_CM_DOLLARS, PLANNED_INCR_UNITS, 
                        PLANNED_PROMO_SPEND_DOLLARS, PLANNED_TRADE_SPEND, PROMOTION_ACCOUNT, PROMOTION_BK, PROMOTION_END_DATE_KEY, PROMOTION_END_DATE__YYYYMMDD, 
                        PROMOTION_END_FISCAL_WEEK__YYYYWW, PROMOTION_HK, PROMOTION_ID, PROMOTION_NAME, PROMOTION_OWNER, PROMOTION_REPORTING_CATEGORY, 
                        PROMOTION_REPORTING_CHANNEL, PROMOTION_REPORTING_CUSTOMER, PROMOTION_START_DATE_KEY, PROMOTION_START_DATE__YYYYMMDD, 
                        PROMOTION_START_FISCAL_WEEK__YYYYWW, PROMOTION_STATUS, PROMOTION_STORE_COUNT, PROMOTION_TYPE, PROMO_DOLLARS_PER_UNIT_EXC_FIXED, 
                        PROMO_RETAIL_PRICE, PURE_PLAY, REC_SRC, VARIABLE_COSTS_RATE FROM {{ ref('pb_promotion_effectiveness') }} as SRC  )

/*
SRC_pb             as ( SELECT * FROM bus_vault.pb_promotion_effectiveness )
*/
---- LOGIC LAYER ----

, LOGIC_pb as (
    SELECT
        DIM_PROMOTION_HK                                             as                                  DIM_PROMOTION_KEY
      , LNK_ACCOUNT_BASE_MATERIAL_PROMOTION_HK
      , KEY_ACCOUNT_GROUP_HK
      , BASE_MATERIAL_HK
      , PROMOTION_HK
      , BASE_MATERIAL_BK
      , KEY_ACCOUNT_GROUP_BK
      , PROMOTION_BK
      , PROMOTION_ID
      , PROMOTION_OWNER
      , PROMOTION_START_DATE_KEY
      , PROMOTION_END_DATE_KEY
      , PROMOTION_NAME
      , BASE_MATERIAL
      , BUSINESS_UNIT
      , PROMOTION_STATUS
      , PROMOTION_TYPE
      , PAYMENT_TYPE
      , PROMOTION_ACCOUNT
      , PURE_PLAY
      , PROMOTION_REPORTING_CATEGORY
      , PROMOTION_START_DATE__YYYYMMDD
      , PROMOTION_END_DATE__YYYYMMDD
      , PROMOTION_REPORTING_CUSTOMER
      , PROMOTION_REPORTING_CHANNEL
      , PROMOTION_START_FISCAL_WEEK__YYYYWW
      , PROMOTION_END_FISCAL_WEEK__YYYYWW
      , PROMOTION_STORE_COUNT
      , BASE_RETAIL_PRICE
      , PROMO_RETAIL_PRICE
      , PLANNED_BASE_UPSPW
      , FUNDING_RATE
      , ADDITIONAL_TRADE_FUNDING_REQUEST
      , ADDITIONAL_PRODUCT_DISPLAY_COST
      , BASE_INVOICE_PRICE
      , PLANNED_BASE_UNITS
      , PLANNED_INCR_UNITS
      , PROMO_DOLLARS_PER_UNIT_EXC_FIXED
      , BILLBACK_AMOUNT
      , PLANNED_PROMO_SPEND_DOLLARS
      , G2N_BEFORE_TRADE_RATE
      , COGS_PER_UNIT
      , VARIABLE_COSTS_RATE
      , PLANNED_CM_DOLLARS_BEFORE_TRADE
      , PLANNED_INCR_CM_DOLLARS
      , PLANNED_TRADE_SPEND
      , BKCC
      , REC_SRC
    FROM SRC_pb
)
---- RENAME LAYER ----

, RENAME_pb as (
    SELECT
        DIM_PROMOTION_KEY
      , LNK_ACCOUNT_BASE_MATERIAL_PROMOTION_HK
      , KEY_ACCOUNT_GROUP_HK
      , BASE_MATERIAL_HK
      , PROMOTION_HK
      , BASE_MATERIAL_BK
      , KEY_ACCOUNT_GROUP_BK
      , PROMOTION_BK
      , PROMOTION_ID
      , PROMOTION_OWNER
      , PROMOTION_START_DATE_KEY
      , PROMOTION_END_DATE_KEY
      , PROMOTION_NAME
      , BASE_MATERIAL
      , BUSINESS_UNIT
      , PROMOTION_STATUS
      , PROMOTION_TYPE
      , PAYMENT_TYPE
      , PROMOTION_ACCOUNT
      , PURE_PLAY
      , PROMOTION_REPORTING_CATEGORY
      , PROMOTION_START_DATE__YYYYMMDD
      , PROMOTION_END_DATE__YYYYMMDD
      , PROMOTION_REPORTING_CUSTOMER
      , PROMOTION_REPORTING_CHANNEL
      , PROMOTION_START_FISCAL_WEEK__YYYYWW
      , PROMOTION_END_FISCAL_WEEK__YYYYWW
      , PROMOTION_STORE_COUNT
      , BASE_RETAIL_PRICE
      , PROMO_RETAIL_PRICE
      , PLANNED_BASE_UPSPW
      , FUNDING_RATE
      , ADDITIONAL_TRADE_FUNDING_REQUEST
      , ADDITIONAL_PRODUCT_DISPLAY_COST
      , BASE_INVOICE_PRICE
      , PLANNED_BASE_UNITS
      , PLANNED_INCR_UNITS
      , PROMO_DOLLARS_PER_UNIT_EXC_FIXED
      , BILLBACK_AMOUNT
      , PLANNED_PROMO_SPEND_DOLLARS
      , G2N_BEFORE_TRADE_RATE
      , COGS_PER_UNIT
      , VARIABLE_COSTS_RATE
      , PLANNED_CM_DOLLARS_BEFORE_TRADE
      , PLANNED_INCR_CM_DOLLARS
      , PLANNED_TRADE_SPEND
      , BKCC
      , REC_SRC
    FROM LOGIC_pb
)
---- FILTER LAYER ----

, FILTER_pb as (
    SELECT *
    FROM RENAME_pb
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM FILTER_pb
)

---- FINAL LAYER ----
SELECT
          DIM_PROMOTION_KEY
        , LNK_ACCOUNT_BASE_MATERIAL_PROMOTION_HK
        , KEY_ACCOUNT_GROUP_HK
        , BASE_MATERIAL_HK
        , PROMOTION_HK
        , BASE_MATERIAL_BK
        , KEY_ACCOUNT_GROUP_BK
        , PROMOTION_BK
        , PROMOTION_ID
        , PROMOTION_OWNER
        , PROMOTION_START_DATE_KEY
        , PROMOTION_END_DATE_KEY
        , PROMOTION_NAME
        , BASE_MATERIAL
        , BUSINESS_UNIT
        , PROMOTION_STATUS
        , PROMOTION_TYPE
        , PAYMENT_TYPE
        , PROMOTION_ACCOUNT
        , PURE_PLAY
        , PROMOTION_REPORTING_CATEGORY
        , PROMOTION_START_DATE__YYYYMMDD
        , PROMOTION_END_DATE__YYYYMMDD
        , PROMOTION_REPORTING_CUSTOMER
        , PROMOTION_REPORTING_CHANNEL
        , PROMOTION_START_FISCAL_WEEK__YYYYWW
        , PROMOTION_END_FISCAL_WEEK__YYYYWW
        , PROMOTION_STORE_COUNT
        , BASE_RETAIL_PRICE
        , PROMO_RETAIL_PRICE
        , PLANNED_BASE_UPSPW
        , FUNDING_RATE
        , ADDITIONAL_TRADE_FUNDING_REQUEST
        , ADDITIONAL_PRODUCT_DISPLAY_COST
        , BASE_INVOICE_PRICE
        , PLANNED_BASE_UNITS
        , PLANNED_INCR_UNITS
        , PROMO_DOLLARS_PER_UNIT_EXC_FIXED
        , BILLBACK_AMOUNT
        , PLANNED_PROMO_SPEND_DOLLARS
        , G2N_BEFORE_TRADE_RATE
        , COGS_PER_UNIT
        , VARIABLE_COSTS_RATE
        , PLANNED_CM_DOLLARS_BEFORE_TRADE
        , PLANNED_INCR_CM_DOLLARS
        , PLANNED_TRADE_SPEND
        , BKCC
        , REC_SRC
FROM JOIN_RESULT
