---- SRC LAYER ----
WITH
SRC_SUP            as ( SELECT BKCC, MDM_BKCC, MDM_GOLDEN_RECORD, MDM_IS_DELETED, MDM_LEGAL_ENTITY_CODE, MDM_REC_SRC, MDM_SOURCE_LAST_RUN_DATE__YYYYMMDD, MDM_SUPPLIER_BK, MDM_SUPPLIER_SITE_BK, REC_SRC, SUPPLIER_BK, SUPPLIER_SITE_LEGAL_ENTITY_KEY FROM {{ ref('pb_supplier_site_legal_entity') }} as SRC  )

/*
SRC_SUP            as ( SELECT * FROM BUS_VAULT.pb_supplier_legal_entity )
*/
---- LOGIC LAYER ----

, LOGIC_SUP as (
    SELECT
        SUPPLIER_SITE_LEGAL_ENTITY_KEY
      , SUPPLIER_BK
      , MDM_SUPPLIER_BK
      , MDM_SUPPLIER_SITE_BK
      , MDM_GOLDEN_RECORD
      , MDM_LEGAL_ENTITY_CODE
      , MDM_SOURCE_LAST_RUN_DATE__YYYYMMDD
      , MDM_IS_DELETED
      , REC_SRC
      , BKCC
      , MDM_REC_SRC
      , MDM_BKCC
    FROM SRC_SUP
)
---- RENAME LAYER ----

, RENAME_SUP as (
    SELECT
        SUPPLIER_SITE_LEGAL_ENTITY_KEY
      , SUPPLIER_BK
      , MDM_SUPPLIER_BK
      , MDM_SUPPLIER_SITE_BK
      , MDM_GOLDEN_RECORD
      , MDM_LEGAL_ENTITY_CODE
      , MDM_SOURCE_LAST_RUN_DATE__YYYYMMDD
      , MDM_IS_DELETED
      , REC_SRC
      , BKCC
      , MDM_REC_SRC
      , MDM_BKCC
    FROM LOGIC_SUP
)
---- FILTER LAYER ----

, FILTER_SUP as (
    SELECT *
    FROM RENAME_SUP
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM FILTER_SUP
)

---- FINAL LAYER ----
SELECT
          SUPPLIER_SITE_LEGAL_ENTITY_KEY
        , SUPPLIER_BK
        , MDM_SUPPLIER_BK
        , MDM_SUPPLIER_SITE_BK
        , MDM_GOLDEN_RECORD
        , MDM_LEGAL_ENTITY_CODE
        , MDM_SOURCE_LAST_RUN_DATE__YYYYMMDD
        , MDM_IS_DELETED
        , REC_SRC
        , BKCC
        , MDM_REC_SRC
        , MDM_BKCC
FROM JOIN_RESULT
