---- SRC LAYER ----
WITH
SRC_P              as ( SELECT BKCC, CONTROLLING_AREA_HK, NAME_OF_THE_CONTROLLING_AREA , CURRENCY_KEY , CHART_OF_ACCOUNTS , FISCAL_YEAR_VARIANT , ALLOCATION_INDICATOR , LOGICAL_SYSTEM , COST_CENTER_DISTRIBUTION_METHOD_USING_ALE , LOGICAL_SYSTEM_FOR_MASTER_DATA_MAINTENANCE , STANDARD_HIERARCHY_FOR_COST_CENTERS , INDICATOR_REVENUE_MUST_BE_CONVERTED , PRODUCTIVE_INDICATOR_FOR_CONTROLLING_AREA , INDICATOR_RESERVE_NOT_USED_AT_PRESENT , OPERATING_CONCERN , DUMMY_PROFIT_CENTER , PROFIT_CENTER_AREA , PROFIT_CENTER_LEDGER , ELIMINATION_OF_INTERNAL_BUS_VOLUME_FOR_PROFIT_CENTER_ACCTG , INDICATOR_DIFFERENT_COMPANY_CODE_CURRENCY_IS_ALLOWED , STANDARD_HIERARCHY_AREA , INDICATOR_ALE_FOR_ACTIVE_BUSINESS_PROCESS_PROCESS_COSTS , COST_ELEMENT_FOR_VENDOR_DOWNPAYMENTS_WO_PURCHASE_ORD_REF , REVENUE_TYPE_FOR_DEBITOR_DOWNPAYMENTS_WITHOUT_SALES_ORD_REF , LOCAL_CURRENCY_FOR_PROFIT_CENTER_ACCOUNTING , CURRENCY_TYPE_OF_THE_PROFIT_CENTER_REPORT_CURRENC , STORE_TRANSACTION_CURRENCY_IN_EC_PCA , CURRENCY_TYPE_FOR_CONTROLLING_AREA , RECONCILIATION_LEDGER_ACTIVE , DOCUMENT_TYPE_FOR_RECONCIL_POSTINGS_FROM_RECONCIL_LEDGER , VALUATION_VIEW , VALUATION_VIEW_FOR_CALCULATION_BASE , REC_SRC, IS_DELETED  FROM {{ ref('pit_controlling_area_current') }} as SRC  )

/*
SRC_P              as ( SELECT * FROM RAW_VAULT.PIT_CONTROLLING_AREA_CURRENT )
*/
---- LOGIC LAYER ----

, LOGIC_P as (
    SELECT
        CONTROLLING_AREA_HK
      , NAME_OF_THE_CONTROLLING_AREA
      , CURRENCY_KEY
      , CHART_OF_ACCOUNTS
      , FISCAL_YEAR_VARIANT
      , ALLOCATION_INDICATOR
      , LOGICAL_SYSTEM
      , COST_CENTER_DISTRIBUTION_METHOD_USING_ALE
      , LOGICAL_SYSTEM_FOR_MASTER_DATA_MAINTENANCE
      , STANDARD_HIERARCHY_FOR_COST_CENTERS
      , INDICATOR_REVENUE_MUST_BE_CONVERTED
      , PRODUCTIVE_INDICATOR_FOR_CONTROLLING_AREA
      , INDICATOR_RESERVE_NOT_USED_AT_PRESENT
      , OPERATING_CONCERN
      , DUMMY_PROFIT_CENTER
      , PROFIT_CENTER_AREA
      , PROFIT_CENTER_LEDGER
      , ELIMINATION_OF_INTERNAL_BUS_VOLUME_FOR_PROFIT_CENTER_ACCTG
      , INDICATOR_DIFFERENT_COMPANY_CODE_CURRENCY_IS_ALLOWED
      , STANDARD_HIERARCHY_AREA
      , INDICATOR_ALE_FOR_ACTIVE_BUSINESS_PROCESS_PROCESS_COSTS
      , COST_ELEMENT_FOR_VENDOR_DOWNPAYMENTS_WO_PURCHASE_ORD_REF
      , REVENUE_TYPE_FOR_DEBITOR_DOWNPAYMENTS_WITHOUT_SALES_ORD_REF
      , LOCAL_CURRENCY_FOR_PROFIT_CENTER_ACCOUNTING
      , CURRENCY_TYPE_OF_THE_PROFIT_CENTER_REPORT_CURRENC
      , STORE_TRANSACTION_CURRENCY_IN_EC_PCA
      , CURRENCY_TYPE_FOR_CONTROLLING_AREA
      , RECONCILIATION_LEDGER_ACTIVE
      , DOCUMENT_TYPE_FOR_RECONCIL_POSTINGS_FROM_RECONCIL_LEDGER
      , VALUATION_VIEW
      , VALUATION_VIEW_FOR_CALCULATION_BASE
      , BKCC
      , REC_SRC
      , IS_DELETED
    FROM SRC_P
)
---- RENAME LAYER ----

, RENAME_P as (
    SELECT
        CONTROLLING_AREA_HK
      , NAME_OF_THE_CONTROLLING_AREA
      , CURRENCY_KEY
      , CHART_OF_ACCOUNTS
      , FISCAL_YEAR_VARIANT
      , ALLOCATION_INDICATOR
      , LOGICAL_SYSTEM
      , COST_CENTER_DISTRIBUTION_METHOD_USING_ALE
      , LOGICAL_SYSTEM_FOR_MASTER_DATA_MAINTENANCE
      , STANDARD_HIERARCHY_FOR_COST_CENTERS
      , INDICATOR_REVENUE_MUST_BE_CONVERTED
      , PRODUCTIVE_INDICATOR_FOR_CONTROLLING_AREA
      , INDICATOR_RESERVE_NOT_USED_AT_PRESENT
      , OPERATING_CONCERN
      , DUMMY_PROFIT_CENTER
      , PROFIT_CENTER_AREA
      , PROFIT_CENTER_LEDGER
      , ELIMINATION_OF_INTERNAL_BUS_VOLUME_FOR_PROFIT_CENTER_ACCTG
      , INDICATOR_DIFFERENT_COMPANY_CODE_CURRENCY_IS_ALLOWED
      , STANDARD_HIERARCHY_AREA
      , INDICATOR_ALE_FOR_ACTIVE_BUSINESS_PROCESS_PROCESS_COSTS
      , COST_ELEMENT_FOR_VENDOR_DOWNPAYMENTS_WO_PURCHASE_ORD_REF
      , REVENUE_TYPE_FOR_DEBITOR_DOWNPAYMENTS_WITHOUT_SALES_ORD_REF
      , LOCAL_CURRENCY_FOR_PROFIT_CENTER_ACCOUNTING
      , CURRENCY_TYPE_OF_THE_PROFIT_CENTER_REPORT_CURRENC
      , STORE_TRANSACTION_CURRENCY_IN_EC_PCA
      , CURRENCY_TYPE_FOR_CONTROLLING_AREA
      , RECONCILIATION_LEDGER_ACTIVE
      , DOCUMENT_TYPE_FOR_RECONCIL_POSTINGS_FROM_RECONCIL_LEDGER
      , VALUATION_VIEW
      , VALUATION_VIEW_FOR_CALCULATION_BASE
      , BKCC
      , REC_SRC
      , IS_DELETED
    FROM LOGIC_P
)
---- FILTER LAYER ----

, FILTER_P as (
    SELECT *
    FROM RENAME_P
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM FILTER_P
)

---- FINAL LAYER ----
SELECT
          CONTROLLING_AREA_HK
      , NAME_OF_THE_CONTROLLING_AREA
      , CURRENCY_KEY
      , CHART_OF_ACCOUNTS
      , FISCAL_YEAR_VARIANT
      , ALLOCATION_INDICATOR
      , LOGICAL_SYSTEM
      , COST_CENTER_DISTRIBUTION_METHOD_USING_ALE
      , LOGICAL_SYSTEM_FOR_MASTER_DATA_MAINTENANCE
      , STANDARD_HIERARCHY_FOR_COST_CENTERS
      , INDICATOR_REVENUE_MUST_BE_CONVERTED
      , PRODUCTIVE_INDICATOR_FOR_CONTROLLING_AREA
      , INDICATOR_RESERVE_NOT_USED_AT_PRESENT
      , OPERATING_CONCERN
      , DUMMY_PROFIT_CENTER
      , PROFIT_CENTER_AREA
      , PROFIT_CENTER_LEDGER
      , ELIMINATION_OF_INTERNAL_BUS_VOLUME_FOR_PROFIT_CENTER_ACCTG
      , INDICATOR_DIFFERENT_COMPANY_CODE_CURRENCY_IS_ALLOWED
      , STANDARD_HIERARCHY_AREA
      , INDICATOR_ALE_FOR_ACTIVE_BUSINESS_PROCESS_PROCESS_COSTS
      , COST_ELEMENT_FOR_VENDOR_DOWNPAYMENTS_WO_PURCHASE_ORD_REF
      , REVENUE_TYPE_FOR_DEBITOR_DOWNPAYMENTS_WITHOUT_SALES_ORD_REF
      , LOCAL_CURRENCY_FOR_PROFIT_CENTER_ACCOUNTING
      , CURRENCY_TYPE_OF_THE_PROFIT_CENTER_REPORT_CURRENC
      , STORE_TRANSACTION_CURRENCY_IN_EC_PCA
      , CURRENCY_TYPE_FOR_CONTROLLING_AREA
      , RECONCILIATION_LEDGER_ACTIVE
      , DOCUMENT_TYPE_FOR_RECONCIL_POSTINGS_FROM_RECONCIL_LEDGER
      , VALUATION_VIEW
      , VALUATION_VIEW_FOR_CALCULATION_BASE
      , BKCC
      , REC_SRC
      , IS_DELETED
FROM JOIN_RESULT

