---- SRC LAYER ----
WITH
SRC_SUP            as ( SELECT SUPPLIER_HK, SUPPLIER_BK, SUPPLIER_NAME_1, SUPPLIER_NAME_2, SUPPLIER_ALT_NAME, INDUSTRY_TYPE, SUPPLIER_TYPE, SUPPLIER_STATUS, PARENT_SUPPLIER_KEY, PARENT_SUPPLIER_NAME, ORGANIZATION_TYPE, SUPPLIER_NUMBER, INACTIVATION_DATE__YYYYMMDD, SOURCE_CREATION_DATE__YYYYMMDD, SOURCE_LAST_UPDATE_DATE__YYYYMMDD, IS_DELETED, REC_SRC, BKCC FROM {{ ref('pit_supplier_v2_current') }} as SRC  )

/*
SRC_SUP            as ( SELECT * FROM BUS_VAULT.pit_supplier_v2_current )
*/
---- LOGIC LAYER ----

, LOGIC_SUP as (
    SELECT
        SUPPLIER_HK
      , SUPPLIER_BK
      , SUPPLIER_NAME_1
      , SUPPLIER_NAME_2
      , SUPPLIER_ALT_NAME
      , INDUSTRY_TYPE
      , SUPPLIER_TYPE
      , SUPPLIER_STATUS
      , PARENT_SUPPLIER_KEY
      , PARENT_SUPPLIER_NAME
      , ORGANIZATION_TYPE
      , SUPPLIER_NUMBER
      , INACTIVATION_DATE__YYYYMMDD
      , SOURCE_CREATION_DATE__YYYYMMDD
      , SOURCE_LAST_UPDATE_DATE__YYYYMMDD
      , IS_DELETED
      , REC_SRC
      , BKCC
    FROM SRC_SUP
)
---- RENAME LAYER ----

, RENAME_SUP as (
    SELECT
        SUPPLIER_HK
      , SUPPLIER_BK
      , SUPPLIER_NAME_1
      , SUPPLIER_NAME_2
      , SUPPLIER_ALT_NAME
      , INDUSTRY_TYPE
      , SUPPLIER_TYPE
      , SUPPLIER_STATUS
      , PARENT_SUPPLIER_KEY
      , PARENT_SUPPLIER_NAME
      , ORGANIZATION_TYPE
      , SUPPLIER_NUMBER
      , INACTIVATION_DATE__YYYYMMDD
      , SOURCE_CREATION_DATE__YYYYMMDD
      , SOURCE_LAST_UPDATE_DATE__YYYYMMDD
      , IS_DELETED
      , REC_SRC
      , BKCC
    FROM LOGIC_SUP
)
---- FILTER LAYER ----

, FILTER_SUP as (
    SELECT *
    FROM RENAME_SUP
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM FILTER_SUP
)

---- FINAL LAYER ----
SELECT
          SUPPLIER_HK
        , SUPPLIER_BK
        , SUPPLIER_NAME_1
        , SUPPLIER_NAME_2
        , SUPPLIER_ALT_NAME
        , INDUSTRY_TYPE
        , SUPPLIER_TYPE
        , SUPPLIER_STATUS
        , PARENT_SUPPLIER_KEY
        , PARENT_SUPPLIER_NAME
        , ORGANIZATION_TYPE
        , SUPPLIER_NUMBER
        , INACTIVATION_DATE__YYYYMMDD
        , SOURCE_CREATION_DATE__YYYYMMDD
        , SOURCE_LAST_UPDATE_DATE__YYYYMMDD
        , IS_DELETED
        , REC_SRC
        , BKCC
FROM JOIN_RESULT
