---- SRC LAYER ----
WITH
SRC_P              as ( SELECT * FROM {{ ref('pit_sales_invoice_current') }} as SRC  )

/*
SRC_P              as ( SELECT * FROM RAW_VAULT.PIT_SALES_INVOICE_CURRENT )
*/
---- LOGIC LAYER ----

, LOGIC_P as (
    SELECT
        SALES_INVOICE_BK
      , BKCC
      , REC_SRC
      , BILLING_TYPE
      , BILLING_CATEGORY
      , DOCUMENT_CATEGORY
      , DOCUMENT_CURRENCY
      , SALES_ORGANIZATION
      , DISTRIBUTION_CHANNEL
      , SHIPPING_CONDITIONS
      , FISCAL_YEAR
      , POSTING_PERIOD
      , CUSTOMER_PRICE_GROUP
      , CUSTOMER_GROUP
      , SALES_DISTRICT
      , EXPORT_INDICATOR
      , ADDITIONAL_VALUE_DAYS
      , FIXED_VALUE_DATE_YYYYMMDD
      , DESTINATION_COUNTRY
      , REGION
      , COMPANY_CODE
      , TAX_CLASSIFICATION_1
      , TAX_CLASSIFICATION_2
      , TAX_CLASSIFICATION_3
      , TAX_CLASSIFICATION_4
      , TAX_CLASSIFICATION_5
      , TAX_CLASSIFICATION_6
      , TAX_CLASSIFICATION_7
      , TAX_CLASSIFICATION_8
      , TAX_CLASSIFICATION_9
      , ENTRY_TIME
      , INVOICE_CREATION_DATE__YYYYMMDD
      , PAYER
      , PARTY_SOLD_TO
      , DUNNING_AREA
      , STATISTICS_CURRENCY
      , INVOICE_UPDATE_DATE__YYYYMMDD
      , INVOICE_LIST_TYPE
      , EXCHANGE_RATE_TYPE
      , DUNNING_BLOCK
      , CREDIT_CONTROL_AREA
      , ASSIGNMENT_NUMBER
      , LOGICAL_SYSTEM
      , TRANSLATION_DATE__YYYYMMDD
      , PAYMENT_REFERENCE
      , PAYMENT_TERMS
      , NET_VALUE
      , VAT_REGISTRATION_NUMBER
      , DIVISION
      , TAX_DEPARTURE_COUNTRY
      , TAX_AMOUNT
      , IS_DELETED
    FROM SRC_P
)
---- RENAME LAYER ----

, RENAME_P as (
    SELECT
        SALES_INVOICE_BK
      , BKCC
      , REC_SRC
      , BILLING_TYPE
      , BILLING_CATEGORY
      , DOCUMENT_CATEGORY
      , DOCUMENT_CURRENCY
      , SALES_ORGANIZATION
      , DISTRIBUTION_CHANNEL
      , SHIPPING_CONDITIONS
      , FISCAL_YEAR
      , POSTING_PERIOD
      , CUSTOMER_PRICE_GROUP
      , CUSTOMER_GROUP
      , SALES_DISTRICT
      , EXPORT_INDICATOR
      , ADDITIONAL_VALUE_DAYS
      , FIXED_VALUE_DATE_YYYYMMDD
      , DESTINATION_COUNTRY
      , REGION
      , COMPANY_CODE
      , TAX_CLASSIFICATION_1
      , TAX_CLASSIFICATION_2
      , TAX_CLASSIFICATION_3
      , TAX_CLASSIFICATION_4
      , TAX_CLASSIFICATION_5
      , TAX_CLASSIFICATION_6
      , TAX_CLASSIFICATION_7
      , TAX_CLASSIFICATION_8
      , TAX_CLASSIFICATION_9
      , ENTRY_TIME
      , INVOICE_CREATION_DATE__YYYYMMDD
      , PAYER
      , PARTY_SOLD_TO
      , DUNNING_AREA
      , STATISTICS_CURRENCY
      , INVOICE_UPDATE_DATE__YYYYMMDD
      , INVOICE_LIST_TYPE
      , EXCHANGE_RATE_TYPE
      , DUNNING_BLOCK
      , CREDIT_CONTROL_AREA
      , ASSIGNMENT_NUMBER
      , LOGICAL_SYSTEM
      , TRANSLATION_DATE__YYYYMMDD
      , PAYMENT_REFERENCE
      , PAYMENT_TERMS
      , NET_VALUE
      , VAT_REGISTRATION_NUMBER
      , DIVISION
      , TAX_DEPARTURE_COUNTRY
      , TAX_AMOUNT
      , IS_DELETED
    FROM LOGIC_P
)
---- FILTER LAYER ----

, FILTER_P as (
    SELECT *
    FROM RENAME_P
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM FILTER_P
)

---- FINAL LAYER ----
SELECT
          SALES_INVOICE_BK
        , BKCC
        , REC_SRC
        , BILLING_TYPE
        , BILLING_CATEGORY
        , DOCUMENT_CATEGORY
        , DOCUMENT_CURRENCY
        , SALES_ORGANIZATION
        , DISTRIBUTION_CHANNEL
        , SHIPPING_CONDITIONS
        , FISCAL_YEAR
        , POSTING_PERIOD
        , CUSTOMER_PRICE_GROUP
        , CUSTOMER_GROUP
        , SALES_DISTRICT
        , EXPORT_INDICATOR
        , ADDITIONAL_VALUE_DAYS
        , FIXED_VALUE_DATE_YYYYMMDD
        , DESTINATION_COUNTRY
        , REGION
        , COMPANY_CODE
        , TAX_CLASSIFICATION_1
        , TAX_CLASSIFICATION_2
        , TAX_CLASSIFICATION_3
        , TAX_CLASSIFICATION_4
        , TAX_CLASSIFICATION_5
        , TAX_CLASSIFICATION_6
        , TAX_CLASSIFICATION_7
        , TAX_CLASSIFICATION_8
        , TAX_CLASSIFICATION_9
        , ENTRY_TIME
        , INVOICE_CREATION_DATE__YYYYMMDD
        , PAYER
        , PARTY_SOLD_TO
        , DUNNING_AREA
        , STATISTICS_CURRENCY
        , INVOICE_UPDATE_DATE__YYYYMMDD
        , INVOICE_LIST_TYPE
        , EXCHANGE_RATE_TYPE
        , DUNNING_BLOCK
        , CREDIT_CONTROL_AREA
        , ASSIGNMENT_NUMBER
        , LOGICAL_SYSTEM
        , TRANSLATION_DATE__YYYYMMDD
        , PAYMENT_REFERENCE
        , PAYMENT_TERMS
        , NET_VALUE
        , VAT_REGISTRATION_NUMBER
        , DIVISION
        , TAX_DEPARTURE_COUNTRY
        , TAX_AMOUNT
        , IS_DELETED
FROM JOIN_RESULT
