---- SRC LAYER ----
WITH
SRC_P              as ( SELECT * FROM {{ ref('pb_material_valuation') }} as SRC  )

---- LOGIC LAYER ----

, LOGIC_P as (
    SELECT
        ITEM_NUMBER
      , VALUATION_AREA
      , VALUATION_TYPE
      , TOTAL_VALUATED_STOCK
      , VALUE_OF_TOTAL_VALUATED_STOCK
      , PRICE_CONTROL_IND
      , AVG_PERIODIC_UNIT_PRICE
      , STD_PRICE
      , PRICE_UNIT
      , VALUATION_CLASS
      , CURR_PERIOD_FISCAL_YEAR__YYYYMMDD
      , CURR_POSTING_PERIOD
      , MAINTENANCE_STATUS
      , LAST_PRICE_CHANGE_DATE__YYYYMMDD
      , MAT_PRICE_DETERMINATION_CONTROL
      , MAT_LEDGER_ACTIVATED_MAT_LEVEL
      , PREV_TOTAL_VALUATED_STOCK
      , VAL_PREV_TOTAL_VALUATED_STOCK
      , PREV_YEAR_TOTAL_VALUATED_STOCK
      , VAL_PREV_YEAR_TOTAL_VALUATED_STOCK
      , IS_DELETED
      , BKCC
      , REC_SRC
    FROM SRC_P
)
---- RENAME LAYER ----

, RENAME_P as (
    SELECT
        ITEM_NUMBER
      , VALUATION_AREA
      , VALUATION_TYPE
      , TOTAL_VALUATED_STOCK
      , VALUE_OF_TOTAL_VALUATED_STOCK
      , PRICE_CONTROL_IND
      , AVG_PERIODIC_UNIT_PRICE
      , STD_PRICE
      , PRICE_UNIT
      , VALUATION_CLASS
      , CURR_PERIOD_FISCAL_YEAR__YYYYMMDD
      , CURR_POSTING_PERIOD
      , MAINTENANCE_STATUS
      , LAST_PRICE_CHANGE_DATE__YYYYMMDD
      , MAT_PRICE_DETERMINATION_CONTROL
      , MAT_LEDGER_ACTIVATED_MAT_LEVEL
      , PREV_TOTAL_VALUATED_STOCK
      , VAL_PREV_TOTAL_VALUATED_STOCK
      , PREV_YEAR_TOTAL_VALUATED_STOCK
      , VAL_PREV_YEAR_TOTAL_VALUATED_STOCK
      , IS_DELETED
      , BKCC
      , REC_SRC
    FROM LOGIC_P
)
---- FILTER LAYER ----

, FILTER_P as (
    SELECT *
    FROM RENAME_P
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM FILTER_P
)

---- FINAL LAYER ----
SELECT
        ITEM_NUMBER
      , VALUATION_AREA
      , VALUATION_TYPE
      , TOTAL_VALUATED_STOCK
      , VALUE_OF_TOTAL_VALUATED_STOCK
      , PRICE_CONTROL_IND
      , AVG_PERIODIC_UNIT_PRICE
      , STD_PRICE
      , PRICE_UNIT
      , VALUATION_CLASS
      , CURR_PERIOD_FISCAL_YEAR__YYYYMMDD
      , CURR_POSTING_PERIOD
      , MAINTENANCE_STATUS
      , LAST_PRICE_CHANGE_DATE__YYYYMMDD
      , MAT_PRICE_DETERMINATION_CONTROL
      , MAT_LEDGER_ACTIVATED_MAT_LEVEL
      , PREV_TOTAL_VALUATED_STOCK
      , VAL_PREV_TOTAL_VALUATED_STOCK
      , PREV_YEAR_TOTAL_VALUATED_STOCK
      , VAL_PREV_YEAR_TOTAL_VALUATED_STOCK
      , IS_DELETED
      , BKCC
      , REC_SRC
FROM JOIN_RESULT
