---- SRC LAYER ----
WITH
SRC_UOM            as ( SELECT * FROM {{ ref('pit_uom_details') }} as SRC  )

/*
SRC_UOM            as ( SELECT * FROM BUS_VAULT.pit_uom_details )
*/
---- LOGIC LAYER ----

, LOGIC_UOM as (
    SELECT
        UOM_BK
      , UNIT_OF_MEASURE_CODE
      , CLIENT_CODE
      , DISPLAY_DECIMALS
      , DIMENSION_CODE
      , CONVERSION_NUMERATOR
      , DECIMAL_PRECISION
      , CONVERSION_DENOMINATOR
      , ADDITIVE_CONSTANT
      , BASE10_EXPONENT
      , ISO_UNIT_CODE
      , SOURCE_SYSTEM_NAME
      , GLUE_CHANGE_TIMESTAMP
      , LANGUAGE_CODE
      , SHORT_DESCRIPTION
      , LONG_DESCRIPTION
      , PIT_REC_SRC
      , BKCC
    FROM SRC_UOM
)
---- RENAME LAYER ----

, RENAME_UOM as (
    SELECT
        UOM_BK
      , UNIT_OF_MEASURE_CODE
      , CLIENT_CODE
      , DISPLAY_DECIMALS
      , DIMENSION_CODE
      , CONVERSION_NUMERATOR
      , DECIMAL_PRECISION
      , CONVERSION_DENOMINATOR
      , ADDITIVE_CONSTANT
      , BASE10_EXPONENT
      , ISO_UNIT_CODE
      , SOURCE_SYSTEM_NAME
      , GLUE_CHANGE_TIMESTAMP
      , LANGUAGE_CODE
      , SHORT_DESCRIPTION
      , LONG_DESCRIPTION
      , PIT_REC_SRC
      , BKCC
    FROM LOGIC_UOM
)
---- FILTER LAYER ----

, FILTER_UOM as (
    SELECT *
    FROM RENAME_UOM
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM FILTER_UOM
)

---- FINAL LAYER ----
SELECT
          UOM_BK
        , UNIT_OF_MEASURE_CODE
        , CLIENT_CODE
        , DISPLAY_DECIMALS
        , DIMENSION_CODE
        , CONVERSION_NUMERATOR
        , DECIMAL_PRECISION
        , CONVERSION_DENOMINATOR
        , ADDITIVE_CONSTANT
        , BASE10_EXPONENT
        , ISO_UNIT_CODE
        , SOURCE_SYSTEM_NAME
        , GLUE_CHANGE_TIMESTAMP
        , LANGUAGE_CODE
        , SHORT_DESCRIPTION
        , LONG_DESCRIPTION
        , PIT_REC_SRC
        , BKCC
FROM JOIN_RESULT
