---- SRC LAYER ----
WITH
SRC_wc             as ( SELECT BKCC, CAPACITY_ID, CAPACITY_ID_WORK_CENTER_CAPACITY, CAPACITY_NUMBER, END_DATE__YYYYMMDD, PLANT, PLANT_BK, REC_SRC, SHORT_DESCRIPTION, START_DATE__YYYYMMDD, TASK_LIST_USAGE_KEY, WORK_CENTER, WORK_CENTER_BK, WORK_CENTER_CATEGORY, WORK_CENTER_HK, WORK_CENTER_LOCATION, WORK_CENTER_OWNER FROM {{ ref('pb_work_center') }} as SRC  )

/*
SRC_wc as ( SELECT * FROM BUS_VAULT.pb_work_center )
*/
---- LOGIC LAYER ---- 

, LOGIC_wc as (
    SELECT
        WORK_CENTER_HK
      , WORK_CENTER_BK
      , PLANT_BK
      , REC_SRC
      , BKCC
      , CAPACITY_ID
      , WORK_CENTER
      , PLANT
      , WORK_CENTER_CATEGORY
      , WORK_CENTER_LOCATION
      , WORK_CENTER_OWNER
      , TASK_LIST_USAGE_KEY
      , START_DATE__YYYYMMDD
      , END_DATE__YYYYMMDD
      , SHORT_DESCRIPTION
      , CAPACITY_ID_WORK_CENTER_CAPACITY
      , CAPACITY_NUMBER
    FROM SRC_wc
)
---- RENAME LAYER ----

, RENAME_wc as (
    SELECT
        WORK_CENTER_HK
      , WORK_CENTER_BK
      , PLANT_BK
      , REC_SRC
      , BKCC
      , CAPACITY_ID
      , WORK_CENTER
      , PLANT
      , WORK_CENTER_CATEGORY
      , WORK_CENTER_LOCATION
      , WORK_CENTER_OWNER
      , TASK_LIST_USAGE_KEY
      , START_DATE__YYYYMMDD
      , END_DATE__YYYYMMDD
      , SHORT_DESCRIPTION
      , CAPACITY_ID_WORK_CENTER_CAPACITY
      , CAPACITY_NUMBER
    FROM LOGIC_wc
)
---- FILTER LAYER ----

, FILTER_wc as (
    SELECT *
    FROM RENAME_wc
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM FILTER_wc
)

---- FINAL LAYER ----
SELECT
          WORK_CENTER_HK
        , WORK_CENTER_BK
        , PLANT_BK
        , REC_SRC
        , BKCC
        , CAPACITY_ID
        , WORK_CENTER
        , PLANT
        , WORK_CENTER_CATEGORY
        , WORK_CENTER_LOCATION
        , WORK_CENTER_OWNER
        , TASK_LIST_USAGE_KEY
        , START_DATE__YYYYMMDD
        , END_DATE__YYYYMMDD
        , SHORT_DESCRIPTION
        , CAPACITY_ID_WORK_CENTER_CAPACITY
        , CAPACITY_NUMBER
FROM JOIN_RESULT