---- SRC LAYER ----
WITH
SRC_PBCSA          as ( SELECT ACCOUNT_NAME, ACCOUNT_NUMBER, APO_FORECAST_ACCOUNT, APO_GROUP, BKCC, BUYING_GROUP_ID, CUSTOMER, CUSTOMER_BK, CUSTOMER_EARLY_SHIP_FLAG, CUSTOMER_HK, CUSTOMER_LEAD_DAYS, CUSTOMER_PRICE_ACCOUNT, CUSTOMER_SALES_ATTRIBUTES_KEY, DISTRIBUTION_CHANNEL, DISTRIBUTION_CHANNEL_BK, DISTRIBUTION_CHANNEL_HK, DIVISION, DIVISION_BK, DIVISION_HK, GROUP_KEY_ACCOUNT, KEY_ACCOUNT, REC_SRC, REPORTING_DISTRICT, SALES_GROUP, SALES_OFFICE, SALES_ORGANIZATION, SALES_ORGANIZATION_BK, SALES_ORGANIZATION_HK, TEAM_CODE FROM {{ ref('pb_customer_sales_attributes') }} as SRC  )

/*
SRC_PBCSA          as ( SELECT * FROM bus_vault.PB_CUSTOMER_SALES_ATTRIBUTES )
*/
---- LOGIC LAYER ----

, LOGIC_PBCSA as (
    SELECT
        CUSTOMER_SALES_ATTRIBUTES_KEY
      , CUSTOMER_HK
      , CUSTOMER_BK
      , CUSTOMER
      , SALES_ORGANIZATION_HK
      , SALES_ORGANIZATION_BK
      , SALES_ORGANIZATION
      , DISTRIBUTION_CHANNEL_HK
      , DISTRIBUTION_CHANNEL_BK
      , DISTRIBUTION_CHANNEL
      , DIVISION_HK
      , DIVISION_BK
      , DIVISION
      , ACCOUNT_NUMBER
      , ACCOUNT_NAME
      , REPORTING_DISTRICT
      , SALES_GROUP
      , SALES_OFFICE
      , CUSTOMER_PRICE_ACCOUNT
      , KEY_ACCOUNT
      , GROUP_KEY_ACCOUNT
      , BUYING_GROUP_ID
      , APO_GROUP
      , APO_FORECAST_ACCOUNT
      , CUSTOMER_LEAD_DAYS
      , CUSTOMER_EARLY_SHIP_FLAG
      , TEAM_CODE
      , REC_SRC
      , BKCC
    FROM SRC_PBCSA
)
---- RENAME LAYER ----

, RENAME_PBCSA as (
    SELECT
        CUSTOMER_SALES_ATTRIBUTES_KEY
      , CUSTOMER_HK
      , CUSTOMER_BK
      , CUSTOMER
      , SALES_ORGANIZATION_HK
      , SALES_ORGANIZATION_BK
      , SALES_ORGANIZATION
      , DISTRIBUTION_CHANNEL_HK
      , DISTRIBUTION_CHANNEL_BK
      , DISTRIBUTION_CHANNEL
      , DIVISION_HK
      , DIVISION_BK
      , DIVISION
      , ACCOUNT_NUMBER
      , ACCOUNT_NAME
      , REPORTING_DISTRICT
      , SALES_GROUP
      , SALES_OFFICE
      , CUSTOMER_PRICE_ACCOUNT
      , KEY_ACCOUNT
      , GROUP_KEY_ACCOUNT
      , BUYING_GROUP_ID
      , APO_GROUP
      , APO_FORECAST_ACCOUNT
      , CUSTOMER_LEAD_DAYS
      , CUSTOMER_EARLY_SHIP_FLAG
      , TEAM_CODE
      , REC_SRC
      , BKCC
    FROM LOGIC_PBCSA
)
---- FILTER LAYER ----

, FILTER_PBCSA as (
    SELECT *
    FROM RENAME_PBCSA
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM FILTER_PBCSA
)

---- FINAL LAYER ----
SELECT
          CUSTOMER_SALES_ATTRIBUTES_KEY
        , CUSTOMER_HK
        , CUSTOMER_BK
        , CUSTOMER
        , SALES_ORGANIZATION_HK
        , SALES_ORGANIZATION_BK
        , SALES_ORGANIZATION
        , DISTRIBUTION_CHANNEL_HK
        , DISTRIBUTION_CHANNEL_BK
        , DISTRIBUTION_CHANNEL
        , DIVISION_HK
        , DIVISION_BK
        , DIVISION
        , ACCOUNT_NUMBER
        , ACCOUNT_NAME
        , REPORTING_DISTRICT
        , SALES_GROUP
        , SALES_OFFICE
        , CUSTOMER_PRICE_ACCOUNT
        , KEY_ACCOUNT
        , GROUP_KEY_ACCOUNT
        , BUYING_GROUP_ID
        , APO_GROUP
        , APO_FORECAST_ACCOUNT
        , CUSTOMER_LEAD_DAYS
        , CUSTOMER_EARLY_SHIP_FLAG
        , TEAM_CODE
        , REC_SRC
        , BKCC
FROM JOIN_RESULT
