---- SRC LAYER ----
WITH
SRC_P_PO_HDR       as ( SELECT BKCC, BUYER_PLANNER_CODE, INCOTERMS_1, INCOTERMS_2, PO_CREATION_DATE, PO_CURRENCY, PO_DOCUMENT_TYPE, PO_HEADER_BK, PO_HEADER_DEL_IND, PO_HEADER_HK, PO_NUMBER, PO_PAYMENT_TERMS, PO_PROCESSING_STATUS, PURCHASING_ORG, REC_SRC, RELEASE_DATE FROM {{ ref('pit_po_header_current') }} as SRC  )

/*
SRC_P_PO_HDR       as ( SELECT * FROM BUS_VAULT.PIT_PO_HEADER_CURRENT )
*/
---- LOGIC LAYER ----

, LOGIC_P_PO_HDR as (
    SELECT
        PO_HEADER_HK
      , PO_HEADER_BK
      , PO_NUMBER
      , PO_DOCUMENT_TYPE
      , PO_HEADER_DEL_IND
      , PO_PROCESSING_STATUS
      , PO_CREATION_DATE
      , PO_PAYMENT_TERMS
      , INCOTERMS_1
      , INCOTERMS_2
      , PURCHASING_ORG
      , BUYER_PLANNER_CODE
      , PO_CURRENCY
      , RELEASE_DATE
      , REC_SRC
      , BKCC
    FROM SRC_P_PO_HDR
)
---- RENAME LAYER ----

, RENAME_P_PO_HDR as (
    SELECT
        PO_HEADER_HK
      , PO_HEADER_BK
      , PO_NUMBER
      , PO_DOCUMENT_TYPE
      , PO_HEADER_DEL_IND
      , PO_PROCESSING_STATUS
      , PO_CREATION_DATE
      , PO_PAYMENT_TERMS
      , INCOTERMS_1
      , INCOTERMS_2
      , PURCHASING_ORG
      , BUYER_PLANNER_CODE
      , PO_CURRENCY
      , RELEASE_DATE
      , REC_SRC
      , BKCC
    FROM LOGIC_P_PO_HDR
)
---- FILTER LAYER ----

, FILTER_P_PO_HDR as (
    SELECT *
    FROM RENAME_P_PO_HDR
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM FILTER_P_PO_HDR
)

---- FINAL LAYER ----
SELECT
          PO_HEADER_HK
        , PO_HEADER_BK
        , PO_NUMBER
        , PO_DOCUMENT_TYPE
        , PO_HEADER_DEL_IND
        , PO_PROCESSING_STATUS
        , PO_PAYMENT_TERMS
        , INCOTERMS_1
        , INCOTERMS_2
        , PURCHASING_ORG
        , BUYER_PLANNER_CODE
        , PO_CURRENCY
        , RELEASE_DATE 
        /* RELEASE_DATE - Applicable to Therma-Tru E21 only */
        , REC_SRC
        , BKCC
FROM JOIN_RESULT
