---- SRC LAYER ----
WITH
SRC_PB             as ( SELECT ACCOUNT_ID, BKCC, CANCELLATION_REASON, DEVICE_ACCOUNT_BK, DEVICE_LOCATION_BK, FIVETRAN_DELETED, FIVETRAN_SYNCED, IS_ACTIVE, PLAN_ID, PROVIDER_CUSTOMER_ID, PROVIDER_SUBSCRIPTION_ID, REC_SRC, RELATED_ENTITY, RELATED_ENTITY_ID, SOURCE_ID, STRIPE_PROVIDER_DATA, SUBSCRIPTION_PROVIDER FROM {{ ref('pb_device_account_location_subscription') }} as SRC  )

/*
SRC_PB             as ( SELECT * FROM BUS_VAULT.PB_DEVICE_ACCOUNT_LOCATION_SUBSCRIPTION )
*/
---- LOGIC LAYER ----

, LOGIC_PB as (
    SELECT
        DEVICE_ACCOUNT_BK
      , DEVICE_LOCATION_BK
      , BKCC
      , REC_SRC
      , ACCOUNT_ID
      , FIVETRAN_SYNCED
      , RELATED_ENTITY_ID
      , IS_ACTIVE
      , PROVIDER_CUSTOMER_ID
      , SOURCE_ID
      , SUBSCRIPTION_PROVIDER
      , PROVIDER_SUBSCRIPTION_ID
      , STRIPE_PROVIDER_DATA
      , PLAN_ID
      , RELATED_ENTITY
      , FIVETRAN_DELETED
      , CANCELLATION_REASON
    FROM SRC_PB
)
---- RENAME LAYER ----

, RENAME_PB as (
    SELECT
        DEVICE_ACCOUNT_BK
      , DEVICE_LOCATION_BK
      , BKCC
      , REC_SRC
      , ACCOUNT_ID
      , FIVETRAN_SYNCED
      , RELATED_ENTITY_ID
      , IS_ACTIVE
      , PROVIDER_CUSTOMER_ID
      , SOURCE_ID
      , SUBSCRIPTION_PROVIDER
      , PROVIDER_SUBSCRIPTION_ID
      , STRIPE_PROVIDER_DATA
      , PLAN_ID
      , RELATED_ENTITY
      , FIVETRAN_DELETED
      , CANCELLATION_REASON
    FROM LOGIC_PB
)
---- FILTER LAYER ----

, FILTER_PB as (
    SELECT *
    FROM RENAME_PB
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM FILTER_PB
)

---- FINAL LAYER ----
SELECT
          DEVICE_ACCOUNT_BK
        , DEVICE_LOCATION_BK
        , BKCC
        , REC_SRC
        , ACCOUNT_ID
        , FIVETRAN_SYNCED
        , RELATED_ENTITY_ID
        , IS_ACTIVE
        , PROVIDER_CUSTOMER_ID
        , SOURCE_ID
        , SUBSCRIPTION_PROVIDER
        , PROVIDER_SUBSCRIPTION_ID
        , STRIPE_PROVIDER_DATA
        , PLAN_ID
        , RELATED_ENTITY
        , FIVETRAN_DELETED
        , CANCELLATION_REASON
FROM JOIN_RESULT
