---- SRC LAYER ----
WITH
SRC_P              as ( SELECT * FROM {{ ref('pit_gl_header_current') }} as SRC  )

/*
SRC_P              as ( SELECT * FROM RAW_VAULT.PIT_GL_HEADER_CURRENT )
*/
---- LOGIC LAYER ----

, LOGIC_P as (
    SELECT
        GENERAL_LEDGER_HK
      , COMPANY_CODE_BK
      , ACCOUNTING_DOC_NUM_BK
      , FISCAL_YEAR_BK
      , ACCOUNTING_YEAR
      , DOCUMENT_TYPE
      , DOCUMENT_DATE__YYYYMMDD
      , POSTING_DATE__YYYYMMDD
      , FISCAL_PERIOD
      , DAY_OF_ENTRY__YYYYMMDD
      , TIME_OF_ENTRY
      , REFERENCE_DOCUMENT_NUMBER
      , CURRENCY_KEY
      , EXCHANGE_RATE
      , REFERENCE_TRANSACTION_TYPE
      , REFERENCE_KEY
      , EXCHANGE_RATE_2ND_CURRENCY
      , EXCHANGE_RATE_TYPE
      , CURRENCY_TYPE_2
      , EXCHANGE_RATE_TYPE_2
      , DOCUMENT_HEADER_TEXT
      , DOCUMENT_STATUS
      , REVERSAL_DOCUMENT_NUMBER
      , FISCAL_YEAR_REVERSAL_DOCUMENT__YYYY
      , REVERSAL_REASON
      , BKCC
      , REC_SRC
      , IS_DELETED
    FROM SRC_P
)
---- RENAME LAYER ----

, RENAME_P as (
    SELECT
        GENERAL_LEDGER_HK
      , COMPANY_CODE_BK
      , ACCOUNTING_DOC_NUM_BK
      , FISCAL_YEAR_BK
      , ACCOUNTING_YEAR
      , DOCUMENT_TYPE
      , DOCUMENT_DATE__YYYYMMDD
      , POSTING_DATE__YYYYMMDD
      , FISCAL_PERIOD
      , DAY_OF_ENTRY__YYYYMMDD
      , TIME_OF_ENTRY
      , REFERENCE_DOCUMENT_NUMBER
      , CURRENCY_KEY
      , EXCHANGE_RATE
      , REFERENCE_TRANSACTION_TYPE
      , REFERENCE_KEY
      , EXCHANGE_RATE_2ND_CURRENCY
      , EXCHANGE_RATE_TYPE
      , CURRENCY_TYPE_2
      , EXCHANGE_RATE_TYPE_2
      , DOCUMENT_HEADER_TEXT
      , DOCUMENT_STATUS
      , REVERSAL_DOCUMENT_NUMBER
      , FISCAL_YEAR_REVERSAL_DOCUMENT__YYYY
      , REVERSAL_REASON
      , BKCC
      , REC_SRC
      , IS_DELETED
    FROM LOGIC_P
)
---- FILTER LAYER ----

, FILTER_P as (
    SELECT *
    FROM RENAME_P
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM FILTER_P
)

---- FINAL LAYER ----
SELECT
          GENERAL_LEDGER_HK
        , COMPANY_CODE_BK
        , ACCOUNTING_DOC_NUM_BK
        , FISCAL_YEAR_BK
        , ACCOUNTING_YEAR
        , DOCUMENT_TYPE
        , DOCUMENT_DATE__YYYYMMDD
        , POSTING_DATE__YYYYMMDD
        , FISCAL_PERIOD
        , DAY_OF_ENTRY__YYYYMMDD
        , TIME_OF_ENTRY
        , REFERENCE_DOCUMENT_NUMBER
        , CURRENCY_KEY
        , EXCHANGE_RATE
        , REFERENCE_TRANSACTION_TYPE
        , REFERENCE_KEY
        , EXCHANGE_RATE_2ND_CURRENCY
        , EXCHANGE_RATE_TYPE
        , CURRENCY_TYPE_2
        , EXCHANGE_RATE_TYPE_2
        , DOCUMENT_HEADER_TEXT
        , DOCUMENT_STATUS
        , REVERSAL_DOCUMENT_NUMBER
        , FISCAL_YEAR_REVERSAL_DOCUMENT__YYYY
        , REVERSAL_REASON
        , BKCC
        , REC_SRC
        , IS_DELETED
FROM JOIN_RESULT
