---- SRC LAYER ----
WITH
SRC_D              as ( SELECT ACTIVITY_TYPE, BASE_QUANTITY,  OPERATION_DESCRIPTION, BKCC, CHANGE_NUMBER, CONTROL_KEY, DELETION_INDICATOR, INTERNAL_OPERATION_NUMBER, OPERATION_NUMBER, REC_SRC, SETUP_TIME, STANDARD_VALUE, TASKLIST_GROUP_KEY, TASKLIST_OPERATION_BK, TASKLIST_OPERATION_HK, TASKLIST_TYPE, VALID_FROM_DATE__YYYYMMDD,  REF_TASKLIST_TYPE , REF_TASKLIST_GROUP , REF_GROUP_COUNTER  FROM {{ ref('pit_tasklist_operation') }} as SRC  )

/*
SRC_D              as ( SELECT * FROM BUS_VAULT.pit_tasklist_operation )
*/
---- LOGIC LAYER ----

, LOGIC_D as (
    SELECT
        REC_SRC
      , TASKLIST_OPERATION_BK
      , TASKLIST_OPERATION_HK
      , TASKLIST_TYPE
      , TASKLIST_GROUP_KEY
      , INTERNAL_OPERATION_NUMBER
      , REF_TASKLIST_TYPE 
      , REF_TASKLIST_GROUP 
      , REF_GROUP_COUNTER 
      , OPERATION_DESCRIPTION
      , OPERATION_NUMBER
      , CONTROL_KEY
      , DELETION_INDICATOR
      , SETUP_TIME
      , STANDARD_VALUE
      , BASE_QUANTITY
      , ACTIVITY_TYPE
      , VALID_FROM_DATE__YYYYMMDD
      , CHANGE_NUMBER
      , BKCC
    FROM SRC_D
)
---- RENAME LAYER ----

, RENAME_D as (
    SELECT
        REC_SRC
      , TASKLIST_OPERATION_BK
      , TASKLIST_OPERATION_HK
      , TASKLIST_TYPE
      , TASKLIST_GROUP_KEY
      , INTERNAL_OPERATION_NUMBER
      , OPERATION_NUMBER
      , REF_TASKLIST_TYPE 
      , REF_TASKLIST_GROUP 
      , REF_GROUP_COUNTER 
      , OPERATION_DESCRIPTION
      , CONTROL_KEY
      , DELETION_INDICATOR
      , SETUP_TIME
      , STANDARD_VALUE
      , BASE_QUANTITY
      , ACTIVITY_TYPE
      , VALID_FROM_DATE__YYYYMMDD
      , CHANGE_NUMBER
      , BKCC
    FROM LOGIC_D
)
---- FILTER LAYER ----

, FILTER_D as (
    SELECT *
    FROM RENAME_D
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM FILTER_D
)

---- FINAL LAYER ----
SELECT
          REC_SRC
        , TASKLIST_OPERATION_BK
        , TASKLIST_OPERATION_HK
        , TASKLIST_TYPE
        , TASKLIST_GROUP_KEY
        , INTERNAL_OPERATION_NUMBER
        , OPERATION_NUMBER
        , REF_TASKLIST_TYPE 
        , REF_TASKLIST_GROUP 
        , REF_GROUP_COUNTER 
        , OPERATION_DESCRIPTION
        , CONTROL_KEY
        , DELETION_INDICATOR
        , SETUP_TIME
        , STANDARD_VALUE
        , BASE_QUANTITY
        , ACTIVITY_TYPE
        , VALID_FROM_DATE__YYYYMMDD
        , CHANGE_NUMBER
        , BKCC
FROM JOIN_RESULT
