---- SRC LAYER ----
WITH
SRC_SUP            as ( SELECT BKCC, CURRENCY_CODE, CURRENT_FLAG, DISCOUNT_DAYS, DISCOUNT_PERCENT, END_DATE__YYYYMMDD, IS_DELETED, PAYMENT_TERM_CODE, PAYMENT_TERM_DESC, PAYMENT_TERM_DUE_DAYS, PURCHASING_ORG_BK, REC_SRC, START_DATE__YYYYMMDD, SUPPLIER_BK, SUPPLIER_HK, SUPPLIER_PAYMENT_TERM_DURABLE_HK, SUPPLIER_PAYMENT_TERM_HK, SUPPLIER_PURCHASING_ORG_STATUS, SUPPLIER_SITE_BK FROM {{ ref('pb_supplier_payment_terms') }} as SRC 
                        
                         )

/*
SRC_SUP            as ( SELECT * FROM BUS_VAULT.pb_supplier_payment_terms )
*/
---- LOGIC LAYER ----

, LOGIC_SUP as (
    SELECT
        SUPPLIER_PAYMENT_TERM_HK
      , SUPPLIER_PAYMENT_TERM_DURABLE_HK
      , SUPPLIER_HK
      , START_DATE__YYYYMMDD
      , END_DATE__YYYYMMDD
      , SUPPLIER_BK
      , PURCHASING_ORG_BK
      , SUPPLIER_SITE_BK
      , PAYMENT_TERM_CODE
      , PAYMENT_TERM_DESC
      , PAYMENT_TERM_DUE_DAYS
      , DISCOUNT_DAYS
      , DISCOUNT_PERCENT
      , CURRENCY_CODE
      , SUPPLIER_PURCHASING_ORG_STATUS
      , IS_DELETED
      , CURRENT_FLAG
      , REC_SRC
      , BKCC
    FROM SRC_SUP
)
---- RENAME LAYER ----

, RENAME_SUP as (
    SELECT
        SUPPLIER_PAYMENT_TERM_HK
      , SUPPLIER_PAYMENT_TERM_DURABLE_HK
      , SUPPLIER_HK
      , START_DATE__YYYYMMDD
      , END_DATE__YYYYMMDD
      , SUPPLIER_BK
      , PURCHASING_ORG_BK
      , SUPPLIER_SITE_BK
      , PAYMENT_TERM_CODE
      , PAYMENT_TERM_DESC
      , PAYMENT_TERM_DUE_DAYS
      , DISCOUNT_DAYS
      , DISCOUNT_PERCENT
      , CURRENCY_CODE
      , SUPPLIER_PURCHASING_ORG_STATUS
      , IS_DELETED
      , CURRENT_FLAG
      , REC_SRC
      , BKCC
    FROM LOGIC_SUP
)
---- FILTER LAYER ----

, FILTER_SUP as (
    SELECT *
    FROM RENAME_SUP
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM FILTER_SUP
)

---- FINAL LAYER ----
SELECT
          SUPPLIER_PAYMENT_TERM_HK
        , SUPPLIER_PAYMENT_TERM_DURABLE_HK
        , SUPPLIER_HK
        , START_DATE__YYYYMMDD
        , END_DATE__YYYYMMDD
        , SUPPLIER_BK
        , PURCHASING_ORG_BK
        , SUPPLIER_SITE_BK
        , PAYMENT_TERM_CODE
        , PAYMENT_TERM_DESC
        , PAYMENT_TERM_DUE_DAYS
        , DISCOUNT_DAYS
        , DISCOUNT_PERCENT
        , CURRENCY_CODE
        , SUPPLIER_PURCHASING_ORG_STATUS
        , IS_DELETED
        , CURRENT_FLAG
        , REC_SRC
        , BKCC
FROM JOIN_RESULT
