WITH pit_date_fiscal_445
AS (
	SELECT *
	FROM {{ ref('pit_date_fiscal_445') }}
	)
SELECT DATE_BK,
	DATE,
	FISCAL_445_CAL_DAY,
	FISCAL_445_CAL_WEEK,
	FISCAL_445_CAL_MONTH,
	FISCAL_445_CAL_QUARTER,
	FISCAL_445_CAL_YEAR,
	FISCAL_445_CAL_QUARTER_YYYYQQ,
	FISCAL_445_CAL_MONTH_YYYYMM,
	FISCAL_445_CAL_WEEK_YYYYWW,
	FISCAL_445_WORKING_DAY_FLAG,
	IS_COMPLETED_FISCAL_MONTH,
	IS_COMPLETED_FISCAL_WEEK,
	FISCAL_LAST_WEEK_FLAG,
	FISCAL_LAST_4_WEEKS_FLAG,
	FISCAL_LAST_13_WEEKS_FLAG,
	FISCAL_LAST_MONTH_FLAG,
	FISCAL_LAST_3_MONTHS_FLAG,
	MONTH_NAME,
	MONTH_NAME_ABBR,
	EPOCH_DAY,
	EPOCH_WEEK,
	EPOCH_MONTH,
	WEEKS_IN_MONTH,
	MONTH_NUMBER_LEADING_ZERO,
	FISCAL_DAY_OF_YEAR,
	FISCAL_YTD_FLAG,
	FISCAL_ROLLING_52_WEEK_FLAG,
    FISCAL_LAST_QUARTER_FLAG,
    FISCAL_LAST_12_MONTHS_FLAG,
    FISCAL_QTD_FLAG
FROM pit_date_fiscal_445
