---- SRC LAYER ----
WITH
SRC_D              as ( SELECT BKCC, DELETION_INDICATOR, GROUP_COUNTER, LOT_SIZE_FROM, LOT_SIZE_TO, REC_SRC, TASKLIST_GROUP_BK, TASKLIST_GROUP_HK, TASKLIST_STATUS, TASKLIST_USAGE, TASK_DESCRIPTION, VALID_FROM_DATE__YYYYMMDD, WC_WITH_PLANNING FROM {{ ref('pit_tasklist_group') }} as SRC  )

/*
SRC_D              as ( SELECT * FROM BUS_VAULT.pit_tasklist_group )
*/
---- LOGIC LAYER ----

, LOGIC_D as (
    SELECT
        REC_SRC
      , TASKLIST_GROUP_BK
      , TASKLIST_GROUP_HK
      , VALID_FROM_DATE__YYYYMMDD
      , TASKLIST_USAGE
      , TASK_DESCRIPTION
      , WC_WITH_PLANNING
      , TASKLIST_STATUS
      , DELETION_INDICATOR
      , GROUP_COUNTER
      , LOT_SIZE_FROM
      , LOT_SIZE_TO
      , BKCC
    FROM SRC_D
)
---- RENAME LAYER ----

, RENAME_D as (
    SELECT
        REC_SRC
      , TASKLIST_GROUP_BK
      , TASKLIST_GROUP_HK
      , VALID_FROM_DATE__YYYYMMDD
      , TASKLIST_USAGE
      , TASK_DESCRIPTION
      , WC_WITH_PLANNING
      , TASKLIST_STATUS
      , DELETION_INDICATOR
      , GROUP_COUNTER
      , LOT_SIZE_FROM
      , LOT_SIZE_TO
      , BKCC
    FROM LOGIC_D
)
---- FILTER LAYER ----

, FILTER_D as (
    SELECT *
    FROM RENAME_D
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM FILTER_D
)

---- FINAL LAYER ----
SELECT
          REC_SRC
        , TASKLIST_GROUP_BK
        , TASKLIST_GROUP_HK
        , VALID_FROM_DATE__YYYYMMDD
        , TASKLIST_USAGE
        , TASK_DESCRIPTION
        , WC_WITH_PLANNING
        , TASKLIST_STATUS
        , DELETION_INDICATOR
        , GROUP_COUNTER
        , LOT_SIZE_FROM
        , LOT_SIZE_TO
        , BKCC
FROM JOIN_RESULT
