---- SRC LAYER ----
WITH
SRC_D              as ( SELECT ALTERNATE_BOM, BASE_UOM, BILL_OF_MATERIAL, BKCC, BOM_CATEGORY, BOM_STATUS, BOM_USAGE, GROUP_COUNTER, MATERIAL, MRP_CONTROLLER, PAENR_CHANGE_NUMBER, REC_SRC, PRODUCTION_ORDER_BK, PRODUCTION_ORDER_HK, PRODUCTION_SUPERVISOR, RESERVATION_ID, ROUTING_EXPLOSION_DATE__YYYYMMDD, ROUTING_NUMBER_OF_OPERATIONS_IN_THE_ORDER, SAENR_CHANGE_NUMBER, SCHEDULING_MARGIN_KEY_FOR_FLOAT, SCHEDULING_TYPE, TASK_LIST_APP, TASK_LIST_GROUP, TASK_LIST_TYPE, TASK_LIST_USAGE FROM {{ ref('pit_production_order') }} as SRC  )

/*
SRC_D              as ( SELECT * FROM BUS_VAULT.pit_production_order )
*/
---- LOGIC LAYER ----

, LOGIC_D as (
    SELECT
        PRODUCTION_ORDER_BK
      , PRODUCTION_ORDER_HK
      , RESERVATION_ID
      , BASE_UOM
      , MATERIAL
      , TASK_LIST_TYPE
      , TASK_LIST_GROUP
      , TASK_LIST_APP
      , GROUP_COUNTER
      , TASK_LIST_USAGE
      , ROUTING_EXPLOSION_DATE__YYYYMMDD
      , PAENR_CHANGE_NUMBER
      , BOM_CATEGORY
      , BOM_STATUS
      , BILL_OF_MATERIAL
      , SAENR_CHANGE_NUMBER
      , ALTERNATE_BOM
      , BOM_USAGE
      , MRP_CONTROLLER
      , ROUTING_NUMBER_OF_OPERATIONS_IN_THE_ORDER
      , PRODUCTION_SUPERVISOR
      , SCHEDULING_MARGIN_KEY_FOR_FLOAT
      , SCHEDULING_TYPE
      , REC_SRC
      , BKCC
    FROM SRC_D
)
---- RENAME LAYER ----

, RENAME_D as (
    SELECT
        PRODUCTION_ORDER_BK
      , PRODUCTION_ORDER_HK
      , RESERVATION_ID
      , BASE_UOM
      , MATERIAL
      , TASK_LIST_TYPE
      , TASK_LIST_GROUP
      , TASK_LIST_APP
      , GROUP_COUNTER
      , TASK_LIST_USAGE
      , ROUTING_EXPLOSION_DATE__YYYYMMDD
      , PAENR_CHANGE_NUMBER
      , BOM_CATEGORY
      , BOM_STATUS
      , BILL_OF_MATERIAL
      , SAENR_CHANGE_NUMBER
      , ALTERNATE_BOM
      , BOM_USAGE
      , MRP_CONTROLLER
      , ROUTING_NUMBER_OF_OPERATIONS_IN_THE_ORDER
      , PRODUCTION_SUPERVISOR
      , SCHEDULING_MARGIN_KEY_FOR_FLOAT
      , SCHEDULING_TYPE
      , REC_SRC
      , BKCC
    FROM LOGIC_D
)
---- FILTER LAYER ----

, FILTER_D as (
    SELECT *
    FROM RENAME_D
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM FILTER_D
)

---- FINAL LAYER ----
SELECT
          PRODUCTION_ORDER_BK
        , PRODUCTION_ORDER_HK
        , RESERVATION_ID
        , BASE_UOM
        , MATERIAL
        , TASK_LIST_TYPE
        , TASK_LIST_GROUP
        , TASK_LIST_APP
        , GROUP_COUNTER
        , TASK_LIST_USAGE
        , ROUTING_EXPLOSION_DATE__YYYYMMDD
        , PAENR_CHANGE_NUMBER
        , BOM_CATEGORY
        , BOM_STATUS
        , BILL_OF_MATERIAL
        , SAENR_CHANGE_NUMBER
        , ALTERNATE_BOM
        , BOM_USAGE
        , MRP_CONTROLLER
        , ROUTING_NUMBER_OF_OPERATIONS_IN_THE_ORDER
        , PRODUCTION_SUPERVISOR
        , SCHEDULING_MARGIN_KEY_FOR_FLOAT
        , SCHEDULING_TYPE
        , REC_SRC
        , BKCC
FROM JOIN_RESULT
