---- SRC LAYER ----
WITH
SRC_PBDOH          as ( SELECT ADJUSTMENT, BILLING_CITY, BILLING_COUNTRY, BILLING_STATE, BILLING_ZIP, BKCC, CANCELLED_DATE__YYYYMMDD, CONSUMER_BK, 
                        CONSUMER_KEY, CREATED_DATE_KEY, CUSTOMER_BK, CUSTOMER_ID, CUSTOMER_KEY, DISCOUNTS, FINANCIAL_STATUS, FULFILLMENT_STATUS, 
                        ORDER_DOLLARS, ORDER_HEADER_BK, ORDER_HEADER_KEY, ORDER_ID, ORDER_SUBTOTAL_DOLLARS, ORDER_TAX, REC_SRC, SHIPPING, SHIPPING_CITY, 
                        SHIPPING_COUNTRY, SHIPPING_STATE, SHIPPING_ZIP, STORE, UPDATED_DATE__YYYYMMDD FROM {{ ref('pb_dtc_order_header') }} as SRC  )

/*
SRC_PBDOH          as ( SELECT * FROM bus_vault.PB_DTC_ORDER_HEADER )
*/
---- LOGIC LAYER ----

, LOGIC_PBDOH as (
    SELECT
        ORDER_HEADER_KEY
      , ORDER_HEADER_BK
      , ORDER_ID
      , CUSTOMER_KEY
      , CUSTOMER_BK
      , CUSTOMER_ID
      , CONSUMER_KEY
      , CONSUMER_BK
      , FINANCIAL_STATUS
      , FULFILLMENT_STATUS
      , ORDER_DOLLARS
      , ORDER_SUBTOTAL_DOLLARS
      , ORDER_TAX
      , SHIPPING
      , DISCOUNTS
      , ADJUSTMENT
      , SHIPPING_CITY
      , SHIPPING_STATE
      , SHIPPING_COUNTRY
      , SHIPPING_ZIP
      , BILLING_CITY
      , BILLING_STATE
      , BILLING_COUNTRY
      , BILLING_ZIP
      , CREATED_DATE_KEY
      , UPDATED_DATE__YYYYMMDD
      , CANCELLED_DATE__YYYYMMDD
      , STORE
      , REC_SRC
      , BKCC
    FROM SRC_PBDOH
)
---- RENAME LAYER ----

, RENAME_PBDOH as (
    SELECT
        ORDER_HEADER_KEY
      , ORDER_HEADER_BK
      , ORDER_ID
      , CUSTOMER_KEY
      , CUSTOMER_BK
      , CUSTOMER_ID
      , CONSUMER_KEY
      , CONSUMER_BK
      , FINANCIAL_STATUS
      , FULFILLMENT_STATUS
      , ORDER_DOLLARS
      , ORDER_SUBTOTAL_DOLLARS
      , ORDER_TAX
      , SHIPPING
      , DISCOUNTS
      , ADJUSTMENT
      , SHIPPING_CITY
      , SHIPPING_STATE
      , SHIPPING_COUNTRY
      , SHIPPING_ZIP
      , BILLING_CITY
      , BILLING_STATE
      , BILLING_COUNTRY
      , BILLING_ZIP
      , CREATED_DATE_KEY
      , UPDATED_DATE__YYYYMMDD
      , CANCELLED_DATE__YYYYMMDD
      , STORE
      , REC_SRC
      , BKCC
    FROM LOGIC_PBDOH
)
---- FILTER LAYER ----

, FILTER_PBDOH as (
    SELECT *
    FROM RENAME_PBDOH
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM FILTER_PBDOH
)

---- FINAL LAYER ----
SELECT
          ORDER_HEADER_KEY
        , ORDER_HEADER_BK
        , ORDER_ID
        , CUSTOMER_KEY
        , CUSTOMER_BK
        , CUSTOMER_ID
        , CONSUMER_KEY
        , CONSUMER_BK
        , FINANCIAL_STATUS
        , FULFILLMENT_STATUS
        , ORDER_DOLLARS
        , ORDER_SUBTOTAL_DOLLARS
        , ORDER_TAX
        , SHIPPING
        , DISCOUNTS
        , ADJUSTMENT
        , SHIPPING_CITY
        , SHIPPING_STATE
        , SHIPPING_COUNTRY
        , SHIPPING_ZIP
        , BILLING_CITY
        , BILLING_STATE
        , BILLING_COUNTRY
        , BILLING_ZIP
        , CREATED_DATE_KEY
        , UPDATED_DATE__YYYYMMDD
        , CANCELLED_DATE__YYYYMMDD
        , STORE
        , REC_SRC
        , BKCC
FROM JOIN_RESULT
