---- SRC LAYER ----
WITH
SRC_PB_ITEMS       as ( SELECT ABC_CATEGORY, ACTIVE_ITEM_PLANT_IND, BASE_MATERIAL, BASE_MATERIAL_KEY, BKCC, BOM_USAGE, BRAND, COMMODITY_DESCRIPTION, COVERAGE_PROFILE, COVERAGE_PROFILE_DESCRIPTION, CRITICAL_PART, DELETION_FLAG, DELIVERY_DATE_KEY, FIXED_LOT_SIZE_QTY, FORECAST_BASE_MATERIAL, ITEM_ABC_CATEGORY, ITEM_ALT_BOM_METHOD, ITEM_ARCHITECTURE, ITEM_ARCHITECTURE_DETAIL, ITEM_BASE_UOM, ITEM_CATEGORY, ITEM_CLASS, ITEM_COUNTRY_OF_ORIGIN, ITEM_DISCONTINUATION_FLAG, ITEM_FINISH, ITEM_HK, ITEM_HTS_CODE, ITEM_IN_HOUSE_PRODUCTION_TIME, ITEM_MRP_CONTROLLER, ITEM_MRP_GROUP, ITEM_MRP_PROFILE, ITEM_MRP_TYPE, ITEM_NUMBER, ITEM_PLANNED_DELIVERY_TIME, ITEM_PRICE_BAND, ITEM_PROCESSING_TIME, ITEM_PROCUREMENT_TYPE, ITEM_PRODUCTION_SUPERVISOR, ITEM_PRODUCT_LINE, ITEM_PRODUCT_SEGMENT, ITEM_PRODUCT_TYPE, ITEM_PURCHASING_GROUP, ITEM_REPORTING_CATEGORY, ITEM_ROOM_AREA_DETAIL, ITEM_SPECIAL_PROCUREMENT_TYPE, ITEM_SUB_CATEGORY, ITEM_SUB_CLASS, ITEM_TAKT_TIME, ITEM_TARGET_SERVICE_LEVEL, ITEM_TITLE, ITEM_TYPE_DESCRIPTION, LEAD_TIME_IN_DAYS, LOT_SIZE_CODE, LOT_SIZE_SCRAP_QTY, MAX_LOT_SIZE, MAX_STOCK, MIN_LOT_SIZE, MOVING_AVG_PRICE, MRP_PLANNING_CALENDAR, MRP_TYPE, OVERDELIVERY_TOLERANCE_PCT, PLANNING_TIME, PLANT_BK, PLANT_HK, PLANT_ITEM_HK, PNS_PRICE_BAND, QUOTA_ARRANGEMENT_USAGE, REC_SRC, ROUNDING_PROFILE, SAFETY_STOCK, SAFETY_TIME_INDICATOR, SAFETY_TIME_IN_DAYS, SCHEDULING_MARGIN_KEY, SOURCE_LIST_REQUIREMENT_IND, SPECIAL_PROCUREMENT_PLANT, STANDARD_PRICE, STOCK_DETERMINATION_GROUP, SYSTEM_ITEM_TYPE_CD, ULTIMATE_ITEM_SUPPLY_SOURCE, UNDERDELIVERY_TOLERANCE_PCT, UNIT_OF_ISSUE FROM {{ ref('pb_items_by_plant') }} as SRC  )

/*
SRC_PB_ITEMS       as ( SELECT * FROM bus_vault.pb_items_by_plant )
*/
---- LOGIC LAYER ----

, LOGIC_PB_ITEMS as (
    SELECT
        PLANT_ITEM_HK                                                as                                     PLANT_ITEM_KEY
      , ITEM_HK                                                      as                                           ITEM_KEY
      , ITEM_NUMBER
      , PLANT_HK                                                     as                                          PLANT_KEY
      , PLANT_BK                                                     as                                              PLANT
      , ITEM_TITLE
      , BASE_MATERIAL_KEY
      , BASE_MATERIAL
      , SYSTEM_ITEM_TYPE_CD                                          as                               ITEM_PLANT_TYPE_CODE
      , ITEM_TYPE_DESCRIPTION
      , ACTIVE_ITEM_PLANT_IND                                        as                                  ITEM_PLANT_STATUS
      , ITEM_PROCUREMENT_TYPE
      , ITEM_SPECIAL_PROCUREMENT_TYPE
      , SPECIAL_PROCUREMENT_PLANT
      , ITEM_COUNTRY_OF_ORIGIN
      , ITEM_HTS_CODE
      , ITEM_BASE_UOM
      , BRAND
      , ITEM_CATEGORY
      , ITEM_SUB_CATEGORY
      , ITEM_CLASS
      , ITEM_SUB_CLASS
      , FORECAST_BASE_MATERIAL
      , ULTIMATE_ITEM_SUPPLY_SOURCE
      , ITEM_ARCHITECTURE
      , ITEM_ARCHITECTURE_DETAIL
      , ITEM_FINISH
      , ITEM_PRICE_BAND
      , PNS_PRICE_BAND
      , ITEM_PRODUCT_LINE
      , ITEM_PRODUCT_SEGMENT
      , ITEM_PRODUCT_TYPE
      , ITEM_REPORTING_CATEGORY
      , ITEM_ROOM_AREA_DETAIL
      , ITEM_PURCHASING_GROUP
      , ITEM_PROCESSING_TIME
      , ITEM_PLANNED_DELIVERY_TIME
      , ITEM_ABC_CATEGORY
      , CRITICAL_PART
      , ITEM_MRP_PROFILE
      , ITEM_MRP_TYPE
      , ITEM_MRP_CONTROLLER
      , ITEM_MRP_GROUP
      , ITEM_ALT_BOM_METHOD
      , ITEM_DISCONTINUATION_FLAG
      , ITEM_PRODUCTION_SUPERVISOR
      , ITEM_IN_HOUSE_PRODUCTION_TIME
      , ITEM_TARGET_SERVICE_LEVEL
      , ITEM_TAKT_TIME
      , LEAD_TIME_IN_DAYS
      , SAFETY_STOCK
      , MAX_STOCK
      , SAFETY_TIME_INDICATOR
      , SAFETY_TIME_IN_DAYS
      , STOCK_DETERMINATION_GROUP
      , COVERAGE_PROFILE
      , MIN_LOT_SIZE
      , MAX_LOT_SIZE
      , ROUNDING_PROFILE
      , MRP_TYPE
      , ABC_CATEGORY
      , COVERAGE_PROFILE_DESCRIPTION
      , DELETION_FLAG
      , UNIT_OF_ISSUE
      , LOT_SIZE_CODE
      , FIXED_LOT_SIZE_QTY
      , LOT_SIZE_SCRAP_QTY
      , SCHEDULING_MARGIN_KEY
      , OVERDELIVERY_TOLERANCE_PCT
      , UNDERDELIVERY_TOLERANCE_PCT
      , QUOTA_ARRANGEMENT_USAGE
      , MRP_PLANNING_CALENDAR
      , SOURCE_LIST_REQUIREMENT_IND
      , DELIVERY_DATE_KEY                                            as                            DELIVERY_DATE__YYYYMMDD
      , PLANNING_TIME
      , BOM_USAGE
      , COMMODITY_DESCRIPTION
      , STANDARD_PRICE
      , MOVING_AVG_PRICE
      , REC_SRC
      , BKCC
    FROM SRC_PB_ITEMS
)
---- RENAME LAYER ----

, RENAME_PB_ITEMS as (
    SELECT
        PLANT_ITEM_KEY
      , ITEM_KEY
      , ITEM_NUMBER
      , PLANT_KEY
      , PLANT
      , ITEM_TITLE
      , BASE_MATERIAL_KEY
      , BASE_MATERIAL
      , ITEM_PLANT_TYPE_CODE
      , ITEM_TYPE_DESCRIPTION
      , ITEM_PLANT_STATUS
      , ITEM_PROCUREMENT_TYPE
      , ITEM_SPECIAL_PROCUREMENT_TYPE
      , SPECIAL_PROCUREMENT_PLANT
      , ITEM_COUNTRY_OF_ORIGIN
      , ITEM_HTS_CODE
      , ITEM_BASE_UOM
      , BRAND
      , ITEM_CATEGORY
      , ITEM_SUB_CATEGORY
      , ITEM_CLASS
      , ITEM_SUB_CLASS
      , FORECAST_BASE_MATERIAL
      , ULTIMATE_ITEM_SUPPLY_SOURCE
      , ITEM_ARCHITECTURE
      , ITEM_ARCHITECTURE_DETAIL
      , ITEM_FINISH
      , ITEM_PRICE_BAND
      , PNS_PRICE_BAND
      , ITEM_PRODUCT_LINE
      , ITEM_PRODUCT_SEGMENT
      , ITEM_PRODUCT_TYPE
      , ITEM_REPORTING_CATEGORY
      , ITEM_ROOM_AREA_DETAIL
      , ITEM_PURCHASING_GROUP
      , ITEM_PROCESSING_TIME
      , ITEM_PLANNED_DELIVERY_TIME
      , ITEM_ABC_CATEGORY
      , CRITICAL_PART
      , ITEM_MRP_PROFILE
      , ITEM_MRP_TYPE
      , ITEM_MRP_CONTROLLER
      , ITEM_MRP_GROUP
      , ITEM_ALT_BOM_METHOD
      , ITEM_DISCONTINUATION_FLAG
      , ITEM_PRODUCTION_SUPERVISOR
      , ITEM_IN_HOUSE_PRODUCTION_TIME
      , ITEM_TARGET_SERVICE_LEVEL
      , ITEM_TAKT_TIME
      , LEAD_TIME_IN_DAYS
      , SAFETY_STOCK
      , MAX_STOCK
      , SAFETY_TIME_INDICATOR
      , SAFETY_TIME_IN_DAYS
      , STOCK_DETERMINATION_GROUP
      , COVERAGE_PROFILE
      , MIN_LOT_SIZE
      , MAX_LOT_SIZE
      , ROUNDING_PROFILE
      , MRP_TYPE
      , ABC_CATEGORY
      , COVERAGE_PROFILE_DESCRIPTION
      , DELETION_FLAG
      , UNIT_OF_ISSUE
      , LOT_SIZE_CODE
      , FIXED_LOT_SIZE_QTY
      , LOT_SIZE_SCRAP_QTY
      , SCHEDULING_MARGIN_KEY
      , OVERDELIVERY_TOLERANCE_PCT
      , UNDERDELIVERY_TOLERANCE_PCT
      , QUOTA_ARRANGEMENT_USAGE
      , MRP_PLANNING_CALENDAR
      , SOURCE_LIST_REQUIREMENT_IND
      , DELIVERY_DATE__YYYYMMDD
      , PLANNING_TIME
      , BOM_USAGE
      , COMMODITY_DESCRIPTION
      , STANDARD_PRICE
      , MOVING_AVG_PRICE
      , REC_SRC
      , BKCC
    FROM LOGIC_PB_ITEMS
)
---- FILTER LAYER ----

, FILTER_PB_ITEMS as (
    SELECT *
    FROM RENAME_PB_ITEMS
    WHERE TRUE GROUP BY ALL
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM FILTER_PB_ITEMS
)

---- FINAL LAYER ----
SELECT
          PLANT_ITEM_KEY
        , ITEM_KEY
        , ITEM_NUMBER
        , PLANT_KEY
        , PLANT
        , ITEM_TITLE
        , BASE_MATERIAL_KEY
        , BASE_MATERIAL
        , ITEM_PLANT_TYPE_CODE
        , ITEM_TYPE_DESCRIPTION
        , ITEM_PLANT_STATUS
        , ITEM_PROCUREMENT_TYPE
        , ITEM_SPECIAL_PROCUREMENT_TYPE
        , SPECIAL_PROCUREMENT_PLANT
        , ITEM_COUNTRY_OF_ORIGIN
        , ITEM_HTS_CODE
        , ITEM_BASE_UOM
        , BRAND
        , ITEM_CATEGORY
        , ITEM_SUB_CATEGORY
        , ITEM_CLASS
        , ITEM_SUB_CLASS
        , FORECAST_BASE_MATERIAL
        , ULTIMATE_ITEM_SUPPLY_SOURCE
        , ITEM_ARCHITECTURE
        , ITEM_ARCHITECTURE_DETAIL
        , ITEM_FINISH
        , ITEM_PRICE_BAND
        , PNS_PRICE_BAND
        , ITEM_PRODUCT_LINE
        , ITEM_PRODUCT_SEGMENT
        , ITEM_PRODUCT_TYPE
        , ITEM_REPORTING_CATEGORY
        , ITEM_ROOM_AREA_DETAIL
        , ITEM_PURCHASING_GROUP
        , ITEM_PROCESSING_TIME
        , ITEM_PLANNED_DELIVERY_TIME
        , ITEM_ABC_CATEGORY
        , CRITICAL_PART
        , ITEM_MRP_PROFILE
        , ITEM_MRP_TYPE
        , ITEM_MRP_CONTROLLER
        , ITEM_MRP_GROUP
        , ITEM_ALT_BOM_METHOD
        , ITEM_DISCONTINUATION_FLAG
        , ITEM_PRODUCTION_SUPERVISOR
        , ITEM_IN_HOUSE_PRODUCTION_TIME
        , ITEM_TARGET_SERVICE_LEVEL
        , ITEM_TAKT_TIME
        , LEAD_TIME_IN_DAYS
        , SAFETY_STOCK
        , MAX_STOCK
        , SAFETY_TIME_INDICATOR
        , SAFETY_TIME_IN_DAYS
        , STOCK_DETERMINATION_GROUP
        , COVERAGE_PROFILE
        , MIN_LOT_SIZE
        , MAX_LOT_SIZE
        , ROUNDING_PROFILE
        , MRP_TYPE
        , ABC_CATEGORY
        , COVERAGE_PROFILE_DESCRIPTION
        , DELETION_FLAG
        , UNIT_OF_ISSUE
        , LOT_SIZE_CODE
        , FIXED_LOT_SIZE_QTY
        , LOT_SIZE_SCRAP_QTY
        , SCHEDULING_MARGIN_KEY
        , OVERDELIVERY_TOLERANCE_PCT
        , UNDERDELIVERY_TOLERANCE_PCT
        , QUOTA_ARRANGEMENT_USAGE
        , MRP_PLANNING_CALENDAR
        , SOURCE_LIST_REQUIREMENT_IND
        , DELIVERY_DATE__YYYYMMDD
        , PLANNING_TIME
        , BOM_USAGE
        , COMMODITY_DESCRIPTION
        , STANDARD_PRICE
        , MOVING_AVG_PRICE
        , REC_SRC
        , BKCC
FROM JOIN_RESULT
