---- SRC LAYER ----
WITH
SRC_pc             as ( SELECT ACTIVE_AVAILABLE_CAPACITY_VERSION, AZNOR_NUM_OF_INDIVIDUAL_CAPACITY, BKCC, CAPACITY_BK, CAPACITY_HK, CAPACITY_CATEGORY, CAPACITY_MEASUREMENT_UNIT, CAPACITY_PLANNER_GROUP, CAPACITY_SHORT_TEXT, CAPACITY_UTILITY_RATE_PERCENT, CUMULATIVE_BREAK_TIME_IN_SECONDS, END_TIME_IN_SECONDS, FACTORY_CALENDAR_ID, PLANT_BK, REC_SRC, START_TIME_IN_SECONDS, TOTAL_DOWNTIME_SECONDS, TOTAL_TIME_SECONDS, TOTAL_TIME_HOURS, TOTAL_TIME_HOUR_PER_WEEK, TOTAL_TIME_MINUTES, TOTAL_UPTIME_PER_DAY, VALID_TO_DATE__YYYYMMDD, AVAILABLE_CAPACITY_VERSION FROM {{ ref('pit_capacity') }} as SRC  )

/*
SRC_pc             as ( SELECT * FROM BUS_VAULT.pit_capacity )
*/
---- LOGIC LAYER ----

, LOGIC_pc as (
    SELECT
        CAPACITY_HK
      , CAPACITY_BK
      , REC_SRC
      , BKCC
      , CAPACITY_UTILITY_RATE_PERCENT
      , PLANT_BK
      , START_TIME_IN_SECONDS
      , END_TIME_IN_SECONDS
      , AZNOR_NUM_OF_INDIVIDUAL_CAPACITY
      , FACTORY_CALENDAR_ID
      , ACTIVE_AVAILABLE_CAPACITY_VERSION
      , CAPACITY_CATEGORY
      , CAPACITY_MEASUREMENT_UNIT
      , CUMULATIVE_BREAK_TIME_IN_SECONDS
      , CAPACITY_PLANNER_GROUP
      , CAPACITY_SHORT_TEXT
      , VALID_TO_DATE__YYYYMMDD
      , AVAILABLE_CAPACITY_VERSION
      , TOTAL_TIME_SECONDS
      , TOTAL_DOWNTIME_SECONDS
      , TOTAL_TIME_MINUTES
      , TOTAL_TIME_HOURS
      , TOTAL_TIME_HOUR_PER_WEEK
      , TOTAL_UPTIME_PER_DAY
    FROM SRC_pc
)
---- RENAME LAYER ----

, RENAME_pc as (
    SELECT
        CAPACITY_HK
      , CAPACITY_BK
      , REC_SRC
      , BKCC
      , CAPACITY_UTILITY_RATE_PERCENT
      , PLANT_BK
      , START_TIME_IN_SECONDS
      , END_TIME_IN_SECONDS
      , AZNOR_NUM_OF_INDIVIDUAL_CAPACITY
      , FACTORY_CALENDAR_ID
      , ACTIVE_AVAILABLE_CAPACITY_VERSION
      , CAPACITY_CATEGORY
      , CAPACITY_MEASUREMENT_UNIT
      , CUMULATIVE_BREAK_TIME_IN_SECONDS
      , CAPACITY_PLANNER_GROUP
      , CAPACITY_SHORT_TEXT
      , VALID_TO_DATE__YYYYMMDD
      , AVAILABLE_CAPACITY_VERSION
      , TOTAL_TIME_SECONDS
      , TOTAL_DOWNTIME_SECONDS
      , TOTAL_TIME_MINUTES
      , TOTAL_TIME_HOURS
      , TOTAL_TIME_HOUR_PER_WEEK
      , TOTAL_UPTIME_PER_DAY
    FROM LOGIC_pc
)
---- FILTER LAYER ----

, FILTER_pc as (
    SELECT *
    FROM RENAME_pc
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM FILTER_pc
)

---- FINAL LAYER ----
SELECT
          CAPACITY_HK
        , CAPACITY_BK
        , REC_SRC
        , BKCC
        , CAPACITY_UTILITY_RATE_PERCENT
        , PLANT_BK
        , START_TIME_IN_SECONDS
        , END_TIME_IN_SECONDS
        , AZNOR_NUM_OF_INDIVIDUAL_CAPACITY
        , FACTORY_CALENDAR_ID
        , ACTIVE_AVAILABLE_CAPACITY_VERSION
        , CAPACITY_CATEGORY
        , CAPACITY_MEASUREMENT_UNIT
        , CUMULATIVE_BREAK_TIME_IN_SECONDS
        , CAPACITY_PLANNER_GROUP
        , CAPACITY_SHORT_TEXT
        , VALID_TO_DATE__YYYYMMDD
        , AVAILABLE_CAPACITY_VERSION
        , TOTAL_TIME_SECONDS
        , TOTAL_DOWNTIME_SECONDS
        , TOTAL_TIME_MINUTES
        , TOTAL_TIME_HOURS
        , TOTAL_TIME_HOUR_PER_WEEK
        , TOTAL_UPTIME_PER_DAY
FROM JOIN_RESULT
