---- SRC LAYER ----
WITH
SRC_SUP            as ( SELECT BKCC, MDM_ADDRESS_LINE_1, MDM_ADDRESS_LINE_2, MDM_ADDRESS_TYPE, MDM_BKCC, MDM_CITY, MDM_COUNTRY, MDM_FAX_NUMBER, MDM_GOLDEN_RECORD, MDM_INACTIVE_DATE__YYYYMMDD, MDM_PHONE_NUMBER, MDM_POSTAL_CODE, MDM_PRIMARY_EMAIL_ADDRESS, MDM_REC_SRC, MDM_SITE_STATUS, MDM_SOURCE_LAST_RUN_DATE__YYYYMMDD, MDM_STATE, MDM_SUPPLIER_BK, MDM_SUPPLIER_SITE_BK, MDM_SUPPLIER_TYPE, MDM_TAX_NUMBER, REC_SRC, SUPPLIER_BK, SUPPLIER_SITE_KEY FROM {{ ref('pb_supplier_site') }} as SRC  )

/*
SRC_SUP            as ( SELECT * FROM BUS_VAULT.pb_supplier_site )
*/
---- LOGIC LAYER ----

, LOGIC_SUP as (
    SELECT
        SUPPLIER_SITE_KEY
      , SUPPLIER_BK
      , MDM_SUPPLIER_BK
      , MDM_SUPPLIER_SITE_BK
      , MDM_GOLDEN_RECORD
      , MDM_ADDRESS_TYPE
      , MDM_ADDRESS_LINE_1
      , MDM_ADDRESS_LINE_2
      , MDM_CITY
      , MDM_STATE
      , MDM_POSTAL_CODE
      , MDM_COUNTRY
      , MDM_TAX_NUMBER
      , MDM_SUPPLIER_TYPE
      , MDM_SOURCE_LAST_RUN_DATE__YYYYMMDD
      , MDM_INACTIVE_DATE__YYYYMMDD
      , MDM_SITE_STATUS
      , MDM_PHONE_NUMBER
      , MDM_FAX_NUMBER
      , MDM_PRIMARY_EMAIL_ADDRESS
      , REC_SRC
      , BKCC
      , MDM_REC_SRC
      , MDM_BKCC
    FROM SRC_SUP
)
---- RENAME LAYER ----

, RENAME_SUP as (
    SELECT
        SUPPLIER_SITE_KEY
      , SUPPLIER_BK
      , MDM_SUPPLIER_BK
      , MDM_SUPPLIER_SITE_BK
      , MDM_GOLDEN_RECORD
      , MDM_ADDRESS_TYPE
      , MDM_ADDRESS_LINE_1
      , MDM_ADDRESS_LINE_2
      , MDM_CITY
      , MDM_STATE
      , MDM_POSTAL_CODE
      , MDM_COUNTRY
      , MDM_TAX_NUMBER
      , MDM_SUPPLIER_TYPE
      , MDM_SOURCE_LAST_RUN_DATE__YYYYMMDD
      , MDM_INACTIVE_DATE__YYYYMMDD
      , MDM_SITE_STATUS
      , MDM_PHONE_NUMBER
      , MDM_FAX_NUMBER
      , MDM_PRIMARY_EMAIL_ADDRESS
      , REC_SRC
      , BKCC
      , MDM_REC_SRC
      , MDM_BKCC
    FROM LOGIC_SUP
)
---- FILTER LAYER ----

, FILTER_SUP as (
    SELECT *
    FROM RENAME_SUP
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM FILTER_SUP
)

---- FINAL LAYER ----
SELECT
          SUPPLIER_SITE_KEY
        , SUPPLIER_BK
        , MDM_SUPPLIER_BK
        , MDM_SUPPLIER_SITE_BK
        , MDM_GOLDEN_RECORD
        , MDM_ADDRESS_TYPE
        , MDM_ADDRESS_LINE_1
        , MDM_ADDRESS_LINE_2
        , MDM_CITY
        , MDM_STATE
        , MDM_POSTAL_CODE
        , MDM_COUNTRY
        , MDM_TAX_NUMBER
        , MDM_SUPPLIER_TYPE
        , MDM_SOURCE_LAST_RUN_DATE__YYYYMMDD
        , MDM_INACTIVE_DATE__YYYYMMDD
        , MDM_SITE_STATUS
        , MDM_PHONE_NUMBER
        , MDM_FAX_NUMBER
        , MDM_PRIMARY_EMAIL_ADDRESS
        , REC_SRC
        , BKCC
        , MDM_REC_SRC
        , MDM_BKCC
FROM JOIN_RESULT
