---- SRC LAYER ----
WITH
SRC_P              as ( SELECT BKCC, IS_DELETED, LEGAL_ENTITY_BK, LEGAL_ENTITY_CODE, LEGAL_ENTITY_COUNTRY_CODE, LEGAL_ENTITY_CURRENCY_CODE, LEGAL_ENTITY_HK, LEGAL_ENTITY_NAME, LEGAL_ENTITY_REGION, REC_SRC FROM {{ ref('pit_legal_entity_current') }} as SRC  )

/*
SRC_P              as ( SELECT * FROM BUS_VAULT.pit_legal_entity_current )
*/
---- LOGIC LAYER ----

, LOGIC_P as (
    SELECT
        LEGAL_ENTITY_HK
      , LEGAL_ENTITY_BK
      , LEGAL_ENTITY_CODE
      , LEGAL_ENTITY_NAME
      , LEGAL_ENTITY_REGION
      , LEGAL_ENTITY_COUNTRY_CODE
      , LEGAL_ENTITY_CURRENCY_CODE
      , IS_DELETED
      , REC_SRC
      , BKCC
    FROM SRC_P
)
---- RENAME LAYER ----

, RENAME_P as (
    SELECT
        LEGAL_ENTITY_HK
      , LEGAL_ENTITY_BK
      , LEGAL_ENTITY_CODE
      , LEGAL_ENTITY_NAME
      , LEGAL_ENTITY_REGION
      , LEGAL_ENTITY_COUNTRY_CODE
      , LEGAL_ENTITY_CURRENCY_CODE
      , IS_DELETED
      , REC_SRC
      , BKCC
    FROM LOGIC_P
)
---- FILTER LAYER ----

, FILTER_P as (
    SELECT *
    FROM RENAME_P
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM FILTER_P
)

---- FINAL LAYER ----
SELECT
          LEGAL_ENTITY_HK
        , LEGAL_ENTITY_BK
        , LEGAL_ENTITY_CODE
        , LEGAL_ENTITY_NAME
        , LEGAL_ENTITY_REGION
        , LEGAL_ENTITY_COUNTRY_CODE
        , LEGAL_ENTITY_CURRENCY_CODE
        , IS_DELETED
        , REC_SRC
        , BKCC
FROM JOIN_RESULT
