---- SRC LAYER ----
WITH
SRC_SUP            as ( SELECT BKCC, INACTIVATION_DATE__YYYYMMDD, INDUSTRY_TYPE, IS_DELETED, MDM_BKCC, MDM_GOLDEN_RECORD, MDM_INACTIVATION_DATE__YYYYMMDD, MDM_INDUSTRY_TYPE, MDM_IS_DELETED, MDM_ORGANIZATION_TYPE, MDM_REC_SRC, MDM_SOURCE_CREATION_DATE__YYYYMMDD, MDM_SOURCE_LAST_UPDATE_DATE__YYYYMMDD, MDM_SOURCE_PKEY, MDM_SUPPLIER_ALT_NAME, MDM_SUPPLIER_BK, MDM_SUPPLIER_NAME, MDM_SUPPLIER_STATUS, ORGANIZATION_TYPE, PARENT_SUPPLIER_KEY, PARENT_SUPPLIER_NAME, REC_SRC, SOURCE_CREATION_DATE__YYYYMMDD, SOURCE_LAST_UPDATE_DATE__YYYYMMDD, SUPPLIER_ALT_NAME, SUPPLIER_BK, SUPPLIER_HK, SUPPLIER_NAME_1, SUPPLIER_NAME_2, SUPPLIER_NUMBER, SUPPLIER_STATUS, SUPPLIER_TYPE, UNIFIED_BKCC, UNIFIED_REC_SRC, UNIFIED_SUPPLIER_KEY, UNIFIED_SUPPLIER_NAME FROM {{ ref('pb_supplier_mdm') }} as SRC 
                        
                         )

/*
SRC_SUP            as ( SELECT * FROM BUS_VAULT.pb_supplier_mdm )
*/
---- LOGIC LAYER ----

, LOGIC_SUP as (
    SELECT
        SUPPLIER_HK
      , SUPPLIER_BK
      , MDM_SUPPLIER_BK
      , MDM_GOLDEN_RECORD
      , MDM_SUPPLIER_NAME
      , MDM_SUPPLIER_ALT_NAME
      , MDM_INDUSTRY_TYPE
      , MDM_SUPPLIER_STATUS
      , MDM_ORGANIZATION_TYPE
      , MDM_INACTIVATION_DATE__YYYYMMDD
      , MDM_SOURCE_CREATION_DATE__YYYYMMDD
      , MDM_SOURCE_LAST_UPDATE_DATE__YYYYMMDD
      , MDM_IS_DELETED
      , MDM_SOURCE_PKEY
      , SUPPLIER_NUMBER
      , SUPPLIER_NAME_1
      , SUPPLIER_NAME_2
      , SUPPLIER_ALT_NAME
      , INDUSTRY_TYPE
      , SUPPLIER_TYPE
      , SUPPLIER_STATUS
      , PARENT_SUPPLIER_KEY
      , PARENT_SUPPLIER_NAME
      , ORGANIZATION_TYPE
      , INACTIVATION_DATE__YYYYMMDD
      , SOURCE_CREATION_DATE__YYYYMMDD
      , SOURCE_LAST_UPDATE_DATE__YYYYMMDD
      , IS_DELETED
      , UNIFIED_SUPPLIER_KEY
      , UNIFIED_SUPPLIER_NAME
      , REC_SRC
      , BKCC
      , MDM_REC_SRC
      , MDM_BKCC
      , UNIFIED_REC_SRC
      , UNIFIED_BKCC
    FROM SRC_SUP
)
---- RENAME LAYER ----

, RENAME_SUP as (
    SELECT
        SUPPLIER_HK
      , SUPPLIER_BK
      , MDM_SUPPLIER_BK
      , MDM_GOLDEN_RECORD
      , MDM_SUPPLIER_NAME
      , MDM_SUPPLIER_ALT_NAME
      , MDM_INDUSTRY_TYPE
      , MDM_SUPPLIER_STATUS
      , MDM_ORGANIZATION_TYPE
      , MDM_INACTIVATION_DATE__YYYYMMDD
      , MDM_SOURCE_CREATION_DATE__YYYYMMDD
      , MDM_SOURCE_LAST_UPDATE_DATE__YYYYMMDD
      , MDM_IS_DELETED
      , MDM_SOURCE_PKEY
      , SUPPLIER_NUMBER
      , SUPPLIER_NAME_1
      , SUPPLIER_NAME_2
      , SUPPLIER_ALT_NAME
      , INDUSTRY_TYPE
      , SUPPLIER_TYPE
      , SUPPLIER_STATUS
      , PARENT_SUPPLIER_KEY
      , PARENT_SUPPLIER_NAME
      , ORGANIZATION_TYPE
      , INACTIVATION_DATE__YYYYMMDD
      , SOURCE_CREATION_DATE__YYYYMMDD
      , SOURCE_LAST_UPDATE_DATE__YYYYMMDD
      , IS_DELETED
      , UNIFIED_SUPPLIER_KEY
      , UNIFIED_SUPPLIER_NAME
      , REC_SRC
      , BKCC
      , MDM_REC_SRC
      , MDM_BKCC
      , UNIFIED_REC_SRC
      , UNIFIED_BKCC
    FROM LOGIC_SUP
)
---- FILTER LAYER ----

, FILTER_SUP as (
    SELECT *
    FROM RENAME_SUP
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM FILTER_SUP
)

---- FINAL LAYER ----
SELECT
          SUPPLIER_HK
        , SUPPLIER_BK
        , MDM_SUPPLIER_BK
        , MDM_GOLDEN_RECORD
        , MDM_SUPPLIER_NAME
        , MDM_SUPPLIER_ALT_NAME
        , MDM_INDUSTRY_TYPE
        , MDM_SUPPLIER_STATUS
        , MDM_ORGANIZATION_TYPE
        , MDM_INACTIVATION_DATE__YYYYMMDD
        , MDM_SOURCE_CREATION_DATE__YYYYMMDD
        , MDM_SOURCE_LAST_UPDATE_DATE__YYYYMMDD
        , MDM_IS_DELETED
        , MDM_SOURCE_PKEY
        , SUPPLIER_NUMBER
        , SUPPLIER_NAME_1
        , SUPPLIER_NAME_2
        , SUPPLIER_ALT_NAME
        , INDUSTRY_TYPE
        , SUPPLIER_TYPE
        , SUPPLIER_STATUS
        , PARENT_SUPPLIER_KEY
        , PARENT_SUPPLIER_NAME
        , ORGANIZATION_TYPE
        , INACTIVATION_DATE__YYYYMMDD
        , SOURCE_CREATION_DATE__YYYYMMDD
        , SOURCE_LAST_UPDATE_DATE__YYYYMMDD
        , IS_DELETED
        , UNIFIED_SUPPLIER_KEY
        , UNIFIED_SUPPLIER_NAME
        , REC_SRC
        , BKCC
        , MDM_REC_SRC
        , MDM_BKCC
        , UNIFIED_REC_SRC
        , UNIFIED_BKCC
FROM JOIN_RESULT
