---- SRC LAYER ----
WITH
SRC_PBDS           as ( SELECT ACCOUNT_ID, BKCC, CANCELLATION_REASON, DEVICE_ACCOUNT_BK, DEVICE_ACCOUNT_HK, DEVICE_ACCOUNT_LOCATION_HK, DEVICE_LOCATION_BK, DEVICE_LOCATION_HK, FIVETRAN_DELETED, FIVETRAN_SYNCED, IS_ACTIVE, PLAN_ID, PROVIDER_CUSTOMER_ID, PROVIDER_SUBSCRIPTION_ID, REC_SRC, RELATED_ENTITY, RELATED_ENTITY_ID, SOURCE_ID, STRIPE_PROVIDER_DATA, SUBSCRIPTION_PROVIDER FROM {{ ref('pb_stg_device_account_location_subscription') }} as SRC  )

/*
SRC_PBDS           as ( SELECT * FROM BUS_VAULT.PB_STG_DEVICE_ACCOUNT_LOCATION_SUBSCRIPTION )
*/
---- LOGIC LAYER ----

, LOGIC_PBDS as (
    SELECT
        DEVICE_ACCOUNT_LOCATION_HK
      , DEVICE_ACCOUNT_HK
      , DEVICE_LOCATION_HK
      , DEVICE_ACCOUNT_BK
      , DEVICE_LOCATION_BK
      , BKCC
      , REC_SRC
      , ACCOUNT_ID
      , FIVETRAN_SYNCED
      , RELATED_ENTITY_ID
      , IS_ACTIVE
      , PROVIDER_CUSTOMER_ID
      , SOURCE_ID
      , SUBSCRIPTION_PROVIDER
      , PROVIDER_SUBSCRIPTION_ID
      , STRIPE_PROVIDER_DATA
      , PLAN_ID
      , RELATED_ENTITY
      , FIVETRAN_DELETED
      , CANCELLATION_REASON
    FROM SRC_PBDS
)
---- RENAME LAYER ----

, RENAME_PBDS as (
    SELECT
        DEVICE_ACCOUNT_LOCATION_HK
      , DEVICE_ACCOUNT_HK
      , DEVICE_LOCATION_HK
      , DEVICE_ACCOUNT_BK
      , DEVICE_LOCATION_BK
      , BKCC
      , REC_SRC
      , ACCOUNT_ID
      , FIVETRAN_SYNCED
      , RELATED_ENTITY_ID
      , IS_ACTIVE
      , PROVIDER_CUSTOMER_ID
      , SOURCE_ID
      , SUBSCRIPTION_PROVIDER
      , PROVIDER_SUBSCRIPTION_ID
      , STRIPE_PROVIDER_DATA
      , PLAN_ID
      , RELATED_ENTITY
      , FIVETRAN_DELETED
      , CANCELLATION_REASON
    FROM LOGIC_PBDS
)
---- FILTER LAYER ----

, FILTER_PBDS as (
    SELECT *
    FROM RENAME_PBDS
)
---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT * FROM FILTER_PBDS
)

---- FINAL LAYER ----
SELECT
              row_number() over(order by 1)                            as SEQ_ID
        , CURRENT_DATE                                                 as SNAPSHOTDATE
        , CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP )                  as PB_LOAD_DTS
        , DEVICE_ACCOUNT_LOCATION_HK
        , DEVICE_ACCOUNT_HK
        , DEVICE_LOCATION_HK
        , DEVICE_ACCOUNT_BK
        , DEVICE_LOCATION_BK
        , BKCC
        , REC_SRC
        , ACCOUNT_ID
        , FIVETRAN_SYNCED
        , RELATED_ENTITY_ID
        , IS_ACTIVE
        , PROVIDER_CUSTOMER_ID
        , SOURCE_ID
        , SUBSCRIPTION_PROVIDER
        , PROVIDER_SUBSCRIPTION_ID
        , STRIPE_PROVIDER_DATA
        , PLAN_ID
        , RELATED_ENTITY
        , FIVETRAN_DELETED
        , CANCELLATION_REASON
FROM JOIN_RESULT
