---- SRC LAYER ----
WITH
SRC_PB             as ( SELECT BKCC_COV, BKCC_DEN, BKCC_NUM, DEVICE_FALSE_ALARMS_PER_MONTH, DEVICE_ID, FALSE_ALARM_COUNT, IS_TELEMETRY_QUALIFIED, MONTH_NUM, NUM_FLOW_EVENTS, PERIOD_START_DATE_KEY, PERIOD_TYPE, QUARTER_NUM, REC_SRC_COV, REC_SRC_DEN, REC_SRC_NUM, TOTAL_ALERT_COUNT, YEAR_NUM FROM {{ ref('pb_stg_false_positive_device_base') }} as SRC  )

/*
SRC_PB             as ( SELECT * FROM BUS_VAULT.PB_STG_FALSE_POSITIVE_DEVICE_BASE )
*/
---- LOGIC LAYER ----

, LOGIC_PB as (
    SELECT
        DEVICE_ID
      , PERIOD_TYPE
      , PERIOD_START_DATE_KEY
      , YEAR_NUM
      , QUARTER_NUM
      , MONTH_NUM
      , IS_TELEMETRY_QUALIFIED
      , FALSE_ALARM_COUNT
      , TOTAL_ALERT_COUNT
      , NUM_FLOW_EVENTS
      , BKCC_COV
      , BKCC_DEN
      , BKCC_NUM
      , REC_SRC_DEN
      , REC_SRC_COV
      , REC_SRC_NUM
      , DEVICE_FALSE_ALARMS_PER_MONTH
    FROM SRC_PB
)
---- RENAME LAYER ----

, RENAME_PB as (
    SELECT
        DEVICE_ID
      , PERIOD_TYPE
      , PERIOD_START_DATE_KEY
      , YEAR_NUM
      , QUARTER_NUM
      , MONTH_NUM
      , IS_TELEMETRY_QUALIFIED
      , FALSE_ALARM_COUNT
      , TOTAL_ALERT_COUNT
      , NUM_FLOW_EVENTS
      , BKCC_COV
      , BKCC_DEN
      , BKCC_NUM
      , REC_SRC_DEN
      , REC_SRC_COV
      , REC_SRC_NUM
      , DEVICE_FALSE_ALARMS_PER_MONTH
    FROM LOGIC_PB
)
---- FILTER LAYER ----

, FILTER_PB as (
    SELECT *
    FROM RENAME_PB
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM FILTER_PB
)

---- FINAL LAYER ----
SELECT
              row_number() over(order by 1)                            as SEQ_ID
        , CURRENT_DATE                                                 as SNAPSHOTDATE
        , CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP )                  as PB_LOAD_DTS
        , PERIOD_TYPE
        , PERIOD_START_DATE_KEY
        , YEAR_NUM
        , QUARTER_NUM
        , MONTH_NUM
        , COUNT(DISTINCT CASE WHEN IS_TELEMETRY_QUALIFIED = 1 THEN DEVICE_ID END) as QUALIFIED_DEVICE_COUNT
        , SUM(CASE WHEN IS_TELEMETRY_QUALIFIED = 1 THEN FALSE_ALARM_COUNT ELSE 0 END) as FALSE_ALARM_COUNT
        , SUM(CASE WHEN IS_TELEMETRY_QUALIFIED = 1 THEN TOTAL_ALERT_COUNT ELSE 0 END) as TOTAL_ALERT_COUNT
        , SUM(CASE WHEN IS_TELEMETRY_QUALIFIED = 1 THEN NUM_FLOW_EVENTS ELSE 0 END) as NUM_FLOW_EVENTS
        , SUM(CASE WHEN IS_TELEMETRY_QUALIFIED = 1 THEN FALSE_ALARM_COUNT ELSE 0 END)
/ NULLIF(SUM(CASE WHEN IS_TELEMETRY_QUALIFIED = 1 THEN NUM_FLOW_EVENTS ELSE 0 END), 0) as FALSE_POSITIVE_RATE
        , MIN(COALESCE(BKCC_DEN, BKCC_COV, BKCC_NUM))                  as BKCC
        , MIN(COALESCE(REC_SRC_DEN, REC_SRC_COV, REC_SRC_NUM))         as REC_SRC
        , AVG(CASE WHEN IS_TELEMETRY_QUALIFIED = 1
             THEN DEVICE_FALSE_ALARMS_PER_MONTH
        END) as AVG_FALSE_ALARMS_PER_MONTH
FROM JOIN_RESULT
GROUP BY
PERIOD_TYPE,
PERIOD_START_DATE_KEY,
YEAR_NUM,
QUARTER_NUM,
MONTH_NUM