WITH
SRC_hdr AS (
    SELECT ID AS SHOPIFY_NUMERIC_ID, NAME AS ORDER_ID, EMAIL, PROCESSED_AT,
           SHIPPING_ADDRESS_FIRST_NAME, SHIPPING_ADDRESS_LAST_NAME,
           SHIPPING_ADDRESS_PHONE, SHIPPING_ADDRESS_ADDRESS_1, SHIPPING_ADDRESS_ADDRESS_2,
           SHIPPING_ADDRESS_CITY, SHIPPING_ADDRESS_PROVINCE_CODE, SHIPPING_ADDRESS_ZIP,
           TOTAL_DISCOUNTS, PAYMENT_GATEWAY_NAMES, NOTE_ATTRIBUTES, UPDATED_AT,
           LNK_ORDER_CUSTOMER_CONSUMER_HK, _FIVETRAN_DELETED, PSA_DELETE_IND
    FROM {{ ref('lsat_order_customer_consumer__winn_shopify') }}
    QUALIFY ROW_NUMBER() OVER (PARTITION BY LNK_ORDER_CUSTOMER_CONSUMER_HK ORDER BY LOAD_DTS DESC) = 1
),
FILTER_hdr AS (
    SELECT SHOPIFY_NUMERIC_ID, ORDER_ID, EMAIL, PROCESSED_AT,
           SHIPPING_ADDRESS_FIRST_NAME, SHIPPING_ADDRESS_LAST_NAME,
           SHIPPING_ADDRESS_PHONE, SHIPPING_ADDRESS_ADDRESS_1, SHIPPING_ADDRESS_ADDRESS_2,
           SHIPPING_ADDRESS_CITY, SHIPPING_ADDRESS_PROVINCE_CODE, SHIPPING_ADDRESS_ZIP,
           TOTAL_DISCOUNTS, PAYMENT_GATEWAY_NAMES, NOTE_ATTRIBUTES, UPDATED_AT,
           LNK_ORDER_CUSTOMER_CONSUMER_HK
    FROM SRC_hdr
),
SRC_ol AS (
    SELECT ORDER_ID, ID AS ORDER_LINE_ID, INDEX, VARIANT_ID, SKU, PRICE, QUANTITY, ORDER_ORDER_LINE_HK, PSA_DELETE_IND
    FROM {{ ref('lsat_order_order_line__winn_shopify') }}
    QUALIFY ROW_NUMBER() OVER (PARTITION BY ORDER_ORDER_LINE_HK ORDER BY LOAD_DTS DESC) = 1
),
FILTER_ol AS (
    SELECT ORDER_ID, ORDER_LINE_ID, INDEX, VARIANT_ID, SKU, PRICE, QUANTITY, ORDER_ORDER_LINE_HK
    FROM SRC_ol
),
SRC_pv AS (
    SELECT ID AS VARIANT_ID, SKU, TITLE, BKCC, REC_SRC, PSA_DELETE_IND
    FROM {{ ref('lsat_product_variant__winn_shopify') }}
    WHERE SKU IN ('900-002-KIT1','900-006-KIT1')
    QUALIFY ROW_NUMBER() OVER (PARTITION BY ID ORDER BY LOAD_DTS DESC) = 1
),
FILTER_pv AS (
    SELECT VARIANT_ID, SKU, TITLE, BKCC, REC_SRC
    FROM SRC_pv
),
SRC_ff AS (
    SELECT ORDER_ID, NAME AS FULFILLMENT_NAME, SHIPMENT_STATUS, UPDATED_AT, PSA_DELETE_IND
    FROM {{ ref('lsat_order_fulfillment__winn_shopify') }}
    QUALIFY ROW_NUMBER() OVER (PARTITION BY ORDER_ID, NAME ORDER BY LOAD_DTS DESC) = 1
),
FILTER_ff AS (
    SELECT ORDER_ID, FULFILLMENT_NAME, SHIPMENT_STATUS, UPDATED_AT
    FROM SRC_ff
),
SRC_olr AS (
    SELECT ORDER_LINE_ID, QUANTITY AS REFUND_QUANTITY, PSA_DELETE_IND
    FROM {{ ref('sat_order_line_refund__winn_shopify') }}
    QUALIFY ROW_NUMBER() OVER (PARTITION BY ORDER_LINE_ID ORDER BY LOAD_DTS DESC) = 1
),
FILTER_olr AS (
    SELECT ORDER_LINE_ID, REFUND_QUANTITY
    FROM SRC_olr
),
SRC_rfd AS (
    SELECT ORDER_ID, CREATED_AT, PSA_DELETE_IND
    FROM {{ ref('lsat_order_refund__winn_shopify') }}
),
FILTER_rfd AS (
    SELECT ORDER_ID, CREATED_AT
    FROM SRC_rfd
),
rfd AS (
    SELECT ORDER_ID, MAX(CREATED_AT) AS REFUND_CREATED_AT
    FROM FILTER_rfd GROUP BY ORDER_ID
),
SRC_otag AS (
    SELECT ORDER_ID, VALUE AS ORDER_TAG, INDEX, PSA_DELETE_IND
    FROM {{ ref('msat_order_tag__winn_shopify') }}
    QUALIFY ROW_NUMBER() OVER (PARTITION BY ORDER_ID, INDEX ORDER BY LOAD_DTS DESC) = 1
),
FILTER_otag AS (
    SELECT ORDER_ID, ORDER_TAG, INDEX
    FROM SRC_otag
),
SRC_discount AS (
    SELECT ORDER_ID, CODE, PSA_DELETE_IND
    FROM {{ ref('msat_order_discount__winn_shopify') }}
),
FILTER_discount AS (
    SELECT ORDER_ID, CODE
    FROM SRC_discount
),
discount AS (
    SELECT ORDER_ID, FIRST_VALUE(CODE) OVER (PARTITION BY ORDER_ID ORDER BY CODE NULLS LAST) AS CODE
    FROM FILTER_discount
    QUALIFY ROW_NUMBER() OVER (PARTITION BY ORDER_ID ORDER BY CODE NULLS LAST) = 1
),
root_kit_orders AS (
    SELECT FILTER_otag.ORDER_TAG, FILTER_hdr.SHOPIFY_NUMERIC_ID, FILTER_hdr.ORDER_ID, FILTER_hdr.PROCESSED_AT AS ORDER_DATE,
           FILTER_hdr.SHIPPING_ADDRESS_FIRST_NAME AS ORDER_FIRST_NAME, FILTER_hdr.SHIPPING_ADDRESS_LAST_NAME AS ORDER_LAST_NAME,
           FILTER_hdr.EMAIL AS ORDER_EMAIL,
           LTRIM(REPLACE(REPLACE(REPLACE(REGEXP_REPLACE(FILTER_hdr.SHIPPING_ADDRESS_PHONE,'[()\\-]',''),'+1',''),' ',''),'+',''),'1') AS ORDER_PHONE,
           FILTER_hdr.SHIPPING_ADDRESS_ADDRESS_1 AS ORDER_ADDRESS_1, FILTER_hdr.SHIPPING_ADDRESS_ADDRESS_2 AS ORDER_ADDRESS_2,
           FILTER_hdr.SHIPPING_ADDRESS_CITY AS ORDER_CITY, FILTER_hdr.SHIPPING_ADDRESS_PROVINCE_CODE AS ORDER_STATE,
           SPLIT_PART(FILTER_hdr.SHIPPING_ADDRESS_ZIP,'-',1) AS ORDER_POSTCODE,
           SPLIT_PART(FILTER_hdr.SHIPPING_ADDRESS_ZIP,'-',2) AS ORDER_POSTCODE_ADD_ON,
           CASE WHEN FILTER_ff.SHIPMENT_STATUS IS NULL AND COALESCE(FILTER_olr.REFUND_QUANTITY,0) = 0 THEN 'order_placed'
                WHEN COALESCE(FILTER_olr.REFUND_QUANTITY,0) = FILTER_ol.QUANTITY THEN 'cancelled/returned'
                ELSE FILTER_ff.SHIPMENT_STATUS END AS ORDER_STATUS,
           1 AS ORDER_QUANTITY, NVL2(FILTER_olr.REFUND_QUANTITY, 1, 0) AS RETURN_QUANTITY,
           FILTER_ol.PRICE * FILTER_ol.QUANTITY AS ORDER_VALUE, FILTER_hdr.TOTAL_DISCOUNTS AS DISCOUNT_VALUE,
           discount.CODE AS DISCOUNT_CODE,
           CASE WHEN FILTER_ff.SHIPMENT_STATUS = 'delivered' THEN FILTER_ff.UPDATED_AT END AS ACTUAL_DELIVERY_DATE,
           FILTER_pv.SKU, FILTER_pv.TITLE AS VALVE_SIZE,
           COALESCE(rfd.REFUND_CREATED_AT, IFF(FILTER_ff.SHIPMENT_STATUS='delivered', FILTER_ff.UPDATED_AT, NULL), FILTER_hdr.UPDATED_AT) AS LASTMODIFIED,
           FILTER_hdr.PAYMENT_GATEWAY_NAMES, FILTER_hdr.NOTE_ATTRIBUTES, FILTER_ol.ORDER_LINE_ID,
           FILTER_pv.BKCC AS BKCC, FILTER_pv.REC_SRC AS REC_SRC
    FROM FILTER_ol
    JOIN FILTER_hdr ON FILTER_hdr.SHOPIFY_NUMERIC_ID = FILTER_ol.ORDER_ID
    JOIN FILTER_pv  ON FILTER_pv.VARIANT_ID = FILTER_ol.VARIANT_ID
    LEFT JOIN FILTER_ff ON CONCAT(FILTER_hdr.ORDER_ID,'.',FILTER_ol.INDEX) = FILTER_ff.FULFILLMENT_NAME AND FILTER_hdr.SHOPIFY_NUMERIC_ID = FILTER_ff.ORDER_ID
    LEFT JOIN FILTER_olr ON FILTER_olr.ORDER_LINE_ID = FILTER_ol.ORDER_LINE_ID
    LEFT JOIN rfd ON rfd.ORDER_ID = FILTER_hdr.SHOPIFY_NUMERIC_ID
    LEFT JOIN FILTER_otag ON FILTER_otag.ORDER_ID = FILTER_hdr.SHOPIFY_NUMERIC_ID
    LEFT JOIN discount ON discount.ORDER_ID = FILTER_hdr.SHOPIFY_NUMERIC_ID
),

-- resurrection-safe: QUALIFY picks latest row first (including soft-deletes),
-- then the _all → named-CTE split filters them out afterward.
SRC_po AS (
    SELECT EXTERNAL_ID, SUBSCRIBER_ID, _FIVETRAN_DELETED, PSA_DELETE_IND
    FROM {{ ref('lsat_subscription_order__winn_prive') }}
    WHERE EXTERNAL_ID LIKE 'gid://shopify/Order/%'
    QUALIFY ROW_NUMBER() OVER (PARTITION BY LNK_SUBSCRIPTION_ORDER_HK ORDER BY LOAD_DTS DESC) = 1
),
FILTER_po AS (
    SELECT EXTERNAL_ID, SUBSCRIBER_ID
    FROM SRC_po
),
SRC_sub AS (
    SELECT SUBSCRIBER_ID, STATUS, _FIVETRAN_DELETED, PSA_DELETE_IND
    FROM {{ ref('sat_subscription__winn_prive') }}
    QUALIFY ROW_NUMBER() OVER (PARTITION BY SUBSCRIPTION_HK ORDER BY LOAD_DTS DESC) = 1
),
FILTER_sub AS (
    SELECT SUBSCRIBER_ID, STATUS
    FROM SRC_sub
),
subscription_emi_data AS (
    SELECT
        TRY_CAST(REPLACE(FILTER_po.EXTERNAL_ID, 'gid://shopify/Order/', '') AS NUMBER) AS SHOPIFY_NUMERIC_ID,
        IFF(FILTER_sub.STATUS = 'ACTIVE', TRUE, FALSE) AS SUBSCRIPTION_STATUS_FLAG
    FROM FILTER_po
    JOIN FILTER_sub ON FILTER_po.SUBSCRIBER_ID = FILTER_sub.SUBSCRIBER_ID
    -- SHOPIFY_NUMERIC_ID IS NOT NULL: any EXTERNAL_ID that passes the LIKE but has a non-numeric
    -- suffix becomes NULL after TRY_CAST; without this guard all NULLs collapse into one
    -- partition and exactly one bad row survives into the output.
    QUALIFY ROW_NUMBER() OVER (PARTITION BY SHOPIFY_NUMERIC_ID ORDER BY SUBSCRIPTION_STATUS_FLAG DESC) = 1
        AND SHOPIFY_NUMERIC_ID IS NOT NULL
),
ist_orders AS (
    SELECT FILTER_hdr.ORDER_ID
    FROM FILTER_ol
    JOIN FILTER_hdr ON FILTER_hdr.SHOPIFY_NUMERIC_ID = FILTER_ol.ORDER_ID
    WHERE FILTER_ol.SKU = 'IST900'
    QUALIFY ROW_NUMBER() OVER (PARTITION BY FILTER_hdr.ORDER_ID ORDER BY 1) = 1
),
base_kit_orders AS (
    SELECT rko.*,
           CASE WHEN ist.ORDER_ID IS NOT NULL THEN TRUE ELSE FALSE END AS INSTALLATION_FLAG,
           COALESCE(sed.SUBSCRIPTION_STATUS_FLAG, FALSE) AS SUBSCRIPTION_FLAG,
           IFF(ARRAY_CONTAINS('Affirm'::VARIANT, rko.PAYMENT_GATEWAY_NAMES), TRUE, FALSE) AS AFFIRM_FLAG
    FROM root_kit_orders rko
    LEFT JOIN ist_orders ist ON ist.ORDER_ID = rko.ORDER_ID
    LEFT JOIN subscription_emi_data sed ON sed.SHOPIFY_NUMERIC_ID = rko.SHOPIFY_NUMERIC_ID
),
note_flattened AS (
    SELECT rko.ORDER_ID, j.VALUE:name::STRING AS note_key, j.VALUE:value::STRING AS note_value
    FROM root_kit_orders rko, LATERAL FLATTEN(INPUT => rko.NOTE_ATTRIBUTES) j
),
order_note AS (
    SELECT ORDER_ID,
           MAX(CASE WHEN note_key = '_partner_code'              THEN note_value END) AS PARTNER_CODE,
           MAX(CASE WHEN note_key = '_partner_number'            THEN note_value END) AS PARTNER_NUMBER,
           MAX(CASE WHEN note_key = 'utility_account_number'     THEN note_value END) AS UTILITY_ACCOUNT_NUMBER,
           MAX(CASE WHEN note_key = 'installation_address_line1' THEN note_value END) AS INSTALLATION_ADDRESS_LINE1,
           MAX(CASE WHEN note_key = 'installation_address_line2' THEN note_value END) AS INSTALLATION_ADDRESS_LINE2,
           MAX(CASE WHEN note_key = 'installation_city'          THEN note_value END) AS INSTALLATION_CITY,
           MAX(CASE WHEN note_key = 'installation_state'         THEN note_value END) AS INSTALLATION_STATE,
           MAX(CASE WHEN note_key = 'installation_zip'           THEN note_value END) AS INSTALLATION_ZIP
    FROM note_flattened
    WHERE note_key IN ('_partner_code','_partner_number','utility_account_number',
                       'installation_address_line1','installation_address_line2',
                       'installation_city','installation_state','installation_zip')
    GROUP BY ORDER_ID
)
SELECT
    ROW_NUMBER() OVER (ORDER BY 1)             AS SEQ_ID,
    CURRENT_DATE                               AS SNAPSHOTDATE,
    CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP) AS PB_LOAD_DTS,
    bko.ORDER_TAG, bko.SHOPIFY_NUMERIC_ID, bko.ORDER_ID,
    bko.BKCC, bko.REC_SRC,
    bko.ORDER_DATE,
    bko.ORDER_FIRST_NAME, bko.ORDER_LAST_NAME, bko.ORDER_EMAIL, bko.ORDER_PHONE,
    bko.ORDER_ADDRESS_1, bko.ORDER_ADDRESS_2, bko.ORDER_CITY, bko.ORDER_STATE,
    bko.ORDER_POSTCODE, bko.ORDER_POSTCODE_ADD_ON,
    bko.ORDER_STATUS, bko.ORDER_QUANTITY, bko.RETURN_QUANTITY,
    bko.ORDER_VALUE, bko.DISCOUNT_VALUE, bko.DISCOUNT_CODE,
    bko.ACTUAL_DELIVERY_DATE, bko.SKU, bko.VALVE_SIZE, bko.LASTMODIFIED,
    bko.INSTALLATION_FLAG, bko.SUBSCRIPTION_FLAG, bko.AFFIRM_FLAG,
    onote.PARTNER_CODE, onote.PARTNER_NUMBER, onote.UTILITY_ACCOUNT_NUMBER,
    onote.INSTALLATION_ADDRESS_LINE1, onote.INSTALLATION_ADDRESS_LINE2,
    onote.INSTALLATION_CITY, onote.INSTALLATION_STATE, onote.INSTALLATION_ZIP,
    bko.ORDER_LINE_ID
FROM base_kit_orders bko
LEFT JOIN order_note onote ON onote.ORDER_ID = bko.ORDER_ID
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY bko.ORDER_ID, bko.SKU, bko.ORDER_LINE_ID, COALESCE(bko.ORDER_TAG,'_no_tag_')
    ORDER BY bko.LASTMODIFIED         DESC NULLS LAST,
             bko.ACTUAL_DELIVERY_DATE DESC NULLS LAST,
             bko.ORDER_LINE_ID        ASC  NULLS LAST
) = 1