WITH
frontdoor AS (
    SELECT ORDER_ID, CORRECT_ORDER_ID_FOR_INSTALL, FRONTDOOR_INSTALL_DATE
    FROM {{ source('reference', 'frontdoor_orderid_installdates') }}
),
frontdoor_excluded_orderids AS (
    SELECT ORDER_ID AS ORDERID FROM frontdoor
    UNION SELECT CORRECT_ORDER_ID_FOR_INSTALL FROM frontdoor
),
installer_event AS (
    SELECT ORDERID, LIFNR, POSNR, PRODUCTINSTALLED,
           TRY_TO_DATE(INSTALLDATE,'YYYYMMDD') AS INSTALL_DATE,
           SERVICENAME, BKCC, REC_SRC
    FROM {{ ref('lsat_installation_event__winn_sap') }}
    QUALIFY ROW_NUMBER() OVER (PARTITION BY LNK_INSTALLATION_DETAIL_HK ORDER BY LOAD_DTS DESC) = 1
),
installer_filtered AS (
    SELECT ORDERID, LIFNR, POSNR, PRODUCTINSTALLED,
           MAX(INSTALL_DATE) AS INSTALL_DATE,
           MAX(BKCC) AS BKCC, MAX(REC_SRC) AS REC_SRC
    FROM installer_event
    WHERE UPPER(COALESCE(SERVICENAME,'')) NOT LIKE '%FAILED%'
      AND NOT EXISTS (
          SELECT 1 FROM frontdoor_excluded_orderids fe
          WHERE fe.ORDERID = installer_event.ORDERID
      )
    GROUP BY ORDERID, LIFNR, POSNR, PRODUCTINSTALLED
),
supplier AS (
    SELECT LIFNR, NAME1
    FROM {{ ref('sat_supplier__winn_sap') }}
    QUALIFY ROW_NUMBER() OVER (PARTITION BY SUPPLIER_HK ORDER BY LOAD_DTS DESC) = 1
),
sap_installer AS (
    SELECT i.ORDERID AS ORDER_ID, i.PRODUCTINSTALLED AS PRODUCT_INSTALLED, i.POSNR,
           i.INSTALL_DATE, i.LIFNR AS VENDOR_ID, s.NAME1 AS VENDOR_NAME,
           i.BKCC AS BKCC, i.REC_SRC AS REC_SRC,
           'SAP_INSTALLER' AS INSTALL_SOURCE_PATH
    FROM installer_filtered i
    LEFT JOIN supplier s ON s.LIFNR = i.LIFNR
),
frontdoor_null AS (
    SELECT ORDER_ID,
           CAST(NULL AS VARCHAR) AS PRODUCT_INSTALLED, CAST(NULL AS VARCHAR) AS POSNR,
           CAST(NULL AS DATE) AS INSTALL_DATE,
           CAST(NULL AS VARCHAR) AS VENDOR_ID, CAST(NULL AS VARCHAR) AS VENDOR_NAME,
           CAST(NULL AS VARCHAR) AS BKCC,
           'BRONZE.REFERENCE.FRONTDOOR_ORDERID_INSTALLDATES' AS REC_SRC,
           'FRONTDOOR_NULL' AS INSTALL_SOURCE_PATH
    FROM frontdoor
),
frontdoor_corrected AS (
    SELECT CORRECT_ORDER_ID_FOR_INSTALL AS ORDER_ID,
           CAST(NULL AS VARCHAR) AS PRODUCT_INSTALLED, CAST(NULL AS VARCHAR) AS POSNR,
           FRONTDOOR_INSTALL_DATE AS INSTALL_DATE,
           CAST(NULL AS VARCHAR) AS VENDOR_ID, CAST(NULL AS VARCHAR) AS VENDOR_NAME,
           CAST(NULL AS VARCHAR) AS BKCC,
           'BRONZE.REFERENCE.FRONTDOOR_ORDERID_INSTALLDATES' AS REC_SRC,
           'FRONTDOOR_CROSSREF' AS INSTALL_SOURCE_PATH
    FROM frontdoor
),
union_all as (
SELECT        
       ORDER_ID, PRODUCT_INSTALLED, BKCC, REC_SRC, POSNR, INSTALL_DATE,
       VENDOR_ID, VENDOR_NAME, INSTALL_SOURCE_PATH FROM sap_installer
UNION ALL
SELECT        
       ORDER_ID, PRODUCT_INSTALLED, BKCC, REC_SRC, POSNR, INSTALL_DATE,
       VENDOR_ID, VENDOR_NAME, INSTALL_SOURCE_PATH FROM frontdoor_null
UNION ALL
SELECT        
       ORDER_ID, PRODUCT_INSTALLED, BKCC, REC_SRC, POSNR, INSTALL_DATE,
       VENDOR_ID, VENDOR_NAME, INSTALL_SOURCE_PATH FROM frontdoor_corrected
)
select ROW_NUMBER() OVER (ORDER BY 1) AS SEQ_ID,
CURRENT_DATE AS SNAPSHOTDATE,
CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP) AS PB_LOAD_DTS,
* from union_all