---- SRC LAYER ----
WITH
SRC_S1             as ( SELECT * FROM {{ source('delighted_hyd_psa', 'response') }} as SRC  ),
SRC_A1             as ( SELECT * FROM {{ ref('ref_business_key_collision') }} as SRC  ),
SRC_S2             as ( SELECT * FROM {{ source('reference_psa', 'ref_product_delighted') }} as SRC 
                        WHERE PRODUCT_NAME =  'SI' )

/*
SRC_S1             as ( SELECT * FROM delighted_hyd_psa.response )
, SRC_A1             as ( SELECT * FROM raw_vault.ref_business_key_collision )
, SRC_S2             as ( SELECT * FROM reference_psa.ref_product_delighted )
*/
---- LOGIC LAYER ----

, LOGIC_S1 as (
    SELECT
        CONVERT_TIMEZONE('UTC',to_timestamp(cast(updated_at as varchar))) as                                           LOAD_DTS
      , ID
      , _FIVETRAN_DELETED
      , PERSON_ID
      , _FIVETRAN_SYNCED
      , PROPERTIES_CONTEXT_PERSONAS_SPACE_ID
      , PROPERTIES_DELIGHTED_BROWSER
      , PROPERTIES_DELIGHTED_SOURCE
      , PROPERTIES_SEGMENT_TRIGGER_MESSAGE_ID
      , PROPERTIES_AUDIENCE_KEY
      , PROPERTIES_SWN_SPRINKLER_CUSTOMERS
      , PROPERTIES_CONTEXT_PERSONAS_COMPUTATION_KEY
      , CREATED_AT
      , PROPERTIES_DELIGHTED_OPERATING_SYSTEM
      , SCORE
      , UPDATED_AT
      , PROPERTIES_CONTEXT_LIBRARY_NAME
      , PROPERTIES_CONTEXT_PERSONAS_COMPUTATION_CLASS
      , PROPERTIES_CONTEXT_LIBRARY_VERSION
      , PROPERTIES_CONTEXT_TRAITS_EMAIL
      , PROPERTIES_TRAITS_SWN_SPRINKLER_CUSTOMERS
      , PROPERTIES_CONTEXT_SEGMENT_INTERNAL_CREATOR
      , SURVEY_TYPE
      , PROPERTIES_CONTEXT_PERSONAS_COMPUTATION_ID
      , PROPERTIES_CONTEXT_PERSONAS_NAMESPACE
      , PROPERTIES_SEGMENT_USER_ID
      , COMMENT
      , PERMALINK
      , PROPERTIES_DELIGHTED_DEVICE_TYPE
      , PROPERTIES_TRAITS_NAB_DEVICE_ADDED
      , PSA_LOAD_DTS
      , PSA_RECORD_SOURCE
      , PSA_DELETE_IND
    FROM SRC_S1
)

, LOGIC_A1 as (
    SELECT
        REC_SRC
      , BKCC
    FROM SRC_A1
)

, LOGIC_S2 as (
    SELECT
        PRODUCT_NAME                                                 as                                         PRODUCT_BK
    FROM SRC_S2
)
---- RENAME LAYER ----

, RENAME_S2 as (
    SELECT
        PRODUCT_BK
    FROM LOGIC_S2
)

, RENAME_S1 as (
    SELECT
        LOAD_DTS
      , ID
      , _FIVETRAN_DELETED
      , PERSON_ID
      , _FIVETRAN_SYNCED
      , PROPERTIES_CONTEXT_PERSONAS_SPACE_ID
      , PROPERTIES_DELIGHTED_BROWSER
      , PROPERTIES_DELIGHTED_SOURCE
      , PROPERTIES_SEGMENT_TRIGGER_MESSAGE_ID
      , PROPERTIES_AUDIENCE_KEY
      , PROPERTIES_SWN_SPRINKLER_CUSTOMERS
      , PROPERTIES_CONTEXT_PERSONAS_COMPUTATION_KEY
      , CREATED_AT
      , PROPERTIES_DELIGHTED_OPERATING_SYSTEM
      , SCORE
      , UPDATED_AT
      , PROPERTIES_CONTEXT_LIBRARY_NAME
      , PROPERTIES_CONTEXT_PERSONAS_COMPUTATION_CLASS
      , PROPERTIES_CONTEXT_LIBRARY_VERSION
      , PROPERTIES_CONTEXT_TRAITS_EMAIL
      , PROPERTIES_TRAITS_SWN_SPRINKLER_CUSTOMERS
      , PROPERTIES_CONTEXT_SEGMENT_INTERNAL_CREATOR
      , SURVEY_TYPE
      , PROPERTIES_CONTEXT_PERSONAS_COMPUTATION_ID
      , PROPERTIES_CONTEXT_PERSONAS_NAMESPACE
      , PROPERTIES_SEGMENT_USER_ID
      , COMMENT
      , PERMALINK
      , PROPERTIES_DELIGHTED_DEVICE_TYPE
      , PROPERTIES_TRAITS_NAB_DEVICE_ADDED
      , PSA_LOAD_DTS
      , PSA_RECORD_SOURCE
      , PSA_DELETE_IND
    FROM LOGIC_S1
)

, RENAME_A1 as (
    SELECT
        REC_SRC
      , BKCC
    FROM LOGIC_A1
)
---- FILTER LAYER ----

, FILTER_S1 as (
    SELECT *
    FROM RENAME_S1
)

, FILTER_A1 as (
    SELECT *
    FROM RENAME_A1
    WHERE rec_src = 'US.DELIGHTED_HYDRA.RESPONSE'
)

, FILTER_S2 as (
    SELECT *
    FROM RENAME_S2
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM FILTER_S1
    INNER JOIN FILTER_A1
        ON '1' = '1'
    INNER JOIN FILTER_S2
        ON '1' = '1'
)

---- FINAL LAYER ----
SELECT
          PRODUCT_BK
        , LOAD_DTS
        , ID
        , _FIVETRAN_DELETED
        , PERSON_ID
        , _FIVETRAN_SYNCED
        , PROPERTIES_CONTEXT_PERSONAS_SPACE_ID
        , PROPERTIES_DELIGHTED_BROWSER
        , PROPERTIES_DELIGHTED_SOURCE
        , PROPERTIES_SEGMENT_TRIGGER_MESSAGE_ID
        , PROPERTIES_AUDIENCE_KEY
        , PROPERTIES_SWN_SPRINKLER_CUSTOMERS
        , PROPERTIES_CONTEXT_PERSONAS_COMPUTATION_KEY
        , CREATED_AT
        , PROPERTIES_DELIGHTED_OPERATING_SYSTEM
        , SCORE
        , UPDATED_AT
        , PROPERTIES_CONTEXT_LIBRARY_NAME
        , PROPERTIES_CONTEXT_PERSONAS_COMPUTATION_CLASS
        , PROPERTIES_CONTEXT_LIBRARY_VERSION
        , PROPERTIES_CONTEXT_TRAITS_EMAIL
        , PROPERTIES_TRAITS_SWN_SPRINKLER_CUSTOMERS
        , PROPERTIES_CONTEXT_SEGMENT_INTERNAL_CREATOR
        , SURVEY_TYPE
        , PROPERTIES_CONTEXT_PERSONAS_COMPUTATION_ID
        , PROPERTIES_CONTEXT_PERSONAS_NAMESPACE
        , PROPERTIES_SEGMENT_USER_ID
        , COMMENT
        , PERMALINK
        , PROPERTIES_DELIGHTED_DEVICE_TYPE
        , PROPERTIES_TRAITS_NAB_DEVICE_ADDED
        , PSA_LOAD_DTS
        , PSA_RECORD_SOURCE
        , PSA_DELETE_IND
        , REC_SRC
        , BKCC
        , MD5_BINARY(UPPER(CONCAT_WS('||',
          COALESCE(NULLIF(TRIM(CAST(PRODUCT_BK as VARCHAR)),''), '^^')
        , COALESCE(NULLIF(TRIM(CAST(BKCC as VARCHAR)),''), '^^')
        ))) as PRODUCT_HK
        , MD5_BINARY(UPPER(NULLIF(CONCAT(
              IFNULL(TRIM(ID::text), '^^') 
            , '||', IFNULL(TRIM(PERSON_ID::text), '^^') 
            , '||', IFNULL(TRIM(PROPERTIES_CONTEXT_PERSONAS_SPACE_ID::text), '^^') 
            , '||', IFNULL(TRIM(PROPERTIES_DELIGHTED_BROWSER::text), '^^') 
            , '||', IFNULL(TRIM(PROPERTIES_DELIGHTED_SOURCE::text), '^^') 
            , '||', IFNULL(TRIM(PROPERTIES_SEGMENT_TRIGGER_MESSAGE_ID::text), '^^') 
            , '||', IFNULL(TRIM(PROPERTIES_AUDIENCE_KEY::text), '^^') 
            , '||', IFNULL(TRIM(PROPERTIES_SWN_SPRINKLER_CUSTOMERS::text), '^^') 
            , '||', IFNULL(TRIM(PROPERTIES_CONTEXT_PERSONAS_COMPUTATION_KEY::text), '^^') 
            , '||', IFNULL(TRIM(CREATED_AT::text), '^^') 
            , '||', IFNULL(TRIM(PROPERTIES_DELIGHTED_OPERATING_SYSTEM::text), '^^') 
            , '||', IFNULL(TRIM(SCORE::text), '^^') 
            , '||', IFNULL(TRIM(PROPERTIES_CONTEXT_LIBRARY_NAME::text), '^^') 
            , '||', IFNULL(TRIM(PROPERTIES_CONTEXT_PERSONAS_COMPUTATION_CLASS::text), '^^') 
            , '||', IFNULL(TRIM(PROPERTIES_CONTEXT_LIBRARY_VERSION::text), '^^') 
            , '||', IFNULL(TRIM(PROPERTIES_CONTEXT_TRAITS_EMAIL::text), '^^') 
            , '||', IFNULL(TRIM(PROPERTIES_TRAITS_SWN_SPRINKLER_CUSTOMERS::text), '^^') 
            , '||', IFNULL(TRIM(PROPERTIES_CONTEXT_SEGMENT_INTERNAL_CREATOR::text), '^^') 
            , '||', IFNULL(TRIM(SURVEY_TYPE::text), '^^') 
            , '||', IFNULL(TRIM(PROPERTIES_CONTEXT_PERSONAS_COMPUTATION_ID::text), '^^') 
            , '||', IFNULL(TRIM(PROPERTIES_CONTEXT_PERSONAS_NAMESPACE::text), '^^') 
            , '||', IFNULL(TRIM(PROPERTIES_SEGMENT_USER_ID::text), '^^') 
            , '||', IFNULL(TRIM(COMMENT::text), '^^') 
            , '||', IFNULL(TRIM(PERMALINK::text), '^^') 
            , '||', IFNULL(TRIM(PROPERTIES_DELIGHTED_DEVICE_TYPE::text), '^^') 
            , '||', IFNULL(TRIM(PROPERTIES_TRAITS_NAB_DEVICE_ADDED::text), '^^') 
        ), '^^||^^')))  as HASHDIFF
FROM JOIN_RESULT
