SELECT *
FROM (
    {{
        check_not_null_v2(
            'fact_device_telemetry',
            [
                'PAIRED_DEVICE_BK',
                'DEVICE_BK',
                'BKCC',
                'REC_SRC',
                'AGGREGATE_DATE',
                'GALLONS',
                'MAX_GPM',
                'MIN_PRESSURE',
                'MAX_PRESSURE',
                'AVG_PRESSURE',
                'MIN_TEMPERATURE',
                'MAX_TEMPERATURE',
                'AVG_TEMPERATURE',
                'RECORDS',
                'FLOW_RECORDS',
                'CREATED_AT',
                'UPDATED_AT',
                'MEDIAN_GPS',
                'P_STATIC'
            ],
            'REC_SRC',
            'US.FLO_DYNAMODB.PROD_ICD'
        )
    }}
)