---- SRC LAYER ----
WITH
SRC_S              as ( SELECT * FROM {{ source('ml_ebs_inv', 'mtl_system_items_b') }} as SRC  ),
SRC_A              as ( SELECT * FROM {{ ref('ref_business_key_collision') }} as SRC  ),
SRC_S2             as ( SELECT * FROM {{ source('ml_ebs_inv', 'mtl_parameters') }} as SRC 
                        qualify 1 = row_number()over (partition by organization_id order by psa_load_dts )  )

/*
SRC_S              as ( SELECT * FROM ml_ebs_inv.mtl_system_items_b )
, SRC_A              as ( SELECT * FROM raw_vault.ref_business_key_collision )
, SRC_S2             as ( SELECT * FROM ml_ebs_inv.mtl_parameters )
*/
---- LOGIC LAYER ----

, LOGIC_S as (
    SELECT
        SEGMENT1                                                     as                                            ITEM_BK
      , SEGMENT1
      , INVENTORY_ITEM_ID
      , ORGANIZATION_ID
      , WIP_SUPPLY_LOCATOR_ID
      , ATTRIBUTE30
      , REPAIR_PROGRAM
      , PARENT_CHILD_GENERATION_FLAG
      , DEFAULT_MATERIAL_STATUS_ID
      , INTERNAL_ORDER_FLAG
      , DAYS_TGT_INV_WINDOW
      , PLANNING_TIME_FENCE_CODE
      , ATTRIBUTE29
      , WEB_STATUS
      , ATTRIBUTE28
      , UNIT_WEIGHT
      , ATTRIBUTE27
      , ATTRIBUTE26
      , WIP_SUPPLY_TYPE
      , MTL_TRANSACTIONS_ENABLED_FLAG
      , ATTRIBUTE3
      , DAYS_LATE_RECEIPT_ALLOWED
      , ATTRIBUTE2
      , ATTRIBUTE1
      , ATTRIBUTE9
      , ATTRIBUTE8
      , ATTRIBUTE7
      , UNIT_WIDTH
      , QTY_RCV_EXCEPTION_CODE
      , ATTRIBUTE6
      , ATTRIBUTE5
      , ATTRIBUTE4
      , OVER_SHIPMENT_TOLERANCE
      , SHRINKAGE_RATE
      , LOT_SPLIT_ENABLED
      , ATTRIBUTE10
      , MUST_USE_APPROVED_VENDOR_FLAG
      , ATTRIBUTE14
      , WIP_SUPPLY_SUBINVENTORY
      , ATTRIBUTE13
      , PICK_COMPONENTS_FLAG
      , ATTRIBUTE12
      , ATTRIBUTE11
      , APPROVAL_STATUS
      , DUAL_UOM_CONTROL
      , ONT_PRICING_QTY_SOURCE
      , EXPENSE_ACCOUNT
      , ATTRIBUTE21
      , ATTRIBUTE20
      , RESPONSE_TIME_PERIOD_CODE
      , ATTRIBUTE25
      , ATTRIBUTE24
      , PRICE_TOLERANCE_PERCENT
      , ATTRIBUTE23
      , ATTRIBUTE22
      , DEFAULT_SERIAL_STATUS_ID
      , SERVICEABLE_PRODUCT_FLAG
      , CURRENT_PHASE_ID
      , RESPONSE_TIME_VALUE
      , PREPOSITION_POINT
      , MAX_MINMAX_QUANTITY
      , ATTRIBUTE18
      , EAM_ACT_NOTIFICATION_FLAG
      , ATTRIBUTE17
      , ATTRIBUTE16
      , ATTRIBUTE15
      , DUAL_UOM_DEVIATION_LOW
      , ATTRIBUTE19
      , PLANNER_CODE
      , INTERNAL_ORDER_ENABLED_FLAG
      , POSITIVE_MEASUREMENT_ERROR
      , GLOBAL_ATTRIBUTE10
      , INVENTORY_PLANNING_CODE
      , INVENTORY_ITEM_FLAG
      , COST_OF_SALES_ACCOUNT
      , OBJECT_VERSION_NUMBER
      , INSPECTION_REQUIRED_FLAG
      , CHILD_LOT_STARTING_NUMBER
      , DAYS_MAX_INV_WINDOW
      , MARKET_PRICE
      , UNIT_OF_ISSUE
      , ACCEPTABLE_EARLY_DAYS
      , FIXED_LEAD_TIME
      , HOLD_DAYS
      , ENFORCE_SHIP_TO_LOCATION_CODE
      , SHELF_LIFE_CODE
      , PROCESS_COSTING_ENABLED_FLAG
      , CRITICAL_COMPONENT_FLAG
      , VENDOR_WARRANTY_FLAG
      , FORECAST_HORIZON
      , ATO_FORECAST_CONTROL
      , USAGE_ITEM_FLAG
      , SAFETY_STOCK_BUCKET_DAYS
      , REPAIR_YIELD
      , UNIT_LENGTH
      , DEFAULT_INCLUDE_IN_ROLLUP_FLAG
      , DEFECT_TRACKING_ON_FLAG
      , INVOICE_CLOSE_TOLERANCE
      , CHECK_SHORTAGES_FLAG
      , ITEM_TYPE
      , SUMMARY_FLAG
      , VMI_MINIMUM_DAYS
      , BOM_ITEM_TYPE
      , REPLENISH_TO_ORDER_FLAG
      , EAM_ITEM_TYPE
      , PLANNING_MAKE_BUY_CODE
      , GLOBAL_ATTRIBUTE_CATEGORY
      , UN_NUMBER_ID
      , CARRYING_COST
      , PRIMARY_SPECIALIST_ID
      , WEIGHT_UOM_CODE
      , MINIMUM_LICENSE_QUANTITY
      , GRADE_CONTROL_FLAG
      , VMI_FORECAST_TYPE
      , PAYMENT_TERMS_ID
      , OUTSIDE_OPERATION_UOM_TYPE
      , GLOBAL_ATTRIBUTE5
      , GLOBAL_ATTRIBUTE4
      , UNDER_RETURN_TOLERANCE
      , GLOBAL_ATTRIBUTE7
      , GLOBAL_ATTRIBUTE6
      , GLOBAL_ATTRIBUTE1
      , GLOBAL_ATTRIBUTE3
      , GLOBAL_ATTRIBUTE2
      , EAM_ACTIVITY_TYPE_CODE
      , STYLE_ITEM_ID
      , GLOBAL_ATTRIBUTE9
      , GLOBAL_ATTRIBUTE8
      , INVOICEABLE_ITEM_FLAG
      , ELECTRONIC_FLAG
      , POSTPROCESSING_LEAD_TIME
      , LIFECYCLE_ID
      , VMI_MAXIMUM_UNITS
      , SERVICEABLE_ITEM_CLASS_ID
      , CONTRACT_ITEM_TYPE_CODE
      , MODEL_CONFIG_CLAUSE_NAME
      , SERIAL_STATUS_ENABLED
      , EAM_ACT_SHUTDOWN_STATUS
      , AUTO_SERIAL_ALPHA_PREFIX
      , PLANNING_EXCEPTION_SET
      , PREPROCESSING_LEAD_TIME
      , RECEIVE_CLOSE_TOLERANCE
      , RETURN_INSPECTION_REQUIREMENT
      , COPY_LOT_ATTRIBUTE_FLAG
      , SO_AUTHORIZATION_FLAG
      , RETEST_INTERVAL
      , STOCK_ENABLED_FLAG
      , RECOVERED_PART_DISP_CODE
      , OVER_RETURN_TOLERANCE
      , CONFIG_MODEL_TYPE
      , ALLOW_ITEM_DESC_UPDATE_FLAG
      , INTERNAL_VOLUME
      , COVERAGE_SCHEDULE_ID
      , RFQ_REQUIRED_FLAG
      , MIN_MINMAX_QUANTITY
      , DEMAND_TIME_FENCE_CODE
      , ORDERABLE_ON_WEB_FLAG
      , CATALOG_STATUS_FLAG
      , SEGMENT11
      , SEGMENT10
      , FIXED_DAYS_SUPPLY
      , SEGMENT13
      , CYCLE_COUNT_ENABLED_FLAG
      , SEGMENT12
      , SEGMENT15
      , SEGMENT14
      , SEGMENT17
      , GLOBAL_ATTRIBUTE20
      , SEGMENT16
      , SEGMENT19
      , FIXED_LOT_MULTIPLIER
      , SEGMENT18
      , DAYS_TGT_INV_SUPPLY
      , SO_TRANSACTIONS_FLAG
      , CHILD_LOT_FLAG
      , GLOBAL_ATTRIBUTE17
      , GLOBAL_ATTRIBUTE18
      , GLOBAL_ATTRIBUTE15
      , GLOBAL_ATTRIBUTE16
      , GLOBAL_ATTRIBUTE13
      , GLOBAL_ATTRIBUTE14
      , VOL_DISCOUNT_EXEMPT_FLAG
      , PLANNED_INV_POINT_FLAG
      , GLOBAL_ATTRIBUTE11
      , GLOBAL_ATTRIBUTE12
      , PREVENTIVE_MAINTENANCE_FLAG
      , LOT_CONTROL_CODE
      , MAX_WARRANTY_AMOUNT
      , SUBSTITUTION_WINDOW_CODE
      , GLOBAL_ATTRIBUTE19
      , SEGMENT20
      , GDSN_OUTBOUND_ENABLED_FLAG
      , ORDER_COST
      , CHILD_LOT_VALIDATION_FLAG
      , UNDER_SHIPMENT_TOLERANCE
      , INVOICING_RULE_ID
      , COMMS_ACTIVATION_REQD_FLAG
      , HAZARD_CLASS_ID
      , EXPENSE_BILLABLE_FLAG
      , LOT_STATUS_ENABLED
      , EFFECTIVITY_CONTROL
      , ATTRIBUTE_CATEGORY
      , SUBSCRIPTION_DEPEND_FLAG
      , PROGRAM_APPLICATION_ID
      , VMI_MINIMUM_UNITS
      , TIME_BILLABLE_FLAG
      , PRORATE_SERVICE_FLAG
      , REPETITIVE_PLANNING_FLAG
      , ALLOW_SUBSTITUTE_RECEIPTS_FLAG
      , OVERCOMPLETION_TOLERANCE_TYPE
      , BOM_ENABLED_FLAG
      , SHIPPABLE_ITEM_FLAG
      , PURCHASING_ITEM_FLAG
      , SOURCE_TYPE
      , SERV_REQ_ENABLED_CODE
      , IB_ITEM_INSTANCE_CLASS
      , LOT_TRANSLATE_ENABLED
      , MAXIMUM_LOAD_WEIGHT
      , SERVICE_DURATION
      , MRP_SAFETY_STOCK_PERCENT
      , ALLOW_UNORDERED_RECEIPTS_FLAG
      , ALLOWED_UNITS_LOOKUP_CODE
      , LAST_UPDATE_LOGIN
      , PROCESS_SUPPLY_LOCATOR_ID
      , PROCESS_YIELD_SUBINVENTORY
      , ACCOUNTING_RULE_ID
      , VMI_MAXIMUM_DAYS
      , INVENTORY_ITEM_STATUS_CODE
      , TAX_CODE
      , AUTO_CREATED_CONFIG_FLAG
      , SUBCONTRACTING_COMPONENT
      , VMI_FIXED_ORDER_QUANTITY
      , PROGRAM_ID
      , CONTAINER_ITEM_FLAG
      , SEGMENT8
      , SEGMENT7
      , SEGMENT9
      , SERIAL_TAGGING_FLAG
      , SEGMENT4
      , SEGMENT3
      , EXPIRATION_ACTION_CODE
      , SEGMENT6
      , SEGMENT5
      , TRADE_ITEM_DESCRIPTOR
      , MINIMUM_FILL_PERCENT
      , END_DATE_ACTIVE
      , SALES_ACCOUNT
      , BACK_ORDERABLE_FLAG
      , STD_LOT_SIZE
      , FINANCING_ALLOWED_FLAG
      , LEAD_TIME_LOT_SIZE
      , PRIMARY_UOM_CODE
      , SHELF_LIFE_DAYS
      , CONTAINER_TYPE_CODE
      , DEFAULT_GRADE
      , CUSTOMER_ORDER_ENABLED_FLAG
      , ITEM_CATALOG_GROUP_ID
      , ATP_RULE_ID
      , SERVICE_STARTING_DELAY
      , RELEASE_TIME_FENCE_DAYS
      , OVERCOMPLETION_TOLERANCE_VALUE
      , UNIT_VOLUME
      , DESCRIPTION
      , CONVERGENCE
      , CUM_MANUFACTURING_LEAD_TIME
      , SHIP_MODEL_COMPLETE_FLAG
      , LOT_SUBSTITUTION_ENABLED
      , OUTSIDE_OPERATION_FLAG
      , AUTO_LOT_ALPHA_PREFIX
      , ATP_FLAG
      , EGO_MASTER_ITEMS_DFF_CTX
      , EAM_ACTIVITY_SOURCE_CODE
      , TAXABLE_FLAG
      , ALLOW_EXPRESS_DELIVERY_FLAG
      , PURCHASING_TAX_CODE
      , ENG_ITEM_FLAG
      , ENGINEERING_ITEM_ID
      , END_ASSEMBLY_PEGGING_FLAG
      , RETURNABLE_FLAG
      , PROCESS_YIELD_LOCATOR_ID
      , EAM_ACTIVITY_CAUSE_CODE
      , MATURITY_DAYS
      , ATP_COMPONENTS_FLAG
      , LAST_UPDATED_BY
      , COUPON_EXEMPT_FLAG
      , PLANNING_TIME_FENCE_DAYS
      , RECEIPT_REQUIRED_FLAG
      , VOLUME_UOM_CODE
      , LOCATION_CONTROL_CODE
      , WARRANTY_VENDOR_ID
      , INVENTORY_ASSET_FLAG
      , ENCUMBRANCE_ACCOUNT
      , SERVICEABLE_COMPONENT_FLAG
      , CUMULATIVE_TOTAL_LEAD_TIME
      , MRP_CALCULATE_ATP_FLAG
      , OUTSOURCED_ASSEMBLY
      , DEFAULT_LOT_STATUS_ID
      , VARIABLE_LEAD_TIME
      , AUTO_REDUCE_MPS
      , RECIPE_ENABLED_FLAG
      , ACCEPTABLE_RATE_DECREASE
      , BUILD_IN_WIP_FLAG
      , RECEIPT_DAYS_EXCEPTION_CODE
      , VEHICLE_ITEM_FLAG
      , CONFIG_MATCH
      , DOWNLOADABLE_FLAG
      , DEFAULT_SO_SOURCE_TYPE
      , FIXED_ORDER_QUANTITY
      , SUBSTITUTION_WINDOW_DAYS
      , EQUIPMENT_TYPE
      , CAS_NUMBER
      , SERV_IMPORTANCE_LEVEL
      , LOT_MERGE_ENABLED
      , SEGMENT2
      , CUSTOMER_ORDER_FLAG
      , ENABLED_FLAG
      , PURCHASING_ENABLED_FLAG
      , WH_UPDATE_DATE
      , OVERRUN_PERCENTAGE
      , ASSET_CREATION_CODE
      , DAYS_EARLY_RECEIPT_ALLOWED
      , NEGATIVE_MEASUREMENT_ERROR
      , BASE_WARRANTY_SERVICE_ID
      , START_AUTO_SERIAL_NUMBER
      , ROUNDING_CONTROL_TYPE
      , LOT_DIVISIBLE_FLAG
      , EXCLUDE_FROM_BUDGET_FLAG
      , MRP_PLANNING_CODE
      , BUYER_ID
      , RESERVABLE_TYPE
      , SOURCE_ORGANIZATION_ID
      , NEW_REVISION_CODE
      , DRP_PLANNED_FLAG
      , ASSET_CATEGORY_ID
      , MRP_SAFETY_STOCK_CODE
      , CONTINOUS_TRANSFER
      , HAZARDOUS_MATERIAL_FLAG
      , COSTING_ENABLED_FLAG
      , DIMENSION_UOM_CODE
      , SERVICE_DURATION_PERIOD_CODE
      , EVENT_FLAG
      , BULK_PICKED_FLAG
      , DEFAULT_SHIPPING_ORG
      , MATERIAL_BILLABLE_FLAG
      , PROCESS_QUALITY_ENABLED_FLAG
      , OPTION_SPECIFIC_SOURCED
      , SECONDARY_SPECIALIST_ID
      , PICKING_RULE_ID
      , EXPIRATION_ACTION_INTERVAL
      , ASN_AUTOEXPIRE_FLAG
      , START_AUTO_LOT_NUMBER
      , MINIMUM_ORDER_QUANTITY
      , COMMS_NL_TRACKABLE_FLAG
      , INVENTORY_CARRY_PENALTY
      , ENGINEERING_ECN_CODE
      , REPAIR_LEADTIME
      , SECONDARY_UOM_CODE
      , RECEIVING_ROUTING_ID
      , PRIMARY_UNIT_OF_MEASURE
      , CREATE_SUPPLY_FLAG
      , MAXIMUM_ORDER_QUANTITY
      , PROCESS_SUPPLY_SUBINVENTORY
      , PRODUCT_FAMILY_ITEM_ID
      , SOURCE_SUBINVENTORY
      , SERIAL_NUMBER_CONTROL_CODE
      , CREATED_BY
      , STYLE_ITEM_FLAG
      , CHARGE_PERIODICITY_CODE
      , INVOICE_ENABLED_FLAG
      , CONSIGNED_FLAG
      , DAYS_MAX_INV_SUPPLY
      , UNIT_HEIGHT
      , PROCESS_EXECUTION_ENABLED_FLAG
      , ROUNDING_FACTOR
      , OPERATION_SLACK_PENALTY
      , DEMAND_TIME_FENCE_DAYS
      , BASE_ITEM_ID
      , COLLATERAL_FLAG
      , REQUEST_ID
      , FULL_LEAD_TIME
      , SERVICE_ITEM_FLAG
      , INDIVISIBLE_FLAG
      , SERV_BILLING_ENABLED_FLAG
      , DIVERGENCE
      , SECONDARY_DEFAULT_IND
      , REVISION_QTY_CONTROL_CODE
      , QTY_RCV_TOLERANCE
      , DUAL_UOM_DEVIATION_HIGH
      , RELEASE_TIME_FENCE_CODE
      , ACCEPTABLE_RATE_INCREASE
      , RESTRICT_SUBINVENTORIES_CODE
      , CONFIG_ORGS
      , LAST_SUBMITTED_NIR_ID
      , RESTRICT_LOCATORS_CODE
      , CHILD_LOT_PREFIX
      , TRACKING_QUANTITY_IND
      , PROGRAM_UPDATE_DATE
      , START_DATE_ACTIVE
      , LIST_PRICE_PER_UNIT
      , CREATION_DATE
      , ENGINEERING_DATE
      , LAST_UPDATE_DATE
      , _FIVETRAN_DELETED
      , _FIVETRAN_ID
      , _FIVETRAN_SYNCED
      , PSA_DELETE_IND
      , PSA_LOAD_DTS
      , PSA_RECORD_SOURCE
      , CONVERT_TIMEZONE('UTC', _FIVETRAN_SYNCED )                   as                                           LOAD_DTS
    FROM SRC_S
)

, LOGIC_A as (
    SELECT
        REC_SRC
      , BKCC
    FROM SRC_A
)

, LOGIC_S2 as (
    SELECT
        organization_code                                            as                                           PLANT_BK
      , organization_id                                              as                                 S2_organization_id
    FROM SRC_S2
)
---- RENAME LAYER ----

, RENAME_S as (
    SELECT
        ITEM_BK
      , SEGMENT1
      , INVENTORY_ITEM_ID
      , ORGANIZATION_ID
      , WIP_SUPPLY_LOCATOR_ID
      , ATTRIBUTE30
      , REPAIR_PROGRAM
      , PARENT_CHILD_GENERATION_FLAG
      , DEFAULT_MATERIAL_STATUS_ID
      , INTERNAL_ORDER_FLAG
      , DAYS_TGT_INV_WINDOW
      , PLANNING_TIME_FENCE_CODE
      , ATTRIBUTE29
      , WEB_STATUS
      , ATTRIBUTE28
      , UNIT_WEIGHT
      , ATTRIBUTE27
      , ATTRIBUTE26
      , WIP_SUPPLY_TYPE
      , MTL_TRANSACTIONS_ENABLED_FLAG
      , ATTRIBUTE3
      , DAYS_LATE_RECEIPT_ALLOWED
      , ATTRIBUTE2
      , ATTRIBUTE1
      , ATTRIBUTE9
      , ATTRIBUTE8
      , ATTRIBUTE7
      , UNIT_WIDTH
      , QTY_RCV_EXCEPTION_CODE
      , ATTRIBUTE6
      , ATTRIBUTE5
      , ATTRIBUTE4
      , OVER_SHIPMENT_TOLERANCE
      , SHRINKAGE_RATE
      , LOT_SPLIT_ENABLED
      , ATTRIBUTE10
      , MUST_USE_APPROVED_VENDOR_FLAG
      , ATTRIBUTE14
      , WIP_SUPPLY_SUBINVENTORY
      , ATTRIBUTE13
      , PICK_COMPONENTS_FLAG
      , ATTRIBUTE12
      , ATTRIBUTE11
      , APPROVAL_STATUS
      , DUAL_UOM_CONTROL
      , ONT_PRICING_QTY_SOURCE
      , EXPENSE_ACCOUNT
      , ATTRIBUTE21
      , ATTRIBUTE20
      , RESPONSE_TIME_PERIOD_CODE
      , ATTRIBUTE25
      , ATTRIBUTE24
      , PRICE_TOLERANCE_PERCENT
      , ATTRIBUTE23
      , ATTRIBUTE22
      , DEFAULT_SERIAL_STATUS_ID
      , SERVICEABLE_PRODUCT_FLAG
      , CURRENT_PHASE_ID
      , RESPONSE_TIME_VALUE
      , PREPOSITION_POINT
      , MAX_MINMAX_QUANTITY
      , ATTRIBUTE18
      , EAM_ACT_NOTIFICATION_FLAG
      , ATTRIBUTE17
      , ATTRIBUTE16
      , ATTRIBUTE15
      , DUAL_UOM_DEVIATION_LOW
      , ATTRIBUTE19
      , PLANNER_CODE
      , INTERNAL_ORDER_ENABLED_FLAG
      , POSITIVE_MEASUREMENT_ERROR
      , GLOBAL_ATTRIBUTE10
      , INVENTORY_PLANNING_CODE
      , INVENTORY_ITEM_FLAG
      , COST_OF_SALES_ACCOUNT
      , OBJECT_VERSION_NUMBER
      , INSPECTION_REQUIRED_FLAG
      , CHILD_LOT_STARTING_NUMBER
      , DAYS_MAX_INV_WINDOW
      , MARKET_PRICE
      , UNIT_OF_ISSUE
      , ACCEPTABLE_EARLY_DAYS
      , FIXED_LEAD_TIME
      , HOLD_DAYS
      , ENFORCE_SHIP_TO_LOCATION_CODE
      , SHELF_LIFE_CODE
      , PROCESS_COSTING_ENABLED_FLAG
      , CRITICAL_COMPONENT_FLAG
      , VENDOR_WARRANTY_FLAG
      , FORECAST_HORIZON
      , ATO_FORECAST_CONTROL
      , USAGE_ITEM_FLAG
      , SAFETY_STOCK_BUCKET_DAYS
      , REPAIR_YIELD
      , UNIT_LENGTH
      , DEFAULT_INCLUDE_IN_ROLLUP_FLAG
      , DEFECT_TRACKING_ON_FLAG
      , INVOICE_CLOSE_TOLERANCE
      , CHECK_SHORTAGES_FLAG
      , ITEM_TYPE
      , SUMMARY_FLAG
      , VMI_MINIMUM_DAYS
      , BOM_ITEM_TYPE
      , REPLENISH_TO_ORDER_FLAG
      , EAM_ITEM_TYPE
      , PLANNING_MAKE_BUY_CODE
      , GLOBAL_ATTRIBUTE_CATEGORY
      , UN_NUMBER_ID
      , CARRYING_COST
      , PRIMARY_SPECIALIST_ID
      , WEIGHT_UOM_CODE
      , MINIMUM_LICENSE_QUANTITY
      , GRADE_CONTROL_FLAG
      , VMI_FORECAST_TYPE
      , PAYMENT_TERMS_ID
      , OUTSIDE_OPERATION_UOM_TYPE
      , GLOBAL_ATTRIBUTE5
      , GLOBAL_ATTRIBUTE4
      , UNDER_RETURN_TOLERANCE
      , GLOBAL_ATTRIBUTE7
      , GLOBAL_ATTRIBUTE6
      , GLOBAL_ATTRIBUTE1
      , GLOBAL_ATTRIBUTE3
      , GLOBAL_ATTRIBUTE2
      , EAM_ACTIVITY_TYPE_CODE
      , STYLE_ITEM_ID
      , GLOBAL_ATTRIBUTE9
      , GLOBAL_ATTRIBUTE8
      , INVOICEABLE_ITEM_FLAG
      , ELECTRONIC_FLAG
      , POSTPROCESSING_LEAD_TIME
      , LIFECYCLE_ID
      , VMI_MAXIMUM_UNITS
      , SERVICEABLE_ITEM_CLASS_ID
      , CONTRACT_ITEM_TYPE_CODE
      , MODEL_CONFIG_CLAUSE_NAME
      , SERIAL_STATUS_ENABLED
      , EAM_ACT_SHUTDOWN_STATUS
      , AUTO_SERIAL_ALPHA_PREFIX
      , PLANNING_EXCEPTION_SET
      , PREPROCESSING_LEAD_TIME
      , RECEIVE_CLOSE_TOLERANCE
      , RETURN_INSPECTION_REQUIREMENT
      , COPY_LOT_ATTRIBUTE_FLAG
      , SO_AUTHORIZATION_FLAG
      , RETEST_INTERVAL
      , STOCK_ENABLED_FLAG
      , RECOVERED_PART_DISP_CODE
      , OVER_RETURN_TOLERANCE
      , CONFIG_MODEL_TYPE
      , ALLOW_ITEM_DESC_UPDATE_FLAG
      , INTERNAL_VOLUME
      , COVERAGE_SCHEDULE_ID
      , RFQ_REQUIRED_FLAG
      , MIN_MINMAX_QUANTITY
      , DEMAND_TIME_FENCE_CODE
      , ORDERABLE_ON_WEB_FLAG
      , CATALOG_STATUS_FLAG
      , SEGMENT11
      , SEGMENT10
      , FIXED_DAYS_SUPPLY
      , SEGMENT13
      , CYCLE_COUNT_ENABLED_FLAG
      , SEGMENT12
      , SEGMENT15
      , SEGMENT14
      , SEGMENT17
      , GLOBAL_ATTRIBUTE20
      , SEGMENT16
      , SEGMENT19
      , FIXED_LOT_MULTIPLIER
      , SEGMENT18
      , DAYS_TGT_INV_SUPPLY
      , SO_TRANSACTIONS_FLAG
      , CHILD_LOT_FLAG
      , GLOBAL_ATTRIBUTE17
      , GLOBAL_ATTRIBUTE18
      , GLOBAL_ATTRIBUTE15
      , GLOBAL_ATTRIBUTE16
      , GLOBAL_ATTRIBUTE13
      , GLOBAL_ATTRIBUTE14
      , VOL_DISCOUNT_EXEMPT_FLAG
      , PLANNED_INV_POINT_FLAG
      , GLOBAL_ATTRIBUTE11
      , GLOBAL_ATTRIBUTE12
      , PREVENTIVE_MAINTENANCE_FLAG
      , LOT_CONTROL_CODE
      , MAX_WARRANTY_AMOUNT
      , SUBSTITUTION_WINDOW_CODE
      , GLOBAL_ATTRIBUTE19
      , SEGMENT20
      , GDSN_OUTBOUND_ENABLED_FLAG
      , ORDER_COST
      , CHILD_LOT_VALIDATION_FLAG
      , UNDER_SHIPMENT_TOLERANCE
      , INVOICING_RULE_ID
      , COMMS_ACTIVATION_REQD_FLAG
      , HAZARD_CLASS_ID
      , EXPENSE_BILLABLE_FLAG
      , LOT_STATUS_ENABLED
      , EFFECTIVITY_CONTROL
      , ATTRIBUTE_CATEGORY
      , SUBSCRIPTION_DEPEND_FLAG
      , PROGRAM_APPLICATION_ID
      , VMI_MINIMUM_UNITS
      , TIME_BILLABLE_FLAG
      , PRORATE_SERVICE_FLAG
      , REPETITIVE_PLANNING_FLAG
      , ALLOW_SUBSTITUTE_RECEIPTS_FLAG
      , OVERCOMPLETION_TOLERANCE_TYPE
      , BOM_ENABLED_FLAG
      , SHIPPABLE_ITEM_FLAG
      , PURCHASING_ITEM_FLAG
      , SOURCE_TYPE
      , SERV_REQ_ENABLED_CODE
      , IB_ITEM_INSTANCE_CLASS
      , LOT_TRANSLATE_ENABLED
      , MAXIMUM_LOAD_WEIGHT
      , SERVICE_DURATION
      , MRP_SAFETY_STOCK_PERCENT
      , ALLOW_UNORDERED_RECEIPTS_FLAG
      , ALLOWED_UNITS_LOOKUP_CODE
      , LAST_UPDATE_LOGIN
      , PROCESS_SUPPLY_LOCATOR_ID
      , PROCESS_YIELD_SUBINVENTORY
      , ACCOUNTING_RULE_ID
      , VMI_MAXIMUM_DAYS
      , INVENTORY_ITEM_STATUS_CODE
      , TAX_CODE
      , AUTO_CREATED_CONFIG_FLAG
      , SUBCONTRACTING_COMPONENT
      , VMI_FIXED_ORDER_QUANTITY
      , PROGRAM_ID
      , CONTAINER_ITEM_FLAG
      , SEGMENT8
      , SEGMENT7
      , SEGMENT9
      , SERIAL_TAGGING_FLAG
      , SEGMENT4
      , SEGMENT3
      , EXPIRATION_ACTION_CODE
      , SEGMENT6
      , SEGMENT5
      , TRADE_ITEM_DESCRIPTOR
      , MINIMUM_FILL_PERCENT
      , END_DATE_ACTIVE
      , SALES_ACCOUNT
      , BACK_ORDERABLE_FLAG
      , STD_LOT_SIZE
      , FINANCING_ALLOWED_FLAG
      , LEAD_TIME_LOT_SIZE
      , PRIMARY_UOM_CODE
      , SHELF_LIFE_DAYS
      , CONTAINER_TYPE_CODE
      , DEFAULT_GRADE
      , CUSTOMER_ORDER_ENABLED_FLAG
      , ITEM_CATALOG_GROUP_ID
      , ATP_RULE_ID
      , SERVICE_STARTING_DELAY
      , RELEASE_TIME_FENCE_DAYS
      , OVERCOMPLETION_TOLERANCE_VALUE
      , UNIT_VOLUME
      , DESCRIPTION
      , CONVERGENCE
      , CUM_MANUFACTURING_LEAD_TIME
      , SHIP_MODEL_COMPLETE_FLAG
      , LOT_SUBSTITUTION_ENABLED
      , OUTSIDE_OPERATION_FLAG
      , AUTO_LOT_ALPHA_PREFIX
      , ATP_FLAG
      , EGO_MASTER_ITEMS_DFF_CTX
      , EAM_ACTIVITY_SOURCE_CODE
      , TAXABLE_FLAG
      , ALLOW_EXPRESS_DELIVERY_FLAG
      , PURCHASING_TAX_CODE
      , ENG_ITEM_FLAG
      , ENGINEERING_ITEM_ID
      , END_ASSEMBLY_PEGGING_FLAG
      , RETURNABLE_FLAG
      , PROCESS_YIELD_LOCATOR_ID
      , EAM_ACTIVITY_CAUSE_CODE
      , MATURITY_DAYS
      , ATP_COMPONENTS_FLAG
      , LAST_UPDATED_BY
      , COUPON_EXEMPT_FLAG
      , PLANNING_TIME_FENCE_DAYS
      , RECEIPT_REQUIRED_FLAG
      , VOLUME_UOM_CODE
      , LOCATION_CONTROL_CODE
      , WARRANTY_VENDOR_ID
      , INVENTORY_ASSET_FLAG
      , ENCUMBRANCE_ACCOUNT
      , SERVICEABLE_COMPONENT_FLAG
      , CUMULATIVE_TOTAL_LEAD_TIME
      , MRP_CALCULATE_ATP_FLAG
      , OUTSOURCED_ASSEMBLY
      , DEFAULT_LOT_STATUS_ID
      , VARIABLE_LEAD_TIME
      , AUTO_REDUCE_MPS
      , RECIPE_ENABLED_FLAG
      , ACCEPTABLE_RATE_DECREASE
      , BUILD_IN_WIP_FLAG
      , RECEIPT_DAYS_EXCEPTION_CODE
      , VEHICLE_ITEM_FLAG
      , CONFIG_MATCH
      , DOWNLOADABLE_FLAG
      , DEFAULT_SO_SOURCE_TYPE
      , FIXED_ORDER_QUANTITY
      , SUBSTITUTION_WINDOW_DAYS
      , EQUIPMENT_TYPE
      , CAS_NUMBER
      , SERV_IMPORTANCE_LEVEL
      , LOT_MERGE_ENABLED
      , SEGMENT2
      , CUSTOMER_ORDER_FLAG
      , ENABLED_FLAG
      , PURCHASING_ENABLED_FLAG
      , WH_UPDATE_DATE
      , OVERRUN_PERCENTAGE
      , ASSET_CREATION_CODE
      , DAYS_EARLY_RECEIPT_ALLOWED
      , NEGATIVE_MEASUREMENT_ERROR
      , BASE_WARRANTY_SERVICE_ID
      , START_AUTO_SERIAL_NUMBER
      , ROUNDING_CONTROL_TYPE
      , LOT_DIVISIBLE_FLAG
      , EXCLUDE_FROM_BUDGET_FLAG
      , MRP_PLANNING_CODE
      , BUYER_ID
      , RESERVABLE_TYPE
      , SOURCE_ORGANIZATION_ID
      , NEW_REVISION_CODE
      , DRP_PLANNED_FLAG
      , ASSET_CATEGORY_ID
      , MRP_SAFETY_STOCK_CODE
      , CONTINOUS_TRANSFER
      , HAZARDOUS_MATERIAL_FLAG
      , COSTING_ENABLED_FLAG
      , DIMENSION_UOM_CODE
      , SERVICE_DURATION_PERIOD_CODE
      , EVENT_FLAG
      , BULK_PICKED_FLAG
      , DEFAULT_SHIPPING_ORG
      , MATERIAL_BILLABLE_FLAG
      , PROCESS_QUALITY_ENABLED_FLAG
      , OPTION_SPECIFIC_SOURCED
      , SECONDARY_SPECIALIST_ID
      , PICKING_RULE_ID
      , EXPIRATION_ACTION_INTERVAL
      , ASN_AUTOEXPIRE_FLAG
      , START_AUTO_LOT_NUMBER
      , MINIMUM_ORDER_QUANTITY
      , COMMS_NL_TRACKABLE_FLAG
      , INVENTORY_CARRY_PENALTY
      , ENGINEERING_ECN_CODE
      , REPAIR_LEADTIME
      , SECONDARY_UOM_CODE
      , RECEIVING_ROUTING_ID
      , PRIMARY_UNIT_OF_MEASURE
      , CREATE_SUPPLY_FLAG
      , MAXIMUM_ORDER_QUANTITY
      , PROCESS_SUPPLY_SUBINVENTORY
      , PRODUCT_FAMILY_ITEM_ID
      , SOURCE_SUBINVENTORY
      , SERIAL_NUMBER_CONTROL_CODE
      , CREATED_BY
      , STYLE_ITEM_FLAG
      , CHARGE_PERIODICITY_CODE
      , INVOICE_ENABLED_FLAG
      , CONSIGNED_FLAG
      , DAYS_MAX_INV_SUPPLY
      , UNIT_HEIGHT
      , PROCESS_EXECUTION_ENABLED_FLAG
      , ROUNDING_FACTOR
      , OPERATION_SLACK_PENALTY
      , DEMAND_TIME_FENCE_DAYS
      , BASE_ITEM_ID
      , COLLATERAL_FLAG
      , REQUEST_ID
      , FULL_LEAD_TIME
      , SERVICE_ITEM_FLAG
      , INDIVISIBLE_FLAG
      , SERV_BILLING_ENABLED_FLAG
      , DIVERGENCE
      , SECONDARY_DEFAULT_IND
      , REVISION_QTY_CONTROL_CODE
      , QTY_RCV_TOLERANCE
      , DUAL_UOM_DEVIATION_HIGH
      , RELEASE_TIME_FENCE_CODE
      , ACCEPTABLE_RATE_INCREASE
      , RESTRICT_SUBINVENTORIES_CODE
      , CONFIG_ORGS
      , LAST_SUBMITTED_NIR_ID
      , RESTRICT_LOCATORS_CODE
      , CHILD_LOT_PREFIX
      , TRACKING_QUANTITY_IND
      , PROGRAM_UPDATE_DATE
      , START_DATE_ACTIVE
      , LIST_PRICE_PER_UNIT
      , CREATION_DATE
      , ENGINEERING_DATE
      , LAST_UPDATE_DATE
      , _FIVETRAN_DELETED
      , _FIVETRAN_ID
      , _FIVETRAN_SYNCED
      , PSA_DELETE_IND
      , PSA_LOAD_DTS
      , PSA_RECORD_SOURCE
      , LOAD_DTS
    FROM LOGIC_S
)

, RENAME_A as (
    SELECT
        REC_SRC
      , BKCC
    FROM LOGIC_A
)

, RENAME_S2 as (
    SELECT
        PLANT_BK
      , S2_organization_id
    FROM LOGIC_S2
)
---- FILTER LAYER ----

, FILTER_S as (
    SELECT *
    FROM RENAME_S
)

, FILTER_A as (
    SELECT *
    FROM RENAME_A
    WHERE rec_src = 'USWIOC.ORCL.EBSPRD.SYSTEM_ITEM'
)

, FILTER_S2 as (
    SELECT *
    FROM RENAME_S2
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM FILTER_S
    INNER JOIN FILTER_A
        ON '1' = '1'
    LEFT JOIN FILTER_S2
        ON organization_id = S2_organization_id
)

---- FINAL LAYER ----
SELECT
          ITEM_BK
        , SEGMENT1
        , INVENTORY_ITEM_ID
        , ORGANIZATION_ID
        , WIP_SUPPLY_LOCATOR_ID
        , ATTRIBUTE30
        , REPAIR_PROGRAM
        , PARENT_CHILD_GENERATION_FLAG
        , DEFAULT_MATERIAL_STATUS_ID
        , INTERNAL_ORDER_FLAG
        , DAYS_TGT_INV_WINDOW
        , PLANNING_TIME_FENCE_CODE
        , ATTRIBUTE29
        , WEB_STATUS
        , ATTRIBUTE28
        , UNIT_WEIGHT
        , ATTRIBUTE27
        , ATTRIBUTE26
        , WIP_SUPPLY_TYPE
        , MTL_TRANSACTIONS_ENABLED_FLAG
        , ATTRIBUTE3
        , DAYS_LATE_RECEIPT_ALLOWED
        , ATTRIBUTE2
        , ATTRIBUTE1
        , ATTRIBUTE9
        , ATTRIBUTE8
        , ATTRIBUTE7
        , UNIT_WIDTH
        , QTY_RCV_EXCEPTION_CODE
        , ATTRIBUTE6
        , ATTRIBUTE5
        , ATTRIBUTE4
        , OVER_SHIPMENT_TOLERANCE
        , SHRINKAGE_RATE
        , LOT_SPLIT_ENABLED
        , ATTRIBUTE10
        , MUST_USE_APPROVED_VENDOR_FLAG
        , ATTRIBUTE14
        , WIP_SUPPLY_SUBINVENTORY
        , ATTRIBUTE13
        , PICK_COMPONENTS_FLAG
        , ATTRIBUTE12
        , ATTRIBUTE11
        , APPROVAL_STATUS
        , DUAL_UOM_CONTROL
        , ONT_PRICING_QTY_SOURCE
        , EXPENSE_ACCOUNT
        , ATTRIBUTE21
        , ATTRIBUTE20
        , RESPONSE_TIME_PERIOD_CODE
        , ATTRIBUTE25
        , ATTRIBUTE24
        , PRICE_TOLERANCE_PERCENT
        , ATTRIBUTE23
        , ATTRIBUTE22
        , DEFAULT_SERIAL_STATUS_ID
        , SERVICEABLE_PRODUCT_FLAG
        , CURRENT_PHASE_ID
        , RESPONSE_TIME_VALUE
        , PREPOSITION_POINT
        , MAX_MINMAX_QUANTITY
        , ATTRIBUTE18
        , EAM_ACT_NOTIFICATION_FLAG
        , ATTRIBUTE17
        , ATTRIBUTE16
        , ATTRIBUTE15
        , DUAL_UOM_DEVIATION_LOW
        , ATTRIBUTE19
        , PLANNER_CODE
        , INTERNAL_ORDER_ENABLED_FLAG
        , POSITIVE_MEASUREMENT_ERROR
        , GLOBAL_ATTRIBUTE10
        , INVENTORY_PLANNING_CODE
        , INVENTORY_ITEM_FLAG
        , COST_OF_SALES_ACCOUNT
        , OBJECT_VERSION_NUMBER
        , INSPECTION_REQUIRED_FLAG
        , CHILD_LOT_STARTING_NUMBER
        , DAYS_MAX_INV_WINDOW
        , MARKET_PRICE
        , UNIT_OF_ISSUE
        , ACCEPTABLE_EARLY_DAYS
        , FIXED_LEAD_TIME
        , HOLD_DAYS
        , ENFORCE_SHIP_TO_LOCATION_CODE
        , SHELF_LIFE_CODE
        , PROCESS_COSTING_ENABLED_FLAG
        , CRITICAL_COMPONENT_FLAG
        , VENDOR_WARRANTY_FLAG
        , FORECAST_HORIZON
        , ATO_FORECAST_CONTROL
        , USAGE_ITEM_FLAG
        , SAFETY_STOCK_BUCKET_DAYS
        , REPAIR_YIELD
        , UNIT_LENGTH
        , DEFAULT_INCLUDE_IN_ROLLUP_FLAG
        , DEFECT_TRACKING_ON_FLAG
        , INVOICE_CLOSE_TOLERANCE
        , CHECK_SHORTAGES_FLAG
        , ITEM_TYPE
        , SUMMARY_FLAG
        , VMI_MINIMUM_DAYS
        , BOM_ITEM_TYPE
        , REPLENISH_TO_ORDER_FLAG
        , EAM_ITEM_TYPE
        , PLANNING_MAKE_BUY_CODE
        , GLOBAL_ATTRIBUTE_CATEGORY
        , UN_NUMBER_ID
        , CARRYING_COST
        , PRIMARY_SPECIALIST_ID
        , WEIGHT_UOM_CODE
        , MINIMUM_LICENSE_QUANTITY
        , GRADE_CONTROL_FLAG
        , VMI_FORECAST_TYPE
        , PAYMENT_TERMS_ID
        , OUTSIDE_OPERATION_UOM_TYPE
        , GLOBAL_ATTRIBUTE5
        , GLOBAL_ATTRIBUTE4
        , UNDER_RETURN_TOLERANCE
        , GLOBAL_ATTRIBUTE7
        , GLOBAL_ATTRIBUTE6
        , GLOBAL_ATTRIBUTE1
        , GLOBAL_ATTRIBUTE3
        , GLOBAL_ATTRIBUTE2
        , EAM_ACTIVITY_TYPE_CODE
        , STYLE_ITEM_ID
        , GLOBAL_ATTRIBUTE9
        , GLOBAL_ATTRIBUTE8
        , INVOICEABLE_ITEM_FLAG
        , ELECTRONIC_FLAG
        , POSTPROCESSING_LEAD_TIME
        , LIFECYCLE_ID
        , VMI_MAXIMUM_UNITS
        , SERVICEABLE_ITEM_CLASS_ID
        , CONTRACT_ITEM_TYPE_CODE
        , MODEL_CONFIG_CLAUSE_NAME
        , SERIAL_STATUS_ENABLED
        , EAM_ACT_SHUTDOWN_STATUS
        , AUTO_SERIAL_ALPHA_PREFIX
        , PLANNING_EXCEPTION_SET
        , PREPROCESSING_LEAD_TIME
        , RECEIVE_CLOSE_TOLERANCE
        , RETURN_INSPECTION_REQUIREMENT
        , COPY_LOT_ATTRIBUTE_FLAG
        , SO_AUTHORIZATION_FLAG
        , RETEST_INTERVAL
        , STOCK_ENABLED_FLAG
        , RECOVERED_PART_DISP_CODE
        , OVER_RETURN_TOLERANCE
        , CONFIG_MODEL_TYPE
        , ALLOW_ITEM_DESC_UPDATE_FLAG
        , INTERNAL_VOLUME
        , COVERAGE_SCHEDULE_ID
        , RFQ_REQUIRED_FLAG
        , MIN_MINMAX_QUANTITY
        , DEMAND_TIME_FENCE_CODE
        , ORDERABLE_ON_WEB_FLAG
        , CATALOG_STATUS_FLAG
        , SEGMENT11
        , SEGMENT10
        , FIXED_DAYS_SUPPLY
        , SEGMENT13
        , CYCLE_COUNT_ENABLED_FLAG
        , SEGMENT12
        , SEGMENT15
        , SEGMENT14
        , SEGMENT17
        , GLOBAL_ATTRIBUTE20
        , SEGMENT16
        , SEGMENT19
        , FIXED_LOT_MULTIPLIER
        , SEGMENT18
        , DAYS_TGT_INV_SUPPLY
        , SO_TRANSACTIONS_FLAG
        , CHILD_LOT_FLAG
        , GLOBAL_ATTRIBUTE17
        , GLOBAL_ATTRIBUTE18
        , GLOBAL_ATTRIBUTE15
        , GLOBAL_ATTRIBUTE16
        , GLOBAL_ATTRIBUTE13
        , GLOBAL_ATTRIBUTE14
        , VOL_DISCOUNT_EXEMPT_FLAG
        , PLANNED_INV_POINT_FLAG
        , GLOBAL_ATTRIBUTE11
        , GLOBAL_ATTRIBUTE12
        , PREVENTIVE_MAINTENANCE_FLAG
        , LOT_CONTROL_CODE
        , MAX_WARRANTY_AMOUNT
        , SUBSTITUTION_WINDOW_CODE
        , GLOBAL_ATTRIBUTE19
        , SEGMENT20
        , GDSN_OUTBOUND_ENABLED_FLAG
        , ORDER_COST
        , CHILD_LOT_VALIDATION_FLAG
        , UNDER_SHIPMENT_TOLERANCE
        , INVOICING_RULE_ID
        , COMMS_ACTIVATION_REQD_FLAG
        , HAZARD_CLASS_ID
        , EXPENSE_BILLABLE_FLAG
        , LOT_STATUS_ENABLED
        , EFFECTIVITY_CONTROL
        , ATTRIBUTE_CATEGORY
        , SUBSCRIPTION_DEPEND_FLAG
        , PROGRAM_APPLICATION_ID
        , VMI_MINIMUM_UNITS
        , TIME_BILLABLE_FLAG
        , PRORATE_SERVICE_FLAG
        , REPETITIVE_PLANNING_FLAG
        , ALLOW_SUBSTITUTE_RECEIPTS_FLAG
        , OVERCOMPLETION_TOLERANCE_TYPE
        , BOM_ENABLED_FLAG
        , SHIPPABLE_ITEM_FLAG
        , PURCHASING_ITEM_FLAG
        , SOURCE_TYPE
        , SERV_REQ_ENABLED_CODE
        , IB_ITEM_INSTANCE_CLASS
        , LOT_TRANSLATE_ENABLED
        , MAXIMUM_LOAD_WEIGHT
        , SERVICE_DURATION
        , MRP_SAFETY_STOCK_PERCENT
        , ALLOW_UNORDERED_RECEIPTS_FLAG
        , ALLOWED_UNITS_LOOKUP_CODE
        , LAST_UPDATE_LOGIN
        , PROCESS_SUPPLY_LOCATOR_ID
        , PROCESS_YIELD_SUBINVENTORY
        , ACCOUNTING_RULE_ID
        , VMI_MAXIMUM_DAYS
        , INVENTORY_ITEM_STATUS_CODE
        , TAX_CODE
        , AUTO_CREATED_CONFIG_FLAG
        , SUBCONTRACTING_COMPONENT
        , VMI_FIXED_ORDER_QUANTITY
        , PROGRAM_ID
        , CONTAINER_ITEM_FLAG
        , SEGMENT8
        , SEGMENT7
        , SEGMENT9
        , SERIAL_TAGGING_FLAG
        , SEGMENT4
        , SEGMENT3
        , EXPIRATION_ACTION_CODE
        , SEGMENT6
        , SEGMENT5
        , TRADE_ITEM_DESCRIPTOR
        , MINIMUM_FILL_PERCENT
        , END_DATE_ACTIVE
        , SALES_ACCOUNT
        , BACK_ORDERABLE_FLAG
        , STD_LOT_SIZE
        , FINANCING_ALLOWED_FLAG
        , LEAD_TIME_LOT_SIZE
        , PRIMARY_UOM_CODE
        , SHELF_LIFE_DAYS
        , CONTAINER_TYPE_CODE
        , DEFAULT_GRADE
        , CUSTOMER_ORDER_ENABLED_FLAG
        , ITEM_CATALOG_GROUP_ID
        , ATP_RULE_ID
        , SERVICE_STARTING_DELAY
        , RELEASE_TIME_FENCE_DAYS
        , OVERCOMPLETION_TOLERANCE_VALUE
        , UNIT_VOLUME
        , DESCRIPTION
        , CONVERGENCE
        , CUM_MANUFACTURING_LEAD_TIME
        , SHIP_MODEL_COMPLETE_FLAG
        , LOT_SUBSTITUTION_ENABLED
        , OUTSIDE_OPERATION_FLAG
        , AUTO_LOT_ALPHA_PREFIX
        , ATP_FLAG
        , EGO_MASTER_ITEMS_DFF_CTX
        , EAM_ACTIVITY_SOURCE_CODE
        , TAXABLE_FLAG
        , ALLOW_EXPRESS_DELIVERY_FLAG
        , PURCHASING_TAX_CODE
        , ENG_ITEM_FLAG
        , ENGINEERING_ITEM_ID
        , END_ASSEMBLY_PEGGING_FLAG
        , RETURNABLE_FLAG
        , PROCESS_YIELD_LOCATOR_ID
        , EAM_ACTIVITY_CAUSE_CODE
        , MATURITY_DAYS
        , ATP_COMPONENTS_FLAG
        , LAST_UPDATED_BY
        , COUPON_EXEMPT_FLAG
        , PLANNING_TIME_FENCE_DAYS
        , RECEIPT_REQUIRED_FLAG
        , VOLUME_UOM_CODE
        , LOCATION_CONTROL_CODE
        , WARRANTY_VENDOR_ID
        , INVENTORY_ASSET_FLAG
        , ENCUMBRANCE_ACCOUNT
        , SERVICEABLE_COMPONENT_FLAG
        , CUMULATIVE_TOTAL_LEAD_TIME
        , MRP_CALCULATE_ATP_FLAG
        , OUTSOURCED_ASSEMBLY
        , DEFAULT_LOT_STATUS_ID
        , VARIABLE_LEAD_TIME
        , AUTO_REDUCE_MPS
        , RECIPE_ENABLED_FLAG
        , ACCEPTABLE_RATE_DECREASE
        , BUILD_IN_WIP_FLAG
        , RECEIPT_DAYS_EXCEPTION_CODE
        , VEHICLE_ITEM_FLAG
        , CONFIG_MATCH
        , DOWNLOADABLE_FLAG
        , DEFAULT_SO_SOURCE_TYPE
        , FIXED_ORDER_QUANTITY
        , SUBSTITUTION_WINDOW_DAYS
        , EQUIPMENT_TYPE
        , CAS_NUMBER
        , SERV_IMPORTANCE_LEVEL
        , LOT_MERGE_ENABLED
        , SEGMENT2
        , CUSTOMER_ORDER_FLAG
        , ENABLED_FLAG
        , PURCHASING_ENABLED_FLAG
        , WH_UPDATE_DATE
        , OVERRUN_PERCENTAGE
        , ASSET_CREATION_CODE
        , DAYS_EARLY_RECEIPT_ALLOWED
        , NEGATIVE_MEASUREMENT_ERROR
        , BASE_WARRANTY_SERVICE_ID
        , START_AUTO_SERIAL_NUMBER
        , ROUNDING_CONTROL_TYPE
        , LOT_DIVISIBLE_FLAG
        , EXCLUDE_FROM_BUDGET_FLAG
        , MRP_PLANNING_CODE
        , BUYER_ID
        , RESERVABLE_TYPE
        , SOURCE_ORGANIZATION_ID
        , NEW_REVISION_CODE
        , DRP_PLANNED_FLAG
        , ASSET_CATEGORY_ID
        , MRP_SAFETY_STOCK_CODE
        , CONTINOUS_TRANSFER
        , HAZARDOUS_MATERIAL_FLAG
        , COSTING_ENABLED_FLAG
        , DIMENSION_UOM_CODE
        , SERVICE_DURATION_PERIOD_CODE
        , EVENT_FLAG
        , BULK_PICKED_FLAG
        , DEFAULT_SHIPPING_ORG
        , MATERIAL_BILLABLE_FLAG
        , PROCESS_QUALITY_ENABLED_FLAG
        , OPTION_SPECIFIC_SOURCED
        , SECONDARY_SPECIALIST_ID
        , PICKING_RULE_ID
        , EXPIRATION_ACTION_INTERVAL
        , ASN_AUTOEXPIRE_FLAG
        , START_AUTO_LOT_NUMBER
        , MINIMUM_ORDER_QUANTITY
        , COMMS_NL_TRACKABLE_FLAG
        , INVENTORY_CARRY_PENALTY
        , ENGINEERING_ECN_CODE
        , REPAIR_LEADTIME
        , SECONDARY_UOM_CODE
        , RECEIVING_ROUTING_ID
        , PRIMARY_UNIT_OF_MEASURE
        , CREATE_SUPPLY_FLAG
        , MAXIMUM_ORDER_QUANTITY
        , PROCESS_SUPPLY_SUBINVENTORY
        , PRODUCT_FAMILY_ITEM_ID
        , SOURCE_SUBINVENTORY
        , SERIAL_NUMBER_CONTROL_CODE
        , CREATED_BY
        , STYLE_ITEM_FLAG
        , CHARGE_PERIODICITY_CODE
        , INVOICE_ENABLED_FLAG
        , CONSIGNED_FLAG
        , DAYS_MAX_INV_SUPPLY
        , UNIT_HEIGHT
        , PROCESS_EXECUTION_ENABLED_FLAG
        , ROUNDING_FACTOR
        , OPERATION_SLACK_PENALTY
        , DEMAND_TIME_FENCE_DAYS
        , BASE_ITEM_ID
        , COLLATERAL_FLAG
        , REQUEST_ID
        , FULL_LEAD_TIME
        , SERVICE_ITEM_FLAG
        , INDIVISIBLE_FLAG
        , SERV_BILLING_ENABLED_FLAG
        , DIVERGENCE
        , SECONDARY_DEFAULT_IND
        , REVISION_QTY_CONTROL_CODE
        , QTY_RCV_TOLERANCE
        , DUAL_UOM_DEVIATION_HIGH
        , RELEASE_TIME_FENCE_CODE
        , ACCEPTABLE_RATE_INCREASE
        , RESTRICT_SUBINVENTORIES_CODE
        , CONFIG_ORGS
        , LAST_SUBMITTED_NIR_ID
        , RESTRICT_LOCATORS_CODE
        , CHILD_LOT_PREFIX
        , TRACKING_QUANTITY_IND
        , PROGRAM_UPDATE_DATE
        , START_DATE_ACTIVE
        , LIST_PRICE_PER_UNIT
        , CREATION_DATE
        , ENGINEERING_DATE
        , LAST_UPDATE_DATE
        , _FIVETRAN_DELETED
        , _FIVETRAN_ID
        , _FIVETRAN_SYNCED
        , PSA_DELETE_IND
        , PSA_LOAD_DTS
        , PSA_RECORD_SOURCE
        , LOAD_DTS
        , REC_SRC
        , BKCC
        , PLANT_BK
        , MD5_BINARY(UPPER(CONCAT_WS('||',
          COALESCE(NULLIF(TRIM(CAST(ITEM_BK as VARCHAR)),''), '^^')
        , COALESCE(NULLIF(TRIM(CAST(BKCC as VARCHAR)),''), '^^')
        ))) as ITEM_HK
        , MD5_BINARY(UPPER(CONCAT_WS('||',
          COALESCE(NULLIF(TRIM(CAST(PLANT_BK as VARCHAR)),''), '^^')
        , COALESCE(NULLIF(TRIM(CAST(BKCC as VARCHAR)),''), '^^')
        ))) as PLANT_HK
        , MD5_BINARY(UPPER(CONCAT_WS('||',
          COALESCE(NULLIF(TRIM(CAST(ITEM_BK as VARCHAR)),''), '^^')
        , COALESCE(NULLIF(TRIM(CAST(PLANT_BK as VARCHAR)),''), '^^')
        , COALESCE(NULLIF(TRIM(CAST(BKCC as VARCHAR)),''), '^^')
        ))) as PLANT_ITEM_HK
        , MD5_BINARY(UPPER(NULLIF(CONCAT(
              IFNULL(TRIM(INVENTORY_ITEM_ID::text), '^^') 
            , '||', IFNULL(TRIM(ORGANIZATION_ID::text), '^^') 
            , '||', IFNULL(TRIM(WIP_SUPPLY_LOCATOR_ID::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE30::text), '^^') 
            , '||', IFNULL(TRIM(REPAIR_PROGRAM::text), '^^') 
            , '||', IFNULL(TRIM(PARENT_CHILD_GENERATION_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(DEFAULT_MATERIAL_STATUS_ID::text), '^^') 
            , '||', IFNULL(TRIM(INTERNAL_ORDER_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(DAYS_TGT_INV_WINDOW::text), '^^') 
            , '||', IFNULL(TRIM(PLANNING_TIME_FENCE_CODE::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE29::text), '^^') 
            , '||', IFNULL(TRIM(WEB_STATUS::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE28::text), '^^') 
            , '||', IFNULL(TRIM(UNIT_WEIGHT::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE27::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE26::text), '^^') 
            , '||', IFNULL(TRIM(WIP_SUPPLY_TYPE::text), '^^') 
            , '||', IFNULL(TRIM(MTL_TRANSACTIONS_ENABLED_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE3::text), '^^') 
            , '||', IFNULL(TRIM(DAYS_LATE_RECEIPT_ALLOWED::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE2::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE1::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE9::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE8::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE7::text), '^^') 
            , '||', IFNULL(TRIM(UNIT_WIDTH::text), '^^') 
            , '||', IFNULL(TRIM(QTY_RCV_EXCEPTION_CODE::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE6::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE5::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE4::text), '^^') 
            , '||', IFNULL(TRIM(OVER_SHIPMENT_TOLERANCE::text), '^^') 
            , '||', IFNULL(TRIM(SHRINKAGE_RATE::text), '^^') 
            , '||', IFNULL(TRIM(LOT_SPLIT_ENABLED::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE10::text), '^^') 
            , '||', IFNULL(TRIM(MUST_USE_APPROVED_VENDOR_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE14::text), '^^') 
            , '||', IFNULL(TRIM(WIP_SUPPLY_SUBINVENTORY::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE13::text), '^^') 
            , '||', IFNULL(TRIM(PICK_COMPONENTS_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE12::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE11::text), '^^') 
            , '||', IFNULL(TRIM(APPROVAL_STATUS::text), '^^') 
            , '||', IFNULL(TRIM(DUAL_UOM_CONTROL::text), '^^') 
            , '||', IFNULL(TRIM(ONT_PRICING_QTY_SOURCE::text), '^^') 
            , '||', IFNULL(TRIM(EXPENSE_ACCOUNT::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE21::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE20::text), '^^') 
            , '||', IFNULL(TRIM(RESPONSE_TIME_PERIOD_CODE::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE25::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE24::text), '^^') 
            , '||', IFNULL(TRIM(PRICE_TOLERANCE_PERCENT::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE23::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE22::text), '^^') 
            , '||', IFNULL(TRIM(DEFAULT_SERIAL_STATUS_ID::text), '^^') 
            , '||', IFNULL(TRIM(SERVICEABLE_PRODUCT_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(CURRENT_PHASE_ID::text), '^^') 
            , '||', IFNULL(TRIM(RESPONSE_TIME_VALUE::text), '^^') 
            , '||', IFNULL(TRIM(PREPOSITION_POINT::text), '^^') 
            , '||', IFNULL(TRIM(MAX_MINMAX_QUANTITY::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE18::text), '^^') 
            , '||', IFNULL(TRIM(EAM_ACT_NOTIFICATION_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE17::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE16::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE15::text), '^^') 
            , '||', IFNULL(TRIM(DUAL_UOM_DEVIATION_LOW::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE19::text), '^^') 
            , '||', IFNULL(TRIM(PLANNER_CODE::text), '^^') 
            , '||', IFNULL(TRIM(INTERNAL_ORDER_ENABLED_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(POSITIVE_MEASUREMENT_ERROR::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE10::text), '^^') 
            , '||', IFNULL(TRIM(INVENTORY_PLANNING_CODE::text), '^^') 
            , '||', IFNULL(TRIM(INVENTORY_ITEM_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(COST_OF_SALES_ACCOUNT::text), '^^') 
            , '||', IFNULL(TRIM(OBJECT_VERSION_NUMBER::text), '^^') 
            , '||', IFNULL(TRIM(INSPECTION_REQUIRED_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(CHILD_LOT_STARTING_NUMBER::text), '^^') 
            , '||', IFNULL(TRIM(DAYS_MAX_INV_WINDOW::text), '^^') 
            , '||', IFNULL(TRIM(MARKET_PRICE::text), '^^') 
            , '||', IFNULL(TRIM(UNIT_OF_ISSUE::text), '^^') 
            , '||', IFNULL(TRIM(ACCEPTABLE_EARLY_DAYS::text), '^^') 
            , '||', IFNULL(TRIM(FIXED_LEAD_TIME::text), '^^') 
            , '||', IFNULL(TRIM(HOLD_DAYS::text), '^^') 
            , '||', IFNULL(TRIM(ENFORCE_SHIP_TO_LOCATION_CODE::text), '^^') 
            , '||', IFNULL(TRIM(SHELF_LIFE_CODE::text), '^^') 
            , '||', IFNULL(TRIM(PROCESS_COSTING_ENABLED_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(CRITICAL_COMPONENT_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(VENDOR_WARRANTY_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(FORECAST_HORIZON::text), '^^') 
            , '||', IFNULL(TRIM(ATO_FORECAST_CONTROL::text), '^^') 
            , '||', IFNULL(TRIM(USAGE_ITEM_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(SAFETY_STOCK_BUCKET_DAYS::text), '^^') 
            , '||', IFNULL(TRIM(REPAIR_YIELD::text), '^^') 
            , '||', IFNULL(TRIM(UNIT_LENGTH::text), '^^') 
            , '||', IFNULL(TRIM(DEFAULT_INCLUDE_IN_ROLLUP_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(DEFECT_TRACKING_ON_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(INVOICE_CLOSE_TOLERANCE::text), '^^') 
            , '||', IFNULL(TRIM(CHECK_SHORTAGES_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(ITEM_TYPE::text), '^^') 
            , '||', IFNULL(TRIM(SUMMARY_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(VMI_MINIMUM_DAYS::text), '^^') 
            , '||', IFNULL(TRIM(BOM_ITEM_TYPE::text), '^^') 
            , '||', IFNULL(TRIM(REPLENISH_TO_ORDER_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(EAM_ITEM_TYPE::text), '^^') 
            , '||', IFNULL(TRIM(PLANNING_MAKE_BUY_CODE::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE_CATEGORY::text), '^^') 
            , '||', IFNULL(TRIM(UN_NUMBER_ID::text), '^^') 
            , '||', IFNULL(TRIM(CARRYING_COST::text), '^^') 
            , '||', IFNULL(TRIM(PRIMARY_SPECIALIST_ID::text), '^^') 
            , '||', IFNULL(TRIM(WEIGHT_UOM_CODE::text), '^^') 
            , '||', IFNULL(TRIM(MINIMUM_LICENSE_QUANTITY::text), '^^') 
            , '||', IFNULL(TRIM(GRADE_CONTROL_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(VMI_FORECAST_TYPE::text), '^^') 
            , '||', IFNULL(TRIM(PAYMENT_TERMS_ID::text), '^^') 
            , '||', IFNULL(TRIM(OUTSIDE_OPERATION_UOM_TYPE::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE5::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE4::text), '^^') 
            , '||', IFNULL(TRIM(UNDER_RETURN_TOLERANCE::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE7::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE6::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE1::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE3::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE2::text), '^^') 
            , '||', IFNULL(TRIM(EAM_ACTIVITY_TYPE_CODE::text), '^^') 
            , '||', IFNULL(TRIM(STYLE_ITEM_ID::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE9::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE8::text), '^^') 
            , '||', IFNULL(TRIM(INVOICEABLE_ITEM_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(ELECTRONIC_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(POSTPROCESSING_LEAD_TIME::text), '^^') 
            , '||', IFNULL(TRIM(LIFECYCLE_ID::text), '^^') 
            , '||', IFNULL(TRIM(VMI_MAXIMUM_UNITS::text), '^^') 
            , '||', IFNULL(TRIM(SERVICEABLE_ITEM_CLASS_ID::text), '^^') 
            , '||', IFNULL(TRIM(CONTRACT_ITEM_TYPE_CODE::text), '^^') 
            , '||', IFNULL(TRIM(MODEL_CONFIG_CLAUSE_NAME::text), '^^') 
            , '||', IFNULL(TRIM(SERIAL_STATUS_ENABLED::text), '^^') 
            , '||', IFNULL(TRIM(EAM_ACT_SHUTDOWN_STATUS::text), '^^') 
            , '||', IFNULL(TRIM(AUTO_SERIAL_ALPHA_PREFIX::text), '^^') 
            , '||', IFNULL(TRIM(PLANNING_EXCEPTION_SET::text), '^^') 
            , '||', IFNULL(TRIM(PREPROCESSING_LEAD_TIME::text), '^^') 
            , '||', IFNULL(TRIM(RECEIVE_CLOSE_TOLERANCE::text), '^^') 
            , '||', IFNULL(TRIM(RETURN_INSPECTION_REQUIREMENT::text), '^^') 
            , '||', IFNULL(TRIM(COPY_LOT_ATTRIBUTE_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(SO_AUTHORIZATION_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(RETEST_INTERVAL::text), '^^') 
            , '||', IFNULL(TRIM(STOCK_ENABLED_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(RECOVERED_PART_DISP_CODE::text), '^^') 
            , '||', IFNULL(TRIM(OVER_RETURN_TOLERANCE::text), '^^') 
            , '||', IFNULL(TRIM(CONFIG_MODEL_TYPE::text), '^^') 
            , '||', IFNULL(TRIM(ALLOW_ITEM_DESC_UPDATE_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(INTERNAL_VOLUME::text), '^^') 
            , '||', IFNULL(TRIM(COVERAGE_SCHEDULE_ID::text), '^^') 
            , '||', IFNULL(TRIM(RFQ_REQUIRED_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(MIN_MINMAX_QUANTITY::text), '^^') 
            , '||', IFNULL(TRIM(DEMAND_TIME_FENCE_CODE::text), '^^') 
            , '||', IFNULL(TRIM(ORDERABLE_ON_WEB_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(CATALOG_STATUS_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(SEGMENT11::text), '^^') 
            , '||', IFNULL(TRIM(SEGMENT10::text), '^^') 
            , '||', IFNULL(TRIM(FIXED_DAYS_SUPPLY::text), '^^') 
            , '||', IFNULL(TRIM(SEGMENT13::text), '^^') 
            , '||', IFNULL(TRIM(CYCLE_COUNT_ENABLED_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(SEGMENT12::text), '^^') 
            , '||', IFNULL(TRIM(SEGMENT15::text), '^^') 
            , '||', IFNULL(TRIM(SEGMENT14::text), '^^') 
            , '||', IFNULL(TRIM(SEGMENT17::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE20::text), '^^') 
            , '||', IFNULL(TRIM(SEGMENT16::text), '^^') 
            , '||', IFNULL(TRIM(SEGMENT19::text), '^^') 
            , '||', IFNULL(TRIM(FIXED_LOT_MULTIPLIER::text), '^^') 
            , '||', IFNULL(TRIM(SEGMENT18::text), '^^') 
            , '||', IFNULL(TRIM(DAYS_TGT_INV_SUPPLY::text), '^^') 
            , '||', IFNULL(TRIM(SO_TRANSACTIONS_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(CHILD_LOT_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE17::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE18::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE15::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE16::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE13::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE14::text), '^^') 
            , '||', IFNULL(TRIM(VOL_DISCOUNT_EXEMPT_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(PLANNED_INV_POINT_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE11::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE12::text), '^^') 
            , '||', IFNULL(TRIM(PREVENTIVE_MAINTENANCE_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(LOT_CONTROL_CODE::text), '^^') 
            , '||', IFNULL(TRIM(MAX_WARRANTY_AMOUNT::text), '^^') 
            , '||', IFNULL(TRIM(SUBSTITUTION_WINDOW_CODE::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE19::text), '^^') 
            , '||', IFNULL(TRIM(SEGMENT20::text), '^^') 
            , '||', IFNULL(TRIM(GDSN_OUTBOUND_ENABLED_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(ORDER_COST::text), '^^') 
            , '||', IFNULL(TRIM(CHILD_LOT_VALIDATION_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(UNDER_SHIPMENT_TOLERANCE::text), '^^') 
            , '||', IFNULL(TRIM(INVOICING_RULE_ID::text), '^^') 
            , '||', IFNULL(TRIM(COMMS_ACTIVATION_REQD_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(HAZARD_CLASS_ID::text), '^^') 
            , '||', IFNULL(TRIM(EXPENSE_BILLABLE_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(LOT_STATUS_ENABLED::text), '^^') 
            , '||', IFNULL(TRIM(EFFECTIVITY_CONTROL::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE_CATEGORY::text), '^^') 
            , '||', IFNULL(TRIM(SUBSCRIPTION_DEPEND_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(PROGRAM_APPLICATION_ID::text), '^^') 
            , '||', IFNULL(TRIM(VMI_MINIMUM_UNITS::text), '^^') 
            , '||', IFNULL(TRIM(TIME_BILLABLE_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(PRORATE_SERVICE_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(REPETITIVE_PLANNING_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(ALLOW_SUBSTITUTE_RECEIPTS_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(OVERCOMPLETION_TOLERANCE_TYPE::text), '^^') 
            , '||', IFNULL(TRIM(BOM_ENABLED_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(SHIPPABLE_ITEM_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(PURCHASING_ITEM_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(SOURCE_TYPE::text), '^^') 
            , '||', IFNULL(TRIM(SERV_REQ_ENABLED_CODE::text), '^^') 
            , '||', IFNULL(TRIM(IB_ITEM_INSTANCE_CLASS::text), '^^') 
            , '||', IFNULL(TRIM(LOT_TRANSLATE_ENABLED::text), '^^') 
            , '||', IFNULL(TRIM(MAXIMUM_LOAD_WEIGHT::text), '^^') 
            , '||', IFNULL(TRIM(SERVICE_DURATION::text), '^^') 
            , '||', IFNULL(TRIM(MRP_SAFETY_STOCK_PERCENT::text), '^^') 
            , '||', IFNULL(TRIM(ALLOW_UNORDERED_RECEIPTS_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(ALLOWED_UNITS_LOOKUP_CODE::text), '^^') 
            , '||', IFNULL(TRIM(LAST_UPDATE_LOGIN::text), '^^') 
            , '||', IFNULL(TRIM(PROCESS_SUPPLY_LOCATOR_ID::text), '^^') 
            , '||', IFNULL(TRIM(PROCESS_YIELD_SUBINVENTORY::text), '^^') 
            , '||', IFNULL(TRIM(ACCOUNTING_RULE_ID::text), '^^') 
            , '||', IFNULL(TRIM(VMI_MAXIMUM_DAYS::text), '^^') 
            , '||', IFNULL(TRIM(INVENTORY_ITEM_STATUS_CODE::text), '^^') 
            , '||', IFNULL(TRIM(TAX_CODE::text), '^^') 
            , '||', IFNULL(TRIM(AUTO_CREATED_CONFIG_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(SUBCONTRACTING_COMPONENT::text), '^^') 
            , '||', IFNULL(TRIM(VMI_FIXED_ORDER_QUANTITY::text), '^^') 
            , '||', IFNULL(TRIM(PROGRAM_ID::text), '^^') 
            , '||', IFNULL(TRIM(CONTAINER_ITEM_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(SEGMENT8::text), '^^') 
            , '||', IFNULL(TRIM(SEGMENT7::text), '^^') 
            , '||', IFNULL(TRIM(SEGMENT9::text), '^^') 
            , '||', IFNULL(TRIM(SERIAL_TAGGING_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(SEGMENT4::text), '^^') 
            , '||', IFNULL(TRIM(SEGMENT3::text), '^^') 
            , '||', IFNULL(TRIM(EXPIRATION_ACTION_CODE::text), '^^') 
            , '||', IFNULL(TRIM(SEGMENT6::text), '^^') 
            , '||', IFNULL(TRIM(SEGMENT5::text), '^^') 
            , '||', IFNULL(TRIM(TRADE_ITEM_DESCRIPTOR::text), '^^') 
            , '||', IFNULL(TRIM(MINIMUM_FILL_PERCENT::text), '^^') 
            , '||', IFNULL(TRIM(END_DATE_ACTIVE::text), '^^') 
            , '||', IFNULL(TRIM(SALES_ACCOUNT::text), '^^') 
            , '||', IFNULL(TRIM(BACK_ORDERABLE_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(STD_LOT_SIZE::text), '^^') 
            , '||', IFNULL(TRIM(FINANCING_ALLOWED_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(LEAD_TIME_LOT_SIZE::text), '^^') 
            , '||', IFNULL(TRIM(PRIMARY_UOM_CODE::text), '^^') 
            , '||', IFNULL(TRIM(SHELF_LIFE_DAYS::text), '^^') 
            , '||', IFNULL(TRIM(CONTAINER_TYPE_CODE::text), '^^') 
            , '||', IFNULL(TRIM(DEFAULT_GRADE::text), '^^') 
            , '||', IFNULL(TRIM(CUSTOMER_ORDER_ENABLED_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(ITEM_CATALOG_GROUP_ID::text), '^^') 
            , '||', IFNULL(TRIM(ATP_RULE_ID::text), '^^') 
            , '||', IFNULL(TRIM(SERVICE_STARTING_DELAY::text), '^^') 
            , '||', IFNULL(TRIM(RELEASE_TIME_FENCE_DAYS::text), '^^') 
            , '||', IFNULL(TRIM(OVERCOMPLETION_TOLERANCE_VALUE::text), '^^') 
            , '||', IFNULL(TRIM(UNIT_VOLUME::text), '^^') 
            , '||', IFNULL(TRIM(DESCRIPTION::text), '^^') 
            , '||', IFNULL(TRIM(CONVERGENCE::text), '^^') 
            , '||', IFNULL(TRIM(CUM_MANUFACTURING_LEAD_TIME::text), '^^') 
            , '||', IFNULL(TRIM(SHIP_MODEL_COMPLETE_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(LOT_SUBSTITUTION_ENABLED::text), '^^') 
            , '||', IFNULL(TRIM(OUTSIDE_OPERATION_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(AUTO_LOT_ALPHA_PREFIX::text), '^^') 
            , '||', IFNULL(TRIM(ATP_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(EGO_MASTER_ITEMS_DFF_CTX::text), '^^') 
            , '||', IFNULL(TRIM(EAM_ACTIVITY_SOURCE_CODE::text), '^^') 
            , '||', IFNULL(TRIM(TAXABLE_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(ALLOW_EXPRESS_DELIVERY_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(PURCHASING_TAX_CODE::text), '^^') 
            , '||', IFNULL(TRIM(ENG_ITEM_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(ENGINEERING_ITEM_ID::text), '^^') 
            , '||', IFNULL(TRIM(END_ASSEMBLY_PEGGING_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(RETURNABLE_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(PROCESS_YIELD_LOCATOR_ID::text), '^^') 
            , '||', IFNULL(TRIM(EAM_ACTIVITY_CAUSE_CODE::text), '^^') 
            , '||', IFNULL(TRIM(MATURITY_DAYS::text), '^^') 
            , '||', IFNULL(TRIM(ATP_COMPONENTS_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(LAST_UPDATED_BY::text), '^^') 
            , '||', IFNULL(TRIM(COUPON_EXEMPT_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(PLANNING_TIME_FENCE_DAYS::text), '^^') 
            , '||', IFNULL(TRIM(RECEIPT_REQUIRED_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(VOLUME_UOM_CODE::text), '^^') 
            , '||', IFNULL(TRIM(LOCATION_CONTROL_CODE::text), '^^') 
            , '||', IFNULL(TRIM(WARRANTY_VENDOR_ID::text), '^^') 
            , '||', IFNULL(TRIM(INVENTORY_ASSET_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(ENCUMBRANCE_ACCOUNT::text), '^^') 
            , '||', IFNULL(TRIM(SERVICEABLE_COMPONENT_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(CUMULATIVE_TOTAL_LEAD_TIME::text), '^^') 
            , '||', IFNULL(TRIM(MRP_CALCULATE_ATP_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(OUTSOURCED_ASSEMBLY::text), '^^') 
            , '||', IFNULL(TRIM(DEFAULT_LOT_STATUS_ID::text), '^^') 
            , '||', IFNULL(TRIM(VARIABLE_LEAD_TIME::text), '^^') 
            , '||', IFNULL(TRIM(AUTO_REDUCE_MPS::text), '^^') 
            , '||', IFNULL(TRIM(RECIPE_ENABLED_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(ACCEPTABLE_RATE_DECREASE::text), '^^') 
            , '||', IFNULL(TRIM(BUILD_IN_WIP_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(RECEIPT_DAYS_EXCEPTION_CODE::text), '^^') 
            , '||', IFNULL(TRIM(VEHICLE_ITEM_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(CONFIG_MATCH::text), '^^') 
            , '||', IFNULL(TRIM(DOWNLOADABLE_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(DEFAULT_SO_SOURCE_TYPE::text), '^^') 
            , '||', IFNULL(TRIM(FIXED_ORDER_QUANTITY::text), '^^') 
            , '||', IFNULL(TRIM(SUBSTITUTION_WINDOW_DAYS::text), '^^') 
            , '||', IFNULL(TRIM(EQUIPMENT_TYPE::text), '^^') 
            , '||', IFNULL(TRIM(CAS_NUMBER::text), '^^') 
            , '||', IFNULL(TRIM(SERV_IMPORTANCE_LEVEL::text), '^^') 
            , '||', IFNULL(TRIM(LOT_MERGE_ENABLED::text), '^^') 
            , '||', IFNULL(TRIM(SEGMENT2::text), '^^') 
            , '||', IFNULL(TRIM(CUSTOMER_ORDER_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(ENABLED_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(PURCHASING_ENABLED_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(WH_UPDATE_DATE::text), '^^') 
            , '||', IFNULL(TRIM(OVERRUN_PERCENTAGE::text), '^^') 
            , '||', IFNULL(TRIM(ASSET_CREATION_CODE::text), '^^') 
            , '||', IFNULL(TRIM(DAYS_EARLY_RECEIPT_ALLOWED::text), '^^') 
            , '||', IFNULL(TRIM(NEGATIVE_MEASUREMENT_ERROR::text), '^^') 
            , '||', IFNULL(TRIM(BASE_WARRANTY_SERVICE_ID::text), '^^') 
            , '||', IFNULL(TRIM(START_AUTO_SERIAL_NUMBER::text), '^^') 
            , '||', IFNULL(TRIM(ROUNDING_CONTROL_TYPE::text), '^^') 
            , '||', IFNULL(TRIM(LOT_DIVISIBLE_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(EXCLUDE_FROM_BUDGET_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(MRP_PLANNING_CODE::text), '^^') 
            , '||', IFNULL(TRIM(BUYER_ID::text), '^^') 
            , '||', IFNULL(TRIM(RESERVABLE_TYPE::text), '^^') 
            , '||', IFNULL(TRIM(SOURCE_ORGANIZATION_ID::text), '^^') 
            , '||', IFNULL(TRIM(NEW_REVISION_CODE::text), '^^') 
            , '||', IFNULL(TRIM(DRP_PLANNED_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(ASSET_CATEGORY_ID::text), '^^') 
            , '||', IFNULL(TRIM(MRP_SAFETY_STOCK_CODE::text), '^^') 
            , '||', IFNULL(TRIM(CONTINOUS_TRANSFER::text), '^^') 
            , '||', IFNULL(TRIM(HAZARDOUS_MATERIAL_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(COSTING_ENABLED_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(DIMENSION_UOM_CODE::text), '^^') 
            , '||', IFNULL(TRIM(SERVICE_DURATION_PERIOD_CODE::text), '^^') 
            , '||', IFNULL(TRIM(EVENT_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(BULK_PICKED_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(DEFAULT_SHIPPING_ORG::text), '^^') 
            , '||', IFNULL(TRIM(MATERIAL_BILLABLE_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(PROCESS_QUALITY_ENABLED_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(OPTION_SPECIFIC_SOURCED::text), '^^') 
            , '||', IFNULL(TRIM(SECONDARY_SPECIALIST_ID::text), '^^') 
            , '||', IFNULL(TRIM(PICKING_RULE_ID::text), '^^') 
            , '||', IFNULL(TRIM(EXPIRATION_ACTION_INTERVAL::text), '^^') 
            , '||', IFNULL(TRIM(ASN_AUTOEXPIRE_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(START_AUTO_LOT_NUMBER::text), '^^') 
            , '||', IFNULL(TRIM(MINIMUM_ORDER_QUANTITY::text), '^^') 
            , '||', IFNULL(TRIM(COMMS_NL_TRACKABLE_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(INVENTORY_CARRY_PENALTY::text), '^^') 
            , '||', IFNULL(TRIM(ENGINEERING_ECN_CODE::text), '^^') 
            , '||', IFNULL(TRIM(REPAIR_LEADTIME::text), '^^') 
            , '||', IFNULL(TRIM(SECONDARY_UOM_CODE::text), '^^') 
            , '||', IFNULL(TRIM(RECEIVING_ROUTING_ID::text), '^^') 
            , '||', IFNULL(TRIM(PRIMARY_UNIT_OF_MEASURE::text), '^^') 
            , '||', IFNULL(TRIM(CREATE_SUPPLY_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(MAXIMUM_ORDER_QUANTITY::text), '^^') 
            , '||', IFNULL(TRIM(PROCESS_SUPPLY_SUBINVENTORY::text), '^^') 
            , '||', IFNULL(TRIM(PRODUCT_FAMILY_ITEM_ID::text), '^^') 
            , '||', IFNULL(TRIM(SOURCE_SUBINVENTORY::text), '^^') 
            , '||', IFNULL(TRIM(SERIAL_NUMBER_CONTROL_CODE::text), '^^') 
            , '||', IFNULL(TRIM(CREATED_BY::text), '^^') 
            , '||', IFNULL(TRIM(STYLE_ITEM_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(CHARGE_PERIODICITY_CODE::text), '^^') 
            , '||', IFNULL(TRIM(INVOICE_ENABLED_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(CONSIGNED_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(DAYS_MAX_INV_SUPPLY::text), '^^') 
            , '||', IFNULL(TRIM(UNIT_HEIGHT::text), '^^') 
            , '||', IFNULL(TRIM(PROCESS_EXECUTION_ENABLED_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(ROUNDING_FACTOR::text), '^^') 
            , '||', IFNULL(TRIM(OPERATION_SLACK_PENALTY::text), '^^') 
            , '||', IFNULL(TRIM(DEMAND_TIME_FENCE_DAYS::text), '^^') 
            , '||', IFNULL(TRIM(BASE_ITEM_ID::text), '^^') 
            , '||', IFNULL(TRIM(COLLATERAL_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(REQUEST_ID::text), '^^') 
            , '||', IFNULL(TRIM(FULL_LEAD_TIME::text), '^^') 
            , '||', IFNULL(TRIM(SERVICE_ITEM_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(INDIVISIBLE_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(SERV_BILLING_ENABLED_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(DIVERGENCE::text), '^^') 
            , '||', IFNULL(TRIM(SECONDARY_DEFAULT_IND::text), '^^') 
            , '||', IFNULL(TRIM(REVISION_QTY_CONTROL_CODE::text), '^^') 
            , '||', IFNULL(TRIM(QTY_RCV_TOLERANCE::text), '^^') 
            , '||', IFNULL(TRIM(DUAL_UOM_DEVIATION_HIGH::text), '^^') 
            , '||', IFNULL(TRIM(RELEASE_TIME_FENCE_CODE::text), '^^') 
            , '||', IFNULL(TRIM(ACCEPTABLE_RATE_INCREASE::text), '^^') 
            , '||', IFNULL(TRIM(RESTRICT_SUBINVENTORIES_CODE::text), '^^') 
            , '||', IFNULL(TRIM(CONFIG_ORGS::text), '^^') 
            , '||', IFNULL(TRIM(LAST_SUBMITTED_NIR_ID::text), '^^') 
            , '||', IFNULL(TRIM(RESTRICT_LOCATORS_CODE::text), '^^') 
            , '||', IFNULL(TRIM(CHILD_LOT_PREFIX::text), '^^') 
            , '||', IFNULL(TRIM(TRACKING_QUANTITY_IND::text), '^^') 
            , '||', IFNULL(TRIM(PROGRAM_UPDATE_DATE::text), '^^') 
            , '||', IFNULL(TRIM(START_DATE_ACTIVE::text), '^^') 
            , '||', IFNULL(TRIM(LIST_PRICE_PER_UNIT::text), '^^') 
            , '||', IFNULL(TRIM(CREATION_DATE::text), '^^') 
            , '||', IFNULL(TRIM(ENGINEERING_DATE::text), '^^') 
            , '||', IFNULL(TRIM(LAST_UPDATE_DATE::text), '^^') 
            , '||', IFNULL(TRIM(_FIVETRAN_DELETED::text), '^^') 
        ), '^^||^^')))  as HASHDIFF
FROM JOIN_RESULT
