---- SRC LAYER ----
WITH
SRC_S              as ( SELECT ACCEPTABLE_EARLY_DAYS, ACCEPTABLE_RATE_DECREASE, ACCEPTABLE_RATE_INCREASE, ACCOUNTING_RULE_ID, ALLOWED_UNITS_LOOKUP_CODE, ALLOW_EXPRESS_DELIVERY_FLAG, ALLOW_ITEM_DESC_UPDATE_FLAG, ALLOW_SUBSTITUTE_RECEIPTS_FLAG, ALLOW_UNORDERED_RECEIPTS_FLAG, APPROVAL_STATUS, ASN_AUTOEXPIRE_FLAG, ASSET_CATEGORY_ID, ASSET_CREATION_CODE, ATO_FORECAST_CONTROL, ATP_COMPONENTS_FLAG, ATP_FLAG, ATP_RULE_ID, ATTRIBUTE1, ATTRIBUTE10, ATTRIBUTE11, ATTRIBUTE12, ATTRIBUTE13, ATTRIBUTE14, ATTRIBUTE15, ATTRIBUTE16, ATTRIBUTE17, ATTRIBUTE18, ATTRIBUTE19, ATTRIBUTE2, ATTRIBUTE20, ATTRIBUTE21, ATTRIBUTE22, ATTRIBUTE23, ATTRIBUTE24, ATTRIBUTE25, ATTRIBUTE26, ATTRIBUTE27, ATTRIBUTE28, ATTRIBUTE29, ATTRIBUTE3, ATTRIBUTE30, ATTRIBUTE4, ATTRIBUTE5, ATTRIBUTE6, ATTRIBUTE7, ATTRIBUTE8, ATTRIBUTE9, ATTRIBUTE_CATEGORY, AUTO_CREATED_CONFIG_FLAG, AUTO_LOT_ALPHA_PREFIX, AUTO_REDUCE_MPS, AUTO_SERIAL_ALPHA_PREFIX, BACK_ORDERABLE_FLAG, BASE_ITEM_ID, BASE_WARRANTY_SERVICE_ID, BOM_ENABLED_FLAG, BOM_ITEM_TYPE, BUILD_IN_WIP_FLAG, BULK_PICKED_FLAG, BUYER_ID, CARRYING_COST, CAS_NUMBER, CATALOG_STATUS_FLAG, CHARGE_PERIODICITY_CODE, CHECK_SHORTAGES_FLAG, CHILD_LOT_FLAG, CHILD_LOT_PREFIX, CHILD_LOT_STARTING_NUMBER, CHILD_LOT_VALIDATION_FLAG, COLLATERAL_FLAG, COMMS_ACTIVATION_REQD_FLAG, COMMS_NL_TRACKABLE_FLAG, CONFIG_MATCH, CONFIG_MODEL_TYPE, CONFIG_ORGS, CONSIGNED_FLAG, CONTAINER_ITEM_FLAG, CONTAINER_TYPE_CODE, CONTINOUS_TRANSFER, CONTRACT_ITEM_TYPE_CODE, CONVERGENCE, COPY_LOT_ATTRIBUTE_FLAG, COSTING_ENABLED_FLAG, COST_OF_SALES_ACCOUNT, COUPON_EXEMPT_FLAG, COVERAGE_SCHEDULE_ID, CREATED_BY, CREATE_SUPPLY_FLAG, CREATION_DATE, CRITICAL_COMPONENT_FLAG, CUMULATIVE_TOTAL_LEAD_TIME, CUM_MANUFACTURING_LEAD_TIME, CURRENT_PHASE_ID, CUSTOMER_ORDER_ENABLED_FLAG, CUSTOMER_ORDER_FLAG, CYCLE_COUNT_ENABLED_FLAG, DAYS_EARLY_RECEIPT_ALLOWED, DAYS_LATE_RECEIPT_ALLOWED, DAYS_MAX_INV_SUPPLY, DAYS_MAX_INV_WINDOW, DAYS_TGT_INV_SUPPLY, DAYS_TGT_INV_WINDOW, DEFAULT_GRADE, DEFAULT_INCLUDE_IN_ROLLUP_FLAG, DEFAULT_LOT_STATUS_ID, DEFAULT_MATERIAL_STATUS_ID, DEFAULT_SERIAL_STATUS_ID, DEFAULT_SHIPPING_ORG, DEFAULT_SO_SOURCE_TYPE, DEFECT_TRACKING_ON_FLAG, DEMAND_TIME_FENCE_CODE, DEMAND_TIME_FENCE_DAYS, DESCRIPTION, DIMENSION_UOM_CODE, DIVERGENCE, DOWNLOADABLE_FLAG, DRP_PLANNED_FLAG, DUAL_UOM_CONTROL, DUAL_UOM_DEVIATION_HIGH, DUAL_UOM_DEVIATION_LOW, EAM_ACTIVITY_CAUSE_CODE, EAM_ACTIVITY_SOURCE_CODE, EAM_ACTIVITY_TYPE_CODE, EAM_ACT_NOTIFICATION_FLAG, EAM_ACT_SHUTDOWN_STATUS, EAM_ITEM_TYPE, EFFECTIVITY_CONTROL, EGO_MASTER_ITEMS_DFF_CTX, ELECTRONIC_FLAG, ENABLED_FLAG, ENCUMBRANCE_ACCOUNT, END_ASSEMBLY_PEGGING_FLAG, END_DATE_ACTIVE, ENFORCE_SHIP_TO_LOCATION_CODE, ENGINEERING_DATE, ENGINEERING_ECN_CODE, ENGINEERING_ITEM_ID, ENG_ITEM_FLAG, EQUIPMENT_TYPE, EVENT_FLAG, EXCLUDE_FROM_BUDGET_FLAG, EXPENSE_ACCOUNT, EXPENSE_BILLABLE_FLAG, EXPIRATION_ACTION_CODE, EXPIRATION_ACTION_INTERVAL, FINANCING_ALLOWED_FLAG, FIXED_DAYS_SUPPLY, FIXED_LEAD_TIME, FIXED_LOT_MULTIPLIER, FIXED_ORDER_QUANTITY, FORECAST_HORIZON, FULL_LEAD_TIME, GDSN_OUTBOUND_ENABLED_FLAG, GLOBAL_ATTRIBUTE1, GLOBAL_ATTRIBUTE10, GLOBAL_ATTRIBUTE11, GLOBAL_ATTRIBUTE12, GLOBAL_ATTRIBUTE13, GLOBAL_ATTRIBUTE14, GLOBAL_ATTRIBUTE15, GLOBAL_ATTRIBUTE16, GLOBAL_ATTRIBUTE17, GLOBAL_ATTRIBUTE18, GLOBAL_ATTRIBUTE19, GLOBAL_ATTRIBUTE2, GLOBAL_ATTRIBUTE20, GLOBAL_ATTRIBUTE21, GLOBAL_ATTRIBUTE22, GLOBAL_ATTRIBUTE23, GLOBAL_ATTRIBUTE24, GLOBAL_ATTRIBUTE25, GLOBAL_ATTRIBUTE26, GLOBAL_ATTRIBUTE27, GLOBAL_ATTRIBUTE28, GLOBAL_ATTRIBUTE29, GLOBAL_ATTRIBUTE3, GLOBAL_ATTRIBUTE30, GLOBAL_ATTRIBUTE31, GLOBAL_ATTRIBUTE32, GLOBAL_ATTRIBUTE33, GLOBAL_ATTRIBUTE34, GLOBAL_ATTRIBUTE35, GLOBAL_ATTRIBUTE36, GLOBAL_ATTRIBUTE37, GLOBAL_ATTRIBUTE38, GLOBAL_ATTRIBUTE39, GLOBAL_ATTRIBUTE4, GLOBAL_ATTRIBUTE40, GLOBAL_ATTRIBUTE5, GLOBAL_ATTRIBUTE6, GLOBAL_ATTRIBUTE7, GLOBAL_ATTRIBUTE8, GLOBAL_ATTRIBUTE9, GLOBAL_ATTRIBUTE_CATEGORY, GRADE_CONTROL_FLAG, HAZARDOUS_MATERIAL_FLAG, HAZARD_CLASS_ID, HOLD_DAYS, IB_ITEM_INSTANCE_CLASS, IB_ITEM_TRACKING_LEVEL, INDIVISIBLE_FLAG, INSPECTION_REQUIRED_FLAG, INTERNAL_ORDER_ENABLED_FLAG, INTERNAL_ORDER_FLAG, INTERNAL_VOLUME, INVENTORY_ASSET_FLAG, INVENTORY_CARRY_PENALTY, INVENTORY_ITEM_FLAG, INVENTORY_ITEM_ID, INVENTORY_ITEM_STATUS_CODE, INVENTORY_PLANNING_CODE, INVOICEABLE_ITEM_FLAG, INVOICE_CLOSE_TOLERANCE, INVOICE_ENABLED_FLAG, INVOICING_RULE_ID, ITEM_CATALOG_GROUP_ID, ITEM_TYPE, LAST_SUBMITTED_NIR_ID, LAST_UPDATED_BY, LAST_UPDATE_DATE, LAST_UPDATE_LOGIN, LEAD_TIME_LOT_SIZE, LIFECYCLE_ID, LIST_PRICE_PER_UNIT, LOCATION_CONTROL_CODE, LOT_CONTROL_CODE, LOT_DIVISIBLE_FLAG, LOT_MERGE_ENABLED, LOT_SPLIT_ENABLED, LOT_STATUS_ENABLED, LOT_SUBSTITUTION_ENABLED, LOT_TRANSLATE_ENABLED, MARKET_PRICE, MATERIAL_BILLABLE_FLAG, MATURITY_DAYS, MAXIMUM_LOAD_WEIGHT, MAXIMUM_ORDER_QUANTITY, MAX_MINMAX_QUANTITY, MAX_WARRANTY_AMOUNT, MCC_CLASSIFICATION_TYPE, MCC_CONTROL_CODE, MCC_TRACKING_CODE, MINIMUM_FILL_PERCENT, MINIMUM_LICENSE_QUANTITY, MINIMUM_ORDER_QUANTITY, MIN_MINMAX_QUANTITY, MODEL_CONFIG_CLAUSE_NAME, MRP_CALCULATE_ATP_FLAG, MRP_PLANNING_CODE, MRP_SAFETY_STOCK_CODE, MRP_SAFETY_STOCK_PERCENT, MTL_TRANSACTIONS_ENABLED_FLAG, MUST_USE_APPROVED_VENDOR_FLAG, NEGATIVE_MEASUREMENT_ERROR, NEW_REVISION_CODE, OBJECT_VERSION_NUMBER, ONT_PRICING_QTY_SOURCE, OPERATION_SLACK_PENALTY, OPTION_SPECIFIC_SOURCED, ORDERABLE_ON_WEB_FLAG, ORDER_COST, ORGANIZATION_ID, OUTSIDE_OPERATION_FLAG, OUTSIDE_OPERATION_UOM_TYPE, OUTSOURCED_ASSEMBLY, OVERCOMPLETION_TOLERANCE_TYPE, OVERCOMPLETION_TOLERANCE_VALUE, OVERRUN_PERCENTAGE, OVER_RETURN_TOLERANCE, OVER_SHIPMENT_TOLERANCE, PARENT_CHILD_GENERATION_FLAG, PAYMENT_TERMS_ID, PICKING_RULE_ID, PICK_COMPONENTS_FLAG, PLANNED_INV_POINT_FLAG, PLANNER_CODE, PLANNING_EXCEPTION_SET, PLANNING_MAKE_BUY_CODE, PLANNING_TIME_FENCE_CODE, PLANNING_TIME_FENCE_DAYS, POSITIVE_MEASUREMENT_ERROR, POSTPROCESSING_LEAD_TIME, PREPOSITION_POINT, PREPROCESSING_LEAD_TIME, PREVENTIVE_MAINTENANCE_FLAG, PRICE_TOLERANCE_PERCENT, PRIMARY_SPECIALIST_ID, PRIMARY_UNIT_OF_MEASURE, PRIMARY_UOM_CODE, PROCESS_COSTING_ENABLED_FLAG, PROCESS_EXECUTION_ENABLED_FLAG, PROCESS_QUALITY_ENABLED_FLAG, PROCESS_SUPPLY_LOCATOR_ID, PROCESS_SUPPLY_SUBINVENTORY, PROCESS_YIELD_LOCATOR_ID, PROCESS_YIELD_SUBINVENTORY, PRODUCT_FAMILY_ITEM_ID, PROGRAM_APPLICATION_ID, PROGRAM_ID, PROGRAM_UPDATE_DATE, PRORATE_SERVICE_FLAG, PSA_DELETE_IND, PSA_LOAD_DTS, PSA_RECORD_SOURCE, PURCHASING_ENABLED_FLAG, PURCHASING_ITEM_FLAG, PURCHASING_TAX_CODE, QTY_RCV_EXCEPTION_CODE, QTY_RCV_TOLERANCE, RECEIPT_DAYS_EXCEPTION_CODE, RECEIPT_REQUIRED_FLAG, RECEIVE_CLOSE_TOLERANCE, RECEIVING_ROUTING_ID, RECIPE_ENABLED_FLAG, RECOVERED_PART_DISP_CODE, RELEASE_TIME_FENCE_CODE, RELEASE_TIME_FENCE_DAYS, REPAIR_LEADTIME, REPAIR_PROGRAM, REPAIR_YIELD, REPETITIVE_PLANNING_FLAG, REPLENISH_TO_ORDER_FLAG, REQUEST_ID, RESERVABLE_TYPE, RESPONSE_TIME_PERIOD_CODE, RESPONSE_TIME_VALUE, RESTRICT_LOCATORS_CODE, RESTRICT_SUBINVENTORIES_CODE, RETEST_INTERVAL, RETURNABLE_FLAG, RETURN_INSPECTION_REQUIREMENT, REVISION_QTY_CONTROL_CODE, RFQ_REQUIRED_FLAG, ROUNDING_CONTROL_TYPE, ROUNDING_FACTOR, SAFETY_STOCK_BUCKET_DAYS, SALES_ACCOUNT, SECONDARY_DEFAULT_IND, SECONDARY_SPECIALIST_ID, SECONDARY_UOM_CODE, SEGMENT1, SEGMENT10, SEGMENT11, SEGMENT12, SEGMENT13, SEGMENT14, SEGMENT15, SEGMENT16, SEGMENT17, SEGMENT18, SEGMENT19, SEGMENT2, SEGMENT20, SEGMENT3, SEGMENT4, SEGMENT5, SEGMENT6, SEGMENT7, SEGMENT8, SEGMENT9, SERIAL_NUMBER_CONTROL_CODE, SERIAL_STATUS_ENABLED, SERIAL_TAGGING_FLAG, SERVICEABLE_COMPONENT_FLAG, SERVICEABLE_ITEM_CLASS_ID, SERVICEABLE_PRODUCT_FLAG, SERVICE_DURATION, SERVICE_DURATION_PERIOD_CODE, SERVICE_ITEM_FLAG, SERVICE_STARTING_DELAY, SERV_BILLING_ENABLED_FLAG, SERV_IMPORTANCE_LEVEL, SERV_REQ_ENABLED_CODE, SHELF_LIFE_CODE, SHELF_LIFE_DAYS, SHIPPABLE_ITEM_FLAG, SHIP_MODEL_COMPLETE_FLAG, SHRINKAGE_RATE, SOURCE_ORGANIZATION_ID, SOURCE_SUBINVENTORY, SOURCE_TYPE, SO_AUTHORIZATION_FLAG, SO_TRANSACTIONS_FLAG, START_AUTO_LOT_NUMBER, START_AUTO_SERIAL_NUMBER, START_DATE_ACTIVE, STD_LOT_SIZE, STOCK_ENABLED_FLAG, STYLE_ITEM_FLAG, STYLE_ITEM_ID, SUBCONTRACTING_COMPONENT, SUBSCRIPTION_DEPEND_FLAG, SUBSTITUTION_WINDOW_CODE, SUBSTITUTION_WINDOW_DAYS, SUMMARY_FLAG, TAXABLE_FLAG, TAX_CODE, TIME_BILLABLE_FLAG, TRACKING_QUANTITY_IND, TRADE_ITEM_DESCRIPTOR, UNDER_RETURN_TOLERANCE, UNDER_SHIPMENT_TOLERANCE, UNIT_HEIGHT, UNIT_LENGTH, UNIT_OF_ISSUE, UNIT_VOLUME, UNIT_WEIGHT, UNIT_WIDTH, UN_NUMBER_ID, USAGE_ITEM_FLAG, VARIABLE_LEAD_TIME, VEHICLE_ITEM_FLAG, VENDOR_WARRANTY_FLAG, VMI_FIXED_ORDER_QUANTITY, VMI_FORECAST_TYPE, VMI_MAXIMUM_DAYS, VMI_MAXIMUM_UNITS, VMI_MINIMUM_DAYS, VMI_MINIMUM_UNITS, VOLUME_UOM_CODE, VOL_DISCOUNT_EXEMPT_FLAG, WARRANTY_VENDOR_ID, WEB_STATUS, WEIGHT_UOM_CODE, WH_UPDATE_DATE, WIP_SUPPLY_LOCATOR_ID, WIP_SUPPLY_SUBINVENTORY, WIP_SUPPLY_TYPE, _FIVETRAN_DELETED, _FIVETRAN_ID, _FIVETRAN_SYNCED FROM {{ source('emtk_ebs_inv', 'mtl_system_items_b') }} as SRC  ),
SRC_A              as ( SELECT BKCC, REC_SRC FROM {{ ref('ref_business_key_collision') }} as SRC  ),
SRC_S2             as ( SELECT organization_code, organization_id FROM {{ source('emtk_ebs_inv', 'mtl_parameters') }} as SRC 
                        qualify 1 = row_number()over (partition by organization_id order by psa_load_dts )  )

/*
SRC_S              as ( SELECT * FROM emtk_ebs_inv.mtl_system_items_b )
SRC_A              as ( SELECT * FROM raw_vault.ref_business_key_collision )
SRC_S2             as ( SELECT * FROM emtk_ebs_inv.mtl_parameters )
*/
---- LOGIC LAYER ----

, LOGIC_S as (
    SELECT
        SEGMENT1                                                     as                                            ITEM_BK
      , SEGMENT1
      , INVENTORY_ITEM_ID
      , ORGANIZATION_ID
      , LAST_UPDATE_DATE
      , LAST_UPDATED_BY
      , CREATION_DATE
      , CREATED_BY
      , LAST_UPDATE_LOGIN
      , SUMMARY_FLAG
      , ENABLED_FLAG
      , START_DATE_ACTIVE
      , END_DATE_ACTIVE
      , DESCRIPTION
      , BUYER_ID
      , ACCOUNTING_RULE_ID
      , INVOICING_RULE_ID
      , SEGMENT2
      , SEGMENT3
      , SEGMENT4
      , SEGMENT5
      , SEGMENT6
      , SEGMENT7
      , SEGMENT8
      , SEGMENT9
      , SEGMENT10
      , SEGMENT11
      , SEGMENT12
      , SEGMENT13
      , SEGMENT14
      , SEGMENT15
      , SEGMENT16
      , SEGMENT17
      , SEGMENT18
      , SEGMENT19
      , SEGMENT20
      , ATTRIBUTE_CATEGORY
      , ATTRIBUTE1
      , ATTRIBUTE2
      , ATTRIBUTE3
      , ATTRIBUTE4
      , ATTRIBUTE5
      , ATTRIBUTE6
      , ATTRIBUTE7
      , ATTRIBUTE8
      , ATTRIBUTE9
      , ATTRIBUTE10
      , ATTRIBUTE11
      , ATTRIBUTE12
      , ATTRIBUTE13
      , ATTRIBUTE14
      , ATTRIBUTE15
      , PURCHASING_ITEM_FLAG
      , SHIPPABLE_ITEM_FLAG
      , CUSTOMER_ORDER_FLAG
      , INTERNAL_ORDER_FLAG
      , SERVICE_ITEM_FLAG
      , INVENTORY_ITEM_FLAG
      , ENG_ITEM_FLAG
      , INVENTORY_ASSET_FLAG
      , PURCHASING_ENABLED_FLAG
      , CUSTOMER_ORDER_ENABLED_FLAG
      , INTERNAL_ORDER_ENABLED_FLAG
      , SO_TRANSACTIONS_FLAG
      , MTL_TRANSACTIONS_ENABLED_FLAG
      , STOCK_ENABLED_FLAG
      , BOM_ENABLED_FLAG
      , BUILD_IN_WIP_FLAG
      , REVISION_QTY_CONTROL_CODE
      , ITEM_CATALOG_GROUP_ID
      , CATALOG_STATUS_FLAG
      , RETURNABLE_FLAG
      , DEFAULT_SHIPPING_ORG
      , COLLATERAL_FLAG
      , TAXABLE_FLAG
      , QTY_RCV_EXCEPTION_CODE
      , ALLOW_ITEM_DESC_UPDATE_FLAG
      , INSPECTION_REQUIRED_FLAG
      , RECEIPT_REQUIRED_FLAG
      , MARKET_PRICE
      , HAZARD_CLASS_ID
      , RFQ_REQUIRED_FLAG
      , QTY_RCV_TOLERANCE
      , LIST_PRICE_PER_UNIT
      , UN_NUMBER_ID
      , PRICE_TOLERANCE_PERCENT
      , ASSET_CATEGORY_ID
      , ROUNDING_FACTOR
      , UNIT_OF_ISSUE
      , ENFORCE_SHIP_TO_LOCATION_CODE
      , ALLOW_SUBSTITUTE_RECEIPTS_FLAG
      , ALLOW_UNORDERED_RECEIPTS_FLAG
      , ALLOW_EXPRESS_DELIVERY_FLAG
      , DAYS_EARLY_RECEIPT_ALLOWED
      , DAYS_LATE_RECEIPT_ALLOWED
      , RECEIPT_DAYS_EXCEPTION_CODE
      , RECEIVING_ROUTING_ID
      , INVOICE_CLOSE_TOLERANCE
      , RECEIVE_CLOSE_TOLERANCE
      , AUTO_LOT_ALPHA_PREFIX
      , START_AUTO_LOT_NUMBER
      , LOT_CONTROL_CODE
      , SHELF_LIFE_CODE
      , SHELF_LIFE_DAYS
      , SERIAL_NUMBER_CONTROL_CODE
      , START_AUTO_SERIAL_NUMBER
      , AUTO_SERIAL_ALPHA_PREFIX
      , SOURCE_TYPE
      , SOURCE_ORGANIZATION_ID
      , SOURCE_SUBINVENTORY
      , EXPENSE_ACCOUNT
      , ENCUMBRANCE_ACCOUNT
      , RESTRICT_SUBINVENTORIES_CODE
      , UNIT_WEIGHT
      , WEIGHT_UOM_CODE
      , VOLUME_UOM_CODE
      , UNIT_VOLUME
      , RESTRICT_LOCATORS_CODE
      , LOCATION_CONTROL_CODE
      , SHRINKAGE_RATE
      , ACCEPTABLE_EARLY_DAYS
      , PLANNING_TIME_FENCE_CODE
      , DEMAND_TIME_FENCE_CODE
      , LEAD_TIME_LOT_SIZE
      , STD_LOT_SIZE
      , CUM_MANUFACTURING_LEAD_TIME
      , OVERRUN_PERCENTAGE
      , MRP_CALCULATE_ATP_FLAG
      , ACCEPTABLE_RATE_INCREASE
      , ACCEPTABLE_RATE_DECREASE
      , CUMULATIVE_TOTAL_LEAD_TIME
      , PLANNING_TIME_FENCE_DAYS
      , DEMAND_TIME_FENCE_DAYS
      , END_ASSEMBLY_PEGGING_FLAG
      , REPETITIVE_PLANNING_FLAG
      , PLANNING_EXCEPTION_SET
      , BOM_ITEM_TYPE
      , PICK_COMPONENTS_FLAG
      , REPLENISH_TO_ORDER_FLAG
      , BASE_ITEM_ID
      , ATP_COMPONENTS_FLAG
      , ATP_FLAG
      , FIXED_LEAD_TIME
      , VARIABLE_LEAD_TIME
      , WIP_SUPPLY_LOCATOR_ID
      , WIP_SUPPLY_TYPE
      , WIP_SUPPLY_SUBINVENTORY
      , PRIMARY_UOM_CODE
      , PRIMARY_UNIT_OF_MEASURE
      , ALLOWED_UNITS_LOOKUP_CODE
      , COST_OF_SALES_ACCOUNT
      , SALES_ACCOUNT
      , DEFAULT_INCLUDE_IN_ROLLUP_FLAG
      , INVENTORY_ITEM_STATUS_CODE
      , INVENTORY_PLANNING_CODE
      , PLANNER_CODE
      , PLANNING_MAKE_BUY_CODE
      , FIXED_LOT_MULTIPLIER
      , ROUNDING_CONTROL_TYPE
      , CARRYING_COST
      , POSTPROCESSING_LEAD_TIME
      , PREPROCESSING_LEAD_TIME
      , FULL_LEAD_TIME
      , ORDER_COST
      , MRP_SAFETY_STOCK_PERCENT
      , MRP_SAFETY_STOCK_CODE
      , MIN_MINMAX_QUANTITY
      , MAX_MINMAX_QUANTITY
      , MINIMUM_ORDER_QUANTITY
      , FIXED_ORDER_QUANTITY
      , FIXED_DAYS_SUPPLY
      , MAXIMUM_ORDER_QUANTITY
      , ATP_RULE_ID
      , PICKING_RULE_ID
      , RESERVABLE_TYPE
      , POSITIVE_MEASUREMENT_ERROR
      , NEGATIVE_MEASUREMENT_ERROR
      , ENGINEERING_ECN_CODE
      , ENGINEERING_ITEM_ID
      , ENGINEERING_DATE
      , SERVICE_STARTING_DELAY
      , VENDOR_WARRANTY_FLAG
      , SERVICEABLE_COMPONENT_FLAG
      , SERVICEABLE_PRODUCT_FLAG
      , BASE_WARRANTY_SERVICE_ID
      , PAYMENT_TERMS_ID
      , PREVENTIVE_MAINTENANCE_FLAG
      , PRIMARY_SPECIALIST_ID
      , SECONDARY_SPECIALIST_ID
      , SERVICEABLE_ITEM_CLASS_ID
      , TIME_BILLABLE_FLAG
      , MATERIAL_BILLABLE_FLAG
      , EXPENSE_BILLABLE_FLAG
      , PRORATE_SERVICE_FLAG
      , COVERAGE_SCHEDULE_ID
      , SERVICE_DURATION_PERIOD_CODE
      , SERVICE_DURATION
      , WARRANTY_VENDOR_ID
      , MAX_WARRANTY_AMOUNT
      , RESPONSE_TIME_PERIOD_CODE
      , RESPONSE_TIME_VALUE
      , NEW_REVISION_CODE
      , INVOICEABLE_ITEM_FLAG
      , TAX_CODE
      , INVOICE_ENABLED_FLAG
      , MUST_USE_APPROVED_VENDOR_FLAG
      , REQUEST_ID
      , PROGRAM_APPLICATION_ID
      , PROGRAM_ID
      , PROGRAM_UPDATE_DATE
      , OUTSIDE_OPERATION_FLAG
      , OUTSIDE_OPERATION_UOM_TYPE
      , SAFETY_STOCK_BUCKET_DAYS
      , AUTO_REDUCE_MPS
      , COSTING_ENABLED_FLAG
      , AUTO_CREATED_CONFIG_FLAG
      , CYCLE_COUNT_ENABLED_FLAG
      , ITEM_TYPE
      , MODEL_CONFIG_CLAUSE_NAME
      , SHIP_MODEL_COMPLETE_FLAG
      , MRP_PLANNING_CODE
      , RETURN_INSPECTION_REQUIREMENT
      , ATO_FORECAST_CONTROL
      , RELEASE_TIME_FENCE_CODE
      , RELEASE_TIME_FENCE_DAYS
      , CONTAINER_ITEM_FLAG
      , VEHICLE_ITEM_FLAG
      , MAXIMUM_LOAD_WEIGHT
      , MINIMUM_FILL_PERCENT
      , CONTAINER_TYPE_CODE
      , INTERNAL_VOLUME
      , WH_UPDATE_DATE
      , PRODUCT_FAMILY_ITEM_ID
      , GLOBAL_ATTRIBUTE_CATEGORY
      , GLOBAL_ATTRIBUTE1
      , GLOBAL_ATTRIBUTE2
      , GLOBAL_ATTRIBUTE3
      , GLOBAL_ATTRIBUTE4
      , GLOBAL_ATTRIBUTE5
      , GLOBAL_ATTRIBUTE6
      , GLOBAL_ATTRIBUTE7
      , GLOBAL_ATTRIBUTE8
      , GLOBAL_ATTRIBUTE9
      , GLOBAL_ATTRIBUTE10
      , PURCHASING_TAX_CODE
      , OVERCOMPLETION_TOLERANCE_TYPE
      , OVERCOMPLETION_TOLERANCE_VALUE
      , EFFECTIVITY_CONTROL
      , CHECK_SHORTAGES_FLAG
      , OVER_SHIPMENT_TOLERANCE
      , UNDER_SHIPMENT_TOLERANCE
      , OVER_RETURN_TOLERANCE
      , UNDER_RETURN_TOLERANCE
      , EQUIPMENT_TYPE
      , RECOVERED_PART_DISP_CODE
      , DEFECT_TRACKING_ON_FLAG
      , USAGE_ITEM_FLAG
      , EVENT_FLAG
      , ELECTRONIC_FLAG
      , DOWNLOADABLE_FLAG
      , VOL_DISCOUNT_EXEMPT_FLAG
      , COUPON_EXEMPT_FLAG
      , COMMS_NL_TRACKABLE_FLAG
      , ASSET_CREATION_CODE
      , COMMS_ACTIVATION_REQD_FLAG
      , ORDERABLE_ON_WEB_FLAG
      , BACK_ORDERABLE_FLAG
      , WEB_STATUS
      , INDIVISIBLE_FLAG
      , DIMENSION_UOM_CODE
      , UNIT_LENGTH
      , UNIT_WIDTH
      , UNIT_HEIGHT
      , BULK_PICKED_FLAG
      , LOT_STATUS_ENABLED
      , DEFAULT_LOT_STATUS_ID
      , SERIAL_STATUS_ENABLED
      , DEFAULT_SERIAL_STATUS_ID
      , LOT_SPLIT_ENABLED
      , LOT_MERGE_ENABLED
      , INVENTORY_CARRY_PENALTY
      , OPERATION_SLACK_PENALTY
      , FINANCING_ALLOWED_FLAG
      , EAM_ITEM_TYPE
      , EAM_ACTIVITY_TYPE_CODE
      , EAM_ACTIVITY_CAUSE_CODE
      , EAM_ACT_NOTIFICATION_FLAG
      , EAM_ACT_SHUTDOWN_STATUS
      , DUAL_UOM_CONTROL
      , SECONDARY_UOM_CODE
      , DUAL_UOM_DEVIATION_HIGH
      , DUAL_UOM_DEVIATION_LOW
      , CONTRACT_ITEM_TYPE_CODE
      , SUBSCRIPTION_DEPEND_FLAG
      , SERV_REQ_ENABLED_CODE
      , SERV_BILLING_ENABLED_FLAG
      , SERV_IMPORTANCE_LEVEL
      , PLANNED_INV_POINT_FLAG
      , LOT_TRANSLATE_ENABLED
      , DEFAULT_SO_SOURCE_TYPE
      , CREATE_SUPPLY_FLAG
      , SUBSTITUTION_WINDOW_CODE
      , SUBSTITUTION_WINDOW_DAYS
      , IB_ITEM_INSTANCE_CLASS
      , CONFIG_MODEL_TYPE
      , LOT_SUBSTITUTION_ENABLED
      , MINIMUM_LICENSE_QUANTITY
      , EAM_ACTIVITY_SOURCE_CODE
      , LIFECYCLE_ID
      , CURRENT_PHASE_ID
      , OBJECT_VERSION_NUMBER
      , TRACKING_QUANTITY_IND
      , ONT_PRICING_QTY_SOURCE
      , SECONDARY_DEFAULT_IND
      , OPTION_SPECIFIC_SOURCED
      , APPROVAL_STATUS
      , VMI_MINIMUM_UNITS
      , VMI_MINIMUM_DAYS
      , VMI_MAXIMUM_UNITS
      , VMI_MAXIMUM_DAYS
      , VMI_FIXED_ORDER_QUANTITY
      , SO_AUTHORIZATION_FLAG
      , CONSIGNED_FLAG
      , ASN_AUTOEXPIRE_FLAG
      , VMI_FORECAST_TYPE
      , FORECAST_HORIZON
      , EXCLUDE_FROM_BUDGET_FLAG
      , DAYS_TGT_INV_SUPPLY
      , DAYS_TGT_INV_WINDOW
      , DAYS_MAX_INV_SUPPLY
      , DAYS_MAX_INV_WINDOW
      , DRP_PLANNED_FLAG
      , CRITICAL_COMPONENT_FLAG
      , CONTINOUS_TRANSFER
      , CONVERGENCE
      , DIVERGENCE
      , CONFIG_ORGS
      , CONFIG_MATCH
      , GLOBAL_ATTRIBUTE11
      , GLOBAL_ATTRIBUTE12
      , GLOBAL_ATTRIBUTE13
      , GLOBAL_ATTRIBUTE14
      , GLOBAL_ATTRIBUTE15
      , GLOBAL_ATTRIBUTE16
      , GLOBAL_ATTRIBUTE17
      , GLOBAL_ATTRIBUTE18
      , GLOBAL_ATTRIBUTE19
      , GLOBAL_ATTRIBUTE20
      , ATTRIBUTE16
      , ATTRIBUTE17
      , ATTRIBUTE18
      , ATTRIBUTE19
      , ATTRIBUTE20
      , ATTRIBUTE21
      , ATTRIBUTE22
      , ATTRIBUTE23
      , ATTRIBUTE24
      , ATTRIBUTE25
      , ATTRIBUTE26
      , ATTRIBUTE27
      , ATTRIBUTE28
      , ATTRIBUTE29
      , ATTRIBUTE30
      , CAS_NUMBER
      , CHILD_LOT_FLAG
      , CHILD_LOT_PREFIX
      , CHILD_LOT_STARTING_NUMBER
      , CHILD_LOT_VALIDATION_FLAG
      , COPY_LOT_ATTRIBUTE_FLAG
      , DEFAULT_GRADE
      , EXPIRATION_ACTION_CODE
      , EXPIRATION_ACTION_INTERVAL
      , GRADE_CONTROL_FLAG
      , HAZARDOUS_MATERIAL_FLAG
      , HOLD_DAYS
      , LOT_DIVISIBLE_FLAG
      , MATURITY_DAYS
      , PARENT_CHILD_GENERATION_FLAG
      , PROCESS_COSTING_ENABLED_FLAG
      , PROCESS_EXECUTION_ENABLED_FLAG
      , PROCESS_QUALITY_ENABLED_FLAG
      , PROCESS_SUPPLY_LOCATOR_ID
      , PROCESS_SUPPLY_SUBINVENTORY
      , PROCESS_YIELD_LOCATOR_ID
      , PROCESS_YIELD_SUBINVENTORY
      , RECIPE_ENABLED_FLAG
      , RETEST_INTERVAL
      , CHARGE_PERIODICITY_CODE
      , REPAIR_LEADTIME
      , REPAIR_YIELD
      , PREPOSITION_POINT
      , REPAIR_PROGRAM
      , SUBCONTRACTING_COMPONENT
      , OUTSOURCED_ASSEMBLY
      , EGO_MASTER_ITEMS_DFF_CTX
      , GDSN_OUTBOUND_ENABLED_FLAG
      , TRADE_ITEM_DESCRIPTOR
      , STYLE_ITEM_ID
      , STYLE_ITEM_FLAG
      , LAST_SUBMITTED_NIR_ID
      , DEFAULT_MATERIAL_STATUS_ID
      , SERIAL_TAGGING_FLAG
      , IB_ITEM_TRACKING_LEVEL
      , MCC_CLASSIFICATION_TYPE
      , MCC_CONTROL_CODE
      , MCC_TRACKING_CODE
      , GLOBAL_ATTRIBUTE21
      , GLOBAL_ATTRIBUTE22
      , GLOBAL_ATTRIBUTE23
      , GLOBAL_ATTRIBUTE24
      , GLOBAL_ATTRIBUTE25
      , GLOBAL_ATTRIBUTE26
      , GLOBAL_ATTRIBUTE27
      , GLOBAL_ATTRIBUTE28
      , GLOBAL_ATTRIBUTE29
      , GLOBAL_ATTRIBUTE30
      , GLOBAL_ATTRIBUTE31
      , GLOBAL_ATTRIBUTE32
      , GLOBAL_ATTRIBUTE33
      , GLOBAL_ATTRIBUTE34
      , GLOBAL_ATTRIBUTE35
      , GLOBAL_ATTRIBUTE36
      , GLOBAL_ATTRIBUTE37
      , GLOBAL_ATTRIBUTE38
      , GLOBAL_ATTRIBUTE39
      , GLOBAL_ATTRIBUTE40
      , _FIVETRAN_DELETED
      , _FIVETRAN_ID
      , _FIVETRAN_SYNCED
      , PSA_DELETE_IND
      , PSA_LOAD_DTS
      , PSA_RECORD_SOURCE
      , CONVERT_TIMEZONE('UTC', _FIVETRAN_SYNCED )                   as                                           LOAD_DTS
    FROM SRC_S
)

, LOGIC_A as (
    SELECT
        REC_SRC
      , BKCC
    FROM SRC_A
)

, LOGIC_S2 as (
    SELECT
        organization_code                                            as                                           PLANT_BK
      , organization_id                                              as                                 S2_organization_id
    FROM SRC_S2
)
---- RENAME LAYER ----

, RENAME_S as (
    SELECT
        ITEM_BK
      , SEGMENT1
      , INVENTORY_ITEM_ID
      , ORGANIZATION_ID
      , LAST_UPDATE_DATE
      , LAST_UPDATED_BY
      , CREATION_DATE
      , CREATED_BY
      , LAST_UPDATE_LOGIN
      , SUMMARY_FLAG
      , ENABLED_FLAG
      , START_DATE_ACTIVE
      , END_DATE_ACTIVE
      , DESCRIPTION
      , BUYER_ID
      , ACCOUNTING_RULE_ID
      , INVOICING_RULE_ID
      , SEGMENT2
      , SEGMENT3
      , SEGMENT4
      , SEGMENT5
      , SEGMENT6
      , SEGMENT7
      , SEGMENT8
      , SEGMENT9
      , SEGMENT10
      , SEGMENT11
      , SEGMENT12
      , SEGMENT13
      , SEGMENT14
      , SEGMENT15
      , SEGMENT16
      , SEGMENT17
      , SEGMENT18
      , SEGMENT19
      , SEGMENT20
      , ATTRIBUTE_CATEGORY
      , ATTRIBUTE1
      , ATTRIBUTE2
      , ATTRIBUTE3
      , ATTRIBUTE4
      , ATTRIBUTE5
      , ATTRIBUTE6
      , ATTRIBUTE7
      , ATTRIBUTE8
      , ATTRIBUTE9
      , ATTRIBUTE10
      , ATTRIBUTE11
      , ATTRIBUTE12
      , ATTRIBUTE13
      , ATTRIBUTE14
      , ATTRIBUTE15
      , PURCHASING_ITEM_FLAG
      , SHIPPABLE_ITEM_FLAG
      , CUSTOMER_ORDER_FLAG
      , INTERNAL_ORDER_FLAG
      , SERVICE_ITEM_FLAG
      , INVENTORY_ITEM_FLAG
      , ENG_ITEM_FLAG
      , INVENTORY_ASSET_FLAG
      , PURCHASING_ENABLED_FLAG
      , CUSTOMER_ORDER_ENABLED_FLAG
      , INTERNAL_ORDER_ENABLED_FLAG
      , SO_TRANSACTIONS_FLAG
      , MTL_TRANSACTIONS_ENABLED_FLAG
      , STOCK_ENABLED_FLAG
      , BOM_ENABLED_FLAG
      , BUILD_IN_WIP_FLAG
      , REVISION_QTY_CONTROL_CODE
      , ITEM_CATALOG_GROUP_ID
      , CATALOG_STATUS_FLAG
      , RETURNABLE_FLAG
      , DEFAULT_SHIPPING_ORG
      , COLLATERAL_FLAG
      , TAXABLE_FLAG
      , QTY_RCV_EXCEPTION_CODE
      , ALLOW_ITEM_DESC_UPDATE_FLAG
      , INSPECTION_REQUIRED_FLAG
      , RECEIPT_REQUIRED_FLAG
      , MARKET_PRICE
      , HAZARD_CLASS_ID
      , RFQ_REQUIRED_FLAG
      , QTY_RCV_TOLERANCE
      , LIST_PRICE_PER_UNIT
      , UN_NUMBER_ID
      , PRICE_TOLERANCE_PERCENT
      , ASSET_CATEGORY_ID
      , ROUNDING_FACTOR
      , UNIT_OF_ISSUE
      , ENFORCE_SHIP_TO_LOCATION_CODE
      , ALLOW_SUBSTITUTE_RECEIPTS_FLAG
      , ALLOW_UNORDERED_RECEIPTS_FLAG
      , ALLOW_EXPRESS_DELIVERY_FLAG
      , DAYS_EARLY_RECEIPT_ALLOWED
      , DAYS_LATE_RECEIPT_ALLOWED
      , RECEIPT_DAYS_EXCEPTION_CODE
      , RECEIVING_ROUTING_ID
      , INVOICE_CLOSE_TOLERANCE
      , RECEIVE_CLOSE_TOLERANCE
      , AUTO_LOT_ALPHA_PREFIX
      , START_AUTO_LOT_NUMBER
      , LOT_CONTROL_CODE
      , SHELF_LIFE_CODE
      , SHELF_LIFE_DAYS
      , SERIAL_NUMBER_CONTROL_CODE
      , START_AUTO_SERIAL_NUMBER
      , AUTO_SERIAL_ALPHA_PREFIX
      , SOURCE_TYPE
      , SOURCE_ORGANIZATION_ID
      , SOURCE_SUBINVENTORY
      , EXPENSE_ACCOUNT
      , ENCUMBRANCE_ACCOUNT
      , RESTRICT_SUBINVENTORIES_CODE
      , UNIT_WEIGHT
      , WEIGHT_UOM_CODE
      , VOLUME_UOM_CODE
      , UNIT_VOLUME
      , RESTRICT_LOCATORS_CODE
      , LOCATION_CONTROL_CODE
      , SHRINKAGE_RATE
      , ACCEPTABLE_EARLY_DAYS
      , PLANNING_TIME_FENCE_CODE
      , DEMAND_TIME_FENCE_CODE
      , LEAD_TIME_LOT_SIZE
      , STD_LOT_SIZE
      , CUM_MANUFACTURING_LEAD_TIME
      , OVERRUN_PERCENTAGE
      , MRP_CALCULATE_ATP_FLAG
      , ACCEPTABLE_RATE_INCREASE
      , ACCEPTABLE_RATE_DECREASE
      , CUMULATIVE_TOTAL_LEAD_TIME
      , PLANNING_TIME_FENCE_DAYS
      , DEMAND_TIME_FENCE_DAYS
      , END_ASSEMBLY_PEGGING_FLAG
      , REPETITIVE_PLANNING_FLAG
      , PLANNING_EXCEPTION_SET
      , BOM_ITEM_TYPE
      , PICK_COMPONENTS_FLAG
      , REPLENISH_TO_ORDER_FLAG
      , BASE_ITEM_ID
      , ATP_COMPONENTS_FLAG
      , ATP_FLAG
      , FIXED_LEAD_TIME
      , VARIABLE_LEAD_TIME
      , WIP_SUPPLY_LOCATOR_ID
      , WIP_SUPPLY_TYPE
      , WIP_SUPPLY_SUBINVENTORY
      , PRIMARY_UOM_CODE
      , PRIMARY_UNIT_OF_MEASURE
      , ALLOWED_UNITS_LOOKUP_CODE
      , COST_OF_SALES_ACCOUNT
      , SALES_ACCOUNT
      , DEFAULT_INCLUDE_IN_ROLLUP_FLAG
      , INVENTORY_ITEM_STATUS_CODE
      , INVENTORY_PLANNING_CODE
      , PLANNER_CODE
      , PLANNING_MAKE_BUY_CODE
      , FIXED_LOT_MULTIPLIER
      , ROUNDING_CONTROL_TYPE
      , CARRYING_COST
      , POSTPROCESSING_LEAD_TIME
      , PREPROCESSING_LEAD_TIME
      , FULL_LEAD_TIME
      , ORDER_COST
      , MRP_SAFETY_STOCK_PERCENT
      , MRP_SAFETY_STOCK_CODE
      , MIN_MINMAX_QUANTITY
      , MAX_MINMAX_QUANTITY
      , MINIMUM_ORDER_QUANTITY
      , FIXED_ORDER_QUANTITY
      , FIXED_DAYS_SUPPLY
      , MAXIMUM_ORDER_QUANTITY
      , ATP_RULE_ID
      , PICKING_RULE_ID
      , RESERVABLE_TYPE
      , POSITIVE_MEASUREMENT_ERROR
      , NEGATIVE_MEASUREMENT_ERROR
      , ENGINEERING_ECN_CODE
      , ENGINEERING_ITEM_ID
      , ENGINEERING_DATE
      , SERVICE_STARTING_DELAY
      , VENDOR_WARRANTY_FLAG
      , SERVICEABLE_COMPONENT_FLAG
      , SERVICEABLE_PRODUCT_FLAG
      , BASE_WARRANTY_SERVICE_ID
      , PAYMENT_TERMS_ID
      , PREVENTIVE_MAINTENANCE_FLAG
      , PRIMARY_SPECIALIST_ID
      , SECONDARY_SPECIALIST_ID
      , SERVICEABLE_ITEM_CLASS_ID
      , TIME_BILLABLE_FLAG
      , MATERIAL_BILLABLE_FLAG
      , EXPENSE_BILLABLE_FLAG
      , PRORATE_SERVICE_FLAG
      , COVERAGE_SCHEDULE_ID
      , SERVICE_DURATION_PERIOD_CODE
      , SERVICE_DURATION
      , WARRANTY_VENDOR_ID
      , MAX_WARRANTY_AMOUNT
      , RESPONSE_TIME_PERIOD_CODE
      , RESPONSE_TIME_VALUE
      , NEW_REVISION_CODE
      , INVOICEABLE_ITEM_FLAG
      , TAX_CODE
      , INVOICE_ENABLED_FLAG
      , MUST_USE_APPROVED_VENDOR_FLAG
      , REQUEST_ID
      , PROGRAM_APPLICATION_ID
      , PROGRAM_ID
      , PROGRAM_UPDATE_DATE
      , OUTSIDE_OPERATION_FLAG
      , OUTSIDE_OPERATION_UOM_TYPE
      , SAFETY_STOCK_BUCKET_DAYS
      , AUTO_REDUCE_MPS
      , COSTING_ENABLED_FLAG
      , AUTO_CREATED_CONFIG_FLAG
      , CYCLE_COUNT_ENABLED_FLAG
      , ITEM_TYPE
      , MODEL_CONFIG_CLAUSE_NAME
      , SHIP_MODEL_COMPLETE_FLAG
      , MRP_PLANNING_CODE
      , RETURN_INSPECTION_REQUIREMENT
      , ATO_FORECAST_CONTROL
      , RELEASE_TIME_FENCE_CODE
      , RELEASE_TIME_FENCE_DAYS
      , CONTAINER_ITEM_FLAG
      , VEHICLE_ITEM_FLAG
      , MAXIMUM_LOAD_WEIGHT
      , MINIMUM_FILL_PERCENT
      , CONTAINER_TYPE_CODE
      , INTERNAL_VOLUME
      , WH_UPDATE_DATE
      , PRODUCT_FAMILY_ITEM_ID
      , GLOBAL_ATTRIBUTE_CATEGORY
      , GLOBAL_ATTRIBUTE1
      , GLOBAL_ATTRIBUTE2
      , GLOBAL_ATTRIBUTE3
      , GLOBAL_ATTRIBUTE4
      , GLOBAL_ATTRIBUTE5
      , GLOBAL_ATTRIBUTE6
      , GLOBAL_ATTRIBUTE7
      , GLOBAL_ATTRIBUTE8
      , GLOBAL_ATTRIBUTE9
      , GLOBAL_ATTRIBUTE10
      , PURCHASING_TAX_CODE
      , OVERCOMPLETION_TOLERANCE_TYPE
      , OVERCOMPLETION_TOLERANCE_VALUE
      , EFFECTIVITY_CONTROL
      , CHECK_SHORTAGES_FLAG
      , OVER_SHIPMENT_TOLERANCE
      , UNDER_SHIPMENT_TOLERANCE
      , OVER_RETURN_TOLERANCE
      , UNDER_RETURN_TOLERANCE
      , EQUIPMENT_TYPE
      , RECOVERED_PART_DISP_CODE
      , DEFECT_TRACKING_ON_FLAG
      , USAGE_ITEM_FLAG
      , EVENT_FLAG
      , ELECTRONIC_FLAG
      , DOWNLOADABLE_FLAG
      , VOL_DISCOUNT_EXEMPT_FLAG
      , COUPON_EXEMPT_FLAG
      , COMMS_NL_TRACKABLE_FLAG
      , ASSET_CREATION_CODE
      , COMMS_ACTIVATION_REQD_FLAG
      , ORDERABLE_ON_WEB_FLAG
      , BACK_ORDERABLE_FLAG
      , WEB_STATUS
      , INDIVISIBLE_FLAG
      , DIMENSION_UOM_CODE
      , UNIT_LENGTH
      , UNIT_WIDTH
      , UNIT_HEIGHT
      , BULK_PICKED_FLAG
      , LOT_STATUS_ENABLED
      , DEFAULT_LOT_STATUS_ID
      , SERIAL_STATUS_ENABLED
      , DEFAULT_SERIAL_STATUS_ID
      , LOT_SPLIT_ENABLED
      , LOT_MERGE_ENABLED
      , INVENTORY_CARRY_PENALTY
      , OPERATION_SLACK_PENALTY
      , FINANCING_ALLOWED_FLAG
      , EAM_ITEM_TYPE
      , EAM_ACTIVITY_TYPE_CODE
      , EAM_ACTIVITY_CAUSE_CODE
      , EAM_ACT_NOTIFICATION_FLAG
      , EAM_ACT_SHUTDOWN_STATUS
      , DUAL_UOM_CONTROL
      , SECONDARY_UOM_CODE
      , DUAL_UOM_DEVIATION_HIGH
      , DUAL_UOM_DEVIATION_LOW
      , CONTRACT_ITEM_TYPE_CODE
      , SUBSCRIPTION_DEPEND_FLAG
      , SERV_REQ_ENABLED_CODE
      , SERV_BILLING_ENABLED_FLAG
      , SERV_IMPORTANCE_LEVEL
      , PLANNED_INV_POINT_FLAG
      , LOT_TRANSLATE_ENABLED
      , DEFAULT_SO_SOURCE_TYPE
      , CREATE_SUPPLY_FLAG
      , SUBSTITUTION_WINDOW_CODE
      , SUBSTITUTION_WINDOW_DAYS
      , IB_ITEM_INSTANCE_CLASS
      , CONFIG_MODEL_TYPE
      , LOT_SUBSTITUTION_ENABLED
      , MINIMUM_LICENSE_QUANTITY
      , EAM_ACTIVITY_SOURCE_CODE
      , LIFECYCLE_ID
      , CURRENT_PHASE_ID
      , OBJECT_VERSION_NUMBER
      , TRACKING_QUANTITY_IND
      , ONT_PRICING_QTY_SOURCE
      , SECONDARY_DEFAULT_IND
      , OPTION_SPECIFIC_SOURCED
      , APPROVAL_STATUS
      , VMI_MINIMUM_UNITS
      , VMI_MINIMUM_DAYS
      , VMI_MAXIMUM_UNITS
      , VMI_MAXIMUM_DAYS
      , VMI_FIXED_ORDER_QUANTITY
      , SO_AUTHORIZATION_FLAG
      , CONSIGNED_FLAG
      , ASN_AUTOEXPIRE_FLAG
      , VMI_FORECAST_TYPE
      , FORECAST_HORIZON
      , EXCLUDE_FROM_BUDGET_FLAG
      , DAYS_TGT_INV_SUPPLY
      , DAYS_TGT_INV_WINDOW
      , DAYS_MAX_INV_SUPPLY
      , DAYS_MAX_INV_WINDOW
      , DRP_PLANNED_FLAG
      , CRITICAL_COMPONENT_FLAG
      , CONTINOUS_TRANSFER
      , CONVERGENCE
      , DIVERGENCE
      , CONFIG_ORGS
      , CONFIG_MATCH
      , GLOBAL_ATTRIBUTE11
      , GLOBAL_ATTRIBUTE12
      , GLOBAL_ATTRIBUTE13
      , GLOBAL_ATTRIBUTE14
      , GLOBAL_ATTRIBUTE15
      , GLOBAL_ATTRIBUTE16
      , GLOBAL_ATTRIBUTE17
      , GLOBAL_ATTRIBUTE18
      , GLOBAL_ATTRIBUTE19
      , GLOBAL_ATTRIBUTE20
      , ATTRIBUTE16
      , ATTRIBUTE17
      , ATTRIBUTE18
      , ATTRIBUTE19
      , ATTRIBUTE20
      , ATTRIBUTE21
      , ATTRIBUTE22
      , ATTRIBUTE23
      , ATTRIBUTE24
      , ATTRIBUTE25
      , ATTRIBUTE26
      , ATTRIBUTE27
      , ATTRIBUTE28
      , ATTRIBUTE29
      , ATTRIBUTE30
      , CAS_NUMBER
      , CHILD_LOT_FLAG
      , CHILD_LOT_PREFIX
      , CHILD_LOT_STARTING_NUMBER
      , CHILD_LOT_VALIDATION_FLAG
      , COPY_LOT_ATTRIBUTE_FLAG
      , DEFAULT_GRADE
      , EXPIRATION_ACTION_CODE
      , EXPIRATION_ACTION_INTERVAL
      , GRADE_CONTROL_FLAG
      , HAZARDOUS_MATERIAL_FLAG
      , HOLD_DAYS
      , LOT_DIVISIBLE_FLAG
      , MATURITY_DAYS
      , PARENT_CHILD_GENERATION_FLAG
      , PROCESS_COSTING_ENABLED_FLAG
      , PROCESS_EXECUTION_ENABLED_FLAG
      , PROCESS_QUALITY_ENABLED_FLAG
      , PROCESS_SUPPLY_LOCATOR_ID
      , PROCESS_SUPPLY_SUBINVENTORY
      , PROCESS_YIELD_LOCATOR_ID
      , PROCESS_YIELD_SUBINVENTORY
      , RECIPE_ENABLED_FLAG
      , RETEST_INTERVAL
      , CHARGE_PERIODICITY_CODE
      , REPAIR_LEADTIME
      , REPAIR_YIELD
      , PREPOSITION_POINT
      , REPAIR_PROGRAM
      , SUBCONTRACTING_COMPONENT
      , OUTSOURCED_ASSEMBLY
      , EGO_MASTER_ITEMS_DFF_CTX
      , GDSN_OUTBOUND_ENABLED_FLAG
      , TRADE_ITEM_DESCRIPTOR
      , STYLE_ITEM_ID
      , STYLE_ITEM_FLAG
      , LAST_SUBMITTED_NIR_ID
      , DEFAULT_MATERIAL_STATUS_ID
      , SERIAL_TAGGING_FLAG
      , IB_ITEM_TRACKING_LEVEL
      , MCC_CLASSIFICATION_TYPE
      , MCC_CONTROL_CODE
      , MCC_TRACKING_CODE
      , GLOBAL_ATTRIBUTE21
      , GLOBAL_ATTRIBUTE22
      , GLOBAL_ATTRIBUTE23
      , GLOBAL_ATTRIBUTE24
      , GLOBAL_ATTRIBUTE25
      , GLOBAL_ATTRIBUTE26
      , GLOBAL_ATTRIBUTE27
      , GLOBAL_ATTRIBUTE28
      , GLOBAL_ATTRIBUTE29
      , GLOBAL_ATTRIBUTE30
      , GLOBAL_ATTRIBUTE31
      , GLOBAL_ATTRIBUTE32
      , GLOBAL_ATTRIBUTE33
      , GLOBAL_ATTRIBUTE34
      , GLOBAL_ATTRIBUTE35
      , GLOBAL_ATTRIBUTE36
      , GLOBAL_ATTRIBUTE37
      , GLOBAL_ATTRIBUTE38
      , GLOBAL_ATTRIBUTE39
      , GLOBAL_ATTRIBUTE40
      , _FIVETRAN_DELETED
      , _FIVETRAN_ID
      , _FIVETRAN_SYNCED
      , PSA_DELETE_IND
      , PSA_LOAD_DTS
      , PSA_RECORD_SOURCE
      , LOAD_DTS
    FROM LOGIC_S
)

, RENAME_A as (
    SELECT
        REC_SRC
      , BKCC
    FROM LOGIC_A
)

, RENAME_S2 as (
    SELECT
        PLANT_BK
      , S2_organization_id
    FROM LOGIC_S2
)
---- FILTER LAYER ----

, FILTER_S as (
    SELECT *
    FROM RENAME_S
)

, FILTER_A as (
    SELECT *
    FROM RENAME_A
    WHERE rec_src = 'USWIOC.ORCL.EBSEMTK.SYSTEM_ITEM'
)

, FILTER_S2 as (
    SELECT *
    FROM RENAME_S2
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM FILTER_S
    INNER JOIN FILTER_A
        ON '1' = '1'
    LEFT JOIN FILTER_S2
        ON organization_id = S2_organization_id
)

---- FINAL LAYER ----
SELECT
          ITEM_BK
        , SEGMENT1
        , INVENTORY_ITEM_ID
        , ORGANIZATION_ID
        , LAST_UPDATE_DATE
        , LAST_UPDATED_BY
        , CREATION_DATE
        , CREATED_BY
        , LAST_UPDATE_LOGIN
        , SUMMARY_FLAG
        , ENABLED_FLAG
        , START_DATE_ACTIVE
        , END_DATE_ACTIVE
        , DESCRIPTION
        , BUYER_ID
        , ACCOUNTING_RULE_ID
        , INVOICING_RULE_ID
        , SEGMENT2
        , SEGMENT3
        , SEGMENT4
        , SEGMENT5
        , SEGMENT6
        , SEGMENT7
        , SEGMENT8
        , SEGMENT9
        , SEGMENT10
        , SEGMENT11
        , SEGMENT12
        , SEGMENT13
        , SEGMENT14
        , SEGMENT15
        , SEGMENT16
        , SEGMENT17
        , SEGMENT18
        , SEGMENT19
        , SEGMENT20
        , ATTRIBUTE_CATEGORY
        , ATTRIBUTE1
        , ATTRIBUTE2
        , ATTRIBUTE3
        , ATTRIBUTE4
        , ATTRIBUTE5
        , ATTRIBUTE6
        , ATTRIBUTE7
        , ATTRIBUTE8
        , ATTRIBUTE9
        , ATTRIBUTE10
        , ATTRIBUTE11
        , ATTRIBUTE12
        , ATTRIBUTE13
        , ATTRIBUTE14
        , ATTRIBUTE15
        , PURCHASING_ITEM_FLAG
        , SHIPPABLE_ITEM_FLAG
        , CUSTOMER_ORDER_FLAG
        , INTERNAL_ORDER_FLAG
        , SERVICE_ITEM_FLAG
        , INVENTORY_ITEM_FLAG
        , ENG_ITEM_FLAG
        , INVENTORY_ASSET_FLAG
        , PURCHASING_ENABLED_FLAG
        , CUSTOMER_ORDER_ENABLED_FLAG
        , INTERNAL_ORDER_ENABLED_FLAG
        , SO_TRANSACTIONS_FLAG
        , MTL_TRANSACTIONS_ENABLED_FLAG
        , STOCK_ENABLED_FLAG
        , BOM_ENABLED_FLAG
        , BUILD_IN_WIP_FLAG
        , REVISION_QTY_CONTROL_CODE
        , ITEM_CATALOG_GROUP_ID
        , CATALOG_STATUS_FLAG
        , RETURNABLE_FLAG
        , DEFAULT_SHIPPING_ORG
        , COLLATERAL_FLAG
        , TAXABLE_FLAG
        , QTY_RCV_EXCEPTION_CODE
        , ALLOW_ITEM_DESC_UPDATE_FLAG
        , INSPECTION_REQUIRED_FLAG
        , RECEIPT_REQUIRED_FLAG
        , MARKET_PRICE
        , HAZARD_CLASS_ID
        , RFQ_REQUIRED_FLAG
        , QTY_RCV_TOLERANCE
        , LIST_PRICE_PER_UNIT
        , UN_NUMBER_ID
        , PRICE_TOLERANCE_PERCENT
        , ASSET_CATEGORY_ID
        , ROUNDING_FACTOR
        , UNIT_OF_ISSUE
        , ENFORCE_SHIP_TO_LOCATION_CODE
        , ALLOW_SUBSTITUTE_RECEIPTS_FLAG
        , ALLOW_UNORDERED_RECEIPTS_FLAG
        , ALLOW_EXPRESS_DELIVERY_FLAG
        , DAYS_EARLY_RECEIPT_ALLOWED
        , DAYS_LATE_RECEIPT_ALLOWED
        , RECEIPT_DAYS_EXCEPTION_CODE
        , RECEIVING_ROUTING_ID
        , INVOICE_CLOSE_TOLERANCE
        , RECEIVE_CLOSE_TOLERANCE
        , AUTO_LOT_ALPHA_PREFIX
        , START_AUTO_LOT_NUMBER
        , LOT_CONTROL_CODE
        , SHELF_LIFE_CODE
        , SHELF_LIFE_DAYS
        , SERIAL_NUMBER_CONTROL_CODE
        , START_AUTO_SERIAL_NUMBER
        , AUTO_SERIAL_ALPHA_PREFIX
        , SOURCE_TYPE
        , SOURCE_ORGANIZATION_ID
        , SOURCE_SUBINVENTORY
        , EXPENSE_ACCOUNT
        , ENCUMBRANCE_ACCOUNT
        , RESTRICT_SUBINVENTORIES_CODE
        , UNIT_WEIGHT
        , WEIGHT_UOM_CODE
        , VOLUME_UOM_CODE
        , UNIT_VOLUME
        , RESTRICT_LOCATORS_CODE
        , LOCATION_CONTROL_CODE
        , SHRINKAGE_RATE
        , ACCEPTABLE_EARLY_DAYS
        , PLANNING_TIME_FENCE_CODE
        , DEMAND_TIME_FENCE_CODE
        , LEAD_TIME_LOT_SIZE
        , STD_LOT_SIZE
        , CUM_MANUFACTURING_LEAD_TIME
        , OVERRUN_PERCENTAGE
        , MRP_CALCULATE_ATP_FLAG
        , ACCEPTABLE_RATE_INCREASE
        , ACCEPTABLE_RATE_DECREASE
        , CUMULATIVE_TOTAL_LEAD_TIME
        , PLANNING_TIME_FENCE_DAYS
        , DEMAND_TIME_FENCE_DAYS
        , END_ASSEMBLY_PEGGING_FLAG
        , REPETITIVE_PLANNING_FLAG
        , PLANNING_EXCEPTION_SET
        , BOM_ITEM_TYPE
        , PICK_COMPONENTS_FLAG
        , REPLENISH_TO_ORDER_FLAG
        , BASE_ITEM_ID
        , ATP_COMPONENTS_FLAG
        , ATP_FLAG
        , FIXED_LEAD_TIME
        , VARIABLE_LEAD_TIME
        , WIP_SUPPLY_LOCATOR_ID
        , WIP_SUPPLY_TYPE
        , WIP_SUPPLY_SUBINVENTORY
        , PRIMARY_UOM_CODE
        , PRIMARY_UNIT_OF_MEASURE
        , ALLOWED_UNITS_LOOKUP_CODE
        , COST_OF_SALES_ACCOUNT
        , SALES_ACCOUNT
        , DEFAULT_INCLUDE_IN_ROLLUP_FLAG
        , INVENTORY_ITEM_STATUS_CODE
        , INVENTORY_PLANNING_CODE
        , PLANNER_CODE
        , PLANNING_MAKE_BUY_CODE
        , FIXED_LOT_MULTIPLIER
        , ROUNDING_CONTROL_TYPE
        , CARRYING_COST
        , POSTPROCESSING_LEAD_TIME
        , PREPROCESSING_LEAD_TIME
        , FULL_LEAD_TIME
        , ORDER_COST
        , MRP_SAFETY_STOCK_PERCENT
        , MRP_SAFETY_STOCK_CODE
        , MIN_MINMAX_QUANTITY
        , MAX_MINMAX_QUANTITY
        , MINIMUM_ORDER_QUANTITY
        , FIXED_ORDER_QUANTITY
        , FIXED_DAYS_SUPPLY
        , MAXIMUM_ORDER_QUANTITY
        , ATP_RULE_ID
        , PICKING_RULE_ID
        , RESERVABLE_TYPE
        , POSITIVE_MEASUREMENT_ERROR
        , NEGATIVE_MEASUREMENT_ERROR
        , ENGINEERING_ECN_CODE
        , ENGINEERING_ITEM_ID
        , ENGINEERING_DATE
        , SERVICE_STARTING_DELAY
        , VENDOR_WARRANTY_FLAG
        , SERVICEABLE_COMPONENT_FLAG
        , SERVICEABLE_PRODUCT_FLAG
        , BASE_WARRANTY_SERVICE_ID
        , PAYMENT_TERMS_ID
        , PREVENTIVE_MAINTENANCE_FLAG
        , PRIMARY_SPECIALIST_ID
        , SECONDARY_SPECIALIST_ID
        , SERVICEABLE_ITEM_CLASS_ID
        , TIME_BILLABLE_FLAG
        , MATERIAL_BILLABLE_FLAG
        , EXPENSE_BILLABLE_FLAG
        , PRORATE_SERVICE_FLAG
        , COVERAGE_SCHEDULE_ID
        , SERVICE_DURATION_PERIOD_CODE
        , SERVICE_DURATION
        , WARRANTY_VENDOR_ID
        , MAX_WARRANTY_AMOUNT
        , RESPONSE_TIME_PERIOD_CODE
        , RESPONSE_TIME_VALUE
        , NEW_REVISION_CODE
        , INVOICEABLE_ITEM_FLAG
        , TAX_CODE
        , INVOICE_ENABLED_FLAG
        , MUST_USE_APPROVED_VENDOR_FLAG
        , REQUEST_ID
        , PROGRAM_APPLICATION_ID
        , PROGRAM_ID
        , PROGRAM_UPDATE_DATE
        , OUTSIDE_OPERATION_FLAG
        , OUTSIDE_OPERATION_UOM_TYPE
        , SAFETY_STOCK_BUCKET_DAYS
        , AUTO_REDUCE_MPS
        , COSTING_ENABLED_FLAG
        , AUTO_CREATED_CONFIG_FLAG
        , CYCLE_COUNT_ENABLED_FLAG
        , ITEM_TYPE
        , MODEL_CONFIG_CLAUSE_NAME
        , SHIP_MODEL_COMPLETE_FLAG
        , MRP_PLANNING_CODE
        , RETURN_INSPECTION_REQUIREMENT
        , ATO_FORECAST_CONTROL
        , RELEASE_TIME_FENCE_CODE
        , RELEASE_TIME_FENCE_DAYS
        , CONTAINER_ITEM_FLAG
        , VEHICLE_ITEM_FLAG
        , MAXIMUM_LOAD_WEIGHT
        , MINIMUM_FILL_PERCENT
        , CONTAINER_TYPE_CODE
        , INTERNAL_VOLUME
        , WH_UPDATE_DATE
        , PRODUCT_FAMILY_ITEM_ID
        , GLOBAL_ATTRIBUTE_CATEGORY
        , GLOBAL_ATTRIBUTE1
        , GLOBAL_ATTRIBUTE2
        , GLOBAL_ATTRIBUTE3
        , GLOBAL_ATTRIBUTE4
        , GLOBAL_ATTRIBUTE5
        , GLOBAL_ATTRIBUTE6
        , GLOBAL_ATTRIBUTE7
        , GLOBAL_ATTRIBUTE8
        , GLOBAL_ATTRIBUTE9
        , GLOBAL_ATTRIBUTE10
        , PURCHASING_TAX_CODE
        , OVERCOMPLETION_TOLERANCE_TYPE
        , OVERCOMPLETION_TOLERANCE_VALUE
        , EFFECTIVITY_CONTROL
        , CHECK_SHORTAGES_FLAG
        , OVER_SHIPMENT_TOLERANCE
        , UNDER_SHIPMENT_TOLERANCE
        , OVER_RETURN_TOLERANCE
        , UNDER_RETURN_TOLERANCE
        , EQUIPMENT_TYPE
        , RECOVERED_PART_DISP_CODE
        , DEFECT_TRACKING_ON_FLAG
        , USAGE_ITEM_FLAG
        , EVENT_FLAG
        , ELECTRONIC_FLAG
        , DOWNLOADABLE_FLAG
        , VOL_DISCOUNT_EXEMPT_FLAG
        , COUPON_EXEMPT_FLAG
        , COMMS_NL_TRACKABLE_FLAG
        , ASSET_CREATION_CODE
        , COMMS_ACTIVATION_REQD_FLAG
        , ORDERABLE_ON_WEB_FLAG
        , BACK_ORDERABLE_FLAG
        , WEB_STATUS
        , INDIVISIBLE_FLAG
        , DIMENSION_UOM_CODE
        , UNIT_LENGTH
        , UNIT_WIDTH
        , UNIT_HEIGHT
        , BULK_PICKED_FLAG
        , LOT_STATUS_ENABLED
        , DEFAULT_LOT_STATUS_ID
        , SERIAL_STATUS_ENABLED
        , DEFAULT_SERIAL_STATUS_ID
        , LOT_SPLIT_ENABLED
        , LOT_MERGE_ENABLED
        , INVENTORY_CARRY_PENALTY
        , OPERATION_SLACK_PENALTY
        , FINANCING_ALLOWED_FLAG
        , EAM_ITEM_TYPE
        , EAM_ACTIVITY_TYPE_CODE
        , EAM_ACTIVITY_CAUSE_CODE
        , EAM_ACT_NOTIFICATION_FLAG
        , EAM_ACT_SHUTDOWN_STATUS
        , DUAL_UOM_CONTROL
        , SECONDARY_UOM_CODE
        , DUAL_UOM_DEVIATION_HIGH
        , DUAL_UOM_DEVIATION_LOW
        , CONTRACT_ITEM_TYPE_CODE
        , SUBSCRIPTION_DEPEND_FLAG
        , SERV_REQ_ENABLED_CODE
        , SERV_BILLING_ENABLED_FLAG
        , SERV_IMPORTANCE_LEVEL
        , PLANNED_INV_POINT_FLAG
        , LOT_TRANSLATE_ENABLED
        , DEFAULT_SO_SOURCE_TYPE
        , CREATE_SUPPLY_FLAG
        , SUBSTITUTION_WINDOW_CODE
        , SUBSTITUTION_WINDOW_DAYS
        , IB_ITEM_INSTANCE_CLASS
        , CONFIG_MODEL_TYPE
        , LOT_SUBSTITUTION_ENABLED
        , MINIMUM_LICENSE_QUANTITY
        , EAM_ACTIVITY_SOURCE_CODE
        , LIFECYCLE_ID
        , CURRENT_PHASE_ID
        , OBJECT_VERSION_NUMBER
        , TRACKING_QUANTITY_IND
        , ONT_PRICING_QTY_SOURCE
        , SECONDARY_DEFAULT_IND
        , OPTION_SPECIFIC_SOURCED
        , APPROVAL_STATUS
        , VMI_MINIMUM_UNITS
        , VMI_MINIMUM_DAYS
        , VMI_MAXIMUM_UNITS
        , VMI_MAXIMUM_DAYS
        , VMI_FIXED_ORDER_QUANTITY
        , SO_AUTHORIZATION_FLAG
        , CONSIGNED_FLAG
        , ASN_AUTOEXPIRE_FLAG
        , VMI_FORECAST_TYPE
        , FORECAST_HORIZON
        , EXCLUDE_FROM_BUDGET_FLAG
        , DAYS_TGT_INV_SUPPLY
        , DAYS_TGT_INV_WINDOW
        , DAYS_MAX_INV_SUPPLY
        , DAYS_MAX_INV_WINDOW
        , DRP_PLANNED_FLAG
        , CRITICAL_COMPONENT_FLAG
        , CONTINOUS_TRANSFER
        , CONVERGENCE
        , DIVERGENCE
        , CONFIG_ORGS
        , CONFIG_MATCH
        , GLOBAL_ATTRIBUTE11
        , GLOBAL_ATTRIBUTE12
        , GLOBAL_ATTRIBUTE13
        , GLOBAL_ATTRIBUTE14
        , GLOBAL_ATTRIBUTE15
        , GLOBAL_ATTRIBUTE16
        , GLOBAL_ATTRIBUTE17
        , GLOBAL_ATTRIBUTE18
        , GLOBAL_ATTRIBUTE19
        , GLOBAL_ATTRIBUTE20
        , ATTRIBUTE16
        , ATTRIBUTE17
        , ATTRIBUTE18
        , ATTRIBUTE19
        , ATTRIBUTE20
        , ATTRIBUTE21
        , ATTRIBUTE22
        , ATTRIBUTE23
        , ATTRIBUTE24
        , ATTRIBUTE25
        , ATTRIBUTE26
        , ATTRIBUTE27
        , ATTRIBUTE28
        , ATTRIBUTE29
        , ATTRIBUTE30
        , CAS_NUMBER
        , CHILD_LOT_FLAG
        , CHILD_LOT_PREFIX
        , CHILD_LOT_STARTING_NUMBER
        , CHILD_LOT_VALIDATION_FLAG
        , COPY_LOT_ATTRIBUTE_FLAG
        , DEFAULT_GRADE
        , EXPIRATION_ACTION_CODE
        , EXPIRATION_ACTION_INTERVAL
        , GRADE_CONTROL_FLAG
        , HAZARDOUS_MATERIAL_FLAG
        , HOLD_DAYS
        , LOT_DIVISIBLE_FLAG
        , MATURITY_DAYS
        , PARENT_CHILD_GENERATION_FLAG
        , PROCESS_COSTING_ENABLED_FLAG
        , PROCESS_EXECUTION_ENABLED_FLAG
        , PROCESS_QUALITY_ENABLED_FLAG
        , PROCESS_SUPPLY_LOCATOR_ID
        , PROCESS_SUPPLY_SUBINVENTORY
        , PROCESS_YIELD_LOCATOR_ID
        , PROCESS_YIELD_SUBINVENTORY
        , RECIPE_ENABLED_FLAG
        , RETEST_INTERVAL
        , CHARGE_PERIODICITY_CODE
        , REPAIR_LEADTIME
        , REPAIR_YIELD
        , PREPOSITION_POINT
        , REPAIR_PROGRAM
        , SUBCONTRACTING_COMPONENT
        , OUTSOURCED_ASSEMBLY
        , EGO_MASTER_ITEMS_DFF_CTX
        , GDSN_OUTBOUND_ENABLED_FLAG
        , TRADE_ITEM_DESCRIPTOR
        , STYLE_ITEM_ID
        , STYLE_ITEM_FLAG
        , LAST_SUBMITTED_NIR_ID
        , DEFAULT_MATERIAL_STATUS_ID
        , SERIAL_TAGGING_FLAG
        , IB_ITEM_TRACKING_LEVEL
        , MCC_CLASSIFICATION_TYPE
        , MCC_CONTROL_CODE
        , MCC_TRACKING_CODE
        , GLOBAL_ATTRIBUTE21
        , GLOBAL_ATTRIBUTE22
        , GLOBAL_ATTRIBUTE23
        , GLOBAL_ATTRIBUTE24
        , GLOBAL_ATTRIBUTE25
        , GLOBAL_ATTRIBUTE26
        , GLOBAL_ATTRIBUTE27
        , GLOBAL_ATTRIBUTE28
        , GLOBAL_ATTRIBUTE29
        , GLOBAL_ATTRIBUTE30
        , GLOBAL_ATTRIBUTE31
        , GLOBAL_ATTRIBUTE32
        , GLOBAL_ATTRIBUTE33
        , GLOBAL_ATTRIBUTE34
        , GLOBAL_ATTRIBUTE35
        , GLOBAL_ATTRIBUTE36
        , GLOBAL_ATTRIBUTE37
        , GLOBAL_ATTRIBUTE38
        , GLOBAL_ATTRIBUTE39
        , GLOBAL_ATTRIBUTE40
        , _FIVETRAN_DELETED
        , _FIVETRAN_ID
        , _FIVETRAN_SYNCED
        , PSA_DELETE_IND
        , PSA_LOAD_DTS
        , PSA_RECORD_SOURCE
        , LOAD_DTS
        , REC_SRC
        , BKCC
        , PLANT_BK
        , MD5_BINARY(UPPER(CONCAT_WS('||',
          COALESCE(NULLIF(TRIM(CAST(ITEM_BK as VARCHAR)),''), '^^')
        , COALESCE(NULLIF(TRIM(CAST(BKCC as VARCHAR)),''), '^^')
        ))) as ITEM_HK
        , MD5_BINARY(UPPER(CONCAT_WS('||',
          COALESCE(NULLIF(TRIM(CAST(PLANT_BK as VARCHAR)),''), '^^')
        , COALESCE(NULLIF(TRIM(CAST(BKCC as VARCHAR)),''), '^^')
        ))) as PLANT_HK
        , MD5_BINARY(UPPER(CONCAT_WS('||',
          COALESCE(NULLIF(TRIM(CAST(ITEM_BK as VARCHAR)),''), '^^')
        , COALESCE(NULLIF(TRIM(CAST(PLANT_BK as VARCHAR)),''), '^^')
        , COALESCE(NULLIF(TRIM(CAST(BKCC as VARCHAR)),''), '^^')
        ))) as PLANT_ITEM_HK
        , MD5_BINARY(UPPER(NULLIF(CONCAT(
              IFNULL(TRIM(INVENTORY_ITEM_ID::text), '^^') 
            , '||', IFNULL(TRIM(ORGANIZATION_ID::text), '^^') 
            , '||', IFNULL(TRIM(LAST_UPDATE_DATE::text), '^^') 
            , '||', IFNULL(TRIM(LAST_UPDATED_BY::text), '^^') 
            , '||', IFNULL(TRIM(CREATION_DATE::text), '^^') 
            , '||', IFNULL(TRIM(CREATED_BY::text), '^^') 
            , '||', IFNULL(TRIM(LAST_UPDATE_LOGIN::text), '^^') 
            , '||', IFNULL(TRIM(SUMMARY_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(ENABLED_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(START_DATE_ACTIVE::text), '^^') 
            , '||', IFNULL(TRIM(END_DATE_ACTIVE::text), '^^') 
            , '||', IFNULL(TRIM(DESCRIPTION::text), '^^') 
            , '||', IFNULL(TRIM(BUYER_ID::text), '^^') 
            , '||', IFNULL(TRIM(ACCOUNTING_RULE_ID::text), '^^') 
            , '||', IFNULL(TRIM(INVOICING_RULE_ID::text), '^^') 
            , '||', IFNULL(TRIM(SEGMENT2::text), '^^') 
            , '||', IFNULL(TRIM(SEGMENT3::text), '^^') 
            , '||', IFNULL(TRIM(SEGMENT4::text), '^^') 
            , '||', IFNULL(TRIM(SEGMENT5::text), '^^') 
            , '||', IFNULL(TRIM(SEGMENT6::text), '^^') 
            , '||', IFNULL(TRIM(SEGMENT7::text), '^^') 
            , '||', IFNULL(TRIM(SEGMENT8::text), '^^') 
            , '||', IFNULL(TRIM(SEGMENT9::text), '^^') 
            , '||', IFNULL(TRIM(SEGMENT10::text), '^^') 
            , '||', IFNULL(TRIM(SEGMENT11::text), '^^') 
            , '||', IFNULL(TRIM(SEGMENT12::text), '^^') 
            , '||', IFNULL(TRIM(SEGMENT13::text), '^^') 
            , '||', IFNULL(TRIM(SEGMENT14::text), '^^') 
            , '||', IFNULL(TRIM(SEGMENT15::text), '^^') 
            , '||', IFNULL(TRIM(SEGMENT16::text), '^^') 
            , '||', IFNULL(TRIM(SEGMENT17::text), '^^') 
            , '||', IFNULL(TRIM(SEGMENT18::text), '^^') 
            , '||', IFNULL(TRIM(SEGMENT19::text), '^^') 
            , '||', IFNULL(TRIM(SEGMENT20::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE_CATEGORY::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE1::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE2::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE3::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE4::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE5::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE6::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE7::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE8::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE9::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE10::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE11::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE12::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE13::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE14::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE15::text), '^^') 
            , '||', IFNULL(TRIM(PURCHASING_ITEM_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(SHIPPABLE_ITEM_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(CUSTOMER_ORDER_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(INTERNAL_ORDER_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(SERVICE_ITEM_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(INVENTORY_ITEM_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(ENG_ITEM_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(INVENTORY_ASSET_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(PURCHASING_ENABLED_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(CUSTOMER_ORDER_ENABLED_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(INTERNAL_ORDER_ENABLED_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(SO_TRANSACTIONS_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(MTL_TRANSACTIONS_ENABLED_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(STOCK_ENABLED_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(BOM_ENABLED_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(BUILD_IN_WIP_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(REVISION_QTY_CONTROL_CODE::text), '^^') 
            , '||', IFNULL(TRIM(ITEM_CATALOG_GROUP_ID::text), '^^') 
            , '||', IFNULL(TRIM(CATALOG_STATUS_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(RETURNABLE_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(DEFAULT_SHIPPING_ORG::text), '^^') 
            , '||', IFNULL(TRIM(COLLATERAL_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(TAXABLE_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(QTY_RCV_EXCEPTION_CODE::text), '^^') 
            , '||', IFNULL(TRIM(ALLOW_ITEM_DESC_UPDATE_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(INSPECTION_REQUIRED_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(RECEIPT_REQUIRED_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(MARKET_PRICE::text), '^^') 
            , '||', IFNULL(TRIM(HAZARD_CLASS_ID::text), '^^') 
            , '||', IFNULL(TRIM(RFQ_REQUIRED_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(QTY_RCV_TOLERANCE::text), '^^') 
            , '||', IFNULL(TRIM(LIST_PRICE_PER_UNIT::text), '^^') 
            , '||', IFNULL(TRIM(UN_NUMBER_ID::text), '^^') 
            , '||', IFNULL(TRIM(PRICE_TOLERANCE_PERCENT::text), '^^') 
            , '||', IFNULL(TRIM(ASSET_CATEGORY_ID::text), '^^') 
            , '||', IFNULL(TRIM(ROUNDING_FACTOR::text), '^^') 
            , '||', IFNULL(TRIM(UNIT_OF_ISSUE::text), '^^') 
            , '||', IFNULL(TRIM(ENFORCE_SHIP_TO_LOCATION_CODE::text), '^^') 
            , '||', IFNULL(TRIM(ALLOW_SUBSTITUTE_RECEIPTS_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(ALLOW_UNORDERED_RECEIPTS_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(ALLOW_EXPRESS_DELIVERY_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(DAYS_EARLY_RECEIPT_ALLOWED::text), '^^') 
            , '||', IFNULL(TRIM(DAYS_LATE_RECEIPT_ALLOWED::text), '^^') 
            , '||', IFNULL(TRIM(RECEIPT_DAYS_EXCEPTION_CODE::text), '^^') 
            , '||', IFNULL(TRIM(RECEIVING_ROUTING_ID::text), '^^') 
            , '||', IFNULL(TRIM(INVOICE_CLOSE_TOLERANCE::text), '^^') 
            , '||', IFNULL(TRIM(RECEIVE_CLOSE_TOLERANCE::text), '^^') 
            , '||', IFNULL(TRIM(AUTO_LOT_ALPHA_PREFIX::text), '^^') 
            , '||', IFNULL(TRIM(START_AUTO_LOT_NUMBER::text), '^^') 
            , '||', IFNULL(TRIM(LOT_CONTROL_CODE::text), '^^') 
            , '||', IFNULL(TRIM(SHELF_LIFE_CODE::text), '^^') 
            , '||', IFNULL(TRIM(SHELF_LIFE_DAYS::text), '^^') 
            , '||', IFNULL(TRIM(SERIAL_NUMBER_CONTROL_CODE::text), '^^') 
            , '||', IFNULL(TRIM(START_AUTO_SERIAL_NUMBER::text), '^^') 
            , '||', IFNULL(TRIM(AUTO_SERIAL_ALPHA_PREFIX::text), '^^') 
            , '||', IFNULL(TRIM(SOURCE_TYPE::text), '^^') 
            , '||', IFNULL(TRIM(SOURCE_ORGANIZATION_ID::text), '^^') 
            , '||', IFNULL(TRIM(SOURCE_SUBINVENTORY::text), '^^') 
            , '||', IFNULL(TRIM(EXPENSE_ACCOUNT::text), '^^') 
            , '||', IFNULL(TRIM(ENCUMBRANCE_ACCOUNT::text), '^^') 
            , '||', IFNULL(TRIM(RESTRICT_SUBINVENTORIES_CODE::text), '^^') 
            , '||', IFNULL(TRIM(UNIT_WEIGHT::text), '^^') 
            , '||', IFNULL(TRIM(WEIGHT_UOM_CODE::text), '^^') 
            , '||', IFNULL(TRIM(VOLUME_UOM_CODE::text), '^^') 
            , '||', IFNULL(TRIM(UNIT_VOLUME::text), '^^') 
            , '||', IFNULL(TRIM(RESTRICT_LOCATORS_CODE::text), '^^') 
            , '||', IFNULL(TRIM(LOCATION_CONTROL_CODE::text), '^^') 
            , '||', IFNULL(TRIM(SHRINKAGE_RATE::text), '^^') 
            , '||', IFNULL(TRIM(ACCEPTABLE_EARLY_DAYS::text), '^^') 
            , '||', IFNULL(TRIM(PLANNING_TIME_FENCE_CODE::text), '^^') 
            , '||', IFNULL(TRIM(DEMAND_TIME_FENCE_CODE::text), '^^') 
            , '||', IFNULL(TRIM(LEAD_TIME_LOT_SIZE::text), '^^') 
            , '||', IFNULL(TRIM(STD_LOT_SIZE::text), '^^') 
            , '||', IFNULL(TRIM(CUM_MANUFACTURING_LEAD_TIME::text), '^^') 
            , '||', IFNULL(TRIM(OVERRUN_PERCENTAGE::text), '^^') 
            , '||', IFNULL(TRIM(MRP_CALCULATE_ATP_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(ACCEPTABLE_RATE_INCREASE::text), '^^') 
            , '||', IFNULL(TRIM(ACCEPTABLE_RATE_DECREASE::text), '^^') 
            , '||', IFNULL(TRIM(CUMULATIVE_TOTAL_LEAD_TIME::text), '^^') 
            , '||', IFNULL(TRIM(PLANNING_TIME_FENCE_DAYS::text), '^^') 
            , '||', IFNULL(TRIM(DEMAND_TIME_FENCE_DAYS::text), '^^') 
            , '||', IFNULL(TRIM(END_ASSEMBLY_PEGGING_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(REPETITIVE_PLANNING_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(PLANNING_EXCEPTION_SET::text), '^^') 
            , '||', IFNULL(TRIM(BOM_ITEM_TYPE::text), '^^') 
            , '||', IFNULL(TRIM(PICK_COMPONENTS_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(REPLENISH_TO_ORDER_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(BASE_ITEM_ID::text), '^^') 
            , '||', IFNULL(TRIM(ATP_COMPONENTS_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(ATP_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(FIXED_LEAD_TIME::text), '^^') 
            , '||', IFNULL(TRIM(VARIABLE_LEAD_TIME::text), '^^') 
            , '||', IFNULL(TRIM(WIP_SUPPLY_LOCATOR_ID::text), '^^') 
            , '||', IFNULL(TRIM(WIP_SUPPLY_TYPE::text), '^^') 
            , '||', IFNULL(TRIM(WIP_SUPPLY_SUBINVENTORY::text), '^^') 
            , '||', IFNULL(TRIM(PRIMARY_UOM_CODE::text), '^^') 
            , '||', IFNULL(TRIM(PRIMARY_UNIT_OF_MEASURE::text), '^^') 
            , '||', IFNULL(TRIM(ALLOWED_UNITS_LOOKUP_CODE::text), '^^') 
            , '||', IFNULL(TRIM(COST_OF_SALES_ACCOUNT::text), '^^') 
            , '||', IFNULL(TRIM(SALES_ACCOUNT::text), '^^') 
            , '||', IFNULL(TRIM(DEFAULT_INCLUDE_IN_ROLLUP_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(INVENTORY_ITEM_STATUS_CODE::text), '^^') 
            , '||', IFNULL(TRIM(INVENTORY_PLANNING_CODE::text), '^^') 
            , '||', IFNULL(TRIM(PLANNER_CODE::text), '^^') 
            , '||', IFNULL(TRIM(PLANNING_MAKE_BUY_CODE::text), '^^') 
            , '||', IFNULL(TRIM(FIXED_LOT_MULTIPLIER::text), '^^') 
            , '||', IFNULL(TRIM(ROUNDING_CONTROL_TYPE::text), '^^') 
            , '||', IFNULL(TRIM(CARRYING_COST::text), '^^') 
            , '||', IFNULL(TRIM(POSTPROCESSING_LEAD_TIME::text), '^^') 
            , '||', IFNULL(TRIM(PREPROCESSING_LEAD_TIME::text), '^^') 
            , '||', IFNULL(TRIM(FULL_LEAD_TIME::text), '^^') 
            , '||', IFNULL(TRIM(ORDER_COST::text), '^^') 
            , '||', IFNULL(TRIM(MRP_SAFETY_STOCK_PERCENT::text), '^^') 
            , '||', IFNULL(TRIM(MRP_SAFETY_STOCK_CODE::text), '^^') 
            , '||', IFNULL(TRIM(MIN_MINMAX_QUANTITY::text), '^^') 
            , '||', IFNULL(TRIM(MAX_MINMAX_QUANTITY::text), '^^') 
            , '||', IFNULL(TRIM(MINIMUM_ORDER_QUANTITY::text), '^^') 
            , '||', IFNULL(TRIM(FIXED_ORDER_QUANTITY::text), '^^') 
            , '||', IFNULL(TRIM(FIXED_DAYS_SUPPLY::text), '^^') 
            , '||', IFNULL(TRIM(MAXIMUM_ORDER_QUANTITY::text), '^^') 
            , '||', IFNULL(TRIM(ATP_RULE_ID::text), '^^') 
            , '||', IFNULL(TRIM(PICKING_RULE_ID::text), '^^') 
            , '||', IFNULL(TRIM(RESERVABLE_TYPE::text), '^^') 
            , '||', IFNULL(TRIM(POSITIVE_MEASUREMENT_ERROR::text), '^^') 
            , '||', IFNULL(TRIM(NEGATIVE_MEASUREMENT_ERROR::text), '^^') 
            , '||', IFNULL(TRIM(ENGINEERING_ECN_CODE::text), '^^') 
            , '||', IFNULL(TRIM(ENGINEERING_ITEM_ID::text), '^^') 
            , '||', IFNULL(TRIM(ENGINEERING_DATE::text), '^^') 
            , '||', IFNULL(TRIM(SERVICE_STARTING_DELAY::text), '^^') 
            , '||', IFNULL(TRIM(VENDOR_WARRANTY_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(SERVICEABLE_COMPONENT_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(SERVICEABLE_PRODUCT_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(BASE_WARRANTY_SERVICE_ID::text), '^^') 
            , '||', IFNULL(TRIM(PAYMENT_TERMS_ID::text), '^^') 
            , '||', IFNULL(TRIM(PREVENTIVE_MAINTENANCE_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(PRIMARY_SPECIALIST_ID::text), '^^') 
            , '||', IFNULL(TRIM(SECONDARY_SPECIALIST_ID::text), '^^') 
            , '||', IFNULL(TRIM(SERVICEABLE_ITEM_CLASS_ID::text), '^^') 
            , '||', IFNULL(TRIM(TIME_BILLABLE_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(MATERIAL_BILLABLE_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(EXPENSE_BILLABLE_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(PRORATE_SERVICE_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(COVERAGE_SCHEDULE_ID::text), '^^') 
            , '||', IFNULL(TRIM(SERVICE_DURATION_PERIOD_CODE::text), '^^') 
            , '||', IFNULL(TRIM(SERVICE_DURATION::text), '^^') 
            , '||', IFNULL(TRIM(WARRANTY_VENDOR_ID::text), '^^') 
            , '||', IFNULL(TRIM(MAX_WARRANTY_AMOUNT::text), '^^') 
            , '||', IFNULL(TRIM(RESPONSE_TIME_PERIOD_CODE::text), '^^') 
            , '||', IFNULL(TRIM(RESPONSE_TIME_VALUE::text), '^^') 
            , '||', IFNULL(TRIM(NEW_REVISION_CODE::text), '^^') 
            , '||', IFNULL(TRIM(INVOICEABLE_ITEM_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(TAX_CODE::text), '^^') 
            , '||', IFNULL(TRIM(INVOICE_ENABLED_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(MUST_USE_APPROVED_VENDOR_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(REQUEST_ID::text), '^^') 
            , '||', IFNULL(TRIM(PROGRAM_APPLICATION_ID::text), '^^') 
            , '||', IFNULL(TRIM(PROGRAM_ID::text), '^^') 
            , '||', IFNULL(TRIM(PROGRAM_UPDATE_DATE::text), '^^') 
            , '||', IFNULL(TRIM(OUTSIDE_OPERATION_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(OUTSIDE_OPERATION_UOM_TYPE::text), '^^') 
            , '||', IFNULL(TRIM(SAFETY_STOCK_BUCKET_DAYS::text), '^^') 
            , '||', IFNULL(TRIM(AUTO_REDUCE_MPS::text), '^^') 
            , '||', IFNULL(TRIM(COSTING_ENABLED_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(AUTO_CREATED_CONFIG_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(CYCLE_COUNT_ENABLED_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(ITEM_TYPE::text), '^^') 
            , '||', IFNULL(TRIM(MODEL_CONFIG_CLAUSE_NAME::text), '^^') 
            , '||', IFNULL(TRIM(SHIP_MODEL_COMPLETE_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(MRP_PLANNING_CODE::text), '^^') 
            , '||', IFNULL(TRIM(RETURN_INSPECTION_REQUIREMENT::text), '^^') 
            , '||', IFNULL(TRIM(ATO_FORECAST_CONTROL::text), '^^') 
            , '||', IFNULL(TRIM(RELEASE_TIME_FENCE_CODE::text), '^^') 
            , '||', IFNULL(TRIM(RELEASE_TIME_FENCE_DAYS::text), '^^') 
            , '||', IFNULL(TRIM(CONTAINER_ITEM_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(VEHICLE_ITEM_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(MAXIMUM_LOAD_WEIGHT::text), '^^') 
            , '||', IFNULL(TRIM(MINIMUM_FILL_PERCENT::text), '^^') 
            , '||', IFNULL(TRIM(CONTAINER_TYPE_CODE::text), '^^') 
            , '||', IFNULL(TRIM(INTERNAL_VOLUME::text), '^^') 
            , '||', IFNULL(TRIM(WH_UPDATE_DATE::text), '^^') 
            , '||', IFNULL(TRIM(PRODUCT_FAMILY_ITEM_ID::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE_CATEGORY::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE1::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE2::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE3::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE4::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE5::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE6::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE7::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE8::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE9::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE10::text), '^^') 
            , '||', IFNULL(TRIM(PURCHASING_TAX_CODE::text), '^^') 
            , '||', IFNULL(TRIM(OVERCOMPLETION_TOLERANCE_TYPE::text), '^^') 
            , '||', IFNULL(TRIM(OVERCOMPLETION_TOLERANCE_VALUE::text), '^^') 
            , '||', IFNULL(TRIM(EFFECTIVITY_CONTROL::text), '^^') 
            , '||', IFNULL(TRIM(CHECK_SHORTAGES_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(OVER_SHIPMENT_TOLERANCE::text), '^^') 
            , '||', IFNULL(TRIM(UNDER_SHIPMENT_TOLERANCE::text), '^^') 
            , '||', IFNULL(TRIM(OVER_RETURN_TOLERANCE::text), '^^') 
            , '||', IFNULL(TRIM(UNDER_RETURN_TOLERANCE::text), '^^') 
            , '||', IFNULL(TRIM(EQUIPMENT_TYPE::text), '^^') 
            , '||', IFNULL(TRIM(RECOVERED_PART_DISP_CODE::text), '^^') 
            , '||', IFNULL(TRIM(DEFECT_TRACKING_ON_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(USAGE_ITEM_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(EVENT_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(ELECTRONIC_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(DOWNLOADABLE_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(VOL_DISCOUNT_EXEMPT_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(COUPON_EXEMPT_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(COMMS_NL_TRACKABLE_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(ASSET_CREATION_CODE::text), '^^') 
            , '||', IFNULL(TRIM(COMMS_ACTIVATION_REQD_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(ORDERABLE_ON_WEB_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(BACK_ORDERABLE_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(WEB_STATUS::text), '^^') 
            , '||', IFNULL(TRIM(INDIVISIBLE_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(DIMENSION_UOM_CODE::text), '^^') 
            , '||', IFNULL(TRIM(UNIT_LENGTH::text), '^^') 
            , '||', IFNULL(TRIM(UNIT_WIDTH::text), '^^') 
            , '||', IFNULL(TRIM(UNIT_HEIGHT::text), '^^') 
            , '||', IFNULL(TRIM(BULK_PICKED_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(LOT_STATUS_ENABLED::text), '^^') 
            , '||', IFNULL(TRIM(DEFAULT_LOT_STATUS_ID::text), '^^') 
            , '||', IFNULL(TRIM(SERIAL_STATUS_ENABLED::text), '^^') 
            , '||', IFNULL(TRIM(DEFAULT_SERIAL_STATUS_ID::text), '^^') 
            , '||', IFNULL(TRIM(LOT_SPLIT_ENABLED::text), '^^') 
            , '||', IFNULL(TRIM(LOT_MERGE_ENABLED::text), '^^') 
            , '||', IFNULL(TRIM(INVENTORY_CARRY_PENALTY::text), '^^') 
            , '||', IFNULL(TRIM(OPERATION_SLACK_PENALTY::text), '^^') 
            , '||', IFNULL(TRIM(FINANCING_ALLOWED_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(EAM_ITEM_TYPE::text), '^^') 
            , '||', IFNULL(TRIM(EAM_ACTIVITY_TYPE_CODE::text), '^^') 
            , '||', IFNULL(TRIM(EAM_ACTIVITY_CAUSE_CODE::text), '^^') 
            , '||', IFNULL(TRIM(EAM_ACT_NOTIFICATION_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(EAM_ACT_SHUTDOWN_STATUS::text), '^^') 
            , '||', IFNULL(TRIM(DUAL_UOM_CONTROL::text), '^^') 
            , '||', IFNULL(TRIM(SECONDARY_UOM_CODE::text), '^^') 
            , '||', IFNULL(TRIM(DUAL_UOM_DEVIATION_HIGH::text), '^^') 
            , '||', IFNULL(TRIM(DUAL_UOM_DEVIATION_LOW::text), '^^') 
            , '||', IFNULL(TRIM(CONTRACT_ITEM_TYPE_CODE::text), '^^') 
            , '||', IFNULL(TRIM(SUBSCRIPTION_DEPEND_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(SERV_REQ_ENABLED_CODE::text), '^^') 
            , '||', IFNULL(TRIM(SERV_BILLING_ENABLED_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(SERV_IMPORTANCE_LEVEL::text), '^^') 
            , '||', IFNULL(TRIM(PLANNED_INV_POINT_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(LOT_TRANSLATE_ENABLED::text), '^^') 
            , '||', IFNULL(TRIM(DEFAULT_SO_SOURCE_TYPE::text), '^^') 
            , '||', IFNULL(TRIM(CREATE_SUPPLY_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(SUBSTITUTION_WINDOW_CODE::text), '^^') 
            , '||', IFNULL(TRIM(SUBSTITUTION_WINDOW_DAYS::text), '^^') 
            , '||', IFNULL(TRIM(IB_ITEM_INSTANCE_CLASS::text), '^^') 
            , '||', IFNULL(TRIM(CONFIG_MODEL_TYPE::text), '^^') 
            , '||', IFNULL(TRIM(LOT_SUBSTITUTION_ENABLED::text), '^^') 
            , '||', IFNULL(TRIM(MINIMUM_LICENSE_QUANTITY::text), '^^') 
            , '||', IFNULL(TRIM(EAM_ACTIVITY_SOURCE_CODE::text), '^^') 
            , '||', IFNULL(TRIM(LIFECYCLE_ID::text), '^^') 
            , '||', IFNULL(TRIM(CURRENT_PHASE_ID::text), '^^') 
            , '||', IFNULL(TRIM(OBJECT_VERSION_NUMBER::text), '^^') 
            , '||', IFNULL(TRIM(TRACKING_QUANTITY_IND::text), '^^') 
            , '||', IFNULL(TRIM(ONT_PRICING_QTY_SOURCE::text), '^^') 
            , '||', IFNULL(TRIM(SECONDARY_DEFAULT_IND::text), '^^') 
            , '||', IFNULL(TRIM(OPTION_SPECIFIC_SOURCED::text), '^^') 
            , '||', IFNULL(TRIM(APPROVAL_STATUS::text), '^^') 
            , '||', IFNULL(TRIM(VMI_MINIMUM_UNITS::text), '^^') 
            , '||', IFNULL(TRIM(VMI_MINIMUM_DAYS::text), '^^') 
            , '||', IFNULL(TRIM(VMI_MAXIMUM_UNITS::text), '^^') 
            , '||', IFNULL(TRIM(VMI_MAXIMUM_DAYS::text), '^^') 
            , '||', IFNULL(TRIM(VMI_FIXED_ORDER_QUANTITY::text), '^^') 
            , '||', IFNULL(TRIM(SO_AUTHORIZATION_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(CONSIGNED_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(ASN_AUTOEXPIRE_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(VMI_FORECAST_TYPE::text), '^^') 
            , '||', IFNULL(TRIM(FORECAST_HORIZON::text), '^^') 
            , '||', IFNULL(TRIM(EXCLUDE_FROM_BUDGET_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(DAYS_TGT_INV_SUPPLY::text), '^^') 
            , '||', IFNULL(TRIM(DAYS_TGT_INV_WINDOW::text), '^^') 
            , '||', IFNULL(TRIM(DAYS_MAX_INV_SUPPLY::text), '^^') 
            , '||', IFNULL(TRIM(DAYS_MAX_INV_WINDOW::text), '^^') 
            , '||', IFNULL(TRIM(DRP_PLANNED_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(CRITICAL_COMPONENT_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(CONTINOUS_TRANSFER::text), '^^') 
            , '||', IFNULL(TRIM(CONVERGENCE::text), '^^') 
            , '||', IFNULL(TRIM(DIVERGENCE::text), '^^') 
            , '||', IFNULL(TRIM(CONFIG_ORGS::text), '^^') 
            , '||', IFNULL(TRIM(CONFIG_MATCH::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE11::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE12::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE13::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE14::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE15::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE16::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE17::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE18::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE19::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE20::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE16::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE17::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE18::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE19::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE20::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE21::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE22::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE23::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE24::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE25::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE26::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE27::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE28::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE29::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE30::text), '^^') 
            , '||', IFNULL(TRIM(CAS_NUMBER::text), '^^') 
            , '||', IFNULL(TRIM(CHILD_LOT_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(CHILD_LOT_PREFIX::text), '^^') 
            , '||', IFNULL(TRIM(CHILD_LOT_STARTING_NUMBER::text), '^^') 
            , '||', IFNULL(TRIM(CHILD_LOT_VALIDATION_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(COPY_LOT_ATTRIBUTE_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(DEFAULT_GRADE::text), '^^') 
            , '||', IFNULL(TRIM(EXPIRATION_ACTION_CODE::text), '^^') 
            , '||', IFNULL(TRIM(EXPIRATION_ACTION_INTERVAL::text), '^^') 
            , '||', IFNULL(TRIM(GRADE_CONTROL_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(HAZARDOUS_MATERIAL_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(HOLD_DAYS::text), '^^') 
            , '||', IFNULL(TRIM(LOT_DIVISIBLE_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(MATURITY_DAYS::text), '^^') 
            , '||', IFNULL(TRIM(PARENT_CHILD_GENERATION_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(PROCESS_COSTING_ENABLED_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(PROCESS_EXECUTION_ENABLED_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(PROCESS_QUALITY_ENABLED_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(PROCESS_SUPPLY_LOCATOR_ID::text), '^^') 
            , '||', IFNULL(TRIM(PROCESS_SUPPLY_SUBINVENTORY::text), '^^') 
            , '||', IFNULL(TRIM(PROCESS_YIELD_LOCATOR_ID::text), '^^') 
            , '||', IFNULL(TRIM(PROCESS_YIELD_SUBINVENTORY::text), '^^') 
            , '||', IFNULL(TRIM(RECIPE_ENABLED_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(RETEST_INTERVAL::text), '^^') 
            , '||', IFNULL(TRIM(CHARGE_PERIODICITY_CODE::text), '^^') 
            , '||', IFNULL(TRIM(REPAIR_LEADTIME::text), '^^') 
            , '||', IFNULL(TRIM(REPAIR_YIELD::text), '^^') 
            , '||', IFNULL(TRIM(PREPOSITION_POINT::text), '^^') 
            , '||', IFNULL(TRIM(REPAIR_PROGRAM::text), '^^') 
            , '||', IFNULL(TRIM(SUBCONTRACTING_COMPONENT::text), '^^') 
            , '||', IFNULL(TRIM(OUTSOURCED_ASSEMBLY::text), '^^') 
            , '||', IFNULL(TRIM(EGO_MASTER_ITEMS_DFF_CTX::text), '^^') 
            , '||', IFNULL(TRIM(GDSN_OUTBOUND_ENABLED_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(TRADE_ITEM_DESCRIPTOR::text), '^^') 
            , '||', IFNULL(TRIM(STYLE_ITEM_ID::text), '^^') 
            , '||', IFNULL(TRIM(STYLE_ITEM_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(LAST_SUBMITTED_NIR_ID::text), '^^') 
            , '||', IFNULL(TRIM(DEFAULT_MATERIAL_STATUS_ID::text), '^^') 
            , '||', IFNULL(TRIM(SERIAL_TAGGING_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(_FIVETRAN_DELETED::text), '^^') 
        ), '^^||^^')))  as HASHDIFF
FROM JOIN_RESULT
