---- SRC LAYER ----
WITH
SRC_S              as ( SELECT ALLOCATE_LOT_FLAG, ALLOCATE_SERIAL_FLAG, ALLOW_DIFFERENT_STATUS, AP_ACCRUAL_ACCOUNT, ATTRIBUTE1, ATTRIBUTE10, ATTRIBUTE11, ATTRIBUTE12, ATTRIBUTE13, ATTRIBUTE14, ATTRIBUTE15, ATTRIBUTE2, ATTRIBUTE3, ATTRIBUTE4, ATTRIBUTE5, ATTRIBUTE6, ATTRIBUTE7, ATTRIBUTE8, ATTRIBUTE9, ATTRIBUTE_CATEGORY, AUTO_DEL_ALLOC_FLAG, AUTO_LOT_ALPHA_PREFIX, AUTO_SERIAL_ALPHA_PREFIX, AVERAGE_COST_VAR_ACCOUNT, AVG_RATES_COST_TYPE_ID, BORRPAY_MATL_VAR_ACCOUNT, BORRPAY_MOH_VAR_ACCOUNT, BORRPAY_OSP_VAR_ACCOUNT, BORRPAY_OVH_VAR_ACCOUNT, BORRPAY_RES_VAR_ACCOUNT, CALENDAR_CODE, CALENDAR_EXCEPTION_SET_ID, CARRIER_MANIFESTING_FLAG, CARTONIZATION_FLAG, CARTONIZE_MANUFACTURING, CARTONIZE_SALES_ORDERS, CAT_WT_ACCOUNT, CC_APPROVAL_TIMEOUT_ACTION, CC_APPROVAL_TIMEOUT_PERIOD, CC_WORKFLOW_ENABLED_FLAG, CHILD_LOT_ALPHA_PREFIX, CHILD_LOT_NUMBER_LENGTH, CHILD_LOT_VALIDATION_FLAG, CHILD_LOT_ZERO_PADDING_FLAG, COMMERCIAL_GOVT_ENTITY_NUMBER, COMPANY_PREFIX, COMPANY_PREFIX_INDEX, CONSIGNED_FLAG, COPY_LOT_ATTRIBUTE_FLAG, COST_CUTOFF_DATE, COST_GROUP_ACCOUNTING, COST_OF_SALES_ACCOUNT, COST_ORGANIZATION_ID, CREATED_BY, CREATE_LOT_UOM_CONVERSION, CREATION_DATE, CROSSDOCK_FLAG, DAILY_CAL_END_TIME, DAILY_CAL_START_TIME, DEFAULT_ATP_RULE_ID, DEFAULT_CARTON_RULE_ID, DEFAULT_CC_TASK_TYPE_ID, DEFAULT_COST_GROUP_ID, DEFAULT_CROSSDOCK_CRITERIA_ID, DEFAULT_CROSSDOCK_LOCATOR_ID, DEFAULT_CROSSDOCK_SUBINVENTORY, DEFAULT_CYC_COUNT_HEADER_ID, DEFAULT_DEMAND_CLASS, DEFAULT_LABEL_COMP_RULE_ID, DEFAULT_LOCATOR_ORDER_VALUE, DEFAULT_MATERIAL_COST_ID, DEFAULT_MATL_OVHD_COST_ID, DEFAULT_MOISSUE_TASK_TYPE_ID, DEFAULT_MOXFER_TASK_TYPE_ID, DEFAULT_PICKING_RULE_ID, DEFAULT_PICK_OP_PLAN_ID, DEFAULT_PICK_TASK_TYPE_ID, DEFAULT_PUTAWAY_TASK_TYPE_ID, DEFAULT_PUT_AWAY_RULE_ID, DEFAULT_REPL_TASK_TYPE_ID, DEFAULT_STATUS_ID, DEFAULT_SUBINV_ORDER_VALUE, DEFAULT_TASK_ASSIGN_RULE_ID, DEFAULT_WMS_PICKING_RULE_ID, DEFERRED_COGS_ACCOUNT, DEFER_LOGICAL_TRANSACTIONS, DIRECT_SHIPPING_ALLOWED, DISPATCH_INBOUND_TASK, DISTRIBUTED_ORGANIZATION_FLAG, DISTRIBUTION_ACCOUNT_ID, EAM_ENABLED_FLAG, ENABLE_COSTING_BY_CATEGORY, ENABLE_EKANBAN, ENCUMBRANCE_ACCOUNT, ENCUMBRANCE_REVERSAL_FLAG, ENFORCE_LOCATOR_ALIS_UNQ_FLAG, EPC_GENERATION_ENABLED_FLAG, EXPENSE_ACCOUNT, GENEALOGY_FORMULA_SECURITY, GENERAL_LEDGER_UPDATE_CODE, GLOBAL_ATTRIBUTE1, GLOBAL_ATTRIBUTE10, GLOBAL_ATTRIBUTE11, GLOBAL_ATTRIBUTE12, GLOBAL_ATTRIBUTE13, GLOBAL_ATTRIBUTE14, GLOBAL_ATTRIBUTE15, GLOBAL_ATTRIBUTE16, GLOBAL_ATTRIBUTE17, GLOBAL_ATTRIBUTE18, GLOBAL_ATTRIBUTE19, GLOBAL_ATTRIBUTE2, GLOBAL_ATTRIBUTE20, GLOBAL_ATTRIBUTE3, GLOBAL_ATTRIBUTE4, GLOBAL_ATTRIBUTE5, GLOBAL_ATTRIBUTE6, GLOBAL_ATTRIBUTE7, GLOBAL_ATTRIBUTE8, GLOBAL_ATTRIBUTE9, GLOBAL_ATTRIBUTE_CATEGORY, INTERORG_PAYABLES_ACCOUNT, INTERORG_PRICE_VAR_ACCOUNT, INTERORG_RECEIVABLES_ACCOUNT, INTERORG_TRANSFER_CR_ACCOUNT, INTERORG_TRNSFR_CHARGE_PERCENT, INTRANSIT_INV_ACCOUNT, INVOICE_PRICE_VAR_ACCOUNT, LABOR_MANAGEMENT_ENABLED_FLAG, LAST_UPDATED_BY, LAST_UPDATE_DATE, LAST_UPDATE_LOGIN, LCM_ENABLED_FLAG, LCM_VAR_ACCOUNT, LOT_NUMBER_GENERATION, LOT_NUMBER_LENGTH, LOT_NUMBER_UNIQUENESS, LOT_NUMBER_ZERO_PADDING, LPN_PREFIX, LPN_STARTING_NUMBER, LPN_SUFFIX, MAINTAIN_FIFO_QTY_STACK_TYPE, MAINT_ORGANIZATION_ID, MASTER_ORGANIZATION_ID, MATERIAL_ACCOUNT, MATERIAL_OVERHEAD_ACCOUNT, MATL_INTERORG_TRANSFER_CODE, MATL_OVHD_ABSORPTION_ACCT, MAT_OVHD_COST_TYPE_ID, MAX_CLUSTERS_ALLOWED, MAX_PICKS_BATCH, MO_APPROVAL_TIMEOUT_ACTION, MO_PICK_CONFIRM_REQUIRED, MO_SOURCE_REQUIRED, NEGATIVE_INV_RECEIPT_CODE, OPSM_ENABLED_FLAG, ORGANIZATION_CODE, ORGANIZATION_ID, ORG_MAX_VOLUME, ORG_MAX_VOLUME_UOM_CODE, ORG_MAX_WEIGHT, ORG_MAX_WEIGHT_UOM_CODE, OUTSIDE_PROCESSING_ACCOUNT, OVERHEAD_ACCOUNT, OVPK_TRANSFER_ORDERS_ENABLED, PARENT_CHILD_GENERATION_FLAG, PICK_VERIFY_CATEGORY_SET_ID, PICK_VERIFY_MO_ENABLED, PICK_VERIFY_SO_ENABLED, PICK_VERIFY_WT_TOLERANCE_NEG, PICK_VERIFY_WT_TOLERANCE_POS, PM_COST_COLLECTION_ENABLED, PREGEN_PUTAWAY_TASKS_FLAG, PRIMARY_COST_METHOD, PRIORITIZE_WIP_JOBS, PROCESS_ENABLED_FLAG, PROCESS_ORGN_CODE, PROGRAM_APPLICATION_ID, PROGRAM_ID, PROGRAM_UPDATE_DATE, PROJECT_CONTROL_LEVEL, PROJECT_COST_ACCOUNT, PROJECT_REFERENCE_ENABLED, PSA_DELETE_IND, PSA_LOAD_DTS, PSA_RECORD_SOURCE, PURCHASE_PRICE_VAR_ACCOUNT, QA_SKIPPING_INSP_FLAG, REGENERATION_INTERVAL, REQUEST_ID, RESOURCE_ACCOUNT, RFID_VERIF_PCNT_THRESHOLD, RULES_OVERRIDE_LOT_RESERVATION, SALES_ACCOUNT, SERIAL_NUMBER_GENERATION, SERIAL_NUMBER_TYPE, SKIP_TASK_WAITING_MINUTES, SOURCE_ORGANIZATION_ID, SOURCE_SUBINVENTORY, SOURCE_TYPE, STARTING_REVISION, START_AUTO_SERIAL_NUMBER, STOCK_LOCATOR_CONTROL_CODE, TIMEZONE_ID, TOTAL_LPN_LENGTH, TRADING_PARTNER_ORG_FLAG, TRADING_PARTNER_ORG_TYPE, TXN_APPROVAL_TIMEOUT_PERIOD, UCC_128_SUFFIX_FLAG, WCS_ENABLED, WIP_OVERPICK_ENABLED, WMS_ENABLED_FLAG, WSM_ENABLED_FLAG, YARD_MANAGEMENT_ENABLED_FLAG, YARD_ORG_ID, YMS_COSTING_ENABLED, YMS_DEFAULT_LOCATOR, YMS_DEFAULT_SUBINV, _FIVETRAN_DELETED, _FIVETRAN_ID, _FIVETRAN_SYNCED FROM {{ source('emtk_ebs_inv', 'mtl_parameters') }} as SRC  ),
SRC_A              as ( SELECT BKCC, REC_SRC FROM {{ ref('ref_business_key_collision') }} as SRC  )

/*
SRC_S              as ( SELECT * FROM emtk_ebs_inv.mtl_parameters  )
SRC_A              as ( SELECT * FROM raw_vault.ref_business_key_collision )
*/
---- LOGIC LAYER ----

, LOGIC_S as (
    SELECT
        ORGANIZATION_CODE                                            as                                           PLANT_BK
      , ORGANIZATION_CODE
      , ORGANIZATION_ID
      , LAST_UPDATE_DATE
      , LAST_UPDATED_BY
      , CREATION_DATE
      , CREATED_BY
      , LAST_UPDATE_LOGIN
      , MASTER_ORGANIZATION_ID
      , PRIMARY_COST_METHOD
      , COST_ORGANIZATION_ID
      , DEFAULT_MATERIAL_COST_ID
      , CALENDAR_EXCEPTION_SET_ID
      , CALENDAR_CODE
      , GENERAL_LEDGER_UPDATE_CODE
      , DEFAULT_ATP_RULE_ID
      , DEFAULT_PICKING_RULE_ID
      , DEFAULT_LOCATOR_ORDER_VALUE
      , DEFAULT_SUBINV_ORDER_VALUE
      , NEGATIVE_INV_RECEIPT_CODE
      , STOCK_LOCATOR_CONTROL_CODE
      , MATERIAL_ACCOUNT
      , MATERIAL_OVERHEAD_ACCOUNT
      , MATL_OVHD_ABSORPTION_ACCT
      , RESOURCE_ACCOUNT
      , PURCHASE_PRICE_VAR_ACCOUNT
      , AP_ACCRUAL_ACCOUNT
      , OVERHEAD_ACCOUNT
      , OUTSIDE_PROCESSING_ACCOUNT
      , INTRANSIT_INV_ACCOUNT
      , INTERORG_RECEIVABLES_ACCOUNT
      , INTERORG_PRICE_VAR_ACCOUNT
      , INTERORG_PAYABLES_ACCOUNT
      , COST_OF_SALES_ACCOUNT
      , ENCUMBRANCE_ACCOUNT
      , PROJECT_COST_ACCOUNT
      , INTERORG_TRANSFER_CR_ACCOUNT
      , MATL_INTERORG_TRANSFER_CODE
      , INTERORG_TRNSFR_CHARGE_PERCENT
      , SOURCE_ORGANIZATION_ID
      , SOURCE_SUBINVENTORY
      , SOURCE_TYPE
      , ORG_MAX_WEIGHT
      , ORG_MAX_WEIGHT_UOM_CODE
      , ORG_MAX_VOLUME
      , ORG_MAX_VOLUME_UOM_CODE
      , SERIAL_NUMBER_TYPE
      , AUTO_SERIAL_ALPHA_PREFIX
      , START_AUTO_SERIAL_NUMBER
      , AUTO_LOT_ALPHA_PREFIX
      , LOT_NUMBER_UNIQUENESS
      , LOT_NUMBER_GENERATION
      , LOT_NUMBER_ZERO_PADDING
      , LOT_NUMBER_LENGTH
      , STARTING_REVISION
      , ATTRIBUTE_CATEGORY
      , ATTRIBUTE1
      , ATTRIBUTE2
      , ATTRIBUTE3
      , ATTRIBUTE4
      , ATTRIBUTE5
      , ATTRIBUTE6
      , ATTRIBUTE7
      , ATTRIBUTE8
      , ATTRIBUTE9
      , ATTRIBUTE10
      , ATTRIBUTE11
      , ATTRIBUTE12
      , ATTRIBUTE13
      , ATTRIBUTE14
      , ATTRIBUTE15
      , DEFAULT_DEMAND_CLASS
      , ENCUMBRANCE_REVERSAL_FLAG
      , MAINTAIN_FIFO_QTY_STACK_TYPE
      , INVOICE_PRICE_VAR_ACCOUNT
      , AVERAGE_COST_VAR_ACCOUNT
      , SALES_ACCOUNT
      , EXPENSE_ACCOUNT
      , SERIAL_NUMBER_GENERATION
      , REQUEST_ID
      , PROGRAM_APPLICATION_ID
      , PROGRAM_ID
      , PROGRAM_UPDATE_DATE
      , GLOBAL_ATTRIBUTE_CATEGORY
      , GLOBAL_ATTRIBUTE1
      , GLOBAL_ATTRIBUTE2
      , GLOBAL_ATTRIBUTE3
      , GLOBAL_ATTRIBUTE4
      , GLOBAL_ATTRIBUTE5
      , GLOBAL_ATTRIBUTE6
      , GLOBAL_ATTRIBUTE7
      , GLOBAL_ATTRIBUTE8
      , GLOBAL_ATTRIBUTE9
      , GLOBAL_ATTRIBUTE10
      , GLOBAL_ATTRIBUTE11
      , GLOBAL_ATTRIBUTE12
      , GLOBAL_ATTRIBUTE13
      , GLOBAL_ATTRIBUTE14
      , GLOBAL_ATTRIBUTE15
      , GLOBAL_ATTRIBUTE16
      , GLOBAL_ATTRIBUTE17
      , GLOBAL_ATTRIBUTE18
      , GLOBAL_ATTRIBUTE19
      , GLOBAL_ATTRIBUTE20
      , MAT_OVHD_COST_TYPE_ID
      , PROJECT_REFERENCE_ENABLED
      , PM_COST_COLLECTION_ENABLED
      , PROJECT_CONTROL_LEVEL
      , AVG_RATES_COST_TYPE_ID
      , TXN_APPROVAL_TIMEOUT_PERIOD
      , MO_SOURCE_REQUIRED
      , MO_PICK_CONFIRM_REQUIRED
      , MO_APPROVAL_TIMEOUT_ACTION
      , BORRPAY_MATL_VAR_ACCOUNT
      , BORRPAY_MOH_VAR_ACCOUNT
      , BORRPAY_RES_VAR_ACCOUNT
      , BORRPAY_OSP_VAR_ACCOUNT
      , BORRPAY_OVH_VAR_ACCOUNT
      , PROCESS_ENABLED_FLAG
      , PROCESS_ORGN_CODE
      , WSM_ENABLED_FLAG
      , DEFAULT_COST_GROUP_ID
      , LPN_PREFIX
      , LPN_SUFFIX
      , LPN_STARTING_NUMBER
      , WMS_ENABLED_FLAG
      , PREGEN_PUTAWAY_TASKS_FLAG
      , REGENERATION_INTERVAL
      , TIMEZONE_ID
      , MAX_PICKS_BATCH
      , DEFAULT_WMS_PICKING_RULE_ID
      , DEFAULT_PUT_AWAY_RULE_ID
      , DEFAULT_TASK_ASSIGN_RULE_ID
      , DEFAULT_LABEL_COMP_RULE_ID
      , DEFAULT_CARTON_RULE_ID
      , DEFAULT_CYC_COUNT_HEADER_ID
      , CROSSDOCK_FLAG
      , CARTONIZATION_FLAG
      , COST_CUTOFF_DATE
      , ENABLE_COSTING_BY_CATEGORY
      , COST_GROUP_ACCOUNTING
      , ALLOCATE_SERIAL_FLAG
      , DEFAULT_PICK_TASK_TYPE_ID
      , DEFAULT_CC_TASK_TYPE_ID
      , DEFAULT_PUTAWAY_TASK_TYPE_ID
      , DEFAULT_REPL_TASK_TYPE_ID
      , EAM_ENABLED_FLAG
      , MAINT_ORGANIZATION_ID
      , PRIORITIZE_WIP_JOBS
      , DEFAULT_CROSSDOCK_SUBINVENTORY
      , SKIP_TASK_WAITING_MINUTES
      , QA_SKIPPING_INSP_FLAG
      , DEFAULT_CROSSDOCK_LOCATOR_ID
      , DEFAULT_MOXFER_TASK_TYPE_ID
      , DEFAULT_MOISSUE_TASK_TYPE_ID
      , DEFAULT_MATL_OVHD_COST_ID
      , DISTRIBUTED_ORGANIZATION_FLAG
      , CARRIER_MANIFESTING_FLAG
      , DISTRIBUTION_ACCOUNT_ID
      , DIRECT_SHIPPING_ALLOWED
      , DEFAULT_PICK_OP_PLAN_ID
      , MAX_CLUSTERS_ALLOWED
      , CONSIGNED_FLAG
      , CARTONIZE_SALES_ORDERS
      , CARTONIZE_MANUFACTURING
      , DEFER_LOGICAL_TRANSACTIONS
      , WIP_OVERPICK_ENABLED
      , OVPK_TRANSFER_ORDERS_ENABLED
      , TOTAL_LPN_LENGTH
      , UCC_128_SUFFIX_FLAG
      , WCS_ENABLED
      , AUTO_DEL_ALLOC_FLAG
      , RFID_VERIF_PCNT_THRESHOLD
      , OPSM_ENABLED_FLAG
      , ALLOW_DIFFERENT_STATUS
      , CHILD_LOT_ALPHA_PREFIX
      , CHILD_LOT_NUMBER_LENGTH
      , CHILD_LOT_VALIDATION_FLAG
      , CHILD_LOT_ZERO_PADDING_FLAG
      , COPY_LOT_ATTRIBUTE_FLAG
      , CREATE_LOT_UOM_CONVERSION
      , GENEALOGY_FORMULA_SECURITY
      , PARENT_CHILD_GENERATION_FLAG
      , RULES_OVERRIDE_LOT_RESERVATION
      , YARD_MANAGEMENT_ENABLED_FLAG
      , TRADING_PARTNER_ORG_FLAG
      , DEFERRED_COGS_ACCOUNT
      , DEFAULT_CROSSDOCK_CRITERIA_ID
      , ENFORCE_LOCATOR_ALIS_UNQ_FLAG
      , EPC_GENERATION_ENABLED_FLAG
      , COMPANY_PREFIX
      , COMPANY_PREFIX_INDEX
      , COMMERCIAL_GOVT_ENTITY_NUMBER
      , LABOR_MANAGEMENT_ENABLED_FLAG
      , DEFAULT_STATUS_ID
      , LCM_ENABLED_FLAG
      , LCM_VAR_ACCOUNT
      , ALLOCATE_LOT_FLAG
      , CAT_WT_ACCOUNT
      , YARD_ORG_ID
      , YMS_COSTING_ENABLED
      , YMS_DEFAULT_SUBINV
      , YMS_DEFAULT_LOCATOR
      , DAILY_CAL_START_TIME
      , DAILY_CAL_END_TIME
      , TRADING_PARTNER_ORG_TYPE
      , DISPATCH_INBOUND_TASK
      , ENABLE_EKANBAN
      , PICK_VERIFY_SO_ENABLED
      , PICK_VERIFY_MO_ENABLED
      , PICK_VERIFY_CATEGORY_SET_ID
      , PICK_VERIFY_WT_TOLERANCE_POS
      , PICK_VERIFY_WT_TOLERANCE_NEG
      , CC_WORKFLOW_ENABLED_FLAG
      , CC_APPROVAL_TIMEOUT_PERIOD
      , CC_APPROVAL_TIMEOUT_ACTION
      , _FIVETRAN_DELETED
      , _FIVETRAN_ID
      , _FIVETRAN_SYNCED
      , PSA_DELETE_IND
      , PSA_LOAD_DTS
      , PSA_RECORD_SOURCE
      , CONVERT_TIMEZONE('UTC', _FIVETRAN_SYNCED )                   as                                           LOAD_DTS
    FROM SRC_S
)

, LOGIC_A as (
    SELECT
        REC_SRC
      , BKCC
    FROM SRC_A
)
---- RENAME LAYER ----

, RENAME_S as (
    SELECT
        PLANT_BK
      , ORGANIZATION_CODE
      , ORGANIZATION_ID
      , LAST_UPDATE_DATE
      , LAST_UPDATED_BY
      , CREATION_DATE
      , CREATED_BY
      , LAST_UPDATE_LOGIN
      , MASTER_ORGANIZATION_ID
      , PRIMARY_COST_METHOD
      , COST_ORGANIZATION_ID
      , DEFAULT_MATERIAL_COST_ID
      , CALENDAR_EXCEPTION_SET_ID
      , CALENDAR_CODE
      , GENERAL_LEDGER_UPDATE_CODE
      , DEFAULT_ATP_RULE_ID
      , DEFAULT_PICKING_RULE_ID
      , DEFAULT_LOCATOR_ORDER_VALUE
      , DEFAULT_SUBINV_ORDER_VALUE
      , NEGATIVE_INV_RECEIPT_CODE
      , STOCK_LOCATOR_CONTROL_CODE
      , MATERIAL_ACCOUNT
      , MATERIAL_OVERHEAD_ACCOUNT
      , MATL_OVHD_ABSORPTION_ACCT
      , RESOURCE_ACCOUNT
      , PURCHASE_PRICE_VAR_ACCOUNT
      , AP_ACCRUAL_ACCOUNT
      , OVERHEAD_ACCOUNT
      , OUTSIDE_PROCESSING_ACCOUNT
      , INTRANSIT_INV_ACCOUNT
      , INTERORG_RECEIVABLES_ACCOUNT
      , INTERORG_PRICE_VAR_ACCOUNT
      , INTERORG_PAYABLES_ACCOUNT
      , COST_OF_SALES_ACCOUNT
      , ENCUMBRANCE_ACCOUNT
      , PROJECT_COST_ACCOUNT
      , INTERORG_TRANSFER_CR_ACCOUNT
      , MATL_INTERORG_TRANSFER_CODE
      , INTERORG_TRNSFR_CHARGE_PERCENT
      , SOURCE_ORGANIZATION_ID
      , SOURCE_SUBINVENTORY
      , SOURCE_TYPE
      , ORG_MAX_WEIGHT
      , ORG_MAX_WEIGHT_UOM_CODE
      , ORG_MAX_VOLUME
      , ORG_MAX_VOLUME_UOM_CODE
      , SERIAL_NUMBER_TYPE
      , AUTO_SERIAL_ALPHA_PREFIX
      , START_AUTO_SERIAL_NUMBER
      , AUTO_LOT_ALPHA_PREFIX
      , LOT_NUMBER_UNIQUENESS
      , LOT_NUMBER_GENERATION
      , LOT_NUMBER_ZERO_PADDING
      , LOT_NUMBER_LENGTH
      , STARTING_REVISION
      , ATTRIBUTE_CATEGORY
      , ATTRIBUTE1
      , ATTRIBUTE2
      , ATTRIBUTE3
      , ATTRIBUTE4
      , ATTRIBUTE5
      , ATTRIBUTE6
      , ATTRIBUTE7
      , ATTRIBUTE8
      , ATTRIBUTE9
      , ATTRIBUTE10
      , ATTRIBUTE11
      , ATTRIBUTE12
      , ATTRIBUTE13
      , ATTRIBUTE14
      , ATTRIBUTE15
      , DEFAULT_DEMAND_CLASS
      , ENCUMBRANCE_REVERSAL_FLAG
      , MAINTAIN_FIFO_QTY_STACK_TYPE
      , INVOICE_PRICE_VAR_ACCOUNT
      , AVERAGE_COST_VAR_ACCOUNT
      , SALES_ACCOUNT
      , EXPENSE_ACCOUNT
      , SERIAL_NUMBER_GENERATION
      , REQUEST_ID
      , PROGRAM_APPLICATION_ID
      , PROGRAM_ID
      , PROGRAM_UPDATE_DATE
      , GLOBAL_ATTRIBUTE_CATEGORY
      , GLOBAL_ATTRIBUTE1
      , GLOBAL_ATTRIBUTE2
      , GLOBAL_ATTRIBUTE3
      , GLOBAL_ATTRIBUTE4
      , GLOBAL_ATTRIBUTE5
      , GLOBAL_ATTRIBUTE6
      , GLOBAL_ATTRIBUTE7
      , GLOBAL_ATTRIBUTE8
      , GLOBAL_ATTRIBUTE9
      , GLOBAL_ATTRIBUTE10
      , GLOBAL_ATTRIBUTE11
      , GLOBAL_ATTRIBUTE12
      , GLOBAL_ATTRIBUTE13
      , GLOBAL_ATTRIBUTE14
      , GLOBAL_ATTRIBUTE15
      , GLOBAL_ATTRIBUTE16
      , GLOBAL_ATTRIBUTE17
      , GLOBAL_ATTRIBUTE18
      , GLOBAL_ATTRIBUTE19
      , GLOBAL_ATTRIBUTE20
      , MAT_OVHD_COST_TYPE_ID
      , PROJECT_REFERENCE_ENABLED
      , PM_COST_COLLECTION_ENABLED
      , PROJECT_CONTROL_LEVEL
      , AVG_RATES_COST_TYPE_ID
      , TXN_APPROVAL_TIMEOUT_PERIOD
      , MO_SOURCE_REQUIRED
      , MO_PICK_CONFIRM_REQUIRED
      , MO_APPROVAL_TIMEOUT_ACTION
      , BORRPAY_MATL_VAR_ACCOUNT
      , BORRPAY_MOH_VAR_ACCOUNT
      , BORRPAY_RES_VAR_ACCOUNT
      , BORRPAY_OSP_VAR_ACCOUNT
      , BORRPAY_OVH_VAR_ACCOUNT
      , PROCESS_ENABLED_FLAG
      , PROCESS_ORGN_CODE
      , WSM_ENABLED_FLAG
      , DEFAULT_COST_GROUP_ID
      , LPN_PREFIX
      , LPN_SUFFIX
      , LPN_STARTING_NUMBER
      , WMS_ENABLED_FLAG
      , PREGEN_PUTAWAY_TASKS_FLAG
      , REGENERATION_INTERVAL
      , TIMEZONE_ID
      , MAX_PICKS_BATCH
      , DEFAULT_WMS_PICKING_RULE_ID
      , DEFAULT_PUT_AWAY_RULE_ID
      , DEFAULT_TASK_ASSIGN_RULE_ID
      , DEFAULT_LABEL_COMP_RULE_ID
      , DEFAULT_CARTON_RULE_ID
      , DEFAULT_CYC_COUNT_HEADER_ID
      , CROSSDOCK_FLAG
      , CARTONIZATION_FLAG
      , COST_CUTOFF_DATE
      , ENABLE_COSTING_BY_CATEGORY
      , COST_GROUP_ACCOUNTING
      , ALLOCATE_SERIAL_FLAG
      , DEFAULT_PICK_TASK_TYPE_ID
      , DEFAULT_CC_TASK_TYPE_ID
      , DEFAULT_PUTAWAY_TASK_TYPE_ID
      , DEFAULT_REPL_TASK_TYPE_ID
      , EAM_ENABLED_FLAG
      , MAINT_ORGANIZATION_ID
      , PRIORITIZE_WIP_JOBS
      , DEFAULT_CROSSDOCK_SUBINVENTORY
      , SKIP_TASK_WAITING_MINUTES
      , QA_SKIPPING_INSP_FLAG
      , DEFAULT_CROSSDOCK_LOCATOR_ID
      , DEFAULT_MOXFER_TASK_TYPE_ID
      , DEFAULT_MOISSUE_TASK_TYPE_ID
      , DEFAULT_MATL_OVHD_COST_ID
      , DISTRIBUTED_ORGANIZATION_FLAG
      , CARRIER_MANIFESTING_FLAG
      , DISTRIBUTION_ACCOUNT_ID
      , DIRECT_SHIPPING_ALLOWED
      , DEFAULT_PICK_OP_PLAN_ID
      , MAX_CLUSTERS_ALLOWED
      , CONSIGNED_FLAG
      , CARTONIZE_SALES_ORDERS
      , CARTONIZE_MANUFACTURING
      , DEFER_LOGICAL_TRANSACTIONS
      , WIP_OVERPICK_ENABLED
      , OVPK_TRANSFER_ORDERS_ENABLED
      , TOTAL_LPN_LENGTH
      , UCC_128_SUFFIX_FLAG
      , WCS_ENABLED
      , AUTO_DEL_ALLOC_FLAG
      , RFID_VERIF_PCNT_THRESHOLD
      , OPSM_ENABLED_FLAG
      , ALLOW_DIFFERENT_STATUS
      , CHILD_LOT_ALPHA_PREFIX
      , CHILD_LOT_NUMBER_LENGTH
      , CHILD_LOT_VALIDATION_FLAG
      , CHILD_LOT_ZERO_PADDING_FLAG
      , COPY_LOT_ATTRIBUTE_FLAG
      , CREATE_LOT_UOM_CONVERSION
      , GENEALOGY_FORMULA_SECURITY
      , PARENT_CHILD_GENERATION_FLAG
      , RULES_OVERRIDE_LOT_RESERVATION
      , YARD_MANAGEMENT_ENABLED_FLAG
      , TRADING_PARTNER_ORG_FLAG
      , DEFERRED_COGS_ACCOUNT
      , DEFAULT_CROSSDOCK_CRITERIA_ID
      , ENFORCE_LOCATOR_ALIS_UNQ_FLAG
      , EPC_GENERATION_ENABLED_FLAG
      , COMPANY_PREFIX
      , COMPANY_PREFIX_INDEX
      , COMMERCIAL_GOVT_ENTITY_NUMBER
      , LABOR_MANAGEMENT_ENABLED_FLAG
      , DEFAULT_STATUS_ID
      , LCM_ENABLED_FLAG
      , LCM_VAR_ACCOUNT
      , ALLOCATE_LOT_FLAG
      , CAT_WT_ACCOUNT
      , YARD_ORG_ID
      , YMS_COSTING_ENABLED
      , YMS_DEFAULT_SUBINV
      , YMS_DEFAULT_LOCATOR
      , DAILY_CAL_START_TIME
      , DAILY_CAL_END_TIME
      , TRADING_PARTNER_ORG_TYPE
      , DISPATCH_INBOUND_TASK
      , ENABLE_EKANBAN
      , PICK_VERIFY_SO_ENABLED
      , PICK_VERIFY_MO_ENABLED
      , PICK_VERIFY_CATEGORY_SET_ID
      , PICK_VERIFY_WT_TOLERANCE_POS
      , PICK_VERIFY_WT_TOLERANCE_NEG
      , CC_WORKFLOW_ENABLED_FLAG
      , CC_APPROVAL_TIMEOUT_PERIOD
      , CC_APPROVAL_TIMEOUT_ACTION
      , _FIVETRAN_DELETED
      , _FIVETRAN_ID
      , _FIVETRAN_SYNCED
      , PSA_DELETE_IND
      , PSA_LOAD_DTS
      , PSA_RECORD_SOURCE
      , LOAD_DTS
    FROM LOGIC_S
)

, RENAME_A as (
    SELECT
        REC_SRC
      , BKCC
    FROM LOGIC_A
)
---- FILTER LAYER ----

, FILTER_S as (
    SELECT *
    FROM RENAME_S
)

, FILTER_A as (
    SELECT *
    FROM RENAME_A
    WHERE rec_src = 'USWIOC.ORCL.EBSEMTK.MTL_PARAMETERS'
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM FILTER_S
    INNER JOIN FILTER_A
        ON '1' = '1'
)

---- FINAL LAYER ----
SELECT
          PLANT_BK
        , ORGANIZATION_CODE
        , ORGANIZATION_ID
        , LAST_UPDATE_DATE
        , LAST_UPDATED_BY
        , CREATION_DATE
        , CREATED_BY
        , LAST_UPDATE_LOGIN
        , MASTER_ORGANIZATION_ID
        , PRIMARY_COST_METHOD
        , COST_ORGANIZATION_ID
        , DEFAULT_MATERIAL_COST_ID
        , CALENDAR_EXCEPTION_SET_ID
        , CALENDAR_CODE
        , GENERAL_LEDGER_UPDATE_CODE
        , DEFAULT_ATP_RULE_ID
        , DEFAULT_PICKING_RULE_ID
        , DEFAULT_LOCATOR_ORDER_VALUE
        , DEFAULT_SUBINV_ORDER_VALUE
        , NEGATIVE_INV_RECEIPT_CODE
        , STOCK_LOCATOR_CONTROL_CODE
        , MATERIAL_ACCOUNT
        , MATERIAL_OVERHEAD_ACCOUNT
        , MATL_OVHD_ABSORPTION_ACCT
        , RESOURCE_ACCOUNT
        , PURCHASE_PRICE_VAR_ACCOUNT
        , AP_ACCRUAL_ACCOUNT
        , OVERHEAD_ACCOUNT
        , OUTSIDE_PROCESSING_ACCOUNT
        , INTRANSIT_INV_ACCOUNT
        , INTERORG_RECEIVABLES_ACCOUNT
        , INTERORG_PRICE_VAR_ACCOUNT
        , INTERORG_PAYABLES_ACCOUNT
        , COST_OF_SALES_ACCOUNT
        , ENCUMBRANCE_ACCOUNT
        , PROJECT_COST_ACCOUNT
        , INTERORG_TRANSFER_CR_ACCOUNT
        , MATL_INTERORG_TRANSFER_CODE
        , INTERORG_TRNSFR_CHARGE_PERCENT
        , SOURCE_ORGANIZATION_ID
        , SOURCE_SUBINVENTORY
        , SOURCE_TYPE
        , ORG_MAX_WEIGHT
        , ORG_MAX_WEIGHT_UOM_CODE
        , ORG_MAX_VOLUME
        , ORG_MAX_VOLUME_UOM_CODE
        , SERIAL_NUMBER_TYPE
        , AUTO_SERIAL_ALPHA_PREFIX
        , START_AUTO_SERIAL_NUMBER
        , AUTO_LOT_ALPHA_PREFIX
        , LOT_NUMBER_UNIQUENESS
        , LOT_NUMBER_GENERATION
        , LOT_NUMBER_ZERO_PADDING
        , LOT_NUMBER_LENGTH
        , STARTING_REVISION
        , ATTRIBUTE_CATEGORY
        , ATTRIBUTE1
        , ATTRIBUTE2
        , ATTRIBUTE3
        , ATTRIBUTE4
        , ATTRIBUTE5
        , ATTRIBUTE6
        , ATTRIBUTE7
        , ATTRIBUTE8
        , ATTRIBUTE9
        , ATTRIBUTE10
        , ATTRIBUTE11
        , ATTRIBUTE12
        , ATTRIBUTE13
        , ATTRIBUTE14
        , ATTRIBUTE15
        , DEFAULT_DEMAND_CLASS
        , ENCUMBRANCE_REVERSAL_FLAG
        , MAINTAIN_FIFO_QTY_STACK_TYPE
        , INVOICE_PRICE_VAR_ACCOUNT
        , AVERAGE_COST_VAR_ACCOUNT
        , SALES_ACCOUNT
        , EXPENSE_ACCOUNT
        , SERIAL_NUMBER_GENERATION
        , REQUEST_ID
        , PROGRAM_APPLICATION_ID
        , PROGRAM_ID
        , PROGRAM_UPDATE_DATE
        , GLOBAL_ATTRIBUTE_CATEGORY
        , GLOBAL_ATTRIBUTE1
        , GLOBAL_ATTRIBUTE2
        , GLOBAL_ATTRIBUTE3
        , GLOBAL_ATTRIBUTE4
        , GLOBAL_ATTRIBUTE5
        , GLOBAL_ATTRIBUTE6
        , GLOBAL_ATTRIBUTE7
        , GLOBAL_ATTRIBUTE8
        , GLOBAL_ATTRIBUTE9
        , GLOBAL_ATTRIBUTE10
        , GLOBAL_ATTRIBUTE11
        , GLOBAL_ATTRIBUTE12
        , GLOBAL_ATTRIBUTE13
        , GLOBAL_ATTRIBUTE14
        , GLOBAL_ATTRIBUTE15
        , GLOBAL_ATTRIBUTE16
        , GLOBAL_ATTRIBUTE17
        , GLOBAL_ATTRIBUTE18
        , GLOBAL_ATTRIBUTE19
        , GLOBAL_ATTRIBUTE20
        , MAT_OVHD_COST_TYPE_ID
        , PROJECT_REFERENCE_ENABLED
        , PM_COST_COLLECTION_ENABLED
        , PROJECT_CONTROL_LEVEL
        , AVG_RATES_COST_TYPE_ID
        , TXN_APPROVAL_TIMEOUT_PERIOD
        , MO_SOURCE_REQUIRED
        , MO_PICK_CONFIRM_REQUIRED
        , MO_APPROVAL_TIMEOUT_ACTION
        , BORRPAY_MATL_VAR_ACCOUNT
        , BORRPAY_MOH_VAR_ACCOUNT
        , BORRPAY_RES_VAR_ACCOUNT
        , BORRPAY_OSP_VAR_ACCOUNT
        , BORRPAY_OVH_VAR_ACCOUNT
        , PROCESS_ENABLED_FLAG
        , PROCESS_ORGN_CODE
        , WSM_ENABLED_FLAG
        , DEFAULT_COST_GROUP_ID
        , LPN_PREFIX
        , LPN_SUFFIX
        , LPN_STARTING_NUMBER
        , WMS_ENABLED_FLAG
        , PREGEN_PUTAWAY_TASKS_FLAG
        , REGENERATION_INTERVAL
        , TIMEZONE_ID
        , MAX_PICKS_BATCH
        , DEFAULT_WMS_PICKING_RULE_ID
        , DEFAULT_PUT_AWAY_RULE_ID
        , DEFAULT_TASK_ASSIGN_RULE_ID
        , DEFAULT_LABEL_COMP_RULE_ID
        , DEFAULT_CARTON_RULE_ID
        , DEFAULT_CYC_COUNT_HEADER_ID
        , CROSSDOCK_FLAG
        , CARTONIZATION_FLAG
        , COST_CUTOFF_DATE
        , ENABLE_COSTING_BY_CATEGORY
        , COST_GROUP_ACCOUNTING
        , ALLOCATE_SERIAL_FLAG
        , DEFAULT_PICK_TASK_TYPE_ID
        , DEFAULT_CC_TASK_TYPE_ID
        , DEFAULT_PUTAWAY_TASK_TYPE_ID
        , DEFAULT_REPL_TASK_TYPE_ID
        , EAM_ENABLED_FLAG
        , MAINT_ORGANIZATION_ID
        , PRIORITIZE_WIP_JOBS
        , DEFAULT_CROSSDOCK_SUBINVENTORY
        , SKIP_TASK_WAITING_MINUTES
        , QA_SKIPPING_INSP_FLAG
        , DEFAULT_CROSSDOCK_LOCATOR_ID
        , DEFAULT_MOXFER_TASK_TYPE_ID
        , DEFAULT_MOISSUE_TASK_TYPE_ID
        , DEFAULT_MATL_OVHD_COST_ID
        , DISTRIBUTED_ORGANIZATION_FLAG
        , CARRIER_MANIFESTING_FLAG
        , DISTRIBUTION_ACCOUNT_ID
        , DIRECT_SHIPPING_ALLOWED
        , DEFAULT_PICK_OP_PLAN_ID
        , MAX_CLUSTERS_ALLOWED
        , CONSIGNED_FLAG
        , CARTONIZE_SALES_ORDERS
        , CARTONIZE_MANUFACTURING
        , DEFER_LOGICAL_TRANSACTIONS
        , WIP_OVERPICK_ENABLED
        , OVPK_TRANSFER_ORDERS_ENABLED
        , TOTAL_LPN_LENGTH
        , UCC_128_SUFFIX_FLAG
        , WCS_ENABLED
        , AUTO_DEL_ALLOC_FLAG
        , RFID_VERIF_PCNT_THRESHOLD
        , OPSM_ENABLED_FLAG
        , ALLOW_DIFFERENT_STATUS
        , CHILD_LOT_ALPHA_PREFIX
        , CHILD_LOT_NUMBER_LENGTH
        , CHILD_LOT_VALIDATION_FLAG
        , CHILD_LOT_ZERO_PADDING_FLAG
        , COPY_LOT_ATTRIBUTE_FLAG
        , CREATE_LOT_UOM_CONVERSION
        , GENEALOGY_FORMULA_SECURITY
        , PARENT_CHILD_GENERATION_FLAG
        , RULES_OVERRIDE_LOT_RESERVATION
        , YARD_MANAGEMENT_ENABLED_FLAG
        , TRADING_PARTNER_ORG_FLAG
        , DEFERRED_COGS_ACCOUNT
        , DEFAULT_CROSSDOCK_CRITERIA_ID
        , ENFORCE_LOCATOR_ALIS_UNQ_FLAG
        , EPC_GENERATION_ENABLED_FLAG
        , COMPANY_PREFIX
        , COMPANY_PREFIX_INDEX
        , COMMERCIAL_GOVT_ENTITY_NUMBER
        , LABOR_MANAGEMENT_ENABLED_FLAG
        , DEFAULT_STATUS_ID
        , LCM_ENABLED_FLAG
        , LCM_VAR_ACCOUNT
        , ALLOCATE_LOT_FLAG
        , CAT_WT_ACCOUNT
        , YARD_ORG_ID
        , YMS_COSTING_ENABLED
        , YMS_DEFAULT_SUBINV
        , YMS_DEFAULT_LOCATOR
        , DAILY_CAL_START_TIME
        , DAILY_CAL_END_TIME
        , TRADING_PARTNER_ORG_TYPE
        , DISPATCH_INBOUND_TASK
        , ENABLE_EKANBAN
        , PICK_VERIFY_SO_ENABLED
        , PICK_VERIFY_MO_ENABLED
        , PICK_VERIFY_CATEGORY_SET_ID
        , PICK_VERIFY_WT_TOLERANCE_POS
        , PICK_VERIFY_WT_TOLERANCE_NEG
        , CC_WORKFLOW_ENABLED_FLAG
        , CC_APPROVAL_TIMEOUT_PERIOD
        , CC_APPROVAL_TIMEOUT_ACTION
        , _FIVETRAN_DELETED
        , _FIVETRAN_ID
        , _FIVETRAN_SYNCED
        , PSA_DELETE_IND
        , PSA_LOAD_DTS
        , PSA_RECORD_SOURCE
        , LOAD_DTS
        , REC_SRC
        , BKCC
        , MD5_BINARY(UPPER(CONCAT_WS('||',
          COALESCE(NULLIF(TRIM(CAST(PLANT_BK as VARCHAR)),''), '^^')
        , COALESCE(NULLIF(TRIM(CAST(BKCC as VARCHAR)),''), '^^')
        ))) as PLANT_HK
        , MD5_BINARY(UPPER(NULLIF(CONCAT(
              IFNULL(TRIM(ORGANIZATION_ID::text), '^^') 
            , '||', IFNULL(TRIM(LAST_UPDATE_DATE::text), '^^') 
            , '||', IFNULL(TRIM(LAST_UPDATED_BY::text), '^^') 
            , '||', IFNULL(TRIM(CREATION_DATE::text), '^^') 
            , '||', IFNULL(TRIM(CREATED_BY::text), '^^') 
            , '||', IFNULL(TRIM(LAST_UPDATE_LOGIN::text), '^^') 
            , '||', IFNULL(TRIM(MASTER_ORGANIZATION_ID::text), '^^') 
            , '||', IFNULL(TRIM(PRIMARY_COST_METHOD::text), '^^') 
            , '||', IFNULL(TRIM(COST_ORGANIZATION_ID::text), '^^') 
            , '||', IFNULL(TRIM(DEFAULT_MATERIAL_COST_ID::text), '^^') 
            , '||', IFNULL(TRIM(CALENDAR_EXCEPTION_SET_ID::text), '^^') 
            , '||', IFNULL(TRIM(CALENDAR_CODE::text), '^^') 
            , '||', IFNULL(TRIM(GENERAL_LEDGER_UPDATE_CODE::text), '^^') 
            , '||', IFNULL(TRIM(DEFAULT_ATP_RULE_ID::text), '^^') 
            , '||', IFNULL(TRIM(DEFAULT_PICKING_RULE_ID::text), '^^') 
            , '||', IFNULL(TRIM(DEFAULT_LOCATOR_ORDER_VALUE::text), '^^') 
            , '||', IFNULL(TRIM(DEFAULT_SUBINV_ORDER_VALUE::text), '^^') 
            , '||', IFNULL(TRIM(NEGATIVE_INV_RECEIPT_CODE::text), '^^') 
            , '||', IFNULL(TRIM(STOCK_LOCATOR_CONTROL_CODE::text), '^^') 
            , '||', IFNULL(TRIM(MATERIAL_ACCOUNT::text), '^^') 
            , '||', IFNULL(TRIM(MATERIAL_OVERHEAD_ACCOUNT::text), '^^') 
            , '||', IFNULL(TRIM(MATL_OVHD_ABSORPTION_ACCT::text), '^^') 
            , '||', IFNULL(TRIM(RESOURCE_ACCOUNT::text), '^^') 
            , '||', IFNULL(TRIM(PURCHASE_PRICE_VAR_ACCOUNT::text), '^^') 
            , '||', IFNULL(TRIM(AP_ACCRUAL_ACCOUNT::text), '^^') 
            , '||', IFNULL(TRIM(OVERHEAD_ACCOUNT::text), '^^') 
            , '||', IFNULL(TRIM(OUTSIDE_PROCESSING_ACCOUNT::text), '^^') 
            , '||', IFNULL(TRIM(INTRANSIT_INV_ACCOUNT::text), '^^') 
            , '||', IFNULL(TRIM(INTERORG_RECEIVABLES_ACCOUNT::text), '^^') 
            , '||', IFNULL(TRIM(INTERORG_PRICE_VAR_ACCOUNT::text), '^^') 
            , '||', IFNULL(TRIM(INTERORG_PAYABLES_ACCOUNT::text), '^^') 
            , '||', IFNULL(TRIM(COST_OF_SALES_ACCOUNT::text), '^^') 
            , '||', IFNULL(TRIM(ENCUMBRANCE_ACCOUNT::text), '^^') 
            , '||', IFNULL(TRIM(PROJECT_COST_ACCOUNT::text), '^^') 
            , '||', IFNULL(TRIM(INTERORG_TRANSFER_CR_ACCOUNT::text), '^^') 
            , '||', IFNULL(TRIM(MATL_INTERORG_TRANSFER_CODE::text), '^^') 
            , '||', IFNULL(TRIM(INTERORG_TRNSFR_CHARGE_PERCENT::text), '^^') 
            , '||', IFNULL(TRIM(SOURCE_ORGANIZATION_ID::text), '^^') 
            , '||', IFNULL(TRIM(SOURCE_SUBINVENTORY::text), '^^') 
            , '||', IFNULL(TRIM(SOURCE_TYPE::text), '^^') 
            , '||', IFNULL(TRIM(ORG_MAX_WEIGHT::text), '^^') 
            , '||', IFNULL(TRIM(ORG_MAX_WEIGHT_UOM_CODE::text), '^^') 
            , '||', IFNULL(TRIM(ORG_MAX_VOLUME::text), '^^') 
            , '||', IFNULL(TRIM(ORG_MAX_VOLUME_UOM_CODE::text), '^^') 
            , '||', IFNULL(TRIM(SERIAL_NUMBER_TYPE::text), '^^') 
            , '||', IFNULL(TRIM(AUTO_SERIAL_ALPHA_PREFIX::text), '^^') 
            , '||', IFNULL(TRIM(START_AUTO_SERIAL_NUMBER::text), '^^') 
            , '||', IFNULL(TRIM(AUTO_LOT_ALPHA_PREFIX::text), '^^') 
            , '||', IFNULL(TRIM(LOT_NUMBER_UNIQUENESS::text), '^^') 
            , '||', IFNULL(TRIM(LOT_NUMBER_GENERATION::text), '^^') 
            , '||', IFNULL(TRIM(LOT_NUMBER_ZERO_PADDING::text), '^^') 
            , '||', IFNULL(TRIM(LOT_NUMBER_LENGTH::text), '^^') 
            , '||', IFNULL(TRIM(STARTING_REVISION::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE_CATEGORY::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE1::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE2::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE3::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE4::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE5::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE6::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE7::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE8::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE9::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE10::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE11::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE12::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE13::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE14::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE15::text), '^^') 
            , '||', IFNULL(TRIM(DEFAULT_DEMAND_CLASS::text), '^^') 
            , '||', IFNULL(TRIM(ENCUMBRANCE_REVERSAL_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(MAINTAIN_FIFO_QTY_STACK_TYPE::text), '^^') 
            , '||', IFNULL(TRIM(INVOICE_PRICE_VAR_ACCOUNT::text), '^^') 
            , '||', IFNULL(TRIM(AVERAGE_COST_VAR_ACCOUNT::text), '^^') 
            , '||', IFNULL(TRIM(SALES_ACCOUNT::text), '^^') 
            , '||', IFNULL(TRIM(EXPENSE_ACCOUNT::text), '^^') 
            , '||', IFNULL(TRIM(SERIAL_NUMBER_GENERATION::text), '^^') 
            , '||', IFNULL(TRIM(REQUEST_ID::text), '^^') 
            , '||', IFNULL(TRIM(PROGRAM_APPLICATION_ID::text), '^^') 
            , '||', IFNULL(TRIM(PROGRAM_ID::text), '^^') 
            , '||', IFNULL(TRIM(PROGRAM_UPDATE_DATE::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE_CATEGORY::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE1::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE2::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE3::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE4::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE5::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE6::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE7::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE8::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE9::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE10::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE11::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE12::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE13::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE14::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE15::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE16::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE17::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE18::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE19::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE20::text), '^^') 
            , '||', IFNULL(TRIM(MAT_OVHD_COST_TYPE_ID::text), '^^') 
            , '||', IFNULL(TRIM(PROJECT_REFERENCE_ENABLED::text), '^^') 
            , '||', IFNULL(TRIM(PM_COST_COLLECTION_ENABLED::text), '^^') 
            , '||', IFNULL(TRIM(PROJECT_CONTROL_LEVEL::text), '^^') 
            , '||', IFNULL(TRIM(AVG_RATES_COST_TYPE_ID::text), '^^') 
            , '||', IFNULL(TRIM(TXN_APPROVAL_TIMEOUT_PERIOD::text), '^^') 
            , '||', IFNULL(TRIM(MO_SOURCE_REQUIRED::text), '^^') 
            , '||', IFNULL(TRIM(MO_PICK_CONFIRM_REQUIRED::text), '^^') 
            , '||', IFNULL(TRIM(MO_APPROVAL_TIMEOUT_ACTION::text), '^^') 
            , '||', IFNULL(TRIM(BORRPAY_MATL_VAR_ACCOUNT::text), '^^') 
            , '||', IFNULL(TRIM(BORRPAY_MOH_VAR_ACCOUNT::text), '^^') 
            , '||', IFNULL(TRIM(BORRPAY_RES_VAR_ACCOUNT::text), '^^') 
            , '||', IFNULL(TRIM(BORRPAY_OSP_VAR_ACCOUNT::text), '^^') 
            , '||', IFNULL(TRIM(BORRPAY_OVH_VAR_ACCOUNT::text), '^^') 
            , '||', IFNULL(TRIM(PROCESS_ENABLED_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(PROCESS_ORGN_CODE::text), '^^') 
            , '||', IFNULL(TRIM(WSM_ENABLED_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(DEFAULT_COST_GROUP_ID::text), '^^') 
            , '||', IFNULL(TRIM(LPN_PREFIX::text), '^^') 
            , '||', IFNULL(TRIM(LPN_SUFFIX::text), '^^') 
            , '||', IFNULL(TRIM(LPN_STARTING_NUMBER::text), '^^') 
            , '||', IFNULL(TRIM(WMS_ENABLED_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(PREGEN_PUTAWAY_TASKS_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(REGENERATION_INTERVAL::text), '^^') 
            , '||', IFNULL(TRIM(TIMEZONE_ID::text), '^^') 
            , '||', IFNULL(TRIM(MAX_PICKS_BATCH::text), '^^') 
            , '||', IFNULL(TRIM(DEFAULT_WMS_PICKING_RULE_ID::text), '^^') 
            , '||', IFNULL(TRIM(DEFAULT_PUT_AWAY_RULE_ID::text), '^^') 
            , '||', IFNULL(TRIM(DEFAULT_TASK_ASSIGN_RULE_ID::text), '^^') 
            , '||', IFNULL(TRIM(DEFAULT_LABEL_COMP_RULE_ID::text), '^^') 
            , '||', IFNULL(TRIM(DEFAULT_CARTON_RULE_ID::text), '^^') 
            , '||', IFNULL(TRIM(DEFAULT_CYC_COUNT_HEADER_ID::text), '^^') 
            , '||', IFNULL(TRIM(CROSSDOCK_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(CARTONIZATION_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(COST_CUTOFF_DATE::text), '^^') 
            , '||', IFNULL(TRIM(ENABLE_COSTING_BY_CATEGORY::text), '^^') 
            , '||', IFNULL(TRIM(COST_GROUP_ACCOUNTING::text), '^^') 
            , '||', IFNULL(TRIM(ALLOCATE_SERIAL_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(DEFAULT_PICK_TASK_TYPE_ID::text), '^^') 
            , '||', IFNULL(TRIM(DEFAULT_CC_TASK_TYPE_ID::text), '^^') 
            , '||', IFNULL(TRIM(DEFAULT_PUTAWAY_TASK_TYPE_ID::text), '^^') 
            , '||', IFNULL(TRIM(DEFAULT_REPL_TASK_TYPE_ID::text), '^^') 
            , '||', IFNULL(TRIM(EAM_ENABLED_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(MAINT_ORGANIZATION_ID::text), '^^') 
            , '||', IFNULL(TRIM(PRIORITIZE_WIP_JOBS::text), '^^') 
            , '||', IFNULL(TRIM(DEFAULT_CROSSDOCK_SUBINVENTORY::text), '^^') 
            , '||', IFNULL(TRIM(SKIP_TASK_WAITING_MINUTES::text), '^^') 
            , '||', IFNULL(TRIM(QA_SKIPPING_INSP_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(DEFAULT_CROSSDOCK_LOCATOR_ID::text), '^^') 
            , '||', IFNULL(TRIM(DEFAULT_MOXFER_TASK_TYPE_ID::text), '^^') 
            , '||', IFNULL(TRIM(DEFAULT_MOISSUE_TASK_TYPE_ID::text), '^^') 
            , '||', IFNULL(TRIM(DEFAULT_MATL_OVHD_COST_ID::text), '^^') 
            , '||', IFNULL(TRIM(DISTRIBUTED_ORGANIZATION_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(CARRIER_MANIFESTING_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(DISTRIBUTION_ACCOUNT_ID::text), '^^') 
            , '||', IFNULL(TRIM(DIRECT_SHIPPING_ALLOWED::text), '^^') 
            , '||', IFNULL(TRIM(DEFAULT_PICK_OP_PLAN_ID::text), '^^') 
            , '||', IFNULL(TRIM(MAX_CLUSTERS_ALLOWED::text), '^^') 
            , '||', IFNULL(TRIM(CONSIGNED_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(CARTONIZE_SALES_ORDERS::text), '^^') 
            , '||', IFNULL(TRIM(CARTONIZE_MANUFACTURING::text), '^^') 
            , '||', IFNULL(TRIM(DEFER_LOGICAL_TRANSACTIONS::text), '^^') 
            , '||', IFNULL(TRIM(WIP_OVERPICK_ENABLED::text), '^^') 
            , '||', IFNULL(TRIM(OVPK_TRANSFER_ORDERS_ENABLED::text), '^^') 
            , '||', IFNULL(TRIM(TOTAL_LPN_LENGTH::text), '^^') 
            , '||', IFNULL(TRIM(UCC_128_SUFFIX_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(WCS_ENABLED::text), '^^') 
            , '||', IFNULL(TRIM(AUTO_DEL_ALLOC_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(RFID_VERIF_PCNT_THRESHOLD::text), '^^') 
            , '||', IFNULL(TRIM(OPSM_ENABLED_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(ALLOW_DIFFERENT_STATUS::text), '^^') 
            , '||', IFNULL(TRIM(CHILD_LOT_ALPHA_PREFIX::text), '^^') 
            , '||', IFNULL(TRIM(CHILD_LOT_NUMBER_LENGTH::text), '^^') 
            , '||', IFNULL(TRIM(CHILD_LOT_VALIDATION_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(CHILD_LOT_ZERO_PADDING_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(COPY_LOT_ATTRIBUTE_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(CREATE_LOT_UOM_CONVERSION::text), '^^') 
            , '||', IFNULL(TRIM(GENEALOGY_FORMULA_SECURITY::text), '^^') 
            , '||', IFNULL(TRIM(PARENT_CHILD_GENERATION_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(RULES_OVERRIDE_LOT_RESERVATION::text), '^^') 
            , '||', IFNULL(TRIM(YARD_MANAGEMENT_ENABLED_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(TRADING_PARTNER_ORG_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(DEFERRED_COGS_ACCOUNT::text), '^^') 
            , '||', IFNULL(TRIM(DEFAULT_CROSSDOCK_CRITERIA_ID::text), '^^') 
            , '||', IFNULL(TRIM(ENFORCE_LOCATOR_ALIS_UNQ_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(EPC_GENERATION_ENABLED_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(COMPANY_PREFIX::text), '^^') 
            , '||', IFNULL(TRIM(COMPANY_PREFIX_INDEX::text), '^^') 
            , '||', IFNULL(TRIM(COMMERCIAL_GOVT_ENTITY_NUMBER::text), '^^') 
            , '||', IFNULL(TRIM(LABOR_MANAGEMENT_ENABLED_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(DEFAULT_STATUS_ID::text), '^^') 
            , '||', IFNULL(TRIM(LCM_ENABLED_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(LCM_VAR_ACCOUNT::text), '^^') 
            , '||', IFNULL(TRIM(_FIVETRAN_DELETED::text), '^^') 
        ), '^^||^^')))  as HASHDIFF
FROM JOIN_RESULT
