---- SRC LAYER ----
WITH
SRC_S              as ( SELECT SEGMENT1, VENDOR_ID, LAST_UPDATE_DATE, LAST_UPDATED_BY, VENDOR_NAME, VENDOR_NAME_ALT, SUMMARY_FLAG, ENABLED_FLAG, SEGMENT2, SEGMENT3, SEGMENT4, SEGMENT5, LAST_UPDATE_LOGIN, CREATION_DATE, CREATED_BY, EMPLOYEE_ID, VENDOR_TYPE_LOOKUP_CODE, CUSTOMER_NUM, ONE_TIME_FLAG, PARENT_VENDOR_ID, MIN_ORDER_AMOUNT, SHIP_TO_LOCATION_ID, BILL_TO_LOCATION_ID, SHIP_VIA_LOOKUP_CODE, FREIGHT_TERMS_LOOKUP_CODE, FOB_LOOKUP_CODE, TERMS_ID, SET_OF_BOOKS_ID, CREDIT_STATUS_LOOKUP_CODE, CREDIT_LIMIT, ALWAYS_TAKE_DISC_FLAG, PAY_DATE_BASIS_LOOKUP_CODE, PAY_GROUP_LOOKUP_CODE, PAYMENT_PRIORITY, INVOICE_CURRENCY_CODE, PAYMENT_CURRENCY_CODE, INVOICE_AMOUNT_LIMIT, EXCHANGE_DATE_LOOKUP_CODE, HOLD_ALL_PAYMENTS_FLAG, HOLD_FUTURE_PAYMENTS_FLAG, HOLD_REASON, DISTRIBUTION_SET_ID, ACCTS_PAY_CODE_COMBINATION_ID, DISC_LOST_CODE_COMBINATION_ID, DISC_TAKEN_CODE_COMBINATION_ID, EXPENSE_CODE_COMBINATION_ID, PREPAY_CODE_COMBINATION_ID, NUM_1099, TYPE_1099, WITHHOLDING_STATUS_LOOKUP_CODE, WITHHOLDING_START_DATE, ORGANIZATION_TYPE_LOOKUP_CODE, VAT_CODE, START_DATE_ACTIVE, END_DATE_ACTIVE, MINORITY_GROUP_LOOKUP_CODE, PAYMENT_METHOD_LOOKUP_CODE, BANK_ACCOUNT_NAME, BANK_ACCOUNT_NUM, BANK_NUM, BANK_ACCOUNT_TYPE, WOMEN_OWNED_FLAG, SMALL_BUSINESS_FLAG, STANDARD_INDUSTRY_CLASS, HOLD_FLAG, PURCHASING_HOLD_REASON, HOLD_BY, HOLD_DATE, TERMS_DATE_BASIS, PRICE_TOLERANCE, INSPECTION_REQUIRED_FLAG, RECEIPT_REQUIRED_FLAG, QTY_RCV_TOLERANCE, QTY_RCV_EXCEPTION_CODE, ENFORCE_SHIP_TO_LOCATION_CODE, DAYS_EARLY_RECEIPT_ALLOWED, DAYS_LATE_RECEIPT_ALLOWED, RECEIPT_DAYS_EXCEPTION_CODE, RECEIVING_ROUTING_ID, ALLOW_SUBSTITUTE_RECEIPTS_FLAG, ALLOW_UNORDERED_RECEIPTS_FLAG, HOLD_UNMATCHED_INVOICES_FLAG, EXCLUSIVE_PAYMENT_FLAG, AP_TAX_ROUNDING_RULE, AUTO_TAX_CALC_FLAG, AUTO_TAX_CALC_OVERRIDE, AMOUNT_INCLUDES_TAX_FLAG, TAX_VERIFICATION_DATE, NAME_CONTROL, STATE_REPORTABLE_FLAG, FEDERAL_REPORTABLE_FLAG, ATTRIBUTE_CATEGORY, ATTRIBUTE1, ATTRIBUTE2, ATTRIBUTE3, ATTRIBUTE4, ATTRIBUTE5, ATTRIBUTE6, ATTRIBUTE7, ATTRIBUTE8, ATTRIBUTE9, ATTRIBUTE10, ATTRIBUTE11, ATTRIBUTE12, ATTRIBUTE13, ATTRIBUTE14, ATTRIBUTE15, REQUEST_ID, PROGRAM_APPLICATION_ID, PROGRAM_ID, PROGRAM_UPDATE_DATE, OFFSET_VAT_CODE, AUTO_CALCULATE_INTEREST_FLAG, VALIDATION_NUMBER, EXCLUDE_FREIGHT_FROM_DISCOUNT, TAX_REPORTING_NAME, CHECK_DIGITS, BANK_NUMBER, ALLOW_AWT_FLAG, AWT_GROUP_ID, GLOBAL_ATTRIBUTE1, GLOBAL_ATTRIBUTE2, GLOBAL_ATTRIBUTE3, GLOBAL_ATTRIBUTE4, GLOBAL_ATTRIBUTE5, GLOBAL_ATTRIBUTE6, GLOBAL_ATTRIBUTE7, GLOBAL_ATTRIBUTE8, GLOBAL_ATTRIBUTE9, GLOBAL_ATTRIBUTE10, GLOBAL_ATTRIBUTE11, GLOBAL_ATTRIBUTE12, GLOBAL_ATTRIBUTE13, GLOBAL_ATTRIBUTE14, GLOBAL_ATTRIBUTE15, GLOBAL_ATTRIBUTE16, GLOBAL_ATTRIBUTE17, GLOBAL_ATTRIBUTE18, GLOBAL_ATTRIBUTE19, GLOBAL_ATTRIBUTE20, GLOBAL_ATTRIBUTE_CATEGORY, EDI_TRANSACTION_HANDLING, EDI_PAYMENT_METHOD, EDI_PAYMENT_FORMAT, EDI_REMITTANCE_METHOD, EDI_REMITTANCE_INSTRUCTION, BANK_CHARGE_BEARER, BANK_BRANCH_TYPE, MATCH_OPTION, FUTURE_DATED_PAYMENT_CCID, CREATE_DEBIT_MEMO_FLAG, OFFSET_TAX_FLAG, PARTY_ID, PARENT_PARTY_ID, NI_NUMBER, TCA_SYNC_NUM_1099, TCA_SYNC_VENDOR_NAME, TCA_SYNC_VAT_REG_NUM, UNIQUE_TAX_REFERENCE_NUM, PARTNERSHIP_UTR, PARTNERSHIP_NAME, CIS_ENABLED_FLAG, FIRST_NAME, SECOND_NAME, LAST_NAME, SALUTATION, TRADING_NAME, WORK_REFERENCE, COMPANY_REGISTRATION_NUMBER, NATIONAL_INSURANCE_NUMBER, VERIFICATION_NUMBER, VERIFICATION_REQUEST_ID, MATCH_STATUS_FLAG, CIS_VERIFICATION_DATE, INDIVIDUAL_1099, PAY_AWT_GROUP_ID, CIS_PARENT_VENDOR_ID, BUS_CLASS_LAST_CERTIFIED_DATE, BUS_CLASS_LAST_CERTIFIED_BY, VAT_REGISTRATION_NUM_1, _FIVETRAN_DELETED, _FIVETRAN_ID, _FIVETRAN_SYNCED, PSA_LOAD_DTS, PSA_DELETE_IND, PSA_RECORD_SOURCE FROM {{ source('emtk_ebs_ap', 'ap_suppliers') }} as SRC  ),
SRC_A              as ( SELECT REC_SRC, BKCC FROM {{ ref('ref_business_key_collision') }} as SRC  )

/*
SRC_S              as ( SELECT * FROM emtk_ebs_ap.ap_suppliers )
SRC_A              as ( SELECT * FROM raw_vault.ref_business_key_collision )
*/
---- LOGIC LAYER ----

, LOGIC_S as (
    SELECT
        SEGMENT1::TEXT                                               as                                        SUPPLIER_BK
      , SEGMENT1
      , VENDOR_ID
      , CONVERT_TIMEZONE('UTC', _FIVETRAN_SYNCED )                   as                                           LOAD_DTS
      , LAST_UPDATE_DATE
      , LAST_UPDATED_BY
      , VENDOR_NAME
      , VENDOR_NAME_ALT
      , SUMMARY_FLAG
      , ENABLED_FLAG
      , SEGMENT2
      , SEGMENT3
      , SEGMENT4
      , SEGMENT5
      , LAST_UPDATE_LOGIN
      , CREATION_DATE
      , CREATED_BY
      , EMPLOYEE_ID
      , VENDOR_TYPE_LOOKUP_CODE
      , CUSTOMER_NUM
      , ONE_TIME_FLAG
      , PARENT_VENDOR_ID
      , MIN_ORDER_AMOUNT
      , SHIP_TO_LOCATION_ID
      , BILL_TO_LOCATION_ID
      , SHIP_VIA_LOOKUP_CODE
      , FREIGHT_TERMS_LOOKUP_CODE
      , FOB_LOOKUP_CODE
      , TERMS_ID
      , SET_OF_BOOKS_ID
      , CREDIT_STATUS_LOOKUP_CODE
      , CREDIT_LIMIT
      , ALWAYS_TAKE_DISC_FLAG
      , PAY_DATE_BASIS_LOOKUP_CODE
      , PAY_GROUP_LOOKUP_CODE
      , PAYMENT_PRIORITY
      , INVOICE_CURRENCY_CODE
      , PAYMENT_CURRENCY_CODE
      , INVOICE_AMOUNT_LIMIT
      , EXCHANGE_DATE_LOOKUP_CODE
      , HOLD_ALL_PAYMENTS_FLAG
      , HOLD_FUTURE_PAYMENTS_FLAG
      , HOLD_REASON
      , DISTRIBUTION_SET_ID
      , ACCTS_PAY_CODE_COMBINATION_ID
      , DISC_LOST_CODE_COMBINATION_ID
      , DISC_TAKEN_CODE_COMBINATION_ID
      , EXPENSE_CODE_COMBINATION_ID
      , PREPAY_CODE_COMBINATION_ID
      , NUM_1099
      , TYPE_1099
      , WITHHOLDING_STATUS_LOOKUP_CODE
      , WITHHOLDING_START_DATE
      , ORGANIZATION_TYPE_LOOKUP_CODE
      , VAT_CODE
      , START_DATE_ACTIVE
      , END_DATE_ACTIVE
      , MINORITY_GROUP_LOOKUP_CODE
      , PAYMENT_METHOD_LOOKUP_CODE
      , BANK_ACCOUNT_NAME
      , BANK_ACCOUNT_NUM
      , BANK_NUM
      , BANK_ACCOUNT_TYPE
      , WOMEN_OWNED_FLAG
      , SMALL_BUSINESS_FLAG
      , STANDARD_INDUSTRY_CLASS
      , HOLD_FLAG
      , PURCHASING_HOLD_REASON
      , HOLD_BY
      , HOLD_DATE
      , TERMS_DATE_BASIS
      , PRICE_TOLERANCE
      , INSPECTION_REQUIRED_FLAG
      , RECEIPT_REQUIRED_FLAG
      , QTY_RCV_TOLERANCE
      , QTY_RCV_EXCEPTION_CODE
      , ENFORCE_SHIP_TO_LOCATION_CODE
      , DAYS_EARLY_RECEIPT_ALLOWED
      , DAYS_LATE_RECEIPT_ALLOWED
      , RECEIPT_DAYS_EXCEPTION_CODE
      , RECEIVING_ROUTING_ID
      , ALLOW_SUBSTITUTE_RECEIPTS_FLAG
      , ALLOW_UNORDERED_RECEIPTS_FLAG
      , HOLD_UNMATCHED_INVOICES_FLAG
      , EXCLUSIVE_PAYMENT_FLAG
      , AP_TAX_ROUNDING_RULE
      , AUTO_TAX_CALC_FLAG
      , AUTO_TAX_CALC_OVERRIDE
      , AMOUNT_INCLUDES_TAX_FLAG
      , TAX_VERIFICATION_DATE
      , NAME_CONTROL
      , STATE_REPORTABLE_FLAG
      , FEDERAL_REPORTABLE_FLAG
      , ATTRIBUTE_CATEGORY
      , ATTRIBUTE1
      , ATTRIBUTE2
      , ATTRIBUTE3
      , ATTRIBUTE4
      , ATTRIBUTE5
      , ATTRIBUTE6
      , ATTRIBUTE7
      , ATTRIBUTE8
      , ATTRIBUTE9
      , ATTRIBUTE10
      , ATTRIBUTE11
      , ATTRIBUTE12
      , ATTRIBUTE13
      , ATTRIBUTE14
      , ATTRIBUTE15
      , REQUEST_ID
      , PROGRAM_APPLICATION_ID
      , PROGRAM_ID
      , PROGRAM_UPDATE_DATE
      , OFFSET_VAT_CODE
      , AUTO_CALCULATE_INTEREST_FLAG
      , VALIDATION_NUMBER
      , EXCLUDE_FREIGHT_FROM_DISCOUNT
      , TAX_REPORTING_NAME
      , CHECK_DIGITS
      , BANK_NUMBER
      , ALLOW_AWT_FLAG
      , AWT_GROUP_ID
      , GLOBAL_ATTRIBUTE1
      , GLOBAL_ATTRIBUTE2
      , GLOBAL_ATTRIBUTE3
      , GLOBAL_ATTRIBUTE4
      , GLOBAL_ATTRIBUTE5
      , GLOBAL_ATTRIBUTE6
      , GLOBAL_ATTRIBUTE7
      , GLOBAL_ATTRIBUTE8
      , GLOBAL_ATTRIBUTE9
      , GLOBAL_ATTRIBUTE10
      , GLOBAL_ATTRIBUTE11
      , GLOBAL_ATTRIBUTE12
      , GLOBAL_ATTRIBUTE13
      , GLOBAL_ATTRIBUTE14
      , GLOBAL_ATTRIBUTE15
      , GLOBAL_ATTRIBUTE16
      , GLOBAL_ATTRIBUTE17
      , GLOBAL_ATTRIBUTE18
      , GLOBAL_ATTRIBUTE19
      , GLOBAL_ATTRIBUTE20
      , GLOBAL_ATTRIBUTE_CATEGORY
      , EDI_TRANSACTION_HANDLING
      , EDI_PAYMENT_METHOD
      , EDI_PAYMENT_FORMAT
      , EDI_REMITTANCE_METHOD
      , EDI_REMITTANCE_INSTRUCTION
      , BANK_CHARGE_BEARER
      , BANK_BRANCH_TYPE
      , MATCH_OPTION
      , FUTURE_DATED_PAYMENT_CCID
      , CREATE_DEBIT_MEMO_FLAG
      , OFFSET_TAX_FLAG
      , PARTY_ID
      , PARENT_PARTY_ID
      , NI_NUMBER
      , TCA_SYNC_NUM_1099
      , TCA_SYNC_VENDOR_NAME
      , TCA_SYNC_VAT_REG_NUM
      , UNIQUE_TAX_REFERENCE_NUM
      , PARTNERSHIP_UTR
      , PARTNERSHIP_NAME
      , CIS_ENABLED_FLAG
      , FIRST_NAME
      , SECOND_NAME
      , LAST_NAME
      , SALUTATION
      , TRADING_NAME
      , WORK_REFERENCE
      , COMPANY_REGISTRATION_NUMBER
      , NATIONAL_INSURANCE_NUMBER
      , VERIFICATION_NUMBER
      , VERIFICATION_REQUEST_ID
      , MATCH_STATUS_FLAG
      , CIS_VERIFICATION_DATE
      , INDIVIDUAL_1099
      , PAY_AWT_GROUP_ID
      , CIS_PARENT_VENDOR_ID
      , BUS_CLASS_LAST_CERTIFIED_DATE
      , BUS_CLASS_LAST_CERTIFIED_BY
      , VAT_REGISTRATION_NUM_1
      , _FIVETRAN_DELETED
      , _FIVETRAN_ID
      , _FIVETRAN_SYNCED
      , PSA_LOAD_DTS
      , PSA_DELETE_IND
      , PSA_RECORD_SOURCE
    FROM SRC_S
)

, LOGIC_A as (
    SELECT
        REC_SRC
      , BKCC
    FROM SRC_A
)
---- RENAME LAYER ----

, RENAME_S as (
    SELECT
        SUPPLIER_BK
      , SEGMENT1
      , VENDOR_ID
      , LOAD_DTS
      , LAST_UPDATE_DATE
      , LAST_UPDATED_BY
      , VENDOR_NAME
      , VENDOR_NAME_ALT
      , SUMMARY_FLAG
      , ENABLED_FLAG
      , SEGMENT2
      , SEGMENT3
      , SEGMENT4
      , SEGMENT5
      , LAST_UPDATE_LOGIN
      , CREATION_DATE
      , CREATED_BY
      , EMPLOYEE_ID
      , VENDOR_TYPE_LOOKUP_CODE
      , CUSTOMER_NUM
      , ONE_TIME_FLAG
      , PARENT_VENDOR_ID
      , MIN_ORDER_AMOUNT
      , SHIP_TO_LOCATION_ID
      , BILL_TO_LOCATION_ID
      , SHIP_VIA_LOOKUP_CODE
      , FREIGHT_TERMS_LOOKUP_CODE
      , FOB_LOOKUP_CODE
      , TERMS_ID
      , SET_OF_BOOKS_ID
      , CREDIT_STATUS_LOOKUP_CODE
      , CREDIT_LIMIT
      , ALWAYS_TAKE_DISC_FLAG
      , PAY_DATE_BASIS_LOOKUP_CODE
      , PAY_GROUP_LOOKUP_CODE
      , PAYMENT_PRIORITY
      , INVOICE_CURRENCY_CODE
      , PAYMENT_CURRENCY_CODE
      , INVOICE_AMOUNT_LIMIT
      , EXCHANGE_DATE_LOOKUP_CODE
      , HOLD_ALL_PAYMENTS_FLAG
      , HOLD_FUTURE_PAYMENTS_FLAG
      , HOLD_REASON
      , DISTRIBUTION_SET_ID
      , ACCTS_PAY_CODE_COMBINATION_ID
      , DISC_LOST_CODE_COMBINATION_ID
      , DISC_TAKEN_CODE_COMBINATION_ID
      , EXPENSE_CODE_COMBINATION_ID
      , PREPAY_CODE_COMBINATION_ID
      , NUM_1099
      , TYPE_1099
      , WITHHOLDING_STATUS_LOOKUP_CODE
      , WITHHOLDING_START_DATE
      , ORGANIZATION_TYPE_LOOKUP_CODE
      , VAT_CODE
      , START_DATE_ACTIVE
      , END_DATE_ACTIVE
      , MINORITY_GROUP_LOOKUP_CODE
      , PAYMENT_METHOD_LOOKUP_CODE
      , BANK_ACCOUNT_NAME
      , BANK_ACCOUNT_NUM
      , BANK_NUM
      , BANK_ACCOUNT_TYPE
      , WOMEN_OWNED_FLAG
      , SMALL_BUSINESS_FLAG
      , STANDARD_INDUSTRY_CLASS
      , HOLD_FLAG
      , PURCHASING_HOLD_REASON
      , HOLD_BY
      , HOLD_DATE
      , TERMS_DATE_BASIS
      , PRICE_TOLERANCE
      , INSPECTION_REQUIRED_FLAG
      , RECEIPT_REQUIRED_FLAG
      , QTY_RCV_TOLERANCE
      , QTY_RCV_EXCEPTION_CODE
      , ENFORCE_SHIP_TO_LOCATION_CODE
      , DAYS_EARLY_RECEIPT_ALLOWED
      , DAYS_LATE_RECEIPT_ALLOWED
      , RECEIPT_DAYS_EXCEPTION_CODE
      , RECEIVING_ROUTING_ID
      , ALLOW_SUBSTITUTE_RECEIPTS_FLAG
      , ALLOW_UNORDERED_RECEIPTS_FLAG
      , HOLD_UNMATCHED_INVOICES_FLAG
      , EXCLUSIVE_PAYMENT_FLAG
      , AP_TAX_ROUNDING_RULE
      , AUTO_TAX_CALC_FLAG
      , AUTO_TAX_CALC_OVERRIDE
      , AMOUNT_INCLUDES_TAX_FLAG
      , TAX_VERIFICATION_DATE
      , NAME_CONTROL
      , STATE_REPORTABLE_FLAG
      , FEDERAL_REPORTABLE_FLAG
      , ATTRIBUTE_CATEGORY
      , ATTRIBUTE1
      , ATTRIBUTE2
      , ATTRIBUTE3
      , ATTRIBUTE4
      , ATTRIBUTE5
      , ATTRIBUTE6
      , ATTRIBUTE7
      , ATTRIBUTE8
      , ATTRIBUTE9
      , ATTRIBUTE10
      , ATTRIBUTE11
      , ATTRIBUTE12
      , ATTRIBUTE13
      , ATTRIBUTE14
      , ATTRIBUTE15
      , REQUEST_ID
      , PROGRAM_APPLICATION_ID
      , PROGRAM_ID
      , PROGRAM_UPDATE_DATE
      , OFFSET_VAT_CODE
      , AUTO_CALCULATE_INTEREST_FLAG
      , VALIDATION_NUMBER
      , EXCLUDE_FREIGHT_FROM_DISCOUNT
      , TAX_REPORTING_NAME
      , CHECK_DIGITS
      , BANK_NUMBER
      , ALLOW_AWT_FLAG
      , AWT_GROUP_ID
      , GLOBAL_ATTRIBUTE1
      , GLOBAL_ATTRIBUTE2
      , GLOBAL_ATTRIBUTE3
      , GLOBAL_ATTRIBUTE4
      , GLOBAL_ATTRIBUTE5
      , GLOBAL_ATTRIBUTE6
      , GLOBAL_ATTRIBUTE7
      , GLOBAL_ATTRIBUTE8
      , GLOBAL_ATTRIBUTE9
      , GLOBAL_ATTRIBUTE10
      , GLOBAL_ATTRIBUTE11
      , GLOBAL_ATTRIBUTE12
      , GLOBAL_ATTRIBUTE13
      , GLOBAL_ATTRIBUTE14
      , GLOBAL_ATTRIBUTE15
      , GLOBAL_ATTRIBUTE16
      , GLOBAL_ATTRIBUTE17
      , GLOBAL_ATTRIBUTE18
      , GLOBAL_ATTRIBUTE19
      , GLOBAL_ATTRIBUTE20
      , GLOBAL_ATTRIBUTE_CATEGORY
      , EDI_TRANSACTION_HANDLING
      , EDI_PAYMENT_METHOD
      , EDI_PAYMENT_FORMAT
      , EDI_REMITTANCE_METHOD
      , EDI_REMITTANCE_INSTRUCTION
      , BANK_CHARGE_BEARER
      , BANK_BRANCH_TYPE
      , MATCH_OPTION
      , FUTURE_DATED_PAYMENT_CCID
      , CREATE_DEBIT_MEMO_FLAG
      , OFFSET_TAX_FLAG
      , PARTY_ID
      , PARENT_PARTY_ID
      , NI_NUMBER
      , TCA_SYNC_NUM_1099
      , TCA_SYNC_VENDOR_NAME
      , TCA_SYNC_VAT_REG_NUM
      , UNIQUE_TAX_REFERENCE_NUM
      , PARTNERSHIP_UTR
      , PARTNERSHIP_NAME
      , CIS_ENABLED_FLAG
      , FIRST_NAME
      , SECOND_NAME
      , LAST_NAME
      , SALUTATION
      , TRADING_NAME
      , WORK_REFERENCE
      , COMPANY_REGISTRATION_NUMBER
      , NATIONAL_INSURANCE_NUMBER
      , VERIFICATION_NUMBER
      , VERIFICATION_REQUEST_ID
      , MATCH_STATUS_FLAG
      , CIS_VERIFICATION_DATE
      , INDIVIDUAL_1099
      , PAY_AWT_GROUP_ID
      , CIS_PARENT_VENDOR_ID
      , BUS_CLASS_LAST_CERTIFIED_DATE
      , BUS_CLASS_LAST_CERTIFIED_BY
      , VAT_REGISTRATION_NUM_1
      , _FIVETRAN_DELETED
      , _FIVETRAN_ID
      , _FIVETRAN_SYNCED
      , PSA_LOAD_DTS
      , PSA_DELETE_IND
      , PSA_RECORD_SOURCE
    FROM LOGIC_S
)

, RENAME_A as (
    SELECT
        REC_SRC
      , BKCC
    FROM LOGIC_A
)
---- FILTER LAYER ----

, FILTER_S as (
    SELECT *
    FROM RENAME_S
)

, FILTER_A as (
    SELECT *
    FROM RENAME_A
    WHERE rec_src = 'USWIOC.ORCL.EBSEMTK.AP_SUPPLIER'
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM FILTER_S
    INNER JOIN FILTER_A
        ON '1' = '1'
)

---- FINAL LAYER ----
SELECT
          SUPPLIER_BK
        , SEGMENT1
        , VENDOR_ID
        , LOAD_DTS
        , LAST_UPDATE_DATE
        , LAST_UPDATED_BY
        , VENDOR_NAME
        , VENDOR_NAME_ALT
        , SUMMARY_FLAG
        , ENABLED_FLAG
        , SEGMENT2
        , SEGMENT3
        , SEGMENT4
        , SEGMENT5
        , LAST_UPDATE_LOGIN
        , CREATION_DATE
        , CREATED_BY
        , EMPLOYEE_ID
        , VENDOR_TYPE_LOOKUP_CODE
        , CUSTOMER_NUM
        , ONE_TIME_FLAG
        , PARENT_VENDOR_ID
        , MIN_ORDER_AMOUNT
        , SHIP_TO_LOCATION_ID
        , BILL_TO_LOCATION_ID
        , SHIP_VIA_LOOKUP_CODE
        , FREIGHT_TERMS_LOOKUP_CODE
        , FOB_LOOKUP_CODE
        , TERMS_ID
        , SET_OF_BOOKS_ID
        , CREDIT_STATUS_LOOKUP_CODE
        , CREDIT_LIMIT
        , ALWAYS_TAKE_DISC_FLAG
        , PAY_DATE_BASIS_LOOKUP_CODE
        , PAY_GROUP_LOOKUP_CODE
        , PAYMENT_PRIORITY
        , INVOICE_CURRENCY_CODE
        , PAYMENT_CURRENCY_CODE
        , INVOICE_AMOUNT_LIMIT
        , EXCHANGE_DATE_LOOKUP_CODE
        , HOLD_ALL_PAYMENTS_FLAG
        , HOLD_FUTURE_PAYMENTS_FLAG
        , HOLD_REASON
        , DISTRIBUTION_SET_ID
        , ACCTS_PAY_CODE_COMBINATION_ID
        , DISC_LOST_CODE_COMBINATION_ID
        , DISC_TAKEN_CODE_COMBINATION_ID
        , EXPENSE_CODE_COMBINATION_ID
        , PREPAY_CODE_COMBINATION_ID
        , NUM_1099
        , TYPE_1099
        , WITHHOLDING_STATUS_LOOKUP_CODE
        , WITHHOLDING_START_DATE
        , ORGANIZATION_TYPE_LOOKUP_CODE
        , VAT_CODE
        , START_DATE_ACTIVE
        , END_DATE_ACTIVE
        , MINORITY_GROUP_LOOKUP_CODE
        , PAYMENT_METHOD_LOOKUP_CODE
        , BANK_ACCOUNT_NAME
        , BANK_ACCOUNT_NUM
        , BANK_NUM
        , BANK_ACCOUNT_TYPE
        , WOMEN_OWNED_FLAG
        , SMALL_BUSINESS_FLAG
        , STANDARD_INDUSTRY_CLASS
        , HOLD_FLAG
        , PURCHASING_HOLD_REASON
        , HOLD_BY
        , HOLD_DATE
        , TERMS_DATE_BASIS
        , PRICE_TOLERANCE
        , INSPECTION_REQUIRED_FLAG
        , RECEIPT_REQUIRED_FLAG
        , QTY_RCV_TOLERANCE
        , QTY_RCV_EXCEPTION_CODE
        , ENFORCE_SHIP_TO_LOCATION_CODE
        , DAYS_EARLY_RECEIPT_ALLOWED
        , DAYS_LATE_RECEIPT_ALLOWED
        , RECEIPT_DAYS_EXCEPTION_CODE
        , RECEIVING_ROUTING_ID
        , ALLOW_SUBSTITUTE_RECEIPTS_FLAG
        , ALLOW_UNORDERED_RECEIPTS_FLAG
        , HOLD_UNMATCHED_INVOICES_FLAG
        , EXCLUSIVE_PAYMENT_FLAG
        , AP_TAX_ROUNDING_RULE
        , AUTO_TAX_CALC_FLAG
        , AUTO_TAX_CALC_OVERRIDE
        , AMOUNT_INCLUDES_TAX_FLAG
        , TAX_VERIFICATION_DATE
        , NAME_CONTROL
        , STATE_REPORTABLE_FLAG
        , FEDERAL_REPORTABLE_FLAG
        , ATTRIBUTE_CATEGORY
        , ATTRIBUTE1
        , ATTRIBUTE2
        , ATTRIBUTE3
        , ATTRIBUTE4
        , ATTRIBUTE5
        , ATTRIBUTE6
        , ATTRIBUTE7
        , ATTRIBUTE8
        , ATTRIBUTE9
        , ATTRIBUTE10
        , ATTRIBUTE11
        , ATTRIBUTE12
        , ATTRIBUTE13
        , ATTRIBUTE14
        , ATTRIBUTE15
        , REQUEST_ID
        , PROGRAM_APPLICATION_ID
        , PROGRAM_ID
        , PROGRAM_UPDATE_DATE
        , OFFSET_VAT_CODE
        , AUTO_CALCULATE_INTEREST_FLAG
        , VALIDATION_NUMBER
        , EXCLUDE_FREIGHT_FROM_DISCOUNT
        , TAX_REPORTING_NAME
        , CHECK_DIGITS
        , BANK_NUMBER
        , ALLOW_AWT_FLAG
        , AWT_GROUP_ID
        , GLOBAL_ATTRIBUTE1
        , GLOBAL_ATTRIBUTE2
        , GLOBAL_ATTRIBUTE3
        , GLOBAL_ATTRIBUTE4
        , GLOBAL_ATTRIBUTE5
        , GLOBAL_ATTRIBUTE6
        , GLOBAL_ATTRIBUTE7
        , GLOBAL_ATTRIBUTE8
        , GLOBAL_ATTRIBUTE9
        , GLOBAL_ATTRIBUTE10
        , GLOBAL_ATTRIBUTE11
        , GLOBAL_ATTRIBUTE12
        , GLOBAL_ATTRIBUTE13
        , GLOBAL_ATTRIBUTE14
        , GLOBAL_ATTRIBUTE15
        , GLOBAL_ATTRIBUTE16
        , GLOBAL_ATTRIBUTE17
        , GLOBAL_ATTRIBUTE18
        , GLOBAL_ATTRIBUTE19
        , GLOBAL_ATTRIBUTE20
        , GLOBAL_ATTRIBUTE_CATEGORY
        , EDI_TRANSACTION_HANDLING
        , EDI_PAYMENT_METHOD
        , EDI_PAYMENT_FORMAT
        , EDI_REMITTANCE_METHOD
        , EDI_REMITTANCE_INSTRUCTION
        , BANK_CHARGE_BEARER
        , BANK_BRANCH_TYPE
        , MATCH_OPTION
        , FUTURE_DATED_PAYMENT_CCID
        , CREATE_DEBIT_MEMO_FLAG
        , OFFSET_TAX_FLAG
        , PARTY_ID
        , PARENT_PARTY_ID
        , NI_NUMBER
        , TCA_SYNC_NUM_1099
        , TCA_SYNC_VENDOR_NAME
        , TCA_SYNC_VAT_REG_NUM
        , UNIQUE_TAX_REFERENCE_NUM
        , PARTNERSHIP_UTR
        , PARTNERSHIP_NAME
        , CIS_ENABLED_FLAG
        , FIRST_NAME
        , SECOND_NAME
        , LAST_NAME
        , SALUTATION
        , TRADING_NAME
        , WORK_REFERENCE
        , COMPANY_REGISTRATION_NUMBER
        , NATIONAL_INSURANCE_NUMBER
        , VERIFICATION_NUMBER
        , VERIFICATION_REQUEST_ID
        , MATCH_STATUS_FLAG
        , CIS_VERIFICATION_DATE
        , INDIVIDUAL_1099
        , PAY_AWT_GROUP_ID
        , CIS_PARENT_VENDOR_ID
        , BUS_CLASS_LAST_CERTIFIED_DATE
        , BUS_CLASS_LAST_CERTIFIED_BY
        , VAT_REGISTRATION_NUM_1
        , _FIVETRAN_DELETED
        , _FIVETRAN_ID
        , _FIVETRAN_SYNCED
        , PSA_LOAD_DTS
        , PSA_DELETE_IND
        , PSA_RECORD_SOURCE
        , REC_SRC
        , BKCC
        , MD5_BINARY(UPPER(CONCAT_WS('||',
          COALESCE(NULLIF(TRIM(CAST(SEGMENT1 as VARCHAR)),''), '^^')
        , COALESCE(NULLIF(TRIM(CAST(BKCC as VARCHAR)),''), '^^')
        ))) as SUPPLIER_HK
        , MD5_BINARY(UPPER(NULLIF(CONCAT(
              IFNULL(TRIM(LAST_UPDATE_DATE::text), '^^') 
            , '||', IFNULL(TRIM(LAST_UPDATED_BY::text), '^^') 
            , '||', IFNULL(TRIM(VENDOR_NAME::text), '^^') 
            , '||', IFNULL(TRIM(VENDOR_NAME_ALT::text), '^^') 
            , '||', IFNULL(TRIM(SUMMARY_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(ENABLED_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(SEGMENT2::text), '^^') 
            , '||', IFNULL(TRIM(SEGMENT3::text), '^^') 
            , '||', IFNULL(TRIM(SEGMENT4::text), '^^') 
            , '||', IFNULL(TRIM(SEGMENT5::text), '^^') 
            , '||', IFNULL(TRIM(LAST_UPDATE_LOGIN::text), '^^') 
            , '||', IFNULL(TRIM(CREATION_DATE::text), '^^') 
            , '||', IFNULL(TRIM(CREATED_BY::text), '^^') 
            , '||', IFNULL(TRIM(EMPLOYEE_ID::text), '^^') 
            , '||', IFNULL(TRIM(VENDOR_TYPE_LOOKUP_CODE::text), '^^') 
            , '||', IFNULL(TRIM(CUSTOMER_NUM::text), '^^') 
            , '||', IFNULL(TRIM(ONE_TIME_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(PARENT_VENDOR_ID::text), '^^') 
            , '||', IFNULL(TRIM(MIN_ORDER_AMOUNT::text), '^^') 
            , '||', IFNULL(TRIM(SHIP_TO_LOCATION_ID::text), '^^') 
            , '||', IFNULL(TRIM(BILL_TO_LOCATION_ID::text), '^^') 
            , '||', IFNULL(TRIM(SHIP_VIA_LOOKUP_CODE::text), '^^') 
            , '||', IFNULL(TRIM(FREIGHT_TERMS_LOOKUP_CODE::text), '^^') 
            , '||', IFNULL(TRIM(FOB_LOOKUP_CODE::text), '^^') 
            , '||', IFNULL(TRIM(TERMS_ID::text), '^^') 
            , '||', IFNULL(TRIM(SET_OF_BOOKS_ID::text), '^^') 
            , '||', IFNULL(TRIM(CREDIT_STATUS_LOOKUP_CODE::text), '^^') 
            , '||', IFNULL(TRIM(CREDIT_LIMIT::text), '^^') 
            , '||', IFNULL(TRIM(ALWAYS_TAKE_DISC_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(PAY_DATE_BASIS_LOOKUP_CODE::text), '^^') 
            , '||', IFNULL(TRIM(PAY_GROUP_LOOKUP_CODE::text), '^^') 
            , '||', IFNULL(TRIM(PAYMENT_PRIORITY::text), '^^') 
            , '||', IFNULL(TRIM(INVOICE_CURRENCY_CODE::text), '^^') 
            , '||', IFNULL(TRIM(PAYMENT_CURRENCY_CODE::text), '^^') 
            , '||', IFNULL(TRIM(INVOICE_AMOUNT_LIMIT::text), '^^') 
            , '||', IFNULL(TRIM(EXCHANGE_DATE_LOOKUP_CODE::text), '^^') 
            , '||', IFNULL(TRIM(HOLD_ALL_PAYMENTS_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(HOLD_FUTURE_PAYMENTS_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(HOLD_REASON::text), '^^') 
            , '||', IFNULL(TRIM(DISTRIBUTION_SET_ID::text), '^^') 
            , '||', IFNULL(TRIM(ACCTS_PAY_CODE_COMBINATION_ID::text), '^^') 
            , '||', IFNULL(TRIM(DISC_LOST_CODE_COMBINATION_ID::text), '^^') 
            , '||', IFNULL(TRIM(DISC_TAKEN_CODE_COMBINATION_ID::text), '^^') 
            , '||', IFNULL(TRIM(EXPENSE_CODE_COMBINATION_ID::text), '^^') 
            , '||', IFNULL(TRIM(PREPAY_CODE_COMBINATION_ID::text), '^^') 
            , '||', IFNULL(TRIM(NUM_1099::text), '^^') 
            , '||', IFNULL(TRIM(TYPE_1099::text), '^^') 
            , '||', IFNULL(TRIM(WITHHOLDING_STATUS_LOOKUP_CODE::text), '^^') 
            , '||', IFNULL(TRIM(WITHHOLDING_START_DATE::text), '^^') 
            , '||', IFNULL(TRIM(ORGANIZATION_TYPE_LOOKUP_CODE::text), '^^') 
            , '||', IFNULL(TRIM(VAT_CODE::text), '^^') 
            , '||', IFNULL(TRIM(START_DATE_ACTIVE::text), '^^') 
            , '||', IFNULL(TRIM(END_DATE_ACTIVE::text), '^^') 
            , '||', IFNULL(TRIM(MINORITY_GROUP_LOOKUP_CODE::text), '^^') 
            , '||', IFNULL(TRIM(PAYMENT_METHOD_LOOKUP_CODE::text), '^^') 
            , '||', IFNULL(TRIM(BANK_ACCOUNT_NAME::text), '^^') 
            , '||', IFNULL(TRIM(BANK_ACCOUNT_NUM::text), '^^') 
            , '||', IFNULL(TRIM(BANK_NUM::text), '^^') 
            , '||', IFNULL(TRIM(BANK_ACCOUNT_TYPE::text), '^^') 
            , '||', IFNULL(TRIM(WOMEN_OWNED_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(SMALL_BUSINESS_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(STANDARD_INDUSTRY_CLASS::text), '^^') 
            , '||', IFNULL(TRIM(HOLD_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(PURCHASING_HOLD_REASON::text), '^^') 
            , '||', IFNULL(TRIM(HOLD_BY::text), '^^') 
            , '||', IFNULL(TRIM(HOLD_DATE::text), '^^') 
            , '||', IFNULL(TRIM(TERMS_DATE_BASIS::text), '^^') 
            , '||', IFNULL(TRIM(PRICE_TOLERANCE::text), '^^') 
            , '||', IFNULL(TRIM(INSPECTION_REQUIRED_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(RECEIPT_REQUIRED_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(QTY_RCV_TOLERANCE::text), '^^') 
            , '||', IFNULL(TRIM(QTY_RCV_EXCEPTION_CODE::text), '^^') 
            , '||', IFNULL(TRIM(ENFORCE_SHIP_TO_LOCATION_CODE::text), '^^') 
            , '||', IFNULL(TRIM(DAYS_EARLY_RECEIPT_ALLOWED::text), '^^') 
            , '||', IFNULL(TRIM(DAYS_LATE_RECEIPT_ALLOWED::text), '^^') 
            , '||', IFNULL(TRIM(RECEIPT_DAYS_EXCEPTION_CODE::text), '^^') 
            , '||', IFNULL(TRIM(RECEIVING_ROUTING_ID::text), '^^') 
            , '||', IFNULL(TRIM(ALLOW_SUBSTITUTE_RECEIPTS_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(ALLOW_UNORDERED_RECEIPTS_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(HOLD_UNMATCHED_INVOICES_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(EXCLUSIVE_PAYMENT_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(AP_TAX_ROUNDING_RULE::text), '^^') 
            , '||', IFNULL(TRIM(AUTO_TAX_CALC_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(AUTO_TAX_CALC_OVERRIDE::text), '^^') 
            , '||', IFNULL(TRIM(AMOUNT_INCLUDES_TAX_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(TAX_VERIFICATION_DATE::text), '^^') 
            , '||', IFNULL(TRIM(NAME_CONTROL::text), '^^') 
            , '||', IFNULL(TRIM(STATE_REPORTABLE_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(FEDERAL_REPORTABLE_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE_CATEGORY::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE1::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE2::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE3::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE4::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE5::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE6::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE7::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE8::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE9::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE10::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE11::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE12::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE13::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE14::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE15::text), '^^') 
            , '||', IFNULL(TRIM(REQUEST_ID::text), '^^') 
            , '||', IFNULL(TRIM(PROGRAM_APPLICATION_ID::text), '^^') 
            , '||', IFNULL(TRIM(PROGRAM_ID::text), '^^') 
            , '||', IFNULL(TRIM(PROGRAM_UPDATE_DATE::text), '^^') 
            , '||', IFNULL(TRIM(OFFSET_VAT_CODE::text), '^^') 
            , '||', IFNULL(TRIM(AUTO_CALCULATE_INTEREST_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(VALIDATION_NUMBER::text), '^^') 
            , '||', IFNULL(TRIM(EXCLUDE_FREIGHT_FROM_DISCOUNT::text), '^^') 
            , '||', IFNULL(TRIM(TAX_REPORTING_NAME::text), '^^') 
            , '||', IFNULL(TRIM(CHECK_DIGITS::text), '^^') 
            , '||', IFNULL(TRIM(BANK_NUMBER::text), '^^') 
            , '||', IFNULL(TRIM(ALLOW_AWT_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(AWT_GROUP_ID::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE1::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE2::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE3::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE4::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE5::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE6::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE7::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE8::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE9::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE10::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE11::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE12::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE13::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE14::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE15::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE16::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE17::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE18::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE19::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE20::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE_CATEGORY::text), '^^') 
            , '||', IFNULL(TRIM(EDI_TRANSACTION_HANDLING::text), '^^') 
            , '||', IFNULL(TRIM(EDI_PAYMENT_METHOD::text), '^^') 
            , '||', IFNULL(TRIM(EDI_PAYMENT_FORMAT::text), '^^') 
            , '||', IFNULL(TRIM(EDI_REMITTANCE_METHOD::text), '^^') 
            , '||', IFNULL(TRIM(EDI_REMITTANCE_INSTRUCTION::text), '^^') 
            , '||', IFNULL(TRIM(BANK_CHARGE_BEARER::text), '^^') 
            , '||', IFNULL(TRIM(BANK_BRANCH_TYPE::text), '^^') 
            , '||', IFNULL(TRIM(MATCH_OPTION::text), '^^') 
            , '||', IFNULL(TRIM(FUTURE_DATED_PAYMENT_CCID::text), '^^') 
            , '||', IFNULL(TRIM(CREATE_DEBIT_MEMO_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(OFFSET_TAX_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(PARTY_ID::text), '^^') 
            , '||', IFNULL(TRIM(PARENT_PARTY_ID::text), '^^') 
            , '||', IFNULL(TRIM(NI_NUMBER::text), '^^') 
            , '||', IFNULL(TRIM(TCA_SYNC_NUM_1099::text), '^^') 
            , '||', IFNULL(TRIM(TCA_SYNC_VENDOR_NAME::text), '^^') 
            , '||', IFNULL(TRIM(TCA_SYNC_VAT_REG_NUM::text), '^^') 
            , '||', IFNULL(TRIM(UNIQUE_TAX_REFERENCE_NUM::text), '^^') 
            , '||', IFNULL(TRIM(PARTNERSHIP_UTR::text), '^^') 
            , '||', IFNULL(TRIM(PARTNERSHIP_NAME::text), '^^') 
            , '||', IFNULL(TRIM(CIS_ENABLED_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(FIRST_NAME::text), '^^') 
            , '||', IFNULL(TRIM(SECOND_NAME::text), '^^') 
            , '||', IFNULL(TRIM(LAST_NAME::text), '^^') 
            , '||', IFNULL(TRIM(SALUTATION::text), '^^') 
            , '||', IFNULL(TRIM(TRADING_NAME::text), '^^') 
            , '||', IFNULL(TRIM(WORK_REFERENCE::text), '^^') 
            , '||', IFNULL(TRIM(COMPANY_REGISTRATION_NUMBER::text), '^^') 
            , '||', IFNULL(TRIM(NATIONAL_INSURANCE_NUMBER::text), '^^') 
            , '||', IFNULL(TRIM(VERIFICATION_NUMBER::text), '^^') 
            , '||', IFNULL(TRIM(VERIFICATION_REQUEST_ID::text), '^^') 
            , '||', IFNULL(TRIM(MATCH_STATUS_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(CIS_VERIFICATION_DATE::text), '^^') 
            , '||', IFNULL(TRIM(INDIVIDUAL_1099::text), '^^') 
            , '||', IFNULL(TRIM(PAY_AWT_GROUP_ID::text), '^^') 
            , '||', IFNULL(TRIM(CIS_PARENT_VENDOR_ID::text), '^^') 
            , '||', IFNULL(TRIM(BUS_CLASS_LAST_CERTIFIED_DATE::text), '^^') 
            , '||', IFNULL(TRIM(BUS_CLASS_LAST_CERTIFIED_BY::text), '^^') 
            , '||', IFNULL(TRIM(VAT_REGISTRATION_NUM_1::text), '^^') 
            , '||', IFNULL(TRIM(_FIVETRAN_DELETED::text), '^^') 
            , '||', IFNULL(TRIM(PSA_DELETE_IND::text), '^^') 
        ), '^^||^^')))  as HASHDIFF
FROM JOIN_RESULT
