---- SRC LAYER ----
WITH
SRC_polfib         as ( SELECT AGING_PERIOD_DAYS, ALLOW_DESCRIPTION_UPDATE_FLAG, ALLOW_PRICE_OVERRIDE_FLAG, AMOUNT, AMOUNT_RELEASED, ATTRIBUTE_1, ATTRIBUTE_10, ATTRIBUTE_11, ATTRIBUTE_12, ATTRIBUTE_13, ATTRIBUTE_14, ATTRIBUTE_15, ATTRIBUTE_16, ATTRIBUTE_17, ATTRIBUTE_18, ATTRIBUTE_19, ATTRIBUTE_2, ATTRIBUTE_20, ATTRIBUTE_3, ATTRIBUTE_4, ATTRIBUTE_5, ATTRIBUTE_6, ATTRIBUTE_7, ATTRIBUTE_8, ATTRIBUTE_9, ATTRIBUTE_CATEGORY, ATTRIBUTE_DATE_1, ATTRIBUTE_DATE_10, ATTRIBUTE_DATE_2, ATTRIBUTE_DATE_3, ATTRIBUTE_DATE_4, ATTRIBUTE_DATE_5, ATTRIBUTE_DATE_6, ATTRIBUTE_DATE_7, ATTRIBUTE_DATE_8, ATTRIBUTE_DATE_9, ATTRIBUTE_NUMBER_1, ATTRIBUTE_NUMBER_10, ATTRIBUTE_NUMBER_2, ATTRIBUTE_NUMBER_3, ATTRIBUTE_NUMBER_4, ATTRIBUTE_NUMBER_5, ATTRIBUTE_NUMBER_6, ATTRIBUTE_NUMBER_7, ATTRIBUTE_NUMBER_8, ATTRIBUTE_NUMBER_9, ATTRIBUTE_TIMESTAMP_1, ATTRIBUTE_TIMESTAMP_10, ATTRIBUTE_TIMESTAMP_2, ATTRIBUTE_TIMESTAMP_3, ATTRIBUTE_TIMESTAMP_4, ATTRIBUTE_TIMESTAMP_5, ATTRIBUTE_TIMESTAMP_6, ATTRIBUTE_TIMESTAMP_7, ATTRIBUTE_TIMESTAMP_8, ATTRIBUTE_TIMESTAMP_9, AUCTION_DISPLAY_NUMBER, AUCTION_HEADER_ID, AUCTION_LINE_NUMBER, BASE_MODEL_ID, BASE_MODEL_PRICE, BASE_QTY, BASE_UNIT_PRICE, BASE_UOM, BID_LINE_NUMBER, BID_NUMBER, CANCELLED_BY, CANCEL_DATE, CANCEL_FLAG, CANCEL_REASON, CAPITAL_EXPENSE_FLAG, CATALOG_NAME, CATEGORY_ID, CLOSED_BY, CLOSED_DATE, CLOSED_REASON, COMMITTED_AMOUNT, COMPONENT_AMOUNT_RELEASED, CONFIGURED_ITEM_FLAG, CONSIGNMENT_LINE_FLAG, CONTRACTOR_FIRST_NAME, CONTRACTOR_LAST_NAME, CONTRACT_ID, CREATED_BY, CREATION_DATE, CREDIT_FLAG, DISCOUNT, DISCOUNT_REASON, DISCOUNT_TYPE, EXPIRATION_DATE, FIRM_DATE, FIRM_STATUS_LOOKUP_CODE, FROM_HEADER_ID, FROM_LINE_ID, FROM_LINE_LOCATION_ID, FUNDS_STATUS, GLOBAL_ATTRIBUTE_1, GLOBAL_ATTRIBUTE_10, GLOBAL_ATTRIBUTE_11, GLOBAL_ATTRIBUTE_12, GLOBAL_ATTRIBUTE_13, GLOBAL_ATTRIBUTE_14, GLOBAL_ATTRIBUTE_15, GLOBAL_ATTRIBUTE_16, GLOBAL_ATTRIBUTE_17, GLOBAL_ATTRIBUTE_18, GLOBAL_ATTRIBUTE_19, GLOBAL_ATTRIBUTE_2, GLOBAL_ATTRIBUTE_20, GLOBAL_ATTRIBUTE_3, GLOBAL_ATTRIBUTE_4, GLOBAL_ATTRIBUTE_5, GLOBAL_ATTRIBUTE_6, GLOBAL_ATTRIBUTE_7, GLOBAL_ATTRIBUTE_8, GLOBAL_ATTRIBUTE_9, GLOBAL_ATTRIBUTE_CATEGORY, GLOBAL_ATTRIBUTE_DATE_1, GLOBAL_ATTRIBUTE_DATE_2, GLOBAL_ATTRIBUTE_DATE_3, GLOBAL_ATTRIBUTE_DATE_4, GLOBAL_ATTRIBUTE_DATE_5, GLOBAL_ATTRIBUTE_NUMBER_1, GLOBAL_ATTRIBUTE_NUMBER_2, GLOBAL_ATTRIBUTE_NUMBER_3, GLOBAL_ATTRIBUTE_NUMBER_4, GLOBAL_ATTRIBUTE_NUMBER_5, GOVERNMENT_CONTEXT, HAZARD_CLASS_ID, ITEM_DESCRIPTION, ITEM_ID, ITEM_REVISION, JOB_DEFINITION_NAME, JOB_DEFINITION_PACKAGE, JOB_ID, LAST_UPDATED_BY, LAST_UPDATED_PROGRAM, LAST_UPDATE_DATE, LAST_UPDATE_LOGIN, LINE_NUM, LINE_REFERENCE_NUM, LINE_START_DATE, LINE_STATUS, LINE_TYPE_ID, LIST_PRICE, LIST_PRICE_PER_UNIT, MANUAL_PRICE_CHANGE_FLAG, MANUFACTURER, MANUFACTURER_PART_NUM, MARKET_PRICE, MATCHING_BASIS, MAX_RETAINAGE_AMOUNT, MIN_RELEASE_AMOUNT, NEGOTIATED_BY_PREPARER_FLAG, NEXT_CONSUMPTION_ADV_GEN_DATE, NOTE_TO_VENDOR, NOT_TO_EXCEED_PRICE, OBJECT_VERSION_NUMBER, OKE_CONTRACT_HEADER_ID, OKE_CONTRACT_VERSION_ID, OPTIONS_PRICE, ORDER_TYPE_LOOKUP_CODE, OVER_TOLERANCE_ERROR_FLAG, PARENT_ITEM_ID, PJC_CONTEXT_CATEGORY, PO_HEADER_ID, PO_LINE_ID, PRC_BU_ID, PREFERRED_GRADE, PRICE_BREAK_LOOKUP_CODE, PRICE_TYPE_LOOKUP_CODE, PROGRAM_APP_NAME, PROGRAM_NAME, PROGRESS_PAYMENT_RATE, PSA_DELETE_IND, PSA_LOAD_DTS, PSA_RECORD_SOURCE, PURCHASE_BASIS, QC_GRADE, QTY_RCV_TOLERANCE, QUANTITY, QUANTITY_COMMITTED, RECOUPMENT_RATE, REFERENCE_NUM, REQUEST_ID, REQ_BU_ID, RETAINAGE_RATE, RETROACTIVE_DATE, SECONDARY_QUANTITY, SECONDARY_UOM_CODE, SHIPPING_UOM_CODE, SHIPPING_UOM_QUANTITY, SH_ATTRIBUTE_1, SH_ATTRIBUTE_10, SH_ATTRIBUTE_11, SH_ATTRIBUTE_12, SH_ATTRIBUTE_13, SH_ATTRIBUTE_14, SH_ATTRIBUTE_15, SH_ATTRIBUTE_16, SH_ATTRIBUTE_17, SH_ATTRIBUTE_18, SH_ATTRIBUTE_19, SH_ATTRIBUTE_2, SH_ATTRIBUTE_20, SH_ATTRIBUTE_3, SH_ATTRIBUTE_4, SH_ATTRIBUTE_5, SH_ATTRIBUTE_6, SH_ATTRIBUTE_7, SH_ATTRIBUTE_8, SH_ATTRIBUTE_9, SH_ATTRIBUTE_CATEGORY, SH_ATTRIBUTE_DATE_1, SH_ATTRIBUTE_DATE_10, SH_ATTRIBUTE_DATE_2, SH_ATTRIBUTE_DATE_3, SH_ATTRIBUTE_DATE_4, SH_ATTRIBUTE_DATE_5, SH_ATTRIBUTE_DATE_6, SH_ATTRIBUTE_DATE_7, SH_ATTRIBUTE_DATE_8, SH_ATTRIBUTE_DATE_9, SH_ATTRIBUTE_NUMBER_1, SH_ATTRIBUTE_NUMBER_10, SH_ATTRIBUTE_NUMBER_2, SH_ATTRIBUTE_NUMBER_3, SH_ATTRIBUTE_NUMBER_4, SH_ATTRIBUTE_NUMBER_5, SH_ATTRIBUTE_NUMBER_6, SH_ATTRIBUTE_NUMBER_7, SH_ATTRIBUTE_NUMBER_8, SH_ATTRIBUTE_NUMBER_9, SH_ATTRIBUTE_TIMESTAMP_1, SH_ATTRIBUTE_TIMESTAMP_10, SH_ATTRIBUTE_TIMESTAMP_2, SH_ATTRIBUTE_TIMESTAMP_3, SH_ATTRIBUTE_TIMESTAMP_4, SH_ATTRIBUTE_TIMESTAMP_5, SH_ATTRIBUTE_TIMESTAMP_6, SH_ATTRIBUTE_TIMESTAMP_7, SH_ATTRIBUTE_TIMESTAMP_8, SH_ATTRIBUTE_TIMESTAMP_9, SOLDTO_BU_ID, SOURCE_DOC_REV_NUM, START_DATE, SUPPLIER_PARENT_ITEM, SUPPLIER_PART_AUXID, SUPPLIER_REF_NUMBER, SUPPLIER_TOP_MODEL, SVC_AMOUNT_NOTIF_SENT, SVC_COMPLETION_NOTIF_SENT, TAXABLE_FLAG, TAX_ATTRIBUTE_UPDATE_CODE, TAX_CODE_ID, TAX_EXCLUSIVE_PRICE, TAX_NAME, TOP_MODEL_ID, TYPE_1099, UNIT_PRICE, UNORDERED_FLAG, UN_NUMBER_ID, UOM_CODE, VENDOR_PRODUCT_NUM, WORK_ORDER_PRODUCT, _FIVETRAN_DELETED, _FIVETRAN_SYNCED FROM {{ source('outd_ocf_po', 'po_lines_all') }} as SRC 
                        /* This filter is to remove dummy records from the source */
                        where ((LINE_NUM is not NULL and PO_HEADER_ID is not NULL) and _FIVETRAN_DELETED = FALSE)  ),
SRC_pofib          as ( SELECT PO_HEADER_ID, SOLDTO_LE_ID, VENDOR_ID FROM {{ source('outd_ocf_po', 'po_headers_all') }} as SRC 
                        qualify 1= row_number()over(partition by po_header_id order by _fivetran_synced desc, psa_load_dts desc) ),
SRC_a              as ( SELECT BKCC, REC_SRC FROM {{ ref('ref_business_key_collision') }} as SRC  ),
SRC_sup            as ( SELECT SEGMENT_1, VENDOR_ID FROM {{ source('outd_ocf_poz', 'poz_suppliers') }} as SRC 
                        qualify 1= row_number()over(partition by vendor_id order by _fivetran_synced desc, psa_load_dts desc) ),
SRC_itm            as ( SELECT INVENTORY_ITEM_ID, ITEM_NUMBER FROM {{ source('outd_ocf_egp', 'egp_system_items_b') }} as SRC 
                        WHERE  organization_id = 300000034179011 -- master organization 
                        qualify 1= row_number()over(partition by inventory_item_id order by _fivetran_synced desc, psa_load_dts desc) ),
SRC_xle            as ( SELECT LEGAL_ENTITY_ID, LEGAL_ENTITY_IDENTIFIER FROM {{ source('outd_ocf_xle', 'xle_entity_profiles') }} as SRC 
                        qualify 1= row_number()over(partition by legal_entity_id order by _fivetran_synced desc, psa_load_dts desc) )

/*
SRC_polfib         as ( SELECT * FROM outd_ocf_po.po_lines_all )
SRC_pofib          as ( SELECT * FROM outd_ocf_po.po_headers_all )
SRC_a              as ( SELECT * FROM raw_vault.ref_business_key_collision )
SRC_sup            as ( SELECT * FROM outd_ocf_poz.poz_suppliers )
SRC_itm            as ( SELECT * FROM outd_ocf_egp.egp_system_items_b )
SRC_xle            as ( SELECT * FROM outd_ocf_xle.xle_entity_profiles )
*/
---- LOGIC LAYER ----

, LOGIC_polfib as (
    SELECT
        CONCAT_WS('||', COALESCE(PO_HEADER_ID::TEXT, ''), COALESCE(LINE_NUM::TEXT, '')) as                                         PO_ITEM_BK
      , COALESCE(PO_HEADER_ID::TEXT, '')                             as                                       PO_HEADER_BK
      , PO_HEADER_ID
      , LINE_NUM
      , PO_LINE_ID
      , CREATION_DATE
      , SOLDTO_BU_ID
      , SH_ATTRIBUTE_8
      , ATTRIBUTE_10
      , ATTRIBUTE_13
      , SH_ATTRIBUTE_NUMBER_4
      , GLOBAL_ATTRIBUTE_7
      , SVC_COMPLETION_NOTIF_SENT
      , ATTRIBUTE_20
      , TAX_NAME
      , SH_ATTRIBUTE_DATE_6
      , NOTE_TO_VENDOR
      , SHIPPING_UOM_QUANTITY
      , ATTRIBUTE_4
      , SH_ATTRIBUTE_7
      , SH_ATTRIBUTE_13
      , COMPONENT_AMOUNT_RELEASED
      , GLOBAL_ATTRIBUTE_10
      , CONFIGURED_ITEM_FLAG
      , ATTRIBUTE_DATE_6
      , CREDIT_FLAG
      , MANUFACTURER
      , AGING_PERIOD_DAYS
      , FUNDS_STATUS
      , SH_ATTRIBUTE_TIMESTAMP_3
      , ATTRIBUTE_NUMBER_7
      , SH_ATTRIBUTE_NUMBER_2
      , ATTRIBUTE_NUMBER_4
      , GLOBAL_ATTRIBUTE_19
      , PARENT_ITEM_ID
      , SH_ATTRIBUTE_CATEGORY
      , OBJECT_VERSION_NUMBER
      , SH_ATTRIBUTE_TIMESTAMP_1
      , ATTRIBUTE_12
      , GLOBAL_ATTRIBUTE_13
      , SH_ATTRIBUTE_TIMESTAMP_6
      , ATTRIBUTE_DATE_2
      , GLOBAL_ATTRIBUTE_15
      , PROGRAM_APP_NAME
      , COMMITTED_AMOUNT
      , ATTRIBUTE_DATE_10
      , SH_ATTRIBUTE_NUMBER_10
      , CREATED_BY
      , DISCOUNT_TYPE
      , GLOBAL_ATTRIBUTE_DATE_4
      , CANCEL_FLAG
      , OVER_TOLERANCE_ERROR_FLAG
      , ATTRIBUTE_TIMESTAMP_6
      , MARKET_PRICE
      , SH_ATTRIBUTE_TIMESTAMP_9
      , SH_ATTRIBUTE_TIMESTAMP_7
      , NOT_TO_EXCEED_PRICE
      , ATTRIBUTE_NUMBER_9
      , PJC_CONTEXT_CATEGORY
      , SH_ATTRIBUTE_20
      , QTY_RCV_TOLERANCE
      , ATTRIBUTE_NUMBER_3
      , CANCELLED_BY
      , ATTRIBUTE_TIMESTAMP_3
      , CONTRACT_ID
      , JOB_ID
      , DISCOUNT
      , SHIPPING_UOM_CODE
      , CONTRACTOR_LAST_NAME
      , SECONDARY_UOM_CODE
      , DISCOUNT_REASON
      , SH_ATTRIBUTE_NUMBER_7
      , GLOBAL_ATTRIBUTE_DATE_2
      , SH_ATTRIBUTE_2
      , ATTRIBUTE_11
      , CATALOG_NAME
      , ATTRIBUTE_17
      , SH_ATTRIBUTE_DATE_3
      , ATTRIBUTE_TIMESTAMP_8
      , LINE_REFERENCE_NUM
      , GLOBAL_ATTRIBUTE_1
      , GLOBAL_ATTRIBUTE_NUMBER_5
      , SH_ATTRIBUTE_DATE_2
      , CLOSED_REASON
      , LINE_TYPE_ID
      , JOB_DEFINITION_PACKAGE
      , PRICE_TYPE_LOOKUP_CODE
      , ATTRIBUTE_16
      , MANUFACTURER_PART_NUM
      , RECOUPMENT_RATE
      , GLOBAL_ATTRIBUTE_8
      , CANCEL_REASON
      , BID_NUMBER
      , GLOBAL_ATTRIBUTE_3
      , START_DATE
      , UN_NUMBER_ID
      , QUANTITY_COMMITTED
      , ATTRIBUTE_NUMBER_2
      , ALLOW_PRICE_OVERRIDE_FLAG
      , UNIT_PRICE
      , ATTRIBUTE_TIMESTAMP_9
      , BASE_UOM
      , FIRM_DATE
      , SH_ATTRIBUTE_NUMBER_1
      , SH_ATTRIBUTE_DATE_4
      , MIN_RELEASE_AMOUNT
      , SH_ATTRIBUTE_9
      , ATTRIBUTE_18
      , PRC_BU_ID
      , GLOBAL_ATTRIBUTE_NUMBER_3
      , ITEM_REVISION
      , SH_ATTRIBUTE_DATE_8
      , FROM_HEADER_ID
      , HAZARD_CLASS_ID
      , LIST_PRICE
      , SH_ATTRIBUTE_4
      , REQUEST_ID
      , ATTRIBUTE_2
      , AMOUNT_RELEASED
      , TAX_CODE_ID
      , BASE_MODEL_ID
      , ATTRIBUTE_DATE_4
      , TAX_ATTRIBUTE_UPDATE_CODE
      , ATTRIBUTE_TIMESTAMP_7
      , SOURCE_DOC_REV_NUM
      , RETAINAGE_RATE
      , LAST_UPDATE_DATE
      , CONTRACTOR_FIRST_NAME
      , TAX_EXCLUSIVE_PRICE
      , ATTRIBUTE_5
      , ATTRIBUTE_NUMBER_8
      , CONSIGNMENT_LINE_FLAG
      , FROM_LINE_LOCATION_ID
      , WORK_ORDER_PRODUCT
      , REQ_BU_ID
      , SH_ATTRIBUTE_11
      , ATTRIBUTE_NUMBER_5
      , ATTRIBUTE_19
      , SH_ATTRIBUTE_NUMBER_9
      , TOP_MODEL_ID
      , FIRM_STATUS_LOOKUP_CODE
      , SH_ATTRIBUTE_TIMESTAMP_10
      , SH_ATTRIBUTE_10
      , SH_ATTRIBUTE_DATE_9
      , VENDOR_PRODUCT_NUM
      , CAPITAL_EXPENSE_FLAG
      , ITEM_DESCRIPTION
      , ATTRIBUTE_7
      , RETROACTIVE_DATE
      , FROM_LINE_ID
      , SH_ATTRIBUTE_TIMESTAMP_8
      , NEXT_CONSUMPTION_ADV_GEN_DATE
      , PROGRESS_PAYMENT_RATE
      , SH_ATTRIBUTE_DATE_10
      , GLOBAL_ATTRIBUTE_6
      , ATTRIBUTE_8
      , UNORDERED_FLAG
      , SUPPLIER_PARENT_ITEM
      , SH_ATTRIBUTE_14
      , GLOBAL_ATTRIBUTE_5
      , SH_ATTRIBUTE_NUMBER_3
      , ATTRIBUTE_DATE_7
      , ATTRIBUTE_3
      , ATTRIBUTE_DATE_8
      , SH_ATTRIBUTE_19
      , SH_ATTRIBUTE_DATE_1
      , LAST_UPDATE_LOGIN
      , OKE_CONTRACT_HEADER_ID
      , SH_ATTRIBUTE_16
      , ATTRIBUTE_9
      , CANCEL_DATE
      , NEGOTIATED_BY_PREPARER_FLAG
      , ITEM_ID
      , ATTRIBUTE_DATE_3
      , LIST_PRICE_PER_UNIT
      , SECONDARY_QUANTITY
      , ATTRIBUTE_DATE_5
      , SH_ATTRIBUTE_TIMESTAMP_5
      , TYPE_1099
      , ATTRIBUTE_TIMESTAMP_1
      , GLOBAL_ATTRIBUTE_NUMBER_1
      , SH_ATTRIBUTE_15
      , GLOBAL_ATTRIBUTE_DATE_1
      , ATTRIBUTE_TIMESTAMP_5
      , ATTRIBUTE_TIMESTAMP_4
      , JOB_DEFINITION_NAME
      , SH_ATTRIBUTE_17
      , PURCHASE_BASIS
      , GLOBAL_ATTRIBUTE_18
      , GLOBAL_ATTRIBUTE_NUMBER_2
      , SH_ATTRIBUTE_18
      , SH_ATTRIBUTE_6
      , GLOBAL_ATTRIBUTE_DATE_5
      , AUCTION_DISPLAY_NUMBER
      , ATTRIBUTE_14
      , SH_ATTRIBUTE_5
      , ATTRIBUTE_6
      , SH_ATTRIBUTE_DATE_7
      , SH_ATTRIBUTE_1
      , ATTRIBUTE_NUMBER_1
      , GLOBAL_ATTRIBUTE_17
      , GLOBAL_ATTRIBUTE_2
      , OPTIONS_PRICE
      , CLOSED_DATE
      , ORDER_TYPE_LOOKUP_CODE
      , ATTRIBUTE_NUMBER_10
      , EXPIRATION_DATE
      , UOM_CODE
      , ATTRIBUTE_CATEGORY
      , SH_ATTRIBUTE_TIMESTAMP_4
      , PRICE_BREAK_LOOKUP_CODE
      , SH_ATTRIBUTE_12
      , GLOBAL_ATTRIBUTE_20
      , BID_LINE_NUMBER
      , SH_ATTRIBUTE_DATE_5
      , LINE_STATUS
      , ALLOW_DESCRIPTION_UPDATE_FLAG
      , OKE_CONTRACT_VERSION_ID
      , SH_ATTRIBUTE_NUMBER_8
      , CATEGORY_ID
      , ATTRIBUTE_15
      , BASE_QTY
      , ATTRIBUTE_TIMESTAMP_2
      , PROGRAM_NAME
      , MAX_RETAINAGE_AMOUNT
      , BASE_UNIT_PRICE
      , SH_ATTRIBUTE_NUMBER_6
      , REFERENCE_NUM
      , AUCTION_HEADER_ID
      , ATTRIBUTE_DATE_1
      , GLOBAL_ATTRIBUTE_4
      , GLOBAL_ATTRIBUTE_CATEGORY
      , ATTRIBUTE_1
      , SH_ATTRIBUTE_NUMBER_5
      , CLOSED_BY
      , GLOBAL_ATTRIBUTE_16
      , GLOBAL_ATTRIBUTE_9
      , GLOBAL_ATTRIBUTE_11
      , AUCTION_LINE_NUMBER
      , ATTRIBUTE_TIMESTAMP_10
      , GLOBAL_ATTRIBUTE_14
      , SH_ATTRIBUTE_3
      , GOVERNMENT_CONTEXT
      , SH_ATTRIBUTE_TIMESTAMP_2
      , ATTRIBUTE_NUMBER_6
      , TAXABLE_FLAG
      , MANUAL_PRICE_CHANGE_FLAG
      , GLOBAL_ATTRIBUTE_NUMBER_4
      , SVC_AMOUNT_NOTIF_SENT
      , QC_GRADE
      , SUPPLIER_PART_AUXID
      , LAST_UPDATED_PROGRAM
      , AMOUNT
      , PREFERRED_GRADE
      , GLOBAL_ATTRIBUTE_DATE_3
      , MATCHING_BASIS
      , SUPPLIER_TOP_MODEL
      , LAST_UPDATED_BY
      , GLOBAL_ATTRIBUTE_12
      , BASE_MODEL_PRICE
      , ATTRIBUTE_DATE_9
      , SUPPLIER_REF_NUMBER
      , QUANTITY
      , LINE_START_DATE
      , _FIVETRAN_DELETED
      , _FIVETRAN_SYNCED
      , PSA_LOAD_DTS
      , PSA_RECORD_SOURCE
      , PSA_DELETE_IND
      , CONVERT_TIMEZONE('UTC', _FIVETRAN_SYNCED)                    as                                           LOAD_DTS
    FROM SRC_polfib
)

, LOGIC_pofib as (
    SELECT
        PO_HEADER_ID                                                 as                                 POFIB_PO_HEADER_ID
      , VENDOR_ID
      , SOLDTO_LE_ID
    FROM SRC_pofib
)

, LOGIC_a as (
    SELECT
        REC_SRC
      , BKCC
    FROM SRC_a
)

, LOGIC_sup as (
    SELECT
        VENDOR_ID                                                    as                                      SUP_VENDOR_ID
      , SEGMENT_1                                                    as                                       SUP_SEGMENT1
    FROM SRC_sup
)

, LOGIC_itm as (
    SELECT
        INVENTORY_ITEM_ID
      , nullif(trim(ITEM_NUMBER), '')                                                  as                                    ITM_ITEM_NUMBER
    FROM SRC_itm
)

, LOGIC_xle as (
    SELECT
        LEGAL_ENTITY_ID
      , LEGAL_ENTITY_IDENTIFIER
    FROM SRC_xle
)
---- RENAME LAYER ----

, RENAME_polfib as (
    SELECT
        PO_ITEM_BK
      , PO_HEADER_BK
      , PO_HEADER_ID
      , LINE_NUM
      , PO_LINE_ID
      , CREATION_DATE
      , SOLDTO_BU_ID
      , SH_ATTRIBUTE_8
      , ATTRIBUTE_10
      , ATTRIBUTE_13
      , SH_ATTRIBUTE_NUMBER_4
      , GLOBAL_ATTRIBUTE_7
      , SVC_COMPLETION_NOTIF_SENT
      , ATTRIBUTE_20
      , TAX_NAME
      , SH_ATTRIBUTE_DATE_6
      , NOTE_TO_VENDOR
      , SHIPPING_UOM_QUANTITY
      , ATTRIBUTE_4
      , SH_ATTRIBUTE_7
      , SH_ATTRIBUTE_13
      , COMPONENT_AMOUNT_RELEASED
      , GLOBAL_ATTRIBUTE_10
      , CONFIGURED_ITEM_FLAG
      , ATTRIBUTE_DATE_6
      , CREDIT_FLAG
      , MANUFACTURER
      , AGING_PERIOD_DAYS
      , FUNDS_STATUS
      , SH_ATTRIBUTE_TIMESTAMP_3
      , ATTRIBUTE_NUMBER_7
      , SH_ATTRIBUTE_NUMBER_2
      , ATTRIBUTE_NUMBER_4
      , GLOBAL_ATTRIBUTE_19
      , PARENT_ITEM_ID
      , SH_ATTRIBUTE_CATEGORY
      , OBJECT_VERSION_NUMBER
      , SH_ATTRIBUTE_TIMESTAMP_1
      , ATTRIBUTE_12
      , GLOBAL_ATTRIBUTE_13
      , SH_ATTRIBUTE_TIMESTAMP_6
      , ATTRIBUTE_DATE_2
      , GLOBAL_ATTRIBUTE_15
      , PROGRAM_APP_NAME
      , COMMITTED_AMOUNT
      , ATTRIBUTE_DATE_10
      , SH_ATTRIBUTE_NUMBER_10
      , CREATED_BY
      , DISCOUNT_TYPE
      , GLOBAL_ATTRIBUTE_DATE_4
      , CANCEL_FLAG
      , OVER_TOLERANCE_ERROR_FLAG
      , ATTRIBUTE_TIMESTAMP_6
      , MARKET_PRICE
      , SH_ATTRIBUTE_TIMESTAMP_9
      , SH_ATTRIBUTE_TIMESTAMP_7
      , NOT_TO_EXCEED_PRICE
      , ATTRIBUTE_NUMBER_9
      , PJC_CONTEXT_CATEGORY
      , SH_ATTRIBUTE_20
      , QTY_RCV_TOLERANCE
      , ATTRIBUTE_NUMBER_3
      , CANCELLED_BY
      , ATTRIBUTE_TIMESTAMP_3
      , CONTRACT_ID
      , JOB_ID
      , DISCOUNT
      , SHIPPING_UOM_CODE
      , CONTRACTOR_LAST_NAME
      , SECONDARY_UOM_CODE
      , DISCOUNT_REASON
      , SH_ATTRIBUTE_NUMBER_7
      , GLOBAL_ATTRIBUTE_DATE_2
      , SH_ATTRIBUTE_2
      , ATTRIBUTE_11
      , CATALOG_NAME
      , ATTRIBUTE_17
      , SH_ATTRIBUTE_DATE_3
      , ATTRIBUTE_TIMESTAMP_8
      , LINE_REFERENCE_NUM
      , GLOBAL_ATTRIBUTE_1
      , GLOBAL_ATTRIBUTE_NUMBER_5
      , SH_ATTRIBUTE_DATE_2
      , CLOSED_REASON
      , LINE_TYPE_ID
      , JOB_DEFINITION_PACKAGE
      , PRICE_TYPE_LOOKUP_CODE
      , ATTRIBUTE_16
      , MANUFACTURER_PART_NUM
      , RECOUPMENT_RATE
      , GLOBAL_ATTRIBUTE_8
      , CANCEL_REASON
      , BID_NUMBER
      , GLOBAL_ATTRIBUTE_3
      , START_DATE
      , UN_NUMBER_ID
      , QUANTITY_COMMITTED
      , ATTRIBUTE_NUMBER_2
      , ALLOW_PRICE_OVERRIDE_FLAG
      , UNIT_PRICE
      , ATTRIBUTE_TIMESTAMP_9
      , BASE_UOM
      , FIRM_DATE
      , SH_ATTRIBUTE_NUMBER_1
      , SH_ATTRIBUTE_DATE_4
      , MIN_RELEASE_AMOUNT
      , SH_ATTRIBUTE_9
      , ATTRIBUTE_18
      , PRC_BU_ID
      , GLOBAL_ATTRIBUTE_NUMBER_3
      , ITEM_REVISION
      , SH_ATTRIBUTE_DATE_8
      , FROM_HEADER_ID
      , HAZARD_CLASS_ID
      , LIST_PRICE
      , SH_ATTRIBUTE_4
      , REQUEST_ID
      , ATTRIBUTE_2
      , AMOUNT_RELEASED
      , TAX_CODE_ID
      , BASE_MODEL_ID
      , ATTRIBUTE_DATE_4
      , TAX_ATTRIBUTE_UPDATE_CODE
      , ATTRIBUTE_TIMESTAMP_7
      , SOURCE_DOC_REV_NUM
      , RETAINAGE_RATE
      , LAST_UPDATE_DATE
      , CONTRACTOR_FIRST_NAME
      , TAX_EXCLUSIVE_PRICE
      , ATTRIBUTE_5
      , ATTRIBUTE_NUMBER_8
      , CONSIGNMENT_LINE_FLAG
      , FROM_LINE_LOCATION_ID
      , WORK_ORDER_PRODUCT
      , REQ_BU_ID
      , SH_ATTRIBUTE_11
      , ATTRIBUTE_NUMBER_5
      , ATTRIBUTE_19
      , SH_ATTRIBUTE_NUMBER_9
      , TOP_MODEL_ID
      , FIRM_STATUS_LOOKUP_CODE
      , SH_ATTRIBUTE_TIMESTAMP_10
      , SH_ATTRIBUTE_10
      , SH_ATTRIBUTE_DATE_9
      , VENDOR_PRODUCT_NUM
      , CAPITAL_EXPENSE_FLAG
      , ITEM_DESCRIPTION
      , ATTRIBUTE_7
      , RETROACTIVE_DATE
      , FROM_LINE_ID
      , SH_ATTRIBUTE_TIMESTAMP_8
      , NEXT_CONSUMPTION_ADV_GEN_DATE
      , PROGRESS_PAYMENT_RATE
      , SH_ATTRIBUTE_DATE_10
      , GLOBAL_ATTRIBUTE_6
      , ATTRIBUTE_8
      , UNORDERED_FLAG
      , SUPPLIER_PARENT_ITEM
      , SH_ATTRIBUTE_14
      , GLOBAL_ATTRIBUTE_5
      , SH_ATTRIBUTE_NUMBER_3
      , ATTRIBUTE_DATE_7
      , ATTRIBUTE_3
      , ATTRIBUTE_DATE_8
      , SH_ATTRIBUTE_19
      , SH_ATTRIBUTE_DATE_1
      , LAST_UPDATE_LOGIN
      , OKE_CONTRACT_HEADER_ID
      , SH_ATTRIBUTE_16
      , ATTRIBUTE_9
      , CANCEL_DATE
      , NEGOTIATED_BY_PREPARER_FLAG
      , ITEM_ID
      , ATTRIBUTE_DATE_3
      , LIST_PRICE_PER_UNIT
      , SECONDARY_QUANTITY
      , ATTRIBUTE_DATE_5
      , SH_ATTRIBUTE_TIMESTAMP_5
      , TYPE_1099
      , ATTRIBUTE_TIMESTAMP_1
      , GLOBAL_ATTRIBUTE_NUMBER_1
      , SH_ATTRIBUTE_15
      , GLOBAL_ATTRIBUTE_DATE_1
      , ATTRIBUTE_TIMESTAMP_5
      , ATTRIBUTE_TIMESTAMP_4
      , JOB_DEFINITION_NAME
      , SH_ATTRIBUTE_17
      , PURCHASE_BASIS
      , GLOBAL_ATTRIBUTE_18
      , GLOBAL_ATTRIBUTE_NUMBER_2
      , SH_ATTRIBUTE_18
      , SH_ATTRIBUTE_6
      , GLOBAL_ATTRIBUTE_DATE_5
      , AUCTION_DISPLAY_NUMBER
      , ATTRIBUTE_14
      , SH_ATTRIBUTE_5
      , ATTRIBUTE_6
      , SH_ATTRIBUTE_DATE_7
      , SH_ATTRIBUTE_1
      , ATTRIBUTE_NUMBER_1
      , GLOBAL_ATTRIBUTE_17
      , GLOBAL_ATTRIBUTE_2
      , OPTIONS_PRICE
      , CLOSED_DATE
      , ORDER_TYPE_LOOKUP_CODE
      , ATTRIBUTE_NUMBER_10
      , EXPIRATION_DATE
      , UOM_CODE
      , ATTRIBUTE_CATEGORY
      , SH_ATTRIBUTE_TIMESTAMP_4
      , PRICE_BREAK_LOOKUP_CODE
      , SH_ATTRIBUTE_12
      , GLOBAL_ATTRIBUTE_20
      , BID_LINE_NUMBER
      , SH_ATTRIBUTE_DATE_5
      , LINE_STATUS
      , ALLOW_DESCRIPTION_UPDATE_FLAG
      , OKE_CONTRACT_VERSION_ID
      , SH_ATTRIBUTE_NUMBER_8
      , CATEGORY_ID
      , ATTRIBUTE_15
      , BASE_QTY
      , ATTRIBUTE_TIMESTAMP_2
      , PROGRAM_NAME
      , MAX_RETAINAGE_AMOUNT
      , BASE_UNIT_PRICE
      , SH_ATTRIBUTE_NUMBER_6
      , REFERENCE_NUM
      , AUCTION_HEADER_ID
      , ATTRIBUTE_DATE_1
      , GLOBAL_ATTRIBUTE_4
      , GLOBAL_ATTRIBUTE_CATEGORY
      , ATTRIBUTE_1
      , SH_ATTRIBUTE_NUMBER_5
      , CLOSED_BY
      , GLOBAL_ATTRIBUTE_16
      , GLOBAL_ATTRIBUTE_9
      , GLOBAL_ATTRIBUTE_11
      , AUCTION_LINE_NUMBER
      , ATTRIBUTE_TIMESTAMP_10
      , GLOBAL_ATTRIBUTE_14
      , SH_ATTRIBUTE_3
      , GOVERNMENT_CONTEXT
      , SH_ATTRIBUTE_TIMESTAMP_2
      , ATTRIBUTE_NUMBER_6
      , TAXABLE_FLAG
      , MANUAL_PRICE_CHANGE_FLAG
      , GLOBAL_ATTRIBUTE_NUMBER_4
      , SVC_AMOUNT_NOTIF_SENT
      , QC_GRADE
      , SUPPLIER_PART_AUXID
      , LAST_UPDATED_PROGRAM
      , AMOUNT
      , PREFERRED_GRADE
      , GLOBAL_ATTRIBUTE_DATE_3
      , MATCHING_BASIS
      , SUPPLIER_TOP_MODEL
      , LAST_UPDATED_BY
      , GLOBAL_ATTRIBUTE_12
      , BASE_MODEL_PRICE
      , ATTRIBUTE_DATE_9
      , SUPPLIER_REF_NUMBER
      , QUANTITY
      , LINE_START_DATE
      , _FIVETRAN_DELETED
      , _FIVETRAN_SYNCED
      , PSA_LOAD_DTS
      , PSA_RECORD_SOURCE
      , PSA_DELETE_IND
      , LOAD_DTS
    FROM LOGIC_polfib
)

, RENAME_a as (
    SELECT
        REC_SRC
      , BKCC
    FROM LOGIC_a
)

, RENAME_sup as (
    SELECT
        SUP_VENDOR_ID
      , SUP_SEGMENT1
    FROM LOGIC_sup
)

, RENAME_pofib as (
    SELECT
        POFIB_PO_HEADER_ID
      , VENDOR_ID
      , SOLDTO_LE_ID
    FROM LOGIC_pofib
)

, RENAME_itm as (
    SELECT
        INVENTORY_ITEM_ID
      , ITM_ITEM_NUMBER
    FROM LOGIC_itm
)

, RENAME_xle as (
    SELECT
        LEGAL_ENTITY_ID
      , LEGAL_ENTITY_IDENTIFIER
    FROM LOGIC_xle
)
---- FILTER LAYER ----

, FILTER_polfib as (
    SELECT *
    FROM RENAME_polfib
)

, FILTER_pofib as (
    SELECT *
    FROM RENAME_pofib
)

, FILTER_a as (
    SELECT *
    FROM RENAME_a
    WHERE rec_src = 'USCLOUD.ORCL.OCFPRD.PO_LINES_ALL'
)

, FILTER_sup as (
    SELECT *
    FROM RENAME_sup
)

, FILTER_itm as (
    SELECT *
    FROM RENAME_itm
)

, FILTER_xle as (
    SELECT *
    FROM RENAME_xle
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM FILTER_polfib
    LEFT JOIN FILTER_pofib
        ON FILTER_polfib.PO_HEADER_ID = FILTER_pofib.POFIB_PO_HEADER_ID
    INNER JOIN FILTER_a
        ON '1' = '1'
    LEFT JOIN FILTER_itm
        ON FILTER_polfib.ITEM_ID = FILTER_itm.INVENTORY_ITEM_ID 
    LEFT JOIN FILTER_sup
        ON FILTER_pofib.VENDOR_ID = FILTER_sup.sup_vendor_id
    LEFT JOIN FILTER_xle
        ON FILTER_pofib.SOLDTO_LE_ID = FILTER_xle.LEGAL_ENTITY_ID
)

---- FINAL LAYER ----
SELECT
          PO_ITEM_BK
        , PO_HEADER_BK
        , PO_HEADER_ID
        , LINE_NUM
        , PO_LINE_ID
        , CREATION_DATE
        , SOLDTO_BU_ID
        , SH_ATTRIBUTE_8
        , ATTRIBUTE_10
        , ATTRIBUTE_13
        , SH_ATTRIBUTE_NUMBER_4
        , GLOBAL_ATTRIBUTE_7
        , SVC_COMPLETION_NOTIF_SENT
        , ATTRIBUTE_20
        , TAX_NAME
        , SH_ATTRIBUTE_DATE_6
        , NOTE_TO_VENDOR
        , SHIPPING_UOM_QUANTITY
        , ATTRIBUTE_4
        , SH_ATTRIBUTE_7
        , SH_ATTRIBUTE_13
        , COMPONENT_AMOUNT_RELEASED
        , GLOBAL_ATTRIBUTE_10
        , CONFIGURED_ITEM_FLAG
        , ATTRIBUTE_DATE_6
        , CREDIT_FLAG
        , MANUFACTURER
        , AGING_PERIOD_DAYS
        , FUNDS_STATUS
        , SH_ATTRIBUTE_TIMESTAMP_3
        , ATTRIBUTE_NUMBER_7
        , SH_ATTRIBUTE_NUMBER_2
        , ATTRIBUTE_NUMBER_4
        , GLOBAL_ATTRIBUTE_19
        , PARENT_ITEM_ID
        , SH_ATTRIBUTE_CATEGORY
        , OBJECT_VERSION_NUMBER
        , SH_ATTRIBUTE_TIMESTAMP_1
        , ATTRIBUTE_12
        , GLOBAL_ATTRIBUTE_13
        , SH_ATTRIBUTE_TIMESTAMP_6
        , ATTRIBUTE_DATE_2
        , GLOBAL_ATTRIBUTE_15
        , PROGRAM_APP_NAME
        , COMMITTED_AMOUNT
        , ATTRIBUTE_DATE_10
        , SH_ATTRIBUTE_NUMBER_10
        , CREATED_BY
        , DISCOUNT_TYPE
        , GLOBAL_ATTRIBUTE_DATE_4
        , CANCEL_FLAG
        , OVER_TOLERANCE_ERROR_FLAG
        , ATTRIBUTE_TIMESTAMP_6
        , MARKET_PRICE
        , SH_ATTRIBUTE_TIMESTAMP_9
        , SH_ATTRIBUTE_TIMESTAMP_7
        , NOT_TO_EXCEED_PRICE
        , ATTRIBUTE_NUMBER_9
        , PJC_CONTEXT_CATEGORY
        , SH_ATTRIBUTE_20
        , QTY_RCV_TOLERANCE
        , ATTRIBUTE_NUMBER_3
        , CANCELLED_BY
        , ATTRIBUTE_TIMESTAMP_3
        , CONTRACT_ID
        , JOB_ID
        , DISCOUNT
        , SHIPPING_UOM_CODE
        , CONTRACTOR_LAST_NAME
        , SECONDARY_UOM_CODE
        , DISCOUNT_REASON
        , SH_ATTRIBUTE_NUMBER_7
        , GLOBAL_ATTRIBUTE_DATE_2
        , SH_ATTRIBUTE_2
        , ATTRIBUTE_11
        , CATALOG_NAME
        , ATTRIBUTE_17
        , SH_ATTRIBUTE_DATE_3
        , ATTRIBUTE_TIMESTAMP_8
        , LINE_REFERENCE_NUM
        , GLOBAL_ATTRIBUTE_1
        , GLOBAL_ATTRIBUTE_NUMBER_5
        , SH_ATTRIBUTE_DATE_2
        , CLOSED_REASON
        , LINE_TYPE_ID
        , JOB_DEFINITION_PACKAGE
        , PRICE_TYPE_LOOKUP_CODE
        , ATTRIBUTE_16
        , MANUFACTURER_PART_NUM
        , RECOUPMENT_RATE
        , GLOBAL_ATTRIBUTE_8
        , CANCEL_REASON
        , BID_NUMBER
        , GLOBAL_ATTRIBUTE_3
        , START_DATE
        , UN_NUMBER_ID
        , QUANTITY_COMMITTED
        , ATTRIBUTE_NUMBER_2
        , ALLOW_PRICE_OVERRIDE_FLAG
        , UNIT_PRICE
        , ATTRIBUTE_TIMESTAMP_9
        , BASE_UOM
        , FIRM_DATE
        , SH_ATTRIBUTE_NUMBER_1
        , SH_ATTRIBUTE_DATE_4
        , MIN_RELEASE_AMOUNT
        , SH_ATTRIBUTE_9
        , ATTRIBUTE_18
        , PRC_BU_ID
        , GLOBAL_ATTRIBUTE_NUMBER_3
        , ITEM_REVISION
        , SH_ATTRIBUTE_DATE_8
        , FROM_HEADER_ID
        , HAZARD_CLASS_ID
        , LIST_PRICE
        , SH_ATTRIBUTE_4
        , REQUEST_ID
        , ATTRIBUTE_2
        , AMOUNT_RELEASED
        , TAX_CODE_ID
        , BASE_MODEL_ID
        , ATTRIBUTE_DATE_4
        , TAX_ATTRIBUTE_UPDATE_CODE
        , ATTRIBUTE_TIMESTAMP_7
        , SOURCE_DOC_REV_NUM
        , RETAINAGE_RATE
        , LAST_UPDATE_DATE
        , CONTRACTOR_FIRST_NAME
        , TAX_EXCLUSIVE_PRICE
        , ATTRIBUTE_5
        , ATTRIBUTE_NUMBER_8
        , CONSIGNMENT_LINE_FLAG
        , FROM_LINE_LOCATION_ID
        , WORK_ORDER_PRODUCT
        , REQ_BU_ID
        , SH_ATTRIBUTE_11
        , ATTRIBUTE_NUMBER_5
        , ATTRIBUTE_19
        , SH_ATTRIBUTE_NUMBER_9
        , TOP_MODEL_ID
        , FIRM_STATUS_LOOKUP_CODE
        , SH_ATTRIBUTE_TIMESTAMP_10
        , SH_ATTRIBUTE_10
        , SH_ATTRIBUTE_DATE_9
        , VENDOR_PRODUCT_NUM
        , CAPITAL_EXPENSE_FLAG
        , ITEM_DESCRIPTION
        , ATTRIBUTE_7
        , RETROACTIVE_DATE
        , FROM_LINE_ID
        , SH_ATTRIBUTE_TIMESTAMP_8
        , NEXT_CONSUMPTION_ADV_GEN_DATE
        , PROGRESS_PAYMENT_RATE
        , SH_ATTRIBUTE_DATE_10
        , GLOBAL_ATTRIBUTE_6
        , ATTRIBUTE_8
        , UNORDERED_FLAG
        , SUPPLIER_PARENT_ITEM
        , SH_ATTRIBUTE_14
        , GLOBAL_ATTRIBUTE_5
        , SH_ATTRIBUTE_NUMBER_3
        , ATTRIBUTE_DATE_7
        , ATTRIBUTE_3
        , ATTRIBUTE_DATE_8
        , SH_ATTRIBUTE_19
        , SH_ATTRIBUTE_DATE_1
        , LAST_UPDATE_LOGIN
        , OKE_CONTRACT_HEADER_ID
        , SH_ATTRIBUTE_16
        , ATTRIBUTE_9
        , CANCEL_DATE
        , NEGOTIATED_BY_PREPARER_FLAG
        , ITEM_ID
        , ATTRIBUTE_DATE_3
        , LIST_PRICE_PER_UNIT
        , SECONDARY_QUANTITY
        , ATTRIBUTE_DATE_5
        , SH_ATTRIBUTE_TIMESTAMP_5
        , TYPE_1099
        , ATTRIBUTE_TIMESTAMP_1
        , GLOBAL_ATTRIBUTE_NUMBER_1
        , SH_ATTRIBUTE_15
        , GLOBAL_ATTRIBUTE_DATE_1
        , ATTRIBUTE_TIMESTAMP_5
        , ATTRIBUTE_TIMESTAMP_4
        , JOB_DEFINITION_NAME
        , SH_ATTRIBUTE_17
        , PURCHASE_BASIS
        , GLOBAL_ATTRIBUTE_18
        , GLOBAL_ATTRIBUTE_NUMBER_2
        , SH_ATTRIBUTE_18
        , SH_ATTRIBUTE_6
        , GLOBAL_ATTRIBUTE_DATE_5
        , AUCTION_DISPLAY_NUMBER
        , ATTRIBUTE_14
        , SH_ATTRIBUTE_5
        , ATTRIBUTE_6
        , SH_ATTRIBUTE_DATE_7
        , SH_ATTRIBUTE_1
        , ATTRIBUTE_NUMBER_1
        , GLOBAL_ATTRIBUTE_17
        , GLOBAL_ATTRIBUTE_2
        , OPTIONS_PRICE
        , CLOSED_DATE
        , ORDER_TYPE_LOOKUP_CODE
        , ATTRIBUTE_NUMBER_10
        , EXPIRATION_DATE
        , UOM_CODE
        , ATTRIBUTE_CATEGORY
        , SH_ATTRIBUTE_TIMESTAMP_4
        , PRICE_BREAK_LOOKUP_CODE
        , SH_ATTRIBUTE_12
        , GLOBAL_ATTRIBUTE_20
        , BID_LINE_NUMBER
        , SH_ATTRIBUTE_DATE_5
        , LINE_STATUS
        , ALLOW_DESCRIPTION_UPDATE_FLAG
        , OKE_CONTRACT_VERSION_ID
        , SH_ATTRIBUTE_NUMBER_8
        , CATEGORY_ID
        , ATTRIBUTE_15
        , BASE_QTY
        , ATTRIBUTE_TIMESTAMP_2
        , PROGRAM_NAME
        , MAX_RETAINAGE_AMOUNT
        , BASE_UNIT_PRICE
        , SH_ATTRIBUTE_NUMBER_6
        , REFERENCE_NUM
        , AUCTION_HEADER_ID
        , ATTRIBUTE_DATE_1
        , GLOBAL_ATTRIBUTE_4
        , GLOBAL_ATTRIBUTE_CATEGORY
        , ATTRIBUTE_1
        , SH_ATTRIBUTE_NUMBER_5
        , CLOSED_BY
        , GLOBAL_ATTRIBUTE_16
        , GLOBAL_ATTRIBUTE_9
        , GLOBAL_ATTRIBUTE_11
        , AUCTION_LINE_NUMBER
        , ATTRIBUTE_TIMESTAMP_10
        , GLOBAL_ATTRIBUTE_14
        , SH_ATTRIBUTE_3
        , GOVERNMENT_CONTEXT
        , SH_ATTRIBUTE_TIMESTAMP_2
        , ATTRIBUTE_NUMBER_6
        , TAXABLE_FLAG
        , MANUAL_PRICE_CHANGE_FLAG
        , GLOBAL_ATTRIBUTE_NUMBER_4
        , SVC_AMOUNT_NOTIF_SENT
        , QC_GRADE
        , SUPPLIER_PART_AUXID
        , LAST_UPDATED_PROGRAM
        , AMOUNT
        , PREFERRED_GRADE
        , GLOBAL_ATTRIBUTE_DATE_3
        , MATCHING_BASIS
        , SUPPLIER_TOP_MODEL
        , LAST_UPDATED_BY
        , GLOBAL_ATTRIBUTE_12
        , BASE_MODEL_PRICE
        , ATTRIBUTE_DATE_9
        , SUPPLIER_REF_NUMBER
        , QUANTITY
        , LINE_START_DATE
        , _FIVETRAN_DELETED
        , _FIVETRAN_SYNCED
        , PSA_LOAD_DTS
        , PSA_RECORD_SOURCE
        , PSA_DELETE_IND
        , LOAD_DTS
        ,     IFF(ITM_ITEM_NUMBER IS NULL, '-2', CONCAT_WS('||',  ITM_ITEM_NUMBER, BKCC)) as DRVD_ITEM_BKCC
        ,     IFF( SUP_SEGMENT1 IS NULL, '-2', CONCAT_WS('||',  SUP_SEGMENT1, BKCC)) as DRVD_SUPPLIER_BKCC
        ,     IFF(LEGAL_ENTITY_IDENTIFIER IS NULL, '-2', CONCAT_WS('||', LEGAL_ENTITY_IDENTIFIER, BKCC)) as DRVD_LEGAL_ENTITY_BKCC
        , REC_SRC
        , BKCC
        , MD5_BINARY(UPPER(CONCAT_WS('||',
          COALESCE(NULLIF(TRIM(CAST(PO_HEADER_ID as VARCHAR)),''), '^^')
        , COALESCE(NULLIF(TRIM(CAST(LINE_NUM as VARCHAR)),''), '^^')
        , COALESCE(NULLIF(TRIM(CAST(BKCC as VARCHAR)),''), '^^')
        ))) as PO_ITEM_HK
        , MD5_BINARY(UPPER(CONCAT_WS('||',
          COALESCE(NULLIF(TRIM(CAST(PO_HEADER_ID as VARCHAR)),''), '^^')
        , COALESCE(NULLIF(TRIM(CAST(LINE_NUM as VARCHAR)),''), '^^')
        , COALESCE(NULLIF(TRIM(CAST(SUP_SEGMENT1 as VARCHAR)),''), '^^')
        , COALESCE(NULLIF(TRIM(CAST(ITM_ITEM_NUMBER as VARCHAR)),''), '^^')
        , COALESCE(NULLIF(TRIM(CAST(LEGAL_ENTITY_IDENTIFIER as VARCHAR)),''), '^^')
        , COALESCE(NULLIF(TRIM(CAST(BKCC as VARCHAR)),''), '^^')
        ))) as LNK_PO_ITEM_HK
        , MD5_BINARY(UPPER(CONCAT_WS('||',
          COALESCE(NULLIF(TRIM(CAST(PO_HEADER_ID as VARCHAR)),''), '^^')
        , COALESCE(NULLIF(TRIM(CAST(BKCC as VARCHAR)),''), '^^')
        ))) as PO_HEADER_HK
        , MD5_BINARY(UPPER(CONCAT_WS('||',
          COALESCE(NULLIF(TRIM(CAST(DRVD_SUPPLIER_BKCC as VARCHAR)),''), '^^')
        ))) as SUPPLIER_HK
        , MD5_BINARY(UPPER(CONCAT_WS('||',
          COALESCE(NULLIF(TRIM(CAST(DRVD_ITEM_BKCC as VARCHAR)),''), '^^')
        ))) as ITEM_HK
        , MD5_BINARY(UPPER(CONCAT_WS('||',
          COALESCE(NULLIF(TRIM(CAST(DRVD_LEGAL_ENTITY_BKCC as VARCHAR)),''), '^^')
        ))) as LEGAL_ENTITY_HK
        , MD5_BINARY(UPPER(CONCAT_WS('||',
          COALESCE(NULLIF(TRIM(CAST('-2' as VARCHAR)),''), '^^')
        ))) as PURCHASING_RECORD_HK
        , MD5_BINARY(UPPER(CONCAT_WS('||',
          COALESCE(NULLIF(TRIM(CAST('-2' as VARCHAR)),''), '^^')
        ))) as PURCHASING_ORG_HK
        , MD5_BINARY(UPPER(NULLIF(CONCAT(
              IFNULL(TRIM(PO_LINE_ID::text), '^^') 
            , '||', IFNULL(TRIM(CREATION_DATE::text), '^^') 
            , '||', IFNULL(TRIM(SOLDTO_BU_ID::text), '^^') 
            , '||', IFNULL(TRIM(SH_ATTRIBUTE_8::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE_10::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE_13::text), '^^') 
            , '||', IFNULL(TRIM(SH_ATTRIBUTE_NUMBER_4::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE_7::text), '^^') 
            , '||', IFNULL(TRIM(SVC_COMPLETION_NOTIF_SENT::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE_20::text), '^^') 
            , '||', IFNULL(TRIM(TAX_NAME::text), '^^') 
            , '||', IFNULL(TRIM(SH_ATTRIBUTE_DATE_6::text), '^^') 
            , '||', IFNULL(TRIM(NOTE_TO_VENDOR::text), '^^') 
            , '||', IFNULL(TRIM(SHIPPING_UOM_QUANTITY::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE_4::text), '^^') 
            , '||', IFNULL(TRIM(SH_ATTRIBUTE_7::text), '^^') 
            , '||', IFNULL(TRIM(SH_ATTRIBUTE_13::text), '^^') 
            , '||', IFNULL(TRIM(COMPONENT_AMOUNT_RELEASED::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE_10::text), '^^') 
            , '||', IFNULL(TRIM(CONFIGURED_ITEM_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE_DATE_6::text), '^^') 
            , '||', IFNULL(TRIM(CREDIT_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(MANUFACTURER::text), '^^') 
            , '||', IFNULL(TRIM(AGING_PERIOD_DAYS::text), '^^') 
            , '||', IFNULL(TRIM(FUNDS_STATUS::text), '^^') 
            , '||', IFNULL(TRIM(SH_ATTRIBUTE_TIMESTAMP_3::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE_NUMBER_7::text), '^^') 
            , '||', IFNULL(TRIM(SH_ATTRIBUTE_NUMBER_2::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE_NUMBER_4::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE_19::text), '^^') 
            , '||', IFNULL(TRIM(PARENT_ITEM_ID::text), '^^') 
            , '||', IFNULL(TRIM(SH_ATTRIBUTE_CATEGORY::text), '^^') 
            , '||', IFNULL(TRIM(OBJECT_VERSION_NUMBER::text), '^^') 
            , '||', IFNULL(TRIM(SH_ATTRIBUTE_TIMESTAMP_1::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE_12::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE_13::text), '^^') 
            , '||', IFNULL(TRIM(SH_ATTRIBUTE_TIMESTAMP_6::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE_DATE_2::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE_15::text), '^^') 
            , '||', IFNULL(TRIM(PROGRAM_APP_NAME::text), '^^') 
            , '||', IFNULL(TRIM(COMMITTED_AMOUNT::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE_DATE_10::text), '^^') 
            , '||', IFNULL(TRIM(SH_ATTRIBUTE_NUMBER_10::text), '^^') 
            , '||', IFNULL(TRIM(CREATED_BY::text), '^^') 
            , '||', IFNULL(TRIM(DISCOUNT_TYPE::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE_DATE_4::text), '^^') 
            , '||', IFNULL(TRIM(CANCEL_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(OVER_TOLERANCE_ERROR_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE_TIMESTAMP_6::text), '^^') 
            , '||', IFNULL(TRIM(MARKET_PRICE::text), '^^') 
            , '||', IFNULL(TRIM(SH_ATTRIBUTE_TIMESTAMP_9::text), '^^') 
            , '||', IFNULL(TRIM(SH_ATTRIBUTE_TIMESTAMP_7::text), '^^') 
            , '||', IFNULL(TRIM(NOT_TO_EXCEED_PRICE::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE_NUMBER_9::text), '^^') 
            , '||', IFNULL(TRIM(PJC_CONTEXT_CATEGORY::text), '^^') 
            , '||', IFNULL(TRIM(SH_ATTRIBUTE_20::text), '^^') 
            , '||', IFNULL(TRIM(QTY_RCV_TOLERANCE::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE_NUMBER_3::text), '^^') 
            , '||', IFNULL(TRIM(CANCELLED_BY::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE_TIMESTAMP_3::text), '^^') 
            , '||', IFNULL(TRIM(CONTRACT_ID::text), '^^') 
            , '||', IFNULL(TRIM(JOB_ID::text), '^^') 
            , '||', IFNULL(TRIM(DISCOUNT::text), '^^') 
            , '||', IFNULL(TRIM(SHIPPING_UOM_CODE::text), '^^') 
            , '||', IFNULL(TRIM(CONTRACTOR_LAST_NAME::text), '^^') 
            , '||', IFNULL(TRIM(SECONDARY_UOM_CODE::text), '^^') 
            , '||', IFNULL(TRIM(DISCOUNT_REASON::text), '^^') 
            , '||', IFNULL(TRIM(SH_ATTRIBUTE_NUMBER_7::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE_DATE_2::text), '^^') 
            , '||', IFNULL(TRIM(SH_ATTRIBUTE_2::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE_11::text), '^^') 
            , '||', IFNULL(TRIM(CATALOG_NAME::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE_17::text), '^^') 
            , '||', IFNULL(TRIM(SH_ATTRIBUTE_DATE_3::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE_TIMESTAMP_8::text), '^^') 
            , '||', IFNULL(TRIM(LINE_REFERENCE_NUM::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE_1::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE_NUMBER_5::text), '^^') 
            , '||', IFNULL(TRIM(SH_ATTRIBUTE_DATE_2::text), '^^') 
            , '||', IFNULL(TRIM(CLOSED_REASON::text), '^^') 
            , '||', IFNULL(TRIM(LINE_TYPE_ID::text), '^^') 
            , '||', IFNULL(TRIM(JOB_DEFINITION_PACKAGE::text), '^^') 
            , '||', IFNULL(TRIM(PRICE_TYPE_LOOKUP_CODE::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE_16::text), '^^') 
            , '||', IFNULL(TRIM(MANUFACTURER_PART_NUM::text), '^^') 
            , '||', IFNULL(TRIM(RECOUPMENT_RATE::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE_8::text), '^^') 
            , '||', IFNULL(TRIM(CANCEL_REASON::text), '^^') 
            , '||', IFNULL(TRIM(BID_NUMBER::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE_3::text), '^^') 
            , '||', IFNULL(TRIM(START_DATE::text), '^^') 
            , '||', IFNULL(TRIM(UN_NUMBER_ID::text), '^^') 
            , '||', IFNULL(TRIM(QUANTITY_COMMITTED::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE_NUMBER_2::text), '^^') 
            , '||', IFNULL(TRIM(ALLOW_PRICE_OVERRIDE_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(UNIT_PRICE::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE_TIMESTAMP_9::text), '^^') 
            , '||', IFNULL(TRIM(BASE_UOM::text), '^^') 
            , '||', IFNULL(TRIM(FIRM_DATE::text), '^^') 
            , '||', IFNULL(TRIM(SH_ATTRIBUTE_NUMBER_1::text), '^^') 
            , '||', IFNULL(TRIM(SH_ATTRIBUTE_DATE_4::text), '^^') 
            , '||', IFNULL(TRIM(MIN_RELEASE_AMOUNT::text), '^^') 
            , '||', IFNULL(TRIM(SH_ATTRIBUTE_9::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE_18::text), '^^') 
            , '||', IFNULL(TRIM(PRC_BU_ID::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE_NUMBER_3::text), '^^') 
            , '||', IFNULL(TRIM(ITEM_REVISION::text), '^^') 
            , '||', IFNULL(TRIM(SH_ATTRIBUTE_DATE_8::text), '^^') 
            , '||', IFNULL(TRIM(FROM_HEADER_ID::text), '^^') 
            , '||', IFNULL(TRIM(HAZARD_CLASS_ID::text), '^^') 
            , '||', IFNULL(TRIM(LIST_PRICE::text), '^^') 
            , '||', IFNULL(TRIM(SH_ATTRIBUTE_4::text), '^^') 
            , '||', IFNULL(TRIM(REQUEST_ID::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE_2::text), '^^') 
            , '||', IFNULL(TRIM(AMOUNT_RELEASED::text), '^^') 
            , '||', IFNULL(TRIM(TAX_CODE_ID::text), '^^') 
            , '||', IFNULL(TRIM(BASE_MODEL_ID::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE_DATE_4::text), '^^') 
            , '||', IFNULL(TRIM(TAX_ATTRIBUTE_UPDATE_CODE::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE_TIMESTAMP_7::text), '^^') 
            , '||', IFNULL(TRIM(SOURCE_DOC_REV_NUM::text), '^^') 
            , '||', IFNULL(TRIM(RETAINAGE_RATE::text), '^^') 
            , '||', IFNULL(TRIM(LAST_UPDATE_DATE::text), '^^') 
            , '||', IFNULL(TRIM(CONTRACTOR_FIRST_NAME::text), '^^') 
            , '||', IFNULL(TRIM(TAX_EXCLUSIVE_PRICE::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE_5::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE_NUMBER_8::text), '^^') 
            , '||', IFNULL(TRIM(CONSIGNMENT_LINE_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(FROM_LINE_LOCATION_ID::text), '^^') 
            , '||', IFNULL(TRIM(WORK_ORDER_PRODUCT::text), '^^') 
            , '||', IFNULL(TRIM(REQ_BU_ID::text), '^^') 
            , '||', IFNULL(TRIM(SH_ATTRIBUTE_11::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE_NUMBER_5::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE_19::text), '^^') 
            , '||', IFNULL(TRIM(SH_ATTRIBUTE_NUMBER_9::text), '^^') 
            , '||', IFNULL(TRIM(TOP_MODEL_ID::text), '^^') 
            , '||', IFNULL(TRIM(FIRM_STATUS_LOOKUP_CODE::text), '^^') 
            , '||', IFNULL(TRIM(SH_ATTRIBUTE_TIMESTAMP_10::text), '^^') 
            , '||', IFNULL(TRIM(SH_ATTRIBUTE_10::text), '^^') 
            , '||', IFNULL(TRIM(SH_ATTRIBUTE_DATE_9::text), '^^') 
            , '||', IFNULL(TRIM(VENDOR_PRODUCT_NUM::text), '^^') 
            , '||', IFNULL(TRIM(CAPITAL_EXPENSE_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(ITEM_DESCRIPTION::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE_7::text), '^^') 
            , '||', IFNULL(TRIM(RETROACTIVE_DATE::text), '^^') 
            , '||', IFNULL(TRIM(FROM_LINE_ID::text), '^^') 
            , '||', IFNULL(TRIM(SH_ATTRIBUTE_TIMESTAMP_8::text), '^^') 
            , '||', IFNULL(TRIM(NEXT_CONSUMPTION_ADV_GEN_DATE::text), '^^') 
            , '||', IFNULL(TRIM(PROGRESS_PAYMENT_RATE::text), '^^') 
            , '||', IFNULL(TRIM(SH_ATTRIBUTE_DATE_10::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE_6::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE_8::text), '^^') 
            , '||', IFNULL(TRIM(UNORDERED_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(SUPPLIER_PARENT_ITEM::text), '^^') 
            , '||', IFNULL(TRIM(SH_ATTRIBUTE_14::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE_5::text), '^^') 
            , '||', IFNULL(TRIM(SH_ATTRIBUTE_NUMBER_3::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE_DATE_7::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE_3::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE_DATE_8::text), '^^') 
            , '||', IFNULL(TRIM(SH_ATTRIBUTE_19::text), '^^') 
            , '||', IFNULL(TRIM(SH_ATTRIBUTE_DATE_1::text), '^^') 
            , '||', IFNULL(TRIM(LAST_UPDATE_LOGIN::text), '^^') 
            , '||', IFNULL(TRIM(OKE_CONTRACT_HEADER_ID::text), '^^') 
            , '||', IFNULL(TRIM(SH_ATTRIBUTE_16::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE_9::text), '^^') 
            , '||', IFNULL(TRIM(CANCEL_DATE::text), '^^') 
            , '||', IFNULL(TRIM(NEGOTIATED_BY_PREPARER_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(ITEM_ID::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE_DATE_3::text), '^^') 
            , '||', IFNULL(TRIM(LIST_PRICE_PER_UNIT::text), '^^') 
            , '||', IFNULL(TRIM(SECONDARY_QUANTITY::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE_DATE_5::text), '^^') 
            , '||', IFNULL(TRIM(SH_ATTRIBUTE_TIMESTAMP_5::text), '^^') 
            , '||', IFNULL(TRIM(TYPE_1099::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE_TIMESTAMP_1::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE_NUMBER_1::text), '^^') 
            , '||', IFNULL(TRIM(SH_ATTRIBUTE_15::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE_DATE_1::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE_TIMESTAMP_5::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE_TIMESTAMP_4::text), '^^') 
            , '||', IFNULL(TRIM(JOB_DEFINITION_NAME::text), '^^') 
            , '||', IFNULL(TRIM(SH_ATTRIBUTE_17::text), '^^') 
            , '||', IFNULL(TRIM(PURCHASE_BASIS::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE_18::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE_NUMBER_2::text), '^^') 
            , '||', IFNULL(TRIM(SH_ATTRIBUTE_18::text), '^^') 
            , '||', IFNULL(TRIM(SH_ATTRIBUTE_6::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE_DATE_5::text), '^^') 
            , '||', IFNULL(TRIM(AUCTION_DISPLAY_NUMBER::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE_14::text), '^^') 
            , '||', IFNULL(TRIM(SH_ATTRIBUTE_5::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE_6::text), '^^') 
            , '||', IFNULL(TRIM(SH_ATTRIBUTE_DATE_7::text), '^^') 
            , '||', IFNULL(TRIM(SH_ATTRIBUTE_1::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE_NUMBER_1::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE_17::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE_2::text), '^^') 
            , '||', IFNULL(TRIM(OPTIONS_PRICE::text), '^^') 
            , '||', IFNULL(TRIM(CLOSED_DATE::text), '^^') 
            , '||', IFNULL(TRIM(ORDER_TYPE_LOOKUP_CODE::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE_NUMBER_10::text), '^^') 
            , '||', IFNULL(TRIM(EXPIRATION_DATE::text), '^^') 
            , '||', IFNULL(TRIM(UOM_CODE::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE_CATEGORY::text), '^^') 
            , '||', IFNULL(TRIM(SH_ATTRIBUTE_TIMESTAMP_4::text), '^^') 
            , '||', IFNULL(TRIM(PRICE_BREAK_LOOKUP_CODE::text), '^^') 
            , '||', IFNULL(TRIM(SH_ATTRIBUTE_12::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE_20::text), '^^') 
            , '||', IFNULL(TRIM(BID_LINE_NUMBER::text), '^^') 
            , '||', IFNULL(TRIM(SH_ATTRIBUTE_DATE_5::text), '^^') 
            , '||', IFNULL(TRIM(LINE_STATUS::text), '^^') 
            , '||', IFNULL(TRIM(ALLOW_DESCRIPTION_UPDATE_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(OKE_CONTRACT_VERSION_ID::text), '^^') 
            , '||', IFNULL(TRIM(SH_ATTRIBUTE_NUMBER_8::text), '^^') 
            , '||', IFNULL(TRIM(CATEGORY_ID::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE_15::text), '^^') 
            , '||', IFNULL(TRIM(BASE_QTY::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE_TIMESTAMP_2::text), '^^') 
            , '||', IFNULL(TRIM(PROGRAM_NAME::text), '^^') 
            , '||', IFNULL(TRIM(MAX_RETAINAGE_AMOUNT::text), '^^') 
            , '||', IFNULL(TRIM(BASE_UNIT_PRICE::text), '^^') 
            , '||', IFNULL(TRIM(SH_ATTRIBUTE_NUMBER_6::text), '^^') 
            , '||', IFNULL(TRIM(REFERENCE_NUM::text), '^^') 
            , '||', IFNULL(TRIM(AUCTION_HEADER_ID::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE_DATE_1::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE_4::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE_CATEGORY::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE_1::text), '^^') 
            , '||', IFNULL(TRIM(SH_ATTRIBUTE_NUMBER_5::text), '^^') 
            , '||', IFNULL(TRIM(CLOSED_BY::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE_16::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE_9::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE_11::text), '^^') 
            , '||', IFNULL(TRIM(AUCTION_LINE_NUMBER::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE_TIMESTAMP_10::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE_14::text), '^^') 
            , '||', IFNULL(TRIM(SH_ATTRIBUTE_3::text), '^^') 
            , '||', IFNULL(TRIM(GOVERNMENT_CONTEXT::text), '^^') 
            , '||', IFNULL(TRIM(SH_ATTRIBUTE_TIMESTAMP_2::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE_NUMBER_6::text), '^^') 
            , '||', IFNULL(TRIM(TAXABLE_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(MANUAL_PRICE_CHANGE_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE_NUMBER_4::text), '^^') 
            , '||', IFNULL(TRIM(SVC_AMOUNT_NOTIF_SENT::text), '^^') 
            , '||', IFNULL(TRIM(QC_GRADE::text), '^^') 
            , '||', IFNULL(TRIM(SUPPLIER_PART_AUXID::text), '^^') 
            , '||', IFNULL(TRIM(LAST_UPDATED_PROGRAM::text), '^^') 
            , '||', IFNULL(TRIM(AMOUNT::text), '^^') 
            , '||', IFNULL(TRIM(PREFERRED_GRADE::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE_DATE_3::text), '^^') 
            , '||', IFNULL(TRIM(MATCHING_BASIS::text), '^^') 
            , '||', IFNULL(TRIM(SUPPLIER_TOP_MODEL::text), '^^') 
            , '||', IFNULL(TRIM(LAST_UPDATED_BY::text), '^^') 
            , '||', IFNULL(TRIM(GLOBAL_ATTRIBUTE_12::text), '^^') 
            , '||', IFNULL(TRIM(BASE_MODEL_PRICE::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE_DATE_9::text), '^^') 
            , '||', IFNULL(TRIM(SUPPLIER_REF_NUMBER::text), '^^') 
            , '||', IFNULL(TRIM(QUANTITY::text), '^^') 
            , '||', IFNULL(TRIM(LINE_START_DATE::text), '^^') 
            , '||', IFNULL(TRIM(_FIVETRAN_DELETED::text), '^^') 
            , '||', IFNULL(TRIM(PSA_DELETE_IND::text), '^^') 
        ), '^^||^^')))  as HASHDIFF
FROM JOIN_RESULT
