---- SRC LAYER ----
WITH
SRC_mtfib          as ( SELECT ACCT_PERIOD_ID, ACTUAL_COST, AGING_EXPIRATION_DATE, AGING_ONSET_DATE, ALM_INTERFACE_ERROR_CODE, ALM_INTERFACE_STATUS, ASSEMBLY_ASSET_ID, ASSEMBLY_SERIAL_NUMBER, ASSESSABLE_VALUE, ATTRIBUTE_1, ATTRIBUTE_10, ATTRIBUTE_11, ATTRIBUTE_12, ATTRIBUTE_13, ATTRIBUTE_14, ATTRIBUTE_15, ATTRIBUTE_16, ATTRIBUTE_17, ATTRIBUTE_18, ATTRIBUTE_19, ATTRIBUTE_2, ATTRIBUTE_20, ATTRIBUTE_3, ATTRIBUTE_4, ATTRIBUTE_5, ATTRIBUTE_6, ATTRIBUTE_7, ATTRIBUTE_8, ATTRIBUTE_9, ATTRIBUTE_CATEGORY, ATTRIBUTE_DATE_1, ATTRIBUTE_DATE_2, ATTRIBUTE_DATE_3, ATTRIBUTE_DATE_4, ATTRIBUTE_DATE_5, ATTRIBUTE_NUMBER_1, ATTRIBUTE_NUMBER_10, ATTRIBUTE_NUMBER_2, ATTRIBUTE_NUMBER_3, ATTRIBUTE_NUMBER_4, ATTRIBUTE_NUMBER_5, ATTRIBUTE_NUMBER_6, ATTRIBUTE_NUMBER_7, ATTRIBUTE_NUMBER_8, ATTRIBUTE_NUMBER_9, ATTRIBUTE_TIMESTAMP_1, ATTRIBUTE_TIMESTAMP_2, ATTRIBUTE_TIMESTAMP_3, ATTRIBUTE_TIMESTAMP_4, ATTRIBUTE_TIMESTAMP_5, AVAIL_XFER_TO_CONSIGNED_QTY, BUILD_BREAK_TO_UOM, CATEGORY_ID, COGS_RECOGNITION_PERCENT, COMMON_BOM_SEQ_ID, COMMON_ROUTING_SEQ_ID, COMPLETION_TRANSACTION_ID, CONSIGNMENT_SOURCE_TXN_ID, CONSUMPTION_LINE_ID, CONSUMPTION_TAX_EXC_UNIT_PRICE, CONSUMPTION_UNIT_PRICE, CONS_ERROR_ACTION_CODE, CONS_ERROR_TYPE_CODE, CONTENT_LPN_ID, COSTED_FLAG, COST_CATEGORY_ID, COST_GROUP_ID, COST_TYPE_ID, COST_UPDATE_ID, COUNTRY_OF_ORIGIN_CODE, CREATED_BY, CREATION_DATE, CSE_INTERFACE_STATUS_CODE, CURRENCY_CODE, CURRENCY_CONVERSION_DATE, CURRENCY_CONVERSION_RATE, CURRENCY_CONVERSION_TYPE, CYCLE_COUNT_ID, DEBRIEF_LINE_ID, DEFAULT_TAXATION_COUNTRY, DELIVERY_CART_ID, DEPARTMENT_CODE, DEPARTMENT_ID, DEPRECIABLE_FLAG, DISTRIBUTION_ACCOUNT_ID, DOCUMENT_SUB_TYPE, EMPLOYEE_CODE, ENCUMBRANCE_ACCOUNT, ENCUMBRANCE_AMOUNT, ERROR_CODE, ERROR_CONS_HEADER_ID, ERROR_EXPLANATION, EXEMPT_CERTIFICATE_NUMBER, EXEMPT_REASON_CODE, EXPENSE_ACCOUNT_ID, EXTERNAL_SYSTEM_PACKING_UNIT, EXTERNAL_SYS_TXN_REFERENCE, E_RECORD_ID, FINAL_COMPLETION_FLAG, FINAL_DISCHARGE_LOCATION_ID, FIRST_PTY_REG_ID, FLOW_SCHEDULE, FOB_POINT, FREIGHT_CODE, FROM_GRADE_CODE, FROM_PROJECT_ID, FROM_TASK_ID, INTENDED_USE_CLASSIF_ID, INTERCOMPANY_COST, INTERCOMPANY_CURRENCY_CODE, INTERCOMPANY_PRICING_OPTION, INTRANSIT_ACCOUNT, INVENTORY_ITEM_ID, INVOICED_FLAG, INV_RESERVED_ATTRIBUTE_1, INV_RESERVED_ATTRIBUTE_2, INV_STRIPING_CATEGORY, INV_USER_DEF_ATTRIBUTE_1, INV_USER_DEF_ATTRIBUTE_10, INV_USER_DEF_ATTRIBUTE_2, INV_USER_DEF_ATTRIBUTE_3, INV_USER_DEF_ATTRIBUTE_4, INV_USER_DEF_ATTRIBUTE_5, INV_USER_DEF_ATTRIBUTE_6, INV_USER_DEF_ATTRIBUTE_7, INV_USER_DEF_ATTRIBUTE_8, INV_USER_DEF_ATTRIBUTE_9, IS_EVENT_PUBLISHED, JOB_DEFINITION_NAME, JOB_DEFINITION_PACKAGE, LAST_UPDATED_BY, LAST_UPDATE_DATE, LAST_UPDATE_LOGIN, LICENSE_PLATE_NUMBER, LOAD_REQUEST_ID, LOCATION_TYPE, LOCATOR_ID, LOGICAL_TRANSACTION, LOGICAL_TRANSACTIONS_CREATED, LOGICAL_TRX_TYPE_CODE, LOT_TXN_GROUP_NAME, LPN_ID, MANUAL_RECEIPT_EXPENSE, MASTER_SCHEDULE_UPDATE_CODE, MATERIAL_ACCOUNT, MATERIAL_OVERHEAD_ACCOUNT, MATERIAL_SEQ_NUMBER, MOVEMENT_ID, MOVE_ORDER_LINE_ID, MOVE_TRANSACTION_ID, MVT_STAT_STATUS, NEW_COST, NUMBER_OF_CONTAINERS, OBJECT_VERSION_NUMBER, OPERATION_SEQ_NUM, OPERATION_SEQ_NUMBER_ID, OPERATION_TRANSACTION_ID, OPM_COSTED_FLAG, ORGANIZATION_ID, ORGANIZATION_TYPE, ORG_COST_GROUP_ID, ORIGINAL_SHIPMENT_TXN_ID, ORIGINAL_TRANSACTION_TEMP_ID, ORIG_LOCATOR_ID, ORIG_LOT_NUMBER, ORIG_SUBINVENTORY_CODE, ORIG_TRANSACTION_QUANTITY, OUTSIDE_PROCESSING_ACCOUNT, OVERCOMPLETION_PRIMARY_QTY, OVERCOMPLETION_TRANSACTION_ID, OVERCOMPLETION_TRANSACTION_QTY, OVERHEAD_ACCOUNT, OWNERSHIP_CHANGE_TXN_ID, OWNING_ORGANIZATION_ID, OWNING_TP_TYPE, PARENT_ID, PARENT_TRANSACTION_ID, PERCENTAGE_CHANGE, PERIODIC_PRIMARY_QUANTITY, PHYSICAL_ADJUSTMENT_ID, PICKING_LINE_ID, PICK_RULE_ID, PICK_SLIP_DATE, PICK_SLIP_LINE_NUMBER, PICK_SLIP_NUMBER, PICK_STRATEGY_ID, PJC_BILLABLE_FLAG, PJC_CAPITALIZABLE_FLAG, PJC_CONTEXT_CATEGORY, PJC_CONTRACT_ID, PJC_CONTRACT_LINE_ID, PJC_EXPENDITURE_ITEM_DATE, PJC_EXPENDITURE_TYPE_ID, PJC_FUNDING_ALLOCATION_ID, PJC_ORGANIZATION_ID, PJC_PROJECT_ID, PJC_RESERVED_ATTRIBUTE_1, PJC_RESERVED_ATTRIBUTE_10, PJC_RESERVED_ATTRIBUTE_2, PJC_RESERVED_ATTRIBUTE_3, PJC_RESERVED_ATTRIBUTE_4, PJC_RESERVED_ATTRIBUTE_5, PJC_RESERVED_ATTRIBUTE_6, PJC_RESERVED_ATTRIBUTE_7, PJC_RESERVED_ATTRIBUTE_8, PJC_RESERVED_ATTRIBUTE_9, PJC_TASK_ID, PJC_USER_DEF_ATTRIBUTE_1, PJC_USER_DEF_ATTRIBUTE_10, PJC_USER_DEF_ATTRIBUTE_2, PJC_USER_DEF_ATTRIBUTE_3, PJC_USER_DEF_ATTRIBUTE_4, PJC_USER_DEF_ATTRIBUTE_5, PJC_USER_DEF_ATTRIBUTE_6, PJC_USER_DEF_ATTRIBUTE_7, PJC_USER_DEF_ATTRIBUTE_8, PJC_USER_DEF_ATTRIBUTE_9, PJC_WORK_TYPE_ID, PLANNING_ORGANIZATION_ID, PLANNING_TP_TYPE, PM_COST_COLLECTED, PM_COST_COLLECTOR_GROUP_ID, PRIMARY_QUANTITY, PRIOR_COST, PRIOR_COSTED_QUANTITY, PRODUCT_CATEGORY, PRODUCT_FISC_CLASSIFICATION, PRODUCT_TYPE, PROJECT_ID, PSA_DELETE_IND, PSA_LOAD_DTS, PSA_RECORD_SOURCE, PUT_AWAY_RULE_ID, PUT_AWAY_STRATEGY_ID, QA_COLLECTION_ID, QUANTITY_ADJUSTED, RCV_TRANSACTION_ID, REASON_ID, RECEIVING_DOCUMENT, REPAIR_TXN_CODE_ID, REPETITIVE_LINE_ID, REQUESTER_ID, REQUEST_ID, RESERVATION_ID, RESOURCE_ACCOUNT, REVISION, RMA_LINE_ID, SECONDARY_TRANSACTION_QUANTITY, SECONDARY_UOM_CODE, SERVICE_WIP_FLAG, SHIPMENT_COSTED, SHIPMENT_LINE_NUMBER, SHIPMENT_NUMBER, SHIP_FROM_LOCATION_ID, SHIP_TO_LOCATION_ID, SHORTAGE_PROCESS_CODE, SOURCE_CODE, SOURCE_LINE_ID, SOURCE_LOT_FLAG, SO_ISSUE_ACCOUNT_TYPE, SUBINVENTORY_CODE, TASK_GROUP_ID, TASK_ID, TAX_CLASSIFICATION_CODE, TAX_INVOICE_DATE, TAX_INVOICE_NUMBER, THIRD_PTY_REG_ID, TO_GRADE_CODE, TO_PROJECT_ID, TO_TASK_ID, TRANSACTION_ACTION_ID, TRANSACTION_BATCH_ID, TRANSACTION_BATCH_SEQ, TRANSACTION_COST, TRANSACTION_DATE, TRANSACTION_GROUP_ID, TRANSACTION_ID, TRANSACTION_INTERFACE_ID, TRANSACTION_INTERFACE_LINE_NUM, TRANSACTION_MODE, TRANSACTION_QUANTITY, TRANSACTION_REFERENCE, TRANSACTION_SET_ID, TRANSACTION_SOURCE_ID, TRANSACTION_SOURCE_NAME, TRANSACTION_SOURCE_TYPE_ID, TRANSACTION_TYPE_ID, TRANSACTION_UOM, TRANSFER_COST, TRANSFER_COST_DIST_ACCOUNT, TRANSFER_COST_GROUP_ID, TRANSFER_LOCATOR_ID, TRANSFER_LPN_ID, TRANSFER_ORGANIZATION_ID, TRANSFER_ORGANIZATION_TYPE, TRANSFER_OWNING_TP_TYPE, TRANSFER_PERCENTAGE, TRANSFER_PLANNING_TP_TYPE, TRANSFER_PRICE, TRANSFER_PRIOR_COSTED_QUANTITY, TRANSFER_PROJECT_ID, TRANSFER_SUBINVENTORY, TRANSFER_TASK_ID, TRANSFER_TRANSACTION_ID, TRANSPORTATION_COST, TRANSPORTATION_DIST_ACCOUNT, TRX_BUSINESS_CATEGORY, TRX_FLOW_HEADER_ID, TRX_SOURCE_DELIVERY_ID, TRX_SOURCE_LINE_ID, USER_DEFINED_FISC_CLASS, USE_CURRENT_COST_FLAG, USSGL_TRANSACTION_CODE, VALUE_CHANGE, VARIANCE_AMOUNT, VENDOR_LOT_NUMBER, WAYBILL_AIRBILL, WIP_SUPPLY_TYPE, WO_EXT_SYS_GROUP_ID, XFR_OWNING_ORGANIZATION_ID, XFR_PLANNING_ORGANIZATION_ID, ZONE_ID, _FIVETRAN_DELETED, _FIVETRAN_SYNCED FROM {{ source('outd_ocf_inv', 'inv_material_txns') }} as SRC ),
SRC_a              as ( SELECT BKCC, REC_SRC FROM {{ ref('ref_business_key_collision') }} as SRC  ),
SRC_rcv            as ( SELECT PO_LINE_ID, TRANSACTION_ID, VENDOR_ID FROM {{ source('outd_ocf_rcv', 'rcv_transactions') }} as SRC 
                        qualify 1 = row_number()over (partition by transaction_id order by psa_load_dts desc) ),
SRC_itm            as ( SELECT INVENTORY_ITEM_ID, ITEM_NUMBER FROM {{ source('outd_ocf_egp', 'egp_system_items_b') }} as SRC 
                        /*Fetch Master Organization Id*/
                        where organization_id = 300000034179011 
                        qualify 1= row_number()over(partition by inventory_item_id order by _fivetran_synced desc, psa_load_dts desc) ),
SRC_po             as ( SELECT LINE_NUM, PO_HEADER_ID, PO_LINE_ID FROM {{ source('outd_ocf_po', 'po_lines_all') }} as SRC 
                        qualify 1 = row_number()over (partition by po_line_id order by psa_load_dts desc) ),
SRC_sup            as ( SELECT SEGMENT_1, VENDOR_ID FROM {{ source('outd_ocf_poz', 'poz_suppliers') }} as SRC 
                        qualify 1= row_number()over(partition by vendor_id order by _fivetran_synced desc, psa_load_dts desc) ),
SRC_p              as ( SELECT ORGANIZATION_CODE, ORGANIZATION_ID FROM {{ source('outd_ocf_inv', 'inv_org_parameters') }} as SRC 
                        qualify 1 = row_number()over (partition by organization_id order by _fivetran_synced desc, psa_load_dts desc) ),
SRC_poh            as ( SELECT PO_HEADER_ID, SOLDTO_LE_ID FROM {{ source('outd_ocf_po', 'po_headers_all') }} as SRC 
                        qualify 1= row_number()over(partition by po_header_id order by _fivetran_synced desc, psa_load_dts desc) ),
SRC_xle            as ( SELECT LEGAL_ENTITY_ID, LEGAL_ENTITY_IDENTIFIER FROM {{ source('outd_ocf_xle', 'xle_entity_profiles') }} as SRC 
                        qualify 1= row_number()over(partition by legal_entity_id order by _fivetran_synced desc, psa_load_dts desc) )

/*
SRC_mtfib          as ( SELECT * FROM outd_ocf_inv.inv_material_txns )
SRC_a              as ( SELECT * FROM raw_vault.ref_business_key_collision )
SRC_rcv            as ( SELECT * FROM outd_ocf_rcv.rcv_transactions )
SRC_itm            as ( SELECT * FROM outd_ocf_egp.egp_system_items_b )
SRC_po             as ( SELECT * FROM outd_ocf_po.po_lines_all )
SRC_sup            as ( SELECT * FROM outd_ocf_poz.poz_suppliers )
SRC_p              as ( SELECT * FROM outd_ocf_inv.inv_org_parameters )
SRC_poh            as ( SELECT * FROM outd_ocf_po.po_headers_all )
SRC_xle            as ( SELECT * FROM outd_ocf_xle.xle_entity_profiles )
*/
---- LOGIC LAYER ----

, LOGIC_mtfib as (
    SELECT
        TRANSACTION_ID
      , COST_CATEGORY_ID
      , ATTRIBUTE_14
      , ATTRIBUTE_NUMBER_8
      , SHIPMENT_NUMBER
      , ATTRIBUTE_16
      , SHIPMENT_COSTED
      , ORGANIZATION_ID
      , ATTRIBUTE_NUMBER_9
      , PJC_USER_DEF_ATTRIBUTE_2
      , SOURCE_LOT_FLAG
      , ORIG_TRANSACTION_QUANTITY
      , INV_RESERVED_ATTRIBUTE_2
      , TRX_SOURCE_LINE_ID
      , ERROR_CODE
      , ORGANIZATION_TYPE
      , ORIGINAL_TRANSACTION_TEMP_ID
      , TRANSFER_PRIOR_COSTED_QUANTITY
      , PJC_RESERVED_ATTRIBUTE_2
      , EMPLOYEE_CODE
      , CONSUMPTION_LINE_ID
      , ATTRIBUTE_DATE_5
      , OPERATION_TRANSACTION_ID
      , TO_PROJECT_ID
      , PJC_USER_DEF_ATTRIBUTE_8
      , TRANSFER_TASK_ID
      , PRIOR_COST
      , NUMBER_OF_CONTAINERS
      , PJC_BILLABLE_FLAG
      , TRX_FLOW_HEADER_ID
      , PRODUCT_FISC_CLASSIFICATION
      , REPAIR_TXN_CODE_ID
      , REVISION
      , LOCATION_TYPE
      , QUANTITY_ADJUSTED
      , SECONDARY_TRANSACTION_QUANTITY
      , ORIG_SUBINVENTORY_CODE
      , CREATED_BY
      , PJC_RESERVED_ATTRIBUTE_6
      , PERIODIC_PRIMARY_QUANTITY
      , SUBINVENTORY_CODE
      , PJC_RESERVED_ATTRIBUTE_10
      , ATTRIBUTE_DATE_1
      , PHYSICAL_ADJUSTMENT_ID
      , BUILD_BREAK_TO_UOM
      , TRANSFER_COST_GROUP_ID
      , TRANSFER_OWNING_TP_TYPE
      , ASSESSABLE_VALUE
      , TRANSFER_LOCATOR_ID
      , ATTRIBUTE_17
      , LAST_UPDATE_LOGIN
      , USER_DEFINED_FISC_CLASS
      , INTERCOMPANY_CURRENCY_CODE
      , PUT_AWAY_STRATEGY_ID
      , PJC_RESERVED_ATTRIBUTE_5
      , LOT_TXN_GROUP_NAME
      , TAX_INVOICE_NUMBER
      , PJC_FUNDING_ALLOCATION_ID
      , CONTENT_LPN_ID
      , CURRENCY_CODE
      , PJC_EXPENDITURE_TYPE_ID
      , PLANNING_TP_TYPE
      , ATTRIBUTE_NUMBER_2
      , JOB_DEFINITION_NAME
      , FINAL_DISCHARGE_LOCATION_ID
      , PICK_SLIP_DATE
      , FOB_POINT
      , ENCUMBRANCE_ACCOUNT
      , TRX_SOURCE_DELIVERY_ID
      , LAST_UPDATED_BY
      , PRODUCT_TYPE
      , TRANSFER_COST_DIST_ACCOUNT
      , TASK_GROUP_ID
      , WIP_SUPPLY_TYPE
      , INV_RESERVED_ATTRIBUTE_1
      , ATTRIBUTE_NUMBER_10
      , RESERVATION_ID
      , INVOICED_FLAG
      , TRANSACTION_COST
      , LOGICAL_TRANSACTIONS_CREATED
      , EXTERNAL_SYS_TXN_REFERENCE
      , DISTRIBUTION_ACCOUNT_ID
      , TRANSACTION_SOURCE_ID
      , ATTRIBUTE_13
      , INV_USER_DEF_ATTRIBUTE_10
      , RESOURCE_ACCOUNT
      , COSTED_FLAG
      , PM_COST_COLLECTOR_GROUP_ID
      , ENCUMBRANCE_AMOUNT
      , CONS_ERROR_TYPE_CODE
      , ATTRIBUTE_9
      , TRANSFER_TRANSACTION_ID
      , TRANSACTION_ACTION_ID
      , TRANSACTION_UOM
      , PJC_RESERVED_ATTRIBUTE_1
      , AGING_EXPIRATION_DATE
      , CURRENCY_CONVERSION_DATE
      , PJC_USER_DEF_ATTRIBUTE_7
      , USSGL_TRANSACTION_CODE
      , DOCUMENT_SUB_TYPE
      , PJC_EXPENDITURE_ITEM_DATE
      , ATTRIBUTE_NUMBER_1
      , INTRANSIT_ACCOUNT
      , ATTRIBUTE_TIMESTAMP_4
      , PJC_RESERVED_ATTRIBUTE_3
      , JOB_DEFINITION_PACKAGE
      , LOCATOR_ID
      , MOVE_TRANSACTION_ID
      , INV_USER_DEF_ATTRIBUTE_8
      , USE_CURRENT_COST_FLAG
      , ATTRIBUTE_12
      , LICENSE_PLATE_NUMBER
      , ORIGINAL_SHIPMENT_TXN_ID
      , PJC_CONTRACT_LINE_ID
      , ATTRIBUTE_DATE_4
      , COST_UPDATE_ID
      , SO_ISSUE_ACCOUNT_TYPE
      , MVT_STAT_STATUS
      , ATTRIBUTE_TIMESTAMP_2
      , OVERCOMPLETION_TRANSACTION_QTY
      , TRANSFER_ORGANIZATION_ID
      , PICK_SLIP_NUMBER
      , CURRENCY_CONVERSION_RATE
      , OBJECT_VERSION_NUMBER
      , TRANSACTION_MODE
      , ATTRIBUTE_19
      , TRANSFER_ORGANIZATION_TYPE
      , VARIANCE_AMOUNT
      , EXPENSE_ACCOUNT_ID
      , WAYBILL_AIRBILL
      , TRANSACTION_BATCH_SEQ
      , PRODUCT_CATEGORY
      , INV_USER_DEF_ATTRIBUTE_7
      , COMMON_ROUTING_SEQ_ID
      , ACTUAL_COST
      , OVERHEAD_ACCOUNT
      , CATEGORY_ID
      , LPN_ID
      , PJC_RESERVED_ATTRIBUTE_8
      , COMMON_BOM_SEQ_ID
      , ERROR_CONS_HEADER_ID
      , REPETITIVE_LINE_ID
      , PICK_SLIP_LINE_NUMBER
      , PJC_CONTEXT_CATEGORY
      , FLOW_SCHEDULE
      , TRANSACTION_SOURCE_NAME
      , TRANSACTION_QUANTITY
      , OWNING_TP_TYPE
      , ATTRIBUTE_TIMESTAMP_1
      , INV_USER_DEF_ATTRIBUTE_2
      , LOGICAL_TRANSACTION
      , ATTRIBUTE_7
      , ASSEMBLY_ASSET_ID
      , PJC_USER_DEF_ATTRIBUTE_5
      , TAX_CLASSIFICATION_CODE
      , PJC_USER_DEF_ATTRIBUTE_10
      , TRANSACTION_INTERFACE_LINE_NUM
      , PJC_TASK_ID
      , INTERCOMPANY_PRICING_OPTION
      , ASSEMBLY_SERIAL_NUMBER
      , XFR_OWNING_ORGANIZATION_ID
      , PJC_RESERVED_ATTRIBUTE_7
      , OVERCOMPLETION_PRIMARY_QTY
      , CONSUMPTION_UNIT_PRICE
      , TRANSACTION_BATCH_ID
      , REASON_ID
      , ATTRIBUTE_10
      , RECEIVING_DOCUMENT
      , INTERCOMPANY_COST
      , TRANSPORTATION_DIST_ACCOUNT
      , PJC_USER_DEF_ATTRIBUTE_9
      , INV_USER_DEF_ATTRIBUTE_6
      , SHIPMENT_LINE_NUMBER
      , TRANSACTION_GROUP_ID
      , PJC_USER_DEF_ATTRIBUTE_1
      , TRANSACTION_SOURCE_TYPE_ID
      , COUNTRY_OF_ORIGIN_CODE
      , SHIP_TO_LOCATION_ID
      , CONSUMPTION_TAX_EXC_UNIT_PRICE
      , PARENT_ID
      , MATERIAL_ACCOUNT
      , RCV_TRANSACTION_ID
      , OPERATION_SEQ_NUM
      , ORIG_LOT_NUMBER
      , ATTRIBUTE_NUMBER_6
      , ATTRIBUTE_DATE_2
      , CYCLE_COUNT_ID
      , ORG_COST_GROUP_ID
      , INV_USER_DEF_ATTRIBUTE_4
      , FINAL_COMPLETION_FLAG
      , MOVE_ORDER_LINE_ID
      , OPERATION_SEQ_NUMBER_ID
      , TRANSPORTATION_COST
      , E_RECORD_ID
      , IS_EVENT_PUBLISHED
      , PRIOR_COSTED_QUANTITY
      , SHORTAGE_PROCESS_CODE
      , TRANSFER_SUBINVENTORY
      , ATTRIBUTE_6
      , TO_TASK_ID
      , ATTRIBUTE_NUMBER_3
      , REQUEST_ID
      , ATTRIBUTE_CATEGORY
      , ATTRIBUTE_TIMESTAMP_3
      , SHIP_FROM_LOCATION_ID
      , REQUESTER_ID
      , ATTRIBUTE_2
      , SOURCE_CODE
      , MASTER_SCHEDULE_UPDATE_CODE
      , EXEMPT_CERTIFICATE_NUMBER
      , ATTRIBUTE_1
      , PERCENTAGE_CHANGE
      , PICK_STRATEGY_ID
      , ATTRIBUTE_5
      , PJC_PROJECT_ID
      , CREATION_DATE
      , DEPARTMENT_CODE
      , INV_USER_DEF_ATTRIBUTE_3
      , PJC_USER_DEF_ATTRIBUTE_3
      , CURRENCY_CONVERSION_TYPE
      , ALM_INTERFACE_ERROR_CODE
      , CSE_INTERFACE_STATUS_CODE
      , PJC_CAPITALIZABLE_FLAG
      , TRANSFER_COST
      , TO_GRADE_CODE
      , MOVEMENT_ID
      , QA_COLLECTION_ID
      , PLANNING_ORGANIZATION_ID
      , ERROR_EXPLANATION
      , COMPLETION_TRANSACTION_ID
      , ATTRIBUTE_4
      , SOURCE_LINE_ID
      , PJC_RESERVED_ATTRIBUTE_4
      , TRANSFER_PRICE
      , MANUAL_RECEIPT_EXPENSE
      , PJC_ORGANIZATION_ID
      , TRANSFER_PLANNING_TP_TYPE
      , CONSIGNMENT_SOURCE_TXN_ID
      , AGING_ONSET_DATE
      , PJC_USER_DEF_ATTRIBUTE_4
      , INV_USER_DEF_ATTRIBUTE_1
      , ATTRIBUTE_18
      , WO_EXT_SYS_GROUP_ID
      , ATTRIBUTE_20
      , ATTRIBUTE_11
      , ALM_INTERFACE_STATUS
      , OUTSIDE_PROCESSING_ACCOUNT
      , DEFAULT_TAXATION_COUNTRY
      , TASK_ID
      , INTENDED_USE_CLASSIF_ID
      , ATTRIBUTE_8
      , FIRST_PTY_REG_ID
      , EXEMPT_REASON_CODE
      , TRANSACTION_SET_ID
      , INVENTORY_ITEM_ID
      , AVAIL_XFER_TO_CONSIGNED_QTY
      , SECONDARY_UOM_CODE
      , VENDOR_LOT_NUMBER
      , FROM_PROJECT_ID
      , ATTRIBUTE_DATE_3
      , PICKING_LINE_ID
      , TRANSFER_PERCENTAGE
      , XFR_PLANNING_ORGANIZATION_ID
      , CONS_ERROR_ACTION_CODE
      , NEW_COST
      , TRANSACTION_TYPE_ID
      , COST_GROUP_ID
      , TRX_BUSINESS_CATEGORY
      , DEPARTMENT_ID
      , OWNING_ORGANIZATION_ID
      , ATTRIBUTE_3
      , LOAD_REQUEST_ID
      , RMA_LINE_ID
      , TRANSFER_LPN_ID
      , INV_USER_DEF_ATTRIBUTE_5
      , TRANSACTION_DATE
      , TAX_INVOICE_DATE
      , PJC_WORK_TYPE_ID
      , ATTRIBUTE_NUMBER_5
      , OPM_COSTED_FLAG
      , PM_COST_COLLECTED
      , VALUE_CHANGE
      , TRANSACTION_REFERENCE
      , PJC_RESERVED_ATTRIBUTE_9
      , PJC_CONTRACT_ID
      , INV_USER_DEF_ATTRIBUTE_9
      , INV_STRIPING_CATEGORY
      , FROM_GRADE_CODE
      , FROM_TASK_ID
      , ATTRIBUTE_15
      , LOGICAL_TRX_TYPE_CODE
      , OWNERSHIP_CHANGE_TXN_ID
      , PARENT_TRANSACTION_ID
      , ATTRIBUTE_NUMBER_7
      , LAST_UPDATE_DATE
      , ORIG_LOCATOR_ID
      , PROJECT_ID
      , PJC_USER_DEF_ATTRIBUTE_6
      , ACCT_PERIOD_ID
      , PUT_AWAY_RULE_ID
      , PRIMARY_QUANTITY
      , COST_TYPE_ID
      , DEPRECIABLE_FLAG
      , COGS_RECOGNITION_PERCENT
      , OVERCOMPLETION_TRANSACTION_ID
      , TRANSACTION_INTERFACE_ID
      , FREIGHT_CODE
      , MATERIAL_OVERHEAD_ACCOUNT
      , PICK_RULE_ID
      , ATTRIBUTE_NUMBER_4
      , EXTERNAL_SYSTEM_PACKING_UNIT
      , TRANSFER_PROJECT_ID
      , ATTRIBUTE_TIMESTAMP_5
      , THIRD_PTY_REG_ID
      , _FIVETRAN_SYNCED
      , DEBRIEF_LINE_ID
      , ZONE_ID
      , SERVICE_WIP_FLAG
      , DELIVERY_CART_ID
      , MATERIAL_SEQ_NUMBER
      , PSA_LOAD_DTS
      , PSA_RECORD_SOURCE
      , PSA_DELETE_IND
      , _FIVETRAN_DELETED
      , CONVERT_TIMEZONE('UTC', _FIVETRAN_SYNCED)                    as                                           LOAD_DTS
    FROM SRC_mtfib
)

, LOGIC_a as (
    SELECT
        BKCC
      , REC_SRC
    FROM SRC_a
)

, LOGIC_rcv as (
    SELECT
        TRANSACTION_ID                                               as                             RCV_RCV_TRANSACTION_ID
      , PO_LINE_ID
      , VENDOR_ID
    FROM SRC_rcv
)

, LOGIC_itm as (
    SELECT
        ITEM_NUMBER                                                  as                                            ITEM_BK
      , ITEM_NUMBER                                                  as                                      ITM_SEGMENT_1
      , INVENTORY_ITEM_ID                                            as                              itm_INVENTORY_ITEM_ID
    FROM SRC_itm
)

, LOGIC_po as (
    SELECT
        PO_HEADER_ID                                                 as                                       PO_HEADER_BK
      , LINE_NUM
      , PO_LINE_ID                                                   as                                      PO_PO_LINE_ID
      , PO_HEADER_ID
    FROM SRC_po
)

, LOGIC_sup as (
    SELECT
        SEGMENT_1                                                    as                                        SUPPLIER_BK
      , SEGMENT_1                                                    as                                      SUP_SEGMENT_1
      , VENDOR_ID                                                    as                                      SUP_VENDOR_ID
    FROM SRC_sup
)

, LOGIC_p as (
    SELECT
        ORGANIZATION_CODE                                            as                                           PLANT_BK
      , ORGANIZATION_CODE
      , ORGANIZATION_ID                                              as                                  P_ORGANIZATION_ID
    FROM SRC_p
)

, LOGIC_poh as (
    SELECT
        PO_HEADER_ID                                                 as                                   POH_PO_HEADER_ID
      , SOLDTO_LE_ID
    FROM SRC_poh
)

, LOGIC_xle as (
    SELECT
        LEGAL_ENTITY_IDENTIFIER                                      as                                    LEGAL_ENTITY_BK
      , LEGAL_ENTITY_IDENTIFIER
      , LEGAL_ENTITY_ID
    FROM SRC_xle
)
---- RENAME LAYER ----

, RENAME_po as (
    SELECT
        PO_HEADER_BK
      , LINE_NUM
      , PO_PO_LINE_ID
      , PO_HEADER_ID
    FROM LOGIC_po
)

, RENAME_sup as (
    SELECT
        SUPPLIER_BK
      , SUP_SEGMENT_1
      , SUP_VENDOR_ID
    FROM LOGIC_sup
)

, RENAME_itm as (
    SELECT
        ITEM_BK
      , ITM_SEGMENT_1
      , itm_INVENTORY_ITEM_ID
    FROM LOGIC_itm
)

, RENAME_p as (
    SELECT
        PLANT_BK
      , ORGANIZATION_CODE
      , P_ORGANIZATION_ID
    FROM LOGIC_p
)

, RENAME_xle as (
    SELECT
        LEGAL_ENTITY_BK
      , LEGAL_ENTITY_IDENTIFIER
      , LEGAL_ENTITY_ID
    FROM LOGIC_xle
)

, RENAME_mtfib as (
    SELECT
        TRANSACTION_ID
      , COST_CATEGORY_ID
      , ATTRIBUTE_14
      , ATTRIBUTE_NUMBER_8
      , SHIPMENT_NUMBER
      , ATTRIBUTE_16
      , SHIPMENT_COSTED
      , ORGANIZATION_ID
      , ATTRIBUTE_NUMBER_9
      , PJC_USER_DEF_ATTRIBUTE_2
      , SOURCE_LOT_FLAG
      , ORIG_TRANSACTION_QUANTITY
      , INV_RESERVED_ATTRIBUTE_2
      , TRX_SOURCE_LINE_ID
      , ERROR_CODE
      , ORGANIZATION_TYPE
      , ORIGINAL_TRANSACTION_TEMP_ID
      , TRANSFER_PRIOR_COSTED_QUANTITY
      , PJC_RESERVED_ATTRIBUTE_2
      , EMPLOYEE_CODE
      , CONSUMPTION_LINE_ID
      , ATTRIBUTE_DATE_5
      , OPERATION_TRANSACTION_ID
      , TO_PROJECT_ID
      , PJC_USER_DEF_ATTRIBUTE_8
      , TRANSFER_TASK_ID
      , PRIOR_COST
      , NUMBER_OF_CONTAINERS
      , PJC_BILLABLE_FLAG
      , TRX_FLOW_HEADER_ID
      , PRODUCT_FISC_CLASSIFICATION
      , REPAIR_TXN_CODE_ID
      , REVISION
      , LOCATION_TYPE
      , QUANTITY_ADJUSTED
      , SECONDARY_TRANSACTION_QUANTITY
      , ORIG_SUBINVENTORY_CODE
      , CREATED_BY
      , PJC_RESERVED_ATTRIBUTE_6
      , PERIODIC_PRIMARY_QUANTITY
      , SUBINVENTORY_CODE
      , PJC_RESERVED_ATTRIBUTE_10
      , ATTRIBUTE_DATE_1
      , PHYSICAL_ADJUSTMENT_ID
      , BUILD_BREAK_TO_UOM
      , TRANSFER_COST_GROUP_ID
      , TRANSFER_OWNING_TP_TYPE
      , ASSESSABLE_VALUE
      , TRANSFER_LOCATOR_ID
      , ATTRIBUTE_17
      , LAST_UPDATE_LOGIN
      , USER_DEFINED_FISC_CLASS
      , INTERCOMPANY_CURRENCY_CODE
      , PUT_AWAY_STRATEGY_ID
      , PJC_RESERVED_ATTRIBUTE_5
      , LOT_TXN_GROUP_NAME
      , TAX_INVOICE_NUMBER
      , PJC_FUNDING_ALLOCATION_ID
      , CONTENT_LPN_ID
      , CURRENCY_CODE
      , PJC_EXPENDITURE_TYPE_ID
      , PLANNING_TP_TYPE
      , ATTRIBUTE_NUMBER_2
      , JOB_DEFINITION_NAME
      , FINAL_DISCHARGE_LOCATION_ID
      , PICK_SLIP_DATE
      , FOB_POINT
      , ENCUMBRANCE_ACCOUNT
      , TRX_SOURCE_DELIVERY_ID
      , LAST_UPDATED_BY
      , PRODUCT_TYPE
      , TRANSFER_COST_DIST_ACCOUNT
      , TASK_GROUP_ID
      , WIP_SUPPLY_TYPE
      , INV_RESERVED_ATTRIBUTE_1
      , ATTRIBUTE_NUMBER_10
      , RESERVATION_ID
      , INVOICED_FLAG
      , TRANSACTION_COST
      , LOGICAL_TRANSACTIONS_CREATED
      , EXTERNAL_SYS_TXN_REFERENCE
      , DISTRIBUTION_ACCOUNT_ID
      , TRANSACTION_SOURCE_ID
      , ATTRIBUTE_13
      , INV_USER_DEF_ATTRIBUTE_10
      , RESOURCE_ACCOUNT
      , COSTED_FLAG
      , PM_COST_COLLECTOR_GROUP_ID
      , ENCUMBRANCE_AMOUNT
      , CONS_ERROR_TYPE_CODE
      , ATTRIBUTE_9
      , TRANSFER_TRANSACTION_ID
      , TRANSACTION_ACTION_ID
      , TRANSACTION_UOM
      , PJC_RESERVED_ATTRIBUTE_1
      , AGING_EXPIRATION_DATE
      , CURRENCY_CONVERSION_DATE
      , PJC_USER_DEF_ATTRIBUTE_7
      , USSGL_TRANSACTION_CODE
      , DOCUMENT_SUB_TYPE
      , PJC_EXPENDITURE_ITEM_DATE
      , ATTRIBUTE_NUMBER_1
      , INTRANSIT_ACCOUNT
      , ATTRIBUTE_TIMESTAMP_4
      , PJC_RESERVED_ATTRIBUTE_3
      , JOB_DEFINITION_PACKAGE
      , LOCATOR_ID
      , MOVE_TRANSACTION_ID
      , INV_USER_DEF_ATTRIBUTE_8
      , USE_CURRENT_COST_FLAG
      , ATTRIBUTE_12
      , LICENSE_PLATE_NUMBER
      , ORIGINAL_SHIPMENT_TXN_ID
      , PJC_CONTRACT_LINE_ID
      , ATTRIBUTE_DATE_4
      , COST_UPDATE_ID
      , SO_ISSUE_ACCOUNT_TYPE
      , MVT_STAT_STATUS
      , ATTRIBUTE_TIMESTAMP_2
      , OVERCOMPLETION_TRANSACTION_QTY
      , TRANSFER_ORGANIZATION_ID
      , PICK_SLIP_NUMBER
      , CURRENCY_CONVERSION_RATE
      , OBJECT_VERSION_NUMBER
      , TRANSACTION_MODE
      , ATTRIBUTE_19
      , TRANSFER_ORGANIZATION_TYPE
      , VARIANCE_AMOUNT
      , EXPENSE_ACCOUNT_ID
      , WAYBILL_AIRBILL
      , TRANSACTION_BATCH_SEQ
      , PRODUCT_CATEGORY
      , INV_USER_DEF_ATTRIBUTE_7
      , COMMON_ROUTING_SEQ_ID
      , ACTUAL_COST
      , OVERHEAD_ACCOUNT
      , CATEGORY_ID
      , LPN_ID
      , PJC_RESERVED_ATTRIBUTE_8
      , COMMON_BOM_SEQ_ID
      , ERROR_CONS_HEADER_ID
      , REPETITIVE_LINE_ID
      , PICK_SLIP_LINE_NUMBER
      , PJC_CONTEXT_CATEGORY
      , FLOW_SCHEDULE
      , TRANSACTION_SOURCE_NAME
      , TRANSACTION_QUANTITY
      , OWNING_TP_TYPE
      , ATTRIBUTE_TIMESTAMP_1
      , INV_USER_DEF_ATTRIBUTE_2
      , LOGICAL_TRANSACTION
      , ATTRIBUTE_7
      , ASSEMBLY_ASSET_ID
      , PJC_USER_DEF_ATTRIBUTE_5
      , TAX_CLASSIFICATION_CODE
      , PJC_USER_DEF_ATTRIBUTE_10
      , TRANSACTION_INTERFACE_LINE_NUM
      , PJC_TASK_ID
      , INTERCOMPANY_PRICING_OPTION
      , ASSEMBLY_SERIAL_NUMBER
      , XFR_OWNING_ORGANIZATION_ID
      , PJC_RESERVED_ATTRIBUTE_7
      , OVERCOMPLETION_PRIMARY_QTY
      , CONSUMPTION_UNIT_PRICE
      , TRANSACTION_BATCH_ID
      , REASON_ID
      , ATTRIBUTE_10
      , RECEIVING_DOCUMENT
      , INTERCOMPANY_COST
      , TRANSPORTATION_DIST_ACCOUNT
      , PJC_USER_DEF_ATTRIBUTE_9
      , INV_USER_DEF_ATTRIBUTE_6
      , SHIPMENT_LINE_NUMBER
      , TRANSACTION_GROUP_ID
      , PJC_USER_DEF_ATTRIBUTE_1
      , TRANSACTION_SOURCE_TYPE_ID
      , COUNTRY_OF_ORIGIN_CODE
      , SHIP_TO_LOCATION_ID
      , CONSUMPTION_TAX_EXC_UNIT_PRICE
      , PARENT_ID
      , MATERIAL_ACCOUNT
      , RCV_TRANSACTION_ID
      , OPERATION_SEQ_NUM
      , ORIG_LOT_NUMBER
      , ATTRIBUTE_NUMBER_6
      , ATTRIBUTE_DATE_2
      , CYCLE_COUNT_ID
      , ORG_COST_GROUP_ID
      , INV_USER_DEF_ATTRIBUTE_4
      , FINAL_COMPLETION_FLAG
      , MOVE_ORDER_LINE_ID
      , OPERATION_SEQ_NUMBER_ID
      , TRANSPORTATION_COST
      , E_RECORD_ID
      , IS_EVENT_PUBLISHED
      , PRIOR_COSTED_QUANTITY
      , SHORTAGE_PROCESS_CODE
      , TRANSFER_SUBINVENTORY
      , ATTRIBUTE_6
      , TO_TASK_ID
      , ATTRIBUTE_NUMBER_3
      , REQUEST_ID
      , ATTRIBUTE_CATEGORY
      , ATTRIBUTE_TIMESTAMP_3
      , SHIP_FROM_LOCATION_ID
      , REQUESTER_ID
      , ATTRIBUTE_2
      , SOURCE_CODE
      , MASTER_SCHEDULE_UPDATE_CODE
      , EXEMPT_CERTIFICATE_NUMBER
      , ATTRIBUTE_1
      , PERCENTAGE_CHANGE
      , PICK_STRATEGY_ID
      , ATTRIBUTE_5
      , PJC_PROJECT_ID
      , CREATION_DATE
      , DEPARTMENT_CODE
      , INV_USER_DEF_ATTRIBUTE_3
      , PJC_USER_DEF_ATTRIBUTE_3
      , CURRENCY_CONVERSION_TYPE
      , ALM_INTERFACE_ERROR_CODE
      , CSE_INTERFACE_STATUS_CODE
      , PJC_CAPITALIZABLE_FLAG
      , TRANSFER_COST
      , TO_GRADE_CODE
      , MOVEMENT_ID
      , QA_COLLECTION_ID
      , PLANNING_ORGANIZATION_ID
      , ERROR_EXPLANATION
      , COMPLETION_TRANSACTION_ID
      , ATTRIBUTE_4
      , SOURCE_LINE_ID
      , PJC_RESERVED_ATTRIBUTE_4
      , TRANSFER_PRICE
      , MANUAL_RECEIPT_EXPENSE
      , PJC_ORGANIZATION_ID
      , TRANSFER_PLANNING_TP_TYPE
      , CONSIGNMENT_SOURCE_TXN_ID
      , AGING_ONSET_DATE
      , PJC_USER_DEF_ATTRIBUTE_4
      , INV_USER_DEF_ATTRIBUTE_1
      , ATTRIBUTE_18
      , WO_EXT_SYS_GROUP_ID
      , ATTRIBUTE_20
      , ATTRIBUTE_11
      , ALM_INTERFACE_STATUS
      , OUTSIDE_PROCESSING_ACCOUNT
      , DEFAULT_TAXATION_COUNTRY
      , TASK_ID
      , INTENDED_USE_CLASSIF_ID
      , ATTRIBUTE_8
      , FIRST_PTY_REG_ID
      , EXEMPT_REASON_CODE
      , TRANSACTION_SET_ID
      , INVENTORY_ITEM_ID
      , AVAIL_XFER_TO_CONSIGNED_QTY
      , SECONDARY_UOM_CODE
      , VENDOR_LOT_NUMBER
      , FROM_PROJECT_ID
      , ATTRIBUTE_DATE_3
      , PICKING_LINE_ID
      , TRANSFER_PERCENTAGE
      , XFR_PLANNING_ORGANIZATION_ID
      , CONS_ERROR_ACTION_CODE
      , NEW_COST
      , TRANSACTION_TYPE_ID
      , COST_GROUP_ID
      , TRX_BUSINESS_CATEGORY
      , DEPARTMENT_ID
      , OWNING_ORGANIZATION_ID
      , ATTRIBUTE_3
      , LOAD_REQUEST_ID
      , RMA_LINE_ID
      , TRANSFER_LPN_ID
      , INV_USER_DEF_ATTRIBUTE_5
      , TRANSACTION_DATE
      , TAX_INVOICE_DATE
      , PJC_WORK_TYPE_ID
      , ATTRIBUTE_NUMBER_5
      , OPM_COSTED_FLAG
      , PM_COST_COLLECTED
      , VALUE_CHANGE
      , TRANSACTION_REFERENCE
      , PJC_RESERVED_ATTRIBUTE_9
      , PJC_CONTRACT_ID
      , INV_USER_DEF_ATTRIBUTE_9
      , INV_STRIPING_CATEGORY
      , FROM_GRADE_CODE
      , FROM_TASK_ID
      , ATTRIBUTE_15
      , LOGICAL_TRX_TYPE_CODE
      , OWNERSHIP_CHANGE_TXN_ID
      , PARENT_TRANSACTION_ID
      , ATTRIBUTE_NUMBER_7
      , LAST_UPDATE_DATE
      , ORIG_LOCATOR_ID
      , PROJECT_ID
      , PJC_USER_DEF_ATTRIBUTE_6
      , ACCT_PERIOD_ID
      , PUT_AWAY_RULE_ID
      , PRIMARY_QUANTITY
      , COST_TYPE_ID
      , DEPRECIABLE_FLAG
      , COGS_RECOGNITION_PERCENT
      , OVERCOMPLETION_TRANSACTION_ID
      , TRANSACTION_INTERFACE_ID
      , FREIGHT_CODE
      , MATERIAL_OVERHEAD_ACCOUNT
      , PICK_RULE_ID
      , ATTRIBUTE_NUMBER_4
      , EXTERNAL_SYSTEM_PACKING_UNIT
      , TRANSFER_PROJECT_ID
      , ATTRIBUTE_TIMESTAMP_5
      , THIRD_PTY_REG_ID
      , _FIVETRAN_SYNCED
      , DEBRIEF_LINE_ID
      , ZONE_ID
      , SERVICE_WIP_FLAG
      , DELIVERY_CART_ID
      , MATERIAL_SEQ_NUMBER
      , PSA_LOAD_DTS
      , PSA_RECORD_SOURCE
      , PSA_DELETE_IND
      , _FIVETRAN_DELETED
      , LOAD_DTS
    FROM LOGIC_mtfib
)

, RENAME_a as (
    SELECT
        BKCC
      , REC_SRC
    FROM LOGIC_a
)

, RENAME_rcv as (
    SELECT
        RCV_RCV_TRANSACTION_ID
      , PO_LINE_ID
      , VENDOR_ID
    FROM LOGIC_rcv
)

, RENAME_poh as (
    SELECT
        POH_PO_HEADER_ID
      , SOLDTO_LE_ID
    FROM LOGIC_poh
)
---- FILTER LAYER ----

, FILTER_mtfib as (
    SELECT *
    FROM RENAME_mtfib
    WHERE TRANSACTION_TYPE_ID IN (71,18,36)
)

, FILTER_a as (
    SELECT *
    FROM RENAME_a
    WHERE rec_src = 'USCLOUD.ORCL.OCFPRD.INV_MATERIAL_TXNS'
)

, FILTER_rcv as (
    SELECT *
    FROM RENAME_rcv
)

, FILTER_itm as (
    SELECT *
    FROM RENAME_itm
)

, FILTER_po as (
    SELECT *
    FROM RENAME_po
)

, FILTER_sup as (
    SELECT *
    FROM RENAME_sup
)

, FILTER_p as (
    SELECT *
    FROM RENAME_p
)

, FILTER_poh as (
    SELECT *
    FROM RENAME_poh
)

, FILTER_xle as (
    SELECT *
    FROM RENAME_xle
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM FILTER_mtfib
    INNER JOIN FILTER_a
        ON '1' = '1'
    LEFT JOIN FILTER_rcv
        ON FILTER_mtfib.RCV_TRANSACTION_ID = RCV_RCV_TRANSACTION_ID
    LEFT JOIN FILTER_itm
        ON FILTER_mtfib.INVENTORY_ITEM_ID = ITM_INVENTORY_ITEM_ID
    LEFT JOIN FILTER_p
        ON FILTER_mtfib.ORGANIZATION_ID = P_ORGANIZATION_ID
    LEFT JOIN FILTER_po
        ON FILTER_rcv.PO_LINE_ID = PO_PO_LINE_ID
    LEFT JOIN FILTER_sup
        ON FILTER_rcv.VENDOR_ID = sup_VENDOR_ID
    LEFT JOIN FILTER_poh
        ON FILTER_po.PO_HEADER_ID = FILTER_poh.POH_PO_HEADER_ID
    LEFT JOIN FILTER_xle
        ON FILTER_poh.SOLDTO_LE_ID = FILTER_xle.LEGAL_ENTITY_ID
)

---- FINAL LAYER ----
SELECT
          CONCAT_WS('||'          
          , COALESCE(PO_HEADER_ID::TEXT,'')
          , COALESCE(LINE_NUM::TEXT,'')
          , COALESCE(TRANSACTION_ID::TEXT,'')) as PO_ITEM_RECEIPT_BK
        , PO_HEADER_BK
        , SUPPLIER_BK
        , ITEM_BK
        , PLANT_BK
        , LEGAL_ENTITY_BK
        , LINE_NUM
        , TRANSACTION_ID
        , COST_CATEGORY_ID
        , ATTRIBUTE_14
        , ATTRIBUTE_NUMBER_8
        , SHIPMENT_NUMBER
        , ATTRIBUTE_16
        , SHIPMENT_COSTED
        , ORGANIZATION_ID
        , ATTRIBUTE_NUMBER_9
        , PJC_USER_DEF_ATTRIBUTE_2
        , SOURCE_LOT_FLAG
        , ORIG_TRANSACTION_QUANTITY
        , INV_RESERVED_ATTRIBUTE_2
        , TRX_SOURCE_LINE_ID
        , ERROR_CODE
        , ORGANIZATION_TYPE
        , ORIGINAL_TRANSACTION_TEMP_ID
        , TRANSFER_PRIOR_COSTED_QUANTITY
        , PJC_RESERVED_ATTRIBUTE_2
        , EMPLOYEE_CODE
        , CONSUMPTION_LINE_ID
        , ATTRIBUTE_DATE_5
        , OPERATION_TRANSACTION_ID
        , TO_PROJECT_ID
        , PJC_USER_DEF_ATTRIBUTE_8
        , TRANSFER_TASK_ID
        , PRIOR_COST
        , NUMBER_OF_CONTAINERS
        , PJC_BILLABLE_FLAG
        , TRX_FLOW_HEADER_ID
        , PRODUCT_FISC_CLASSIFICATION
        , REPAIR_TXN_CODE_ID
        , REVISION
        , LOCATION_TYPE
        , QUANTITY_ADJUSTED
        , SECONDARY_TRANSACTION_QUANTITY
        , ORIG_SUBINVENTORY_CODE
        , CREATED_BY
        , PJC_RESERVED_ATTRIBUTE_6
        , PERIODIC_PRIMARY_QUANTITY
        , SUBINVENTORY_CODE
        , PJC_RESERVED_ATTRIBUTE_10
        , ATTRIBUTE_DATE_1
        , PHYSICAL_ADJUSTMENT_ID
        , BUILD_BREAK_TO_UOM
        , TRANSFER_COST_GROUP_ID
        , TRANSFER_OWNING_TP_TYPE
        , ASSESSABLE_VALUE
        , TRANSFER_LOCATOR_ID
        , ATTRIBUTE_17
        , LAST_UPDATE_LOGIN
        , USER_DEFINED_FISC_CLASS
        , INTERCOMPANY_CURRENCY_CODE
        , PUT_AWAY_STRATEGY_ID
        , PJC_RESERVED_ATTRIBUTE_5
        , LOT_TXN_GROUP_NAME
        , TAX_INVOICE_NUMBER
        , PJC_FUNDING_ALLOCATION_ID
        , CONTENT_LPN_ID
        , CURRENCY_CODE
        , PJC_EXPENDITURE_TYPE_ID
        , PLANNING_TP_TYPE
        , ATTRIBUTE_NUMBER_2
        , JOB_DEFINITION_NAME
        , FINAL_DISCHARGE_LOCATION_ID
        , PICK_SLIP_DATE
        , FOB_POINT
        , ENCUMBRANCE_ACCOUNT
        , TRX_SOURCE_DELIVERY_ID
        , LAST_UPDATED_BY
        , PRODUCT_TYPE
        , TRANSFER_COST_DIST_ACCOUNT
        , TASK_GROUP_ID
        , WIP_SUPPLY_TYPE
        , INV_RESERVED_ATTRIBUTE_1
        , ATTRIBUTE_NUMBER_10
        , RESERVATION_ID
        , INVOICED_FLAG
        , TRANSACTION_COST
        , LOGICAL_TRANSACTIONS_CREATED
        , EXTERNAL_SYS_TXN_REFERENCE
        , DISTRIBUTION_ACCOUNT_ID
        , TRANSACTION_SOURCE_ID
        , ATTRIBUTE_13
        , INV_USER_DEF_ATTRIBUTE_10
        , RESOURCE_ACCOUNT
        , COSTED_FLAG
        , PM_COST_COLLECTOR_GROUP_ID
        , ENCUMBRANCE_AMOUNT
        , CONS_ERROR_TYPE_CODE
        , ATTRIBUTE_9
        , TRANSFER_TRANSACTION_ID
        , TRANSACTION_ACTION_ID
        , TRANSACTION_UOM
        , PJC_RESERVED_ATTRIBUTE_1
        , AGING_EXPIRATION_DATE
        , CURRENCY_CONVERSION_DATE
        , PJC_USER_DEF_ATTRIBUTE_7
        , USSGL_TRANSACTION_CODE
        , DOCUMENT_SUB_TYPE
        , PJC_EXPENDITURE_ITEM_DATE
        , ATTRIBUTE_NUMBER_1
        , INTRANSIT_ACCOUNT
        , ATTRIBUTE_TIMESTAMP_4
        , PJC_RESERVED_ATTRIBUTE_3
        , JOB_DEFINITION_PACKAGE
        , LOCATOR_ID
        , MOVE_TRANSACTION_ID
        , INV_USER_DEF_ATTRIBUTE_8
        , USE_CURRENT_COST_FLAG
        , ATTRIBUTE_12
        , LICENSE_PLATE_NUMBER
        , ORIGINAL_SHIPMENT_TXN_ID
        , PJC_CONTRACT_LINE_ID
        , ATTRIBUTE_DATE_4
        , COST_UPDATE_ID
        , SO_ISSUE_ACCOUNT_TYPE
        , MVT_STAT_STATUS
        , ATTRIBUTE_TIMESTAMP_2
        , OVERCOMPLETION_TRANSACTION_QTY
        , TRANSFER_ORGANIZATION_ID
        , PICK_SLIP_NUMBER
        , CURRENCY_CONVERSION_RATE
        , OBJECT_VERSION_NUMBER
        , TRANSACTION_MODE
        , ATTRIBUTE_19
        , TRANSFER_ORGANIZATION_TYPE
        , VARIANCE_AMOUNT
        , EXPENSE_ACCOUNT_ID
        , WAYBILL_AIRBILL
        , TRANSACTION_BATCH_SEQ
        , PRODUCT_CATEGORY
        , INV_USER_DEF_ATTRIBUTE_7
        , COMMON_ROUTING_SEQ_ID
        , ACTUAL_COST
        , OVERHEAD_ACCOUNT
        , CATEGORY_ID
        , LPN_ID
        , PJC_RESERVED_ATTRIBUTE_8
        , COMMON_BOM_SEQ_ID
        , ERROR_CONS_HEADER_ID
        , REPETITIVE_LINE_ID
        , PICK_SLIP_LINE_NUMBER
        , PJC_CONTEXT_CATEGORY
        , FLOW_SCHEDULE
        , TRANSACTION_SOURCE_NAME
        , TRANSACTION_QUANTITY
        , OWNING_TP_TYPE
        , ATTRIBUTE_TIMESTAMP_1
        , INV_USER_DEF_ATTRIBUTE_2
        , LOGICAL_TRANSACTION
        , ATTRIBUTE_7
        , ASSEMBLY_ASSET_ID
        , PJC_USER_DEF_ATTRIBUTE_5
        , TAX_CLASSIFICATION_CODE
        , PJC_USER_DEF_ATTRIBUTE_10
        , TRANSACTION_INTERFACE_LINE_NUM
        , PJC_TASK_ID
        , INTERCOMPANY_PRICING_OPTION
        , ASSEMBLY_SERIAL_NUMBER
        , XFR_OWNING_ORGANIZATION_ID
        , PJC_RESERVED_ATTRIBUTE_7
        , OVERCOMPLETION_PRIMARY_QTY
        , CONSUMPTION_UNIT_PRICE
        , TRANSACTION_BATCH_ID
        , REASON_ID
        , ATTRIBUTE_10
        , RECEIVING_DOCUMENT
        , INTERCOMPANY_COST
        , TRANSPORTATION_DIST_ACCOUNT
        , PJC_USER_DEF_ATTRIBUTE_9
        , INV_USER_DEF_ATTRIBUTE_6
        , SHIPMENT_LINE_NUMBER
        , TRANSACTION_GROUP_ID
        , PJC_USER_DEF_ATTRIBUTE_1
        , TRANSACTION_SOURCE_TYPE_ID
        , COUNTRY_OF_ORIGIN_CODE
        , SHIP_TO_LOCATION_ID
        , CONSUMPTION_TAX_EXC_UNIT_PRICE
        , PARENT_ID
        , MATERIAL_ACCOUNT
        , RCV_TRANSACTION_ID
        , OPERATION_SEQ_NUM
        , ORIG_LOT_NUMBER
        , ATTRIBUTE_NUMBER_6
        , ATTRIBUTE_DATE_2
        , CYCLE_COUNT_ID
        , ORG_COST_GROUP_ID
        , INV_USER_DEF_ATTRIBUTE_4
        , FINAL_COMPLETION_FLAG
        , MOVE_ORDER_LINE_ID
        , OPERATION_SEQ_NUMBER_ID
        , TRANSPORTATION_COST
        , E_RECORD_ID
        , IS_EVENT_PUBLISHED
        , PRIOR_COSTED_QUANTITY
        , SHORTAGE_PROCESS_CODE
        , TRANSFER_SUBINVENTORY
        , ATTRIBUTE_6
        , TO_TASK_ID
        , ATTRIBUTE_NUMBER_3
        , REQUEST_ID
        , ATTRIBUTE_CATEGORY
        , ATTRIBUTE_TIMESTAMP_3
        , SHIP_FROM_LOCATION_ID
        , REQUESTER_ID
        , ATTRIBUTE_2
        , SOURCE_CODE
        , MASTER_SCHEDULE_UPDATE_CODE
        , EXEMPT_CERTIFICATE_NUMBER
        , ATTRIBUTE_1
        , PERCENTAGE_CHANGE
        , PICK_STRATEGY_ID
        , ATTRIBUTE_5
        , PJC_PROJECT_ID
        , CREATION_DATE
        , DEPARTMENT_CODE
        , INV_USER_DEF_ATTRIBUTE_3
        , PJC_USER_DEF_ATTRIBUTE_3
        , CURRENCY_CONVERSION_TYPE
        , ALM_INTERFACE_ERROR_CODE
        , CSE_INTERFACE_STATUS_CODE
        , PJC_CAPITALIZABLE_FLAG
        , TRANSFER_COST
        , TO_GRADE_CODE
        , MOVEMENT_ID
        , QA_COLLECTION_ID
        , PLANNING_ORGANIZATION_ID
        , ERROR_EXPLANATION
        , COMPLETION_TRANSACTION_ID
        , ATTRIBUTE_4
        , SOURCE_LINE_ID
        , PJC_RESERVED_ATTRIBUTE_4
        , TRANSFER_PRICE
        , MANUAL_RECEIPT_EXPENSE
        , PJC_ORGANIZATION_ID
        , TRANSFER_PLANNING_TP_TYPE
        , CONSIGNMENT_SOURCE_TXN_ID
        , AGING_ONSET_DATE
        , PJC_USER_DEF_ATTRIBUTE_4
        , INV_USER_DEF_ATTRIBUTE_1
        , ATTRIBUTE_18
        , WO_EXT_SYS_GROUP_ID
        , ATTRIBUTE_20
        , ATTRIBUTE_11
        , ALM_INTERFACE_STATUS
        , OUTSIDE_PROCESSING_ACCOUNT
        , DEFAULT_TAXATION_COUNTRY
        , TASK_ID
        , INTENDED_USE_CLASSIF_ID
        , ATTRIBUTE_8
        , FIRST_PTY_REG_ID
        , EXEMPT_REASON_CODE
        , TRANSACTION_SET_ID
        , INVENTORY_ITEM_ID
        , AVAIL_XFER_TO_CONSIGNED_QTY
        , SECONDARY_UOM_CODE
        , VENDOR_LOT_NUMBER
        , FROM_PROJECT_ID
        , ATTRIBUTE_DATE_3
        , PICKING_LINE_ID
        , TRANSFER_PERCENTAGE
        , XFR_PLANNING_ORGANIZATION_ID
        , CONS_ERROR_ACTION_CODE
        , NEW_COST
        , TRANSACTION_TYPE_ID
        , COST_GROUP_ID
        , TRX_BUSINESS_CATEGORY
        , DEPARTMENT_ID
        , OWNING_ORGANIZATION_ID
        , ATTRIBUTE_3
        , LOAD_REQUEST_ID
        , RMA_LINE_ID
        , TRANSFER_LPN_ID
        , INV_USER_DEF_ATTRIBUTE_5
        , TRANSACTION_DATE
        , TAX_INVOICE_DATE
        , PJC_WORK_TYPE_ID
        , ATTRIBUTE_NUMBER_5
        , OPM_COSTED_FLAG
        , PM_COST_COLLECTED
        , VALUE_CHANGE
        , TRANSACTION_REFERENCE
        , PJC_RESERVED_ATTRIBUTE_9
        , PJC_CONTRACT_ID
        , INV_USER_DEF_ATTRIBUTE_9
        , INV_STRIPING_CATEGORY
        , FROM_GRADE_CODE
        , FROM_TASK_ID
        , ATTRIBUTE_15
        , LOGICAL_TRX_TYPE_CODE
        , OWNERSHIP_CHANGE_TXN_ID
        , PARENT_TRANSACTION_ID
        , ATTRIBUTE_NUMBER_7
        , LAST_UPDATE_DATE
        , ORIG_LOCATOR_ID
        , PROJECT_ID
        , PJC_USER_DEF_ATTRIBUTE_6
        , ACCT_PERIOD_ID
        , PUT_AWAY_RULE_ID
        , PRIMARY_QUANTITY
        , COST_TYPE_ID
        , DEPRECIABLE_FLAG
        , COGS_RECOGNITION_PERCENT
        , OVERCOMPLETION_TRANSACTION_ID
        , TRANSACTION_INTERFACE_ID
        , FREIGHT_CODE
        , MATERIAL_OVERHEAD_ACCOUNT
        , PICK_RULE_ID
        , ATTRIBUTE_NUMBER_4
        , EXTERNAL_SYSTEM_PACKING_UNIT
        , TRANSFER_PROJECT_ID
        , ATTRIBUTE_TIMESTAMP_5
        , THIRD_PTY_REG_ID
        , _FIVETRAN_SYNCED
        , DEBRIEF_LINE_ID
        , ZONE_ID
        , SERVICE_WIP_FLAG
        , DELIVERY_CART_ID
        , MATERIAL_SEQ_NUMBER
        , PSA_LOAD_DTS
        , PSA_RECORD_SOURCE
        , PSA_DELETE_IND
        , _FIVETRAN_DELETED
        , LOAD_DTS
        , SUP_SEGMENT_1
        , ITM_SEGMENT_1
        , ORGANIZATION_CODE
        , LEGAL_ENTITY_IDENTIFIER
        , BKCC
        , REC_SRC
        , MD5_BINARY(UPPER(CONCAT_WS('||',
          COALESCE(NULLIF(TRIM(CAST(PO_HEADER_ID as VARCHAR)),''), '^^')
        , COALESCE(NULLIF(TRIM(CAST(LINE_NUM as VARCHAR)),''), '^^')
        , COALESCE(NULLIF(TRIM(CAST(TRANSACTION_ID as VARCHAR)),''), '^^')
        , COALESCE(NULLIF(TRIM(CAST(SUP_SEGMENT_1 as VARCHAR)),''), '^^')
        , COALESCE(NULLIF(TRIM(CAST(ITM_SEGMENT_1 as VARCHAR)),''), '^^')
        , COALESCE(NULLIF(TRIM(CAST(ORGANIZATION_CODE as VARCHAR)),''), '^^')
        , COALESCE(NULLIF(TRIM(CAST(LEGAL_ENTITY_IDENTIFIER as VARCHAR)),''), '^^')
        , COALESCE(NULLIF(TRIM(CAST(BKCC as VARCHAR)),''), '^^')
        ))) as LNK_PO_RECEIPT_HK
        , MD5_BINARY(UPPER(CONCAT_WS('||',
          COALESCE(NULLIF(TRIM(CAST(PO_HEADER_ID as VARCHAR)),''), '^^')
        , COALESCE(NULLIF(TRIM(CAST(BKCC as VARCHAR)),''), '^^')
        ))) as PO_HEADER_HK
        , MD5_BINARY(UPPER(CONCAT_WS('||',
          COALESCE(NULLIF(TRIM(CAST(PO_HEADER_ID as VARCHAR)),''), '^^')
        , COALESCE(NULLIF(TRIM(CAST(LINE_NUM as VARCHAR)),''), '^^')
        , COALESCE(NULLIF(TRIM(CAST(BKCC as VARCHAR)),''), '^^')
        ))) as PO_ITEM_HK
        , MD5_BINARY(UPPER(CONCAT_WS('||',
          COALESCE(NULLIF(TRIM(CAST(PO_HEADER_ID as VARCHAR)),''), '^^')
        , COALESCE(NULLIF(TRIM(CAST(LINE_NUM as VARCHAR)),''), '^^')
        , COALESCE(NULLIF(TRIM(CAST(TRANSACTION_ID as VARCHAR)),''), '^^')
        , COALESCE(NULLIF(TRIM(CAST(BKCC as VARCHAR)),''), '^^')
        ))) as PO_ITEM_RECEIPT_DK
        , MD5_BINARY(UPPER(CONCAT_WS('||',
          COALESCE(NULLIF(TRIM(CAST(SUP_SEGMENT_1 as VARCHAR)),''), '^^')
        , COALESCE(NULLIF(TRIM(CAST(BKCC as VARCHAR)),''), '^^')
        ))) as SUPPLIER_HK
        , MD5_BINARY(UPPER(CONCAT_WS('||',
          COALESCE(NULLIF(TRIM(CAST(ITM_SEGMENT_1 as VARCHAR)),''), '^^')
        , COALESCE(NULLIF(TRIM(CAST(BKCC as VARCHAR)),''), '^^')
        ))) as ITEM_HK
        , MD5_BINARY(UPPER(CONCAT_WS('||',
          COALESCE(NULLIF(TRIM(CAST(ORGANIZATION_CODE as VARCHAR)),''), '^^')
        , COALESCE(NULLIF(TRIM(CAST(BKCC as VARCHAR)),''), '^^')
        ))) as PLANT_HK
        , MD5_BINARY(UPPER(CONCAT_WS('||',
          COALESCE(NULLIF(TRIM(CAST(LEGAL_ENTITY_IDENTIFIER as VARCHAR)),''), '^^')
        , COALESCE(NULLIF(TRIM(CAST(BKCC as VARCHAR)),''), '^^')
        ))) as LEGAL_ENTITY_HK
        , MD5_BINARY(UPPER(NULLIF(CONCAT(
              IFNULL(TRIM(COST_CATEGORY_ID::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE_14::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE_NUMBER_8::text), '^^') 
            , '||', IFNULL(TRIM(SHIPMENT_NUMBER::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE_16::text), '^^') 
            , '||', IFNULL(TRIM(SHIPMENT_COSTED::text), '^^') 
            , '||', IFNULL(TRIM(ORGANIZATION_ID::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE_NUMBER_9::text), '^^') 
            , '||', IFNULL(TRIM(PJC_USER_DEF_ATTRIBUTE_2::text), '^^') 
            , '||', IFNULL(TRIM(SOURCE_LOT_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(ORIG_TRANSACTION_QUANTITY::text), '^^') 
            , '||', IFNULL(TRIM(INV_RESERVED_ATTRIBUTE_2::text), '^^') 
            , '||', IFNULL(TRIM(TRX_SOURCE_LINE_ID::text), '^^') 
            , '||', IFNULL(TRIM(ERROR_CODE::text), '^^') 
            , '||', IFNULL(TRIM(ORGANIZATION_TYPE::text), '^^') 
            , '||', IFNULL(TRIM(ORIGINAL_TRANSACTION_TEMP_ID::text), '^^') 
            , '||', IFNULL(TRIM(TRANSFER_PRIOR_COSTED_QUANTITY::text), '^^') 
            , '||', IFNULL(TRIM(PJC_RESERVED_ATTRIBUTE_2::text), '^^') 
            , '||', IFNULL(TRIM(EMPLOYEE_CODE::text), '^^') 
            , '||', IFNULL(TRIM(CONSUMPTION_LINE_ID::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE_DATE_5::text), '^^') 
            , '||', IFNULL(TRIM(OPERATION_TRANSACTION_ID::text), '^^') 
            , '||', IFNULL(TRIM(TO_PROJECT_ID::text), '^^') 
            , '||', IFNULL(TRIM(PJC_USER_DEF_ATTRIBUTE_8::text), '^^') 
            , '||', IFNULL(TRIM(TRANSFER_TASK_ID::text), '^^') 
            , '||', IFNULL(TRIM(PRIOR_COST::text), '^^') 
            , '||', IFNULL(TRIM(NUMBER_OF_CONTAINERS::text), '^^') 
            , '||', IFNULL(TRIM(PJC_BILLABLE_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(TRX_FLOW_HEADER_ID::text), '^^') 
            , '||', IFNULL(TRIM(PRODUCT_FISC_CLASSIFICATION::text), '^^') 
            , '||', IFNULL(TRIM(REPAIR_TXN_CODE_ID::text), '^^') 
            , '||', IFNULL(TRIM(REVISION::text), '^^') 
            , '||', IFNULL(TRIM(LOCATION_TYPE::text), '^^') 
            , '||', IFNULL(TRIM(QUANTITY_ADJUSTED::text), '^^') 
            , '||', IFNULL(TRIM(SECONDARY_TRANSACTION_QUANTITY::text), '^^') 
            , '||', IFNULL(TRIM(ORIG_SUBINVENTORY_CODE::text), '^^') 
            , '||', IFNULL(TRIM(CREATED_BY::text), '^^') 
            , '||', IFNULL(TRIM(PJC_RESERVED_ATTRIBUTE_6::text), '^^') 
            , '||', IFNULL(TRIM(PERIODIC_PRIMARY_QUANTITY::text), '^^') 
            , '||', IFNULL(TRIM(SUBINVENTORY_CODE::text), '^^') 
            , '||', IFNULL(TRIM(PJC_RESERVED_ATTRIBUTE_10::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE_DATE_1::text), '^^') 
            , '||', IFNULL(TRIM(PHYSICAL_ADJUSTMENT_ID::text), '^^') 
            , '||', IFNULL(TRIM(TRANSFER_COST_GROUP_ID::text), '^^') 
            , '||', IFNULL(TRIM(TRANSFER_OWNING_TP_TYPE::text), '^^') 
            , '||', IFNULL(TRIM(TRANSFER_LOCATOR_ID::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE_17::text), '^^') 
            , '||', IFNULL(TRIM(LAST_UPDATE_LOGIN::text), '^^') 
            , '||', IFNULL(TRIM(USER_DEFINED_FISC_CLASS::text), '^^') 
            , '||', IFNULL(TRIM(INTERCOMPANY_CURRENCY_CODE::text), '^^') 
            , '||', IFNULL(TRIM(PUT_AWAY_STRATEGY_ID::text), '^^') 
            , '||', IFNULL(TRIM(PJC_RESERVED_ATTRIBUTE_5::text), '^^') 
            , '||', IFNULL(TRIM(LOT_TXN_GROUP_NAME::text), '^^') 
            , '||', IFNULL(TRIM(TAX_INVOICE_NUMBER::text), '^^') 
            , '||', IFNULL(TRIM(PJC_FUNDING_ALLOCATION_ID::text), '^^') 
            , '||', IFNULL(TRIM(CONTENT_LPN_ID::text), '^^') 
            , '||', IFNULL(TRIM(CURRENCY_CODE::text), '^^') 
            , '||', IFNULL(TRIM(PJC_EXPENDITURE_TYPE_ID::text), '^^') 
            , '||', IFNULL(TRIM(PLANNING_TP_TYPE::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE_NUMBER_2::text), '^^') 
            , '||', IFNULL(TRIM(JOB_DEFINITION_NAME::text), '^^') 
            , '||', IFNULL(TRIM(FINAL_DISCHARGE_LOCATION_ID::text), '^^') 
            , '||', IFNULL(TRIM(PICK_SLIP_DATE::text), '^^') 
            , '||', IFNULL(TRIM(FOB_POINT::text), '^^') 
            , '||', IFNULL(TRIM(ENCUMBRANCE_ACCOUNT::text), '^^') 
            , '||', IFNULL(TRIM(TRX_SOURCE_DELIVERY_ID::text), '^^') 
            , '||', IFNULL(TRIM(LAST_UPDATED_BY::text), '^^') 
            , '||', IFNULL(TRIM(PRODUCT_TYPE::text), '^^') 
            , '||', IFNULL(TRIM(TRANSFER_COST_DIST_ACCOUNT::text), '^^') 
            , '||', IFNULL(TRIM(TASK_GROUP_ID::text), '^^') 
            , '||', IFNULL(TRIM(WIP_SUPPLY_TYPE::text), '^^') 
            , '||', IFNULL(TRIM(INV_RESERVED_ATTRIBUTE_1::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE_NUMBER_10::text), '^^') 
            , '||', IFNULL(TRIM(RESERVATION_ID::text), '^^') 
            , '||', IFNULL(TRIM(INVOICED_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(TRANSACTION_COST::text), '^^') 
            , '||', IFNULL(TRIM(LOGICAL_TRANSACTIONS_CREATED::text), '^^') 
            , '||', IFNULL(TRIM(EXTERNAL_SYS_TXN_REFERENCE::text), '^^') 
            , '||', IFNULL(TRIM(DISTRIBUTION_ACCOUNT_ID::text), '^^') 
            , '||', IFNULL(TRIM(TRANSACTION_SOURCE_ID::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE_13::text), '^^') 
            , '||', IFNULL(TRIM(INV_USER_DEF_ATTRIBUTE_10::text), '^^') 
            , '||', IFNULL(TRIM(RESOURCE_ACCOUNT::text), '^^') 
            , '||', IFNULL(TRIM(COSTED_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(PM_COST_COLLECTOR_GROUP_ID::text), '^^') 
            , '||', IFNULL(TRIM(ENCUMBRANCE_AMOUNT::text), '^^') 
            , '||', IFNULL(TRIM(CONS_ERROR_TYPE_CODE::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE_9::text), '^^') 
            , '||', IFNULL(TRIM(TRANSFER_TRANSACTION_ID::text), '^^') 
            , '||', IFNULL(TRIM(TRANSACTION_ACTION_ID::text), '^^') 
            , '||', IFNULL(TRIM(TRANSACTION_UOM::text), '^^') 
            , '||', IFNULL(TRIM(PJC_RESERVED_ATTRIBUTE_1::text), '^^') 
            , '||', IFNULL(TRIM(AGING_EXPIRATION_DATE::text), '^^') 
            , '||', IFNULL(TRIM(CURRENCY_CONVERSION_DATE::text), '^^') 
            , '||', IFNULL(TRIM(PJC_USER_DEF_ATTRIBUTE_7::text), '^^') 
            , '||', IFNULL(TRIM(USSGL_TRANSACTION_CODE::text), '^^') 
            , '||', IFNULL(TRIM(DOCUMENT_SUB_TYPE::text), '^^') 
            , '||', IFNULL(TRIM(PJC_EXPENDITURE_ITEM_DATE::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE_NUMBER_1::text), '^^') 
            , '||', IFNULL(TRIM(INTRANSIT_ACCOUNT::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE_TIMESTAMP_4::text), '^^') 
            , '||', IFNULL(TRIM(PJC_RESERVED_ATTRIBUTE_3::text), '^^') 
            , '||', IFNULL(TRIM(JOB_DEFINITION_PACKAGE::text), '^^') 
            , '||', IFNULL(TRIM(LOCATOR_ID::text), '^^') 
            , '||', IFNULL(TRIM(MOVE_TRANSACTION_ID::text), '^^') 
            , '||', IFNULL(TRIM(INV_USER_DEF_ATTRIBUTE_8::text), '^^') 
            , '||', IFNULL(TRIM(USE_CURRENT_COST_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE_12::text), '^^') 
            , '||', IFNULL(TRIM(LICENSE_PLATE_NUMBER::text), '^^') 
            , '||', IFNULL(TRIM(ORIGINAL_SHIPMENT_TXN_ID::text), '^^') 
            , '||', IFNULL(TRIM(PJC_CONTRACT_LINE_ID::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE_DATE_4::text), '^^') 
            , '||', IFNULL(TRIM(COST_UPDATE_ID::text), '^^') 
            , '||', IFNULL(TRIM(SO_ISSUE_ACCOUNT_TYPE::text), '^^') 
            , '||', IFNULL(TRIM(MVT_STAT_STATUS::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE_TIMESTAMP_2::text), '^^') 
            , '||', IFNULL(TRIM(OVERCOMPLETION_TRANSACTION_QTY::text), '^^') 
            , '||', IFNULL(TRIM(TRANSFER_ORGANIZATION_ID::text), '^^') 
            , '||', IFNULL(TRIM(PICK_SLIP_NUMBER::text), '^^') 
            , '||', IFNULL(TRIM(CURRENCY_CONVERSION_RATE::text), '^^') 
            , '||', IFNULL(TRIM(OBJECT_VERSION_NUMBER::text), '^^') 
            , '||', IFNULL(TRIM(TRANSACTION_MODE::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE_19::text), '^^') 
            , '||', IFNULL(TRIM(TRANSFER_ORGANIZATION_TYPE::text), '^^') 
            , '||', IFNULL(TRIM(VARIANCE_AMOUNT::text), '^^') 
            , '||', IFNULL(TRIM(EXPENSE_ACCOUNT_ID::text), '^^') 
            , '||', IFNULL(TRIM(WAYBILL_AIRBILL::text), '^^') 
            , '||', IFNULL(TRIM(TRANSACTION_BATCH_SEQ::text), '^^') 
            , '||', IFNULL(TRIM(PRODUCT_CATEGORY::text), '^^') 
            , '||', IFNULL(TRIM(INV_USER_DEF_ATTRIBUTE_7::text), '^^') 
            , '||', IFNULL(TRIM(COMMON_ROUTING_SEQ_ID::text), '^^') 
            , '||', IFNULL(TRIM(ACTUAL_COST::text), '^^') 
            , '||', IFNULL(TRIM(OVERHEAD_ACCOUNT::text), '^^') 
            , '||', IFNULL(TRIM(CATEGORY_ID::text), '^^') 
            , '||', IFNULL(TRIM(LPN_ID::text), '^^') 
            , '||', IFNULL(TRIM(PJC_RESERVED_ATTRIBUTE_8::text), '^^') 
            , '||', IFNULL(TRIM(COMMON_BOM_SEQ_ID::text), '^^') 
            , '||', IFNULL(TRIM(ERROR_CONS_HEADER_ID::text), '^^') 
            , '||', IFNULL(TRIM(REPETITIVE_LINE_ID::text), '^^') 
            , '||', IFNULL(TRIM(PICK_SLIP_LINE_NUMBER::text), '^^') 
            , '||', IFNULL(TRIM(PJC_CONTEXT_CATEGORY::text), '^^') 
            , '||', IFNULL(TRIM(FLOW_SCHEDULE::text), '^^') 
            , '||', IFNULL(TRIM(TRANSACTION_SOURCE_NAME::text), '^^') 
            , '||', IFNULL(TRIM(TRANSACTION_QUANTITY::text), '^^') 
            , '||', IFNULL(TRIM(OWNING_TP_TYPE::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE_TIMESTAMP_1::text), '^^') 
            , '||', IFNULL(TRIM(INV_USER_DEF_ATTRIBUTE_2::text), '^^') 
            , '||', IFNULL(TRIM(LOGICAL_TRANSACTION::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE_7::text), '^^') 
            , '||', IFNULL(TRIM(ASSEMBLY_ASSET_ID::text), '^^') 
            , '||', IFNULL(TRIM(PJC_USER_DEF_ATTRIBUTE_5::text), '^^') 
            , '||', IFNULL(TRIM(TAX_CLASSIFICATION_CODE::text), '^^') 
            , '||', IFNULL(TRIM(PJC_USER_DEF_ATTRIBUTE_10::text), '^^') 
            , '||', IFNULL(TRIM(TRANSACTION_INTERFACE_LINE_NUM::text), '^^') 
            , '||', IFNULL(TRIM(PJC_TASK_ID::text), '^^') 
            , '||', IFNULL(TRIM(INTERCOMPANY_PRICING_OPTION::text), '^^') 
            , '||', IFNULL(TRIM(ASSEMBLY_SERIAL_NUMBER::text), '^^') 
            , '||', IFNULL(TRIM(XFR_OWNING_ORGANIZATION_ID::text), '^^') 
            , '||', IFNULL(TRIM(PJC_RESERVED_ATTRIBUTE_7::text), '^^') 
            , '||', IFNULL(TRIM(OVERCOMPLETION_PRIMARY_QTY::text), '^^') 
            , '||', IFNULL(TRIM(CONSUMPTION_UNIT_PRICE::text), '^^') 
            , '||', IFNULL(TRIM(TRANSACTION_BATCH_ID::text), '^^') 
            , '||', IFNULL(TRIM(REASON_ID::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE_10::text), '^^') 
            , '||', IFNULL(TRIM(RECEIVING_DOCUMENT::text), '^^') 
            , '||', IFNULL(TRIM(INTERCOMPANY_COST::text), '^^') 
            , '||', IFNULL(TRIM(TRANSPORTATION_DIST_ACCOUNT::text), '^^') 
            , '||', IFNULL(TRIM(PJC_USER_DEF_ATTRIBUTE_9::text), '^^') 
            , '||', IFNULL(TRIM(INV_USER_DEF_ATTRIBUTE_6::text), '^^') 
            , '||', IFNULL(TRIM(SHIPMENT_LINE_NUMBER::text), '^^') 
            , '||', IFNULL(TRIM(TRANSACTION_GROUP_ID::text), '^^') 
            , '||', IFNULL(TRIM(PJC_USER_DEF_ATTRIBUTE_1::text), '^^') 
            , '||', IFNULL(TRIM(TRANSACTION_SOURCE_TYPE_ID::text), '^^') 
            , '||', IFNULL(TRIM(COUNTRY_OF_ORIGIN_CODE::text), '^^') 
            , '||', IFNULL(TRIM(SHIP_TO_LOCATION_ID::text), '^^') 
            , '||', IFNULL(TRIM(CONSUMPTION_TAX_EXC_UNIT_PRICE::text), '^^') 
            , '||', IFNULL(TRIM(PARENT_ID::text), '^^') 
            , '||', IFNULL(TRIM(MATERIAL_ACCOUNT::text), '^^') 
            , '||', IFNULL(TRIM(RCV_TRANSACTION_ID::text), '^^') 
            , '||', IFNULL(TRIM(OPERATION_SEQ_NUM::text), '^^') 
            , '||', IFNULL(TRIM(ORIG_LOT_NUMBER::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE_NUMBER_6::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE_DATE_2::text), '^^') 
            , '||', IFNULL(TRIM(CYCLE_COUNT_ID::text), '^^') 
            , '||', IFNULL(TRIM(ORG_COST_GROUP_ID::text), '^^') 
            , '||', IFNULL(TRIM(INV_USER_DEF_ATTRIBUTE_4::text), '^^') 
            , '||', IFNULL(TRIM(FINAL_COMPLETION_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(MOVE_ORDER_LINE_ID::text), '^^') 
            , '||', IFNULL(TRIM(OPERATION_SEQ_NUMBER_ID::text), '^^') 
            , '||', IFNULL(TRIM(TRANSPORTATION_COST::text), '^^') 
            , '||', IFNULL(TRIM(E_RECORD_ID::text), '^^') 
            , '||', IFNULL(TRIM(IS_EVENT_PUBLISHED::text), '^^') 
            , '||', IFNULL(TRIM(PRIOR_COSTED_QUANTITY::text), '^^') 
            , '||', IFNULL(TRIM(SHORTAGE_PROCESS_CODE::text), '^^') 
            , '||', IFNULL(TRIM(TRANSFER_SUBINVENTORY::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE_6::text), '^^') 
            , '||', IFNULL(TRIM(TO_TASK_ID::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE_NUMBER_3::text), '^^') 
            , '||', IFNULL(TRIM(REQUEST_ID::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE_CATEGORY::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE_TIMESTAMP_3::text), '^^') 
            , '||', IFNULL(TRIM(SHIP_FROM_LOCATION_ID::text), '^^') 
            , '||', IFNULL(TRIM(REQUESTER_ID::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE_2::text), '^^') 
            , '||', IFNULL(TRIM(SOURCE_CODE::text), '^^') 
            , '||', IFNULL(TRIM(MASTER_SCHEDULE_UPDATE_CODE::text), '^^') 
            , '||', IFNULL(TRIM(EXEMPT_CERTIFICATE_NUMBER::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE_1::text), '^^') 
            , '||', IFNULL(TRIM(PERCENTAGE_CHANGE::text), '^^') 
            , '||', IFNULL(TRIM(PICK_STRATEGY_ID::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE_5::text), '^^') 
            , '||', IFNULL(TRIM(PJC_PROJECT_ID::text), '^^') 
            , '||', IFNULL(TRIM(CREATION_DATE::text), '^^') 
            , '||', IFNULL(TRIM(DEPARTMENT_CODE::text), '^^') 
            , '||', IFNULL(TRIM(INV_USER_DEF_ATTRIBUTE_3::text), '^^') 
            , '||', IFNULL(TRIM(PJC_USER_DEF_ATTRIBUTE_3::text), '^^') 
            , '||', IFNULL(TRIM(CURRENCY_CONVERSION_TYPE::text), '^^') 
            , '||', IFNULL(TRIM(ALM_INTERFACE_ERROR_CODE::text), '^^') 
            , '||', IFNULL(TRIM(CSE_INTERFACE_STATUS_CODE::text), '^^') 
            , '||', IFNULL(TRIM(PJC_CAPITALIZABLE_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(TRANSFER_COST::text), '^^') 
            , '||', IFNULL(TRIM(TO_GRADE_CODE::text), '^^') 
            , '||', IFNULL(TRIM(MOVEMENT_ID::text), '^^') 
            , '||', IFNULL(TRIM(QA_COLLECTION_ID::text), '^^') 
            , '||', IFNULL(TRIM(PLANNING_ORGANIZATION_ID::text), '^^') 
            , '||', IFNULL(TRIM(ERROR_EXPLANATION::text), '^^') 
            , '||', IFNULL(TRIM(COMPLETION_TRANSACTION_ID::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE_4::text), '^^') 
            , '||', IFNULL(TRIM(SOURCE_LINE_ID::text), '^^') 
            , '||', IFNULL(TRIM(PJC_RESERVED_ATTRIBUTE_4::text), '^^') 
            , '||', IFNULL(TRIM(TRANSFER_PRICE::text), '^^') 
            , '||', IFNULL(TRIM(MANUAL_RECEIPT_EXPENSE::text), '^^') 
            , '||', IFNULL(TRIM(PJC_ORGANIZATION_ID::text), '^^') 
            , '||', IFNULL(TRIM(TRANSFER_PLANNING_TP_TYPE::text), '^^') 
            , '||', IFNULL(TRIM(CONSIGNMENT_SOURCE_TXN_ID::text), '^^') 
            , '||', IFNULL(TRIM(AGING_ONSET_DATE::text), '^^') 
            , '||', IFNULL(TRIM(PJC_USER_DEF_ATTRIBUTE_4::text), '^^') 
            , '||', IFNULL(TRIM(INV_USER_DEF_ATTRIBUTE_1::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE_18::text), '^^') 
            , '||', IFNULL(TRIM(WO_EXT_SYS_GROUP_ID::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE_20::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE_11::text), '^^') 
            , '||', IFNULL(TRIM(ALM_INTERFACE_STATUS::text), '^^') 
            , '||', IFNULL(TRIM(OUTSIDE_PROCESSING_ACCOUNT::text), '^^') 
            , '||', IFNULL(TRIM(DEFAULT_TAXATION_COUNTRY::text), '^^') 
            , '||', IFNULL(TRIM(TASK_ID::text), '^^') 
            , '||', IFNULL(TRIM(INTENDED_USE_CLASSIF_ID::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE_8::text), '^^') 
            , '||', IFNULL(TRIM(FIRST_PTY_REG_ID::text), '^^') 
            , '||', IFNULL(TRIM(EXEMPT_REASON_CODE::text), '^^') 
            , '||', IFNULL(TRIM(TRANSACTION_SET_ID::text), '^^') 
            , '||', IFNULL(TRIM(INVENTORY_ITEM_ID::text), '^^') 
            , '||', IFNULL(TRIM(AVAIL_XFER_TO_CONSIGNED_QTY::text), '^^') 
            , '||', IFNULL(TRIM(SECONDARY_UOM_CODE::text), '^^') 
            , '||', IFNULL(TRIM(VENDOR_LOT_NUMBER::text), '^^') 
            , '||', IFNULL(TRIM(FROM_PROJECT_ID::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE_DATE_3::text), '^^') 
            , '||', IFNULL(TRIM(PICKING_LINE_ID::text), '^^') 
            , '||', IFNULL(TRIM(TRANSFER_PERCENTAGE::text), '^^') 
            , '||', IFNULL(TRIM(XFR_PLANNING_ORGANIZATION_ID::text), '^^') 
            , '||', IFNULL(TRIM(CONS_ERROR_ACTION_CODE::text), '^^') 
            , '||', IFNULL(TRIM(NEW_COST::text), '^^') 
            , '||', IFNULL(TRIM(TRANSACTION_TYPE_ID::text), '^^') 
            , '||', IFNULL(TRIM(COST_GROUP_ID::text), '^^') 
            , '||', IFNULL(TRIM(TRX_BUSINESS_CATEGORY::text), '^^') 
            , '||', IFNULL(TRIM(DEPARTMENT_ID::text), '^^') 
            , '||', IFNULL(TRIM(OWNING_ORGANIZATION_ID::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE_3::text), '^^') 
            , '||', IFNULL(TRIM(LOAD_REQUEST_ID::text), '^^') 
            , '||', IFNULL(TRIM(RMA_LINE_ID::text), '^^') 
            , '||', IFNULL(TRIM(TRANSFER_LPN_ID::text), '^^') 
            , '||', IFNULL(TRIM(INV_USER_DEF_ATTRIBUTE_5::text), '^^') 
            , '||', IFNULL(TRIM(TRANSACTION_DATE::text), '^^') 
            , '||', IFNULL(TRIM(TAX_INVOICE_DATE::text), '^^') 
            , '||', IFNULL(TRIM(PJC_WORK_TYPE_ID::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE_NUMBER_5::text), '^^') 
            , '||', IFNULL(TRIM(OPM_COSTED_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(PM_COST_COLLECTED::text), '^^') 
            , '||', IFNULL(TRIM(VALUE_CHANGE::text), '^^') 
            , '||', IFNULL(TRIM(TRANSACTION_REFERENCE::text), '^^') 
            , '||', IFNULL(TRIM(PJC_RESERVED_ATTRIBUTE_9::text), '^^') 
            , '||', IFNULL(TRIM(PJC_CONTRACT_ID::text), '^^') 
            , '||', IFNULL(TRIM(INV_USER_DEF_ATTRIBUTE_9::text), '^^') 
            , '||', IFNULL(TRIM(INV_STRIPING_CATEGORY::text), '^^') 
            , '||', IFNULL(TRIM(FROM_GRADE_CODE::text), '^^') 
            , '||', IFNULL(TRIM(FROM_TASK_ID::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE_15::text), '^^') 
            , '||', IFNULL(TRIM(LOGICAL_TRX_TYPE_CODE::text), '^^') 
            , '||', IFNULL(TRIM(OWNERSHIP_CHANGE_TXN_ID::text), '^^') 
            , '||', IFNULL(TRIM(PARENT_TRANSACTION_ID::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE_NUMBER_7::text), '^^') 
            , '||', IFNULL(TRIM(LAST_UPDATE_DATE::text), '^^') 
            , '||', IFNULL(TRIM(ORIG_LOCATOR_ID::text), '^^') 
            , '||', IFNULL(TRIM(PROJECT_ID::text), '^^') 
            , '||', IFNULL(TRIM(PJC_USER_DEF_ATTRIBUTE_6::text), '^^') 
            , '||', IFNULL(TRIM(ACCT_PERIOD_ID::text), '^^') 
            , '||', IFNULL(TRIM(PUT_AWAY_RULE_ID::text), '^^') 
            , '||', IFNULL(TRIM(PRIMARY_QUANTITY::text), '^^') 
            , '||', IFNULL(TRIM(COST_TYPE_ID::text), '^^') 
            , '||', IFNULL(TRIM(DEPRECIABLE_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(COGS_RECOGNITION_PERCENT::text), '^^') 
            , '||', IFNULL(TRIM(OVERCOMPLETION_TRANSACTION_ID::text), '^^') 
            , '||', IFNULL(TRIM(TRANSACTION_INTERFACE_ID::text), '^^') 
            , '||', IFNULL(TRIM(FREIGHT_CODE::text), '^^') 
            , '||', IFNULL(TRIM(MATERIAL_OVERHEAD_ACCOUNT::text), '^^') 
            , '||', IFNULL(TRIM(PICK_RULE_ID::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE_NUMBER_4::text), '^^') 
            , '||', IFNULL(TRIM(EXTERNAL_SYSTEM_PACKING_UNIT::text), '^^') 
            , '||', IFNULL(TRIM(TRANSFER_PROJECT_ID::text), '^^') 
            , '||', IFNULL(TRIM(ATTRIBUTE_TIMESTAMP_5::text), '^^') 
            , '||', IFNULL(TRIM(THIRD_PTY_REG_ID::text), '^^') 
            , '||', IFNULL(TRIM(_FIVETRAN_SYNCED::text), '^^') 
            , '||', IFNULL(TRIM(DEBRIEF_LINE_ID::text), '^^') 
            , '||', IFNULL(TRIM(ZONE_ID::text), '^^') 
            , '||', IFNULL(TRIM(SERVICE_WIP_FLAG::text), '^^') 
            , '||', IFNULL(TRIM(DELIVERY_CART_ID::text), '^^') 
            , '||', IFNULL(TRIM(MATERIAL_SEQ_NUMBER::text), '^^') 
            , '||', IFNULL(TRIM(PSA_DELETE_IND::text), '^^') 
            , '||', IFNULL(TRIM(_FIVETRAN_DELETED::text), '^^') 
        ), '^^||^^')))  as HASHDIFF
FROM JOIN_RESULT
