---- SRC LAYER ----
WITH
SRC_a              as ( SELECT BILLABLE_WEIGHT_UNIT_OF_MEASURE, BILLABLE_WEIGHT_VALUE, BILL_TO_PARTY_ADDRESS_LINE_1, BILL_TO_PARTY_ADDRESS_LINE_2, BILL_TO_PARTY_ADDRESS_LINE_3, BILL_TO_PARTY_ADDRESS_TYPE, BILL_TO_PARTY_CITY, BILL_TO_PARTY_COUNTRY, BILL_TO_PARTY_COUNTRY_CODE, BILL_TO_PARTY_DISTRICT, BILL_TO_PARTY_DISTRICT_OR_COUNTY, BILL_TO_PARTY_MUNICIPALITY, BILL_TO_PARTY_NAME, BILL_TO_PARTY_PARTY_ID, BILL_TO_PARTY_PHONE, BILL_TO_PARTY_POSTAL_CODE, BILL_TO_PARTY_STATE_OR_REGION, BILL_TO_PARTY_TAX_REGISTRATION_NUMBER, BILL_TO_PARTY_TAX_REGISTRATION_TYPE, BUYING_PARTY_ADDRESS_LINE_1, BUYING_PARTY_ADDRESS_LINE_2, BUYING_PARTY_ADDRESS_LINE_3, BUYING_PARTY_ADDRESS_TYPE, BUYING_PARTY_CITY, BUYING_PARTY_COUNTRY, BUYING_PARTY_COUNTRY_CODE, BUYING_PARTY_DISTRICT, BUYING_PARTY_DISTRICT_OR_COUNTY, BUYING_PARTY_MUNICIPALITY, BUYING_PARTY_NAME, BUYING_PARTY_PARTY_ID, BUYING_PARTY_PHONE, BUYING_PARTY_POSTAL_CODE, BUYING_PARTY_STATE_OR_REGION, BUYING_PARTY_TAX_REGISTRATION_NUMBER, BUYING_PARTY_TAX_REGISTRATION_TYPE, DEAL_CODE, DELIVERY_WINDOW, ESTIMATED_SHIP_BY_DATE, HANDLING_INSTRUCTIONS, IMPORT_CONTAINERS, INTERNATIONAL_COMMERCIAL_TERMS, METHOD_OF_PAYMENT, PAYMENT_METHOD, PORT_OF_DELIVERY, PSA_DELETE_IND, PSA_LOAD_DTS, PSA_RECORD_SOURCE, PURCHASE_ORDER_CHANGED_DATE, PURCHASE_ORDER_DATE, PURCHASE_ORDER_NUMBER, PURCHASE_ORDER_STATE, PURCHASE_ORDER_STATE_CHANGED_DATE, PURCHASE_ORDER_TYPE, SEAL_NUMBER, SELLING_PARTY_ADDRESS_LINE_1, SELLING_PARTY_ADDRESS_LINE_2, SELLING_PARTY_ADDRESS_LINE_3, SELLING_PARTY_ADDRESS_TYPE, SELLING_PARTY_CITY, SELLING_PARTY_COUNTRY, SELLING_PARTY_COUNTRY_CODE, SELLING_PARTY_DISTRICT, SELLING_PARTY_DISTRICT_OR_COUNTY, SELLING_PARTY_MUNICIPALITY, SELLING_PARTY_NAME, SELLING_PARTY_PARTY_ID, SELLING_PARTY_PHONE, SELLING_PARTY_POSTAL_CODE, SELLING_PARTY_STATE_OR_REGION, SELLING_PARTY_TAX_REGISTRATION_NUMBER, SELLING_PARTY_TAX_REGISTRATION_TYPE, SHIPPING_INSTRUCTIONS, SHIP_TO_PARTY_ADDRESS_LINE_1, SHIP_TO_PARTY_ADDRESS_LINE_2, SHIP_TO_PARTY_ADDRESS_LINE_3, SHIP_TO_PARTY_ADDRESS_TYPE, SHIP_TO_PARTY_CITY, SHIP_TO_PARTY_COUNTRY, SHIP_TO_PARTY_COUNTRY_CODE, SHIP_TO_PARTY_DISTRICT, SHIP_TO_PARTY_DISTRICT_OR_COUNTY, SHIP_TO_PARTY_MUNICIPALITY, SHIP_TO_PARTY_NAME, SHIP_TO_PARTY_PARTY_ID, SHIP_TO_PARTY_PHONE, SHIP_TO_PARTY_POSTAL_CODE, SHIP_TO_PARTY_STATE_OR_REGION, SHIP_TO_PARTY_TAX_REGISTRATION_NUMBER, SHIP_TO_PARTY_TAX_REGISTRATION_TYPE, SHIP_WINDOW, _FIVETRAN_SYNCED FROM {{ source('amazon_sp_ft_moen_inc', 'vendor_retail_procurement_order') }} as SRC  ),
SRC_bkcc           as ( SELECT BKCC, REC_SRC FROM {{ ref('ref_business_key_collision') }} as SRC  )

/*
SRC_a              as ( SELECT * FROM amazon_sp_ft_moen_inc.vendor_retail_procurement_order )
SRC_bkcc           as ( SELECT * FROM raw_vault.ref_business_key_collision )
*/
---- LOGIC LAYER ----

, LOGIC_a as (
    SELECT
        PURCHASE_ORDER_NUMBER                                        as                                    VENDOR_ORDER_BK
      , PURCHASE_ORDER_DATE
      , PURCHASE_ORDER_NUMBER
      , PURCHASE_ORDER_STATE
      , PURCHASE_ORDER_CHANGED_DATE
      , PURCHASE_ORDER_STATE_CHANGED_DATE
      , PURCHASE_ORDER_TYPE
      , METHOD_OF_PAYMENT
      , INTERNATIONAL_COMMERCIAL_TERMS
      , PORT_OF_DELIVERY
      , IMPORT_CONTAINERS
      , SHIPPING_INSTRUCTIONS
      , SEAL_NUMBER
      , BILLABLE_WEIGHT_UNIT_OF_MEASURE
      , BILLABLE_WEIGHT_VALUE
      , ESTIMATED_SHIP_BY_DATE
      , HANDLING_INSTRUCTIONS
      , DEAL_CODE
      , PAYMENT_METHOD
      , BUYING_PARTY_PARTY_ID
      , BUYING_PARTY_NAME
      , BUYING_PARTY_ADDRESS_LINE_1
      , BUYING_PARTY_ADDRESS_LINE_2
      , BUYING_PARTY_ADDRESS_LINE_3
      , BUYING_PARTY_CITY
      , BUYING_PARTY_DISTRICT_OR_COUNTY
      , BUYING_PARTY_COUNTRY
      , BUYING_PARTY_DISTRICT
      , BUYING_PARTY_STATE_OR_REGION
      , BUYING_PARTY_MUNICIPALITY
      , BUYING_PARTY_POSTAL_CODE
      , BUYING_PARTY_COUNTRY_CODE
      , BUYING_PARTY_PHONE
      , BUYING_PARTY_ADDRESS_TYPE
      , BUYING_PARTY_TAX_REGISTRATION_TYPE
      , BUYING_PARTY_TAX_REGISTRATION_NUMBER
      , SELLING_PARTY_PARTY_ID
      , SELLING_PARTY_NAME
      , SELLING_PARTY_ADDRESS_LINE_1
      , SELLING_PARTY_ADDRESS_LINE_2
      , SELLING_PARTY_ADDRESS_LINE_3
      , SELLING_PARTY_CITY
      , SELLING_PARTY_DISTRICT_OR_COUNTY
      , SELLING_PARTY_COUNTRY
      , SELLING_PARTY_DISTRICT
      , SELLING_PARTY_STATE_OR_REGION
      , SELLING_PARTY_MUNICIPALITY
      , SELLING_PARTY_POSTAL_CODE
      , SELLING_PARTY_COUNTRY_CODE
      , SELLING_PARTY_PHONE
      , SELLING_PARTY_ADDRESS_TYPE
      , SELLING_PARTY_TAX_REGISTRATION_TYPE
      , SELLING_PARTY_TAX_REGISTRATION_NUMBER
      , SHIP_TO_PARTY_PARTY_ID
      , SHIP_TO_PARTY_NAME
      , SHIP_TO_PARTY_ADDRESS_LINE_1
      , SHIP_TO_PARTY_ADDRESS_LINE_2
      , SHIP_TO_PARTY_ADDRESS_LINE_3
      , SHIP_TO_PARTY_CITY
      , SHIP_TO_PARTY_DISTRICT_OR_COUNTY
      , SHIP_TO_PARTY_COUNTRY
      , SHIP_TO_PARTY_DISTRICT
      , SHIP_TO_PARTY_STATE_OR_REGION
      , SHIP_TO_PARTY_MUNICIPALITY
      , SHIP_TO_PARTY_POSTAL_CODE
      , SHIP_TO_PARTY_COUNTRY_CODE
      , SHIP_TO_PARTY_PHONE
      , SHIP_TO_PARTY_ADDRESS_TYPE
      , SHIP_TO_PARTY_TAX_REGISTRATION_TYPE
      , SHIP_TO_PARTY_TAX_REGISTRATION_NUMBER
      , BILL_TO_PARTY_PARTY_ID
      , BILL_TO_PARTY_NAME
      , BILL_TO_PARTY_ADDRESS_LINE_1
      , BILL_TO_PARTY_ADDRESS_LINE_2
      , BILL_TO_PARTY_ADDRESS_LINE_3
      , BILL_TO_PARTY_CITY
      , BILL_TO_PARTY_DISTRICT_OR_COUNTY
      , BILL_TO_PARTY_COUNTRY
      , BILL_TO_PARTY_DISTRICT
      , BILL_TO_PARTY_STATE_OR_REGION
      , BILL_TO_PARTY_MUNICIPALITY
      , BILL_TO_PARTY_POSTAL_CODE
      , BILL_TO_PARTY_COUNTRY_CODE
      , BILL_TO_PARTY_PHONE
      , BILL_TO_PARTY_ADDRESS_TYPE
      , BILL_TO_PARTY_TAX_REGISTRATION_TYPE
      , BILL_TO_PARTY_TAX_REGISTRATION_NUMBER
      , SHIP_WINDOW
      , DELIVERY_WINDOW
      , _FIVETRAN_SYNCED
      , PSA_LOAD_DTS
      , PSA_RECORD_SOURCE
      , PSA_DELETE_IND
      , IFF(
            PSA_DELETE_IND = 'Y',
            PSA_LOAD_DTS, CONVERT_TIMEZONE('UTC',_FIVETRAN_SYNCED)) as LOAD_DTS
    FROM SRC_a
)

, LOGIC_bkcc as (
    SELECT
        REC_SRC
      , BKCC
    FROM SRC_bkcc
)
---- RENAME LAYER ----

, RENAME_a as (
    SELECT
        VENDOR_ORDER_BK
      , PURCHASE_ORDER_DATE
      , PURCHASE_ORDER_NUMBER
      , PURCHASE_ORDER_STATE
      , PURCHASE_ORDER_CHANGED_DATE
      , PURCHASE_ORDER_STATE_CHANGED_DATE
      , PURCHASE_ORDER_TYPE
      , METHOD_OF_PAYMENT
      , INTERNATIONAL_COMMERCIAL_TERMS
      , PORT_OF_DELIVERY
      , IMPORT_CONTAINERS
      , SHIPPING_INSTRUCTIONS
      , SEAL_NUMBER
      , BILLABLE_WEIGHT_UNIT_OF_MEASURE
      , BILLABLE_WEIGHT_VALUE
      , ESTIMATED_SHIP_BY_DATE
      , HANDLING_INSTRUCTIONS
      , DEAL_CODE
      , PAYMENT_METHOD
      , BUYING_PARTY_PARTY_ID
      , BUYING_PARTY_NAME
      , BUYING_PARTY_ADDRESS_LINE_1
      , BUYING_PARTY_ADDRESS_LINE_2
      , BUYING_PARTY_ADDRESS_LINE_3
      , BUYING_PARTY_CITY
      , BUYING_PARTY_DISTRICT_OR_COUNTY
      , BUYING_PARTY_COUNTRY
      , BUYING_PARTY_DISTRICT
      , BUYING_PARTY_STATE_OR_REGION
      , BUYING_PARTY_MUNICIPALITY
      , BUYING_PARTY_POSTAL_CODE
      , BUYING_PARTY_COUNTRY_CODE
      , BUYING_PARTY_PHONE
      , BUYING_PARTY_ADDRESS_TYPE
      , BUYING_PARTY_TAX_REGISTRATION_TYPE
      , BUYING_PARTY_TAX_REGISTRATION_NUMBER
      , SELLING_PARTY_PARTY_ID
      , SELLING_PARTY_NAME
      , SELLING_PARTY_ADDRESS_LINE_1
      , SELLING_PARTY_ADDRESS_LINE_2
      , SELLING_PARTY_ADDRESS_LINE_3
      , SELLING_PARTY_CITY
      , SELLING_PARTY_DISTRICT_OR_COUNTY
      , SELLING_PARTY_COUNTRY
      , SELLING_PARTY_DISTRICT
      , SELLING_PARTY_STATE_OR_REGION
      , SELLING_PARTY_MUNICIPALITY
      , SELLING_PARTY_POSTAL_CODE
      , SELLING_PARTY_COUNTRY_CODE
      , SELLING_PARTY_PHONE
      , SELLING_PARTY_ADDRESS_TYPE
      , SELLING_PARTY_TAX_REGISTRATION_TYPE
      , SELLING_PARTY_TAX_REGISTRATION_NUMBER
      , SHIP_TO_PARTY_PARTY_ID
      , SHIP_TO_PARTY_NAME
      , SHIP_TO_PARTY_ADDRESS_LINE_1
      , SHIP_TO_PARTY_ADDRESS_LINE_2
      , SHIP_TO_PARTY_ADDRESS_LINE_3
      , SHIP_TO_PARTY_CITY
      , SHIP_TO_PARTY_DISTRICT_OR_COUNTY
      , SHIP_TO_PARTY_COUNTRY
      , SHIP_TO_PARTY_DISTRICT
      , SHIP_TO_PARTY_STATE_OR_REGION
      , SHIP_TO_PARTY_MUNICIPALITY
      , SHIP_TO_PARTY_POSTAL_CODE
      , SHIP_TO_PARTY_COUNTRY_CODE
      , SHIP_TO_PARTY_PHONE
      , SHIP_TO_PARTY_ADDRESS_TYPE
      , SHIP_TO_PARTY_TAX_REGISTRATION_TYPE
      , SHIP_TO_PARTY_TAX_REGISTRATION_NUMBER
      , BILL_TO_PARTY_PARTY_ID
      , BILL_TO_PARTY_NAME
      , BILL_TO_PARTY_ADDRESS_LINE_1
      , BILL_TO_PARTY_ADDRESS_LINE_2
      , BILL_TO_PARTY_ADDRESS_LINE_3
      , BILL_TO_PARTY_CITY
      , BILL_TO_PARTY_DISTRICT_OR_COUNTY
      , BILL_TO_PARTY_COUNTRY
      , BILL_TO_PARTY_DISTRICT
      , BILL_TO_PARTY_STATE_OR_REGION
      , BILL_TO_PARTY_MUNICIPALITY
      , BILL_TO_PARTY_POSTAL_CODE
      , BILL_TO_PARTY_COUNTRY_CODE
      , BILL_TO_PARTY_PHONE
      , BILL_TO_PARTY_ADDRESS_TYPE
      , BILL_TO_PARTY_TAX_REGISTRATION_TYPE
      , BILL_TO_PARTY_TAX_REGISTRATION_NUMBER
      , SHIP_WINDOW
      , DELIVERY_WINDOW
      , _FIVETRAN_SYNCED
      , PSA_LOAD_DTS
      , PSA_RECORD_SOURCE
      , PSA_DELETE_IND
      , LOAD_DTS
    FROM LOGIC_a
)

, RENAME_bkcc as (
    SELECT
        REC_SRC
      , BKCC
    FROM LOGIC_bkcc
)
---- FILTER LAYER ----

, FILTER_a as (
    SELECT *
    FROM RENAME_a
)

, FILTER_bkcc as (
    SELECT *
    FROM RENAME_bkcc
    WHERE rec_src = 'US.API_FT.AMAZON_VC.VENDOR_RETAIL_PROCUREMENT_ORDER'
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM FILTER_a
    INNER JOIN FILTER_bkcc
        ON '1' = '1'
)

---- FINAL LAYER ----
SELECT
          VENDOR_ORDER_BK
        , PURCHASE_ORDER_DATE
        , PURCHASE_ORDER_NUMBER
        , PURCHASE_ORDER_STATE
        , PURCHASE_ORDER_CHANGED_DATE
        , PURCHASE_ORDER_STATE_CHANGED_DATE
        , PURCHASE_ORDER_TYPE
        , METHOD_OF_PAYMENT
        , INTERNATIONAL_COMMERCIAL_TERMS
        , PORT_OF_DELIVERY
        , IMPORT_CONTAINERS
        , SHIPPING_INSTRUCTIONS
        , SEAL_NUMBER
        , BILLABLE_WEIGHT_UNIT_OF_MEASURE
        , BILLABLE_WEIGHT_VALUE
        , ESTIMATED_SHIP_BY_DATE
        , HANDLING_INSTRUCTIONS
        , DEAL_CODE
        , PAYMENT_METHOD
        , BUYING_PARTY_PARTY_ID
        , BUYING_PARTY_NAME
        , BUYING_PARTY_ADDRESS_LINE_1
        , BUYING_PARTY_ADDRESS_LINE_2
        , BUYING_PARTY_ADDRESS_LINE_3
        , BUYING_PARTY_CITY
        , BUYING_PARTY_DISTRICT_OR_COUNTY
        , BUYING_PARTY_COUNTRY
        , BUYING_PARTY_DISTRICT
        , BUYING_PARTY_STATE_OR_REGION
        , BUYING_PARTY_MUNICIPALITY
        , BUYING_PARTY_POSTAL_CODE
        , BUYING_PARTY_COUNTRY_CODE
        , BUYING_PARTY_PHONE
        , BUYING_PARTY_ADDRESS_TYPE
        , BUYING_PARTY_TAX_REGISTRATION_TYPE
        , BUYING_PARTY_TAX_REGISTRATION_NUMBER
        , SELLING_PARTY_PARTY_ID
        , SELLING_PARTY_NAME
        , SELLING_PARTY_ADDRESS_LINE_1
        , SELLING_PARTY_ADDRESS_LINE_2
        , SELLING_PARTY_ADDRESS_LINE_3
        , SELLING_PARTY_CITY
        , SELLING_PARTY_DISTRICT_OR_COUNTY
        , SELLING_PARTY_COUNTRY
        , SELLING_PARTY_DISTRICT
        , SELLING_PARTY_STATE_OR_REGION
        , SELLING_PARTY_MUNICIPALITY
        , SELLING_PARTY_POSTAL_CODE
        , SELLING_PARTY_COUNTRY_CODE
        , SELLING_PARTY_PHONE
        , SELLING_PARTY_ADDRESS_TYPE
        , SELLING_PARTY_TAX_REGISTRATION_TYPE
        , SELLING_PARTY_TAX_REGISTRATION_NUMBER
        , SHIP_TO_PARTY_PARTY_ID
        , SHIP_TO_PARTY_NAME
        , SHIP_TO_PARTY_ADDRESS_LINE_1
        , SHIP_TO_PARTY_ADDRESS_LINE_2
        , SHIP_TO_PARTY_ADDRESS_LINE_3
        , SHIP_TO_PARTY_CITY
        , SHIP_TO_PARTY_DISTRICT_OR_COUNTY
        , SHIP_TO_PARTY_COUNTRY
        , SHIP_TO_PARTY_DISTRICT
        , SHIP_TO_PARTY_STATE_OR_REGION
        , SHIP_TO_PARTY_MUNICIPALITY
        , SHIP_TO_PARTY_POSTAL_CODE
        , SHIP_TO_PARTY_COUNTRY_CODE
        , SHIP_TO_PARTY_PHONE
        , SHIP_TO_PARTY_ADDRESS_TYPE
        , SHIP_TO_PARTY_TAX_REGISTRATION_TYPE
        , SHIP_TO_PARTY_TAX_REGISTRATION_NUMBER
        , BILL_TO_PARTY_PARTY_ID
        , BILL_TO_PARTY_NAME
        , BILL_TO_PARTY_ADDRESS_LINE_1
        , BILL_TO_PARTY_ADDRESS_LINE_2
        , BILL_TO_PARTY_ADDRESS_LINE_3
        , BILL_TO_PARTY_CITY
        , BILL_TO_PARTY_DISTRICT_OR_COUNTY
        , BILL_TO_PARTY_COUNTRY
        , BILL_TO_PARTY_DISTRICT
        , BILL_TO_PARTY_STATE_OR_REGION
        , BILL_TO_PARTY_MUNICIPALITY
        , BILL_TO_PARTY_POSTAL_CODE
        , BILL_TO_PARTY_COUNTRY_CODE
        , BILL_TO_PARTY_PHONE
        , BILL_TO_PARTY_ADDRESS_TYPE
        , BILL_TO_PARTY_TAX_REGISTRATION_TYPE
        , BILL_TO_PARTY_TAX_REGISTRATION_NUMBER
        , SHIP_WINDOW
        , DELIVERY_WINDOW
        , _FIVETRAN_SYNCED
        , PSA_LOAD_DTS
        , PSA_RECORD_SOURCE
        , PSA_DELETE_IND
        , LOAD_DTS
        , REC_SRC
        , BKCC
        , MD5_BINARY(UPPER(CONCAT_WS('||',
          COALESCE(NULLIF(TRIM(CAST(VENDOR_ORDER_BK as VARCHAR)),''), '^^')
        , COALESCE(NULLIF(TRIM(CAST(BKCC as VARCHAR)),''), '^^')
        ))) as VENDOR_ORDER_HK
        , MD5_BINARY(UPPER(NULLIF(CONCAT(
              IFNULL(TRIM(PURCHASE_ORDER_DATE::text), '^^') 
            , '||', IFNULL(TRIM(PURCHASE_ORDER_STATE::text), '^^') 
            , '||', IFNULL(TRIM(PURCHASE_ORDER_CHANGED_DATE::text), '^^') 
            , '||', IFNULL(TRIM(PURCHASE_ORDER_STATE_CHANGED_DATE::text), '^^') 
            , '||', IFNULL(TRIM(PURCHASE_ORDER_TYPE::text), '^^') 
            , '||', IFNULL(TRIM(METHOD_OF_PAYMENT::text), '^^') 
            , '||', IFNULL(TRIM(INTERNATIONAL_COMMERCIAL_TERMS::text), '^^') 
            , '||', IFNULL(TRIM(PORT_OF_DELIVERY::text), '^^') 
            , '||', IFNULL(TRIM(IMPORT_CONTAINERS::text), '^^') 
            , '||', IFNULL(TRIM(SHIPPING_INSTRUCTIONS::text), '^^') 
            , '||', IFNULL(TRIM(SEAL_NUMBER::text), '^^') 
            , '||', IFNULL(TRIM(BILLABLE_WEIGHT_UNIT_OF_MEASURE::text), '^^') 
            , '||', IFNULL(TRIM(BILLABLE_WEIGHT_VALUE::text), '^^') 
            , '||', IFNULL(TRIM(ESTIMATED_SHIP_BY_DATE::text), '^^') 
            , '||', IFNULL(TRIM(HANDLING_INSTRUCTIONS::text), '^^') 
            , '||', IFNULL(TRIM(DEAL_CODE::text), '^^') 
            , '||', IFNULL(TRIM(PAYMENT_METHOD::text), '^^') 
            , '||', IFNULL(TRIM(BUYING_PARTY_PARTY_ID::text), '^^') 
            , '||', IFNULL(TRIM(BUYING_PARTY_NAME::text), '^^') 
            , '||', IFNULL(TRIM(BUYING_PARTY_ADDRESS_LINE_1::text), '^^') 
            , '||', IFNULL(TRIM(BUYING_PARTY_ADDRESS_LINE_2::text), '^^') 
            , '||', IFNULL(TRIM(BUYING_PARTY_ADDRESS_LINE_3::text), '^^') 
            , '||', IFNULL(TRIM(BUYING_PARTY_CITY::text), '^^') 
            , '||', IFNULL(TRIM(BUYING_PARTY_DISTRICT_OR_COUNTY::text), '^^') 
            , '||', IFNULL(TRIM(BUYING_PARTY_COUNTRY::text), '^^') 
            , '||', IFNULL(TRIM(BUYING_PARTY_DISTRICT::text), '^^') 
            , '||', IFNULL(TRIM(BUYING_PARTY_STATE_OR_REGION::text), '^^') 
            , '||', IFNULL(TRIM(BUYING_PARTY_MUNICIPALITY::text), '^^') 
            , '||', IFNULL(TRIM(BUYING_PARTY_POSTAL_CODE::text), '^^') 
            , '||', IFNULL(TRIM(BUYING_PARTY_COUNTRY_CODE::text), '^^') 
            , '||', IFNULL(TRIM(BUYING_PARTY_PHONE::text), '^^') 
            , '||', IFNULL(TRIM(BUYING_PARTY_ADDRESS_TYPE::text), '^^') 
            , '||', IFNULL(TRIM(BUYING_PARTY_TAX_REGISTRATION_TYPE::text), '^^') 
            , '||', IFNULL(TRIM(BUYING_PARTY_TAX_REGISTRATION_NUMBER::text), '^^') 
            , '||', IFNULL(TRIM(SELLING_PARTY_PARTY_ID::text), '^^') 
            , '||', IFNULL(TRIM(SELLING_PARTY_NAME::text), '^^') 
            , '||', IFNULL(TRIM(SELLING_PARTY_ADDRESS_LINE_1::text), '^^') 
            , '||', IFNULL(TRIM(SELLING_PARTY_ADDRESS_LINE_2::text), '^^') 
            , '||', IFNULL(TRIM(SELLING_PARTY_ADDRESS_LINE_3::text), '^^') 
            , '||', IFNULL(TRIM(SELLING_PARTY_CITY::text), '^^') 
            , '||', IFNULL(TRIM(SELLING_PARTY_DISTRICT_OR_COUNTY::text), '^^') 
            , '||', IFNULL(TRIM(SELLING_PARTY_COUNTRY::text), '^^') 
            , '||', IFNULL(TRIM(SELLING_PARTY_DISTRICT::text), '^^') 
            , '||', IFNULL(TRIM(SELLING_PARTY_STATE_OR_REGION::text), '^^') 
            , '||', IFNULL(TRIM(SELLING_PARTY_MUNICIPALITY::text), '^^') 
            , '||', IFNULL(TRIM(SELLING_PARTY_POSTAL_CODE::text), '^^') 
            , '||', IFNULL(TRIM(SELLING_PARTY_COUNTRY_CODE::text), '^^') 
            , '||', IFNULL(TRIM(SELLING_PARTY_PHONE::text), '^^') 
            , '||', IFNULL(TRIM(SELLING_PARTY_ADDRESS_TYPE::text), '^^') 
            , '||', IFNULL(TRIM(SELLING_PARTY_TAX_REGISTRATION_TYPE::text), '^^') 
            , '||', IFNULL(TRIM(SELLING_PARTY_TAX_REGISTRATION_NUMBER::text), '^^') 
            , '||', IFNULL(TRIM(SHIP_TO_PARTY_PARTY_ID::text), '^^') 
            , '||', IFNULL(TRIM(SHIP_TO_PARTY_NAME::text), '^^') 
            , '||', IFNULL(TRIM(SHIP_TO_PARTY_ADDRESS_LINE_1::text), '^^') 
            , '||', IFNULL(TRIM(SHIP_TO_PARTY_ADDRESS_LINE_2::text), '^^') 
            , '||', IFNULL(TRIM(SHIP_TO_PARTY_ADDRESS_LINE_3::text), '^^') 
            , '||', IFNULL(TRIM(SHIP_TO_PARTY_CITY::text), '^^') 
            , '||', IFNULL(TRIM(SHIP_TO_PARTY_DISTRICT_OR_COUNTY::text), '^^') 
            , '||', IFNULL(TRIM(SHIP_TO_PARTY_COUNTRY::text), '^^') 
            , '||', IFNULL(TRIM(SHIP_TO_PARTY_DISTRICT::text), '^^') 
            , '||', IFNULL(TRIM(SHIP_TO_PARTY_STATE_OR_REGION::text), '^^') 
            , '||', IFNULL(TRIM(SHIP_TO_PARTY_MUNICIPALITY::text), '^^') 
            , '||', IFNULL(TRIM(SHIP_TO_PARTY_POSTAL_CODE::text), '^^') 
            , '||', IFNULL(TRIM(SHIP_TO_PARTY_COUNTRY_CODE::text), '^^') 
            , '||', IFNULL(TRIM(SHIP_TO_PARTY_PHONE::text), '^^') 
            , '||', IFNULL(TRIM(SHIP_TO_PARTY_ADDRESS_TYPE::text), '^^') 
            , '||', IFNULL(TRIM(SHIP_TO_PARTY_TAX_REGISTRATION_TYPE::text), '^^') 
            , '||', IFNULL(TRIM(SHIP_TO_PARTY_TAX_REGISTRATION_NUMBER::text), '^^') 
            , '||', IFNULL(TRIM(BILL_TO_PARTY_PARTY_ID::text), '^^') 
            , '||', IFNULL(TRIM(BILL_TO_PARTY_NAME::text), '^^') 
            , '||', IFNULL(TRIM(BILL_TO_PARTY_ADDRESS_LINE_1::text), '^^') 
            , '||', IFNULL(TRIM(BILL_TO_PARTY_ADDRESS_LINE_2::text), '^^') 
            , '||', IFNULL(TRIM(BILL_TO_PARTY_ADDRESS_LINE_3::text), '^^') 
            , '||', IFNULL(TRIM(BILL_TO_PARTY_CITY::text), '^^') 
            , '||', IFNULL(TRIM(BILL_TO_PARTY_DISTRICT_OR_COUNTY::text), '^^') 
            , '||', IFNULL(TRIM(BILL_TO_PARTY_COUNTRY::text), '^^') 
            , '||', IFNULL(TRIM(BILL_TO_PARTY_DISTRICT::text), '^^') 
            , '||', IFNULL(TRIM(BILL_TO_PARTY_STATE_OR_REGION::text), '^^') 
            , '||', IFNULL(TRIM(BILL_TO_PARTY_MUNICIPALITY::text), '^^') 
            , '||', IFNULL(TRIM(BILL_TO_PARTY_POSTAL_CODE::text), '^^') 
            , '||', IFNULL(TRIM(BILL_TO_PARTY_COUNTRY_CODE::text), '^^') 
            , '||', IFNULL(TRIM(BILL_TO_PARTY_PHONE::text), '^^') 
            , '||', IFNULL(TRIM(BILL_TO_PARTY_ADDRESS_TYPE::text), '^^') 
            , '||', IFNULL(TRIM(BILL_TO_PARTY_TAX_REGISTRATION_TYPE::text), '^^') 
            , '||', IFNULL(TRIM(BILL_TO_PARTY_TAX_REGISTRATION_NUMBER::text), '^^') 
            , '||', IFNULL(TRIM(SHIP_WINDOW::text), '^^') 
            , '||', IFNULL(TRIM(DELIVERY_WINDOW::text), '^^') 
            , '||', IFNULL(TRIM(PSA_DELETE_IND::text), '^^') 
        ), '^^||^^')))  as HASHDIFF
FROM JOIN_RESULT
