---- SRC LAYER ----
WITH
SRC_ZSERVLEVEL     as ( SELECT CUSTOMER_HK, DISTRIBUTION_CHANNEL_HK, DIVISION_HK, GOODS_STORAGE_LOCATION_HK, ITEM_HK, LNK_SERVICE_LEVELS_HK, LOAD_DTS, ORDER_HEADER_HK, ORDER_LINE_HK, PLANT_HK, REC_SRC, SALES_ORGANIZATION_HK, ZSERVCODE FROM {{ ref('v_psa_stg_service_levels__winn_sap') }} as SRC 
                        QUALIFY ROW_NUMBER() OVER(PARTITION BY LNK_SERVICE_LEVELS_HK ORDER BY LOAD_DTS )=1 )

/*
SRC_ZSERVLEVEL     as ( SELECT * FROM STAGING.v_psa_stg_service_levels__winn_sap )
*/
---- LOGIC LAYER ----

, LOGIC_ZSERVLEVEL as (
    SELECT
        LNK_SERVICE_LEVELS_HK
      , ORDER_HEADER_HK
      , ORDER_LINE_HK
      , CUSTOMER_HK
      , SALES_ORGANIZATION_HK
      , DISTRIBUTION_CHANNEL_HK
      , DIVISION_HK
      , ITEM_HK
      , PLANT_HK
      , GOODS_STORAGE_LOCATION_HK
      , ZSERVCODE
      , LOAD_DTS
      , REC_SRC
    FROM SRC_ZSERVLEVEL
)
---- RENAME LAYER ----

, RENAME_ZSERVLEVEL as (
    SELECT
        LNK_SERVICE_LEVELS_HK
      , ORDER_HEADER_HK
      , ORDER_LINE_HK
      , CUSTOMER_HK
      , SALES_ORGANIZATION_HK
      , DISTRIBUTION_CHANNEL_HK
      , DIVISION_HK
      , ITEM_HK
      , PLANT_HK
      , GOODS_STORAGE_LOCATION_HK
      , ZSERVCODE
      , LOAD_DTS
      , REC_SRC
    FROM LOGIC_ZSERVLEVEL
)
---- FILTER LAYER ----

, FILTER_ZSERVLEVEL as (
    SELECT *
    FROM RENAME_ZSERVLEVEL
)
---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT * FROM FILTER_ZSERVLEVEL
)

---- FINAL LAYER ----
SELECT
          LNK_SERVICE_LEVELS_HK
        , ORDER_HEADER_HK
        , ORDER_LINE_HK
        , CUSTOMER_HK
        , SALES_ORGANIZATION_HK
        , DISTRIBUTION_CHANNEL_HK
        , DIVISION_HK
        , ITEM_HK
        , PLANT_HK
        , GOODS_STORAGE_LOCATION_HK
        , ZSERVCODE
        , LOAD_DTS
        , REC_SRC
FROM JOIN_RESULT
{% if is_incremental() %}
WHERE NOT EXISTS (
    SELECT 1 
    FROM {{ this }} existing
    WHERE existing.LNK_SERVICE_LEVELS_HK = JOIN_RESULT.LNK_SERVICE_LEVELS_HK
)
{% endif %}
{% if not is_incremental() %}

union all
SELECT 
MD5_BINARY(GR.VALUE) AS LNK_SERVICE_LEVELS_HK,
MD5_BINARY(GR.VALUE) AS ORDER_HEADER_HK,
MD5_BINARY(GR.VALUE) AS ORDER_LINE_HK,
MD5_BINARY(GR.VALUE) AS CUSTOMER_HK,
MD5_BINARY(GR.VALUE) AS SALES_ORGANIZATION_HK,
MD5_BINARY(GR.VALUE) AS DISTRIBUTION_CHANNEL_HK,
MD5_BINARY(GR.VALUE) AS DIVISION_HK,
MD5_BINARY(GR.VALUE) AS ITEM_HK,
MD5_BINARY(GR.VALUE) AS PLANT_HK,
MD5_BINARY(GR.VALUE) AS GOODS_STORAGE_LOCATION_HK,
GR.VALUE::text AS ZSERVCODE,
CONVERT_TIMEZONE('UTC','1900-01-01'::TIMESTAMP) AS LOAD_DTS,
'USAZET.SNOWFLAKE.FBIN.DERIVED' AS REC_SRC
FROM
TABLE(strtok_split_to_table('0|-1|-2', '|')) AS GR
{% endif %}
