---- SRC LAYER ----
WITH
SRC_SCSMWS         as ( SELECT CUSTOMER_HK, DISTRIBUTION_CHANNEL_HK, DIVISION_HK, LNK_CUSTOMER_SALES_ORGANIZATION_DISTRIBUTION_CHANNEL_DIVISION_HK, 
                        LOAD_DTS, REC_SRC, SALES_ORGANIZATION_HK FROM {{ ref('v_psa_stg_customer_sales_master__winn_sap') }} as SRC 
                        QUALIFY ROW_NUMBER() OVER(PARTITION BY LNK_CUSTOMER_SALES_ORGANIZATION_DISTRIBUTION_CHANNEL_DIVISION_HK ORDER BY LOAD_DTS )=1 ),
SRC_ZSERVLEVEL     as ( SELECT CUSTOMER_HK, DISTRIBUTION_CHANNEL_HK, DIVISION_HK, LNK_CUSTOMER_SALES_ORGANIZATION_DISTRIBUTION_CHANNEL_DIVISION_HK, 
                        LOAD_DTS, REC_SRC, SALES_ORGANIZATION_HK FROM {{ ref('v_psa_stg_service_levels__winn_sap') }} as SRC 
                        QUALIFY ROW_NUMBER() OVER(PARTITION BY LNK_CUSTOMER_SALES_ORGANIZATION_DISTRIBUTION_CHANNEL_DIVISION_HK ORDER BY LOAD_DTS )=1 )

/*
SRC_SCSMWS         as ( SELECT * FROM STAGING.v_psa_stg_customer_sales_master__winn_sap )
SRC_ZSERVLEVEL     as ( SELECT * FROM STAGING.v_psa_stg_service_levels__winn_sap )
*/
---- LOGIC LAYER ----

, LOGIC_SCSMWS as (
    SELECT
        LNK_CUSTOMER_SALES_ORGANIZATION_DISTRIBUTION_CHANNEL_DIVISION_HK
      , CUSTOMER_HK
      , SALES_ORGANIZATION_HK
      , DISTRIBUTION_CHANNEL_HK
      , DIVISION_HK
      , LOAD_DTS
      , REC_SRC
    FROM SRC_SCSMWS
)

, LOGIC_ZSERVLEVEL as (
    SELECT
        LNK_CUSTOMER_SALES_ORGANIZATION_DISTRIBUTION_CHANNEL_DIVISION_HK
      , CUSTOMER_HK
      , SALES_ORGANIZATION_HK
      , DISTRIBUTION_CHANNEL_HK
      , DIVISION_HK
      , LOAD_DTS
      , REC_SRC
    FROM SRC_ZSERVLEVEL
)
---- RENAME LAYER ----

, RENAME_SCSMWS as (
    SELECT
        LNK_CUSTOMER_SALES_ORGANIZATION_DISTRIBUTION_CHANNEL_DIVISION_HK
      , CUSTOMER_HK
      , SALES_ORGANIZATION_HK
      , DISTRIBUTION_CHANNEL_HK
      , DIVISION_HK
      , LOAD_DTS
      , REC_SRC
    FROM LOGIC_SCSMWS
)

, RENAME_ZSERVLEVEL as (
    SELECT
        LNK_CUSTOMER_SALES_ORGANIZATION_DISTRIBUTION_CHANNEL_DIVISION_HK
      , CUSTOMER_HK
      , SALES_ORGANIZATION_HK
      , DISTRIBUTION_CHANNEL_HK
      , DIVISION_HK
      , LOAD_DTS
      , REC_SRC
    FROM LOGIC_ZSERVLEVEL
)
---- FILTER LAYER ----

, FILTER_SCSMWS as (
    SELECT *
    FROM RENAME_SCSMWS
)

, FILTER_ZSERVLEVEL as (
    SELECT *
    FROM RENAME_ZSERVLEVEL
)
---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT * FROM FILTER_SCSMWS
    UNION ALL
    SELECT * FROM FILTER_ZSERVLEVEL
)

---- FINAL LAYER ----
SELECT
          LNK_CUSTOMER_SALES_ORGANIZATION_DISTRIBUTION_CHANNEL_DIVISION_HK
        , CUSTOMER_HK
        , SALES_ORGANIZATION_HK
        , DISTRIBUTION_CHANNEL_HK
        , DIVISION_HK
        , LOAD_DTS
        , REC_SRC
FROM JOIN_RESULT
{% if is_incremental() %}
WHERE NOT EXISTS (
    SELECT 1 
    FROM {{ this }} existing
    WHERE existing.LNK_CUSTOMER_SALES_ORGANIZATION_DISTRIBUTION_CHANNEL_DIVISION_HK = JOIN_RESULT.LNK_CUSTOMER_SALES_ORGANIZATION_DISTRIBUTION_CHANNEL_DIVISION_HK
)
{% endif %}
/*To select relationships that don't exist in knvv but exist elsewhere*/
QUALIFY 1 = RANK() OVER (PARTITION BY LNK_CUSTOMER_SALES_ORGANIZATION_DISTRIBUTION_CHANNEL_DIVISION_HK ORDER BY DECODE(REC_SRC, 'USOHNO.SAP.ECCPRD.Z_KNVV', 1, 'USOHNO.SAP.ECCPRD.Z_ZSERVLEVEL', 2, 3))
{% if not is_incremental() %}

union all
SELECT 
MD5_BINARY(GR.VALUE) AS LNK_CUSTOMER_SALES_ORGANIZATION_DISTRIBUTION_CHANNEL_DIVISION_HK,
MD5_BINARY(GR.VALUE) AS CUSTOMER_HK,
MD5_BINARY(GR.VALUE) AS SALES_ORGANIZATION_HK,
MD5_BINARY(GR.VALUE) AS DISTRIBUTION_CHANNEL_HK,
MD5_BINARY(GR.VALUE) AS DIVISION_HK,
CONVERT_TIMEZONE('UTC','1900-01-01'::TIMESTAMP) AS LOAD_DTS,
'USAZET.SNOWFLAKE.FBIN.DERIVED' AS REC_SRC
FROM
TABLE(strtok_split_to_table('0|-1|-2', '|')) AS GR
{% endif %}
