---- SRC LAYER ----
WITH
SRC_GAPSCH         as ( SELECT ECOMMERCE_ACCOUNT_HK, ECOMMERCE_PROPERTY_HK, LNK_ECOMMERCE_ACCOUNT_PROPERTY_HK, LOAD_DTS, REC_SRC FROM {{ ref('v_psa_stg_ecommerce_properties_history__winn_google_analytics') }} as SRC 
                        QUALIFY ROW_NUMBER() OVER(PARTITION BY LNK_ECOMMERCE_ACCOUNT_PROPERTY_HK ORDER BY LOAD_DTS )=1 ),
SRC_GAPSC          as ( SELECT ECOMMERCE_ACCOUNT_HK, ECOMMERCE_PROPERTY_HK, LNK_ECOMMERCE_ACCOUNT_PROPERTY_HK, LOAD_DTS, REC_SRC FROM {{ ref('v_psa_stg_ecommerce_properties__winn_google_analytics') }} as SRC 
                        QUALIFY ROW_NUMBER() OVER(PARTITION BY LNK_ECOMMERCE_ACCOUNT_PROPERTY_HK ORDER BY LOAD_DTS )=1 )

/*
SRC_GAPSCH         as ( SELECT * FROM STAGING.v_psa_stg_ecommerce_properties_history__winn_google_analytics )
SRC_GAPSC          as ( SELECT * FROM STAGING.v_psa_stg_ecommerce_properties__winn_google_analytics )
*/
---- LOGIC LAYER ----

, LOGIC_GAPSCH as (
    SELECT
        LNK_ECOMMERCE_ACCOUNT_PROPERTY_HK
      , ECOMMERCE_ACCOUNT_HK
      , ECOMMERCE_PROPERTY_HK
      , LOAD_DTS
      , REC_SRC
    FROM SRC_GAPSCH
)

, LOGIC_GAPSC as (
    SELECT
        LNK_ECOMMERCE_ACCOUNT_PROPERTY_HK
      , ECOMMERCE_ACCOUNT_HK
      , ECOMMERCE_PROPERTY_HK
      , LOAD_DTS
      , REC_SRC
    FROM SRC_GAPSC
)
---- RENAME LAYER ----

, RENAME_GAPSCH as (
    SELECT
        LNK_ECOMMERCE_ACCOUNT_PROPERTY_HK
      , ECOMMERCE_ACCOUNT_HK
      , ECOMMERCE_PROPERTY_HK
      , LOAD_DTS
      , REC_SRC
    FROM LOGIC_GAPSCH
)

, RENAME_GAPSC as (
    SELECT
        LNK_ECOMMERCE_ACCOUNT_PROPERTY_HK
      , ECOMMERCE_ACCOUNT_HK
      , ECOMMERCE_PROPERTY_HK
      , LOAD_DTS
      , REC_SRC
    FROM LOGIC_GAPSC
)
---- FILTER LAYER ----

, FILTER_GAPSCH as (
    SELECT *
    FROM RENAME_GAPSCH
)

, FILTER_GAPSC as (
    SELECT *
    FROM RENAME_GAPSC
)
---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT * FROM FILTER_GAPSCH
    UNION ALL
    SELECT * FROM FILTER_GAPSC
)

---- FINAL LAYER ----
SELECT
          LNK_ECOMMERCE_ACCOUNT_PROPERTY_HK
        , ECOMMERCE_ACCOUNT_HK
        , ECOMMERCE_PROPERTY_HK
        , LOAD_DTS
        , REC_SRC
FROM JOIN_RESULT
{% if is_incremental() %}
WHERE NOT EXISTS (
    SELECT 1 
    FROM {{ this }} existing
    WHERE existing.LNK_ECOMMERCE_ACCOUNT_PROPERTY_HK = JOIN_RESULT.LNK_ECOMMERCE_ACCOUNT_PROPERTY_HK
)
{% endif %}
{% if not is_incremental() %}

union all
SELECT 
MD5_BINARY(GR.VALUE) AS LNK_ECOMMERCE_ACCOUNT_PROPERTY_HK,
MD5_BINARY(GR.VALUE) AS ECOMMERCE_ACCOUNT_HK,
MD5_BINARY(GR.VALUE) AS ECOMMERCE_PROPERTY_HK,
CONVERT_TIMEZONE('UTC','1900-01-01'::TIMESTAMP) AS LOAD_DTS,
'USAZET.SNOWFLAKE.FBIN.DERIVED' AS REC_SRC
FROM
TABLE(strtok_split_to_table('0|-1|-2', '|')) AS GR
{% endif %}
