---- SRC LAYER ----
WITH
SRC_SBIHLR         as ( SELECT * FROM {{ ref('v_psa_stg_bi_hdr__lrsn_psft') }} as SRC 
                        QUALIFY (ROW_NUMBER() OVER(PARTITION BY INVOICE_CUSTOMER_HK ORDER BY LOAD_DTS ))=1 ),
SRC_SINVFB         as ( SELECT * FROM {{ ref('v_psa_stg_invoice_header__fib_ocf') }} as SRC  
                        QUALIFY (ROW_NUMBER() OVER(PARTITION BY INVOICE_CUSTOMER_HK ORDER BY LOAD_DTS ))=1 )

/*
SRC_SBIHLR         as ( SELECT * FROM STAGING.v_psa_stg_bi_hdr__lrsn_psft )
, SRC_SINVFB         as ( SELECT * FROM STAGING.v_psa_stg_invoice_header__fib_ocf  )
*/
---- LOGIC LAYER ----

, LOGIC_SBIHLR as (
    SELECT
        INVOICE_CUSTOMER_HK
      , INVOICE_HK
      , CUSTOMER_SOLDTO_HK
      , CUSTOMER_SHIPTO_HK
      , CUSTOMER_BILLTO_HK
      , LOAD_DTS
      , REC_SRC
    FROM SRC_SBIHLR
)

, LOGIC_SINVFB as (
    SELECT
        INVOICE_CUSTOMER_HK
      , INVOICE_HK
      , CUSTOMER_SOLDTO_HK
      , CUSTOMER_SHIPTO_HK
      , CUSTOMER_BILLTO_HK
      , LOAD_DTS
      , REC_SRC
    FROM SRC_SINVFB
)
---- RENAME LAYER ----

, RENAME_SBIHLR as (
    SELECT
        INVOICE_CUSTOMER_HK
      , INVOICE_HK
      , CUSTOMER_SOLDTO_HK
      , CUSTOMER_SHIPTO_HK
      , CUSTOMER_BILLTO_HK
      , LOAD_DTS
      , REC_SRC
    FROM LOGIC_SBIHLR
)

, RENAME_SINVFB as (
    SELECT
        INVOICE_CUSTOMER_HK
      , INVOICE_HK
      , CUSTOMER_SOLDTO_HK
      , CUSTOMER_SHIPTO_HK
      , CUSTOMER_BILLTO_HK
      , LOAD_DTS
      , REC_SRC
    FROM LOGIC_SINVFB
)
---- FILTER LAYER ----

, FILTER_SBIHLR as (
    SELECT *
    FROM RENAME_SBIHLR
)

, FILTER_SINVFB as (
    SELECT *
    FROM RENAME_SINVFB
)
---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT * FROM FILTER_SBIHLR
    UNION ALL
    SELECT * FROM FILTER_SINVFB
)

---- FINAL LAYER ----
SELECT
          INVOICE_CUSTOMER_HK
        , INVOICE_HK
        , CUSTOMER_SOLDTO_HK
        , CUSTOMER_SHIPTO_HK
        , CUSTOMER_BILLTO_HK
        , LOAD_DTS
        , REC_SRC
FROM JOIN_RESULT
{% if is_incremental() %}
WHERE NOT EXISTS (
    SELECT 1 
    FROM {{ this }} existing
    WHERE existing.INVOICE_CUSTOMER_HK = JOIN_RESULT.INVOICE_CUSTOMER_HK
)
{% endif %}
{% if not is_incremental() %}

union all
SELECT 
MD5_BINARY(GR.VALUE) AS INVOICE_CUSTOMER_HK,
MD5_BINARY(GR.VALUE) AS INVOICE_HK,
MD5_BINARY(GR.VALUE) AS CUSTOMER_SOLDTO_HK,
MD5_BINARY(GR.VALUE) AS CUSTOMER_SHIPTO_HK,
MD5_BINARY(GR.VALUE) AS CUSTOMER_BILLTO_HK,
CONVERT_TIMEZONE('UTC','1900-01-01'::TIMESTAMP) AS LOAD_DTS,
'USAZET.SNOWFLAKE.FBIN.DERIVED' AS REC_SRC
FROM
TABLE(strtok_split_to_table('0|-1|-2', '|')) AS GR
{% endif %}
