---- SRC LAYER ----
WITH
SRC_LZD            as ( SELECT CUSTOMER_HK, INSTALLATION_HK, ITEM_HK, LNK_INSTALLATION_DETAIL_HK, LOAD_DTS, ORDER_HEADER_HK, ORDER_LINE_HK, REC_SRC, SUPPLIER_HK FROM {{ ref('v_psa_stg_installation_event__winn_sap') }} as SRC 
                        QUALIFY (ROW_NUMBER() OVER(PARTITION BY LNK_INSTALLATION_DETAIL_HK ORDER BY LOAD_DTS DESC))=1 )

/*
SRC_LZD            as ( SELECT * FROM STAGING.v_psa_stg_installation_event__winn_sap )
*/
---- LOGIC LAYER ----

, LOGIC_LZD as (
    SELECT
        LNK_INSTALLATION_DETAIL_HK
      , INSTALLATION_HK
      , SUPPLIER_HK
      , ORDER_HEADER_HK
      , ORDER_LINE_HK
      , CUSTOMER_HK
      , ITEM_HK
      , LOAD_DTS
      , REC_SRC
    FROM SRC_LZD
)
---- RENAME LAYER ----

, RENAME_LZD as (
    SELECT
        LNK_INSTALLATION_DETAIL_HK
      , INSTALLATION_HK
      , SUPPLIER_HK
      , ORDER_HEADER_HK
      , ORDER_LINE_HK
      , CUSTOMER_HK
      , ITEM_HK
      , LOAD_DTS
      , REC_SRC
    FROM LOGIC_LZD
)
---- FILTER LAYER ----

, FILTER_LZD as (
    SELECT *
    FROM RENAME_LZD
)
---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT * FROM FILTER_LZD
)

---- FINAL LAYER ----
SELECT
          LNK_INSTALLATION_DETAIL_HK
        , INSTALLATION_HK
        , SUPPLIER_HK
        , ORDER_HEADER_HK
        , ORDER_LINE_HK
        , CUSTOMER_HK
        , ITEM_HK
        , LOAD_DTS
        , REC_SRC
FROM JOIN_RESULT
{% if is_incremental() %}
WHERE NOT EXISTS (
    SELECT 1 
    FROM {{ this }} existing
    WHERE existing.LNK_INSTALLATION_DETAIL_HK = JOIN_RESULT.LNK_INSTALLATION_DETAIL_HK
)
{% endif %}
--this is to consolidate records coming from 2 diff tables with the same bkcc
QUALIFY (ROW_NUMBER() OVER(PARTITION BY LNK_INSTALLATION_DETAIL_HK ORDER BY LOAD_DTS DESC))=1
{% if not is_incremental() %}

union all
SELECT 
 MD5_BINARY(GR.VALUE) AS LNK_INSTALLATION_DETAIL_HK
, MD5_BINARY(GR.VALUE) AS INSTALLATION_HK
, MD5_BINARY(GR.VALUE) AS SUPPLIER_HK
, MD5_BINARY(GR.VALUE) AS ORDER_HEADER_HK
, MD5_BINARY(GR.VALUE) AS ORDER_LINE_HK
, MD5_BINARY(GR.VALUE) AS CUSTOMER_HK
, MD5_BINARY(GR.VALUE) AS ITEM_HK
, CONVERT_TIMEZONE('UTC','1900-01-01'::TIMESTAMP)  AS LOAD_DTS
, 'USAZET.SNOWFLAKE.FBIN.DERIVED' AS REC_SRC
FROM
TABLE(strtok_split_to_table('0|-1|-2', '|')) AS GR
{% endif %}