---- SRC LAYER ----
WITH
SRC_SORDLML        as ( SELECT LOAD_DTS, ORDER_HEADER_HK, ORDER_LINE_HK, ORDER_ORDER_LINE_HK, REC_SRC FROM {{ ref('v_psa_stg_order_line__ml_ebs') }} as SRC 
                        QUALIFY ROW_NUMBER() OVER(PARTITION BY ORDER_ORDER_LINE_HK ORDER BY LOAD_DTS )=1 ),
SRC_SHOPORDLN      as ( SELECT LOAD_DTS, ORDER_HEADER_HK, ORDER_LINE_HK, ORDER_ORDER_LINE_HK, REC_SRC FROM {{ ref('v_psa_stg_dtc_order_line__winn_shopify') }} as SRC 
                        QUALIFY ROW_NUMBER() OVER(PARTITION BY ORDER_ORDER_LINE_HK ORDER BY LOAD_DTS )=1 )

/*
SRC_SORDLML        as ( SELECT * FROM STAGING.v_psa_stg_order_line__ml_ebs )
SRC_SHOPORDLN      as ( SELECT * FROM STAGING.v_psa_stg_dtc_order_line__winn_shopify )
*/
---- LOGIC LAYER ----

, LOGIC_SORDLML as (
    SELECT
        ORDER_ORDER_LINE_HK
      , ORDER_HEADER_HK
      , ORDER_LINE_HK
      , LOAD_DTS
      , REC_SRC
    FROM SRC_SORDLML
)

, LOGIC_SHOPORDLN as (
    SELECT
        ORDER_ORDER_LINE_HK
      , ORDER_HEADER_HK
      , ORDER_LINE_HK
      , LOAD_DTS
      , REC_SRC
    FROM SRC_SHOPORDLN
)
---- RENAME LAYER ----

, RENAME_SORDLML as (
    SELECT
        ORDER_ORDER_LINE_HK
      , ORDER_HEADER_HK
      , ORDER_LINE_HK
      , LOAD_DTS
      , REC_SRC
    FROM LOGIC_SORDLML
)

, RENAME_SHOPORDLN as (
    SELECT
        ORDER_ORDER_LINE_HK
      , ORDER_HEADER_HK
      , ORDER_LINE_HK
      , LOAD_DTS
      , REC_SRC
    FROM LOGIC_SHOPORDLN
)
---- FILTER LAYER ----

, FILTER_SORDLML as (
    SELECT *
    FROM RENAME_SORDLML
)

, FILTER_SHOPORDLN as (
    SELECT *
    FROM RENAME_SHOPORDLN
)
---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT * FROM FILTER_SORDLML
    UNION ALL
    SELECT * FROM FILTER_SHOPORDLN
)

---- FINAL LAYER ----
SELECT
          ORDER_ORDER_LINE_HK
        , ORDER_HEADER_HK
        , ORDER_LINE_HK
        , LOAD_DTS
        , REC_SRC
FROM JOIN_RESULT
{% if is_incremental() %}
WHERE NOT EXISTS (
    SELECT 1 
    FROM {{ this }} existing
    WHERE existing.ORDER_ORDER_LINE_HK = JOIN_RESULT.ORDER_ORDER_LINE_HK
)
{% endif %}
{% if not is_incremental() %}

union all
SELECT 
MD5_BINARY(GR.VALUE) AS ORDER_ORDER_LINE_HK,
MD5_BINARY(GR.VALUE) AS ORDER_HEADER_HK,
MD5_BINARY(GR.VALUE) AS ORDER_LINE_HK,
CONVERT_TIMEZONE('UTC','1900-01-01'::TIMESTAMP) AS LOAD_DTS,
'USAZET.SNOWFLAKE.FBIN.DERIVED' AS REC_SRC
FROM
TABLE(strtok_split_to_table('0|-1|-2', '|')) AS GR
{% endif %}
