
---- SRC LAYER ----
WITH
SRC_DMDPL         as ( 
    SELECT 
        DEMAND_PLAN_LHK, 
        DISTRIBUTION_CHANNEL_HK, 
        DIVISION_HK, 
        ITEM_HK, 
        PLANT_HK, 
        SALES_ORGANIZATION_HK, 
        UOM_HK,
        PLANNING_PERIOD,
        FORECAST_CUSTOMER_GROUP_HK,
        LOAD_DTS, 
        REC_SRC 
    FROM {{ ref('v_psa_stg_demand_planning__winn_sap') }} as SRC 
    QUALIFY (ROW_NUMBER() OVER(PARTITION BY DEMAND_PLAN_LHK ORDER BY LOAD_DTS ))=1 
),
SRC_DMDPLH       as ( 
    SELECT 
        DEMAND_PLAN_LHK, 
        DISTRIBUTION_CHANNEL_HK, 
        DIVISION_HK, 
        ITEM_HK, 
        PLANT_HK, 
        SALES_ORGANIZATION_HK, 
        UOM_HK,
        PLANNING_PERIOD,
        FORECAST_CUSTOMER_GROUP_HK,
        LOAD_DTS, 
        REC_SRC 
    FROM {{ ref('v_psa_stg_demand_planning_history__winn_sap') }} as SRC 
    QUALIFY (ROW_NUMBER() OVER(PARTITION BY DEMAND_PLAN_LHK ORDER BY LOAD_DTS ))=1 
)

---- LOGIC LAYER ----

, LOGIC_DMDPL as (
    SELECT
        DEMAND_PLAN_LHK,
        DISTRIBUTION_CHANNEL_HK,
        DIVISION_HK,
        ITEM_HK,
        PLANT_HK,
        SALES_ORGANIZATION_HK,
        UOM_HK,
        PLANNING_PERIOD,
        FORECAST_CUSTOMER_GROUP_HK,
        LOAD_DTS,
        REC_SRC
    FROM SRC_DMDPL
)

, LOGIC_DMDPLH as (
    SELECT
        DEMAND_PLAN_LHK,
        DISTRIBUTION_CHANNEL_HK,
        DIVISION_HK,
        ITEM_HK,
        PLANT_HK,
        SALES_ORGANIZATION_HK,
        UOM_HK,
        PLANNING_PERIOD,
        FORECAST_CUSTOMER_GROUP_HK,
        LOAD_DTS,
        REC_SRC
    FROM SRC_DMDPLH
)

---- RENAME LAYER ----

, RENAME_DMDPL as (
    SELECT
        DEMAND_PLAN_LHK,
        DISTRIBUTION_CHANNEL_HK,
        DIVISION_HK,
        ITEM_HK,
        PLANT_HK,
        SALES_ORGANIZATION_HK,
        UOM_HK,
        PLANNING_PERIOD,
        FORECAST_CUSTOMER_GROUP_HK,
        LOAD_DTS,
        REC_SRC
    FROM LOGIC_DMDPL
)

, RENAME_DMDPLH as (
    SELECT
        DEMAND_PLAN_LHK,
        DISTRIBUTION_CHANNEL_HK,
        DIVISION_HK,
        ITEM_HK,
        PLANT_HK,
        SALES_ORGANIZATION_HK,
        UOM_HK,
        PLANNING_PERIOD,
        FORECAST_CUSTOMER_GROUP_HK,
        LOAD_DTS,
        REC_SRC
    FROM LOGIC_DMDPLH
)

---- FILTER LAYER ----

, FILTER_DMDPL as (
    SELECT *
    FROM RENAME_DMDPL
)

, FILTER_DMDPLH as (
    SELECT *
    FROM RENAME_DMDPLH
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT * FROM FILTER_DMDPL
    UNION ALL
    SELECT * FROM FILTER_DMDPLH
)

---- FINAL LAYER ----
SELECT
    DEMAND_PLAN_LHK,
    DISTRIBUTION_CHANNEL_HK,
    DIVISION_HK,
    ITEM_HK,
    PLANT_HK,
    SALES_ORGANIZATION_HK,
    UOM_HK,
    PLANNING_PERIOD,
    FORECAST_CUSTOMER_GROUP_HK,
    LOAD_DTS,
    REC_SRC
FROM JOIN_RESULT
{% if is_incremental() %}
WHERE NOT EXISTS (
    SELECT 1 
    FROM {{ this }} existing
    WHERE existing.DEMAND_PLAN_LHK = JOIN_RESULT.DEMAND_PLAN_LHK )
{% endif %}
QUALIFY 1= ROW_NUMBER() OVER (PARTITION BY DEMAND_PLAN_LHK ORDER BY LOAD_DTS)
{% if not is_incremental() %}

union all
SELECT 
    MD5_BINARY(GR.VALUE) AS DEMAND_PLAN_LHK,
    MD5_BINARY(GR.VALUE) AS DISTRIBUTION_CHANNEL_HK,
    MD5_BINARY(GR.VALUE) AS DIVISION_HK,
    MD5_BINARY(GR.VALUE) AS ITEM_HK,
    MD5_BINARY(GR.VALUE) AS PLANT_HK,
    MD5_BINARY(GR.VALUE) AS SALES_ORGANIZATION_HK,
    MD5_BINARY(GR.VALUE) AS UOM_HK,
    GR.VALUE::text       AS PLANNING_PERIOD,
    MD5_BINARY(GR.VALUE) AS FORECAST_CUSTOMER_GROUP_HK,
    CONVERT_TIMEZONE('UTC','1900-01-01'::TIMESTAMP) AS LOAD_DTS,
    'USAZET.SNOWFLAKE.FBIN.DERIVED' AS REC_SRC
FROM
TABLE(strtok_split_to_table('0|-1|-2', '|')) AS GR
{% endif %}