---- SRC LAYER ----
WITH
SRC_a              as ( SELECT LNK_TASKLIST_OPERATION_HK, LOAD_DTS, REC_SRC, TASKLIST_GROUP_HK, TASKLIST_OPERATION_HK FROM {{ ref('v_psa_stg_tasklist_group_operation__winn_sap') }} as SRC 
                        QUALIFY (ROW_NUMBER() OVER(PARTITION BY LNK_TASKLIST_OPERATION_HK ORDER BY LOAD_DTS ))=1 )

/*
SRC_a              as ( SELECT * FROM STAGING.V_PSA_STG_TASKLIST_GROUP_OPERATION__WINN_SAP )
*/
---- LOGIC LAYER ----

, LOGIC_a as (
    SELECT
        LNK_TASKLIST_OPERATION_HK
      , TASKLIST_OPERATION_HK
      , TASKLIST_GROUP_HK
      , LOAD_DTS
      , REC_SRC
    FROM SRC_a
)
---- RENAME LAYER ----

, RENAME_a as (
    SELECT
        LNK_TASKLIST_OPERATION_HK
      , TASKLIST_OPERATION_HK
      , TASKLIST_GROUP_HK
      , LOAD_DTS
      , REC_SRC
    FROM LOGIC_a
)
---- FILTER LAYER ----

, FILTER_a as (
    SELECT *
    FROM RENAME_a
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM FILTER_a
)

---- FINAL LAYER ----
SELECT
          LNK_TASKLIST_OPERATION_HK
        , TASKLIST_OPERATION_HK
        , TASKLIST_GROUP_HK
        , LOAD_DTS
        , REC_SRC
FROM JOIN_RESULT
{% if is_incremental() %}
WHERE NOT EXISTS (
    SELECT 1 
    FROM {{ this }} existing
    WHERE existing.LNK_TASKLIST_OPERATION_HK = JOIN_RESULT.LNK_TASKLIST_OPERATION_HK
)
{% endif %}
{% if not is_incremental() %}

union all
SELECT 
MD5_BINARY(GR.VALUE) AS LNK_TASKLIST_OPERATION_HK,
MD5_BINARY(GR.VALUE) AS TASKLIST_OPERATION_HK,
MD5_BINARY(GR.VALUE) AS TASKLIST_GROUP_HK,
CONVERT_TIMEZONE('UTC','1900-01-01'::TIMESTAMP) AS LOAD_DTS,
'USAZET.SNOWFLAKE.FBIN.DERIVED' AS REC_SRC
FROM
TABLE(strtok_split_to_table('0|-1|-2', '|')) AS GR
{% endif %}
