---- SRC LAYER ----
WITH
SRC_WINNPROMO      as ( SELECT BASE_MATERIAL_HK, KEY_ACCOUNT_GROUP_HK, LNK_ACCOUNT_BASE_MATERIAL_PROMOTION_HK, LOAD_DTS, PROMOTION_HK, REC_SRC FROM {{ ref('v_psa_stg_consolidated_promo_flow_input__winn_rgm') }} as SRC 
                        QUALIFY ROW_NUMBER() OVER(PARTITION BY LNK_ACCOUNT_BASE_MATERIAL_PROMOTION_HK ORDER BY LOAD_DTS )=1 )

/*
SRC_WINNPROMO      as ( SELECT * FROM STAGING.v_psa_stg_consolidated_promo_flow_input__winn_rgm )
*/
---- LOGIC LAYER ----

, LOGIC_WINNPROMO as (
    SELECT
        LNK_ACCOUNT_BASE_MATERIAL_PROMOTION_HK
      , KEY_ACCOUNT_GROUP_HK
      , BASE_MATERIAL_HK
      , PROMOTION_HK
      , LOAD_DTS
      , REC_SRC
    FROM SRC_WINNPROMO
)
---- RENAME LAYER ----

, RENAME_WINNPROMO as (
    SELECT
        LNK_ACCOUNT_BASE_MATERIAL_PROMOTION_HK
      , KEY_ACCOUNT_GROUP_HK
      , BASE_MATERIAL_HK
      , PROMOTION_HK
      , LOAD_DTS
      , REC_SRC
    FROM LOGIC_WINNPROMO
)
---- FILTER LAYER ----

, FILTER_WINNPROMO as (
    SELECT *
    FROM RENAME_WINNPROMO
)
---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT * FROM FILTER_WINNPROMO
)

---- FINAL LAYER ----
SELECT
          LNK_ACCOUNT_BASE_MATERIAL_PROMOTION_HK
        , KEY_ACCOUNT_GROUP_HK
        , BASE_MATERIAL_HK
        , PROMOTION_HK
        , LOAD_DTS
        , REC_SRC
FROM JOIN_RESULT
{% if is_incremental() %}
WHERE NOT EXISTS (
    SELECT 1 
    FROM {{ this }} existing
    WHERE existing.LNK_ACCOUNT_BASE_MATERIAL_PROMOTION_HK = JOIN_RESULT.LNK_ACCOUNT_BASE_MATERIAL_PROMOTION_HK
)
{% endif %}
{% if not is_incremental() %}

union all
SELECT 
MD5_BINARY(GR.VALUE) AS LNK_ACCOUNT_BASE_MATERIAL_PROMOTION_HK,
MD5_BINARY(GR.VALUE) AS KEY_ACCOUNT_GROUP_HK,
MD5_BINARY(GR.VALUE) AS BASE_MATERIAL_HK,
MD5_BINARY(GR.VALUE) AS PROMOTION_HK,
CONVERT_TIMEZONE('UTC','1900-01-01'::TIMESTAMP) AS LOAD_DTS,
'USAZET.SNOWFLAKE.FBIN.DERIVED' AS REC_SRC
FROM
TABLE(strtok_split_to_table('0|-1|-2', '|')) AS GR
{% endif %}
