---- SRC LAYER ----
WITH
SRC_QMMA           as ( SELECT * FROM {{ ref('v_psa_stg_quality_activities') }} as SRC 
                        QUALIFY (ROW_NUMBER() OVER(PARTITION BY QUALITY_ACTIVITY_HK ORDER BY LOAD_DTS ))=1 )

/*
SRC_QMEL           as ( SELECT * FROM STAGING.V_PSA_STG_QUALITY_NOTIFICATIONS )
, SRC_QMMA           as ( SELECT * FROM STAGING.v_psa_stg_quality_activities )
*/
---- LOGIC LAYER ----

, LOGIC_QMMA as (
    SELECT
        QUALITY_NOTIFICATION_ACTIVITY_CAUSES_HK
      , QUALITY_ACTIVITY_HK                                                    
      , QUALITY_ACTIVITY_BK
      , QUALITY_NOTIFICATION_HK
      , QUALITY_CAUSES_HK
      , LOAD_DTS
      , REC_SRC
    FROM SRC_QMMA
)
---- RENAME LAYER ----

, RENAME_QMMA as (
    SELECT
        QUALITY_NOTIFICATION_ACTIVITY_CAUSES_HK
      , QUALITY_ACTIVITY_HK
      , QUALITY_ACTIVITY_BK
      , QUALITY_NOTIFICATION_HK
      , QUALITY_CAUSES_HK
      , LOAD_DTS
      , REC_SRC
    FROM LOGIC_QMMA
)
---- FILTER LAYER ----

, FILTER_QMMA as (
    SELECT *
    FROM RENAME_QMMA
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM FILTER_QMMA
)

---- FINAL LAYER ----
SELECT 
          QUALITY_NOTIFICATION_ACTIVITY_CAUSES_HK
        , QUALITY_ACTIVITY_HK
        , QUALITY_NOTIFICATION_HK
        , QUALITY_CAUSES_HK
        , LOAD_DTS
        , REC_SRC
FROM JOIN_RESULT
{% if is_incremental() %}
WHERE NOT EXISTS (
    SELECT 1 
    FROM {{ this }} existing
    WHERE existing.QUALITY_NOTIFICATION_ACTIVITY_CAUSES_HK = JOIN_RESULT.QUALITY_NOTIFICATION_ACTIVITY_CAUSES_HK
)
{% endif %}

{% if not is_incremental() %}
union all
SELECT 
MD5_BINARY(GR.VALUE) as QUALITY_NOTIFICATION_ACTIVITY_CAUSES_HK
, MD5_BINARY(GR.VALUE) as QUALITY_ACTIVITY_HK
, MD5_BINARY(GR.VALUE) as QUALITY_NOTIFICATION_HK
, MD5_BINARY(GR.VALUE) as QUALITY_CAUSES_HK
, CONVERT_TIMEZONE('UTC','1900-01-01'::TIMESTAMP)  AS LOAD_DTS
, 'USAZET.SNOWFLAKE.FBIN.DERIVED' AS REC_SRC
FROM
TABLE(strtok_split_to_table('0|-1|-2', '|')) AS GR
{% endif %}