---- SRC LAYER ----
WITH
SRC_FD             as ( SELECT DEVICE_LOCATION_HK, LOAD_DTS, PAIRED_DEVICE_HK, PAIRED_DEVICE_LOCATION_HK, REC_SRC FROM {{ ref('v_psa_stg_flo_device_icd') }} as SRC 
                        QUALIFY (ROW_NUMBER() OVER(PARTITION BY PAIRED_DEVICE_LOCATION_HK ORDER BY LOAD_DTS))=1 )

/*
SRC_FD             as ( SELECT * FROM STAGING.v_psa_stg_flo_device_icd )
*/
---- LOGIC LAYER ----

, LOGIC_FD as (
    SELECT
        PAIRED_DEVICE_LOCATION_HK
      , PAIRED_DEVICE_HK
      , DEVICE_LOCATION_HK
      , LOAD_DTS
      , REC_SRC
    FROM SRC_FD
)
---- RENAME LAYER ----

, RENAME_FD as (
    SELECT
        PAIRED_DEVICE_LOCATION_HK
      , PAIRED_DEVICE_HK
      , DEVICE_LOCATION_HK
      , LOAD_DTS
      , REC_SRC
    FROM LOGIC_FD
)
---- FILTER LAYER ----

, FILTER_FD as (
    SELECT *
    FROM RENAME_FD
)
---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT * FROM FILTER_FD
)

---- FINAL LAYER ----
SELECT
          PAIRED_DEVICE_LOCATION_HK
        , PAIRED_DEVICE_HK
        , DEVICE_LOCATION_HK
        , LOAD_DTS
        , REC_SRC
FROM JOIN_RESULT
{% if is_incremental() %}
WHERE NOT EXISTS (
    SELECT 1 
    FROM {{ this }} existing
    WHERE existing.PAIRED_DEVICE_LOCATION_HK = JOIN_RESULT.PAIRED_DEVICE_LOCATION_HK
)
{% endif %}
--this is to consolidate records coming from 2 diff tables with the same bkcc
QUALIFY (ROW_NUMBER() OVER(PARTITION BY PAIRED_DEVICE_LOCATION_HK ORDER BY LOAD_DTS))=1
{% if not is_incremental() %}

union all
SELECT 
 MD5_BINARY(GR.VALUE) AS PAIRED_DEVICE_LOCATION_HK
, MD5_BINARY(GR.VALUE) AS PAIRED_DEVICE_HK
, MD5_BINARY(GR.VALUE) AS DEVICE_LOCATION_HK
, CONVERT_TIMEZONE('UTC','1900-01-01'::TIMESTAMP)  AS LOAD_DTS
, 'USAZET.SNOWFLAKE.FBIN.DERIVED' AS REC_SRC
FROM
TABLE(strtok_split_to_table('0|-1|-2', '|')) AS GR
{% endif %}