---- SRC LAYER ----
WITH
SRC_a              as ( SELECT ITEM_HK, LNK_SALES_ORDER_VENDOR_DETAILS_HK, LOAD_DTS, ORDER_LINE_HK, REC_SRC, VENDOR_ORDER_HK, VENDOR_ORDER_ITEM_HK FROM {{ ref('v_psa_stg_vendor_order_details__amazon') }} as SRC 
                        QUALIFY (ROW_NUMBER() OVER(PARTITION BY LNK_SALES_ORDER_VENDOR_DETAILS_HK ORDER BY LOAD_DTS ))=1 )

/*
SRC_a              as ( SELECT * FROM STAGING.V_PSA_STG_VENDOR_ORDER_DETAILS__AMAZON )
*/
---- LOGIC LAYER ----

, LOGIC_a as (
    SELECT
        LNK_SALES_ORDER_VENDOR_DETAILS_HK
      , ITEM_HK
      , ORDER_LINE_HK
      , VENDOR_ORDER_HK
      , VENDOR_ORDER_ITEM_HK
      , LOAD_DTS
      , REC_SRC
    FROM SRC_a
)
---- RENAME LAYER ----

, RENAME_a as (
    SELECT
        LNK_SALES_ORDER_VENDOR_DETAILS_HK
      , ITEM_HK
      , ORDER_LINE_HK
      , VENDOR_ORDER_HK
      , VENDOR_ORDER_ITEM_HK
      , LOAD_DTS
      , REC_SRC
    FROM LOGIC_a
)
---- FILTER LAYER ----

, FILTER_a as (
    SELECT *
    FROM RENAME_a
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM FILTER_a
)

---- FINAL LAYER ----
SELECT
          LNK_SALES_ORDER_VENDOR_DETAILS_HK
        , ITEM_HK
        , ORDER_LINE_HK
        , VENDOR_ORDER_HK
        , VENDOR_ORDER_ITEM_HK
        , LOAD_DTS
        , REC_SRC
FROM JOIN_RESULT
{% if is_incremental() %}
WHERE NOT EXISTS (
    SELECT 1 
    FROM {{ this }} existing
    WHERE existing.LNK_SALES_ORDER_VENDOR_DETAILS_HK = JOIN_RESULT.LNK_SALES_ORDER_VENDOR_DETAILS_HK
)
{% endif %}
{% if not is_incremental() %}

union all
SELECT 
MD5_BINARY(GR.VALUE) AS LNK_SALES_ORDER_VENDOR_DETAILS_HK,
MD5_BINARY(GR.VALUE) AS ITEM_HK,
MD5_BINARY(GR.VALUE) AS ORDER_LINE_HK,
MD5_BINARY(GR.VALUE) AS VENDOR_ORDER_HK,
MD5_BINARY(GR.VALUE) AS VENDOR_ORDER_ITEM_HK,
CONVERT_TIMEZONE('UTC','1900-01-01'::TIMESTAMP) AS LOAD_DTS,
'USAZET.SNOWFLAKE.FBIN.DERIVED' AS REC_SRC
FROM
TABLE(strtok_split_to_table('0|-1|-2', '|')) AS GR
{% endif %}