---- SRC LAYER ----
WITH
SRC_SRC            as ( SELECT COST_CENTER_HK, LNK_LOCATION_ASSIGNMENT_DETAIL_HK, LOAD_DTS, LOCATION_ASSIGNMENT_HK, PLANT_HK, REC_SRC FROM {{ ref('v_psa_stg_location_assignment__winn_sap') }} as SRC 
                        QUALIFY (ROW_NUMBER() OVER(PARTITION BY LNK_LOCATION_ASSIGNMENT_DETAIL_HK ORDER BY LOAD_DTS)) = 1 )

/*
SRC_SRC            as ( SELECT * FROM int_staging_views.v_psa_stg_location_assignment__winn_sap )
*/
---- LOGIC LAYER ----

, LOGIC_SRC as (
    SELECT
        LNK_LOCATION_ASSIGNMENT_DETAIL_HK
      , LOCATION_ASSIGNMENT_HK
      , COST_CENTER_HK
      , PLANT_HK
      , LOAD_DTS
      , REC_SRC
    FROM SRC_SRC
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM LOGIC_SRC
)

---- FINAL LAYER ----
SELECT
          LNK_LOCATION_ASSIGNMENT_DETAIL_HK
        , LOCATION_ASSIGNMENT_HK
        , COST_CENTER_HK
        , PLANT_HK
        , LOAD_DTS
        , REC_SRC
FROM JOIN_RESULT
{% if is_incremental() %}
WHERE NOT EXISTS (
    SELECT 1
    FROM {{ this }} existing
    WHERE existing.LNK_LOCATION_ASSIGNMENT_DETAIL_HK = JOIN_RESULT.LNK_LOCATION_ASSIGNMENT_DETAIL_HK
)
{% endif %}
{% if not is_incremental() %}

union all
SELECT 
MD5_BINARY(GR.VALUE) AS LNK_LOCATION_ASSIGNMENT_DETAIL_HK,
MD5_BINARY(GR.VALUE) AS LOCATION_ASSIGNMENT_HK,
MD5_BINARY(GR.VALUE) AS COST_CENTER_HK,
MD5_BINARY(GR.VALUE) AS PLANT_HK,
'1900-01-01T00:00:00'::TIMESTAMP_NTZ AS LOAD_DTS,
'USAZET.SNOWFLAKE.FBIN.DERIVED' AS REC_SRC
FROM
TABLE(strtok_split_to_table('0|-1|-2', '|')) AS GR
{% endif %}
