---- SRC LAYER ----
WITH
SRC_SML            as ( SELECT LNK_SUPPLIER_SITE_PAYMENT_TERM_HK, LOAD_DTS, PAYMENT_TERM_HK, REC_SRC, SUPPLIER_HK, SUPPLIER_SITE_HK FROM {{ ref('v_psa_stg_supplier_site__ml_ebs') }} as SRC 
                        QUALIFY (ROW_NUMBER() OVER(PARTITION BY LNK_SUPPLIER_SITE_PAYMENT_TERM_HK ORDER BY LOAD_DTS ))=1 ),
SRC_SEMTK          as ( SELECT LNK_SUPPLIER_SITE_PAYMENT_TERM_HK, LOAD_DTS, PAYMENT_TERM_HK, REC_SRC, SUPPLIER_HK, SUPPLIER_SITE_HK FROM {{ ref('v_psa_stg_supplier_site__emtk_ebs') }} as SRC 
                        QUALIFY (ROW_NUMBER() OVER(PARTITION BY LNK_SUPPLIER_SITE_PAYMENT_TERM_HK ORDER BY LOAD_DTS ))=1 ),
SRC_SFIB           as ( SELECT LNK_SUPPLIER_SITE_PAYMENT_TERM_HK, LOAD_DTS, PAYMENT_TERM_HK, REC_SRC, SUPPLIER_HK, SUPPLIER_SITE_HK FROM {{ ref('v_psa_stg_supplier_site__fib_ocf') }} as SRC 
                        QUALIFY (ROW_NUMBER() OVER(PARTITION BY LNK_SUPPLIER_SITE_PAYMENT_TERM_HK ORDER BY LOAD_DTS ))=1 ),
SRC_LRSN           as ( SELECT LNK_SUPPLIER_SITE_PAYMENT_TERM_HK, LOAD_DTS, PAYMENT_TERM_HK, REC_SRC, SUPPLIER_HK, SUPPLIER_SITE_HK FROM {{ ref('v_psa_stg_supplier_site__lrsn_psft') }} as SRC 
                        QUALIFY (ROW_NUMBER() OVER(PARTITION BY LNK_SUPPLIER_SITE_PAYMENT_TERM_HK ORDER BY LOAD_DTS ))=1 )

/*
SRC_SML            as ( SELECT * FROM STAGING.v_psa_stg_supplier_site__ml_ebs )
SRC_SEMTK          as ( SELECT * FROM STAGING.v_psa_stg_supplier_site__emtk_ebs )
SRC_SFIB           as ( SELECT * FROM STAGING.v_psa_stg_supplier_site__fib_ocf )
SRC_LRSN           as ( SELECT * FROM STAGING.v_psa_stg_supplier_site__lrsn_psft )
*/
---- LOGIC LAYER ----

, LOGIC_SML as (
    SELECT
        LNK_SUPPLIER_SITE_PAYMENT_TERM_HK
      , SUPPLIER_HK
      , SUPPLIER_SITE_HK
      , PAYMENT_TERM_HK
      , LOAD_DTS
      , REC_SRC
    FROM SRC_SML
)

, LOGIC_SEMTK as (
    SELECT
        LNK_SUPPLIER_SITE_PAYMENT_TERM_HK
      , SUPPLIER_HK
      , SUPPLIER_SITE_HK
      , PAYMENT_TERM_HK
      , LOAD_DTS
      , REC_SRC
    FROM SRC_SEMTK
)

, LOGIC_SFIB as (
    SELECT
        LNK_SUPPLIER_SITE_PAYMENT_TERM_HK
      , SUPPLIER_HK
      , SUPPLIER_SITE_HK
      , PAYMENT_TERM_HK
      , LOAD_DTS
      , REC_SRC
    FROM SRC_SFIB
)

, LOGIC_LRSN as (
    SELECT
        LNK_SUPPLIER_SITE_PAYMENT_TERM_HK
      , SUPPLIER_HK
      , SUPPLIER_SITE_HK
      , PAYMENT_TERM_HK
      , LOAD_DTS
      , REC_SRC
    FROM SRC_LRSN
)
---- RENAME LAYER ----

, RENAME_SML as (
    SELECT
        LNK_SUPPLIER_SITE_PAYMENT_TERM_HK
      , SUPPLIER_HK
      , SUPPLIER_SITE_HK
      , PAYMENT_TERM_HK
      , LOAD_DTS
      , REC_SRC
    FROM LOGIC_SML
)

, RENAME_SEMTK as (
    SELECT
        LNK_SUPPLIER_SITE_PAYMENT_TERM_HK
      , SUPPLIER_HK
      , SUPPLIER_SITE_HK
      , PAYMENT_TERM_HK
      , LOAD_DTS
      , REC_SRC
    FROM LOGIC_SEMTK
)

, RENAME_SFIB as (
    SELECT
        LNK_SUPPLIER_SITE_PAYMENT_TERM_HK
      , SUPPLIER_HK
      , SUPPLIER_SITE_HK
      , PAYMENT_TERM_HK
      , LOAD_DTS
      , REC_SRC
    FROM LOGIC_SFIB
)

, RENAME_LRSN as (
    SELECT
        LNK_SUPPLIER_SITE_PAYMENT_TERM_HK
      , SUPPLIER_HK
      , SUPPLIER_SITE_HK
      , PAYMENT_TERM_HK
      , LOAD_DTS
      , REC_SRC
    FROM LOGIC_LRSN
)
---- FILTER LAYER ----

, FILTER_SML as (
    SELECT *
    FROM RENAME_SML
)

, FILTER_SEMTK as (
    SELECT *
    FROM RENAME_SEMTK
)

, FILTER_SFIB as (
    SELECT *
    FROM RENAME_SFIB
)

, FILTER_LRSN as (
    SELECT *
    FROM RENAME_LRSN
)
---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT * FROM FILTER_SML
    UNION ALL
    SELECT * FROM FILTER_SEMTK
    UNION ALL
    SELECT * FROM FILTER_SFIB
    UNION ALL
    SELECT * FROM FILTER_LRSN
)

---- FINAL LAYER ----
SELECT
          LNK_SUPPLIER_SITE_PAYMENT_TERM_HK
        , SUPPLIER_HK
        , SUPPLIER_SITE_HK
        , PAYMENT_TERM_HK
        , LOAD_DTS
        , REC_SRC
FROM JOIN_RESULT
{% if is_incremental() %}
WHERE NOT EXISTS (
    SELECT 1 
    FROM {{ this }} existing
    WHERE existing.LNK_SUPPLIER_SITE_PAYMENT_TERM_HK = JOIN_RESULT.LNK_SUPPLIER_SITE_PAYMENT_TERM_HK )
{% endif %}
{% if not is_incremental() %}

union all
SELECT 
MD5_BINARY(GR.VALUE) AS LNK_SUPPLIER_SITE_PAYMENT_TERM_HK,
MD5_BINARY(GR.VALUE) AS SUPPLIER_HK,
MD5_BINARY(GR.VALUE) AS SUPPLIER_SITE_HK,
MD5_BINARY(GR.VALUE) AS PAYMENT_TERM_HK,
CONVERT_TIMEZONE('UTC','1900-01-01'::TIMESTAMP) AS LOAD_DTS,
'USAZET.SNOWFLAKE.FBIN.DERIVED' AS REC_SRC
FROM
TABLE(strtok_split_to_table('0|-1|-2', '|')) AS GR
{% endif %}
