---- SRC LAYER ----
WITH
SRC_DAS            as ( SELECT DEVICE_ACCOUNT_HK, DEVICE_ACCOUNT_LOCATION_HK, DEVICE_LOCATION_HK, LOAD_DTS, REC_SRC FROM {{ ref('v_psa_stg_flo_device_account_subscription') }} as SRC 
                        QUALIFY (ROW_NUMBER() OVER(PARTITION BY DEVICE_ACCOUNT_LOCATION_HK ORDER BY LOAD_DTS))=1 )

/*
SRC_DAS            as ( SELECT * FROM STAGING.v_psa_stg_flo_device_account_subscription )
*/
---- LOGIC LAYER ----

, LOGIC_DAS as (
    SELECT
        DEVICE_ACCOUNT_LOCATION_HK
      , DEVICE_ACCOUNT_HK
      , DEVICE_LOCATION_HK
      , LOAD_DTS
      , REC_SRC
    FROM SRC_DAS
)
---- RENAME LAYER ----

, RENAME_DAS as (
    SELECT
        DEVICE_ACCOUNT_LOCATION_HK
      , DEVICE_ACCOUNT_HK
      , DEVICE_LOCATION_HK
      , LOAD_DTS
      , REC_SRC
    FROM LOGIC_DAS
)
---- FILTER LAYER ----

, FILTER_DAS as (
    SELECT *
    FROM RENAME_DAS
)
---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT * FROM FILTER_DAS
)

---- FINAL LAYER ----
SELECT
          DEVICE_ACCOUNT_LOCATION_HK
        , DEVICE_ACCOUNT_HK
        , DEVICE_LOCATION_HK
        , LOAD_DTS
        , REC_SRC
FROM JOIN_RESULT
{% if is_incremental() %}
WHERE NOT EXISTS (
    SELECT 1 
    FROM {{ this }} existing
    WHERE existing.DEVICE_ACCOUNT_LOCATION_HK = JOIN_RESULT.DEVICE_ACCOUNT_LOCATION_HK
)
{% endif %}
--this is to consolidate records coming from 2 diff tables with the same bkcc
QUALIFY (ROW_NUMBER() OVER(PARTITION BY DEVICE_ACCOUNT_LOCATION_HK ORDER BY LOAD_DTS))=1
{% if not is_incremental() %}

union all
SELECT 
 MD5_BINARY(GR.VALUE) AS DEVICE_ACCOUNT_LOCATION_HK
, MD5_BINARY(GR.VALUE) AS DEVICE_LOCATION_HK
, MD5_BINARY(GR.VALUE) AS DEVICE_ACCOUNT_HK
, CONVERT_TIMEZONE('UTC','1900-01-01'::TIMESTAMP)  AS LOAD_DTS
, 'USAZET.SNOWFLAKE.FBIN.DERIVED' AS REC_SRC
FROM
TABLE(strtok_split_to_table('0|-1|-2', '|')) AS GR
{% endif %}