---- SRC LAYER ----
WITH
SRC_a              as ( SELECT CHANGE_MASTER_HK, ITEM_HK, LNK_PLANT_TASKLIST_ITEM_ASSIGNMENT_HK, LOAD_DTS, PLANT_HK, REC_SRC, TASKLIST_GROUP_HK FROM {{ ref('v_psa_stg_tasklist_assignment__winn_sap') }} as SRC 
                        QUALIFY (ROW_NUMBER() OVER(PARTITION BY LNK_PLANT_TASKLIST_ITEM_ASSIGNMENT_HK ORDER BY LOAD_DTS ))=1 )

/*
SRC_a              as ( SELECT * FROM STAGING.V_PSA_STG_TASKLIST_ASSIGNMENT__WINN_SAP )
*/
---- LOGIC LAYER ----

, LOGIC_a as (
    SELECT
        LNK_PLANT_TASKLIST_ITEM_ASSIGNMENT_HK
      , PLANT_HK
      , ITEM_HK
      , CHANGE_MASTER_HK
      , TASKLIST_GROUP_HK
      , LOAD_DTS
      , REC_SRC
    FROM SRC_a
)
---- RENAME LAYER ----

, RENAME_a as (
    SELECT
        LNK_PLANT_TASKLIST_ITEM_ASSIGNMENT_HK
      , PLANT_HK
      , ITEM_HK
      , CHANGE_MASTER_HK
      , TASKLIST_GROUP_HK
      , LOAD_DTS
      , REC_SRC
    FROM LOGIC_a
)
---- FILTER LAYER ----

, FILTER_a as (
    SELECT *
    FROM RENAME_a
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM FILTER_a
)

---- FINAL LAYER ----
SELECT
          LNK_PLANT_TASKLIST_ITEM_ASSIGNMENT_HK
        , PLANT_HK
        , ITEM_HK
        , CHANGE_MASTER_HK
        , TASKLIST_GROUP_HK
        , LOAD_DTS
        , REC_SRC
FROM JOIN_RESULT
{% if is_incremental() %}
WHERE NOT EXISTS (
    SELECT 1 
    FROM {{ this }} existing
    WHERE existing.LNK_PLANT_TASKLIST_ITEM_ASSIGNMENT_HK = JOIN_RESULT.LNK_PLANT_TASKLIST_ITEM_ASSIGNMENT_HK
)
{% endif %}
{% if not is_incremental() %}

union all
SELECT 
MD5_BINARY(GR.VALUE) AS LNK_PLANT_TASKLIST_ITEM_ASSIGNMENT_HK,
MD5_BINARY(GR.VALUE) AS PLANT_HK,
MD5_BINARY(GR.VALUE) AS ITEM_HK,
MD5_BINARY(GR.VALUE) AS CHANGE_MASTER_HK,
MD5_BINARY(GR.VALUE) AS TASKLIST_GROUP_HK,
CONVERT_TIMEZONE('UTC','1900-01-01'::TIMESTAMP) AS LOAD_DTS,
'USAZET.SNOWFLAKE.FBIN.DERIVED' AS REC_SRC
FROM
TABLE(strtok_split_to_table('0|-1|-2', '|')) AS GR
{% endif %}
