---- SRC LAYER ----
WITH
SRC_R              as ( SELECT BOM_HK, CHANGE_MASTER_HK, GL_ACCOUNT_NUMBER_HK, GOODS_STORAGE_LOCATION_HK, ITEM_ASSEMBLY_HK, ITEM_HK, LNK_DEPENDENCY_RESERVATION_HK, LOAD_DTS, ORDER_HEADER_HK, ORDER_LINE_HK, PLANNED_ORDER_HK, PLANT_HK, PO_HEADER_HK, PO_ITEM_HK, PO_LINE_HK, PURCHASE_REQUISITION_HK, PURCHASE_REQUISITION_ITEM_HK, REC_SRC, RESERVATION_HK, RESERVATION_LINE_HK, RESERVATION_RECORD_TYPE_DC, ROUTING_HK, STORAGE_BIN_HK, UOM_HK, PRODUCTION_ORDER_HK FROM {{ ref('v_psa_stg_reservation_line__winn_sap') }} as SRC 
                        QUALIFY (ROW_NUMBER() OVER(PARTITION BY LNK_DEPENDENCY_RESERVATION_HK ORDER BY LOAD_DTS ))=1 )

/*
SRC_R              as ( SELECT * FROM STAGING.V_PSA_STG_RESERVATION_LINE__WINN_SAP )
*/
---- LOGIC LAYER ----

, LOGIC_R as (
    SELECT
        LNK_DEPENDENCY_RESERVATION_HK
      , PLANT_HK
      , ITEM_HK
      , PLANNED_ORDER_HK
      , PURCHASE_REQUISITION_HK
      , PURCHASE_REQUISITION_ITEM_HK
      , PO_HEADER_HK
      , PO_ITEM_HK
      , PO_LINE_HK
      , ROUTING_HK
      , CHANGE_MASTER_HK
      , GOODS_STORAGE_LOCATION_HK
      , PRODUCTION_ORDER_HK
      , STORAGE_BIN_HK
      , BOM_HK
      , UOM_HK
      , ITEM_ASSEMBLY_HK
      , ORDER_HEADER_HK
      , ORDER_LINE_HK
      , GL_ACCOUNT_NUMBER_HK
      , RESERVATION_HK
      , RESERVATION_LINE_HK
      , RESERVATION_RECORD_TYPE_DC
      , LOAD_DTS
      , REC_SRC
    FROM SRC_R
)
---- RENAME LAYER ----

, RENAME_R as (
    SELECT
        LNK_DEPENDENCY_RESERVATION_HK
      , PLANT_HK
      , ITEM_HK
      , PLANNED_ORDER_HK
      , PURCHASE_REQUISITION_HK
      , PURCHASE_REQUISITION_ITEM_HK
      , PO_HEADER_HK
      , PO_ITEM_HK
      , PO_LINE_HK
      , ROUTING_HK
      , CHANGE_MASTER_HK
      , GOODS_STORAGE_LOCATION_HK
      , PRODUCTION_ORDER_HK
      , STORAGE_BIN_HK
      , BOM_HK
      , UOM_HK
      , ITEM_ASSEMBLY_HK
      , ORDER_HEADER_HK
      , ORDER_LINE_HK
      , GL_ACCOUNT_NUMBER_HK
      , RESERVATION_HK
      , RESERVATION_LINE_HK
      , RESERVATION_RECORD_TYPE_DC
      , LOAD_DTS
      , REC_SRC
    FROM LOGIC_R
)
---- FILTER LAYER ----

, FILTER_R as (
    SELECT *
    FROM RENAME_R
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM FILTER_R
)

---- FINAL LAYER ----
SELECT
          LNK_DEPENDENCY_RESERVATION_HK
        , PLANT_HK
        , ITEM_HK
        , PLANNED_ORDER_HK
        , PURCHASE_REQUISITION_HK
        , PURCHASE_REQUISITION_ITEM_HK
        , PO_HEADER_HK
        , PO_ITEM_HK
        , PO_LINE_HK
        , ROUTING_HK
        , CHANGE_MASTER_HK
        , GOODS_STORAGE_LOCATION_HK
        , PRODUCTION_ORDER_HK
        , STORAGE_BIN_HK
        , BOM_HK
        , UOM_HK
        , ITEM_ASSEMBLY_HK
        , ORDER_HEADER_HK
        , ORDER_LINE_HK
        , GL_ACCOUNT_NUMBER_HK
        , RESERVATION_HK
        , RESERVATION_LINE_HK
        , RESERVATION_RECORD_TYPE_DC
        , LOAD_DTS
        , REC_SRC
FROM JOIN_RESULT
{% if is_incremental() %}
WHERE NOT EXISTS (
    SELECT 1 
    FROM {{ this }} existing
    WHERE existing.LNK_DEPENDENCY_RESERVATION_HK = JOIN_RESULT.LNK_DEPENDENCY_RESERVATION_HK )
{% endif %}
{% if not is_incremental() %}

union all
SELECT 
MD5_BINARY(GR.VALUE) AS LNK_DEPENDENCY_RESERVATION_HK,
MD5_BINARY(GR.VALUE) AS PLANT_HK,
MD5_BINARY(GR.VALUE) AS ITEM_HK,
MD5_BINARY(GR.VALUE) AS PLANNED_ORDER_HK,
MD5_BINARY(GR.VALUE) AS PURCHASE_REQUISITION_HK,
MD5_BINARY(GR.VALUE) AS PURCHASE_REQUISITION_ITEM_HK,
MD5_BINARY(GR.VALUE) AS PO_HEADER_HK,
MD5_BINARY(GR.VALUE) AS PO_ITEM_HK,
MD5_BINARY(GR.VALUE) AS PO_LINE_HK,
MD5_BINARY(GR.VALUE) AS ROUTING_HK,
MD5_BINARY(GR.VALUE) AS CHANGE_MASTER_HK,
MD5_BINARY(GR.VALUE) AS GOODS_STORAGE_LOCATION_HK,
MD5_BINARY(GR.VALUE) AS PRODUCTION_ORDER_HK,
MD5_BINARY(GR.VALUE) AS STORAGE_BIN_HK,
MD5_BINARY(GR.VALUE) AS BOM_HK,
MD5_BINARY(GR.VALUE) AS UOM_HK,
MD5_BINARY(GR.VALUE) AS ITEM_ASSEMBLY_HK,
MD5_BINARY(GR.VALUE) AS ORDER_HEADER_HK,
MD5_BINARY(GR.VALUE) AS ORDER_LINE_HK,
MD5_BINARY(GR.VALUE) AS GL_ACCOUNT_NUMBER_HK,
MD5_BINARY(GR.VALUE) AS RESERVATION_HK,
MD5_BINARY(GR.VALUE) AS RESERVATION_LINE_HK,
GR.VALUE::text AS RESERVATION_RECORD_TYPE_DC,
CONVERT_TIMEZONE('UTC','1900-01-01'::TIMESTAMP) AS LOAD_DTS,
'USAZET.SNOWFLAKE.FBIN.DERIVED' AS REC_SRC
FROM
TABLE(strtok_split_to_table('0|-1|-2', '|')) AS GR
{% endif %}