---- SRC LAYER ----
WITH
SRC_swinn          as ( SELECT LNK_SUPPLIER_PURCHASING_ORG_PAYMENT_TERM_HK, LOAD_DTS, PAYMENT_TERM_HK, PURCHASING_ORG_HK, REC_SRC, SUPPLIER_HK FROM {{ ref('v_psa_stg_supplier_purchasing_org__winn_sap') }} as SRC 
                        QUALIFY (ROW_NUMBER() OVER(PARTITION BY LNK_SUPPLIER_PURCHASING_ORG_PAYMENT_TERM_HK ORDER BY LOAD_DTS ))=1 )

/*
SRC_swinn          as ( SELECT * FROM STAGING.v_psa_stg_supplier_purchasing_org__ winn_sap )
*/
---- LOGIC LAYER ----

, LOGIC_swinn as (
    SELECT
        LNK_SUPPLIER_PURCHASING_ORG_PAYMENT_TERM_HK
      , SUPPLIER_HK
      , PURCHASING_ORG_HK
      , PAYMENT_TERM_HK
      , LOAD_DTS
      , REC_SRC
    FROM SRC_swinn
)
---- RENAME LAYER ----

, RENAME_swinn as (
    SELECT
        LNK_SUPPLIER_PURCHASING_ORG_PAYMENT_TERM_HK
      , SUPPLIER_HK
      , PURCHASING_ORG_HK
      , PAYMENT_TERM_HK
      , LOAD_DTS
      , REC_SRC
    FROM LOGIC_swinn
)
---- FILTER LAYER ----

, FILTER_swinn as (
    SELECT *
    FROM RENAME_swinn
)
---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT * FROM FILTER_swinn
)

---- FINAL LAYER ----
SELECT
          LNK_SUPPLIER_PURCHASING_ORG_PAYMENT_TERM_HK
        , SUPPLIER_HK
        , PURCHASING_ORG_HK
        , PAYMENT_TERM_HK
        , LOAD_DTS
        , REC_SRC
FROM JOIN_RESULT
{% if is_incremental() %}
WHERE NOT EXISTS (
    SELECT 1 
    FROM {{ this }} existing
    WHERE existing.LNK_SUPPLIER_PURCHASING_ORG_PAYMENT_TERM_HK = JOIN_RESULT.LNK_SUPPLIER_PURCHASING_ORG_PAYMENT_TERM_HK )
{% endif %}
{% if not is_incremental() %}

union all
SELECT 
MD5_BINARY(GR.VALUE) AS LNK_SUPPLIER_PURCHASING_ORG_PAYMENT_TERM_HK,
MD5_BINARY(GR.VALUE) AS SUPPLIER_HK,
MD5_BINARY(GR.VALUE) AS PURCHASING_ORG_HK,
MD5_BINARY(GR.VALUE) AS PAYMENT_TERM_HK,
CONVERT_TIMEZONE('UTC','1900-01-01'::TIMESTAMP) AS LOAD_DTS,
'USAZET.SNOWFLAKE.FBIN.DERIVED' AS REC_SRC
FROM
TABLE(strtok_split_to_table('0|-1|-2', '|')) AS GR
{% endif %}
