---- SRC LAYER ----
WITH
SRC_b              as ( SELECT BASE_QUANTITY_UOM_HK, BASE_UOM_HK, BOM_CHANGE_NUMBER_HK, BOM_HK, BOM_SPECIFIED_ITEM_HK, ENGINEERING_CHANGE_NUMBER_HK, LEAD_PRODUCTION_ORDER_HK, LNK_PRODUCTION_ORDER_ROUTING_RESERVATION_HK, LOAD_DTS, PLANNED_ROUTING_UOM_HK, PRODUCTION_ORDER_BASE_UOM_HK, PRODUCTION_ORDER_HK, PRODUCTION_ORDER_ROUTING_NUMBER_HK, REC_SRC, RESERVATION_HK, RESERVATION_LINE_HK, ROUTING_CHANGE_NUMBER_HK, ROUTING_NUMBER_OPERATIONS_HK, ROUTING_PLANNED_ITEM_HK FROM {{ ref('v_psa_stg_production_order_header__winn_sap') }} as SRC 
                        QUALIFY (ROW_NUMBER() OVER(PARTITION BY LNK_PRODUCTION_ORDER_ROUTING_RESERVATION_HK ORDER BY LOAD_DTS ))=1 )

/*
SRC_b              as ( SELECT * FROM STAGING.V_PSA_STG_PRODUCTION_ORDER_HEADER__WINN_SAP )
*/
---- LOGIC LAYER ----

, LOGIC_b as (
    SELECT
        LNK_PRODUCTION_ORDER_ROUTING_RESERVATION_HK
      , PRODUCTION_ORDER_HK
      , LEAD_PRODUCTION_ORDER_HK
      , RESERVATION_HK
      , RESERVATION_LINE_HK
      , ROUTING_PLANNED_ITEM_HK
      , ROUTING_NUMBER_OPERATIONS_HK
      , PRODUCTION_ORDER_ROUTING_NUMBER_HK
      , BOM_SPECIFIED_ITEM_HK
      , BASE_UOM_HK
      , PRODUCTION_ORDER_BASE_UOM_HK
      , BASE_QUANTITY_UOM_HK
      , PLANNED_ROUTING_UOM_HK
      , ROUTING_CHANGE_NUMBER_HK
      , BOM_CHANGE_NUMBER_HK
      , ENGINEERING_CHANGE_NUMBER_HK
      , BOM_HK
      , LOAD_DTS
      , REC_SRC
    FROM SRC_b
)
---- RENAME LAYER ----

, RENAME_b as (
    SELECT
        LNK_PRODUCTION_ORDER_ROUTING_RESERVATION_HK
      , PRODUCTION_ORDER_HK
      , LEAD_PRODUCTION_ORDER_HK
      , RESERVATION_HK
      , RESERVATION_LINE_HK
      , ROUTING_PLANNED_ITEM_HK
      , ROUTING_NUMBER_OPERATIONS_HK
      , PRODUCTION_ORDER_ROUTING_NUMBER_HK
      , BOM_SPECIFIED_ITEM_HK
      , BASE_UOM_HK
      , PRODUCTION_ORDER_BASE_UOM_HK
      , BASE_QUANTITY_UOM_HK
      , PLANNED_ROUTING_UOM_HK
      , ROUTING_CHANGE_NUMBER_HK
      , BOM_CHANGE_NUMBER_HK
      , ENGINEERING_CHANGE_NUMBER_HK
      , BOM_HK
      , LOAD_DTS
      , REC_SRC
    FROM LOGIC_b
)
---- FILTER LAYER ----

, FILTER_b as (
    SELECT *
    FROM RENAME_b
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM FILTER_b
)

---- FINAL LAYER ----
SELECT
          LNK_PRODUCTION_ORDER_ROUTING_RESERVATION_HK
        , PRODUCTION_ORDER_HK
        , LEAD_PRODUCTION_ORDER_HK
        , RESERVATION_HK
        , RESERVATION_LINE_HK
        , ROUTING_PLANNED_ITEM_HK
        , ROUTING_NUMBER_OPERATIONS_HK
        , PRODUCTION_ORDER_ROUTING_NUMBER_HK
        , BOM_SPECIFIED_ITEM_HK
        , BASE_UOM_HK
        , PRODUCTION_ORDER_BASE_UOM_HK
        , BASE_QUANTITY_UOM_HK
        , PLANNED_ROUTING_UOM_HK
        , ROUTING_CHANGE_NUMBER_HK
        , BOM_CHANGE_NUMBER_HK
        , ENGINEERING_CHANGE_NUMBER_HK
        , BOM_HK
        , LOAD_DTS
        , REC_SRC
FROM JOIN_RESULT
{% if is_incremental() %}
WHERE NOT EXISTS (
    SELECT 1 
    FROM {{ this }} existing
    WHERE existing.LNK_PRODUCTION_ORDER_ROUTING_RESERVATION_HK = JOIN_RESULT.LNK_PRODUCTION_ORDER_ROUTING_RESERVATION_HK
)
{% endif %}
{% if not is_incremental() %}

union all
SELECT 
MD5_BINARY(GR.VALUE) AS LNK_PRODUCTION_ORDER_ROUTING_RESERVATION_HK,
MD5_BINARY(GR.VALUE) AS PRODUCTION_ORDER_HK,
MD5_BINARY(GR.VALUE) AS LEAD_PRODUCTION_ORDER_HK,
MD5_BINARY(GR.VALUE) AS RESERVATION_HK,
MD5_BINARY(GR.VALUE) AS RESERVATION_LINE_HK,
MD5_BINARY(GR.VALUE) AS ROUTING_PLANNED_ITEM_HK,
MD5_BINARY(GR.VALUE) AS ROUTING_NUMBER_OPERATIONS_HK,
MD5_BINARY(GR.VALUE) AS PRODUCTION_ORDER_ROUTING_NUMBER_HK,
MD5_BINARY(GR.VALUE) AS BOM_SPECIFIED_ITEM_HK,
MD5_BINARY(GR.VALUE) AS BASE_UOM_HK,
MD5_BINARY(GR.VALUE) AS PRODUCTION_ORDER_BASE_UOM_HK,
MD5_BINARY(GR.VALUE) AS BASE_QUANTITY_UOM_HK,
MD5_BINARY(GR.VALUE) AS PLANNED_ROUTING_UOM_HK,
MD5_BINARY(GR.VALUE) AS ROUTING_CHANGE_NUMBER_HK,
MD5_BINARY(GR.VALUE) AS BOM_CHANGE_NUMBER_HK,
MD5_BINARY(GR.VALUE) AS ENGINEERING_CHANGE_NUMBER_HK,
MD5_BINARY(GR.VALUE) AS BOM_HK,
CONVERT_TIMEZONE('UTC','1900-01-01'::TIMESTAMP) AS LOAD_DTS,
'USAZET.SNOWFLAKE.FBIN.DERIVED' AS REC_SRC
FROM
TABLE(strtok_split_to_table('0|-1|-2', '|')) AS GR
{% endif %}
