---- SRC LAYER ----
WITH
SRC_cosp           as ( SELECT * FROM {{ ref('v_psa_stg_cost_totals_for_external_postings__winn_sap') }} as SRC 
                        QUALIFY (ROW_NUMBER() OVER(PARTITION BY COST_TOTALS_FOR_EXTERNAL_POSTINGS_HK ORDER BY LOAD_DTS ))=1 )

/*
SRC_cosp           as ( SELECT * FROM sap_ecc_prd.v_psa_stg_cost_totals_for_external_postings__winn_sap )
*/
---- LOGIC LAYER ----

, LOGIC_cosp as (
    SELECT
        COST_TOTALS_FOR_EXTERNAL_POSTINGS_HK
      , OBJECT_NUMBER_HK
      , COST_ELEMENT_HK
      , FISCAL_PERIOD_HK
      , COST_VALUE_TYPE_HK
      , COST_VERSION_HK
      , ORIGIN_GROUP_HK
      , COST_BUSINESS_TRANSACTION_TYPE_HK
      , CURRENCY_HK
      , DEBIT_CREDIT_INDICATOR_HK
      , TRADING_PARTNER_BUSINESS_AREA_HK
      , LEDGER_HK
      , LEGAL_ENTITY_HK
      , LOAD_DTS
      , REC_SRC
    FROM SRC_cosp
)
---- RENAME LAYER ----

, RENAME_cosp as (
    SELECT
        COST_TOTALS_FOR_EXTERNAL_POSTINGS_HK
      , OBJECT_NUMBER_HK
      , COST_ELEMENT_HK
      , FISCAL_PERIOD_HK
      , COST_VALUE_TYPE_HK
      , COST_VERSION_HK
      , ORIGIN_GROUP_HK
      , COST_BUSINESS_TRANSACTION_TYPE_HK
      , CURRENCY_HK
      , DEBIT_CREDIT_INDICATOR_HK
      , TRADING_PARTNER_BUSINESS_AREA_HK
      , LEDGER_HK
      , LEGAL_ENTITY_HK
      , LOAD_DTS
      , REC_SRC
    FROM LOGIC_cosp
)
---- FILTER LAYER ----

, FILTER_cosp as (
    SELECT *
    FROM RENAME_cosp
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM FILTER_cosp
)

---- FINAL LAYER ----
SELECT
          COST_TOTALS_FOR_EXTERNAL_POSTINGS_HK
        , OBJECT_NUMBER_HK
        , COST_ELEMENT_HK
        , FISCAL_PERIOD_HK
        , COST_VALUE_TYPE_HK
        , COST_VERSION_HK
        , ORIGIN_GROUP_HK
        , COST_BUSINESS_TRANSACTION_TYPE_HK
        , CURRENCY_HK
        , DEBIT_CREDIT_INDICATOR_HK
        , TRADING_PARTNER_BUSINESS_AREA_HK
        , LEDGER_HK
        , LEGAL_ENTITY_HK
        , LOAD_DTS
        , REC_SRC
FROM JOIN_RESULT
{% if is_incremental() %}
WHERE NOT EXISTS (
    SELECT 1 
    FROM {{ this }} existing
    WHERE existing.COST_TOTALS_FOR_EXTERNAL_POSTINGS_HK= JOIN_RESULT.COST_TOTALS_FOR_EXTERNAL_POSTINGS_HK
)
{% endif %}

{% if not is_incremental() %}
union all
SELECT 
 MD5_BINARY(GR.VALUE) AS COST_TOTALS_FOR_EXTERNAL_POSTINGS_HK
, MD5_BINARY(GR.VALUE) AS OBJECT_NUMBER_HK
, MD5_BINARY(GR.VALUE) AS COST_ELEMENT_HK
, MD5_BINARY(GR.VALUE) AS FISCAL_PERIOD_HK
, MD5_BINARY(GR.VALUE) AS COST_VALUE_TYPE_HK
, MD5_BINARY(GR.VALUE) AS COST_VERSION_HK
, MD5_BINARY(GR.VALUE) AS ORIGIN_GROUP_HK
, MD5_BINARY(GR.VALUE) AS COST_BUSINESS_TRANSACTION_TYPE_HK
, MD5_BINARY(GR.VALUE) AS CURRENCY_HK
, MD5_BINARY(GR.VALUE) AS DEBIT_CREDIT_INDICATOR_HK
, MD5_BINARY(GR.VALUE) AS TRADING_PARTNER_BUSINESS_AREA_HK
, MD5_BINARY(GR.VALUE) AS LEDGER_HK
, MD5_BINARY(GR.VALUE) AS LEGAL_ENTITY_HK
, CONVERT_TIMEZONE('UTC','1900-01-01')  AS LOAD_DTS
, 'USAZET.SNOWFLAKE.FBIN.DERIVED' AS REC_SRC
FROM
TABLE(strtok_split_to_table('0|-1|-2', '|')) AS GR
{% endif %}
