---- SRC LAYER ----
WITH
SRC_LN             as ( SELECT ALARM_HK, INCIDENT_ALARM_DEVICE_HK, INCIDENT_HK, LOAD_DTS, PAIRED_DEVICE_HK, REC_SRC FROM {{ ref('v_psa_stg_incident') }} as SRC 
                        QUALIFY (ROW_NUMBER() OVER(PARTITION BY INCIDENT_ALARM_DEVICE_HK ORDER BY LOAD_DTS))=1 )

/*
SRC_LN             as ( SELECT * FROM STAGING.v_psa_stg_incident )
*/
---- LOGIC LAYER ----

, LOGIC_LN as (
    SELECT
        INCIDENT_ALARM_DEVICE_HK
      , INCIDENT_HK
      , ALARM_HK
      , PAIRED_DEVICE_HK
      , LOAD_DTS
      , REC_SRC
    FROM SRC_LN
)
---- RENAME LAYER ----

, RENAME_LN as (
    SELECT
        INCIDENT_ALARM_DEVICE_HK
      , INCIDENT_HK
      , ALARM_HK
      , PAIRED_DEVICE_HK
      , LOAD_DTS
      , REC_SRC
    FROM LOGIC_LN
)
---- FILTER LAYER ----

, FILTER_LN as (
    SELECT *
    FROM RENAME_LN
)
---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT * FROM FILTER_LN
)

---- FINAL LAYER ----
SELECT
          INCIDENT_ALARM_DEVICE_HK
        , INCIDENT_HK
        , ALARM_HK
        , PAIRED_DEVICE_HK
        , LOAD_DTS
        , REC_SRC
FROM JOIN_RESULT
{% if is_incremental() %}
WHERE NOT EXISTS (
    SELECT 1 
    FROM {{ this }} existing
    WHERE existing.INCIDENT_ALARM_DEVICE_HK = JOIN_RESULT.INCIDENT_ALARM_DEVICE_HK
)
{% endif %}
--this is to consolidate records coming from 2 diff tables with the same bkcc
QUALIFY (ROW_NUMBER() OVER(PARTITION BY INCIDENT_ALARM_DEVICE_HK ORDER BY LOAD_DTS))=1
{% if not is_incremental() %}

union all
SELECT 
 MD5_BINARY(GR.VALUE) AS INCIDENT_ALARM_DEVICE_HK
, MD5_BINARY(GR.VALUE) AS INCIDENT_HK
, MD5_BINARY(GR.VALUE) AS ALARM_HK
, MD5_BINARY(GR.VALUE) AS PAIRED_DEVICE_HK
, CONVERT_TIMEZONE('UTC','1900-01-01'::TIMESTAMP)  AS LOAD_DTS
, 'USAZET.SNOWFLAKE.FBIN.DERIVED' AS REC_SRC
FROM
TABLE(strtok_split_to_table('0|-1|-2', '|')) AS GR
{% endif %}