SELECT *
FROM (
    {{
        check_not_null_v2(
            'fact_ecommerce_traffic_by_session',
            [
                'ecommerce_account_bk',
                'ecommerce_property_bk',
                'ecommerce_account_country',
                'ecommerce_analytics_service',
                'ecommerce_property_id',
                'ecommerce_property_type',
                'ecommerce_property_timezone',
                'week_ending_datekey',
                'sessions',
                'engagement_rate',
                'key_events',
                'total_users',
                'engaged_sessions',
                'event_count',
                'events_per_session',
                'events_per_engaged_session',
                'sessions_per_user',
                'total_revenue',
                'ecommerce_property_currency_code',
                'rec_src'
            ],
            'bkcc',
            'Wagging_Tail'
        )
    }}
)