{{ config(alias='dim_date_fiscal_445') }}
---- SRC LAYER ----
WITH
SRC_dim_date       as ( SELECT DATE, DATE_BK, EPOCH_DAY, EPOCH_MONTH, EPOCH_WEEK, FISCAL_445_CAL_DAY, FISCAL_445_CAL_MONTH, FISCAL_445_CAL_MONTH_YYYYMM, FISCAL_445_CAL_QUARTER, FISCAL_445_CAL_QUARTER_YYYYQQ, FISCAL_445_CAL_WEEK, FISCAL_445_CAL_WEEK_YYYYWW, FISCAL_445_CAL_YEAR, FISCAL_445_WORKING_DAY_FLAG, FISCAL_DAY_OF_YEAR, FISCAL_LAST_13_WEEKS_FLAG, FISCAL_LAST_3_MONTHS_FLAG, FISCAL_LAST_4_WEEKS_FLAG, FISCAL_LAST_MONTH_FLAG, FISCAL_LAST_WEEK_FLAG, FISCAL_ROLLING_52_WEEK_FLAG, FISCAL_YTD_FLAG, IS_COMPLETED_FISCAL_MONTH, IS_COMPLETED_FISCAL_WEEK, MONTH_NAME, MONTH_NAME_ABBR, MONTH_NUMBER_LEADING_ZERO, WEEKS_IN_MONTH FROM {{ ref('dim_date_fiscal_445') }} as SRC  )

/*
SRC_dim_date       as ( SELECT * FROM bus_vault.dim_date_fiscal_445 )
*/
---- LOGIC LAYER ----

, LOGIC_dim_date as (
    SELECT
        DATE_BK
      , DATE
      , FISCAL_445_CAL_DAY
      , FISCAL_445_CAL_WEEK
      , FISCAL_445_CAL_MONTH
      , FISCAL_445_CAL_QUARTER
      , FISCAL_445_CAL_YEAR
      , FISCAL_445_CAL_QUARTER_YYYYQQ
      , FISCAL_445_CAL_MONTH_YYYYMM
      , FISCAL_445_CAL_WEEK_YYYYWW
      , FISCAL_445_WORKING_DAY_FLAG
      , IS_COMPLETED_FISCAL_MONTH
      , IS_COMPLETED_FISCAL_WEEK
      , FISCAL_LAST_WEEK_FLAG
      , FISCAL_LAST_4_WEEKS_FLAG
      , FISCAL_LAST_13_WEEKS_FLAG
      , FISCAL_LAST_MONTH_FLAG
      , FISCAL_LAST_3_MONTHS_FLAG
      , MONTH_NAME
      , MONTH_NAME_ABBR
      , EPOCH_DAY
      , EPOCH_WEEK
      , EPOCH_MONTH
      , WEEKS_IN_MONTH
      , MONTH_NUMBER_LEADING_ZERO
      , FISCAL_DAY_OF_YEAR
      , FISCAL_YTD_FLAG
      , FISCAL_ROLLING_52_WEEK_FLAG
    FROM SRC_dim_date
)
---- RENAME LAYER ----

, RENAME_dim_date as (
    SELECT
        DATE_BK
      , DATE
      , FISCAL_445_CAL_DAY
      , FISCAL_445_CAL_WEEK
      , FISCAL_445_CAL_MONTH
      , FISCAL_445_CAL_QUARTER
      , FISCAL_445_CAL_YEAR
      , FISCAL_445_CAL_QUARTER_YYYYQQ
      , FISCAL_445_CAL_MONTH_YYYYMM
      , FISCAL_445_CAL_WEEK_YYYYWW
      , FISCAL_445_WORKING_DAY_FLAG
      , IS_COMPLETED_FISCAL_MONTH
      , IS_COMPLETED_FISCAL_WEEK
      , FISCAL_LAST_WEEK_FLAG
      , FISCAL_LAST_4_WEEKS_FLAG
      , FISCAL_LAST_13_WEEKS_FLAG
      , FISCAL_LAST_MONTH_FLAG
      , FISCAL_LAST_3_MONTHS_FLAG
      , MONTH_NAME
      , MONTH_NAME_ABBR
      , EPOCH_DAY
      , EPOCH_WEEK
      , EPOCH_MONTH
      , WEEKS_IN_MONTH
      , MONTH_NUMBER_LEADING_ZERO
      , FISCAL_DAY_OF_YEAR
      , FISCAL_YTD_FLAG
      , FISCAL_ROLLING_52_WEEK_FLAG
    FROM LOGIC_dim_date
)
---- FILTER LAYER ----

, FILTER_dim_date as (
    SELECT *
    FROM RENAME_dim_date
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM FILTER_dim_date
)

---- FINAL LAYER ----
SELECT
          DATE_BK
        , DATE
        , FISCAL_445_CAL_DAY
        , FISCAL_445_CAL_WEEK
        , FISCAL_445_CAL_MONTH
        , FISCAL_445_CAL_QUARTER
        , FISCAL_445_CAL_YEAR
        , FISCAL_445_CAL_QUARTER_YYYYQQ
        , FISCAL_445_CAL_MONTH_YYYYMM
        , FISCAL_445_CAL_WEEK_YYYYWW
        , FISCAL_445_WORKING_DAY_FLAG
        , IS_COMPLETED_FISCAL_MONTH
        , IS_COMPLETED_FISCAL_WEEK
        , FISCAL_LAST_WEEK_FLAG
        , FISCAL_LAST_4_WEEKS_FLAG
        , FISCAL_LAST_13_WEEKS_FLAG
        , FISCAL_LAST_MONTH_FLAG
        , FISCAL_LAST_3_MONTHS_FLAG
        , MONTH_NAME
        , MONTH_NAME_ABBR
        , EPOCH_DAY
        , EPOCH_WEEK
        , EPOCH_MONTH
        , WEEKS_IN_MONTH
        , MONTH_NUMBER_LEADING_ZERO
        , FISCAL_DAY_OF_YEAR
        , FISCAL_YTD_FLAG
        , FISCAL_ROLLING_52_WEEK_FLAG
FROM JOIN_RESULT
