SELECT * FROM ({{ data_exist('dim_retailer','US.PROFITERO_WINN.PRICING_AVAILABILITY_HISTORY') }})
UNION ALL
SELECT * FROM ({{ data_exist('dim_retailer','US.PROFITERO_FIBERON.PRICING_AVAILABILITY_HISTORY') }})
UNION ALL
SELECT * FROM ({{ data_exist('dim_retailer','US.PROFITERO_FYPON.PRICING_AVAILABILITY_HISTORY') }})
UNION ALL
SELECT * FROM ({{ data_exist('dim_retailer','US.PROFITERO_THERMATRU.RETAILERS') }})
UNION ALL
SELECT * FROM ({{ data_exist('dim_retailer','US.PROFITERO_THERMATRU.PRICING_AVAILABILITY_HISTORY') }})
UNION ALL
SELECT * FROM ({{ data_exist('dim_retailer','US.PROFITERO_FYPON.RETAILERS') }})
UNION ALL
SELECT * FROM ({{ data_exist('dim_retailer','US.PROFITERO_WINN.RETAILERS') }})
UNION ALL
SELECT * FROM ({{ data_exist('dim_retailer','US.PROFITERO_FIBERON.RETAILERS') }})
UNION ALL
SELECT * FROM ({{ data_exist('dim_retailer','US.PROFITERO_SECURITY.RETAILERS') }})
UNION ALL
SELECT * FROM ({{ data_exist('dim_retailer','US.PROFITERO_SECURITY.PRICING_AVAILABILITY_HISTORY') }})
UNION ALL
SELECT * FROM ({{ data_exist('dim_retailer','US.PROFITERO_FIBERON.PRODUCTS') }})