---- SRC LAYER ----
WITH
SRC_PBP            as ( SELECT "DATE", BKCC, BRAND_BK, COUNTRY, CUMULATIVE_1_STAR_REVIEWS, CUMULATIVE_2_STAR_REVIEWS, CUMULATIVE_3_STAR_REVIEWS, CUMULATIVE_4_STAR_REVIEWS, CUMULATIVE_5_STAR_REVIEWS, CUMULATIVE_REVIEWS, CUMULATIVE_STAR_RATING, INCRE_1_STAR, INCRE_2_STAR, INCRE_3_STAR, INCRE_4_STAR, INCRE_5_STAR, PRODUCT_BK, PRODUCT_HK, PRODUCT_RETAILER_HK, REC_SRC, RETAILER_BK, RETAILER_HK, SOURCE, UPDATED_AT FROM {{ ref('pb_stg_daily_cumulative_product_rating_v2__profitero') }} as SRC 
                        WHERE "DATE" <= '20260327' ),
SRC_PBPS           as ( SELECT "DATE", BKCC, BRAND_BK, COUNTRY, CUMULATIVE_1_STAR_REVIEWS, CUMULATIVE_2_STAR_REVIEWS, CUMULATIVE_3_STAR_REVIEWS, CUMULATIVE_4_STAR_REVIEWS, CUMULATIVE_5_STAR_REVIEWS, CUMULATIVE_REVIEWS, CUMULATIVE_STAR_RATING, INCRE_1_STAR, INCRE_2_STAR, INCRE_3_STAR, INCRE_4_STAR, INCRE_5_STAR, PRODUCT_BK, PRODUCT_HK, PRODUCT_RETAILER_HK, REC_SRC, RETAILER_BK, RETAILER_HK, SOURCE, UPDATED_AT FROM {{ ref('pb_stg_daily_cumulative_product_rating_v2__profitero_share') }} as SRC 
                        WHERE "DATE" > '20260327' ),
SRC_PBA            as ( SELECT "DATE", BKCC, BRAND_BK, COUNTRY, CUMULATIVE_1_STAR_REVIEWS, CUMULATIVE_2_STAR_REVIEWS, CUMULATIVE_3_STAR_REVIEWS, CUMULATIVE_4_STAR_REVIEWS, CUMULATIVE_5_STAR_REVIEWS, CUMULATIVE_REVIEWS, CUMULATIVE_STAR_RATING, INCRE_1_STAR, INCRE_2_STAR, INCRE_3_STAR, INCRE_4_STAR, INCRE_5_STAR, PRODUCT_BK, PRODUCT_HK, PRODUCT_RETAILER_HK, REC_SRC, RETAILER_BK, RETAILER_HK, SOURCE, UPDATED_AT FROM {{ ref('pb_stg_daily_cumulative_product_rating_v2__appbot') }} as SRC  ),
SRC_PBD            as ( SELECT BKCC, BRAND_BK, COUNTRY, CUMULATIVE_1_STAR_REVIEWS, CUMULATIVE_2_STAR_REVIEWS, CUMULATIVE_3_STAR_REVIEWS, CUMULATIVE_4_STAR_REVIEWS, CUMULATIVE_5_STAR_REVIEWS, CUMULATIVE_REVIEWS, CUMULATIVE_STAR_RATING, DATE_KEY, INCRE_1_STAR, INCRE_2_STAR, INCRE_3_STAR, INCRE_4_STAR, INCRE_5_STAR, PRODUCT_BK, PRODUCT_HK, PRODUCT_RETAILER_HK, REC_SRC, RETAILER_BK, RETAILER_HK, SOURCE, UPDATED_AT FROM {{ ref('pb_stg_daily_cumulative_product_rating_v2__delighted') }} as SRC  )

/*
SRC_PBP            as ( SELECT * FROM bus_vault.PB_STG_DAILY_CUMULATIVE_PRODUCT_RATING_V2__PROFITERO )
SRC_PBPS           as ( SELECT * FROM bus_vault.PB_STG_DAILY_CUMULATIVE_PRODUCT_RATING_V2__PROFITERO )
SRC_PBA            as ( SELECT * FROM bus_vault.PB_STG_DAILY_CUMULATIVE_PRODUCT_RATING_V2__APPBOT )
SRC_PBD            as ( SELECT * FROM bus_vault.PB_STG_DAILY_CUMULATIVE_PRODUCT_RATING_V2__DELIGHTED )
*/
---- LOGIC LAYER ----

, LOGIC_PBP as (
    SELECT
        PRODUCT_RETAILER_HK
      , PRODUCT_HK
      , RETAILER_HK
      , PRODUCT_BK
      , RETAILER_BK
      , BKCC
      , REC_SRC
      , "DATE"                                                       as                                           DATE_KEY
      , CUMULATIVE_STAR_RATING
      , CUMULATIVE_REVIEWS
      , CUMULATIVE_5_STAR_REVIEWS
      , CUMULATIVE_4_STAR_REVIEWS
      , CUMULATIVE_3_STAR_REVIEWS
      , CUMULATIVE_2_STAR_REVIEWS
      , CUMULATIVE_1_STAR_REVIEWS
      , INCRE_1_STAR
      , INCRE_2_STAR
      , INCRE_3_STAR
      , INCRE_4_STAR
      , INCRE_5_STAR
      , UPDATED_AT
      , BRAND_BK
      , SOURCE
      , COUNTRY
    FROM SRC_PBP
)

, LOGIC_PBPS as (
    SELECT
        PRODUCT_RETAILER_HK
      , PRODUCT_HK
      , RETAILER_HK
      , PRODUCT_BK
      , RETAILER_BK
      , BKCC
      , REC_SRC
      , "DATE"                                                       as                                           DATE_KEY
      , CUMULATIVE_STAR_RATING
      , CUMULATIVE_REVIEWS
      , CUMULATIVE_5_STAR_REVIEWS
      , CUMULATIVE_4_STAR_REVIEWS
      , CUMULATIVE_3_STAR_REVIEWS
      , CUMULATIVE_2_STAR_REVIEWS
      , CUMULATIVE_1_STAR_REVIEWS
      , INCRE_1_STAR
      , INCRE_2_STAR
      , INCRE_3_STAR
      , INCRE_4_STAR
      , INCRE_5_STAR
      , UPDATED_AT
      , BRAND_BK
      , SOURCE
      , COUNTRY
    FROM SRC_PBPS
)

, LOGIC_PBA as (
    SELECT
        PRODUCT_RETAILER_HK
      , PRODUCT_HK
      , RETAILER_HK
      , PRODUCT_BK
      , RETAILER_BK
      , BKCC
      , REC_SRC
      , "DATE"                                                       as                                           DATE_KEY
      , CUMULATIVE_STAR_RATING
      , CUMULATIVE_REVIEWS
      , CUMULATIVE_5_STAR_REVIEWS
      , CUMULATIVE_4_STAR_REVIEWS
      , CUMULATIVE_3_STAR_REVIEWS
      , CUMULATIVE_2_STAR_REVIEWS
      , CUMULATIVE_1_STAR_REVIEWS
      , INCRE_1_STAR
      , INCRE_2_STAR
      , INCRE_3_STAR
      , INCRE_4_STAR
      , INCRE_5_STAR
      , UPDATED_AT
      , BRAND_BK
      , SOURCE
      , COUNTRY
    FROM SRC_PBA
)

, LOGIC_PBD as (
    SELECT
        PRODUCT_RETAILER_HK
      , PRODUCT_HK
      , RETAILER_HK
      , PRODUCT_BK
      , RETAILER_BK
      , BKCC
      , REC_SRC
      , DATE_KEY
      , CUMULATIVE_STAR_RATING
      , CUMULATIVE_REVIEWS
      , CUMULATIVE_5_STAR_REVIEWS
      , CUMULATIVE_4_STAR_REVIEWS
      , CUMULATIVE_3_STAR_REVIEWS
      , CUMULATIVE_2_STAR_REVIEWS
      , CUMULATIVE_1_STAR_REVIEWS
      , INCRE_1_STAR
      , INCRE_2_STAR
      , INCRE_3_STAR
      , INCRE_4_STAR
      , INCRE_5_STAR
      , UPDATED_AT
      , BRAND_BK
      , SOURCE
      , COUNTRY
    FROM SRC_PBD
)
---- RENAME LAYER ----

, RENAME_PBP as (
    SELECT
        PRODUCT_RETAILER_HK
      , PRODUCT_HK
      , RETAILER_HK
      , PRODUCT_BK
      , RETAILER_BK
      , BKCC
      , REC_SRC
      , DATE_KEY
      , CUMULATIVE_STAR_RATING
      , CUMULATIVE_REVIEWS
      , CUMULATIVE_5_STAR_REVIEWS
      , CUMULATIVE_4_STAR_REVIEWS
      , CUMULATIVE_3_STAR_REVIEWS
      , CUMULATIVE_2_STAR_REVIEWS
      , CUMULATIVE_1_STAR_REVIEWS
      , INCRE_1_STAR
      , INCRE_2_STAR
      , INCRE_3_STAR
      , INCRE_4_STAR
      , INCRE_5_STAR
      , UPDATED_AT
      , BRAND_BK
      , SOURCE
      , COUNTRY
    FROM LOGIC_PBP
)

, RENAME_PBA as (
    SELECT
        PRODUCT_RETAILER_HK
      , PRODUCT_HK
      , RETAILER_HK
      , PRODUCT_BK
      , RETAILER_BK
      , BKCC
      , REC_SRC
      , DATE_KEY
      , CUMULATIVE_STAR_RATING
      , CUMULATIVE_REVIEWS
      , CUMULATIVE_5_STAR_REVIEWS
      , CUMULATIVE_4_STAR_REVIEWS
      , CUMULATIVE_3_STAR_REVIEWS
      , CUMULATIVE_2_STAR_REVIEWS
      , CUMULATIVE_1_STAR_REVIEWS
      , INCRE_1_STAR
      , INCRE_2_STAR
      , INCRE_3_STAR
      , INCRE_4_STAR
      , INCRE_5_STAR
      , UPDATED_AT
      , BRAND_BK
      , SOURCE
      , COUNTRY
    FROM LOGIC_PBA
)

, RENAME_PBD as (
    SELECT
        PRODUCT_RETAILER_HK
      , PRODUCT_HK
      , RETAILER_HK
      , PRODUCT_BK
      , RETAILER_BK
      , BKCC
      , REC_SRC
      , DATE_KEY
      , CUMULATIVE_STAR_RATING
      , CUMULATIVE_REVIEWS
      , CUMULATIVE_5_STAR_REVIEWS
      , CUMULATIVE_4_STAR_REVIEWS
      , CUMULATIVE_3_STAR_REVIEWS
      , CUMULATIVE_2_STAR_REVIEWS
      , CUMULATIVE_1_STAR_REVIEWS
      , INCRE_1_STAR
      , INCRE_2_STAR
      , INCRE_3_STAR
      , INCRE_4_STAR
      , INCRE_5_STAR
      , UPDATED_AT
      , BRAND_BK
      , SOURCE
      , COUNTRY
    FROM LOGIC_PBD
)

, RENAME_PBPS as (
    SELECT
        PRODUCT_RETAILER_HK
      , PRODUCT_HK
      , RETAILER_HK
      , PRODUCT_BK
      , RETAILER_BK
      , BKCC
      , REC_SRC
      , DATE_KEY
      , CUMULATIVE_STAR_RATING
      , CUMULATIVE_REVIEWS
      , CUMULATIVE_5_STAR_REVIEWS
      , CUMULATIVE_4_STAR_REVIEWS
      , CUMULATIVE_3_STAR_REVIEWS
      , CUMULATIVE_2_STAR_REVIEWS
      , CUMULATIVE_1_STAR_REVIEWS
      , INCRE_1_STAR
      , INCRE_2_STAR
      , INCRE_3_STAR
      , INCRE_4_STAR
      , INCRE_5_STAR
      , UPDATED_AT
      , BRAND_BK
      , SOURCE
      , COUNTRY
    FROM LOGIC_PBPS
)
---- FILTER LAYER ----

, FILTER_PBP as (
    SELECT *
    FROM RENAME_PBP
)

, FILTER_PBPS as (
    SELECT *
    FROM RENAME_PBPS
)

, FILTER_PBA as (
    SELECT *
    FROM RENAME_PBA
)

, FILTER_PBD as (
    SELECT *
    FROM RENAME_PBD
)
---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT * FROM FILTER_PBP
    UNION ALL
    SELECT * FROM FILTER_PBPS
    UNION ALL
    SELECT * FROM FILTER_PBA
    UNION ALL
    SELECT * FROM FILTER_PBD
)

---- FINAL LAYER ----
SELECT
              row_number() over(order by 1)                            as SEQ_ID
        , CURRENT_DATE                                                 as SNAPSHOTDATE
        , CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP )                  as PB_LOAD_DTS
        , PRODUCT_RETAILER_HK
        , PRODUCT_HK
        , RETAILER_HK
        , PRODUCT_BK
        , RETAILER_BK
        , BKCC
        , REC_SRC
        , DATE_KEY::NUMBER(8,0)                                            as DATE_KEY
        , CUMULATIVE_STAR_RATING
        , CUMULATIVE_REVIEWS
        , CUMULATIVE_5_STAR_REVIEWS
        , CUMULATIVE_4_STAR_REVIEWS
        , CUMULATIVE_3_STAR_REVIEWS
        , CUMULATIVE_2_STAR_REVIEWS
        , CUMULATIVE_1_STAR_REVIEWS
        , INCRE_1_STAR
        , INCRE_2_STAR
        , INCRE_3_STAR
        , INCRE_4_STAR
        , INCRE_5_STAR
        , UPDATED_AT::NUMBER(8,0)                                          as UPDATED_AT
        , BRAND_BK
        , SOURCE
        , COUNTRY
FROM JOIN_RESULT
--dedup for brand variations: Kohler vs Kohler Simplice
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY PRODUCT_RETAILER_HK, DATE_KEY, BKCC
    ORDER BY bRAND_BK ASC
) = 1