---- SRC LAYER ----
WITH
SRC_PBDS           as ( SELECT AUTHOR, BKCC, BRAND_BK, COUNTRY, DB_CREATED_AT_KEY, IS_DELETED, MANUFACTURER_COMMENT_DATE_KEY, MANUFACTURER_COMMENT_TEXT, PRODUCT_BK, PRODUCT_HK, PRODUCT_ID, PRODUCT_RETAILER_HK, PURCHASE_SOURCE, PURCHASE_SOURCE_EXTRA_TEXT, REC_SRC, RETAILER_BK, RETAILER_HK, REVIEW_DATE_KEY, REVIEW_TEXT, REVIEW_TITLE, REVIEW_URL, SENTIMENT_PROCESSED, SOURCE, STAR_RATING, SURVEY_TYPE, UKEY, UPDATED_AT_DATE_KEY, RESPONDENT_EMAIL FROM {{ ref('pb_stg_product_review_v2__delighted_sws') }} as SRC  ),
SRC_PBDN           as ( SELECT AUTHOR, BKCC, BRAND_BK, COUNTRY, DB_CREATED_AT_KEY, IS_DELETED, MANUFACTURER_COMMENT_DATE_KEY, MANUFACTURER_COMMENT_TEXT, PRODUCT_BK, PRODUCT_HK, PRODUCT_ID, PRODUCT_RETAILER_HK, PURCHASE_SOURCE, PURCHASE_SOURCE_EXTRA_TEXT, REC_SRC, RETAILER_BK, RETAILER_HK, REVIEW_DATE_KEY, REVIEW_TEXT, REVIEW_TITLE, REVIEW_URL, SENTIMENT_PROCESSED, SOURCE, STAR_RATING, SURVEY_TYPE, UKEY, UPDATED_AT_DATE_KEY, RESPONDENT_EMAIL FROM {{ ref('pb_stg_product_review_v2__delighted_naboo') }} as SRC  ),
SRC_PBDH           as ( SELECT AUTHOR, BKCC, BRAND_BK, COUNTRY, DB_CREATED_AT_KEY, IS_DELETED, MANUFACTURER_COMMENT_DATE_KEY, MANUFACTURER_COMMENT_TEXT, PRODUCT_BK, PRODUCT_HK, PRODUCT_ID, PRODUCT_RETAILER_HK, PURCHASE_SOURCE, PURCHASE_SOURCE_EXTRA_TEXT, REC_SRC, RETAILER_BK, RETAILER_HK, REVIEW_DATE_KEY, REVIEW_TEXT, REVIEW_TITLE, REVIEW_URL, SENTIMENT_PROCESSED, SOURCE, STAR_RATING, SURVEY_TYPE, UKEY, UPDATED_AT_DATE_KEY, RESPONDENT_EMAIL FROM {{ ref('pb_stg_product_review_v2__delighted_hyd') }} as SRC  ),
SRC_PBDV           as ( SELECT AUTHOR, BKCC, BRAND_BK, COUNTRY, DB_CREATED_AT_KEY, IS_DELETED, MANUFACTURER_COMMENT_DATE_KEY, MANUFACTURER_COMMENT_TEXT, PRODUCT_BK, PRODUCT_HK, PRODUCT_ID, PRODUCT_RETAILER_HK, PURCHASE_SOURCE, PURCHASE_SOURCE_EXTRA_TEXT, REC_SRC, RETAILER_BK, RETAILER_HK, REVIEW_DATE_KEY, REVIEW_TEXT, REVIEW_TITLE, REVIEW_URL, SENTIMENT_PROCESSED, SOURCE, STAR_RATING, SURVEY_TYPE, UKEY, UPDATED_AT_DATE_KEY, RESPONDENT_EMAIL FROM {{ ref('pb_stg_product_review_v2__delighted_vak') }} as SRC  ),
SRC_PBSS           as ( SELECT AUTHOR, BKCC, BRAND_BK, COUNTRY, DB_CREATED_AT_KEY, IS_DELETED, MANUFACTURER_COMMENT_DATE_KEY, MANUFACTURER_COMMENT_TEXT, PRODUCT_BK, PRODUCT_HK, PRODUCT_ID, PRODUCT_RETAILER_HK, PURCHASE_SOURCE, PURCHASE_SOURCE_EXTRA_TEXT, REC_SRC, RETAILER_BK, RETAILER_HK, REVIEW_DATE_KEY, REVIEW_TEXT, REVIEW_TITLE, REVIEW_URL, SENTIMENT_PROCESSED, SOURCE, STAR_RATING, SURVEY_TYPE, UKEY, UPDATED_AT_DATE_KEY, RESPONDENT_EMAIL FROM {{ ref('pb_stg_product_review_v2__simplesat_sws') }} as SRC  ),
SRC_PBP            as ( SELECT AUTHOR, BKCC, BRAND_BK, COUNTRY, DB_CREATED_AT_KEY, IS_DELETED, MANUFACTURER_COMMENT_DATE_KEY, MANUFACTURER_COMMENT_TEXT, PRODUCT_BK, PRODUCT_HK, PRODUCT_ID, PRODUCT_RETAILER_HK, PURCHASE_SOURCE, PURCHASE_SOURCE_EXTRA_TEXT, REC_SRC, RETAILER_BK, RETAILER_HK, REVIEW_DATE_KEY, REVIEW_TEXT, REVIEW_TITLE, REVIEW_URL, SENTIMENT_PROCESSED, SOURCE, STAR_RATING, SURVEY_TYPE, UKEY, UPDATED_AT_DATE_KEY FROM {{ ref('pb_stg_product_review_v2__profitero') }} as SRC 
                        qualify 1= row_number() over(partition by PRODUCT_BK, RETAILER_BK, product_id, UKEY, IS_DELETED order by LOAD_DTS DESC) ),
SRC_PBA            as ( SELECT AUTHOR, BKCC, BRAND_BK, COUNTRY, DB_CREATED_AT_KEY, IS_DELETED, MANUFACTURER_COMMENT_DATE_KEY, MANUFACTURER_COMMENT_TEXT, PRODUCT_BK, PRODUCT_HK, PRODUCT_ID, PRODUCT_RETAILER_HK, PURCHASE_SOURCE, PURCHASE_SOURCE_EXTRA_TEXT, REC_SRC, RETAILER_BK, RETAILER_HK, REVIEW_DATE_KEY, REVIEW_TEXT, REVIEW_TITLE, REVIEW_URL, SENTIMENT_PROCESSED, SOURCE, STAR_RATING, SURVEY_TYPE, UKEY, UPDATED_AT_DATE_KEY FROM {{ ref('pb_stg_product_review_v2__appbot') }} as SRC  ),
SRC_PBDY           as ( SELECT AUTHOR, BKCC, BRAND_BK, COUNTRY, DB_CREATED_AT_KEY, IS_DELETED, MANUFACTURER_COMMENT_DATE_KEY, MANUFACTURER_COMMENT_TEXT, PRODUCT_BK, PRODUCT_HK, PRODUCT_ID, PRODUCT_RETAILER_HK, PURCHASE_SOURCE, PURCHASE_SOURCE_EXTRA_TEXT, REC_SRC, RETAILER_BK, RETAILER_HK, REVIEW_DATE_KEY, REVIEW_TEXT, REVIEW_TITLE, REVIEW_URL, SENTIMENT_PROCESSED, SOURCE, STAR_RATING, SURVEY_TYPE, UKEY, UPDATED_AT_DATE_KEY FROM {{ ref('pb_stg_product_review_v2__delighted_yale') }} as SRC  ),
SRC_PBBV           as ( SELECT AUTHOR, BKCC, BRAND_BK, COUNTRY, DB_CREATED_AT_KEY, IS_DELETED, MANUFACTURER_COMMENT_DATE_KEY, MANUFACTURER_COMMENT_TEXT, PRODUCT_BK, PRODUCT_HK, PRODUCT_ID, PRODUCT_RETAILER_HK, PURCHASE_SOURCE, PURCHASE_SOURCE_EXTRA_TEXT, REC_SRC, RETAILER_BK, RETAILER_HK, REVIEW_DATE_KEY, REVIEW_TEXT, REVIEW_TITLE, REVIEW_URL, SENTIMENT_PROCESSED, SOURCE, STAR_RATING, SURVEY_TYPE, UKEY, UPDATED_AT_DATE_KEY FROM {{ ref('pb_stg_product_review_v2__bazaarvoice') }} as SRC  ),
SRC_PBBVY          as ( SELECT AUTHOR, BKCC, BRAND_BK, COUNTRY, DB_CREATED_AT_KEY, IS_DELETED, MANUFACTURER_COMMENT_DATE_KEY, MANUFACTURER_COMMENT_TEXT, PRODUCT_BK, PRODUCT_HK, PRODUCT_ID, PRODUCT_RETAILER_HK, PURCHASE_SOURCE, PURCHASE_SOURCE_EXTRA_TEXT, REC_SRC, RETAILER_BK, RETAILER_HK, REVIEW_DATE_KEY, REVIEW_TEXT, REVIEW_TITLE, REVIEW_URL, SENTIMENT_PROCESSED, SOURCE, STAR_RATING, SURVEY_TYPE, UKEY, UPDATED_AT_DATE_KEY FROM {{ ref('pb_stg_product_review_v2__bazaarvoice_yale') }} as SRC  ),
SRC_PBSY           as ( SELECT AUTHOR, BKCC, BRAND_BK, COUNTRY, DB_CREATED_AT_KEY, IS_DELETED, MANUFACTURER_COMMENT_DATE_KEY, MANUFACTURER_COMMENT_TEXT, PRODUCT_BK, PRODUCT_HK, PRODUCT_ID, PRODUCT_RETAILER_HK, PURCHASE_SOURCE, PURCHASE_SOURCE_EXTRA_TEXT, REC_SRC, RETAILER_BK, RETAILER_HK, REVIEW_DATE_KEY, REVIEW_TEXT, REVIEW_TITLE, REVIEW_URL, SENTIMENT_PROCESSED, SOURCE, STAR_RATING, SURVEY_TYPE, UKEY, UPDATED_AT_DATE_KEY FROM {{ ref('pb_stg_product_review_v2__simplesat_yale') }} as SRC  ),
SRC_PBPS           as ( SELECT AUTHOR, BKCC, BRAND_BK, COUNTRY, DB_CREATED_AT_KEY, IS_DELETED, MANUFACTURER_COMMENT_DATE_KEY, MANUFACTURER_COMMENT_TEXT, PRODUCT_BK, PRODUCT_HK, PRODUCT_ID, PRODUCT_RETAILER_HK, PURCHASE_SOURCE, PURCHASE_SOURCE_EXTRA_TEXT, REC_SRC, RETAILER_BK, RETAILER_HK, REVIEW_DATE_KEY, REVIEW_TEXT, REVIEW_TITLE, REVIEW_URL, SENTIMENT_PROCESSED, SOURCE, STAR_RATING, SURVEY_TYPE, UKEY, UPDATED_AT_DATE_KEY FROM {{ ref('pb_stg_product_review_v2__profitero_share') }} as SRC 
                        qualify 1= row_number() over(partition by PRODUCT_BK, RETAILER_BK, product_id, UKEY, IS_DELETED order by LOAD_DTS DESC) )

/*
SRC_PBP            as ( SELECT * FROM BUS_VAULT.PB_STG_PRODUCT_REVIEW_V2__PROFITERO )
SRC_PBA            as ( SELECT * FROM BUS_VAULT.PB_STG_PRODUCT_REVIEW_V2__APPBOT )
SRC_PBDS           as ( SELECT * FROM BUS_VAULT.PB_STG_PRODUCT_REVIEW_V2__DELIGHTED_SWS )
SRC_PBDN           as ( SELECT * FROM BUS_VAULT.PB_STG_PRODUCT_REVIEW_V2__DELIGHTED_NABOO )
SRC_PBDH           as ( SELECT * FROM BUS_VAULT.PB_STG_PRODUCT_REVIEW_V2__DELIGHTED_HYD )
SRC_PBDV           as ( SELECT * FROM BUS_VAULT.PB_STG_PRODUCT_REVIEW_V2__DELIGHTED_VAK )
SRC_PBDY           as ( SELECT * FROM BUS_VAULT.PB_STG_PRODUCT_REVIEW_V2__DELIGHTED_YALE )
SRC_PBBV           as ( SELECT * FROM BUS_VAULT.PB_STG_PRODUCT_REVIEW_V2__BAZAARVOICE )
SRC_PBBVY          as ( SELECT * FROM BUS_VAULT.PB_STG_PRODUCT_REVIEW_V2__BAZAARVOICE_YALE )
SRC_PBSS           as ( SELECT * FROM BUS_VAULT.PB_STG_PRODUCT_REVIEW_V2__SIMPLESAT_SWS )
SRC_PBSY           as ( SELECT * FROM BUS_VAULT.PB_STG_PRODUCT_REVIEW_V2__SIMPLESAT_YALE )
SRC_PBPS           as ( SELECT * FROM BUS_VAULT.PB_STG_PRODUCT_REVIEW_V2__PROFITERO_SHARE )
*/
---- LOGIC LAYER ----

, LOGIC_PBDS as (
    SELECT
        PRODUCT_RETAILER_HK
      , PRODUCT_HK
      , RETAILER_HK
      , PRODUCT_BK
      , RETAILER_BK
      , BKCC
      , REC_SRC
      , REVIEW_DATE_KEY
      , REVIEW_TITLE
      , REVIEW_TEXT
      , STAR_RATING
      , REVIEW_URL
      , UKEY
      , AUTHOR
      , COUNTRY
      , DB_CREATED_AT_KEY
      , UPDATED_AT_DATE_KEY
      , BRAND_BK
      , MANUFACTURER_COMMENT_TEXT
      , MANUFACTURER_COMMENT_DATE_KEY
      , SOURCE
      , PRODUCT_ID
      , IS_DELETED
      , SENTIMENT_PROCESSED
      , PURCHASE_SOURCE
      , PURCHASE_SOURCE_EXTRA_TEXT
      , SURVEY_TYPE
      , RESPONDENT_EMAIL
      , 1 AS SRC_PRIORITY   -- delighted_sws: no overlap
    FROM SRC_PBDS
)

, LOGIC_PBDN as (
    SELECT
        PRODUCT_RETAILER_HK
      , PRODUCT_HK
      , RETAILER_HK
      , PRODUCT_BK
      , RETAILER_BK
      , BKCC
      , REC_SRC
      , REVIEW_DATE_KEY
      , REVIEW_TITLE
      , REVIEW_TEXT
      , STAR_RATING
      , REVIEW_URL
      , UKEY
      , AUTHOR
      , COUNTRY
      , DB_CREATED_AT_KEY
      , UPDATED_AT_DATE_KEY
      , BRAND_BK
      , MANUFACTURER_COMMENT_TEXT
      , MANUFACTURER_COMMENT_DATE_KEY
      , SOURCE
      , PRODUCT_ID
      , IS_DELETED
      , SENTIMENT_PROCESSED
      , PURCHASE_SOURCE
      , PURCHASE_SOURCE_EXTRA_TEXT
      , SURVEY_TYPE
      , RESPONDENT_EMAIL
      , 1 AS SRC_PRIORITY   -- delighted_naboo: no overlap
    FROM SRC_PBDN
)

, LOGIC_PBDH as (
    SELECT
        PRODUCT_RETAILER_HK
      , PRODUCT_HK
      , RETAILER_HK
      , PRODUCT_BK
      , RETAILER_BK
      , BKCC
      , REC_SRC
      , REVIEW_DATE_KEY
      , REVIEW_TITLE
      , REVIEW_TEXT
      , STAR_RATING
      , REVIEW_URL
      , UKEY
      , AUTHOR
      , COUNTRY
      , DB_CREATED_AT_KEY
      , UPDATED_AT_DATE_KEY
      , BRAND_BK
      , MANUFACTURER_COMMENT_TEXT
      , MANUFACTURER_COMMENT_DATE_KEY
      , SOURCE
      , PRODUCT_ID
      , IS_DELETED
      , SENTIMENT_PROCESSED
      , PURCHASE_SOURCE
      , PURCHASE_SOURCE_EXTRA_TEXT
      , SURVEY_TYPE
      , RESPONDENT_EMAIL
      , 1 AS SRC_PRIORITY   -- delighted_hyd: no overlap
    FROM SRC_PBDH
)

, LOGIC_PBDV as (
    SELECT
        PRODUCT_RETAILER_HK
      , PRODUCT_HK
      , RETAILER_HK
      , PRODUCT_BK
      , RETAILER_BK
      , BKCC
      , REC_SRC
      , REVIEW_DATE_KEY
      , REVIEW_TITLE
      , REVIEW_TEXT
      , STAR_RATING
      , REVIEW_URL
      , UKEY
      , AUTHOR
      , COUNTRY
      , DB_CREATED_AT_KEY
      , UPDATED_AT_DATE_KEY
      , BRAND_BK
      , MANUFACTURER_COMMENT_TEXT
      , MANUFACTURER_COMMENT_DATE_KEY
      , SOURCE
      , PRODUCT_ID
      , IS_DELETED
      , SENTIMENT_PROCESSED
      , PURCHASE_SOURCE
      , PURCHASE_SOURCE_EXTRA_TEXT
      , SURVEY_TYPE
      , RESPONDENT_EMAIL
      , 1 AS SRC_PRIORITY   -- delighted_vak: no overlap
    FROM SRC_PBDV
)

, LOGIC_PBSS as (
    SELECT
        PRODUCT_RETAILER_HK
      , PRODUCT_HK
      , RETAILER_HK
      , PRODUCT_BK
      , RETAILER_BK
      , BKCC
      , REC_SRC
      , REVIEW_DATE_KEY
      , REVIEW_TITLE
      , REVIEW_TEXT
      , STAR_RATING
      , REVIEW_URL
      , UKEY
      , AUTHOR
      , COUNTRY
      , DB_CREATED_AT_KEY
      , UPDATED_AT_DATE_KEY
      , BRAND_BK
      , MANUFACTURER_COMMENT_TEXT
      , MANUFACTURER_COMMENT_DATE_KEY
      , SOURCE
      , PRODUCT_ID
      , IS_DELETED
      , SENTIMENT_PROCESSED
      , PURCHASE_SOURCE
      , PURCHASE_SOURCE_EXTRA_TEXT
      , SURVEY_TYPE
      , RESPONDENT_EMAIL
      , 1 AS SRC_PRIORITY   -- simplesat_sws: no overlap
    FROM SRC_PBSS
)

, LOGIC_PBP as (
    SELECT
        PRODUCT_RETAILER_HK
      , PRODUCT_HK
      , RETAILER_HK
      , PRODUCT_BK
      , RETAILER_BK
      , BKCC
      , REC_SRC
      , REVIEW_DATE_KEY
      , REVIEW_TITLE
      , REVIEW_TEXT
      , STAR_RATING
      , REVIEW_URL
      , UKEY
      , AUTHOR
      , COUNTRY
      , DB_CREATED_AT_KEY
      , UPDATED_AT_DATE_KEY
      , BRAND_BK
      , MANUFACTURER_COMMENT_TEXT
      , MANUFACTURER_COMMENT_DATE_KEY
      , SOURCE
      , PRODUCT_ID
      , IS_DELETED
      , SENTIMENT_PROCESSED
      , PURCHASE_SOURCE
      , PURCHASE_SOURCE_EXTRA_TEXT
      , SURVEY_TYPE
      , CAST(NULL AS VARCHAR) AS RESPONDENT_EMAIL
      , 2 AS SRC_PRIORITY   -- old profitero: loses to share on UKEY+BKCC collision
    FROM SRC_PBP
)

, LOGIC_PBA as (
    SELECT
        PRODUCT_RETAILER_HK
      , PRODUCT_HK
      , RETAILER_HK
      , PRODUCT_BK
      , RETAILER_BK
      , BKCC
      , REC_SRC
      , REVIEW_DATE_KEY
      , REVIEW_TITLE
      , REVIEW_TEXT
      , STAR_RATING
      , REVIEW_URL
      , UKEY
      , AUTHOR
      , COUNTRY
      , DB_CREATED_AT_KEY
      , UPDATED_AT_DATE_KEY
      , BRAND_BK
      , MANUFACTURER_COMMENT_TEXT
      , MANUFACTURER_COMMENT_DATE_KEY
      , SOURCE
      , PRODUCT_ID
      , IS_DELETED
      , SENTIMENT_PROCESSED
      , PURCHASE_SOURCE
      , PURCHASE_SOURCE_EXTRA_TEXT
      , SURVEY_TYPE
      , CAST(NULL AS VARCHAR) AS RESPONDENT_EMAIL
      , 1 AS SRC_PRIORITY   -- appbot: no overlap with profitero
    FROM SRC_PBA
)

, LOGIC_PBDY as (
    SELECT
        PRODUCT_RETAILER_HK
      , PRODUCT_HK
      , RETAILER_HK
      , PRODUCT_BK
      , RETAILER_BK
      , BKCC
      , REC_SRC
      , REVIEW_DATE_KEY
      , REVIEW_TITLE
      , REVIEW_TEXT
      , STAR_RATING
      , REVIEW_URL
      , UKEY
      , AUTHOR
      , COUNTRY
      , DB_CREATED_AT_KEY
      , UPDATED_AT_DATE_KEY
      , BRAND_BK
      , MANUFACTURER_COMMENT_TEXT
      , MANUFACTURER_COMMENT_DATE_KEY
      , SOURCE
      , PRODUCT_ID
      , IS_DELETED
      , SENTIMENT_PROCESSED
      , PURCHASE_SOURCE
      , PURCHASE_SOURCE_EXTRA_TEXT
      , SURVEY_TYPE
      , CAST(NULL AS VARCHAR) AS RESPONDENT_EMAIL
      , 1 AS SRC_PRIORITY   -- delighted_yale: no overlap
    FROM SRC_PBDY
)

, LOGIC_PBBV as (
    SELECT
        PRODUCT_RETAILER_HK
      , PRODUCT_HK
      , RETAILER_HK
      , PRODUCT_BK
      , RETAILER_BK
      , BKCC
      , REC_SRC
      , REVIEW_DATE_KEY
      , REVIEW_TITLE
      , REVIEW_TEXT
      , STAR_RATING
      , REVIEW_URL
      , UKEY
      , AUTHOR
      , COUNTRY
      , DB_CREATED_AT_KEY
      , UPDATED_AT_DATE_KEY
      , BRAND_BK
      , MANUFACTURER_COMMENT_TEXT
      , MANUFACTURER_COMMENT_DATE_KEY
      , SOURCE
      , PRODUCT_ID
      , IS_DELETED
      , SENTIMENT_PROCESSED
      , PURCHASE_SOURCE
      , PURCHASE_SOURCE_EXTRA_TEXT
      , SURVEY_TYPE
      , CAST(NULL AS VARCHAR) AS RESPONDENT_EMAIL
      , 1 AS SRC_PRIORITY   -- bazaarvoice: no overlap
    FROM SRC_PBBV
)

, LOGIC_PBBVY as (
    SELECT
        PRODUCT_RETAILER_HK
      , PRODUCT_HK
      , RETAILER_HK
      , PRODUCT_BK
      , RETAILER_BK
      , BKCC
      , REC_SRC
      , REVIEW_DATE_KEY
      , REVIEW_TITLE
      , REVIEW_TEXT
      , STAR_RATING
      , REVIEW_URL
      , UKEY
      , AUTHOR
      , COUNTRY
      , DB_CREATED_AT_KEY
      , UPDATED_AT_DATE_KEY
      , BRAND_BK
      , MANUFACTURER_COMMENT_TEXT
      , MANUFACTURER_COMMENT_DATE_KEY
      , SOURCE
      , PRODUCT_ID
      , IS_DELETED
      , SENTIMENT_PROCESSED
      , PURCHASE_SOURCE
      , PURCHASE_SOURCE_EXTRA_TEXT
      , SURVEY_TYPE
      , CAST(NULL AS VARCHAR) AS RESPONDENT_EMAIL
      , 1 AS SRC_PRIORITY   -- bazaarvoice_yale: no overlap
    FROM SRC_PBBVY
)

, LOGIC_PBSY as (
    SELECT
        PRODUCT_RETAILER_HK
      , PRODUCT_HK
      , RETAILER_HK
      , PRODUCT_BK
      , RETAILER_BK
      , BKCC
      , REC_SRC
      , REVIEW_DATE_KEY
      , REVIEW_TITLE
      , REVIEW_TEXT
      , STAR_RATING
      , REVIEW_URL
      , UKEY
      , AUTHOR
      , COUNTRY
      , DB_CREATED_AT_KEY
      , UPDATED_AT_DATE_KEY
      , BRAND_BK
      , MANUFACTURER_COMMENT_TEXT
      , MANUFACTURER_COMMENT_DATE_KEY
      , SOURCE
      , PRODUCT_ID
      , IS_DELETED
      , SENTIMENT_PROCESSED
      , PURCHASE_SOURCE
      , PURCHASE_SOURCE_EXTRA_TEXT
      , SURVEY_TYPE
      , CAST(NULL AS VARCHAR) AS RESPONDENT_EMAIL
      , 1 AS SRC_PRIORITY   -- simplesat_yale: no overlap
    FROM SRC_PBSY
)

, LOGIC_PBPS as (
    SELECT
        PRODUCT_RETAILER_HK
      , PRODUCT_HK
      , RETAILER_HK
      , PRODUCT_BK
      , RETAILER_BK
      , BKCC
      , REC_SRC
      , REVIEW_DATE_KEY
      , REVIEW_TITLE
      , REVIEW_TEXT
      , STAR_RATING
      , REVIEW_URL
      , UKEY
      , AUTHOR
      , COUNTRY
      , DB_CREATED_AT_KEY
      , UPDATED_AT_DATE_KEY
      , BRAND_BK
      , MANUFACTURER_COMMENT_TEXT
      , MANUFACTURER_COMMENT_DATE_KEY
      , SOURCE
      , PRODUCT_ID
      , IS_DELETED
      , SENTIMENT_PROCESSED
      , PURCHASE_SOURCE
      , PURCHASE_SOURCE_EXTRA_TEXT
      , SURVEY_TYPE
      , CAST(NULL AS VARCHAR) AS RESPONDENT_EMAIL
      , 1 AS SRC_PRIORITY  -- profitero_share: preferred over old profitero on collision
    FROM SRC_PBPS
)
---- RENAME LAYER ----

, RENAME_PBDS as (
    SELECT
        PRODUCT_RETAILER_HK
      , PRODUCT_HK
      , RETAILER_HK
      , PRODUCT_BK
      , RETAILER_BK
      , BKCC
      , REC_SRC
      , REVIEW_DATE_KEY
      , REVIEW_TITLE
      , REVIEW_TEXT
      , STAR_RATING
      , REVIEW_URL
      , UKEY
      , AUTHOR
      , COUNTRY
      , DB_CREATED_AT_KEY
      , UPDATED_AT_DATE_KEY
      , BRAND_BK
      , MANUFACTURER_COMMENT_TEXT
      , MANUFACTURER_COMMENT_DATE_KEY
      , SOURCE
      , PRODUCT_ID
      , IS_DELETED
      , SENTIMENT_PROCESSED
      , PURCHASE_SOURCE
      , PURCHASE_SOURCE_EXTRA_TEXT
      , SURVEY_TYPE
      , RESPONDENT_EMAIL
      , SRC_PRIORITY
    FROM LOGIC_PBDS
)

, RENAME_PBDN as (
    SELECT
        PRODUCT_RETAILER_HK
      , PRODUCT_HK
      , RETAILER_HK
      , PRODUCT_BK
      , RETAILER_BK
      , BKCC
      , REC_SRC
      , REVIEW_DATE_KEY
      , REVIEW_TITLE
      , REVIEW_TEXT
      , STAR_RATING
      , REVIEW_URL
      , UKEY
      , AUTHOR
      , COUNTRY
      , DB_CREATED_AT_KEY
      , UPDATED_AT_DATE_KEY
      , BRAND_BK
      , MANUFACTURER_COMMENT_TEXT
      , MANUFACTURER_COMMENT_DATE_KEY
      , SOURCE
      , PRODUCT_ID
      , IS_DELETED
      , SENTIMENT_PROCESSED
      , PURCHASE_SOURCE
      , PURCHASE_SOURCE_EXTRA_TEXT
      , SURVEY_TYPE
      , RESPONDENT_EMAIL
      , SRC_PRIORITY
    FROM LOGIC_PBDN
)

, RENAME_PBDH as (
    SELECT
        PRODUCT_RETAILER_HK
      , PRODUCT_HK
      , RETAILER_HK
      , PRODUCT_BK
      , RETAILER_BK
      , BKCC
      , REC_SRC
      , REVIEW_DATE_KEY
      , REVIEW_TITLE
      , REVIEW_TEXT
      , STAR_RATING
      , REVIEW_URL
      , UKEY
      , AUTHOR
      , COUNTRY
      , DB_CREATED_AT_KEY
      , UPDATED_AT_DATE_KEY
      , BRAND_BK
      , MANUFACTURER_COMMENT_TEXT
      , MANUFACTURER_COMMENT_DATE_KEY
      , SOURCE
      , PRODUCT_ID
      , IS_DELETED
      , SENTIMENT_PROCESSED
      , PURCHASE_SOURCE
      , PURCHASE_SOURCE_EXTRA_TEXT
      , SURVEY_TYPE
      , RESPONDENT_EMAIL
      , SRC_PRIORITY
    FROM LOGIC_PBDH
)

, RENAME_PBDV as (
    SELECT
        PRODUCT_RETAILER_HK
      , PRODUCT_HK
      , RETAILER_HK
      , PRODUCT_BK
      , RETAILER_BK
      , BKCC
      , REC_SRC
      , REVIEW_DATE_KEY
      , REVIEW_TITLE
      , REVIEW_TEXT
      , STAR_RATING
      , REVIEW_URL
      , UKEY
      , AUTHOR
      , COUNTRY
      , DB_CREATED_AT_KEY
      , UPDATED_AT_DATE_KEY
      , BRAND_BK
      , MANUFACTURER_COMMENT_TEXT
      , MANUFACTURER_COMMENT_DATE_KEY
      , SOURCE
      , PRODUCT_ID
      , IS_DELETED
      , SENTIMENT_PROCESSED
      , PURCHASE_SOURCE
      , PURCHASE_SOURCE_EXTRA_TEXT
      , SURVEY_TYPE
      , RESPONDENT_EMAIL
      , SRC_PRIORITY
    FROM LOGIC_PBDV
)

, RENAME_PBSS as (
    SELECT
        PRODUCT_RETAILER_HK
      , PRODUCT_HK
      , RETAILER_HK
      , PRODUCT_BK
      , RETAILER_BK
      , BKCC
      , REC_SRC
      , REVIEW_DATE_KEY
      , REVIEW_TITLE
      , REVIEW_TEXT
      , STAR_RATING
      , REVIEW_URL
      , UKEY
      , AUTHOR
      , COUNTRY
      , DB_CREATED_AT_KEY
      , UPDATED_AT_DATE_KEY
      , BRAND_BK
      , MANUFACTURER_COMMENT_TEXT
      , MANUFACTURER_COMMENT_DATE_KEY
      , SOURCE
      , PRODUCT_ID
      , IS_DELETED
      , SENTIMENT_PROCESSED
      , PURCHASE_SOURCE
      , PURCHASE_SOURCE_EXTRA_TEXT
      , SURVEY_TYPE
      , RESPONDENT_EMAIL
      , SRC_PRIORITY
    FROM LOGIC_PBSS
)

, RENAME_PBP as (
    SELECT
        PRODUCT_RETAILER_HK
      , PRODUCT_HK
      , RETAILER_HK
      , PRODUCT_BK
      , RETAILER_BK
      , BKCC
      , REC_SRC
      , REVIEW_DATE_KEY
      , REVIEW_TITLE
      , REVIEW_TEXT
      , STAR_RATING
      , REVIEW_URL
      , UKEY
      , AUTHOR
      , COUNTRY
      , DB_CREATED_AT_KEY
      , UPDATED_AT_DATE_KEY
      , BRAND_BK
      , MANUFACTURER_COMMENT_TEXT
      , MANUFACTURER_COMMENT_DATE_KEY
      , SOURCE
      , PRODUCT_ID
      , IS_DELETED
      , SENTIMENT_PROCESSED
      , PURCHASE_SOURCE
      , PURCHASE_SOURCE_EXTRA_TEXT
      , SURVEY_TYPE
      , RESPONDENT_EMAIL
      , SRC_PRIORITY
    FROM LOGIC_PBP
)

, RENAME_PBA as (
    SELECT
        PRODUCT_RETAILER_HK
      , PRODUCT_HK
      , RETAILER_HK
      , PRODUCT_BK
      , RETAILER_BK
      , BKCC
      , REC_SRC
      , REVIEW_DATE_KEY
      , REVIEW_TITLE
      , REVIEW_TEXT
      , STAR_RATING
      , REVIEW_URL
      , UKEY
      , AUTHOR
      , COUNTRY
      , DB_CREATED_AT_KEY
      , UPDATED_AT_DATE_KEY
      , BRAND_BK
      , MANUFACTURER_COMMENT_TEXT
      , MANUFACTURER_COMMENT_DATE_KEY
      , SOURCE
      , PRODUCT_ID
      , IS_DELETED
      , SENTIMENT_PROCESSED
      , PURCHASE_SOURCE
      , PURCHASE_SOURCE_EXTRA_TEXT
      , SURVEY_TYPE
      , RESPONDENT_EMAIL
      , SRC_PRIORITY
    FROM LOGIC_PBA
)

, RENAME_PBDY as (
    SELECT
        PRODUCT_RETAILER_HK
      , PRODUCT_HK
      , RETAILER_HK
      , PRODUCT_BK
      , RETAILER_BK
      , BKCC
      , REC_SRC
      , REVIEW_DATE_KEY
      , REVIEW_TITLE
      , REVIEW_TEXT
      , STAR_RATING
      , REVIEW_URL
      , UKEY
      , AUTHOR
      , COUNTRY
      , DB_CREATED_AT_KEY
      , UPDATED_AT_DATE_KEY
      , BRAND_BK
      , MANUFACTURER_COMMENT_TEXT
      , MANUFACTURER_COMMENT_DATE_KEY
      , SOURCE
      , PRODUCT_ID
      , IS_DELETED
      , SENTIMENT_PROCESSED
      , PURCHASE_SOURCE
      , PURCHASE_SOURCE_EXTRA_TEXT
      , SURVEY_TYPE
      , RESPONDENT_EMAIL
      , SRC_PRIORITY
    FROM LOGIC_PBDY
)

, RENAME_PBBV as (
    SELECT
        PRODUCT_RETAILER_HK
      , PRODUCT_HK
      , RETAILER_HK
      , PRODUCT_BK
      , RETAILER_BK
      , BKCC
      , REC_SRC
      , REVIEW_DATE_KEY
      , REVIEW_TITLE
      , REVIEW_TEXT
      , STAR_RATING
      , REVIEW_URL
      , UKEY
      , AUTHOR
      , COUNTRY
      , DB_CREATED_AT_KEY
      , UPDATED_AT_DATE_KEY
      , BRAND_BK
      , MANUFACTURER_COMMENT_TEXT
      , MANUFACTURER_COMMENT_DATE_KEY
      , SOURCE
      , PRODUCT_ID
      , IS_DELETED
      , SENTIMENT_PROCESSED
      , PURCHASE_SOURCE
      , PURCHASE_SOURCE_EXTRA_TEXT
      , SURVEY_TYPE
      , RESPONDENT_EMAIL
      , SRC_PRIORITY
    FROM LOGIC_PBBV
)

, RENAME_PBBVY as (
    SELECT
        PRODUCT_RETAILER_HK
      , PRODUCT_HK
      , RETAILER_HK
      , PRODUCT_BK
      , RETAILER_BK
      , BKCC
      , REC_SRC
      , REVIEW_DATE_KEY
      , REVIEW_TITLE
      , REVIEW_TEXT
      , STAR_RATING
      , REVIEW_URL
      , UKEY
      , AUTHOR
      , COUNTRY
      , DB_CREATED_AT_KEY
      , UPDATED_AT_DATE_KEY
      , BRAND_BK
      , MANUFACTURER_COMMENT_TEXT
      , MANUFACTURER_COMMENT_DATE_KEY
      , SOURCE
      , PRODUCT_ID
      , IS_DELETED
      , SENTIMENT_PROCESSED
      , PURCHASE_SOURCE
      , PURCHASE_SOURCE_EXTRA_TEXT
      , SURVEY_TYPE
      , RESPONDENT_EMAIL
      , SRC_PRIORITY
    FROM LOGIC_PBBVY
)

, RENAME_PBSY as (
    SELECT
        PRODUCT_RETAILER_HK
      , PRODUCT_HK
      , RETAILER_HK
      , PRODUCT_BK
      , RETAILER_BK
      , BKCC
      , REC_SRC
      , REVIEW_DATE_KEY
      , REVIEW_TITLE
      , REVIEW_TEXT
      , STAR_RATING
      , REVIEW_URL
      , UKEY
      , AUTHOR
      , COUNTRY
      , DB_CREATED_AT_KEY
      , UPDATED_AT_DATE_KEY
      , BRAND_BK
      , MANUFACTURER_COMMENT_TEXT
      , MANUFACTURER_COMMENT_DATE_KEY
      , SOURCE
      , PRODUCT_ID
      , IS_DELETED
      , SENTIMENT_PROCESSED
      , PURCHASE_SOURCE
      , PURCHASE_SOURCE_EXTRA_TEXT
      , SURVEY_TYPE
      , RESPONDENT_EMAIL
      , SRC_PRIORITY
    FROM LOGIC_PBSY
)

, RENAME_PBPS as (
    SELECT
        PRODUCT_RETAILER_HK
      , PRODUCT_HK
      , RETAILER_HK
      , PRODUCT_BK
      , RETAILER_BK
      , BKCC
      , REC_SRC
      , REVIEW_DATE_KEY
      , REVIEW_TITLE
      , REVIEW_TEXT
      , STAR_RATING
      , REVIEW_URL
      , UKEY
      , AUTHOR
      , COUNTRY
      , DB_CREATED_AT_KEY
      , UPDATED_AT_DATE_KEY
      , BRAND_BK
      , MANUFACTURER_COMMENT_TEXT
      , MANUFACTURER_COMMENT_DATE_KEY
      , SOURCE
      , PRODUCT_ID
      , IS_DELETED
      , SENTIMENT_PROCESSED
      , PURCHASE_SOURCE
      , PURCHASE_SOURCE_EXTRA_TEXT
      , SURVEY_TYPE
      , RESPONDENT_EMAIL
      , SRC_PRIORITY
    FROM LOGIC_PBPS
)
---- FILTER LAYER ----

, FILTER_PBDS as (
    SELECT *
    FROM RENAME_PBDS
)

, FILTER_PBDN as (
    SELECT *
    FROM RENAME_PBDN
)

, FILTER_PBDH as (
    SELECT *
    FROM RENAME_PBDH
)

, FILTER_PBDV as (
    SELECT *
    FROM RENAME_PBDV
)

, FILTER_PBSS as (
    SELECT *
    FROM RENAME_PBSS
)

, FILTER_PBP as (
    SELECT *
    FROM RENAME_PBP
)

, FILTER_PBA as (
    SELECT *
    FROM RENAME_PBA
)

, FILTER_PBDY as (
    SELECT *
    FROM RENAME_PBDY
)

, FILTER_PBBV as (
    SELECT *
    FROM RENAME_PBBV
)

, FILTER_PBBVY as (
    SELECT *
    FROM RENAME_PBBVY
)

, FILTER_PBSY as (
    SELECT *
    FROM RENAME_PBSY
)

, FILTER_PBPS as (
    SELECT *
    FROM RENAME_PBPS
)
---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT * FROM FILTER_PBDS
    UNION ALL
    SELECT * FROM FILTER_PBDN
    UNION ALL
    SELECT * FROM FILTER_PBDH
    UNION ALL
    SELECT * FROM FILTER_PBDV
    UNION ALL
    SELECT * FROM FILTER_PBSS
    UNION ALL
    SELECT * FROM FILTER_PBP
    UNION ALL
    SELECT * FROM FILTER_PBA
    UNION ALL
    SELECT * FROM FILTER_PBDY
    UNION ALL
    SELECT * FROM FILTER_PBBV
    UNION ALL
    SELECT * FROM FILTER_PBBVY
    UNION ALL
    SELECT * FROM FILTER_PBSY
    UNION ALL
    SELECT * FROM FILTER_PBPS
)

---- EMAIL LOOKUP CTEs ----
, SRC_INSURANCE_EMAILS AS (
    SELECT UPPER(ORDER_EMAIL) AS EMAIL
    FROM {{ ref('pb_insurance_partner_order') }}
    WHERE ORDER_EMAIL IS NOT NULL
    QUALIFY ROW_NUMBER() OVER (PARTITION BY UPPER(ORDER_EMAIL) ORDER BY UPPER(ORDER_EMAIL)) = 1
)

, SRC_AMAZON_EMAILS AS (
    SELECT UPPER(EMAIL) AS EMAIL
    FROM {{ ref('pb_amazon_device_email') }}
    WHERE EMAIL IS NOT NULL
    QUALIFY ROW_NUMBER() OVER (PARTITION BY UPPER(EMAIL) ORDER BY UPPER(EMAIL)) = 1
)

---- FINAL LAYER ----
SELECT
              row_number() over(order by 1)                            as SEQ_ID
        , CURRENT_DATE                                                 as SNAPSHOTDATE
        , CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP )                  as PB_LOAD_DTS
        , JR.PRODUCT_RETAILER_HK
        , JR.PRODUCT_HK
        , JR.RETAILER_HK
        , JR.PRODUCT_BK
        , JR.RETAILER_BK
        , JR.BKCC
        , JR.REC_SRC
        , JR.REVIEW_DATE_KEY
        , JR.REVIEW_TITLE
        , JR.REVIEW_TEXT
        , JR.STAR_RATING
        , JR.REVIEW_URL
        , JR.UKEY
        , JR.AUTHOR
        , JR.COUNTRY
        , JR.DB_CREATED_AT_KEY
        , JR.UPDATED_AT_DATE_KEY
        , JR.BRAND_BK
        , JR.MANUFACTURER_COMMENT_TEXT
        , JR.MANUFACTURER_COMMENT_DATE_KEY
        , JR.SOURCE
        , JR.PRODUCT_ID
        , JR.IS_DELETED
        , JR.SENTIMENT_PROCESSED
        , JR.PURCHASE_SOURCE
        , JR.PURCHASE_SOURCE_EXTRA_TEXT
        , JR.SURVEY_TYPE
        , CASE
            WHEN INS.EMAIL IS NOT NULL THEN 'Insurance'
            WHEN AMZ.EMAIL IS NOT NULL THEN 'Amazon'
            WHEN JR.PURCHASE_SOURCE = 'Insurance Partner' THEN 'Insurance'
            WHEN JR.PURCHASE_SOURCE = 'Other'
             AND LOWER(JR.PURCHASE_SOURCE_EXTRA_TEXT) LIKE '%insurance%' THEN 'Insurance'
            ELSE 'None'
          END                                                          as PURCHASE_CHANNEL
FROM JOIN_RESULT JR
LEFT JOIN SRC_INSURANCE_EMAILS INS
    ON UPPER(JR.RESPONDENT_EMAIL) = INS.EMAIL
LEFT JOIN SRC_AMAZON_EMAILS AMZ
    ON UPPER(JR.RESPONDENT_EMAIL) = AMZ.EMAIL
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY JR.PRODUCT_BK, JR.RETAILER_BK, JR.UKEY, JR.BKCC
    ORDER BY JR.SRC_PRIORITY ASC, REVIEW_DATE_KEY DESC
) = 1
