---- SRC LAYER ----
WITH
SRC_pb             as ( SELECT BASE_UOM, BKCC, BUSINESS_UNIT, CAL_MONTH, CAL_YEAR, CATEGORY_LEADER_NAME, COUNTRY_OF_ORIGIN, DIRECTOR_NAME, DOCUMENT_TYPE, DRVD_OPCO, FBIN_CATEGORY_I, FBIN_CATEGORY_II, FBIN_CATEGORY_III, ITEM_BK, ITEM_HK, NET_PRICE, OPCO_CATEGORY, OPCO_ITEM, PLANNED_ORDER_BK, PLANNED_ORDER_FINISH_DATE, PLANNED_ORDER_FINISH_DATE_BK, PLANNED_ORDER_HK, PLANT_BK, PLANT_HK, PRICE_PER_UNIT, PURCHASING_ORG_HK, PURCHASING_RECORD_HK, REC_SRC, SOURCE, SPEND, SUPPLIER_HK, SUPPLIER_NAME_CHILD, SUPPLIER_NAME_PARENT, SUPPLIER_NUMBER_CHILD, SUPPLIER_NUMBER_PARENT, UOM, UOM_D, UOM_N, VOLUME FROM {{ ref('pb_planned_order_spend_detail') }} as SRC  )

/*
SRC_pb             as ( SELECT * FROM BUS_VAULT.pb_planned_order_spend_detail )
*/
---- LOGIC LAYER ----

, LOGIC_pb as (
    SELECT
        PLANNED_ORDER_BK
      , PLANNED_ORDER_FINISH_DATE
      , TO_CHAR(PLANNED_ORDER_FINISH_DATE, 'YYYYMMDD')::INTEGER      as                      PLANNED_ORDER_FINISH_DATE_KEY
      , CAL_YEAR
      , CAL_MONTH
      , VOLUME
      , UOM
      , UOM_N
      , UOM_D
      , BASE_UOM
      , NET_PRICE
      , PRICE_PER_UNIT
      , SPEND
      , DRVD_OPCO
      , OPCO_ITEM
      , SUPPLIER_NUMBER_PARENT
      , SUPPLIER_NAME_PARENT
      , SUPPLIER_NUMBER_CHILD
      , SUPPLIER_NAME_CHILD
      , COUNTRY_OF_ORIGIN
      , OPCO_CATEGORY
      , CATEGORY_LEADER_NAME
      , DIRECTOR_NAME
      , FBIN_CATEGORY_I
      , FBIN_CATEGORY_II
      , FBIN_CATEGORY_III
      , DOCUMENT_TYPE
      , ITEM_BK
      , PLANT_BK
      , PLANNED_ORDER_FINISH_DATE_BK::INTEGER                        as                 PLANNED_ORDER_FINISH_DATE_YYYYMMDD
      , PLANNED_ORDER_HK
      , SUPPLIER_HK
      , ITEM_HK
      , PLANT_HK
      , PURCHASING_ORG_HK
      , PURCHASING_RECORD_HK
      , SOURCE
      , BUSINESS_UNIT
      , REC_SRC
      , BKCC
    FROM SRC_pb
)
---- RENAME LAYER ----

, RENAME_pb as (
    SELECT
        PLANNED_ORDER_BK
      , PLANNED_ORDER_FINISH_DATE
      , PLANNED_ORDER_FINISH_DATE_KEY
      , CAL_YEAR
      , CAL_MONTH
      , VOLUME
      , UOM
      , UOM_N
      , UOM_D
      , BASE_UOM
      , NET_PRICE
      , PRICE_PER_UNIT
      , SPEND
      , DRVD_OPCO
      , OPCO_ITEM
      , SUPPLIER_NUMBER_PARENT
      , SUPPLIER_NAME_PARENT
      , SUPPLIER_NUMBER_CHILD
      , SUPPLIER_NAME_CHILD
      , COUNTRY_OF_ORIGIN
      , OPCO_CATEGORY
      , CATEGORY_LEADER_NAME
      , DIRECTOR_NAME
      , FBIN_CATEGORY_I
      , FBIN_CATEGORY_II
      , FBIN_CATEGORY_III
      , DOCUMENT_TYPE
      , ITEM_BK
      , PLANT_BK
      , PLANNED_ORDER_FINISH_DATE_YYYYMMDD
      , PLANNED_ORDER_HK
      , SUPPLIER_HK
      , ITEM_HK
      , PLANT_HK
      , PURCHASING_ORG_HK
      , PURCHASING_RECORD_HK
      , SOURCE
      , BUSINESS_UNIT
      , REC_SRC
      , BKCC
    FROM LOGIC_pb
)
---- FILTER LAYER ----

, FILTER_pb as (
    SELECT *
    FROM RENAME_pb
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM FILTER_pb
)

---- FINAL LAYER ----
SELECT
          PLANNED_ORDER_BK
        , PLANNED_ORDER_FINISH_DATE_KEY
        , CAL_YEAR
        , CAL_MONTH
        , VOLUME
        , UOM
        , UOM_N
        , UOM_D
        , BASE_UOM
        , NET_PRICE
        , PRICE_PER_UNIT
        , SPEND
        , DRVD_OPCO
        , OPCO_ITEM
        , SUPPLIER_NUMBER_PARENT
        , SUPPLIER_NAME_PARENT
        , SUPPLIER_NUMBER_CHILD
        , SUPPLIER_NAME_CHILD
        , COUNTRY_OF_ORIGIN
        , OPCO_CATEGORY
        , CATEGORY_LEADER_NAME
        , DIRECTOR_NAME
        , FBIN_CATEGORY_I
        , FBIN_CATEGORY_II
        , FBIN_CATEGORY_III
        , DOCUMENT_TYPE
        , ITEM_BK
        , PLANT_BK
        , PLANNED_ORDER_FINISH_DATE_YYYYMMDD
        , PLANNED_ORDER_HK
        , SUPPLIER_HK
        , ITEM_HK
        , PLANT_HK
        , PURCHASING_ORG_HK
        , PURCHASING_RECORD_HK
        , SOURCE
        , BUSINESS_UNIT
        , REC_SRC
        , BKCC
FROM JOIN_RESULT
/* Descriptive Attributes are also now part of the fact */