---- SRC LAYER ----
WITH
SRC_pb             as ( SELECT ACTUAL_INCREMENTAL_CM_DOLLARS, ACTUAL_INCREMENTAL_GROSS_SALES, ACTUAL_INCREMENTAL_NET_SALES, ACTUAL_INCREMENTAL_UNITS, ACTUAL_LIFT, 
                        ACTUAL_ROI, ACTUAL_TOTAL_CM_DOLLARS, ACTUAL_TOTAL_GROSS_SALES, ACTUAL_TOTAL_NET_SALES, ACTUAL_TOTAL_UNITS, ACTUAL_TRADE_SPEND, 
                        ADDITIONAL_PRODUCT_DISPLAY_COST, ADDITIONAL_TRADE_FUNDING_REQUEST, BASE_INVOICE_PRICE, BASE_MATERIAL, BASE_MATERIAL_BK, BASE_MATERIAL_HK, 
                        BASE_RETAIL_PRICE, BILLBACK_AMOUNT, BKCC, BUSINESS_UNIT, COGS_PER_UNIT, DIM_PROMOTION_HK, FUNDING_RATE, G2N_BEFORE_TRADE_RATE, KEY_ACCOUNT_GROUP_BK, 
                        KEY_ACCOUNT_GROUP_HK, LNK_ACCOUNT_BASE_MATERIAL_PROMOTION_HK, PAYMENT_TYPE, PLANNED_BASE_NET_SALES, PLANNED_BASE_UNITS, PLANNED_BASE_UPSPW, 
                        PLANNED_CM_DOLLARS_BEFORE_TRADE, PLANNED_INCR_CM_DOLLARS, PLANNED_INCR_GROSS_SALES, PLANNED_INCR_NET_SALES, PLANNED_INCR_UNITS, PLANNED_LIFT, 
                        PLANNED_PROMO_SPEND_DOLLARS, PLANNED_ROI, PLANNED_TOTAL_CM_DOLLARS, PLANNED_TOTAL_GROSS_SALES, PLANNED_TOTAL_NET_SALES, PLANNED_TOTAL_UNITS, 
                        PLANNED_TRADE_SPEND, PROMOTION_ACCOUNT, PROMOTION_BK, PROMOTION_DISCOUNT_DOLLARS, PROMOTION_DISCOUNT_PER_UNIT_RATE, PROMOTION_END_DATE_KEY, 
                        PROMOTION_END_DATE__YYYYMMDD, PROMOTION_END_FISCAL_WEEK__YYYYWW, PROMOTION_HK, PROMOTION_ID, PROMOTION_NAME, PROMOTION_OWNER, 
                        PROMOTION_REPORTING_CATEGORY, PROMOTION_REPORTING_CHANNEL, PROMOTION_REPORTING_CUSTOMER, PROMOTION_START_DATE_KEY, PROMOTION_START_DATE__YYYYMMDD, 
                        PROMOTION_START_FISCAL_WEEK__YYYYWW, PROMOTION_STATUS, PROMOTION_STORE_COUNT, PROMOTION_TYPE, PROMO_DOLLARS_PER_UNIT_EXC_FIXED, PROMO_RETAIL_PRICE, 
                        PURE_PLAY, REC_SRC, TOTAL_PROMOTION_WEEK_COUNT, VARIABLE_COSTS_RATE FROM {{ ref('pb_promotion_effectiveness') }} as SRC  )

/*
SRC_pb             as ( SELECT * FROM bus_vault.pb_promotion_effectiveness )
*/
---- LOGIC LAYER ----

, LOGIC_pb as (
    SELECT
        LNK_ACCOUNT_BASE_MATERIAL_PROMOTION_HK
      , KEY_ACCOUNT_GROUP_HK
      , BASE_MATERIAL_HK
      , PROMOTION_HK
      , DIM_PROMOTION_HK                                             as                                  DIM_PROMOTION_KEY
      , BASE_MATERIAL_BK
      , KEY_ACCOUNT_GROUP_BK
      , PROMOTION_BK
      , PROMOTION_ID
      , PROMOTION_OWNER
      , PROMOTION_START_DATE_KEY
      , PROMOTION_END_DATE_KEY
      , PROMOTION_NAME
      , BASE_MATERIAL
      , BUSINESS_UNIT
      , PROMOTION_STATUS
      , PROMOTION_TYPE
      , PAYMENT_TYPE
      , PROMOTION_ACCOUNT
      , PURE_PLAY
      , PROMOTION_REPORTING_CATEGORY
      , PROMOTION_START_DATE__YYYYMMDD
      , PROMOTION_END_DATE__YYYYMMDD
      , PROMOTION_REPORTING_CUSTOMER
      , PROMOTION_REPORTING_CHANNEL
      , PROMOTION_START_FISCAL_WEEK__YYYYWW
      , PROMOTION_END_FISCAL_WEEK__YYYYWW
      , PROMOTION_STORE_COUNT
      , BASE_RETAIL_PRICE
      , PROMO_RETAIL_PRICE
      , PLANNED_BASE_UPSPW
      , FUNDING_RATE
      , ADDITIONAL_TRADE_FUNDING_REQUEST
      , ADDITIONAL_PRODUCT_DISPLAY_COST
      , BASE_INVOICE_PRICE
      , PLANNED_BASE_UNITS
      , PLANNED_INCR_UNITS
      , PROMO_DOLLARS_PER_UNIT_EXC_FIXED
      , BILLBACK_AMOUNT
      , PLANNED_PROMO_SPEND_DOLLARS
      , G2N_BEFORE_TRADE_RATE
      , COGS_PER_UNIT
      , VARIABLE_COSTS_RATE
      , PLANNED_CM_DOLLARS_BEFORE_TRADE
      , PLANNED_INCR_CM_DOLLARS
      , PLANNED_TRADE_SPEND
      , ACTUAL_TOTAL_UNITS
      , PROMOTION_DISCOUNT_DOLLARS
      , PROMOTION_DISCOUNT_PER_UNIT_RATE
      , TOTAL_PROMOTION_WEEK_COUNT
      , PLANNED_TOTAL_UNITS
      , PLANNED_TOTAL_GROSS_SALES
      , PLANNED_INCR_GROSS_SALES
      , PLANNED_BASE_NET_SALES
      , PLANNED_INCR_NET_SALES
      , PLANNED_TOTAL_NET_SALES
      , PLANNED_TOTAL_CM_DOLLARS
      , PLANNED_LIFT
      , PLANNED_ROI
      , ACTUAL_INCREMENTAL_UNITS
      , ACTUAL_TOTAL_GROSS_SALES
      , ACTUAL_INCREMENTAL_GROSS_SALES
      , ACTUAL_TRADE_SPEND
      , ACTUAL_TOTAL_NET_SALES
      , ACTUAL_INCREMENTAL_NET_SALES
      , ACTUAL_TOTAL_CM_DOLLARS
      , ACTUAL_INCREMENTAL_CM_DOLLARS
      , ACTUAL_ROI
      , ACTUAL_LIFT
      , REC_SRC
      , BKCC
    FROM SRC_pb
)
---- RENAME LAYER ----

, RENAME_pb as (
    SELECT
        LNK_ACCOUNT_BASE_MATERIAL_PROMOTION_HK
      , KEY_ACCOUNT_GROUP_HK
      , BASE_MATERIAL_HK
      , PROMOTION_HK
      , DIM_PROMOTION_KEY
      , BASE_MATERIAL_BK
      , KEY_ACCOUNT_GROUP_BK
      , PROMOTION_BK
      , PROMOTION_ID
      , PROMOTION_OWNER
      , PROMOTION_START_DATE_KEY
      , PROMOTION_END_DATE_KEY
      , PROMOTION_NAME
      , BASE_MATERIAL
      , BUSINESS_UNIT
      , PROMOTION_STATUS
      , PROMOTION_TYPE
      , PAYMENT_TYPE
      , PROMOTION_ACCOUNT
      , PURE_PLAY
      , PROMOTION_REPORTING_CATEGORY
      , PROMOTION_START_DATE__YYYYMMDD
      , PROMOTION_END_DATE__YYYYMMDD
      , PROMOTION_REPORTING_CUSTOMER
      , PROMOTION_REPORTING_CHANNEL
      , PROMOTION_START_FISCAL_WEEK__YYYYWW
      , PROMOTION_END_FISCAL_WEEK__YYYYWW
      , PROMOTION_STORE_COUNT
      , BASE_RETAIL_PRICE
      , PROMO_RETAIL_PRICE
      , PLANNED_BASE_UPSPW
      , FUNDING_RATE
      , ADDITIONAL_TRADE_FUNDING_REQUEST
      , ADDITIONAL_PRODUCT_DISPLAY_COST
      , BASE_INVOICE_PRICE
      , PLANNED_BASE_UNITS
      , PLANNED_INCR_UNITS
      , PROMO_DOLLARS_PER_UNIT_EXC_FIXED
      , BILLBACK_AMOUNT
      , PLANNED_PROMO_SPEND_DOLLARS
      , G2N_BEFORE_TRADE_RATE
      , COGS_PER_UNIT
      , VARIABLE_COSTS_RATE
      , PLANNED_CM_DOLLARS_BEFORE_TRADE
      , PLANNED_INCR_CM_DOLLARS
      , PLANNED_TRADE_SPEND
      , ACTUAL_TOTAL_UNITS
      , PROMOTION_DISCOUNT_DOLLARS
      , PROMOTION_DISCOUNT_PER_UNIT_RATE
      , TOTAL_PROMOTION_WEEK_COUNT
      , PLANNED_TOTAL_UNITS
      , PLANNED_TOTAL_GROSS_SALES
      , PLANNED_INCR_GROSS_SALES
      , PLANNED_BASE_NET_SALES
      , PLANNED_INCR_NET_SALES
      , PLANNED_TOTAL_NET_SALES
      , PLANNED_TOTAL_CM_DOLLARS
      , PLANNED_LIFT
      , PLANNED_ROI
      , ACTUAL_INCREMENTAL_UNITS
      , ACTUAL_TOTAL_GROSS_SALES
      , ACTUAL_INCREMENTAL_GROSS_SALES
      , ACTUAL_TRADE_SPEND
      , ACTUAL_TOTAL_NET_SALES
      , ACTUAL_INCREMENTAL_NET_SALES
      , ACTUAL_TOTAL_CM_DOLLARS
      , ACTUAL_INCREMENTAL_CM_DOLLARS
      , ACTUAL_ROI
      , ACTUAL_LIFT
      , REC_SRC
      , BKCC
    FROM LOGIC_pb
)
---- FILTER LAYER ----

, FILTER_pb as (
    SELECT *
    FROM RENAME_pb
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM FILTER_pb
)

---- FINAL LAYER ----
SELECT
          LNK_ACCOUNT_BASE_MATERIAL_PROMOTION_HK
        , KEY_ACCOUNT_GROUP_HK
        , BASE_MATERIAL_HK
        , PROMOTION_HK
        , DIM_PROMOTION_KEY
        , BASE_MATERIAL_BK
        , KEY_ACCOUNT_GROUP_BK
        , PROMOTION_BK
        , PROMOTION_ID
        , PROMOTION_OWNER
        , PROMOTION_START_DATE_KEY
        , PROMOTION_END_DATE_KEY
        , PROMOTION_NAME
        , BASE_MATERIAL
        , BUSINESS_UNIT
        , PROMOTION_STATUS
        , PROMOTION_TYPE
        , PAYMENT_TYPE
        , PROMOTION_ACCOUNT
        , PURE_PLAY
        , PROMOTION_REPORTING_CATEGORY
        , PROMOTION_START_DATE__YYYYMMDD
        , PROMOTION_END_DATE__YYYYMMDD
        , PROMOTION_REPORTING_CUSTOMER
        , PROMOTION_REPORTING_CHANNEL
        , PROMOTION_START_FISCAL_WEEK__YYYYWW
        , PROMOTION_END_FISCAL_WEEK__YYYYWW
        , PROMOTION_STORE_COUNT
        , BASE_RETAIL_PRICE
        , PROMO_RETAIL_PRICE
        , PLANNED_BASE_UPSPW
        , FUNDING_RATE
        , ADDITIONAL_TRADE_FUNDING_REQUEST
        , ADDITIONAL_PRODUCT_DISPLAY_COST
        , BASE_INVOICE_PRICE
        , PLANNED_BASE_UNITS
        , PLANNED_INCR_UNITS
        , PROMO_DOLLARS_PER_UNIT_EXC_FIXED
        , BILLBACK_AMOUNT
        , PLANNED_PROMO_SPEND_DOLLARS
        , G2N_BEFORE_TRADE_RATE
        , COGS_PER_UNIT
        , VARIABLE_COSTS_RATE
        , PLANNED_CM_DOLLARS_BEFORE_TRADE
        , PLANNED_INCR_CM_DOLLARS
        , PLANNED_TRADE_SPEND
        , ACTUAL_TOTAL_UNITS
        , PROMOTION_DISCOUNT_DOLLARS
        , PROMOTION_DISCOUNT_PER_UNIT_RATE
        , TOTAL_PROMOTION_WEEK_COUNT
        , PLANNED_TOTAL_UNITS
        , PLANNED_TOTAL_GROSS_SALES
        , PLANNED_INCR_GROSS_SALES
        , PLANNED_BASE_NET_SALES
        , PLANNED_INCR_NET_SALES
        , PLANNED_TOTAL_NET_SALES
        , PLANNED_TOTAL_CM_DOLLARS
        , PLANNED_LIFT
        , PLANNED_ROI
        , ACTUAL_INCREMENTAL_UNITS
        , ACTUAL_TOTAL_GROSS_SALES
        , ACTUAL_INCREMENTAL_GROSS_SALES
        , ACTUAL_TRADE_SPEND
        , ACTUAL_TOTAL_NET_SALES
        , ACTUAL_INCREMENTAL_NET_SALES
        , ACTUAL_TOTAL_CM_DOLLARS
        , ACTUAL_INCREMENTAL_CM_DOLLARS
        , ACTUAL_ROI
        , ACTUAL_LIFT
        , REC_SRC
        , BKCC
FROM JOIN_RESULT
