---- SRC LAYER ----
WITH
SRC_PB             as ( SELECT APP_SOURCE, BKCC, CONSUMER_BK, CONSUMER_HK, PLATFORM, REC_SRC, SCREEN_ACTION_TS, SCREEN_NAME, SCREEN_TRACKING_ID, SCREEN_TRAIT_ID FROM {{ ref('pb_app_user_engagement_screen') }} as SRC  )

/*
SRC_PB             as ( SELECT * FROM BUS_VAULT.PB_APP_USER_ENGAGEMENT_SCREEN )
*/
---- LOGIC LAYER ----

, LOGIC_PB as (
    SELECT
        CONSUMER_BK
      , BKCC
      , REC_SRC
      , CONSUMER_HK
      , SCREEN_TRAIT_ID
      , SCREEN_TRACKING_ID
      , SCREEN_NAME
      , SCREEN_ACTION_TS
      , PLATFORM
      , APP_SOURCE
    FROM SRC_PB
)
---- RENAME LAYER ----

, RENAME_PB as (
    SELECT
        CONSUMER_BK
      , BKCC
      , REC_SRC
      , CONSUMER_HK
      , SCREEN_TRAIT_ID
      , SCREEN_TRACKING_ID
      , SCREEN_NAME
      , SCREEN_ACTION_TS
      , PLATFORM
      , APP_SOURCE
    FROM LOGIC_PB
)
---- FILTER LAYER ----

, FILTER_PB as (
    SELECT *
    FROM RENAME_PB
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM FILTER_PB
)

---- FINAL LAYER ----
SELECT
          CONSUMER_BK
        , BKCC
        , REC_SRC
        , CONSUMER_HK
        , SCREEN_TRAIT_ID
        , SCREEN_TRACKING_ID
        , SCREEN_NAME
        , SCREEN_ACTION_TS
        , PLATFORM
        , APP_SOURCE
FROM JOIN_RESULT
