---- SRC LAYER ----
WITH
SRC_PB             as ( SELECT AVG_FALSE_ALARMS_PER_MONTH, BKCC, FALSE_ALARM_COUNT, FALSE_POSITIVE_RATE, MONTH_NUM, NUM_FLOW_EVENTS, PERIOD_START_DATE_KEY, PERIOD_TYPE, QUALIFIED_DEVICE_COUNT, QUARTER_NUM, REC_SRC, TOTAL_ALERT_COUNT, YEAR_NUM FROM {{ ref('pb_false_positive_rate_period') }} as SRC  )

/*
SRC_PB             as ( SELECT * FROM BUS_VAULT.PB_FALSE_POSITIVE_RATE_PERIOD )
*/
---- LOGIC LAYER ----

, LOGIC_PB as (
    SELECT
        PERIOD_TYPE
      , PERIOD_START_DATE_KEY
      , YEAR_NUM
      , QUARTER_NUM
      , MONTH_NUM
      , QUALIFIED_DEVICE_COUNT
      , FALSE_ALARM_COUNT
      , TOTAL_ALERT_COUNT
      , NUM_FLOW_EVENTS
      , FALSE_POSITIVE_RATE
      , AVG_FALSE_ALARMS_PER_MONTH
      , BKCC
      , REC_SRC
    FROM SRC_PB
)
---- RENAME LAYER ----

, RENAME_PB as (
    SELECT
        PERIOD_TYPE
      , PERIOD_START_DATE_KEY
      , YEAR_NUM
      , QUARTER_NUM
      , MONTH_NUM
      , QUALIFIED_DEVICE_COUNT
      , FALSE_ALARM_COUNT
      , TOTAL_ALERT_COUNT
      , NUM_FLOW_EVENTS
      , FALSE_POSITIVE_RATE
      , AVG_FALSE_ALARMS_PER_MONTH
      , BKCC
      , REC_SRC
    FROM LOGIC_PB
)
---- FILTER LAYER ----

, FILTER_PB as (
    SELECT *
    FROM RENAME_PB
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM FILTER_PB
)

---- FINAL LAYER ----
SELECT
          PERIOD_TYPE
        , PERIOD_START_DATE_KEY
        , YEAR_NUM
        , QUARTER_NUM
        , MONTH_NUM
        , QUALIFIED_DEVICE_COUNT
        , FALSE_ALARM_COUNT
        , TOTAL_ALERT_COUNT
        , NUM_FLOW_EVENTS
        , FALSE_POSITIVE_RATE
        , AVG_FALSE_ALARMS_PER_MONTH
        , BKCC
        , REC_SRC
FROM JOIN_RESULT
