---- SRC LAYER ----
WITH
SRC_dc             as ( SELECT SEQ_ID, BKCC, CUSTOMER_BK, CUSTOMER_HK, DISTRIBUTION_CHANNEL_BK, DISTRIBUTION_CHANNEL_HK, DIVISION_BK, DIVISION_HK, INVOICED_DATE__YYYYMMDD, INVOICED_QUANTITY, INVOICE_BK, INVOICE_HK, INVOICE_LINE_BK, INVOICE_LINE_HK, INVOICE_LINE_PACING_LHK, ITEM_HK, NET_VALUE, PLANT_BK, PLANT_HK, REC_SRC, SALES_ORGANIZATION_BK, SALES_ORGANIZATION_HK, TAX_AMOUNT, ITEM_BK FROM {{ ref('pb_invoice_line_pacing') }} as SRC  )

/*
SRC_dc             as ( SELECT * FROM BUS_VAULT.pb_invoice_line_pacing )
*/
---- LOGIC LAYER ----

, LOGIC_dc as (
    SELECT
        SEQ_ID
      , BKCC
      , REC_SRC
      , ITEM_HK
      , PLANT_HK
      , CUSTOMER_HK
      , DIVISION_HK
      , SALES_ORGANIZATION_HK
      , DISTRIBUTION_CHANNEL_HK
      , INVOICE_HK
      , INVOICE_LINE_HK
      , INVOICE_LINE_PACING_LHK
      , INVOICED_QUANTITY
      , NET_VALUE
      , TAX_AMOUNT
      , INVOICED_DATE__YYYYMMDD
      , PLANT_BK
      , CUSTOMER_BK
      , DIVISION_BK
      , SALES_ORGANIZATION_BK
      , DISTRIBUTION_CHANNEL_BK
      , INVOICE_BK
      , INVOICE_LINE_BK
      , ITEM_BK
    FROM SRC_dc
)
---- RENAME LAYER ----

, RENAME_dc as (
    SELECT
        SEQ_ID
      , BKCC
      , REC_SRC
      , ITEM_HK
      , PLANT_HK
      , CUSTOMER_HK
      , DIVISION_HK
      , SALES_ORGANIZATION_HK
      , DISTRIBUTION_CHANNEL_HK
      , INVOICE_HK
      , INVOICE_LINE_HK
      , INVOICE_LINE_PACING_LHK
      , INVOICED_QUANTITY
      , NET_VALUE
      , TAX_AMOUNT
      , INVOICED_DATE__YYYYMMDD
      , PLANT_BK
      , CUSTOMER_BK
      , DIVISION_BK
      , SALES_ORGANIZATION_BK
      , DISTRIBUTION_CHANNEL_BK
      , INVOICE_BK
      , INVOICE_LINE_BK
      , ITEM_BK
    FROM LOGIC_dc
)
---- FILTER LAYER ----

, FILTER_dc as (
    SELECT *
    FROM RENAME_dc
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM FILTER_dc
)

---- FINAL LAYER ----
SELECT
          SEQ_ID
        , BKCC
        , REC_SRC
        , ITEM_HK
        , PLANT_HK
        , CUSTOMER_HK
        , DIVISION_HK
        , SALES_ORGANIZATION_HK
        , DISTRIBUTION_CHANNEL_HK
        , INVOICE_HK
        , INVOICE_LINE_HK
        , INVOICE_LINE_PACING_LHK
        , INVOICED_QUANTITY
        , NET_VALUE
        , TAX_AMOUNT
        , INVOICED_DATE__YYYYMMDD
        , PLANT_BK
        , CUSTOMER_BK
        , DIVISION_BK
        , SALES_ORGANIZATION_BK
        , DISTRIBUTION_CHANNEL_BK
        , INVOICE_BK
        , INVOICE_LINE_BK
        , ITEM_BK
FROM JOIN_RESULT
