---- SRC LAYER ----
WITH
SRC_dc             as ( SELECT VENDOR_ORDER_ITEM_HK,VENDOR_ORDER_HK,VENDOR_ORDER_BK,VENDOR_ORDER_LINE_BK,REC_SRC,BKCC,VENDOR_PO_SEQUENCE_NUMBER,NET_COST_AMOUNT,AMOUNT,LIST_PRICE_AMOUNT,ORDERED_QUANTITY_AMOUNT,REJECTED_QUANTITY_AMOUNT,RECEIVED_QUANTITY_AMOUNT,ACCEPTED_QUANTITY_AMOUNT,STATUS_NET_COST_AMOUNT,STATUS_LIST_PRICE_AMOUNT,CONFIRMATION_STATUS,RECEIPT_REJECTED_QUANTITY_AMOUNT,RECEIPT_ACCEPTED_QUANTITY_AMOUNT,RECEIVE_STATUS,VENDOR_PO_NUMBER,ACKNOWLEDGEMENT_DATE__YYYYMMDD,ITEM_HK,ITEM_BK,ORDER_LINE_HK,ORDER_LINE_BK,SNAPSHOT_DTS,PSA_DELETE_IND FROM {{ ref('pb_vendor_purchase_order_item') }} as SRC  )

/*
SRC_dc             as ( SELECT * FROM BUS_VAULT.pit_vendor_purchase_order_item )
*/
---- LOGIC LAYER ----

, LOGIC_dc as (
    SELECT
         VENDOR_ORDER_ITEM_HK
        ,VENDOR_ORDER_HK
        ,VENDOR_ORDER_BK
        ,VENDOR_ORDER_LINE_BK
        ,REC_SRC
        ,BKCC
        ,VENDOR_PO_SEQUENCE_NUMBER
        ,NET_COST_AMOUNT
        ,AMOUNT
        ,LIST_PRICE_AMOUNT
        ,ORDERED_QUANTITY_AMOUNT
        ,REJECTED_QUANTITY_AMOUNT
        ,RECEIVED_QUANTITY_AMOUNT
        ,ACCEPTED_QUANTITY_AMOUNT
        ,STATUS_NET_COST_AMOUNT
        ,STATUS_LIST_PRICE_AMOUNT
        ,CONFIRMATION_STATUS
        ,RECEIPT_REJECTED_QUANTITY_AMOUNT
        ,RECEIPT_ACCEPTED_QUANTITY_AMOUNT
        ,RECEIVE_STATUS
        ,VENDOR_PO_NUMBER
        ,ACKNOWLEDGEMENT_DATE__YYYYMMDD
        ,ITEM_HK
        ,ITEM_BK
        ,ORDER_LINE_HK
        ,ORDER_LINE_BK
        ,SNAPSHOT_DTS
        ,PSA_DELETE_IND
    FROM SRC_dc
)
---- RENAME LAYER ----

, RENAME_dc as (
    SELECT
        VENDOR_ORDER_ITEM_HK
        ,VENDOR_ORDER_HK
        ,VENDOR_ORDER_BK
        ,VENDOR_ORDER_LINE_BK
        ,REC_SRC
        ,BKCC
        ,VENDOR_PO_SEQUENCE_NUMBER
        ,NET_COST_AMOUNT
        ,AMOUNT
        ,LIST_PRICE_AMOUNT
        ,ORDERED_QUANTITY_AMOUNT
        ,REJECTED_QUANTITY_AMOUNT
        ,RECEIVED_QUANTITY_AMOUNT
        ,ACCEPTED_QUANTITY_AMOUNT
        ,STATUS_NET_COST_AMOUNT
        ,STATUS_LIST_PRICE_AMOUNT
        ,CONFIRMATION_STATUS
        ,RECEIPT_REJECTED_QUANTITY_AMOUNT
        ,RECEIPT_ACCEPTED_QUANTITY_AMOUNT
        ,RECEIVE_STATUS
        ,VENDOR_PO_NUMBER
        ,ACKNOWLEDGEMENT_DATE__YYYYMMDD
        ,ITEM_HK
        ,ITEM_BK
        ,ORDER_LINE_HK
        ,ORDER_LINE_BK
        ,SNAPSHOT_DTS
        ,PSA_DELETE_IND
    FROM LOGIC_dc
)
---- FILTER LAYER ----

, FILTER_dc as (
    SELECT *
    FROM RENAME_dc
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM FILTER_dc
)

---- FINAL LAYER ----
SELECT
          VENDOR_ORDER_ITEM_HK
        ,VENDOR_ORDER_HK
        ,VENDOR_ORDER_BK
        ,VENDOR_ORDER_LINE_BK
        ,REC_SRC
        ,BKCC
        ,VENDOR_PO_SEQUENCE_NUMBER
        ,NET_COST_AMOUNT
        ,AMOUNT
        ,LIST_PRICE_AMOUNT
        ,ORDERED_QUANTITY_AMOUNT
        ,REJECTED_QUANTITY_AMOUNT
        ,RECEIVED_QUANTITY_AMOUNT
        ,ACCEPTED_QUANTITY_AMOUNT
        ,STATUS_NET_COST_AMOUNT
        ,STATUS_LIST_PRICE_AMOUNT
        ,CONFIRMATION_STATUS
        ,RECEIPT_REJECTED_QUANTITY_AMOUNT
        ,RECEIPT_ACCEPTED_QUANTITY_AMOUNT
        ,RECEIVE_STATUS
        ,VENDOR_PO_NUMBER
        ,ACKNOWLEDGEMENT_DATE__YYYYMMDD
        ,ITEM_HK
        ,ITEM_BK
        ,ORDER_LINE_HK
        ,ORDER_LINE_BK
        ,SNAPSHOT_DTS
        ,PSA_DELETE_IND
FROM JOIN_RESULT
