---- SRC LAYER ----
WITH
SRC_P              as ( SELECT * FROM {{ ref('pit_sales_invoice_line_current') }} as SRC  )

/*
SRC_P              as ( SELECT * FROM RAW_VAULT.PIT_SALES_INVOICE_LINE_CURRENT )
*/
---- LOGIC LAYER ----

, LOGIC_P as (
    SELECT
        SALES_INVOICE_LINE_BK
      , BKCC
      , REC_SRC
      , BASE_UNIT_OF_MEASURE
      , SCALE_BASE_UNIT_OF_MEASURE
      , SKU_BILLING_QTY
      , MATERIAL_REFERENCE_SKU_QTY
      , ACTUAL_INVOICE_QTY
      , SALES_UNIT
      , NET_WEIGHT
      , GROSS_WEIGHT
      , WEIGHT_UNIT
      , VOLUME
      , VOLUME_UNIT
      , BUSINESS_AREA
      , PRICE_DATE_EXCHANGE_RATE
      , SERVICE_RENDERED_DATE__YYYYMMDD
      , EXC_RATE_PRICE_DET
      , CURRENCY_AMOUNT_1
      , ORIGINAL_ITEM
      , REFERENCE_DOCUMENT
      , ITEM_NUM_REFERENCE
      , DOCUMENT_CATEGORY_SDDOCUMENT
      , SALES_DOCUMENT
      , SALES_DOCUMENT_ITEM
      , SALES_DOCUMENT_FROM_REFERENCE
      , MATERIAL_NUM
      , SHORT_TXT_SALES_ORDER_ITEM
      , PRICE_REFERENCE_MATERIAL
      , BATCH_NUM
      , MATERIAL_GROUP
      , SALES_DOCUMENT_ITEM_CATEGORY
      , ITEM_TYPE
      , SHIP_POINT
      , DIVISION
      , ITEM_NUM_PART_SEGMENT
      , PLANT
      , DEPART_COUNTRY
      , PLANT_REGION
      , PLANT_COUNTRY
      , PLANT_CITY
      , TAX_CLASSIFICATION_MATERIAL
      , TAX_CLASSIFICATION_MATERIAL2
      , TAX_CLASSIFICATION_MATERIAL3
      , TAX_CLASSIFICATION_MATERIAL4
      , TAX_CLASSIFICATION_MATERIAL5
      , TAX_CLASSIFICATION_MATERIAL6
      , TAX_CLASSIFICATION_MATERIAL7
      , TAX_CLASSIFICATION_MATERIAL8
      , TAX_CLASSIFICATION_MATERIAL9
      , CURRENCY_AMOUNT_2
      , MATERIAL_PRICING_GROUP
      , COST_CENTER
      , VOLUME_REBATE_GROUP
      , STORAGE_LOCATION
      , COST_DOCUMENT_CURRENCY
      , ITEM_CREDIT_PRICE
      , SD_DOCUMENT_CATEGORY
      , COMMISSION_GROUP
      , SALES_GROUP
      , SALES_OFFICE
      , ORDER_HEAD_DIV
      , RETURN_ITEM
      , INVOICE_CREATION_DATE__YYYYMMDD
      , PROFIT_CENTER
      , CUSTOMER_GROUP1
      , CUSTOMER_GROUP2
      , CUSTOMER_GROUP3
      , CUSTOMER_GROUP4
      , CUSTOMER_GROUP5
      , MATERIAL_GROUP1
      , MATERIAL_GROUP2
      , MATERIAL_GROUP3
      , MATERIAL_GROUP4
      , MATERIAL_GROUP5
      , MATERIAL_ENTERED
      , PROFIT_SEGMENT_NUM
      , SALES_DISTRICT_SALES_ORDER
      , CUSTOMER_GROUP_SALES_ORDER
      , PRICE_GROUP_SALES_ORDER
      , COUNTRY_DESTINATION_SALES_ORDER
      , STATUS_MAN_PRICE_CHANGE
      , PRICE_LIST_TYPE_SALES_ORDER
      , REGION_SALES_ORDER
      , SALES_ORG_SALES_ORDER
      , DISTRIBUTION_CHAN_SALES_ORDER
      , PROMOTION
      , SALES_DEAL
      , RETURN_REFUND_CODE
      , RETURN_REASON
      , DISPUTE_CASE
      , ACCOUNTING_DOCUMENT_TRANSACTION_SEQUENCE_NUM
      , IS_DELETED
    FROM SRC_P
)
---- RENAME LAYER ----

, RENAME_P as (
    SELECT
        SALES_INVOICE_LINE_BK
      , BKCC
      , REC_SRC
      , BASE_UNIT_OF_MEASURE
      , SCALE_BASE_UNIT_OF_MEASURE
      , SKU_BILLING_QTY
      , MATERIAL_REFERENCE_SKU_QTY
      , ACTUAL_INVOICE_QTY
      , SALES_UNIT
      , NET_WEIGHT
      , GROSS_WEIGHT
      , WEIGHT_UNIT
      , VOLUME  
      , VOLUME_UNIT
      , BUSINESS_AREA
      , PRICE_DATE_EXCHANGE_RATE 
      , SERVICE_RENDERED_DATE__YYYYMMDD
      , EXC_RATE_PRICE_DET
      , CURRENCY_AMOUNT_1
      , ORIGINAL_ITEM
      , REFERENCE_DOCUMENT
      , ITEM_NUM_REFERENCE
      , DOCUMENT_CATEGORY_SDDOCUMENT
      , SALES_DOCUMENT
      , SALES_DOCUMENT_ITEM
      , SALES_DOCUMENT_FROM_REFERENCE
      , MATERIAL_NUM
      , SHORT_TXT_SALES_ORDER_ITEM
      , PRICE_REFERENCE_MATERIAL
      , BATCH_NUM
      , MATERIAL_GROUP
      , SALES_DOCUMENT_ITEM_CATEGORY
      , ITEM_TYPE
      , SHIP_POINT
      , DIVISION  
      , ITEM_NUM_PART_SEGMENT
      , PLANT
      , DEPART_COUNTRY
      , PLANT_REGION
      , PLANT_COUNTRY
      , PLANT_CITY
      , TAX_CLASSIFICATION_MATERIAL
      , TAX_CLASSIFICATION_MATERIAL2
      , TAX_CLASSIFICATION_MATERIAL3
      , TAX_CLASSIFICATION_MATERIAL4
      , TAX_CLASSIFICATION_MATERIAL5
      , TAX_CLASSIFICATION_MATERIAL6
      , TAX_CLASSIFICATION_MATERIAL7
      , TAX_CLASSIFICATION_MATERIAL8
      , TAX_CLASSIFICATION_MATERIAL9
      , CURRENCY_AMOUNT_2
      , MATERIAL_PRICING_GROUP
      , COST_CENTER
      , VOLUME_REBATE_GROUP
      , STORAGE_LOCATION
      , COST_DOCUMENT_CURRENCY
      , ITEM_CREDIT_PRICE
      , SD_DOCUMENT_CATEGORY
      , COMMISSION_GROUP
      , SALES_GROUP
      , SALES_OFFICE
      , ORDER_HEAD_DIV
      , RETURN_ITEM
      , INVOICE_CREATION_DATE__YYYYMMDD
      , PROFIT_CENTER
      , CUSTOMER_GROUP1
      , CUSTOMER_GROUP2
      , CUSTOMER_GROUP3
      , CUSTOMER_GROUP4
      , CUSTOMER_GROUP5
      , MATERIAL_GROUP1
      , MATERIAL_GROUP2
      , MATERIAL_GROUP3
      , MATERIAL_GROUP4
      , MATERIAL_GROUP5
      , MATERIAL_ENTERED
      , PROFIT_SEGMENT_NUM
      , SALES_DISTRICT_SALES_ORDER
      , CUSTOMER_GROUP_SALES_ORDER
      , PRICE_GROUP_SALES_ORDER
      , COUNTRY_DESTINATION_SALES_ORDER
      , STATUS_MAN_PRICE_CHANGE
      , PRICE_LIST_TYPE_SALES_ORDER
      , REGION_SALES_ORDER
      , SALES_ORG_SALES_ORDER
      , DISTRIBUTION_CHAN_SALES_ORDER
      , PROMOTION
      , SALES_DEAL
      , RETURN_REFUND_CODE
      , RETURN_REASON
      , DISPUTE_CASE
      , ACCOUNTING_DOCUMENT_TRANSACTION_SEQUENCE_NUM
      , IS_DELETED
    FROM LOGIC_P
)
---- FILTER LAYER ----

, FILTER_P as (
    SELECT *
    FROM RENAME_P   /* This filter is to exclude the ghost records */
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM FILTER_P
)

---- FINAL LAYER ----
SELECT
          SALES_INVOICE_LINE_BK
        , BKCC
        , REC_SRC
        , BASE_UNIT_OF_MEASURE
        , SCALE_BASE_UNIT_OF_MEASURE
        , SKU_BILLING_QTY
        , MATERIAL_REFERENCE_SKU_QTY
        , ACTUAL_INVOICE_QTY
        , SALES_UNIT
        , NET_WEIGHT
        , GROSS_WEIGHT
        , WEIGHT_UNIT
        , VOLUME  
        , VOLUME_UNIT
        , BUSINESS_AREA
        , PRICE_DATE_EXCHANGE_RATE 
        , SERVICE_RENDERED_DATE__YYYYMMDD
        , EXC_RATE_PRICE_DET
        , CURRENCY_AMOUNT_1
        , ORIGINAL_ITEM
        , REFERENCE_DOCUMENT
        , ITEM_NUM_REFERENCE
        , DOCUMENT_CATEGORY_SDDOCUMENT
        , SALES_DOCUMENT
        , SALES_DOCUMENT_ITEM
        , SALES_DOCUMENT_FROM_REFERENCE
        , MATERIAL_NUM
        , SHORT_TXT_SALES_ORDER_ITEM
        , PRICE_REFERENCE_MATERIAL
        , BATCH_NUM
        , MATERIAL_GROUP
        , SALES_DOCUMENT_ITEM_CATEGORY
        , ITEM_TYPE
        , SHIP_POINT
        , DIVISION  
        , ITEM_NUM_PART_SEGMENT
        , PLANT
        , DEPART_COUNTRY
        , PLANT_REGION
        , PLANT_COUNTRY
        , PLANT_CITY
        , TAX_CLASSIFICATION_MATERIAL
        , TAX_CLASSIFICATION_MATERIAL2
        , TAX_CLASSIFICATION_MATERIAL3
        , TAX_CLASSIFICATION_MATERIAL4
        , TAX_CLASSIFICATION_MATERIAL5
        , TAX_CLASSIFICATION_MATERIAL6
        , TAX_CLASSIFICATION_MATERIAL7
        , TAX_CLASSIFICATION_MATERIAL8
        , TAX_CLASSIFICATION_MATERIAL9
        , CURRENCY_AMOUNT_2
        , MATERIAL_PRICING_GROUP
        , COST_CENTER
        , VOLUME_REBATE_GROUP
        , STORAGE_LOCATION
        , COST_DOCUMENT_CURRENCY
        , ITEM_CREDIT_PRICE
        , SD_DOCUMENT_CATEGORY
        , COMMISSION_GROUP
        , SALES_GROUP
        , SALES_OFFICE
        , ORDER_HEAD_DIV
        , RETURN_ITEM
        , INVOICE_CREATION_DATE__YYYYMMDD
        , PROFIT_CENTER
        , CUSTOMER_GROUP1
        , CUSTOMER_GROUP2
        , CUSTOMER_GROUP3
        , CUSTOMER_GROUP4
        , CUSTOMER_GROUP5
        , MATERIAL_GROUP1
        , MATERIAL_GROUP2
        , MATERIAL_GROUP3
        , MATERIAL_GROUP4
        , MATERIAL_GROUP5
        , MATERIAL_ENTERED
        , PROFIT_SEGMENT_NUM
        , SALES_DISTRICT_SALES_ORDER
        , CUSTOMER_GROUP_SALES_ORDER
        , PRICE_GROUP_SALES_ORDER
        , COUNTRY_DESTINATION_SALES_ORDER
        , STATUS_MAN_PRICE_CHANGE
        , PRICE_LIST_TYPE_SALES_ORDER
        , REGION_SALES_ORDER
        , SALES_ORG_SALES_ORDER
        , DISTRIBUTION_CHAN_SALES_ORDER
        , PROMOTION
        , SALES_DEAL
        , RETURN_REFUND_CODE
        , RETURN_REASON
        , DISPUTE_CASE
        , ACCOUNTING_DOCUMENT_TRANSACTION_SEQUENCE_NUM
        , IS_DELETED
FROM JOIN_RESULT
