{{
  config(
    materialized = 'incremental',
    unique_key='CONTROLLING_LEDGER_ENTRY_HK',
    incremental_strategy= 'merge'
  )
}}
---- SRC LAYER ----
WITH
SRC_PB             as ( SELECT CONTROLLING_LEDGER_ENTRY_HK, BKCC, REC_SRC, CLIENT, CONTROLLING_AREA, DOCUMENT_NUMBER, POSTING_ROW, PERIOD, TOTAL_VALUE_TRANSACTION_CURRENCY, TOTAL_VALUE_OBJECT_CURRENCY, TOTAL_VALUE_CO_AREA_CURRENCY, FIXED_VALUE_CO_AREA_CURRENCY, TOTAL_PRICE_VARIANCE_CO_AREA_CURRENCY, FIXED_PRICE_VARIANCE_CO_AREA_CURRENCY, TOTAL_QUANTITY, FIXED_QUANTITY, TOTAL_QUANTITY_ENTERED, FIXED_QUANTITY_ENTERED, LEDGER, OBJECT_NUMBER, FISCAL_YEAR__YYYY, VALUE_TYPE, VERSION, COST_ELEMENT, ORIGIN, TRANSACTION, PARTNER_OBJECT, PARTNER_OBJECT_ALWAYS_FILLED, SOURCE_OBJECT_COST_CENTER_ACTIVITY_TYPE, TRADING_PARTNER_COMPANY_ID, TRADING_PARTNER_BUSINESS_AREA, TRANSACTION_CURRENCY, OBJECT_CURRENCY, BASE_UNIT_OF_MEASURE, UNIT_OF_MEASURE, ITEM_TEXT, REFERENCE_DOCUMENT_POSTING_ROW, DOCUMENT_ITEM_NUMBER, OPERATIVE_VERSION_POSTING_ROW, OFFSETTING_ACCOUNT_NUMBER, OFFSETTING_ACCOUNT_TYPE, PLANT, MATERIAL_NUMBER, REFERENCE_PURCHASE_ORDER_CATEGORY, PURCHASING_DOCUMENT_NUMBER, PURCHASING_DOCUMENT_ITEM_NUMBER, ACCOUNT_ASSIGNMENT_SEQUENTIAL_NUMBER, PERSONNEL_NUMBER, CO_AREA_CURRENCY_AMOUNT_CLASS, AUXILIARY_ACCOUNT_ASSIGNMENT_1, AUXILIARY_ACCOUNT_ASSIGNMENT_2, PROFITABILITY_SEGMENT_NUMBER, DEBIT_TYPE, COMPANY_CODE, BUSINESS_AREA, FUNCTIONAL_AREA, SEGMENT, PARTNER_COMPANY_CODE, PARTNER_FUNCTIONAL_AREA, PARTNER_SEGMENT, SETTLEMENT_DATE__YYYYMMDD, ALLOCATION_PRICE_STRATEGY, TIME_CREATED_GMT, FI_REFERENCE_DOCUMENT_POSTING_ITEM, JVA_PRODUCTION_MONTH, IS_DELETED FROM {{ ref('pb_controlling_ledger_entry') }} as SRC  )

/*
SRC_PB             as ( SELECT * FROM BUS_VAULT.PB_CONTROLLING_LEDGER_ENTRY )
*/
---- LOGIC LAYER ----

, LOGIC_PB as (
    SELECT
        CONTROLLING_LEDGER_ENTRY_HK
      , BKCC
      , REC_SRC
      , CLIENT
      , CONTROLLING_AREA
      , DOCUMENT_NUMBER
      , POSTING_ROW
      , PERIOD
      , TOTAL_VALUE_TRANSACTION_CURRENCY
      , TOTAL_VALUE_OBJECT_CURRENCY
      , TOTAL_VALUE_CO_AREA_CURRENCY
      , FIXED_VALUE_CO_AREA_CURRENCY
      , TOTAL_PRICE_VARIANCE_CO_AREA_CURRENCY
      , FIXED_PRICE_VARIANCE_CO_AREA_CURRENCY
      , TOTAL_QUANTITY
      , FIXED_QUANTITY
      , TOTAL_QUANTITY_ENTERED
      , FIXED_QUANTITY_ENTERED
      , LEDGER
      , OBJECT_NUMBER
      , FISCAL_YEAR__YYYY
      , VALUE_TYPE
      , VERSION
      , COST_ELEMENT
      , ORIGIN
      , TRANSACTION
      , PARTNER_OBJECT
      , PARTNER_OBJECT_ALWAYS_FILLED
      , SOURCE_OBJECT_COST_CENTER_ACTIVITY_TYPE
      , TRADING_PARTNER_COMPANY_ID
      , TRADING_PARTNER_BUSINESS_AREA
      , TRANSACTION_CURRENCY
      , OBJECT_CURRENCY
      , BASE_UNIT_OF_MEASURE
      , UNIT_OF_MEASURE
      , ITEM_TEXT
      , REFERENCE_DOCUMENT_POSTING_ROW
      , DOCUMENT_ITEM_NUMBER
      , OPERATIVE_VERSION_POSTING_ROW
      , OFFSETTING_ACCOUNT_NUMBER
      , OFFSETTING_ACCOUNT_TYPE
      , PLANT
      , MATERIAL_NUMBER
      , REFERENCE_PURCHASE_ORDER_CATEGORY
      , PURCHASING_DOCUMENT_NUMBER
      , PURCHASING_DOCUMENT_ITEM_NUMBER
      , ACCOUNT_ASSIGNMENT_SEQUENTIAL_NUMBER
      , PERSONNEL_NUMBER
      , CO_AREA_CURRENCY_AMOUNT_CLASS
      , AUXILIARY_ACCOUNT_ASSIGNMENT_1
      , AUXILIARY_ACCOUNT_ASSIGNMENT_2
      , PROFITABILITY_SEGMENT_NUMBER
      , DEBIT_TYPE
      , COMPANY_CODE
      , BUSINESS_AREA
      , FUNCTIONAL_AREA
      , SEGMENT
      , PARTNER_COMPANY_CODE
      , PARTNER_FUNCTIONAL_AREA
      , PARTNER_SEGMENT
      , SETTLEMENT_DATE__YYYYMMDD
      , ALLOCATION_PRICE_STRATEGY
      , TIME_CREATED_GMT
      , FI_REFERENCE_DOCUMENT_POSTING_ITEM
      , JVA_PRODUCTION_MONTH
      , IS_DELETED
    FROM SRC_PB
)
---- RENAME LAYER ----

, RENAME_PB as (
    SELECT
        CONTROLLING_LEDGER_ENTRY_HK
      , BKCC
      , REC_SRC
      , CLIENT
      , CONTROLLING_AREA
      , DOCUMENT_NUMBER
      , POSTING_ROW
      , PERIOD
      , TOTAL_VALUE_TRANSACTION_CURRENCY
      , TOTAL_VALUE_OBJECT_CURRENCY
      , TOTAL_VALUE_CO_AREA_CURRENCY
      , FIXED_VALUE_CO_AREA_CURRENCY
      , TOTAL_PRICE_VARIANCE_CO_AREA_CURRENCY
      , FIXED_PRICE_VARIANCE_CO_AREA_CURRENCY
      , TOTAL_QUANTITY
      , FIXED_QUANTITY
      , TOTAL_QUANTITY_ENTERED
      , FIXED_QUANTITY_ENTERED
      , LEDGER
      , OBJECT_NUMBER
      , FISCAL_YEAR__YYYY
      , VALUE_TYPE
      , VERSION
      , COST_ELEMENT
      , ORIGIN
      , TRANSACTION
      , PARTNER_OBJECT
      , PARTNER_OBJECT_ALWAYS_FILLED
      , SOURCE_OBJECT_COST_CENTER_ACTIVITY_TYPE
      , TRADING_PARTNER_COMPANY_ID
      , TRADING_PARTNER_BUSINESS_AREA
      , TRANSACTION_CURRENCY
      , OBJECT_CURRENCY
      , BASE_UNIT_OF_MEASURE
      , UNIT_OF_MEASURE
      , ITEM_TEXT
      , REFERENCE_DOCUMENT_POSTING_ROW
      , DOCUMENT_ITEM_NUMBER
      , OPERATIVE_VERSION_POSTING_ROW
      , OFFSETTING_ACCOUNT_NUMBER
      , OFFSETTING_ACCOUNT_TYPE
      , PLANT
      , MATERIAL_NUMBER
      , REFERENCE_PURCHASE_ORDER_CATEGORY
      , PURCHASING_DOCUMENT_NUMBER
      , PURCHASING_DOCUMENT_ITEM_NUMBER
      , ACCOUNT_ASSIGNMENT_SEQUENTIAL_NUMBER
      , PERSONNEL_NUMBER
      , CO_AREA_CURRENCY_AMOUNT_CLASS
      , AUXILIARY_ACCOUNT_ASSIGNMENT_1
      , AUXILIARY_ACCOUNT_ASSIGNMENT_2
      , PROFITABILITY_SEGMENT_NUMBER
      , DEBIT_TYPE
      , COMPANY_CODE
      , BUSINESS_AREA
      , FUNCTIONAL_AREA
      , SEGMENT
      , PARTNER_COMPANY_CODE
      , PARTNER_FUNCTIONAL_AREA
      , PARTNER_SEGMENT
      , SETTLEMENT_DATE__YYYYMMDD
      , ALLOCATION_PRICE_STRATEGY
      , TIME_CREATED_GMT
      , FI_REFERENCE_DOCUMENT_POSTING_ITEM
      , JVA_PRODUCTION_MONTH
      , IS_DELETED
    FROM LOGIC_PB
)
---- FILTER LAYER ----

, FILTER_PB as (
    SELECT *
    FROM RENAME_PB
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM FILTER_PB
)

---- FINAL LAYER ----
SELECT
          CONTROLLING_LEDGER_ENTRY_HK
        , BKCC
        , REC_SRC
        , CLIENT
        , CONTROLLING_AREA
        , DOCUMENT_NUMBER
        , POSTING_ROW
        , PERIOD
        , TOTAL_VALUE_TRANSACTION_CURRENCY
        , TOTAL_VALUE_OBJECT_CURRENCY
        , TOTAL_VALUE_CO_AREA_CURRENCY
        , FIXED_VALUE_CO_AREA_CURRENCY
        , TOTAL_PRICE_VARIANCE_CO_AREA_CURRENCY
        , FIXED_PRICE_VARIANCE_CO_AREA_CURRENCY
        , TOTAL_QUANTITY
        , FIXED_QUANTITY
        , TOTAL_QUANTITY_ENTERED
        , FIXED_QUANTITY_ENTERED
        , LEDGER
        , OBJECT_NUMBER
        , FISCAL_YEAR__YYYY
        , VALUE_TYPE
        , VERSION
        , COST_ELEMENT
        , ORIGIN
        , TRANSACTION
        , PARTNER_OBJECT
        , PARTNER_OBJECT_ALWAYS_FILLED
        , SOURCE_OBJECT_COST_CENTER_ACTIVITY_TYPE
        , TRADING_PARTNER_COMPANY_ID
        , TRADING_PARTNER_BUSINESS_AREA
        , TRANSACTION_CURRENCY
        , OBJECT_CURRENCY
        , BASE_UNIT_OF_MEASURE
        , UNIT_OF_MEASURE
        , ITEM_TEXT
        , REFERENCE_DOCUMENT_POSTING_ROW
        , DOCUMENT_ITEM_NUMBER
        , OPERATIVE_VERSION_POSTING_ROW
        , OFFSETTING_ACCOUNT_NUMBER
        , OFFSETTING_ACCOUNT_TYPE
        , PLANT
        , MATERIAL_NUMBER
        , REFERENCE_PURCHASE_ORDER_CATEGORY
        , PURCHASING_DOCUMENT_NUMBER
        , PURCHASING_DOCUMENT_ITEM_NUMBER
        , ACCOUNT_ASSIGNMENT_SEQUENTIAL_NUMBER
        , PERSONNEL_NUMBER
        , CO_AREA_CURRENCY_AMOUNT_CLASS
        , AUXILIARY_ACCOUNT_ASSIGNMENT_1
        , AUXILIARY_ACCOUNT_ASSIGNMENT_2
        , PROFITABILITY_SEGMENT_NUMBER
        , DEBIT_TYPE
        , COMPANY_CODE
        , BUSINESS_AREA
        , FUNCTIONAL_AREA
        , SEGMENT
        , PARTNER_COMPANY_CODE
        , PARTNER_FUNCTIONAL_AREA
        , PARTNER_SEGMENT
        , SETTLEMENT_DATE__YYYYMMDD
        , ALLOCATION_PRICE_STRATEGY
        , TIME_CREATED_GMT
        , FI_REFERENCE_DOCUMENT_POSTING_ITEM
        , JVA_PRODUCTION_MONTH
        , IS_DELETED
FROM JOIN_RESULT
{% if is_incremental() %}
    WHERE CONTROLLING_LEDGER_ENTRY_HK NOT IN (
        SELECT CONTROLLING_LEDGER_ENTRY_HK 
        FROM {{ this }}
    )
    AND TO_DATE(FISCAL_YEAR__YYYY || LPAD(PERIOD::INTEGER, 2, '0') || '01', 'YYYYMMDD') 
        >= DATE_TRUNC('day', CURRENT_DATE() - 60)
{% endif %}


