---- SRC LAYER ----
WITH
SRC_P              as ( SELECT * FROM {{ ref('pit_statistical_key_figure_totals_current') }} as SRC  )

/*
SRC_P              as ( SELECT * FROM RAW_VAULT.PIT_STATISTICAL_KEY_FIGURE_TOTALS_CURRENT )
*/
---- LOGIC LAYER ----

, LOGIC_P as (
    SELECT
        STATISTICAL_KEY_FIGURE_TOTALS_HK
      , LEDGER_FOR_CONTROLLING_OBJECTS
      , OBJECT_NUM
      , FISCAL_YEAR__YYYY
      , VALUE_TYPE
      , VERSION
      , STATISTICAL_KEY_FIGURE
      , CO_KEY_SUBNUMBER
      , CO_BUSINESS_TRANSACTION
      , PERIOD_BLOCK
      , STATISTICAL_QTY_1
      , STATISTICAL_QTY_2
      , MAX_STATISTICAL_QTY_1
      , MAX_STATISTICAL_QTY_2
      , BKCC
      , REC_SRC
      , IS_DELETED
    FROM SRC_P
)
---- RENAME LAYER ----

, RENAME_P as (
    SELECT
        STATISTICAL_KEY_FIGURE_TOTALS_HK
      , LEDGER_FOR_CONTROLLING_OBJECTS
      , OBJECT_NUM
      , FISCAL_YEAR__YYYY
      , VALUE_TYPE
      , VERSION
      , STATISTICAL_KEY_FIGURE
      , CO_KEY_SUBNUMBER
      , CO_BUSINESS_TRANSACTION
      , PERIOD_BLOCK
      , STATISTICAL_QTY_1
      , STATISTICAL_QTY_2
      , MAX_STATISTICAL_QTY_1
      , MAX_STATISTICAL_QTY_2
      , BKCC
      , REC_SRC
      , IS_DELETED
    FROM LOGIC_P
)
---- FILTER LAYER ----

, FILTER_P as (
    SELECT *
    FROM RENAME_P
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM FILTER_P
)

---- FINAL LAYER ----
SELECT
          STATISTICAL_KEY_FIGURE_TOTALS_HK
        , LEDGER_FOR_CONTROLLING_OBJECTS
        , OBJECT_NUM
        , FISCAL_YEAR__YYYY
        , VALUE_TYPE
        , VERSION
        , STATISTICAL_KEY_FIGURE
        , CO_KEY_SUBNUMBER
        , CO_BUSINESS_TRANSACTION
        , PERIOD_BLOCK
        , STATISTICAL_QTY_1
        , STATISTICAL_QTY_2
        , MAX_STATISTICAL_QTY_1
        , MAX_STATISTICAL_QTY_2
        , BKCC
        , REC_SRC
        , IS_DELETED
FROM JOIN_RESULT
