---- SRC LAYER ----
WITH
SRC_PB_PIR         as ( SELECT BASE_UOM, BKCC, CONVERSION_ORDER_UOM_TO_BASE_UOM_D, CONVERSION_ORDER_UOM_TO_BASE_UOM_N, CONVERSION_PRICE_UOM_TO_ORDER_UOM_D, CONVERSION_PRICE_UOM_TO_ORDER_UOM_N, COUNTRY_OF_ORIGIN, CURRENCY_CODE, IS_DELETED, ITEM_BK, ITEM_HK, MANUFACTURER, NET_PRICE, ORDER_UOM, OVER_DELIVERY_TOLORANCE_LIMIT, PIR_CREATION_DATE__YYYYMMDD, PIR_DELETE_INDICATOR, PIR_PORG_CREATION_DATE__YYYYMMDD, PIR_PORG_DELETE_INDICATOR, PLANNED_DELIVERY_TIME_IN_DAYS, PLANT_BK, PRICE_UNIT, PRICE_UOM, PRICE_VALID_UNTIL__YYYYMMDD, PURCHASING_GROUP, PURCHASING_INFO_RECORD_BK, PURCHASING_INFO_RECORD_CATEGORY, PURCHASING_INFO_RECORD_ORG_HK, PURCHASING_ORG_BK, REC_SRC, SUPPLIER_BK, SUPPLIER_HK, UNDER_DELIVERY_TOLORANCE_LIMIT, VENDOR_MATERIAL_NUMBER FROM {{ ref('pb_purchase_info_record') }} as SRC 
                        /* View that selects columns from PIT Bridge */ )

/*
SRC_PB_PIR         as ( SELECT * FROM BUS_VAULT.pb_purchase_info_record )
*/
---- LOGIC LAYER ----

, LOGIC_PB_PIR as (
    SELECT
        PURCHASING_INFO_RECORD_ORG_HK
      , PURCHASING_INFO_RECORD_BK
      , ITEM_BK
      , ITEM_HK
      , SUPPLIER_BK
      , SUPPLIER_HK
      , PURCHASING_ORG_BK
      , PLANT_BK
      , PURCHASING_INFO_RECORD_CATEGORY
      , ORDER_UOM
      , BASE_UOM
      , CONVERSION_ORDER_UOM_TO_BASE_UOM_N
      , CONVERSION_ORDER_UOM_TO_BASE_UOM_D
      , COUNTRY_OF_ORIGIN
      , VENDOR_MATERIAL_NUMBER
      , MANUFACTURER
      , PURCHASING_GROUP
      , CURRENCY_CODE
      , PLANNED_DELIVERY_TIME_IN_DAYS
      , NET_PRICE
      , PRICE_UNIT
      , PRICE_UOM
      , CONVERSION_PRICE_UOM_TO_ORDER_UOM_N
      , CONVERSION_PRICE_UOM_TO_ORDER_UOM_D
      , PRICE_VALID_UNTIL__YYYYMMDD
      , OVER_DELIVERY_TOLORANCE_LIMIT
      , UNDER_DELIVERY_TOLORANCE_LIMIT
      , PIR_CREATION_DATE__YYYYMMDD
      , PIR_DELETE_INDICATOR
      , PIR_PORG_CREATION_DATE__YYYYMMDD
      , PIR_PORG_DELETE_INDICATOR
      , IS_DELETED
      , REC_SRC
      , BKCC
    FROM SRC_PB_PIR
)
---- RENAME LAYER ----

, RENAME_PB_PIR as (
    SELECT
        PURCHASING_INFO_RECORD_ORG_HK
      , PURCHASING_INFO_RECORD_BK
      , ITEM_BK
      , ITEM_HK
      , SUPPLIER_BK
      , SUPPLIER_HK
      , PURCHASING_ORG_BK
      , PLANT_BK
      , PURCHASING_INFO_RECORD_CATEGORY
      , ORDER_UOM
      , BASE_UOM
      , CONVERSION_ORDER_UOM_TO_BASE_UOM_N
      , CONVERSION_ORDER_UOM_TO_BASE_UOM_D
      , COUNTRY_OF_ORIGIN
      , VENDOR_MATERIAL_NUMBER
      , MANUFACTURER
      , PURCHASING_GROUP
      , CURRENCY_CODE
      , PLANNED_DELIVERY_TIME_IN_DAYS
      , NET_PRICE
      , PRICE_UNIT
      , PRICE_UOM
      , CONVERSION_PRICE_UOM_TO_ORDER_UOM_N
      , CONVERSION_PRICE_UOM_TO_ORDER_UOM_D
      , PRICE_VALID_UNTIL__YYYYMMDD
      , OVER_DELIVERY_TOLORANCE_LIMIT
      , UNDER_DELIVERY_TOLORANCE_LIMIT
      , PIR_CREATION_DATE__YYYYMMDD
      , PIR_DELETE_INDICATOR
      , PIR_PORG_CREATION_DATE__YYYYMMDD
      , PIR_PORG_DELETE_INDICATOR
      , IS_DELETED
      , REC_SRC
      , BKCC
    FROM LOGIC_PB_PIR
)
---- FILTER LAYER ----

, FILTER_PB_PIR as (
    SELECT *
    FROM RENAME_PB_PIR
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM FILTER_PB_PIR
)

---- FINAL LAYER ----
SELECT
          PURCHASING_INFO_RECORD_ORG_HK
        , PURCHASING_INFO_RECORD_BK
        , ITEM_BK
        , ITEM_HK
        , SUPPLIER_BK
        , SUPPLIER_HK
        , PURCHASING_ORG_BK
        , PLANT_BK
        , PURCHASING_INFO_RECORD_CATEGORY
        , ORDER_UOM
        , BASE_UOM
        , CONVERSION_ORDER_UOM_TO_BASE_UOM_N
        , CONVERSION_ORDER_UOM_TO_BASE_UOM_D
        , COUNTRY_OF_ORIGIN
        , VENDOR_MATERIAL_NUMBER
        , MANUFACTURER
        , PURCHASING_GROUP
        , CURRENCY_CODE
        , PLANNED_DELIVERY_TIME_IN_DAYS
        , NET_PRICE
        , PRICE_UNIT
        , PRICE_UOM
        , CONVERSION_PRICE_UOM_TO_ORDER_UOM_N
        , CONVERSION_PRICE_UOM_TO_ORDER_UOM_D
        , PRICE_VALID_UNTIL__YYYYMMDD
        , OVER_DELIVERY_TOLORANCE_LIMIT
        , UNDER_DELIVERY_TOLORANCE_LIMIT
        , PIR_CREATION_DATE__YYYYMMDD
        , PIR_DELETE_INDICATOR
        , PIR_PORG_CREATION_DATE__YYYYMMDD
        , PIR_PORG_DELETE_INDICATOR
        , IS_DELETED
        , REC_SRC
        , BKCC
FROM JOIN_RESULT
