---- SRC LAYER ----
WITH
SRC_PB             as ( SELECT BKCC, DEVICE_ID, MONTH_NUM, PERIOD_START_DATE_KEY, PERIOD_TYPE, QUARTER_NUM, REC_SRC, TELEMETRY_DATE, YEAR_NUM FROM {{ ref('pb_device_telemetry_coverage_period') }} as SRC  )

/*
SRC_PB             as ( SELECT * FROM BUS_VAULT.PB_DEVICE_TELEMETRY_COVERAGE_PERIOD )
*/
---- LOGIC LAYER ----

, LOGIC_PB as (
    SELECT
        DEVICE_ID
      , PERIOD_TYPE
      , PERIOD_START_DATE_KEY
      , YEAR_NUM
      , QUARTER_NUM
      , MONTH_NUM
      , BKCC
      , REC_SRC
      , TELEMETRY_DATE
    FROM SRC_PB
)
---- RENAME LAYER ----

, RENAME_PB as (
    SELECT
        DEVICE_ID
      , PERIOD_TYPE
      , PERIOD_START_DATE_KEY
      , YEAR_NUM
      , QUARTER_NUM
      , MONTH_NUM
      , BKCC
      , REC_SRC
      , TELEMETRY_DATE
    FROM LOGIC_PB
)
---- FILTER LAYER ----

, FILTER_PB as (
    SELECT *
    FROM RENAME_PB
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM FILTER_PB
)

---- FINAL LAYER ----
SELECT
          DEVICE_ID
        , PERIOD_TYPE
        , PERIOD_START_DATE_KEY
        , YEAR_NUM
        , QUARTER_NUM
        , MONTH_NUM
        , COUNT(DISTINCT TELEMETRY_DATE)                               as TELEMETRY_DAYS
        , CASE
  WHEN PERIOD_TYPE = 'MONTHLY' THEN
    CASE
      WHEN TO_DATE(TO_VARCHAR(PERIOD_START_DATE_KEY), 'YYYYMMDD') = DATE_TRUNC('MONTH', CURRENT_DATE())::DATE
        THEN DATEDIFF(DAY,
                      TO_DATE(TO_VARCHAR(PERIOD_START_DATE_KEY), 'YYYYMMDD'),
                      DATEADD(DAY, 1, CURRENT_DATE()))
      ELSE DATEDIFF(DAY,
                    TO_DATE(TO_VARCHAR(PERIOD_START_DATE_KEY), 'YYYYMMDD'),
                    DATEADD(DAY, 1, DATEADD(DAY, -1, DATEADD(MONTH, 1, TO_DATE(TO_VARCHAR(PERIOD_START_DATE_KEY), 'YYYYMMDD')))))
    END

  WHEN PERIOD_TYPE = 'QUARTERLY' THEN
    CASE
      WHEN TO_DATE(TO_VARCHAR(PERIOD_START_DATE_KEY), 'YYYYMMDD') = DATE_TRUNC('QUARTER', CURRENT_DATE())::DATE
        THEN DATEDIFF(DAY,
                      TO_DATE(TO_VARCHAR(PERIOD_START_DATE_KEY), 'YYYYMMDD'),
                      DATEADD(DAY, 1, CURRENT_DATE()))
      ELSE DATEDIFF(DAY,
                    TO_DATE(TO_VARCHAR(PERIOD_START_DATE_KEY), 'YYYYMMDD'),
                    DATEADD(DAY, 1, DATEADD(DAY, -1, DATEADD(QUARTER, 1, TO_DATE(TO_VARCHAR(PERIOD_START_DATE_KEY), 'YYYYMMDD')))))
    END

  WHEN PERIOD_TYPE = 'YEARLY' THEN
    CASE
      WHEN TO_DATE(TO_VARCHAR(PERIOD_START_DATE_KEY), 'YYYYMMDD') = DATE_TRUNC('YEAR', CURRENT_DATE())::DATE
        THEN DATEDIFF(DAY,
                      TO_DATE(TO_VARCHAR(PERIOD_START_DATE_KEY), 'YYYYMMDD'),
                      DATEADD(DAY, 1, CURRENT_DATE()))
      ELSE 365
    END
  ELSE NULL
END as DAYS_IN_PERIOD
        , TELEMETRY_DAYS / NULLIF(DAYS_IN_PERIOD,0)                    as TELEMETRY_DAYS_PERCENT
        , MIN(BKCC)                                                    as BKCC
        , MIN(REC_SRC)                                                 as REC_SRC
        , CASE WHEN TELEMETRY_DAYS_PERCENT > 0.90 THEN 1 ELSE 0 END    as IS_TELEMETRY_QUALIFIED
FROM JOIN_RESULT
GROUP BY 
DEVICE_ID,
PERIOD_TYPE,
PERIOD_START_DATE_KEY,
YEAR_NUM,
QUARTER_NUM,
MONTH_NUM