---- SRC LAYER ----
WITH
SRC_po             as ( SELECT BOM_BK, REC_SRC, BKCC, BOM_HK, CHANGE_MASTER_BK, CHANGE_MASTER_HK, ENTERED_QTY, FIXED_FOREIGN_PRICE, GL_ACCOUNT_NUMBER_BK, GL_ACCOUNT_NUMBER_HK, GOODS_STORAGE_LOCATION_BK, GOODS_STORAGE_LOCATION_HK, ITEM_ASSEMBLY_BK, ITEM_ASSEMBLY_HK, ITEM_BK, ITEM_HK, LNK_DEPENDENCY_RESERVATION_HK, LOT_SIZE, LOT_UNIT_PRICE, OPEN_QTY, ORDER_HEADER_BK, ORDER_HEADER_HK, ORDER_LINE_BK, ORDER_LINE_HK, PLANNED_ORDER_BK, PLANNED_ORDER_HK, PLANT_BK, PLANT_HK, PO_HEADER_BK, PO_HEADER_HK, PO_ITEM_BK, PO_ITEM_HK, PO_LINE_BK, PO_LINE_HK, PRODUCTION_ORDER_BK, PRODUCTION_ORDER_HK, PURCHASE_REQUISITION_BK, PURCHASE_REQUISITION_HK, PURCHASE_REQUISITION_ITEM_BK, PURCHASE_REQUISITION_ITEM_HK, REQUIRED_QTY, RESERVATION_BK, RESERVATION_HK, RESERVATION_LINE_BK, RESERVATION_LINE_HK, ROUTING_BK, ROUTING_HK, STOCK_CATEGORY, STORAGE_BIN_BK, STORAGE_BIN_HK, UOM_BK, UOM_HK, VALUE_WITHDRAWN, WITHDRAWN_QTY FROM {{ ref('pb_reservation') }} as SRC  )

/*
SRC_po             as ( SELECT * FROM BUS_VAULT.pb_reservation )
*/
---- LOGIC LAYER ----

, LOGIC_po as (
    SELECT
        LNK_DEPENDENCY_RESERVATION_HK
      , RESERVATION_HK
      , RESERVATION_BK
      , RESERVATION_LINE_HK
      , RESERVATION_LINE_BK
      , PLANT_HK
      , PLANT_BK
      , ITEM_HK
      , ITEM_BK
      , ITEM_ASSEMBLY_HK
      , ITEM_ASSEMBLY_BK
      , PLANNED_ORDER_HK
      , PLANNED_ORDER_BK
      , PURCHASE_REQUISITION_HK
      , PURCHASE_REQUISITION_BK
      , PURCHASE_REQUISITION_ITEM_HK
      , PURCHASE_REQUISITION_ITEM_BK
      , PO_HEADER_HK
      , PO_HEADER_BK
      , PO_ITEM_HK
      , PO_ITEM_BK
      , PO_LINE_HK
      , PO_LINE_BK
      , ROUTING_HK
      , ROUTING_BK
      , CHANGE_MASTER_HK
      , CHANGE_MASTER_BK
      , GOODS_STORAGE_LOCATION_HK
      , GOODS_STORAGE_LOCATION_BK
      , PRODUCTION_ORDER_HK
      , PRODUCTION_ORDER_BK
      , STORAGE_BIN_HK
      , STORAGE_BIN_BK
      , BOM_HK
      , BOM_BK
      , UOM_HK
      , UOM_BK
      , ORDER_HEADER_HK
      , ORDER_HEADER_BK
      , ORDER_LINE_HK
      , ORDER_LINE_BK
      , GL_ACCOUNT_NUMBER_HK
      , GL_ACCOUNT_NUMBER_BK
      , REQUIRED_QTY
      , ENTERED_QTY
      , VALUE_WITHDRAWN
      , WITHDRAWN_QTY
      , OPEN_QTY
      , LOT_UNIT_PRICE
      , FIXED_FOREIGN_PRICE
      , LOT_SIZE
      , STOCK_CATEGORY
      , REC_SRC
      , BKCC
    FROM SRC_po
)
---- RENAME LAYER ----

, RENAME_po as (
    SELECT
        LNK_DEPENDENCY_RESERVATION_HK
      , RESERVATION_HK
      , RESERVATION_BK
      , RESERVATION_LINE_HK
      , RESERVATION_LINE_BK
      , PLANT_HK
      , PLANT_BK
      , ITEM_HK
      , ITEM_BK
      , ITEM_ASSEMBLY_HK
      , ITEM_ASSEMBLY_BK
      , PLANNED_ORDER_HK
      , PLANNED_ORDER_BK
      , PURCHASE_REQUISITION_HK
      , PURCHASE_REQUISITION_BK
      , PURCHASE_REQUISITION_ITEM_HK
      , PURCHASE_REQUISITION_ITEM_BK
      , PO_HEADER_HK
      , PO_HEADER_BK
      , PO_ITEM_HK
      , PO_ITEM_BK
      , PO_LINE_HK
      , PO_LINE_BK
      , ROUTING_HK
      , ROUTING_BK
      , CHANGE_MASTER_HK
      , CHANGE_MASTER_BK
      , GOODS_STORAGE_LOCATION_HK
      , GOODS_STORAGE_LOCATION_BK
      , PRODUCTION_ORDER_HK
      , PRODUCTION_ORDER_BK
      , STORAGE_BIN_HK
      , STORAGE_BIN_BK
      , BOM_HK
      , BOM_BK
      , UOM_HK
      , UOM_BK
      , ORDER_HEADER_HK
      , ORDER_HEADER_BK
      , ORDER_LINE_HK
      , ORDER_LINE_BK
      , GL_ACCOUNT_NUMBER_HK
      , GL_ACCOUNT_NUMBER_BK
      , REQUIRED_QTY
      , ENTERED_QTY
      , VALUE_WITHDRAWN
      , WITHDRAWN_QTY
      , OPEN_QTY
      , LOT_UNIT_PRICE
      , FIXED_FOREIGN_PRICE
      , LOT_SIZE
      , STOCK_CATEGORY
      , REC_SRC
      , BKCC
    FROM LOGIC_po
)
---- FILTER LAYER ----

, FILTER_po as (
    SELECT *
    FROM RENAME_po
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM FILTER_po
)

---- FINAL LAYER ----
SELECT
          LNK_DEPENDENCY_RESERVATION_HK
        , RESERVATION_HK
        , RESERVATION_BK
        , RESERVATION_LINE_HK
        , RESERVATION_LINE_BK
        , PLANT_HK
        , PLANT_BK
        , ITEM_HK
        , ITEM_BK
        , ITEM_ASSEMBLY_HK
        , ITEM_ASSEMBLY_BK
        , PLANNED_ORDER_HK
        , PLANNED_ORDER_BK
        , PURCHASE_REQUISITION_HK
        , PURCHASE_REQUISITION_BK
        , PURCHASE_REQUISITION_ITEM_HK
        , PURCHASE_REQUISITION_ITEM_BK
        , PO_HEADER_HK
        , PO_HEADER_BK
        , PO_ITEM_HK
        , PO_ITEM_BK
        , PO_LINE_HK
        , PO_LINE_BK
        , ROUTING_HK
        , ROUTING_BK
        , CHANGE_MASTER_HK
        , CHANGE_MASTER_BK
        , GOODS_STORAGE_LOCATION_HK
        , GOODS_STORAGE_LOCATION_BK
        , PRODUCTION_ORDER_HK
        , PRODUCTION_ORDER_BK
        , STORAGE_BIN_HK
        , STORAGE_BIN_BK
        , BOM_HK
        , BOM_BK
        , UOM_HK
        , UOM_BK
        , ORDER_HEADER_HK
        , ORDER_HEADER_BK
        , ORDER_LINE_HK
        , ORDER_LINE_BK
        , GL_ACCOUNT_NUMBER_HK
        , GL_ACCOUNT_NUMBER_BK
        , REQUIRED_QTY
        , ENTERED_QTY
        , VALUE_WITHDRAWN
        , WITHDRAWN_QTY
        , OPEN_QTY
        , LOT_UNIT_PRICE
        , FIXED_FOREIGN_PRICE
        , LOT_SIZE
        , STOCK_CATEGORY
        , REC_SRC
        , BKCC
FROM JOIN_RESULT