---- SRC LAYER ----
WITH
SRC_pb             as ( SELECT BKCC, BUSINESS_UNIT, CAL_MONTH, CAL_YEAR, CATEGORY_LEADER_NAME, COUNTRY_OF_ORIGIN, DIRECTOR_NAME, DOCUMENT_TYPE, DRVD_OPCO, FBIN_CATEGORY_I, FBIN_CATEGORY_II, FBIN_CATEGORY_III, ITEM_BK, ITEM_HK, LEGAL_ENTITY_BK, LEGAL_ENTITY_HK, NET_PRICE, OPCO_CATEGORY, OPCO_ITEM, OPEN_PO_HK, ORDER_NUMBER, ORDER_QTY, PAYMENT_TERMS, PLANT_BK, PLAN_CREATION_DATE, PO_CREATION_DATE, PO_HEADER_DEL_IND, PO_HEADER_HK, PO_HEADER_ID, PO_ITEM_HK, PO_ITEM_UOM, PO_LINE_NUMBER, PO_SCHEDULE_LINE_NUMBER, PURCHASING_ORG_HK, PURCHASING_RECORD_HK, RECEIVED_QTY, REC_SRC, SCHEDULE_LINE_DELIVERY_DATE, SCHEDULE_LINE_DELIVERY_DATE_BK, SOURCE, SPEND, SUPPLIER_HK, SUPPLIER_NAME_CHILD, SUPPLIER_NAME_PARENT, SUPPLIER_NUMBER_CHILD, SUPPLIER_NUMBER_PARENT, TRANSACTION_ID, VOLUME FROM {{ ref('pb_open_po_lines_spend') }} as SRC  )

/*
SRC_pb             as ( SELECT * FROM BUS_VAULT.pb_open_po_lines_spend )
*/
---- LOGIC LAYER ----

, LOGIC_pb as (
    SELECT
        OPEN_PO_HK
      , PO_HEADER_ID
      , PO_LINE_NUMBER
      , PO_SCHEDULE_LINE_NUMBER
      , TO_CHAR(PLAN_CREATION_DATE, 'YYYYMMDD')::INTEGER             as                       PLAN_CREATION_DATE__YYYYMMDD
      , PLAN_CREATION_DATE
      , ORDER_NUMBER
      , TRANSACTION_ID
      , TO_CHAR(PO_CREATION_DATE, 'YYYYMMDD')::INTEGER               as                         PO_CREATION_DATE__YYYYMMDD
      , PO_CREATION_DATE
      , TO_CHAR(SCHEDULE_LINE_DELIVERY_DATE, 'YYYYMMDD')::INTEGER    as                    SCHEDULE_LINE_DELIVERY_DATE_KEY
      , SCHEDULE_LINE_DELIVERY_DATE
      , PO_ITEM_UOM
      , ORDER_QTY
      , RECEIVED_QTY
      , NET_PRICE
      , VOLUME
      , SPEND
      , CAL_YEAR
      , CAL_MONTH
      , BUSINESS_UNIT
      , DRVD_OPCO
      , OPCO_ITEM
      , SUPPLIER_NUMBER_PARENT
      , SUPPLIER_NAME_PARENT
      , SUPPLIER_NUMBER_CHILD
      , SUPPLIER_NAME_CHILD
      , COUNTRY_OF_ORIGIN
      , PO_HEADER_DEL_IND
      , PAYMENT_TERMS
      , DOCUMENT_TYPE
      , OPCO_CATEGORY
      , CATEGORY_LEADER_NAME
      , DIRECTOR_NAME
      , FBIN_CATEGORY_I
      , FBIN_CATEGORY_II
      , FBIN_CATEGORY_III
      , ITEM_BK
      , PLANT_BK
      , LEGAL_ENTITY_BK
      , SOURCE
      , TO_CHAR(SCHEDULE_LINE_DELIVERY_DATE_BK, 'YYYYMMDD')::INTEGER as              SCHEDULE_LINE_DELIVERY_DATE__YYYYMMDD
      , SCHEDULE_LINE_DELIVERY_DATE_BK
      , PO_HEADER_HK
      , PO_ITEM_HK
      , ITEM_HK
      , SUPPLIER_HK
      , LEGAL_ENTITY_HK
      , PURCHASING_RECORD_HK
      , PURCHASING_ORG_HK
      , REC_SRC
      , BKCC
    FROM SRC_pb
)
---- RENAME LAYER ----

, RENAME_pb as (
    SELECT
        OPEN_PO_HK
      , PO_HEADER_ID
      , PO_LINE_NUMBER
      , PO_SCHEDULE_LINE_NUMBER
      , PLAN_CREATION_DATE__YYYYMMDD
      , PLAN_CREATION_DATE
      , ORDER_NUMBER
      , TRANSACTION_ID
      , PO_CREATION_DATE__YYYYMMDD
      , PO_CREATION_DATE
      , SCHEDULE_LINE_DELIVERY_DATE_KEY
      , SCHEDULE_LINE_DELIVERY_DATE
      , PO_ITEM_UOM
      , ORDER_QTY
      , RECEIVED_QTY
      , NET_PRICE
      , VOLUME
      , SPEND
      , CAL_YEAR
      , CAL_MONTH
      , BUSINESS_UNIT
      , DRVD_OPCO
      , OPCO_ITEM
      , SUPPLIER_NUMBER_PARENT
      , SUPPLIER_NAME_PARENT
      , SUPPLIER_NUMBER_CHILD
      , SUPPLIER_NAME_CHILD
      , COUNTRY_OF_ORIGIN
      , PO_HEADER_DEL_IND
      , PAYMENT_TERMS
      , DOCUMENT_TYPE
      , OPCO_CATEGORY
      , CATEGORY_LEADER_NAME
      , DIRECTOR_NAME
      , FBIN_CATEGORY_I
      , FBIN_CATEGORY_II
      , FBIN_CATEGORY_III
      , ITEM_BK
      , PLANT_BK
      , LEGAL_ENTITY_BK
      , SOURCE
      , SCHEDULE_LINE_DELIVERY_DATE__YYYYMMDD
      , SCHEDULE_LINE_DELIVERY_DATE_BK
      , PO_HEADER_HK
      , PO_ITEM_HK
      , ITEM_HK
      , SUPPLIER_HK
      , LEGAL_ENTITY_HK
      , PURCHASING_RECORD_HK
      , PURCHASING_ORG_HK
      , REC_SRC
      , BKCC
    FROM LOGIC_pb
)
---- FILTER LAYER ----

, FILTER_pb as (
    SELECT *
    FROM RENAME_pb
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM FILTER_pb
)

---- FINAL LAYER ----
SELECT
          OPEN_PO_HK
        , PO_HEADER_ID
        , PO_LINE_NUMBER
        , PO_SCHEDULE_LINE_NUMBER
        , PLAN_CREATION_DATE__YYYYMMDD
        , ORDER_NUMBER
        , TRANSACTION_ID
        , PO_CREATION_DATE__YYYYMMDD
        , SCHEDULE_LINE_DELIVERY_DATE_KEY
        , PO_ITEM_UOM
        , ORDER_QTY
        , RECEIVED_QTY
        , NET_PRICE
        , VOLUME
        , SPEND
        , CAL_YEAR
        , CAL_MONTH
        , BUSINESS_UNIT
        , DRVD_OPCO
        , OPCO_ITEM
        , SUPPLIER_NUMBER_PARENT
        , SUPPLIER_NAME_PARENT
        , SUPPLIER_NUMBER_CHILD
        , SUPPLIER_NAME_CHILD
        , COUNTRY_OF_ORIGIN
        , PO_HEADER_DEL_IND
        , PAYMENT_TERMS
        , DOCUMENT_TYPE
        , OPCO_CATEGORY
        , CATEGORY_LEADER_NAME
        , DIRECTOR_NAME
        , FBIN_CATEGORY_I
        , FBIN_CATEGORY_II
        , FBIN_CATEGORY_III
        , ITEM_BK
        , PLANT_BK
        , LEGAL_ENTITY_BK
        , SOURCE
        , SCHEDULE_LINE_DELIVERY_DATE__YYYYMMDD
        , PO_HEADER_HK
        , PO_ITEM_HK
        , ITEM_HK
        , SUPPLIER_HK
        , LEGAL_ENTITY_HK
        , PURCHASING_RECORD_HK
        , PURCHASING_ORG_HK
        , REC_SRC
        , BKCC
FROM JOIN_RESULT
/* Descriptive Attributes are also now part of the fact */