---- SRC LAYER ----
WITH
SRC_D              as ( SELECT ACTUAL_CHECK_IN_DATE__YYYYMMDD, ACTUAL_LOADING_END_DATE__YYYYMMDD, ACTUAL_LOADING_START_DATE__YYYYMMDD, ACTUAL_SHIPMENT_COMPLETION__YYYYMMDD, ACTUAL_SHIPMENT_END_DATE__YYYYMMDD, ACTUAL_SHIPMENT_START_DATE__YYYYMMDD, BKCC, CARRIER_ID, DELIVERY_BK, DELIVERY_GROSS_WEIGHT_KG, DELIVERY_HK, DELIVERY_ID, DELIVERY_NET_WEIGHT_KG, DELIVERY_VOLUME, PLANNED_CHECK_IN_DATE__YYYYMMDD, PLANNED_SHIPMENT_COMPLETION__YYYYMMDD, PLANNED_SHIPMENT_END_DATE__YYYYMMDD, PLANNED_SHIPMENT_START_DATE__YYYYMMDD, PLAN_LOADING_END_DATE__YYYYMMDD, PLAN_LOADING_START_DATE__YYYYMMDD, REC_SRC, REF_TOTAL_SHIPMENT_DISTANCE, REF_TOTAL_SHIPMENT_WEIGHT_UNIT, SHIPMENT_BK, SHIPMENT_HK, SHIPMENT_ID, SHIPMENT_ITEM_ID, SHIPMENT_TYPE FROM {{ ref('pb_shipment_details') }} as SRC  )

/*
SRC_D              as ( SELECT * FROM BUS_VAULT.pb_shipment_details )
*/
---- LOGIC LAYER ----

, LOGIC_D as (
    SELECT
        REC_SRC
      , DELIVERY_HK
      , SHIPMENT_HK
      , DELIVERY_BK
      , SHIPMENT_BK
      , DELIVERY_ID
      , SHIPMENT_ITEM_ID
      , DELIVERY_GROSS_WEIGHT_KG
      , DELIVERY_NET_WEIGHT_KG
      , DELIVERY_VOLUME
      , SHIPMENT_ID
      , CARRIER_ID
      , SHIPMENT_TYPE
      , PLANNED_CHECK_IN_DATE__YYYYMMDD
      , ACTUAL_CHECK_IN_DATE__YYYYMMDD
      , PLAN_LOADING_START_DATE__YYYYMMDD
      , PLAN_LOADING_END_DATE__YYYYMMDD
      , ACTUAL_LOADING_START_DATE__YYYYMMDD
      , ACTUAL_LOADING_END_DATE__YYYYMMDD
      , PLANNED_SHIPMENT_COMPLETION__YYYYMMDD
      , ACTUAL_SHIPMENT_COMPLETION__YYYYMMDD
      , PLANNED_SHIPMENT_START_DATE__YYYYMMDD
      , PLANNED_SHIPMENT_END_DATE__YYYYMMDD
      , ACTUAL_SHIPMENT_START_DATE__YYYYMMDD
      , ACTUAL_SHIPMENT_END_DATE__YYYYMMDD
      , REF_TOTAL_SHIPMENT_WEIGHT_UNIT
      , REF_TOTAL_SHIPMENT_DISTANCE
      , BKCC
    FROM SRC_D
)
---- RENAME LAYER ----

, RENAME_D as (
    SELECT
        REC_SRC
      , DELIVERY_HK
      , SHIPMENT_HK
      , DELIVERY_BK
      , SHIPMENT_BK
      , DELIVERY_ID
      , SHIPMENT_ITEM_ID
      , DELIVERY_GROSS_WEIGHT_KG
      , DELIVERY_NET_WEIGHT_KG
      , DELIVERY_VOLUME
      , SHIPMENT_ID
      , CARRIER_ID
      , SHIPMENT_TYPE
      , PLANNED_CHECK_IN_DATE__YYYYMMDD
      , ACTUAL_CHECK_IN_DATE__YYYYMMDD
      , PLAN_LOADING_START_DATE__YYYYMMDD
      , PLAN_LOADING_END_DATE__YYYYMMDD
      , ACTUAL_LOADING_START_DATE__YYYYMMDD
      , ACTUAL_LOADING_END_DATE__YYYYMMDD
      , PLANNED_SHIPMENT_COMPLETION__YYYYMMDD
      , ACTUAL_SHIPMENT_COMPLETION__YYYYMMDD
      , PLANNED_SHIPMENT_START_DATE__YYYYMMDD
      , PLANNED_SHIPMENT_END_DATE__YYYYMMDD
      , ACTUAL_SHIPMENT_START_DATE__YYYYMMDD
      , ACTUAL_SHIPMENT_END_DATE__YYYYMMDD
      , REF_TOTAL_SHIPMENT_WEIGHT_UNIT
      , REF_TOTAL_SHIPMENT_DISTANCE
      , BKCC
    FROM LOGIC_D
)
---- FILTER LAYER ----

, FILTER_D as (
    SELECT *
    FROM RENAME_D
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM FILTER_D
)

---- FINAL LAYER ----
SELECT
          REC_SRC
        , DELIVERY_HK
        , SHIPMENT_HK
        , DELIVERY_BK
        , SHIPMENT_BK
        , DELIVERY_ID
        , SHIPMENT_ITEM_ID
        , DELIVERY_GROSS_WEIGHT_KG
        , DELIVERY_NET_WEIGHT_KG
        , DELIVERY_VOLUME
        , SHIPMENT_ID
        , CARRIER_ID
        , SHIPMENT_TYPE
        , PLANNED_CHECK_IN_DATE__YYYYMMDD
        , ACTUAL_CHECK_IN_DATE__YYYYMMDD
        , PLAN_LOADING_START_DATE__YYYYMMDD
        , PLAN_LOADING_END_DATE__YYYYMMDD
        , ACTUAL_LOADING_START_DATE__YYYYMMDD
        , ACTUAL_LOADING_END_DATE__YYYYMMDD
        , PLANNED_SHIPMENT_COMPLETION__YYYYMMDD
        , ACTUAL_SHIPMENT_COMPLETION__YYYYMMDD
        , PLANNED_SHIPMENT_START_DATE__YYYYMMDD
        , PLANNED_SHIPMENT_END_DATE__YYYYMMDD
        , ACTUAL_SHIPMENT_START_DATE__YYYYMMDD
        , ACTUAL_SHIPMENT_END_DATE__YYYYMMDD
        , REF_TOTAL_SHIPMENT_WEIGHT_UNIT
        , REF_TOTAL_SHIPMENT_DISTANCE
        , BKCC
FROM JOIN_RESULT
