---- SRC LAYER ----
WITH
SRC_pb as ( 
    SELECT 
         SEQ_ID
        ,REC_SRC
        ,BKCC
        ,CHANNEL_ITEM_INVENTORY_LHK
        ,ASIN
        ,REPORT_DATE__YYYYMMDD
        ,AGED_90_PLUS_COST_AMT
        ,AGED_90_PLUS_CURRENCY_CODE
        ,AGED_90_PLUS_UNITS
        ,AVG_VENDOR_LEAD_TIME_DAYS
        ,NET_RECEIVED_COST_AMT
        ,NET_RECEIVED_CURRENCY_CODE
        ,NET_RECEIVED_INVENTORY_UNITS
        ,OPEN_PO_UNITS
        ,UNFILLED_CUSTOMER_ORDERED_UNITS
        ,SELLABLE_ON_HAND_INVENTORY_COST_AMOUNT
        ,SELLABLE_OH_UNITS
        ,SELLABLE_ON_HAND_INVENTORY_COST_CURRENCY_CODE
        ,UNHEALTHY_COST_AMT
        ,UNHEALTHY_UNITS
        ,UNHEALTHY_INVENTORY_COST_CURRENCY_CODE
        ,UNSELLABLE_ON_HAND_INVENTORY_COST_AMOUNT
        ,UNSELLABLE_OH_UNITS
        ,UNSELLABLE_INVENTORY_COST_CURRENCY_CODE
        ,ITEM_HK
        ,ITEM_BK
        ,STORE_HK
        ,STORE_BK
        ,IS_DELETED
    FROM {{ ref('pb_channel_item_inventory') }} 
)

/*
SRC_pb             as ( SELECT * FROM BUS_VAULT.pb_channel_item_inventory )
*/

---- LOGIC LAYER ----

, LOGIC_pb as (
    SELECT
         SEQ_ID
        ,REC_SRC
        ,BKCC
        ,CHANNEL_ITEM_INVENTORY_LHK
        ,ASIN
        ,REPORT_DATE__YYYYMMDD
        ,AGED_90_PLUS_COST_AMT
        ,AGED_90_PLUS_CURRENCY_CODE
        ,AGED_90_PLUS_UNITS
        ,AVG_VENDOR_LEAD_TIME_DAYS
        ,NET_RECEIVED_COST_AMT
        ,NET_RECEIVED_CURRENCY_CODE
        ,NET_RECEIVED_INVENTORY_UNITS
        ,OPEN_PO_UNITS
        ,UNFILLED_CUSTOMER_ORDERED_UNITS
        ,SELLABLE_ON_HAND_INVENTORY_COST_AMOUNT
        ,SELLABLE_OH_UNITS
        ,SELLABLE_ON_HAND_INVENTORY_COST_CURRENCY_CODE
        ,UNHEALTHY_COST_AMT
        ,UNHEALTHY_UNITS
        ,UNHEALTHY_INVENTORY_COST_CURRENCY_CODE
        ,UNSELLABLE_ON_HAND_INVENTORY_COST_AMOUNT
        ,UNSELLABLE_OH_UNITS
        ,UNSELLABLE_INVENTORY_COST_CURRENCY_CODE
        ,ITEM_HK
        ,ITEM_BK
        ,STORE_HK
        ,STORE_BK
        ,IS_DELETED
    FROM SRC_pb
)

---- RENAME LAYER ----

, RENAME_pb as ( 
    SELECT 
         SEQ_ID
        ,REC_SRC
        ,BKCC
        ,CHANNEL_ITEM_INVENTORY_LHK
        ,ASIN
        ,REPORT_DATE__YYYYMMDD
        ,AGED_90_PLUS_COST_AMT
        ,AGED_90_PLUS_CURRENCY_CODE
        ,AGED_90_PLUS_UNITS
        ,AVG_VENDOR_LEAD_TIME_DAYS
        ,NET_RECEIVED_COST_AMT
        ,NET_RECEIVED_CURRENCY_CODE
        ,NET_RECEIVED_INVENTORY_UNITS
        ,OPEN_PO_UNITS
        ,UNFILLED_CUSTOMER_ORDERED_UNITS
        ,SELLABLE_ON_HAND_INVENTORY_COST_AMOUNT
        ,SELLABLE_OH_UNITS
        ,SELLABLE_ON_HAND_INVENTORY_COST_CURRENCY_CODE
        ,UNHEALTHY_COST_AMT
        ,UNHEALTHY_UNITS
        ,UNHEALTHY_INVENTORY_COST_CURRENCY_CODE
        ,UNSELLABLE_ON_HAND_INVENTORY_COST_AMOUNT
        ,UNSELLABLE_OH_UNITS
        ,UNSELLABLE_INVENTORY_COST_CURRENCY_CODE
        ,ITEM_HK
        ,ITEM_BK
        ,STORE_HK
        ,STORE_BK
        ,IS_DELETED
    FROM LOGIC_pb 
)

---- FILTER LAYER ----

, FILTER_pb as (
    SELECT *
    FROM RENAME_pb
)

---- JOIN LAYER ----

, JOIN_RESULT as (
    SELECT *
    FROM FILTER_pb
)

---- FINAL LAYER ----

SELECT
      SEQ_ID
    , REC_SRC
    , BKCC
    , CHANNEL_ITEM_INVENTORY_LHK
    , ASIN
    , REPORT_DATE__YYYYMMDD
    , AGED_90_PLUS_COST_AMT
    , AGED_90_PLUS_CURRENCY_CODE
    , AGED_90_PLUS_UNITS
    , AVG_VENDOR_LEAD_TIME_DAYS
    , NET_RECEIVED_COST_AMT
    , NET_RECEIVED_CURRENCY_CODE
    , NET_RECEIVED_INVENTORY_UNITS
    , OPEN_PO_UNITS
    , UNFILLED_CUSTOMER_ORDERED_UNITS
    , SELLABLE_ON_HAND_INVENTORY_COST_AMOUNT
    , SELLABLE_OH_UNITS
    , SELLABLE_ON_HAND_INVENTORY_COST_CURRENCY_CODE
    , UNHEALTHY_COST_AMT
    , UNHEALTHY_UNITS
    , UNHEALTHY_INVENTORY_COST_CURRENCY_CODE
    , UNSELLABLE_ON_HAND_INVENTORY_COST_AMOUNT
    , UNSELLABLE_OH_UNITS
    , UNSELLABLE_INVENTORY_COST_CURRENCY_CODE
    , ITEM_HK
    , ITEM_BK
    , STORE_HK
    , STORE_BK
    , IS_DELETED 
FROM JOIN_RESULT