{{
  config(
    materialized = 'view'
  )
}}
---- SRC LAYER ----
WITH
SRC_P              as ( SELECT * FROM {{ ref('pb_recurring_revenue') }} as SRC )
/*
SRC_P              as ( SELECT * FROM BUS_VAULT.PB_RECURRING_REVENUE )
*/
---- LOGIC LAYER ----
, LOGIC_P as (
    SELECT
        RECURRING_REVENUE_BK
      , SALES_ORDER_LINE_HK
      , SALES_ORDER_LINE_BK
      , SALES_ORDER_HEADER_HK
      , SALES_ORDER_NUMBER
      , SALES_ORDER_LINE_NUMBER
      , CUSTOMER_BK
      , SUBSCRIPTION_ID
      , SUBSCRIPTION_SOURCE
      , ITEM_BK
      , SALES_ORDER_ITEM_DESC
      , PRODUCT_NUMBER
      , SALES_ORDER_DOCUMENT_TYPE
      , BILLING_TYPE
      , SALES_ORGANIZATION
      , DISTRIBUTION_CHANNEL
      , DIVISION
      , SALES_ORDER_CURRENCY
      , NET_SALES_REVENUE
      , COST_OF_GOODS_SOLD
      , GROSS_PRICE
      , ORDER_QUANTITY
      , STANDARD_COST
      , RECURRING_REVENUE
      , SUBSCRIPTION_START_DATE_KEY
      , BILLING_DATE_KEY
      , REVENUE_MONTH_DATE_KEY
      , REVENUE_MONTH_END_DATE_KEY
      , PERIOD_NUMBER
      , FISCAL_MONTH__YYYYMM
      , SUBSCRIPTION_STATUS
      , REC_SRC
      , BKCC
      , COPA_REC_SRC
    FROM SRC_P
)
---- RENAME LAYER ----
, RENAME_P as (
    SELECT
        RECURRING_REVENUE_BK
      , SALES_ORDER_LINE_HK
      , SALES_ORDER_LINE_BK
      , SALES_ORDER_HEADER_HK
      , SALES_ORDER_NUMBER
      , SALES_ORDER_LINE_NUMBER
      , CUSTOMER_BK
      , SUBSCRIPTION_ID
      , SUBSCRIPTION_SOURCE
      , ITEM_BK
      , SALES_ORDER_ITEM_DESC
      , PRODUCT_NUMBER
      , SALES_ORDER_DOCUMENT_TYPE
      , BILLING_TYPE
      , SALES_ORGANIZATION
      , DISTRIBUTION_CHANNEL
      , DIVISION
      , SALES_ORDER_CURRENCY
      , NET_SALES_REVENUE
      , COST_OF_GOODS_SOLD
      , GROSS_PRICE
      , ORDER_QUANTITY
      , STANDARD_COST
      , RECURRING_REVENUE
      , SUBSCRIPTION_START_DATE_KEY
      , BILLING_DATE_KEY
      , REVENUE_MONTH_DATE_KEY
      , REVENUE_MONTH_END_DATE_KEY
      , PERIOD_NUMBER
      , FISCAL_MONTH__YYYYMM
      , SUBSCRIPTION_STATUS
      , REC_SRC
      , BKCC
      , COPA_REC_SRC
    FROM LOGIC_P
)
---- FILTER LAYER ----
, FILTER_P as (
    SELECT *
    FROM RENAME_P
)
---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM FILTER_P
)
---- FINAL LAYER ----
SELECT
        RECURRING_REVENUE_BK
      , SALES_ORDER_LINE_HK
      , SALES_ORDER_LINE_BK
      , SALES_ORDER_HEADER_HK
      , SALES_ORDER_NUMBER
      , SALES_ORDER_LINE_NUMBER
      , CUSTOMER_BK
      , SUBSCRIPTION_ID
      , SUBSCRIPTION_SOURCE
      , ITEM_BK
      , SALES_ORDER_ITEM_DESC
      , PRODUCT_NUMBER
      , SALES_ORDER_DOCUMENT_TYPE
      , BILLING_TYPE
      , SALES_ORGANIZATION
      , DISTRIBUTION_CHANNEL
      , DIVISION
      , SALES_ORDER_CURRENCY
      , NET_SALES_REVENUE
      , COST_OF_GOODS_SOLD
      , GROSS_PRICE
      , ORDER_QUANTITY
      , STANDARD_COST
      , RECURRING_REVENUE
      , SUBSCRIPTION_START_DATE_KEY
      , BILLING_DATE_KEY
      , REVENUE_MONTH_DATE_KEY
      , REVENUE_MONTH_END_DATE_KEY
      , PERIOD_NUMBER
      , FISCAL_MONTH__YYYYMM
      , SUBSCRIPTION_STATUS
      , REC_SRC
      , BKCC
      , COPA_REC_SRC
FROM JOIN_RESULT
