---- SRC LAYER ----
WITH
SRC_PB             as ( SELECT ASIN, ASIN_KEY, BKCC, BRAND_BK, BRAND_ID, BRAND_KEY, BUSINESS_UNIT, CATEGORY_NAME, CATEGORY_TYPE, DATE, HOMEDEPOT_REGION, LOWES_REGION, MAX_BULK_PRICE, MAX_BULK_UNIT_THRESHOLD, MIN_BULK_PRICE, MIN_BULK_UNIT_THRESHOLD, MODEL, PLATFORM, PRODUCT_NAME, REC_SRC, REGION, RETAILER, SOURCE, STATE, STORES, SUM_FIRST_PARTY_SALES, SUM_FIRST_PARTY_UNITS, SUM_THIRD_PARTY_SALES, SUM_THIRD_PARTY_UNITS, SUM_TOTAL_SALES, SUM_TOTAL_UNITS, UNITS_ON_HAND_MEDIAN, UNITS_REPLENISHED, UPC, VALUE_ON_HAND, VALUE_REPLENISHED FROM {{ ref('pb_competitive_share_weekly') }} as SRC 
                        where category_type in ('RETAILER','N/A') )

/*
SRC_PB             as ( SELECT * FROM bus_vault.PB_COMPETITIVE_SHARE_WEEKLY )
*/
---- LOGIC LAYER ----

, LOGIC_PB as (
    SELECT
        DATE
      , ASIN
      , ASIN_KEY
      , PLATFORM
      , SUM_FIRST_PARTY_SALES
      , SUM_THIRD_PARTY_SALES
      , SUM_TOTAL_SALES
      , SUM_FIRST_PARTY_UNITS
      , SUM_THIRD_PARTY_UNITS
      , SUM_TOTAL_UNITS
      , CATEGORY_NAME
      , CATEGORY_TYPE
      , PRODUCT_NAME
      , UPC
      , MODEL
      , BRAND_ID
      , BRAND_BK
      , BRAND_KEY
      , MAX_BULK_PRICE
      , MAX_BULK_UNIT_THRESHOLD
      , MIN_BULK_PRICE
      , MIN_BULK_UNIT_THRESHOLD
      , UNITS_ON_HAND_MEDIAN
      , UNITS_REPLENISHED
      , VALUE_ON_HAND
      , VALUE_REPLENISHED
      , REGION
      , STATE
      , HOMEDEPOT_REGION
      , LOWES_REGION
      , SOURCE
      , RETAILER
      , BUSINESS_UNIT
      , STORES
      , BKCC
      , REC_SRC
    FROM SRC_PB
)
---- RENAME LAYER ----

, RENAME_PB as (
    SELECT
        DATE
      , ASIN
      , ASIN_KEY
      , PLATFORM
      , SUM_FIRST_PARTY_SALES
      , SUM_THIRD_PARTY_SALES
      , SUM_TOTAL_SALES
      , SUM_FIRST_PARTY_UNITS
      , SUM_THIRD_PARTY_UNITS
      , SUM_TOTAL_UNITS
      , CATEGORY_NAME
      , CATEGORY_TYPE
      , PRODUCT_NAME
      , UPC
      , MODEL
      , BRAND_ID
      , BRAND_BK
      , BRAND_KEY
      , MAX_BULK_PRICE
      , MAX_BULK_UNIT_THRESHOLD
      , MIN_BULK_PRICE
      , MIN_BULK_UNIT_THRESHOLD
      , UNITS_ON_HAND_MEDIAN
      , UNITS_REPLENISHED
      , VALUE_ON_HAND
      , VALUE_REPLENISHED
      , REGION
      , STATE
      , HOMEDEPOT_REGION
      , LOWES_REGION
      , SOURCE
      , RETAILER
      , BUSINESS_UNIT
      , STORES
      , BKCC
      , REC_SRC
    FROM LOGIC_PB
)
---- FILTER LAYER ----

, FILTER_PB as (
    SELECT *
    FROM RENAME_PB
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM FILTER_PB
)

---- FINAL LAYER ----
SELECT
          DATE
        , ASIN
        , ASIN_KEY
        , PLATFORM
        , SUM_FIRST_PARTY_SALES
        , SUM_THIRD_PARTY_SALES
        , SUM_TOTAL_SALES
        , SUM_FIRST_PARTY_UNITS
        , SUM_THIRD_PARTY_UNITS
        , SUM_TOTAL_UNITS
        , CATEGORY_NAME
        , CATEGORY_TYPE
        , PRODUCT_NAME
        , UPC
        , MODEL
        , BRAND_ID
        , BRAND_BK
        , BRAND_KEY
        , MAX_BULK_PRICE
        , MAX_BULK_UNIT_THRESHOLD
        , MIN_BULK_PRICE
        , MIN_BULK_UNIT_THRESHOLD
        , UNITS_ON_HAND_MEDIAN
        , UNITS_REPLENISHED
        , VALUE_ON_HAND
        , VALUE_REPLENISHED
        , REGION
        , STATE
        , HOMEDEPOT_REGION
        , LOWES_REGION
        , SOURCE
        , RETAILER
        , BUSINESS_UNIT
        , STORES
        , BKCC
        , REC_SRC
FROM JOIN_RESULT
