{{ config(alias='fact_global_spend_detail' + ('_global_spend' if target.name not in ['dev', 'qa', 'prod'] else '')) }}

SELECT
          PO_HEADER_ID
        , PO_NUMBER
        , PO_LINE_NUMBER
        , MATERIAL_DOCUMENT_NUMBER
        , MATERIAL_DOCUMENT_ITEM
        , TRANSACTION_ID
        , RELEASE_NUMBER
        , PO_CREATION_DATE_KEY
        , POSTING_DATE_KEY
        , CAL_YEAR
        , CAL_MONTH
        , ORDER_QTY
        , TOTAL_RCPT_QTY
        , TOTAL_RCPT_SPEND
        , TOTAL_INV_QTY
        , TOTAL_INV_SPEND
        , RECEIPT_QTY
        , RECEIPT_SPEND
        , PO_CURRENCY
        , AVG_INV_PRICE
        , SPEND_VOLUME
        , SPEND_AMOUNT_LOCAL_CURRENCY
        , LOCAL_CURRENCY
        , SPEND_USD
        , USD_PO_ITEM_PRICE
        , PO_ITEM_UOM
        , ORDER_UNIT_PRICE
        , ORDER_UNIT_PRICE_USD
        , PO_RECEIPT_UOM
        , PO_LINE_ELIKZ
        , OPCO
        , OPCO_CATEGORY
        , DIRECTOR_NAME
        , CATEGORY_LEADER_NAME
        , FBIN_CATEGORY_I
        , FBIN_CATEGORY_II
        , FBIN_CATEGORY_III
        , CONSIGNMENT_IND
        , CATEGORY_CD
        , CATEGORY_DESC
        , HDR_BUYER_CODE
        , SUPPLIER_NUMBER_PARENT
        , SUPPLIER_NAME_PARENT
        , SUPPLIER_NUMBER_CHILD
        , SUPPLIER_NAME_CHILD
        , PAYMENT_TERMS
        , DOCUMENT_TYPE
        , COUNTRY_OF_ORIGIN
        , SPEND_TYPE_FLAG
        , PURCHASING_ORG_BK
        , SUPPLIER_SITE_BK
        , SUPPLIER_BK
        , ITEM_BK
        , PLANT_BK
        , LEGAL_ENTITY_BK
        , PURCHASING_RECORD_BK
        , PO_CREATION_DATE__YYYYMMDD
        , POSTING_DATE__YYYYMMDD
        , PO_HEADER_HK
        , ITEM_HK
        , SUPPLIER_HK
        , PLANT_HK
        , LEGAL_ENTITY_HK
        , SUPPLIER_PAYMENT_TERM_HK
        , SUPPLIER_PAYMENT_TERM_DURABLE_HK
        , PURCHASING_RECORD_HK
        , BKCC
        , REC_SRC
        , BUSINESS_UNIT
from {{ ref('fact_global_spend_detail') }}
