---- SRC LAYER ----
WITH
SRC_WU             as ( SELECT FISCAL_YEAR__YYYY, FISCAL_MONTH__YYYYMM, FORECAST_MATERIAL, MATERIAL_KEY, MATERIAL_DESCRIPTION, SENDER_COST_CENTER, _GLACCOUNTCOPA, GL_ACCOUNT_LONG_TEXT, ORDER_REASON_DESCRIPTION, SALES_ORGANIZATION, COMPANY_CODE, DISTRIBUTION_CHANNEL_CODE, NO_CHARGE_UNITS, WARRANTY_COST
                        FROM {{ ref('fact_warranty_unit') }} as SRC )
/*
SRC_WU             as ( SELECT * FROM BUS_VAULT.PB_WARRANTY_UNIT )
*/
---- LOGIC LAYER ----

, LOGIC_WU as (
    SELECT
        FISCAL_YEAR__YYYY
      , FISCAL_MONTH__YYYYMM
      , FORECAST_MATERIAL
      , MATERIAL_KEY
      , MATERIAL_DESCRIPTION
      , SENDER_COST_CENTER
      , _GLACCOUNTCOPA
      , GL_ACCOUNT_LONG_TEXT
      , ORDER_REASON_DESCRIPTION
      , SALES_ORGANIZATION
      , COMPANY_CODE
      , DISTRIBUTION_CHANNEL_CODE
      , NO_CHARGE_UNITS
      , WARRANTY_COST
    FROM SRC_WU
)
---- RENAME LAYER ----

, RENAME_WU as (
    SELECT
        FISCAL_YEAR__YYYY
      , FISCAL_MONTH__YYYYMM
      , FORECAST_MATERIAL
      , MATERIAL_KEY
      , MATERIAL_DESCRIPTION
      , SENDER_COST_CENTER
      , _GLACCOUNTCOPA
      , GL_ACCOUNT_LONG_TEXT
      , ORDER_REASON_DESCRIPTION
      , SALES_ORGANIZATION
      , COMPANY_CODE
      , DISTRIBUTION_CHANNEL_CODE
      , NO_CHARGE_UNITS
      , WARRANTY_COST
    FROM LOGIC_WU
)
---- FILTER LAYER ----

, FILTER_WU as (
    SELECT *
    FROM RENAME_WU
)
---- JOIN LAYER ----

, JOIN_RESULT as (
    SELECT *
    FROM FILTER_WU
)

---- FINAL LAYER ----
SELECT
        FISCAL_YEAR__YYYY
      , FISCAL_MONTH__YYYYMM
      , FORECAST_MATERIAL
      , MATERIAL_KEY
      , MATERIAL_DESCRIPTION
      , SENDER_COST_CENTER
      , _GLACCOUNTCOPA
      , GL_ACCOUNT_LONG_TEXT
      , ORDER_REASON_DESCRIPTION
      , SALES_ORGANIZATION
      , COMPANY_CODE
      , DISTRIBUTION_CHANNEL_CODE
      , NO_CHARGE_UNITS
      , WARRANTY_COST
FROM JOIN_RESULT