---- SRC LAYER ----
WITH
SRC_FGSD           as ( SELECT AVG_INV_PRICE, BKCC, BUSINESS_UNIT, CAL_MONTH, CAL_YEAR, CATEGORY_CD, CATEGORY_DESC, CATEGORY_LEADER_NAME, CONSIGNMENT_IND, COUNTRY_OF_ORIGIN, DIRECTOR_NAME, DOCUMENT_TYPE, FBIN_CATEGORY_I, FBIN_CATEGORY_II, FBIN_CATEGORY_III, HDR_BUYER_CODE, ITEM_BK, ITEM_HK, LEGAL_ENTITY_BK, LEGAL_ENTITY_HK, LOCAL_CURRENCY, MATERIAL_DOCUMENT_ITEM, MATERIAL_DOCUMENT_NUMBER, OPCO, OPCO_CATEGORY, ORDER_QTY, ORDER_UNIT_PRICE, ORDER_UNIT_PRICE_USD, PAYMENT_TERMS, PLANT_BK, PLANT_HK, POSTING_DATE_KEY, PO_CREATION_DATE_KEY, PO_HEADER_HK, PO_HEADER_ID, PO_ITEM_UOM, PO_LINE_ELIKZ, PO_LINE_NUMBER, PO_NUMBER, PO_RECEIPT_UOM, PURCHASING_ORG_BK, RECEIPT_QTY, RECEIPT_SPEND, REC_SRC, RELEASE_NUMBER, SPEND_AMOUNT_LOCAL_CURRENCY, SPEND_USD, SPEND_VOLUME, SUPPLIER_BK, SUPPLIER_HK, SUPPLIER_NAME_CHILD, SUPPLIER_NAME_PARENT, SUPPLIER_NUMBER_CHILD, SUPPLIER_NUMBER_PARENT, SUPPLIER_PAYMENT_TERM_HK, TOTAL_INV_QTY, TOTAL_INV_SPEND, TOTAL_RCPT_QTY, TOTAL_RCPT_SPEND, TRANSACTION_ID, USD_PO_ITEM_PRICE FROM {{ ref('fact_global_spend_detail') }} as SRC  ),
SRC_DITM           as ( SELECT ITEM_ID, ITEM_TITLE FROM {{ ref('dim_item_fbin') }} as SRC 
                        qualify ROW_NUMBER() over ( partition by ITEM_ID order by ITEM_TITLE desc ) = 1 ),
SRC_DFY            as ( SELECT DATE_BK, FISCAL_445_CAL_MONTH, FISCAL_445_CAL_YEAR FROM {{ ref('dim_date_fiscal_445') }} as SRC  ),
SRC_FGSD_DFY       as ( SELECT DATE_BK, FISCAL_445_CAL_MONTH FROM {{ ref('dim_date_fiscal_445') }} as SRC  )

/*
SRC_FGSD           as ( SELECT * FROM BUS_VAULT.fact_global_spend_detail )
SRC_DITM           as ( SELECT * FROM BUS_VAULT.DIM_ITEM_FBIN )
SRC_DFY            as ( SELECT * FROM BUS_VAULT.DIM_DATE_FISCAL_445 )
SRC_FGSD_DFY       as ( SELECT * FROM BUS_VAULT.DIM_DATE_FISCAL_445 )
*/
---- LOGIC LAYER ----

, LOGIC_FGSD as (
    SELECT
        PO_HEADER_ID
      , PO_NUMBER
      , PO_LINE_NUMBER
      , MATERIAL_DOCUMENT_NUMBER
      , MATERIAL_DOCUMENT_ITEM
      , TRANSACTION_ID
      , RELEASE_NUMBER
      , PO_CREATION_DATE_KEY
      , POSTING_DATE_KEY
      , CAL_YEAR
      , CAL_MONTH
      , ORDER_QTY
      , TOTAL_RCPT_QTY
      , TOTAL_RCPT_SPEND
      , TOTAL_INV_QTY
      , TOTAL_INV_SPEND
      , RECEIPT_QTY
      , RECEIPT_SPEND
      , AVG_INV_PRICE
      , SPEND_VOLUME
      , SPEND_AMOUNT_LOCAL_CURRENCY
      , LOCAL_CURRENCY
      , SPEND_USD
      , USD_PO_ITEM_PRICE
      , PO_ITEM_UOM
      , ORDER_UNIT_PRICE
      , ORDER_UNIT_PRICE_USD
      , PO_RECEIPT_UOM
      , PO_LINE_ELIKZ
      , OPCO
      , OPCO_CATEGORY
      , DIRECTOR_NAME
      , CATEGORY_LEADER_NAME
      , FBIN_CATEGORY_I
      , FBIN_CATEGORY_II
      , FBIN_CATEGORY_III
      , CONSIGNMENT_IND
      , CATEGORY_CD
      , CATEGORY_DESC
      , HDR_BUYER_CODE
      , SUPPLIER_NUMBER_PARENT
      , SUPPLIER_NAME_PARENT
      , SUPPLIER_NUMBER_CHILD
      , SUPPLIER_NAME_CHILD
      , PAYMENT_TERMS
      , DOCUMENT_TYPE
      , COUNTRY_OF_ORIGIN
      , PURCHASING_ORG_BK
      , SUPPLIER_BK
      , ITEM_BK                                                      as                                               ITEM
      , PLANT_BK
      , LEGAL_ENTITY_BK
      , PO_HEADER_HK
      , ITEM_HK
      , SUPPLIER_HK
      , PLANT_HK
      , LEGAL_ENTITY_HK
      , SUPPLIER_PAYMENT_TERM_HK
      , BKCC
      , REC_SRC
      , BUSINESS_UNIT
    FROM SRC_FGSD
)

, LOGIC_DITM as (
    SELECT
        ITEM_TITLE                                                   as                                   ITEM_DESCRIPTION
      , ITEM_ID
    FROM SRC_DITM
)

, LOGIC_DFY as (
    SELECT
        FISCAL_445_CAL_MONTH                                         as                           POSTING_FISCAL_445_MONTH
      , DATE_BK
      , FISCAL_445_CAL_YEAR
      , FISCAL_445_CAL_MONTH
    FROM SRC_DFY
)

, LOGIC_FGSD_DFY as (
    SELECT
        FISCAL_445_CAL_MONTH                                         as                       PO_CREATION_FISCAL_445_MONTH
      , DATE_BK                                                      as                                   FGSD_DFY_DATE_BK
    FROM SRC_FGSD_DFY
)
---- RENAME LAYER ----

, RENAME_FGSD as (
    SELECT
        PO_HEADER_ID
      , PO_NUMBER
      , PO_LINE_NUMBER
      , MATERIAL_DOCUMENT_NUMBER
      , MATERIAL_DOCUMENT_ITEM
      , TRANSACTION_ID
      , RELEASE_NUMBER
      , PO_CREATION_DATE_KEY
      , POSTING_DATE_KEY
      , CAL_YEAR
      , CAL_MONTH
      , ORDER_QTY
      , TOTAL_RCPT_QTY
      , TOTAL_RCPT_SPEND
      , TOTAL_INV_QTY
      , TOTAL_INV_SPEND
      , RECEIPT_QTY
      , RECEIPT_SPEND
      , AVG_INV_PRICE
      , SPEND_VOLUME
      , SPEND_AMOUNT_LOCAL_CURRENCY
      , LOCAL_CURRENCY
      , SPEND_USD
      , USD_PO_ITEM_PRICE
      , PO_ITEM_UOM
      , ORDER_UNIT_PRICE
      , ORDER_UNIT_PRICE_USD
      , PO_RECEIPT_UOM
      , PO_LINE_ELIKZ
      , OPCO
      , OPCO_CATEGORY
      , DIRECTOR_NAME
      , CATEGORY_LEADER_NAME
      , FBIN_CATEGORY_I
      , FBIN_CATEGORY_II
      , FBIN_CATEGORY_III
      , CONSIGNMENT_IND
      , CATEGORY_CD
      , CATEGORY_DESC
      , HDR_BUYER_CODE
      , SUPPLIER_NUMBER_PARENT
      , SUPPLIER_NAME_PARENT
      , SUPPLIER_NUMBER_CHILD
      , SUPPLIER_NAME_CHILD
      , PAYMENT_TERMS
      , DOCUMENT_TYPE
      , COUNTRY_OF_ORIGIN
      , PURCHASING_ORG_BK
      , SUPPLIER_BK
      , ITEM
      , PLANT_BK
      , LEGAL_ENTITY_BK
      , PO_HEADER_HK
      , ITEM_HK
      , SUPPLIER_HK
      , PLANT_HK
      , LEGAL_ENTITY_HK
      , SUPPLIER_PAYMENT_TERM_HK
      , BKCC
      , REC_SRC
      , BUSINESS_UNIT
    FROM LOGIC_FGSD
)

, RENAME_FGSD_DFY as (
    SELECT
        PO_CREATION_FISCAL_445_MONTH
      , FGSD_DFY_DATE_BK
    FROM LOGIC_FGSD_DFY
)

, RENAME_DFY as (
    SELECT
        POSTING_FISCAL_445_MONTH
      , DATE_BK
      , FISCAL_445_CAL_YEAR
      , FISCAL_445_CAL_MONTH
    FROM LOGIC_DFY
)

, RENAME_DITM as (
    SELECT
        ITEM_DESCRIPTION
      , ITEM_ID
    FROM LOGIC_DITM
)
---- FILTER LAYER ----

, FILTER_FGSD as (
    SELECT *
    FROM RENAME_FGSD
)

, FILTER_DITM as (
    SELECT *
    FROM RENAME_DITM
)

, FILTER_DFY as (
    SELECT *
    FROM RENAME_DFY
)

, FILTER_FGSD_DFY as (
    SELECT *
    FROM RENAME_FGSD_DFY
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM FILTER_FGSD
    LEFT JOIN FILTER_DITM
        ON FILTER_FGSD.ITEM_HK = FILTER_DITM.ITEM_ID
    LEFT JOIN FILTER_DFY
        ON FILTER_FGSD.POSTING_DATE_KEY = FILTER_DFY.DATE_BK
    LEFT JOIN FILTER_FGSD_DFY
        ON FILTER_FGSD.PO_CREATION_DATE_KEY = FGSD_DFY_DATE_BK
)

---- FINAL LAYER ----
SELECT
          PO_HEADER_ID
        , PO_NUMBER
        , PO_LINE_NUMBER
        , MATERIAL_DOCUMENT_NUMBER
        , MATERIAL_DOCUMENT_ITEM
        , TRANSACTION_ID
        , RELEASE_NUMBER
        , PO_CREATION_DATE_KEY
        , PO_CREATION_FISCAL_445_MONTH
        , POSTING_DATE_KEY
        , POSTING_FISCAL_445_MONTH
        , CAL_YEAR
        , CAL_MONTH
        , CONCAT(CAL_YEAR, '|', CAL_MONTH )                            as YEAR_MONTH
        , ORDER_QTY
        , TOTAL_RCPT_QTY
        , TOTAL_RCPT_SPEND
        , TOTAL_INV_QTY
        , TOTAL_INV_SPEND
        , RECEIPT_QTY
        , RECEIPT_SPEND
        , AVG_INV_PRICE
        , SPEND_VOLUME
        , SPEND_AMOUNT_LOCAL_CURRENCY
        , LOCAL_CURRENCY
        , SPEND_USD
        , USD_PO_ITEM_PRICE
        , PO_ITEM_UOM
        , ORDER_UNIT_PRICE
        , ORDER_UNIT_PRICE_USD
        , PO_RECEIPT_UOM
        , PO_LINE_ELIKZ
        , OPCO
        , OPCO_CATEGORY
        , DIRECTOR_NAME
        , CATEGORY_LEADER_NAME
        , FBIN_CATEGORY_I
        , FBIN_CATEGORY_II
        , FBIN_CATEGORY_III
        , CONSIGNMENT_IND
        , CATEGORY_CD
        , CATEGORY_DESC
        , HDR_BUYER_CODE
        , SUPPLIER_NUMBER_PARENT
        , SUPPLIER_NAME_PARENT
        , SUPPLIER_NUMBER_CHILD
        , SUPPLIER_NAME_CHILD
        , PAYMENT_TERMS
        , DOCUMENT_TYPE
        , COUNTRY_OF_ORIGIN
        , PURCHASING_ORG_BK
        , SUPPLIER_BK
        , ITEM
        , ITEM_DESCRIPTION
        , PLANT_BK
        , LEGAL_ENTITY_BK
        , PO_HEADER_HK
        , ITEM_HK
        , SUPPLIER_HK
        , PLANT_HK
        , LEGAL_ENTITY_HK
        , SUPPLIER_PAYMENT_TERM_HK
        , FISCAL_445_CAL_YEAR
        , FISCAL_445_CAL_MONTH
        , CONCAT(FISCAL_445_CAL_YEAR, '|', FISCAL_445_CAL_MONTH)       as FISCAL_445_YEAR_MONTH
        , BKCC
        , REC_SRC
        , BUSINESS_UNIT
FROM JOIN_RESULT
