---- SRC LAYER ----
WITH
SRC_SML            as ( SELECT * FROM {{ ref('v_psa_stg_receivables__ml_ebs') }} as SRC 
                         {% if is_incremental() %}
                         WHERE SRC.LOAD_DTS > (SELECT DATEADD('HOUR', '-1', MAX(LOAD_DTS)) FROM {{this}})
                         {% endif %}  )

/*
SRC_SML            as ( SELECT * FROM STAGING.v_psa_stg__receivables__ML_EBS )
*/
---- LOGIC LAYER ----

, LOGIC_SML as (
    SELECT
        RECEIVABLES_BK
      , ORG_ID
      , RECEIVABLES_TRX_ID
      , GLOBAL_ATTRIBUTE10
      , LAST_UPDATE_DATE
      , RISK_ELIMINATION_DAYS
      , GLOBAL_ATTRIBUTE5
      , GLOBAL_ATTRIBUTE4
      , STATUS
      , GLOBAL_ATTRIBUTE7
      , GL_ACCOUNT_SOURCE
      , GLOBAL_ATTRIBUTE6
      , GLOBAL_ATTRIBUTE1
      , GLOBAL_ATTRIBUTE3
      , GLOBAL_ATTRIBUTE2
      , GLOBAL_ATTRIBUTE9
      , TYPE
      , END_DATE_ACTIVE
      , GLOBAL_ATTRIBUTE8
      , CREATED_BY
      , ATTRIBUTE3
      , LAST_UPDATED_BY
      , ATTRIBUTE2
      , ATTRIBUTE1
      , CREATION_DATE
      , DEFAULT_ACCTG_DISTRIBUTION_SET
      , ATTRIBUTE9
      , ATTRIBUTE8
      , ATTRIBUTE7
      , ATTRIBUTE6
      , ATTRIBUTE5
      , NAME
      , ATTRIBUTE4
      , ATTRIBUTE_CATEGORY
      , TAX_RECOVERABLE_FLAG
      , ATTRIBUTE10
      , ATTRIBUTE14
      , ATTRIBUTE13
      , TAX_CODE_SOURCE
      , ATTRIBUTE12
      , ATTRIBUTE11
      , SET_OF_BOOKS_ID
      , LIABILITY_TAX_CODE
      , ACCOUNTING_AFFECT_FLAG
      , ASSET_TAX_CODE
      , DESCRIPTION
      , CODE_COMBINATION_ID
      , INACTIVE_DATE
      , START_DATE_ACTIVE
      , GLOBAL_ATTRIBUTE20
      , LAST_UPDATE_LOGIN
      , GLOBAL_ATTRIBUTE_CATEGORY
      , GLOBAL_ATTRIBUTE17
      , GLOBAL_ATTRIBUTE18
      , GLOBAL_ATTRIBUTE15
      , GLOBAL_ATTRIBUTE16
      , GLOBAL_ATTRIBUTE13
      , GLOBAL_ATTRIBUTE14
      , GLOBAL_ATTRIBUTE11
      , GLOBAL_ATTRIBUTE12
      , ATTRIBUTE15
      , GLOBAL_ATTRIBUTE19
      , _FIVETRAN_DELETED
      , _FIVETRAN_ID
      , _FIVETRAN_SYNCED
      , PSA_LOAD_DTS
      , PSA_RECORD_SOURCE
      , PSA_DELETE_IND
      , LOAD_DTS
      , REC_SRC
      , HASHDIFF
    FROM SRC_SML
)
---- RENAME LAYER ----

, RENAME_SML as (
    SELECT
        RECEIVABLES_BK
      , ORG_ID
      , RECEIVABLES_TRX_ID
      , GLOBAL_ATTRIBUTE10
      , LAST_UPDATE_DATE
      , RISK_ELIMINATION_DAYS
      , GLOBAL_ATTRIBUTE5
      , GLOBAL_ATTRIBUTE4
      , STATUS
      , GLOBAL_ATTRIBUTE7
      , GL_ACCOUNT_SOURCE
      , GLOBAL_ATTRIBUTE6
      , GLOBAL_ATTRIBUTE1
      , GLOBAL_ATTRIBUTE3
      , GLOBAL_ATTRIBUTE2
      , GLOBAL_ATTRIBUTE9
      , TYPE
      , END_DATE_ACTIVE
      , GLOBAL_ATTRIBUTE8
      , CREATED_BY
      , ATTRIBUTE3
      , LAST_UPDATED_BY
      , ATTRIBUTE2
      , ATTRIBUTE1
      , CREATION_DATE
      , DEFAULT_ACCTG_DISTRIBUTION_SET
      , ATTRIBUTE9
      , ATTRIBUTE8
      , ATTRIBUTE7
      , ATTRIBUTE6
      , ATTRIBUTE5
      , NAME
      , ATTRIBUTE4
      , ATTRIBUTE_CATEGORY
      , TAX_RECOVERABLE_FLAG
      , ATTRIBUTE10
      , ATTRIBUTE14
      , ATTRIBUTE13
      , TAX_CODE_SOURCE
      , ATTRIBUTE12
      , ATTRIBUTE11
      , SET_OF_BOOKS_ID
      , LIABILITY_TAX_CODE
      , ACCOUNTING_AFFECT_FLAG
      , ASSET_TAX_CODE
      , DESCRIPTION
      , CODE_COMBINATION_ID
      , INACTIVE_DATE
      , START_DATE_ACTIVE
      , GLOBAL_ATTRIBUTE20
      , LAST_UPDATE_LOGIN
      , GLOBAL_ATTRIBUTE_CATEGORY
      , GLOBAL_ATTRIBUTE17
      , GLOBAL_ATTRIBUTE18
      , GLOBAL_ATTRIBUTE15
      , GLOBAL_ATTRIBUTE16
      , GLOBAL_ATTRIBUTE13
      , GLOBAL_ATTRIBUTE14
      , GLOBAL_ATTRIBUTE11
      , GLOBAL_ATTRIBUTE12
      , ATTRIBUTE15
      , GLOBAL_ATTRIBUTE19
      , _FIVETRAN_DELETED
      , _FIVETRAN_ID
      , _FIVETRAN_SYNCED
      , PSA_LOAD_DTS
      , PSA_RECORD_SOURCE
      , PSA_DELETE_IND
      , LOAD_DTS
      , REC_SRC
      , HASHDIFF
    FROM LOGIC_SML
)
---- FILTER LAYER ----

, FILTER_SML as (
    SELECT *
    FROM RENAME_SML
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM FILTER_SML
)

---- FINAL LAYER ----
SELECT
          RECEIVABLES_BK
        , ORG_ID
        , RECEIVABLES_TRX_ID
        , GLOBAL_ATTRIBUTE10
        , LAST_UPDATE_DATE
        , RISK_ELIMINATION_DAYS
        , GLOBAL_ATTRIBUTE5
        , GLOBAL_ATTRIBUTE4
        , STATUS
        , GLOBAL_ATTRIBUTE7
        , GL_ACCOUNT_SOURCE
        , GLOBAL_ATTRIBUTE6
        , GLOBAL_ATTRIBUTE1
        , GLOBAL_ATTRIBUTE3
        , GLOBAL_ATTRIBUTE2
        , GLOBAL_ATTRIBUTE9
        , TYPE
        , END_DATE_ACTIVE
        , GLOBAL_ATTRIBUTE8
        , CREATED_BY
        , ATTRIBUTE3
        , LAST_UPDATED_BY
        , ATTRIBUTE2
        , ATTRIBUTE1
        , CREATION_DATE
        , DEFAULT_ACCTG_DISTRIBUTION_SET
        , ATTRIBUTE9
        , ATTRIBUTE8
        , ATTRIBUTE7
        , ATTRIBUTE6
        , ATTRIBUTE5
        , NAME
        , ATTRIBUTE4
        , ATTRIBUTE_CATEGORY
        , TAX_RECOVERABLE_FLAG
        , ATTRIBUTE10
        , ATTRIBUTE14
        , ATTRIBUTE13
        , TAX_CODE_SOURCE
        , ATTRIBUTE12
        , ATTRIBUTE11
        , SET_OF_BOOKS_ID
        , LIABILITY_TAX_CODE
        , ACCOUNTING_AFFECT_FLAG
        , ASSET_TAX_CODE
        , DESCRIPTION
        , CODE_COMBINATION_ID
        , INACTIVE_DATE
        , START_DATE_ACTIVE
        , GLOBAL_ATTRIBUTE20
        , LAST_UPDATE_LOGIN
        , GLOBAL_ATTRIBUTE_CATEGORY
        , GLOBAL_ATTRIBUTE17
        , GLOBAL_ATTRIBUTE18
        , GLOBAL_ATTRIBUTE15
        , GLOBAL_ATTRIBUTE16
        , GLOBAL_ATTRIBUTE13
        , GLOBAL_ATTRIBUTE14
        , GLOBAL_ATTRIBUTE11
        , GLOBAL_ATTRIBUTE12
        , ATTRIBUTE15
        , GLOBAL_ATTRIBUTE19
        , _FIVETRAN_DELETED
        , _FIVETRAN_ID
        , _FIVETRAN_SYNCED
        , PSA_LOAD_DTS
        , PSA_RECORD_SOURCE
        , PSA_DELETE_IND
        , LOAD_DTS
        , REC_SRC
        , HASHDIFF
FROM JOIN_RESULT
{% if is_incremental() %}
WHERE NOT EXISTS (
    SELECT 1 
    FROM {{ this }} existing
    WHERE existing.RECEIVABLES_BK = JOIN_RESULT.RECEIVABLES_BK
    AND existing.HASH_DIFF = JOIN_RESULT.HASH_DIFF
)
{% endif %} 
{% if not is_incremental() %}
union all
    SELECT  GR.VALUE as RECEIVABLES_BK
, GR.VALUE::NUMBER as ORG_ID
, GR.VALUE::NUMBER as RECEIVABLES_TRX_ID
    , null as GLOBAL_ATTRIBUTE10
    , null as LAST_UPDATE_DATE
    , null as RISK_ELIMINATION_DAYS
    , null as GLOBAL_ATTRIBUTE5
    , null as GLOBAL_ATTRIBUTE4
    , null as STATUS
    , null as GLOBAL_ATTRIBUTE7
    , null as GL_ACCOUNT_SOURCE
    , null as GLOBAL_ATTRIBUTE6
    , null as GLOBAL_ATTRIBUTE1
    , null as GLOBAL_ATTRIBUTE3
    , null as GLOBAL_ATTRIBUTE2
    , null as GLOBAL_ATTRIBUTE9
    , null as TYPE
    , null as END_DATE_ACTIVE
    , null as GLOBAL_ATTRIBUTE8
    , null as CREATED_BY
    , null as ATTRIBUTE3
    , null as LAST_UPDATED_BY
    , null as ATTRIBUTE2
    , null as ATTRIBUTE1
    , null as CREATION_DATE
    , null as DEFAULT_ACCTG_DISTRIBUTION_SET
    , null as ATTRIBUTE9
    , null as ATTRIBUTE8
    , null as ATTRIBUTE7
    , null as ATTRIBUTE6
    , null as ATTRIBUTE5
    , null as NAME
    , null as ATTRIBUTE4
    , null as ATTRIBUTE_CATEGORY
    , null as TAX_RECOVERABLE_FLAG
    , null as ATTRIBUTE10
    , null as ATTRIBUTE14
    , null as ATTRIBUTE13
    , null as TAX_CODE_SOURCE
    , null as ATTRIBUTE12
    , null as ATTRIBUTE11
    , null as SET_OF_BOOKS_ID
    , null as LIABILITY_TAX_CODE
    , null as ACCOUNTING_AFFECT_FLAG
    , null as ASSET_TAX_CODE
    , null as DESCRIPTION
    , null as CODE_COMBINATION_ID
    , null as INACTIVE_DATE
    , null as START_DATE_ACTIVE
    , null as GLOBAL_ATTRIBUTE20
    , null as LAST_UPDATE_LOGIN
    , null as GLOBAL_ATTRIBUTE_CATEGORY
    , null as GLOBAL_ATTRIBUTE17
    , null as GLOBAL_ATTRIBUTE18
    , null as GLOBAL_ATTRIBUTE15
    , null as GLOBAL_ATTRIBUTE16
    , null as GLOBAL_ATTRIBUTE13
    , null as GLOBAL_ATTRIBUTE14
    , null as GLOBAL_ATTRIBUTE11
    , null as GLOBAL_ATTRIBUTE12
    , null as ATTRIBUTE15
    , null as GLOBAL_ATTRIBUTE19
    , null as _FIVETRAN_DELETED
    , null as _FIVETRAN_ID
    , null as _FIVETRAN_SYNCED
    , null as PSA_LOAD_DTS
    , null as PSA_RECORD_SOURCE
    , null as PSA_DELETE_IND, CONVERT_TIMEZONE('UTC','1900-01-01'::TIMESTAMP)::TIMESTAMP  as  LOAD_DTS
	,'USAZET.SNOWFLAKE.FBIN.DERIVED' AS REC_SRC
	,''::BINARY as HASH_DIFF
        FROM
        TABLE(strtok_split_to_table('0|-1|-2', '|')) AS GR
{% endif %}