---- SRC LAYER ----
WITH
SRC_SML            as ( SELECT * FROM {{ ref('v_psa_stg_batch_sources__ml_ebs') }} as SRC 
                         {% if is_incremental() %}
                         WHERE SRC.LOAD_DTS > (SELECT DATEADD('HOUR', '-1', MAX(LOAD_DTS)) FROM {{this}})
                         {% endif %}  )

/*
SRC_SML            as ( SELECT * FROM STAGING.v_psa_stg_batch_sources__ML_EBS )
*/
---- LOGIC LAYER ----

, LOGIC_SML as (
    SELECT
        BATCH_SOURCE_BK
      , ORG_ID
      , BATCH_SOURCE_ID
      , BILL_CUSTOMER_RULE
      , COPY_INV_TIDFF_TO_CM_FLAG
      , GLOBAL_ATTRIBUTE5
      , GLOBAL_ATTRIBUTE4
      , GLOBAL_ATTRIBUTE7
      , AGREEMENT_RULE
      , GLOBAL_ATTRIBUTE6
      , GLOBAL_ATTRIBUTE1
      , GLOBAL_ATTRIBUTE3
      , GLOBAL_ATTRIBUTE2
      , BILL_CONTACT_RULE
      , GLOBAL_ATTRIBUTE9
      , GLOBAL_ATTRIBUTE8
      , BILL_ADDRESS_RULE
      , ATTRIBUTE3
      , ATTRIBUTE2
      , ATTRIBUTE1
      , ALLOW_DUPLICATE_TRX_NUM_FLAG
      , ATTRIBUTE9
      , ATTRIBUTE8
      , ATTRIBUTE7
      , ATTRIBUTE6
      , ATTRIBUTE5
      , GL_DATE_PERIOD_RULE
      , ATTRIBUTE4
      , CUST_TRX_TYPE_RULE
      , FOB_POINT_RULE
      , INVENTORY_ITEM_RULE
      , PAYMENT_DET_DEF_HIERARCHY
      , CREATE_CLEARING_FLAG
      , REV_ACC_ALLOCATION_RULE
      , ATTRIBUTE10
      , SALESPERSON_RULE
      , SALES_CREDIT_TYPE_RULE
      , ATTRIBUTE14
      , TERM_RULE
      , ATTRIBUTE13
      , ATTRIBUTE12
      , ATTRIBUTE11
      , GEN_LINE_LEVEL_BAL_FLAG
      , INVALID_TAX_RATE_RULE
      , DESCRIPTION
      , SHIP_CONTACT_RULE
      , RECEIPT_HANDLING_OPTION
      , GLOBAL_ATTRIBUTE20
      , START_DATE
      , GROUPING_RULE_ID
      , GLOBAL_ATTRIBUTE17
      , GLOBAL_ATTRIBUTE18
      , GLOBAL_ATTRIBUTE15
      , GLOBAL_ATTRIBUTE16
      , CUSTOMER_BANK_ACCOUNT_RULE
      , GLOBAL_ATTRIBUTE13
      , GLOBAL_ATTRIBUTE14
      , GLOBAL_ATTRIBUTE11
      , GLOBAL_ATTRIBUTE12
      , ATTRIBUTE15
      , GLOBAL_ATTRIBUTE19
      , SALES_TERRITORY_RULE
      , COPY_DOC_NUMBER_FLAG
      , BATCH_SOURCE_TYPE
      , END_DATE
      , GLOBAL_ATTRIBUTE10
      , LAST_BATCH_NUM
      , LAST_UPDATE_DATE
      , RELATED_DOCUMENT_RULE
      , AUTO_BATCH_NUMBERING_FLAG
      , SHIP_ADDRESS_RULE
      , STATUS
      , ALLOW_SALES_CREDIT_FLAG
      , INVALID_LINES_RULE
      , MEMO_REASON_RULE
      , ACCOUNTING_RULE_RULE
      , DERIVE_DATE_FLAG
      , CREATED_BY
      , LAST_UPDATED_BY
      , ACCOUNTING_FLEXFIELD_RULE
      , AUTO_TRX_NUMBERING_FLAG
      , LEGAL_ENTITY_ID
      , CREATION_DATE
      , UNIT_OF_MEASURE_RULE
      , NAME
      , DEFAULT_REFERENCE
      , ATTRIBUTE_CATEGORY
      , DEFAULT_INV_TRX_TYPE
      , MEMO_LINE_RULE
      , RECEIPT_METHOD_RULE
      , CREDIT_MEMO_BATCH_SOURCE_ID
      , SHIP_CUSTOMER_RULE
      , SOLD_CUSTOMER_RULE
      , SHIP_VIA_RULE
      , SALES_CREDIT_RULE
      , INVOICING_RULE_RULE
      , LAST_UPDATE_LOGIN
      , GLOBAL_ATTRIBUTE_CATEGORY
      , _FIVETRAN_DELETED
      , _FIVETRAN_ID
      , _FIVETRAN_SYNCED
      , PSA_LOAD_DTS
      , PSA_RECORD_SOURCE
      , PSA_DELETE_IND
      , LOAD_DTS
      , REC_SRC
      , HASHDIFF
    FROM SRC_SML
)
---- RENAME LAYER ----

, RENAME_SML as (
    SELECT
        BATCH_SOURCE_BK
      , ORG_ID
      , BATCH_SOURCE_ID
      , BILL_CUSTOMER_RULE
      , COPY_INV_TIDFF_TO_CM_FLAG
      , GLOBAL_ATTRIBUTE5
      , GLOBAL_ATTRIBUTE4
      , GLOBAL_ATTRIBUTE7
      , AGREEMENT_RULE
      , GLOBAL_ATTRIBUTE6
      , GLOBAL_ATTRIBUTE1
      , GLOBAL_ATTRIBUTE3
      , GLOBAL_ATTRIBUTE2
      , BILL_CONTACT_RULE
      , GLOBAL_ATTRIBUTE9
      , GLOBAL_ATTRIBUTE8
      , BILL_ADDRESS_RULE
      , ATTRIBUTE3
      , ATTRIBUTE2
      , ATTRIBUTE1
      , ALLOW_DUPLICATE_TRX_NUM_FLAG
      , ATTRIBUTE9
      , ATTRIBUTE8
      , ATTRIBUTE7
      , ATTRIBUTE6
      , ATTRIBUTE5
      , GL_DATE_PERIOD_RULE
      , ATTRIBUTE4
      , CUST_TRX_TYPE_RULE
      , FOB_POINT_RULE
      , INVENTORY_ITEM_RULE
      , PAYMENT_DET_DEF_HIERARCHY
      , CREATE_CLEARING_FLAG
      , REV_ACC_ALLOCATION_RULE
      , ATTRIBUTE10
      , SALESPERSON_RULE
      , SALES_CREDIT_TYPE_RULE
      , ATTRIBUTE14
      , TERM_RULE
      , ATTRIBUTE13
      , ATTRIBUTE12
      , ATTRIBUTE11
      , GEN_LINE_LEVEL_BAL_FLAG
      , INVALID_TAX_RATE_RULE
      , DESCRIPTION
      , SHIP_CONTACT_RULE
      , RECEIPT_HANDLING_OPTION
      , GLOBAL_ATTRIBUTE20
      , START_DATE
      , GROUPING_RULE_ID
      , GLOBAL_ATTRIBUTE17
      , GLOBAL_ATTRIBUTE18
      , GLOBAL_ATTRIBUTE15
      , GLOBAL_ATTRIBUTE16
      , CUSTOMER_BANK_ACCOUNT_RULE
      , GLOBAL_ATTRIBUTE13
      , GLOBAL_ATTRIBUTE14
      , GLOBAL_ATTRIBUTE11
      , GLOBAL_ATTRIBUTE12
      , ATTRIBUTE15
      , GLOBAL_ATTRIBUTE19
      , SALES_TERRITORY_RULE
      , COPY_DOC_NUMBER_FLAG
      , BATCH_SOURCE_TYPE
      , END_DATE
      , GLOBAL_ATTRIBUTE10
      , LAST_BATCH_NUM
      , LAST_UPDATE_DATE
      , RELATED_DOCUMENT_RULE
      , AUTO_BATCH_NUMBERING_FLAG
      , SHIP_ADDRESS_RULE
      , STATUS
      , ALLOW_SALES_CREDIT_FLAG
      , INVALID_LINES_RULE
      , MEMO_REASON_RULE
      , ACCOUNTING_RULE_RULE
      , DERIVE_DATE_FLAG
      , CREATED_BY
      , LAST_UPDATED_BY
      , ACCOUNTING_FLEXFIELD_RULE
      , AUTO_TRX_NUMBERING_FLAG
      , LEGAL_ENTITY_ID
      , CREATION_DATE
      , UNIT_OF_MEASURE_RULE
      , NAME
      , DEFAULT_REFERENCE
      , ATTRIBUTE_CATEGORY
      , DEFAULT_INV_TRX_TYPE
      , MEMO_LINE_RULE
      , RECEIPT_METHOD_RULE
      , CREDIT_MEMO_BATCH_SOURCE_ID
      , SHIP_CUSTOMER_RULE
      , SOLD_CUSTOMER_RULE
      , SHIP_VIA_RULE
      , SALES_CREDIT_RULE
      , INVOICING_RULE_RULE
      , LAST_UPDATE_LOGIN
      , GLOBAL_ATTRIBUTE_CATEGORY
      , _FIVETRAN_DELETED
      , _FIVETRAN_ID
      , _FIVETRAN_SYNCED
      , PSA_LOAD_DTS
      , PSA_RECORD_SOURCE
      , PSA_DELETE_IND
      , LOAD_DTS
      , REC_SRC
      , HASHDIFF
    FROM LOGIC_SML
)
---- FILTER LAYER ----

, FILTER_SML as (
    SELECT *
    FROM RENAME_SML
)

---- JOIN LAYER ----
, JOIN_RESULT as (
    SELECT *
    FROM FILTER_SML
)

---- FINAL LAYER ----
SELECT
          BATCH_SOURCE_BK
        , ORG_ID
        , BATCH_SOURCE_ID
        , BILL_CUSTOMER_RULE
        , COPY_INV_TIDFF_TO_CM_FLAG
        , GLOBAL_ATTRIBUTE5
        , GLOBAL_ATTRIBUTE4
        , GLOBAL_ATTRIBUTE7
        , AGREEMENT_RULE
        , GLOBAL_ATTRIBUTE6
        , GLOBAL_ATTRIBUTE1
        , GLOBAL_ATTRIBUTE3
        , GLOBAL_ATTRIBUTE2
        , BILL_CONTACT_RULE
        , GLOBAL_ATTRIBUTE9
        , GLOBAL_ATTRIBUTE8
        , BILL_ADDRESS_RULE
        , ATTRIBUTE3
        , ATTRIBUTE2
        , ATTRIBUTE1
        , ALLOW_DUPLICATE_TRX_NUM_FLAG
        , ATTRIBUTE9
        , ATTRIBUTE8
        , ATTRIBUTE7
        , ATTRIBUTE6
        , ATTRIBUTE5
        , GL_DATE_PERIOD_RULE
        , ATTRIBUTE4
        , CUST_TRX_TYPE_RULE
        , FOB_POINT_RULE
        , INVENTORY_ITEM_RULE
        , PAYMENT_DET_DEF_HIERARCHY
        , CREATE_CLEARING_FLAG
        , REV_ACC_ALLOCATION_RULE
        , ATTRIBUTE10
        , SALESPERSON_RULE
        , SALES_CREDIT_TYPE_RULE
        , ATTRIBUTE14
        , TERM_RULE
        , ATTRIBUTE13
        , ATTRIBUTE12
        , ATTRIBUTE11
        , GEN_LINE_LEVEL_BAL_FLAG
        , INVALID_TAX_RATE_RULE
        , DESCRIPTION
        , SHIP_CONTACT_RULE
        , RECEIPT_HANDLING_OPTION
        , GLOBAL_ATTRIBUTE20
        , START_DATE
        , GROUPING_RULE_ID
        , GLOBAL_ATTRIBUTE17
        , GLOBAL_ATTRIBUTE18
        , GLOBAL_ATTRIBUTE15
        , GLOBAL_ATTRIBUTE16
        , CUSTOMER_BANK_ACCOUNT_RULE
        , GLOBAL_ATTRIBUTE13
        , GLOBAL_ATTRIBUTE14
        , GLOBAL_ATTRIBUTE11
        , GLOBAL_ATTRIBUTE12
        , ATTRIBUTE15
        , GLOBAL_ATTRIBUTE19
        , SALES_TERRITORY_RULE
        , COPY_DOC_NUMBER_FLAG
        , BATCH_SOURCE_TYPE
        , END_DATE
        , GLOBAL_ATTRIBUTE10
        , LAST_BATCH_NUM
        , LAST_UPDATE_DATE
        , RELATED_DOCUMENT_RULE
        , AUTO_BATCH_NUMBERING_FLAG
        , SHIP_ADDRESS_RULE
        , STATUS
        , ALLOW_SALES_CREDIT_FLAG
        , INVALID_LINES_RULE
        , MEMO_REASON_RULE
        , ACCOUNTING_RULE_RULE
        , DERIVE_DATE_FLAG
        , CREATED_BY
        , LAST_UPDATED_BY
        , ACCOUNTING_FLEXFIELD_RULE
        , AUTO_TRX_NUMBERING_FLAG
        , LEGAL_ENTITY_ID
        , CREATION_DATE
        , UNIT_OF_MEASURE_RULE
        , NAME
        , DEFAULT_REFERENCE
        , ATTRIBUTE_CATEGORY
        , DEFAULT_INV_TRX_TYPE
        , MEMO_LINE_RULE
        , RECEIPT_METHOD_RULE
        , CREDIT_MEMO_BATCH_SOURCE_ID
        , SHIP_CUSTOMER_RULE
        , SOLD_CUSTOMER_RULE
        , SHIP_VIA_RULE
        , SALES_CREDIT_RULE
        , INVOICING_RULE_RULE
        , LAST_UPDATE_LOGIN
        , GLOBAL_ATTRIBUTE_CATEGORY
        , _FIVETRAN_DELETED
        , _FIVETRAN_ID
        , _FIVETRAN_SYNCED
        , PSA_LOAD_DTS
        , PSA_RECORD_SOURCE
        , PSA_DELETE_IND
        , LOAD_DTS
        , REC_SRC
        , HASHDIFF
FROM JOIN_RESULT
{% if is_incremental() %}
WHERE NOT EXISTS (
    SELECT 1 
    FROM {{ this }} existing
    WHERE existing.BATCH_SOURCE_BK = JOIN_RESULT.BATCH_SOURCE_BK
    AND existing.HASH_DIFF = JOIN_RESULT.HASH_DIFF
)
{% endif %} 
{% if not is_incremental() %}
union all
    SELECT GR.VALUE as BATCH_SOURCE_BK
    , null as ORG_ID
    , null as BATCH_SOURCE_ID
    , null as BILL_CUSTOMER_RULE
    , null as COPY_INV_TIDFF_TO_CM_FLAG
    , null as GLOBAL_ATTRIBUTE5
    , null as GLOBAL_ATTRIBUTE4
    , null as GLOBAL_ATTRIBUTE7
    , null as AGREEMENT_RULE
    , null as GLOBAL_ATTRIBUTE6
    , null as GLOBAL_ATTRIBUTE1
    , null as GLOBAL_ATTRIBUTE3
    , null as GLOBAL_ATTRIBUTE2
    , null as BILL_CONTACT_RULE
    , null as GLOBAL_ATTRIBUTE9
    , null as GLOBAL_ATTRIBUTE8
    , null as BILL_ADDRESS_RULE
    , null as ATTRIBUTE3
    , null as ATTRIBUTE2
    , null as ATTRIBUTE1
    , null as ALLOW_DUPLICATE_TRX_NUM_FLAG
    , null as ATTRIBUTE9
    , null as ATTRIBUTE8
    , null as ATTRIBUTE7
    , null as ATTRIBUTE6
    , null as ATTRIBUTE5
    , null as GL_DATE_PERIOD_RULE
    , null as ATTRIBUTE4
    , null as CUST_TRX_TYPE_RULE
    , null as FOB_POINT_RULE
    , null as INVENTORY_ITEM_RULE
    , null as PAYMENT_DET_DEF_HIERARCHY
    , null as CREATE_CLEARING_FLAG
    , null as REV_ACC_ALLOCATION_RULE
    , null as ATTRIBUTE10
    , null as SALESPERSON_RULE
    , null as SALES_CREDIT_TYPE_RULE
    , null as ATTRIBUTE14
    , null as TERM_RULE
    , null as ATTRIBUTE13
    , null as ATTRIBUTE12
    , null as ATTRIBUTE11
    , null as GEN_LINE_LEVEL_BAL_FLAG
    , null as INVALID_TAX_RATE_RULE
    , null as DESCRIPTION
    , null as SHIP_CONTACT_RULE
    , null as RECEIPT_HANDLING_OPTION
    , null as GLOBAL_ATTRIBUTE20
    , null as START_DATE
    , null as GROUPING_RULE_ID
    , null as GLOBAL_ATTRIBUTE17
    , null as GLOBAL_ATTRIBUTE18
    , null as GLOBAL_ATTRIBUTE15
    , null as GLOBAL_ATTRIBUTE16
    , null as CUSTOMER_BANK_ACCOUNT_RULE
    , null as GLOBAL_ATTRIBUTE13
    , null as GLOBAL_ATTRIBUTE14
    , null as GLOBAL_ATTRIBUTE11
    , null as GLOBAL_ATTRIBUTE12
    , null as ATTRIBUTE15
    , null as GLOBAL_ATTRIBUTE19
    , null as SALES_TERRITORY_RULE
    , null as COPY_DOC_NUMBER_FLAG
    , null as BATCH_SOURCE_TYPE
    , null as END_DATE
    , null as GLOBAL_ATTRIBUTE10
    , null as LAST_BATCH_NUM
    , null as LAST_UPDATE_DATE
    , null as RELATED_DOCUMENT_RULE
    , null as AUTO_BATCH_NUMBERING_FLAG
    , null as SHIP_ADDRESS_RULE
    , null as STATUS
    , null as ALLOW_SALES_CREDIT_FLAG
    , null as INVALID_LINES_RULE
    , null as MEMO_REASON_RULE
    , null as ACCOUNTING_RULE_RULE
    , null as DERIVE_DATE_FLAG
    , null as CREATED_BY
    , null as LAST_UPDATED_BY
    , null as ACCOUNTING_FLEXFIELD_RULE
    , null as AUTO_TRX_NUMBERING_FLAG
    , null as LEGAL_ENTITY_ID
    , null as CREATION_DATE
    , null as UNIT_OF_MEASURE_RULE
    , null as NAME
    , null as DEFAULT_REFERENCE
    , null as ATTRIBUTE_CATEGORY
    , null as DEFAULT_INV_TRX_TYPE
    , null as MEMO_LINE_RULE
    , null as RECEIPT_METHOD_RULE
    , null as CREDIT_MEMO_BATCH_SOURCE_ID
    , null as SHIP_CUSTOMER_RULE
    , null as SOLD_CUSTOMER_RULE
    , null as SHIP_VIA_RULE
    , null as SALES_CREDIT_RULE
    , null as INVOICING_RULE_RULE
    , null as LAST_UPDATE_LOGIN
    , null as GLOBAL_ATTRIBUTE_CATEGORY
    , null as _FIVETRAN_DELETED
    , null as _FIVETRAN_ID
    , null as _FIVETRAN_SYNCED
    , null as PSA_LOAD_DTS
    , null as PSA_RECORD_SOURCE
    , null as PSA_DELETE_IND
, CONVERT_TIMEZONE('UTC','1900-01-01'::TIMESTAMP)::TIMESTAMP  as  LOAD_DTS
	,'USAZET.SNOWFLAKE.FBIN.DERIVED' AS REC_SRC
	,''::BINARY as HASH_DIFF
        FROM
        TABLE(strtok_split_to_table('0|-1|-2', '|')) AS GR
{% endif %}