with
cte_bkcc as (
    select * from {{ ref('ref_business_key_collision') }}
    where rec_src = 'USWIOC.ORCL.EBSPRD.MTL_PARAMETERS'
)

select
    to_varchar(organization_id) as organization_id
    , _fivetran_id
    , default_task_assign_rule_id
    , parent_child_generation_flag
    , default_carton_rule_id
    , child_lot_alpha_prefix
    , company_prefix_index
    , program_id
    , default_status_id
    , sales_account
    , wip_overpick_enabled
    , attribute3
    , attribute2
    , attribute1
    , default_crossdock_subinventory
    , attribute9
    , attribute8
    , mo_approval_timeout_action
    , attribute7
    , attribute6
    , opsm_enabled_flag
    , attribute5
    , attribute4
    , calendar_code
    , enable_costing_by_category
    , direct_shipping_allowed
    , serial_number_type
    , attribute10
    , allocate_lot_flag
    , deferred_cogs_account
    , cartonization_flag
    , create_lot_uom_conversion
    , attribute14
    , attribute13
    , negative_inv_receipt_code
    , attribute12
    , attribute11
    , org_max_volume_uom_code
    , lpn_suffix
    , interorg_payables_account
    , epc_generation_enabled_flag
    , default_putaway_task_type_id
    , primary_cost_method
    , expense_account
    , borrpay_ovh_var_account
    , max_picks_batch
    , total_lpn_length
    , avg_rates_cost_type_id
    , wsm_enabled_flag
    , trading_partner_org_flag
    , txn_approval_timeout_period
    , company_prefix
    , default_matl_ovhd_cost_id
    , process_enabled_flag
    , regeneration_interval
    , auto_lot_alpha_prefix
    , attribute15
    , stock_locator_control_code
    , lcm_enabled_flag
    , prioritize_wip_jobs
    , cartonize_sales_orders
    , global_attribute10
    , cost_group_accounting
    , cost_of_sales_account
    , default_material_cost_id
    , resource_account
    , default_moxfer_task_type_id
    , eam_enabled_flag
    , lot_number_zero_padding
    , default_wms_picking_rule_id
    , last_updated_by
    , default_locator_order_value
    , purchase_price_var_account
    , default_crossdock_criteria_id
    , default_subinv_order_value
    , default_put_away_rule_id
    , borrpay_osp_var_account
    , default_label_comp_rule_id
    , encumbrance_account
    , org_max_volume
    , wms_enabled_flag
    , interorg_receivables_account
    , lcm_var_account
    , labor_management_enabled_flag
    , crossdock_flag
    , default_cyc_count_header_id
    , pregen_putaway_tasks_flag
    , maintain_fifo_qty_stack_type
    , cost_cutoff_date
    , child_lot_zero_padding_flag
    , distributed_organization_flag
    , calendar_exception_set_id
    , global_attribute_category
    , carrier_manifesting_flag
    , auto_del_alloc_flag
    , lpn_starting_number
    , serial_number_generation
    , intransit_inv_account
    , commercial_govt_entity_number
    , borrpay_moh_var_account
    , skip_task_waiting_minutes
    , ap_accrual_account
    , start_auto_serial_number
    , mo_source_required
    , project_reference_enabled
    , lot_number_length
    , global_attribute5
    , org_max_weight
    , global_attribute4
    , global_attribute7
    , global_attribute6
    , borrpay_res_var_account
    , matl_ovhd_absorption_acct
    , global_attribute1
    , global_attribute3
    , global_attribute2
    , default_crossdock_locator_id
    , starting_revision
    , material_account
    , source_organization_id
    , global_attribute9
    , global_attribute8
    , child_lot_number_length
    , defer_logical_transactions
    , borrpay_matl_var_account
    , default_demand_class
    , cartonize_manufacturing
    , distribution_account_id
    , allocate_serial_flag
    , auto_serial_alpha_prefix
    , master_organization_id
    , copy_lot_attribute_flag
    , mo_pick_confirm_required
    , lpn_prefix
    , pm_cost_collection_enabled
    , timezone_id
    , default_cc_task_type_id
    , default_pick_task_type_id
    , matl_interorg_transfer_code
    , org_max_weight_uom_code
    , organization_code
    , wcs_enabled
    , global_attribute20
    , ovpk_transfer_orders_enabled
    , encumbrance_reversal_flag
    , global_attribute17
    , global_attribute18
    , global_attribute15
    , average_cost_var_account
    , global_attribute16
    , global_attribute13
    , global_attribute14
    , global_attribute11
    , global_attribute12
    , yard_management_enabled_flag
    , global_attribute19
    , process_orgn_code
    , invoice_price_var_account
    , outside_processing_account
    , qa_skipping_insp_flag
    , enforce_locator_alis_unq_flag
    , material_overhead_account
    , maint_organization_id
    , last_update_date
    , mat_ovhd_cost_type_id
    , default_pick_op_plan_id
    , source_subinventory
    , overhead_account
    , child_lot_validation_flag
    , default_repl_task_type_id
    , rules_override_lot_reservation
    , created_by
    , max_clusters_allowed
    , rfid_verif_pcnt_threshold
    , default_picking_rule_id
    , interorg_trnsfr_charge_percent
    , creation_date
    , project_control_level
    , program_update_date
    , consigned_flag
    , attribute_category
    , genealogy_formula_security
    , program_application_id
    , default_atp_rule_id
    , lot_number_generation
    , request_id
    , project_cost_account
    , source_type
    , interorg_price_var_account
    , default_moissue_task_type_id
    , last_update_login
    , lot_number_uniqueness
    , allow_different_status
    , ucc_128_suffix_flag
    , general_ledger_update_code
    , default_cost_group_id
    , cost_organization_id
    , interorg_transfer_cr_account
    , _fivetran_deleted
    , _fivetran_synced
    , cte_bkcc.rec_src
    , cte_bkcc.bkcc
from {{ source('bronze_ml_ebs_inv', 'mtl_parameters') }}
    inner join cte_bkcc on 1 = 1
where _fivetran_deleted = false
